### ISSUE TITLE
[Feature request]: use epic commit messages

### ISSUE THREAD

**Issue by pwespi** [ionic-team/capacitor#100]
Commit messages tend to be boring. Using some epic words would make it more attractive for people to follow the progress on a github repo.

**Comment by pwespi** [comment]
Closed in https://github.com/ionic-team/capacitor/commit/65d547c95fc47c951d38d77ea28bfc0852a1682c 
Nice job @mlynch

**Comment by mlynch** [comment]
😂 just trying to keep y’all entertained 🤙
