### ISSUE TITLE
SplashScreen was automatically hidden after default timeout.

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#1000]
```
I`export class AppComponent implements OnInit {


  constructor(
    private platform: Platform,
    private modalService: ModalService,
    private swapService: SwapService,
    private statusBarService: StatusBarService

  ) {
    this.initializeApp();
  }

  ngOnInit() {
    this.initListeners();
  }

  async initializeApp() {
    this.platform.ready().then(() => {
      this.statusBarService.setStatusBar('light');
      SplashScreen.hide();
      console.log('App is ready to go!');
    });
  }
```

Why do I still get the splash screen message, even though I have set the splashscreen hide methods when the app loads?

SplashScreen.hideSplash: SplashScreen was automatically hidden after default timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout). Read more at https://capacitor.ionicframework.com/docs/apis/splash-screen/#hiding-the-splash-screen

**Comment by jcesarmobile** [comment]
Your app it taking more than 3 seconds to launch, so the splash was hidden before you called hide. 

As the message says, increase the timeout. Or also you can disable autohide
