### ISSUE TITLE
[android] CLI sync or copy do not remove cached files

### ISSUE THREAD

**Issue by ArrowsOff** [ionic-team/capacitor#1005]
I was just experimenting with the capacitor framework when I noticed code on my device wasn't always updating when running the commands:

`npx cap sync android` and `npx cap copy android`

Strange at first since I did check if the files actually got copied, which they did. But then I noticed Android Studio created a backup of some kind in the following directory: `android\app\build\intermediates\merged_assets` which contains older code of my application. This was causing my app to not see any updates.

Honestly this might be a setting for Android Studio which I don't know about and could be disabled but I'm not sure about that. Preferably we might add a remove command to the sync and copy commands to make sure that folder is deleted. This would make sure the files would always be updated.

Some information about my system:

I'm using Android Studio 3.2.1

```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (C:\Users\me\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

```
"@capacitor/cli": "^1.0.0-beta.11",
"@capacitor/core": "^1.0.0-beta.11",
```

And I was using a OnePlus 6T on Android 9.0 aswell as a simulator on API level 26 (7.0)

**Comment by leiche123** [comment]
I run into the same problem. My current workaround is to clean the project and rebuild it which is kind of annoying.

I'm using Android Studio 3.3.2

```Ionic:
ionic (Ionic CLI)             : 4.12.0 (/home/leiche/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
Ionic Framework               : @ionic/angular 4.2.0
@angular-devkit/build-angular : 0.13.8
@angular-devkit/schematics    : 7.2.4
@angular/cli                  : 7.3.8
@ionic/angular-toolkit        : 1.4.1

System:

NodeJS : v10.15.3 (/home/leiche/.nvm/versions/node/v10.15.3/bin/node)
npm    : 6.4.1
OS     : Linux 4.15

 
"@capacitor/android": "^1.0.0-beta.19",
"@capacitor/cli": "^1.0.0-beta.19",
"@capacitor/core": "^1.0.0-beta.19",

**Comment by leiche123** [comment]
Apparently gradle was the problem in my case.. In my android platform folder the version of gradle was 4.1 when Android Studio started for the first time it suggested me to upgrade gradle to 5.1 which I did. I think this messed things up. After removing, re-adding my android platform and this time denying the upgrade to gradle 5.1 the syncing is working fine.

**Comment by jcesarmobile** [comment]
I've never hit this problem after 2 years of using capacitor and created hundreds of projects in at least 5 different computers, and based on the number of reactions on the issue, it's not very common, so I'll just close until somebody finds a way of easily reproducing it.
