### ISSUE TITLE
Cordova Plugin needs AVFoundation and Audiotoolbox in iOS

### ISSUE THREAD

**Issue by orlyapps** [ionic-team/capacitor#1008]
Hello everyone,

im using 'phonegap-plugin-barcodescanner' but i cannot compile the project.

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AVCaptureDeviceInput", referenced from:`

I can fix this by linking the iOS Frameworks AVFoundation and Audiotoolbox in the "CapacitorCordova" Target.

But on every npx cap sync this settings getting dropped. Is this an issues or im doing something wrong?

Thanks

**Comment by jcesarmobile** [comment]
Just released phonegap-plugin-barcodescanner 8.0.1 that works fine with Capacitor
