### ISSUE TITLE
Some questions regarding capacitor electron

### ISSUE THREAD

**Issue by aammfe** [ionic-team/capacitor#1018]
Hello!!

1 - can we use like live reload or HMR with capacitor electron (for both main and renderer thread)…?
or is there any way we can do it.

2- capacitor electron official support for typescript for main thread.

3- how can we share code bw both projects.(electron , ionic)

4- how we can use electron features like [ipcRenderer](https://electronjs.org/docs/api/ipc-renderer) in ionic project ?

**Comment by jcesarmobile** [comment]
Sorry, issues should be used for reporting issues, not for asking questions.

You can ask questions on the forum https://forum.getcapacitor.com/
Or on slack https://getcapacitor.herokuapp.com/
