### ISSUE TITLE
Unable to simultaneously satisfy constraints

### ISSUE THREAD

**Issue by pixelbucket-dev** [ionic-team/capacitor#1035]
I get the error in the title in XCode when I focus a `contenteditable` element and the keyboard appears.

Tha full error:

>Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x1c02837a0 _UIButtonBarStackView:0x101e16a20.width <= 178   (active)>",
    "<NSLayoutConstraint:0x1c028ebf0 _UIUCBKBSelectionBackground:0x101e3fa30.width >= 34   (active)>",
    "<NSLayoutConstraint:0x1c028ea60 H:|-(0)-[_UIUCBKBSelectionBackground:0x101e3fa30]   (active, names: '|':_UIButtonBarButton:0x101e3c760 )>",
    "<NSLayoutConstraint:0x1c028eb00 _UIUCBKBSelectionBackground:0x101e3fa30.trailing == _UIButtonBarButton:0x101e3c760.trailing   (active)>",
    "<NSLayoutConstraint:0x1c028f3c0 _UIUCBKBSelectionBackground:0x101e3c450.width >= 34   (active)>",
    "<NSLayoutConstraint:0x1c028f230 H:|-(0)-[_UIUCBKBSelectionBackground:0x101e3c450]   (active, names: '|':_UIButtonBarButton:0x101e3c200 )>",
    "<NSLayoutConstraint:0x1c028f2d0 _UIUCBKBSelectionBackground:0x101e3c450.trailing == _UIButtonBarButton:0x101e3c200.trailing   (active)>",
    "<NSLayoutConstraint:0x1c42935b0 _UIUCBKBSelectionBackground:0x101d7e270.width >= 34   (active)>",
    "<NSLayoutConstraint:0x1c4293380 H:|-(0)-[_UIUCBKBSelectionBackground:0x101d7e270]   (active, names: '|':_UIButtonBarButton:0x101d56ae0 )>",
    "<NSLayoutConstraint:0x1c42932e0 _UIUCBKBSelectionBackground:0x101d7e270.trailing == _UIButtonBarButton:0x101d56ae0.trailing   (active)>",
    "<NSLayoutConstraint:0x1c429d650 _UIUCBKBSelectionBackground:0x101d41560.width >= 34   (active)>",
    "<NSLayoutConstraint:0x1c4298100 H:|-(0)-[_UIUCBKBSelectionBackground:0x101d41560]   (active, names: '|':_UIButtonBarButton:0x101d824a0 )>",
    "<NSLayoutConstraint:0x1c4288a20 _UIUCBKBSelectionBackground:0x101d41560.trailing == _UIButtonBarButton:0x101d824a0.trailing   (active)>",
    "<NSLayoutConstraint:0x1c42979d0 _UIUCBKBSelectionBackground:0x101d67490.width >= 34   (active)>",
    "<NSLayoutConstraint:0x1c428a690 H:|-(0)-[_UIUCBKBSelectionBackground:0x101d67490]   (active, names: '|':_UIButtonBarButton:0x101d685d0 )>",
    "<NSLayoutConstraint:0x1c4293740 _UIUCBKBSelectionBackground:0x101d67490.trailing == _UIButtonBarButton:0x101d685d0.trailing   (active)>",
    "<NSLayoutConstraint:0x1c028c1c0 'UISV-canvas-connection' UILayoutGuide:0x1c01a6ac0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x101e3c200.trailing   (active)>",
    "<NSLayoutConstraint:0x1c0296c60 'UISV-canvas-connection' UILayoutGuide:0x1c01a6ac0'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x101d56ae0.leading   (active)>",
    "<NSLayoutConstraint:0x1c028c260 'UISV-spacing' H:[_UIButtonBarButton:0x101e3c760]-(0)-[UIView:0x101e2b920]   (active)>",
    "<NSLayoutConstraint:0x1c028c8f0 'UISV-spacing' H:[_UIButtonBarButton:0x101d56ae0]-(0)-[UIView:0x101d57e90]   (active)>",
    "<NSLayoutConstraint:0x1c0296f30 'UISV-spacing' H:[UIView:0x101d57e90]-(0)-[_UIButtonBarButton:0x101d824a0]   (active)>",
    "<NSLayoutConstraint:0x1c0294050 'UISV-spacing' H:[_UIButtonBarButton:0x101d824a0]-(0)-[UIView:0x101d56f50]   (active)>",
    "<NSLayoutConstraint:0x1c028a9b0 'UISV-spacing' H:[UIView:0x101d56f50]-(0)-[_UIButtonBarButton:0x101d685d0]   (active)>",
    "<NSLayoutConstraint:0x1c028b680 'UISV-spacing' H:[_UIButtonBarButton:0x101d685d0]-(0)-[UIView:0x101e62b10]   (active)>",
    "<NSLayoutConstraint:0x1c02973e0 'UISV-spacing' H:[UIView:0x101e62b10]-(0)-[_UIButtonBarButton:0x101e3c760]   (active)>",
    "<NSLayoutConstraint:0x1c02856e0 'UISV-spacing' H:[UIView:0x101e2b920]-(0)-[_UIButtonBarButton:0x101e3c200]   (active)>",
    "<NSLayoutConstraint:0x1c02830c0 'UIView-leftMargin-guide-constraint' H:|-(15)-[UILayoutGuide:0x1c01a6ac0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x101e16a20 )>",
    "<NSLayoutConstraint:0x1c0283160 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x1c01a6ac0'UIViewLayoutMarginsGuide']-(15)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x101e16a20 )>"
)

> Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1c42979d0 _UIUCBKBSelectionBackground:0x101d67490.width >= 34   (active)>

> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

I have the feeling that causes the UI to be slow, i.e. the keyboard takes some milliseconds to appear and the element is not in focus straight away.

[Edit]

Clarification: The component containing the `contenteditable` is a Stencil component.

**Comment by Nudelsieb** [comment]
Thanks.

**Comment by jfbloom22** [comment]
Did you happen to open a webkit bug for this?  I am running into a similar issue.  The view scrolls correctly for all my form inputs, except for email.  On email, I get this error and the view does not scroll.  

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

```
2023-06-27 17:39:51.971158-0400 App[99406:2278115] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003679e50 'accessoryView.bottom' _UIRemoteKeyboardPlaceholderView:0x15b583000.bottom == _UIKBCompatInputView:0x15b514d10.top   (active)>",
    "<NSLayoutConstraint:0x600003679d60 'assistantHeight' SystemInputAssistantView.height == 45   (active, names: SystemInputAssistantView:0x13b6517c0 )>",
    "<NSLayoutConstraint:0x600003650410 'assistantView.bottom' SystemInputAssistantView.bottom == _UIKBCompatInputView:0x15b514d10.top   (active, names: SystemInputAssistantView:0x13b6517c0 )>",
    "<NSLayoutConstraint:0x6000036500f0 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x15b583000]-(0)-[SystemInputAssistantView]   (active, names: SystemInputAssistantView:0x13b6517c0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000036500f0 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x15b583000]-(0)-[SystemInputAssistantView]   (active, names: SystemInputAssistantView:0x13b6517c0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
⚡️  TO JS {"keyboardHeight":335}
⚡️  TO JS {"keyboardHeight":380}
```
