### ISSUE TITLE
iOS app bundle size

### ISSUE THREAD

**Issue by diachedelic** [ionic-team/capacitor#1036]
It seems that a [stock installation](https://capacitor.ionicframework.com/docs/getting-started/#optional-starting-a-fresh-project) of Capacitor generates `.ipa` (iOS) bundles of *~122MB*, whereas the equivalent `.apk` (Android) bundles are *~3MB*.  

I am interested in why there is such a huge discrepency, as it greatly impacts deployment time (especially here in Australia, where it can take up to 15 minutes to upload even a small `.ipa` to the Apple Store).

**Comment by mlynch** [comment]
It's not as simple as measuring the .ipa file you have generated doing a local release build. Capacitor uses Swift, which results in larger bundles at build time. However, Apple does a ton of optimization in the store to cut down on the actual final install size. There's not a 1-1 map

**Comment by diachedelic** [comment]
@jcesarmobile @mlynch I am 

1. Archive the app in Xcode
2. Distribute App
3. iOS App Store
4. Export (sign and export without uploading)
5. Accept all default options (however, unchecking bitcode and unchecking app symbols reduces size to *~85MB*)
6. Check the size of the exported `.ipa` file.

I can confirm that producing an Ad Hoc build produces a `.ipa` file of *3.1MB*.  Also, from App Store Connect (go Activity -> All Builds -> Build #) it appears the resulting "Compressed file size" is only a few MB.

I appreciate this is absolutely not Capacitor's responsibility, thanks for the explanation.

**Comment by jcesarmobile** [comment]
Ah, yeah, tried like that and got a 121MB .ipa too.

I don't know the internals of Xcode and why there is such a big difference between the App Store .ipa and the development/ad-hoc ipa. But knowing last ones are small, and the final .ipa used on the store is small too, I'm happy enough.

**Comment by HarelM** [comment]
Is it possible that this was now addressed in version 4 of capacitor?
I see a dramatic change in the ipa file size from 130 Mb to around 20.
If so, thanks!!
i.e. for anyone reading this in the future make sure to update to version 4 of capacitor or later.
