### ISSUE TITLE
Electron does not work anymore

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/capacitor#1037]
When running
```
npm run electron:start
```
got the following errors:
  - No @ionic/core ToastController detected, please make sure ....
  - Get file:///runtime.js net::ERR_FILE_NOT_FOUND
  - Get file:///polyfill.js net::ERR_FILE_NOT_FOUND
  - Get file:///styles.js net::ERR_FILE_NOT_FOUND
  - Get file:///vendor.js net::ERR_FILE_NOT_FOUND
  - Get file:///main.js net::ERR_FILE_NOT_FOUND

**Comment by schwamic** [comment]
I get the same error.

angular: 7.1.2
capacitor: 1.0.0-beta.11
ionic/angular": 4.0.0-beta.15-0
ionic-native: 5.0.0-beta.22

**Comment by jepiqueau** [comment]
Solve in Capacitor 1.0.0-beta.13

**Comment by jepiqueau** [comment]
It is working fine, for a capacitor ionic-angular application if in the index.html you change  ```   <base href="/" /> ``` by ```   <base href="./" /> ``` . in a capacitor ionic-vue project you must add a vue.config.js file in the project folder which contains ```
module.exports = {
  baseUrl: "./"
};```. I didn't test an app with tabs so try

**Comment by ta3ban** [comment]
I have the same problem and still wasn't able to figure a way to run electron (capacitor ionic 4 vue project net::ERR_FILE_NOT_FOUND
)
 I Added vue.config.js  module.exports = {publicPath: './',}
 and added <base href="./" /> in index.html  when running yarn run electron:start the application Never progress beyond that 
yarn run v1.15.2
warning ../../../../../../package.json: No license field
$ electron ./

**Comment by hellokvn** [comment]
That issue is back.
