### ISSUE TITLE
On updating to beta.11 from beta.8 getting error on sync

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#1039]
On doing **npx cap sync**. What am I missing? It was working good with beta.8

<img width="1161" alt="screenshot 2018-12-07 at 10 45 59 pm" src="https://user-images.githubusercontent.com/8480351/49662543-217f3280-fa72-11e8-8b0c-04bfc184fd55.png">

```
✖ Updating iOS native dependencies: 
✖ update ios: 
[error] Error running update: Analyzing dependencies
Fetching podspec for `Capacitor` from `../../node_modules/@capacitor/ios`
Fetching podspec for `CapacitorCordova` from `../../node_modules/@capacitor/ios`
Fetching podspec for `CordovaPlugins` from `../capacitor-cordova-ios-plugins`
[!] CocoaPods could not find compatible versions for pod "Capacitor":
  In Podfile:
    Capacitor (from `../../node_modules/@capacitor/ios`)

Specs satisfying the `Capacitor (from `../../node_modules/@capacitor/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by stripathix** [comment]
Hi @jcesarmobile , could you please help with this.

**Comment by jcesarmobile** [comment]
Latest beta dropped support for iOS 10, so you have to change the project deployment target to iOS 11. It was mentioned on the release notes as breaking change.

**Comment by stripathix** [comment]
Thanks that fixed that bug. Now getting this:

<img width="1082" alt="screenshot 2018-12-07 at 11 14 09 pm" src="https://user-images.githubusercontent.com/8480351/49663840-e4b53a80-fa75-11e8-8255-26c963a0f660.png">

**Comment by jcesarmobile** [comment]
Did you run `npx cap update ios` again? 
The GCDWebServer is gone on latest beta too, so those files are gone, but shouldn't complain about it.
Also try to do a Product -> Clean build folder in Xcode so it cleans old files that might be still there.

Also try closing Xcode and running `npx cap update ios` again with Xcode closed and then do `npx cap open ios`. Xcode 10 is having some weird caching issues.

**Comment by stripathix** [comment]
Restarting xCode fixed my issue. Thanks @jcesarmobile .
