### ISSUE TITLE
Avoid modifying cordova.js if we can help it

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#104]
See note on #102 
https://github.com/ionic-team/capacitor/pull/102#pullrequestreview-93334503

**Comment by jcesarmobile** [comment]
For Capacitor plugins we also use `window.androidBridge` for Android and `window.webkit.messageHandlers.bridge` for iOS. 
see native-bridge.js (https://github.com/ionic-team/capacitor/blob/master/core/native-bridge.js#L22-L40)

So if we do it, we should do it for both.

**Comment by mlynch** [comment]
Yea, that's what I mean. I wonder if we can somehow export the same thing so we just call one `window` object on both iOS and Android, for Capacitor and Cordova
