### ISSUE TITLE
Capacitor is loading app at capacitor://app instead localhost

### ISSUE THREAD

**Issue by rabs19912** [ionic-team/capacitor#1041]
Hi, im running a ionic app with capacitor in and iphone 7 plus, 
im using xcode and everything is ok
when i run the app, with the phone connected, everything works, but the app start running in
"capactitor://app" instead localhost
i have configure a port in capactir.config.json, and was working until today,
after, when i run the aplicatin, the xcode console said 'loading at localhost:MICONFIGUREPORT'
and worked perfectly
now, is running at 'capactor://app' although is working right
i have problems with the CORS
even i allow the origin "capacitor://app" in my serve but stiil having thie cors origin problem
im using ionic 4 and
"@capacitor/android": "^1.0.0-beta.11",
    "@capacitor/cli": "^1.0.0-beta.8",
    "@capacitor/core": "^1.0.0-beta.8",
    "@capacitor/ios": "^1.0.0-beta.8",

**Comment by rabs19912** [comment]
@jcesarmobile it would be a veeery big sample app
but there is the error in console
Origin capacitor://app is not allowed by Access-Control-Allow-Origin.
Failed to load resource: Origin capacitor://app is not allowed by Access-Control-Allow-Origin.
2
and how is this working without a webserver? as locals files?
thanks for answer!

**Comment by jcesarmobile** [comment]
Ok, sorry, you probably didn't properly set CORS on the server, it works fine on my tests.

**Comment by rabs19912** [comment]
how should i configure the server for this case? 
should I set Access-Control-Allow-Origin: *
or Access-Control-Allow-Origin: capacitor://app
?
