### ISSUE TITLE
iOS 12 with iPhone landscape when keyboard opens then input box goes out of view area.

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#1045]
On clicking on any input field on the iPhone landscape page shift is wrong. input field goes out of view and even on some screens keyboard is hidden behind a keyboard.
See in attached screenshot how when I tap on a input field then that input field goes out of view area. I have also attached a video screencast.

<img width="512" alt="49791214-f9cfe900-fd55-11e8-9134-9f890e4b3fb8" src="https://user-images.githubusercontent.com/8480351/49806349-8772ff00-fd7d-11e8-9296-ac1fe077ed2f.png">

https://youtu.be/kveJ663r-oA

I am using Ionic 4 + Vue + Capacitor.

```
"@capacitor/android": "1.0.0-beta.11",
		"@capacitor/cli": "1.0.0-beta.11",
		"@capacitor/core": "1.0.0-beta.11",
		"@capacitor/ios": "1.0.0-beta.11",
"@ionic/core": "4.0.0-beta.17",
		"@ionic/vue": "0.0.1",
```

```
<div class="ion-page">
  <ion-header>
    <ion-toolbar color="dark">
      <ion-buttons slot="start">
        <menu-button></menu-button>
      </ion-buttons>
      <ion-title>
        Developer
      </ion-title>
    </ion-toolbar>
  </ion-header>
  <ion-content class="hasfooter">
    <ion-list>
      <ion-item>
        <ion-label position="stacked">Service Host</ion-label>
        <ion-input :value="serviceHost" @ionInput="serviceHost = $event.target.value" placeholder="Enter Service Host"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="stacked">Test1</ion-label>
        <ion-input :value="serviceHost" @ionInput="serviceHost = $event.target.value" placeholder="Enter Service Host"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="stacked">Test2</ion-label>
        <ion-input :value="serviceHost" @ionInput="serviceHost = $event.target.value" placeholder="Enter Service Host"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="stacked">test3</ion-label>
        <ion-input :value="serviceHost" @ionInput="serviceHost = $event.target.value" placeholder="Enter Service Host"></ion-input>
      </ion-item>
    
    </ion-list>
  </ion-content>
  <ion-footer>
    <ion-toolbar color="dark">
    </ion-toolbar>
  </ion-footer>
</div>
```

Initially, I reported it to ionic but they pointed this as an issue related to keyboard (Capacitor or Cordova).

**Comment by stripathix** [comment]
Any update on this.

**Comment by boozedog** [comment]
I'm also interested in a solution for this please!!

**Comment by moberwasserlechner** [comment]
Have you tried the solution presented in the following comment? 

https://github.com/ionic-team/capacitor/issues/814#issuecomment-441607213

If not plz do so.

**Comment by sneko** [comment]
https://github.com/ionic-team/capacitor/pull/1119 maybe it can help you. Note this PR is not released for now ---> modify the file directly to try it.

**Comment by jcesarmobile** [comment]
https://github.com/ionic-team/capacitor/pull/1119 is merged.
It fixes the problem for me using `ionic` and `body` resize options:
```
"plugins": {
      "Keyboard": {
          "resize": "ionic"
      }
  }
```
@stripathix can you verify and close if it fixes the problem?

**Comment by stripathix** [comment]
@jcesarmobile where to add below config?

```
"plugins": {
      "Keyboard": {
          "resize": "ionic"
      }
  }
```

I have updated node_modules below file with latest code from: https://github.com/ionic-team/capacitor/pull/1119/files

@capacitor/ios/ios/Capacitor/Capacitor/Plugins/Keyboard.m

**Comment by sneko** [comment]
@stripathix in your `capacitor.config.json` file. You should have something default like:

```
  "plugins": {
    "SplashScreen": {
      "launchAutoHide": false
    }
  }
```

**Comment by stripathix** [comment]
Thanks, @sneko. Like this?

```
{
  "appId": "net.***.****",
  "appName": "****",
  "bundledWebRuntime": false,
  "webDir": "dist",
  "ios": {
    "minVersion": "11"
  },
  "plugins": {
    "SplashScreen": {
      "launchAutoHide": false
    },
    "Keyboard": {
          "resize": "ionic"
    }
  }
}

```

**Comment by sneko** [comment]
Yes :)

On Jan 24, 2019, at 10:09, Shashwat Tripathi <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, @sneko<https://github.com/sneko>. Like this?

{
  "appId": "net.***.****",
  "appName": "****",
  "bundledWebRuntime": false,
  "webDir": "dist",
  "ios": {
    "minVersion": "11"
  },
  "plugins": {
    "SplashScreen": {
      "launchAutoHide": false
    },
    "Keyboard": {
          "resize": "ionic"
    }
  }
}

**Comment by stripathix** [comment]
@jcesarmobile I am still getting same issue. On focusing a input field input field does get shifted and is hidden behind header.

In below screenshot see cursor next to Preferences header title. Input field shifts behind the header.

Note: It is in iPhone 8 Landscape mode.

<img width="519" alt="screenshot 2019-01-24 at 5 30 59 pm" src="https://user-images.githubusercontent.com/8480351/51676884-f8a10580-1ffd-11e9-946e-070ed49a4e7a.png">

Steps I did
1) In Capacitor.config.json I have following
```
{
  "appId": "net.******.******",
  "appName": "*******",
  "bundledWebRuntime": false,
  "webDir": "dist",
  "ios": {
    "minVersion": "11"
  },
  "plugins": {
    "SplashScreen": {
      "launchAutoHide": false
    },
    "Keyboard": {
      "resize": "ionic",
      "style": "dark"
    }
  }
}
```

2) Replaced code of below file by latest code from Github master branch
```
/node_modules/@capacitor/ios/ios/Capacitor/Capacitor/Plugins/Keyboard.m
```
Used this file: https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/Plugins/Keyboard.m

3) Then executed below commands
```
npx cap sync
npx cap copy
```

**Comment by jcesarmobile** [comment]
I don't think it's the "same" issue now as it no longer is behind the keyboard, but behind the header, and only sometimes. I get the same behaviour on Cordova, so not entirely sure if now it's a Capacitor/Cordova Keyboard plugin bug or an Ionic bug

**Comment by stripathix** [comment]
Any update on this?

**Comment by jcesarmobile** [comment]
This is an Ionic bug since it also happens in Cordova apps
