### ISSUE TITLE
Android Documentation: Incorrect links in further reading

### ISSUE THREAD

**Issue by darthdie** [ionic-team/capacitor#106]
The Further Reading Section of the Android documentation specifies the html extension, i.e.
https://capacitor.ionicframework.com/docs/android/configuration.html
instead of
https://capacitor.ionicframework.com/docs/android/configuration

Which is incorrect and clicking the links causes the site to freak out (technical term).

**Comment by mlynch** [comment]
Fixed in 7b9cc48b5c53eafad168ac02a9bf91b4e6c565da
