### ISSUE TITLE
cordova-plugin-websocket-server doesn't work with capacitor

### ISSUE THREAD

**Issue by nkprince007** [ionic-team/capacitor#1065]
Info:
Repo: https://github.com/becvert/cordova-plugin-websocket-server
Plugin Version: 1.4.11
Capacitor version: 1.0.0-beta.11

Usage:

```javascript
  var wsserver = cordova.plugins.wsserver;
  wsserver.start(0, {
    // WebSocket Server handlers
    'onFailure': function (addr, port, reason) {
      console.log('Stopped listening on %s:%d. Reason: %s', addr, port, reason);
    },
    // WebSocket Connection handlers
    'onOpen': function (conn) {
      /* conn: {
       'uuid' : '8e176b14-a1af-70a7-3e3d-8b341977a16e',
       'remoteAddr' : '192.168.1.10',
       'httpFields' : {...},
       'resource' : '/?param1=value1&param2=value2'
       } */
      console.log('A user connected from %s', conn.remoteAddr);
    },
    'onMessage': function (conn, msg) {
      console.log(conn, msg);
    },
    'onClose': function (conn, code, reason, wasClean) {
      console.log('A user disconnected from %s', conn.remoteAddr);
    },
    // Other options
    'tcpNoDelay': true // disables Nagle's algorithm.
  }, function onStart(addr, port) {
    console.log('Listening on %s:%d', addr, port);
  }, function onDidNotStart(reason) {
    console.log('Did not start. Reason: %s', reason);
  });
```

Here's the error log:

```
WebSocketServer start WebSocketServer1499161060 ["options": [0, <null>, <null>, 1]]
Error: Plugin Optional("WebSocketServer") does not respond to method call start:.
Ensure plugin method exists and uses @objc in its declaration
```

**Comment by nkprince007** [comment]
On further research by using Safari Web Inspector, I found that, `cordova.plugins.wsserver` indeed has these methods attached. But calling them throws the error shown below.

```
To Native Cordova ->  WebSocketServer start WebSocketServer1431458101 ["options": [0, <null>, <null>, 1]]
Error: Plugin Optional("WebSocketServer") does not respond to method call start:.
Ensure plugin method exists and uses @objc in its declaration
To Native Cordova ->  WebSocketServer getInterfaces INVALID ["options": []]
Error: Plugin Optional("WebSocketServer") does not respond to method call getInterfaces:.
Ensure plugin method exists and uses @objc in its declaration
```

**Comment by jcesarmobile** [comment]
That's because the plugin is not updated to use Swift 4 and it's methods don't use `@objc`, so they can't be called from Swift 4 (that's what Capacitor use).

You can configure Cordova plugins to use Swift 3 instead of Swift 4 by adding this to your `capacitor.config.json` and run `npx cap update ios` again

```
"ios": {
    "cordovaSwiftVersion": "3.0"
  }
```

Doing that the plugin works

**Comment by nkprince007** [comment]
I still receive the same error.

**Comment by nkprince007** [comment]
Please don't close issues abruptly. That's rude.

**Comment by jcesarmobile** [comment]
Add that, then do `npx cap update ios` (preferably with Xcode closed), open Xcode with `npx cap open`, Do a Product -> Clean build folder. And finally run again.

I did all those steps times and it worked, that's why I closed "abruptly"

**Comment by nkprince007** [comment]
Yes, I did the same.

I had to manually change the compiler version in Xcode and it works now.

**Comment by nkprince007** [comment]
Thanks for the help @jcesarmobile :)

**Comment by jcesarmobile** [comment]
Did you do it with Xcode closed?
Looks like Xcode 10.x caches the CocoaPods and if you run `npx cap update ios` with Xcode open, sometimes it doesn't pick changes.

I tried with Xcode closed and worked 5 of 5 times I tried, but with Xcode open it didn't change the version some of the times I tried.

**Comment by nkprince007** [comment]
Yeah, I did close Xcode but my stupid code editor was undoing the file changes, I noticed it now. 
😅 Sorry about it.
