### ISSUE TITLE
Make Android Studio optional

### ISSUE THREAD

**Issue by pickfire** [ionic-team/capacitor#1067]
I believe making Android Studio optional would be nice for developers without Android Studio. All the way from using Cordova, starting up `emulator` instead would be simpler and faster than Android Studio.

**Comment by jcesarmobile** [comment]
Biggest pain point of Cordova users is configuring Android SDK, java JDK, etc. Android Studio. Gives it all of that out of the box.
It will be required to have it installed, but might not require to use it to run the apps in the future, we have another issue for tracking running from the CLI 
https://github.com/ionic-team/capacitor/issues/324 
I recommend follow the progress there and also read the commend as in the comments there are a few commands you can use for installing/running the app from terminal
