### ISSUE TITLE
App does not have web implementation

### ISSUE THREAD

**Issue by t0msk** [ionic-team/capacitor#1068]
Hello,

I'm building PWA and I need to access the `App` functionality, so I test it with this chunk of code:

```
      await App.canOpenUrl({ url: 'com.getcapacitor.myapp' }).then((r) => {
          console.log("Success: " + r);
      }).catch((e) => {
          console.log("Error: " + e);
      });
```

And if I get error message like: `App does not have web implementation.`

Is there any way to access `App` inside PWA?

**Comment by mlynch** [comment]
Added a basic `App` plugin in `ea7e1f74f4dd89a68523a8ddcd8a3b9223d0ec7e`.

However, `canOpenUrl` will always return true because that feature isn't supported in the web.
