### ISSUE TITLE
ZoneAwarePromise instead of string from Capacitor Storage.get

### ISSUE THREAD

**Issue by maedewiza** [ionic-team/capacitor#1078]
I've tried many times with many ways, but I still can't correctly get token from Capacitor Storage, to send this into request's Authorization header. Can you help me?

This code returns instead of a string with token, an [object Promise]:

```
import { Injectable } from '@angular/core';
import { HttpRequest, HttpHandler, HttpEvent, HttpInterceptor } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
    Storage
} from '@capacitor/core';

@Injectable()
export class JwtInterceptor implements HttpInterceptor {
    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

        request = request.clone({
                setHeaders: {
                    Authorization: `Bearer ${Storage.get({ key: 'token' }).then(token => { return token;
                    })}`
                }});

        return next.handle(request);
    }
}
```

On a simpler example:
```
    async getToken() {
        return await Storage.get({ key: 'token' });
      }

    test() {
        console.log(this.getToken());
    }
```
console.log will return ZoneAwarePromise instead of string

**Comment by maedewiza** [comment]
Nevermind, I found a solution.

**Comment by jcesarmobile** [comment]
All Capacitor plugins return promises.

The problem here is in your code, in your simplified example, despite you have the await, as the getToken function is async, it wraps whatever you return into a new promise, so you should await again in test function.
Also, the get promise will provide an object, not the actual token you should do something like this to get the token value:

```
let token = await Storage.get({ key: 'token' });
console.log(token.value);
```

**Comment by DiogoBatista** [comment]
@maedewiza could you share the solution you found? I'm having the same problem.

**Comment by jcesarmobile** [comment]
The solution is to use await as explained on the docs, or handle the promise. The plugin returns a promise, not a string.
In the OP's case, despite they were using await, the function where it was used had `async` on it, that makes the function to return a promise with the result, so when using `getToken` they have to await for it too.
