### ISSUE TITLE
callback from broadcast reciever not being called

### ISSUE THREAD

**Issue by sirpy** [ionic-team/capacitor#1080]
I've tried two sms plugins
https://github.com/andreszs/cordova-plugin-sms-receive
https://github.com/sandeepdillerao/cordova-plugin-otp-auto-verification

non of them send the SMS back. They both reach the point where they call callbackcontext when an sms arrives but nothing happens.
I've tried to debug a little and calling callbackcontext outside the sms event and it works.
I've also tried calling the callback when doing cordova.getActivity.execute(new Runnable(){.... callbackcontext}) and also nothing happens.

I haven't tested with cordova.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
