### ISSUE TITLE
domexception error when trying to access the camera

### ISSUE THREAD

**Issue by jgw96** [ionic-team/capacitor#1081]
Hey!

Its awesome to see the progress on Capacitor, it has come such a long way! 

On to the issue, I have an app (Stencil + Ionic 4) which uses the `getUserMedia` api to access the camera stream. It then plays this stream in a video element. The code that handles that is here https://github.com/jgw96/IdentiDog/blob/master/src/components/app-home/app-home.tsx#L36. 

On Android using Capacitor, this code fails with a `domexception` error (that is literally the error, no other context or anything) when it tries to play the video https://github.com/jgw96/IdentiDog/blob/master/src/components/app-home/app-home.tsx#L48.

 If i then open up chrome dev tools and then run the `play()` method on the video element manually, it starts rendering the video stream and everything works fine.

Env info:

```
    "@capacitor/android": "^1.0.0-beta.13",
    "@capacitor/cli": "^1.0.0-beta.13",
    "@capacitor/core": "^1.0.0-beta.13",
```

Repro steps:
- clone the app: https://github.com/jgw96/IdentiDog.git
- `npm install && npm start`
- Run it on your android device
- hit the get started button
- Accept the camera permission
- Notice the error in devtools (using Chrome://inspect)

Let me know if you need any more info (:

**Comment by jgw96** [comment]
Also, i should add that im getting this error on a Pixel 3 XL running the latest Android update (9.0)

**Comment by jgw96** [comment]
Alright, so fixed the issue with this little bit of native code. You can replace your MainActivity with this if you run into the issue (warning, this might not be great Java, its been a long time since i did anything with Java so I just dont know):

```
package com.identidog.app;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Bridge;
import com.getcapacitor.Plugin;

import android.webkit.WebSettings;
import android.webkit.WebView;

import java.util.ArrayList;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
    }});

    Bridge goodBridge = this.getBridge();

    WebView wv = goodBridge.getWebView();
    WebSettings ws = wv.getSettings();
    ws.setMediaPlaybackRequiresUserGesture(false);

  }
}
```

**Comment by jgw96** [comment]
@jcesarmobile Im gonna leave this open for now even though i figured out how to fix it as i don't know if this is something you all want to handle internally. Feel free to close if that makes more sense to you (:

**Comment by jcesarmobile** [comment]
Yeah, we should handle it and make this preference configurable being false the default. TBH, I only tested that I was getting the stream object when I tried getUserMedia, so as I didn’t play it in a video I didn’t notice.
Good catch and thanks for doing the investigation!

**Comment by jgw96** [comment]
No problem at all, thanks!
