### ISSUE TITLE
Ability to attach / debug via VSCode to application running on emulator

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/capacitor#1082]
I have a test Ionic4/Angular/Capacitor test project. When I run it in the Android emulator (via Android studio), I would like to use VSCode to debug it.

Using the following debugger configuration....

```
{
      "name": "Attach to running android on emulator",
      "type": "cordova",
      "request": "attach",
      "platform": "android",
      "target": "emulator",
      "port": 8199,
      "sourceMaps": true,
      "cwd": "${workspaceFolder}"
    },
```

I get the following error...

![image](https://user-images.githubusercontent.com/10663978/50531379-9f030380-0b43-11e9-8ad5-b6d3a2a8b43f.png)

**Comment by Sampath-Lokuge** [comment]
I think you need to log this issue here: https://github.com/Microsoft/vscode-cordova/issues

**Comment by pjc2007** [comment]
I an see the problem here is that Capacitor does not have `platform` in the path to the android project, so the debugger is looking in the wrong place (for the Capacitor project)
