### ISSUE TITLE
Duplicate PushNotifications ('registration') event

### ISSUE THREAD

**Issue by ghq2340** [ionic-team/capacitor#1088]
PushNotification **"Registration"** event is triggered twice during PN registration, tasks that depend on this event will be executed twice:

PushNotifications.addListener('registration',  (token: PushNotificationToken) => {
      console.log('token ' + token.value);
    });

How to duplicate this problem:

1. Create a new ionic 4 app (angular type)
2. Install capacitor 
3. Add PN listeners to app.component.ts
    PushNotifications.register();
    PushNotifications.addListener('registrationError', (error: any) => {
      console.log('error on register ' + JSON.stringify(error));
    });
    PushNotifications.addListener('pushNotificationReceived', (notification: PushNotification) => {
      console.log('notification ' + JSON.stringify(notification));
    });
    PushNotifications.addListener('registration', (token: PushNotificationToken) => {
      console.log('token: ' + token.value);
    });

4.  Console logs show 2 events (check timestamp)
01-01 19:26:43.794 20498-20596/xxxxx I/Capacitor/Plugin/Console: token: XXXXXXX
01-01 19:26:43.829 20498-20596/xxxxx I/Capacitor/Plugin/Console: token: XXXXXXX

**Comment by jcesarmobile** [comment]
register makes the registration event to fire, but only once.
The thing is `onNewToken` can also fire registration event at any moment, when the token changes. We can't control that.
So looks like in your case the token changed and you got both the register and the `onNewToken` events.
If you want to avoid it, don't call register every time your app launches, once you got the first register you can skip the next one, and you'll still get a new token if it changes in the future.

**Comment by davidgv88** [comment]
@ghq2340 how did you fix this? I have the same problem

**Comment by BrojJedan** [comment]
I have the same problem, except the token is exactly the same in both cases.. so it cannot be because of token change.

**Comment by Danbardo** [comment]
I have the same issue, my work around was to store the token in localStorage then check it against the token passed to the register event handler. If the stored token equals to the passed token, it will return and stop the function, otherwise, it will store the passed token into localStorage.

This means the registration event handle will immediately stop, unless a new token has been issued.

I found the registration event was triggered twice within 2 ms which was so fast it confused my database resulting in duplicate rows.

Only seems to effect Android.

**Comment by joaolisboa** [comment]
Have the same issue the first time the registration token is generated. Event was fired immediately after the first, both with the same token. I've managed a workaround but It'd be great if this wasn't a concern.
