### ISSUE TITLE
Xcode error - class 'CAPKeyboard' does not conform to protocol 'CAPBridgedPlugin'

### ISSUE THREAD

**Issue by scriptPilot** [ionic-team/capacitor#1092]
Xcode shows error:
`class 'CAPKeyboard' does not conform to protocol 'CAPBridgedPlugin'`

Latest Capacitor / Xcode / macOS version used.

![bildschirmfoto 2019-01-02 um 21 05 22](https://user-images.githubusercontent.com/19615586/50610188-54321480-0ed2-11e9-86d4-081450bba7a4.png)

**Comment by jcesarmobile** [comment]
that's a warning, not an error, the error should be at the end

**Comment by scriptPilot** [comment]
You are right. In addition I re-installed now everything and the error was not reproduced. Sorry for making noise.

**Comment by alaswer** [comment]
> You are right. In addition I re-installed now everything and the error was not reproduced. Sorry for making noise.

Hi.. sorry, I'm new to the whole capacitor framework, could you please tell me how you fixed it? you re-installed what exactly?

**Comment by CVHvisuals** [comment]
Same issue, can you please share your fix? What had to be reinstalled
?
