### ISSUE TITLE
Android: Show image from local file

### ISSUE THREAD

**Issue by viccatoff** [ionic-team/capacitor#1096]
In my app I have functionality that downloads image from url and saves it local file system. And then I show this image inside img tag. On iOS device everything works like it should be. But on android I have an error: 
`GET https://localhost:6469/_capacitor_/data/user/0/io.ionic.starter/files/images/das1dp5nnlcacs-5baa4e982ff98.jpg net::ERR_CONNECTION_REFUSED`

File exists on device - I checked it by using `Filesystem.stat()` for this file:
```
{
    mtime: 1546531603000
    size: 210927
    type: "file"
    uri: "file:///data/user/0/io.ionic.starter/files/images/das1dp5nnlcacs-5baa4e982ff98.jpg"
}
```

To convert local file url to proper img url I'm using `window.Ionic.WebView.convertFileSrc()` function. 
Again, on iOS this works great, but not on Android. 

Am I doing something wrong?

**Comment by jcesarmobile** [comment]
are you using latest version of Capacitor? we no longer use the `_capacitor_` prefix but a dedicated scheme. Your url should look like `capacitor-file://data/user/0/io.ionic.starter/files/images/das1dp5nnlcacs-5baa4e982ff98.jpg`

**Comment by viccatoff** [comment]
Sorry, yeah, I had beta11 version. Just updated to beta13. Now error on Android looks like this: `GET capacitor-file:///data/user/0/io.ionic.starter/files/images/dasou31ie6ojdh-57bd499c29df6.jpg net::ERR_UNKNOWN_URL_SCHEME`

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by viccatoff** [comment]
Just created new sample app from scratch:

```
import { Plugins, FilesystemDirectory } from '@capacitor/core';
import { HTTP } from '@ionic-native/http/ngx';
const { Filesystem } = Plugins;

export class HomePage {
    public imageUrl;
    public imageShow = false;
    readonly targetDir;

    constructor(
        private httpNative: HTTP,
    ) {
        this.targetDir = FilesystemDirectory.Data;
    }

    public getData(): void {
        this.download('http://personal.psu.edu/xqz5228/jpg.jpg').then(imageUrl => {
          this.imageUrl = imageUrl;
          this.imageShow = true;
        }).catch(e => {
          console.log('error', e);
        });
    }

    public download(url: string): Promise<any> {
        return new Promise<any>((resolve, reject) => {
            const fileName = 'test2.jpg';

            Filesystem.getUri({
                directory: this.targetDir,
                path: ''
            }).then((result) => {
                const targetPath = result.uri + '/' + fileName;
                this.httpNative.downloadFile(url, null, null, targetPath).then((res) => {
                    if (res) {
                        resolve((<any>window).Ionic.WebView.convertFileSrc(targetPath));
                    } else {
                        reject();
                    }
                }).catch(reject);
            }).catch(reject);
        });
    }
}
```

and template:
```
<ion-content padding>
  <ion-button type="button" (click)="getData()"  fill="solid">getData</ion-button>
  <ion-img [src]="imageUrl" *ngIf="imageShow"></ion-img>
</ion-content>
```

By clicking on getData button it successfully downloaded image, stored it in data folder, return formatted url and tried to show in ion-img tag. But it throw an error `GET capacitor-file:///data/user/0/img.downloader.app/files/test2.jpg net::ERR_UNKNOWN_URL_SCHEME`

**Comment by jcesarmobile** [comment]
can you publish the sample app on github so I can clone and run it?

**Comment by viccatoff** [comment]
Sure, here it is - [ionic-image-downloader](https://github.com/viccatoff/ionic-image-downloader)

**Comment by jcesarmobile** [comment]
It's working fine on my devices (tested Android 5 and Android 8), I can see the minions image.

How are you testing? running the app directly or using live reload?

What's your Android version? real device or emulator?

**Comment by viccatoff** [comment]
Wow. That's interesting. I used both emulator (pixel 2) and real device (xiaomi mi mix 2s - android 9). I tested it like this:

```
npx cap add android
ionic cap run android -l
```
In Android Studio I just clicked Run and selected target device.

And yes, its using live reload. And how did you tested it?

**Comment by viccatoff** [comment]
Cool! Thank you!

**Comment by brospars** [comment]
Hi sorry to hijack this issue but I have a similar one loading a local video on Android : 
```
GET http://localhost/_capacitor_file_/data/user/0/fr.inria.epoc/files/video.mp4 net::ERR_FAILED
```

But then if I turn fullscreen on, the video loads... Any idea ? 

@jcesarmobile what do you means you don't use `_capacitor_file_` prefix anymore ? I still have it on Capacitor 3
