### ISSUE TITLE
How to set additional wkWebView settings

### ISSUE THREAD

**Issue by timboozle** [ionic-team/capacitor#1097]
I am using Capacitor without Ionic and I want to set additional WKWebView settings like:
- allowsBackForwardNavigationGestures
- allowsLinkPreview
- scrollView.bounces

How would this be possible?

**Comment by jcesarmobile** [comment]
It's not possible at the moment

**Comment by timboozle** [comment]
Thanks, so it's not possible at all to set those variables? Or is there a workaround maybe? Sorry, no experience with Swift but would like to have those things in my app

**Comment by jcesarmobile** [comment]
the only "workaround" is to manually edit the code to set the values you want

**Comment by chris-carrington** [comment]
Thank you ionic team for all your contributions to the community, allowing the ability to "allowsBackForwardNavigationGestures" would be much appreciated

**Comment by mlynch** [comment]
Thanks, certainly something we could explore adding down the road

**Comment by realityfilter** [comment]
On our project we had the need to register a custom url scheme handler. This can only
be done before the webview is initialized. I think one could easily refactor `CAPBridgeViewController`
to have factory methods for setting up the webview and the webview configuration and make the 
class and the factory methods open. Within a subclass `CAPBridgeViewController` one would be able to override as needed and specify the controller in the main storyboard.

If this is a viable solution I could make a PR for this. In the meantime we swizzle `WKWebViewConfiguration`.

**Comment by macdja38** [comment]
What does everyone think of adding a static method that plugins can implement to allow them to modify the WKWebViewConfiguration?

Something like this
```swift
    public static override func configureWKWebView(_ configuration: WKWebViewConfiguration) {
        CAPLog.print("Wouldn't it be cool if this got called?")
        configuration.ignoresViewportScaleLimits = true
    }
```
My only issue would plugins might step on each others toes, but I'm not sure how to possibly get around that.

**Comment by jcesarmobile** [comment]
since the issue is about the webview settings, those can be changed at any time, and as plugins have a reference to the webview, they can change any of the settings, so I'll just close.

@realityfilter @macdja38 as the `WKWebViewConfiguration` is a different issue, maybe you should create a new issue about it, or we can just keep @macdja38 PR as reference. Or you can send a separate PR since you mentioned a different idea.

**Comment by jcesarmobile** [comment]
In capacitor 3 you can use your own WebView, so you can configure it the way you want

for changing values during runtime, better create a plugin of your own that exposes the properties you need

**Comment by mb21** [comment]
So the recommended way in capacitor 3 is to use a [custom ViewController](https://capacitorjs.com/docs/ios/viewcontroller) and then implementing the `capacitorDidLoad` function? And there do something like:

     webview.allowsBackForwardNavigationGestures = true

**Comment by jcesarmobile** [comment]
It depends on what you want to change, if they are values that can be changed at runtime I recommend creating a plugin that allows to change those values.

**Comment by mb21** [comment]
Thanks for the reply! We just want to have `allowsBackForwardNavigationGestures` set to true... and don't want to change it afterwards. What's the reason you recommend doing that as a plugin instead of in `capacitorDidLoad`? is the plugin-api more stable? I'm a little bit worried of race conditions and such... but maybe there's no reason to?

**Comment by wr9** [comment]
@mb21 what did you end up doing?

**Comment by mb21** [comment]
we ended up using a [custom ViewController](https://capacitorjs.com/docs/ios/viewcontroller) that looks like this:

```swift
import UIKit
import Capacitor

class MyViewController: CAPBridgeViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        webView!.allowsBackForwardNavigationGestures = true
    }
}
```

**Comment by wr9** [comment]
@mb21 thank you, much appreciated!
