### ISSUE TITLE
E2E Testing for iOS and Android runtime

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#11]
My gut says E2E testing is going to be easier than unit testing plugins and mocking native APIs. Perhaps we need an app that tests each plugin at the JS layer, or doing something at the native layer. Would be awesome to only have to write it once.

**Comment by mlynch** [comment]
I believe manu is going to look into adding this directly into each runtime project so testing can be localized to the ios and android runtimes, respecitively

**Comment by mlynch** [comment]
Closing to keep features/improvements somewhere else

**Comment by jase88** [comment]
Would be great to have some documentation about (e2e) testing options for capacitor plugins 🙂

**Comment by markemer** [comment]
Closing as stale
