### ISSUE TITLE
Question: Does capacitor supports In App Purchase for iOS

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#1102]
Need to implement In-app purchase for iOS. Does the capacitor provide some plugin for integrating this feature?

Or will I have to use some cordova plugin to integrate In-app purchase.

**Comment by jcesarmobile** [comment]
There is no core plugin for In App Purchase, not sure about 3rd party plugins

**Comment by Bramzor** [comment]
There is a cordova plugin for this that you can use called cordova-plugin-inapppurchase

**Comment by nathantaal** [comment]
> There is a cordova plugin for this that you can use called cordova-plugin-inapppurchase

Did you ever manage to get that working together?

**Comment by stripathix** [comment]
Yes all good.

**Comment by twalkerjr22** [comment]
> Yes all good.

How did you get this to work?

**Comment by nathantaal** [comment]
> > Yes all good.
> 
> How did you get this to work?

You have to edit al the source files cordova used to do. Open an iap ionic app and look through the files. I remember editing android file to include the billing key, but it might require some more

**Comment by selected-pixel-jameson** [comment]
How is this just disregarded so easily? In App Purchase is a huge requirement seeing that Apple forces you to use their payment services for any kind of subscription and various other specific direct purchases.

**Comment by stripathix** [comment]
> > Yes all good.
> 
> How did you get this to work?

Was seamless for me. Command based integration just worked out of the box without any changes.

**Comment by Seanmclem** [comment]
> How is this just disregarded so easily? In App Purchase is a huge requirement seeing that Apple forces you to use their payment services for any kind of subscription and various other specific direct purchases.

Since making money is for businesses - its probably a premium API offered by Ionic for money.

**Comment by ve-amitsharma** [comment]
> > > Yes all good.
> > 
> > 
> > How did you get this to work?
> 
> You have to edit al the source files cordova used to do. Open an iap ionic app and look through the files. I remember editing android file to include the billing key, but it might require some more

Hi Can you please explain which file I need to update to add my Billing key.. Thanks in advance

**Comment by ve-amitsharma** [comment]
> > > Yes all good.
> > 
> > 
> > How did you get this to work?
> 
> Was seamless for me. Command based integration just worked out of the box without any changes.

Is it also Worked for Android? It's not working on Android for me. I'm getting this error continuously that { errorCode: -2, message: "Billing is not initialized", code: -2 }

**Comment by ve-amitsharma** [comment]
> > > Yes all good.
> > 
> > 
> > How did you get this to work?
> 
> Was seamless for me. Command based integration just worked out of the box without any changes.

Hi @stripathix , Please share the solution I can take help of that.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/2. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
