### ISSUE TITLE
How to make an existing VueJS + Ionic4 + Capacitor app a PWA 

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#1104]
I am little confused with documentation.

In documentation to add iOS we need to run 
`npx cap add ios`

But I am not sure what I need to do to add PWA support to my app.

In Capacitor docs https://capacitor.ionicframework.com/docs/web/ it is told that I just need to add below code to make a PWA app. And after build I need to serve my dis folder **npx cap serve** 
`import { Capacitor } from '@capacitor/core';`

But on doing **npx cap serve** I am not seeing any manifest file or service worker in developer tools.

Am I missing anything?

My capacitor.config.json looks like this
```
{
  "appId": "net.b*********",
  "appName": "***********",
  "bundledWebRuntime": false,
  "webDir": "dist",
  "ios": {
    "minVersion": "11"
  }
}
```

Do I need to create my own service worker and manifest files so that splash screen and icons of PWA can be configured or Capacitor itself does that?

**Comment by stripathix** [comment]
Will this need a combination of capacitor and https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa ?

**Comment by GuilhermeBCC** [comment]
I'm not sure, but I'll try to help

You already know what you need to have a PWA so create one. Capacitor does not create the PWA. You create it. And then you can use the Capacitor Plugins (with pwa support) in your PWA.

**Comment by stripathix** [comment]
@GuilhermeBCC That's what I thought. I have integrated PWA support in my existing vue app using cli-plugin-pwa :-) Working on deploying it over https dev environment to test n real device as service-worker works only on localhost or https.

**Comment by mlynch** [comment]
Hey @stripathix thanks for the question.

We don't *make* your app a PWA. You should manage your manifest and service worker in your Vue project yourself. Capacitor then provides API access to certain key Web APIs in a way that is cross-platform and works the same when you deploy to iOS and Android.

So really the "web" side of Capacitor is just your web app that you manage yourself, and then Capacitor's cross-platform plugin layer.
