### ISSUE TITLE
Update the roadmap

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#1111]
Curious to learn what the updated roadmap for 2019 will be. 

That will also help people trying to understand roughly when capacitor may be production ready, what functionality will be in the initial release and what stuff may go into the future releases.

**Comment by jcesarmobile** [comment]
Maybe this blog post can help https://blog.ionicframework.com/capacitor-in-2019-native-progressive-web-apps-for-all/?

**Comment by sandstrom** [comment]
@jcesarmobile Awesome, it does indeed!

If you'd like you can update the Roadmap heading in the readme (that's what prompted me to open this issue), to avoid having the project look stale (I know it isn't, but others might now).

**Comment by sandstrom** [comment]
friendly ping @jcesarmobile
