### ISSUE TITLE
absolute URLs with no hostname not loading over ajax with default settings

### ISSUE THREAD

**Issue by rj33** [ionic-team/capacitor#1118]
Prior to the removal of the webserver ( and shift to using capacitor://) urls like
"/foo/target.js" would load fine.

Now they don't. 

Absolute URLs are working fine when loaded from my index.html, but fail to load over ajax in absolute form, i.e

looks like in the latest version (I'm running beta 13) the protocol/host is
capacitor://localhost and the absolute URLs in index.html such as
"/foo/init.js" seem to be translated fine to:
capacitor://localhost/foo/init.js

However when loaded from ajax they are getting loaded as
capacitor:///foo/ajaxtarget.js and this fails.

I'm able to work around this by setting an explicit server url to use for loading:
 "server": {
        "url":"capacitor://"
    }

But this workaround seems to be leading to some other problems (since moving from beta 11 to beta 13 , I'm having some CORS problems, which I haven't diagnosed yet, but may be related to this workaround).

Is it possible to fix the asset loader so that absolute urls work as expected from ajax loads?

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

I can't reproduce on a new Ionic app, tried `fetch("1.js")`, `fetch("./1.js")` and `fetch("/1.js")` and all of them worked.

**Comment by rj33** [comment]
Sorry I don't have anything I can easily send right now.

The fetch("/1.js") case is the case that is failing for me in terms of URL form, but I'm probably not using the fetch API, and I'm not sure how close the code path is on the traditional ajax api's (I'm using systemjs to do module loading, which is why I'm not 100% sure whether I'm using fetch or not for this particular error case, but I'm running a fairly old version of systemjs that I suspect would be using XMLHttpRequest,  I use XMLHttpRequest in other parts of my code, but I can't test that yet, because that code doesn't load with the default capacitor settings due to the module loader failing before then when trying to grab the modules over ajax calls).

Do you expect fetch to behave exactly the same as XMLHttpRequest? Can you confirm a "/1.js" style URL works for you with an XMLHttpRequest object for the ajax call?

If the problem is at my end, do you have a theory why setting 
"server": {
"url":"capacitor://"
}

Fixes the ajax loading problem?

**Comment by rj33** [comment]
Sorry, just a follow up after noticing you'd added the following code 5 days ago:
    if (url.startsWith('/')) {
      return 'capacitor-file:///' + url;
    }

That looks like it might be relevant to my case, are you running your ajax tests from master or from the last official release?

**Comment by jcesarmobile** [comment]
That's for when using `convertFileSrc` function, I'm not using `convertFileSrc` in my tests, are you?

**Comment by rj33** [comment]
No I'm not. Were you able to confirm that XMLHttpRequest also worked for "/1.js" URLs in your test?

**Comment by jcesarmobile** [comment]
I have no experience with systemjs, but looks like a problem in their end.

capacitor:///js/foo.js and capacitor://localhost/js/foo.js are not effectively the same for the browser as it takes the hostname into account and usually even forbids cross domain requests.
What you can do instead of setting the server url is to set the server hostname with “” or “/“ as the server url setting is for using an external url and might produce some different behavior

**Comment by rj33** [comment]
> I have no experience with systemjs, but looks like a problem in their end.
> 
> capacitor:///js/foo.js and capacitor://localhost/js/foo.js are not effectively the same for the browser as it takes the hostname into account and usually even forbids cross domain requests.
> What you can do instead of setting the server url is to set the server hostname with “” or “/“ as the server url setting is for using an external url and might produce some different behavior

Whether capacitor:///js/foo.js and capacitor://localhost/js/foo.js are the same depends on the rules you define for the scheme. For file:// for example they are equivalent, from RFC3986:

  "If the URI scheme defines a default for host, then that default
   applies when the host subcomponent is undefined or when the
   registered name is empty (zero length).  For example, the "file" URI
   scheme is defined so that no authority, an empty host, and
   "localhost" all mean the end-user's machine, whereas the "http"
   scheme considers a missing authority or empty host invalid."

This makes file:///js/foo.js and file://localhost/js/foo.js equivalent in the browser.

It feels to me like your capacitor scheme could operate similar to the file scheme in that respect, and define localhost as the default host,  especially if the capacitor scheme is only ever used to load from local device's filesystem. It might help make it work with a wider set of libraries.  I'm not sure why the systemjs system loader is  assuming SCHEME+absolute paths without hostnames are legal uris with the capacitor scheme. I'm not explicitly feeding it any scheme, it seems to be auto-deciding on the scheme to generate the module load paths, and perhaps decides anything not http/https is ok to use without hostname.

Anyway, I might be change the module loader config to force a full path, although I was trying to get away with as few changes as possible between the non-capacitor web version and the native version. I'll also try your suggestion of hostname instead of url config.

**Comment by jcesarmobile** [comment]
I've tested doing a fetch and XHR to "capacitor:///1.js" and it's being blocked by Safari because of cross origin restrictions. So, yeah, they are "equivalent", but for Safari it's a different origin and blocks it because it only allows it for HTTP. We can't configure this behaviour,  nor the scheme rules because Apple doesn't provide any way of doing it.

I've tried configuring the hostname to "" and "/" and both of them worked
Example:
```
"server": {
      "hostname": "/"
}
```

**Comment by rj33** [comment]
Thanks, that makes sense regarding scheme configurability. Your hostname suggestion does indeed allow systemjs to load the modules now. Thanks for your time and suggestions! I'm still having some CORS issues that seemed to resolved prior to the capacitor:// change,  but that is probably a config issue at my end, so I won't bother you that.
