### ISSUE TITLE
Running the example Android application

### ISSUE THREAD

**Issue by cwoolum** [ionic-team/capacitor#112]
I  am trying to run the example android app but I get this error to select an Android SDK version. I would expect the framework to select that by default so I could just open Android Studio and click run. Running on Windows 10 with Android Studio 3.0

![image](https://user-images.githubusercontent.com/942415/35819896-eb9c563e-0a58-11e8-9136-9f27145506fb.png)

Default Settings for the module:

![image](https://user-images.githubusercontent.com/942415/35819978-2fb8ec24-0a59-11e8-8de2-9f3e2fed9844.png)

**Comment by mlynch** [comment]
You need to sync gradle after opening it and before doing a run:

https://capacitor.ionicframework.com/docs/android/#syncing-gradle

Can you confirm it works after doing that?
