### ISSUE TITLE
[iOS] Updating the ios platform automatically removes my second target

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor#1121]
Hi,

I'm using several targets in the Podfile so I can manage multiple environments (production and development for example).

But when running `npx cap update ios` it removes the second target from the Podfile and everything linked to it (inside Podfile.lock and project.pbxproj). To fix that I need to manually set a new time the second target by discarding changes of the Podfile, and then, I have to run `pod install` inside the Podfile directory to install what "disappeared". After that I'm able to run my second target.

That's really annoying but I didn't see a related issue. Any thoughts?

Thank you,

**Comment by jcesarmobile** [comment]
Can you provide a sample of how your podfile looks like before being overwritten?

**Comment by sneko** [comment]
@jcesarmobile  sure:

```
platform :ios, '11.0'
use_frameworks!

target 'Production' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  # Do not delete
end

target 'Development' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  # Do not delete
end
```

The "Development" one is the one removed.

**Comment by jcesarmobile** [comment]
Yeah, it uses a regular expression to add the content, by adding a second closing tag it will delete all in between.
I’ll try to find a way of making it easier to have multiple targets

**Comment by sneko** [comment]
Thank you @jcesarmobile 👍

**Comment by jcesarmobile** [comment]
As the fix is a change on the Podfile you won't get the change on existing projects, so you'll have to change your Podfile to look like the one on the PR.

Add this before your targets
```
def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  
  # Do not delete
end
```

And in your targets add `capacitor_pods` like this:

```
target 'Development' do
  capacitor_pods
  # Add your Pods here
end

target 'Production' do
  capacitor_pods
  # Add your Pods here
end
```
