### ISSUE TITLE
Modals.confirm can't set title

### ISSUE THREAD

**Issue by HellsingMatt** [ionic-team/capacitor#1126]
Can't set Modals.confirm's Title, am I wrong ???: 

```
let exit = async () => {
    let ret = await Modals.confirm({
        title: 'exit ?',
        message: 'blahblahblah'
    })
    console.log(ret)
}

```

![image](https://user-images.githubusercontent.com/30370186/51235726-391fd400-19ab-11e9-905e-1fa23db6bb74.png)

BTW: can't we change buttons' text ?

**Comment by jcesarmobile** [comment]
Are you testing as Android app or on web/PWA?
In case it's Android app, which Android version? 
I can't reproduce

For configuring Confirm button titles you have `okButtonTitle` and `cancelButtonTitle`

**Comment by HellsingMatt** [comment]
> Are you testing as Android app or on web/PWA?
> In case it's Android app, which Android version?
> I can't reproduce
> 
> For configuring Confirm button titles you have `okButtonTitle` and `cancelButtonTitle`

sorry my bad,

I'm testing on Android Pie 9.0, omni 9,
@capacitor/android/cli/core all 1.0.0-beta.13

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce.
Looks like you are using the web implementation instead of the native one.
