### ISSUE TITLE
Filesystem.WriteFile doesn't save file correctly

### ISSUE THREAD

**Issue by GuilhermeBCC** [ionic-team/capacitor#1130]
When saving a file, other than text, it does not display properly in the android file system.

Often when using FileReader.readAsDataURL to create a string from a Blob a header is also created.
The android system does not recognize this seemingly or he is formatted wrong, I do not know ..

Solution.

Removes the header before creating the file.
```javascript
   //remove header
    const split = data.split(',')[1]; //data:image/jpeg;base64,AUIDUHIWad....
    data = split[1] || data;
```

**Comment by mhjam** [comment]
As far as I see, this fix breaks saving plain text files, as soon as they contain a comma. The splitting of data should happen only in the else-branch of `if (charset != null)`.

**Comment by GuilhermeBCC** [comment]
Hello, you could create a pull request?

**Comment by mhjam** [comment]
@GuilhermeBCC Will try to, but at the moment I am busy with other stuff.

**Comment by jcesarmobile** [comment]
I've fixed it here https://github.com/ionic-team/capacitor/pull/1473

@mhjam, please, if you find issues report them on https://github.com/ionic-team/capacitor/issues as a new issue instead of commenting in old issues. Comments on old issues might be missed.
