### ISSUE TITLE
Local notification sounds

### ISSUE THREAD

**Issue by CrixuAMG** [ionic-team/capacitor#1146]
I've looked at the current documentation for local notification, and while it does display which methods and options are available, it does not explain what type can be used for each option.
What I'm trying to do is use a custom notification sound, but I haven't got it working yet.
The sound is located at [ROOT_PROJECT]/public/assets/sound/sound.aiff (for iOS), and trying to load in the sound using the snippit below.

```
import { Plugins } from '@capacitor/core';
const { LocalNotifications } = Plugins;

LocalNotifications.schedule({
  notifications: [
    {
      title: "Title",
      body: "Body",
      id: 1,
      schedule: { at: new Date(Date.now() + 1000 * 5) },
      sound: 'assets/sounds/sound.aiff',
      attachments: null,
      actionTypeId: "",
      extra: null
    }
  ]
});
```

I've also tried applying `file://` in front of it (got this from [ionic](https://ionicframework.com/docs/native/local-notifications/)), and using a direct path.
I know that the sound exists at that path, and that it can be played, but I have no clue what needs to be done to make it play that sound.

If anyone has an idea on how to do it, please let me know!

**Comment by mlynch** [comment]
Hey @CrixuAMG,

So this sound needs to be relative to the actual native project. If it's in your web content it *won't* work.

Try putting the sound in your android project in the `res/raw` folder in your android project, and then pass 

```javascript
'android.resource://com.yourapp.whatever/raw/mysound.mp3'
```

Replacing the `com.yourapp.whatever` and `mysound.mp3` with the proper values.

Let us know if that works!

Linking with #1530 to better document this stuff.

**Comment by CrixuAMG** [comment]
@mlynch thank you for replying!

Would the same fix also apply for iOS devices?

**Comment by lucascardoso** [comment]
Hello @CrixuAMG! 
I still can't make the sound work.
I tried to do it that way

![imports](https://user-images.githubusercontent.com/2519428/61906376-93bd5e00-af01-11e9-8ca8-bd5f0375cb93.PNG)
![notification](https://user-images.githubusercontent.com/2519428/61905415-666fb080-aeff-11e9-8bf7-29847384b9d2.PNG)

Can you help me?
Thank you very much in advance!

**Comment by CrixuAMG** [comment]
@lucascardoso @mlynch 

I finally fixed the problem. It was actually very simple to do, just had to check the iOS directory...

This is the fix:
`sound:        './public/assets/sounds/sound.aiff',`

Works on at least iOS 12 and 13.1 beta 2

**Comment by naveedahmed1** [comment]
I placed sound file in `android\app\src\main\res\raw` and have below settings for `LocalNotifications.schedule`:

```
LocalNotifications.schedule({
                        notifications: [
                            {
                                title: data['title'],
                                body: data['body'],
                                id: 1,
                                schedule: { at: new Date(Date.now() + 1000 * 5) },
                                sound: 'android.resource://com.mypackagename/raw/pop_drip.wav',
                                smallIcon:'res://icon_silhouette',
                                actionTypeId: "",
                                extra: null,
                                attachments: null
                            }
                        ]
                    });
```

But its not working, its still playing default sound.

**Comment by zlannin** [comment]
@naveedahmed1 Did you ever get the sound to work? Having the same issue currently.

**Comment by naveedahmed1** [comment]
No

**Comment by Faroukymedia** [comment]
same problem here, any fix ?

**Comment by moderntechllc** [comment]
Hey guys after long time testing, I have figured it out using the capacitor local notifications on any version of Android. ******To get the sound working you must create a channel*****

First you need to put the sound.mp3 file that you have inside the raw folder located in the res folder of Android files.

Second you need to create a channel using the plugin and put in the right values, for sound: 'sound.mp3'. Then schedule a notification with the basic values but don't include the sound file. 

Third inside the capacitor.config.json file put 
Plugins {
LocalNotification {
 "sound": "sound.mp3"
}
}

That's all after that it will be working. Once your notification triggers it will play the custom sound you assigned. If you get confused let me know. Here is the video you can follow to help you understand better.
https://youtu.be/bww4a4B43tM

**Comment by bitflower** [comment]
Thanks @moderntechllc 

The actual position in the video is this: https://youtu.be/bww4a4B43tM?t=466

**Comment by Maraaghib** [comment]
I have fixed this issue by creating first a channel:

![image](https://user-images.githubusercontent.com/25940227/102218381-2804d800-3ede-11eb-88da-ccb1ba3f5f5a.png)

Then, I schedule my notification without speciying the sound path:

![image](https://user-images.githubusercontent.com/25940227/102218721-b24d3c00-3ede-11eb-835f-ae6124b0d34c.png)

**PS: I did not do any configuration on capcitor.config.json**

It works perfectly on Samsung Galaxy A71 (SM-A715F) - Android 10

If you want to change dynamically the notification sound, you delete this channel and create another one with only a different id

**Comment by KumarShubham001** [comment]
Fixed the issue by creating the channel. But channel is only supporting in android. Here is my solution:
constructor() {
    LocalNotifications.createChannel({
      id: 'CurrencyAlerts',
      name: 'CurrencyAlerts',
      importance: 5,
      description: 'Currency alerts',
      sound: 'notification.mp3',
      visibility: 1,
      vibration: true,
    });
  }
You can create this channel in the service's constructor maybe...

And then use this channel's ID to trigger the notification like this:
async alert(title, body) {
    const randomId = Date.now() + 69;

    return await LocalNotifications.schedule({
      notifications: [
        {
          title: title,
          body: body,
          id: randomId,
          schedule: { at: new Date(Date.now() + 500) },
          // sound: null,
          attachments: null,
          actionTypeId: '',
          extra: null,
          channelId: 'CurrencyAlerts',
        },
      ],
    });
  }
So here, You will get the unique ID for every alert. DONT USE THE SOUND in the schedule options and schedule it after 0.5secs of target date-time.

**Comment by mayankkataria** [comment]
I tried all above ways. Still sound is not coming. I even tried cordova plugin. Idk what's the issue.
