### ISSUE TITLE
Persistent local notification (Android)

### ISSUE THREAD

**Issue by nathantaal** [ionic-team/capacitor#1147]
I want to be able to make notifications on android persistent (So it cannot be swiped away) is this already possible?

**Comment by jcesarmobile** [comment]
It's not possible.
As far as I know, the setOngoing should be true to be persistent, but right now it's not configurable
https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java#L150

**Comment by nathantaal** [comment]
There are lots of todo's there but it should be as simple as putting ongoing in the localNotification object and reading it instead of setting it hardcoded to false. I might do that I have have some spare time at the end of this week.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest

**Comment by nathantaal** [comment]
A few hours before closing I actually opened capacitor on GitHub to look at the statues of my issue (I looked how far my issue was away from the last page, I figured low-priority issues coming closer to the last page would eventually be resolved.)
In general, I think for capacitor to succeed, it's needs a few full-featured API's and not many API's that are all implemented half. I'm not saying local notifications needs to be this API but last time I checked (And yes, that is a half year ago) most a API where's just half-done.

**Comment by DasNiels** [comment]
Would love to have this aswell, a simple boolean value shouldn't be too hard to implement no?

**Comment by jcesarmobile** [comment]
Removing feature request tag since it was implemented in https://github.com/ionic-team/capacitor/pull/3165
