### ISSUE TITLE
Android: Audio can't be played outside of user gesture events

### ISSUE THREAD

**Issue by redwolf2** [ionic-team/capacitor#1152]
My code:
```
 protected async playFile(context: string) {
    const audio = new Audio();
    audio.src = context;
    audio.load();
    await audio.play();
  }
```

`await this.playFile('/assets/audio/goodbeep.wav');`

will run fine on chrome desktop, but will cause this error on Android:

`capacitor-runtime.js:70 ERROR Error: Uncaught (in promise): NotAllowedError: play() can only be initiated by a user gesture.`

This is the fix, that should get it to work on the native WebView, but how do I set it in code and shouldn't that setting be a default for native web apps?

`webView.getSettings().setMediaPlaybackRequiresUserGesture(false);`

**Comment by jcesarmobile** [comment]
It's already there https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L311, but not released yet

**Comment by redwolf2** [comment]
Alright, thank you.

**Comment by jcesarmobile** [comment]
It’s released now

**Comment by redwolf2** [comment]
That's me flipping the table right now, dude, you are fast.
