### ISSUE TITLE
Cli copy does not respect platform dir config

### ISSUE THREAD

**Issue by mhamel06** [ionic-team/capacitor#1157]
## Project Setup
Added capacitor to existing non ionic project and ran the command: `npx cap  add ios`

Cap created ios dir at root of project.
I modified the config to look as follows:
```
{
  "appId": "my.sample.app",
  "appName": "my-sample",
  "bundledWebRuntime": false,
  "webDir": "dist/apps/web"
}
```
Everything works as expected

I moved the ios dir to `apps/ios` and modified the config to:
```
{
  "appId": "my.sample.app",
  "appName": "my-sample",
  "bundledWebRuntime": false,
  "webDir": "dist/apps/web",
  "ios": {
    "platformDir": "apps/ios"
  }
}
```

running any cap commands for ios like `npx cap copy ios` result in the error:
`[error] ios" platform has not been created. Use "capacitor add ios" to add the platform project.
`.

Adding a dummy ios directory allows the `selectPlatform` call to pass but does not respect the platform dir for copying any assets. https://github.com/ionic-team/capacitor/blob/5e6feb6f69a327993613b0579310507209183e6c/cli/src/config.ts#L239

I am new to the project but I think the copy and other platform specific commands should be changed to always check and respect the platformDir config.

ex. https://github.com/ionic-team/capacitor/blob/master/cli/src/tasks/copy.ts#L34-L37

My only motivation is to be able to move the platform dir to a new location inside my project so if there is a way to do this, that would resolve my issue as well. 

Thanks

**Comment by jcesarmobile** [comment]
`platformDir` is not really configurable, there is no way of moving the platforms dirs to other places, iOS platform code will be inside ios folder, Android inside android and electron inside electron.

**Comment by mhamel06** [comment]
I'm fine with platform specific code being inside it's designated directory. I would just like to at least configure the parent for the platform directories. That way I could move the ios, android and electron dir from the root of my project to a subdirectory.
ex. 
```
From:
/ios
/android
/electron
/apps
    /web

To:
/apps
    /web
    /ios
    /android
    /electron
```

**Comment by sbannigan** [comment]
As of beta 14, you should be able to do something like this:
```
{
  "appId": "my.sample.app",
  "appName": "my-sample",
  "bundledWebRuntime": false,
  "rootDir": "apps"
  "webDir": "../dist/apps/web"
}
```
By setting the rootDir all the platform directories will be in that directory. The webDir is then relative to the rootDir.

**Comment by mhamel06** [comment]
thanks @sbannigan that works for me

**Comment by DmitryEfimenko** [comment]
each time I try to run `npx cap add android` after setting `rootDir` it does not get past the "Installing android dependencies" step. However, if I (1) run  `npx cap add android` with default settings so that it installs deps, (2) undo that step by manually deleting generated files except for the deps, (3) update the `rootDir` like shown above and (4) run `npx cap add android` again, it will skip the failing step and succeed. Super annoying

**Comment by tvvignesh** [comment]
Great! Would be great if this is documented in the docs. Thanks.
