### ISSUE TITLE
Keyboard does not show tab bar, until another input is clicked

### ISSUE THREAD

**Issue by EricKit** [ionic-team/capacitor#1161]
Selecting an ion-input opens the keyboard (and raises the input). The tab bar is not displayed. When another input is selected, the tab bar pops into view.

Expected behavior: Either the tab bar is present or is not present for all input clicks.

![out](https://user-images.githubusercontent.com/4143477/51793099-f19a0480-216f-11e9-9728-e5eada35f16a.gif)

Of note, there is a similar Cordova Keyboard issue: https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/47

```
  "plugins": {
    "Keyboard": {
      "resize": "ionic"
    }
  }
```

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 2.0.0
   ios-sim    : 7.0.0
   NodeJS     : v11.6.0 (/usr/local/bin/node)
   npm        : 6.7.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```
Possibly similar to @sneko https://github.com/ionic-team/capacitor/pull/1119

**Comment by jcesarmobile** [comment]
Proper behaviour for tab bar is to disappear when the keyboard appears, it shouldn't appear when you change the field. I've fixed the problem in the linked PR.

**Comment by solojuve1897** [comment]
@jcesarmobile 
On Android I have the problem where my fixed tab bar doesn't dissapear when the keyboard appears. The keyboard just pushes the fixed tab bar upward like @EricKits image shows.

I'm on beta 17. I don't use Ionic. I use Vue.js with Vuetify. More specifically I use this component with it's fixed property:
https://vuetifyjs.com/en/components/bottom-navigation#bottom-nav

I haven't tested the application iOS and therefore can't say what happens there.

**Comment by jcesarmobile** [comment]
I was talking about proper Ionic behaviour, not sure about other frameworks.
Here is Ionic what hides the tab bar when the keyboard appears, but if Vue doesn't do it you should ask them for that feature, or see if you can hide it yourself.
The only thing Capacitor does it to send the hide/show events so frameworks can know, but the handling depends on them or the framework users.
