### ISSUE TITLE
Launch Image changes size

### ISSUE THREAD

**Issue by smelzer** [ionic-team/capacitor#1162]
I replaced the default capacitor launch screen images in the Assets.xcassets file.  My problem is about halfway through the app load the splash screen image changes size.

I tried 3 different approaches.  
First I tried to replace the 2732x2732 full screen capacitor default images with 240x240 images and set the UIImagesView Content Mode to 'Center' instead of 'Aspect Fill'.  It looks correct at first, then halfway through the splash screen time, the image blows up to cover the entire screen and even covers the home page when it starts for a moment.

Then I created my own 2732x2732 images but still left the Content Mode to 'Center'.  Halfway through the image gets smaller but otherwise works correctly.

Third attempt I changed the Content Mode to 'Aspect Fill' like the default, and everything works correctly.

I do not have an issue but rather just a curiosity.  I am wondering why the resizing happens.  What event is firing and why does the screen "change size"?

Thanks,
Steve

**Comment by jcesarmobile** [comment]
Closing as it was a curiosity and I answered it
