### ISSUE TITLE
[1.0.0-beta.17][iOS] When keyboard is displayed we can scroll down and see a blank area

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor#1166]
Hi,

#1119 has fixed the keyboard showing up but there is an issue of scroll: if I focus on an input, the keyboard will show up, but if now I try to scroll the view, I can go further than the bottom of my content.

It seems to correspond to the keyboard height, so that's maybe the padding set in #1119 to push the content up?

Here is an example:
![image](https://user-images.githubusercontent.com/8195958/51802140-275dec80-2247-11e9-9269-000ebfaf7da9.png)

Thank you,

Note: I'm using the released Ionic 4.0

**Comment by jcesarmobile** [comment]
Should be fixed on https://github.com/ionic-team/capacitor/pull/1180

**Comment by sneko** [comment]
I just tried by patching manually the files and it works, there is more white area under content.

Thank you!
