### ISSUE TITLE
[iOS] CAPPlugin.m, line 10: Property 'getWebView' not found on object of type 'CAPBridge *'

### ISSUE THREAD

**Issue by drtomato** [ionic-team/capacitor#1168]
Could not build on iOS because of the error above. Fails on 1.0.0-beta.15 and later but works on 1.0.0- beta.14, so the cause should be somewhere in the upgrade from beta.14 to beta.15.

**Comment by jcesarmobile** [comment]
I can't reproduce on beta 17. I think beta 15 went wrong according to a message on Capacitor's slack.

If you can still reproduce on beta 17 try this.
First make sure you are on Xcode 10 as beta 17 will use Swift 4.2, which is not available on Xcode 9.
Second, completely close Xcode.
Run `npx cap update ios` and then `npx cap open ios`.
Finally do a Product -> Clean Build Folder and run the app with run button when the clean finish.
