### ISSUE TITLE
[1.0.0-beta.17][iOS] The scroll bouncing behavior is still enabled

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor#1169]
Hi,

To follow up my question posted in December on Slack: the bouncing is present when scrolling.

I would like to disable this behavior but I don't understand how I can proceed... It seems already disabled in the Capacitor settings:
https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L49

I was also hoping on a hack on Ionic side, but it's precised in its documentation (https://github.com/ionic-team/ionic/tree/2c37a5a7b279da9f82b377d54b27ba2a8391eaed/core/src/components/content#forceoverscroll) that: `Note, the does not disable the system bounce on iOS. That is an OS level setting.`

To reproduce the behavior you just need to have a content in <body bigger than the <body height, something like:
```
  span hey
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  span hey
  br
  br
  br
  br
  br
  br
  ...
  br
  br
  br
  br
  br
  span hey
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
  br
```

Thank you,

EDIT: by the way, since I'm not seeing any people posting a related issue, maybe I'm doing wrong. If someone has the bouncing disabled, please share a code example 👍

**Comment by jcesarmobile** [comment]
I can't reproduce. On a regular app without framework it doesn't bounce.
In an Ionic app it bounces, but just the ion-content content, not the header, so I think that's ion-content behaviour and you can probably configure it to not bounce.
If using a different framework, same thing, should be framework related.

**Comment by sneko** [comment]
As you noticed the ion-header and ion-footer are sticked properly without bouncing.

About ion-content I already tried with force-overscroll="false" but it does not change anything. I will post over their repo.

Note: didn't try for now with another framework or with just vanilla JS

**Comment by gesrt** [comment]
Same issue.

**Comment by jcesarmobile** [comment]
Can any of you provide a sample app?

@sneko to be clear, what bounces is the ion-content?

**Comment by MarkChrisLevy** [comment]
If you want to disable bouncing in ios you need to add somewhere (e.g. create DisableBounce.m file) following code:
```
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@implementation UIScrollView (NoBounce)
- (void)didMoveToWindow {
    [super didMoveToWindow];
    self.bounces = NO;
}
@end
```

Additionally, if you use ionic 4, for each ion-content you should set force-overscroll=false.

**Comment by sneko** [comment]
Such a good news haha! It works!

Thank you @MarkChrisLevy 👍 

BTW, any idea why https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L49 does not have the same behavior?

**Comment by ollydixon** [comment]
> If you want to disable bouncing in ios you need to add somewhere (e.g. create DisableBounce.m file) following code:
> 
> ```
> #import <Foundation/Foundation.h>
> #import <UIKit/UIKit.h>
> 
> @implementation UIScrollView (NoBounce)
> - (void)didMoveToWindow {
>     [super didMoveToWindow];
>     self.bounces = NO;
> }
> @end
> ```
> 
> Additionally, if you use ionic 4, for each ion-content you should set force-overscroll=false.

this breaks < IonRefresher /> at least in React and a few other components act strange. Why is a basic thing still so broken....

**Comment by giuseeFG** [comment]
> > If you want to disable bouncing in ios you need to add somewhere (e.g. create DisableBounce.m file) following code:
> > ```
> > #import <Foundation/Foundation.h>
> > #import <UIKit/UIKit.h>
> > 
> > @implementation UIScrollView (NoBounce)
> > - (void)didMoveToWindow {
> >     [super didMoveToWindow];
> >     self.bounces = NO;
> > }
> > @end
> > ```
> > 
> > 
> > Additionally, if you use ionic 4, for each ion-content you should set force-overscroll=false.
> 
> this breaks < IonRefresher /> at least in React and a few other components act strange. Why is a basic thing still so broken....

Did you find a solution to use the Obj-C code combined with ion-refresher?

**Comment by hsdmedia** [comment]
> If you want to disable bouncing in ios you need to add somewhere (e.g. create DisableBounce.m file) following code:
> 
> ```
> #import <Foundation/Foundation.h>
> #import <UIKit/UIKit.h>
> 
> @implementation UIScrollView (NoBounce)
> - (void)didMoveToWindow {
>     [super didMoveToWindow];
>     self.bounces = NO;
> }
> @end
> ```
> 
> Additionally, if you use ionic 4, for each ion-content you should set force-overscroll=false.

this works, but it breaks <ion-refresh> in entire application, any hack ?
