### ISSUE TITLE
Manifest-based apps generation

### ISSUE THREAD

**Issue by antarestupin** [ionic-team/capacitor#1170]
Are there any plans to add manifest-based apps generation, similarly to what Microsoft did with [PWABuilder](https://www.pwabuilder.com/)?

It would be helpful to be able to only embed into the generated apps the URL of the PWA's manifest and then let them fetch the PWA's manifest and resources when starting. Compared to rebuild and redeploy the apps at each update, the main advantages would be:

- Well, not having to rebuild and redeploy the apps at each update, it would be necessary only for changes such as adding / removing Capacitor plugins
- The generated apps would always be up-to-date, like a regular PWA would behave
- Resources can be cached thanks to service workers, so it would still be possible to keep correct startup performance compared to having all the resources locally

I think that, for many apps, being able to convert PWAs this way would improve developers productivity and make the generated apps behave more like standard PWAs, which seems to be compliant with the vision encouraged by Capacitor and Ionic.

What's your opinion on this?

**Comment by mlynch** [comment]
What do you mean 'generated apps'? Basically put a URL in for a website, pull that down and create a PWA out of it?

**Comment by antarestupin** [comment]
It seems the scope of PWABuilder changed since I opened this issue, I guess it makes it harder to understand the idea. Now it only generates a manifest and a few services workers in order to help you create a PWA.

Originally, this tool (called [Manifold](https://github.com/pwa-builder/PWABuilder-CLI/wiki) at the time) generated iOS and Android apps that were quite simple: at launch, they fetched the manifest file of the website and then its main page (the one defined in manifest's `start_url`), and ran the PWA inside a WebView. Cordova was included so that the PWA could access native features, but basically the idea was to emulate the behaviour of an installed PWA, so that it could be installed via app stores in smartphones that don't support PWAs.

My idea here was to do the same, but using Capacitor instead of Cordova.

**Comment by jcesarmobile** [comment]
I think this is out of the scope of Capacitor and apps like that can easily get banned by Apple or Google since they don't like wrapped apps.

Using [Appflow](https://ionicframework.com/appflow) and other services you can get live updates, but your main app code will always live inside your app, not online.

Capacitor allows to load from remote urls if you configure the `server.url` property in the `capacitor.config.json`, that's meant to be used for development, but you can use it in production on your own risk.
