### ISSUE TITLE
Capacitor beta.17 update causing so 17 errors

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#1176]
Since I update to capacitor.beta.17 I am seeing lot of errors . Are there any breaking changes?

<img width="1075" alt="screenshot 2019-01-29 at 3 39 23 pm" src="https://user-images.githubusercontent.com/8480351/51900796-2b6f4300-23dc-11e9-8a42-7018a6c23ee9.png">

**Comment by jcesarmobile** [comment]
It has been updated to swift 4.2. 
What’s your swift version?
What’s your Xcode version?

**Comment by stripathix** [comment]
Updated to swift 4.2.
Xocde version: Version 10.1 (10B61)

After updating to swift 4.2 now I am getting three errors.

<img width="1037" alt="screenshot 2019-01-29 at 4 32 21 pm" src="https://user-images.githubusercontent.com/8480351/51903959-78a2e300-23e3-11e9-8d6f-af51e0e02da0.png">

**Comment by stripathix** [comment]
Updated swift version is xCode under Build Settings. Do I need to change it anywhere else also?

<img width="641" alt="screenshot 2019-01-29 at 4 33 34 pm" src="https://user-images.githubusercontent.com/8480351/51904052-ad169f00-23e3-11e9-90f8-c1354e9f1a13.png">

**Comment by jcesarmobile** [comment]
If you manually changed ti to 4.2 then you weren't using 4.2. You have to do a migration. Do a Edit -> Convert -> To current Swift syntax.
It should only ask you to convert the target "App".
In case Capacitor target also appears for Conversion, check the Swift version that appears there and also provide your CocoaPods version.

**Comment by stripathix** [comment]
@jcesarmobile  Thanks :-) .

To fix this what I did was to move back to beta.14 then convert the app to swift 4.2 and after that, I updated capacitor modules to beta.17. 

All good now. :-)
