### ISSUE TITLE
Actual list of possible platforms in Device plugin

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#1177]
Previously it was stated that `latform` from `await Device.getInfo()` can be either of those:

- `android`
- `ios`
- `electron`
- `pwa`

Searching through the docs and codebase I wasn't able to find any enum or something like that which would clearly specify all possible values. Are they still actual? It seems that instead of the `pwa` now returned `web`. Are there any cases when `pwa` still can be returned?

**Comment by jcesarmobile** [comment]
Where does it says that platform can be pwa? we changed it to web long ago, but maybe we missed it somewhere.

But yeah, instead of string we should return an enum or similar

**Comment by ArmorDarks** [comment]
I didn't encounter `pwa` anywhere in the codebase, but since there was no single source of truth and sometimes it is especially hard to say where some variables in Capacitor comes from, I decided to reask, just in case it still used anywhere.

So, that the full list of current platforms?

- `android`
- `ios`
- `electron`
- `web` (previusly `pwa`)

**Comment by jcesarmobile** [comment]
On Android it can return `amazon-fireos` if in an Amazon device, but not sure if we should do that as it will make people checking for platforms a bit confused when they expect it to be Android, but it isn't.

**Comment by ArmorDarks** [comment]
Tough question. I think it worth to understand precisely what we want to say.

Current `platform` is a bit confusing. When you launch web-app in a browser on Android device, one might say that he would expect to see `platform: 'android'` (since, well, it runs on Android), while actually, it will be `web`.

I'm starting to think that maybe wether app running within Capacitor or as a plain web application shouldn't be expressed in `platform` at all.

That might help on making a decision whether `amazon-fireos` worth throwing to the enum of `platform`.

**Comment by jcesarmobile** [comment]
Platform refers to the capacitor platform, so when run as PWA from any browser it will return web. We can probably add a new property called OS where we could return the device OS, on iOS and Android will match the platform, but on electron and web might be useful to know the operating system in some cases.

I've removed fireos here https://github.com/ionic-team/capacitor/pull/1429
And on #1432 will limit the possible platform values to 'ios', 'android', 'electron' or 'web'.
