### ISSUE TITLE
Interface error when getting the value of the areEnabled method from the localNotifications plugin

### ISSUE THREAD

**Issue by JhonArlex** [ionic-team/capacitor#1182]
When a permissions check is done, it is in the documentation and in the implementation in the code or it mentions that returns a data type LocalNotificationEnabledResult, but when checking the result, this returns is another type of data so it gives error in the typescript of ionic The result it gives is the following:
{
       areEnabled: true
}

**Comment by jcesarmobile** [comment]
Yeah, sorry about that, I first used areEnabled and then changed it to value and looks like I forgot to change it on Android.
