### ISSUE TITLE
Capacitor trimming error stack and its details

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#1186]
Looks like a capacitor is trimming error information.

In attached screenshot capacitor is getting all information but by the time it reaches sentry raven most of the error information is lost.

<img width="1222" alt="screenshot 2019-01-31 at 11 07 19 am" src="https://user-images.githubusercontent.com/8480351/52032814-9b9ad780-2548-11e9-80e9-7110327507b2.png">

On the website it works good where app is not running inside capacitor.

**Comment by jcesarmobile** [comment]
We removed the error popup, not sure it that could have fixed this issue.
Can you please check again?
If not, could you provide some sample project where it can be reproduced? I'm not really familiar with sentry raven

**Comment by jcesarmobile** [comment]
Closing as there was no response after a reasonable amount of time
