### ISSUE TITLE
Add feature to hide splash in root of Capacitor code?

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#119]
Want to avoid cases where the app loads quickly but the developer isn't explicitly hiding the splash.

Though this might be too difficult or presumptuous

**Comment by janpio** [comment]
#285 adds a feature to at least notify the user when the "hide after x seconds" functionality of the standard SplashScreen triggers, thus making it more discoverable to developers that they should manually hide it when their app is ready.

**Comment by jcesarmobile** [comment]
I think we are good with janpio's change, it's the use who should hide the splash, we can't know for sure when the app internals have finished with all they want to do, but as we warn, they are aware of it and should take action.
