### ISSUE TITLE
Filesystem does not have web implementation

### ISSUE THREAD

**Issue by garyfawcett** [ionic-team/capacitor#1191]
After following the example here:
https://capacitor.ionicframework.com/docs/apis/filesystem
I get the error:
ERROR [home-home-module.js:1816] Filesystem does not have web implementation.
This happens both in the browser and when running via Android Studio.

**Comment by jcesarmobile** [comment]
Please, provide a sample app as I can't reproduce when running from Android Studio.

In the browser it happens because Filesystem doesn't have web implementation.

**Comment by garyfawcett** [comment]
I managed to get this working by deleting the android folder in my project and then re-running the command:
npx cap add android
Then reopening with:
npx cap open android
So part of my problem was the android folder was not being updated with the changes I was making even after running the command:
npx cap copy android

**Comment by jcesarmobile** [comment]
Looks like this issue then
https://github.com/ionic-team/capacitor/issues/1005

But I’ve created hundreds of project and never faced this issue, so it’s going to be hard to fix it if I can’t reproduce.

**Comment by zajcman** [comment]
i have got the same problem. I update my code but after **npx cap copy** or ** npx cap sync** i have old code in my android studio: 

VSCode ( new code) 
![image](https://user-images.githubusercontent.com/15013936/54583675-324a2780-4a15-11e9-9262-9f4997902941.png)

Android Studio( after sync - OLD CODE!!! )

![image](https://user-images.githubusercontent.com/15013936/54583702-4beb6f00-4a15-11e9-9155-26eb49c389f4.png)
