### ISSUE TITLE
I am not able to differ background push notification from foreground push notification

### ISSUE THREAD

**Issue by mateusduraes** [ionic-team/capacitor#1192]
Hello.

I have the plugin implementation just like the following.

```typescript
PushNotifications.register();

PushNotifications.addListener('registration', (token: PushNotificationToken) => {
  // registering token on my backend
});

PushNotifications.addListener('registrationError', (error: any) => {
  console.log('error on register ', JSON.stringify(error));
});

PushNotifications.addListener('pushNotificationReceived', (notification: PushNotification) => {
  // receive push notification (opened application)
  console.log('notification', notification.data);
});

PushNotifications.addListener('pushNotificationActionPerformed', (notification: PushNotificationActionPerformed) => {
  // never called
  console.log('notification action performed', notification);
});
```

When i receive the push notification with the app opened (foreground), my console.log is executed as expected.
But, if the app is closed, when i tap the notification, the app become open, but none of ther listeners are fired.

Am i doing something wrong?

**Comment by LucasPMM** [comment]
I am having the same problem.

**Comment by mateusduraes** [comment]
Oh yes, i am sorry. Im using the exact same versions.

**Comment by mateusduraes** [comment]
I believe it is related to https://github.com/ionic-team/capacitor/issues/1178

**Comment by jcesarmobile** [comment]
should be fixed in beta 22

**Comment by LucasPMM** [comment]
Was solved? I don't think so..

**Comment by FinnBossen** [comment]
@oliverandersencox @gusmarra 
Have you solved the Problem I have the same Issue. Would be nice if you have a Solution

**Comment by oliverandersencox** [comment]
@FinnBossen yes. If you add this to your capacitor config file:

`"plugins": {
  "PushNotifications": {
    "presentationOptions": ["badge", "sound", "alert"]
  }
}`

then remove the options you wish to have disabled for foreground notifications. 

https://capacitor.ionicframework.com/docs/apis/push-notifications

**Comment by gusmarra** [comment]
@FinnBossen the only thing I had to do was to update the capacitor version. I was not using the last version and it did not support this.
