### ISSUE TITLE
`ionic capacitor add ios` add `@capacitor/cli` to dependencies and not devDependencies

### ISSUE THREAD

**Issue by timowolf** [ionic-team/capacitor#1194]
The `@capacitor/cli` should be added to the devDependencies and not to the dependencies.

**Comment by jcesarmobile** [comment]
You should probably report that in ionic repo as you are using ionic command

**Comment by timowolf** [comment]
Done at https://github.com/ionic-team/ionic/issues/17393

Thanks for the quick feedback and sorry for my mistake.

**Comment by jcesarmobile** [comment]
No problem, I tried to move it but couldn't find how.
