### ISSUE TITLE
 file-transfer cordova plugin is not working on Android

### ISSUE THREAD

**Issue by ryaa** [ionic-team/capacitor#1199]
Description of the problem:
Downloading a file in the Ionic 4/Capacitor application with  file-transfer cordova plugin is not working on Android. It works fine on iOS but immediately fails with 401 error on Android. I tried to debug it in Android Studio and it looks like this plugin methods are not even hit..

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
ionic info output

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (4 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/alexryltsov/Library/Android/sdk/)
   NodeJS            : v10.14.2 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

Capacitor version:
see above

node version:
see above

npm version:
see above

CocoaPods version:
1.5.3

Steps to reproduce:
download any file from valid link (having HTTPS!) using file-transfer cordova plugin fails with 401 error

Link to sample project:
N/A

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by ryaa** [comment]
> Can you provide a sample app?
OK. I will try to create it.
Question - what is the best way to share it?

**Comment by jcesarmobile** [comment]
Best way is a github repository

**Comment by ryaa** [comment]
Here is the repo https://github.com/ryaa/File-transfer-cordova-plugin-not-working-with-capacitor-and-Ionic-4

Please note that debugging works in this project that I created from scratch. Not sure why it does not work in my Ionic 4/Capacitor project.
Based on some debugging I think the problem could be related to whitelisting. The file-transfer cordova plugin requires whitelist cordova plugin (see https://github.com/apache/cordova-plugin-whitelist) to be installed. Besides this, in a cordova based project there are some configuration in config.xml. For example <access origin="*" />

I'm not sure how to enable whitelisting in a capacitor based Ionic project.

**Comment by jcesarmobile** [comment]
Thanks for looking into it.
In `res/xml/` there is a config.xml, if you manually add the `<access origin="*" />` there, does it work?
If so I'll just add it to the generated config.xml.

**Comment by ryaa** [comment]
It seems to fix the problem :) At least it works in my sample repo.
Thank you very much for very prompt response and help!

Not sure if these details should be added somewhere into capacitor documentation to others.

**Comment by jcesarmobile** [comment]
That file is regenerated, so it’s not recommended to write there. I’ll change it so it adds that by default. Will reopen this until fixed

**Comment by Bktechmasala** [comment]
capacitor share plugin fully worked prooved see video solved your problem https://youtu.be/5ulM4jedpB0

**Comment by aacassandra** [comment]
hi developers, it's the end of 2020. and the problem is still there, i am using ionic 5 and vue js (capacitor). there is a fix for this?
@tavosansal @jcesarmobile

**Comment by aacassandra** [comment]
seems to have worked with installing cordova-plugin-whitelist. thanks @tavosansal

**Comment by richrichDev** [comment]
> seems to have worked with installing cordova-plugin-whitelist. thanks @tavosansal

Plugin doesn't support this project's cordova-android version. cordova-android: 10.1.1, failed version requirement: >=4.0.0 <10.0.0
Skipping 'cordova-plugin-whitelist' for android

any solution ?
