### ISSUE TITLE
Error compiling signed APK

### ISSUE THREAD

**Issue by thekalkulator** [ionic-team/capacitor#1202]
**Description of the problem:**
As I compile a signed release APK I get errors (signed debug works fine). It says MissingDefaultResource: Missing Default (referring to 10 splash.png files, see pictures bellow). I fix this error with: 

android {
    lintOptions {
        abortOnError false
    }
}

**Affected platform**
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

**OS of the development machine**
- [ ] Windows
- [X] macOS
- [ ] linux

**Capacitor version:**
TRUE

**node version:**
v10.15.0

**npm version:**
6.7.0

**Pictures:**
![err1](https://user-images.githubusercontent.com/36248431/52389252-ac5eb800-2a36-11e9-8215-dc99ff52d9c6.png)
![error0](https://user-images.githubusercontent.com/36248431/52389270-b97ba700-2a36-11e9-8c60-f0ad8ba47bc3.png)

**Comment by stefanhuber** [comment]
I have the same problem. A easy workaround is to just create a png with name `splash.png` inside the drawable folder.

**Comment by rahadur** [comment]
@stefanhuber I had this problem and worked around it by adding

```gradle
lintOptions { 

    checkReleaseBuilds false

}
```
to my build.grade file within the android{ } section.

**Comment by thekalkulator** [comment]
> I have the same problem. A easy workaround is to just create a png with name `splash.png` inside the drawable folder.



> @stefanhuber I had this problem and worked around it by adding
> 
> ```groovy-gradle
> lintOptions { 
> 
>     checkReleaseBuilds false
> 
> }
> ```
> 
> to my build.grade file within the android{ } section.

Yes, this worked for me too... I added this to the build.gradle (Module: app) because my project has at least four build.gradle files. I am glad yours is working.

**Comment by thekalkulator** [comment]
> I have the same problem. A easy workaround is to just create a png with name `splash.png` inside the drawable folder.

@stefanhuber what size splash.png image did you place within the drawable folder?
