### ISSUE TITLE
Doc Site Not Working ! (https://capacitor.ionicframework.com/ )

### ISSUE THREAD

**Issue by mesutcakir** [ionic-team/capacitor#1208]
Your sites not working. https://capacitor.ionicframework.com/ 

Problem definition in the gif url.

https://i.hizliresim.com/4jpmqQ.gif

**Comment by jcesarmobile** [comment]
I can see it fine, can you check again?

**Comment by jcesarmobile** [comment]
I've tried multiple times in different browsers and devices and didn't find any problem, so going to close, might have been something temporary.
