### ISSUE TITLE
npx cap init fails: compilation terminated

### ISSUE THREAD

**Issue by poef** [ionic-team/capacitor#1212]
Description of the problem:
Following the getting started guide I did this:
> mkdir capacitor
> cd capacitor
> npm install --save @capacitor/core @capacitor/cli
> npx cap init

The result:
```
../src/binding.cc:4:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
make: *** [Release/obj.target/cap/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.7.0-0.bpo.1-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/auke/.npm/_npx/19093/lib/node_modules/cap
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cap@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

OS of the development machine
- [x] linux

node version:
v8.9.4

npm version:
5.6.0

**Comment by Erudition** [comment]
I have the same issue.
npm -v: 6.9.0
node -v: v10.15.0

**Comment by Erudition** [comment]
**Phew!**

Tried a ton of things, the on that finally got npx to "see it" was using this:
`npx @capacitor/cli init`

**Comment by jcesarmobile** [comment]
Looks like a node-gyp issue.
I've tried today on a VM with CentOS, and node 11 installed with nvm and didn't have any problem.

Will close for now, if a lot more people face this we might need to add some workaround to the docs.

**Comment by LuisJoseSanchez** [comment]
I have exactly the same problem in my Linux.
I created a brand new project in Ionic and install maps with `npm install @capacitor/google-maps`. Then typed `npx cap sync` and got the error.
