### ISSUE TITLE
[camera] IOS camera display issue (PWA in homescreen)

### ISSUE THREAD

**Issue by koshkakosh** [ionic-team/capacitor#1215]
Hello,
I have a display problem when launching the camera on an ionic 4 / angular / pwa app when the app is launched from the IOS home screen.
This is a black background without the image of the camera. But this problem does not occur when the app is launched directly from the safari explorer.
I specify that this occurs while the app is hosted on a secure server on firebase ... I specify this because this question was raised in an old post : https://github.com/ionic-team/capacitor/issues/539#issue-322708798

Debugging (thanks to macOs safari connected to the ios device) shows an error in this file :
'https://unpkg.com/@ionic/pwa-elements@1.0.1/dist/ionicpwaelements/vdhd0mud.entry.js' 
line 81 :  await this.queryDevices()

> [Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.enumerateDevices')
> 	(fonction anonyme) (vdhd0mud.entry.js:81)
> 	asyncFunctionResume
> 	(fonction anonyme)
> 	promiseReactionJob

![img_0721](https://user-images.githubusercontent.com/41581576/52525078-bc3bfd80-2cbd-11e9-97bc-5e9e81f18d9d.JPG)

Affected platform
- [x] iOS

OS of the development machine
- [x] macOS 10.14.2

Other information:
"@ionic/angular": "4.0.0",
"@angular/core": "^7.2.2",
"@angular/pwa": "^0.13.1",

Capacitor version:
1.0.0-beta.17

node version:
v10.15.0
npm version:
6.7.0

Steps to reproduce:
My code :
1/page.ts

  async uploadPicture(): Promise<void> {
  const { Camera } = Plugins;
  const pic = await Camera.getPhoto({
    quality: 90,
    allowEditing: true,
    resultType: CameraResultType.Base64,
    source: CameraSource.Prompt
  });
  this.avatar.takePic(pic.base64Data);
  }

2/ avatar.service.ts
... upload function to firebase...

**Comment by jcesarmobile** [comment]
It uses getUserMedia, which is not available on iOS when on PWA mode. But we should probably return some error instead of the black screen

**Comment by jcesarmobile** [comment]
Closing as should be fixed in ionic Oda elements, created the issue there 
https://github.com/ionic-team/ionic-pwa-elements/issues/14

**Comment by irux** [comment]
now this works! but I am having a problem with it. The camera sometimes freeze and when I press the button to take a picture it doesn't do anything. Some ideas ?

**Comment by zsyphon** [comment]
@irux Have you found a solution to the camera freeze issue? I am experiencing the same behavior.
