### ISSUE TITLE
Capacitor/CapacitorCordova beta.17 has older version on npmjs

### ISSUE THREAD

**Issue by sergiog90** [ionic-team/capacitor#1218]
Description of the problem:
When I use beta.17 on iOS it installs beta.16 from npmjs for Capacitor and CapacitorCordova.
URL: https://registry.npmjs.org/@capacitor/ios/-/ios-1.0.0-beta.17.tgz
Capacitor.podspec and CapacitorCordova.podspec has beta.16 as version.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0-beta.17

node version: v11.4.0

npm version: 6.5.0

CocoaPods version: 1.5.3

Steps to reproduce: Use ""@capacitor/ios": "^1.0.0-beta.17"" on your package.json.

Link to sample project:

**Comment by jcesarmobile** [comment]
This is a bug on the release script that bumps the version after the npm publish. I think it was already reported, but can’t find the issue, so I’ll keep this one
