### ISSUE TITLE
Push Notification issues

### ISSUE THREAD

**Issue by pegler** [ionic-team/capacitor#1221]
While trying to implement push notifications I have encountered quite a few bugs and inconsistencies across platforms. I want to recap the different scenarios here along with the issues I've encountered.

Maybe I am approaching some of these scenarios incorrectly and there is a different way of handling it. I'm happy to work on pull requests for anything that is deemed a bug. I am fairly new to Capacitor so I will need some guidance and feedback on the changes.

### App in foreground

The PushNotification.pushNotificationReceived event is correctly sent.

Issues:
 - The alert is always shown. https://github.com/ionic-team/capacitor/pull/1201/commits/72ad0c52f7b38da1f39d7f2d5fe704b88026a6a5
 - The data from the notification is not passed to the listener via the PushNotification object: https://github.com/ionic-team/capacitor/pull/1201

### App in background and notification tapped

The PushNotification.pushNotificationActionPerformed event is correctly sent.

Issues:
 - The data from the notification is not passed to the listener via the PushNotification object: https://github.com/ionic-team/capacitor/pull/1201

### App closed and notification tapped

Issues:
 - The PushNotification.pushNotificationActionPerformed event is sent before the listeners can be added: https://github.com/ionic-team/capacitor/pull/1220

### App in foreground

The PushNotification.pushNotificationReceived event is correctly sent.

Issues:
 - Notification title and body are not passed via the PushNotification object: https://github.com/ionic-team/capacitor/pull/1201

### App in background and notification tapped

The app is opened but I do not see a way of detecting this scenario.

Issues:
 - PushNotifications.pushNotificationActionPerformed event is not sent. While debugging, it looks like the LocalNotifications.localNotificationActionPerformed event is sent when the push notification is tapped.

### App closed and notification tapped

The app is opened but I do not see a way of detecting this scenario.

Issues:
 - PushNotifications.pushNotificationActionPerformed event is not sent. Unlike scenario above, LocalNotifications.localNotificationActionPerformed does not appear to be sent.

---

Affected platform
- [x] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Capacitor version:
1.0.0. beta 17

**Comment by solojuve1897** [comment]
Good report. All Android-specific I also have encountered.

**Comment by denisroldan** [comment]
Waiting for this to be fixed too. Thanks for reporting!

**Comment by pegler** [comment]
@jcesarmobile I'd like to take on the issues with Android not sending PushNotification.pushNotificationActionPerformed events next. As mentioned in my first comment, LocalNotifications.localNotificationActionPerformed does seem to be sent when a push notification is tapped and the app is in the background. I believe this originates from [LocalNotifications.handleOnNewIntent](https://github.com/ionic-team/capacitor/blob/bc112478a40ae53153b415e148b079558310d7af/android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java#L45), where [LocalNotificationManager.handleNotificationActionPerformed](https://github.com/ionic-team/capacitor/blob/bc112478a40ae53153b415e148b079558310d7af/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java#L58) returns null due to it in fact being a Push Notification and not a Local Notification. The code currently checks for `LocalNotificationManager.NOTIFICATION_INTENT_KEY` within the intent's data and it appears this is not set for push notifications, which may be a good way of differentiating local from push notifications. If this is the case I think we can easily differentiate local from push notifications and send the correct event (pushNotificationActionPerformed vs localNotificationActionPerformed).

When the app is a closed and a push notification is tapped, it appears the notification's data is attached to the app's launch intent as the extras. This is identical to the intent when the app is in the background. The difference is that when the app is in the background handleOnNewIntent is called, while when the app is closed handleOnNewIntent is not called. This seems to make sense since handleOnNewIntent is only called when there's a new intent.

I'm not sure simply checking for the lack of `LocalNotificationManager.NOTIFICATION_INTENT_KEY` in the Intent's data is enough to know a push notification was tapped. It very may be that the app was opened normally from the launcher or from a URL.

Do you have any thoughts on this one?

**Comment by dm-AS** [comment]
Yeah.. reported a part of these issues some time before in #1178 and there is another one #1181. 
I use the ionic-native plugin for iOS to avoid most of the bugs (except [this one](https://github.com/katzer/cordova-plugin-local-notifications/issues/1541)).

Has anybody had the issue where no local notification was shown after a restart?

**Comment by solojuve1897** [comment]
@pegler Must ask. Have you managed to clear the bagde on iOS? Calling capacitors removeAllDeliveredNotifications didn't do it. It did clear the notifications from the notification center though.

**Comment by jurepurgar** [comment]
@pegler I think we can differentiate push from local like this: #1313

**Comment by pegler** [comment]
@jurepurgar I believe that will do what we need for Android push notifs. Relying on the presence of "google.message_id" seems a bit messy but I don't think there's any other way to determine if the app was launched from a tap.

**Comment by jurepurgar** [comment]
This can probably be closed since #1349 and #1347 are merged.

**Comment by pegler** [comment]
It does look like those two pulls fix the remaining issues here. I haven't tested them personally yet, but the code looks good. I'll close this and reopen if I encounter any issues.
