### ISSUE TITLE
Preserving aspect ratio of splash screen on Android

### ISSUE THREAD

**Issue by rj33** [ionic-team/capacitor#1222]
Description of the problem:

A few months ago there was a change to Splash.java to change the scaleType from CENTER_CROP to FIT_XY. This appear to have fixed the issue mentioned here:
https://github.com/ionic-team/capacitor/issues/226

However as mentioned later by @sbannigan, this still breaks the aspect ratio on some devices/setups. I'm using what I thought would have been a set of standard image sizes produced by an online splash generator, but it seems on the device I'm testing on (LG K8) the aspect ratio is off, so FIT_XY doesn't preserve the aspect ratio.  Changing FIT_XY back to CENTER_CROP fixed my distorted splash image too. 

Note that the existing launch_splash.xml is also using centerCrop:
```<?xml version="1.0" encoding="utf-8"?>
<bitmap xmlns:android="http://schemas.android.com/apk/res/android"
    android:src="@drawable/splash"
    android:scaleType="centerCrop"
    />
```

Although I'm not sure where launch_splash.xml is getting referenced from because
styles.xml references drawable/splash, and I'm not sure if that hooks up with launch_splash.xml or just the raw drawable image. I suspect it is only using the raw image, and not the center cropped version from launch_xml as changing anything inside launch_splash.xml didn't seem to change the preview image shown by clicking on activity_main.xml, or the actual behaviour of the installed app, so I think it might not be used right now (there seems to be two displays of the splash, one very quick one before it is handed over to the webview, so perhaps one of the two is using launch_splash.xml already in a spot I didn't find).

The relevant section of styles.xml currently reads:
```
<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">@drawable/splash</item>
 </style>
```
If you change drawable/splash to drawable/launch_splash it seems to start to take notice of
changes in the launch_splash.xml file rather than referencing the raw images.

I ended up testing with something like this for my own launch_splash.xml
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
<item
    android:drawable="@android:color/black"
    android:gravity="fill" />

<item
    android:drawable="@drawable/splash"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerInside"
    android:gravity="center"/>

</layer-list>
```

As this handles filling in the space around the centered image with my background colour should it not be a perfect fit. With that file and Splash.java reverted back to CENTER_CROP

it seems CENTER_CROP is a safer choice for Splash.java as it is designed to be aspect ratio preserving whereas FIT_XY is explicitly not.  If the drawable has a version with the correct size for the orientation/screen size then CENTER_CROP and FIT_XY should be equivalent I suppose, but if there isn't a perfect match, FIT_XY is probably going to always do the wrong thing, whereas CENTER_CROP has a better chance of not producing a distorted image. 

Affected platform
- [ x ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ x] macOS
- [ ] linux

Capacitor version:
beta.17

**Comment by jcesarmobile** [comment]
The scaleType can now be configured https://github.com/ionic-team/capacitor/pull/1246

So users can choose based on their images, is that enough to close this?

**Comment by rj33** [comment]
Yes I think so. Thanks for the configurability close.

**Comment by maxbechtold** [comment]
Just a heads up, the pull request #1246 was adopted with changes, the proper configuration key is as follows:
```"androidScaleType": "CENTER_CROP"```  (or any other of the [ImageView ScaleTypes](https://developer.android.com/reference/android/widget/ImageView.ScaleType))
