### ISSUE TITLE
Feature Request: Screen Sharing Support 

### ISSUE THREAD

**Issue by mytee306** [ionic-team/capacitor#1224]
I realize that screen sharing on the web has it's limitations, however it would be a very useful feature. Pray list anything else that might pose as an obstacle.

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/12. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
