### ISSUE TITLE
Gradle repositories hard coded in a generated gradle file

### ISSUE THREAD

**Issue by nerdic-coder** [ionic-team/capacitor#1225]
Description of the problem:
I would like to override the repositories in: capacitor/capacitor-cordova-android-plugins/build.gradle
Since we are behind an enterprise firewall, we need to download everything from our internal Nexus, but this file is making gradle trying to download dependencies from the real JCenter and that's not possible in our companies network.

Affected platform
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

Capacitor version:
beta-17

node version:
node -v
v10.13.0

npm version:
npm -v
6.7.0

CocoaPods version:
pod --version
1.5.3

Steps to reproduce:
1. Be behind a company firewall
2. Try to build Capacitor Android APK file.

Link to sample project:
Internal

**Comment by jcesarmobile** [comment]
Does it work if you change them in the Android build.gradle (the one that appears as build.gradle (Project: Android).
I think the changes you make there should affect all modules.

**Comment by nerdic-coder** [comment]
Don't seem to help, we have it like this and it still tries to download from the external Jcenter
`repositories {
        google()
        maven {
            url "https://nexus.mycompany.com/content/repositories/bintray-jcenter/"
        }
        jcenter {
            url "https://nexus.mycompany.com/content/repositories/bintray-jcenter/"
        }
    }`

and this I have tried to add to all repositories list that I have found in gradle files that is not auto generated.

**Comment by jcesarmobile** [comment]
there are two entries, the `buildscript` and the `allprojects`, in which one are you doing it?

**Comment by nerdic-coder** [comment]
Both

**Comment by jcesarmobile** [comment]
`capacitor-cordova-android-plugins/build.gradle` is just for Cordova plugins, how were you doing it in Cordova?

**Comment by nerdic-coder** [comment]
When we used cordova we had an ugly work around where we made copies of the gradle files and added the repositories as we wanted them in the copies and then copied over the generated once at build time.
Could probably do the same here, but don't feel like having that as the final solution.

**Comment by nerdic-coder** [comment]
I installed a few certificates in the java cacerts so now it works. Closing issue.

**Comment by caspergreen** [comment]
How did you solve this?

We want to use Artifactory, but because the repositories are hardcoded in `capacitor-cordova-android-plugins` and in Capacitor Android Runtime project, we cannot seem to control it.

Do you have any suggestions how to make it work? Currently we tried a workaround where we add the generated projects to Git and change the `build.gradle` files, but surely this cannot be the intended way to make it work

**Comment by mattdsteele** [comment]
Are there any new approaches to get custom repositories working with Cordova plugins, or even a possible workaround? It appears, `capacitor-cordova-android-plugins/build.gradle` still includes [hardcoded references to `jcenter()` and `google()`](https://github.com/ionic-team/capacitor/blob/main/capacitor-cordova-android-plugins/build.gradle#L6), which will get overridden if you run `cap sync`.

We're hoping to migrate some of our Cordova apps to Capacitor, but this is a pretty hard blocker, so any suggestions would be helpful.

@mlynch would the Capacitor Configure tool be of any help here? Are there any supported ways to modify Gradle files and preserve the changes?
