### ISSUE TITLE
[Android] Kotlin for app & plugin & capacitor codebase?

### ISSUE THREAD

**Issue by NemoOudeis** [ionic-team/capacitor#1227]
Hi guys, 

I've been browsing the capacitor source code and was wondering if you are open to modernizing & cleaning up the android codebase and plugin/app templates that are generated by `npx @capacitor/cli plugin:generate`, `npx @capacitor/cli create` and `npx cap init`. 
I'm thinking: more recent Android gradle plugin, less unused boiler plate (that android studio project templates create, e.g. local jar dependencies, test dependencies on unused libraries, unused proguard files etc.), kotlin & androidx setup by default, app/plugin code generated in Kotlin.

If you are open to this I could contribute a pull request with what i have in mind and we can continue discussion based on that. If not - no hard feelings 😉 

Cheers
Nemo

**Comment by jcesarmobile** [comment]
Sure, we are open, but please, if you do it don’t do it all at once, better send small PRs that can be easily reviewed and tested as I don’t have experience with Kotlin

**Comment by untilbit** [comment]
@jcesarmobile You can request help from other mamber that have more experience working with Kotlin

**Comment by NemoOudeis** [comment]
Yes I would definitely split up the work, we may need to discuss the changes based on small scope PRs. Will give it a shot next week 👍

**Comment by jcesarmobile** [comment]
Closing as it was more a question about if we were open to the changes, and not a real issue.

**Comment by fkirc** [comment]
Are you still planning to convert Capacitor-Android to Kotlin, or open to accept PRs?

This would be especially important for the embedded use case; because Kotlin is now the primary language for native Android apps.

**Comment by dwieeb** [comment]
My understanding is by using Kotlin in Capacitor Android, we'd be adding the Kotlin dependency to every app. I don't see this as something we want to attempt to figure out for Capacitor 3, but perhaps a later major version. 

Can you elaborate on why it's important for embedded? Kotlin should interop with Java quite well.

**Comment by fkirc** [comment]
I agree that this is a major change and therefore too soon for Capacitor 3 (but I hope that Capacitor 4 is doable).

Kotlin interops well with Java, but the native Android community is more and more moving towards "Kotlin first". 
To keep up with the Android world, the question is not if, but when the move should be made. 
It already starts with the template app: If the template app is written in Kotlin, then it is faster to get up to speed with a decent Android setup.

Moreover, if done right, Kotlin could improve the quality of the Android code (for example, preventing random NullpointerExceptions like https://github.com/ionic-team/capacitor/pull/3553).

**Comment by IngAjVillalon** [comment]
Definitely, Kotlin is the future of Android,
It is also very similar to Typescript, so that it will be easier for Typescript programmers to code in Kotlin.
I join the motion to integrate CapacitorJS to Kotlin.

**Comment by riderx** [comment]
any news on  that ?

**Comment by Ryubal** [comment]
It's 3 years later, any updates? Would love to see Kotlin, since it's being adopted a lot of devs by now, and it's an official Android language.
