### ISSUE TITLE
[Question] Switch between multiple app bundles?

### ISSUE THREAD

**Issue by NemoOudeis** [ionic-team/capacitor#1228]
Hi,

does capacitor support dynamically switching the web app that is served/displayed? I'm thinking of features like Microsoft Code Push (OTA updates to mobile apps without Google/Apple Store release) or using capacitor for dedicated screens as a part of native mobile apps, e.g. 

* Home screen native
* Feature 1 in capacitor (web app 1)
* Feature 2 in capacitor (web app 2)
* Feature 3 in native

You can make it work with Cordova & ReactNative, so I was wondering if that is something capacitor supports directly or via old Cordova Plugins? If yes what are the APIs to look for on the native side? 

I looked at the android code my initial impression was that a local webserver serves a hardcoded directory in the android `assets`. I didn't see a way to inject a different location/content resolver.

Thank you 🙏

**Comment by jcesarmobile** [comment]
You can do it with the webview plugin methods, setServerBasePath, persistServerBasePath, that will tell the app which folder contains the files it should use. But it’s broken on iOS at the moment. See 
https://github.com/ionic-team/capacitor/issues/638 for progress.

It has to be done with those methods, most Cordova plugins will just redirect to a file path and that’s not supported nor will be.

**Comment by NemoOudeis** [comment]
@jcesarmobile thanks for your reply.
I found the WebView Plugin in source ([android](https://github.com/ionic-team/capacitor/blob/5a23f598fe15d99ab3a925a2f5e15f21a96fa5a6/android/capacitor/src/main/java/com/getcapacitor/plugin/WebView.java) [ios](https://github.com/ionic-team/capacitor/blob/5a23f598fe15d99ab3a925a2f5e15f21a96fa5a6/ios/Capacitor/Capacitor/Plugins/WebView.swift)) - but didn't find much documentation on it. Is there docs for it or should I go read the code?

**Comment by alexcroox** [comment]
@NemoOudeis did you ever get this working? With MS Codepush not supporting Capacitor yet I'm looking into rolling my own self updating process having done something similar in an Electron project years ago. Thanks.

**Comment by NemoOudeis** [comment]
@alexcroox I don't recall if I got it work in hacky ways, but I definitely did not reach a clean solution that I would use in production. That being said I did not spent that much effort on it iirc.
