### ISSUE TITLE
Background flickering black when the keyboard appears or extends

### ISSUE THREAD

**Issue by maedewiza** [ionic-team/capacitor#1230]
**Description of the problem:**
Background flickering black when the keyboard appears or extends, where it expands.

**Affected platform**
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

**OS of the development machine**
- [ ] Windows
- [x ] macOS
- [ ] linux

**Capacitor version:**
capacitor (Capacitor CLI) : 1.0.0-beta.17
@capacitor/core           : 1.0.0-beta.17

**node version:**
v11.10.0

**npm version:**
6.8.0

**CocoaPods version:**
1.6.0

**Comment by jcesarmobile** [comment]
This is fixed, but not released yet

**Comment by jayordway** [comment]
Has it been released yet? I am still seeing the problem.

**Comment by jcesarmobile** [comment]
Yes, should be ok on beta 19, released last week

**Comment by jayordway** [comment]
Yeah it works, thanks
