### ISSUE TITLE
Feature request: native date picker

### ISSUE THREAD

**Issue by maedewiza** [ionic-team/capacitor#1231]
iOS have UIDatePicker in UIKit and Android SDK have DatePicker in widgets. It would be nice to see support for them at Capacitor.

**Comment by rahadur** [comment]
There is already community plugins for your requirements.

https://capacitor.ionicframework.com/docs/community/plugins/

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

But as there is a 3rd party plugin for it already, it won't be a priority

**Comment by DoctorsInTech** [comment]
I agree this would be very useful as the current community date picker doesn't have web implementation. It would be nice to have a date picker that also works in the browser!

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/7. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
