### ISSUE TITLE
cordvoa  ''cordova-hot-code-push-plugin"  can't use in capacitor

### ISSUE THREAD

**Issue by ModeYapu** [ionic-team/capacitor#1239]
Executing tasks: [:app:assembleDebug]

FAILURE: Build failed with an exception.

* Where:
Script 'D:\ProjectTest\ionic\vuecapacitordemo\node_modules\cordova-hot-code-push-plugin\src\android\chcp.gradle' line: 3

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'cdvPluginPostBuildExtras' for project ':app' of type org.gradle.api.Project.

**Comment by match08** [comment]
Update to Capacitor:
https://github.com/match08/cordova-hot-code-push
npm install git+https://github.com/match08/cordova-hot-code-push.git
