### ISSUE TITLE
 https://capacitor.ionicframework.com/ Now Workinging.

### ISSUE THREAD

**Issue by mesutcakir** [ionic-team/capacitor#1241]
Description of the problem: Not working site.

![image](https://user-images.githubusercontent.com/4125460/53029001-120c6480-3479-11e9-88db-c01b4a7b87ba.png)

Similar error ionicicons solved. https://github.com/ionic-team/ionicons/issues/663#event-2149299901

From Turkey Region.

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:

node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by mesutcakir** [comment]
![image](https://user-images.githubusercontent.com/4125460/53328427-fa126600-38fa-11e9-82b8-53b99a790014.png)
He's still not showing.

**Comment by jcesarmobile** [comment]
The changes have not been deployed yet
