### ISSUE TITLE
ionic cap run electron throws error

### ISSUE THREAD

**Issue by NiklasMerz** [ionic-team/capacitor#1249]
Description of the problem:

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

Capacitor version:
beta 17
node version:
10.10
npm version:
6.7
Steps to reproduce:
`ionic cap run electron` on project with capacitor initialized for electron throws error:

```
> capacitor copy electron
⠋ Copying web assets from www to electron/appCleaning /home/niklas/Projekte/exportoo/electron/app...
Copying web assets...
✔ Copying web assets from www to electron/app in 324.87ms
✔ Copying capacitor.config.json in 531.53μp
✔ copy in 327.81ms

[INFO] Ready for use in your Native IDE!
       
       To continue, run your project on a device or emulator using Android Studio!

> capacitor open electron
[error] Platform electron is not valid.
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor open electron exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```
Probably this wants to start the native IDE for electron which is not needed. I expected it to run `npm run electron:start` in the electron folder.

**Comment by jcesarmobile** [comment]
This is an ionic bug then, can you report it in ionic repo?

**Comment by NiklasMerz** [comment]
Opened issue in ionic-cli repo https://github.com/ionic-team/ionic-cli/issues/3871
