### ISSUE TITLE
iOS can't download from MapKit JS CDN with capacitor:// prefix

### ISSUE THREAD

**Issue by EricKit** [ionic-team/capacitor#1252]
Description of the problem:

Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 2.0.0
   ios-sim    : 7.0.0
   NodeJS     : v11.6.0 (/usr/local/bin/node)
   npm        : 6.8.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

Steps to reproduce:

Build a full app with MapKit JS and try to run on iOS. When mapkit.js is downloaded, it attempts to download about 20 images from a CDN. On Safari, Chrome, and native Android it works. On iOS it fails to download. The error is:

[Error] Failed to load resource: The file “logo_3x.png” couldn’t be opened because there is no such file.

And on the network tab in Safari:

No response with:
URL: capacitor://cdn.apple-mapkit.com/mk/5.16.0/images/logos/logo_3x.png 

(replace capacitor:// with https:// and you'll get the image)

In the MapKit.js I'm not sure where it requesting the download but I found 
            cdnBase: "//cdn.apple-mapkit.com/mk",

I'm not sure if the // is being converted to capacitor:// instead of https://. I'm honestly not sure if this is an error with MapKit JS or Capacitor, but I'd love to see the two work together. MapKit still works, just can't download some of the images.

**Comment by jcesarmobile** [comment]
If they don't set a scheme then it will use the same scheme as the app uses and capacitor uses capacitor://.

Sorry, we can't fix this, they should use a scheme. Not sure if you can configure the cdnBase somehow.

**Comment by EricKit** [comment]
Apple pushed an update for anyone that finds this post. It's fixed due to a bug report with them.

**Comment by jcesarmobile** [comment]
Good to know, thanks for reporting!

**Comment by eliotfrost** [comment]
> Apple pushed an update for anyone that finds this post. It's fixed due to a bug report with them.

Interesting because I still see this same issue today. Any advice on how to address this?

**Comment by jcesarmobile** [comment]
they might have reintroduced the issue, report it again

**Comment by EricKit** [comment]
I'm not seeing any issues in my mapkit map. Is this on an iOS app?
