### ISSUE TITLE
Custom URL Scheme for Electron and PWA

### ISSUE THREAD

**Issue by dotnetdreamer** [ionic-team/capacitor#1253]
Description of the problem:

Affected platform
- [x] electron
- [x] web

OS of the development machine
- [x] Windows

Other information:
We need Custom URL scheme support for electron App just like Android and iOS.

**Comment by jcesarmobile** [comment]
You mean a scheme that opens the app or a scheme to serve the app?

**Comment by dotnetdreamer** [comment]
i have build an Ionic 4 app which i wanna run it in Electron. I have another application (WPF desktop) which will pass data to my ionic app (Electron) using Custom scheme....

**Comment by dotnetdreamer** [comment]
I tried the following but it only works if i use **custom scheme internally**. I have to modify index.js in electron app as the Capacitor implementation for core plugin 'App' isn't available on the web. I had follow [this](https://glebbahmutov.com/blog/electron-app-with-custom-protocol/) article. 

```
const PROTOCOL_PREFIX = 'mycustomscheme';
const { app, BrowserWindow, Menu, protocol } = require('electron');
  protocol.registerHttpProtocol(PROTOCOL_PREFIX, (req, cb) => {
    devToolsLog('full url to open ' + req.url)
  })
```
and then to hit the code i had to do following:
`<a href="mycustomscheme://testing">Testing</a>`

**Comment by mlynch** [comment]
Authoritative task issue #1528

**Comment by IT-MikeS** [comment]
Might be able to close this and move future issues around electron to the community org.
