### ISSUE TITLE
New project fails to build in XCode 10.1

### ISSUE THREAD

**Issue by shuppert** [ionic-team/capacitor#1258]
Description of the problem:

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0.beta.17
node version:
10.15.1
npm version:
6.4.1
CocoaPods version:
1.6.1

Steps to reproduce:
ionic start Test blank --type=angular
npm install --save @capacitor/core @capacitor/cli
npx cap init
ionic build
npx cap add ios
cd ios/App
pod update
npx cap open ios

The build will error:
ld: can't open file, errno=22 file '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.ios.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I also tried updating the Podfile.lock to beta.17 and doing another pod update but I get the same linker error.

**Comment by jcesarmobile** [comment]
Why are you doing the cd ios/App and pod update?
Can you run the npx cap open ios from the root?
Do you have Cordova plugins installed?

**Comment by shuppert** [comment]
Is there another/better way to run the pod update?
I am running npx cap open ios from the root.
The only Cordova plugins would be whatever is installed with the Ionic blank starter template.
I started working with my real app that also had the InAppBrowser plugin but I wanted to reproduce with the starter template.

**Comment by jcesarmobile** [comment]
There is no better or worse way, you just don’t have to run it.

About the error I have no idea, I’ve found multiple similar issues on different projects and no solution. Some recommend reinstalling Xcode

**Comment by shuppert** [comment]
Just for kicks I decided to try another project with the Capacitor CLI:
npx @capacitor/cli create
npx cap add ios
npx cap open ios

And I get the same linker error.  I'll try reinstalling XCode.

**Comment by shuppert** [comment]
Reinstalling XCode resolved that issue.  Now to fight the other issues.  Thanks @jcesarmobile!
