### ISSUE TITLE
Support HMR for electron apps main / renderer threads

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor#1260]
Hey folks! 

Getting my teeth into the Cap/Electron stuff lately. This is a feature request (apologies I did not find an issue template for this if there is one.)

Currently the dev workflow for Capacitor/electron apps seems like it's headed in a good direction. Things work well. That said, hot module reloading is a fairly big necessity for productivity, and would be excellent if this were supported out of the box (everything else does.)

One might argue that a PWA should not need to support HMR on native features of Electron, but if the desktop build of the app is going to integrate with the OS or display any kind of subsequent/external/child windows (which is extremely common when building any non-trivial desktop app or integration), this is a necessity.

There is already support for this in the electron ecosystem:

https://webpack.electron.build/

However, this would take some work to integrate into the existing dev workflow.

- build Ionic app
- npx cap copy
- build electron app

Possibly with static files configured to reload when the ./app/ dir changes, so you can update both the main thread and the built application/renderer at the same time. Additionally, setting up typescript in electron by default would also be a good choice in my opinion, since Ionic is fairly biased toward TS already (and that seems to be the direction the JS community is headed.)

Anyway, I think this is important :) I've rambled enough.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by jcesarmobile** [comment]
Capacitor 3 removed electron support, it's a community platform now
You can request the feature there (might be already supported)

https://github.com/capacitor-community/electron
