### ISSUE TITLE
ionic serve -c

### ISSUE THREAD

**Issue by thekalkulator** [ionic-team/capacitor#1263]
Description of the problem:
In Ionic 3 I could run the command (ionic serve -c) and log cool messages to the terminal to help with my development. In Ionic 4 this command is apparently not present. Is there a substitute?

OS of the development machine
- [ ] Windows
- [x ] macOS
- [ ] linux

**Comment by jcesarmobile** [comment]
You have opened the issue on Capacitor repository, do you think it’s related to Capacitor?

**Comment by thekalkulator** [comment]
@jcesarmobile sorry about that I'll move this issue to a different url.
