### ISSUE TITLE
Why is iOS Release build so big?

### ISSUE THREAD

**Issue by shuppert** [ionic-team/capacitor#1267]
We've been using Cordova for a long time and have a pretty good feel for how big the IPA file should be.  I was able to build both Debug and Release IPA files and the Debug is 16MB but the Release is 86MB.  Is this a side effect of Capacitor?  What are others seeing?

Thanks,
-Scott

**Comment by jcesarmobile** [comment]
See 
https://github.com/ionic-team/capacitor/issues/1036.
