### ISSUE TITLE
Electron: Cannot read property 'SplashScreen' of undefined

### ISSUE THREAD

**Issue by jvink** [ionic-team/capacitor#1268]
When running my Ionic application using `npm run electron:start`, I'm getting an error: `Cannot read property 'SplashScreen' of undefined`.

Electron app opens but is blank:
![image](https://user-images.githubusercontent.com/27773080/53404303-ac0e6880-39b5-11e9-9b8a-c75514246788.png)

Running `npx cap doctor electron` results in:
```
Dependencies:

  @capacitor/cli: 1.0.0-beta.17

  @capacitor/core: 1.0.0-beta.17

  @capacitor/android: 1.0.0-beta.17

  @capacitor/ios: 1.0.0-beta.17

  Capacitor Android: not installed

[fatal] Platform electron is not valid.

```
OS: Windows 10 Pro
Capacitor CLI: 1.0.0-beta.17
Capacitor Core: 1.0.0-beta.17

**Comment by jcesarmobile** [comment]
Read https://github.com/ionic-team/capacitor/issues/888
