### ISSUE TITLE
Image orientation on iOS

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#1269]
Description of the problem:
When uploading an image through the Camera-plugin the image is rotated. Tested on an iPad. I haven't encountered this issue on my Android-devices.

Affected platform
- [ ] Android
- [x ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x ] Windows
- [x ] macOS
- [ ] linux

Other information:

Capacitor version:
Beta 17
node version:

npm version:

CocoaPods version:

Steps to reproduce:
1. Take a picture with your iOS-device in portrait
2. Upload the image through the Camera-plugin in your app.
3. Result: the image is flipped.

Link to sample project:

**Comment by jcesarmobile** [comment]
What do you mean by “upload”? Can you provide sample code or project?

**Comment by solojuve1897** [comment]
I mean to choose the image in the library. I can provide a sample project in an hour or so if still needed.

**Comment by jcesarmobile** [comment]
Yes please, provide a sample project or at least the code you are using

**Comment by solojuve1897** [comment]
@jcesarmobile 
After creating a sample project I have come to the conclusion that the problem is on my part. I don't know exactly how, but yet it is. For some reason my backend understands the image differently depending on whether it comes from an Android or iOS-device. I have a method which converts the image from base64 to a Blob. I then send the blob to the backend (on the backend I simply save the blob as a file on the server). My best guess is that the problem occurs during the conversion, i.e. the following method. Maybe I should rethink this all together.

```
base64toBlob (base64) {
      let byteString
      let mimestring
      if (base64.split(',')[0].indexOf('base64') !== -1) {
        byteString = atob(base64.split(',')[1])
      } else {
        byteString = decodeURI(base64.split(',')[1])
      }
      mimestring = base64.split(',')[0].split(':')[1].split(';')[0]
      let content = []
      for (var i = 0; i < byteString.length; i++) {
        content[i] = byteString.charCodeAt(i)
      }
      return new Blob([new Uint8Array(content)], { type: mimestring })
    }
```

Don't know if you have any idea regarding how this is possible?

**Comment by jcesarmobile** [comment]
are you using correctOrientation option? the docs say it's true as default, but just checked iOS code and it's false, while it's true on Android, so that might be the problem

**Comment by solojuve1897** [comment]
I don't use it. But I actually played around with it by putting it to false to see if that fixes the problem but then also images from Android encountered the same issue. If I want it to be true for both should I explicitly set it to true?

**Comment by jcesarmobile** [comment]
Set, set it to true and if it works.

But I'll change the default anyway as docs say default is true.

**Comment by solojuve1897** [comment]
That fixed it. What a relief!

Thanx for the help.

**Comment by jcesarmobile** [comment]
reopened to use it as related issue for changing the default

**Comment by rgolea** [comment]
This issue is not entirely fixed. I am locking my device in portrait with this package https://ionicframework.com/docs/native/device-orientation and I am setting `{correctOrientation: true}`. However, if I take it in portrait mode, it rotates it 90º counter-clockwise. If I, however take it in landscape, it gets rotated 180º. Any ideas?

**Comment by gokulgdas007** [comment]
Hi @solojuve1897 where to set the correct orientation true, can u provide a sample code of that

**Comment by solojuve1897** [comment]
> Hi @solojuve1897 where to set the correct orientation true, can you provide a sample code of that

```
import { Plugins, CameraResultType, CameraSource } from '@capacitor/core'
const { Camera } = Plugins

const uploadedImage = await Camera.getPhoto({
        quality: 60,
        allowEditing: false,
        correctOrientation: true,
        resultType: CameraResultType.Base64,
        source: cameraSource === 'photos' ? CameraSource.Photos : CameraSource.Camera
      })
```

**Comment by gokulgdas007** [comment]
@solojuve1897 This solved the issue in mobile app, i used a file transfer in web app for that after the base64 encoding the image orientation is changing. Is there any option to set the correct orientation in web also.There i am not using cordova camera plugin instead of that am using input type file.

**Comment by solojuve1897** [comment]
> @solojuve1897 This solved the issue in mobile app, i used a file transfer in web app for that after the base64 encoding the image orientation is changing. Is there any option to set the correct orientation in web also.There i am not using cordova camera plugin instead of that am using input type file.

Sorry, can't answer that. I have only used this Capacitor plugin for the purpose of a mobile app which I created.
