### ISSUE TITLE
Support Service Worker

### ISSUE THREAD

**Issue by wspringer** [ionic-team/capacitor#1270]
It seems I can't use the Service Worker API, or at least not on iOS. Am I missing something?

This is what it shows in the XCode debugging console:

```
APP ACTIVE
⚡️  [warn] - Service workers are not supported.
⚡️  WebView loaded
```

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

**Comment by jcesarmobile** [comment]
WKWebView doesn't have service workers available https://webkit.org/blog/8090/workers-at-your-service/

**Comment by dimaip** [comment]
I'm just curious, how to you go around this? Say I want to use service worker cache to pre-cache some API requests, how would I do it with Capacitor? Emulate it with Storage/localStorage? Any better options?

**Comment by novaknole** [comment]
@jcesarmobile any answer for @dimaip 's last question?

**Comment by dminkovsky** [comment]
You can't get around it... https://dev.to/ben/will-ios-14-support-service-workers-in-wkwebview-5gn

**Comment by kainosnoema** [comment]
Apps opting into App Bound domains (https://webkit.org/blog/10882/app-bound-domains) do actually get service worker support in WKWebView. They're not advertising it broadly yet, but it's supported: https://twitter.com/othermaciej/status/1295434201865412608
