### ISSUE TITLE
How to use Firebase/Auth on ios to log in to the hosted Javascript Firebase

### ISSUE THREAD

**Issue by mwawrusch** [ionic-team/capacitor#1273]
So it seems that the use of capacitor:// as a url scheme breaks the phone authentication in when hosting firebase/auth as the recaptcha requires a http(s) scheme. Now this is not the perfect way to handle login anyways, so I am wondering if anyone can point me in the right direction how I can transfer a successful login on ios into a valid auth/user in my hosted app.

**Comment by maedewiza** [comment]
I used this https://github.com/arnesson/cordova-plugin-firebase/tree/87fe7d9a25ecda5fa80b59f4056b27a7c5a32355

**Comment by jcesarmobile** [comment]
Sorry, the issue tracker is not the proper place to ask questions, you can ask on slack https://getcapacitor.herokuapp.com/ or the forum https://forum.getcapacitor.com/

If the web sdk requires https then you'll have to use the native sdk with a plugin

**Comment by baumblatt** [comment]
Hello @mwawrusch, 

I'm in the middle of the implementation of a capacitor plugin to do that.

For awhile, just Google authentication is running in iOS (version 0.0.2)

[Capacitor Firebase Auth](https://www.npmjs.com/package/capacitor-firebase-auth)

> This is a working in progress plugins, please do not use in production mode.

Best regards,
Bernardo Baumblatt

**Comment by iaguilera14** [comment]
@mwawrusch did you ever find a solution? I’m working on the same thing.

**Comment by baumblatt** [comment]
> @mwawrusch did you ever find a solution? I’m working on the same thing.

Hi @iaguilera14 , please take a look on my plugin, is working for Google , Facebook and Twitter!

The phone authentication is working just for Android, maybe this weekend I finish the iOS version, if I'm not struggling with this Issue. Anyway, if the silent push notifications is turned on, this will not necessarily at all!

**Comment by iaguilera14** [comment]
@baumblatt  I will do that! Thanks! I wasn't sure if it was ready for production use. I will take a look.

**Comment by baumblatt** [comment]
Hi  @iaguilera14 you are right, maybe it was not ready for production use, we have plans to go for it at the end of this month.

I wondered if you could help us testing it.

Best regards,
Baumblatt

**Comment by iaguilera14** [comment]
@baumblatt I would be happy to. However we have moved this portion of the project back a ways to focus on more pressing things. I will however reach out when we pick it back up!
