### ISSUE TITLE
Status bar overlays webview on iOS

### ISSUE THREAD

**Issue by sChupin** [ionic-team/capacitor#1277]
Description of the problem:
I would like to achieve the same behavior of statusbar as in the capacitor example, i.e. automatically add the correct padding so my app content doesn't display inside the status bar.
However, I don't use the ionic framework but angular and the status bar overlays the webview of my application. Therefore, the content of my app is visible in the status bar.

I was expecting a method that allows to change this behavior (as the _ overlaysWebView_ method of ionic native status bar).
I also tried to add `<preference name="StatusBarOverlaysWebView" value="false" />` in the _config.xml_ file but I don't know if I should install the cordova statusbar plugin or not.

Maybe I shouldn't change this configuration and just play with padding, but then I don't know how to handle the different status bar height on different iOS devices.

I'm new to Capacitor and I never used Ionic nor Cordova. I someone could help me deal with this problem, I would be very grateful.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0-beta.17

node version: 9.11.1

npm version: 6.5.0

CocoaPods version: 1.6.0

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
You have to take safe areas into account, read this article to know more 
https://webkit.org/blog/7929/designing-websites-for-iphone-x/
