### ISSUE TITLE
npx cap add ios - on windows

### ISSUE THREAD

**Issue by baranelitez** [ionic-team/capacitor#1285]
Description of the problem:
'npx cap add ios' won't add ios as a platform. Prints:
[error] Not running Mac OS X, can't add ios platform

I'd like to create the project files in Windows, and use OSX for just building.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0-beta.17

node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by ffMathy** [comment]
Same here.

**Comment by rgolea** [comment]
@baranelitez @ffMathy you cannot compile nor create an iOS project on a Windows machine. You need XCode nor Cocoapods and they are available only for macOS.

**Comment by jcesarmobile** [comment]
But you can use cloud services to compile the native projects, so being able to add the iOS project from windows is a planned feature

**Comment by mlynch** [comment]
Adding to high priority as we will need to support this in Appflow

**Comment by baranelitez** [comment]
@rgolea I know of Quasar and Unity engine can create xcode projects in a windows OS. So I don’t see why it’s not possible.
