### ISSUE TITLE
No matching client found for package name 'capacitor.android.plugins'

### ISSUE THREAD

**Issue by hnassr** [ionic-team/capacitor#1286]
Description of the problem:

When i try to run app on android i get this error `No matching client found for package name 'capacitor.android.plugins'`

the problem appear after installing this package `cordova-plugin-fcm-with-dependecy-updated`

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0-beta.17

node version: v8.12.0

npm version: 6.4.1

**Comment by zakton5** [comment]
@hnassr Did you find a solution?

**Comment by hnassr** [comment]
@zakton5 no, and i currently don't care  😅

**Comment by emi-arcioni** [comment]
Hey @zakton5 , did you find any solution?

**Comment by ga27** [comment]
Same problem, someone find a solution? @florianchevallier sadly your solution don't work for me

**Comment by ujeon** [comment]
Did you solve this problem? I'm in emergency

**Comment by ga27** [comment]
> Did you solve this problem? I'm in emergency

I've switched from FCM to PushNotifications plugin in Capacitor core. It works with some bugs, but it works.

**Comment by Radecom** [comment]
I get the same problem installing cordova-plugin-fcm-with-dependency-updated with capacitor, the funny thing is that only with capacitor, since with cordova it works very well.

Does anyone know the trick to install cordova-plugin-fcm-with-dependency-updated with capacitor?
