### ISSUE TITLE
Numerous errors when building on iOS

### ISSUE THREAD

**Issue by matthiasunt** [ionic-team/capacitor#1289]
I'm getting numerous errors when I try to build my Ionic App on iOS as described in the docs.
![image](https://user-images.githubusercontent.com/17273057/53752320-9cf45280-3eae-11e9-92d0-68f312d58712.png)

What could be the issue?

**Comment by jcesarmobile** [comment]
what's your Xcode version? Capacitor version? CocoaPods version? is it a new project?

**Comment by solojuve1897** [comment]
Have you tried cleaning the build-folder and then building again? Product - > Clean Build Folder.

**Comment by matthiasunt** [comment]
I ended up removing the ios folder and adding it again. Now it works.
