### ISSUE TITLE
hot-code-push don't support

### ISSUE THREAD

**Issue by Sevenonclick** [ionic-team/capacitor#1290]
I'd like to transform my project to Capacitor, but hot-code-push is not support , or I don't know how to use it , it's too bad for developer

**Comment by solojuve1897** [comment]
The idea of being able to update the app without actually going to the appstores every time is very interesting. Are Google Play and App Store okey with this? If so then I believe this is a very valuable feature for most developers.

The cordova hot-code-push plugin is deprecated.

**Comment by solojuve1897** [comment]
"Deliver live app updates, content changes, A/B tests, bug fixes, and more—before or after your app is in the store. No lines, no waiting, no slowdowns."

Ionic Appflow:
https://ionicframework.com/appflow

No idea if or how one can connect a Capacitor-app to this.

**Comment by jcesarmobile** [comment]
Capacitor will support launching from a different folder than the public folder, it's already implemented for Android (but unreleased) and it was for iOS but got broken on a release. Plugins will have to adapt for this, setting the folder where the update was downloaded, I don't think hot-code-push works that way, so it's not going to work out of the box, they'll have to update or the developers will have to set the folder themselves if they can get the path to the folder where the update was downloaded.

**Comment by match08** [comment]
Update to Capacitor:
https://github.com/match08/cordova-hot-code-push
npm install git+https://github.com/match08/cordova-hot-code-push.git

**Comment by WizeOneR** [comment]
> Update to Capacitor:
> https://github.com/match08/cordova-hot-code-push
> npm install git+https://github.com/match08/cordova-hot-code-push.git

Please, help me. How this work with capacitor? 
I don`t understand the sequence of actions when using a capacitor.

Thank you for your answer

**Comment by match08** [comment]
> > Update to Capacitor:
> > https://github.com/match08/cordova-hot-code-push
> > npm install git+https://github.com/match08/cordova-hot-code-push.git
> 
> Please, help me. How this work with capacitor?
> I don`t understand the sequence of actions when using a capacitor.
> 
> Thank you for your answer
wiki:
https://github.com/nordnet/cordova-hot-code-push/wiki/Fetch-update
