### ISSUE TITLE
Browser addListener not working 

### ISSUE THREAD

**Issue by kogutu** [ionic-team/capacitor#1291]
Hello I have problem I test Capacitor on my App and I want run browser and use addListner to observe change url.

I have this code:
```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, ModalController } from 'ionic-angular';
import { Plugins } from '@capacitor/core';
const { Browser } = Plugins;

export class HomePage {
constructor(){

  Browser.addListener("browserFinished", (info: any) => {
    console.log(info.url);
  })
 
}
  async openWebpage(url: string) {
    await   Plugins.Browser.open({ url: 'http://capacitor.ionicframework.com/' });
}
}
```

When I pushed the button, Browser Start but addListener don't give me event with console.log.

Please tell me what is wrong.

Ionic 4.10.3 but project is created on ionic 3
Cordova 8.1.2 (cordova-lib@8.1.1)

**Comment by jcesarmobile** [comment]
Is this on iOS? Android? browser?

**Comment by kogutu** [comment]
On android

śr., 6.03.2019, 16:21 użytkownik jcesarmobile <notifications@github.com>
napisał:

**Comment by jcesarmobile** [comment]
You can't observe the url change in Browser plugin
I've added browserPageLoaded implementation for Android, but it only tells you it finished loading, not the url. https://github.com/ionic-team/capacitor/pull/1293
browserFinished is for when you close the browser, not for when the navigation finishes, but it's not possible to know on Android, so going to close the issue.

**Comment by nourkrimesh** [comment]
Hello Ionic Team,

Browser Plugin with event browserPageLoaded doesn't give the url or info about the page has been loaded.

How to check if a specific route has been loaded?

I use this to check if the user finished payment and it redirected to a specific success page so then I close the browser.

It was working in cordova plugin "In App Browser".

Should I user the cordova "In App Browser" plugin instead??

**Comment by challamzinniagroup** [comment]
I am having an issue where the listeners are not firing. I have tried both the "browserFinished" and the "browserPageLoaded" events, and in neither case does my handler get called.
I am running this under electron.
I am happy to provide any additional information you need. Thanks!

**Comment by dannyg** [comment]
This is such a fundamental missing thing from Capacitor - for example when you need to take the user to a site to perform some action and then help them return to the app when completed.
The inappbrowser in cordova was very widely used to support this.
I understand why you keep closing the ticket because it is an inconvenience to incorporate a non-chrome based browser, but this is such a pain in the *ss for so many of us, for so long, it is really hindering the uptake of capacitor.
A plea to the Ionicframework folks:  make @ionic-enterprise/inappbrowser available to all!

**Comment by jayasin** [comment]
How to use the Capacitor's browserFinished addListener event on ionic for browser platform?

**Comment by cgadam** [comment]
@jcesarmobile thanks for clarifying that [Browser plugin](https://capacitorjs.com/docs/apis/browser) does not support reading url changes. I think it would be nice for this to be documented here: https://capacitorjs.com/docs/apis/browser

There are a couple of things that make us believe we could be reading URL changes from the official doc:

- It says it's compliant with leading oAuth service. (one would assume that the token returned can be read when the oauth flow ends and trigger some action from the app itself)

- The signature of the function `listenerFunc` is:  `(info: any) => void` which makes us believe some kind of info is actually returned for a 'browserPageLoaded' event. (one would assume that that info should contain the actual URL of the page being loaded)

I that's a clearer in the doc, one can start thinking of other ways of closing the browser automatically, like dynamic links, etc.

**Comment by vohrahul** [comment]
> @cgadam Good feedback, thank you!
> 
> I do know that for the [Capacitor 3 docs](https://capacitorjs.com/docs/v3/apis/browser), we removed the `info` parameter. I think we can definitely clean up that strange sentence about OAuth. I'm not sure what it means, either. 😄
> 
> > A plea to the Ionicframework folks: make @ionic-enterprise/inappbrowser available to all!
> 
> You should be able to use [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) in Capacitor apps. cordova-plugin-inappbrower and the Capacitor Browser plugin are fundamentally different implementations. We need a section in the docs about this for sure. I added this issue to do that: [ionic-team/capacitor-site#218](https://github.com/ionic-team/capacitor-site/issues/218)

cordova-plugin-inappbrowser is not always a correct alternative. As in many case, we need camera and microphone permission in the in-app browser. Unfortunately, the WebView doesn't support the required permissions and hence certain features can't work.

It will be great to just support a urlChangeListener in the capacitor browser plugin.

**Comment by Hyperblaster** [comment]
I need this really badly,

As far as i can tell there isn't any documented way to get any feedback or event back from the Capacitor Browser plugin right now.

**Comment by jjacobs33589** [comment]
I need this as well

**Comment by naveendonepudi** [comment]
We definitely need this :(

**Comment by rushabhmshah99** [comment]
+1 to the feature request

**Comment by PtahDA** [comment]
+1
