### ISSUE TITLE
Gradle can't sync when adding cordova-plugin-firebase

### ISSUE THREAD

**Issue by tayfun14** [ionic-team/capacitor#1297]
Description of the problem:
I can't sync gradle in Android Studio after adding cordova-plugin-firebase to my Capacitor/PWA project.
I created a new project to see if the problem came from my inital project, but the result is the same...
Affected platform
- Android

OS of the development machine
- Windows

Other information:

Capacitor version: 1.0.0-beta.18

node version: 10.15.1

npm version: 6.7.0

CocoaPods version: /

Steps to reproduce:

-ionic start firebase blank --capacitor
-cd ./firebase
-npm i cordova-plugin-firebase
-npm i @ionic-native/firebase
-ionic build --prod
-npx cap init
-npx cap add android
-npx cap open android

**Comment by jcesarmobile** [comment]
what's the error?

**Comment by tayfun14** [comment]
Some meaningless errors...

In my initial project : ERROR: Could not get unknown property 'cdvPluginPostBuildExtras' for project ':app' of type org.gradle.api.Project.

In the sample project : ERROR: Plugin with id 'io.fabric' not found.

In both cases, there is an error with FileProvider (in AndroidManifest.xml, in <provider>) in the IDE : 
![error firebase cordova](https://user-images.githubusercontent.com/17989186/54028570-babf0180-41a5-11e9-8482-f8fb06082aae.PNG)
at line 

android:name="android.support.v4.content.FileProvider"

Error : Unresolved class 'FileProvider'
Inspection info: Validates resource references inside Android XML files.

**Comment by jcesarmobile** [comment]
The problem is Capacitor doesn't support cordova hooks and that plugin uses one for setting the fabric repository and dependency, that's something you'll have to do manually, see https://docs.fabric.io/android/crashlytics/build-tools.html

**Comment by obermoserkitz** [comment]
would be nice if anybody can add step by step instructions about what to add to what file.

**Comment by joshlatimer** [comment]
Desperately need a fix for this

**Comment by dupiesdupreez** [comment]
Typical Ionic. No support. It should just die already

**Comment by realnsleo** [comment]
Anyone found a fix for this?

**Comment by tayfun14** [comment]
> Anyone found a fix for this?

Hey friend,
Unfortunately I wasn't able to make this cordova plugin works with Capacitor, so finally I replaced the cordova plugin by Capacitor Push Notification API : `https://capacitor.ionicframework.com/docs/apis/push-notifications/`

jcesarmobile did a push notification sample project : `https://github.com/jcesarmobile/ionic-angular-capacitor-push-example`

Have a nice day

**Comment by stryd3r** [comment]
Unfortunately I have the same issue. Before builded just fine but now I got "Plugin with id 'io.fabric' not found " out of nowhere :(

**Comment by shahalRahman** [comment]
> Unfortunately I have the same issue. Before builded just fine but now I got "Plugin with id 'io.fabric' not found " out of nowhere :(

Even i'm getting the same issue. Any luck on this ?

**Comment by pratikw7** [comment]
use this cmd: ionic cordova plugin remove firebase 

And try to find a workaround for Cordova, Capacitor might be a good alternative. That fix worked for me since I'm just beginning.

**Comment by ketankatdare** [comment]
If you are using capacitor
Use this : https://capacitorjs.com/docs/guides/push-notifications-firebase#creating-a-project-for-your-app-on-firebase

**Comment by chaslauer** [comment]
I had a working ionic capacitor app, but after adding firebase I am getting the same error:
"Plugin with id 'io.fabric' not found."

Any new information on this issue?

**Comment by shide1989** [comment]
Same, and Jetifier didn't help

**Comment by shide1989** [comment]
A workaround i Found is to use "cordova-plugin-firebase-messaging": "^4.4.2". Since it's only the messaging part, this combined with "cordova-plugin-firebase-analytics": "^4.3.1", has worked for me

**Comment by chaslauer** [comment]
I did the following: 

- install the firebase like in the documentation ([(https://ionicframework.com/docs/native/firebase)])

- remove the cordova-plugin-firebase from the package.json ("cordova-plugin-firebase": "^2.0.5",)

- run npm install

- run ionic capacitor copy android

This fixes my "Plugin with id 'io.fabric' not found." ERROR

**Comment by ma7moudjadallah** [comment]
did not work with me
