### ISSUE TITLE
[Android] Prevent Toast messages from showing

### ISSUE THREAD

**Issue by sandervandenbrink** [ionic-team/capacitor#1299]
[Here](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L180) and [here](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L238) a toaster message is displayed without the ability to prevent them from showing.

**Comment by nathanpronto** [comment]
Facing the same issue here. :(
