### ISSUE TITLE
[iOS] How to handle badge count for push notifications

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#1301]
On Android one does nothing special. It automatically counts the number of unhandled notifications you have. Although there is the issue which is already reported regarding not being able to call method to remove all delivered notifications at once: https://github.com/ionic-team/capacitor/issues/1217.

But for iOS, what is the thought here? How does one achieve what is already working out of the box on Android?

**Comment by solojuve1897** [comment]
iOS differs from Android with regards to the badge-count. While on Android it is directly connected to the number of unhandled recieved notifications on iOS it's dependent upon what you yourself set it to.

You need to include the badge-count in the payload:

```
{
    "aps" : {
        "alert" : "You got your emails.",
        "badge" : 9
    }
}
```

What I have done for my usecase is the following:

1. On my backend whenever a push-notification is to be sent I do a count for unread messages and then send the push-notification with the count as the badge in the payload.

2. When the app opens I clear all notifications (which also clears the badge-count):
`PushNotifications.removeAllDeliveredNotifications()`

3. When app is in foreground I don't take into consideration any recieved notification - whether it is alert, sound or badge. One does this in Capacitor by adding the following in capacitor.config.json under "plugins":

```
"PushNotifications": {
  "presentationOptions": []
}
```

**Comment by zakton5** [comment]
I feel like there still needs to be a way to handle modifying the badge count. In the 3 steps you mentioned, I agree with Step 1 and 3, but if there are pending alerts that the user should see then I want the app badge to just decrement appropriately instead of clearing everything away. If I do clear everything away then the user won't see the pending alerts until they get another badge related notification.

I would love to see methods like `getBadgeCount` `setBadgeCount` that I can use with `removeDeliveredNotifications` and `removeAllDelivereNotifications` so that I can update the badge count exactly as I want.

**Comment by sabahang** [comment]
hey can anyone point me to the right direction here. How is the backend supposed to know what badge number to send? Backend can't know which notification is yet consumed and what's not or am I missing something?

**Comment by mesqueeb** [comment]
@sabahang you need to manage how many notifications your users did not read yet by saving such data on the users whenever they interact with your app.
That way the backend can check your database on how many unread messages your users still have and include that number as the badge count + 1 for the current notification.

**Comment by danishin** [comment]
Could we take a look at this again? We had this capability back in cordova-plugin-push and it'd be nice to be able to clear badge without clearing all of notifications in notification center. Appreciate the help!

**Comment by bladerunner41** [comment]
@danishin found this Capacitor plugin you could try:
https://github.com/TeamHive/fancy-notifications

**Comment by bladerunner41** [comment]
@danishin  actually there is a community plugin propsoal for Capactior open issue
https://github.com/capacitor-community/proposals/issues/101

**Comment by derwaldgeist** [comment]
Once question here: What's the best practice to send push notifications to *all* users of your app, as part of your marketing activities? Let's say I want to inform everybody about some cool content. If I have to calculate the badge count for each and every user, this is not only a lot of load on the server and database, but also lots (maybe even millions) of push send calls to Apple's backend. What is the best practice here?

**Comment by mesqueeb** [comment]
For that you can use fcm topics, no?

**Comment by kingkarki** [comment]
Simply use this plugin https://www.npmjs.com/package/@robingenz/capacitor-badge
