### ISSUE TITLE
App not loading on IOS

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#1302]
My Ionic capacitor app has stopped working out of nowhere.

It was fine this morning and now wont get past the splash screen. The splash screen is hidden and then a white screen stays.

I updated npm packages stupidly - npm update - and now the application shows a plain white screen after the splash screen.

on Xcode the only difference I can see is this:

> ⚡️  [log] - onscript loading complete

> ⚡️  [error] - ERROR {"ngTempTokenPath":null,"ngTokenPath":[null],"line":1,"column":179909,"sourceURL":"capacitor://localhost/main.c7642e6ad4a5f28fdc6e.js"}
> ⚡️  [log] - {"ngTempTokenPath":null,"ngTokenPath":[null],"line":1,"column":179909,"sourceURL":"capacitor://localhost/main.c7642e6ad4a5f28fdc6e.js"}
> ⚡️  WebView loaded
> ⚡️  [log] - Ionic Native: deviceready event fired after 89 ms
> 2019-03-10 14:57:47.661454+0000 App[68076:4764666] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x10bd1cfc0] get output frames failed, state 8196
> 2019-03-10 14:57:47.661824+0000 App[68076:4764666] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x10bd1cfc0] get output frames failed, state 8196
> 2019-03-10 14:57:47.662911+0000 App[68076:4764666] TIC Read Status [1:0x0]: 1:57
> 2019-03-10 14:57:47.662987+0000 App[68076:4764666] TIC Read Status [1:0x0]: 1:57
> SplashScreen.hideSplash: SplashScreen was automatically hidden after default timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout). Read more at https://capacitor.ionicframework.com/docs/apis/splash-screen/#hiding-the-splash-screen

**Comment by jcesarmobile** [comment]
Javascript errors cause white screens on angular apps, you should figure out why are you getting that ngTempTokenPath null error

**Comment by oliverandersencox** [comment]
I thought as much, however it runs absolutely fine on chrome and safari with no errors being show

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce on a new angular project and it's clearly a js error. So you'll have to figure out what the problem is, and if you can prove it's Capacitor's fault then report a new issue providing more information.
