### ISSUE TITLE
cordova-plugin-3dtouch not working

### ISSUE THREAD

**Issue by 5an1ty** [ionic-team/capacitor#1307]
Description of the problem:

Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

It depends on MainViewController.h which is not found.

**Comment by jcesarmobile** [comment]
I've sent a PR to the plugin removing the import as it's not used. There is nothing else we can do about it if it's not merged/released.

**Comment by EddyVerbruggen** [comment]
Of course I'll merge and release! :) Thanks for the PR!

**Comment by jcesarmobile** [comment]
Thanks @EddyVerbruggen!!
