### ISSUE TITLE
[Android] getDeliveredNotifications not implemented

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#1314]
Description of the problem:
When calling method getDeliveredNotifications the following is shown in the logcat:

`Sending plugin error: {"save":false,"callbackId":"119341262","pluginId":"PushNotifications","methodName":"getDeliveredNotifications","success":false,"error":{"message":"not implemented"}}`

Affected platform
- [x ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
Beta. 19
node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by mlynch** [comment]
@jcesarmobile my read of the Android docs suggest that we would need to implement `NotificationManager.getActiveNotifications()`: https://developer.android.com/reference/android/app/NotificationManager.html#getActiveNotifications()

This API is only available on API 23 (our min is 21), but we should just support it conditionally for 23 and above.

**Comment by skeemer** [comment]
The getActiveNotifications() method does not in any way lead to getting data passed by notifications. You can access PendingIntent, but they have blocked accessing the data in the Intent for security reasons.

[https://stackoverflow.com/questions/23725035/how-to-get-intent-from-pendingintent/23725068#23725068](https://stackoverflow.com/questions/23725035/how-to-get-intent-from-pendingintent/23725068#23725068)

**Comment by jcesarmobile** [comment]
It was implemented using getActiveNotifications in https://github.com/ionic-team/capacitor/pull/2266
