### ISSUE TITLE
[Android] status bar: set linear background color not work for android.

### ISSUE THREAD

**Issue by uniquejava** [ionic-team/capacitor#1315]
Description of the problem:

`StatusBar.setBackgroundColor({ color: 'linear-gradient(225deg, #38a3eb 0%, #2880c8 100%)' })` works great for iOS, but not work for android. the status bar background color is black is this case.

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0-beta.19

node version:
10.15.2

npm version:
6.4.1

CocoaPods version:

Steps to reproduce:

Create a blank typescript ionic 4 project.  integrate capacitor and add android platform. 
Change app.component.ts as below:

```ts
import { Component } from '@angular/core';
import { Plugins, StatusBarStyle } from '@capacitor/core';
const { SplashScreen, StatusBar } = Plugins;
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})
export class AppComponent {
  constructor(private dataService: DataService) {
    SplashScreen.hide().catch(err => {
      console.warn(err);
    });
    StatusBar.setBackgroundColor({ color: 'linear-gradient(225deg, #38a3eb 0%, #2880c8 100%)' }).catch(err => {
      console.warn(err);
    });
    StatusBar.setStyle({
      style: StatusBarStyle.Dark
    }).catch(err => {
      console.warn(err);
    });
  }
}
```

noticed that this line

```js
  StatusBar.setBackgroundColor({ color: 'linear-gradient(225deg, #38a3eb 0%, #2880c8 100%)' }).catch(err => {
      console.warn(err);
    });
``` 
works only for iOS but not for android.

Link to sample project:

**Comment by jcesarmobile** [comment]
`setBackgroundColor` doesn't accept gradients, it's returning an error `"Invalid color provided. Must be a hex string (ex: #ff0000"}`.

I'm more intrigued by the fact that you claim that it works on iOS, where `setBackgroundColor` is not supported at all.
