### ISSUE TITLE
iOS Build errors with beta19 / swift 4.2

### ISSUE THREAD

**Issue by bmcharg** [ionic-team/capacitor#1317]
### Description of the problem:
I've updated our project which (to be fair) was running a very old beta8 to the latest beta19. However, now when I build I'm getting lots of errors.

`'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'`
`'inset(by:)' has been renamed to 'UIEdgeInsetsInsetRect(_:_:)'`
`'voiceOverStatusDidChangeNotification' has been renamed to 'NSNotification.Name.UIAccessibilityVoiceOverStatusDidChange'`
`'didBecomeActiveNotification' has been renamed to 'NSNotification.Name.UIApplicationDidBecomeActive'`

My project is definitely set to Swift 4.2. Interestingly if I look at eg `Clipboard.swift` in my beta8 version then calls like `UIImagePNGRepresentation` are correctly named (and hence why the project builds fine). However, once I've upgraded to beta19 `Clipboard.swift` does indeed contain the `pngData()` call instead.

My update steps were as follows;

1. `npm install @capacitor/core@latest --save`
2. `npm install @capacitor/cli@latest --save`
3. `npm install @capacitor/ios@latest --save`
4. `npm install @capacitor/android@latest --save`
5. `npx cap update ios`
6. `npx cap sync`

and package.json correctly reflects 

`"@capacitor/android": "^1.0.0-beta.19",
"@capacitor/cli": "^1.0.0-beta.19",
"@capacitor/core": "^1.0.0-beta.19",
"@capacitor/ios": "^1.0.0-beta.19",`

### Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

### OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

### Other information:

Capacitor version: Upgrading from beta8 to beta19
node version: 11.7.0
npm version: 6.5.0
CocoaPods version: 1.5.3
Xcode version: 10.1 (10B61)

**Comment by bmcharg** [comment]
We managed to eventually get to the bottom of this. The targets of Capacitor, CapacitorCordova and CordovaPlugins was not being set correctly in the Pods targets.

We had to change the following;

Targets > Capacitor > Swift Language Version = Swift 4.2
Targets > CapacitorCordova > SWIFT_VERSION = 4.2
Targets > CordovaPlugins > SWIFT_VERSION = 4.2

However, when we next ran `npx cap sync` these changes were blown away.

To get the change to persist, we had to edit `Podfile` as follows;

```  installer.pods_project.targets.each do |target|
      if ['Capacitor'].include? target.name
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.2'
          end
      end
  end
```

**Comment by jcesarmobile** [comment]
Since this doesn't affect new projects and you figured it out I'm going to close. 

BTW, the CordovaPlugins swift version can be configured like this in the `capacitor.config.json`

```
"ios": {
    "cordovaSwiftVersion": "4.2"
  }
```

And CapacitorCordova doesn't use Swift at all, so you shouldn't need to force a version.
