### ISSUE TITLE
Ionic slides custom component instances do not behave the same

### ISSUE THREAD

**Issue by JohnGrisham** [ionic-team/capacitor#1318]
Description of the problem: 

Only one of the component instances resizes and maintains number of slides
property. The others do not respond well to screen resizing and break
number of slides per view and centering. This causes issues where slides
show many items as opposed to 3 items in the view and the number of items
do not reset to 3 per view upon any other resize event. Slides also do not
maintain centering on the screen I have tested with only one slide and it
works fine when there are more instances only one works.

Affected platform
- [ ] web

OS of the development machine
- [ ] Windows

Other information:
Ionic version - 4.11.0
Capacitor version:
3.9.2
node version:
8.12.0
npm version:
6.4.1

Steps to reproduce:
[movieslides.zip](https://github.com/ionic-team/capacitor/files/2961624/movieslides.zip)
[home.zip](https://github.com/ionic-team/capacitor/files/2961628/home.zip)

Link to sample project:

**Comment by jcesarmobile** [comment]
Sorry, I still don't see any indication of this being a Capacitor bug and it's even less clear than the previous one.

**Comment by jcesarmobile** [comment]
By looking at your code, you have this:

```
this.platform.resize.subscribe(() => {
  this.screenResized = true;
  this.slides.resize();
});
```

That's what you mean that is not working, right?

That's not Capacitor code but ionic-angular code

**Comment by JohnGrisham** [comment]
Your profile picture is appropriate because that is the emotion I'm feeling
right now. I resubmitted the previous issue because you were right the code
pasted was formatted badly. I instead upload my files directly and updated
the description. I do not normally post issues but I cannot resolve this
one. I will attempt to post this issue within the base ionic issue set. I
am however using capacitor which is still in Beta and since I could not
find anyone else with this issue in the ionic issues I assumed that it
might have something to do with capacitor instead. Maybe instead of just
closing issues you could actually listen to developers and try to guide
them in the right direction.

**Comment by JohnGrisham** [comment]
The behavior is the same even without that code. It has something to do
with how the actual slides component functions. When wrapped inside another
component.
