### ISSUE TITLE
Setting html directory to project folder (not subfolder) recursively creates infinitely nested folders, crashing build processes

### ISSUE THREAD

**Issue by Erudition** [ionic-team/capacitor#1324]
Description of the problem:
Upon first trying capacitor on my existing web project (built with Elm platform), I ran into several issues including a fresh android studio failing to build - with java Out Of Memory errors. This project had nothing but a js and an html file in the project directory, and I had plenty of RAM, so that was very strange. I could not find very much info on this problem on the web, so I bit the bullet and settled for a workaround (already) of raising the GC RAM limit for the java process. The build still took forever, but this time failed with a different error about not being able to list the contents of a directory. And it's no wonder - check out what happened when I gave up and tried deleting the capacitor-generated `android/` directory: (yes, keep scrolling horizontally)

```
Error opening directory '/home/(me)/Projects/Elm/ProjectName/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/android/app/src/main/assets/public/node_modules/json-schema': No such file or directory
```

(Others experiencing this issue: if you get `java.lang.OutOfMemoryError: GC overhead limit exceeded` [build failure in Android Studio](https://stackoverflow.com/questions/32133013/java-lang-outofmemoryerror-gc-overhead-limit-exceeded-on-android-1-4/32133048), this may be what is happening!)

So the reason everything was failing was because there was a symlink (or capacitor actually copied it that many times?) from the html assets directory to ProjectName/android/app/src/main/assets/public/, and that's bad, because in my case, ProjectName _is my html assets directory._ 

(As far as I know, It's not standard in Elm to shove all output html into a subfolder for a simple project, and I certainly see no other reason why I should have a "www" folder. So my capacitor.config.json was set to `"webDir": "."`, which otherwise worked fine.)

Affected platform
- [X] Android
- [?] iOS
- [?] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [X] gnu/linux

Other information:

Doing it the `ProjectName/www/` way works, but it's not an ideal workaround.

Capacitor version:
1.0.0-beta.19 (latest via `npx`)

Steps to reproduce:
1. Create a capacitor project
2. Set `webDir` to `./`
3. `cap open android` and attempt to build

**Comment by jcesarmobile** [comment]
Capacitor requires an "assets" folder that is copied to the platform, it can't be the root folder as it copies everything inside it.
I've sent a pull request that will prevent setting the webDir to `.`, `./` and some other invalid values to avoid problems like yours. 
I don't know much about elm, but I think it allows you to set the path where you build the resulting .html/.js, so you'll have to configure it to build to a folder and configure webDir to point to that same folder, but you can keep your sources on the root.
