### ISSUE TITLE
window.open not working on Android

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/capacitor#1327]
Description of the problem:

`window.open` does not work on Android. Ideally it would have the same behavior as iOS and open the device's browser as reported in #798 and fixed in #804.

Affected platform
- Android

OS of the development machine
- macOS

Capacitor version: `1.0.0-beta.19`

Steps to reproduce:
Try to open a url with `window.open(someUrlHere)` on Android. Nothing happens whereas on iOS the Capacitor app will close and safari will open the url.

**Comment by jcesarmobile** [comment]
Interesting, it doesn't work if I use the code inside the app, but works if I use it in the dev tools, no idea what's going on.

**Comment by jcesarmobile** [comment]
I have a fix, but for some reason github is not working fine, it was just a missing setting we had to enable on the WebView.
