### ISSUE TITLE
Show alert for copy errors when running natively

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#134]
For example, missing `index.html` and `native-bridge.js`

**Comment by vincent-herlemont** [comment]
This troubleshooting is report [here](https://github.com/ionic-team/capacitor/blob/master/site/docs-md/android/troubleshooting.md).
But when I run the fixing command ```npx cap copy android``` at origin of the example project. I have the following issues.
```Stage not set, please call something such as `cap production deploy`, where production is a stage you have defined.```
