### ISSUE TITLE
How to completely disable the splashscreen?

### ISSUE THREAD

**Issue by MulverineX** [ionic-team/capacitor#1341]
I figured out how to do it for electron easily, but for android/ios I can't find configuration anywhere to turn it off, I'm told to call a function to tell capacitor when the app is done loading, but I don't know how to do that within vue (within webpack)

**Comment by solojuve1897** [comment]
I don't know about completely disabling the splash splashscreen but hiding it when the app is loaded in Vue is simple enough. Add the following line in the mounted hook in the App.vue-file:

SplashScreen.hide()

**Comment by MulverineX** [comment]
Do I need to import something or should it just work?

**Comment by solojuve1897** [comment]
In the same file you add:

import { Plugins } from '@capacitor/core'
const { SplashScreen } = Plugins

**Comment by mlynch** [comment]
Closing as it seems this is resolved.

Let us know if you'd like to completely remove it for some reason (and would love to know why!)

**Comment by nate-eisner** [comment]
@mlynch, I do have a use case in which I would like to completely disable the splash screen. I have a native component that is used initially on launch. (different ViewController in iOS and different Activity in Android) The user is then brought into the Capacitor component from that native piece.

**Comment by davidrock** [comment]
Please, let us know how to REMOVE the splash-screen. It should be an optional not required feature.
Is not logical have to hide something when the app is loaded whether I don`t need this thing at all.

**Comment by jnettome** [comment]
Guys, I've made some progress on it tweaking the SplashScreen.java, overriding those fade params. Has anyone got success on it?

**Comment by skmohammadi** [comment]
In React-JS, i have placed *Splashscreen.hide()* before *ReactDom.render* line. Splash duration decreased but still it is visible ~ 1 second. It is may to remove Splash completely?

**Comment by ryandegruyter** [comment]
in BridgeActivity.main you can remove Splash.showOnLaunch(this);
But it's not configurable
