### ISSUE TITLE
Platform field in Device.getInfo() is always set to "web" even when running app in Android or iOS 

### ISSUE THREAD

**Issue by ShinZ6** [ionic-team/capacitor#1351]
Description of the problem:

Affected platform
- [X ] Android
- [ X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [x] linux

Other information:

Capacitor version: 1.0.0-beta.19

node version: 10.15.3

npm version: 6.9.0

CocoaPods version: 1.6.1

Steps to reproduce: Just print Device.getInfo() output when running on Android or iOS

Link to sample project:

**Comment by jcesarmobile** [comment]
How are you running iOS from linux?

**Comment by ShinZ6** [comment]
> How are you running iOS from linux?

I use a mac for building on iOS.

**Comment by jcesarmobile** [comment]
Can you share your code? When it uses the web implementation instead of the native implementation is usually by a mistake on the import/usage

**Comment by ShinZ6** [comment]
I just print this on logcat or on xcode debug:

import {Device} from '@capacitor/core'
Device.getInfo().then((info) => {
    console.log(info);
});

The other fields on the info object are set fine except of the platform field.

**Comment by ShinZ6** [comment]
I got a hint from your comment above, maybe I need to import it like this?

import { Plugins } from '@capacitor/core';
const { Device } = Plugins;

**Comment by jcesarmobile** [comment]
Yes, that's the way of using the plugins, you import Plugins, which is the plugin registry, not the plugin object directly, and get the plugin from the registry as you said `const { Device } = Plugins;`

**Comment by ShinZ6** [comment]
Ah okay, thanks.
