### ISSUE TITLE
Cordova plugins can't execute javascript code with webView.loadUrl

### ISSUE THREAD

**Issue by petarov** [ionic-team/capacitor#1353]
Description of the problem:

It seems like Capacitor does not allow for Cordova `cordova.fireDocumentEvent` to be received using `document.addEventListener`.

I'm using the [Cordova Admob Free plugin](https://github.com/ratson/cordova-plugin-admob-free) with Capacitor. The plugin installs and works as expected, meaning the bridge calls work and it displays test ads, however, my Capacitor app does not receive any of the plugin issued [cordova.fireDocumentEvent](https://github.com/ratson/cordova-plugin-admob-free/blob/master/src/android/CordovaEventBuilder.java#L27) events.

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

I've tried with both Cordova framework 7.0.0 and 8.0.0 as dependencies in the Android project.

Capacitor version: 1.0.0-beta.19

node version: 11.7.0

npm version: 6.5.0
 
CocoaPods version:

Steps to reproduce:

1. Clone and build the repository at https://github.com/petarov/capacitor-cordova-fireevent
2. `npx cap open android` to open the app in Android Studio.
3. Build & run the app on an Android device.
4. Open Logcat in Android Studio.
5. Press the `Show Ad` button in the app on the device.
6. None of the `admob.interstitial.events.*` events in [app.js](https://github.com/petarov/capacitor-cordova-fireevent/blob/master/www/js/app.js#L24) get displayed in Logcat.

Link to sample project: https://github.com/petarov/capacitor-cordova-fireevent

**Comment by jcesarmobile** [comment]
Your sample app was crashing at first, I got it working by updating the dependencies to latest

```
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.android.gms:play-services-ads:17.2.0"
```

Now I get
D/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
03-27 20:01:24.840 11642-11642/my.test.app I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
 Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to *
    * find your app ID.   

looks like you didn't add your google-services.json file, or should I add mine?

Anyway, cordova.fireDocumentEvent  works fine for me out of your app, I just tried this:

```
document.addEventListener('hello', function (event) {
  console.log("hello ", event);
});
cordova.fireDocumentEvent('hello');
```

So the problem seems to be that we don't do anything on plugin.webView.loadUrl method.

**Comment by petarov** [comment]
Hi @jcesarmobile and thanks a lot for looking into this!

I never added a `google-services.json`, I don't think it is needed for this particular example. There's just a Google Admob test `APPLICATION_ID`  in `capacitor-cordova-android-plugins/src/main/AndroidManifest.xml` and that should be sufficient.

If there's something else that I can test/try, just let me know.

**Comment by jcesarmobile** [comment]
Maybe it’s only required on newer play services versions, so you used the default ones? You didn’t do any manual change at all to make it work?

**Comment by petarov** [comment]
I only did two changes:

 - Bump the`play-services-base` and `play-services-ads` versions in `capacitor-cordova-fireevent/test/android/capacitor-cordova-android-plugins/build.gradle`.
 - Added a test `APPLICATION_ID` in `capacitor-cordova-android-plugins/src/main/AndroidManifest.xml`.

There is a `com.google.firebase:firebase-messaging:17.1.0` dependency that capacitor generates in `app/build.gradle`. Maybe that is where the `google-services.json` message comes from. I'm not sure.

I also did not experience any crash as on your side, so that still perplexes me. What happens when you tap the *Show Ad* button?

**Comment by jcesarmobile** [comment]
Which versions did you use?
What’s the test APPLICATION_ID? 
You didn’t commit the capacitor-cordova-android-plugins

**Comment by jcesarmobile** [comment]
Ok, I got the test APPLICATION_ID and was able to test and fix it.

BTW, don't manually edit anything in capacitor-cordova-android-plugins, all that is recreated on update and sync commands.

You can add the id on the app's AndroidManifest.xml like this

```<meta-data tools:replace="android:value"
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>```

(It requires to add the tools namespace to the manifest tag ` xmlns:tools="http://schemas.android.com/tools"`)

**Comment by petarov** [comment]
I've just tested the fix and it all works great! Thank you again @jcesarmobile and thanks for the id hint.

I'm sorry about the missing `capacitor-cordova-android-plugins` folder. Looks like it was in the `.gitignore` file Capacitor generated and I completely missed it. My bad!
