### ISSUE TITLE
Camera does not show up anything

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor#1360]
Hi,

I try to use the Camera plugin on the desktop version but I always end up with an error due to camera modal element that does not exist.

![image](https://user-images.githubusercontent.com/8195958/55023288-c19aa080-4ffc-11e9-901f-064df29fad92.png)

I can confirm that `ion-pwa-camera-element` is created in the DOM each time I call the getPhoto() function  but they are all empty :/

Does anyone succeed to make it working?

Note: I also have this issue on iOS

Thank you,

**Comment by jcesarmobile** [comment]
I've made it work in the past, didn't try recently.
Can you provide a sample app?
In which browser are you testing?

By "I also have this issue on iOS" you mean in native iOS? or in web iOS?
In case it's in native, the issue is the cameraModal.present is not a function or that camera doesn't show up?

**Comment by sneko** [comment]
- Yes I will try to find time to make a demo/debug app
- I tested in Google Chrome and in Safari (desktop for both)
- Sorry for missing details, I meant testing in the native application (so not CameraWebPlugin but the iOS one)
- About the native test, the camera also does not show up. There is also an error (image below):
![image](https://user-images.githubusercontent.com/8195958/55024562-67e7a580-4fff-11e9-9b1d-9d5f1e92dada.png)

**Comment by sneko** [comment]
@jcesarmobile while looking at all `pwa-elements` occurences in my runtime source files I saw a path to the es5 js version.

So I checked at `node_modules/@ionic/pwa-elements/dist/esm/es5/index.js` but the file is totally empty. On the other hand in the `.../es2017/index.js` file I can find this content:
```
import { h } from '../ionicpwaelements.core.js';
```

Could you confirm you have the same please?

**Comment by jcesarmobile** [comment]
At the moment it only works if you add the script tag with PWA elements

`<script src="https://unpkg.com/@ionic/pwa-elements@1.0.2/dist/ionicpwaelements.js"></script>`

We have this issue open for finding a better solution: https://github.com/ionic-team/capacitor/issues/387

**Comment by sneko** [comment]
Ok thank you, I have subscribed to this issue.

BTW, PWA elements are not responsible for my error in my native iOS application. I still need to figure out what's happening hmmm 🤔

**Comment by jcesarmobile** [comment]
Going to close as on web the problem was the pwa-elements script not being added, and I can't reproduce on iOS

**Comment by shravanvis** [comment]
thank you both of you
it works for me
<script src="https://unpkg.com/@ionic/pwa-elements@1.0.2/dist/ionicpwaelements.js"></script>

**Comment by sneko** [comment]
If I try to add this script tag I'm getting this issue:
![image](https://user-images.githubusercontent.com/8195958/55898350-afa32b00-5bc2-11e9-83d4-10f9d7d6eea1.png)

It seems Ionic and PwaElements try to define same properties.

Just to check, instead of adding directly in my HTML the script tag, I add it a few instants after the application is initialized by using the createElement() function. I get the same error but this time from PwaElements since it has been loaded after Ionic core:

![image](https://user-images.githubusercontent.com/8195958/55898539-1c1e2a00-5bc3-11e9-92d7-0db64082f5a9.png)

Any idea how I could manage that?

Thank you,
