### ISSUE TITLE
[ios] deployment target = 9

### ISSUE THREAD

**Issue by Dadoeo** [ionic-team/capacitor#1363]
Hi,

I’m trying to replace Cordova with my application, the problem that is my application has deployment target = 9, but when I put it with Capacitor I get this error:

Compiling for iOS 9.0, but module ‘Capacitor’ has a minimum deployment target of iOS 11.

Is there a way, a plugin, anything, to make Capacitor work with ios 9?

Regards

**Comment by jcesarmobile** [comment]
No, Capacitor only works on iOS 11+.
That's 92% of the iOS market share https://developer.apple.com/support/app-store/
