### ISSUE TITLE
How to Create Custom Plugins without Publishing to NPM?

### ISSUE THREAD

**Issue by thmclellan** [ionic-team/capacitor#1365]
This may be more of a documentation / support issue, but is there a recommended way to create and debug a custom Capacitor plugin without publishing it to NPM and without making direct edits under node_modules?  (Related docs: https://capacitor.ionicframework.com/docs/plugins/) 

It seems like some directory layouts have changed since Josh Morony's guide at https://www.joshmorony.com/running-custom-native-ios-code-in-ionic-with-capacitor/. 

Anyway appreciate any suggestions... looking to build out a custom iOS plugin in Objective-C and love the approach of Capacitor over Cordova. Thanks

**Comment by jcesarmobile** [comment]
I think easiest way it's just to `npm install /path/to/plugin/folder`

**Comment by thmclellan** [comment]
Thanks @jcesarmobile that works really well
