### ISSUE TITLE
cordova-plugin-ibeacon fails initialization

### ISSUE THREAD

**Issue by RangerRick** [ionic-team/capacitor#1367]
Description of the problem:

I'm attempting to use `cordova-plugin-ibeacon` and `@ionic-native/ibeacon` in a freshly-created ionic 4 project, but it fails initialization.  I'm not sure if it's because of capacitor's way of importing the plugin, or Ionic's build system.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

I'm following the basic initialization in [the ionic-native docs](https://ionicframework.com/docs/native/ibeacon/) and it fails when attempting to get the `Delegate()`.

The error in Xcode's drawer is:

```
⚡️  [error] - ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'new _ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["cordova"].plugins.locationManager')
http://192.168.211.52:8100/vendor.js:75016:102
http://192.168.211.52:8100/main.js:1023:50
onInvoke@http://192.168.211.52:8100/vendor.js:51141:39
run@http://192.168.211.52:8100/polyfills.js:2508:49
http://192.168.211.52:8100/polyfills.js:3247:37
onInvokeTask@http://192.168.211.52:8100/vendor.js:51132:43
runTask@http://192.168.211.52:8100/polyfills.js:2553:57
drainMicroTaskQueue@http://192.168.211.52:8100/polyfills.js:2959:42
invokeTask@http://192.168.211.52:8100/polyfills.js:2860:40
timer@http://192.168.211.52:8100/polyfills.js:4639:34
```

If I list the plugins in `window.cordova.plugins` there is a `locationManager` property.

Capacitor version:

1.0.0-beta.19

node version:

8.15.1

npm version:

6.4.1

CocoaPods version:

1.6.1

Steps to reproduce:

`ionic build && ionic cap sync && ionic cap run -l`

Link to sample project:

https://github.com/RangerRick/cm-5000.git

**Comment by jcesarmobile** [comment]
I get the same error if testing with Cordova, so I don't think this is a Capacitor issue, but a plugin issue or an ionic native issue on the ibeacon wrapper

**Comment by jcesarmobile** [comment]
It's an ionic native bug, see https://github.com/ionic-team/ionic-native/issues/2631
