### ISSUE TITLE
Storage.get doesn't work

### ISSUE THREAD

**Issue by Lexus123** [ionic-team/capacitor#1370]
Description of the problem:
Storage.get(ARGUMENT) doesn't work.
When passing in the argument {key: 'text'}, it says it needs a string. When I pass in a string, it says it needs {key: string}.

Screenshots:
https://imgur.com/a/4P0Qz4t

Affected platform
Android, as far as I know

OS of the development machine
- [x] macOS

Capacitor version:
Beta 19

**Comment by Lexus123** [comment]
Wow. It works if I take it out of the JSON.parse... Please update the docs, because this would've saved me hours...

**Comment by mlynch** [comment]
Fixed in master will be in the site soon thanks
