### ISSUE TITLE
[iOS] removeAllDeliveredNotifications doesn't clear badge-count

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#1374]
Description of the problem:
On Android removeAllDeliveredNotifications will also clear the badge-count. On iOS it doesn't. What do we want to do here?

I have a solution which I am implementing locally. If you think it is the way to go I can make a PR. I have added the following in the removeAllDeliveredNotifications-method in PushNotifications.swift:

```
DispatchQueue.main.async(execute: {
  UIApplication.shared.applicationIconBadgeNumber = 0
})
```

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

**Comment by jcesarmobile** [comment]
I was thinking in adding a new method as phonegap push plugin had, but considering in old days the only way of removing push notifications was setting the badge to 0, I think it makes sense to put it there.
As I was already looking into push issues I've sent a PR.

**Comment by solojuve1897** [comment]
Cool!
