### ISSUE TITLE
Filesystem removing folder

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#1375]
Description of the problem:

I have built an image cache using capacitor, and all works great. I can see the images being stored into the filesystem correctly.

However the next time i reload the application, I can get the uri of the file using the filesystem URI function and all looks fine. However the image won't load.

Now I have converted to a safe url using both the dom sanitizer and 'win.Ionic.WebView.convertFileSrc(url)' and the output is correct.

However when I go and actually navigate to the physical folder stated in the uri:

> capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/0D3DE1FC-AE52-4293-BD15-5E144104CAEB/Documents/skwap-file-718134147.jpg

I can navigate to the Application folder and then I see that the next folder I'm looking for has disappeared. It was there when In stored the images, however after restarting the app, its been removed.

I am storing here - directory: FilesystemDirectory.Data

I thought the idea of the filesystem was to be able to store things perm, however no matter what approach I take, the folder is delete on restart which defeats the purpose of it.

Affected platform
- [ ] Android
- [x ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ x] macOS
- [ ] linux

Other information:

Capacitor version: most recent

**Comment by jcesarmobile** [comment]
On iOS while in development, the `/var/mobile/Containers/Data/Application/0D3DE1FC-AE52-4293-BD15-5E144104CAEB/` part changes on every launch, so you can't store the absolute path for using it on next launch.

You'll have to store just the relative path and recreating the full path by getting the new Documents path

**Comment by oliverandersencox** [comment]
Great, thank you. I wasn't aware of this. 

Fixed the issue accordingly.
