### ISSUE TITLE
PR#1128 broke my use case

### ISSUE THREAD

**Issue by leshik** [ionic-team/capacitor#1381]
Description of the problem: `Capacitor` object is undefined when loading the external URL with `allowNavigation`.

Affected platform
- [x] Android

OS of the development machine
- [x] macOS

Capacitor version: `1.0.0-beta.19`

I tried to upgrade my application from `1.0.0-beta11` to `1.0.0-beta19` and things get broken on Android. In Chrome console, I can see the `Capacitor` object and its methods, but it's undefined when I try to invoke any (such as `isAndroid`).

While I understand #1128 is a great improvement, I'm not sure what should I do on my end to fix the issue. Reverting #1128 resolves it, but there should be a better way.

My config is as follows: `server.allowNavigation` contains a list of allowed URLs, then in `www/index.html` the only code is `location.href = 'https://one-of-allowed-urls-here'`.

@jcesarmobile could you please advice on what can I try?

**Comment by leshik** [comment]
@jcesarmobile Unfortunately, #1387 didn't help. Can you reopen, please?

ps: and shouldn't it be injected it `http` too?

**Comment by jcesarmobile** [comment]
It works for me. 
The previous line to the one I added is injecting it to http.

**Comment by leshik** [comment]
@jcesarmobile well, but how? To be sure I've put an empty file `test.html` to my server, then added the following HTML to `www/index.html`:

```
<!DOCTYPE html>
<head>
  <script>
    location.href = 'https://my-website-address/test.html'
  </script>
</head>
<body>
</body>
</html>
```

After the build I attach the console using `chrome://inspect` but the `Capacitor` is still undefined:

![image](https://user-images.githubusercontent.com/443678/55385636-c0ff8e00-5557-11e9-9ef6-cd4a7a8e3ab4.png)

Just tested again right now to be sure, doesn't work.

**Comment by jcesarmobile** [comment]
Unless you provide real information I can’t properly test what’s wrong on your side.
I did it with https://www.google.es and worked

**Comment by leshik** [comment]
`package.json`:

```
{
  "name": "capacitor-app",
  "version": "1.0.0",
  "description": "An Amazing Capacitor App",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "capacitor",
    "mobile"
  ],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@capacitor/cli": "1.0.0-beta.19",
    "@capacitor/core": "1.0.0-beta.19"
  },
  "dependencies": {
    "@byteowls/capacitor-oauth2": "1.0.0-alpha.27",
    "@capacitor/android": "1.0.0-beta.19",
    "@capacitor/ios": "1.0.0-beta.19",
    "cordova-plugin-speechrecognition": "git+https://github.com/leshik/cordova-plugin-speechrecognition.git#fix-incorrect-pluginResult-codes",
    "phonegap-plugin-barcodescanner": "git+https://github.com/phonegap/phonegap-plugin-barcodescanner.git"
  }
}
```

#1387 patch added to `node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java` right after `npm i`, then:

```
npx cap sync
npx cap open android
```

`capacitor.config.json`:

```
{
  "appId": "com.example.app",
  "appName": "App",
  "bundledWebRuntime": true,
  "webDir": "www",
  "plugins": {
    "SplashScreen": {
      "launchAutoHide": false,
      "androidScaleType": "CENTER"
    }
  },
  "server": {
    "allowNavigation": [
      "*.google.es"
    ],
    "port": "7721"
  }
}
```

`www/index.html`:

```
<!DOCTYPE html>
<head>
  <script>
    location.href = 'https://www.google.es'
  </script>
</head>
<body>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/443678/55386707-48e69780-555a-11e9-8557-1748695146d4.png)

I there is anything else you need me to provide, please let me know.

**Comment by jcesarmobile** [comment]
The problem is probably because of the * on the allowNavigation

**Comment by leshik** [comment]
@jcesarmobile how one could be related to another? I wrote this code and it was working fine before (I mean, the code that is related to `allowNavigation`), wildcards were part of the design (check `matchHost` function in `Bridge.java`.) Anyway after changing to `www.google.es` it didn't help.

**Comment by jcesarmobile** [comment]
Despite your page says google.es, it's actually the thailand one, that's why it doesn't work in your case.
In my case as I load the .es, this works fine `"allowNavigation": ["www.google.es"]`, while this doesn't `"allowNavigation": ["*.google.es"]`.

The code handling the allowNavigation and the one that injects the Capacitor javascript is different.
Previously it was "working" because it was being injected twice in two different ways, but it wasn't really working as the injection on didFinish was using the web implementation of plugins instead of the native ones.

I'm going to create a new issue for the Capacitor code not injected when using * in allowNavigation, will link it to this one.

**Comment by leshik** [comment]
@jcesarmobile thanks for clarifications, but I'm unable to make it work no matter if I use wildcards or not, google.es or any other site. Seems that `allowNavigation` is completely broken now – the part that is injecting the code. The URL is opened in the embedded WebView, no matter of wildcard or not, but the `Capacitor` object is not injected.

ps: `google.es` is not redirecting, checked both in Chrome incognito and with curl. Yes, it displays the localized content, but the URL stays the same.

**Comment by leshik** [comment]
I did some tests on the fresh projects and there are more findings. I'll describe them in #1389.
