### ISSUE TITLE
CordovaPluginQrscanner

### ISSUE THREAD

**Issue by cuni0716** [ionic-team/capacitor#1382]
The build fail cause to a deprecated functions

<img width="1112" alt="Screenshot 2019-04-01 at 12 45 24" src="https://user-images.githubusercontent.com/9133999/55322236-16ff0380-547c-11e9-96b2-a90760fb4ee1.png">

Can I use this plugin doing something? I need some help here, thnx in advance!

**Comment by jcesarmobile** [comment]
You have to configure the Swift version to use based on the plugin required Swift version

https://capacitor.ionicframework.com/docs/basics/configuring-your-app
