### ISSUE TITLE
Proxy is not defined at new CapacitorWeb

### ISSUE THREAD

**Issue by deveshmishra34** [ionic-team/capacitor#1388]
Description of the problem:
This issue is occurs when we use capacitor plugins in lower android devices like android 5, 5.1, 6. But if you remove the capacitor plugins usage application will work but then css will not render properly. Style will not apply as you want.
Can any one help.... otherwise i have to switch ionic 3

Affected platform
- [x] Android

OS of the development machine
- [x] macOS

Other information:

Capacitor version: 
"@capacitor/android": "^1.0.0-beta.19",
"@capacitor/core": "^1.0.0-beta.19",
"@capacitor/cli": "^1.0.0-beta.19",

node version: v8.12.0

npm version:  6.4.1

**Comment by jcesarmobile** [comment]
The problem is the same as on 
https://github.com/ionic-team/capacitor/issues/456

Proxy is not available in your device. In Android it should work, but as you are testing in an emulator it’s probably out of date. Try updating the sdks for emulators and the system Webview/chrome if possible.

**Comment by deveshmishra34** [comment]
No this problem is not only occur in emulator it also occurs in real devices. I have a live ionic 4 application and most of the people commented app not opening and mostly from android 5, 5.1 or 6

**Comment by jcesarmobile** [comment]
That's a different issue, you might need to enable polyfills for older Android versions/webviews to properly work, see https://ionicframework.com/docs/faq/runtime#blank-app

Also check this related issue https://github.com/ionic-team/ionic/issues/17781

**Comment by deveshmishra34** [comment]
Hello, These are the device list who are facing the issues "Proxy is not defined at new CapacitorWeb"
<img width="365" alt="Screenshot 2019-04-04 at 5 03 10 PM" src="https://user-images.githubusercontent.com/8393611/55552680-a403c000-56fb-11e9-92c8-a18e86de4b95.png">

Here the screen shot form OPPO A37fw (Android 5.1.1, API 22
![photo_2019-04-04_17-07-14](https://user-images.githubusercontent.com/8393611/55552891-563b8780-56fc-11e9-85a7-a1b115de1198.jpg)
)

**Comment by jcesarmobile** [comment]
This doesn't depend on the device itself, but on the Android System WebView version. The Android System WebView can be updated from Google play, it's required version 67 or newer (latest is 73).

If users don't have it up to date there is nothing we can't do.

There is another issue for the Proxy problem, I already linked it, subscribe if you want to get notifications about progress.
