### ISSUE TITLE
Proxy do not reload after registerWebPlugin() in PWA/Web

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/capacitor#1393]
Description of the problem:

not work: Proxy is not work after registerWebPlugin().

```
import { Plugins } from '@capacitor/core';
const {【Community Plugin】} from Plugins;
```

the reason:
Before registerWebPlugin(), target[【Community Plugin】] is undefined. So do not available Proxy.
https://github.com/ionic-team/capacitor/blob/master/core/src/web-runtime.ts#L11

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [x] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
instead method: direct access.

```
import { Plugins } from '@capacitor/core';
Plugins.【Community Plugin】
```

Capacitor version:
   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

node version:
   NodeJS : v10.15.3 (/usr/local/bin/node)

npm version:
   npm    : 6.9.0

CocoaPods version:

Steps to reproduce:

Link to sample project:

Related:
https://github.com/ionic-team/capacitor/issues/749

**Comment by mlynch** [comment]
Likely fixed in 997a5a84d6b9a02b005be1d57980431cfe3e67e7
