### ISSUE TITLE
Admob plus doesn't work with capacitor

### ISSUE THREAD

**Issue by nathantaal** [ionic-team/capacitor#1398]
The cordova plugin admob-plus doesn't work with capacitor. It throws the error 

> error: lambda expressions are not supported in -source 1.7
(use -source 8 or higher to enable lambda expressions)

**Comment by solojuve1897** [comment]
You can press Alt + Enter (I think for Windows) in Android Studio on the lambda and you'll get the option to convert it to a regular function. But sure, would be nice to have support for lambdas.

**Comment by nathantaal** [comment]
I did the conversions already but then it starts nagging about target sdk being lower then the sdk a part of the code was written for and that continues until I don't know how to resolve the errors anymore

**Comment by solojuve1897** [comment]
So what's requested is a bump to 1.8 for better plugin-support. Hope it's easily doable!

**Comment by nathantaal** [comment]
> So what's requested is a bump to 1.8 for better plugin-support. Hope it's easily doable!

I hope it's enough to get it working, let's wait :)

**Comment by jcesarmobile** [comment]
would be good if you could provide a sample project with the plugin installed
