### ISSUE TITLE
Please add support for major plugins

### ISSUE THREAD

**Issue by naveedahmed1** [ionic-team/capacitor#1399]
I recently started exploring Capacitor while migrating one of our apps to Ionic 4. Its so simple and straight forward that we don't wana go back to Cordova.

But I think support for a lot of major plugins is missing in Capacitor.

For example, support for social logins for major social networking sites: 

Facebook (@ionic-native/facebook)
GooglePlus (@ionic-native/google-plus)
LinkedIn (@ionic-native/linkedin)

Similarly some of the other useful plugins like:

Deeplinks (@ionic-native/deeplinks)
Code-push (@ionic-native/code-push)
App-minimize (@ionic-native/app-minimize)
App-rate (@ionic-native/app-rate)
Launch-navigator (@ionic-native/launch-navigator)
Transfer (@ionic-native/transfer)
Text-to-speech (@ionic-native/text-to-speech)
Header-color (@ionic-native/header-color)

**Comment by jcesarmobile** [comment]
Sorry, we can't support all plugins available in the market.
But Capacitor has Cordova compatibility, so all those Cordova plugins should work just fine with Capacitor. If any of them doesn't work create a separate issue and we will try to fix the compatibility problems.
