### ISSUE TITLE
npx capacitor add ios android only add first one

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#140]
Running `npx capacitor add ios android` as `capacitor init` suggest, only adds the first platform (ios), but not the second one (android).

We should fix it so it adds both or remove that suggestion text

**Comment by jcesarmobile** [comment]
I now see it as separate commands, not sure when was updated

**Comment by mlynch** [comment]
Yea I decided for now to just make it singular and updated the reference elsewhere
