### ISSUE TITLE
Referencing an ENV variable in the Capacitor config file

### ISSUE THREAD

**Issue by drewrawitz** [ionic-team/capacitor#1405]
Hi there,

I have the following in my `capacitor.config.json` file:

```
{
  ...
  "server": {
    "url": "http://localhost:8080"
  }
}
```

I'd like to be able to set that value in an `.env` file: 

`VUE_APP_SERVER_URL=http://localhost:8080`

However, I can't reference `process.env.VUE_APP_SERVER_URL` in the JSON file, for obvious reasons. Is there an environment variable name that I can use to set that value, so I can exclude the `server` object from my config altogether?

Thank you!

**Comment by jcesarmobile** [comment]
If you don't want to set the server url in the root `capacitor.config.json`, you'll have to create a script that reads the environment variable and set it on the `ios/App/App/capacitor.config.json` and  `android/app/src/main/assets/capacitor.config.json`. Or a script that modifies the value in the root one before doing the copy/sync

**Comment by creativiii** [comment]
Is there any chance this could be reopened? Being able to quickly switch between dev and production environments without manually modifying JSON files would be really useful.

Is there any reason why `capacitor.config.json` can't be a `.js` file?

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/3133

**Comment by brightchip** [comment]
Hi, How do you read variables from .env file ?
