### ISSUE TITLE
Background fetch not working

### ISSUE THREAD

**Issue by rgolea** [ionic-team/capacitor#1409]
Hi there! I know capacitor has a way to finish a job called Background Task, but I would like to retrieve the geolocation of the device once in a while.

Basically, make [cordova-plugin-background-fetch](https://github.com/transistorsoft/cordova-plugin-background-fetch) but for some reason, it doesn't work.

I get the log where it gets sent to cordova but the plugin still doesn't work when I do `Debug->Simulate Background Fetch`.

Any ideas or alternative for this?

Thank you!

**Comment by jcesarmobile** [comment]
Plugins that add categories to AppDelegate usually don't work on Capacitor and this seem to be the case.

You can try to add to your `AppDelegate.swift` what the category does

First import `import TSBackgroundFetch` and then
    ```
func application(_ application: UIApplication,
                     performFetchWithCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        NSLog("AppDelegate received fetch event")
        let fetchManager = TSBackgroundFetch.sharedInstance()
        fetchManager?.perform(completionHandler: completionHandler, applicationState: application.applicationState)
    }
```

I've tried and sees to call the internal method of the plugin's `TSBackgroundFetch.framework` fine.

But closing as known incompatible plugins

**Comment by rgolea** [comment]
@jcesarmobile do we have a native capacitor alternative?

**Comment by jcesarmobile** [comment]
Not in the core plugins, not sure about 3rd party ones, but you can try what I told you, that seems to work.

**Comment by rgolea** [comment]
@jcesarmobile would this happen in Android as well?

**Comment by jcesarmobile** [comment]
I just tried iOS, so I don't know.

**Comment by rgolea** [comment]
Thank you so much @jcesarmobile. I hate bothering you so much. Still having problems importing in my `AppDelegate.swift` the `TSBackgroundFetch` module since it can't find it.

**Comment by jcesarmobile** [comment]
But did you have the plugin installed? It worked without problems on my sample app

**Comment by rgolea** [comment]
Yes, it installed the plugin and did `npx cap sync`.
Got the following:
```
Found 1 Cordova plugin for ios
    CordovaPluginBackgroundFetch (5.4.1)
✔ Updating iOS native dependencies in 9.41s
[info] Plugin cordova-plugin-background-fetch requires you to add 
  <key>UIBackgroundModes</key>
  <array>
    <string>fetch</string>
  </array>
 to your Info.plist to work
```
And I see it in xcode like in the following image:
![Screenshot 2019-04-11 at 16 12 39](https://user-images.githubusercontent.com/8843202/55964287-c3a76500-5c74-11e9-88d8-f573882550ab.png)

**Comment by rgolea** [comment]
@jcesarmobile how do I install the development version?

**Comment by jcesarmobile** [comment]
There are a few ways, probably easier is just to clone the whole github repository and then do `npm uninstall @capacitor/cli` to remove the old cli and then `npm install /path/to/cloned/folder/cli`.

**Comment by christocracy** [comment]
I've added Capacitor Support in [`cordova-plugin-background-fetch@5.6.0`](https://github.com/transistorsoft/cordova-plugin-background-fetch#capacitor) 

```bash
npm install cordova-plugin-background-fetch
npx cap sync
```

Capacitor support for [`cordova-background-geolocation-lt`](https://github.com/transistorsoft/cordova-background-geolocation-lt) will be published next week.

**Comment by jcesarmobile** [comment]
Thanks @christocracy, removing the known incompatible cordova plugin label and from the incompatible plugins doc.
