### ISSUE TITLE
 Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib

### ISSUE THREAD

**Issue by idhard** [ionic-team/capacitor#1410]
Description of the problem:
```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/xxx/Library/Developer/Xcode/DerivedData/App-afxnupsooluxigguxdnlnojmjwov/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh (in target: App)
    cd /Users/xxx/Sites/capacitor/ios/App
    /bin/sh -c /Users/odifisIH/Library/Developer/Xcode/DerivedData/App-afxnupsooluxigguxdnlnojmjwov/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh

mkdir -p /Users/xxx/Library/Developer/Xcode/DerivedData/App-afxnupsooluxigguxdnlnojmjwov/Build/Products/Debug-iphonesimulator/App.app/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/xxx/Library/Developer/Xcode/DerivedData/App-afxnupsooluxigguxdnlnojmjwov/Build/Products/Debug-iphonesimulator/Capacitor/Capacitor.framework" "/Users/xxx/Library/Developer/Xcode/DerivedData/App-afxnupsooluxigguxdnlnojmjwov/Build/Products/Debug-iphonesimulator/App.app/Frameworks"
sending incremental file list

sent 220 bytes  received 18 bytes  476.00 bytes/sec
total size is 2,078,063  speedup is 8,731.36
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found

```
Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

Capacitor version:
@capacitor/cli@1.0.0-beta.19 
@capacitor/core@1.0.0-beta.19
@capacitor/ios@1.0.0-beta.19
node version:

npm version:
6.4.1
CocoaPods version:
cocoapods-1.6.1

Steps to reproduce:

fresh install , add ios support and try to build the project

**Comment by jcesarmobile** [comment]
What's your Xcode version?
Have you installed ruby overwriting the default one that comes with the mac?

**Comment by idhard** [comment]
xcode version : 10.2 (10E125) 
macOS version: 10.14.4
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

i don't think i have installed other version of Ruby , i'm not a Ruby developer but i might installed other app that required it through homebrew.

**Comment by jcesarmobile** [comment]
I have exactly the same, so shouldn't be the problem.

To be clear, you get that error when building from Xcode, right?
Maybe Xcode wasn't properly installed? There was an user that had a similar problem and reinstalling Xcode fixed their problems.
Can you create and run a native app?

**Comment by idhard** [comment]
hey seems to work now, did brew update & cleanup ,restart and now the build works , thanks for quick answer!
