### ISSUE TITLE
[Android] Can't close a browser

### ISSUE THREAD

**Issue by mkrou** [ionic-team/capacitor#1414]
Description of the problem:

The close function from the browser plugin doesn't close a window on android.

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Capacitor version: 1.0.0-beta.19

node version: v11.12.0

npm version: 6.9.0

Steps to reproduce: 
```js
Capacitor.Plugins.Browser.open({'url': 'http://localhost:8080/close'});
  setTimeout(function() { Capacitor.Plugins.Browser.close(); }, 5000);
```

**Comment by rgolea** [comment]
@mkrou It's stated in the docs that closing a browser on android doesn't work.

**Comment by jcesarmobile** [comment]
As stated on the docs, it's not supported, Browser plugin uses Chrome Custom Tabs, which don't provide a way of programmatically closing them.

**Comment by raviada** [comment]
How do return to the app then? let's say I finished an oAuth flow in the browser instance, I am using client callback to close the browser and return to the app. This works great on iOS, but can't return to the app using capacitor:// url pattern. Browser instance shows a message to go back to my app, but I wasn't successfully bring the app to foreground. Any ideas? Thanks in advance.

**Comment by rgolea** [comment]
You can use this repository as reference or just go ahead and feel free to use this library: https://github.com/moberwasserlechner/capacitor-oauth2

**Comment by MPdevelopers** [comment]
How to close the browser then?

**Comment by savgiannis** [comment]
The docs state that Browser.close() works only in ios, Actually i only managed to make it work in desktop chrome windows 10, in ios it does not work either.
