### ISSUE TITLE
Can't programmatically open keyboard on iOS 12.2

### ISSUE THREAD

**Issue by mernen** [ionic-team/capacitor#1416]
Description of the problem: Invoking `HTMLInputElement.focus()` (or `IonInput.setFocus()`) outside of direct user events has no effect on iOS 12.2.

Applying https://github.com/ionic-team/cordova-plugin-ionic-webview/commit/cb4c491778bb9bf0716a9e9db8cb71d231dcef63 from ionic-team/cordova-plugin-ionic-webview#334 seems to solve the issue.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0-beta.19

node version: 11.14.0

npm version: Yarn 1.15.2

CocoaPods version: 1.6.1

Steps to reproduce:
1. Create an Ionic 4 app
2. Add an `<input>` element to the page
2. Add something like this to the page component:

    ```typescript
    @ViewChild('input') input: ElementRef<HTMLInputElement>;

    ngAfterViewInit() {
        setTimeout(() => this.input.nativeElement.focus(), 500);
    }
    ```
3. Run the app on an iOS 12.2 device/simulator with Capacitor

**Comment by jcesarmobile** [comment]
It was fixed here https://github.com/ionic-team/capacitor/pull/1352, but not released yet

**Comment by mernen** [comment]
Ah, thanks, I hadn't found that issue in my search.
