### ISSUE TITLE
Support adding custom pods

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#142]
We auto-generate the Podfile, but we should support adding your own stuff to this, even if through our command line

**Comment by jcesarmobile** [comment]
At the moment it's possible with Cordova plugins by adding them to the plugin.xml like this:

```
<platform name="ios">
    <framework src="FirebaseMessaging" type="podspec" spec="~> 2.0.0"/>
</platform>
```

Maybe we can add something similar in the Capacitor plugin package.json?

Or if we do it from the CLI, then where will we store the pods added to keep track of them? in capacitor.config.json?

**Comment by jcesarmobile** [comment]
Users are free to write on the Podfile
Plugins will have a .podspec where they can add dependiencies

So we have both cases covered, closing
