### ISSUE TITLE
cordova-plugin-document-viewer

### ISSUE THREAD

**Issue by bocodigital** [ionic-team/capacitor#1420]
This plugin seems to not be supported.

**Comment by solojuve1897** [comment]
The last commit was made about a year ago. Does the plugin work even in the latest version of Cordova? What happens with Capacitor? Any error-message? What's expected and what occurs? Can you provide a repo?

**Comment by bocodigital** [comment]
I redact my issue. I just missed a step in the installation. It works fine in capacitor.
