### ISSUE TITLE
Cordova code-push do not work with capacitor

### ISSUE THREAD

**Issue by richardgong1987** [ionic-team/capacitor#1421]
Description of the problem:
Cordova [code-push](https://github.com/Microsoft/cordova-plugin-code-push) do not work with capacitor

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
npx cap -V
1.0.0-beta.19

node version:
node -v
v10.14.2

npm version:
npm -v
6.9.0

CocoaPods version:

Steps to reproduce:

same issue discuss:

https://github.com/Microsoft/cordova-plugin-code-push

https://github.com/Microsoft/code-push/issues/615

**Comment by mlynch** [comment]
Will defer to the Microsoft team to support this.

In the meantime we will support remote code deploy for Capacitor in our [Appflow offering](https://ionicframework.com/appflow) shortly.

**Comment by jcesarmobile** [comment]
There is nothing we can do about it, it's Microsoft who has to create a new plugin for Capacitor or make the Cordova plugin compatible.

**Comment by mlynch** [comment]
An update as well on my last comment: [Capacitor is now officially supported in Appflow](https://ionicframework.com/blog/introducing-capacitor-support-for-ionic-appflow/), so you can push remote updates and do cloud iOS/Android builds.

**Comment by dylanvdmerwe** [comment]
I would love to move to Appflow, but the price is prohibitive, especially compared to Code Push. Code Push support for Capacitor is a blocker before we can think of migrating.

**Comment by rammere** [comment]
Hey @mlynch any updates from microsoft team on capacitor with code-push , many in the community including me are blocked to move to capacitor because of code push not supported.
And for AppFlow it is really very good but cost wise , specially if you have more than 20 apps and need to run updates.
Thank you

**Comment by pradella** [comment]
> Hey @mlynch any updates from microsoft team on capacitor with code-push , many in the community including me are blocked to move to capacitor because of code push not supported.
> And for AppFlow it is really very good but cost wise , specially if you have more than 20 apps and need to run updates.
> Thank you

Same here, still waiting for updates

**Comment by mlynch** [comment]
The best way to encourage Microsoft to do this is to share your thoughts on https://github.com/microsoft/code-push/issues/615
