### ISSUE TITLE
Phonegap Push Plugin compatibility issue with ionic 4

### ISSUE THREAD

**Issue by deveshmishra34** [ionic-team/capacitor#1440]
Phonegap Push Plugin is working fine with ionic3 but with ionic4 not all feature working.
We're receiving notification using Push plugin in ionic4 but if we send payload with notification, it does not work.
Is this plugin issue or capacitor issue..??

**Comment by jcesarmobile** [comment]
Is the Ionic 3 app using Cordova or Capacitor? 

Capacitor push classes probably interfere with Phonegap push plugin classes, so keep using Cordova or move to Capacitor push notifications https://capacitor.ionicframework.com/docs/apis/push-notifications

**Comment by deveshmishra34** [comment]
In ionic3 i'm using cordova (Push Plugin working fine) and In ionic4 i'm using capacitor (Push Plugin works fine without payload data) .

Previously i was using capacitor plugin but it cause problem like - proxy not defined in lower end device
Is there any solution where i can send . notification in ionic 4 with "Big Picture".
