### ISSUE TITLE
Android: TypeError: cordova.fireDocumentEvent is not a function

### ISSUE THREAD

**Issue by karol-depka** [ionic-team/capacitor#1443]
Description of the problem:

Fresh project via `npx @capacitor/cli create`.
After `npx cap add android` `npx cap open android`, app runs in emulator, displaying error.

```
    cordova.fireDocumentEvent is not a function
    TypeError: cordova.fireDocumentEvent is not a function
        at <anonymous>:1:9
```

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version:
````
  "dependencies": {
    "@capacitor/android": "^1.0.0-beta.22",
    "@capacitor/cli": "^1.0.0-beta.22",
    "@capacitor/core": "^1.0.0-beta.22"
  }
````

node version:
v10.15.3

npm version:
6.4.1

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
This happens because there are no Cordova plugins installed, so cordova.js is not injected.
As workaround you can install any cordova plugin and run `npx cap sync`.

But I'll work in a better fix

**Comment by KnowYourselves** [comment]
Hello  @jcesarmobile!

**Comment by jcesarmobile** [comment]
That’s not a cordova plugin, just the wrapper. You have to npm install cordova-plugin-file

**Comment by alterhu2020** [comment]
I met this issue too as the same capacitor version below .

**Comment by jcesarmobile** [comment]
It's fixed but not released yet. As workaround you can install any cordova plugin so the cordova.js is injected.

**Comment by alterhu2020** [comment]
thanks @jcesarmobile , waiting for it releases.

**Comment by JacobSobolev** [comment]
> That’s not a cordova plugin, just the wrapper. You have to npm install cordova-plugin-file

thanks, solved the issue
