### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by karol-depka** [ionic-team/capacitor#1444]
Description of the problem:

Fresh project via `npx @capacitor/cli create`.
After `npx cap add android` `npx cap open android`, app runs in emulator, displaying error.

```
missing ) after argument list
SyntaxError: missing ) after argument list
```

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version:
````
  "dependencies": {
    "@capacitor/android": "^1.0.0-beta.22",
    "@capacitor/cli": "^1.0.0-beta.22",
    "@capacitor/core": "^1.0.0-beta.22"
  }
````

node version:
v10.15.3

npm version:
6.4.1

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
What's the Android version of the emulator?
And what string do you get when running navigator.userAgent?

I can't reproduce on real devices with the System WebView/Chrome up to date and on old emulators where the System WebView can't be updated I get different errors (some of them known already like Proxy is not defined)

**Comment by mlynch** [comment]
Likely a very old app that is failing with some of the newer APIs used in that example
