### ISSUE TITLE
Camera direction Front option not working

### ISSUE THREAD

**Issue by Mathyn** [ionic-team/capacitor#1447]
Description of the problem:

When starting the camera with `direction` set to `Front` the camera start with the rear facing camera instead.

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Tested on a Galaxy S8 running Android 9.

Capacitor version:

`npx --version` -> 9.7.1

and

```
"@capacitor/android": "^1.0.0-beta.22",
"@capacitor/cli": "^1.0.0-beta.22",
"@capacitor/core": "^1.0.0-beta.22",
```

Also tested with

```
"@capacitor/android": "^1.0.0-beta.19",
"@capacitor/cli": "1.0.0-beta.19",
"@capacitor/core": "1.0.0-beta.19"
```

node version:

v8.11.2

npm version:

5.6.0

Steps to reproduce:

I use the following code start the camera:

```
Camera.getPhoto({
        quality: 100,
        allowEditing: false,
        resultType: CameraResultType.Base64,
        source: CameraSource.Camera,
        direction: CameraDirection.Front
});
```

**Comment by solojuve1897** [comment]
According to the doc that option is iOS-only. Why this limitation exist I don't know though.

**Comment by jcesarmobile** [comment]
There is no official way of setting the front Camera on the Android Intent the Camera uses.

There is an unofficial way, but it's not supported by all devices. I've tried in and worked on 2 of 5 devices, so not sure if it's worth implementing it

**Comment by jcesarmobile** [comment]
Going to close as it's already documented that it's iOS only and the Android workaround doesn't work in most cases.
