### ISSUE TITLE
Unknown installation options: disable_input_output_paths

### ISSUE THREAD

**Issue by JillevdW** [ionic-team/capacitor#1448]
Description of the problem:
When trying to build a newly generated ionic capacitor project I am faced with the error `[error] Error running update: [!] Unknown installation options: disable_input_output_paths.`. This issue can be fixed by finding the Podfile in the `ios/App` directory and removing `, :disable_input_output_paths => true` from the file (line 7).

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0-beta.22

node version: 8.9.4

npm version: 6.5.0

CocoaPods version: 1.5.3

Steps to reproduce:

- Create new ionic capacitor app
- Add the iOS platform (`npx cap add ios`)
- Sync the project (`npx cap sync`)

Both of these last steps should show the error I highlight here.
Now to reproduce the fix:

- Find the Podfile in the `ios/App` directory. Remove the following line: `, :disable_input_output_paths => true`.
- Sync the project again (`npx cap sync`)

You should now see the sync complete successfully.

**Comment by jcesarmobile** [comment]
As the comment on top of that line says 
> Requires CocoaPods 1.6 or newer
So you have two choices, update your CocoaPods version or removing the line as you already did. But it's not a bug.

**Comment by Sampath-Lokuge** [comment]
Yes,  this works for me `update your CocoaPods version`: Link: https://stackoverflow.com/a/39482577/1077309
