### ISSUE TITLE
Android build fails when both QR Scanner and Barcode scanner cordova plugins are installed

### ISSUE THREAD

**Issue by ryaa** [ionic-team/capacitor#1464]
Description of the problem:
I have ionic 4/capacitor project with barcode plugin installed (https://github.com/phonegap/phonegap-plugin-barcodescanner). All works fine however after I added the latest version of the QR Scanner plugin the android build fails.

There are multiple errors:
error: cannot find symbol variable SHOW_FLIP_CAMERA_BUTTON
error: cannot find symbol variable TORCH_ON
error: cannot find symbol variable BEEP_ON_SCAN
error: cannot find symbol variable ORIENTATION_LOCK
error: cannot find symbol variable Encode

<img width="1483" alt="Screen Shot 2019-05-03 at 7 18 29 AM" src="https://user-images.githubusercontent.com/3608222/57120760-bc571100-6d73-11e9-833a-74f0d9e32f63.png">

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
**Here is the ionic info output**
```
Alexs-MacBook-Pro:1794-rapid-inventory alexryltsov$ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/alexryltsov/Library/Android/sdk/)
   NodeJS            : v10.14.2 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

Alexs-MacBook-Pro:1794-rapid-inventory alexryltsov$
```

**Below are the plugins installed**
```
Alexs-MacBook-Pro:1794-rapid-inventory alexryltsov$ npx cap update
✔ Updating Android plugins in 62.21ms
  Found 0 Capacitor plugins for android:
  Found 14 Cordova plugins for android
    CordovaPluginCamera (4.0.3)
    CordovaPluginFile (6.0.1)
    CordovaPluginFileOpener2 (2.1.4)
    CordovaPluginFileTransfer (1.7.1)
    CordovaPluginFilechooser (1.2.0)
    CordovaPluginFilepath (1.5.1)
    CordovaPluginMarket (1.2.0)
    CordovaPluginQrscanner (3.0.1)
    CordovaPluginScreenOrientation (3.0.1)
    CordovaPluginWhitelist (1.3.3)
    CordovaSqliteStorage (2.6.0)
    Cordova.plugins.diagnostic (4.0.11)
    Es6PromisePlugin (4.2.2)
    PhonegapPluginBarcodescanner (8.0.1)
✔ update android in 223.82ms
✔ Updating iOS plugins in 39.29ms
  Found 0 Capacitor plugins for ios:
  Found 11 Cordova plugins for ios
    CordovaPluginCamera (4.0.3)
    CordovaPluginFile (6.0.1)
    CordovaPluginFileOpener2 (2.1.4)
    CordovaPluginFileTransfer (1.7.1)
    CordovaPluginMarket (1.2.0)
    CordovaPluginQrscanner (3.0.1)
    CordovaPluginScreenOrientation (3.0.1)
    CordovaSqliteStorage (2.6.0)
    Cordova.plugins.diagnostic (4.0.11)
    Es6PromisePlugin (4.2.2)
    PhonegapPluginBarcodescanner (8.0.1)
✔ Updating iOS native dependencies in 6.15s
  Found 3 incompatible Cordova plugins for ios, skipped install
    CordovaPluginFilechooser (1.2.0)
    CordovaPluginFilepath (1.5.1)
    CordovaPluginWhitelist (1.3.3)
✔ update ios in 6.31s
✔ update web in 14.21μp
Update finished in 6.543s
```

Capacitor version:
See ionic info output above

node version:
See ionic info output above

npm version:
See ionic info output above

CocoaPods version:
```
Alexs-MacBook-Pro:1794-rapid-inventory alexryltsov$ pod --version
Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
1.5.3
```

Steps to reproduce:
1) create new ionic 4/capacitor project
2) add Barcode cordova plugin
3) add QR Scanner cordova plugin
4) build, update plugins and open Android Studio with the project and try to build

Link to sample project:
N/A

**Comment by jcesarmobile** [comment]
This is a conflict between the plugins, not related to Capacitor, it also affects Cordova https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/510
It happens because phonegap-plugin-barcode scanner uses a modified zxing with all those symbols, but when installing the other one, the original zxing intent is launched and it doesn't include those symbols.
