### ISSUE TITLE
CameraPhoto.base64string is empty

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/capacitor#1469]
**Description of the problem:**

https://github.com/ionic-team/capacitor/blob/a04087d07ba18fd3314bb39d87d540d53ad49e33/core/src/core-plugin-definitions.ts#L324-L327

This property doesn't exist on the returned photo anymore:

```js
{
  dataUrl: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD…mwVwT0Oa8Z8Wyjw78aPD2rAYi1CNYpTjjnKH8uKpapjXY/9k=",
  webPath: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD…mwVwT0Oa8Z8Wyjw78aPD2rAYi1CNYpTjjnKH8uKpapjXY/9k=",
  format: "jpeg",
}
```

Have only tested on web, using PWA elements. Maybe it's related that the prop got renamed from `base64data` to `base64String`?

**Affected platform**
- [ ] Android
- [ ] iOS
- [ ] electron
- [x] web

**OS of the development machine**
- [ ] Windows
- [x] macOS
- [ ] linux

**Capacitor version:**

beta 22

**node version:**

8.16.0

**npm version:**

6.4.1

**Steps to reproduce:**

```ts
const picture = await Camera.getPhoto({
  source: CameraSource.Prompt,
  resultType: CameraResultType.Base64,
  quality: 90,
  allowEditing: true,
  height: 640,
  width: 640,
});

console.log(picture);
```

**Comment by jcesarmobile** [comment]
It was fixed here https://github.com/ionic-team/capacitor/pull/1455

**Comment by simonhaenisch** [comment]
Ok thanks, I’ll wait for the next release then!

**Comment by jcesarmobile** [comment]
Anyway, if you just want the base 64 string, you can just remove the “data:image/jpeg;base64,” part from the dataUrl
