### ISSUE TITLE
A way to disable Capacitor Config.json Server Url in Production

### ISSUE THREAD

**Issue by agrosner** [ionic-team/capacitor#1478]
Currently, when running the app with livereload enabled via:
```
ionic capacitor run ios --livereload
```
will insert into our `capacitor.config.json` a server url:
```
{
  "appId": "io.ionic.starter",
  "appName": "app",
  "bundledWebRuntime": false,
  "webDir": "www",
  "plugins": {
    "Keyboard": {
      "resize": "none"
    }
  },
****
  "server": {
    "url": "http://192.168.28.43:8100"
  }
****
}
```

This is problematic because if this is ever accidently committed to the repo, on launch from a production build from a CI server, it will still look for that URL, and users would be presented with a blank app screen that never loads.

This is a request to provide a way to turn off url searching, or provide a better way to set up live reloading without need for it to modify this file in the first place, possibly through the tooling in a different way.

**Comment by jcesarmobile** [comment]
Some people is using the url to point to real websites, so we can't disable it for production as it will break some use cases.
What about using a new "devUrl" that is only used while in development mode?

Note that this will require Ionic CLI changes as it's Ionic CLI the one that sets the server url, so probably better report it there. https://github.com/ionic-team/ionic-cli/issues

**Comment by agrosner** [comment]
good point, but yes, it should set a `devUrl` for live reloading, but wouldn't the url change based on a dev's ip address? I think this should be something if its set, is useable on any computer, since it could be checked in. Devs with different IP addresses would constantly be overwriting this line, cluttering git changelog. React Native, Flutter, and other tools do not require this field when live reloading, so maybe its just implementation details?

**Comment by diachedelic** [comment]
my solution is to generate `capacitor.config.json` on build:

```javascript
// generate_capacitor_config.js

const ip = require('ip')
const fs = require('fs')
const path = require('path')

const capacitorConfig = {
  // ...
  server: {},
}

const isHotspotting = (
  // Samsung A5 + Macbook
  ip.address() === '192.168.43.101' &&
  process.env.NODE_ENV !== 'production'
)

if (isHotspotting) {
  // support HMR on device
  capacitorConfig.server.url = 'http://192.168.43.101:8013'
}

const configPath = path.resolve(__dirname, 'capacitor.config.json')

fs.writeFileSync(configPath, JSON.stringify(capacitorConfig))
```
```javascript
// package.json
{
  "scripts": {
    "build": "export NODE_ENV=production && npm run config && vue-cli-service build --mode development && cap copy",
    "config": "node ./generate_capacitor_config.js"
  }
}
```

**Comment by agrosner** [comment]
that is an interesting though. the issue I'm describing is that it _modifies_ the capacitor config.json on build if you live reload, leading to accidental checkin to git, which essentially breaks the app if someones computer is not hosting the live reload server. 

There should be a separate file that is used that is ignored by git with any capacitor project. why not name it `capacitor.config.dev.json`? this file would be ignored on production builds anyways and so to keep it clean and allow you to configure the app differently if need be. This could go further to allow more configuration files based on `ng` environment.

**Comment by jupl** [comment]
There can also be an option like `-config` where one can specify a custom config that is different from `capacitor.config.json`.

**Comment by nklayman** [comment]
In [vue cli plugin capacitor](https://github.com/nklayman/vue-cli-plugin-capacitor), I modify the `capacitor.config.json` inside of the `android` or `ios` folder, as seen [here](https://github.com/nklayman/vue-cli-plugin-capacitor/blob/facb7050b89348478f0a6a865301a84d22b8a446/index.js#L159-L177). This allows me to have capacitor use the dev server url without having to modify the user's `capacitor.config.js`.

**Comment by eladcandroid** [comment]
Any news? I think it's very confusing and @agrosner solution sounds great..

**Comment by Cretezy** [comment]
Would it also be possible to only use `server.url`? Say I always want to load the public web app version, and not bundle the app in.

**Comment by jcesarmobile** [comment]
Yes, that's possible, but Apple will probably not approve your app if you do that.

**Comment by vance** [comment]
Any way to get this on a future milestone?

**Comment by dotrub** [comment]
Just don't check in your `capacitor.config.json`. Check in versions of it like `capacitor.config.dev.json` and `capacitor.config.prod.json`, and when you build, construct `capacitor.config.json` form the appropriate file. Then it doesn't matter if your `capacitor.config.json` gets rewritten, it won't get pushed to source control anyway.

**Comment by nodeful** [comment]
My NPM script:
```
"dev:android": "ionic capacitor run android --livereload --livereload-url=$(node -e 'console.log(require(\"ip\").address())'):8100"
```
