### ISSUE TITLE
Override capacitor config from the CLI

### ISSUE THREAD

**Issue by Iar0** [ionic-team/capacitor#1486]
Currently, my `webDir`option in `capacitor.config.json` is set to `src`: in this way I can develop on native using live-reload.

The problem is when I actually want to build the app. Because the output folder is `www`, I would like to change the `webDir` to `www` as well before running `ionic capacitor run ios`.

Apart from this specific use case, I think it would be generally good to have the option to override the configuration of `capacitor.config.json` from the cli. The actual workaround would be to update the file on the CI for the specific use case.

**Comment by jcesarmobile** [comment]
You don't have to set the `webDir` to `src` to use live reload. When using live reload, a new server object is added to the `capacitor.config.json` with an url pointing to the live reload server url.

We don't plan to add new commands, at least not in short term.

You can use `npx cap init` with `--web-dir` option to set the `webDir` again, but it's not optimal as it will also ask you for the app name and id again.
