### ISSUE TITLE
Proposal - make documentation links absolute instead of relative

### ISSUE THREAD

**Issue by ZaLiTHkA** [ionic-team/capacitor#1489]
>Note: I'm not using the provided issue template because this is regarding documentation, not project code.. If I need to adjust the structure of this description at all, please let me know.

While learning Capacitor from reading the docs (yes, I *actually do* RTFM 😁), I noticed a problem with two of the links on the [Using Cordova Plugins](https://capacitor.ionicframework.com/docs/basics/cordova/) page. Looking in the source MD file, the relevant line is defined as:

```markdown
Consult the [iOS](../ios/configuration) and [Android](../android/configuration) configuration guides for info on how to configure each platform.
```

Combined with the fact that this page gets deployed to `https://capacitor.ionicframework.com/docs/basics/cordova/`, this results in the following two URLs:

* iOS: `https://capacitor.ionicframework.com/docs/basics/ios/configuration`
* Android: `https://capacitor.ionicframework.com/docs/basics/android/configuration`

These URLs lead to a page that loads the main website theme and then gets stuck in an endless loop, which you can see quite easily in DevTools' Network tab and by the fact that the tab title keeps flipping between two different strings.

The generated links should *actually* be:

* iOS: `https://capacitor.ionicframework.com/docs/ios/configuration`
* Android: `https://capacitor.ionicframework.com/docs/android/configuration`

---

Now, while simply adding another `../` to the MD source link would technically resolve the redirect loop problem with *these* links, I feel it would be safer to switch them over to use absolute references, resulting in line 18 reading as:

```markdown
Consult the [iOS](/docs/ios/configuration) and [Android](/docs/android/configuration) configuration guides for info on how to configure each platform.
```

Furthermore, for the sake of consistency, I think all inter-document page links should follow the same logic.

Any thoughts/concerns with this idea? I'd be happy to do a PR for these, just wanted to chat about it a bit before diving down that rabbit hole. (:

**Comment by mlynch** [comment]
sure I see no problem with the change!

**Comment by dotNetkow** [comment]
hi @ZaLiTHkA - appreciate the issue! We definitely need to do this. Just a heads up, I've been making some serious changes to all Cordova-related instructions, and am about to merge them. This includes removing the page in question (/docs/basics/cordova). If you see any other relative links that we missed, please feel free to PR! Thank you.

**Comment by ZaLiTHkA** [comment]
@dotNetkow, that's cool.. I'll hang on for the moment then, I see a couple open docs-related PRs at the moment, so I'll keep an eye on those and chip in where I can. (:
