### ISSUE TITLE
Capacitor does not write compiler-flags to xcode

### ISSUE THREAD

**Issue by ronwondaal** [ionic-team/capacitor#1498]
Description of the problem:

Affected platform
- [ ] Android
- [x ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x ] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0-beta.17

node version: 11.10.0

npm version: 6.8.0

CocoaPods version: 1.6.1

Steps to reproduce:
Create a new project and add 'npm install --save cordova-sqlite-ext'.
Add a cordova iOS platform.
Add a capacitor iOS platform.
Check the Project-> Build Phases and search for sqlite3

First screenshot is from the **cordova** build, and the second screenshot is from the **capacitor** build. Notice the missing compiler flags in the capacitor build.
<img width="1280" alt="Screenshot 2019-05-13 at 22 37 31" src="https://user-images.githubusercontent.com/2373708/57652458-e7d9c700-75cf-11e9-9d4d-00d6fb87b18f.png">
<img width="1280" alt="Screenshot 2019-05-13 at 22 38 16" src="https://user-images.githubusercontent.com/2373708/57652460-e7d9c700-75cf-11e9-9d93-029794e76a7e.png">

Expected result:
On install Capacitor should write the compiler flags to xcode.

**Comment by jcesarmobile** [comment]
For the Cordova compatibility we make a conversion from plugin.xml to CocoaPods podspec and CocoaPods doesn't support per file compiler flags.
Can you check if it works if you set those compiler flags as project compiler flags instead of per file flags?
If not the solution should be to exclude the files with the flags and create a subspec for each one of them, but I don't think it's worth the effort.

**Comment by mlynch** [comment]
Do we modify their project even w/ the cordova compat?

**Comment by ronwondaal** [comment]
Hi @jcesarmobile, I just checked it with setting the flash per project, but that does not work.
The problem here is that the sqlite3.c is build using various compiler flags to enable different options on the sqlite database (like json1 extension). If you forget to copy-paste the compiler flag manually to xcode then database will be of completely different specifications.

**Comment by jcesarmobile** [comment]
@mlynch this is on the CordovaPlugins pod that is automatically generated, not on the user project.
I think it’s technically possible via cocoapod subspecs, but highly complex as it would need a subspec per file with flags and also removing those files from the main spec. Considering most plugins don’t do this I don’t think it’s worth the effort

**Comment by ronwondaal** [comment]
If not automatically writing the flags, would it be possible to generate some sort of notice during build to include the build flags or something like that? Otherwise we would need to check the plugin xml for every plugin we download if it contains build flags. Would be nice to get some sort of reminder if the plugin has any flags set.

**Comment by ronwondaal** [comment]
Okay @jcesarmobile, maybe this will work?
I checked the app.xcodeproj file of the cordova build, for the sqlite3.c file file it has the following entry:
```
6E59F8D4645642DCB128D243 /* sqlite3.c in Sources */ = {isa = PBXBuildFile; fileRef = B65169919F6E42F08F1CDFD6 /* sqlite3.c */; settings = {COMPILER_FLAGS = "-w -DSQLITE_THREADSAFE=1 -DSQLITE_DEFAULT_SYNCHRONOUS=3 -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_OMIT_DECLTYPE -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_TEMP_STORE=2 -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_JSON1 -DSQLITE_DEFAULT_PAGE_SIZE=1024 -DSQLITE_DEFAULT_CACHE_SIZE=2000"; }; };
```

When I check the Capacitor App->Pods->Pods.xcodeproj, it has this entry:
```
99D70E2471E7FFCFC84F2E09A9656A96 /* sqlite3.c in Sources */ = {isa = PBXBuildFile; fileRef = E9D751A0D95F014588EBB1300375B83D /* sqlite3.c */;};
```

I copied the settings: = {COMPILER_FLAGS = .....} from the cordova build into the capacitor Pods.xcodeproj file and now it compiles with the required flags.

Would it be possible to search the cordova plugin.xml files of installed plugins for these compiler flags, and if they have them, copy them into the Pods.xcodeproj file automatically? Just a simple search and add function when performing a ```npx cap sync```?

**Comment by jcesarmobile** [comment]
No, Capacitor doesn't do any writing or modifications of .xcodeproj files, it relies on CocoaPods for that.
