### ISSUE TITLE
Plugin Motion deprecated

### ISSUE THREAD

**Issue by silvelo** [ionic-team/capacitor#1499]
The plugin motion is not working because the events are deprecated. There are some solution for this (using capacitor without cordova plugins)

![image](https://user-images.githubusercontent.com/6561064/57707232-8cf3ae80-7667-11e9-86dc-a25a4d3354ee.png)

**Comment by jcesarmobile** [comment]
in which platform is this?
notice that it says "is deprecated on insecure origins", so not really deprecated, just needs https

**Comment by silvelo** [comment]
The warning is showing in android platform.

**Comment by jcesarmobile** [comment]
are you using livereload to test?

**Comment by silvelo** [comment]
Yes, I am using the default ionic configuration to run the server and use server url config to livereload

**Comment by silvelo** [comment]
@jcesarmobile Thanks for all, I try install apk without livereload and works perfect. There is any config to still use livereload and dont throw this warning?

**Comment by jcesarmobile** [comment]
I think you can use `--ssl` option in the serve command to use https instead of http, closing as it doesn't affect regular apps.
