### ISSUE TITLE
Use first arg to plugin:generate as plugin id

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#150]

**Comment by jcesarmobile** [comment]
first question is the name, so first arg should be the name too, right?

**Comment by buschtoens** [comment]
Even better yet, I would like to be able to pass all `inquirer` prompts as CLI options. This would allow for proper sriptability.

```sh
cap plugin:generate \
  --name capacitor-plugin-example
  --id capacitor-plugin-example
  --class Example
  --description "Example Plugin"
  --repo git+https://github.com/example/my-plugin.git
  --author Jan Buschtöns <jan.buschtoens@example.com>
  --license MIT
```

Assuming all required options are provided, the last `confirm` question should just be ditched.

**Comment by dwieeb** [comment]
@buschtoens Yeah these make way more sense as command line options. For Capacitor 3, we're planning on removing this command actually, in favor of a new package which will be used like this:

```
npm init @capacitor/plugin [options]
```

**Comment by dwieeb** [comment]
@buschtoens You can track [this issue](https://github.com/ionic-team/capacitor/issues/3413). I'd love to hear your feedback!
