### ISSUE TITLE
Capacitor doesn't play nicely with strictNullChecks

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/capacitor#1506]
When enabling `strictNullChecks` in the Typescript config, I have two issues with Capacitor.

For one, all Plugins are possibly undefined, even though they are proxied at runtime and will therefore never return `undefined`. I either need to use the `!` operator (non-null-assertion) which neither I nor my linter likes, or add a null-check, or use `as` syntax to overwrite the type (e. g. `const storage = Plugins.Storage as StoragePlugin`).

Second, I also get the following bug because of how the `PluginRegistry` is defined:

```
[ ERROR ]  TypeScript: node_modules/@capacitor/core/dist/esm/core-plugin-definitions.d.ts:3:4
           Property 'Accessibility' of type 'AccessibilityPlugin | undefined' is not assignable to string index type '{
           [prop: string]: any; }'.

      L2:  export interface PluginRegistry {
      L3:      Accessibility?: AccessibilityPlugin;
      L4:      App?: AppPlugin;
```

The issue is that all the Plugins are marked as optional (`?`) in `PluginRegistry`:

https://github.com/ionic-team/capacitor/blob/083b5bbe37dac25742b864ebb3bd18d28e333c93/core/src/core-plugin-definitions.ts#L3-L26

and thus they clash with its own type definition which doesn't allow `undefined` as a value:

https://github.com/ionic-team/capacitor/blob/083b5bbe37dac25742b864ebb3bd18d28e333c93/core/src/core-plugin-definitions.ts#L28-L31

To fix that, one could either add the `?`:

```ts
[pluginName: string]?: { 
  [prop: string]: any; 
} 
```

Or, what I think makes more sense, is to not mark all the plugins as optional, since they are always defined at runtime (by the proxy). That would not only fix my first issue, but also prevent people from trying to check whether a plugin is available by doing e. g. `if (Plugins.Storage) ...`.

**Comment by Bktechmasala** [comment]
capacitor share plugin fully worked prooved see video solved your problem https://youtu.be/5ulM4jedpB0
