### ISSUE TITLE
Separate update of plugins from update of core library?

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#151]
Right now `update` updates your core plugins _and_ Capacitor libraries. Down the road, managing those versions might be more sensitive. Should we make `update` less greedy?

**Comment by mlynch** [comment]
Okay yes, I think we need a separate command here, for a few reasons. The first is that we do get proper versioning for plugins through npm, but we don't use npm for our iOS or Android runtimes.

I'm wondering if we get rid of `update` and instead do:

`capacitor install` -> does the `install` of plugins after you `npm install` them.
`capacitor lib update` -> Updates Capacitor iOS/Android/Web

Thoughts?

**Comment by janpio** [comment]
OT (sorry): 

> but we don't use npm for our iOS or Android runtimes.

Why not? Is it all one package together with Capacitor itself?

**Comment by jcesarmobile** [comment]
He means we distribute in CocoaPods for iOS and JCenter/Gradle for Android. This way it's easier to integrate in native projects.

**Comment by jcesarmobile** [comment]
now that we have @capacitor/ios and @capacitor/android with the iOS/Android library code, this makes more sense as we npm install them on `npx cap add` and users might not be aware of it and might not know they will need to update those packages for getting latest version of the libraries and not just @capacitor/cli and @capacitor/core

**Comment by jcesarmobile** [comment]
Going to close as we now distribute the platforms in npm too, so users can update with npm update or npm install as any other package.
The update command only copies and set things to plugin to work, and warns if the platforms versions are older than the CLI version.
