### ISSUE TITLE
Camera webPath is incorrect if the server hostname ends with a slash

### ISSUE THREAD

**Issue by PaulJrdn** [ionic-team/capacitor#1517]
Description of the problem:
The `webPath` returned by the Camera plugin is incorrect if the configured hostname ends with a `/`.
For example, if the hostname is `localhost/`, `webPath` key will start with something like `capacitor://localhost//_capacitor_file_/private/var/mobile/...` instead of `capacitor://localhost/_capacitor_file_/private/var/mobile/...`

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: **beta-24**

node version: **v11.0.0**

npm version: **6.9.0**

CocoaPods version: **1.6.1**

Steps to reproduce:

1. Set the `server.hostname` key to `localhost/` in `capacitor.config.json`
2. Take a picture with `Camera.getPhoto()` from the Camera plugin
3. Check the `webPath` key contained in the result

**Comment by jcesarmobile** [comment]
hostname shouldn't include the `/`, why do you need it?

**Comment by mlynch** [comment]
Thanks, closing because hostname shouldn't have a slash in it.
