### ISSUE TITLE
Some plugin dependencies not found for android build

### ISSUE THREAD

**Issue by j3gb3rt** [ionic-team/capacitor#152]
Below is the message output for gradle after following capacitor docs then trying to build.

I used capacitor 0.95 to generate this. I am using android studio 3.0.1

Information:Gradle tasks [:app:assembleDebug]
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/cordova/plugins/Diagnostic.java
Error:(63, 29) error: package android.support.v4.os does not exist
Error:(73, 30) error: package android.support.v4.app does not exist
Error:(74, 30) error: package android.support.v4.app does not exist
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/de/appplant/cordova/plugin/badge/BadgeImpl.java
Error:(26, 32) error: package me.leolin.shortcutbadger does not exist
Error:(28, 39) error: package me.leolin.shortcutbadger does not exist
Error:(28, 1) error: static import only from classes and interfaces
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/de/appplant/cordova/plugin/notification/Notification.java
Error:(33, 30) error: package android.support.v4.app does not exist
Error:(34, 31) error: package android.support.v4.util does not exist
Error:(35, 31) error: package android.support.v4.util does not exist
Error:(52, 37) error: package android.support.v4.app does not exist
Error:(52, 1) error: static import only from classes and interfaces
Error:(53, 37) error: package android.support.v4.app does not exist
Error:(53, 1) error: static import only from classes and interfaces
Error:(79, 50) error: package NotificationCompat does not exist
Error:(88, 37) error: package NotificationCompat does not exist
Error:(97, 71) error: package NotificationCompat does not exist
Error:(446, 30) error: package NotificationCompat does not exist
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/de/appplant/cordova/plugin/notification/Options.java
Error:(28, 30) error: package android.support.v4.app does not exist
Error:(29, 64) error: package android.support.v4.app.NotificationCompat.MessagingStyle does not exist
Error:(30, 40) error: package android.support.v4.media.session does not exist
Error:(44, 37) error: package android.support.v4.app does not exist
Error:(44, 1) error: static import only from classes and interfaces
Error:(45, 37) error: package android.support.v4.app does not exist
Error:(45, 1) error: static import only from classes and interfaces
Error:(46, 37) error: package android.support.v4.app does not exist
Error:(46, 1) error: static import only from classes and interfaces
Error:(47, 37) error: package android.support.v4.app does not exist
Error:(47, 1) error: static import only from classes and interfaces
Error:(48, 37) error: package android.support.v4.app does not exist
Error:(48, 1) error: static import only from classes and interfaces
Error:(49, 37) error: package android.support.v4.app does not exist
Error:(49, 1) error: static import only from classes and interfaces
Error:(50, 37) error: package android.support.v4.app does not exist
Error:(50, 1) error: static import only from classes and interfaces
Error:(606, 5) error: cannot find symbol class Message
Error:(637, 23) error: package MediaSessionCompat does not exist
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/de/appplant/cordova/plugin/notification/action/Action.java
Error:(25, 30) error: package android.support.v4.app does not exist
Error:(111, 12) error: cannot find symbol class RemoteInput
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/de/appplant/cordova/plugin/localnotification/ClickReceiver.java
Error:(25, 30) error: package android.support.v4.app does not exist
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/de/appplant/cordova/plugin/notification/Manager.java
Error:(30, 30) error: package android.support.v4.app does not exist
Error:(44, 37) error: package android.support.v4.app does not exist
Error:(44, 1) error: static import only from classes and interfaces
Error:(413, 13) error: cannot find symbol class NotificationManagerCompat
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/de/appplant/cordova/plugin/notification/Builder.java
Error:(30, 30) error: package android.support.v4.app does not exist
Error:(31, 64) error: package android.support.v4.app.NotificationCompat.MessagingStyle does not exist
Error:(32, 55) error: package android.support.v4.media.app.NotificationCompat does not exist
Error:(33, 40) error: package android.support.v4.media.session does not exist
Error:(177, 47) error: package NotificationCompat does not exist
Error:(219, 56) error: package NotificationCompat does not exist
Error:(220, 38) error: cannot find symbol class Message
Error:(240, 57) error: package NotificationCompat does not exist
Error:(259, 52) error: package NotificationCompat does not exist
Error:(278, 54) error: package NotificationCompat does not exist
Error:(294, 52) error: package NotificationCompat does not exist
Error:(295, 52) error: package MediaSessionCompat does not exist
Error:(311, 56) error: package NotificationCompat does not exist
Error:(335, 57) error: package NotificationCompat does not exist
Error:(360, 50) error: package NotificationCompat does not exist
Error:(412, 31) error: package NotificationCompat does not exist
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/de/appplant/cordova/plugin/notification/util/AssetProvider.java
Error:(22, 34) error: package android.support.v4.content does not exist
Error:(24, 36) error: cannot find symbol class FileProvider
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/org/apache/cordova/camera/CameraLauncher.java
Error:(64, 34) error: package android.support.v4.content does not exist
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/org/apache/cordova/camera/CordovaUri.java
Error:(25, 34) error: package android.support.v4.content does not exist
/manhdev/capititor-tms-mobile/node_modules/@capacitor/cli/assets/capacitor-android-plugins/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocation.java
Error:(3, 50) error: package com.transistorsoft.locationmanager.adapter does not exist
Error:(4, 1) error: package com.transistorsoft.locationmanager.adapter.callback does not exist
Error:(5, 47) error: package com.transistorsoft.locationmanager.data does not exist
Error:(6, 48) error: package com.transistorsoft.locationmanager.event does not exist
Error:(7, 48) error: package com.transistorsoft.locationmanager.event does not exist
Error:(8, 48) error: package com.transistorsoft.locationmanager.event does not exist
Error:(9, 48) error: package com.transistorsoft.locationmanager.event does not exist
Error:(10, 48) error: package com.transistorsoft.locationmanager.event does not exist
Error:(11, 51) error: package com.transistorsoft.locationmanager.geofence does not exist
Error:(12, 47) error: package com.transistorsoft.locationmanager.http does not exist
Error:(13, 51) error: package com.transistorsoft.locationmanager.location does not exist
Error:(14, 49) error: package com.transistorsoft.locationmanager.logger does not exist
Error:(15, 52) error: package com.transistorsoft.locationmanager.scheduler does not exist
Error:(16, 51) error: package com.transistorsoft.locationmanager.settings does not exist
Error:(17, 47) error: package com.transistorsoft.locationmanager.util does not exist
Error:(35, 37) error: package com.google.android.gms.common does not exist
Error:(85, 18) error: cannot find symbol class TSCallback
Error:(953, 54) error: cannot find symbol class TSCallback
Error:(993, 13) error: cannot find symbol class BackgroundGeolocation
Error:(331, 53) error: cannot find symbol class TSCallback
Error:(368, 43) error: cannot find symbol class TSCallback
Error:(85, 77) error: cannot find symbol class TSCallback
Error:(100, 54) error: cannot find symbol class TSPlayServicesConnectErrorCallback
Error:(114, 34) error: package BackgroundGeolocation does not exist
Error:(123, 41) error: package BackgroundGeolocation does not exist
Error:(126, 41) error: package BackgroundGeolocation does not exist
Error:(146, 41) error: package BackgroundGeolocation does not exist
Error:(152, 41) error: package BackgroundGeolocation does not exist
Error:(154, 18) error: cannot find symbol variable Settings
Error:(160, 41) error: package BackgroundGeolocation does not exist
Error:(169, 41) error: package BackgroundGeolocation does not exist
Error:(172, 41) error: package BackgroundGeolocation does not exist
Error:(175, 41) error: package BackgroundGeolocation does not exist
Error:(178, 41) error: package BackgroundGeolocation does not exist
Error:(181, 41) error: package BackgroundGeolocation does not exist
Error:(184, 41) error: package BackgroundGeolocation does not exist
Error:(187, 41) error: package BackgroundGeolocation does not exist
Error:Execution failed for task ':capacitor-android-plugins:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by j3gb3rt** [comment]
@mlynch Looking through, all of the packages facing problems are cordova packages

**Comment by jcesarmobile** [comment]
Can you test https://github.com/ionic-team/capacitor/pull/154? I think it should fix this errors, or most of them

**Comment by mlynch** [comment]
Just merged #154, releasing 0.0.98 w/ this fix right now

**Comment by j3gb3rt** [comment]
Copying from slack:

> @max Most errors are gone now. There is only one remaining, should I make a new issue
> ```Error:(36, 1) A problem occurred evaluating project ':capacitor-android-plugins'.
> Could not get unknown property 'GOOGLE_API_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> ```
> (edited)
> 
> This is a cordova propery on the cordova-background-geolocation-lt plugin
> Looks like the properties are properly being used in the build.gradle for the plugin, but never defined > with an actual value

**Comment by j3gb3rt** [comment]
```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 26
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    google()
    jcenter()
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'org.apache.cordova:framework:7.0.0'
    // SUB-PROJECT DEPENDENCIES START
    implementation "com.google.android.gms:play-services-location:$GOOGLE_API_VERSION"
    implementation "com.android.support:appcompat-v7:$APPCOMPAT_VERSION"
    implementation "com.android.support:support-v4:24.1.1+"
    implementation "com.android.support:support-v4:26.+"
    implementation "com.android.support:support-v4:26.+"
    implementation "com.android.support:appcompat-v7:26.+"
    // SUB-PROJECT DEPENDENCIES END
}
```

**Comment by jcesarmobile** [comment]
The variables are now replaced with the default value, but only one occurrence.
Closing this in favour of https://github.com/ionic-team/capacitor/issues/215 as it's about the duplicate variables.
