### ISSUE TITLE
[Enhancement] New CLI command to list installed plugins and platforms

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/capacitor#1522]
Once you initially add each Platform (npx cap add android), there's no easy way to quickly see which platforms and plugins you have installed again at a later time.

Add new CLI command: **npx cap ls**  

List platforms installed, list installed cordova plugins, list all capacitor plugins and also cordova plugins that are skipped because they are incompatible. Something like the following, similar to how "npx cap add ios" is formatted:

**npx cap ls**

Found 2 platforms:
  iOS
  Android

Found 3 Cordova plugins:
  cordova-plugin-camera (4.0.3)
  cordova-plugin-device (2.0.2)
  cordova-plugin-file (6.0.1)

Found 5 incompatible Cordova plugins:
    cordova-plugin-ionic-keyboard (2.1.3)
    cordova-plugin-ionic-webview (4.0.1)
    cordova-plugin-splashscreen (5.0.2)
    cordova-plugin-statusbar (2.4.2)
    cordova-plugin-whitelist (1.3.3)

Found 2 Capacitor plugins:
  splash-screen

**Comment by mlynch** [comment]
I know sync/update do something similar but it would be nice to have an `ls` command like npm and cordova
