### ISSUE TITLE
Add support for deep linking in Electron apps

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#1528]
Along with the related `App` methods and events: https://discuss.atom.io/t/enable-deep-linking/27518

**Comment by dotnetdreamer** [comment]
hello. Any workaround for this ?

**Comment by IT-MikeS** [comment]
Might be able to close this and move future issues around electron to the community org.

**Comment by dotnetdreamer** [comment]
@dwieeb  why this issue is closed ?

**Comment by IT-MikeS** [comment]
@dotnetdreamer this was closed as it wont relate to this repo anymore as Electron is being moved to a community plugin, and this feature is implemented in that version

**Comment by dotnetdreamer** [comment]
OH...any documentation link ?

**Comment by IT-MikeS** [comment]
This is the community organization, the repo along with other community plugins and proposals live there. 

https://github.com/capacitor-community
