### ISSUE TITLE
cordova-plugin-privacyscreen causes compile errors on iOS

### ISSUE THREAD

**Issue by Mathyn** [ionic-team/capacitor#1531]
Description of the problem:

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
None

Capacitor version:
1.0.0-beta.25

node version:
v8.11.2

npm version:
5.6.0

CocoaPods version:
1.6.0

Steps to reproduce:

```
ionic start privacy-screen-bug blank --capacitor

ng build

npx cap add ios

npm install cordova-plugin-privacyscreen

ng build

npx cap sync ios

npx cap open ios
```

Next in xCode build the project for a device of your choosing

You will get the following compile error:

```
Declaration of 'CDVScreenOrientationDelegate' must be imported from module 'Cordova.CDVScreenOrientationDelegate' before it is required
```

This error is thrown on [this](https://github.com/devgeeks/PrivacyScreenPlugin/blob/master/src/ios/PrivacyScreenPlugin.m#L77) line.

**Comment by jcesarmobile** [comment]
I've sent a PR that fix the build problem, but be aware that the plugin will not correctly work as it uses the Cordova splash screen image names and Capacitor use different names, so it will just show a black screen. We can't fix that.
