### ISSUE TITLE
bug: extending PluginRegistry doesn't work like stated in the docs

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/capacitor#1547]
**Description of the problem:**

According to the "TypeScript Interface" section of https://capacitor.ionicframework.com/docs/plugins/, it should be possible to merge additional custom Plugins into the `PluginRegistry` interface:

```ts
declare module '@capacitor/core' {
	interface PluginRegistry {
		Echo: EchoPlugin;
	}
}
```

However this does not work, the type doesn't get merged in:

<img src="https://user-images.githubusercontent.com/3410759/58103328-157fcb00-7be3-11e9-8b7d-7cfde04e82c2.png" width="277">

Instead, the module has to be declared as `@capacitor/core/dist/esm/core-plugin-definitions`:

```ts
declare module '@capacitor/core/dist/esm/core-plugin-definitions' {
	interface PluginRegistry {
		Echo: EchoPlugin;
	}
}
```

<img src="https://user-images.githubusercontent.com/3410759/58103652-9fc82f00-7be3-11e9-8bf2-ef563e3e9e23.png" width="255">

TBH I don't exactly understand why the first version doesn't work, because `dist/esm/index.d.ts` exports everything from `./core-plugin-definitions` 🤷🏻‍♂️

---

Affected platform
- [x] Android
- [x] iOS
- [x] electron
- [x] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Capacitor version: beta.25

node version: 10.x

npm version: 6.4

**Comment by digaus** [comment]
@simonhaenisch I ran into this problem aswell but your solution did not work for me... any idea why?
see https://github.com/digaus/capacitor-background-fcm

(Plugin works fine but types not)

**Comment by simonhaenisch** [comment]
Nope sorry I don't... the workaround works for us with `v1.1.0` currently.

**Comment by digaus** [comment]
@jcesarmobile

Could you check this out?

**Comment by unitree-czk** [comment]
@jcesarmobile
I also encounter this problem.

**Comment by unitree-czk** [comment]
@simonhaenisch 
I find a method
for instance
import "capacitor-udp"
import { Plugins } from "@capacitor/core";

import the additional package before and you can find your plugin.

**Comment by unitree-czk** [comment]
@simonhaenisch
Another possibility is that, there might be additional node_modules files within each plugin
vscode might load @capacitor/core within these node_modules instead of the root one. 
Some plugins has the setting:
  "dependencies": {
    "@capacitor/core": "latest"
  },
This will cause the installation process to add additional node_modules files inside the plugin folder. 
If you delete those node_modules within the plugin folder. It might work.

**Comment by fzamperin** [comment]
I'm having exact same problema as @simonhaenisch posted, I just can't make ir appear in the type definition, although if I manually call a function the plugin provides works normally. What @unitree-czk stated but does not work too.

**Comment by dwieeb** [comment]
I believe I saw this as well, but upgrading TypeScript to 3.9+ fixed it for me.

**Comment by digaus** [comment]
@dwieeb 
I now have a problem when importing two custom plugins.

Only the first one gets the correct definition. Can you reproduce that?

**Comment by swernimo** [comment]
I ran into this same issue. Here's my Ionic Info. 

![Screen Shot 2021-02-23 at 4 19 33 PM](https://user-images.githubusercontent.com/11137058/108921004-ec2f7280-75f2-11eb-99ac-296d0221d010.png)

For me it was the order of imports. I was importing Plugins before I was importing the custom plugin. Lost about half a day before I found this thread.

**Comment by jcesarmobile** [comment]
`PluginRegistry` is now deprecated, the new way of generating plugins should (hopefully) not cause this kind of problems

https://capacitorjs.com/docs/plugins/creating-plugins
