### ISSUE TITLE
SplashScreen does not have web implementatio On Android

### ISSUE THREAD

**Issue by bubundas17** [ionic-team/capacitor#1550]
Description of the problem:
I am trying to build a capacitor app using Nuxt + Vuetify but when calling Any Device Specific Plugin it throwing an error  "Uncaught (in promise) <PluginName>does not have web implementation."

in my case, I am trying to hide the Splash screen But it shows an error On an Android Device
caught (in promise) SplashScreen does not have web implementation.
It is happening On an Android Device.

after looking around a bit, I came to realize in fact no API works! here I have a created a fresh Nuxt Project please have a look
[capacitor-nuxt-demo](https://github.com/bubundas17/capacitor-nuxt-demo)
I have also built the apk and uploaded here. 
[app-debug.apk](https://github.com/bubundas17/capacitor-nuxt-demo/raw/master/app-debug.apk)

Screenshot: [Screenshot](https://photos.app.goo.gl/BE2Nky6QxQkbSn387)
Please have a look. If you found the solution, please add a pull request. 
```
  import { Plugins } from '@capacitor/core';
  const { SplashScreen, StatusBar } = Plugins;
...
mounted(){
    try{
        SplashScreen.hide()
        StatusBar.setBackgroundColor({color: "#fff"})
    } catch(e){
        console.log(e)
    }
}
```

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

**Comment by jcesarmobile** [comment]
I have no experience with Nuxt + Vuetify, can you provide a sample app?

And can you also provide details about how are you running the app?

**Comment by bubundas17** [comment]
Well, Nuxt is a framework for vue.js it provides an easy to manage project structure. 
Let me create a new app; after that will provide a GitHub repo with app.

**Comment by bubundas17** [comment]
> I have no experience with Nuxt + Vuetify, can you provide a sample app?
> 
> And can you also provide details about how are you running the app?

Hi, I just uploaded the demo app. please have a look.
also here is the screenshot of the error.
[Screensort](https://photos.app.goo.gl/BE2Nky6QxQkbSn387)

**Comment by jcesarmobile** [comment]
thanks for the sample project, it was helpful

**Comment by bubundas17** [comment]
Thank you so much for the pull request. So this means making <head data-n-head=""> to <head> will solve the issue temporarily? If yes I am doing so now!

**Comment by jcesarmobile** [comment]
Yes, that should work too, the fix it to search for `</head>` when there is no `<head>` as I was not sure if all nuxt apps will have `<head data-n-head="">`.

**Comment by bubundas17** [comment]
yap all nuxt apps will have `<head data-n-head="">`,

but how can I update my current project to apply your changes?
because I tried deleting the android project and re-adding it. but it seems to not work.

**Comment by jcesarmobile** [comment]
The fix is not released yet, we are going to do a new release later today, so if you can wait a few hours you just will need to update the npm @capacitor/android version.

If you can't wait you can just manually apply the changes to the `JSInjector.java` class, it's inside the capacitor-android module in your Android Studio project.

**Comment by bubundas17** [comment]
Oh, Thank you so much! I'd rather wait. because there is still some time left in releasing our application. 
thank you for your effort.
Have a nice day!
