### ISSUE TITLE
Calling Storage.clear() breaks Stencil+Ionic app

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/capacitor#1566]
**Description of the problem:**

We have an app written in Stencil, using Ionic and wrapped with Capacitor. Our app calls `Storage.clear()` within the `componentWillLoad` hook of our root component `app-root`. On Android, this will cause the app to not work.

Instead, only an empty `<app-root></app-root>` element will exist in the DOM. There are no errors in any of the consoles.

**Affected platform**
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

**OS of the development machine**
- [ ] Windows
- [x] macOS
- [ ] linux

**Other information:** It works on iOS and web, haven't tested electron.

**Capacitor version:** 1.0.0

**node version:** latest 10.x

**npm version:** 6.4.1

**CocoaPods version:** ??

**Steps to reproduce:**

The issue is reproducible, so I created a simple app based on the app starter:
https://github.com/simonhaenisch/stencil-one-issues/tree/cap-clear-storage#readme

Instructions are in the readme.

**Comment by simonhaenisch** [comment]
Thanks!

**Comment by jcesarmobile** [comment]
Thanks to you for great issues with sample projects 😉
