### ISSUE TITLE
Document deeplinking

### ISSUE THREAD

**Issue by BorntraegerMarc** [ionic-team/capacitor#1567]
I understood from multiple sources that capacitor has some sort of deeplinking built in. But couldn't find any documentation for it.

So I wanted to raise an issue to check whether documentation for deeplinking is planned?

Cheers

**Comment by jcesarmobile** [comment]
There is another issue already
https://github.com/ionic-team/capacitor/issues/1284

But basically, you configure it as on any native app, and then use App plugin's `appUrlOpen` to listen for the intent that opens the app and use the url to do whatever you need (like navigate to that url)
