### ISSUE TITLE
LocalNotifications: introduce `startTime` for `every` (intervals)

### ISSUE THREAD

**Issue by haschu** [ionic-team/capacitor#1569]
It would be nice if one could schedule an interval notification (e.g. every day) but with a custom startTime.

Consider the following example:

```ts
 notifications: [{
   // ....
   schedule: {
     every: 'day'
    }
   // ....
 }]
```

This schedules a notification that triggers every day from NOW on. So if one would schedule a notification at 11:00 am, it would trigger the next day at 11:00 am, and so on...

What I'm looking for is something like "remind every day on 08:00 am", so for example:

 ```ts
 notifications: [{
   // ....
   schedule: {
     every: 'day',
     startDate: aSpecificStartDate
    }
   // ....
 }]
```

This should be fairly easy to implement. Looking at the [Android source](https://github.com/ionic-team/capacitor/blob/fb118f7bf7b0029ba7c7a11a538ac8edb02b4086/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java#L265), `startTime` needs to be configurable. (For the swift sources is's almost the same)

I would suggest to introduce a new property `startTime` for the `schedule` object. For me, this seems to be the most straightforward way, plus is stays backwards compatible.

Any thoughts on this? If you guys are okay with that solution I would give it a try and submit a pull request.

Or maybe am I missing something and there is a workaround for my problem?

**Comment by DonWolfram** [comment]
Hi, I got the same issue here. Daily reminders at a specific time would be awesome!

**Comment by ralscha** [comment]
Hi. You can already do that with `on`. 

"remind every day on 08:00 am"

```
        schedule: {
          on: {
            hour: 8,
            minute: 0
          }
        }
```

"remind every day on 11:00 am"

```
        schedule: {
          on: {
            hour: 11,
            minute: 0
          }
        }
```

"remind every month on the 17th on 7:00 am"

```
        schedule: {
          on: {
            day: 17
            hour: 7,
            minute: 0
          }
        }
```

**Comment by haschu** [comment]
@ralscha Ah, thanks! Going to try that out :)

**Comment by Jannnnnn** [comment]
I have a similar problem. The documentation is unfortunately insufficient. I would like to send notifications every Monday at 20:00, is that possible?

**Comment by ralscha** [comment]
@Jannnnnn Don't see a way to do that with the current implementation. A `startTime` for `every` would solve that. Or if `on` would support a `day of week` property, like cron.

**Comment by Jannnnnn** [comment]
@ralscha I went through the source code and come to the same conclusion. I have now switched back to the cordova plugin https://github.com/katzer/cordova-plugin-local-notifications

**Comment by askilondz** [comment]
Looking for the ability to schedule a notification on a specific day of the week every week like @Jannnnnn mentioned. Any other thoughts on how to achieve this?

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Or if you are really interested and have the knowledge to implement this, you can send a PR.

**Comment by slevy85** [comment]
I think this an important feature for notifications, this issue is also the same as #2752
