### ISSUE TITLE
Unable to inject Capacitor, Plugins won't work

### ISSUE THREAD

**Issue by mrodal** [ionic-team/capacitor#1572]
Description of the problem:
Hey, I just got started with capacitor, and Im getting this error on the Android studio console when running the app:
`E/Capacitor: Unable to inject Capacitor, Plugins won't work`

Is it normal?

Affected platform
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [X] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
4.12

node version:
10.15

npm version:
6.9

CocoaPods version:
-

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
Can you provide a little more information? like what steps did you follow

A sample app would be helpful

**Comment by mrodal** [comment]
Of course, its a vue app, so the type in ionic config is custom.
I created the app with vue-cli
I installed ionic as described here https://github.com/ionic-team/ionic/tree/master/vue
Executed `ionic init`
Then `ionic capacitor add android`
Added `"ionic:serve": "vue-cli-service serve",` to the package.json scripts
Executed `ionic capacitor run android --livereload`
Then ran the app on an emulator on android studio

Heres the app:
https://github.com/mrodal/reported-issues/tree/unable-inject-capacitor

**Comment by mrodal** [comment]
Ok, I looked for the code raising the error, and its on JSInjector.java:
![image](https://user-images.githubusercontent.com/20667544/58345359-86ff8980-7e2e-11e9-9cf5-6f76ec186518.png)

This is called first with the site's html, where the script is injected succesfully, and then again a couple of times with content like this:
`{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":1469886054}`

So it is actually working, but it is trying to also inject the scripts where it shouldnt

**Comment by jcesarmobile** [comment]
Yeah, Capacitor injects itself into html files searching for the head tag, but it's trying to inject itself into json files too showing that error message. Will fix it.

**Comment by mrodal** [comment]
If you think its a good solution, I can make a PR checking for the content type on WebViewLocalServer.java:

![image](https://user-images.githubusercontent.com/20667544/58347380-23785a80-7e34-11e9-8d98-0fbf90172e21.png)

**Comment by jcesarmobile** [comment]
Thanks, but I've already sent it.

**Comment by theunreal** [comment]
I am facing this issue, what is the workaround?

**Comment by jcesarmobile** [comment]
Should be a harmless message as it happens when it tries to inject itself to json or other type of files. Unless you plugins don't work, in that case create a new issue and provide more information.

**Comment by theunreal** [comment]
Thanks @jcesarmobile , I opened a new issue.

https://github.com/ionic-team/capacitor/issues/1595
