### ISSUE TITLE
not work browser api in ios with pwa

### ISSUE THREAD

**Issue by shomid** [ionic-team/capacitor#1576]
Description of the problem:

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [x] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

Capacitor version: 1.0.0

node version: 10.15.0

npm version: 6.9.0

Steps to reproduce:
for open url in external pwa use capacitor browser api to my ionic project.
this work correctly in android but not work in ios safari.
how to resolve this problem ?

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce.
