### ISSUE TITLE
[IPC] Connection::waitForSyncReply: Timed-out while waiting for reply, id = 72

### ISSUE THREAD

**Issue by ronwondaal** [ionic-team/capacitor#1581]
Description of the problem:
After switch to Ionic 4, running the app with either Cordova or Capacitor sometimes produces an 
```
[IPC] Connection::waitForSyncReply: Timed-out while waiting for reply, id = 72
```
which freezes the system and the app becomes unresponsive, a full exit and restart is required to get back to a working app. Any ideas how this error can be debugged to see which package/plugin/code is causing the issue?

Running in the simulator gives no errors, only on the real device.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Capacitor version: 1.0.0-beta.24

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
All I find is about apps using maps or beacons, but as you say, it also affects Cordova, so it’s probably a WKWebView or iOS bug.

**Comment by ronwondaal** [comment]
No, not really able to provide a sample, because it is totally random when it happens. I tried searching the iOS source code to see if the message is emitted somewhere so I can debug it, but haven't found anything.

**Comment by jcesarmobile** [comment]
This is a webkit bug, should be reported to Apple as only them can fix it. I've seen it even on Safari a few times (not the log but the freezing).
Searching for the error message, seems to be related to maps or beacons, so probably related to high memory usage.

**Comment by bingtao001** [comment]
only in iOS 12 appear ,I used WKWebView to load the url 'https://auth.alipay.com/login/homeB.htm?loginScene=7&goto=https://auth.alipay.com/login/taobao_trust_login.htm?target=https://buyertrade.taobao.com/trade/itemlist/list_bought_items.htm'

**Comment by Topiya** [comment]
I am also facing the same issue in my Ionic 4 app. Can you please provide any suggestion related to this?

**Comment by mateusduraes** [comment]
Something? Same error here

**Comment by stevenroussey-privicy** [comment]
Same error here.

**Comment by stevenroussey-privicy** [comment]
I found that we were using IAB with the shouldPauseOnSuspend: 'yes' setting, and it was affecting the capacitor webview as well. Changing to 'no' and I don't see the issue now.
