### ISSUE TITLE
CameraSource.Photos launches camera on PWA rather than image picker

### ISSUE THREAD

**Issue by andrew-motorcentral** [ionic-team/capacitor#1582]
Description of the problem:

When  launching Camera.getPhto with parameter, source: CameraSource.Photos, the camera modal pops up rather than an image picker.   Possibly related to #490 ?
 
Affected platform
- [x] Android
- [x] iOS
- [ ] electron
- [x] web

OS of the development machine
- [x] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0-beta.25

node version: v11.6.0

npm version: 6.5.0-next.0

CocoaPods version:

Steps to reproduce:
`		const image = await Plugins.Camera.getPhoto({
			quality: 100,
			allowEditing: false,
			resultType: CameraResultType.Base64,
			width: this.maxWidth,
			correctOrientation: true,
			source: CameraSource.Photos,
			saveToGallery: false
		});`

Link to sample project:

**Comment by bkarv** [comment]
I confirm I also have this issue, opens up camera not the photos in PWA.

**Comment by jcesarmobile** [comment]
Closing in favor of https://github.com/ionic-team/capacitor/issues/490, I've edited it to cover both cases.

**Comment by bkarv** [comment]
@jcesarmobile only concern #490 was over a year ago, any likelihood it will be sorted out in the near future?

**Comment by andrew-motorcentral** [comment]
@bkarv I've had to code in an alternative for PWA's using input type="file" for the time being.

I based my solution on @judgewest2000's example... Refer https://forum.ionicframework.com/t/ionic-4-pwa-camera/151148/3  and https://github.com/judgewest2000/IonicPwa  (I removed the capture attribute to trigger an action sheet prompt for image source).

**Comment by ikishanoza** [comment]
I am stii having same issue any updates on this ?
