### ISSUE TITLE
Camera PWA - Blackscreen

### ISSUE THREAD

**Issue by bkarv** [ionic-team/capacitor#1583]
Description of the problem:
I have followed the tutorial in https://capacitor.ionicframework.com/docs/guides/ionic-framework-app/ to setup a camera in my Ionic 4 App. I compile the app using the following command:
`ionic serve --devapp -c`

I then use DevApp to open the app on my Ipad Pro (iOS12) as well as android samsung s10. When I open the camera, I get a black screen and unable to take the photo. See below:

Ipad Pro
![IMG-0079](https://user-images.githubusercontent.com/10624315/58417127-32c30680-80c7-11e9-8e19-7d9a22e24d32.JPG)

Android Samsung S10
![Screenshot_20190527-220601_Ionic DevApp](https://user-images.githubusercontent.com/10624315/58418223-8f73f080-80ca-11e9-8075-20217a558409.jpg)

Thinking it was an issue with Ionic Devapp, I tried building the app and then opening it via a local webserver. I then get the following error ('unable to initialize camera). 
Ipad Pro & Android Samsung S9
![91719](https://user-images.githubusercontent.com/10624315/58417139-39517e00-80c7-11e9-912a-19d6dd7fca2a.jpg)

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [ X] web

OS of the development machine
- [ ] Windows
- [X ] macOS
- [ ] linux

Other information:
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.1
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Capacitor version:
   capacitor (Capacitor CLI) : 1.0.0
   @capacitor/core           : 1.0.0
npm version:
6.7.0

Steps to reproduce:

index.html,

I added the following in <head>
```
<script type="module" src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"></script>
  <script nomodule src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"></script>
```

main.ts

added
`
import { defineCustomElements } from '@ionic/pwa-elements/loader';`

Also at end of script

`defineCustomElements(window);`

Component.ts
```
import { Plugins, CameraResultType, CameraSource } from '@capacitor/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

async takePicture() {
    const image = await Plugins.Camera.getPhoto({
      quality: 100,
      allowEditing: false,
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Photos
    });

    this.photo = this.sanitizer.bypassSecurityTrustResourceUrl(image && (image.dataUrl));
  }
```

Appreciate any help on this, thanks in advance.

**Comment by jcesarmobile** [comment]
Capacitor apps won't work on DevApp because DevApp is only for Cordova.

When running with serve, you get a black screen because getUserMedia requires https urls to work, there is another issue already https://github.com/ionic-team/capacitor/issues/1577

**Comment by sharatdotinfo** [comment]
Is there any way to test capacitor apps on a real device? How do I know that the Camera API will actually take pics and display them?

**Comment by jcesarmobile** [comment]
Yes, you test the apps by running them. 
Make sure you have read the docs https://capacitor.ionicframework.com/docs/basics/workflow
