### ISSUE TITLE
Camera PWA Issues - Rear Facing Camera

### ISSUE THREAD

**Issue by bkarv** [ionic-team/capacitor#1589]
Description of the problem:
Taking photos with PWA browser funny things are happening with rear facing camera.

Ipad Pro 
Image is show as a mirror image (ie image is flipped).
Image in camera more rear facing(image is flipped):
![IMG-0081](https://user-images.githubusercontent.com/10624315/58451083-3c934b00-8155-11e9-88c0-606d718040a1.JPG)

Image once photo taken (correctly shown). 

![IMG-0082](https://user-images.githubusercontent.com/10624315/58451085-4026d200-8155-11e9-93aa-d0b6b5bb469e.JPG)

Android Samsung S9 fishbowl effect on rear face camera

![Screenshot_20190528-090842_Chrome](https://user-images.githubusercontent.com/10624315/58451104-5fbdfa80-8155-11e9-99e6-019dedf505ab.jpg)

Affected platform
- [X] Android
- [X] iOS
- [ ] electron
- [X] web

OS of the development machine
- [ ] Windows
- [X ] macOS
- [ ] linux

Other information:
Ionic:

ionic (Ionic CLI) : 4.12.0 (/usr/local/lib/node_modules/ionic)
Ionic Framework : @ionic/angular 4.3.0
@angular-devkit/build-angular : 0.13.8
@angular-devkit/schematics : 7.2.1
@angular/cli : 7.3.8
@ionic/angular-toolkit : 1.5.1

Capacitor version:
capacitor (Capacitor CLI) : 1.0.0
@capacitor/core : 1.0.0
npm version:
6.7.0

Steps to reproduce:

index.html,

I added the following in
```

<script type="module" src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"></script>
  <script nomodule src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"></script>

```
main.ts

added`
import { defineCustomElements } from '@ionic/pwa-elements/loader';`

Also at end of script
`
defineCustomElements(window);`

Component.ts

```
import { Plugins, CameraResultType, CameraSource } from '@capacitor/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

async takePicture() {
    const image = await Plugins.Camera.getPhoto({
      quality: 100,
      allowEditing: false,
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Photos
    });

    this.photo = this.sanitizer.bypassSecurityTrustResourceUrl(image && (image.dataUrl));
  }

```

**Comment by jcesarmobile** [comment]
This is a problem on pwa-elements, there is an issue open there already
https://github.com/ionic-team/pwa-elements/issues/11

BTW, you don't need to add the scripts and the import, if you add the scripts don't do the import, if you do the import don't add the scripts. (Recommended is the import)

**Comment by bkarv** [comment]
@jcesarmobile yes only talks about the mirror image, there is also a fishbowl issue in Android.

**Comment by bkarv** [comment]
Also noted on the script issue, thanks!
