### ISSUE TITLE
Is it feasible to write cross-platform plug-ins using kotlin-native?

### ISSUE THREAD

**Issue by liangzeng** [ionic-team/capacitor#1600]
Is it feasible to write cross-platform plug-ins using kotlin native?

**Comment by jcesarmobile** [comment]
I've just done a quick read about kotlin native, but looks like you can create a common frameworks to use in both iOS and Android, but then you'll need to create a regular Capacitor plugin that uses that framework, so you will still need a minimum java/swift/Objective-C amount of code.

**Comment by distante** [comment]
I was just thinking about this. 

There are use cases where both apps have to interact with a third party libraries (like Firebase, AdMob, AWS) and having a public interface that is respected in both iOS and Android could eventually prevent some bugs like https://github.com/capacitor-community/admob/issues/40
