### ISSUE TITLE
Feature request: Bluetooth Low Energy Plugin

### ISSUE THREAD

**Issue by untilbit** [ionic-team/capacitor#1601]
Capacitor need a robust BLE plugin.

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/23. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
