### ISSUE TITLE
How does capacitor detect which plattform is being used?

### ISSUE THREAD

**Issue by mrodal** [ionic-team/capacitor#1606]
Description of the problem:
Im on an emulator trying to save files with the Filesystem api, and its using the web implementation with indexeddb instead of saving the actual files on the device. How does capacitor decide which implementation to use?

Affected platform
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [X] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:

node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
Capacitor injects itself and the native plugins into the webview, so if there is native plugins code it will use the native implementation, if not, it will use the web implementation.

So, can you provide more information or a sample project to try to figure out why capacitor is not being injected in your app?

**Comment by mrodal** [comment]
Nevermind, I forgot to do 
`const { Filesystem } = Plugins;`
And was using Filesystem directly from capacitor/core
