### ISSUE TITLE
Impossible to use latest Firebase and Capacitor (use_frameworks!)

### ISSUE THREAD

**Issue by bandodebits** [ionic-team/capacitor#1609]
Description of the problem:

Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0
node version:
v10.15.3
npm version:
6.4.1
CocoaPods version:
1.7.0

Steps to reproduce:
Install the latest Firebase pod (pod 'Firebase') or Cordova Firabase Analytics, Cordova Firabase Analytics, etc.
**--- The error ---**
![Screen Shot 2019-05-30 at 15 29 48](https://user-images.githubusercontent.com/3931241/58664463-0dbbd700-8305-11e9-895b-8cb102b9e36f.png)

"'FirebaseCore/FirebaseCore.h' file not found"
**--- The reason ---**
use_frameworks! and the latest Firebase

Link to sample project:

**Comment by joseadame** [comment]
Why do you install Firebase with pod? I think that your Firebase dependency is in package.json.

**Comment by bandodebits** [comment]
The problem occurs by installing directly through Pods or by Cordova Plugins. The question is the latest versions of Firebase with the use_frameworks!, required by the Capacitor.

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce with current version of Firebase (6.3.0).
And when plugins use CocoaPods, they are generated as a static framework, so they don't have problems with `use_frameworks!` neither.
Capacitor plugins using Firebase as dependency should also be created as static, see [this](https://github.com/stewwan/capacitor-fcm/blob/master/CapacitorFCM.podspec#L18) as an example.
