### ISSUE TITLE
Bad performance with ionic caused by slow fetching of chunks

### ISSUE THREAD

**Issue by toxsickcoder** [ionic-team/capacitor#1612]
*Description of the problem*:

The application takes a long time to start. After profiling with Chrome, I noticed that the application lags around certain chunks, causing a very long boot time. 
The chunks in question are very small, max 4Kb. The chunks before and after the lagging ones are loaded normally. When running Ionic in the browser none of these issues occur.

*Affected platform*
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

*OS of the development machine*
- [X] Windows
- [ ] macOS
- [ ] linux

*Other information:*

Samsung Galaxy Tab S3 as test device (only one I got)

*Capacitor version:* 
v1.0.0

*node version:* 
v10.15.3

*npm version:* v
6.4.1

*Steps to reproduce:*

- Create a profile using Chrome while refreshing the app. 

Profile 1:
![image](https://user-images.githubusercontent.com/7610043/58694764-17405000-8394-11e9-8c0c-78f307d460eb.png)

Profile 2:
![image](https://user-images.githubusercontent.com/7610043/58694797-2a532000-8394-11e9-83e6-0b366e6ca556.png)

Profile 3:
![image](https://user-images.githubusercontent.com/7610043/58694891-5ec6dc00-8394-11e9-8f48-57a1b89c2d17.png)

Browser as baseline:
![image](https://user-images.githubusercontent.com/7610043/58694910-69817100-8394-11e9-9750-59913ecb747a.png)

*Link to sample project:*
https://github.com/osrs-tracker/osrs-tracker/

**Comment by toxsickcoder** [comment]
The chunks in question are very small, max 4Kb. The chunks before and after the lagging ones are loaded normally. When running Ionic in the browser none of these issues occur.

**Comment by toxsickcoder** [comment]
These are on a One plus 3:

Profile 1:
![image](https://user-images.githubusercontent.com/7610043/58763551-591bf280-855c-11e9-81ff-05e125ab0323.png)

Profile 2 :
![image](https://user-images.githubusercontent.com/7610043/58763562-6f29b300-855c-11e9-8444-91096e891b1a.png)

Profile 3:
![image](https://user-images.githubusercontent.com/7610043/58763567-82d51980-855c-11e9-84e4-6178196870ec.png)

**Comment by toxsickcoder** [comment]
After some checking I found out the performance issue is caused by ion-icon svg's in the app.component blocking the first lazy route (homepage). 
I don't know why they take so long to load though, because the svg's are local and tiny.

**Comment by toxsickcoder** [comment]
Same issue without svg's though. Probably bad performance because of the large amount of chunks.

**Comment by AndreasGassmann** [comment]
I'm looking into upgrading our app to use capacitor as well. Were you able to resolve this issue?

On a side note, I noticed that `ionic serve` is sometimes also very slow because of loading svgs. Are you sure this problem is directly related to capacitor and was it not an issue when you were using cordova?

**Comment by toxsickcoder** [comment]
> I'm looking into upgrading our app to use capacitor as well. Were you able to resolve this issue?
> 
> On a side note, I noticed that `ionic serve` is sometimes also very slow because of loading svgs. Are you sure this problem is directly related to capacitor and was it not an issue when you were using cordova?

I'll try it tonight on an older version of the app, see if it happens on Cordova as well. I guess if it will be slow on Cordova too that it's a Webview problem?

Keep you posted.

**Comment by toxsickcoder** [comment]
Hmm Cordova seems to have the same issue:

**Comment by toxsickcoder** [comment]
Hmm, Cordova seems to have the same issue:
![image](https://user-images.githubusercontent.com/7610043/59547584-6912d980-8f41-11e9-8650-a331c94de0d0.png)

I suppose it's not a Capacitor issue then. I'll close this issue for now until some evidence shows up that it's a Capacitor issue.

**Comment by AndreasGassmann** [comment]
It's strange, because for me it only seemed to be an issue when I do `ionic serve`, but not when it's loaded on a device. But I'll also check if the issue exists in our android app.

**Comment by Sitronik** [comment]
I faced the same problem, the screenshot in the example shows how the same file is loaded very slowly on android

![Снимок экрана 2022-01-24 в 16 24 53](https://user-images.githubusercontent.com/7203872/150801206-8f843008-bbed-43d0-98d0-205a05976ebb.png)

On iOS, the application loads within 2 seconds, on Android it takes 7 seconds, although the web application is initialized within 2 seconds, there are no problems in the browser

I analyzed the capacitor code, namely the WebViewLocalServer file, I managed to find out that the main code base was taken from here:
https://github.com/google/webview-local-server

And several functions were partially redefined and new code was added. These sources are already 7 years old, I assume that the problem may be in the webview-local-server, unfortunately I am not a Java developer and cannot write a new web server implementation using best practices, I think if this is done it will fly just like on iOS!
