### ISSUE TITLE
cordova-plugin-media-capture don't call callback functions

### ISSUE THREAD

**Issue by Watauinewa** [ionic-team/capacitor#1617]
**Description of the problem:**
I am using `cordova-plugin-media-capture` with and without `@ionic-native/media-capture`. It starts and records correctly, but when the operation ends `callback` functions are never called.

```
let options: CaptureImageOptions = { limit: 1 }
this.mediaCapture.captureVideo(options).then(
    (data: MediaFile[]) => console.log("OK", data),         // <--- This never is called
    (err: CaptureError) => console.error("ERROR", err)      // <--- This never is called
);
```
I have tried with cordova and it works

**Affected platform**
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

**OS of the development machine**
- [ ] Windows
- [ ] macOS
- [x] linux

**Other information:**
"cordova-plugin-file": "version": "6.0.1"
"cordova-plugin-media-capture": "version": "3.0.2"

**Capacitor version:**  1.0.0

**node version:** v10.16.0

**npm version:** 6.9.0

**Steps to reproduce:**
- Create a new project
```
ionic start videocapture blank --capacitor &&
cd videocapture &&
ionic integrations enable capacitor &&
npx cap init videocapture org.videocapture.app &&
ionic build &&
npx cap add android &&
npm install cordova-plugin-media-capture
```

- Edit `videocapturesrc/app/home/home.page.html`
```
<ion-content>
    <ion-button (click)="capture()">Capture</ion-button>
</ion-content>
```

- Edit `videocapturesrc/app/home/home.page.ts`
```
import { Component } from '@angular/core';

declare var navigator: any;

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {

    constructor() {}
  
    capture() {
        var captureSuccess = function( mediaFiles) {    // <-- this never is called
            console.log("OK", mediaFiles);
        }

        var captureError = function( error) {           // <-- this never is called
            console.log("ERROR", error);
        }

        navigator.device.capture.captureVideo(captureSuccess, captureError, { limit: 1 });
    }
}
```

- Build and run
```
ionic build &&
npx cap sync &&
npx cap copy &&
npx cap open android
```

- Record a video and ends the operation ( callback should be called but it's not)

**Link to sample project:**
[https://github.com/Watauinewa/capacitor-cordova-plugin-media-capture-test](https://github.com/Watauinewa/capacitor-cordova-plugin-media-capture-test)

Thanks.

**Comment by jcesarmobile** [comment]
Thanks for the sample project, I could reproduce.

It fails the first time, the second time you click the button it calls the error callback and then once you record the video the second time it works. Looking into it.

It works fine on iOS.
