### ISSUE TITLE
[Feature request] Positioning the toast element

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor#1621]
Hi,

I would like to be able to customize the toast position instead of forcing it to the bottom. In my case the user submits forms with a bottom button, and in case of error the toast appears under its finger, that's a bit weird I think.

I saw you were waiting for more requests on this (https://github.com/ionic-team/capacitor/pull/549#issuecomment-389980807). #crossingFingers 😄 

Thank you,

**Comment by veloce** [comment]
👍

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Or if you are really interested and have the knowledge to implement this, you can send a PR.

**Comment by sneko** [comment]
Please reopen :)

**Comment by jcesarmobile** [comment]
No, issues tagged with feature request are closed but tracked for reactions, so we can see which feature requests have more 👍 reactions. So if you want this feature add a 👍 reaction to your issue and if it gets a lot we might implement it.

Or you can send a pull request, that would speed things up.

**Comment by jcesarmobile** [comment]
removing feature request label since it's been implemented
