### ISSUE TITLE
Carlo and Webview2 Support

### ISSUE THREAD

**Issue by edwardchanjw** [ionic-team/capacitor#1622]
Feel free to open another forked Issue and closed this one, if any of following is accepted.

1. [Carlo](https://github.com/GoogleChromeLabs/carlo)
2. [Webview2](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2)

Simply support Carlo, and hope MS Edge Chromium support the base API is the best way though (MS Edge added certain feature, but unsure if they removed some)

Webview2 should be in [Github Sponsor Matching Funds](https://help.github.com/en/articles/about-github-sponsors). Please forward to Microsoft team. Working between capacitor API with Ionic Team and Microsoft team would be amazing. No easy but I am hoping it worked.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

Also, I've looked into both projects and they don't seem to have a very extensive API, so, as biggest goal of Capacitor is to provide a common API of plugins, most of core plugins won't be possible on those platforms as native plugins, so not sure if it's worth adding them as platforms.

They both should be able to use the web plugins without us doing anything.

**Comment by RichiCoder1** [comment]
WebView2 would have full access to UWP (if done right), so you'd be able to implement most of Capacitor's plugins "easily"
