### ISSUE TITLE
Network.addListener('networkStatusChange') ubg

### ISSUE THREAD

**Issue by UlisesCeca** [ionic-team/capacitor#1625]
Description of the problem:

The event `Network.addListener('networkStatusChange'...)` is fired every time the device is unlocked.

Affected platform
- [ X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [ X] linux

Other information:

Capacitor version: 1.0.0

node version: 10.16.0

npm version: 6.9.0

**Comment by solojuve1897** [comment]
Connected to https://github.com/ionic-team/capacitor/issues/1492

**Comment by jcesarmobile** [comment]
It's a duplicate of https://github.com/ionic-team/capacitor/issues/1492
