### ISSUE TITLE
Splash Screen scaling displays twice

### ISSUE THREAD

**Issue by johnwargo** [ionic-team/capacitor#1627]
Description of the problem:
I followed the instructions to configure splash screen scaling described here: https://capacitor.ionicframework.com/docs/apis/splash-screen/#configuration. When the app launches, Capacitor displays my splash screen scaled incorrectly, then adjusts to the scaling I have in my `capacitor.config.json` file:

```
"plugins": {
    "SplashScreen": {
      "launchShowDuration": 1000,
      "launchAutoHide": true,
      "androidSplashResourceName": "splash",
      "androidScaleType": "CENTER_CROP"
    }
  },
```
What I'm expecting is that the splash screen displays once, at the specified scale. 

Affected platform
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [X] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
5.0
node version:
10.15.3
npm version:
6.9.0
CocoaPods version:

Steps to reproduce:
As described above.

Link to sample project:

**Comment by jcesarmobile** [comment]
Unlike Cordova, which first shows a grey empty screen and then the splash screen, Capacitor is able to show the splash image from the beginning. But this "trick" is done by first showing theme with the image and then a native view showing the same image (similar to iOS where it first shows the launch storyboard and then the native image).
For some reason, in your case, the theme and the native view don't match and you see the transition from one to the another.

Would be helpful if you could provide the images you are using, or even better if you can provide a sample project.

Meanwhile, if the effect is very annoying for you, you can just remove `android:theme="@style/AppTheme.NoActionBarLaunch"` from the activity and then it will behave like Cordova apps, showing an empty screen before the native screen with the splash image.

**Comment by johnwargo** [comment]
@jcesarmobile I can make a sample project that shows this, but won't be able to do so for a couple of weeks. Can you delete these once you pull it down?
[splash-files.zip](https://github.com/ionic-team/capacitor/files/3267338/splash-files.zip)

**Comment by digaus** [comment]
I got the same issue... first splash is stretched and then shown correctly. Removing `android:theme="@style/AppTheme.NoActionBarLaunch"` is a good workarround though

**Comment by vfportero** [comment]
Having the same issue here wiht a Xiami MI A9SE (5.97-inch touchscreen display with a resolution of 1080x2340 pixels at a pixel density of 432 pixels per inch)

In my case Android is using the xxhdpi image that is this one: https://user-images.githubusercontent.com/1107782/65594996-1317ee00-df94-11e9-9d3c-b0aa3dc56e9e.png

And this is a GIF of the bad behaviour: 
![ezgif-4-b12117d410fc](https://user-images.githubusercontent.com/1107782/65595757-b4ec0a80-df95-11e9-93e3-8517a3497da4.gif)

As you can see, the first image show is deformed and then have a FOUC to the actual splash screen with `androidScaleType` set as `CENTER_CROP`

**Comment by KevinSleegers** [comment]
Any news on how to fix this?

I'm currently facing the same issue where the scaling of the initial splash image does not match the androidScaleType: CENTER_CROP I've defined in capacitor.config.json.

I also did try to remove the android:theme="@style/AppTheme.NoActionBarLaunch" but then the screen is white at first which looks odd since my splash screen is a red image. I haven't been able to find a way to change the background color since that would also kind of solve the issue at this moment.

Thanks in advance,
Kevin

**Comment by raycarter** [comment]
Same issue

**Comment by katzenjunge** [comment]
This issue still is a problem. Hoping this will get fixed :)

**Comment by peterpeterparker** [comment]
Instead of removing `android:theme="@style/AppTheme.NoActionBarLaunch"` as @jcesarmobile suggested, which would display a grey screen before booting your splash, I suggest to set a color for this first screen, in my case my splash screen main predominant background.

In file `android/app/src/main/res/values/styles.xml` modify `AppTheme.NoActionBarLaunch` with your background color, for example:

```
<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
  <item name="android:background">#230F29</item>
</style>
```

**Comment by digaus** [comment]
> This issue still is a problem. Hoping this will get fixed :)

Tried to fix it myself but it is quite hard or not even possible since you also would have to respect the `androidScaleType`.
Don't know if @jcesarmobile has an idea how to solve that.

**Comment by alexcroox** [comment]
@peterpeterparker nice work around with the background colour, thank you!

**Comment by IljaDaderko** [comment]
This becomes big issue if custom splash screen is made i.e. in iOS using lottie animation or something it initially shows that screen, then goes to second one that shows just static splash screen image. Is there a way to leave just one of them for easier and more consistent maintenance?

**Comment by jcesarmobile** [comment]
As I explained, the way it works is by first showing a theme with the image as background and then a native view showing the same image. This works fine for simple images, but for more complex images you'll have to tweak your theme, or try 9-Patch images.

With the OP's provided images, there is no noticeable change from the background image to the native image if using the default FIT_XY, but of course, the image is not properly sized.

Sadly the background image can't be sized, I think the people is getting confused because there was a `launch_splash.xml` file that had `android:scaleType="centerCrop"` on it.
But that file was not being used, and even if the user changes the theme to use the file, the `android:scaleType="centerCrop"` doesn't work on bitmaps, only on ImageViews (And ImageViews can't be used in a drawable).

We have removed that file to avoid this kind of confusions. (see https://github.com/ionic-team/capacitor/pull/2411).

Though, for the OP's provided images, I've found another way of displaying the image with the `"androidScaleType": "CENTER_CROP"` configuration option.
This way is showing the Splash image in full screen mode (available on Capacitor 1.5.0).

First in `capacitor.config.json` add

```
"androidScaleType": "CENTER_CROP",
"splashFullScreen": true
```
Then change the theme to also show in full screen
```
<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
    <item name="android:windowNoTitle">true</item>
    <item name="android:windowActionBar">false</item>
    <item name="android:windowFullscreen">true</item>
    <item name="android:background">@drawable/splash</item>
</style>
```


Going to close since we can't really do anything about this since the launch theme has this limitations, if it doesn't work for you try one of the mentioned workarounds:

1. Use FIT_XY
2. Remove the theme (a grey area will be shown instead)
3. Keep the theme but remove the image and use a color instead
4. Use a full screen theme and full screen splash screen.

**Comment by sofiageo** [comment]
@jcesarmobile 4 is not working. The drawable splash screen is always FIT_XY and ignores scaletype. The only way it worked was by replacing android:background with android:src - but then my app crashes from missing images:
```
android.content.res.Resources$NotFoundException: Drawable android:drawable/edit_text_material with resource ID #0x108029e
    Caused by: java.lang.RuntimeException: org.xmlpull.v1.XmlPullParserException: <internal>: <nine-patch> requires a valid 9-patch source image
```

**Comment by alex-steinberg** [comment]
I am migrating a Cordova app to Capacitor and am experiencing this problem using the exact same splash images the Cordova app renders perfectly. The workaround of adding a background colour works but it's a degradation. I'd love to see Lottie support in Capacitor, that would make this problem disappear and allow us to deliver the best possible user experience. Unfortunately, the Cordova plugin doesn't work: https://github.com/timbru31/cordova-plugin-lottie-splashscreen/issues/188

**Comment by daveshirman** [comment]
@peterpeterparker This is the only acceptable solution here.  It's honestly pathetic that this isn't mentioned in the Capacitor docs, as if it's a perfect replacement for Cordova splash out of the box.  

@mlynch @mhartington This is not good enough.  If you want people to trust Capacitor over Cordova, get these basic things right and make sure the docs are correct please.

For anyone else, this is my `capacitor.config.json`:
```
  "plugins": {
    "SplashScreen": {
      "launchAutoHide": false,
      "androidScaleType": "CENTER_CROP",
      "showSpinner": true,
      "splashFullScreen": false,
      "splashImmersive": false
    }
  }
```

My `styles.xml` - where the hex is the same colour as the background on my splash: 
```
    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">#4D4D4D</item>
    </style>
```

**NOTE**: I have autohide set to false as I programatically hide when I'm ready.

**Comment by Boby** [comment]
+1 on @daveshirman comment, this is happening on capacitor 2.0 also I find quite frustrating for basic stuffs but essential and we have to effortly fix this issue and yes I used the @peterpeterparker method for now and that is the only visible way of solving the issues.

**Comment by Nuajan** [comment]
Hi,
having the same issue and digged on Ionic Forums and find the following.
Just appying as follows it did the job for me, without setting up a color as @peterpeterparker  said (it also works but this seems to do the trick on a better way).
Check it out.

`<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="android:windowIsTranslucent">true</item>
    </style>`

By the way, i also agree such a simple thing to be so frustating. Maybe not the worst issue on an app but, if all customers have a similarity all around the world is for putting their eyes in such little things - just opening the app - before all the incredible effort behind the scenes.

Regards.

**Comment by losciur** [comment]
THANKS @Nuajan  
THIS IS THE SOLUTION FOR ME!

PS:  i also agree such a simple thing to be so frustating.

**Comment by danielehrhardt** [comment]
> Hi,
> having the same issue and digged on Ionic Forums and find the following.
> Just appying as follows it did the job for me, without setting up a color as @peterpeterparker said (it also works but this seems to do the trick on a better way).
> Check it out.
> 
> `<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar"> <item name="android:windowNoTitle">true</item> <item name="android:windowActionBar">false</item> <item name="android:windowFullscreen">true</item> <item name="android:windowContentOverlay">@null</item> <item name="android:windowIsTranslucent">true</item> </style>`
> 
> By the way, i also agree such a simple thing to be so frustating. Maybe not the worst issue on an app but, if all customers have a similarity all around the world is for putting their eyes in such little things - just opening the app - before all the incredible effort behind the scenes.
> 
> Regards.

Could you share your capacitor.config.json?

**Comment by danielehrhardt** [comment]
This is how i do it now:

app.component.ts
```
setTimeout(() => {
      SplashScreen.hide();
    }, 300);
```
styles.xml
```
<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">

    </style>

```
capacitor.config.json
```
"plugins": {
    "SplashScreen": {
      "launchAutoHide": false,
      "showSpinner": true,
      "androidSpinnerStyle": "small",
      "iosSpinnerStyle": "small",
      "spinnerColor": "#ffffff",
      "backgroundColor": "#21252dff",
      "splashFullScreen": true,
      "androidScaleType": "CENTER_CROP",
      "splashImmersive": false
    }
  },
```

This was with the native Android start Animations the smoothest way.

**Comment by maxime-guyot** [comment]
The solution of @Nuajan cause crash on android 8 if you set `android:screenOrientation="portrait` on AndroidManifest.xml
Exception : `java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation`

To solve problem you should : 
- remove `android:screenOrientation="portrait` on AndroidManifest.xml
- set orientation on MainActivity.java : 
```java
if (android.os.Build.VERSION.SDK_INT > Build.VERSION_CODES.O) {
    setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
}
```

**Comment by tronix99** [comment]
> Hi,
> having the same issue and digged on Ionic Forums and find the following.
> Just appying as follows it did the job for me, without setting up a color as @peterpeterparker said (it also works but this seems to do the trick on a better way).
> Check it out.
> 
> `<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar"> <item name="android:windowNoTitle">true</item> <item name="android:windowActionBar">false</item> <item name="android:windowFullscreen">true</item> <item name="android:windowContentOverlay">@null</item> <item name="android:windowIsTranslucent">true</item> </style>`
> 
> By the way, i also agree such a simple thing to be so frustating. Maybe not the worst issue on an app but, if all customers have a similarity all around the world is for putting their eyes in such little things - just opening the app - before all the incredible effort behind the scenes.
> 
> Regards.

This Worked! Thank you

**Comment by DuebassLei** [comment]
When the app launches, ,I found twice splash.I fixed： 

```
    <!-- default -->
    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">@drawable/splash</item>
    </style>
  
    <!-- modified-->
    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">@null</item>
    </style>
```

**Comment by SnowBases** [comment]
So frustrating, It takes me the whole night to fix this.

**Comment by danielehrhardt** [comment]
> So frustrating, It takes me the whole night to fix this.

How did you fixed it?

**Comment by vishnuvardhana** [comment]
After spending a lot of time on this I found solution for my app. 

In AndroidManifest.xml use   `android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"`  rather than using NoActionBar. 

Cheers,

**Comment by AE1NS** [comment]
@danielehrhardt 
> btw. between the App Start and the Splash Screen and the WebView load there is a quick blank background with a Color that i am not able to change. Do you know where I can change that?

capacitor.config.json
```
{
    ...
    // Either for android + ios
    "backgroundColor": "#123456",
    // Or specific
    "android": {
        "backgroundColor": "#123456"
    },
    "plugins": {
        "SplashScreen": {
            ...
            "backgroundColor": "#123456"
        }
    }
}
```

**Comment by digaus** [comment]
> Hi,
> having the same issue and digged on Ionic Forums and find the following.
> Just appying as follows it did the job for me, without setting up a color as @peterpeterparker said (it also works but this seems to do the trick on a better way).
> Check it out.
> 
> `<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar"> <item name="android:windowNoTitle">true</item> <item name="android:windowActionBar">false</item> <item name="android:windowFullscreen">true</item> <item name="android:windowContentOverlay">@null</item> <item name="android:windowIsTranslucent">true</item> </style>`
> 
> By the way, i also agree such a simple thing to be so frustating. Maybe not the worst issue on an app but, if all customers have a similarity all around the world is for putting their eyes in such little things - just opening the app - before all the incredible effort behind the scenes.
> 
> Regards.

This might be upvoted a lot, but I think it is a bad solution. This solution results in the behaviour shown in this comment: https://github.com/ionic-team/capacitor/issues/2992#issuecomment-689815690

On slower devices the user does not get any visual feedback if the application has started or not.  

So either we should show a loading icon before the splashscreen or just a blank page. Optimally the splash screen should not be scaled differently at first but I have not found a solution for that.

**Comment by SnowBases** [comment]
@danielehrhardt 

This is only my workaround in Android:

1. AndroidManifest.xml, 

> application: **android:theme="@style/AppTheme"** 
> activity: **android:theme="@style/AppTheme.NoActionBar"**

```
<application
	android:allowBackup="true"
	android:icon="@mipmap/ic_launcher"
	android:label="@string/app_name"
	android:roundIcon="@mipmap/ic_launcher_round"
	android:supportsRtl="true"
	android:theme="@style/AppTheme">

	<activity
		android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
		android:name="com.snowbases.workoutapp.MainActivity"
		android:label="@string/title_activity_main"
		android:theme="@style/AppTheme.NoActionBar"
		android:launchMode="singleTask">
```

2. res > values > styles.xml ( this one will show immediately after you open the app )

```
<!-- Base application theme. -->
<style name="AppTheme" parent="AppTheme.NoActionBar">
	<!-- Customize your theme here. -->
	<item name="colorPrimary">@color/colorPrimary</item>
	<item name="colorPrimaryDark">@color/colorPrimaryDark</item>
	<item name="colorAccent">@color/colorAccent</item>
</style>

<style name="AppTheme.NoActionBar" parent="Theme.AppCompat">
	<item name="windowActionBar">false</item>
	<item name="windowNoTitle">true</item>
	<item name="android:background">@drawable/splash</item>
	<item name="android:navigationBarColor">@android:color/white</item>
	<item name="android:windowLightNavigationBar">true</item>
	<item name="android:statusBarColor">@android:color/white</item>
</style>
```

This line you can change yourself, I'm using this holo_orange_light, holo_red_dark for testing.
```
<item name="android:navigationBarColor">@android:color/white</item>
<item name="android:windowLightNavigationBar">true</item>
<item name="android:statusBarColor">@android:color/white</item>
```

3. changing capacitor code, Splash.java ( this one will run in Bridge.java for the second time )

You can search this:
**Splash.showOnLaunch((BridgeActivity) context, this.config);**

show():

![image](https://user-images.githubusercontent.com/31583701/97110363-c2814000-1713-11eb-8b28-324d8adae8f4.png)

```
Window window = a.getWindow();
window.setStatusBarColor(Color.RED);
window.setNavigationBarColor(Color.BLUE);
```

buildViews()

![image](https://user-images.githubusercontent.com/31583701/97110695-9c5c9f80-1715-11eb-88c0-f61d21f88cc4.png)

4. and the last line was in capacitor.config.json (this is important)

capacitor.config.json

```
"plugins": {
	"SplashScreen": {
	  "launchShowDuration": 60000
	}
}
```

launchShowDuration is set to 60sec but in this case, it's hiding the splash screen it in my home page ts, so it will immediately hide after the page is ready

![image](https://user-images.githubusercontent.com/31583701/97110764-02e1bd80-1716-11eb-9166-b51a20e544fc.png)
![image](https://user-images.githubusercontent.com/31583701/97110799-2c024e00-1716-11eb-8aca-d83f3e6320be.png)

using statusbar overlay true:
![image](https://user-images.githubusercontent.com/31583701/97110847-5b18bf80-1716-11eb-879b-b73437b7cf36.png)

force the toolbar component to have some padding for the status bar
![image](https://user-images.githubusercontent.com/31583701/97110866-78e62480-1716-11eb-85d1-ec895b5541a9.png)

Please note that I'm using https://github.com/fagundes/cordova-plugin-navigationbar to change the in-app navigation bar color to white.


Result: 

![testing](https://user-images.githubusercontent.com/31583701/97111211-82708c00-1718-11eb-82af-165054e517b0.gif)

**Comment by aparajita** [comment]
Just an FYI, hopefully this week I'll be releasing a new splash screen plugin that will let you use layouts as the splash screen and add your own custom animation code without having to hack Capacitor.

**Comment by aparajita** [comment]
In addition to **tons** of other features. 😁

**Comment by dwieeb** [comment]
@aparajita Looking forward to seeing your implementation! When it's ready, would you be willing to work with us (Capacitor team) to incorporate your new plugin into the official Splash Screen plugin for Capacitor 3?

**Comment by aparajita** [comment]
> When it's ready, would you be willing to work with us (Capacitor team) to incorporate your new plugin into the official Splash Screen plugin for Capacitor 3?

@dwieeb I thought you'd never ask. 😁  Of course, I have been designing it all along to be a replacement for the current splash screen machinery.

**Comment by aparajita** [comment]
> I have been designing it all along to be a replacement for the current splash screen machinery.

Not that I expected it would — I'm not that conceited — but I wanted it to be as compatible as possible with the existing plugin with as few breaking changes as possible to the config.

**Comment by aparajita** [comment]
Hey @dwieeb, is the new config API fairly stable?

**Comment by katzenjunge** [comment]
The original behaviour this issue was about (splash screen flickering/showing twice) was fixed for me by updating to Capacitor 2.4.2. See these release notes: https://github.com/ionic-team/capacitor/blob/2.x/CHANGELOG.md#242-2020-09-24

I have removed all workarounds now and it's looking great! Thanks for everyone participating in this thread and sharing solutions though. 😊

@aparajita That's great news, looking forward to it!

**Comment by danielehrhardt** [comment]
> The original behaviour this issue was about (splash screen flickering/showing twice) was fixed for me by updating to Capacitor 2.4.2. See these release notes: https://github.com/ionic-team/capacitor/blob/2.x/CHANGELOG.md#242-2020-09-24
> 
> I have removed all workarounds now and it's looking great! Thanks for everyone participating in this thread and sharing solutions though. 😊
> 
> @aparajita That's great news, looking forward to it!

Does not work for me

**Comment by danielehrhardt** [comment]
> Just an FYI, hopefully this week I'll be releasing a new splash screen plugin that will let you use layouts as the splash screen and add your own custom animation code without having to hack Capacitor.

Did you released it somewhere?

**Comment by aparajita** [comment]
@danielehrhardt Coming later this week hopefully. The code is done, I have to document everything and make some examples.

**Comment by AE1NS** [comment]
@aparajita Am I right, that your plugin does not effect the native splash image in the first second when launching the app? One Android problem is the stretched image in the first second on certain devices (Pixel 4, Galaxy S20, ...), so I removed the image in my case and set a background color. After this second, the Capacitor Splashscreen or your Splashscreen take over and shows the image properly. But the initial problem with this stretched image cant be fixed, neither with your plugin, right?

**Comment by aparajita** [comment]
The only way to fix it on Android is to manually set the content view in `onCreate` in MainActivity.java. That way you have control over the sizing of the image.

The new splash screen plugin is going to be published soon (really), and once you have that, I recommend using a layout on Android rather than an image, you get much more control over positioning and sizing.

**Comment by tellybrown** [comment]
You might try my method by moving to a vector for your splash screen.  There is a builtin tool in android studio to convert svg to vector but <text> elements wont convert.

splash.xml  - remove png
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:layout_height="match_parent" android:layout_width="match_parent">
<item android:gravity="center"
      android:width="400dp"
      android:height="400dp">
    <vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt"
        android:viewportWidth="400"
        android:viewportHeight="400"
        android:fillColor="#303030"
        android:gravity="center"
        android:width="400dp"
        android:height="400dp">
<yourVector/>
    </vector>
</item>
</layer-list>
```

capacitor.config.json
```
    "SplashScreen": {
      "backgroundColor": "#303030",
      "launchShowDuration": 30000,
      "splashImmersive": "false",
      "splashFullScreen": "false"
    },
```

app.component.ts
```
    @HostListener('document:readystatechange', ['$event'])
    onReadyStateChanged(event) {
        if (event.target.readyState === 'complete') {
            SplashScreen.hide();
        }
    }
```

**Comment by sergiuturus** [comment]
Hi, I added "androidScaleType": "CENTER_CROP" but it seems like my splash image is still stretched. Any idea why?

**Comment by bitflower** [comment]
You want this solution from above: https://github.com/ionic-team/capacitor/issues/1627#issuecomment-633693708

I just tried it and also still had a streched image.

**Comment by sergiuturus** [comment]
EDIT: I added "androidScaleType": "CENTER_CROP")  and I thought the splash image was stretched but it seems like the loading spinner is not being centered. Here are 2 screenshots from 2 apps: capacitor (not centered) and cordova. 

https://imgur.com/woYrD1p
https://imgur.com/a/i0p3kJA

Any idea why this is happening?

**Comment by AE1NS** [comment]
@aparajita Did you/the capacitor team already find a solution for the initial stretched splashscreen issue to be release with capacitor 3?

**Comment by preeti6695** [comment]
> So frustrating, It takes me the whole night to fix this.

can you tell me solution for this?

**Comment by preeti6695** [comment]
please give me some refrences

**Comment by thesurya9** [comment]
> @peterpeterparker This is the only acceptable solution here. It's honestly pathetic that this isn't mentioned in the Capacitor docs, as if it's a perfect replacement for Cordova splash out of the box.
> 
> @mlynch @mhartington This is not good enough. If you want people to trust Capacitor over Cordova, get these basic things right and make sure the docs are correct please.
> 
> For anyone else, this is my `capacitor.config.json`:
> 
> ```
>   "plugins": {
>     "SplashScreen": {
>       "launchAutoHide": false,
>       "androidScaleType": "CENTER_CROP",
>       "showSpinner": true,
>       "splashFullScreen": false,
>       "splashImmersive": false
>     }
>   }
> ```
> 
> My `styles.xml` - where the hex is the same colour as the background on my splash:
> 
> ```
>     <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
>         <item name="android:background">#4D4D4D</item>
>     </style>
> ```
> 
> **NOTE**: I have autohide set to false as I programatically hide when I'm ready.

Thanks brother <3

**Comment by justindfunk** [comment]
Same issue.  For some reason I couldn't figure out how to hide the splash screen from the code, but by tweaking a few backgrounds based on the responses here, I got it close enough to what I wanted.  Not perfect, just close enough.

And yes, this whole thing is completely ridiculous.  Literally every person who makes an app on this platform has to go through the splash screen, so how is this even still an issue?  How was it ever released in this state in the first place?

Everything I've gone through today trying to solve this, and a few other things that should be fundamental, it's finally convinced me to abandon Ionic completely and go check out React Native.  I've been using Ionic for years and it's just been one disaster after another with bad documentation, constant refactoring and dependency conflicts, and absolutely garbage support from the Ionic team.  Good riddance.

**Comment by zLinz** [comment]
> Hi,
> having the same issue and digged on Ionic Forums and find the following.
> Just appying as follows it did the job for me, without setting up a color as @peterpeterparker said (it also works but this seems to do the trick on a better way).
> Check it out.
> 
> `<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar"> <item name="android:windowNoTitle">true</item> <item name="android:windowActionBar">false</item> <item name="android:windowFullscreen">true</item> <item name="android:windowContentOverlay">@null</item> <item name="android:windowIsTranslucent">true</item> </style>`
> 
> By the way, i also agree such a simple thing to be so frustating. Maybe not the worst issue on an app but, if all customers have a similarity all around the world is for putting their eyes in such little things - just opening the app - before all the incredible effort behind the scenes.
> 
> Regards.

this resolve my problem. thanks bro!

**Comment by syuraj** [comment]
How about new drawable?

`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:drawable="@color/ic_launcher_background"/>
    <item
        android:width="200dp"
        android:height="200dp"
        android:drawable="@drawable/ic_launcher_foreground"
        android:gravity="center" />
</layer-list>`

and use it like this
`<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">@drawable/bootsplash</item>
    </style>`

**Comment by johannds** [comment]
Try this on for size in your capacitor config: 

```
 "plugins": {
  	"SplashScreen": {
			"launchAutoHide": false,
			"androidScaleType": "FIT_XY",
			"backgroundColor": "#000000",
			"showSpinner": false,
                         "splashFullScreen": false,
                         "splashImmersive": false
		}
  },
```

IMPORTANT: DO NOT FORGET TO UPDATE `src/main/assets/capacitor.config.json` WITH THE SAME VALUES.

This made the issue go away on my side. I suspect there is an issue somewhere in the code that deals with offsets when the screen is fullscreen or immersive.

**Comment by liho00** [comment]
> Try this on for size in your capacitor config:
> 
> ```
>  "plugins": {
>   	"SplashScreen": {
> 			"launchAutoHide": false,
> 			"androidScaleType": "FIT_XY",
> 			"backgroundColor": "#000000",
> 			"showSpinner": false,
>                          "splashFullScreen": false,
>                          "splashImmersive": false
> 		}
>   },
> ```
> 
> IMPORTANT: DO NOT FORGET TO UPDATE `src/main/assets/capacitor.config.json` WITH THE SAME VALUES.
> 
> This made the issue go away on my side. I suspect there is an issue somewhere in the code that deals with offsets when the screen is fullscreen or immersive.
> 
> ALSO IMPORTANT: you might want to turn `launchAutoHide` on, unless you manually hide the splash screen in code.

tried, same scaling twice

**Comment by sathishsundar05** [comment]
> Hi,
> having the same issue and digged on Ionic Forums and find the following.
> Just appying as follows it did the job for me, without setting up a color as @peterpeterparker said (it also works but this seems to do the trick on a better way).
> Check it out.
> 
> `<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar"> <item name="android:windowNoTitle">true</item> <item name="android:windowActionBar">false</item> <item name="android:windowFullscreen">true</item> <item name="android:windowContentOverlay">@null</item> <item name="android:windowIsTranslucent">true</item> </style>`
> 
> By the way, i also agree such a simple thing to be so frustating. Maybe not the worst issue on an app but, if all customers have a similarity all around the world is for putting their eyes in such little things - just opening the app - before all the incredible effort behind the scenes.
> 
> Regards.

That really works, great work

**Comment by Pacjonek** [comment]
Shame and disgrace that AFTER MORE THAN A YEAR (sic!) since the bug was reported, it still hasn't been resolved! I cannot belive it. I would never in my life buy premium service from a company that so blatantly ignores problems in its own most important child. I totally understand why react-native or flutter is considered better and more developers work with it

> I am seeing the same issue as well. The only workaround I found was setting the initial screen to a static background color and not showing the splash image.
> 
> ```
> <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
>     <item name="android:statusBarColor">#000000</item>
>     <item name="android:navigationBarColor">#000000</item>
>     <item name="android:background">#000000</item>
> </style>
> ```
> 
> The drawback is that you get a blank screen without an image for about a second. If anyone has a better workaround let me know.

The above workaround does not work with the plugin from barcode scanner which require transparent background. 
My workaround (the drawback with blank white screen still exist there but it work):
```xml
    <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.NoActionBar">
        <item name="android:windowActionBar">false</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowBackground">@android:color/white</item>
    </style>
    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar"></style>
```

**Comment by bitflower** [comment]
@Pacjonek Opensource works the other way round: be grateful for what you got not be thankless for what you didn‘t get.

**Comment by Pacjonek** [comment]
I'm not talking about a project of a few developers working on an extra project after hours. I'm talking about the main project of a not-so-small corporation that willingly undertook to create its own version of Cordova because they found that Cordova is not good enough and then they stopped to fix very important bugs.
EOT.

**Comment by Pacjonek** [comment]
@bitflower I'm not talking about a project of a few developers working on an extra project after hours. I'm talking about the main project of a not-so-small corporation that willingly undertook to create its own version of Cordova because they found that Cordova is not good enough and then they stopped to fix very important bugs.
EOT.

**Comment by danielehrhardt** [comment]
> @bitflower I'm not talking about a project of a one/few developers working on an extra project after hours. I'm talking about the main project of a not-so-small corporation that willingly undertook to create its own version of Cordova because they found that it is not good enough. 
> And then they stopped fixing bugs... for years
> EOT.

Hire a professional developer. Let's fix him this and then make a pull request.

**Comment by mlynch** [comment]
@Pacjonek We actively work on and maintain Capacitor, so I'm not sure what you're talking about. Clearly the workarounds in this issue aren't sufficient for people in here but this is a tricky one to get right. We'll take a look.

**Comment by jfcere** [comment]
I just want to share my experience if it can help anyone...

[@peterpeterparker solution](https://github.com/ionic-team/capacitor/issues/1627#issuecomment-569910417) works well! The result is that you get a plain background with the desired color for 1 second before your splash screen kicks in but still acceptable as it is smooth.

[@enginkarabel solution](https://github.com/ionic-team/capacitor/issues/1627#issuecomment-938057201) works as we expect the plugin to behave! This fixes the badly resizing that squeezes the splash screen but requires a "little" more work (believe me it's pretty easy).

**Comment by insel-maz** [comment]
We also have crashes with Samsung Galaxy S20 / Android 12.

Because we only use one icon and one background color, I switched to (in addition to https://github.com/ionic-team/capacitor/issues/1627#issuecomment-938057201):

capacitor.config.ts

	plugins: {
		SplashScreen: {
			launchAutoHide: false,
			androidSplashResourceName: 'custom_splash',
		},
	},

custom_splash.xml

	<?xml version="1.0" encoding="utf-8"?>
	<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
		<item android:drawable="@color/ic_launcher_background"/>
		<item>
			<bitmap android:src="@drawable/splash_icon" android:gravity="center"/>
		</item>
	</layer-list>

**Comment by timvanuum** [comment]
> Hi, having the same issue and digged on Ionic Forums and find the following. Just appying as follows it did the job for me, without setting up a color as @peterpeterparker said (it also works but this seems to do the trick on a better way). Check it out.
> 
> `<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar"> <item name="android:windowNoTitle">true</item> <item name="android:windowActionBar">false</item> <item name="android:windowFullscreen">true</item> <item name="android:windowContentOverlay">@null</item> <item name="android:windowIsTranslucent">true</item> </style>`
> 
> By the way, i also agree such a simple thing to be so frustating. Maybe not the worst issue on an app but, if all customers have a similarity all around the world is for putting their eyes in such little things - just opening the app - before all the incredible effort behind the scenes.
> 
> Regards.

It works, but makes startup very slow, a second delay. Using a background color for now. But hoping for a real solution.
