### ISSUE TITLE
LocalNotifications identifier should take UUID/String not only Integer

### ISSUE THREAD

**Issue by PaulJrdn** [ionic-team/capacitor#1634]
Description of the problem:
Currently `LocalNotifications` plugin forces the notification identifier to be an `Integer` whereas push notifications can have UUID/String as notification identifier.

Affected platform
- [x] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: **1.0.0**

node version: **v11.0.0**

npm version: **6.9.0**

CocoaPods version: **1.6.1**

Steps to reproduce:

1. Import `LocalNotifications` plugin
2. Schedule a new local notification with the key `id` set with an UUID

**Comment by jcesarmobile** [comment]
On Android, the `NotificationManager` class requires an integer id for the `notify` method. We used to have a string for iOS, but changed it to integer once we added the Android implementation because of that.
