### ISSUE TITLE
Copy command clobbers update

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#164]
Right now if you run `copy`, it will remove the old platform directory and recreate it. The problem is that cordova plugins are copied over on `update`. 

My thought: move Cordova process back to `update`, or, we remove `copy` and `update` and just have one `sync` command.

Thoughts @jcesarmobile?

**Comment by jcesarmobile** [comment]
I prefer only having sync, but it takes a lot of time on iOS, so probably moving the js part of Cordova to copy command, but keep the native part in update is better

**Comment by jcesarmobile** [comment]
mmm, but update should also update the cordova_plugins.js and copy the plugins js files in case any plugin was installed after the copy command

**Comment by mlynch** [comment]
What if we run it on both `copy` and `update`?

**Comment by jcesarmobile** [comment]
Closed by https://github.com/ionic-team/capacitor/pull/165
