### ISSUE TITLE
cordova.plugins undefined

### ISSUE THREAD

**Issue by kdubuc** [ionic-team/capacitor#1642]
Description of the problem: ```cordova.plugins``` undefined

Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:
Capacitor version: 1.0
node version: 11.11.0
npm version: 6.7.0
CocoaPods version: 1.7.1

Hello all,
I have some cordova plugins declared in my package.json. capacitor detect them, and all seems fine with syncing :
```
...
  Found 6 Cordova plugins for ios
    cordova-plugin-actionsheet (2.3.3)
    cordova-plugin-dialogs (2.0.1)
    cordova-plugin-email (1.2.7)
    cordova-plugin-file (6.0.1)
    cordova-plugin-media (5.0.2)
    uk.co.workingedge.phonegap.plugin.launchnavigator (5.0.4)
...
```

But, in my app ```cordova.plugins``` (or ```window.plugins```) is undefined (```cordova``` is okay).
All Capacitor Plugins are okay, but I cannot use Cordova Plugins (```cordova.plugins.email.open({...})``` produce an error).

Also, the xcode console shows some logs like this :
```
⚡️  [log] - deviceready has not fired after 5 seconds.
⚡️  [log] - Channel not fired: onCordovaReady
⚡️  [log] - Channel not fired: onFileSystemPathsReady
```

I tried to erase ios/ and re-sync from scratch, but same results.

I pretty sure all of this worked before the 1.0.

Some ideas ?

Thanks !

**Comment by jcesarmobile** [comment]
Fixed in https://github.com/ionic-team/capacitor/pull/1616

**Comment by kdubuc** [comment]
exactly, thanks !

**Comment by gelinger777** [comment]
I have exactly the same issue. 
any ideas how to solve it? 

```
Ionic:

   Ionic CLI                     : 6.20.8 (/home/bln77/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.6.1
   @angular-devkit/build-angular : 15.2.2
   @angular-devkit/schematics    : 15.2.2
   @angular/cli                  : 15.2.2
   @ionic/angular-toolkit        : 8.0.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.19.0 (/home/bln77/.nvm/versions/node/v16.19.0/bin/node)
   npm    : 8.19.3
   OS     : Linux 5.4

```
