### ISSUE TITLE
How to stop refresh page when app state changed?

### ISSUE THREAD

**Issue by Jimmysh** [ionic-team/capacitor#1652]
Description of the problem:
 when the application state from  inactive to active. it will refresh page. How to stop it.
Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0

node version: v10.15.3

npm version:6.9.0

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
Can you provide some sample project or more details?
I don't see my apps refreshing when state changes

**Comment by Jimmysh** [comment]
@jcesarmobile I make a mistake.  It is white screen not refresh page. Sometime  from inactive to active it will show white  few seconds first.

**Comment by jcesarmobile** [comment]
is you splash screen white? because in some of my apps, sometimes it shows the splash screen again, but not a white screen.
