### ISSUE TITLE
Connection refused when call ngsw-worker.js file and Service worker is not registering

### ISSUE THREAD

**Issue by minajacob** [ionic-team/capacitor#1655]
I can't register service worker in capacitor webview 
I used angular and capacitor 1.0.0-beta.24

I think that URL schema need to be https which service worker required, How to make this https ? or what is the suitable solution to register **SW** 
**My  package.json is :**

![image](https://user-images.githubusercontent.com/6568103/59346278-39ca5580-8d12-11e9-807b-ee188bcd2f30.png)

**and the problem is :** (**_This is from Android Emulator_**)

```
Failed to load resource: net::ERR_CONNECTION_REFUSED
Uncaught Error: Uncaught (in promise): TypeError: Failed to register a ServiceWorker: An unknown error occurred when fetching the script.
TypeError: Failed to register a ServiceWorker: An unknown error occurred when fetching the script.
```

![image](https://user-images.githubusercontent.com/6568103/59345649-dc81d480-8d10-11e9-848f-0ec134cf6597.png)

**Comment by jcesarmobile** [comment]
What are you doing with the service workers?
Can you provide a sample app?

**Comment by minajacob** [comment]
Thanks @jcesarmobile for your reply
I created a PWA app that uses service worker for caching some requests and offline support. This work nice in web but not sure how this PWA app should work well inside the capacitor due to this issue.

**Comment by jcesarmobile** [comment]
So, can you provide a sample app?

**Comment by minajacob** [comment]
I create a sample app in this repository
https://github.com/minajacob/capacitor-sw

**Comment by dimitrios1988** [comment]
Is there any news about the matter? I am having the same issue

**Comment by jcesarmobile** [comment]
So, the problem is the web worker requests don't go through the regular shouldInterceptRequest.

You can use this workaround 
https://stackoverflow.com/questions/55894716/how-to-package-a-hosted-web-app-with-ionic-capacitor

You don't need a plugin, you can use a similar code in the `MainActivity.java` like this:
```
if(Build.VERSION.SDK_INT >= 24 ){
      ServiceWorkerController swController = ServiceWorkerController.getInstance();

      swController.setServiceWorkerClient(new ServiceWorkerClient() {
        @Override
        public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
          return bridge.getLocalServer().shouldInterceptRequest(request);
        }
      });
    }
```

But notice that it requires SDK 24 and Capacitor supports SDK 21, so it won't work on 21-23

**Comment by kenezetele** [comment]
This workaround doesnt work anymore with the latest webview update (v90). If the app had a worker registered, doesnt load at all, and if not, cant register the worker. For me it seems like ServiceWorkerClient gets overridden even if I am overriding it. Do you have any other workaround suggestions?

**Comment by jcesarmobile** [comment]
If google broke something you’ll have to report it to google, they probably didn’t do it on purpose 

https://bugs.chromium.org/p/chromium/issues/list?q=component:Mobile%3EWebView

**Comment by kenezetele** [comment]
I am making a report. Do you think is it possible to make a workaround until they fix it? The app is broken in production. Reinstalling it removes the service worker but then the modules are loaded slower from the app than from the cache.

**Comment by laurentgoudet** [comment]
> I am making a report. Do you think is it possible to make a workaround until they fix it? The app is broken in production. Reinstalling it removes the service worker but then the modules are loaded slower from the app than from the cache.

Did you end up making a report @kenezetele? The v91 WebView update seems to have fixed the issue

**Comment by kenezetele** [comment]
> Did you end up making a report @kenezetele? The v91 WebView update seems to have fixed the issue

Yes, I have made a report with a sample app tp reproduce the issue. They have fixed it from there.

**Comment by dylanvdmerwe** [comment]
Note that this does not work:
![image](https://user-images.githubusercontent.com/2852839/143602473-c9638459-f029-4ce7-9495-09b97de788ec.png)

When the site is served from the service worker capacitor is not injected:
![image](https://user-images.githubusercontent.com/2852839/143602551-f37ecf84-8a9f-4212-8e9f-b49c9021e42b.png)
![image](https://user-images.githubusercontent.com/2852839/143602590-04e651aa-faf6-4be3-a6f6-988b8a5b3a6c.png)
