### ISSUE TITLE
Swift 5

### ISSUE THREAD

**Issue by agrosner** [ionic-team/capacitor#1658]
Hi, 
I am wondering when Capacitor will be updated to support Swift 5 / Xcode 10.2 + ?

**Comment by jcesarmobile** [comment]
What’s the problem with Xcode 10.2? I use it every day and didn’t notice any problem

Updating to swift 5 is probably a breaking change, so might take a while until we do it, but Xcode can handle different swift versions, so you can update your project or create plugins that use swift 5, so it using swift 4.2 shouldn’t affect you for now

**Comment by jcesarmobile** [comment]
First PR: https://github.com/ionic-team/capacitor/pull/2465

**Comment by jcesarmobile** [comment]
template update: https://github.com/ionic-team/capacitor/pull/2467

**Comment by jcesarmobile** [comment]
plugin template https://github.com/ionic-team/capacitor/pull/2468

**Comment by jcesarmobile** [comment]
All Swift 5 PRs are merged, closing
