### ISSUE TITLE
npx cap sync - fails to add plugin variable 

### ISSUE THREAD

**Issue by theunreal** [ionic-team/capacitor#1667]
Description of the problem:

Affected platform
- [x ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ z] Windows
- [ ] macOS
- [ ] linux

Capacitor version: 1.0

node version: 10

npm version: 5.6

Steps to reproduce:
1. Install cordova-plugin-admob-free plugin
2. Set the ADMOB_APP_ID:
```
<plugin name="cordova-plugin-admob-free" spec="^0.27.0">
        <variable name="ADMOB_APP_ID" value="ca-app-pub-my-pub-id" />
    </plugin>
```
3. run npx cap sync
4. The AndroidManifiest of capacitor-cordova-android-plugins update with this:
`<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="$ADMOB_APP_ID"/>`
5. $ADMOB_APP_ID is undefined.

**Comment by jcesarmobile** [comment]
Capacitor doesn't support Cordova plugin variables, you have to check what the plugin does with them and do it manually.

In this case, as it has been previously [reported](https://github.com/ionic-team/capacitor/issues/1353), I already looked into it. What you need to do is to add this into the app's `AndroidManifest.xml`

```
<meta-data tools:replace="android:value"
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="the-variable-value-here"/>
```

Might require you to add `xmlns:tools="http://schemas.android.com/tools"` in the `AndroidManifest.xml` too if you don't have it already.

This will replace the existing entry in the capacitor-cordova-android-plugins `AndroidManifest.xml` with the unresolved variable.
