### ISSUE TITLE
Media API, sound, microphone etc

### ISSUE THREAD

**Issue by netgfx** [ionic-team/capacitor#1669]
I don't see any Media API to capture sounds or to playback media. Is this supported or on the roadmap to be supported?

Thanks.

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

On Android and web you can use `getUserMedia` for audio capture, on iOS and Android you can use input with type file and capture property. On all of them you have audio tag to play the sounds. But there is no native plugin for it.

**Comment by sta55en** [comment]
Is there any interest in ever supporting this super important feature in Capacitor?

Right now on iOS13, background audio via the webview is broken and stops playing after a few seconds in background mode. It worked in iOS12. There are no good Cordova plugins to manage audio and it would be extremely useful if Capacitor could at least play some audio.

**Comment by Tyutyesz** [comment]
If I'm correct, Apple doesn't support `getUserMedia()` in WKWebview and UIWebview. 
Will be there any solution for this, or should I change to cordova?
I need to access the users microphone.

**Comment by jcesarmobile** [comment]
I already commented on your stackoverflow question a few days ago, cordova doesn't support getUserMedia neither, it's an Apple limitation.  Already commented on this thread too. So please, read the comments.

**Comment by Tyutyesz** [comment]
> Already

Thank you for your answer and sorry about it. I read your comment, but though that maybe there is another way for it.

**Comment by joshstovall** [comment]
Any updates on this?  I am hoping to use getUserMedia microphone and connect to WebAudio nodes.  

I tried [this](https://github.com/edimuj/cordova-plugin-audioinput) Cordova plugin, I had success requesting microphone permission, but never seemed to get it working when trying to 'plug' it in to a WebAudio node.

Specifically looking for a iOS solution.  getUserMedia seems to work perfect on Android out of the box!

**Comment by MadyAkira** [comment]
I'm using Cordova media capture plugin which is working like a charm for native run (iOs & android)

[Cordova plugin media capture github](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-media-capture/)

**Comment by joshstovall** [comment]
Hi MadyAkira,

I was able to get cordova-plugin-media-capture working.   Though I am not looking to record an audio file.  

I am trying to steam the microphone input in realtime to a [ScriptProcessorNode](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode).  I have it working great in iOS Safari using [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) and [createMediaStreamSource](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource).  Though I cannot seem to figure out a way to get this to work with Capacitor. 😕

**Comment by joshstovall** [comment]
Ok I finally got it working using [cordova-plugin-audioinput](https://github.com/edimuj/cordova-plugin-audioinput).

See [Advanced Usage example,](https://github.com/edimuj/cordova-plugin-audioinput#advanced-usage-example---events) then pass the `evt.data` array to [this function](https://stackoverflow.com/a/25776663/10499018).  Now you can connect `src` to a WebAudio node.

Seems like a round-about method.  But hey, at least it works! 👍

**Comment by diachedelic** [comment]
Just to clarify @jcesarmobile 's reply - you cannot use 
```html
<input type="file" name="audio" accept="audio/*" capture>
```
to record audio-only on iOS, it opens a video picker on iOS 13.4.1.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/19. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
