### ISSUE TITLE
capacitor-android(cordova-plugin-googlemaps) java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by edy-ap** [ionic-team/capacitor#1670]
Description of the problem:

Affected platform
- [ X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [X ] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0
node version:

npm version:
6.9.0
CocoaPods version:

Steps to reproduce:
1.- Install capacitor
2.- Add plugin cordova-plugin-googlemaps
3.- Add android platform
4.- Run project
![error-maps-plugin](https://user-images.githubusercontent.com/13421021/59612793-5506dd80-90e3-11e9-84c5-3936502ddb12.PNG)

Link to sample project:

**Comment by jcesarmobile** [comment]
It was fixed in https://github.com/ionic-team/capacitor/pull/1643, but it's not released yet

As workaround, check the generated config.xml and remove the empty feature tag `<feature/>`
