### ISSUE TITLE
Android build error in ionic capacitor

### ISSUE THREAD

**Issue by Kaoschuks** [ionic-team/capacitor#1680]
Whenever i build my ionic capacitor app for android i get

E/AccountKitPlugin: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
at
android.support.v4.app.BaseFragmentActivityApi14.checkForValidRequestCode(BaseFragmentActivityApi14.java:79)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:748)
at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:68)
at org.apache.cordova.facebook.AccountKitPlugin.executeLogin(AccountKitPlugin.java:136)
at org.apache.cordova.facebook.AccountKitPlugin$1.run(AccountKitPlugin.java:56)

Affected platform
- [* ] Android

OS of the development machine
- [x] macOS

Steps to reproduce:
* ionic start ionicAccountkIt --type=ionic-angular --capacitor
* cordova plugin add cordova-plugin-accountkit --save \
   --variable APP_ID="123456789" \
   --variable APP_NAME="myApplication" \
   --variable CLIENT_TOKEN="abcdefghijklmnopqrstuvwxyz" \
   --variable API_VERSION="v1.1"
** Add accountkit cordova login with phone number logic to home component and connect to a button
* ionic build --prod
* npx cap add android
* npx cap open android
** build android app and run

**Comment by jcesarmobile** [comment]
Capacitor has a limitation on the max request code allowed, being 16 bits (65536), but cordova-plugin-accountkit is using 65537. You'll have to fork the plugin and change this line to use a smaller number https://github.com/gurisko/cordova-plugin-accountkit/blob/2f1ec00415c9c110f45ecd4361f1d5cad2bd4b2b/src/android/AccountKitPlugin.java#L31
kudos if you send a pull request to the original plugin so other people can also benefit.

**Comment by Kaoschuks** [comment]
I have reduced it to 65530 but it didn't work

**Comment by jcesarmobile** [comment]
I have tried and I no longer get the 16 bit error, si if you mean the plugin still doesn't work, report a new issue providing more information and a sample project.

If you still got the same 16 bit error message, then try doing a clean first, but 65530 worked for me.

**Comment by Kaoschuks** [comment]
Please tell me what you did that made it work.
Your steps.
How you included the plugin to the project etc

**Comment by jcesarmobile** [comment]
I’m not sayings it works, but it doesn’t have that error anymore. I have no idea about how to use that plugin, that’s why I’m asking for more information and a sample project if you are getting a different error now.

**Comment by Kaoschuks** [comment]
Okay I could add you to the project on azure devops send me an email on kaosemeka@yahoo.com
