### ISSUE TITLE
How to subscribe to a topic in Firebase Push Notification

### ISSUE THREAD

**Issue by bubundas17** [ionic-team/capacitor#1682]
Hi, I had an issue while implementing Push Notifications in an app. 

The push notifications functionality is working fine! But the issue is, how do I Subscribe and Then Unscribe user from a topic? There is no Documentation for that!

Please, guys, It Is a must-have feature.

**Comment by minajacob** [comment]
Add this plugin
https://github.com/stewwan/capacitor-fcm

**Comment by bubundas17** [comment]
> Add this plugin
> https://github.com/stewwan/capacitor-fcm

Yap, It helps. Thank you!

**Comment by bubundas17** [comment]
But well. it should be also implemented in Capacitor's Native plugin also.

**Comment by bubundas17** [comment]
@jcesarmobile Any Comments?

**Comment by jcesarmobile** [comment]
PRs are always welcome, but if somebody want to add this feature, it has to be Android only as iOS APNS don't support topics.

**Comment by bubundas17** [comment]
> Add this plugin
> https://github.com/stewwan/capacitor-fcm

Well, It seems to not work properly.

**Comment by jwhijazi** [comment]
the solution worked for me.
Maybe you missed the line in the documentation for android devices:

on your MainActivity.java file add import io.stewan.capacitor.fcm.FCMPlugin; and then inside the init callback add(FCMPlugin.class);

**Comment by orhan-swe** [comment]
For us this is only working on Android, there we are reading the FCM token. The issue is with iOS, there it seems the device is only giving us the APNS token which we can not user with FCM, has anyone seen or resolved this issue?
We have also tried with https://github.com/stewwan/capacitor-fcm but on iOS the "getToken" method only returns an empty object.
Any information on this would be greatly appreciated!

**Comment by madmacc** [comment]
@orhan-swe

**Comment by naveedahmed1** [comment]
@stewwan since you have already implemented similar functionality in your plugin https://github.com/stewwan/capacitor-fcm can you please create a pull request to implement this feature for the capacitor push notification plugin?

**Comment by stewwan** [comment]
@naveedahmed1 @jcesarmobile explains above. That's why I created the plugin which serves both platform with no pain.

enjoy it

> PRs are always welcome, but if somebody want to add this feature, it has to be Android only as iOS APNS don't support topics.

**Comment by naveedahmed1** [comment]
@stewwan yes its awesome, great job.

But @jcesarmobile who's a member of capacitor repository mentioned.

> PRs are always welcome, but if somebody want to add this feature, it has to be Android only as iOS APNS don't support topics.

So if you could create a PR which adds the same functionality to the Capacitor Push Notification Plugin?

**Comment by RichardBoyder** [comment]
@stewwan  Would be amazing if you could add it to capacitor push notification plugin. Its All your hard work going into helping Capacitor elevate their plugins... Thats worth a bells or 2.

**Comment by RichardBoyder** [comment]
> PRs are always welcome, but if somebody want to add this feature, it has to be Android only as iOS APNS don't support topics.

Im using FCM plugin for Cordova and it does allow subscript to topic and does work for iOS. Just noting it down here.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

As mentioned earlier, if you are really interested and have the knowledge to implement this, you can send a PR.

**Comment by Simbaclaws** [comment]
@dibyendusaha Could you make a pull request from your forked capacitor repository which adds this functionality to the push notifications?

I would like to be able to subscribe to topics like I could with the phonegap-plugin-push plugin.
We've recently switched to capacitor but this functionality is vital to what my company is trying to achieve. Since we're using ionic 4, using phonegap-plugin-push isn't really an option anymore.

I'm hoping that this can be added to the core capacitor plugin for push notifications.

Otherwise I'm going to try using @stewwan his plugin.

**Comment by dibyendusaha** [comment]
@Simbaclaws , I already raised the pull request and that may be the reason you are seeing this above commit, but due to some direct dependency (for ios) it is not merged to the main branch, so I will suggest to use @stewwan plugin for now, until & unless it is merged to main branch.

**Comment by Simbaclaws** [comment]
@dibyendusaha Thank you, I will do so :)

**Comment by CharlesElGriego** [comment]
Hi, @stewwan plugin works for IOS?

**Comment by dibyendusaha** [comment]
> Hi, @stewwan plugin works for IOS?

@CharlesElGriego , I think it will work for both iOS & android. You can try it.

**Comment by JeremyFae** [comment]
Is there a way to do with using https://github.com/stewwan/capacitor-fcm as a script include? or maybe there is a way to change the plugin so i can use it as a  script include. I am new to the web and java script so i may have missed something obvious.

**Comment by stewwan** [comment]
hey @dibyendusaha yes it works on both plaform ios/android
I did transfer my plugin to the capacitor community org
check it out
https://github.com/capacitor-community/fcm

**Comment by Erdou** [comment]
Note that it is impossible to get any notifications for all users if you don't handle topics and your backend use FCM REST API. As those APIs doesn't allow segment selection, so you are basically forced to use either topics or a specific user tokens.

**Comment by vigamage** [comment]
> 

In the documentation, I cannot find this. May be for the latest releases it is not needed ?

**Comment by vigamage** [comment]
> the solution worked for me. Maybe you missed the line in the documentation for android devices:
> 
> on your MainActivity.java file add import io.stewan.capacitor.fcm.FCMPlugin; and then inside the init callback add(FCMPlugin.class);

In the documentation, I cannot find this. May be for the latest releases it is not needed ?
