### ISSUE TITLE
Unable to get push notifications to work with iOS

### ISSUE THREAD

**Issue by gubbigubbi** [ionic-team/capacitor#1683]
Description of the problem:

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version:
1.0

node version:

npm version:

CocoaPods version:

Steps to reproduce:
I am able to send push notifications to iOS via the console. However if I manually put in my devices ID, then the push notification does not arrive. 

I wonder if the device token obtained from iOS is not correct? I have noticed the tokens from ios look like this:
E5F197E70DDA5DC1497CC97B1E36A48524D2EF5081A6447C911DA5DA1D8D9EA2

Whilst the android id's look like this:
cNtkYK6LGjQ:APA91bENTieeHl25mZIs6y5vIuFt4irDYgR1zj8f_w_N2Kp3AQ0eGh5DZ3vnHXmLRHyzfRwJq4p9Fta_h2GInSteM5I-I6Y6loOpUtak18Xf2gL7oDGWvnVGg-ujNravwX-C4mb-FsMK

Link to sample project:

**Comment by gubbigubbi** [comment]
As it turns out - looks like my device token is an APNS token. Im going to try converting it to a FCM token and try with that.

**Comment by iamnels1** [comment]
same problem here since few hours..

**Comment by jcesarmobile** [comment]
Capacitor only has APNS implemented, not FCM. You’ll have to use some fcm plugin to get the fcm token or handle the code yourself

**Comment by gubbigubbi** [comment]
Thank - I am no using this plugin to get my token:
https://www.npmjs.com/package/capacitor-fcm

**Comment by iamnels1** [comment]
@gubbigubbi did you solve the problem ?

**Comment by gubbigubbi** [comment]
> @gubbigubbi did you solve the problem ?

Yes - using capacitor-fcm solved the problem I can now receive push notifications on ios with firebase cloud messaging :)

**Comment by iamnels1** [comment]
Wonderfull, I'll do that too; thank you ;)

**Comment by iamnels1** [comment]
doesn't work... build error... @"#!!

**Comment by jcesarmobile** [comment]
Locking the conversation as it's off topic, please, if you have problems using a 3rd party plugin, report it on the plugin repo. 
If looking for help use the forums
