### ISSUE TITLE
'npx cap open electron' results in 'Platform electron is not valid.'

### ISSUE THREAD

**Issue by roberttolton** [ionic-team/capacitor#1684]
**Description of the problem:**
Using a VueJS and Ionic v4 setup, I have successfully used `npx cap add ios` and `npx cap add android` and can open them with the relevant commands, too.

However, while I am able to successfully run `npx cap add electron` and it is installed correctly, `npx cap open electron` gives me an error: `[fatal] Platform electron is not valid.`

`npx cap doctor electron` shows:

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.0.0

  @capacitor/core: 1.0.0

  @capacitor/android: 1.0.0

  @capacitor/ios: 1.0.0

Installed Dependencies:

  @capacitor/cli 1.0.0

  @capacitor/core 1.0.0

  @capacitor/android 1.0.0

  @capacitor/ios 1.0.0

[fatal] Platform electron is not valid.
```
If I go into the `electron` folder and run the `electron:start` script from there, Electron and my App boot successfully. So the Electron setup seems ok, just Capacitor can't start it.

**Affected platform**
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

**OS of the development machine**
- [ ] Windows
- [x] macOS
- [ ] linux

**Other information:**
Using VueJS Project Type

**Capacitor version:** `1.0.0`

**node version:** `v10.15.3`

**npm version:** `6.4.1`

**CocoaPods version:** `1.7.2`

**Steps to reproduce:**
Create any new Ionic v4 project using VueJS, add capacitor and try the commands above.

**Link to sample project:**
Currently not in a public repo.

**Comment by jcesarmobile** [comment]
Was implemented in here
https://github.com/ionic-team/capacitor/pull/1666

current instructions can be found here
https://capacitor.ionicframework.com/docs/electron

```
cd electron/
npm run electron:start
```

**Comment by roberttolton** [comment]
Thanks @jcesarmobile, though the current instructions make no mention of `npm run electron:start`, but at least it seems to be the right thing to do.

**Comment by jcesarmobile** [comment]
ah, looks like I have a cached version of the docs and a new version of the docs have been deployed before releasing that new feature.
