### ISSUE TITLE
Geolocation Accuracy improvements

### ISSUE THREAD

**Issue by Jaspur** [ionic-team/capacitor#1685]
Description of the problem:
The accuracy of the Geolocation that is provided with the WatchPosition can be done better for iOS and Android.

Affected platform
- [ x ] Android
- [ x ] iOS

OS of the development machine
- [ x ] macOS

Other information:
For Android you better can use the "Fused Location" (#379)

And for Swift it uses by default:
```
self.locationManager.desiredAccuracy = kCLLocationAccuracyBest
```
But Best Accuracy isn't really the best option. 
There are also the options ```kCLLocationAccuracyNearestTenMeters``` and ```kCLLocationAccuracyBestForNavigation``` See: https://developer.apple.com/documentation/corelocation/cllocationaccuracy

How can I chose myself which ```CLLocationAccuracy``` option to use?

**Comment by jcesarmobile** [comment]
Fixed in https://github.com/ionic-team/capacitor/pull/1773
