### ISSUE TITLE
Camera plugins doesn't work in IOS (PWA in homescreen)

### ISSUE THREAD

**Issue by IAtaneqI** [ionic-team/capacitor#1686]
I read this: "Old getUserMedia API was removed in favor of WebRTC".
There is a way to adapt the camera plugin for IOS?

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
iOS version where you tested?

**Comment by jcesarmobile** [comment]
Closing as this is an Apple bug, they fixed in iOS 13 beta 1, but it's broken again in beta 2, and sadly, there is nothing we can do about it.
Next Capacitor release will provide error messages instead of just showing a black screen.
