### ISSUE TITLE
 the call.resolve(data) returns information only once

### ISSUE THREAD

**Issue by JhonArlex** [ionic-team/capacitor#1687]
He creado un plugin para la lectura de código qr. Este plugin funciona una promer vez bien y envia la información a la app pero cuando voy a leer el código qr por segunda vez, este no devuelve nada.

`
package com.jhon.capacitor_qrcode;

import android.content.Intent;
import android.util.Log;

import com.getcapacitor.JSObject;
import com.getcapacitor.NativePlugin;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;

@NativePlugin(requestCodes = 9001)
public class QRCodePlugin extends Plugin {

    private static final int RC_BARCODE_CAPTURE = 9001;
    private static final String TAG = "BarcodeMain";

    @PluginMethod()
    public void getCodeQR(PluginCall call) {
        Intent intent = new Intent(this.getBridge().getContext(), BarcodeCaptureActivity.class);
        intent.putExtra(BarcodeCaptureActivity.AutoFocus, true);
        startActivityForResult(call, intent, RC_BARCODE_CAPTURE);
    }

    @Override
    protected void handleOnActivityResult(int requestCode, int resultCode, Intent data) {
        super.handleOnActivityResult(requestCode, resultCode, data);

        Log.d(TAG, "handle");

        PluginCall savedCall = getSavedCall();

        if (savedCall == null) {
            return;
        }
        if (requestCode == RC_BARCODE_CAPTURE) {
            // Do something with the data
            proccessData(savedCall, data);
        }
    }

    public void proccessData(PluginCall call, Intent data) {
        JSObject ret = new JSObject();
        ret.put("code", data.getStringExtra("code"));
        call.resolve(ret);
    }
}
`

Repository project
https://github.com/JhonArlex/capacitor_qrcode

**Comment by jcesarmobile** [comment]
You had a few issues in the plugin, I explained them in your repo.
The most important part is you have to call `saveCall(call);` before launching an intent.
