### ISSUE TITLE
Electron refreshing to blank white screen

### ISSUE THREAD

**Issue by tyvdh** [ionic-team/capacitor#1688]
Description of the problem:
I'm able to build an electron application quite nicely, but when I Command + R or window.location.reload() the application dies and returns an empty white screen. **Important** I am not using the history.state as this is the default index.html route before any navigation has happened.

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
![Screen Recording 2019-06-19 at 03 07 PM](https://user-images.githubusercontent.com/4383610/59793628-00ab5b80-92a5-11e9-9559-e072fb481b98.gif)

Capacitor version:
1.0.0

node version:
11.0.0

npm version:
6.9.0

CocoaPods version:
1.7.2

Steps to reproduce:
```bash
// From the root
$ yarn cap
```

```bash
// From electron dir
$ yarn electron:start
```
From the open electron app refresh the app.

Link to sample project:
https://github.com/tyvdh/stellarauth-electron

**Comment by jcesarmobile** [comment]
I get the error, but not the white screen.

Anyway, will be fixed on next release, but will require manual changes in your index.js (or remove and add electron platform again if you didn't do any changes on it) 
https://github.com/ionic-team/capacitor/pull/1672
