### ISSUE TITLE
Custom PlugIn inputs and outputs

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/capacitor#169]
This issue contains a set of comments and suggestions related to creating a new PlugIn using Capacitor.  These comments are related to the calling process involving parameters being passed to the plugin and results being returned by the plugin.  Sorry that it got a bit long but figured it was better to pass on the thoughts from a new user perspective. 

### call.getBool, call.getInt - defaultValue argument should be optional

Some of the utility methods like `call.getString` use nil as a default so the `defaultValue` parameter does not need to be specified.  `getBool` and `getInt` should use a similar style where the parameter is not required.

It is often useful to specify default values using the Nil-Coalescing Operator in order to know that the result is not nil.  In this case it is cleaner to not have to specify `defaultValue:nil`.  For example:

```swift
let count = call.getInt("count") ?? 5
```

### call.getDouble

It would be useful to have a `getDouble` (or whatever data type makes sense) utility function to handle non integer Javascript numbers.

There may be some rounding issues to consider with floating point numbers.  Calling a plugin method with {num: 123.456} results in:

```swift
let x = call.get("num", Float.self) // 123.456001
let y = call.get("num", Double.self) // 123.456
```

### call.hasOption(name: String) -> Bool

It is sometimes useful to know whether an argument has been specified in order to differentiate between an undefined value and a null value.

For example, when updating a Contact with a set of changes a null value might be used to specify that the field value should be cleared whereas the absence of a value would mean to leave the field value unchanged.  For example:

```ts
PlugIns.Contacts.updateContact({id, changes: { organizationName: null } })
```

In this case, the desire is to only clear a field value when it is specified as null but not update fields that have not been specified.

This could be done with a utility method:

```swift
if call.hasOption("organizationName") { ... }
```

### Type validation for arguments

If a PlugIn function is called with a parameter value that is not the correct data type then the parameter values appears as nil and there is no error.  This can lead to problems when the caller is not aware that the arguments have been ignored.  For example:

```
// js caller
PlugIns.Contacts.updateContact({id, age: 21.5})

// plugin
let age = call.getInt("age") // gets nil
```

In this case the plugin things that the user specified a null value to clear the field and clears the field.  The caller does not get an error and thinks that the field has been updated correctly.  Not only is the update not saved, but the existing value is also lost when it is set to null.

### Ability to return other result types

It is sometimes useful to return values other than an Object.  This avoids the nested `value` property within the result object.  For example:

Contacts.getContacts(predicate) => Contact[] // An array of values
Clipboard.read() => String

### Ability to return property values with nil

```swift
call.success([
        "name": "John",
        "status": nil // This results in an error
])
```

### Error handling

Perform default error handling for plugin methods that throw errors.  This could simplify some methods vs. having the same error catch block in lots of places.

## Naming

Some possible ideas for naming changes:
- call.args instead of call.options
- call.resolve(result), call.reject(error) instead of call.success(result) and call.error(error)

## Overall feedback

Capacitor is great!  After a short amount of time working on a custom plugin it has been a very productive environment and very powerful to have full access to the native environment.  I have used various Cordova plugins in the past and have been continually frustrated with missing features and this feels like a good way to be able to do anything on the device.  Great work!

**Comment by mlynch** [comment]
Awesome feedback, thanks so much! I definitely like the `resolve` `reject` change, I'm going to get that in before we do the alpha.

As for type checking, I know Cordova had some of this at runtime, but I'd prefer to use TypeScript and get this at build time instead. Not ideal for those not using TS but given those types can be used in JS in some cases, I think this is an okay middle ground.

Will look into adding some of those other type things.

The return type for plugins is something I'd like to improve, along with going the other direction: making it easier to use non-object types as params. Keeping it object only is simple, but I had an implementation of other type support earlier on, so it's certainly doable.

**Comment by mlynch** [comment]
Awesome, got the data type changes and resolve/reject in there. Closing for now as the other ones are more subjective.

**Comment by cjorasch** [comment]
Wow - that was fast!

One quick thing I noticed was the `hasOption` implementation:

```swift
  public func hasOption(_ key: String) -> Bool {
    return self.options[key] != nil
  }
```

Checking for `nil` is not quite the same as checking if an option was specified.

For example, if I make the call `MyPlugin.test({ a: 1, b: null })` then I am hoping to be able to know that `c` was not specified and `b` was specified.  Essentially a way to differentiate `undefined` from `null`.

An alternate approach might be:

```swift
  public func hasOption(_ key: String) -> Bool {
    return self.options.index(forKey: key) != nil
  }
```

This would result in:
- hasOption("a") -> true
- hasOption("b") -> true
- hasOption("c") -> false

**Comment by mlynch** [comment]
Good call, just tweaked that
