### ISSUE TITLE
Save image with Filesystem 

### ISSUE THREAD

**Issue by salime45** [ionic-team/capacitor#1694]
Hey i am trying to use the Filesystem to save a image create in a canvas. The original image is in base64 i tried to convert to file but i dont know sabe the file with filesystem

    Filesystem.writeFile({
      path: 'my-path/' + fileName,
      data: imageBase64,
      directory: FilesystemDirectory.Documents,
      encoding: FilesystemEncoding.UTF8
    })

This is posible?

**Comment by jcesarmobile** [comment]
if you don't pass any encoding it accepts the base64 string.

**Comment by salime45** [comment]
thanks
