### ISSUE TITLE
iOS Statusbarstyle not set

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/capacitor#1703]
Description of the problem:

The statusbar style `light` is not set correctly. The statusbar is still displayed as `dark` on iOS if the style is set to light.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.1

node version: 12

npm version: 6.9

Steps to reproduce:

```ts
    if (Capacitor.isPluginAvailable('StatusBar')) {
      StatusBar.setStyle({ style: StatusBarStyle.Light });
      StatusBar.show();
    }
```

**Comment by jcesarmobile** [comment]
The style doesn’t affect the statusbar itself but the text on it, iOS statusbar doesn’t have a background you can colour.

Light style means dark text

StatusBarStyle

```
enum StatusBarStyle {
// Light text for dark backgrounds.
Dark: "DARK"
// Dark text for light backgrounds.
Light: "LIGHT"
}
```

**Comment by danielsogl** [comment]
Yes the text should change to light but it does not work. Maybe I described my problem not good enough.

**Comment by jcesarmobile** [comment]
Light style is dark text

**Comment by jcesarmobile** [comment]
Just checked and it's working as documented.
It's true that `StatusBarStyle.Light` might be counterintuitive for iOS users as it sets the native value to `default`, and `StatusBarStyle.Dark` to `lightContent`, but Android works the other way around, so, as we want both platforms to behave the same way, we choose the Android behavior this time.
Changing this to behave like iOS will be a breaking change and users used to Android behavior might complain then as it should be changed for both platforms. So we are keeping current behavior.

```
// Light text for dark backgrounds.
Dark: "DARK"
// Dark text for light backgrounds.
Light: "LIGHT"

```

**Comment by danielsogl** [comment]
Thanks for your explanation. Not it is clear for me how to configure the plugin correctly.
