### ISSUE TITLE
Annoying error that can only be solved by ctrl-s (re-build)

### ISSUE THREAD

**Issue by aldwnesx** [ionic-team/capacitor#1710]
Description of the problem:  https://www.reddit.com/r/ionic/comments/c5912f/annoying_error_whenever_i_encounter_this_issue_i/

Affected platform

- [x] web

OS of the development machine
- [x] Windows

Steps to reproduce:
Pops up randomly, only way I can "prevent" it is to hit ctrl s for it to build again, and then after that it appears randomly.

Link to sample project: https://www.reddit.com/r/ionic/comments/c5912f/annoying_error_whenever_i_encounter_this_issue_i/

**Comment by jcesarmobile** [comment]
You should report this in the ionic 3 repo. Capacitor doesn’t do the building, but it requires typescript 2.9 or newer and your problem seems to be related to that, sometimes it works and sometimes it doesn’t

**Comment by aldwnesx** [comment]
@jcesarmobile  My version is : "typescript": "~3.1.6"

I don't think that's the cause (?), this is the only project that uses capacitor and has this issue. Any ideas? (I followed this tutorial https://www.joshmorony.com/using-google-maps-and-geolocation-in-ionic-with-capacitor/)

**Comment by jcesarmobile** [comment]
But is it an ionic 3 project? Because in that case it probably uses the typescript version of app-scripts sometimes

**Comment by aldwnesx** [comment]
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v9.9.0
   npm    : 5.6.0
   OS     : Windows 10

**Comment by aldwnesx** [comment]
It's an ionic-angular project, seems like the version is 4 @jcesarmobile

**Comment by jcesarmobile** [comment]
That’s the ionic cli version, not the version of ionic framework, check your package.json

**Comment by aldwnesx** [comment]
"dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/core": "^4.8.0",
    "@ionic-native/geolocation": "^4.8.0",
    "@ionic-native/google-maps": "^5.5.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "cordova-plugin-geolocation": "4.0.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "rxjs-compat": "^6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  }

@jcesarmobile

**Comment by jcesarmobile** [comment]
Yeah, that's ionic 4 (`"@ionic/angular": "^4.1.0"`)

The problem might be related to using `@ionic-native` 4 as it shipped with typescript 2.x and webpack might be using the wrong version of typescript for building sometimes (when it fails) and the right version when it works. Try updating `@ionic-native/core` and `@ionic-native/geolocation` to latest 5.x available.
