### ISSUE TITLE
Android Studio Gradle Sync Issue

### ISSUE THREAD

**Issue by jupl** [ionic-team/capacitor#1714]
I'm currently getting this in Android Studio and lose functionality like autocomplete and references. In Android studio I get an error `gradle sync failed`. However, running tasks like build work just fine.

![ss2](https://user-images.githubusercontent.com/2065876/60201889-0d80ff80-980f-11e9-93ce-7d76c7e15903.png)

![ss4](https://user-images.githubusercontent.com/2065876/60202614-8df43000-9810-11e9-8782-718626e29cbc.png)

I have the latest `1.1.0` installed for @capacitor/android.

**Comment by jcesarmobile** [comment]
Can you provide a little more information?

When gradle sync fails is for a reason, but with just a screenshot I won't be able to help.

Do you have cordova plugins installed? if so, can you list them?

Or even better, can you provide a sample project reproducing the issue?

**Comment by jupl** [comment]
As I was working on reproducible steps from a new project with @capacitor/cli, I'm not getting this issue on my original project now and am having trouble reproducing. Will close until I can replicate reliably.
