### ISSUE TITLE
Create readme when auto Generating an example plugin

### ISSUE THREAD

**Issue by macdja38** [ionic-team/capacitor#1717]
It would be nice when using the plugin generator if a readme with the instructions on how to install the plugin that was created.

Create react app does a decent job of this when you use it to bootstrap a react project. https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md

Most importantly this should include the install steps for the the npm package as well as `npx cap sync` etc.

It'd be cool if this went a step further and automatically populated the package name in the install command, seeing as the user is asked to give that on plugin creation.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Or if you are really interested and have the knowledge to implement this, you can send a PR.
