### ISSUE TITLE
How to run shell/Command Line Program/Unix Executable in capacitor app？

### ISSUE THREAD

**Issue by hugetiny** [ionic-team/capacitor#1719]
How to run shell/Command Line Program/Unix Executable in capacitor app？
such as node
![image](https://user-images.githubusercontent.com/19659202/56096552-4271fb80-5f1c-11e9-9fbb-13f6b67fd6b0.png)

**Comment by jcesarmobile** [comment]
Sorry, this is not an issue, is a question. Don't use github issues for asking questions.

**Comment by hugetiny** [comment]
This is a feature request。Cordova has plugins for running shell for Android and worked well
(https://github.com/petervojtek/cordova-plugin-shell-exec)
Is there any plan to make a plugin for running shell in Capacitor ?

**Comment by jcesarmobile** [comment]
Does the cordova plugin work?

In short term there are no plans for adding new plugins to core. Added the "plugin request" label so can be tracked to see which plugins had more 👍 reactions.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/5. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
