### ISSUE TITLE
Add `saveFile` and `loadFile` Methods to Filesystem for Cross Platform File Exporting and Importing

### ISSUE THREAD

**Issue by mehmetoguzderin** [ionic-team/capacitor#1720]
# `saveFile` ( `exportFile` )
Filesystem API of Capacitor provides a good way to emulate filesystem experience even on the web. But there is one caveat that comes with it, and there is no standard way to download (save) these files in a cross-platform way.

Filesystem API can be used to allow users to create and update content in their local system with no internet connection. But eventually, it will be natural for those users to wish to export those contents. The StreamSaver project at https://github.com/jimmywarting/StreamSaver.js and its predecessor https://github.com/eligrey/FileSaver.js create an abstraction to quickly achieve that in the web platform, which works quite well with the recent Download Manager in iPadOS's Safari. Other platforms have corresponding functionalities for such facility too.

# `loadFile` ( `importFile` )
This function would act as a way of loading previously exported or obtained from elsewhere content files with a prompt that also works in web.

# Difference from Web Share Level 2
Although Web Share Level 2 will provide a way to share files, at least on the browser of iPadOS, the behavior will be subtly different, where both functions will target different scenarios.

# Naming of Functions
Although this could be best resolved by Ionic Team, `exportFile` and `importFile` namings would represent functionality clearly.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.
