### ISSUE TITLE
My HTTP requests are not working

### ISSUE THREAD

**Issue by joelreyna1104** [ionic-team/capacitor#1723]
Hi,
I have been developing my application for a month now. Everything was working fine, I deployed my app to my android through Android Studio so I could test it. Last week all my HTTP requests just stopped working (from API fetch to retrieving an image in html with the src). The server I am fetching is an http:// one, I tried to set the "allowMixedContent" android config to true but it didn't work. 
The weird thing is that my app was working just fine and suddenly it stopped working. This error of not fetching the server just occurs when I deploy the app to android studio, when I run the development server in my browser works perfectly.

**Comment by jcesarmobile** [comment]
What's your @capacitor/android version? did you update it recently?

**Comment by joelreyna1104** [comment]
My @capacitor/android version is 1.1.0, I tried to downgrade it to 1.0.0 and I still had the problem.

**Comment by jcesarmobile** [comment]
Yeah, there were a lot of betas before the 1.0.0.
What's the Android version of the device you are testing?

**Comment by joelreyna1104** [comment]
My android is currently Android 9. I updated my device recently, could that be the reason? If so, how can I fix it?

**Comment by jcesarmobile** [comment]
then that's the problem, Android 9 doesn't allow clear text communication (http) by default, you have to configure the app to allow it or use https. 
See https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted
