### ISSUE TITLE
Capacitor does not copy Cordova plugin files

### ISSUE THREAD

**Issue by mval1002** [ionic-team/capacitor#1726]
I was trying to use cordova-plugin-badge (with ionic-native, for what that's worth) with my app, and kept getting an error in the Xcode log that the Cordova plugin was not installed. In the Terminal window `npx cap sync ios` shows 

```
    Found 1 Cordova plugin for ios
    cordova-plugin-badge (0.8.8)
```

as expected, and the javascript file is added to the `app/public/plugins` directory, however `APPBadge.h` and `APPBadge.m` were not added to `Pods/Development Pods/CapacitorCordova/Classes/Public`. Copying those files manually solved the problem. 

In my attempts to figure out what was wrong I added `cordova-plugin-push` which I previously used in the app without issue, and experienced the same thing.

I'm on Capacitor 1.1.0 - the aforementioned push plugin working was prior to updating, so it may be a new issue introduced in newer version(s)?

I have not had a chance to check if the equivalent happens for Android as well, but will do so tomorrow morning.

Update, as promised: This does not seem to be an issue with Android. Everything worked fine there!

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce.

The plugin files go to `CordovaPlugins` Pod not to `CapacitorCordova` Pod, they are located at yourProject/ios/capacitor-cordova-ios-plugins and your Podfile should point to it like this `pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'`.

**Comment by mval1002** [comment]
Thank you for the reply! It seems my pod file was missing the CordovaPlugins path for some reason, so thank you for recognizing that being a potential problem area and including it in your response!
