### ISSUE TITLE
Building for production still tries to use livereload server if 'server' is set in capacitor.config.json

### ISSUE THREAD

**Issue by ebk46** [ionic-team/capacitor#1727]
Description of the problem:
'server' is set in capacitor.config.json after doing `ionic capacitor run --livereload` and it stays there until you manually delete it. If you try to build for production, the app will still try to find files where the dev server was putting them (using the url in the 'server' config) unless you manually revert the capacitor.config.json file (i.e. remove the 'server' config).

Affected platform
- [ ] Android (not tested)
- [x] iOS
- [ ] electron (not tested)
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
Not sure if it is relevant, but I am including 2 additional environment variables when I build or run. My commands are:

`"ionic:build:dev": "REACT_APP_API_HOST='xxxxxxxx.ngrok.io' REACT_APP_API_PROTOCOL='https' react-scripts build && ionic capacitor copy"`
and
`"ionic:run:dev": "REACT_APP_API_HOST='xxxxxxxx.ngrok.io' REACT_APP_API_PROTOCOL='https' ionic capacitor run --livereload"`

In addition this has only been tested with simulators, not with real devices.

Capacitor version: 5.2.1

node version: 12.1.0

npm version: *yarn* 1.16.0

CocoaPods version: 1.6.1

Steps to reproduce:

1. `ionic capacitor run --livereload` which should build, run the dev server, add the following to your capacitor.config.json, and open Xcode:
`"server": {
  "url": "http://localhost:8100"
}`

2. `yarn/npm ionic:build` which should build for production.

3. Open Xcode and try to build/install/run the app.

Expected outcome: The app will still try to load livereload files from the url specified in the config even though you are using a production build.

Link to sample project:

**Comment by ebk46** [comment]
Just wanted to leave a note here instead of just closing it. It seems when you close the dev server it is supposed to delete that addition to the config, but in my case it did not. I likely did a stash pop or something that added it back when the dev server was no longer running. When I tested it again it did work properly.

**Comment by jcesarmobile** [comment]
this is an Ionic CLI issue, I've reported it there https://github.com/ionic-team/ionic-cli/issues/4089
