### ISSUE TITLE
Permission handling feature

### ISSUE THREAD

**Issue by Ajax-ua** [ionic-team/capacitor#1728]
I need to provide users with the ability to edit app permissions in their profiles. Short example:
1) User logins to the app
2) After login, he is asked for push notification permission for the app
3) When he accepts/declines it, the switcher in his profile gets the corresponding on/off value
4) When the user tries to change the push notification setting from off to on, then he is asked for push permission again. Thus, in fact, the user is able to manage permissions in his profile

There is no description in the documentation of how to get user response (user decision event) after permission request was prompted to him. Also, there is no mentioning of how to prompt the permission programmatically. Could anyone help me with this?

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by dwieeb** [comment]
@Ajax-ua Would you mind re-creating this in our new [Capacitor Community proposals repo](https://github.com/capacitor-community/proposals)?
