### ISSUE TITLE
Speech recognition plugin is not available for Capacitor

### ISSUE THREAD

**Issue by Madhulika08** [ionic-team/capacitor#1729]
Please add speech recognition plugin for capacitor as well

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

Also, you can use the existing cordova speech recognition plugins.

**Comment by Monomachus** [comment]
:+1:

**Comment by wmjoers** [comment]
👍

**Comment by jcesarmobile** [comment]
you have to click on the 👍 icon on the first message, not comment with 👍

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/18. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
