### ISSUE TITLE
Cordova-plugin-ionic-webview and Capacitor use different ‘origins’ by default

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/capacitor#1736]
For apps currently using cordova-plugin-ionic-webview (v4) and planning to migrate to Capacitor, the saved local storage data will get lost due to different default origins.

**From cordova-plugin-ionic-webview documentation:**
https://github.com/ionic-team/cordova-plugin-ionic-webview

> The default origin for requests from the Android WebView is  `http://localhost` .

> The default origin for requests from the iOS WebView is  `ionic://localhost`

**From Capacitor documentation:**
https://ionicframework.com/docs/faq/cors

> For example, apps running in Capacitor have  `capacitor://localhost`  (iOS) or  `http://localhost`  (Android) as their origin.

**What is the best way to handle this migration?** Can we change the origin for Capacitor to match what we have in cordova plugin, or is it better to configure the cordova plugin 'now' to use whatever Capacitor will want to use 'later' (at least apps not in production yet)? 

cordova-plugin-ionic-webview documentation allows configuring origin, but couldn't find something similar in Capacitor docs. It will also help if a section is added to Migration guide at https://capacitor.ionicframework.com/docs/cordova/migrating-from-cordova-to-capacitor

Best would be to have default origins same for Capacitor and cordova-plugin-ionic-webview, but that will break existing apps.

**Comment by WorldMaker** [comment]
Also: it's interesting that FAQ answer is the Framework docs rather than Capacitor's own. That would be something useful to include in Capacitor's own docs.
