### ISSUE TITLE
Camera plugin doesn't return image path in electron

### ISSUE THREAD

**Issue by musa-pro** [ionic-team/capacitor#1738]
Description of the problem:
When I take picture, it suppose to have image physical path as well on `image.path`, but it is empty in capacitor electron.

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [x] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0
node version:
8.9.4
npm version:
6.9.0
CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by Bktechmasala** [comment]
watch this video to solved all problems capacitor camera plugin https://youtu.be/EPysW31oryk

**Comment by jcesarmobile** [comment]
Can you provide the code you are using?

**Comment by jcesarmobile** [comment]
Ah, I understand now, you are using webPath, but path is empty. 
On web the image is not saved to the file system, so there is no physical path, so the options are to not return anything as there is nothing to return (current approach), or return the same as on webPath.

**Comment by jcesarmobile** [comment]
Going to close since there was no input from the reporter.

As I said, on web/electron, the image is not saved, so there is no path, you can use webPath that will contain the blob url.
