### ISSUE TITLE
TypeError with Modals

### ISSUE THREAD

**Issue by scottopolis** [ionic-team/capacitor#1740]
Initiating a modal such as an alert:

import { Plugins } from '@capacitor/core';

async showAlert() {
  let alertRet = await Plugins.alert({
    title: 'Stop',
    message: 'this is an error'
  });
}

Causes this error when compiling:

ERROR in src/app/pages/bp-modal/bp-modal.ts(291,25): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '{ [prop: string]: any; }' has no compatible call signatures.

It will still compile successfully using ionic serve. When I try to call the alert function in the app, it shows this error:

ERROR Error: Uncaught (in promise): TypeError: _capacitor_core__WEBPACK_IMPORTED_MODULE_10__.Plugins.showActions is not a function
TypeError: _capacitor_core__WEBPACK_IMPORTED_MODULE_10__.Plugins.showActions is not a function
    at BpModal.<anonymous> (bp-modal.ts:291)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at tslib.es6.js:73
    at new ZoneAwarePromise (zone.js:910)
    at Module.__awaiter (tslib.es6.js:69)
    at BpModal.push../src/app/pages/bp-modal/bp-modal.ts.BpModal.imageSheet (bp-modal.ts:289)
    at Object.eval [as handleEvent] (BpModal.html:56)
    at handleEvent (core.js:23107)
    at callWithDebugContext (core.js:24177)
    at resolvePromise (zone.js:831)
    at new ZoneAwarePromise (zone.js:913)
    at Module.__awaiter (tslib.es6.js:69)
    at BpModal.push../src/app/pages/bp-modal/bp-modal.ts.BpModal.imageSheet (bp-modal.ts:289)
    at Object.eval [as handleEvent] (BpModal.html:56)
    at handleEvent (core.js:23107)
    at callWithDebugContext (core.js:24177)
    at Object.debugHandleEvent [as handleEvent] (core.js:23904)
    at dispatchEvent (core.js:20556)
    at core.js:21003
defaultErrorLogger @ core.js:15724

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [ x] web

OS of the development machine
- [ ] Windows
- [x ] macOS
- [ ] linux

Other information: 

Same error using Ionic 4 and 3.x
Typescript: ~3.1.6

Capacitor version: 1.1.0

node version: 9.10.0

npm version: 6.9.0

Dependencies:

{
...
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@capacitor/cli": "^1.1.0",
    "@capacitor/core": "^1.1.0",
    "@ionic-native/action-sheet": "^5.0.0",
    "@ionic-native/admob-free": "^5.0.0",
    "@ionic-native/camera": "^5.0.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/device": "^5.0.0",
    "@ionic-native/dialogs": "^5.0.0",
    "@ionic-native/facebook": "^5.0.0",
    "@ionic-native/file": "^5.0.0",
    "@ionic-native/file-transfer": "^5.0.0",
    "@ionic-native/geolocation": "^5.0.0",
    "@ionic-native/in-app-browser": "^5.0.0",
    "@ionic-native/in-app-purchase": "^5.0.0",
    "@ionic-native/keyboard": "^5.0.0",
    "@ionic-native/network": "^5.0.0",
    "@ionic-native/push": "^5.0.0",
    "@ionic-native/social-sharing": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "@ionic/pwa-elements": "^1.3.0",
    "@ionic/storage": "2.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "anchorme": "^1.1.2",
    "angulartics2": "^7.5.2",
    "core-js": "^2.5.4",
    "guid-typescript": "^1.0.9",
    "rxjs": "^6.5.1",
    "rxjs-compat": "^6.5.2",
    "tslib": "^1.9.0",
    "videogular2": "6.1.1",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.13.8",
    "@angular-devkit/build-angular": "~0.13.8",
    "@angular-devkit/core": "~7.3.8",
    "@angular-devkit/schematics": "~7.3.8",
    "@angular/cli": "~7.3.8",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "~1.5.1",
    "@types/node": "~12.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.3.0",
    "tslint": "~5.17.0",
    "typescript": "~3.1.6"
  }
}

Thanks!

**Comment by scottopolis** [comment]
If I use the constant as in the documentation:

import { Plugins } from '@capacitor/core';

const Modals = { Plugins };

async showAlert() {
let alertRet = await Modals.alert({
title: 'Stop',
message: 'this is an error'
});
}

I get this error on compile instead:

error TS2339: Property 'alert' does not exist on type '{ Plugins: PluginRegistry; }'.

And this error in the browser console:

ERROR Error: Uncaught (in promise): TypeError: Modals.alert is not a function

**Comment by Raerten** [comment]
Try to import `Modals` as in doc (curly braces position):
```
import { Plugins } from '@capacitor/core';

 const { Modals } = Plugins;
```

**Comment by scottopolis** [comment]
@Raerten that worked, thanks so much!
