### ISSUE TITLE
Provide better configuration management / better documentation for configuration management

### ISSUE THREAD

**Issue by macdja38** [ionic-team/capacitor#1741]
In the iOS app build flow and android flow you can configure different variables to be used in Production / Staging / Dev builds.

As it stands at least the documented capacitor workflow for `capacitor.config.json` doesn't allow for using a different values for production vs staging, say you wanted to load from a different server the `server.url` would have to be edited by the user then copies to the environments.

There are also no best practice / documented recommendations on how to manage the `capacitor.config.json` file with source control / with staging / ci environments as far as I can find?

**Comment by Bktechmasala** [comment]
watch this video to solved all problems capacitor camera plugin https://youtu.be/EPysW31oryk

**Comment by dwieeb** [comment]
Closed in favor of https://github.com/ionic-team/capacitor/issues/3141
