### ISSUE TITLE
Storage/Documentation query with capacitor

### ISSUE THREAD

**Issue by coffeymatt** [ionic-team/capacitor#1746]
The capacitor storage docs (https://capacitor.ionicframework.com/docs/apis/storage) say that you need to stringify objects to store them.

However, if I don't, it seems to work just fine. e.g.

```
async saveThing(thing: Thing): Promise<any> {
    return await this.storage.set('Thingy', thing);
  }
```

```
  async getThing(): Promise<Thing> {
    const thing = (await this.storage.get('Thingy')) as Thing;
     return thing;
   }
```

My questions are:

1. Do we definitely need to JSON stringify/parse things in out of storage? My code seems to be working, am I running a risk?

2. Could the library provide some shorthand for this? E.g. 'storage.get&lt;Thing&gt;()' and have get and set just take care of things under the covers if stringify is really needed?

**Comment by jcesarmobile** [comment]
how does `thing` looks like? the bridge can only pass string and a few other simple types, so it's probably doing a stringify somewhere before passing the data for all plugin calls.

**Comment by jcesarmobile** [comment]
closing since there was no response
