### ISSUE TITLE
Project not respecting appName

### ISSUE THREAD

**Issue by tyvdh** [ionic-team/capacitor#1751]
Description of the problem:
Trying to add and build an ios project with my project name but I'm just getting `App`.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
```
// capacitor.config.json
{
  "appId": "com.stellarauth",
  "appName": "StellarAuth",
  "bundledWebRuntime": false,
  "npmClient": "yarn",
  "webDir": "dist"
}
```

```
// ionic.config.json
{
  "name": "StellarAuth",
  "integrations": {
    "capacitor": {}
  },
  "type": "custom"
}
```

![Screen Shot 2019-07-10 at 9 34 09 AM](https://user-images.githubusercontent.com/4383610/60973256-e689f980-a2f5-11e9-917e-023c5cf87457.png)

Capacitor version:
1.1.0

node version:
v10.16.0

yarn version:
1.16.0

**Comment by jcesarmobile** [comment]
The `appName` is only used for the `CFBundleDisplayName`, not for the project structure or target name. 

From Xcode you can change the target name if you want, but you'll have to update the Podfile by replacing `target 'App' do` with `target 'StellarAuth' do`.
