### ISSUE TITLE
Local Notifications icon cannot be changed

### ISSUE THREAD

**Issue by ShinZ6** [ionic-team/capacitor#1752]
Description of the problem:
Cannot change local notifications icon (it stays a circle with an "i" by default) on Android even though I can change the push notifications icon by setting the required property on AndroidManifest.xml. On iOS it takes the app's own launcher icon by default.

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

Capacitor version: 1.1.0

node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by adrm** [comment]
I've been reading the source code to see if there is any way to signal a resource to be used for the notification icon in Android, but it is a known pending task.

https://github.com/ionic-team/capacitor/blob/debe27a2c544224f014e45962958a62bfd815b2f/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotification.java#L181

It seems important enough to be able to have a native feeling app, to be honest. I hope it can be resolved soon.

**Comment by ShinZ6** [comment]
I solved it momentarily by applying the changes made in this pull request:
[https://github.com/ionic-team/capacitor/pull/1510/commits/7e0439da37bc20f83f055156b5b59d877be53643](url)

**Comment by nikosdouvlis** [comment]
Opened #1830 that solved this one
