### ISSUE TITLE
CI build fails to install Pods as capacitor-cordova-ios-plugins is not checked in

### ISSUE THREAD

**Issue by masimplo** [ionic-team/capacitor#1755]
Description of the problem:
Building the project on the development machine that has run `npx cap sync ios` at least once everything works. Checking in the code and running the same build on CircleCI fails with the error 
```
[!] No podspec found for `CordovaPlugins` in `../capacitor-cordova-ios-plugins`
```
as capacitor-cordova-ios-plugins is excluded from git due to the generated .gitignore inside the ios folder. 
`npx cap update ios` generates the folder again, but it is not something I thing should be run on the CI, as it goes against the fact that the native projects are not build artifacts anymore.

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

Capacitor version:
1.1.0
node version:
11.13.0
npm version:
6.7.0
CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
Same way you have to run `npm install`, `npm run build` and some other build commands, it's recommended to run `npx cap sync` in your CI. The native project is not a build artifact, but the cordova plugins still are. That folder is recreated every time you run update/sync commands, so we don't recommend to commit it, but you can change the .gitignore if you want to commit it.

**Comment by masimplo** [comment]
That makes sense, if you think of the cordova plugins as pods. Thanks for clearing that up.
