### ISSUE TITLE
Capacitor storage: Can't find indexeddb in Chrome when iphone is selected in device toolbar

### ISSUE THREAD

**Issue by coffeymatt** [ionic-team/capacitor#1756]
Description of the problem:

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [x] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Other information:

I'm using Capacitor storage and have my driver order set as such:

```
IonicStorageModule.forRoot({
      name: 'cosmos',
      driverOrder: ['sqlite', 'indexeddb']
    })
```

I don't want websql, I want to force indexeddb as websql seems to be prone to clearing itself out from time to time, indexeddb seems to persist and is faster. I also want it to be using the same storage consistently as I test as different devices as I have a lot of offline data in my app.

When in debugging an Ionic/Capacitor app in Chrome, with the developer tools you can select a device e.g. 'Responsive' or 'Galaxy S5' or 'Iphone 6/7/8'. This is really useful as I can see what my app looks like on different platforms very quickly. However, when you select iPhone, it doesn't find indexeddb, it just says:

**Error: No available storage method found.**

With responsive or an android device, it selects indexeddb just fine. If I allow it to use websql (adding it as the last driver), my app runs but obviously it's now using the wrong storage. Indexeddb still works in this mode as I'm using Pouchdb with the indexdb driver, but Ionic/Capacitor refuses to find it.

Capacitor version:

1.1.0

node version:

npm version:

Steps to reproduce:

1. Set up capacitor storage with only the indexeddb driver.
2. Debug your app in Chrome, use the developer tools to select 'Iphone 6/7/8' and refresh.
3. Observe error in debug console: Error: No available storage method found.

**Comment by jcesarmobile** [comment]
I think you are talking about https://ionicframework.com/docs/building/storage right? not Capacitor Storage plugin.
Can you provide a sample app using that plugin?

**Comment by jcesarmobile** [comment]
Closing as there was no response and it's not clear what the problem is, but it's not in Capacitor Storage plugin.
