### ISSUE TITLE
Missing Capacitor.getPlatform()  in android and ios platform

### ISSUE THREAD

**Issue by looklookson** [ionic-team/capacitor#1759]
Description of the problem:
Function Capacitor.getPlatform() implemented in electron and web platform but does not be implemented in Android and iOS platform 

Affected platform
- [x ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
v1.1.0

node version:
v10.15.1

npm version:
v6.4.1 

CocoaPods version:

Steps to reproduce:
The javascript Capacitor.getPlatform()  can return correct value in electron and web platform but failure in andorid and ios platform

Link to sample project:

**Comment by jcesarmobile** [comment]
You can use Capacitor.platform, but yeah, the getPlatform method should also be in those platforms.
