### ISSUE TITLE
How to Request GPS permission

### ISSUE THREAD

**Issue by hamadrehman** [ionic-team/capacitor#1762]
Hello, 
I want to know if there is any way to request GPS permission using capacitor without having to install cordova plugins ?
![image](https://user-images.githubusercontent.com/25491002/61221106-3111d880-a731-11e9-915e-f14d4a42d592.png)
This is the kind of dialogue  I want to trigger to enable GPS

**Comment by jcesarmobile** [comment]
You can use Geolocation plugin itself to request it's permissions like this: `Geolocation.requestPermissions();`

Anyway, it's always recommended to let the plugins work themselves, when you try to use `getCurrentPosition` or `watchPosition`, the plugin will automatically request the permission if not granted.

**Comment by eltoky** [comment]
I have following error: Geolocation.requestPermissions is not a function. (In 'Geolocation.requestPermissions()', 'Geolocation.requestPermissions' is undefined

Looks like the requestPermissions is not defined for Geolocation plugin

**Comment by javiercoh** [comment]
> I have following error: Geolocation.requestPermissions is not a function. (In 'Geolocation.requestPermissions()', 'Geolocation.requestPermissions' is undefined
> 
> Looks like the requestPermissions is not defined for Geolocation plugin

same issue here
