### ISSUE TITLE
jcesarmobile\Library\Android path hardcoded somewhere?

### ISSUE THREAD

**Issue by AndrWeisR** [ionic-team/capacitor#1765]
Description of the problem:
When I build a blank ionic 4/capacitor project and open it in Android Studio for the first time, you get an error from Android Studio:
![Error](https://user-images.githubusercontent.com/34931916/61258788-7b896880-a7b6-11e9-8bae-1ddb1a0d43f4.png)

Affected platform
- [ X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ X] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
1.1.0

node version:
10.16.0

npm version:
6.9.0

CocoaPods version:

Steps to reproduce:
ionic start bug blank --capacitor
npx cap init name name.bug
ionic build
npx cap add android
npx cap open android

Link to sample project:

**Comment by AndrWeisR** [comment]
This is the generated android/local.properties file:

```
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Wed May 15 19:34:14 CEST 2019
sdk.dir=/Users/jcesarmobile/Library/Android/sdk
```

**Comment by jcesarmobile** [comment]
yeah, sorry about that, we have the file gitignored, but npm still published it, will be gone on next release
