### ISSUE TITLE
IFrame Pinch Zoom

### ISSUE THREAD

**Issue by tansah** [ionic-team/capacitor#1771]
Hi.. Can I check if capacitor has any plugin to allow pinch zoom on content within html iframe? Tried to search far and wide, with no progress. What I am trying to achieve is to display a pdf file within iframe using google gview, ie: https://docs.google.com/viewer?url=http://www.pdf995.com/samples/pdf.pdf&embedded=true, also with my other dynamic html / php page, and have the content within iframe zoomable by pinch - in / pinch - out.

Thanks in Advance.

**Comment by jcesarmobile** [comment]
Sorry, this is not an issue. Don’t use issues to ask questions, we have a slack and a forum, ask there.
