### ISSUE TITLE
Change Splash Screen Orientation

### ISSUE THREAD

**Issue by lhaisrs** [ionic-team/capacitor#1778]
I want to change the splash screen orientation of my application to be always portrait. I've tried to do in AndroidManifest.xml but wasn't successful. Do you guys have any ideia how can I do it using capacitor?

**Comment by jcesarmobile** [comment]
But does your app only supports portrait orientation? If it supports both you have to provide both. 
What you can do is to design the landscape splash images to look like they are portrait ones.

**Comment by lhaisrs** [comment]
No, it doesn't support and looks really weird when it's in landscape orientation. I really need put just in the portrait way.

**Comment by jcesarmobile** [comment]
Would be helpful if you could provide a sample app

**Comment by jcesarmobile** [comment]
I've added `android:screenOrientation="portrait"` to the activity tag in the AndroidManifest.xml and then ran the app and the splash screen is only displayed in portrait.
