### ISSUE TITLE
Plugin method is not called when passing complex payload to options

### ISSUE THREAD

**Issue by masimplo** [ionic-team/capacitor#1779]
Description of the problem:
I am trying to port a plugin from Cordova to Capacitor and got to a point where I fill stuck. I am implementing a function that adds one or more contacts to the native addressbook.
Getting the contacts works fine and the result arrives in Ionic perfectly as it did in Cordova.
Trying to add or update one or more contacts, requires a similar payload to what is returned from getContacts to be passed through call options.
When I put a payload in the update call, the native call is never invoked (never even passes from CAPBridgeDelegate), if the payload is empty, the native function is called normally. 

I am worried it has to do with the serialization of the payload or something similar. I tried to find a plugin that receives complex objects through the call options but could not find any. Is there any limitation to the passed objects? 

Calling update function from Ionic
```typescript
CONTACTS.createContacts({ contacts })
```
where contacts is of type `INativeContact[]`

And swift function looks like
```swift
    @objc func createContacts(_ call: CAPPluginCall) {
        let contacts = call.getArray("contacts", [String: Any].self) ?? [[String: Any]]()

        let helper = ContactHelper()
        let result = helper.createContacts(contacts)
        let hasErrors = result["hasErrors"] as? Bool ?? true

        if hasErrors == true {
            call.reject("Did not create contact")
            return
        }
        call.resolve(result)
    }
```

Payload schema looks like
```typescript
export interface INativeContact {
  id?: string;
  name?: INativeName;
  emails?: INativeEmail[];
  phones?: INativePhone[];
  organizations?: INativeOrganization[];
  countries?: ILocation[];
  addresses?: IAddress[];
  notes?: string;
  lastUpdatedAt?: number;
  photoIds?: INativePhotoId[];
  photoBase64?: string;
  checksum?: number;
}

export interface INativeName {
  prefix?: string;
  givenName?: string;
  middleName?: string;
  familyName?: string;
  suffix?: string;
}

export interface INativeOrganization {
  company?: string;
  title?: string;
}

export interface INativeEmail {
  address: string;
}

export interface INativePhone {
  number: string;
  type?: PhoneType;
  label?: string;
}

export interface ILocation {
  country: string;
}

export interface IAddress {
  street1?: string;
  street2?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
  countryIso?: string;
  subAdministrativeArea?: string;
  subLocality?: string;
  poBox?: string;
  neighborhood?: string;
  type?: AddressType;
  label?: string;
}

export interface INativePhotoId {
  fileId: string;
  dataId: string;
  isSuperPrimary: boolean;
}
```

I have also tried replacing the Swift implementation with just a `call.resolve()` but that makes no difference.

Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

Capacitor version:
1.1.1
node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by masimplo** [comment]
Turns out I was passing class objects and Capacitor does not seem to like that. Transforming them to objects did the trick!

**Comment by Boosten** [comment]
@masimplo  I encountered the same behavior. The docs weren't very clear on this. 
Are you also parsing the JSON on the JS layer? I need to use JSON.parse(). I would rather see that the Capacitor layer would take care of this.

**Comment by masimplo** [comment]
> @masimplo I encountered the same behavior. The documentation wasn't very clear on this.
> Are you also parsing the JSON on the JS layer? I need to use JSON.parse(). I would rather see that the Capacitor layer would take care of this.

The data you are passing down to capacitor must be simple JSON objects, not a Class Object, not something with functions, just plain JSON objects with plain properties. At least back when I opened this issue, as I haven't checked if something different works since then. 
As for if Capacitor should handle that, it does sound reasonable, but on the other handle a lot of libraries do not (for instance saving on PouchDb has a similar constrain).
