### ISSUE TITLE
Filesystem dont request permission in iOS (The file doesn´t exists)

### ISSUE THREAD

**Issue by salime45** [ionic-team/capacitor#1780]
I am using this api and works perfectly in android, but in ios dont request permission a show the error "The file xxxxx  doesn´t exists"

    async saveImageInGallery(imageBase64: string) {

      try {

      let date = new Date(),
        time = date.getTime(),
        fileName = time + '.png';

      const path = 'someFolder/' + fileName

      return await Filesystem.writeFile({
        path: path,
        data: imageBase64,
        directory: FilesystemDirectory.Documents,
      })

    } catch (err) {
      console.log("err", err)
      return;
    }

    }
My Info.plist has the keys

<key>NSPhotoLibraryAddUsageDescription</key>
<string>Store camera photos to camera</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>To Pick Photos from Library</string>

I try to read the folder too and similiar error. Anyone know if this is a configuration error o capacitor error?

**Comment by jcesarmobile** [comment]
iOS doesn’t require permissions to write files (and on android it depends on the where you write them, some places don’t require a permission neither).

Will look into the issue on Monday, but a full sample app would be helpful

**Comment by jcesarmobile** [comment]
The problem is "someFolder" doesn't exists and iOS doesn't create the intermediate folders when using writeFile. There is another issue for this already https://github.com/ionic-team/capacitor/issues/1611

**Comment by salime45** [comment]
Hi thank you , Any work around for this? 

I tryed to test with other paths instead "FilesystemDirectory.Documents" but the same error

**Comment by jcesarmobile** [comment]
The only workaround is to use `mkdir` first to create someFolder or to write in the root instead of using the someFolder that doesn't exist.

**Comment by mwyld** [comment]
I'm having the same issue but using `Filesystem.readFile({ path })`. I just get:

> The file … couldn’t be opened because you don’t have permission

I have also tried adding these into the plist

![image](https://user-images.githubusercontent.com/12820928/91826342-59aaa980-ec35-11ea-985f-be68feacb1e3.png)
