### ISSUE TITLE
Can't add android

### ISSUE THREAD

**Issue by juliancruzsanchez** [ionic-team/capacitor#1783]
**Description of the problem:**

**Affected platform**
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

**OS of the development machine**
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

**Capacitor version:** 1.1.1

**node version:** v12.5.0

**npm version:** 6.9.0
**yarn version:** 1.16.0

**CocoaPods version:** 1.7.4

**Steps to reproduce:**
Run the following: 
`admin@Admins-MacBook-Air ~/app> npx cap add android`

This happens:
```
ℹ Installing android dependencies – Skipping: already installed
✖ Adding native android project in: /Users/admin/app/android: ENOENT: no such file or directory, lstat '/Users/admin/app/node_modules/@capacitor/cli/assets/android-template'
✖ add: ENOENT: no such file or directory, lstat '/Users/admin/app/node_modules/@capacitor/cli/assets/android-template'
[error] [Error: ENOENT: no such file or directory, lstat '/Users/admin/app/node_modules/@capacitor/cli/assets/android-template'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/admin/app/node_modules/@capacitor/cli/assets/android-template'
}
```
Link to sample project:

**Comment by juliancruzsanchez** [comment]
This fixed it
![Captura de Pantalla 2019-07-21 a la(s) 1 25 21 p  m](https://user-images.githubusercontent.com/20978820/61595984-fe496380-abba-11e9-8784-43eec8f595c5.png)

**Comment by jcesarmobile** [comment]
I can't reproduce, maybe you didn't install the CLI locally?

I've downloaded the [1.1.1 tarball ](https://registry.npmjs.org/@capacitor/cli/-/cli-1.1.1.tgz) and the files are there.
