### ISSUE TITLE
Android resource linking failed when using a plugin that uses value lookup from xml

### ISSUE THREAD

**Issue by masimplo** [ionic-team/capacitor#1784]
Description of the problem:
When building for android with capacitor-FCM plugin I get:
```
> Task :capacitor-fcm:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':capacitor-fcm:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/michael/Repos/covve.XPApp-Capacitor/node_modules/capacitor-fcm/android/capacitor-fcm/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/michael/Repos/covve.XPApp-Capacitor/node_modules/capacitor-fcm/android/capacitor-fcm/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/michael/Repos/covve.XPApp-Capacitor/node_modules/capacitor-fcm/android/capacitor-fcm/build/intermediates/res/merged/release/values/values.xml:3864: error: resource android:attr/fontVariationSettings not found.
  /Users/michael/Repos/covve.XPApp-Capacitor/node_modules/capacitor-fcm/android/capacitor-fcm/build/intermediates/res/merged/release/values/values.xml:3865: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```
Removing the plugin makes the error go away. 

Adding plugin cordova-plugin-facebook4 and building produces a similar error:
```
> Task :capacitor-cordova-android-plugins:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':capacitor-cordova-android-plugins:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  warn: removing resource capacitor.android.plugins:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.
  /Users/michael/Repos/covve.XPApp-Capacitor/android/capacitor-cordova-android-plugins/build/intermediates/aapt_friendly_merged_manifests/release/aapt/AndroidManifest.xml:54: error: resource string/fb_app_id (aka capacitor.android.plugins:string/fb_app_id) not found.
  /Users/michael/Repos/covve.XPApp-Capacitor/android/capacitor-cordova-android-plugins/build/intermediates/aapt_friendly_merged_manifests/release/aapt/AndroidManifest.xml:57: error: resource string/fb_app_name (aka capacitor.android.plugins:string/fb_app_name) not found.
  /Users/michael/Repos/covve.XPApp-Capacitor/android/capacitor-cordova-android-plugins/build/intermediates/aapt_friendly_merged_manifests/release/aapt/AndroidManifest.xml:61: error: resource string/fb_app_name (aka capacitor.android.plugins:string/fb_app_name) not found.
  error: failed processing manifest.
```

But strings.xml has the required values that the build nags about: 
```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">xxx</string>
    <string name="title_activity_main">xxx</string>
    <string name="package_name">xxx</string>
    <string name="fileprovider_authority">xxx</string>
    <string name="custom_url_scheme">xxx</string>
    <string name="fb_app_id">xxx</string>
    <string name="fb_app_name">xxx</string>
</resources>

```
This happens consistently when doing a command line build with `gradlew`. Building with Android Studio this error comes up like 3 times out of 10. Some builds are successful. On another machine this error happens 10/10 in android studio.

Affected platform
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version:
1.1.1
node version:
10.15.3
npm version:
6.9.2
CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
For the first error, that happens when the targetSdkVersion and the android support libraries versions don't match, so you'll have to make them match.

For the second, there is another issue already open where you already commented. https://github.com/ionic-team/capacitor/issues/943.

**Comment by masimplo** [comment]
For the first it seems that these version in my project do match, unless you mean something different.
```
android {
    compileSdkVersion 28
    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 28
    }
```
and
```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation project(':capacitor-android')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation project(':capacitor-cordova-android-plugins')

    // Needed for crashlytics
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
}
```
TargetSdkVersion is 28 and support libraries are also 28.

For the second error, I am aware of the other issue that I commented on, which was the first I found after I faced this issue, but since a similar error occurs when removing the facebook plugin thought that there is a more generic underlined issue here. Maybe I should have posted this over to the other issue, but did not want create confusion.

**Comment by jcesarmobile** [comment]
but the plugin is using 27.1.1 in a few of it's dependencies https://github.com/stewwan/capacitor-fcm/blob/master/android/capacitor-fcm/build.gradle#L48

**Comment by masimplo** [comment]
Oh so I have to match the SDK of the plugins even though I am defining a greater support library as an app dependency. 
Can I use that lowest or does it have to be the same? Because if it has to be the same, then we need to keep all plugins in sync, which can turn into a real problem. I will go ahead and try setting my app SDK version to 27 and see what happens.
Thanks for the input, I appreciate it.

**Comment by jcesarmobile** [comment]
Supposedly if you add the exact same dependency with the version you want to use to the app's build.gradle it will use that version, but sometimes fails for some strange reason (I blame gradle).

You can also force the gradle version for all modules/plugins by adding this to the project's build.gradle (not the app one, the project one)

```
project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && details.requested.name != 'multidex'
                    && details.requested.name != 'multidex-instrumentation') {
                details.useVersion 28.0.0
            }
        }
    }
```

We also plan to add gradle variables so it's easier to set common versions, but once we do, plugins should also need to be updated to use those variables instead of fixed versions.
