### ISSUE TITLE
CameraResultType.Base64 contain "new line" or '\n' on Android Device

### ISSUE THREAD

**Issue by alghifari24** [ionic-team/capacitor#1786]
Description of the problem:
Camera Plugins for CameraResultType.Base64 result contain **new line** or '**\n**' after each 75 character. Its will need to remove new line tag to add on html image source. This bug will show on android device,on web its normal.

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Capacitor version: v 1.1
node version: v 9.11.1
npm version: v 5.7.1

**Comment by jcesarmobile** [comment]
what's you @capacitor/android version?

**Comment by alghifari24** [comment]
> what's you @capacitor/android version?

@capacitor/android : v 1.1.0

**Comment by jcesarmobile** [comment]
I can see the new lines, but I don't see it preventing from displaying on devices. Can you share a sample app or some code you are using?

**Comment by alghifari24** [comment]
> I can see the new lines, but I don't see it preventing from displaying on devices. Can you share a sample app or some code you are using?

**component.page.ts**
```typescript
import { DomSanitizer } from '@angular/platform-browser';
export class PhotoUploadPage implements OnInit {
  constructor(private sanitizer: DomSanitizer) { }
  async openCamera() {
    const selectimage = await Camera.getPhoto({
      quality: 90,
      width: 800,
      correctOrientation: true,
      resultType: CameraResultType.Base64,
      saveToGallery: true,
      source: CameraSource.Camera
    });
    
    // im using this code to remove new line
    // this.base64Image = selectimage.base64String.replace(/(\r\n|\n|\r)/gm, '');
    this.base64Image = selectimage.base64String;
  }
 }

  transform(base64Image) {
    return this.sanitizer.bypassSecurityTrustResourceUrl('data:image/jpeg;base64, ' + base64Image);
  }

}
```

**component.page.html**
```typescript
<img [src]="transform(base64Image)">
```

**Comment by jcesarmobile** [comment]
With your code the image is still displayed properly, base64 allows those new line characters.

Anyway, will remove it for consistency with iOS.
