### ISSUE TITLE
iOS stuck at splashscreen

### ISSUE THREAD

**Issue by bhumin3i** [ionic-team/capacitor#1787]
i download repo and follow all steps after run application splachscreen is stuck and in console xcode ill show error:

`Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

![Screen Shot 2019-07-22 at 3 40 47 PM](https://user-images.githubusercontent.com/25737987/61624989-5190e400-ac97-11e9-97e4-3125171db25d.png)

**Comment by ConnorsApps** [comment]
This issue can also happen if the iOS project does not include config.xml. The exception can be thrown here https://github.com/ionic-team/capacitor/blob/87a46a13da4cda6bfaf95fff4c6310d3e558ebd3/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L47
