### ISSUE TITLE
[Filesystem Plugin] writeFile should return file URI and webpath URI

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/capacitor#1788]
Currently, after writing a file, you have to use `Filesystem.getUri` to retrieve the newly created file URI. Could the `writeFile` function return the URI, which would save a step?

**Current:**
`
await Filesystem.writeFile({
        path: new Date().getTime() + '.jpeg',
        data: readFile.data,
        directory: FilesystemDirectory.Data
      });

    const newFile = await Filesystem.getUri({
      directory: FilesystemDirectory.Data,
      path: fileName
    });

    return newFile.uri;
`

**Proposed:**
const newFile = await Filesystem.writeFile({
        path: new Date().getTime() + '.jpeg',
        data: readFile.data,
        directory: FilesystemDirectory.Data
      });
const uri = newFile.uri;

Additionally, returning the webpath URI from `writeFile` would be great, too - so the user doesn't have to convert using this:

`const webPathUri = Capacitor.convertFileSrc(newFile);`

**Comment by jcesarmobile** [comment]
It is like that because the plugin "mimics" the node API.

I'm not opposed to changing the plugin to return the paths, but would like to know @mlynch opinion first.

**Comment by bitflower** [comment]
Hi, I would appreciate this change as well.

One question: The `uri` does change with every app start, right? Is this the expected behaviour or a bug?

For example I have tracked this down before and after app restart:
```
{
  "NEW_URI": "file:///var/mobile/Containers/Data/Application/7321B7D3-0BA3-475B-AC12-7A70BC4E6F16/Documents/5dc73a223379e923e19bd9b8.png",
  "OLD_URI": "file:///var/mobile/Containers/Data/Application/CF11919B-2C65-458F-B1A3-B7D197A2CE8D/Documents/5dc73a223379e923e19bd9b8.png",
  "IS_DIFFERENT": true
}
```
See Slack reference: https://getcapacitor.slack.com/archives/C88QP9W56/p1573416440072600

Thanks!
