### ISSUE TITLE
cordova-plugin-facebook4 always get User Cancelled when logging with App

### ISSUE THREAD

**Issue by bandodebits** [ionic-team/capacitor#1790]
ionic start issue-ionic --capacitor
npx cap init issue-ionic com.thiago.FBDemoApp
ionic build
npx cap add ios
npx cap open ios
ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="FBDemoApp"
# in capacitor apps, those cordova params doesn't do much, as explained here: 
# https://www.joshmorony.com/using-cordova-plugins-that-require-install-variables-with-capacitor/
npx cap sync

**Comment by bandodebits** [comment]
Ionic:

   Ionic CLI                     : 5.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : 0.5.1 (update available: 0.5.2)
   native-run  : 0.2.7 

System:

   Android SDK Tools : 26.1.1 (/Users/xxxx/Library/Android/sdk)
   NodeJS            : v10.16.0 (/usr/local/Cellar/node@10/10.16.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

**Comment by bandodebits** [comment]
I did exactly the same setup using Cordova, and had success logging with Facebook App.

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce, I created a new app, configured it manually and called `facebookConnectPlugin.login(['email', 'public_profile'], function(){console.log('success');}, function(){console.log('failure');})`, that prompted me to open Facebook app, then logged in and came back with the app and executed the success success

**Comment by bandodebits** [comment]
Sorry, but the problem is with the cordova-plugin-facebook4 4.2.1 version, not the 5.0.0.
Did you used the "Login with App" ou "Email and Phone"? The problem only occurs using Facebook App

**Comment by jcesarmobile** [comment]
If you provide a sample app I’ll look into it.
