### ISSUE TITLE
Android cap sync fails with: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by vially** [ionic-team/capacitor#1793]
Description of the problem:

`npx cap sync android` fails with: `[fatal] TypeError: Cannot read property 'replace' of undefined` when a cordova plugin contains:

```xml
<edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">
    <uses-sdk android:minSdkVersion="16" android:maxSdkVersion="23" />
</edit-config>
```

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information: N/A

Capacitor version: `1.1.1`

node version: `10.16.0`

npm version: `6.10.1`

CocoaPods version: N/A

Steps to reproduce:

1. Install a cordova plugin that contains an `edit-config` block in its `plugin.xml` similar to:

```xml
<edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">
    <uses-sdk android:minSdkVersion="16" android:maxSdkVersion="23" />
</edit-config>
```

One such plugin is the [phonegap-nfc](https://github.com/chariotsolutions/phonegap-nfc), but most probably there are lots of others ([relevant section](https://github.com/chariotsolutions/phonegap-nfc/blob/aa92afca3686dff038d71d2ecb270c62e07c4bcb/plugin.xml#L39-L41) in `plugin.xml`).

2. Run: `npx cap sync android`

This will fail with the error: `[fatal] TypeError: Cannot read property 'replace' of undefined`

This error is thrown from [this line of code](https://github.com/ionic-team/capacitor/blob/93b1434a7bd8719a9831aef86ba46cbdcf708ab5/cli/src/android/update.ts#L253).

This is due to [configElement.$.parent](https://github.com/ionic-team/capacitor/blob/93b1434a7bd8719a9831aef86ba46cbdcf708ab5/cli/src/android/update.ts#L219) being `undefined` when `configElement` has this structure:

```json
{
  "$": {
    "file": "AndroidManifest.xml",
    "target": "manifest/uses-sdk",
    "mode": "merge"
  },
  "uses-sdk": [{"$": "[some object]"}]
}
```

**Comment by jcesarmobile** [comment]
awesome issue

**Comment by vially** [comment]
Wow, that was quick! :+1:
