### ISSUE TITLE
capacitor android java.io.IOException: Cleartext HTTP traffic to * not permitted

### ISSUE THREAD

**Issue by edy-ap** [ionic-team/capacitor#1795]
add android:usesCleartextTraffic="true" to AndroidManifest.xml to resolve java.io.IOException: Cleartext HTTP traffic to * not permitted

**Comment by jcesarmobile** [comment]
Can you please provide a little more information?
Or even better if you can provide a sample app.

**Comment by jcesarmobile** [comment]
closing as there was no response an is not clear what the issue is.
