### ISSUE TITLE
LocalNotification: Get pending notification content and not just the id

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/capacitor#1796]
Description of the problem:
Calling the `LocalNotifications.getPending()` function will only return an array of id's instead of the whole notification items. The Cordova plugin returns the whole notification information. This should be implemented in capacitor too.

Affected platform
- [x] Android
- [x] iOS
- [x] electron
- [x] web

OS of the development machine
- [x] Windows
- [x] macOS
- [ ] linux

Capacitor version:
Latest

node version:
Latest

npm version:
Latest

CocoaPods version:
Latest

**Comment by JoshuvaGeorge03** [comment]
Any update on this issue?

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

**Comment by Unkn0wn0x** [comment]
The feature would be awesome. For now, the only workaround I see is to use the devices storage to store the Notification itself, before it gets scheduled.

Hope this will get some attention.

**Comment by jcesarmobile** [comment]
on @capacitor/local-notifications getPending returns more information about the notification and not just the id, removing the labels
