### ISSUE TITLE
Capacitor browser options

### ISSUE THREAD

**Issue by ekwok1** [ionic-team/capacitor#1803]
Having issues with browser option to click "done". Will there be future browser options for the ability to hide navigation, location, toolbar, etc?

**Comment by kickertw** [comment]
To clarify, I'm also noticing the issue w/ regards to the In-App Browser "done" button for iOS devices. I wanted to capture the event emitted when the button is pressed (I'm assuming there is a browser finished event), but it's not capturing as expected.

**Comment by jcesarmobile** [comment]
This code is working fine on iOS for me:

```
import { Plugins } from '@capacitor/core';
const { Browser } = Plugins;
```

Then in the constructor of the page where I'm listening (angular app, might be different with other frameworks, or could be better places to do it depending on your app, this was just a quick test)

```
Browser.addListener('browserFinished', (info: any) => {
    console.log('browserFinished with info ', info); // there isn't really any info
});
```
It's fired as soon as I click the close button.

The plugin uses `SFSafariViewController`, which doesn't allow to hide the native controls, so we won't be able to make that configurable.
