### ISSUE TITLE
[Feature Request]Webpack intergration needed

### ISSUE THREAD

**Issue by hugetiny** [ionic-team/capacitor#1807]
I can't use Webpack hot-load server.
Any schedule for Webpack intergration?

**Comment by jcesarmobile** [comment]
Sorry, but I'm not sure what you can't integrate or why. 
As long as you have a hot reload server you just have to configure your app to load from the server url. 
Check the configuration docs to see how to configure to load from a server https://capacitor.ionicframework.com/docs/basics/configuring-your-app
