### ISSUE TITLE
bug: Replace deprecated AssetsLibrary for macOS 15 support

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/capacitor#1814]
Description of the problem:
macOS 10.15 deprecated the `AssetsLibrary` (found inside the `CDVURLProtocol.m` file).
By replacing the library Capacitor should be able to run on macOS Catalina as an native app.

Affected platform
- [x] macOS

OS of the development machine
- [ ] Windows
- [ ] macOS
- [ ] linux

Other information:

```
AssetsLibrary is deprecated and is not available when building for Mac Catalyst. Consider migrating to Photos instead, or use `#if !TARGET_OS_MACCATALYST` to conditionally import this framework.
```

Capacitor version: latest

node version: latest

npm version: latest

CocoaPods version: latest

Steps to reproduce:

1. Create a new Capacitor project
2. Open Xcode 11
3. Activate macOS as target platform
4. Build the app

**Comment by danielsogl** [comment]
I think this bug could be fixed by replacing the Cordova file-plugin with the capacitor api. But I'm not sure if the import will be included even without cordova-plugin-file.

**Comment by jcesarmobile** [comment]
This is from `CDVURLProtocol` class, not from `cordova-plugin-file`, we don't include `cordova-plugin-file` by default (but if users add it, it also imports AssetsLibrary and won't work).

 We only added `CDVURLProtocol` for better Cordova plugin compatibility (let some plugins using it to compile), but as `CDVURLProtocol` doesn't work with WKWebView, we can try to remove enough code from the class that allows to be compatible with macOS, but keep compiling when plugins contain the class.

Will try to remove it tomorrow, but it's not going to be enough to make macOS 15 work, will need a few more changes, but not sure if it's a planned update in short term (it's not even launched yet)
