### ISSUE TITLE
isPluginAvailable is inaccurate (?)

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/capacitor#1817]
Description of the problem:
When asking `isPluginAvailable` if platform has plugin it returns true (in this case for web), but when calling plugin methods I get an error: `Uncaught (in promise): EmailPlugin does not have web implementation.`

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [x] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

```ts
import { Injectable } from '@angular/core';

import { Capacitor } from '@capacitor/core';
import { Email } from '@teamhive/capacitor-email';

@Injectable({
	providedIn: 'root'
})
export class EmailService {

	public isAvailable(): boolean {
		const isPluginAvailable = Capacitor.isPluginAvailable('EmailPlugin');
		console.log('Is email plugin available?', isPluginAvailable); // returns true on web
		return isPluginAvailable;
	}

	public async open(to: string, subject: string, body: string, debugInfo?: string): Promise<any> {
		const email = new Email();
		return email.open(); // error on web: Uncaught (in promise): EmailPlugin does not have web implementation.
	}

}
```

This is the capacitor plugin I'm using: https://github.com/TeamHive/capacitor-email and as far as I can tell it has a web implementation - but maybe it's not setup correctly? I haven't been able to tell from reading capacitor docs or comparing to other plugins.

**Comment by jcesarmobile** [comment]
`isPluginAvailable('something')` only checks if `Capacitor.Plugins` has a `something` property, and that plugin is adding it, so technically is working as expected. 

Not sure if it's a bug in the plugin, but I get the same "Does not have web implementation" error if using as stated in their docs.
It works if I use it like this:
```
const email = new Email();
const { EmailPlugin } = Plugins;
EmailPlugin.open();
```
