### ISSUE TITLE
Filesystem 'mkdir' function cannot recursively create files/directories.

### ISSUE THREAD

**Issue by alexdhill** [ionic-team/capacitor#1831]
Description of the problem:

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
The Filesystem.mkdir function is unable to create a directory when the path specified in the "path" key of options is set to 'parent/dir' as opposed to just 'dir'. createIntermediateDirectories is set to true but it still doesn't function.

Capacitor version:
"@capacitor/core": "1.1.1",

node version:
v10.14.2

npm version:
6.10.1

CocoaPods version:
1.7.5

Steps to reproduce:
-Create Ionic project ($ ionic start {{proj}} blank --no-cordova)
-Add Capacitor ($ ionic integrations enable capacitor)
-create function using mkdir
---path: 'parent/dir'
---directory: Filesystem.Documents
---createIntermediateDirectories: true
-update tsconfig file
-build (ionic build)
-add electron (npx cap add electron)
-run (npx cap open electron)

Link to sample project:
https://github.com/alexdhill/Capacitor-Filesystem-Recusion

**Comment by jcesarmobile** [comment]
Already fixed
https://github.com/ionic-team/capacitor/pull/1812

But needs electron 5

**Comment by alexdhill** [comment]
Thanks for the info, but my function is still failing in electron v5.0.6.

**Comment by jcesarmobile** [comment]
It's not released yet, will be in next one
