### ISSUE TITLE
Fullscreen not working in iOS

### ISSUE THREAD

**Issue by black-hawk85** [ionic-team/capacitor#1834]
Description of the problem:

I am working with capacitor plugin (nice work by the way) and using [vue-fullscreen](https://github.com/mirari/vue-fullscreen).
Since v1.1.1 it is working for Android but iOS is not turing into fullscreen mode.
Can this problem be reviewed?

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Capacitor version: 1.1.1

node version: 10.16.0

npm version: 6.10.0

CocoaPods version: 1.7.2

**Comment by jcesarmobile** [comment]
Consider I have no idea about vue nor know what "vue-fullscreen" component is supposed to do, so can you provide more details and a sample?

Also, you say "since 1.1.1", so was it working before? or you didn't try?

**Comment by black-hawk85** [comment]
I had linked the plugin, there is an example given with it.
The plugin is supposed to fullscreen a specific Vue-Component which is placed anywhere on your site.

I tried with v1.1.0 and it wasn't working on Android aswell.
Since v1.1.1 it is working on Android but on iOS is still not working.

**Comment by jcesarmobile** [comment]
That plugin uses Full Screen API, but that is not enabled on WKWebView, so if you want that feature you should report it to Apple.
