### ISSUE TITLE
Add note on Filesystem API docs

### ISSUE THREAD

**Issue by mrodal** [ionic-team/capacitor#1835]
I think a note should be added to the filesystem api docs, saying that the Application directory should not be used for iOS. 
I was trying to use it and it was working well on the iOS emulator, but on real devices I was getting an error saying that the app didnt have permissions to write there.

Here's more info
https://stackoverflow.com/a/3439986/3552458

**Comment by jcesarmobile** [comment]
Thanks for the issue, the Application directory has never worked on iOS and it's not the real application directory on Android. I've created an issue to discuss if we remove it or properly implement it with a few questions, would be good if you can chime in. 

https://github.com/ionic-team/capacitor/issues/2312
