### ISSUE TITLE
 Showing Recent Messages Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by andirsun** [ionic-team/capacitor#1840]
Description of the problem:

Affected platform

- [ ] iOS

OS of the development machine
- [ ] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:

node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/linamarvalencia/Library/Developer/Xcode/DerivedData/App-crvwvskyflislfgmcpcgnctzbbac/Build/Intermediates.noindex/App.build/Debug-iphoneos/App.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh (in target: App)
    cd /Users/linamarvalencia/Downloads/EddyMusicAplication-master/ios/App
    /bin/sh -c /Users/linamarvalencia/Library/Developer/Xcode/DerivedData/App-crvwvskyflislfgmcpcgnctzbbac/Build/Intermediates.noindex/App.build/Debug-iphoneos/App.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh

mkdir -p /Users/linamarvalencia/Library/Developer/Xcode/DerivedData/App-crvwvskyflislfgmcpcgnctzbbac/Build/Products/Debug-iphoneos/App.app/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/linamarvalencia/Library/Developer/Xcode/DerivedData/App-crvwvskyflislfgmcpcgnctzbbac/Build/Products/Debug-iphoneos/Capacitor/Capacitor.framework" "/Users/linamarvalencia/Library/Developer/Xcode/DerivedData/App-crvwvskyflislfgmcpcgnctzbbac/Build/Products/Debug-iphoneos/App.app/Frameworks"
building file list ... done
Capacitor.framework/
Capacitor.framework/Capacitor
Capacitor.framework/Info.plist

sent 2138234 bytes  received 70 bytes  4276608.00 bytes/sec
total size is 2137742  speedup is 1.00
Code Signing /Users/linamarvalencia/Library/Developer/Xcode/DerivedData/App-crvwvskyflislfgmcpcgnctzbbac/Build/Products/Debug-iphoneos/App.app/Frameworks/Capacitor.framework with Identity iPhone Developer: Jhon Rubio Delgado (K2G9MW6WT8)
/usr/bin/codesign --force --sign BCCF645AE9AFEB3C40AECB18E54B3D3144A2A2B6  --preserve-metadata=identifier,entitlements '/Users/linamarvalencia/Library/Developer/Xcode/DerivedData/App-crvwvskyflislfgmcpcgnctzbbac/Build/Products/Debug-iphoneos/App.app/Frameworks/Capacitor.framework'
/Users/linamarvalencia/Library/Developer/Xcode/DerivedData/App-crvwvskyflislfgmcpcgnctzbbac/Build/Products/Debug-iphoneos/App.app/Frameworks/Capacitor.framework: errSecInternalComponent
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by andirsun** [comment]
I cant build the project for simulator, but i cant build for real phone. and i cant update to appstore

**Comment by jcesarmobile** [comment]
It says it’s failing in the script phase.
What’s the Script-9592DBEFFC6D2A0C8D5DEB22.sh and what’s it doing?

**Comment by andirsun** [comment]
@jcesarmobile I solved . Just it was failed permission of access token .

**Comment by jcesarmobile** [comment]
Ok, closing then.

**Comment by giuliu** [comment]
@andirsun Could you be more specific about the solution, please? I have also faced the same problem.

**Comment by andirsun** [comment]
> @andirsun Could you be more specific about the solution, please? I have also faced the same problem.
THe xcode says that you need to put your pass of your keystore, then you need to put your admin password and press always remember or always use this password("i cant remeber well the phrase")
