### ISSUE TITLE
Browser: ability to insert CSS

### ISSUE THREAD

**Issue by francescomosca** [ionic-team/capacitor#1842]
The plugin InAppBrowser (Ionic Native) is able to [insert custom CSS](https://github.com/apache/cordova-plugin-inappbrowser#inappbrowserinsertcss) in the webpage.
May this feature be added in the Capacitor Browser plugin?

**Comment by jcesarmobile** [comment]
It’s not possible, the native components used by the plugin don’t allow it for security reasons.
