### ISSUE TITLE
Camera Plugin will crash the app if no photo app installed in Android

### ISSUE THREAD

**Issue by mrahmadt** [ionic-team/capacitor#1845]
Description of the problem:

App will crash if no photo app installed in the device and camera app will not work,

catch {\"message\":\"Unable to create photo on disk\"}"
java.io.IOException: No such file or directory

Affected platform
- [X ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ X] Windows
- [ ] macOS
- [ X] linux

Other information:

Full log
https://www.dropbox.com/s/vgpwx34vf82bz5a/log-2.json?dl=0

Capacitor version:
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (/home/x/.nvm/versions/node/v12.6.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.801.1
   @angular-devkit/schematics    : 8.1.1
   @angular/cli                  : 8.1.1
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.6.0 (/home/x/.nvm/versions/node/v12.6.0/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.4

node version:
12.6.0
npm version:
6.9.0
CocoaPods version:

Steps to reproduce:

    Plugins.Camera.getPhoto({
      allowEditing: false,
      quality: 50,
      source: CameraSource.Prompt,
      correctOrientation: true,
      // height: 320,
      width: 300,
      //resultType: CameraResultType.Base64
      resultType: CameraResultType.DataUrl
    })
      .then(image => {
        console.log('onPickImage then');
        alert('THEN');
        //this.selectedImage = image.base64Data;
        //this.imagePick.emit(image.base64Data);
        this.selectedImage = image.dataUrl;
        this.imagePick.emit(image.dataUrl);

      })
      .catch(error => {
        console.log('onPickImage catch',error);
        alert('error');
        if (this.usePicker) {
          this.filePickerRef.nativeElement.click();
        }
        return false;
      });

Link to sample project:

**Comment by jcesarmobile** [comment]
The "Unable to create photo on disk" has been fixed here: https://github.com/ionic-team/capacitor/pull/2016
