### ISSUE TITLE
Background mode on web?

### ISSUE THREAD

**Issue by jakub-cywka** [ionic-team/capacitor#1846]
Description of the problem:
I'm developing a pomodoro application and I'd like to know how I can use setInterval() in the background - I recently discovered BackgroundTask Capacitor Plugin, but this seems to not work on the web.

Affected platform
- web

OS of the development machine
- Windows

Other information:
When trying to use setInterval() in the background - it doesn't work. When using isPluginAvaitable(), Capacitor shows BackgroundTask is not available for the web usage. I'm using React.
Capacitor version:
1.1.0
node version:
8.11.2
npm version:
6.7.0
CocoaPods version:
-

Steps to reproduce:
- Try to use BackgroundTask plugin on web

Link to sample project:
-

**Comment by jcesarmobile** [comment]
There is a [background task API on some browsers](https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API), but it's not the same as the native Background Task for iOS/Android. It's for queueing tasks to be executed automatically by the user agent when it determines that there is free time to do so.

Going to clse as feature request, but I don't think we will be able to implement something like the native code for browsers as @macdja38 explained.

Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by jcesarmobile** [comment]
we have killed the Background plugin so we won't be doing this for web, removing the labels
