### ISSUE TITLE
npx cap init fails: error on install node-gyp rebuild

### ISSUE THREAD

**Issue by yuvalbl** [ionic-team/capacitor#1847]
I've tried to use the `npx cap` [initialization command](https://capacitor.ionicframework.com/docs/getting-started#adding-capacitor-to-an-existing-web-app) and got the following:
```
me@machine:~/playground$ sudo npx cap init
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/me/.npm/_npx/9713/lib/node_modules/cap/build'
gyp ERR! System Linux 4.15.0-55-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/me/.npm/_npx/9713/lib/node_modules/cap
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cap@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This was after I've  upgraded from node `v10.15`. Got a similar issue on macOS (mojave 10.14).
According to log file, error occur on installation of `node-gyp` and `rebuild`:
```
105 verbose stack Error: cap@0.2.1 install: `node-gyp rebuild`
105 verbose stack Exit status 1
105 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
105 verbose stack     at EventEmitter.emit (events.js:193:13)
105 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
105 verbose stack     at ChildProcess.emit (events.js:193:13)
105 verbose stack     at maybeClose (internal/child_process.js:999:16)
105 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
106 verbose pkgid cap@0.2.1
```

However, I had no problem to install `node-gyp` and `rebuild` globally.
Also, this `permission denied` message occur even when using superuser / after changing the ownership of `/home/me/.npm/_npx` to current user.

**Comment by jcesarmobile** [comment]
Did you install `@capacitor/cli` first?

**Comment by yuvalbl** [comment]
No. Is it require even when using `npx`?

**Comment by yuvalbl** [comment]
Installing `@capacitor/cli` solve the issue, and android was added successfully.
However, I get an error when trying to `open android`

```
$ npx cap open android
[info] Opening Android project at /home/my-app/android
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/android-studio/bin/studio.sh ENOENT
```

This might be unrelated to the original issue

**Comment by jcesarmobile** [comment]
Yes, you need the CLI installed to use `npx cap` command.

To configure the Android Studio path, you can add `"linuxAndroidStudioPath": "/your/path/to/android/studio.sh"` in the `capacitor.config.json` file.
