### ISSUE TITLE
Improper CSS Rendering With Transitions From Color To Transparent On iOS

### ISSUE THREAD

**Issue by brandonhudson** [ionic-team/capacitor#1849]
Description of the problem:
CSS not properly transitioning from a colored background to a transparent background. The transition works correctly going from transparent -> color. Also works correctly when transitioning between two colors.

Example of failing CSS:
```
.navbar-top {
    background: transparent;
   
    transition: background .15s ease-in, border .15s ease-in;

    &.navbar-dark {
        background: #000000;
    }
}
```

![vA2NWiQfY8](https://user-images.githubusercontent.com/3893578/62510258-577cde00-b7dc-11e9-8d99-363f44d53d4c.gif)

-------------
Example of working CSS:
```
.navbar-top {
    background: #FFFFFF;
   
    transition: background .15s ease-in, border .15s ease-in;

    &.navbar-dark {
        background: #000000;
    }
}
```

![zLsItolo9g](https://user-images.githubusercontent.com/3893578/62510256-551a8400-b7dc-11e9-820f-d27743e8164b.gif)

-------------
Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:
App is running AngularJS 1.7.7 and using Bootstrap for CSS/SCSS styling. Tested transition and verified it works in all modern browsers with both transparent -> color and color -> transparent.

Capacitor version:
1.1.1

node version:
v11.10.0

npm version:
6.7.0

CocoaPods version:

Steps to reproduce:
Copy the class above and use it on an element.

Link to sample project:
N/A

**Comment by jcesarmobile** [comment]
can you provide a sample app where it can be easily reproduced?

also, does it only happen in Capacitor? or the behaviour is the same in iOS Safari?

**Comment by jcesarmobile** [comment]
closing as there was no response
