### ISSUE TITLE
Geolocation not working in electron prod build

### ISSUE THREAD

**Issue by karvannan-thi** [ionic-team/capacitor#1850]
Description of the problem:

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [x] Windows
- [x] macOS
- [ ] linux

Other information:
web Geolocation plugin file is empty in electron
All web plugin file show in as empty. 
Capacitor version: 1.1.1

node version: 10

npm version: 6.2

CocoaPods version:

Steps to reproduce:

When I include geolocation plugin in the app and build in electron. Geolocation function return error. 

Link to sample project:

**Comment by jcesarmobile** [comment]
Did you install @capacitor/core as a dependency or devDependency (check where it is in the package.json)

**Comment by karvannan-thi** [comment]
In package.json contain
   `"@capacitor/android": "^1.1.0",
    "@capacitor/cli": "1.1.0",
    "@capacitor/core": "1.1.0",
    "@capacitor/electron": "^1.1.1",
    "@capacitor/ios": "^1.1.0",`

**Comment by jcesarmobile** [comment]
and what do you mean by "prod build"?

**Comment by karvannan-thi** [comment]
when in build production version like 
`ionic build --prod`
`npx cap copy`
In electron app, web plugin is empty like geolocation.  web plugin not working in an electron app.

**Comment by jcesarmobile** [comment]
can you make sure "@capacitor/core" is in dependencies and not in devDependencies?
I can't reproduce

**Comment by karvannan-thi** [comment]
its in dependencies only.

**Comment by jcesarmobile** [comment]
Sorry, I still can't reproduce.
Try updating @capacitor/cli, @capacitor/core and @capacitor/electron to latest.
