### ISSUE TITLE
Can not build fresh Android project

### ISSUE THREAD

**Issue by ndhbr** [ionic-team/capacitor#1854]
Description of the problem:
If i remove the .gradle/ and android/ folder and run `npx cap add android` the folders get created again. After that i run `npx cap open android`. Android Studio opens and i want to run my app. After pressing the play button this error message shows up:
![Bildschirmfoto 2019-08-07 um 10 14 18](https://user-images.githubusercontent.com/13482230/62606294-34e1e680-b8fc-11e9-97d1-a990312bd55a.png)

Affected platform
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

Capacitor version: 1.1.1

node version: v12.6.0

npm version: 6.9.0

CocoaPods version: 1.6.1

Steps to reproduce:
1. `npx cap add android`
2. `npx cap open android`
3. Try to build project

**Comment by LukaszGrela** [comment]
Does calling `npx cap update` and/or `npx cap copy` (assuming web project was built) makes any difference? You could try also in Android Studio to `Sync Project with Gradle Files`.

**Comment by ndhbr** [comment]
I did all that things a hundred times.

Finally i got it working with reinstalling capacitor cli + core.
