### ISSUE TITLE
Electron Geolocation Error

### ISSUE THREAD

**Issue by appskitchen** [ionic-team/capacitor#1858]
Description of the problem:
I tried the codes below (Following this article [https://capacitor.ionicframework.com/docs/apis/geolocation/] ) ) in an electron project - 
```
async getGeoLocation() {
    try {
      const coordinates = await Geolocation.getCurrentPosition();
      console.log('Current', coordinates);
    } catch (err) {
      console.error(err);
      debugger;
    }
  }
```
But it throws me PositionError, code 2.
I was expecting it should return the coordinates as I've internet access(Although I don't have GPS device in it). I tried in Windows 10 and macOS Mojave - both has same issue. Could anyone help me out? Thanks

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [x] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0
node version:
v12.6.0
npm version:
6.9.0
CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by bcallaghan-fri** [comment]
Did you set a Google Maps API key in your `main.js` Electron file? It would look like this
```js
process.env.GOOGLE_API_KEY = '<your-api-key>';
```

Capacitor uses the web implementation of the Geolocation plugin when running on Electron, which means it's up to the browser to determine your current location. The browser, in this case, is Electron. Unfortunately, Electron requires you to provide your own Google Maps API key (the other three platforms don't require this). For reference, see [this documentation](https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#google_api_key)

**Comment by jcesarmobile** [comment]
What @bcallaghan-fri is right, this is an electron bug/feature, geolocation doesn't seem to work without a google API key.

**Comment by appskitchen** [comment]
@jcesarmobile @bcallaghan-fri I have entered google API key in index.js as you mentioned earlier, but it does has zero impact. I still see the same error. Wondering how to resolve this issue.
Also my plan to run the application in windows 10 offline, on that case how to handle this thing? Any idea?

**Comment by karvannan-thi** [comment]
Fyi
Refer this library to access native window device
https://github.com/NodeRT/NodeRT

**Comment by hemangshah** [comment]
Getting the same error on cordova electron platform -
Here's the issue - https://github.com/apache/cordova-plugin-geolocation/issues/213
