### ISSUE TITLE
Push Notifications Plugin onToken Refresh iOS - Android

### ISSUE THREAD

**Issue by Alexookah** [ionic-team/capacitor#1859]
Hi, 
I am using the capacitor plugin for iOs and Android.
I would like to know if the method on refresh token is handled in android and iOS.

I think in iOS i get only the apns.
So if i am using fcm i should add in appDelegate the onRefresh method from firebase fcm docs.

What about in android?

**Comment by jcesarmobile** [comment]
Please, don't use github issues to ask questions.
The code is open source, so you can take a look. If you don't find what you are looking for you can ask on [slack](https://getcapacitor.herokuapp.com/)  or the [forums](https://forum.ionicframework.com/).
You can see [here](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/CapacitorFirebaseMessagingService.java#L10) that the token change is handled.
