### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined, not custom plugin related.

### ISSUE THREAD

**Issue by LukaszGrela** [ionic-team/capacitor#1860]
Description of the problem:

Affected platform
- [x] Android 5.0.2
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Other information:
Run on emulator, the same app run on Android 6+ works fine.

Capacitor version:
1.1.1

node version:
8.13.0

npm version:
6.4.1

Steps to reproduce:
Create a project for android, 
run it on the Android 5.0 (device or emulator), 
use the `addListener` on `App` plugin
Inspect the WebView and notice the error in console: `Uncaught TypeError: Cannot read property 'call' of undefined`

Try to call following from the dev tools console:
`Capacitor.Plugins.App.addListener('appStateChange', function handler() {console.log("App State Changed");})` You will notice the `TypeError: Cannot read property 'call' of undefined` error. debug and it will point to the 
```
    } catch (e) {
      orgConsole.error.call(win.console, e); // this line
    }
```

further debug will show that `orgConsole` is empty! and was attemptet to populate with a line starting `Object.keys(win.console)`

Attempt to console log the `Object.keys(window.console)` will show taht only `memory` key is lsited (where is `log`, `error`?) It seems that on the WebView available for Android 5.0 the console is not iterable.

The same call on the dev tools on the Android 6+ lists all of available console methods. (e.g. Android 8 - 24 items listed)

Possible solution could be to create a static list of console props

```
const consoleLevels = [    
    'debug',
    'error',
    'info',
    'log',
    'trace',
    'warn',
    // anything else needed
];
// then
consoleLevels.forEach(function(level){
   // rest of the code
});
```

Link to sample project:
N\A

**Comment by jcesarmobile** [comment]
next release of capacitor-android won't have this console overwrite, so won't be a problem

**Comment by LukaszGrela** [comment]
And when the next release is planned?

**Comment by basher** [comment]
Hi @jcesarmobile - any idea when next release of capacitor-android will be?

We need to run our app on a Clover Flex device, which runs Android 5.1.

**Comment by LukaszGrela** [comment]
Hi @jcesarmobile - the [`native-bridge for 1.2.0](https://github.com/ionic-team/capacitor/blob/1.2.0/core/native-bridge.js#L70) is still causing a problem. 

My temporary solution to sort this out is:

```
  const consoleKeys = ["debug", "error", "info", "log", "warn", 
  "dir", "dirxml", "table", "trace", "group", "groupCollapsed", 
  "groupEnd", "clear", "count", "countReset", "assert", "profile", 
  "profileEnd", "time", "timeLog", "timeEnd", "timeStamp", "context", 
  "memory", "reactStack", "reactStackEnd"];
  // Object.keys(win.console)
  consoleKeys.forEach(function (level) {
```

**Comment by LukaszGrela** [comment]
This can be sorted with 
```
  var useFallbackLogging = Object.keys(win.console).length < 2;
  if(useFallbackLogging) {
    win.console.warn('Advance console logging disabled.')
  }
```

as on android 5.1 the `Object.keys(win.console).length` returns `1` (`["memory"]`) not `0`. But then I'm wondering why the `useFallbackLoggin` is set not on actual advanced logging features but on ability to enumerate of the `console`. As this bug proves `useFallbackLogging=true` doesnt meant a call to `win.console.groupCollapsed` will fail.

There is a test if `win.console` contains certain enumerated method and this method is a function, then this could be leveraged as `Object.keys(win.console).length === 0` could mean `win.console.warn('Advance console logging disabled.')` will fail too.

Better solution would be with the `consoleKeys` static list to filll the `orgConsole` and the `useFallbackLogging` method that will test for advanced logging features.

```
  const consoleKeys = [
    'debug',
    'error',
    'info',
    'log',
    'warn',
    'dir',
    'dirxml',
    'table',
    'trace',
    'group',
    'groupCollapsed',
    'groupEnd',
    'clear',
    'count',
    'countReset',
    'assert',
    'profile',
    'profileEnd',
    'time',
    'timeLog',
    'timeEnd',
    'timeStamp',
    'context',
    'memory',
  ];
  // here enumerate which console methods are required for advanced logging
  var advancedConsoleMethods = ['groupCollapsed','dir','groupEnd','error'];

  /**
   * Tests the `orgConsole` object for existance of listed in `advancedConsoleMethods` console functions. 
   * If `advancedConsoleMethods` is empty then full `consoleKeys` is used.
   * @returns {boolean} `true` when needs to use fallback logging
   */
  useFallbackLogging = function() {
    var methods = advancedConsoleMethods;
    if (methods === undefined || methods.length === 0) {
      methods = consoleKeys;
    }
    //
    var valid = true;
    var i = 0;
    while (valid && i < methods.length) {
      var method = methods[i];
      valid = typeof orgConsole[method] === 'function';
      i++;
    }
    return !valid;
  };

  if (useFallbackLogging()) {
    win.console.warn('Advance console logging disabled.');
  }
```
