### ISSUE TITLE
cap create should offer pnpm as npm client option

### ISSUE THREAD

**Issue by fczuardi** [ionic-team/capacitor#1863]
Description of the problem:

The tool for creating a capacitor app from scratch currently offers either npm or yarn as npm client options. It would be nice to have a pnpm option there as well.

More info: https://pnpm.js.org/

Capacitor version: 1.1.1

node version: 10.16.1

Steps to reproduce:

1. cap create ExampleApp
1. answer the first 3 questions
1. stop at the 4th as your favorite npm client is not listed

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Or if you are really interested and have the knowledge to implement this, you can send a PR.

**Comment by dwieeb** [comment]
Capacitor 3 won't install dependencies for you (the `npmClient` option is being removed), so this can be closed. See https://github.com/ionic-team/capacitor/pull/3409 for more info.
