### ISSUE TITLE
WebAssembly Mime-type problem

### ISSUE THREAD

**Issue by XamiKami** [ionic-team/capacitor#1864]
Hey!

Im currently trying to set up an Ionic/React based App with Capacitor, that in part is based on WebAssembly.

Trying to start that App on the Emulator i get a blank screen. After looking into the chrome://inspect thing, I'm able to see the problem:
```
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': 
Incorrect response MIME type. Expected 'application/wasm'.
```
When using it in the browser (ionic serve etc) it does work, so this seems to be a Capacitor-problem.

Any help? 
if you believe [#774](https://github.com/ionic-team/capacitor/issues/774), Wasm is supposed to work...

Thanks in advance for any help ;D

**Comment by jcesarmobile** [comment]
sample app https://github.com/XamiKami/Capacitor-Wasm-problem-simple-case-

**Comment by rokit** [comment]
@jcesarmobile That link is now broken.
