### ISSUE TITLE
Push Notification Page not working

### ISSUE THREAD

**Issue by KSayed91** [ionic-team/capacitor#1866]
Description of the problem:
Push Notification Page not working on Decumentation website: 

[https://capacitor.ionicframework.com/docs/apis/push-notifications/ ](https://capacitor.ionicframework.com/docs/apis/push-notifications/ )

![image](https://user-images.githubusercontent.com/5659755/62851251-29bcfb00-bcee-11e9-87a0-23d042858ac1.png)

**Comment by jcesarmobile** [comment]
I can't reproduce, what's your browser and browser language?

**Comment by KSayed91** [comment]
> I can't reproduce, what's your browser and browser language?

I got this Errors on Console
![image](https://user-images.githubusercontent.com/5659755/63019745-eb1d7100-bea4-11e9-9295-ba1357066a80.png)


and this is chrome version, it's English Version:
![image](https://user-images.githubusercontent.com/5659755/63019790-08ead600-bea5-11e9-8501-4be5b84e0b66.png)

**Comment by KSayed91** [comment]
it's working now.

**Comment by Ekaanth** [comment]
Hi, this Link https://capacitor.ionicframework.com/docs/apis/push-notifications/ is still not working. can you please look into this?

**Comment by dotNetkow** [comment]
Working for me in Google Chrome on Mac, @Ekaanth. Can you give us more details, such as browser etc?

**Comment by Ekaanth** [comment]
Im using Brave browser:
Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit).
Yes, I just check that it's working perfectly in chrome.

**Comment by rebron** [comment]
Hi @Ekaanth  Still an issue for you with Brave 1.13.82 our current release version? I couldn't reproduce on 1.13.82 and our current version in beta 1.14.x

**Comment by Ekaanth** [comment]
> Hi @Ekaanth Still an issue for you with Brave 1.13.82 our current release version? I couldn't reproduce on 1.13.82 and our current version in beta 1.14.x

It is working now.
