### ISSUE TITLE
ios and android Subscription

### ISSUE THREAD

**Issue by sirsquall** [ionic-team/capacitor#1868]
Description of the problem:
Hello,
I wanted to use the Google Play and the AppStore subscription model, but I didn't found any documentation, do know if it's possible to add that with Capacitor?

Affected platform
- [x ] Android
- [ x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x ] macOS
- [ ] linux

**Comment by jcesarmobile** [comment]
It's not possible with the Core plugins, you'll have to create one yourself or search for existing Cordova/Capacitor 3rd party plugins.

**Comment by solojuve1897** [comment]
@sirsquall I'm using RevenueCat.
https://github.com/RevenueCat/cordova-plugin-purchases
