### ISSUE TITLE
Android studio always opens

### ISSUE THREAD

**Issue by pegak** [ionic-team/capacitor#1869]
Description of the problem:
Android studio is always opened when I run `ionic capacitor run android`. Isn't it possible to run it silently as Cordova does?

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
Mac OS X 10.15 Beta
Capacitor version:
1.1.1
node version:
12.0.0
npm version:
6.10.3

Steps to reproduce:
Run `ionic capacitor run android` in Angular Capacitor app.
Android Studio is opened.
I have to click on "Play" button to actually run it.

**Comment by jcesarmobile** [comment]
Capacitor apps are meant to be run from Android Studio.

`ionic capacitor run android` is an Ionic CLI command, not a Capacitor command. If you want that command to be able to run Capacitor apps without Android Studio, you can create a feature request on the Ionic CLI repo https://github.com/ionic-team/ionic-cli/issues
