### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by NunoSav** [ionic-team/capacitor#1870]
Description of the problem:
After updating Capacitor from version `beta-22` to `1.1.1` trying to build app on Android Studio throws the following error(s):

```
Android resource linking failed
\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:4166: error: resource android:attr/fontVariationSettings not found.
\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:4167: error: resource android:attr/ttcIndex not found.
error: failed linking references.
```

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Capacitor version: 1.1.1

node version: 10.14.2

npm version: 6.4.1

**Comment by jcesarmobile** [comment]
Capacitor 1.0 bumped the targetSDK to 28, you'll have to update your app's `compileSdkVersion` and `targetSdkVersion` to 28 too and also update any support library you are using from 27.x.x to 28.0.0.
If you didn't do any change in the Android project, easier way would be to remove android folder and run `npx cap add android`.
If you can't remove android folder, check the android template in case you need some more changes in the gradle files.
https://github.com/ionic-team/capacitor/tree/master/android-template.

From 1.0.0 release we document any required changes, but there are no docs for updating from beta versions.
