### ISSUE TITLE
When add electron, report " add: stdout maxBuffer length exceeded"

### ISSUE THREAD

**Issue by gzf6** [ionic-team/capacitor#1872]
environments

> Ionic:
   Ionic CLI                     : 5.2.3 (C:\Users\youngman\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0
Capacitor:
   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1
Utility:
   cordova-res : not installed
   native-run  : not installed
System:
   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

run `npx cap add electron`

it report like this:

> × Installing NPM Dependencies: stdout maxBuffer length exceeded
× add: stdout maxBuffer length exceeded
[error] { RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceededxceeded
    at Socket.onChildStdout (child_process.js:348:14)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:261:13)
    at Socket.Readable.push (_stream_readable.js:220:10)                            }
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17) cmd: 'npm install' }

**Comment by jcesarmobile** [comment]
can you try with Capacitor 1.4.0? I can't reproduce
Also, do you use regular cmd on windows? or do you use another terminal?

**Comment by gzf6** [comment]
> can you try with Capacitor 1.4.0? I can't reproduce
> Also, do you use regular cmd on windows? or do you use another terminal?

Sorry,it is my mistake. I forgot to close this issue. When I change the electron_mirror to https://cdn.npm.taobao.org/dist/electron/  , it is OK.
