### ISSUE TITLE
appUrlOpen Listener never emitted

### ISSUE THREAD

**Issue by LrMiLoef** [ionic-team/capacitor#1875]
Description of the problem:

Affected platform
[ ] Android
[ x ] iOS
[ ] electron
[ ] web

OS of the development machine
[ ] Windows
[ x ] macOS
[ ] linux

Capacitor version: 1.1.1

node version: 10.16.1

npm version: 6.9.0

CocoaPods version: 1.7.5

Steps to reproduce:

We have this part of code in our VueJS application:

``` 
if (Capacitor.isPluginAvailable('App')) {
    App.addListener('appUrlOpen', (urlOpen) => {
        console.log(`URL: ${urlOpen.url}`);
        vm.handleDeepLink(urlOpen.url);
    });
 }
```

It will be called in the "mounted hook" of the VueJs application. 
So, when i open a link that's assigned to our application, the application opens but it will not run into the section of code that must be called when the 'appUrlOpen' event was emitted. 

```
// This never will be called
console.log(`URL: ${urlOpen.url}`);
vm.handleDeepLink(urlOpen.url);
```

So it looks like the event never will be emitted.

**Comment by jcesarmobile** [comment]
Can you provide a sample app? I can't reproduce on Angular apps and I don't have any experience with vue

**Comment by LrMiLoef** [comment]
I think it's a little bit difficult to provide a sample app, because you have to register associated domains at apples developer account website. But i can show you the main component of our application. Then you can see how it's implemented:


```
<template>
    <div id="app">
        <h1>This is our main application</h1>
    </div>
</template>

<script>
import { Capacitor, Plugins, StatusBarStyle } from '@capacitor/core';

const { App } = Plugins;
const { Toast } = Plugins;
const { Browser } = Plugins;

export default {
  name: 'App',

  async mounted() {
    this.initializeCapacitor();
  },

  methods: {
    async getLaunchUrl() {
        const urlOpen = await Plugins.App.getLaunchUrl();
        console.log(`URL: ${urlOpen.url}`);
        if (!urlOpen || !urlOpen.url) {
            return;
        }
        this.handleDeepLink(urlOpen.url);
    },

    handleDeepLink(url) {
        console.log(url);
    },

    async initializeCapacitor() {
        const vm = this;

        // Statusleiste des Handys in den DarkMode versetzen
        if (Capacitor.isPluginAvailable('StatusBar')) {
            const { StatusBar } = Plugins;
            StatusBar.setStyle({ style: StatusBarStyle.Dark }).then();
        }

        if (Capacitor.isPluginAvailable('App')) {
            // Listener für DeepLinks in die App registrieren
            App.addListener('appUrlOpen', (urlOpen) => {
            console.log(`URL: ${urlOpen.url}`);
            vm.handleDeepLink(urlOpen.url);
            });
        }

        this.getLaunchUrl();
      }
    },
  },
};
</script>

<style lang="scss" scoped>
    
</style>

```
That's the one and only place where we try to do something with the App Plugin. And this VueJS-Component is always visible, because it handles all the rest of our application.

**Comment by LrMiLoef** [comment]
So we figured out, that the android version works fine with the code above. It's only an problem with iOS. Universal Link Registration itself works fine. When i klick an associated link, our app opens, but without emitting appUrlOpen-Event.

**Comment by LrMiLoef** [comment]
I think we have solved our problem. We did not recognize that we have to update ios-template manually: [https://capacitor.ionicframework.com/docs/ios/updating/](url)

**Comment by LiLeiAndroid** [comment]
Hi LrMiLoef ,how did you solve this issue? I also have this issue,  I can use "App.addListener('appUrlOpen', (urlOpen: any) => " to listen the url info on Android ,but it doesn't work on ios, I have spend one week to find a solution,  but I still can't fix this 
 issue, thanks a lot!

**Comment by LrMiLoef** [comment]
Hey,
as i wrote in my last post, we had to update the ios template as it's descriped here: [https://capacitor.ionicframework.com/docs/ios/updating/](https://capacitor.ionicframework.com/docs/ios/updating/) 
Maybe it can solve your problem too.

**Comment by LiLeiAndroid** [comment]
Thanks, I saw the link, and update the version to the newest, but I still can not listen the openUrl, because I need use some params in the url, I think it is a bug for capacitor. My version is below
`"@capacitor/android": "~2.4.3",
    "@capacitor/core": "^2.4.3",
    "@capacitor/ios": "^2.4.3",`
thank you so much anyway!

**Comment by brassier** [comment]
I'm also struggling with this issue.  We are running version `@2.4.7`.  My custom URL opens the app, there is a `TO JS` log with the link details, then a `APP ACTIVE` log, but the actual `appUrlOpen` event never fires on iOS.  Any thoughts?

**Comment by Flos** [comment]
@brassier 
I'm facing the same issue right now. 
The browser for the OIDC + PKCE Flow stays open, and `appUrlOpen` is not triggered
```
⚡️  To Native ->  Browser addListener 52440395
⚡️  To Native ->  Browser open 52440396
⚡️  TO JS {"value":true}
⚡️  TO JS {"value":true}
2021-04-21 23:44:15.608637+0200 App[47380:7061072] [AXRuntimeCommon] Unknown client: App
2021-04-21 23:44:16.005211+0200 App[47380:7060661] Unbalanced calls to begin/end appearance transitions for <Capacitor.TmpViewController: 0x7ff31f11a9a0>.
⚡️  TO JS {}
``` 

I'cant get it working right now on iOS, here is a duplicate of the same issue, just for references: https://github.com/ionic-team/capacitor/issues/2929

**Comment by Flos** [comment]
I see that the customeUrl schema callback is triggering the CAPBridge.handleOpenUrl

```
 func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    // Called when the app was launched with a url. Feel free to add additional processing here,
    // but if you want the App API to support tracking app url opens, make sure to keep this call
    print("url = \(url.absoluteString )")
    return CAPBridge.handleOpenUrl(url, options)
  }
```

But nothing happens after the CAPBridge.handleOpenUrl call
```
/**
   * Handle an openUrl action and dispatch a notification.
   */
  public static func handleOpenUrl(_ url: URL, _ options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.URLOpen.name()), object: [
      "url": url,
      "options": options
    ])
    NotificationCenter.default.post(name: NSNotification.Name.CDVPluginHandleOpenURL, object: url)
    CAPBridge.lastUrl = url
    return true
  }
```

**Comment by brassier** [comment]
Hello -

I did eventually get this working for iOS and Android.  One of the big issues I had was due to how I was using the Browser plugin.  See this link for tips on that: https://stackoverflow.com/questions/66591207/capacitor-in-app-navigation-custom-url-redirect

I also had to manually call `Browser.close();` to close the browser after the auth callback finished.  Hopefully those tips help.

**Comment by Flos** [comment]
@brassier thanks for the feedback. I'm using [ionic-appauth](https://github.com/wi3land/ionic-appauth) and the browser handling is implemented there. There is also one quite similar issues again  https://github.com/wi3land/ionic-appauth/issues/57

I could resolve my issue by upgrading to the release candidate of Capacitor 3.0
https://capacitorjs.com/docs/v3/updating/3-0
