### ISSUE TITLE
Transparent status bar

### ISSUE THREAD

**Issue by UlisesCeca** [ionic-team/capacitor#1876]
Hello,

is it possible to make the status bar transparent or translucent like the image below with the current plugin?

![image](https://user-images.githubusercontent.com/23300072/63000691-0fac2580-be72-11e9-8904-1f49dceb0962.png)

Thanks!

**Comment by jcesarmobile** [comment]
It's possible to make the bar translucent as it accepts AARRGGBB as color, but it's not possible to show the webview behind the statusbar.

**Comment by UlisesCeca** [comment]
Okay, thank you!

Will this ever be considered to be implemented in the future?

**Comment by jcesarmobile** [comment]
Tagging with feature request tag:
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

In case it's done, it would be android only method, should be like the cordova-plugin-statusbar `overlaysWebView` method.

**Comment by Crylion** [comment]
I'm also really missing this :/
We're currently migrating a cordova app to capacitor and supporting phones with Notches correctly as an important part of the design, so we really relied on the cordova statusbar plugin being able to overlay the webview :(
Are there workarounds by changing the android code directly? The last time I developed for Android was about five years ago, so I'm a bit rusty x)

**Comment by jcesarmobile** [comment]
this has been implemented on https://github.com/ionic-team/capacitor/pull/2597, removing the feature request label

**Comment by sisoje** [comment]
@jcesarmobile what about ios support?

**Comment by jcesarmobile** [comment]
iOS always overlays the status bar, you can avoid the status bar area by respecting safe areas
https://webkit.org/blog/7929/designing-websites-for-iphone-x/
