### ISSUE TITLE
Certain CLI commands don't account for spaces in the current path

### ISSUE THREAD

**Issue by chrislambe** [ionic-team/capacitor#188]
I was getting some ambiguous errors when running `npx cap sync` and traced the error back to the iOS update command failing to `cd` to a directory with spaces.

The offending lines are here:
https://github.com/ionic-team/capacitor/blob/master/cli/src/ios/update.ts#L104
https://github.com/ionic-team/capacitor/blob/master/cli/src/ios/update.ts#L106

I was able to resolve the issue by wrapping the app directory with quotes:
```
await runCommand(`cd "${config.app.rootDir}"<snip>
```

Happy to submit a PR if you want!

**Comment by mlynch** [comment]
Thanks for debugging this, just pushed a fix and will be resolved in the next release tomorrow!
