### ISSUE TITLE
Filesystem.getUri returns wrong uri for FilesystemDirectory.Application 

### ISSUE THREAD

**Issue by bergisch-media** [ionic-team/capacitor#1881]
Description of the problem:

**Affected platform**
- [ ] Android
- [x] iOS
- [x] electron
- [ ] web

**OS of the development machine**
- [ ] Windows
- [x] macOS
- [ ] linux

**Other information:**
Tested with iPhone Xr simulator

**Capacitor version:**
1.1.1

**node version:**
12.8.0

**npm version:**
6.10.2

**CocoaPods version:**
1.6.1

**Steps to reproduce:**
- put a file into your app e.g. "static/demo.pdf" so that it is copied into the public directory of the iOS app when building
- the file resides in "ios/App/public/static/demo.pdf" after building
- call Filesystem.getUri({path: "static/demo.pdf", directory: FilesystemDirectory.Application})
- uri of result object is "file:///Users/.../data/Containers/Data/Application/B6289A2B-85BA-4E63-B6BD-6C3959F9DD74/Applications/static/demo.pdf" which does not exist
- should result in "file:///Users/.../data/Containers/Bundle/Application/367EFDB6-BE6A-421A-89E1-A91CC8116B15/App.app/public/static/demo.pdf" which is given when using cordova.file.applicationDirectory + 'public/' + 'static/demo.pdf' and window.resolveLocalFileSystemURL with that path

Electron doesn't know the APPLICATION directory: "APPLICATION directory is currently not supported in the Electron implementation". Should we use DRIVE_ROOT instead?

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/2312
