### ISSUE TITLE
Location tracking in background and foreground

### ISSUE THREAD

**Issue by abhibly** [ionic-team/capacitor#1885]
Hello,

I am building an android app for a company, where the users will work in remote locations. So the owner of the company needs to track the location of the users. The Company employees will login into the app and we need to begin the tracking. I want the location of the user every 30 minutes(even if the user has/hasn't moved from the previous location).
I just want to know from the capacitor team, Can i achieve this functionality using capacitor geolocation and setinterval in my ionic 4 project?
Any help or suggestions would be appreciated.

Thanks,
Abhilash

**Comment by jcesarmobile** [comment]
Same as https://github.com/ionic-team/capacitor/issues/1886, you don't need to create multiple issues if you didn't get an answer.
