### ISSUE TITLE
App pauses after few minutes in background

### ISSUE THREAD

**Issue by abhibly** [ionic-team/capacitor#1886]
Description of the problem:
In my android app, I want to capture the location of my employees every few minutes. I have used a set interval to get the location of users. When the app is in the foreground, locations are captured and sent to the server always.
When the app is in background or screen is locked, the set interval in fired and the locations are captured and is sent to the server. But it stops sending after sending a few times.

Affected platform
- [*] Android

OS of the development machine
- [*] Windows

Link to sample project:
Here is my repo: https://github.com/abhibly/BGLocationTracker
Clone and run the app.

Can somebody please tell me, how to get the locations in the background.

Thanks,
Abhilash

**Comment by jcesarmobile** [comment]
Capacitor geolocation plugin doesn't support background geolocation.
You can try with this one https://ionicframework.com/docs/native/background-geolocation
