### ISSUE TITLE
Android 'tabs' starter: Capacitor: Unable to read file at path public/plugins

### ISSUE THREAD

**Issue by appde** [ionic-team/capacitor#1889]
Description of the problem:
The starter works fine under the Chrome browser, but crashes or shows a white screen on some Android devices.

logcat:
Capacitor: Unable to read file at path public/plugins
Capacitor/Plugin/Browser: Error binding to custom tabs service

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Other information:
Tested on Android Emulator and real devices - API 21, 22, 25

Capacitor version:
"@capacitor/android" = 1.1.1
"@capacitor/core" = 1.1.1
"@capacitor/cli" = 1.1.1

node version:
v12.3.1

npm version:
6.4.1

CocoaPods version:
-

Steps to reproduce:

> ionic start itest tabs
> ionic build
> ionic capacitor sync android

Link to sample project:

https://github.com/appde/itest

**Comment by jcesarmobile** [comment]
None of those should crash the app.
In which devices is it failing?

**Comment by appde** [comment]
Just tested Genymotion 7.1 (API 25) and 5.0 (API 21) - 5.0 shows the white screen forever, 7.1 crashes.
And both of them seemed to have the same logcat messages.

**Comment by jcesarmobile** [comment]
The white screen on genymotion is probably related to not having the system webview up to date.

**Comment by MatHuf** [comment]
Experiencing the same issue using the tabs starter with Android API 24 and earlier. API 25 and up works as expected.

**Comment by JCGeorge1** [comment]
i have same issue,How can it be solved

**Comment by 2manoj1** [comment]
same issue  E/Capacitor: Unable to read file at path public/plugins

**Comment by WolfieXIII** [comment]
Same issue as well, multiple devices, but works on emu.

**Comment by WolfieXIII** [comment]
I had this issue `E/Capacitor: Unable to read file at path public/plugins` above, webDir in capacitor.config.json was set to src instead of www.   

After fixing that, rebuilding the android studio project I could deploy again without error.

**Comment by kilroy05** [comment]
What are you using @WolfieXIII 
My build has no www folder, it's build (default project)

**Comment by arnaud-zad** [comment]
@jcesarmobile It's not only about crashing or not. If you don't have cordova plugins, is it correct to have an error in logs ?

**Comment by kavitha306** [comment]
- This problem occurs if we are using blank application as well
- This is due to no plugin in the application
- Added one plugin the problem fixed
```
npm install com-darryncampbell-cordova-plugin-intent
npm install @ionic-native/web-intent
ionic cap sync
```

**Comment by alexandermorgan** [comment]
> capacitor.config.json

@WolfieXIII Where is this capacitor.config.json supposed to be? I don't seem to have one in my project. It was working previously, but now my capacitor workflow is broken, so maybe I deleted this json file somehow.

**Comment by zuozuomu-z** [comment]
What I saw in the log of Android studio is

E/Capacitor/BrowserPlugin: Error binding to custom tabs service

Such tips

**Comment by ogorei** [comment]
Hey guys any concrete idea on how to solve this.... im not having a black screen on emulator but the app is crashing after submitting to google play for testing
error is the same:  2022-08-25 20:32:07.386 E/Capacitor/BrowserPlugin: Error binding to custom tabs service
