### ISSUE TITLE
cap open followed by select from menu fails silently-ish when the target platform hasn't been added

### ISSUE THREAD

**Issue by chrislambe** [ionic-team/capacitor#189]
## Reproduction steps
In a project where Android hasn't been added a platform:
* Run `npx cap open`
* Select `android` from the menu

## Expected result
An error is produced as when `npx cap open android` is run:
```
[error] android" platform has not been created. Use "capacitor add android" to add the platform project.
```

## Actual result
This is printed:
```
Don't forget to run "npx cap copy" before running your app
[info] Opening Android project at /path/to/android
```

**Comment by mlynch** [comment]
Fixed, thanks!
