### ISSUE TITLE
Geolocation on iOS is slow because it is always using high accuracy

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/capacitor#1893]
The geolocation plugin on iOS is taking a long time to get the users location because it is always using `kCLLocationAccuracyBest` or `kCLLocationAccuracyBestForNavigation`. Pull request #1773 added the option for `enableHighAccuracy`, but according to [Apple's developer documentation](https://developer.apple.com/documentation/corelocation/kcllocationaccuracybestfornavigation) on `kCLLocationAccuracyBestForNavigation`: "Because of the extra power requirements, use this level of accuracy only while the device is plugged in.". This level of accuracy seems like it is too high to be used for `enableHighAccuracy`.

The [cordova plugin equivalent](https://github.com/apache/cordova-plugin-geolocation/blob/6570cf9fd2c546620f6aa8b2a07cf0b8b073a95c/src/ios/CDVLocation.m#L140) uses `kCLLocationAccuracyThreeKilometers` by default and `kCLLocationAccuracyBest` for high accuracy.

Ideally the user could choose the desired accuracy from all of the iOS options listed in the documentation, but these might not line up with android very well. Regardless the current implementation takes a long time to get the current location, especially when high accuracy is not required by the app.

Note that the long wait time to fetch the current location is not as noticeable on the simulator and a physical device should be used to see the true wait time.

**Comment by jcesarmobile** [comment]
It uses `kCLLocationAccuracyBestForNavigation` for  `enableHighAccuracy` because some users complained about `kCLLocationAccuracyBest` results being bad.

We can change `kCLLocationAccuracyBest` for when `enableHighAccuracy` is false/not set for another value that has less accuracy and is faster.

Android also has[ multiple possible values](https://developer.android.com/reference/android/location/Criteria), so maybe we can add a new property that can match some of the iOS values with similar Android values.

**Comment by WIStudent** [comment]
I am having the same issue. In my case it didn't matter if `enableHighAccuracy` was set to true or false, getting the current position on iOS took each time around 10 seconds. On android on the other hand the position is returned almost immediately.

**Comment by WIStudent** [comment]
I just found a workaround that returns the location in less than 50ms on my iOS device, even with `enableHighAccuracy` set to true:
```typescript
const internalGetCurrentPosition = async (options: GeolocationOptions = {}): Promise<GeolocationPosition> => {
  return new Promise<GeolocationPosition>((resolve, reject) => {
    const id = Geolocation.watchPosition(options, (position, err) => {
      Geolocation.clearWatch({id});
      if(err) {
        reject(err);
        return;
      }
      resolve(position);
    });
  });
};
```

What tipped me of was [this article](https://fluffy.es/current-location/#retrieving) that says that using `startUpdatingLocation()` and `stopUpdatingLocation()` can be much faster than using `requestLocation()`

**Comment by derWebdesigner** [comment]
I have the same issue. I just fully reworked my Ionic 3 app with Cordova to Ionic 4 with Capacitor, so the code base in general is the same, API is identical, but fetching the geo position is much much slower and a lot of my users are reporting this issue. I guess I will have to try your approach @WIStudent .

**Comment by tebantebanteban** [comment]
Same here, Geolocation with Capacitor takes around 10 seg to get coordinates

**Comment by tebantebanteban** [comment]
> ```ts
> const internalGetCurrentPosition = async (options: GeolocationOptions = {}): Promise<GeolocationPosition> => {
>   return new Promise<GeolocationPosition>((resolve, reject) => {
>     const id = Geolocation.watchPosition(options, (position, err) => {
>       Geolocation.clearWatch({id});
>       if(err) {
>         reject(err);
>         return;
>       }
>       resolve(position);
>     });
>   });
> };
> ```

works perfect! thank!

**Comment by tebantebanteban** [comment]
Solution Works on iOS, but in android got blank screen. 

i need to use

```
if(!this.platform.is('android')){
                const internalGetCurrentPosition = async (options: GeolocationOptions = {}): Promise<GeolocationPosition> => {
                          return new Promise<GeolocationPosition>((resolve, reject) => {
                            const id = Geolocation.watchPosition(options, (position, err) => {
                              Geolocation.clearWatch({id});
                              if(err) {
                                reject(err);
                                return;
                              }
                              resolve(position);
                            });
                          });
                        };

                internalGetCurrentPosition(options).then((resp) => {

}).catch((error) => {    

});
        }else{
             Geolocation.getCurrentPosition().then((resp) => {

}).catch((error) => {    

});
}
```

**Comment by derWebdesigner** [comment]
@tebantebanteban Yeah you are right, just tried it and the solution is only working on iOS, Android isn't loading with this solution though, so the switch based on the platform seems to be needed right now if you want to have a quick solution on both platforms.

**Comment by derWebdesigner** [comment]
@jcesarmobile Should I open a separate issue for watchPosition() not working at all on Android? Because currently there is no solution at all to get the current position on Android (because getCurrentPosition() is only returning the last known position, which is intentional by design when I understood you correctly).

**Comment by jcesarmobile** [comment]
We are changing the whole android geolocation code on android for next major release, so hopefully will fix that

**Comment by derWebdesigner** [comment]
@jcesarmobile Awesome, can't wait for testing the new release. Is there any timing for it yet? Thank you by the way for doing such a great job, really appreciate that!

**Comment by leonelngande** [comment]
> We are changing the whole android geolocation code on android for next major release, so hopefully will fix that

Hi @jcesarmobile, thanks for this information. If you don't mind, when can we be expecting the next major release please..? Considering waiting for it given my app depends heavily on geolocation.

Also if anyone found a temporal workaround for this, i'd love to hear it. Thanks.

**Comment by aspoonemore** [comment]
@leonelngande  We switched back to the cordova plugin for now

**Comment by derWebdesigner** [comment]
@aspoonemore That's great to hear. Was thinking about switching back as well and wasn't sure if this would solve my issue. Thank you very much for this hint, that helps a lot! :-)

**Comment by jcesarmobile** [comment]
Just FYI, cordova's plugin doesn't have any native code for Android, it's just the webview geolocation, so you can use the webview geolocation in capacitor too.

**Comment by leonelngande** [comment]
Thanks @aspoonemore. @jcesarmobile thanks for the tip, wasn't sure webview geolocation will work on a native device, just got confirmation.

**Comment by derWebdesigner** [comment]
@jcesarmobile That's very good to know. Is webview geolocation within Ionic and Typescript just used like in the browser or is there any hint somewhere how to use it for now until the new version of Capacitor is released? I am asking because imho geo location is the most important feature for apps in general and it would be very helpful to at least know how to use it for now with Capacitor, making it much easier for all users to wait for the next release. Thank you so much as always!

**Comment by jcesarmobile** [comment]
You need to request the permission first (you can use permissions plugin or just call `Geolocation.requestPermissions();`), then you can use it as in any browser.

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

But please, stop the off-topic, this issue is about iOS

**Comment by ustadji** [comment]
> We are changing the whole android geolocation code on android for next major release, so hopefully will fix that

Thanks @jcesarmobile when you say major release is that Capacitor 1.5 or Capacitor 2.x?
Also, are there any fixes for iOs in particular given that the ~10 second latency is only manifested on that platform?
In the meantime, I'm guessing using the Geolocation.watchposition() workaround above is the only solution for now?

**Comment by jcesarmobile** [comment]
We use semver for versions

that's 
major.minor.patch

So next major version means 2.0.0

We released the first beta last week, you can install it with `npm install @capacitor/ios@next` (you should also update core, cli and android if using it)

**Comment by ustadji** [comment]
> We use semver for versions
> 
> that's
> major.minor.patch
> 
> So next major version means 2.0.0
> 
> We released the first beta last week, you can install it with `npm install @capacitor/ios@next` (you should also update core, cli and android if using it)

Thank you @jcesarmobile for the quick response!  Could you briefly explain how you overcame the Geolocation.getCurrentLocation() latency?

**Comment by DURK** [comment]
Any update on this? We're also experiencing a 10 seconds delay in `Geolocation.getCurrentLocation()`, using the latest Capacitor 2.0.1 release and the `enableHighAccuracy` option enabled.

Any idea why @WIStudent's workaround would work with the same high accuracy result?

**Comment by ustadji** [comment]
After the update to Capacitor, iOS geolocation is alot faster thank you!  It comes at a small cost of absolute accuracy but for us that's a small price to pay!
