### ISSUE TITLE
[feature request]openDir for Capacitor Filesystem

### ISSUE THREAD

**Issue by hugetiny** [ionic-team/capacitor#1894]
As i know electron got this function called showItemInFolder.
Can Capacitor add this function?

**Comment by jcesarmobile** [comment]
Can you be a bit more specific?

**Comment by hugetiny** [comment]
@jcesarmobile I mean to add openDir function for Capacitor Filesystem

**Comment by jcesarmobile** [comment]
I don't think this is possible on iOS nor Android, so closing.
