### ISSUE TITLE
Capacitor App Api - LaunchURL always empty and callback not triggered

### ISSUE THREAD

**Issue by SimonScholl** [ionic-team/capacitor#1904]
Description of the problem:
I am trying to integrate https://capacitor.ionicframework.com/docs/apis/app/ to read out deeplinks starting my application. The deeplink works the app opens in a proper way. 

```
ret = await App.getLaunchUrl();
if(ret && ret.url) {
  console.log('App opened with URL: ' + ret.url);
}
console.log('Launch url: ', ret);
```

ret is always == {"url":""} also the callback for already started apps is not triggered when the deeplink brings the app into the foreground. I tried it on web, i expected something like the window.location.href as a value for ret but its even empty.

I added both calls in the constructor of my app.component.ts and tried it also in the ngOnInit lifecycle - hook.

```
Plugins.App.getLaunchUrl().then((ret) => {
console.log('Launch url: ' + JSON.stringify(ret));
});

Plugins.App.addListener('appUrlOpen', (data: any) => {
console.log('Launch opened with URL: ' +  data.url);
});
```

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [x] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Ionic Info:

>    Ionic CLI                     : 5.2.5 
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1
> Capacitor:
   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0
> Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 18 other plugins)
> Utility:
   cordova-res : 0.6.0
   native-run  : 0.2.7 (update available: 0.2.8)
> System:
   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

**Comment by SimonScholl** [comment]
Reformat

**Comment by SimonScholl** [comment]
I want to give an update, the whole plugin seems to be not functional, none of the functions mentioned here https://capacitor.ionicframework.com/docs/apis/app/ is working. For instance 

```
var ret = await App.canOpenUrl({ url: 'https://www.google.com/' });
console.log('Can open url: ', ret.value);

ret = await App.openUrl({ url: 'https://www.google.com/' });
console.log('Open url response: ', ret);
```

The first method returns true, and the second gives 'completed' as a feedback but nothing happens.
Even when i consider

> Open an app with the given URL

My working deeplink is not called by the plugin. No errormessage, no nothing. Would be grateful for any help and i can provide more details on demand.

**Comment by jcesarmobile** [comment]
Looks like you are using the web version of the plugin. Can you provide a sample app?

**Comment by SimonScholl** [comment]
> 
> 
> Looks like you are using the web version of the plugin. Can you provide a sample app?

Thank you for the reply, yes i am using the web version. The problem is that i want to open the native app version with a deeplink from the web version of the app after checking several conditions.

```
import { Plugins } from '@capacitor/core';

constructor(
    private platform: Platform
  ) {}

ngOnInit() {
    if (Capacitor.isPluginAvailable('App')) {
      Plugins.App.getLaunchUrl().then((ret) => {
        console.log('LaunchURL: ' + JSON.stringify(ret));
      });

      Plugins.App.addListener('appUrlOpen', data => {
        console.log('LaunchURL: ' +  data.url);
      });

      Plugins.App.canOpenUrl({ url: 'https://google.com' }).then((ret) => {
        console.log('Can open url: ' + ret.value);
      });

      Plugins.App.openUrl({ url: 'https://google.com' }).then((ret) => {
        console.log('Open url response: ' + JSON.stringify(ret));
      });

    } else {
      console.log('LaunchURL - Cap not available');
    }
}
```

I can only provide this snippets from my codebase, i cannot share this project in public. I thought Capacitor Plugins are completely cross platform? At least it is written on the plugin page 'pwa
ios android electron'.

**Comment by SimonScholl** [comment]
Okay another update, i found the major issue was caused by myself. I did read the documentation but it was not obvious for me that i have to build the app with Android Studio and sync it with
` npx cap sync`. 

Because i am using ionic, with cordova and capacitor it was common for me to run my application via the command
`ionic cordova run android/ios` 

i also run the pwa with 
`ionic serve`
`ionic serve --devapp`

So now all the commands are working in the native android app version, i can get the launchURL and also open a link e.g.: 'market://*'. But the PWA is still not working, i also did deploy it to a server with https and everything because i know ionic devapp is a limiting factor. But the PWA does not open the marketlink i provided and does not give me the launch url. Do i have to do something special to make capacitor plugins work on Web?

**Comment by jcesarmobile** [comment]
Not all native features are available on web platform for obvious reasons, so web plugins do their best they can to provide the functionality they can, but not everything will work because it's just not possible.

You can check the App Plugin code for web here https://github.com/ionic-team/capacitor/blob/master/core/src/web/app.ts.

If you think some of the App plugin functionalities could be implemented for web, report a new issue and provide some information about how that would be possible.
