### ISSUE TITLE
Serve resources as https

### ISSUE THREAD

**Issue by apiaget** [ionic-team/capacitor#1908]
Description of the problem:
I am using a JS library (Stripe.js) that has to be included on https webpage.
Capacitor seems to serve the resources to the WebView as http.
Is there a way to serve the app as https and not http ?

Some people use a workaround : They load an https iframe in their app. Then in this iframe, they include the Stripe.js library...

I am not 100% sure that I asked the question in the right place. If so, don't hesitate to tell me where to discuss :-).

Thank you !

apiaget

**Comment by jcesarmobile** [comment]
in next release the scheme will be configurable.
