### ISSUE TITLE
Device.getInfo can take up to 1 min on web platform on Chrome 76 on Android

### ISSUE THREAD

**Issue by piitaya** [ionic-team/capacitor#1913]
Description of the problem:
I opened this issue on chromium : https://bugs.chromium.org/p/chromium/issues/detail?id=999063
In Chrome 76 on Android, the `navigator.getBattery` promise can take up to 1 min if the phone is not charging (if you plug your phone, the promise resolve immediately).
Code example : https://codesandbox.io/embed/android-chrome-76-battery-issue-mhvdn

The `getInfo` method on the Device web plugin wait for the battery. 
I see some solutions:
1. Split the `getInfo` in 2 methods : `getInfo` and `getBattery`.
2. Add a `withBattery` parameter to the getInfo to have to battery info.
3. Add a timeout on the getInfo method

I prefer the first solution but it's a breaking change. What's your opinion about this ?

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [x] web

OS of the development machine
- [x] Windows
- [x] macOS
- [x] linux

Other information:
The bug is only on Chrome 76 on Android when phone is not charging 😳

Capacitor version: all
node version: all
npm version: all

**Comment by jurepurgar** [comment]
If you don't actually need the battery status the temporary solution could be to just override the function, before it is called, like this:
`
if (navigator.getBattery) {
      navigator.getBattery = function () {
        return Promise.reject();
      };
    }
`

**Comment by piitaya** [comment]
Yes, I made a workaround on my code but I think it could be a good idea to split the battery info and the device info.

**Comment by MeijerM1** [comment]
I'm running into this issue because when I bootstrap my Angular app I call Device.getInfo().
Would you know how to make a workaround so it will still work because I don't need the battery indication?

**Comment by jcesarmobile** [comment]
Looks like it's fixed in Chrome 79.

I've created a new issue proposing to move the battery info from getInfo to a new getBatteryInfo function

https://github.com/ionic-team/capacitor/issues/2311
