### ISSUE TITLE
Blank screen with IonReactRouter and Electron

### ISSUE THREAD

**Issue by spidercatnat** [ionic-team/capacitor#1918]
Description of the problem:

IonReactRouter does not work in Electron production builds. With Capacitor, it does not work whatsoever. The elements are present in the markup, but they are rendered invisible. Is it possible to allow IonReactRouter to have an additional API layer over the HashRouter instead of just BrowserRouter, which does not work with Electron? 

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

Capacitor version: `1.1.1`

node version: `10.16.3`

npm version: `6.9.0`

CocoaPods version: `N/A`

Steps to reproduce:
1. Generated boilerplate code with
 `ionic start ionic-electron sidemenu --capacitor --type=react`

2. Set homepage in `package.json`:
``` 
{
...
  "homepage": ".",
...
}
```
3. Created a build with `ionic build`

4. Initialized Electron project with `npx cap add electron`

5. Copied project contents to electron project with `npx cap copy`

6. Ran app with `npx cap open electron`

**This issue happens with the component regardless of whether or not the project was bootstrapped with Capacitor.**

**Comment by timoplus** [comment]
I'm having the same issue, but on Windows and Mac.
runtime-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
polyfills-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
styles-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vendor-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/tim/electron/…ity-warnings.js:272 Electron Deprecation Warning (contextIsolation default change) This window has context isolation disabled by default. In Electron 5.0.0, context isolation will be enabled by default. To prepare for this change, set {contextIsolation: false} in the webPreferences for this window, or ensure that this window does not rely on context isolation being disabled, and set {contextIsolation: true}.
For more information, see https://electronjs.org/docs/tutorial/security#3-enable-context-isolation-for-remote-content
/Users/tim/electron/…ity-warnings.js:170 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
In the index.html I replaced
  <base href="/" />
with
<base href="./">, but it doesn't help.

**Comment by gkTim** [comment]
I'm having the same problem with an angular based project

**Comment by lewixlabs** [comment]
I think my issue is related to this post.
https://forum.ionicframework.com/t/tutorial-guide-to-build-for-ionic-react-electron-app/176872

Anybody can help us?
Thanks

Lewix

**Comment by VincentvanMedenbach** [comment]
Having the exact same issue on my project

**Comment by timoplus** [comment]
To give a bit more detail, the ERR_FILE_NOT_FOUND problem is detailed in [this GitHub project](https://github.com/timofeysie/gosh).
It was while following the [official Capacitor docs](https://capacitor.ionicframework.com/docs/electron/).

**Comment by InfTkm** [comment]
I am have the same issue as well.

**Comment by nasrat-v** [comment]
Same issue for me with Angular based project

**Comment by jcesarmobile** [comment]
After adding the homepage, you also have to remove the `<base href="/" />` in `index.html` or change it to `<base href="%PUBLIC_URL%/">`

https://github.com/ionic-team/capacitor/issues/2103

**Comment by andonivianez** [comment]
I can´t understand how can you close this issue... it is not fixed yet. I´ve done the same steps as reporter said, and it doesn´t work... it´s anoying... :(

**Comment by jcesarmobile** [comment]
If you read my comment in the issue I linked, I explained how to make it work for react.
Also says it’s the same issue as https://github.com/ionic-team/capacitor/issues/639, which is open. 
So, why I closed it? Because it’s a duplicate of a duplicate

**Comment by andonivianez** [comment]
Mm...I think that it´s similar but not the same, as for example I get no errors in the console, but I´ve the same blank screen. The other one it´s related to errors of assets linking ;)
Anyway, thanks for your fast reply :) I didn´t see that related issue.

**Comment by RonAmihai** [comment]
> Mm...I think that it´s similar but not the same, as for example I get no errors in the console, but I´ve the same blank screen. The other one it´s related to errors of assets linking ;)
> Anyway, thanks for your fast reply :) I didn´t see that related issue.

I'm also getting blank screen.... 
Using the blank starter template
. 
I've tried any combination of `"homepage": "."` in package.json, `<base href="%PUBLIC_URL%/">` in public/index.html, or no href in public/index.html. Nothing solves this issue

**Comment by evalsxonted** [comment]
i think this issue should not be closed it is way different than other issues i have the same for me. see my comment there may be useful information  https://github.com/ionic-team/capacitor/issues/2103#issuecomment-640681297

**Comment by evalsxonted** [comment]
https://github.com/ionic-team/ionic/issues/19246#issuecomment-552858490 
this workaround really works. check it out

**Comment by ollydixon** [comment]
I see the same issue, the only fix is to add a div. But that breaks the animations for iOS...

Broken for desktop, but annimations work for iOS.
```
 <IonReactRouter history={history} >
      <IonRouterOutlet>
        {/* Main tab paths */}
        <Route path={["/" + getLanguage().homeLink]} component={MainTabs} exact={true} />
        <Route path={["/" + getLanguage().exploreLink]} component={MainTabs} exact={true} />
        {/* Standalone paths */}
        <Route path={["/" + getLanguage().createRecipeLink]} component={CreateRecipePage} exact={true} />

        <Route path="/" render={() => <Redirect to="/home" />} exact={true} />
      </IonRouterOutlet>
    </IonReactRouter>
```

Works for desktop but no annimations.

 <IonReactRouter history={history} >
      <IonRouterOutlet>
           <div>
        {/* Main tab paths */}
        <Route path={["/" + getLanguage().homeLink]} component={MainTabs} exact={true} />
        <Route path={["/" + getLanguage().exploreLink]} component={MainTabs} exact={true} />
        {/* Standalone paths */}
        <Route path={["/" + getLanguage().createRecipeLink]} component={CreateRecipePage} exact={true} />

        <Route path="/" render={() => <Redirect to="/home" />} exact={true} />
          </div>
      </IonRouterOutlet>
    </IonReactRouter>
