### ISSUE TITLE
Uncaught (in promise) Keyboard does not have web implementation.

### ISSUE THREAD

**Issue by alexcroox** [ionic-team/capacitor#1919]
I am wrapping my plugin calls in try/catches to avoid promise rejections being uncaught, but this doesn't seem to be working:

```
try {
  const { Keyboard } = Plugins
  Keyboard.setAccessoryBarVisible({ isVisible: true })
} catch (error) {
  // Keyboard isn't available on web so we need to swallow the error
}
```
Uncaught (in promise) Keyboard does not have web implementation.

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [x] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

Capacitor version: 1.1.1

node version: v10.15.3

npm version: 6.4.1

**Comment by juliancruzsanchez** [comment]
This is how I fixed this issue
```js
let Keyboard;
  if (Capacitor.platform !== "web") {
    Keyboard = Plugins.Keyboard
}
```

**Comment by alexcroox** [comment]
Thank you so much! I wasn't aware of `Capacitor.platform` and it's use has solved a lot of other conditional headaches for me!

**Comment by jcesarmobile** [comment]
You can also use Capacitor.isPluginAvailable
