### ISSUE TITLE
How to call JavaScript callback multiple times in native code

### ISSUE THREAD

**Issue by toyobayashi** [ionic-team/capacitor#1920]
Description of the problem:

If I don't want to use plugin events, is there any way to do like this

``` js
import { Plugins } from '@capacitor/core'

Plugins.MyAudioPlugin.decode({
  path: 'the/audio/that/I/want/to/use/native/code/to/decode'
  callback: function (progress) {
    // here I want to update progress bar
    // the progress is from native code
  }
})
```

Capacitor version: 1.1.1

**Comment by jcesarmobile** [comment]
This is a question, not an issue, please, don't use github issues to ask questions, you can ask on the [forums](https://forum.ionicframework.com/) or [slack](https://getcapacitor.herokuapp.com/)

To use callbacks in plugins, check Geolocation and Background Task plugins, they both implement one.
