### ISSUE TITLE
[Android] getCurrentPosition fails with "location unavailable" after GPS has been toggled off and on

### ISSUE THREAD

**Issue by N0ps32** [ionic-team/capacitor#1921]
Steps to reproduce:
 - turn off location services on your device
 - open capacitor app that calls getCurrentPosition()
 -> now it should fail because you turned off location services that's okay so far
 - turn on location services and switch back to your app and run getCurrentPosition() again
 -> now the call **STILL FAILS** even though location services are turned back on

This is because getBestLocation tries to run getLastKnownLocation on the passive provider which returns null, because no other App has requested a Location since you turned Location services back on. If you switch to google maps and request your current location  getCurrentPosition starts working again because the Android location service has another location in memory.

**Comment by jcesarmobile** [comment]
Sadly that's how current implementation works, a possible solution is switching to fused location providers, there is already an issue for it, so going to close this one as duplicate-

https://github.com/ionic-team/capacitor/issues/379
