### ISSUE TITLE
Clover Flex Android device fails to load the HTTP url

### ISSUE THREAD

**Issue by LukaszGrela** [ionic-team/capacitor#1924]
I'm trying to run the Capacitor wrapped app on the [Clover Flex Android device](https://www.clover.com/shop/clover-flex). I've been able to install the app but on screen I see only the `HTTP Not Allowed` message

Is there a way to set the web server to serve the pages over https?

![image](https://user-images.githubusercontent.com/7643591/64247941-c9ddfc80-cf07-11e9-8ec5-8edf54a6e053.png)

**Comment by jcesarmobile** [comment]
yeah, next release will allow to configure the scheme to use

**Comment by LukaszGrela** [comment]
Are there any indication to the release date?

**Comment by dinesh-krish** [comment]
Hi Am also facing this issue. how can i fix this

**Comment by vespina** [comment]
I am also facing this issue with Clover devices. Is there a way to solve this on the current version of Ionic?

**Comment by LukaszGrela** [comment]
The Scheme is implemented: 
```
//capacitor.config.json
{
  "server": {
    "androidScheme": "https",
  }
}
```

**Comment by vespina** [comment]
Exactly!! I found this same solution yesterday by debugging the java code on Android Studio.  For Cordova, the solution is to add this line on the appropriate section on config.xml:

`<preference name="Scheme" value="https" />`


Victor Espina


> The Scheme is implemented:
> [DOCS: configuration your app](https://capacitor.ionicframework.com/docs/basics/configuring-your-app/)
> 
> ```
> //capacitor.config.json
> {
>   "server": {
>     "iosScheme": "https",
>     "androidScheme": "https",
>   }
> }
> ```
> 
> also you can assign web view client e.g.
> 
> ```
>     this.getBridge().getWebView().setWebViewClient(new BridgeWebViewClient(this.getBridge()) {
> 
>       @SuppressWarnings("deprecation")
>       @Override
>       public void onReceivedError(WebView view, int errorCode, String description, String failingUrl) {
>           Log.e("MainActivity", "onReceivedError: " + errorCode + ", " + description + ", " + failingUrl);
>       }
>     });
> ```
