### ISSUE TITLE
Capacitor.convertFileSrc produces "unsafe" capacitor:// scheme on iOS

### ISSUE THREAD

**Issue by barrcodes** [ionic-team/capacitor#1931]
My application requires knowing both the file URI and the source path of various media files. To achieve this, I am:

- capturing media (example: photo) using CameraResultType.Uri
- copying the resulting photo to a persistent location
- testing the photo by loading it into my app.

Pseudocode:

```
// capture photo using CameraResultType.Uri so we can move the resulting photo
const photo = await Camera.getPhoto({
    resultType: CameraResultType.Uri,
    saveToGallery: true,
    source: cameraSource,
});

const srcUri = photo.path;

// get "x.jpg"
const fileName = this.fileService.getFileNameWithExtension(srcUri); 

//make folder, if it doesn't exist
await Filesystem.mkdir({
    path: folderName,
    directory: FilesystemDirectory.Data,
    createIntermediateDirectories: true
})
.catch((err: Error) => {
    console.log(`Couldn't create folder: ${err.message}`)
});

//get folder uri
const getUriResult = await Filesystem.getUri({
    path: folderName,
    directory: FilesystemDirectory.Data
});

// normalizes folder URI, because iOS returns with a trailing /
const folderUri = this.fileService.normalizeDirectory(getUriResult.uri);
const newFileUri = `${folderUri}${fileName}`;

// copy to new uri, and delete original
const fileReadResult = await Filesystem.readFile({
    path: srcUri
});

const writeResult = await Filesystem.writeFile({
    path: newFileUri,
    data: fileReadResult.data
});

await Filesystem.deleteFile({`
    path: srcUri
});

// get src path for display
imageSrc = this.sanitizer.bypassSecurityTrustUrl(Capacitor.convertFileSrc(newFileUri));
```
The problem is that Capacitor.convertFileSrc returns a capacitor://localhost/_capacitor_file_/... url, and the capacitor:// scheme is considered unsafe by angular.

Failure to do DomSanitizer.bypassSecurityTrustUrl will cause the error:

```
Sanitizing unsafe url capacitor://localhost/_capacitor_file_/... 
Failed unsafe:capacitor://localhost/_capacitor_file_/... to load resource: unsupported URL.
```

However, bypassing security in this way could pose XSS vulnerabilities, depending on from where the data arrives. It is therefore recommended to have the ability to whitelist these custom capacitor schemes.

Theoretically, if these schemes are whitelisted, XSS is still possible. Input validation is still necessary to prevent an XSS attack. However, forcing the developer to sanitize these URLs creates an unsafe pattern where developers may sanitize *other* URLs that they should not.

**Comment by jcesarmobile** [comment]
Capacitor apps use `capacitor://` scheme on iOS, it's how it works. The scheme can be configured, but angular won't like any of them (Apple won't let you use http or https for local resources).

I think you can configure angular to trust all `capacitor://` urls without the need of using `bypassSecurityTrustUrl` in each one of them, but I'm not angular expert.

I don't see this as a Capacitor bug, so going to close.

**Comment by ibrahimAboelsuod** [comment]
Capacitor is heavly used within ionic with Angular. How is this not a Capacitor bug?
