### ISSUE TITLE
Feature Request: Please add support for App.minimizeApp()

### ISSUE THREAD

**Issue by naveedahmed1** [ionic-team/capacitor#1933]
Description of the problem:

Currently we are able to use hardware back button to exit app by listening to `backButton `event and then calling `App.exitApp();`:

```
App.addListener('backButton', (data: AppUrlOpen) => {
            if (!(this.routerOutlet && this.routerOutlet.canGoBack())) {
                App.exitApp();
            }
        });
```

It would be great, that if an option to Minimize App could also be added to the capacitor and we could use something like `App.minimizeApp(); `

There's a cordova plugin https://github.com/tomloprod/cordova-plugin-appminimize for this purpose, but I believe since its a common use case, it should be added to the Capacitor.

Affected platform
- [x ] Android
- [ x] iOS

OS of the development machine
- [x ] Windows

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Or if you are really interested and have the knowledge to implement this, you can send a PR.
