### ISSUE TITLE
[Web] toasts are not displayed

### ISSUE THREAD

**Issue by diachedelic** [ionic-team/capacitor#1934]
Description of the problem:

A `<pwa-toast>` element is added to the DOM, but is not made visible or filled with text. Am I expected to install a `pwa-toast` web component or something? I am not using Ionic, just plain Capacitor.

See https://github.com/ionic-team/capacitor/blob/master/core/src/web/toast.ts

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [x] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Capacitor version: 1.2.0

Steps to reproduce:

use `Toast.show({ text: 'hello' })` in the browser

**Comment by diachedelic** [comment]
![image](https://user-images.githubusercontent.com/310464/64484047-2d419480-d250-11e9-82c3-7db6987bb8c0.png)

**Comment by jcesarmobile** [comment]
Yeah, some plugins such as Camera and Toast require to install [PWA Elements](https://capacitor.ionicframework.com/docs/pwa-elements) to work.
Added a note on #1998
