### ISSUE TITLE
Use Android X dependencies

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#1937]
Next major should be updated to use Android X (dependencies and code usage on @capacitor/android should be updated).

See if [jetifier](https://github.com/mikehardy/jetifier)  works on cordova/capacitor plugins, if not, the CLI should remap cordova plugins to use Android X on the update process, remapping dependencies and patching the code usages, and we might want to create a tool that works like jetifier that for Capacitor plugins.

**Comment by unclebumpy** [comment]
@nikmartin How did you do that?

**Comment by kyleabens** [comment]
@nikmartin I would also like to know how you did that because I tried incorporating the Firebase Analytics sdk (17.2.0) which uses Android X and was unable to build it without some kind of error.

**Comment by jcesarmobile** [comment]
please people, don't hijack the thread for your own questions

**Comment by jcesarmobile** [comment]
according to a message in Capacitor slack, jetifier is able to patch plugins and even @capacitor/android 

> Mike Roberts
> While we wait for 2.0 to add Android X support, just add this to gradle.properties
> android.enableJetifier=true
> android.useAndroidX=true
> And if you have issues with stuff in node_modules not using android x then `install jetifier npm i -D jetifier` and add a postinstall hook in package.json under scripts and run `npm install` again
>     "postinstall": "jetifier -r"
> 

Going to unlock the thread so people can comment if they find issues with this approach, but please, keep it on topic or I'll lock it again.

**Comment by Nasicus** [comment]
Hmm I just tried the approach, didn't work at all for me:

I did the following, after doing `npm i` the jetifier did some stuff:

```
> jetifier -r

Jetifier found 170 file(s) to reverse-jetify. Using 8 workers...
```
However once I opened Android Studio and tried to build I still got this:
![image](https://user-images.githubusercontent.com/1086065/68924082-3a16c300-0780-11ea-84b4-d03088b4872f.png)
=> the `Plugin.java` is also in the `node_modules` folder...but it looks like `jetfier` didn't modify / touch it...

**Comment by Raerten** [comment]
@Nasicus use `jetifier` without `-r`

**Comment by Nasicus** [comment]
I see... what is correct now?  With `-r` and without is a big difference:
>

However without the `-r` I seem to have more success, but it still doesn't work. I can now build it again in Android Studio and then even deploy/install it on the phone, however there it opens and closes immediately and from the log cat I see the following:

```
    java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/ch.cycl.capsal-trk9mT-ootskpmX4v0v56g==/base.apk"],nativeLibraryDirectories=[/data/app/ch.cycl.capsal-trk9mT-ootskpmX4v0v56g==/lib/arm64, /system/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6625)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6150)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
        at android.app.ActivityThread.access$1300(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1758)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Here is the sample project in which I tried to make it work (see the commit log for the commands I executed).
https://github.com/Nasicus/capsal/commit/4ac736de0a766eee459f26510716bf6e3893e44e

**Comment by Raerten** [comment]
without `-r` it patchs `node_modules` for AndroidX
`-r` for reverse - patch for support lib.
@Nasicus now you have error in project native code
find string `android.support.v4.content.FileProvider` in `android/app/src/main/AndroidManifest.xml` and change it to `androidx.core.content.FileProvider`

**Comment by Nasicus** [comment]
@Raerten Thanks again. I actually did it via Android Studio: `Refactor => Migrate to Android X....` 
Here are the changed files, for anyone who cares: https://github.com/Nasicus/capsal/commit/ddf75a43ee84314645253e17cd7c2e9cf32bad12

Anyway after this I could indeed build & install the app again.

Now I just have to do it with my real application, pray to god (for safety maybe sacrifice a baby goat) and hope that it works too...

**Comment by Karrlllis** [comment]
Hi 
Jetifier without "-r" works for me
**"postinstall": "jetifier"**

Migrate to androidX will work on one system. After committing files nex env will not work and another Migrate will fail.

**Comment by mike-roberts** [comment]
Ah yeah, my bad, without the `-r` is the proper way. Was looking at my react-native app when I typed that which needs the reverse, my bad!

**Comment by andirsun** [comment]
> Hi
> Jetifier without "-r" works for me
> **"postinstall": "jetifier"**
> 
> Migrate to androidX will work on one system. After committing files nex env will not work and another Migrate will fail.

please can you describe me the changes that i need to do  ? I want to add analitycs integrations but my app close when i open it.

**Comment by donjon1234** [comment]
Well, I struggled with this 2 days now thanks to this thread I got it working, with androidX set to true.
Jetifier works for sure but its a bit sad we needs to do all the extra work and debugging all the time to make it work Capacitor is not supporting androidx per out of the box but ah well thanks guys for the help!

**Comment by andirsun** [comment]
> @Raerten Thanks again. I actually did it via Android Studio: `Refactor => Migrate to Android X....`
> Here are the changed files, for anyone who cares: [Nasicus/capsal@ddf75a4](https://github.com/Nasicus/capsal/commit/ddf75a43ee84314645253e17cd7c2e9cf32bad12)
> 
> Anyway after this I could indeed build & install the app again.
> 
> Now I just have to do it with my real application, pray to god (for safety maybe sacrifice a baby goat) and hope that it works too...

Work For Me thankssss

**Comment by thesheikhwasim** [comment]
Add below lines to gradle.properties to overcome this error
android.useAndroidX=true
android.enableJetifier=true

**Comment by karthickbadrick** [comment]
![image](https://user-images.githubusercontent.com/34476082/190864496-e7ebe514-9970-44a0-ad03-9b5a9cfd5fa6.png)
i tried many methods but cannot resolve this issue plz give any solution

**Comment by nikmartin** [comment]
@karthickbadrick you should open a new issue, not reply to this three year old unrelated issue
