### ISSUE TITLE
Notifications should support muti-line text - Proposed solution

### ISSUE THREAD

**Issue by naveedahmed1** [ionic-team/capacitor#1940]
Description of the problem:
Notifications should support multi-line text. I believe it requires just a small change in  `buildNotification` method of below file:

https://github.com/ionic-team/capacitor/blob/bdc03980a2274dee146cbde360c4d2a33e2ed04e/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java#L145

If we add `.setStyle(new NotificationCompat.BigTextStyle().bigText(localNotification.getBody()))`, it should fix this issue. I have tested it on my local machine and its works.

Affected platform
- [x ] Android

OS of the development machine
- [ x] Windows

Other information:

Capacitor version:
1.2.0

**Comment by katzenjunge** [comment]
This is still a pretty big issue, I hope this will get taken care of.

**Comment by andysousa** [comment]
Local Notification needs A LOT of help and this is another biggie... you should submit a PR so we can get this into an official release!
