### ISSUE TITLE
ERROR: Plugin with id 'io.fabric' not found.

### ISSUE THREAD

**Issue by davids200** [ionic-team/capacitor#1941]
I have been building my ionic + firebase app successfully, but recently i started getting this error "ERROR: Plugin with id 'io.fabric' not found.". What could be the cause and how can i update the plugin automatically? i use ionic 4 +firebase+android: 
Thank you in advance.

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/1297

**Comment by ma7moudjadallah** [comment]
any update >?
