### ISSUE TITLE
NSArrayM was mutated while being enumerated

### ISSUE THREAD

**Issue by CrixuAMG** [ionic-team/capacitor#1943]
While testing on iOS I saw the app freeze and display the error below on xcode. I have no experience with the native code part of Capacitor and don't know what to do with it. Is it Capacitor related, OS X Catalina/iOS 13 related? Any information would be great!

```
2019-09-10 10:58:07.462204+0200 App[4922:1313018] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x2814fc2a0> was mutated while being enumerated.'
*** First throw call stack:
(0x181521c20 0x18123c0c8 0x181521588 0x18124f0f8 0x104613870 0x10461364c 0x1046c6eb8 0x1046c7228 0x1818ec288 0x181479b20 0x181479b70 0x181478e68 0x181478b00 0x1813f1ab8 0x181478430 0x1817dadcc 0x10413cea8 0x10413d06c 0x10443de48 0x10443f2a8 0x10444d35c 0x18149ce10 0x181497b6c 0x181497088 0x18b5f1534 0x1855b4fb8 0x10413d578 0x181316f30)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

Capacitor 1.2.0
iOS 13.1 beta 2
OS X Mojave 10.14.5

**Comment by CrixuAMG** [comment]
I think I fixed the bug. While working on the app I noticed a method getting more calls than it should, fixed that and now I cannot reproduce the error anymore. The method that was being called returns the device's information and registers a push notification handler.

**Comment by RangerRick** [comment]
I have actually run into this issue.  Hard to reproduce reliably but it happens when you remove event listeners while there are events being triggered.

I've worked around it in my own code so it won't trigger this time around, but it's a real synchronization problem in Capacitor.  The "easy" fix is to iterate by index:

```diff
diff --git a/ios/Capacitor/Capacitor/CAPPlugin.m b/ios/Capacitor/Capacitor/CAPPlugin.m
index f0fe9e14..fe153c0a 100644
--- a/ios/Capacitor/Capacitor/CAPPlugin.m
+++ b/ios/Capacitor/Capacitor/CAPPlugin.m
@@ -99,10 +99,14 @@
     }
     return;
   }
-
-  for(CAPPluginCall *call in listenersForEvent) {
-    CAPPluginCallResult *result = [[CAPPluginCallResult alloc] init:data];
-    call.successHandler(result, call);
+
+  for (int i=0; i < listenersForEvent.count; i++) {
+      CAPPluginCall *call = listenersForEvent[i];
+      if (call != nil) {
+        CAPPluginCallResult *result = [[CAPPluginCallResult alloc] init:data];
+        call.successHandler(result, call);
+      }
+    }
   }
 }
```

...although it could technically drop/miss events because of timing.  The "real" fix is to probably use a serial queue of some kind to be sure actions on the event listeners are not all done simultaneously.
