### ISSUE TITLE
Question:  Where should I set DisableDeploy?

### ISSUE THREAD

**Issue by borodiliz** [ionic-team/capacitor#1944]
Newbie question but I can't find any solution. Thanks in advance

Where should I set DisableDeploy?. Tested so far:
* `config.xml`: No effect at all. Is this [example file](https://github.com/ionic-team/capacitor/blob/master/example/config.xml) required on a Capacitor project?
* `ios/App/App/Info.plist`: No effect at all
* `ios/App/App/config.xml` and `android/app/src/main/res/xml/config.xml`: Works fine until you execute `npx cap sync`. This command overwrites `ios/App/App/config.xml` and `android/app/src/main/res/xml/config.xml`

**Comment by jcesarmobile** [comment]
At the moment the only way is manually copying the value to the generated config.xml file, but as you say, it gets overwritten.

With [this PR](https://github.com/ionic-team/capacitor/pull/1977) you'll be able to set it like this in capacitor.config.json:

```
"cordova": {
    "preferences": {
      "DisableDeploy": "true"
    }
  }
```

Works for any Cordova preference, not just DisableDeploy.

**Comment by typeoneerror** [comment]
@jcesarmobile is this released? I am adding the "cordova" block to our capactitor.config and it is still getting overwritten

**Comment by jcesarmobile** [comment]
Yes, it's released. 
The config.xml is always overwritten, what the PR does is to set your own preferences into the config.xml based on the capacitor.config.json preferences.

**Comment by biesbjerg** [comment]
The PR was merged 23th september, and as far as I can tell the latest release is 1.2.1 released on 17th september?

**Comment by jcesarmobile** [comment]
ah, yeah, sorry, it's not released yet

**Comment by jcesarmobile** [comment]
1.3.0 was released yesterday including this feature

**Comment by LouAdrien** [comment]
Hello. This seems to NOT be working at all in capacitor 1.5.1
Setting 

```
"cordova": {
    "preferences": {
      "DisableDeploy": "true"
    }
  }
```

in capacitor.config will indeed update 
android/app/src/main/res/xml/config.xml
and
ios/App/App/config.xml 

to contain   <preference name="DisableDeploy" value="true" />

But this will have no impact on the plugin being used (it is still used).
Can anyone get this to work on capacitor 1.5.1?

**Comment by nelson6e65** [comment]
> This seems to NOT be working at all in capacitor 1.5.1


It's working on Capacitor 2.4.2/Ionic 5.3.4.

PD: Just in case, you must use ***`"true"` (string)*** instead of `true` (boolean) in order to work.

**Comment by ihazar** [comment]
In Angular, inside `capacitor.config.ts` from the project root, add the following:
`cordova: {
        preferences: {
	        DisableDeploy: 'true',
        }
}`
so that it looks like this:
`
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
	appId: 'app-id',
	appName: 'my-app-name',
	webDir: 'dist',
	bundledWebRuntime: false,
	plugins: {
		PushNotifications: {
			presentationOptions: ['badge', 'sound', 'alert'],
		},
	},
	cordova: {
		preferences: {
			DisableDeploy: 'true',
		}
	}
};

export default config;
`

Then you can run `npx cap sync` and then `npm cap update` and it should update the required files.
