### ISSUE TITLE
Can't add external repositories while creating plugin in capacitor 

### ISSUE THREAD

**Issue by suriyakumarcs** [ionic-team/capacitor#1945]
Description of the problem:
I'm trying to add external repo **com.github.ExCiteS:apache-commons-codec-shaded:1.11** using build.gradle file. But i got error at run time

```
**Could not find com.github.ExCiteS:apache-commons-codec-shaded:1.11**

Searched in the following locations:
  - file:/home/ubuntu/Android/Sdk/extras/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
  - file:/home/ubuntu/Android/Sdk/extras/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
  - file:/home/ubuntu/Android/Sdk/extras/google/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
  - file:/home/ubuntu/Android/Sdk/extras/google/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
  - file:/home/ubuntu/Android/Sdk/extras/android/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
  - file:/home/ubuntu/Android/Sdk/extras/android/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
  - https://dl.google.com/dl/android/maven2/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
  - https://dl.google.com/dl/android/maven2/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
  - https://jcenter.bintray.com/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
  - https://jcenter.bintray.com/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
  - https://dl.bintray.com/ionic-team/capacitor/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
  - https://dl.bintray.com/ionic-team/capacitor/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
  - file:/home/ubuntu/Projects/Fund-request/Fund-Request/android/capacitor-cordova-android-plugins/src/main/libs/apache-commons-codec-shaded-1.11.jar
  - file:/home/ubuntu/Projects/Fund-request/Fund-Request/android/capacitor-cordova-android-plugins/src/main/libs/apache-commons-codec-shaded.jar
  - file:/home/ubuntu/Projects/Fund-request/Fund-Request/android/app/libs/apache-commons-codec-shaded-1.11.jar
  - file:/home/ubuntu/Projects/Fund-request/Fund-Request/android/app/libs/apache-commons-codec-shaded.jar
Required by:
    project :app > project :cordova-plugin-aes256-encryption
```

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

build.gradle file
 Runtime error occured when i access Hex.

Capacitor version:latest

node version:V10.5.3

npm version:6.4.1

CocoaPods version:

Steps to reproduce:

My build.gradle file

```
repositories {
    google()
    jcenter()
    mavenCentral()  
    maven { url 'https://jitpack.io' } 
}


dependencies {
    implementation 'com.github.ExCiteS:apache-commons-codec-shaded:1.11'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':capacitor-android')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```
OS version: **Android**

Can someone help me on this!?

Link to sample project:

**Comment by suriyakumarcs** [comment]
> Description of the problem:
> I'm trying to add external repo **com.github.ExCiteS:apache-commons-codec-shaded:1.11** using build.gradle file. But i got error at run time
> 
> ```
> **Could not find com.github.ExCiteS:apache-commons-codec-shaded:1.11**
> 
> Searched in the following locations:
>   - file:/home/ubuntu/Android/Sdk/extras/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
>   - file:/home/ubuntu/Android/Sdk/extras/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
>   - file:/home/ubuntu/Android/Sdk/extras/google/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
>   - file:/home/ubuntu/Android/Sdk/extras/google/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
>   - file:/home/ubuntu/Android/Sdk/extras/android/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
>   - file:/home/ubuntu/Android/Sdk/extras/android/m2repository/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
>   - https://dl.google.com/dl/android/maven2/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
>   - https://dl.google.com/dl/android/maven2/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
>   - https://jcenter.bintray.com/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
>   - https://jcenter.bintray.com/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
>   - https://dl.bintray.com/ionic-team/capacitor/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.pom
>   - https://dl.bintray.com/ionic-team/capacitor/com/github/ExCiteS/apache-commons-codec-shaded/1.11/apache-commons-codec-shaded-1.11.jar
>   - file:/home/ubuntu/Projects/Fund-request/Fund-Request/android/capacitor-cordova-android-plugins/src/main/libs/apache-commons-codec-shaded-1.11.jar
>   - file:/home/ubuntu/Projects/Fund-request/Fund-Request/android/capacitor-cordova-android-plugins/src/main/libs/apache-commons-codec-shaded.jar
>   - file:/home/ubuntu/Projects/Fund-request/Fund-Request/android/app/libs/apache-commons-codec-shaded-1.11.jar
>   - file:/home/ubuntu/Projects/Fund-request/Fund-Request/android/app/libs/apache-commons-codec-shaded.jar
> Required by:
>     project :app > project :cordova-plugin-aes256-encryption
> ```
> 
> Affected platform
> 
> * [x]  Android
> * [ ]  iOS
> * [ ]  electron
> * [ ]  web
> 
> OS of the development machine
> 
> * [ ]  Windows
> * [ ]  macOS
> * [x]  linux
> 
> Other information:
> 
> build.gradle file
> Runtime error occured when i access Hex.
> 
> Capacitor version:latest
> 
> node version:V10.5.3
> 
> npm version:6.4.1
> 
> CocoaPods version:
> 
> Steps to reproduce:
> 
> My build.gradle file
> 
> ```
> repositories {
>     google()
>     jcenter()
>     mavenCentral()  
>     maven { url 'https://jitpack.io' } 
> }
> 
> 
> dependencies {
>     implementation 'com.github.ExCiteS:apache-commons-codec-shaded:1.11'
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation project(':capacitor-android')
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'com.android.support.test:runner:1.0.2'
>     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
> }
> ```
> 
> OS version: **Android**
> 
> Can someone help me on this!?
> 
> Link to sample project:

**Comment by jcesarmobile** [comment]
Use `compileOnly` instead of `implementation`, that way it will only be used for compiling your plugin
