### ISSUE TITLE
Single Sign-on (SSO) Child Browser Flow

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#1948]
Capacitor has an excellent [Browser API](https://capacitor.ionicframework.com/docs/apis/browser). 

However, a common usage is Single Sign-on (SSO) such as OpenID-Connect and system-to-system authentication, such as OAuth. For these use-cases the Browser API doesn't work that well.

It would be great if Capacitors Browser API would support this common use-case.

Happy to elaborate on this and describe the use-cases in-depth.

Let me know what you think! Is this something that could be added to the Browser API?

## iOS
Apple has two classes for this, [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) (deprecated) and [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) (their most recent API). 

They make sure that credentials (active sessions) with the identity provider is re-used within the child-browser, to avoid prompting the user for login credentials over and over again.

## Android
Android has [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs#whentouse) for this purpose, they work similar to their iOS equivalents.

**Comment by jcesarmobile** [comment]
Browser already uses Chrome Custom Tabs on Android, so not sure what are you suggesting.

Anyway, there is already a feature request issue for an Auth plugin https://github.com/ionic-team/capacitor/issues/395

Also you can use current browser implementation and make the auth provider to redirect to a custom app scheme that you have configured and use App plugin to listen for the appUrlOpen event, it should contain the login token

**Comment by sandstrom** [comment]
@jcesarmobile Thanks for commenting on this!

For SSO use-cases one should use [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) on iOS. So that's basically what this issue is about.

**Comment by tonyxiao** [comment]
@sandstrom do you have a sense of what's the difference of using `ASWebAuthenticationSession` vs using `SFSafariViewController` with custom scheme to redirect back into the app?

**Comment by sandstrom** [comment]
@tonyxiao No, I don't know without researching that, sorry.

**Comment by doublechecker** [comment]
Hey there. This is quite important because we already had some trouble with Apple App Review. Sometimes they reject our app because we do not use the desired way of ASWebAuthenticationSession. When ASWebAuthenticationSession is used there is an alert asking the user if the app should open a authentication-session (see screenshot as example).

![33736712-3d3deaf4-db59-11e7-9336-552df2fc092d](https://user-images.githubusercontent.com/50179741/159162634-c122db23-b9ad-4b94-bbe7-feed6d67ba33.png)

**Comment by sandstrom** [comment]
@jcesarmobile Would you be willing to re-open this issue? 

I'd say this is still an issue, see:
- https://github.com/ionic-team/capacitor/issues/1948#issuecomment-573780866
- https://github.com/ionic-team/capacitor/issues/1948#issuecomment-1073242146
