### ISSUE TITLE
can't open deep links anymore

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#1965]
Description of the problem:
I updated capaciotr over the weekend and now when I try and open a deep link using the app.openUrl, the app crashes with this error:

> > Fatal error: Unexpectedly found nil while unwrapping an Optional value
> 2019-09-15 21:48:58.339501+0200 App[22699:8429800] Fatal error: Unexpectedly found nil while unwrapping an Optional value

`await App.openUrl({ url });`

Affected platform
- [ ] Android
- [x ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x ] macOS
- [ ] linux

This was working perfect before updating capacitor so im wondering what has changed?

**Comment by oliverandersencox** [comment]
@jcesarmobile any ideas?

**Comment by stewwan** [comment]
so what was the problem here? please try to explain why the issue is being closed.

I know some folks that are experiencing the same with iPhone X and ios 13
