### ISSUE TITLE
capacitor open android return unhandled 'error' event

### ISSUE THREAD

**Issue by checcoux** [ionic-team/capacitor#1971]
Description of the problem:
running `ionic capacitor open android` does not open android studio and return an unexpected error:
```
[info] Opening Android project at /home/checcoux/uxadmin/android
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: spawn /usr/local/android-studio/bin/studio.sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[ERROR] An error occurred while running subprocess capacitor.
```
I have to open manually android studio then.

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

```
OS: Arch Linux x86_64
Hostname: hp
Uptime: 2:26, 33 sec
Kernel: 5.2.14-arch2-1-ARCH
Shell: /usr/bin/zsh
RAM: 6948M / 12006M (57%)
CPU: Intel(R) Xeon(R) CPU 5150 @ 2.66GHz
Root: 39G / 106G (39%) (ext4)

```

Capacitor version:
v1.1.1

node version:
v10.16.3

npm version:
v6.9.0

CocoaPods version:
none

Steps to reproduce:
`ionic capacitor open android` or every cli command that includes that (for example `ionic capacitor run android --livereload`)

**Comment by Ucheduk** [comment]
I am having the same issue right now....  I hope it get fixed soon

**Comment by Joshmatjjen** [comment]
This error just put my project on pending, i am using linux .... I hope this can be fixed by the @mlynch @jcesarmobile

**Comment by jcesarmobile** [comment]
Since looks like every linux distro put Android Studio in a different place (or the user can change the default install path too) the default location we use might not work on same computer, Capacitor has `linuxAndroidStudioPath` configuration option to manually point to the Android Studio path.

There is an issue about automatic detection of the path, but not really sure if that's possible.
https://github.com/ionic-team/capacitor/issues/560

**Comment by LuisJoseSanchez** [comment]
I have the same problem with Android and Linux.
