### ISSUE TITLE
[Feature] web: Camera.getPhoto open file explorer 

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor#1973]
I'm not sure if the Capacitor-Team is even interest to support a web fallback to test things with `ionic --serve`in the browser but it would be cool if `Camera.getPhoto` opens the file explorer and let me choose a photo from my computer instead of "natively opens the camera". So I can test the implementation in my app before testing it on my device.

**Comment by kayneth** [comment]
Hi @muuvmuuv !

I think you might be interested by [this PR about using file input](https://github.com/ionic-team/capacitor/pull/1856). 😄

**Comment by jcesarmobile** [comment]
closing as duplicate of https://github.com/ionic-team/capacitor/issues/490
