### ISSUE TITLE
events keyboardWillHide not triggered

### ISSUE THREAD

**Issue by maxime-guyot** [ionic-team/capacitor#1974]
Description of the problem:

events keyboardWillHide not triggered when app return from background mode

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

Capacitor version: 1.2.1

Steps to reproduce:

- Open app, focus input, send app to background mode
- Send push notification with another device to this device
- Swipe notification to go in app
- App navigate to another page (this action blur previous input)
==> event "keyboardWillHide" not triggered...

**Comment by jcesarmobile** [comment]
can you provide a sample app?

Since it involves navigating to a different page it's a bit conplex to reproduce

**Comment by jcesarmobile** [comment]
closing since there was no response and I couldn't reproduce
