### ISSUE TITLE
Android Dark-Mode could not be detected

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/capacitor#1978]
The Capacitor WebView is unable to detect the media query `@media (prefers-color-scheme: dark)`. When opening the app inside chrome without capacitor, the dark mode is working as expected.

Try out the ionic example inside the browser and then with capacitor: https://ionicframework.com/docs/theming/dark-mode

Steps to reproduce:

1. create a new Ionic app with Capacitor
2. c&p the dark-mode code from the Ionic docs: https://ionicframework.com/docs/theming/dark-mode
3. run the app on an Android 10 device or simulator
4. toggle the system dark-Mode

Link to sample project: https://ionicframework.com/docs/theming/dark-mode

**Comment by rossholdway** [comment]
Hi. I'm also seeing this issue. Running the latest webview (v77) on Andorid 10 it doesn't seem to support the `prefers-color-scheme` CSS media feature however it does if you open the chrome app.

Setting `setForceDark` to `FORCE_DARK_AUTO` for the webview should fix this? https://developer.android.com/reference/android/webkit/WebSettings#setForceDark(int)

**Comment by jcesarmobile** [comment]
Looks like it's a bug on Android or on the WebView, according to what I've read it should just work, but it doesn't. `prefers-color-scheme` is recognized, but has `no-preference` value.
As workaround you can add this code to the MainActivity.java that forces dark mode into the WebView if the device has dark mode enabled.

```
    int nightModeFlags = getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
    WebSettings webSettings = this.bridge.getWebView().getSettings();
    if (nightModeFlags == Configuration.UI_MODE_NIGHT_YES) {
      if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
        webSettings.setForceDark(WebSettings.FORCE_DARK_ON);
      }
    }
```

But you need to target SDK 29, which might cause other issues.
Also only works for dark value, not for light.

**Comment by sean-perkins** [comment]
Adding to @jcesarmobile answer, we have used this solution for our needs:

Update MainActivity.java `onStart` method to include this:

```
@Override
    public void onStart() {
        super.onStart();
        // Android fix for enabling dark mode
        int nightModeFlags = getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
        WebSettings webSettings = this.bridge.getWebView().getSettings();
        if (nightModeFlags == Configuration.UI_MODE_NIGHT_YES) {
            String userAgent = webSettings.getUserAgentString();
            userAgent = userAgent + " AndroidDarkMode";
            webSettings.setUserAgentString(userAgent);
        }
    }
```

Then in whatever implementation you are using prefers-color-scheme, add the following to handle detecting the appended user agent string:

```
// Android fix for enabling dark mode, see native implementation in MainActivity.java
if (window.navigator.userAgent.includes('AndroidDarkMode')) {
     // Apply dark theme or set theme css variables to dark
}
```

We used user agent so we could share the same code across web and "native" platforms and avoid targeting SDK 29.

**Comment by jpike88** [comment]
Is there ANY WAY of overriding prefers-color-scheme on the web view without targeting a recent SDK?

**Comment by AlessandroFBK** [comment]
@sean-perkins Thank you for your solution, which work.
Nevertheless, I've defined some dark mode CSS inside a component which seems to be ignored on an emulator running the native app and works when an Android device is emulated using Chrome dev tool.
```
@media (prefers-color-scheme: dark) { ... }
```

**Comment by hinddeep** [comment]
If you want to dynamically listen to changes in the dark mode on android, you can use the plugin I've developed. In opposition to checking whether dark mode has been enabled during app lauch, the plugin will allow you to listen to changes in the dark mode even while your app is running. Also, there is no need to target sdk 29. I've tested the plugin by targetting sdk 28 and it works fine. 

https://github.com/hinddeep/ionicCapacitorDarkMode

**Comment by cmaas** [comment]
To make this a bit more complete, could you guys also post your preferred solution to handle the navigationBarColor when using dark mode in a Capacitor app? On my Samsung test device, the webview app will still run with a light navigation bar (not status bar!) even though the dark mode is enabled. One workaround would be to set the navigationBarColor programmatically:

```java
if (nightModeFlags == Configuration.UI_MODE_NIGHT_YES) {
    // ...
    getWindow().setNavigationBarColor(ContextCompat.getColor(this, R.color.colorNavbarDark));
}
```
How do you do it? Especially if the user disables the dark mode and you want to go back to the default system color?

(cc @sean-perkins @jcesarmobile )

**Comment by hinddeep** [comment]
> 
> 
> To make this a bit more complete, could you guys also post your preferred solution to handle the navigationBarColor when using dark mode in a Capacitor app? On my Samsung test device, the webview app will still run with a light navigation bar (not status bar!) even though the dark mode is enabled. One workaround would be to set the navigationBarColor programmatically:
> 
> ```java
> if (nightModeFlags == Configuration.UI_MODE_NIGHT_YES) {
>     // ...
>     getWindow().setNavigationBarColor(ContextCompat.getColor(this, R.color.colorNavbarDark));
> }
> ```
> 
> How do you do it? Especially if the user disables the dark mode and you want to go back to the default system color?
> 
> (cc @sean-perkins @jcesarmobile )

The plugin I've written is only responsible for notifying the web app of system wide color scheme changes. The rest needs to be handled within the web app. For instance, if you're using my plugin, you can set the color of Status Bar inside the "darkModeStateChanged" listener. You can alter the color of the statusbar by using the following Capacitor API:
https://capacitor.ionicframework.com/docs/apis/status-bar/

Inside the web app:
Plugins.DarkMode.addListener("darkModeStateChanged", (state: any) => {
if(state.isDarkModeOn)
{
// Dark mode is on. Apply dark theme to your app
   StatusBar.setStyle({
      style: StatusBarStyle.Dark
    });
}
else
{
// Dark mode is off. Apply light theme to your app
StatusBar.setStyle({
      style: StatusBarStyle.Light
    });
}
if(state.supported == false)
{
// Dark mode is not supported by the platform
}
});
I hope this helps. Please let me know if you need more clarification.

**Comment by cmaas** [comment]
@hinddeep Thanks, but I'm talking about the **navigation bar** (Home, Back, Recent), not the status bar. I think this can be set in the Android theme. I just wonder what the "proper" way to do this would be.
