### ISSUE TITLE
feat: add .gitignore to plugin template

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/capacitor#1980]
Description of the problem:

Running the `npx @capacitor/cli plugin:generate` command will not generate a `.gitignore` but a `.npmignore` file that duplicates the `files` configuration inside the `package.json` file.
Also the command should init the plugin with git.

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Steps to reproduce:
run `npx @capacitor/cli plugin:generate`

**Comment by mburger81** [comment]
Error still persists, does someone have a usefull template for .gitignore?

**Comment by jcesarmobile** [comment]
2.4.0 should generate the `.gitignore` file
was fixed in https://github.com/ionic-team/capacitor/pull/3292
