### ISSUE TITLE
Using DisableDeploy 

### ISSUE THREAD

**Issue by Livijn** [ionic-team/capacitor#1981]
[The docs state](https://beta.ionicframework.com/docs/appflow/deploy/api#disabledeploy) that I should add `<preference name="DisableDeploy" value="true" />` to the `config.xml`. At first, I tried creating a `config.xml` in the root of the project "cordova style" and then running `ionic cordova prepare` but that gave me en error.
 > Cordova is not supported for vue projects

So instead, I edited the `/ios/App/App/config.xml` which works. However, when running `npx cap copy` that `config.xml` is being overwritten. So I'll manually have to edit this after each run.

How is this supposed to work? Shouldn't there be an option in the `capacitor.config.json`?  Also, the other deploy configuration options are located in `Info.plist` & `strings.xml` but this option isn't. That feels strange.

**Comment by borodiliz** [comment]
@Livijn check #1944
