### ISSUE TITLE
How can run 19 on Capacitor 

### ISSUE THREAD

**Issue by KSayed91** [ionic-team/capacitor#1984]
Depend on Documentation [here](https://capacitor.ionicframework.com/docs/android/#running-your-app) is support at lease android 5.0, is there any way to support android 4.0 using capacitor ?

**Comment by LukaszGrela** [comment]
Definitely you will need this update #1956 (to have it working on Android 5.0-6.0), but have you tried to run it on Android 4.0? What errors you've encountered?

**Comment by jcesarmobile** [comment]
No, there is no way of making it work on Android 4.
