### ISSUE TITLE
NewRelicAgent/NewRelic.h file not found

### ISSUE THREAD

**Issue by wilsolutions** [ionic-team/capacitor#1986]
Hi,

I've been using Newrelic for a while with Cordova 9.
I'm trying to switch to Capacitor however the build fails with `NewRelicAgent/NewRelic.h file not found` error.

Thank you
Wils

**Comment by jcesarmobile** [comment]
The plugin has hooks and Capacitor doesn't support hooks.

I've created a node script that is similar to `before_plugin_install.js` and makes the app build after running it.

```
var fs = require("fs");
var linkPath = "ios/capacitor-cordova-ios-plugins/sources/NewrelicCordovaPlugin/libs/ios/NewRelicAgent.framework/";
var targetPath = "Versions/A/";
if(!fs.existsSync(linkPath + 'NewRelicAgent')){
    fs.symlinkSync(targetPath + 'Headers/', linkPath + 'Headers', 'dir');
    fs.symlinkSync(targetPath + 'NewRelicAgent', linkPath + 'NewRelicAgent', 'file');
    fs.symlinkSync(targetPath + 'Resources/', linkPath + 'Resources', 'dir');
}
```
