### ISSUE TITLE
Any way to remove the share button on the IOS InAppBrowser?

### ISSUE THREAD

**Issue by edgarciametro** [ionic-team/capacitor#1989]
Description of the problem:

https://capacitor.ionicframework.com/docs/apis/browser#type-270

The Browser.open method has some features but none if them allow hiding the share and "view in Safari" buttons. Is there any way to remove those buttons/features?

Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Capacitor version: 1.2.1

**Comment by jcesarmobile** [comment]
It's not possible

**Comment by edgarciametro** [comment]
Any way to request this as a feature? There are plenty of situations where you only want to display the HTML page without the user getting the URL - for example in internal pages and reports you dont want a user to share.

**Comment by jcesarmobile** [comment]
It's not possible in the native component the plugin uses, so unless you request the feature to Apple, the answer is still no.
