### ISSUE TITLE
[Android] Asp.Net Core Blazor WebView 404

### ISSUE THREAD

**Issue by rdlaitila** [ionic-team/capacitor#1992]
This may or may not be a capacitor specific issue but looking for guidance on Android WebView behavior in relation to capacitor.

When attempting to load my Blazor client side application via Capacitor Android WebView I get 404's on the blazor javascript files. from my android studio logcat:

`
E/Capacitor: Unable to open asset URL: http://localhost/_framework/blazor.webassembly.js
`

Using emulator: Pixel 2 API 28

If i manually remove the underscores from Blazor folders and paths, and manually update some of their boot scripts to reference the updated paths everything works fine. ex:

`
http://localhost/framework/blazor.webassembly.js
`

Is there some restriction on leading underscores in Android web views, or some security configuration that I could apply? I will likely create an issue for the Asp.Net Core Blazor team as well on this.

Thanks!

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/1750
