### ISSUE TITLE
Capacitor unable to find .framework file in Cordova plugins

### ISSUE THREAD

**Issue by Taylorsuk** [ionic-team/capacitor#1997]
I've tried this with two Cordova plugins and have the same error on both. 

Plugins tried are:
`cordova-plugin-voxeet`
`cordova-plugin-opentok`

```
✖ update ios: ENOENT: no such file or directory, stat 'FILES/node_modules/cordova-plugin-voxeet/src/ios/Carthage/Build/iOS/VoxeetConferenceKit.framework'
[error] Error running update: { Error: ENOENT: no such file or directory, stat 'FILES/node_modules/cordova-plugin-voxeet/src/ios/Carthage/Build/iOS/VoxeetConferenceKit.framework'
    at Object.statSync (fs.js:824:3)
    at Object.statSync (FILES/node_modules/graceful-fs/polyfills.js:308:16)
    at Object.copySync (FILES/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:86)
    at frameworks.map (FILES/node_modules/@capacitor/cli/dist/ios/update.js:276:22)
    at Array.map (<anonymous>)
    at cordovaPlugins.map.p (FILES/node_modules/@capacitor/cli/dist/ios/update.js:274:20)
    at Array.map (<anonymous>)
    at copyPluginsNativeFiles (FILES/node_modules/@capacitor/cli/dist/ios/update.js:235:20)
    at Object.updateIOS (FILES/node_modules/@capacitor/cli/dist/ios/update.js:28:9)
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path:
   'FILES/node_modules/cordova-plugin-voxeet/src/ios/Carthage/Build/iOS/VoxeetConferenceKit.framework' }
✔ copy in 3.13ms
✔ update web in 13.53μp
Sync finished in 1.035s
```

**Comment by jcesarmobile** [comment]
Those plugins use cordova hooks to build those frameworks. Since Capacitor doesn't support hooks, you'll have to run the scripts yourself to generate the frameworks.

**Comment by Taylorsuk** [comment]
Thanks for the reply @jcesarmobile. However, it doesn't offer any assistance to overcome the problem, for me or other developers facing this issue as we endeavour to migrate to away from Cordova. Solving issues such as this are key to Capacitor adoption and therefore it's growth and success. I'm happy to contribute in anyway that I can, however guidance on where to start would be greatly appreciated.

Currently, I am planning on running a separate project to build the framework as part of `cordova prepare` and then copy it over? Will this work, or am I way off the mark?

**Comment by jcesarmobile** [comment]
The plugins are open source, so you can check their code and see what they are doing, and even if they aren't, their code will be in your mode_modules folder, so you can always check there.

I can't write a guide for every possible plugin that have hooks, but as a rule of thumb, check the plugin.xml and see if it has any hook, in this case:
https://github.com/voxeet/voxeet-cordova-conferencekit/blob/master/plugin.xml#L106
Then, as it's a node script, try running it with node `node build_ios_frameworks.js` from `yourProject/node_modules/cordova-plugin-voxeet` folder.

Another option is to ask the plugin maintainer to ship the frameworks already built instead of using a hook to build them.

Installing it in a Cordova project and copying the files over your project should work too.

**Comment by Taylorsuk** [comment]
Perfect! I wasn't asking for a guide for all plugins, but the above info is absolute gold for users like me who are desperately trying to reach the point where we can delete that `config.xml` from an ionic app. 

I've asked the developer to ship this already. 

Thanks very much for takin the time to reply.

**Comment by Taylorsuk** [comment]
Anyone landing here with a similar issue with `voxeet` you can find more specific instructions on iOS implementation on the actual iOS package `https://github.com/voxeet/voxeet-ios-conferencekit#project-setup`

**Comment by abhibly** [comment]
@Taylorsuk Did you fix the issue? I am facing the same issue. I followed the steps in the documents you mentioned. After I run 'carthage update' command, I can see the carthage folder and webrtc.framework created in it. Files like, VoxeetConferenceKit.framework, VoxeetSDK.framework, Kingfisher.framework are missing. How can I solve this?

**Comment by Taylorsuk** [comment]
@abhibly Sorry for the late reply. I didn't ever get this sorted. Have you managed to make any headway?
