### ISSUE TITLE
[Docs] Deeplinked pages stay highlighted in navigation even when navigating away

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#200]
If you open a page directly via the URL like https://capacitor.ionicframework.com/docs/basics/opening-native-projects, this page stays highlighted in the navigation even when you navigate to another page.

![image](https://user-images.githubusercontent.com/183673/36804787-da633d54-1cbb-11e8-8357-d42f37504790.png)

**Comment by janpio** [comment]
Problem is still present, but sometimes when clicking around now the whole page reloads visibly and then the problem is gone.

**Comment by jcesarmobile** [comment]
this doesn't happen on current docs site

**Comment by janpio** [comment]
Correct, replaced by #1665 🙈
