### ISSUE TITLE
iOS Keyboard should apply Dark style if dark mode is enabled

### ISSUE THREAD

**Issue by AVatch** [ionic-team/capacitor#2007]
Description of the problem:
Currently you can set a dark preference for iOS keyboard in a config file, however a user can change their dark mode preference and there is no way to update the configuration programmatically to either ignore or reflect the new user dark mode preference. 

Affected platform
- [ ] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

Capacitor version:

node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
Latest docs have not been redeployed yet, but there is a new `setStyle` function in keyboard plugin now that you can use to change the style at run time.

The only apps with dark style I've tested are all Apple apps, but looks like all of them show the dark keyboard, so yeah, could be a good idea to do the same.

**Comment by piotrblasiak** [comment]
I think this should be the responsibility of the developer - I might or might not choose to set my app to dark mode when the phone is in dark mode.

**Comment by AVatch** [comment]
The `setStyle` function does exactly what I would expect - thanks for pointing that out before updating the docs. I'll close this as it is not an issue.

**Comment by piotrblasiak** [comment]
It seems like the setStyle does not work?

`Plugins.Keyboard.setStyle(darkMode ? "dark" : "light");`

doesn´t do anything...

**Comment by piotrblasiak** [comment]
Ok, nevermind - did some digging and apparently it´s supposed to be setStyle({style: "DARK") which is weird, because that is not what you put in the config file to make the keyboard dark.

**Comment by AVatch** [comment]
You should just import `StatusBarStyle` from `@capacitor/core` and use the values from there rather than using the strings.

**Comment by jcesarmobile** [comment]
It’s KeyboardStyle, StatusbarStyle is for status bar. But doesn’t look like he is using typescript

**Comment by piotrblasiak** [comment]
ah there we go. Thanks.

**Comment by srgustafson8** [comment]
I appreciate this is a long dead issue - but should the default not be to follow the system theme with an override available? I personally would expect the native keyboard to follow the native theme by default.

**Comment by jcesarmobile** [comment]
Next release of keyboard plugin will work like that, was changed last week.

please, don’t comment on old issues
