### ISSUE TITLE
Maybe more help question than bug, but can't project "can't load resources"

### ISSUE THREAD

**Issue by willnix86** [ionic-team/capacitor#2008]
Description of the problem:

Affected platform
- [X] Android
- [X] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

Capacitor version:
Migrating from Cordova to Capacitor

node version :v10.16.0

npm version: 6.11.3

CocoaPods version: 1.7.2

Followed the steps to migrate my cordova project to capacitor - when I run the app, it fails with the following message:

````
[error] - {"src":"dojoLoader","info":["//JS/main.js",{"isTrusted":true}],"line":2,"column":387,"sourceURL":"capacitor://localhost/arcGIS/dojo/dojo.js"}
````

If I open Safari devtools and inspect the app, I see the following:

````
[Error] Failed to load resource: The file “angular-route.min.js.map” couldn’t be opened because there is no such file.
[Error] Failed to load resource: The file “dojo.js.map” couldn’t be opened because there is no such file.
[Error] Failed to load resource: The file “angular-touch.min.js.map” couldn’t be opened because there is no such file.
[Error] Failed to load resource: The file “angular.min.js.map” couldn’t be opened because there is no such file.
````

What's odd is that in the network tab, I can previous each of those files above that have failed to load.

Also, I inspect the network requests, I see that some files are being fetched here:  capacitor://localhost/libs/angular.min.js 

while one or two are fetched here: capacitor://JS/main.js

The folder 'JS' is in the same root 'www' folder as 'libs' and others that are fetched fine.

Any thoughts?

**Comment by jcesarmobile** [comment]
can you provide a sample app?

looks like a problem in your end.

**Comment by jcesarmobile** [comment]
closing since there was no response
