### ISSUE TITLE
CapacitorSplashScreen causing redirect to file:// protocol in electron after 4500ms

### ISSUE THREAD

**Issue by carlblock** [ionic-team/capacitor#2011]
I'm running a electron app pointed to a local dev server `http://127.0.0.1:8080` with webpack-dev-server. Unfortunately if I have the splash screen enabled in electron I get redirected back to electrons static files at the `file://` protocol. This breaks the autoreloading and HMR of webpack.

After inspecting the SplashScreen code I don't find any options for changing what URL the SplashScreen opens after 4500ms. But now I've disabled the SplashScreen instead.

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

I assume this section of `@capacitor/electron/index.js` is causing the redirect.

```js
    this.splashWindow.loadURL(`data:text/html;charset=UTF-8,${splashHtml}`, {baseURLForDataURL: `file://${rootPath}/splash_assets/`});

    this.splashWindow.webContents.on('dom-ready', async () => {
      this.splashWindow.show();
      setTimeout(async () => {
        if (inject) {
          this.mainWindowRef.loadURL(await injectCapacitor(`file://${rootPath}/app/index.html`), {baseURLForDataURL: `file://${rootPath}/app/`});
        } else {
          this.mainWindowRef.loadURL(`file://${rootPath}/app/index.html`);
        }
      }, 4500);
    });
```

Capacitor version: 1.2.1

Steps to reproduce:
Install the normal boilerplate from the cli and point the mainWindow.loadUrl in electron to a http protocol url instead of `file://`

**Comment by bcallaghan-fri** [comment]
The project I'm working on just happens to use /app/index.html as the page to load all the time, but I agree that this is a bug. Capacitor should not dictate what web page is loaded, especially from the SplashScreen plugin. Loading the main window should be left up to the developer.

**Comment by jcesarmobile** [comment]
We have an issue for refactoring splash screen, so I'll add this information there and close
https://github.com/ionic-team/capacitor/issues/1529
