### ISSUE TITLE
Android plugin documentation missing details for handling Intent for Result

### ISSUE THREAD

**Issue by domoosterloo** [ionic-team/capacitor#2019]
Documentation in https://capacitor.ionicframework.com/docs/plugins/android/ section Intents with result, missing the fact you need to register your requestCode in the plugin class @NativePlugin annotation for handleOnActivityResult to be called.

Using the example in the documentation:
static final int REQUEST_IMAGE_PICK = 12345;
Intent intent = new Intent(Intent.ACTION_PICK);
intent.setType("image/*");
startActivityForResult(call, intent, REQUEST_IMAGE_PICK);

For this to work the plugin class would also require:
@NativePlugin(
        requestCodes={MyPlugin.REQUEST_IMAGE_PICK}
)
public class MyPlugin extends Plugin {
....

**Comment by LukaszGrela** [comment]
Relates to https://github.com/ionic-team/capacitor/issues/1983
