### ISSUE TITLE
bug: Android Not Finding Console Plugin

### ISSUE THREAD

**Issue by brandonhudson** [ionic-team/capacitor#2021]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/cli 1.1.1

  @capacitor/core 1.1.1

  @capacitor/android 1.2.1

  @capacitor/ios 1.1.1


[success] Android looking great! 👌
  Found 2 Capacitor plugins for ios:
    capacitor-fingerprint-auth (0.0.2)
    phonegap-plugin-barcodescanner (8.1.0)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Capacitor on Android keep displaying an error attempting to load the `Console` plugin:
```
I/Capacitor/Console: File: capacitor-runtime.js - Line 84 - Msg: onscript loading complete
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: -1, pluginId: Console, methodName: log
E/Capacitor: unable to find plugin : Console
D/Capacitor: Sending plugin error: {"save":false,"callbackId":"-1","pluginId":"Console","methodName":"log","success":false,"error":{"message":"unable to find plugin : Console"}}
D/Capacitor/Plugin/App: Firing restored result
```
Occuring inside Android emulator - API v28, Pie 9.0

## Expected Behavior
Log messages appear inside the console, but the error should not be thrown.

## Other Technical Details

`npm --version` output: 6.7.0

`node --version` output: v11.10.0

`pod --version` output (iOS issues only): N/A

**Comment by jcesarmobile** [comment]
Update @capacitor/core to the same version as @capacitor/android
