### ISSUE TITLE
bug: Capacitor Attempting Multiple Injections On Android

### ISSUE THREAD

**Issue by brandonhudson** [ionic-team/capacitor#2022]
# Bug Report
Capacitor is attempting multiple javascript injections on Android. This is occuring when an app references separate HTML templates after the app is loaded in `index.html`. In our case, we load HTML templates dynamically using AngularJS via a UI router. Each time one of these resources is requested, Capacitor attempts to reinject the javascript, but fails because these files do not have `<head>` tags in them. This error is occuring at the following line:

https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java#L245

Example:
```
D/Capacitor: Handling local request: http://localhost/assets/templates/views/_home.html
E/Capacitor: Unable to inject Capacitor, Plugins won't work
```

To resolve this, I was able to add the following check at line 245:
```
if (path.equals("/index.html")) {
        responseStream = jsInjector.getInjectedStream(responseStream);
}
````

This ensures that the injection only occurs on the base `index.html` page. Unsure if this is a proper universal solution, as this only works for cases where the app is intended to be run as a single page application.

A better solution would be to check if the javascript has been previously injected. If this is the case, and the HTML file requested does not have a header tag, downgrade from an error to a warning or info log.

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/cli 1.1.1

  @capacitor/android 1.2.1

  @capacitor/core 1.1.1

  @capacitor/ios 1.1.1


[success] Android looking great! 👌
  Found 2 Capacitor plugins for ios:
    capacitor-fingerprint-auth (0.0.2)
    phonegap-plugin-barcodescanner (8.1.0)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

See above comments.

## Expected Behavior

Capacitor should not error each time the JS is not injected. It should also not attempt to inject multiple times (if possible)

## Other Technical Details

`npm --version` output: 

`node --version` output:

`pod --version` output (iOS issues only): N/A

**Comment by jcesarmobile** [comment]
But what if the app navigates to a different .html file? then what you propose won't work.

Capacitor should be able to inject itself to any html file where navigates to, but it's hard to know if the app is navigating or just using a xhr/fetch call to a file.

For now I'm ok changing the error to a warning to not scare people.

**Comment by brandonhudson** [comment]
Agree with all the points you raise. Just brainstorming, but an option could be to have an (optional) whitelist in the Capacitor configuration. That would at least enable it’s behavior in a more flexible, user-defined manner.
