### ISSUE TITLE
[Docs] Capacitor Android Plugin Guide > Export To Capacitor clarification

### ISSUE THREAD

**Issue by ingageco** [ionic-team/capacitor#2024]
In the docs, on the Capacitor Android Plugin Guide page, under Export To Capacitor: 

Suggestion: It should be more clear that adding the plugin to your MainActivity is a change made in the app where you use the plugin, not a part of the plugin development. It took me a while to find the context of this as someone trying to learn the ropes on building plugins for Capacitor. I think this change could help future contributors.

**Comment by LukaszGrela** [comment]
Relates to https://github.com/ionic-team/capacitor/issues/1983
