### ISSUE TITLE
feat: Xcode 11 / MacOS Catalina

### ISSUE THREAD

**Issue by adrynov** [ionic-team/capacitor#2025]
# Feature Request

Support for XCode 11 and Mac OS Catalina 

## Describe the Feature Request

Make sure that Capacitor apps build and run successfully with the new XCode/OS updates.

**Comment by jcesarmobile** [comment]
Have you found any issue? I’ve been using Xcode 11 since it was a beta without any problem. Only tested a few times in Catalina and didn’t see any problem neither

**Comment by bryplano** [comment]
Agreed. I have not had any issue building or running Capacitor apps in Xcode 11. Catalina does not make any difference either from what I've seen.

If you believe there is something specific to your environment causing a problem, as @jcesarmobile said, you'll need to provide an error message and sample application (the latter if possible).

**Comment by agonzalezjr** [comment]
I just tried with GA Xcode 11.1, and things are working without issues there as well.

**Comment by agonzalezjr** [comment]
Could these warnings be all cleaned up though?

![xcode-11 1-warnings](https://user-images.githubusercontent.com/8965941/66355053-cee20180-e934-11e9-84c4-409764841083.png)

**Comment by jcesarmobile** [comment]
Going to close, if you find some issue, please report it with more details.
