### ISSUE TITLE
Keyboard.show not implemented?

### ISSUE THREAD

**Issue by piotrblasiak** [ionic-team/capacitor#2034]
The docs say it´s in alpha and may have bugs, but when I run it the error says:

⚡️  To Native ->  Keyboard show 121613390
ERROR MESSAGE:  {"message":"not implemented","errorMessage":""}

Does this mean it´s not implemented at all, or am I calling it wrong? (Plugins.Keyboard.show()).

**Comment by jcesarmobile** [comment]
where does it say it's in alpha? we launched the final in May.

`Plugins.Keyboard.show()` is Android only, on iOS it's not technically possible to show the keyboard, only possible if you focus the keyboard on an input field (calling .focus() on that input field)

**Comment by piotrblasiak** [comment]
Ok, and apparently .focus() will not work unless you have touched the screen at the same time. It will focus but keyboard will not show - so I was trying to make a workaround by checking if keyboard had showed when an element was focused on the site - otherwise show the keyboard. I guess that won´t be possible then.

The docs page with the alpha comment is at https://capacitor.ionicframework.com/docs/apis/keyboard#method-show-0

**Comment by jcesarmobile** [comment]
Focus should just work without touching, but if you are testing on iOS 13 it was broken there, we fixed it but it’s not released yet

**Comment by piotrblasiak** [comment]
Oh, that´s good to know - then I don´t have to try and do some workaround 😅. Thanks.

**Comment by jcesarmobile** [comment]
just tested with iPadOS 13.2 beta and keeps working, so going to close. Will be fixed in next Capacitor  release. Was fixed here https://github.com/ionic-team/capacitor/pull/1995
