### ISSUE TITLE
bug: mailto: links make app crash

### ISSUE THREAD

**Issue by piotrblasiak** [ionic-team/capacitor#2035]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/cli 1.2.1

  @capacitor/core 1.2.1

  @capacitor/android 1.2.1

  @capacitor/ios 1.2.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When calling Plugins.App.openUrl({url: "mailto:whatever@hey.com"}) or Plugins.Browser.open({url: "mailto:whatever@hey.com"}) the app crashes.

## Expected Behavior

The system mail app should open

**Comment by jcesarmobile** [comment]
I can reproduce on Browser plugin, Browser can only open http or https links, should return an error when a different scheme is used.

Can't reproduce on App plugin:
what's the error?
iOS version?
Device?
Xcode version?

**Comment by piotrblasiak** [comment]
Sorry - just the Browser plugin makes the app crash. None of them will work with mailto:, however.

**Comment by jcesarmobile** [comment]
The App one opens mail app for me as expected. Do you have it configured with a mail address? Do you see some message on Xcode? Does canOpen return true for mailto?

**Comment by piotrblasiak** [comment]
Plugins.App.openUrl({url: "mailto:test@test.com"}) works - sorry must have done something else wrong then, thanks!

**Comment by jcesarmobile** [comment]
ok, thanks, will fix the browser plugin to not crash when it doesn't like the scheme of the url

**Comment by douglasrehem** [comment]
Hi, It's not working for me. I'm getting the follow error message in XCode 

`App[28183:2883294] [default] Failed to open URL mailto:contact@visitlog.app: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=247, _LSFunction=-[_LSDOpenClient openURL:options:completionHandler:]}`

My code is:
`Plugins.App.openUrl({ url: 'mailto:contact@visitlog.app' });`

My Capacitor dependencies are:
    "@capacitor/android": "^2.4.0",
    "@capacitor/core": "2.4.0",
    "@capacitor/ios": "^2.4.0",

**Comment by idesignpixels** [comment]
@douglasrehem Did you find a solution i get the the same problem

**Comment by sanderschnydrig** [comment]
This is still happening on Android. On iOS nothing happens at all.
