### ISSUE TITLE
bug:  Latest version of capacitor breaks the application header and allows the status bar to overlay it.

### ISSUE THREAD

**Issue by cambronjay** [ionic-team/capacitor#2036]
# Bug Report

## Capacitor Version

`npx cap doctor` output: 1.2.1

## Affected Platform(s)

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Status bar overlays ionic header/toolbar in version 1.2.1 of capacitor. Capacitor 1.1.1 does not have this issue.

## Expected Behavior
The ionic header/toolbar will have correct padding under the status bar on iphone 11 and 10. 

## Sample Code or Sample Application Repo
use the stencil conference app https://github.com/ionic-team/ionic-stencil-conference-app

## Reproduction Steps

Build the app and sync with capacitor then run it on an iphone 11 simulator. You will notice the header/toolbar issue.  I tested a build using the same repo with capacitor 1.1.1 and there was no issue. 

## Other Technical Details
I am using Xcode 11.1

`npm --version` output: 10.16.0

`node --version` output: 6.9.0

`pod --version` output (iOS issues only): 1.8.3

## Other Information
I don't know what changed in capacitor but it breaks the ionic header/toolbar and status bar now.

**Comment by Flowrome** [comment]
Also for me it's not working

![image](https://user-images.githubusercontent.com/5570880/66832498-5396d600-ef5a-11e9-9eba-35bc4af6fca8.png)

**Comment by Flowrome** [comment]
It seems that there is an error on Statusbar implementation
![image](https://user-images.githubusercontent.com/5570880/66849027-746d2480-ef76-11e9-88de-53a19fb7b4a3.png)

**Comment by PR1YANKPAT3L** [comment]
[setBackgroundColor](https://github.com/ionic-team/capacitor/blob/e374f2eeab91469aa402ff705655b1dae472706f/ios/Capacitor/Capacitor/Plugins/StatusBar.swift#L35) is not implemented yet.

**Comment by cambronjay** [comment]
Latest version of Capacitor seems to fix this issue.

**Comment by giorgiogalassi** [comment]
Still broke after updating @capacitor/cli - core - android & iOS to 1.0.4.
