### ISSUE TITLE
feat: Add "iosScheme": "https" support to capacitor.config.json

### ISSUE THREAD

**Issue by aleleba** [ionic-team/capacitor#2037]
Version of capacitor:

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/cli 1.2.1

  @capacitor/android 1.2.1

  @capacitor/ios 1.2.1

  @capacitor/core 1.2.1

# Feature Request
Add "iosScheme": "https" support to capacitor.config.json

## Describe the Feature Request
When use "iosScheme": "https"  in capacitor.config.json on ios it use capacitor as iosScheme. It will be possible to use https as iosScheme.

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
When use "iosScheme": "https"  in capacitor.config.json on ios it use capacitor as iosScheme. It will be possible to use https as iosScheme.

**Comment by jcesarmobile** [comment]
It's not possible

**Comment by aleleba** [comment]
Thank you @jcesarmobile 😁
