### ISSUE TITLE
bug: Camera plugin doesn't work on Firefox 71.0b8 (edited because I tried it on 71.0b8 on November 8)

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/capacitor#2038]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.2.1

  @capacitor/core 1.2.1

  @capacitor/ios 1.2.1

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Electron
- [ X ] Web

## Current Behavior

When trying to take a picture it doesn't show anything on the screen when using the Firefox browser. 

## Expected Behavior

It should show video images on the screen.

## Sample Code or Sample Application Repo
            const image = await Camera.getPhoto({
                quality: 100,
                allowEditing: false,
                resultType: CameraResultType.DataUrl,
                source: CameraSource.Prompt
            });
            this.imgUrl = image.dataUrl;

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by bryplano** [comment]
@Bandito11 - have you tried this in the actual release of Firefox 70? Do you have this issue in other browsers? A sample application and repro steps would go a long way here.

**Comment by Bandito11** [comment]
https://millefollium.firebaseapp.com
https://github.com/Bandito11/millefollium


I did tried it on Firefox 70 (I am on Nightly so I am currently testing on FF71)

Thanks!
Esteban Morales

________________________________

**Comment by hscheuerle** [comment]
Having this issue with ff v68 v69 v70. An Ionic/Angular/Capacitor blank app that follows the tutorial has this issue on my device. The Camera is not the issue, but the video stream has no picture.

**Comment by hscheuerle** [comment]
Noticing the video steam is working. But the animation bringing z-index of the video component to 0 is remaining -1 in firefox

**Comment by hscheuerle** [comment]
https://github.com/ionic-team/pwa-elements/pull/41

**Comment by Bandito11** [comment]
I'll try this after I go home.

Thanks!
Esteban Morales

________________________________

**Comment by jcesarmobile** [comment]
This is a pwa-elements bug, will be fixed there
