### ISSUE TITLE
bug: cordova-plugin-ionic is blocking device ready event

### ISSUE THREAD

**Issue by terranmarine** [ionic-team/capacitor#2039]
# Bug Report
I am migrating our app from cordova to capacitor. Generally we managed to limit the cordova plugins to 3:
```  Found 3 Cordova plugins for android
    cordova-plugin-ionic (5.4.4)
    cordova-plugin-whitelist (1.3.4)
    phonegap-plugin-barcodescanner (8.1.0)
```
Using `cordova-plugin-ionic (5.4.4)` is messing up deviceready event and app cannot be started. 

When inspecting the app in Google remote devices the following error is shown.
`Uncaught (in promise) String resource ID #0x0`. Similar issue should have been resolved in the plugin repo `https://github.com/ionic-team/cordova-plugin-ionic/issues/223`. 

Once the plugin is removed the app start functioning as normal.

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/cli 1.2.1

  @capacitor/core 1.2.1

  @capacitor/ios 1.2.1

  @capacitor/android 1.2.1

## Affected Platform(s)
- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Application cannot be roaded.
## Expected Behavior
Application should be launched ans normal. No incompatible plugins are being used.

## Reproduction Steps
Inside an capacitor project run in terminal: 

`cordova plugin add cordova-plugin-ionic --save --variable APP_ID="abcd1234" --variable CHANNEL_NAME="Master" --variable UPDATE_METHOD="background"`

`ionic build` or `npm run build`

`npx cap sync android`

`npx cap open android`

Run app in simulator or on device. App is not loaded correctly.

## Other Technical Details

`npm --version` output:
6.9.0
`node --version` output:
v10.16.3

**Comment by jcesarmobile** [comment]
Capacitor doesn't support plugin variables

Ionic CLI added a command to enable deploy on Capacitor apps `ionic deploy add`, but as you already added it as cordova plugin it will probably cause issues. You can also check the `strings.xml` file in the cordova project and copy the values to capacitor's `strings.xml`

**Comment by jcesarmobile** [comment]
not deploy with the CLI.
The cordova plugin variables are used to write values to `strings.xml` and `Info.plis`, that's just not possible with Capacitor, but Ionic CLI added a "workaround", the `ionic deploy add` command, that will write those values. You still need the plugin, but as you have installed it as a cordova plugin, the deploy command will probably think you already integrated deploy and won't do anything.

**Comment by terranmarine** [comment]
I understand now. I just ran `ionic deploy add`. 

Thank you for your time!

**Comment by maximnara** [comment]
I've just remove old plugin `cordova-plugin-ionic` and problem gone
