### ISSUE TITLE
bug: Unable to access the camera from webview on IOS platform.

### ISSUE THREAD

**Issue by aleleba** [ionic-team/capacitor#2040]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/cli 1.2.1

  @capacitor/android 1.2.1

  @capacitor/ios 1.2.1

  @capacitor/core 1.2.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Unable to access the camera from webview on IOS platform. 
I currently use the library "@ zxing / library": "^ 0.14.2" to scan QR codes and IOS does not give the permissions to access the camera on the webview

## Expected Behavior

I would like to have access to the camera in webview in IOS, in order to use the library "@ zxing / library": "^ 0.14.2".

## Other Technical Details

`npm --version` output:
6.9.0

`node --version` output:
v10.16.3

`pod --version` output (iOS issues only):
1.8.4

**Comment by jcesarmobile** [comment]
This is a WKWebView limitation, Apple doesn't allow to access the camera by using getUserMedia (which zxing internally uses). 
See the related zxing issue https://github.com/zxing-js/library/issues/15
