### ISSUE TITLE
Can any one explain how to use PhotoPlugin in the app

### ISSUE THREAD

**Issue by parthnayak7448** [ionic-team/capacitor#2047]
Try to use the plugin but it is not working. If anyone can give example here for IOS and android it will be great help

**Comment by jcesarmobile** [comment]
The plugin is not implemented for Android, Web or Electron, that's why it's not documented. 
For questions better use the [forum](https://forum.ionicframework.com/) or [slack](https://getcapacitor.herokuapp.com/)
