### ISSUE TITLE
feat: Get keyboard size

### ISSUE THREAD

**Issue by piotrblasiak** [ionic-team/capacitor#2051]
# Feature Request

## Describe the Feature Request

Currently, the Keyboard plugin has resize modes that will resize the body of the page or the entire webview, but would it be possible to just get the size of the keyboard so that you can handle this yourself - if you for example would like to have the keyboard cover parts of your app for a nice shine-through etc?

I tried working around this by setting resize to "ionic" and doing something like this:

`const ionApp = document.createElement("ion-app");
		const resizeObserver = new ResizeObserver(props =>
			console.log("Resize", props)
		);
		resizeObserver.observe(ionApp);
		document.body.appendChild(ionApp);`

But that didn´t do much unfortunately.

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

**Comment by jcesarmobile** [comment]
The keyboard events (keyboardWillShow, keyboardDidShow)  provide the height of the keyboard

**Comment by piotrblasiak** [comment]
Oh, sorry about that.
