### ISSUE TITLE
capacitor plugin:generate produces a plugin that doesn't work on android

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/capacitor#2052]
# Bug Report

Newly created capacitor plugin doesn't work on  android. Instead it results in vague error when `echo` is invoked:

<img width="739" alt="Screen Shot 2019-10-15 at 12 50 08 AM" src="https://user-images.githubusercontent.com/39473/66801407-f9a8f880-eee6-11e9-9bb4-a5935ca7fa61.png">

It seems to work well on ios.

## Capacitor Version
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/cli 1.2.1
  @capacitor/android 1.2.1
  @capacitor/core 1.2.1

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
'echo' method in capacitor plugin results in error

## Sample Code or Sample Application Repo
Sample code is barebones.  A new ionic/capacitor/tabs app and a newly generated plugin.

sample app: https://github.com/josh-m-sharpe/capApp
sample plugin: https://github.com/josh-m-sharpe/foo-bar

### app generated with these commands (more or less):
```
ionic start capApp tabs --capacitor
npx cap init
ionic integrations enable capacitor
ionic build
npx cap add android
```
### plugin generated with:
capacitor plugin:generate

### plugin added with:
yarn add https://github.com/josh-m-sharpe/foo-bar.git

### plugin usage:
https://github.com/josh-m-sharpe/capApp/blob/master/src/app/tab1/tab1.page.ts#L3-L18

### Reproduction steps
- git clone https://github.com/josh-m-sharpe/capApp.git
- cd capApp
- yarn install
- ionic build
- npx cap sync android
- npx ionic cap run android --livereload --consolelogs
- run app
- click on "click"
- see errors in android studio 

`npm --version` output:
6.11.3
`node --version` output:
v12.11.1

**Comment by jcesarmobile** [comment]
I don’t see the plugin registered in MainActivity.java

https://github.com/josh-m-sharpe/capApp/blob/master/android/app/src/main/java/com/example/app/MainActivity.java
