### ISSUE TITLE
TS constructor in native plugin

### ISSUE THREAD

**Issue by parthibd** [ionic-team/capacitor#2053]
I am unable to find the dock that explains how to call a TS constructor on a native plugin . Can someone explain it to me ?

**Comment by jcesarmobile** [comment]
Can you be more specific?

**Comment by parthibd** [comment]
Okay . Say I am building a native plugin for Android .  I want to call methods foo() from js level . I understand how the call is made and how to extract the params on Java side . What I want to is that how I call a constructor on TS eg new Foo() so that it invokes the Java said constructor Bar() ?

**Comment by jcesarmobile** [comment]
Sorry, still not clear. Looks like a javascript/typescript question and not a real issue, so going to close. 
You can ask on [slack](https://getcapacitor.herokuapp.com/) or the [forums](https://forum.ionicframework.com/)
