### ISSUE TITLE
bug: WKWebView not allowing non-http redirects

### ISSUE THREAD

**Issue by austin43** [ionic-team/capacitor#2055]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.1.1

  @capacitor/ios 1.1.1

  @capacitor/core 1.1.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I'm attempting to use the auth0-spa-js library to login on the iOS platform.  Upon first load (or refresh in browser cases) the app runs the following js: 
```
loginWithRedirect({
    appState: { targetUrl: window.location.pathname }
})
```
with window.location.pathname being `capacitor://localhost`.

However, when I successfully login and attempt to redirect to a custom scheme (capacitor://localhost) the web view fails to navigate to the url.
```
⚡️  WebView failed provisional navigation   
⚡️  Error: Redirection to URL with a scheme that is not HTTP(S)   
```

## Expected Behavior

Expect WKWebView to redirect to the app URL after successful login and continue loading the app.

## Reproduction Steps

Call auth0.loginWithRedirect with a redirect_uri of `capacitor://localhost` and sign in.

## Other Technical Details

`npm --version` output:
6.9.0
`node --version` output:
v10.16.3
`pod --version` output (iOS issues only):
1.8.3
## Other Information

//capacitor.config.json
```
{
  "appId": "com.appname",
  "appName": "app",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "build",
  "server": {
    "allowNavigation": [
      "appname.auth0.com"
    ]
  }
}
```

**Comment by jcesarmobile** [comment]
How are you doing the redirection? `window.location.href = 'capacitor://localhost';` seems to work fine

**Comment by austin43** [comment]
@jcesarmobile I'm using the auth0-spa-js react quickstart.  I should have specified I'm using @ionic/react as well.  https://auth0.com/docs/quickstart/spa/react#install-the-auth0-react-wrapper.  

This wrapper handles loading the login page with PKCE flow, then redirects back to the redirect_uri I pass it (in this case capacitor://localhost).  

`window.location.href = 'capacitor://localhost';` throws my app into an infinite loop of loading my App component for what it's worth.  I'm guessing that may be a pointer to the core problem.

**Comment by jcesarmobile** [comment]
Might be framework related, can you provide a sample app?

**Comment by austin43** [comment]
@jcesarmobile I put together this sample app which points to a sample auth0 endpoint I set up.  It contains the flow we're using without apollo dependencies in between.  It may hang on your first login, but upon re-running the app you will be logged in and it will throw the error.

**Comment by jcesarmobile** [comment]
I see the error message now, if Apple doesn't allow webview redirects to schemes I don't think there is much we can do about it. You can try reporting it to Apple.

Anyway, allowNavigation should be used to navigate to urls you control, not to external sites such as auth providers. I think a better approach is to use Browser plugin to load the auth site, make it redirect to a custom scheme, and then use App plugin to get the url that launched the app, but of course requires more work.
A workaround can be to redirect to your own site that gets the token and triggers a javascript redirect as that seems to work fine.

**Comment by austin43** [comment]
Ah bummer, I will try a more customized browser plugin approach.  Thanks for the hard work on ionic and on my issue 😄

**Comment by austin43** [comment]
@jcesarmobile Jumping back in here.  The key problem with using the Browser plugin to load the auth site is with how auth0-spa-js is structured.  The loginWithRedirect method is pretty self contained: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L214.  The Browser plugin seems pretty simple, and it doesn't appear there's a way to capture url navigation and use SafariViewController short of modifying the auth0-spa-js library to return a URL I can use.

Could you elaborate on "redirect to your own site"?  Is this a middleman of sorts to get around the non-http redirects issue in wkwebview?

**Comment by austin43** [comment]
Update: Working on a PR at the moment to enable URL retrieval which will make this possible. 
 https://github.com/auth0/auth0-spa-js/issues/273

**Comment by jcesarmobile** [comment]
If using Browser plugin you can redirect to an app scheme you have registered (capacitor:// by default, but should be changed to use your own), that will call `appUrlOpen` from App plugin and then you can close the browser with close function.

By "redirect to your own site", yeah, I mean you have a "proxy" website that you use as redirect page in the auth service, it takes the auth token and redirects with javascript as javascript redirects work.

Closing the issue since if Apple doesn't allow the redirect, we can't do anything about it.

**Comment by iZootoNotifcation** [comment]
We are implemented the WKWebview in our application but redirect url is not working ,What are we do?

**Comment by AKoulabukhov** [comment]
@iZootoNotifcation, handle redirect in `WKWebView` and if scheme other from `http(s)` redirect user to safari with `UIApplication.shared.open(url:..)`

**Comment by nilshcp15** [comment]
Does the browser plugin approach worked as expected?
Any limitations?

**Comment by bmadhan90** [comment]
Hi all,

Any one solve the issue, I’m also stuck in a similar issue.
I’m using ionic + Cordova urlscheme with angular-oidc-auth-client library.

For me working in android. IOS after login not redirecting to app. Second time click blank page displays.

**Comment by Jthornburg1** [comment]
@bmadhan90 did you ever come up with a solution for this? I'm experiencing something similar. I log into the app, tap the button to load a request into a wkwebView, the expected screen loads. After dismissing the wkWebview and tapping the button to load it again with the same request, it just hangs. This is only in iOS 15 and the behavior resets after relaunching the app.
