### ISSUE TITLE
Android dependency 'com.android.support:customtabs' has different version for the compile

### ISSUE THREAD

**Issue by edy-ap** [ionic-team/capacitor#206]
Error:Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:customtabs' has different version for the compile (26.1.0) and runtime (27.0.2) classpath. You should manually set the same version via DependencyResolution

**Comment by jcesarmobile** [comment]
Which plugin are you using?
Right now Capacitor with take the default version from the plugin.xml and not the one from config.xml/package.json if you have one set.
Capacitor uses 26.1.0 version appcompat. You can change it to 27.0.2 in the app build.gradle, but using 27.x.x will also require to compile using SDK 27.

@mlynch we should make that configurable somehow?

**Comment by edy-ap** [comment]
I use onesignal plugin

**Comment by edy-ap** [comment]
I already solved it, it was a problem of versions

**Comment by mlynch** [comment]
Was it something you did or we did?

**Comment by devotebest** [comment]
@edy-ap  how did you solve?

**Comment by jimUpdate** [comment]
+1 @edy-ap how did you solve?
