### ISSUE TITLE
bug: compiling with cordova-plugin-iosrtc 

### ISSUE THREAD

**Issue by DiegoRodriguez93** [ionic-team/capacitor#2063]
i've been working on project with apirtc for videocall, i had problems when i added cordova-plugin-iosrtc and compiling in xcode
![20191017_111033](https://user-images.githubusercontent.com/40219882/67016975-6848aa80-f0cf-11e9-9ceb-168e06dbc422.jpg)

**Comment by carter-dewey** [comment]
Ever get this to compile Diego, I similarly need to use cordova-plugin-iosrtc with capacitor but it fails to build in xcode. Looks  mostly like swift compile errors to me.

**Comment by jcesarmobile** [comment]
the plugin has a hook that makes a lot of changes on the native project, since Capacitor doesn't support hooks, it won't work.
Closing as "knonw incompatible cordova plugin"

**Comment by rwwagner90** [comment]
If this isn't supported in capacitor, there is no way to use `getUserMedia` in capacitor, correct?

**Comment by danielehrhardt** [comment]
The Docs have been updated. The Plugin should work now with Capacitor:
https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/docs/Building.md

**Comment by jcesarmobile** [comment]
adding workaround label as it seems to work, but looks like it has some issues (I tried their sample app and in Cordova it shows two camera feeds, one full screen and the other a small window, and in Capacitor only the small window shows the feed, but not the full screen)
