### ISSUE TITLE
Can't remove one local notification

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#2064]
I use local notifications quite frequently throughout out my Ionic/Capacitor app, and often need to remove one of the pending notifications.

The docs specify you can pass all the pending notifications for cancellation, suing the cancel method.

Is it possible to cancel just one of the pending notifications?

**Comment by jcesarmobile** [comment]
cancel takes an array, you can pass all the pending or just a single one, as long as it's in an array should be ok.

**Comment by frederikheld** [comment]
In case someone is looking for a code example... this is the way to do it:
https://stackoverflow.com/a/70591014/10043870
