### ISSUE TITLE
bug: AndroidManifest.xml gets rewritten to defaults every build

### ISSUE THREAD

**Issue by dwasyluk** [ionic-team/capacitor#2065]
Using capacitor to build an Android app the file android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml keeps getting changed to include the default permissions on every build. I am not sure how to prevent this.

Meanwhile android/src/main/AndroidManifest.xml has the correct settings. How do these two files relate and why is the former continually, incorrectly regenerated on each build?

**Comment by dwasyluk** [comment]
Here is the rewritten AndroidManifest.xml, I am trying to remove `WRITE_EXTERNAL_STORAGE` but the build process always puts it back.

Before build:
```
<?xml version='1.0' encoding='utf-8'?>
<manifest package="capacitor.android.plugins"
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:amazon="http://schemas.amazon.com/apk/res/android">
<application>
<activity android:name="com.google.zxing.client.android.CaptureActivity" android:clearTaskOnLaunch="true" android:configChanges="orientation|keyboardHidden|screenSize" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:windowSoftInputMode="stateAlwaysHidden" android:exported="false"/>
<activity android:name="com.google.zxing.client.android.encode.EncodeActivity" android:label="Share"/>
</application>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.FLASHLIGHT"/>
<uses-feature android:name="android.hardware.camera" android:required="true"/>
</manifest>
```

after build

```
<?xml version='1.0' encoding='utf-8'?>
<manifest package="capacitor.android.plugins"
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:amazon="http://schemas.amazon.com/apk/res/android">
<application>
<activity android:name="com.google.zxing.client.android.CaptureActivity" android:clearTaskOnLaunch="true" android:configChanges="orientation|keyboardHidden|screenSize" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:windowSoftInputMode="stateAlwaysHidden" android:exported="false"/>
<activity android:name="com.google.zxing.client.android.encode.EncodeActivity" android:label="Share"/>
</application>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.FLASHLIGHT"/>
<uses-feature android:name="android.hardware.camera" android:required="true"/>
</manifest>
```

What's goin on here?

**Comment by jcesarmobile** [comment]
android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml is generated based on the cordova plugins you have installed, some of your plugins require that and it’s adding it to the project. You should never edit capacitor-cordova-android-plugins project, it gets generated every time you run update/sync.

If you want to remove a permission from a module, instead of manually deleting it, use android studio manifest merger features. By adding this to your apps AndroidManifest.xml you can make the generated manifest to not include the permission.

`<uses-permission
        android:name="android.permission. WRITE_EXTERNAL_STORAGE"
        tools:node="remove" />`


But have in mind that the plugin adding that permission might not work as expected.
