### ISSUE TITLE
Capacitor with third-party AndroidX library

### ISSUE THREAD

**Issue by Nasicus** [ionic-team/capacitor#2082]
Roughly said I have the following project:

- Out of the box app with create-react-app & typescript (`npx create-react-app my-app --typescript`)
- Added capacitor (`npm install --save @capacitor/core @capacitor/cli`)
- Initialized capacitor (`npx cap init`)
- Added Android (`npx cap add android`)
- Created a custom plugin (`npx @capacitor/cli plugin:generate`) 
- referenced this plugin in my `package.json` of the react app (`"capsal-msal-plugin": "file:capsal-msal-plugin"`)
- added the third-party library which uses androidx to the `build.gradle` file of my plugin, i.e.
 ```
dependencies {
    implementation 'com.microsoft.identity.client:msal:1.0.+'
}
```

Now when I try to build Android I get the following error:

```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-43:19 to override.
```
If you google this you quickly find, that his is an AndroidX issue:
https://stackoverflow.com/questions/51793345/android-material-and-appcompat-manifest-merger-failed

I tried various things (bascially all are from the SO thread above):
- Using Android Studio with the command `Refactor => Migrate To Android X` 
- enable jetifier in the `gradle.properties`

None of it worked, it just resulted in different errors.

So my question:
Did anyone ever manage to add a third-party library which uses AndroidX? If so can you please tell me how this can be achieved?

I pushed my sample project to this repository:
https://github.com/Nasicus/capsal

**Comment by jcesarmobile** [comment]
Android X can’t be used just for one dependency, it has to be used for al dependencies in all plugins and modules, including Capacitor itself, which doesn’t support it yet.

https://github.com/ionic-team/capacitor/issues/1937

**Comment by Nasicus** [comment]
@jcesarmobile I know it doesn't work yet. I hoped there is a workaround for it. Especially because I read something in https://github.com/ionic-team/capacitor/issues/1937#issuecomment-530901736

**Comment by PR1YANKPAT3L** [comment]
I have a PR #2045  submitted got AndroidX support. Maybe try it as a workaround?

**Comment by Nasicus** [comment]
Thanks @PR1YANKPAT3L is there an easy was of how to use your version? do I need to build it locally and stuff?

**Comment by PR1YANKPAT3L** [comment]
I simply referenced the repository locally. This is my current setup.

-- projects
---- capacitor (forked repo)
---- main-project (current project)

I ran from main-project the following: `npm i ../capacitor/android --save'.  Once installed, you can run: `npx cap sync`.
