### ISSUE TITLE
bug: Can't programmatically open keyboard on iOS 13.1.3

### ISSUE THREAD

**Issue by masimplo** [ionic-team/capacitor#2085]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Installed Dependencies:

  @capacitor/cli 1.2.1
  @capacitor/core 1.2.1
  @capacitor/android 1.2.1
  @capacitor/ios 1.2.1
    @byteowls/capacitor-oauth2 (1.0.1)
    capacitor-analytics (0.0.4)
    capacitor-fcm (0.1.0)
    cc.fovea.cordova.purchase (8.1.1)
    cordova-launch-review (3.1.1)
    cordova-plugin-appsflyer-sdk (4.4.22)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-call-number (1.0.1)
    cordova-plugin-camera (4.1.0)
    cordova-plugin-globalization (1.11.0)
    cordova-plugin-x-socialsharing (5.6.0)
    cordova-sms-plugin (1.0.0)
    cordova-sqlite-storage (3.4.0)
    es6-promise-plugin (4.2.2)
    skwas-cordova-plugin-datetimepicker (2.0.1)
```
## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

1. Add an ion-input on a page
2. Call focus on the input
```
@ViewChild('input') input: ElementRef<HTMLInputElement>;

ngAfterViewInit() {
    setTimeout(() => this.input.nativeElement.focus(), 500);
}
```
3. Run the app on an actual iPhone
4. Nothing happens. BUT if you switch to another app and come back to the your app, the input gets focus.

The same happens when calling setFocus on an ion-searchbar component.

## Expected Behavior

The input should get focus when focus() is called.

## Other Technical Details

`npm --version` output:
6.11.3
`node --version` output:
v10.16.1
`pod --version` output (iOS issues only):
1.8.3

**Comment by maxime-guyot** [comment]
I'have upgrade to capacitoor 1.3, focus element don't show the keyboard on ios13 🤔

**Comment by dabaaaz** [comment]
same same :/
