### ISSUE TITLE
feat: Add userAgent related properties to capacitor config.xml

### ISSUE THREAD

**Issue by gabceb** [ionic-team/capacitor#2088]
# Feature Request

Add userAgent related properties to capacitor config.xml

## Describe the Feature Request

Cordova's config.xml supports `AppendUserAgent` and `OverrideUserAgent` as a preference which is quite useful for monitoring and logging of custom apps and how they interact with other services

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Describe Preferred Solution

Once these options are set the platform's embedded browser should have the user agent defined.

## Describe Alternatives

Updating the user agent via native code per platform

## Additional Context

https://cordova.apache.org/docs/en/latest/config_ref/

**Comment by Seanmclem** [comment]
Is there documentation for this?
