### ISSUE TITLE
feat: Add native app web build to gitignore

### ISSUE THREAD

**Issue by schontz** [ionic-team/capacitor#2090]
# Feature Request

## Describe the Feature Request

Automatically add the web build files to `.gitignore` to keep the repo clean.

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Describe Preferred Solution

Add the path to the build directory for the native app. For example:
```
# .gitignore

# npx cap add ios
/ios/App/public/*

# npx cap add android
/android/app/src/main/assets/public/*
```

**Comment by jcesarmobile** [comment]
They are already git ignored, but not in the root `.gitignore`, each platform has it's own:

https://github.com/ionic-team/capacitor/blob/master/android-template/gitignore#L91
https://github.com/ionic-team/capacitor/blob/master/ios-template/gitignore#L7
https://github.com/ionic-team/capacitor/blob/master/electron-template/gitignore#L5

Is it not working?

**Comment by schontz** [comment]
Ah! I didn't notice those. They do appear to be working.
