### ISSUE TITLE
code object is not signed at all In architecture: x86_64

### ISSUE THREAD

**Issue by victorwang0526** [ionic-team/capacitor#2092]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/cli 1.2.1

  @capacitor/ios 1.2.1

  @capacitor/android 1.2.1

  @capacitor/core 1.2.1

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I use ionic with vue, then add capacitor, but when I build app with xcode, the error disappeared.

```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh
    cd /Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App
    /bin/sh -c /Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh

mkdir -p /Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App/DerivedData/Build/Products/Debug-iphonesimulator/Capacitor/Capacitor.framework" "/Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app/Frameworks"
building file list ... done
Capacitor.framework/
Capacitor.framework/Capacitor
Capacitor.framework/Info.plist
Capacitor.framework/_CodeSignature/
Capacitor.framework/_CodeSignature/CodeResources

sent 2208053 bytes  received 98 bytes  4416302.00 bytes/sec
total size is 2207438  speedup is 1.00
Code Signing /Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app/Frameworks/Capacitor.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app/Frameworks/Capacitor.framework'
/Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app/Frameworks/Capacitor.framework: replacing existing signature
/Users/victor/Desktop/workspace_node/ionic-preset-vue/ios/App/DerivedData/Build/Products/Debug-iphonesimulator/App.app/Frameworks/Capacitor.framework: code object is not signed at all
In architecture: x86_64
Command /bin/sh failed with exit code 1
```

## Expected Behavior

Build app success.

## Reproduction Steps

I am trying to write a preset for ionic with vue, so you can run follow commands to reproduce this issue.

```
$ vue create -p victorwang0526/ionic-preset-vue my-project

you can use default config, any template is ok.

$ cd my-project

$ npm run build

$ npx cap add ios

$ npx cap open ios

```

Then build the app with XCode, and build failed with this one error.

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.15.3

`pod --version` output (iOS issues only): 1.8.4

## Other Information

Xcode version: 10.3

`vue --version` output: @vue/cli 4.0.5

**Comment by victorwang0526** [comment]
I searched all day with google, try `Legacy Build System`, nothing happened.
And some other ways, none of them helped me.

**Comment by victorwang0526** [comment]
I also tried use this docs to create an ionic with capacitor, still same error.
https://capacitor.ionicframework.com/docs/getting-started/with-ionic

**Comment by jcesarmobile** [comment]
I can't reproduce with the steps you provided, the app builds fine in both Xcode 10.3 and 11.1

Can you provide a sample app? or maybe, try to update Xcode just in case it's a problem in your installation.

**Comment by victorwang0526** [comment]
@jcesarmobile Thanks, I will try update XCode later.

**Comment by victorwang0526** [comment]
When I updated Xcode by App Store, it's running ok now.
