### ISSUE TITLE
feat: cli clears out custom preferences in the config.xml file for iOS

### ISSUE THREAD

**Issue by stevenroussey-privicy** [ionic-team/capacitor#2093]
# Feature Request

## Describe the Feature Request
feat: cli clears out custom preferences in the config.xml file for iOS

## Platform Support Requested
- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
It looks like the code is in master, but would be great to release it. Thanks.

**Comment by jcesarmobile** [comment]
if it's fixed in master then it's not an issue, we will release when we can
