### ISSUE TITLE
bug: SafeArea for iphoneX in notch

### ISSUE THREAD

**Issue by aleleba** [ionic-team/capacitor#2100]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/cli 1.3.0

  @capacitor/core 1.3.0

  @capacitor/android 1.3.0

  @capacitor/ios 1.3.0

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Currently in iphone X there is no safe area for the webview, in order to see the content correctly and not overlap the notification bar.

## Expected Behavior

It is desired that there is a safearea for the webview on an iPhone X, so that the content is viewed correctly and does not overlap the notification bar.

## Other Technical Details

`npm --version` output:
6.9.0

`node --version` output:
v10.16.3

`pod --version` output (iOS issues only):
1.8.4

## Other Information

![Captura de Pantalla 2019-10-26 a la(s) 14 08 24](https://user-images.githubusercontent.com/28767814/67625359-5b783500-f7fa-11e9-8a0f-c313d9582365.png)

**Comment by piotrblasiak** [comment]
You should use CSS for this: https://webkit.org/blog/7929/designing-websites-for-iphone-x/

If you need to know the safe area insets in JS, you can do this using this library: https://github.com/zhetengbiji/safeAreaInsets

I am doing this and it works perfectly.

**Comment by dotNetkow** [comment]
Yes, this is web/css concern, not a Capacitor one. For what it's worth, [Ionic Framework](https://ionicframework.com/docs) handles this for you.

**Comment by brandonhudson** [comment]
FWIW, I recently had to implement this as well. The approach I took that worked was:

1. Detect the type of device using the Device API
2. Using JavaScript, fetch and match screen viewport sizes to the known sizes for iPhones/iPads with notches
3. If a match is found, append a css class to the body tag (ex: “ios”, “iphone”, "notch", etc.)
4. Create CSS styles that modify based on thE platform-specific classes you create.
3.

**Comment by aleleba** [comment]
Thanks for helping @piotrblasiak and @dotNetkow. 😁 I will try that. 😁👍

**Comment by mattsteve** [comment]
@brandonhudson I'm not a fan of this solution as it is not device agnostic. The point of the env(safe-area-inset-top) variable is if Apple releases a new iPhone you don't have to update your app to keep track of it. Capacitor should fix these environment variables.

**Comment by mcqj** [comment]
Thansk @piotrblasiak 
Question: Does capacitor correctly return the CSS environment variable values as set on the underlying platform or is it necessary to JS for that?

**Comment by piotrblasiak** [comment]
@mcqj capacitor does not provide you with those values as it's not needed - the browser that your app runs inside already has this information and you can access it using css with or without js (see links I posted previously).

**Comment by loama** [comment]
webview inside capacitor is returning 0 for env(safe-area-inset-top)

**Comment by piotrblasiak** [comment]
> webview inside capacitor is returning 0 for env(safe-area-inset-top) in an iPhone X

That is weird - I'm using https://github.com/zhetengbiji/safeAreaInsets without any problems.

**Comment by loama** [comment]
@piotrblasiak thanks for the fast reply, I'll try with that package. Do you know if that also works with Android?

**Comment by piotrblasiak** [comment]
Unfortunately it does not work with android yet.

**Comment by bigboypantson** [comment]
> Forget it, I was missing the viewport-fit=cover in the meta tag. Thanks!

I have tried this and still not working for me, the safe areas are always 0 from webview in capacitor, any help?

Thanks

**Comment by josiahbryan** [comment]
I have viewport-fit=cover and it does not work in android either. Neither does `safe-area-insets` - whats the fix here? Why is this closed?

**Comment by loama** [comment]
@josiahbryan can you put basic code to reproduce your issue? This is working fine for me in multiple apps, maybe I can help.
