### ISSUE TITLE
bug: IOS StatusBar.setBackgroundColor({color:'#fff000'}  ERROR MESSAGE:  not implemented

### ISSUE THREAD

**Issue by jeanmichelcraye** [ionic-team/capacitor#2101]
# Bug Report

## Capacitor Version

  @capacitor/cli 1.3.
  @capacitor/ios 1.3.0
  @capacitor/core 1.3.0

## Affected Platform(s)

- [ ] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
cannot set StatusBar.BackgroundColor .

Xcode simulator return ERROR MESSAGE:  {"message":"not implemented","errorMessage":""}

## Expected Behavior
status bar color should change for color:'#fff000'

## Sample Code or Sample Application Repo

import { Component } from '@angular/core';
import { Platform } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import {Plugins } from '@capacitor/core';

const { StatusBar } = Plugins;

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss']
})
export class AppComponent {
  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.splashScreen.hide();
      StatusBar.show(); // Ok
      StatusBar.setBackgroundColor({color:'#fff000'}).catch(error => alert(error.message));
    });
  }
}
## ios Xcode output

⚡️  To Native ->  StatusBar show 30579453
⚡️  To Native ->  StatusBar setBackgroundColor 30579454
⚡️  TO JS {}
ERROR MESSAGE:  {"message":"not implemented","errorMessage":""}

**Comment by jcesarmobile** [comment]
`setBackgroundColor` is not implemented for iOS and won't be unless Apple provides an API to do it (very unlikely)

**Comment by kmanaseryan** [comment]
> `setBackgroundColor` is not implemented for iOS and won't be unless Apple provides an API to do it (very unlikely)

@jcesarmobile then how does [Ionic Native Status Bar](https://ionicframework.com/docs/native/status-bar) do this if it's not supported? It would be really helpful if you mention in the doc that it's not supported on iOS. This will help folks to understand when to migrate the app from Ionic Native to Capacitor.

**Comment by jcesarmobile** [comment]
it adds a fake view and places it in the place where the status bar is and resizes the webview to avoid that area

nowadays you can use CSS safe areas to color or avoid the place where the status bar is

**Comment by jongbonga** [comment]
I'm getting the same error with `hide()`

```
To Native ->  SplashScreen hide 37589176
ERROR MESSAGE:  {"errorMessage":"","message":"not implemented"}
```
