### ISSUE TITLE
bug: XMLHttpRequest fails

### ISSUE THREAD

**Issue by beukaert** [ionic-team/capacitor#2107]
# Bug Report
XMLHttpRequest fails

## Capacitor Version

`npx cap doctor` output:
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.3.0

  @capacitor/android 1.3.0

  @capacitor/core 1.3.0

[success] Android looking great!

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Fails to receive XMLHttpRequest response:
 E/Capacitor/Console: File: http://domain.com/login - Line 0 - Msg: Access to XMLHttpRequest at 'https://domain/api/v1/auth/login' from origin 'http://domain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Which worked perfectly fine before (capacitor/android@1.2.1). Nothing changed on our back-end. Double-checked CORS headers, nothing strange. Tried changing the hostname back to localhost in the capacitor config, the issue persisted.

## Expected Behavior

Get a response from domain.com.

## Other Technical Details

`npm --version` output:
6.9.0

`node --version` output:
v10.16.1

## Other Information

Downgrading to capacitor/android 1.2.1 solved the issue.

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
Is your server configured to allow CORS to your app?

**Comment by beukaert** [comment]
I cannot provide you with an app at this moment, I am sorry.

Yes CORS is definately enabled. It works from my dev server running at localhost.

I've been manually downgraded file **WebViewLocalServer.java** from 1.3.0 to the 1.2.1 version (see this change: https://github.com/ionic-team/capacitor/commit/ccc00b3). 

Apparently this line it's all about:
`175: if (isLocalFile(loadingUrl) || Config.getString("server.url") == null) {`

So I figured I should lookup my config..

```
{
    "appId": "com.domain",
    "appName": "MyApp",
    "bundledWebRuntime": false,
    "npmClient": "npm",
    "webDir": "dist",
    "server": {
        "hostname": "domain.com",
        "allowNavigation": [
            "domain.com",
            "*.domain.com"
        ]
    },
    "backgroundColor": "#ffffff",
    "android": {
        "allowMixedContent": false,
        "captureInput": false,
        "webContentsDebuggingEnabled": true
    },
    "plugins": {
        "LocalNotifications": {
            "smallIcon": "ic_stat_icon_sample"
        },
        "SplashScreen": {
            "launchShowDuration": 20000
        }
    }
}
```

Eventually removed the whole server part, and now it works. 

I noticed the server part changed the hostname of the local webview, at first sight I set this to the domain name to avoid potential CORS issues.

Maybe the server config should be ignored in total if no server.url is present?

Thanks!!

**Comment by jcesarmobile** [comment]
The `allowNavigation` makes to proxy the requests to inject Capacitor in remote sites, so that's probably causing the issue. You shouldn't use it if you are not navigating to those remote sites.
