### ISSUE TITLE
bug: ionic-native or cordova include in capacitor

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/capacitor#2108]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
C:\Users\indra26\Desktop\capacitor-experiment\cap-exp>npx cap doctor
   Capacitor Doctor
Latest Dependencies:
  @capacitor/cli: 1.3.0
  @capacitor/core: 1.3.0
  @capacitor/android: 1.3.0
  @capacitor/ios: 1.3.0
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/core 1.3.0
  @capacitor/cli 1.3.0
  @capacitor/android 1.3.0
[success] Android looking great! 👌
```

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

After including ionic-native cordova or cordova, when you execute npx cap open android, you will get this error in terminal. And after that it will invoke open files and will say to add cordova plugin iml file something. But you will able to build apk.
```
Error Loading Project: Cannot load module capacitor-cordova-android-plugins
```
## Expected Behavior

It shouldn't throw any error.

## Sample Code or Sample Application Repo
```
11:30 AM	Error Loading Project: Cannot load module capacitor-cordova-android-plugins
```
Open below image in new tab.
![image](https://user-images.githubusercontent.com/23274631/67741866-62908480-fa40-11e9-8a92-fc717d2b5ff7.png)

## Reproduction Steps
**REPO**
Repo: https://github.com/indraraj26/camera-capacitor/tree/cordova-cap

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: 6.9.0

`pod --version` output (iOS issues only):

## Other Information

```
C:\Users\indra26\Desktop\capacitor-experiment\cap-exp>ionic info
Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (2 plugins total)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.9

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
C:\Users\indra26\Desktop\capacitor-experiment\cap-exp>
```

**Comment by PR1YANKPAT3L** [comment]
It's not a critical error. If you simply press yes and **Refresh Gradle Project**, you will be able to sync and build. iml files are module files generated by your IDE (Android Studio) in order to store indexing data.

**Comment by jcesarmobile** [comment]
I also could build without problems, just ran
```
npm install
ionic build
npx cap sync android
```

When the .iml is not found, clicking the "Sync Project with Gradle Files" button should regenerate it. (or File -> Sync Project with Gradle Files if you don't have the button in the toolbar)
