### ISSUE TITLE
statusTap event not working on iOS 13

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/capacitor#2109]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/cli 1.3.0

  @capacitor/core 1.3.0

  @capacitor/android 1.3.0

  @capacitor/ios 1.3.0


[success] Android looking great! 👌
  Found 4 Capacitor plugins for ios:
    @biesbjerg/capacitor-music-player (0.0.1)
    @teamhive/capacitor-email (2.1.2)
    capacitor-analytics (0.0.4)
    cordova-plugin-inapppurchase (1.2.0)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When tapping on status bar ion-content does not scroll to top

## Expected Behavior

Scroll to top on tap

**Comment by jcesarmobile** [comment]
This is only on iOS 13, right?

**Comment by andreas-aeschlimann** [comment]
I have seen this issue on iOS 13.0 and 13.1 (iPhone XS Max, iPhone 11 Pro Max) so far.

On Android and iOS 12.x (iPhone X) it worked as expected.

**Comment by jcesarmobile** [comment]
The problem is statusTap event not working on iOS 13. Ionic uses that event to scroll the internal content.

On a non Ionic app with content bigger than the screen, if you tap the status bar it will still scroll to top as expected.

**Comment by andreas-aeschlimann** [comment]
What do you suggest as workaround until it is fixed?

Does the Cordova plugin have the same issue in iOS 13?

**Comment by bryplano** [comment]
The Cordova approach adds a scrollview off screen that forwards in the touch/tap event. It's a hacky solution that causes other problems.

There isn't a great workaround until Apple makes changes to better support or fix statusTap in iOS.

**Comment by jcesarmobile** [comment]
I've found another possible solution, but it's also hacky.

We can swizzle handleTapAction on UIStatusBarManager class. (meaning, it removes the handleTapAction method and add a custom one that can send the event to javascript).

So either way, the two possible options are hacky, not sure which one is better.

**Comment by Proper-Job** [comment]
The reason the statusTap event isn't called is because [touchesBegan](https://github.com/ionic-team/capacitor/blob/1.5.0/ios-template/App/App/AppDelegate.swift#L50) is no longer called on the AppDelegate on iOS 13.
iOS 13 introduced a new way to [manage the App's Life Cycle](https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle) with UISceneDelegate.

**Comment by andreas-aeschlimann** [comment]
This works for me now, thanks a lot for fixing it!
