### ISSUE TITLE
Camera source prompt-mode and translations

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#2113]
Thanks for a great framework! 🎖 

When using the camera plugin with the `prompt` `source` value, one can choose between using the camera and picking from the library. So far so good.

However, the prompt is always displayed in english with no ability to provide translation values.

Would be neat if we could pass in translation strings, so we could use this in any locale.

Is this something you've considered adding?

**Comment by jcesarmobile** [comment]
There is already an issue for localizing all the plugin messages
https://github.com/ionic-team/capacitor/issues/872

**Comment by sandstrom** [comment]
@jcesarmobile I think it's easier to simply make the handful of strings configurable. That way we can use our existing localization mechanism.

I've written down my thoughts on this in this comment: https://github.com/ionic-team/capacitor/issues/872#issuecomment-548047623

If you agree with me, I'd suggest reopening this issue to track full localization support for this plugin.

**Comment by sandstrom** [comment]
Fixed in https://github.com/ionic-team/capacitor/pull/2631
