### ISSUE TITLE
bug: stencil live-reload not working (or big lag)

### ISSUE THREAD

**Issue by miqmago** [ionic-team/capacitor#2119]
# Bug Report

Live reload does not refresh android app on file changes or it does after random time.
Actual config:
- Stencil.js project
- Integrated with capacitor
- Android platform
- capacitor.config.json with `server.url` to local lan url
- Stencil.js `npm start` running in `server.url`

On file changed, browser app reloads instantly but android seems to be reloading randomly after 30s to 2min or more. Also it seems that sometimes reload happens because of a disconnection (connection reset) from server.

## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:
  @capacitor/cli: 1.3.0
  @capacitor/core: 1.3.0
  @capacitor/android: 1.3.0
  @capacitor/ios: 1.3.0

Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/core 1.3.0
  @capacitor/cli 1.3.0
  @capacitor/android 1.3.0

[success] Android looking great! 👌

## Affected Platform(s)

- [X] Android
- [ ] ?? iOS (not tested)
- [ ] Electron
- [ ] Web

## Current Behavior
App compiles fine and content is served but live reload does not work.

Both app and dev machine are connected in same network, so `server.url` is visible from mobile device.

## Sample Code or Sample Application Repo

**`capacitor.config.json`**:
```json
{
    "appId": "com.bitgenoma.appname",
    "appName": "appname",
    "bundledWebRuntime": false,
    "npmClient": "npm",
    "webDir": "www",
    "cordova": {},
    "plugins": {
        "SplashScreen": {
            "launchAutoHide": false,
            "showSpinner": true
        }
    },
    "server": {
        "url": "http://192.168.1.130:3333"
    }
}
```

When inspecting app from `chrome://inspect/#devices` it shows the following html:

```html
<html dir="ltr" lang="en" class="plt-android plt-phablet plt-cordova plt-capacitor plt-mobile plt-hybrid md hydrated" mode="md">
<head>
    <script type="text/javascript">window.Capacitor = { DEBUG: true };
        ...
        window.WEBVIEW_SERVER_URL = 'http://192.168.1.130:3333';</script>
    <meta charset="utf-8">
    <style data-styles=""></style>
    <title>Awesome Bitgenoma.com app</title>
    <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="Welcome to the Bit Genoma Cool App's">
    <meta name="theme-color" content="#16161d">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="Ionic PWA">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta http-equiv="x-ua-compatible" content="IE=Edge">
    <link rel="modulepreload" href="/build/p-in42994y.js">
    <link rel="modulepreload" href="/build/p-42a0b39d.js">
    <link rel="modulepreload" href="/build/p-461103b9.js">
    <link rel="modulepreload" href="/build/p-6d89b466.js">
    <link rel="modulepreload" href="/build/p-716d1419.js">
    <link rel="modulepreload" href="/build/p-87820f34.js">
    <link rel="modulepreload" href="/build/p-8a939906.js">
    <link rel="modulepreload" href="/build/p-b73aafdf.js">
    <link rel="modulepreload" href="/build/p-c58c7fd2.js">
    <link rel="modulepreload" href="/build/p-da20fd29.js">
    <link rel="modulepreload" href="/build/p-f1a4df63.js">
    <script type="module" src="/build/p-in42994y.js" data-resources-url="/build/" data-stencil-namespace="app"></script>
    <script nomodule="" src="/build/app.js"></script>
    <link href="/build/p-5t7wd5yr.css" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="http://192.168.1.130:3333/assets/icon/apple-touch-icon.png" data-href="http://192.168.1.130:3333/assets/icon/apple-touch-icon.png" data-type="" type="">
    <link rel="icon" type="image/x-icon" href="http://192.168.1.130:3333/assets/icon/favicon.ico" data-href="http://192.168.1.130:3333/assets/icon/favicon.ico" data-type="image/x-icon">
    <link rel="manifest" href="/manifest.json">
</head>

<body>
    <app-root class="hydrated">
        <ion-app class="md ion-page hydrated">
            ...
        </ion-app>
    </app-root>
    <iframe title="Stencil Dev Server Connector ⚡" src="http://192.168.1.130:3333/~dev-server" style="display:block;width:0;height:0;border:0"></iframe>
</body>

</html>
```

## Reproduction Steps

- Set up `server.url` inside `capacitor.config.json`
- `npm run build` ==> `stencil build`
- `npx cap copy`
- `cd android && gradlew installDebug && cd ..`
- `npm start`==> `stencil build --dev --watch --serve`

- `adb shell am start -n `cat capacitor.config.json | grep 'appId' | cut -d'"' -f4`/`cat capacitor.config.json | grep 'appId' | cut -d'"' -f4`.MainActivity`

**Comment by jcesarmobile** [comment]
I can't reproduce, but in any case it's an stencil issue, not Capacitor since Capacitor only loads the url, the reload is handled by stencil
