### ISSUE TITLE
bug: Use capacitor for projects created with baseHref predefined

### ISSUE THREAD

**Issue by josepol** [ionic-team/capacitor#2120]
# Bug Report

## Capacitor Version
1.3.0

`npx cap doctor` output:
Latest Dependencies:
  @capacitor/cli: 1.3.0
  @capacitor/core: 1.3.0
  @capacitor/android: 1.3.0
  @capacitor/ios: 1.3.0

Installed Dependencies:
  @capacitor/ios 1.3.0
  @capacitor/android 1.3.0
  @capacitor/cli 1.3.0
  @capacitor/core 1.3.0

## Affected Platform(s)

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
For an already created project that it is configured to use a predefined baseHref in angular.json, when I try to generate the same build application for iOS or Android, after the splashscreen dissapears I only see a white screen. But if I clear that baseHref field, both iOS and Android apps works perfectly.

## Expected Behavior
Given the following configuration in angular.json: {..., baseHref: 'MyPageRoot, ...}'.
I would expect to avoid changing that field to '/' in order to make iOS and Android applications.
If I have the following url: https://domain.com/MyPageRoot/login for my website, I do not expect to change '/MyPageRoot/' to '/' anytime I want to build a new iOS or Android app version.

## Other Technical Details

`npm --version` output:
6.4.1

`node --version` output:
10.15.3

## Other Information
Awesome work guys!

**Comment by jcesarmobile** [comment]
Capacitor is framework agnostic, so won’t be checking framework configurations to adapt. You can try setting capacitor hostname to include the /myPageRoot
