### ISSUE TITLE
bug: undefined is not an object (evaluating 'cordova.ThemeableBrowser.open')

### ISSUE THREAD

**Issue by manhlh** [ionic-team/capacitor#2127]
# Bug Report

## Capacitor Version
 @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.3.0

  @capacitor/ios 1.3.0

  @capacitor/core 1.3.0

  Found 19 Capacitor plugins for ios:
    cordova-clipboard (1.2.1)
    cordova-plugin-advanced-http (2.2.0)
    cordova-plugin-app-version (0.1.9)
    cordova-plugin-camera (4.0.3)
    cordova-plugin-datepicker (0.9.3)
    cordova-plugin-device (2.0.2)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-fcm-with-dependecy-updated (2.4.0)
    cordova-plugin-file (6.0.1)
    cordova-plugin-inappbrowser (3.1.0)
    cordova-plugin-ionic-keyboard (2.1.3)
    cordova-plugin-ionic-webview (4.1.2)
    cordova-plugin-ios-camera-permissions (1.2.0)
    cordova-plugin-native-spinner (1.1.3)
    cordova-plugin-nativestorage (2.3.2)
    cordova-plugin-splashscreen (5.0.2)
    cordova-plugin-statusbar (2.4.2)
    cordova-plugin-themeablebrowser (0.2.18)
    cordova-plugin-whitelist (1.3.3)
[success] iOS looking great! 👌

- [x] iOS

## Current Behavior
- I install plugin Themeable Browser into my project ( ionic 3), after I enabled capacitor, I follow the guidge and last step run "npx cap open ios" . inside app, I open function used plugin Themeable Browser and .... omg !! Bugs it here, log I see: 
TypeError: undefined is not an object (evaluating 'cordova.ThemeableBrowser.open')
(anonymous function) — shopping.ts:181
(anonymous function)
callWithDebugContext — core.js:15098
dispatchEvent — core.js:10004
(anonymous function) — platform-browser.js:2628
onInvokeTask — core.js:4751
(anonymous function) — polyfills.js:3875
(anonymous function) — polyfills.js:4017
p — polyfills.js:3227
v — polyfills.js:3240 

BUT I run with only Ionic, it run...

## Sample Code or Sample Application Repo
declare var cordova: any;
...
 this.ref = cordova.ThemeableBrowser.open(this.productUrl, '_blank', options)

`npm --version` output: 6.12.1

`node --version` output: v10.16.3

`pod --version` output (iOS issues only):1.8.4

**Comment by jcesarmobile** [comment]
did you run `npx cap update` or `npx cap sync` after installing the plugin?
If you ran them and still face the issue, can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing since there was no response from the reporter
