### ISSUE TITLE
bug: Update documentation

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2128]
Having a lot of issues getting the firebase push notifications working on iOS

Seems that the correct pods are (rather than pod 'Firebase/Messaging')

```
  capacitor_pods
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'
```

and app delegate import is: 
```import FirebaseCore```

**Comment by PR1YANKPAT3L** [comment]
Do you have a sample code? My app uses `pod 'Firebase/Messaging'` according to the [firebase docs ](https://firebase.google.com/docs/cloud-messaging/ios/client).

**Comment by jcesarmobile** [comment]
That dependencies are working fine, not sure what your problem is, but it's not related to Capacitor
