### ISSUE TITLE
bug: Share API does not share URL when sharing using iOS's copy

### ISSUE THREAD

**Issue by Jdatechong** [ionic-team/capacitor#2129]
# Bug Report

## Capacitor Version

`npx cap doctor` output:  

  @capacitor/cli 1.1.1

  @capacitor/core 1.1.1

  @capacitor/android 1.1.1

  @capacitor/ios 1.1.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Selecting the 'copy' option from the share interface copies the the text and URL to clipboard, but will not paste the URL on certain text fields (especially fields within the app I am copying from).

## Expected Behavior

Paste will paste text as well as URL

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.13.0

`pod --version` output (iOS issues only): 1.7.5

**Comment by jcesarmobile** [comment]
can you provide a sample app? maybe the problem is in the fields where you are trying to paste?

**Comment by jcesarmobile** [comment]
closing since there was no response from the reporter

**Comment by KirstenStake** [comment]
@jcesarmobile @Jdatechong Jdatechong

i am experiencing the same issue. my code is as follows:

`      await Share.share({
        text: this._frameworkService.getTranslatedText('DYNAMIC_CHECK_OUT_INSTRUMENT', { value: this.symbol }),
        url: shareUrl
      });`

- Android working without problems
- iOS share with messenger, sms etc all working fine with displaying text + url. **ONLY** iOS "copy" functionality not working and only copies across the text (not the url)


Setup plugin version:
 "@capacitor/share": "^1.0.3"


Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.12
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.0.5
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : 3.1.2

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur
