### ISSUE TITLE
Question: How to access the www directory in Swift?

### ISSUE THREAD

**Issue by ingageco** [ionic-team/capacitor#2134]
I'm trying to reference a file included within the Capacitor app - in www/assets/imgs/img.jpg - and locate it within Swift to return a UIImage. Here's the code: 

coverURI is a string = "www/assets/imgs/img.jpg" that is passed from Ionic

```
let baseCoverImagePath = NSSearchPathForDirectoriesInDomains(.applicationDirectory, . userDomainMask, true)[0];

let fullCoverImagePath = String(format:"%@%@", baseCoverImagePath, coverUri);
            
let defaultManager = FileManager.default;
            
if(defaultManager.fileExists(atPath: fullCoverImagePath)){
                coverImage = UIImage(contentsOfFile: fullCoverImagePath)!
} else {
                print("Image could not be found");
                print(fullCoverImagePath);
}
```

What i'm confused about is the ".applicationDirectory" part. I can't seem to find the www directory of the app to locate this file. I've tried .documentDirectory as well and no-dice. 

How do i accurately reference the image so it is found and used?

Any help is appreciated, as I'm trying to finish porting over Cordova Music Controls to Capacitor for the community.

**Comment by jcesarmobile** [comment]
This is not a Capacitor issue, it's a question, please, use the forums or slack to ask questions and issues to real Capacitor issues only.

Files on www folder are not in the filesystem, but in the App [bundle](https://developer.apple.com/documentation/foundation/bundle).
