### ISSUE TITLE
bug: SplashScreen won't hide manually

### ISSUE THREAD

**Issue by cambronjay** [ionic-team/capacitor#2138]
# Bug Report

## Capacitor Version

`npx cap doctor` output: 1.3.0

## Affected Platform(s)

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

SplashScreen.hide() won't hide the splashscreen.

## Expected Behavior

The splash screen should hide when splashscreen.hide() is called and when launchAutoHide: false

## Sample Code or Sample Application Repo
https://github.com/ionic-team/ionic-stencil-conference-app
"plugins": {
    "SplashScreen": {
      "launchAutoHide": false,
      "showSpinner": false
    }
  }

## Reproduction Steps
Pull down the ionic stencil conference app, add  the below code code to the capacitor.config.json file, and then run the ios app and notice the SplashScreen won't hide when SplashScreen.hide() is called in the app-root.tsx
"plugins": {
    "SplashScreen": {
      "launchAutoHide": false,
      "showSpinner": false
    }
  }

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: 10.16.0

`pod --version` output (iOS issues only): 1.8.4

**Comment by successiveoverrelaxation** [comment]
I experienced similar issues today when using Capacitor.SplashScreen.hide(). I then tried Capacitor.Plugins.SplashScreen.hide() and it worked for me.

**Comment by peterpeterparker** [comment]
same to me because I used the auto-import of Webstorm which imported "only" `Splashscreen` as I didn't typed `Plugins`

```
await SplashScreen.hide()
```

-> auto-import ->

```
import {SplashScreen} from '@capacitor/core';
```

which correctly should be:

```
import { Plugins } from '@capacitor/core';
const { SplashScreen } = Plugins;
```

**Comment by jcesarmobile** [comment]
I've tested the conference app and it's working fine

**Comment by vycoder** [comment]
I'm having the same issue. I'm using the same/proper code:
```
import { Plugins } from '@capacitor/core';
const { SplashScreen } = Plugins;
```
Works on Android but fails on IOS, getting stuck on the Splash Screen. Anybody had any ideas on how I could fix this?

**Comment by davidseek** [comment]
> I'm having the same issue. I'm using the same/proper code:
> 
> ```
> import { Plugins } from '@capacitor/core';
> const { SplashScreen } = Plugins;
> ```
> 
> Works on Android but fails on IOS, getting stuck on the Splash Screen. Anybody had any ideas on how I could fix this?

Did you fix it? I have the same issue.

**Comment by vycoder** [comment]
@davidseek unfortunately I just re-enabled the auto hiding of SplashScreen, it seems like it's an IOS issue and Idk what to do with it or if I can even do anything with it tbh. I tried drinking 5 cups of coffee and stared at a wall and I still came up with nothing. Maybe I'm too dumb to be doing this whole software engineering thing.

RIght now, I'm just hoping someone smarter than me would come up with something and then I'm just going update my codebase and it will all go away.

**Comment by davidseek** [comment]
> @davidseek unfortunately I just re-enabled the auto hiding of SplashScreen, it seems like it's an IOS issue and Idk what to do with it or if I can even do anything with it tbh. I tried drinking 5 cups of coffee and stared at a wall and I still came up with nothing. Maybe I'm too dumb to be doing this whole software engineering thing.
> 
> 
> 
> RIght now, I'm just hoping someone smarter than me would come up with something and then I'm just going update my codebase and it will all go away.

So my issue was old code. 
I have a script to build, remove iOS, add iOS, 
edit assets, etc. 
But one step failed because of permission issues
and therefore no matter what I changed,
the code base was actually never updated. 

The SplashScreen didnt remove because the App crashed because of missing injections of plugins. 

I deleted then the www folder through Sudo and ran capacitor add iOS, capacitor sync and copy to update the plugins and now everything works as expected.

**Comment by Boosten** [comment]
> same to me because I used the auto-import of Webstorm which imported "only" `Splashscreen` as I didn't typed `Plugins`
> 
> ```
> await SplashScreen.hide()
> ```
> 
> -> auto-import ->
> 
> ```
> import {SplashScreen} from '@capacitor/core';
> ```
> 
> which doesn't produce any compilation error but is incorrect. correct should be:
> 
> ```
> import { Plugins } from '@capacitor/core';
> const { SplashScreen } = Plugins;
> ```

🙈 embarrassing that I needed this issue to realize that my import was wrong. Thanks 😀 .

**Comment by fhouenou** [comment]
You have to remove or set launchAutoHide to true from capacitor.config.ts to hide splash screen.
