### ISSUE TITLE
Play Developers API deprecated

### ISSUE THREAD

**Issue by chrischance67** [ionic-team/capacitor#2141]
Hello everyone!

I have a somewhat particular problem. I made an app in Capacitor with React 1 week ago, I uploaded it to the Google Play Store and the panel says "We have detected that your application uses an old version of the API for Google Play developers. As of December 1, 2019 , versions 1 and 2 of this API will no longer be available. Upgrade to version 3 before that date. Please note that this is not related to the Billing / AIDL library becoming unavailable. More information. "

Something that remarkably seems to affect my app, so I wanted to know if you are going to update this.

I attach the information link  => https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

Thank you

**Comment by jcesarmobile** [comment]
I don’t see how this is related to Capacitor. Capacitor doesn’t use any billing or play developer API.
Are you using some plugin that might be using it?

**Comment by jcesarmobile** [comment]
closing as there was no response from the reporter
