### ISSUE TITLE
Update gradle and dependencies

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#2148]
Update gradle wrapper, gradle tools, google services and all other dependencies

**Comment by PR1YANKPAT3L** [comment]
I meant to create new PR for this upgrade but it ended up appending the [commit](79ad0e224137116354945335225bcf5ccf368457) to my AndroidX PR.

**Comment by jcesarmobile** [comment]
please, don't do that, let's keep PRs separated by the issues they fix

**Comment by mrjmorant** [comment]
It is safe to / should I upgrade gradle through Android Studio? I'm receiving this message: _To take advantage of the latest features, improvements, and security fixes, we strongly recommend that you update the Android Gradle plugin from the current version 3.3.2 to version 3.5.3 and Gradle to version 5.4.1._

Thank you in advance :)
