### ISSUE TITLE
incompatible: ionic-native/google-maps

### ISSUE THREAD

**Issue by wf9a5m75** [ionic-team/capacitor#215]
Hi, this is the author of [cordova-plugin-googlemaps](https://github.com/mapsplugin/cordova-plugin-googlemaps), as known also as `@ionic-native/google-maps` plugin.

I have been testing the alpha version, but there are some installation problems.

---------------------------------------------------------------

### problem 1. `$PLAY_SERVICES_VERSION` is replaced only at once

`cordova` supports `<variable>` tag in `plugin.xml` file.

I define two locations for one variable  in the `plugin.xml` file of the maps plugin like this:

```xml
<preference name="PLAY_SERVICES_VERSION" default="11.8.0" />
<framework src="com.google.android.gms:play-services-maps:$PLAY_SERVICES_VERSION" />
<framework src="com.google.android.gms:play-services-location:$PLAY_SERVICES_VERSION" />
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b76d905ece6a88595afa539204b57b8ae18cd2ed/plugin.xml#L237-L239

However the `$PLAY_SERVICES_VERSION` is replaced only at once in the generated `build.gradle` file.

```

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'org.apache.cordova:framework:7.0.0'
    // SUB-PROJECT DEPENDENCIES START
    implementation "com.google.android.gms:play-services-maps:11.8.0"
    implementation "com.google.android.gms:play-services-location:$PLAY_SERVICES_VERSION"  <-- This should be replaced.
    implementation "com.android.support:support-core-utils:24.1.0"
    // SUB-PROJECT DEPENDENCIES END
}

```

---------------------------------------------------------------

### problem 2. need to support  `<framework src=""  custom="true" type="gradleReference" />`

The maps plugin requires extra gradle script for many reasons.
`cordova` takes care them very well.
But `capacitor` ignores these tags, then `Android Studio` can not recognizes `aar` file.

```
<framework src="src/android/frameworks/build-extras.gradle"  custom="true" type="gradleReference" />
<framework src="src/android/frameworks/tbxml-android.gradle"  custom="true" type="gradleReference" />
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b76d905ece6a88595afa539204b57b8ae18cd2ed/plugin.xml#L201-L202

**Comment by jcesarmobile** [comment]
With https://github.com/ionic-team/capacitor/pull/240, https://github.com/ionic-team/capacitor/pull/239, https://github.com/ionic-team/capacitor/pull/238 and https://github.com/ionic-team/capacitor/pull/222, should be fixed.

I was able to see the map in your sample app, but sometimes the sections didn't load, we should investigate more about that.

BTW, also tested iOS and it's not going to work there, your plugin is highly coupled with CDVViewController and we don't use it (as we have our own view controller class)

**Comment by wf9a5m75** [comment]
Thank you for updating. I will check it later.

Inside the native code is my area, so don't worry about that. I will adjust the code.

**Comment by thiphariel** [comment]
So, this plugin will be compatible with capacitor or not at the end ?

**Comment by jcesarmobile** [comment]
No, on iOS it won't work.
