### ISSUE TITLE
discuss:  Android catches all plugin exceptions and logs message while iOS allows them to crash the app.  Should they be made to work the same across platforms?

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/capacitor#2150]
In trying to create a [plugin](https://github.com/josh-m-sharpe/capacitor-firebase-crashlytics) for Firebase Crashlytics, it seems that `@capacitor/ios` allows exceptions within a plugin method to bubble all the way up and crash the app and `@capacitor/android` catches all exceptions and logs a simple message.  Android code is [here](https://github.com/ionic-team/capacitor/blob/1.3.0/android/capacitor/src/main/java/com/getcapacitor/PluginHandle.java#L98-L102) and [here](https://github.com/ionic-team/capacitor/blob/1.3.0/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L531-L534).

To me, the Android implementation seems like it could hide problems within the plugin, never to be seen or reported by tools like Crashlytics.  While good intentioned, this seems like a bad idea overall.

Would the Capacitor team welcome PRs that remove the exception catching logic from the android platform?

**Comment by PR1YANKPAT3L** [comment]
I wouldn't necessarily remove exception checks and use notifyListener to transmit errors, which can be handled by the web app?

**Comment by josh-m-sharpe** [comment]
I think that approach would work too.  Either way, I suspect it makes sense to update all platforms to work the same.

It would be good to hear from the internal team on this though.

**Comment by jcesarmobile** [comment]
I agree, will add this to the 2.0.0 milestone

**Comment by nphyatt** [comment]
My gut says that it would be ideal to not catch the unexpected exceptions similar to how a regular native app would work. Plugins should catch exceptions they expect and return the appropriate responses. If an exception occurs that is not expected code should be fixed to handle it as the web side of the app really has no context in how to do so.

**Comment by jcesarmobile** [comment]
@josh-m-sharpe, I've sent a PR, let me know what do you think

**Comment by josh-m-sharpe** [comment]
Seems solid.  Thanks!
