### ISSUE TITLE
bug: Object.fromNative (capacitor-runtime.js) appearing only during Google Play build/release process?

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/capacitor#2154]
# Bug Report

## Capacitor Version
npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/cli 1.3.0

  @capacitor/android 1.3.0

  @capacitor/ios 1.3.0

  @capacitor/core 1.3.0

  Found 4 Capacitor plugins for ios:
    capacitor-branch-deep-links (1.0.0)
    capacitor-fcm (0.1.0)
    capacitor-firebase-crashlytics (0.0.1)
    phonegap-plugin-barcodescanner (8.1.0)

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
The following stack track is reported in my error tracking tool (sentry.io) immediately following every version I push to Google Play:

```
Error
Uncaught (in promise): Error: Failed to get instance FirebaseID
Error: Failed to get instance FirebaseID
    at Object.fromNative (capacitor-runtime.js:230:14)
    at <anonymous>:1:18
```

I suspect it's coming from some of their internal build/release tooling, but I have no way to concretely prove that.  Here's some circumstantial evidence:

1) I've never seen the error locally
2) It only appears in my error tracking tool (sentry.io)
3) It only appears immediately after pushing a new version to Google Play
4) The IPs geolocate to Mountain View, CA.
5) It hasn't (yet) manifested itself during normal production usage

## Sample Code or Sample Application Repo

As I can't reproduce this in development, I'm not interested in that angle of attack.  What's more curious is... `capacitor-runtime.js` in the error.  What is that?  `find node_modules -name *capacitor-runtime*` doesn't return anything.  It's not in my app either.  Firebase certainly wouldn't have a file named anything `capacitor` - so where is that file being generated?  If anyone knows something about that it might be easier to track down where `Object.fromNative` is being called.

**Comment by jcesarmobile** [comment]
The error comes from capacitor-fcm https://github.com/stewwan/capacitor-fcm/blob/master/android/capacitor-fcm/src/main/java/io/stewan/capacitor/fcm/FCMPlugin.java#L98

Google runs apps in real devices when you submit APKs, and looks like one of them is not getting the FCM token and you are not using a catch in the getToken function.

**Comment by josh-m-sharpe** [comment]
Ah, nice find!  Out of pure curiosity, do you know what that `capacitor-runtime.js` file is, where it comes from, etc...?

**Comment by jcesarmobile** [comment]
It's `native-bridge.js`, but probably appears with a different name because of https://github.com/ionic-team/capacitor/blob/master/core/native-bridge.js#L1
