### ISSUE TITLE
Error: File does not exist, when trying to upload photo from android with PWA

### ISSUE THREAD

**Issue by aybarchu** [ionic-team/capacitor#2172]
# Bug Report

## Capacitor Version

  @capacitor/core 1.3.0

  @capacitor/cli 1.3.0

  @capacitor/ios 1.3.0

  @capacitor/android 1.3.0

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [X] Web

## Current Behavior

When Im trying to upload a photo from android device through pwa. I get an error saying 'File does not exist' 

const originalPhoto does not include .path property, even with resultType: CameraResultType.Uri at imageOptions

## Expected Behavior

Photo should upload.
## Sample Code or Sample Application Repo
  async takePhoto() {
    const options = {
      resultType: CameraResultType.Uri
    };

    const originalPhoto = await Camera.getPhoto(options);
    console.log(originalPhoto,' original photo');
    const photoInTempStorage = await Filesystem.readFile({ path: originalPhoto.path }); // ERROR: FILE DOES NOT EXIST 
    console.log(photoInTempStorage,' photoInTempStorage');

    let date = new Date(),
      time = date.getTime(),
      fileName = time + ".jpeg";

    await Filesystem.writeFile({
      data: photoInTempStorage.data,
      path: fileName,
      directory: FilesystemDirectory.Data
    });

    const finalPhotoUri = await Filesystem.getUri({
      directory: FilesystemDirectory.Data,
      path: fileName,
    });

    // this.subirImagen(finalPhotoUri);
    console.log(finalPhotoUri, 'final photo uri');
    let photoPath = Capacitor.convertFileSrc(finalPhotoUri.uri);
    console.log(photoPath, 'photopath for web');
  }

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/1738

**Comment by theGeekyLad** [comment]
How's it relevant @jcesarmobile ? The author is facing this issue on Android which uses Capacitor which in turn requires full platform-specific file path as `file.path`. Issue #1738 is with regards Electron and the documentation clearly states `file.webPath` is what works on web.

I'm still facing this issue on Android as `file.path` doesn't resolve. Here's the error:
```
Error in readAsBase64(): Error: File does not exist.
```
`readAsBase64()` is defined exactly as show in the official docs [here](https://ionicframework.com/docs/angular/your-first-app/5-adding-mobile#platform-specific-logic).

**Comment by jcesarmobile** [comment]
The creator of the issue was having the problem on a PWA, that means they are using the web implementation, not the native implementation. Electron also uses the web version in this case, so it’s the same problem.
If you are having it in android native then report a new issue.

**Comment by theGeekyLad** [comment]
That's plausible but I see that the author has checked Android under affected platforms. Shall create a new issue anyway. Thanks @jcesarmobile .
