### ISSUE TITLE
bug: Setting iosScheme to http has no effect

### ISSUE THREAD

**Issue by malua** [ionic-team/capacitor#2173]
# Bug Report

## Capacitor Version
```
@capacitor/cli 1.3.0
@capacitor/ios 1.3.0
@capacitor/android 1.3.0
@capacitor/core 1.3.0
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Setting `iosScheme` in `capacitor.config.json` to `http` makes no difference. App is still being loaded from `capacitor://`
I already removed the ios platform completely and an re-added it, but that didn't work unfortunatley. Am I missing something? Do I need to set something in the plist file or anywhere else?

## Expected Behavior

Setting `iosScheme` in `capacitor.config.json` to `http` should make capacitor load the app from `http://` instead of `capacitor://`

`npm --version` output:
6.9.0
`node --version` output:
v12.13.0
`pod --version` output (iOS issues only):
1.7.5

Thank you for your help and awesome products!

**Comment by malua** [comment]
oh, it's just working with custom protocols right? do you happen to know if ionic://localhost or capacitor://localhost are considered safe for something like stripe.js?

**Comment by jcesarmobile** [comment]
WKWebView doesn't allow to use http or http for serving local assets, this works as expected.

Not sure about stripe, sorry.

**Comment by kedarguy** [comment]
> oh, it's just working with custom protocols right? do you happen to know if ionic://localhost or capacitor://localhost are considered safe for something like stripe.js?

Hey, I am also looking in to this for Stripe.js, did you find a way to integrate Stripe with capacitor ios and android apps?

**Comment by malua** [comment]
we are still using cordova with cordova-plugin-ionic-webview@2.5.3
i dont think its possible to get Stripe.js working with custom protocols.

your best is to work with a plugin like this one and use the native stripe sdk
https://github.com/zyra/capacitor-stripe

**Comment by joseph-navant** [comment]
> WKWebView doesn't allow to use http or http for serving local assets, this works as expected.
> 
> Not sure about stripe, sorry.

Hi @jcesarmobile! Could you explain why WKWebView doesn't allow to use http or https for serving local assets? I would like to know more about this but I don't know what/how to search it.

Thanks in advance

**Comment by malua** [comment]
as far as i can tell, stripe.js now also sees file:// and ionic:// as safe origins!
in the stripe js file you can find this function:
`key: "_ensureHTTPS",
              value: function () {
                var e = window.location.protocol,
                  t = -1 !== ["https:", "file:", "ionic:"].indexOf(e),`

I also test it right now, and it works if you serve your app from ionic:// on ios!

**Comment by mikeyyyzhao** [comment]
is there anyway to set the scheme to http? Google still does not recognize capacitor:// or ionic:// as safe origins in Authorized JavaScript origins for their auth unfortunately

**Comment by malua** [comment]
I was talking about Stripe working, not about Google as mikeyyyzhao was. 
I can definity confirm that stripe works on ionic://.

I have the ios on ionic:// and the android app on https://

**Comment by malua** [comment]
i have not tried that, but I guess you would not work. rather you would have to use this plugin https://github.com/capacitor-community/stripe and handle the payment in the native part

**Comment by madmacc** [comment]
Yeah it looks like it won't work with Ionic.
I got that capacitor plugin working today and it works.

The main issue is that you need to register a merchant id for the plugin (native) but not for the web version.  I would prefer not to register a merchant id for every stripe connected account I am paying to.  Having to set up a merchant id means I would have to release a new version of the app every time a customer joined my platform which is not feasible.
