### ISSUE TITLE
How to embed Android AAR in capacitor plugin?

### ISSUE THREAD

**Issue by SvshX** [ionic-team/capacitor#2174]
Has anyone ever successfully integrated an aar file into a plugin?
My goal is to wrap my Android library in a capacitor plugin.

**Comment by PR1YANKPAT3L** [comment]
I am currently using a aar dependency. You can follow the default steps for importing a standard library.

**File -> New -> New Module -> Import .jar/.aar and import your .aar.**

Then in your project’s build.gradle (the one under ‘app’) add the following:
```
dependencies {
     compile project(‘:Name-of-the-Project’)
}
```

Clean Build after all the above steps.

**Comment by SvshX** [comment]
I guess you talk about a normal capacitor app project, because a capacitor "PLUGIN" doesn't have app level. 
This is what I build: [https://capacitor.ionicframework.com/docs/plugins/](url)

I've done it for iOS this way: [https://stackoverflow.com/questions/58045726/how-to-embed-third-party-framework-on-ionic-capacitor-custom-plugin](url)

That works! The default steps for Android using File -> New -> New Module -> Import .jar/.aar does not work. The project cannot be found.

So you add an AAR dependency to your capacitor app? How you bridge it to JavaScript then?





Anyways, I also import the AAR like in an Android project (New Module etc.) as well as add the AAR project to the dependencies.
However, when I install the capacitor plugin via npm in

**Comment by SvshX** [comment]
Solved it! It was a naming issue.
The npm plugin must have the same name as the aar dependency.

**Comment by PR1YANKPAT3L** [comment]
You might want to close the issue.

**Comment by SvshX** [comment]
False report. It does not fix the issue.

The integrated module is ultimately no longer recognised as a module in the app. As a result, the functions from the AAR module are no longer accessible.

ERROR: Project with path ':Name-of-the-AAR-Project' could not be found in project ':Name-of-the-Capacitor-Project'.

**Comment by jcesarmobile** [comment]
can you provide a sample project of the plugin you created? looks like a problem on your end

**Comment by jcesarmobile** [comment]
closing as there was no response

**Comment by SvshX** [comment]
I'ts still an issue. The project has been cancelled though. No more time is scheduled for this.

**Comment by kas84** [comment]
I am new to capacitor and I'm having an issue where the plugin does recognize the aar but when I npm link the plugin and npm install it, it doesn't.

How can I troubleshoot this @jcesarmobile? I could provide a sample plugin

**Comment by tobika** [comment]
@kas84 I have the same problem, workaround for me is just to add the aar again to my main app where I use the plugin, not very pretty but works

**Comment by kndl22** [comment]
Having the same issue, I want to integrate an aar into my plugin. 
I can successfully export the plugin and install it at my ionic project, but when running 'npm build run' the build fails since it can't find the aar path

@jcesarmobile @priyankpat can you advice here?
