### ISSUE TITLE
Question: What is the correct way of using `cdvfile` within Capacitor?

### ISSUE THREAD

**Issue by terranmarine** [ionic-team/capacitor#2176]
The header speaks of itself. 

If I have something like this `cdvfile://localhost/sdcard/DCIM/100ANDRO/MOV_0787.mp4` that comes from cordova, how can I use it inside capacitor and the Filesystem plugin?

**Comment by jcesarmobile** [comment]
That's a cordova format, you can only use it in cordova plugins.

**Comment by koraysels** [comment]
I have the same issue, I can stat the file i need with the capacitor Filesystem plugin but when I try to load the path into `cordova-media-plugin` it cannot find the file... how are we supposed to convert such cases for capacitor ?

**Comment by terranmarine** [comment]
I ended up using the following code. The context is simple: record a video and send it as file to some API endpoint. 

For anyone else who comes here:
`    private getVideoFromFileSystem = (fileSystem) => {
        // iOS SOLUTION
        if (Capacitor.getPlatform() === 'ios') {
            (<any>window).resolveLocalFileSystemURL(fileSystem, async (fileEntry) => {
                Plugins.Filesystem.readFile({ path: fileEntry.toNativeURL() }).then(
                    async (reps) => {
                        const file = await this.base64toBlob(reps.data, 'mp4');
                        this.sendFilesToServer(file);
                    }
                );
            });
            return;
        }

        // Android solution
        (<any>window).resolveLocalFileSystemURL(fileSystem, async (fileEntry) => {
            fileEntry.file((cordovaFile) => {
                // This came from the shadow realm...
                let FileReader: new () => FileReader = ((window as any).FileReader as any)
                    .__zone_symbol__OriginalDelegate;
                const reader = new FileReader();

                reader.onloadend = async () => {
                    const data = <string>reader.result;
                    const file = await this.base64toBlob(data.slice(data.indexOf(',') + 1), 'mp4');
                    this.sendFilesToServer(file);
                };

                reader.readAsDataURL(cordovaFile);
            });
        });
    };`
