### ISSUE TITLE
E/Capacitor/Console error

### ISSUE THREAD

**Issue by diegorsd** [ionic-team/capacitor#2183]
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.3.0

  @capacitor/core 1.3.0

  @capacitor/android 1.3.0

[success] Android looking great! 👌

> ## Affected Platform(s)
> * [x]  Android
> * [ ]  iOS
> * [ ]  Electron
> * [ ]  Web
> 
> ## Current Behavior
> The following errors running on device

**E/LB: fail to open file: No such file or directory
E/Capacitor/Console: File:  - Line 1 - Msg: Uncaught TypeError: Cannot read property 'triggerEvent' of undefined
    File:  - Line 1 - Msg: Uncaught TypeError: Cannot read property 'triggerEvent' of undefined

E/Capacitor/Console: File: capacitor-runtime.js - Line 11016 - Msg: Uncaught (in promise) String resource ID #0x0**

**Comment by aidan-mundy** [comment]
Currently getting all of the same errors (except the runtime one) on android as well.

**Comment by sabahang** [comment]
same here

**Comment by jcesarmobile** [comment]
can you provide a sample app? I can't reproduce

**Comment by amalfarid** [comment]
I face the same issue 

E/Capacitor/Console: File: chrome-error://chromewebdata/ - Line 1 - Msg: Uncaught TypeError: Cannot read property 'triggerEvent' of undefined

**Comment by jcesarmobile** [comment]
closing since there was no response and I can't reproduce

**Comment by mpacary** [comment]
Got this error when my mobile device was connected to a wrong network.

**Comment by J3m5** [comment]
It happen to me when the app is launched on an android device with a file server on https.
As a side effect, I assume, cordova is not available as a global variable.
"onscript loading complete" is not logged into the remote debugging console whereas on http, the error doesn't occur and the message is logged correctly.

Details:
I'm on capacitor 1.5.2
On https, in the console, the Capacitor platform is Web whereas on http it's Android
I'm using Quasar

@mpacary Can you elaborate, please?
@jcesarmobile Do you need more info to resolve this issue?

Thank you in advance

**Comment by mpacary** [comment]
@J3m5 My mobile device was not connected to the same network as my laptop, then hot reloading did (logically) not work in remote debug mode (using [Quasar Framework](https://quasar.dev/)) & I got a very similar error ; when I'll work again with Capacitor I will try to reproduce & copy/paste here the full error message.

**Comment by lhaiscapyba** [comment]
I had to removed _url_ from 'server' field in **capacitor.config.json** to work for me.

**Comment by josephepia** [comment]
In your `AndroidManifest.xml` inside the` <application> `tag add the following line` android: usesCleartextTraffic = "true" `.
that worked for me. you will see the following form:

```
<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true">           <------- here
```

more information [docs](https://www.it-swarm.dev/es/android/webview-que-muestra-err-cleartext-not-permitted-aunque-el-sitio-es-https/806944862/)

sorry my english i am spanish speaking

**Comment by LasanthaRanga** [comment]
> In your `AndroidManifest.xml` inside the`<application>`tag add the following line`android: usesCleartextTraffic = "true"`.
> that worked for me. you will see the following form:
> 
> ```
> <application
>         android:allowBackup="true"
>         android:icon="@mipmap/ic_launcher"
>         android:label="@string/app_name"
>         android:roundIcon="@mipmap/ic_launcher_round"
>         android:supportsRtl="true"
>         android:theme="@style/AppTheme"
>         android:usesCleartextTraffic="true">           <------- here
> ```
> 
> more information [docs](https://www.it-swarm.dev/es/android/webview-que-muestra-err-cleartext-not-permitted-aunque-el-sitio-es-https/806944862/)
> 
> sorry my english i am spanish speaking


**This works correctly  Thank you very much..**

**Comment by dinith72** [comment]
> I had to removed _url_ from 'server' field in **capacitor.config.json** to work for me.

it worked for me too

**Comment by svrakata** [comment]
As @mpacary said this problem might come from your device being connected to different network than the one the app is running on. I had to connect the (real physical) device via wireless to the same network where the application was running (e.g. in case using ```ionic capacitor run android --livereload --external``` ).
