### ISSUE TITLE
bug: Using Plugins with custom framework break on application level - Module not found error.

### ISSUE THREAD

**Issue by bijanmmarkes** [ionic-team/capacitor#2184]
# Bug Report

## Capacitor Version
1.3.0

`npx cap doctor` output:
`Withing Demo App:`
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.3.0

  @capacitor/core 1.3.0

  @capacitor/ios 1.3.0


  Found 1 Capacitor plugin for ios:
    capacitor-plugin-mycustomplugin (0.0.1)
[success] iOS looking great! 👌
```

## Affected Platform(s)
Currently only working with iOS / Pod

- [ ] Android
- [x ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
1. I have a custom cocoa framework I created with Swift 5, the plugin builds perfectly.
2. I generated a capacitor plugin using the `plugin:generate` command, imported my custom cocoa framework using the Podfile, and the plugin built successfully, and I had 0 issues on the plugin level..

NOW - Here is the issue:

3. I generated a fresh ionic capacitor demo app using the CLI - I used npm install to install my capacitor plugin which has my custom framework imported - But when trying to build it via the xcodeworkspace, it throws the error within the plugin, that the custom framework cannot be found on import, hence causing the capacitor demo app to fail it's build.

How am I supposed to incorporate a custom plugin which has custom frameworks in use inside a capacitor application???

This has been blocking me for days, I am so close to just going back to Cordova, as I've never had these type of issues.

## Expected Behavior

Using npm install to install a capacitor plugin which is using third-party frameworks should properly install the required pods. What am I missing?

**Comment by bijanmmarkes** [comment]
Guessing this won't be answered? I've already switched back to Cordova and all is working fine.

**Comment by jcesarmobile** [comment]
Can you provide the plugin you are creating?
The most likely problem is that you didn't add your framework on the .podspec file

**Comment by jcesarmobile** [comment]
closing since there was no response

but just as a note, if you add a framework, you have to add it on the podspec, not the Podfile

**Comment by mrunwal** [comment]
I have similar situation but in android prospective. so what would be the steps ?
e.g.
I have create custom plugin. Its entry is visible in package.json but at the ionic if I import 'myPackage' with same name its not appearing.
