### ISSUE TITLE
feat: Provide documentation on how to embed capacitor into an existing native app

### ISSUE THREAD

**Issue by merlinchen** [ionic-team/capacitor#2187]
# Feature Request

## Describe the Feature Request
Provide documentation on how to embed capacitor into an existing native app.
Some native app may need to manually present capacitor powered webview.
## Platform Support Requested
- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
A Step by Step guide.

**Comment by dwieeb** [comment]
I am going to close this because achieving embedded Capacitor isn't just a documentation issue and it will require quite the endeavor. It is something we're interested in for Capacitor 3, though.
