### ISSUE TITLE
feat: API to run platform-specific executables/commands

### ISSUE THREAD

**Issue by hugetiny** [ionic-team/capacitor#2188]
# Feature Request

## Describe the Feature Request
The dart:io Process API runs/works platform-specific executables  in Flutter apps. Is there a similar api for capacitor to run platform-specific executables
## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
Add api for capacitor to run platform-specific executables

**Comment by hugetiny** [comment]
here is the dart:io api
https://api.dartlang.org/stable/2.5.0/dart-io/Process-class.html
I wish to run commands like 'ls','pwd','ping' etc.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
