### ISSUE TITLE
The file plugins does not work with capacitor

### ISSUE THREAD

**Issue by profe1000** [ionic-team/capacitor#2189]
The file plugins does not work with capacitor

**Comment by PR1YANKPAT3L** [comment]
What have you tried? Do you have any sample code? You should also follow the [template](https://github.com/ionic-team/capacitor/blob/df6bd87183a25bf2b98043c39470b09c15b769d3/.github/ISSUE_TEMPLATE/bug-report.md) when creating new issues.

**Comment by jcesarmobile** [comment]
closing since it's not clear what your problem is and you didn't answer the questions
