### ISSUE TITLE
Built app does not render any elements on the screen

### ISSUE THREAD

**Issue by aidan-mundy** [ionic-team/capacitor#2190]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.3.0

  @capacitor/android 1.3.0

  @capacitor/core 1.3.0

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Using Quasar's dev server (`quasar dev -m capacitor -T android`) the app loads just fine, but after building with capacitor (`quasar build -m capacitor -T android`) the app is blank when installed on a phone. I loaded a debug version of the app (that runs html/js from the webserver on an android device `quasar build -m capacitor -T android --dev`) and Android Studio's debug tool reported some errors from capacitor that look concerning but have minimal info online. 

## Expected Behavior
App displays on screen when built into an APK and loaded on phone.

## Sample Code or Sample Application Repo

https://github.com/aidan-mundy/quasartest/tree/master/src-capacitor
(Because of quasar's nonstandard setup, some resources may be up a folder in quasartest)

## Reproduction Steps

1. `quasar dev -m capacitor -T android` the app loads just fine
2. `quasar build -m capacitor -T android` then sign app and load on phone or emulator, it will be blank.
3. `quasar build -m capacitor -T android --dev` and use Android Studio's debug tool to see errors listed below. 

## Other Technical Details

`npm --version` output: 6.13.1

`node --version` output: v12.13.0

## Other Information

Debug log with all lines:
https://gist.github.com/aidan-mundy/75cbb0cd1383ba04e5e91c293189985d
Specific error lines related to capacitor (in no particular order, lines with no mention of capacitor omitted):
`E/Capacitor: Unable to read file at path public/plugins`

`E/Capacitor/Plugin/Browser: Error binding to custom tabs service`

`E/Capacitor/Console: File: https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_US.2O_3XQTFIPY.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCM0JjSA0I0wvcxN0q5y4p-sc5Yxiw/cb=gapi.loaded_0 - Line 151 - Msg: Uncaught [object Object]`
(this one is likely my fault because I have an invalid Google Sign In setup right now)

`E/Capacitor/Console: File: http://10.0.0.54:8080/#/ - Line 1 - Msg: Uncaught TypeError: window.Capacitor.triggerEvent is not a function`
(quasar dev server is running at that IP)

**Comment by haliccatalin** [comment]
go to "capacitor.config.json" file and remove "server": { "url":""}

**Comment by jcesarmobile** [comment]
this was a quasar bug, was fixed in @quasar/app 1.3.4

https://github.com/quasarframework/quasar/issues/5824
