### ISSUE TITLE
feat: `getBadgeCount` and `setBadgeCount` methods for notifications

### ISSUE THREAD

**Issue by rossholdway** [ionic-team/capacitor#2192]
# Feature Request

## Describe the Feature Request
iOS (and some Android) notification payloads often contain the number of unread notifications, however currently this value can't be used. Support setting and getting the notification badge count by implementing `getBadgeCount` and `setBadgeCount` methods.

I notice this feature has been mentioned in other issues too (#1301 #837 etc). It is also currently a supported feature of the phonegap push plugin. See `push.setApplicationIconBadgeNumber` and `push.getApplicationIconBadgeNumber` at https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
Add `getBadgeCount` and `setBadgeCount` methods

**Comment by scriptPilot** [comment]
Is there any workaround with the current **LocalNotifications** plugin?

**Comment by rossholdway** [comment]
Unfortunately not that I can see from the Capacitor local notifications docs

**Comment by scriptPilot** [comment]
@rossholdway - Do you found another solution? I did not found proper documentation how to use the Cordova plugins unfortunately ... (see https://github.com/ionic-team/capacitor/issues/2195).

**Comment by rossholdway** [comment]
@scriptPilot No, sorry haven't found another way to do this.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Note that this is not officially supported on Android. It's only possible in a few vendors. There is a 3rd party library to handle those called shortcutBadger and we don't plan to add that dependency just for this feature, so I think it fits better in a 3rd party plugin

**Comment by dminkovsky** [comment]
This looks promising: https://github.com/katzer/cordova-plugin-badge

Haven't tried it yet, but intend to.

**Comment by shide1989** [comment]
@dminkovsky this plugins hasn't been updated since 3 years. As @jcesarmobile mentionned, it's best to try using `shortcutBadger` plugin

**Comment by nelsonjimartinez** [comment]
> Los problemas etiquetados con solicitud de función se cierran, pero se realiza un seguimiento de las reacciones para medir el interés.
> 
> Tenga en cuenta que esto no es compatible oficialmente con Android. Solo es posible en unos pocos proveedores. Hay una biblioteca de terceros para manejar los llamados shortcutBadger y no planeamos agregar esa dependencia solo para esta función, así que creo que encaja mejor en un complemento de terceros

https://developer.android.com/training/notify-user/badges
