### ISSUE TITLE
bug: Storage does not hold it's value on app re-launches (iOS)

### ISSUE THREAD

**Issue by jbonigomes** [ionic-team/capacitor#2193]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Latest Dependencies:
  @capacitor/cli: 1.3.0
  @capacitor/core: 1.3.0
  @capacitor/android: 1.3.0
  @capacitor/ios: 1.3.0

Installed Dependencies:
  @capacitor/android 1.3.0
  @capacitor/core 1.3.0
  @capacitor/ios 1.3.0
  @capacitor/cli 1.3.0

## Affected Platform(s)

- [ ] Android
- [ x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I would expect the values to be present when re-launching the app, but storage is empty. Data does not persist across re-launches.

## Expected Behavior

Would be able to access previously stored values on app re-launch.

## Sample Code or Sample Application Repo

`
import { Plugins } from '@capacitor/core'
const { Storage } = Plugins
Storage.set({ key: 'aKey', value: JSON.stringify({...someObj}) })
`

## Reproduction Steps

- Create a React component that saves user input into 'Storage' and display it on screen
- On iOS app re-launch, expect to see the previously stored data

## Other Technical Details

`npm --version` output: 6.12.0

`node --version` output: v12.13.0

`pod --version` output (iOS issues only): 1.8.4

## Other Information

If this is the intended behaviour (Storage is ephemeral), would SQLite be the right go to choice? If I do not want to use a community plugin, are there any good examples on how to use SQLite with Capacitor directly?

**Comment by jbonigomes** [comment]
Nevermind, closing this issue, it happened because I set the 'key' of my items to be a number, it **MUST** be a string.

**Comment by wasimbakali** [comment]
@jbonigomes jbonigomes Can you please provide example? because I have used string key but still having this issue only in IOS.

**Comment by jbonigomes** [comment]
Hi @wasimbakali the value has to be a string as well.

**Comment by wasimbakali** [comment]
yes i am doint same here is my code.

`    import { Plugins } from '@capacitor/core';
    const { Storage } = Plugins;

    public setStoragedata (keyname: string, data: any) {
        
     return new Promise(resolve => {
       Storage.set({key: keyname, value: JSON.stringify(data)})
      .then(result => {resolve(result)})
      .catch(e => resolve(false));
     })
    }

    public getStoragedata (keyname: string) {
       return new Promise(resolve => {
        Storage.get({key: keyname})
         .then(result => { resolve(result.value); })
          .catch(e => resolve(false));
      })
     }`

**Comment by jbonigomes** [comment]
@wasimbakali, I've reopened the issue in case someone else has an answer.

**Comment by jcesarmobile** [comment]
I can't reproduce on capacitor 3 and the new @capacitor/storage plugin

If people still face this issue, please, report it on https://github.com/ionic-team/capacitor-plugins/issues and provide a sample app where it can be reproduced
