### ISSUE TITLE
feat: mobile screenshots

### ISSUE THREAD

**Issue by 2x2xplz** [ionic-team/capacitor#2194]
# Feature Request

## Describe the Feature Request
I'd like the Capacitor API be able to take full-screen screenshots on mobile devices.

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Cordova has this project: https://github.com/gitawego/cordova-screenshot
Even better than a separate project would be to have the capability baked into the API

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/10. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
