### ISSUE TITLE
Improve Cordova Plugin documentation

### ISSUE THREAD

**Issue by scriptPilot** [ionic-team/capacitor#2195]
I want to use a Cordova plugin for [local badge updates](https://github.com/katzer/cordova-plugin-badge). After reading the [documentation](https://capacitor.ionicframework.com/docs/cordova/using-cordova-plugins/), it's still not clear to me how to use the plugin properly in my Capacitor app.

Herewith I kindly ask to update the documentation accordingly and propose a solution.

**Comment by dotNetkow** [comment]
Thanks for the feedback. In the docs, we have:

```
npm install cordova-plugin-name
npx cap sync
```

In this case, the plugin name is "cordova-plugin-badge" so you'd run:

```
npm install cordova-plugin-badge
npx cap sync
```

I'm honestly not sure how to make that more clear, but I'd love to know: do you have any suggestions?

**Comment by kodemi** [comment]
Maybe documentation could describe how to manually apply configuration by mapping between the plugin's plugin.xml and required settings on iOS and Android?

**Comment by dotNetkow** [comment]
@kodemi yes, good catch. On the same page, we have [this paragraph](https://capacitor.ionicframework.com/docs/cordova/using-cordova-plugins/#important-configuration) that directs you to exactly that.

**Comment by scriptPilot** [comment]
@dotNetkow - Maybe I missed something. For me it's not clear how to use the plugin ... window.Cordova is undefined. Do you have an example somewhere?

**Comment by htorbov** [comment]
> @dotNetkow - Maybe I missed something. For me it's not clear how to use the plugin ... window.Cordova is undefined. Do you have an example somewhere?

Exactly! We're well aware how to `npm install`, but what next? How do we call a plugin?

I just opened an issue for that: https://github.com/ionic-team/capacitor/issues/2256

I tried like 143145312 things.

@dotNetkow are there any additional instructions?

**Comment by jcesarmobile** [comment]
You use the plugin the same way you would use it in a Cordova project.

The plugin uses `cordova`, not `Cordova`, case matters.
