### ISSUE TITLE
Touch pointer move a lot

### ISSUE THREAD

**Issue by naturalfreak** [ionic-team/capacitor#2197]
I'm using angular blank application after build apk for android and install on the application on real device and scroll fast the screen, there is a lag.  I got this message on console. 
This only happens on a real device

Tested devices:

Device Huawei p30 lite with Android v9.1
Device Nokia 8.1 with Android 10

```
W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:13.311218, limit is:60The moving distance of Y is:93.05371, limit is:60
W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:2.6289978, limit is:60The moving distance of Y is:70.385864, limit is:60
I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
```
OS Ubumtu 16.04
Node v12.13.1
npm - 6.13.1

capacitor doctor

```
 💊  Capacitor Doctor  💊 

  @capacitor/ios not installed
  @capacitor/cli 1.3.0
  @capacitor/android 1.3.0
  @capacitor/core 1.3.0

[success] Android looking great! 

```
EDITED:

Аfter debugging it turned out that lag was caused by svg file on the bottom of the page. I'm not sure how it is related but after removing this svg, everything works as expected.

`<img src="/assets/images/play-store.svg" width="175px" height="70px" />`

**Comment by jcesarmobile** [comment]
doesn't look related to Capacitor
