### ISSUE TITLE
Browser.addListener browserFinished not fired on android

### ISSUE THREAD

**Issue by tebantebanteban** [ionic-team/capacitor#2202]
browserFinished not fired when close Browser on android. on iOS works fine

**Comment by dhulme** [comment]
Looking at the code doesn't look like it's been implemented?
https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/Browser.java

**Comment by timofeysie** [comment]
That link does appear to have no implemented addListener methods.  There is one for open:
``` 
@PluginMethod()
  public void open(PluginCall call) {
```
This is the only thing that seems to work...
But the [docs](https://capacitor.ionicframework.com/docs/apis/browser/) show two listeners...
