### ISSUE TITLE
https://capacitor.ionicframework.com/ website is down any idea?

### ISSUE THREAD

**Issue by jakupi1** [ionic-team/capacitor#2203]
[![image](https://i.hizliresim.com/vaWlnz.png)](https://hizliresim.com/vaWlnz)

**Comment by tebantebanteban** [comment]
<img width="1680" alt="Captura de Pantalla 2019-11-22 a la(s) 15 15 44" src="https://user-images.githubusercontent.com/31634150/69450235-77a8bc80-0d3b-11ea-9f4c-6ff7a883c683.png">

Here works fine 👀

**Comment by jakupi1** [comment]
@tebantebanteban what may be the problem any idea?

**Comment by bryplano** [comment]
I would wager Cloudflare is having some kind of issue today (even though their status page says they are not: https://www.cloudflarestatus.com/). Our site has not been the only one affected today - I've seen this elsewhere too (npmjs.com for example).

Try clearing your browser cache and give it another shot, or try again later :)

**Comment by SlavenIvanov** [comment]
Hi  @bryplano , https://capacitor.ionicframework.com/ seems to be down again .
![image](https://user-images.githubusercontent.com/25117060/69990115-bdd8f980-154d-11ea-9617-5d9fc437e3a9.png)

**Comment by bryplano** [comment]
@SlavenIvanov - I would recommend waiting a bit and trying again. I have no issues accessing the site today (US-based), so it could be another temporary Cloudflare issue similar to the first time this issue was posted where most people can access the site but a few could not. Sorry about that :\

**Comment by SlavenIvanov** [comment]
@bryplano I noticed that the author of the bug is in the same city as me. And I have not been able to access the Capacitor website for close to a month. Is there anything I can do to help with this issue ?

**Comment by bryplano** [comment]
@SlavenIvanov - it's possible your ISP or local government is blocking the site in some manner, or there's some issue with your local environment. Our servers have been up and fine :\
