### ISSUE TITLE
capacitor-google-maps plugin without ionic 

### ISSUE THREAD

**Issue by tototares** [ionic-team/capacitor#2204]
Is there any possibility to use the capacitor-google-maps plugin without ionic? I use Capacitor in my Angular project and want to integrate native google maps support. I don't want to use the google web static maps api.

**Comment by bryplano** [comment]
You'll want to ask that on the plugin repo, not here: https://github.com/joshuamorony/capacitor-google-maps

We can't verify every community plugin, so I would suggest either trying it out or asking the community in the Capacitor Slack: https://getcapacitor.herokuapp.com/
