### ISSUE TITLE
bug: cordova-plugin-swrve compatibility issue on iOS

### ISSUE THREAD

**Issue by TCCJay** [ionic-team/capacitor#2209]
# Bug Report

## Capacitor Version
`npx cap doctor` output:
Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/cli 1.3.0

  @capacitor/android 1.3.0

  @capacitor/core 1.3.0

  @capacitor/ios 1.3.0

## Affected Platform(s)

- [] Android
- [o ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Throwing the compilation errors on iOS:
Property 'webview' not found on object of type 'CDViewController *' SwrvePlugin.m

## Expected Behavior
Runs without compilation errors

## Sample Code or Sample Application Repo

I don't have the sample code but the this link is probably a point of failure (https://github.com/ionic-team/capacitor/blob/master/ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVViewController.m)

## Reproduction Steps
1. Install cordova-plugin-swrve (2.0.1)
2. npx cap sync
3. run ios project

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

## Other Information

**Comment by jcesarmobile** [comment]
I've sent a PR that avoids the build failure, but the plugin won't work, plugins that rely on CDVViewController won't work because Capacitor uses CAPBridgeViewController instead.
