### ISSUE TITLE
bug: ion-input autofill does not work

### ISSUE THREAD

**Issue by cmaas** [ionic-team/capacitor#2211]
# Bug Report

Autofill such as username and password doesn't work on `ion-input` in a Capacitor environment, but it does in iOS Safari. This bug was described in the regular ionic bug tracker, altough it seems to be related to Capacitor. See: https://github.com/ionic-team/ionic/issues/19478

## Capacitor Version

`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/cli 1.3.0

  @capacitor/android 1.3.0

  @capacitor/core 1.3.0

  @capacitor/ios 1.3.0

## Affected Platform(s)

- [ ] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

See original issue at https://github.com/ionic-team/ionic/issues/19478

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by cmaas** [comment]
Update: Possibly not a Capacitor bug, since the same happens in a non-Capacitor lightweight webview wrapper I used.

**Comment by bryplano** [comment]
This is a WebKit bug that we'll need Apple to fix - see https://bugs.webkit.org/show_bug.cgi?id=203299 (also mentioned in https://github.com/ionic-team/ionic/issues/19478).

**Comment by danielehrhardt** [comment]
This issue is more than half a Year old. Really bad that Apple is not looking in to that Issue.

**Comment by f1ght4fun** [comment]
is there actually an issue - as having setup everything (associated domains, webcredentials, password autofill provider etc) and having tried both with simple ion-input, with html input - nothing works for me on latest ios safari and capacitor versions.

It does fill values in background but until you focus it doesnt call change event on the shadow dom input. None of the directive or workarounds help with that.

Can anyone share snippets of actually working workaround pls!
