### ISSUE TITLE
"Native progressive web app" explanation

### ISSUE THREAD

**Issue by eeerrrttty** [ionic-team/capacitor#2214]
This term is new, so i think it requires a lot more explanation to it, comparison with common cordova apps and comparison to real native apps, will "native progressive web app" be faster than cordova ? Will it perform like a native app? 

This requires a lot more of info for people to jump into it.

Quasar now is with capacitor build option, so it will receive a lot more options for devs, as now we are powered by both angular and vuejs with strong frameworks

**Comment by jcesarmobile** [comment]
This is the text you refer to:
> Capacitor is a cross-platform app runtime that makes it easy to build web apps that run natively on iOS, Android, Electron, and the web. **We** call these apps "Native Progressive Web Apps".

I've put the We in bold, it's just a name we used, and it's quoted. 

Basically, they can be packaged as native apps for iOS, Android or Electron, and run as Progressive Web App on the web, with the same code base you can build all of them, unlike Cordova, when that was written didn't have Electron support, and for making them work as a web you required a lot of additional changes.
But other than that, Capacitor apps use WebViews, it's also on the docs, so not very different from Cordova, just simpler.
