### ISSUE TITLE
bug: Installing missing dependency loops forever with cordova-plugin-chrome-apps-common

### ISSUE THREAD

**Issue by xurxofp** [ionic-team/capacitor#2217]
# Bug Report
The cordova-plugin-chrome-apps-common is causing a dependency install loop on npx cap sync:

```
npx cap sync
✔ Copying web assets from www to android/app/src/main/assets/public in 668.68ms
✔ Copying native bridge in 2.36ms
✔ Copying capacitor.config.json in 1.48ms
⠧ copy  Found 2 Cordova plugins for android
    cordova-plugin-chrome-apps-common (1.0.7)
    cordova-plugin-chrome-apps-sockets-udp (1.3.0)
✔ copy in 835.77ms
✔ Updating Android plugins in 13.83ms
[info] installing missing dependency plugin cordova-plugin-chrome-apps-common@1
✔ Updating Android plugins in 13.55ms
[info] installing missing dependency plugin cordova-plugin-chrome-apps-common@1
✔ Updating Android plugins in 10.81ms
[info] installing missing dependency plugin cordova-plugin-chrome-apps-common@1
✔ Updating Android plugins in 4.93ms
[info] installing missing dependency plugin cordova-plugin-chrome-apps-common@1
✔ Updating Android plugins in 5.60ms
[info] installing missing dependency plugin cordova-plugin-chrome-apps-common@1
```
And it goes forever...

## Capacitor Version

`npx cap doctor` output:
```
Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.3.0

  @capacitor/core 1.3.0

  @capacitor/android 1.3.0

```

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Reproduction Steps

Just creating a blank project and installing the plugin:

```
ionic start test blank --type=angular
npm install --save @capacitor/core @capacitor/cli
npx cap init
npx cap add android
npm install cordova-plugin-chrome-apps-sockets-udp
npx cap sync
```

## Other Technical Details

```
Ionic:

   Ionic CLI                     : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.2.0 (/usr/local/Cellar/node/13.2.0/bin/node)
   npm    : 6.13.1
   OS     : macOS Catalina
```

**Comment by bryplano** [comment]
This is probably an incompatible plugin, considering the last publish to it was [5 years ago](https://www.npmjs.com/package/cordova-plugin-chrome-apps-common). :\

**Comment by jcesarmobile** [comment]
This is really a problem in the plugin `cordova-plugin-chrome-apps-sockets-udp`, the dependencies are not using proper syntax, it has a PR that should fix it, but has not been merged after almost 3 years.

Anyway, the CLI could easily handle this by removing the `@1` part when looking for dependencies. 

https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp/pull/20/files

**Comment by parthnayak7448** [comment]
How to solve this can anyone help please with proper step instead of linking the commit it will be appreciated thanks

**Comment by unitree-czk** [comment]
> How to solve this can anyone help please with proper step instead of linking the commit it will be appreciated thanks

Please see my plugin, capacitor-udp

**Comment by unitree-czk** [comment]
I have written a udp plugin for capacitor. Feel free to check it out!

capacitor-udp
