### ISSUE TITLE
bug: On android "release" build Device.getInfo().platform is returning "web" when minifyEnabled set to true

### ISSUE THREAD

**Issue by orhan-swe** [ionic-team/capacitor#2218]
# Bug Report
On android "release" build Device.getInfo().platform is returning "web" (bug)
On android "debug" build Device.getInfo().platform is returning "android"

I have run the test on physical device Samsumng S9 and on emulator "Pixel 2 API 29"

The strangest thing is that issue is only showing up on android "release" build and is not showing up on the "debug" build. The debug build is returning "android" correctly. 

It is working correctly on ios and web platforms.

## Capacitor Version
1.3.0

`npx cap doctor` output:
@capacitor/cli 1.3.0
  @capacitor/android 1.3.0
  @capacitor/core 1.3.0
  @capacitor/ios 1.3.0

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

On android "release" build Device.getInfo().platform is returning "web".

## Expected Behavior

On android "release" build Device.getInfo().platform should return "android".

## Sample Code or Sample Application Repo
        let info = await Device.getInfo();
        alert("Your platform is: " + info.platform)

## Reproduction Steps

Build the project in Android as a "release"  and run it, alert will show "your platform is web"
If you build it as "debug" it will show correct behavior.

**Comment by orhan-swe** [comment]
I have tested this on a sample app on another computer and there the behavior is correct. So this has something to do with my app/computer environment. I will investigate further and update this item within a day or two. Otherwise this can be closed.

**Comment by orhan-swe** [comment]
I have managed to reproduce this on a sample project also. The issue only occurs when apps build.gradel has minifyEnabeld set to true.
I would suggest adding this to documentation: never set minifyEnabled to true as it can cause unpredictable behavior!

**Comment by jcesarmobile** [comment]
it's a known issue, already reported here https://github.com/ionic-team/capacitor/issues/739
