### ISSUE TITLE
feat: Add support for electron 7.x

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/capacitor#2219]
# Feature Request

## Describe the Feature Request

Requesting to add Electron 7.x and 8.x support to capacitor.

## Platform Support Requested

- [ ] Android
- [ ] iOS
- [x] Electron
- [ ] Web

Hi. I was trying to run the sample app in this repository (as well as my own) with electron. It worked only with 4.x but not with 7.1

Would be great to add 7.1 support since 4.x is a bit too old with no ES6 support. Thanks.

**Comment by tvvignesh** [comment]
splashScreen.init breaks in 7.1 due to this issue (open in electron): https://github.com/electron/electron/issues/20700

Also, when you add server.url in capacitor.config.json the electron app still loads the local index.html file. We have to rather go inside the js file and add `mainWindow.loadURL` instead of `mainWindow.loadFile` and then it works.

**Comment by bryplano** [comment]
8.X is not addressed, but 7.X support will be out for new apps with the next release: https://github.com/ionic-team/capacitor/pull/2084
