### ISSUE TITLE
bug: IOS local images are not being displayed

### ISSUE THREAD

**Issue by frabaddo** [ionic-team/capacitor#2225]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/cli 1.2.1

  @capacitor/core 1.2.1

  @capacitor/android 1.3.0

  @capacitor/ios 1.3.0

[success] Android looking great! 👌
  Found 24 Capacitor plugins for ios:
    @codetrix-studio/capacitor-google-auth (1.4.0)
    capacitor-branch-deep-links (1.0.0)
    com-sarriaroman-photoviewer (1.2.4)
    cordova-clipboard (1.3.0)
    cordova-plugin-advanced-http (2.1.1)
    cordova-plugin-app-version (0.1.9)
    cordova-plugin-browsertab (0.2.0)
    cordova-plugin-buildinfo (2.0.3)
    cordova-plugin-camera (4.1.0)
    cordova-plugin-compat (1.2.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-filepath (1.5.6)
    cordova-plugin-inappbrowser (3.1.0)
    cordova-plugin-ionic-keyboard (2.1.3)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.4)
    cordova-plugin-x-socialsharing (5.6.2)
    cordova-plugin-x-toast (2.7.2)
    cordova-support-google-services (1.3.2)
    es6-promise-plugin (4.2.2)
    phonegap-plugin-multidex (1.0.0)
    phonegap-plugin-push (2.3.0)
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Hi, we are trying to migrate our project from Cordova to Capacitor but we cannot display locally saved images on iOS while on Android is working correctly. 

Img saved in tmp directory, as the img get with camera plugin, are rendered, while all img saved in cache or Data aren’t
(We are saving images in a subdirectory “downloads” both in cache and data)

We are using capacitor Fylesystem to save and retrive images from the device.
(cordova-plugin-file-transfer to download the img)

To get the native path of an image we use capacitor.convertFileSrc and ion-img to display it.

In iOS ,the path is correctly formatted, it starts with “capacitor://“  and we know that the file exists at the given path.

When we try to display the image by using domsanitizer.bypassSecurityTrustResourceUrl we get the url that is transformed into: “SafeValue must use [property]=binding: capacitor://localhost …” and the image is not displayed. Obliviously we are using property binding to assign the src property.

Without sanitising the url the image is not displayed and ion-img emits an error.

## Expected Behavior

to be able to show loacaly saved img in ios as in android.
## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.16.0

`pod --version` output (iOS issues only): 1.8.4

**Comment by jcesarmobile** [comment]
can you provide a sample app?
that looks like an angular problem on your side

**Comment by jcesarmobile** [comment]
closing as there was no response and I can't reproduce

**Comment by Eldo** [comment]
Hi @jcesarmobile. I'm having issues showing downloaded images and videos in ionic capacitor. Images and video exist in folder. I want to run the downloaded files offline.

Here's what the Local URL looks like http://localhost/_capacitor_file_/storage/emulated/0/folder/image/img.jpg

**Comment by LousyJohnny** [comment]
Did you manage to make it work ?
I have the exact same issue, and I can't find  a sample app or clear documentation on how to do tis.
