### ISSUE TITLE
feat: provide WebViewClient accessor on bridge

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#2230]
Some plugins or scripts might want to modify or augment the WebViewClient.

Android webView has a getWebViewClient method, but requires API 26.

Would be good if the bridge could provide a getWebViewClient method itself that returns the WebViewClient being set by Capacitor.

Also we should use a WebViewClient subclass that can be subclassed to make it easier to override unimplemented methods (or the implemented ones if needed).

**Comment by cepages** [comment]
@jcesarmobile is there any documentation that helps me to use this feature? Thanks
