### ISSUE TITLE
bug: Android platform load page from remote server print error

### ISSUE THREAD

**Issue by 2018Cool** [ionic-team/capacitor#2232]
# Bug Report

## Affected Platform(s)

- [ ] Android

## Current Behavior

I want to load page from remote server, like this
```
window.onload = async() => {
  const status = await Network.getStatus()
  if (env === 'production') {
    const devInfo = await Device.getInfo()
    url = `https://xxx.file.myqcloud.com/TrendOS-APP/index.html`
  } else if (env === 'development') {
    url = 'http://10.107.117.177:8080/app/index.html?' + Date.now()
  }
  if (!status.connected) {
    SplashScreen.hide()
    showConfirm('暂无网络连接，请检查网络后重试')
  } else {
    location.replace(url)
  }
}
```

## Expected Behavior

I modified capacitor's WebViewLocalServer.java file and fixed this bug.
![image](https://user-images.githubusercontent.com/12771178/70406924-4f2ffa80-1a7d-11ea-9a98-88f2109925ca.png)

## Other Information

In android studio print this error
![image](https://user-images.githubusercontent.com/12771178/70406727-a41f4100-1a7c-11ea-8d8d-2dc9e7f96030.png)

**Comment by jcesarmobile** [comment]
Capacitor 1.4.0 had changes on that line, so not sure if this is still a problem.
Try updating and if you still face the issue, create a new issue with a sample project where it can be reproduced easily.
