### ISSUE TITLE
`npx cap add ios` on Windows

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#224]
Right now one unfortunately gets this error message when running `npx cap add ios` on Windows:
```
λ npx cap add ios
C:\Projects\...\node_modules\@capacitor\cli\bin\capacitor
[error] Not running Mac OS X, can't add ios platform
```

That's pretty unfortunate, as one should be able to do everything but actually build the platform on Windows.

**Comment by jcesarmobile** [comment]
Buy a mac 💻

Yeah, we can probably let users add the platform and get the Xcode project despite they can't open it. I see no harm.

If you have ruby, CocoaPods and node, shouldn't be a problem.

**Comment by janpio** [comment]
I have a few Mac but they are all 💩 

Are ruby, CocoaPods and node needed just to add the platform?

**Comment by jcesarmobile** [comment]
Yeah, when you add the platform, sync is also executed, and sync execute update which requires CocoaPods, and CocoaPods require Ruby. But not really sure if CocoaPods will work fine on windows.

If you don't have node then capacitor won't work, we can assume they have it already, and it's mentioned in the docs.

**Comment by IT-MikeS** [comment]
Without node, they will have a bad time using npm and making their project to begin with :rofl:

**Comment by mlynch** [comment]
Added this, it just skips the sync and adds the template content.

**Comment by dwieeb** [comment]
I am still getting this error in alpha.37 on Windows:

```
[error] Not running Mac OS X, can't add ios platform
```

More context: https://github.com/ionic-team/ionic-cli/issues/3129#issuecomment-388603972

**Comment by baranelitez** [comment]
Me too. Still prints [error] Not running Mac OS X, can't add ios platform when I try generating project files.
