### ISSUE TITLE
bug: Back button does not work for allowNavigation domains in Android

### ISSUE THREAD

**Issue by rachelpopa** [ionic-team/capacitor#2241]
# Bug Report

## Capacitor Version
1.4.0

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Since the fix in 1.4.0, we can configure domains in allowNavigation and navigate to them within the same browser as our Ionic app.  However, the back button in Android does not work, so we cannot return to the app.

## Expected Behavior
When navigating to an external link that is specified in allowNavigation, I should be able to hit the Android back button and navigate back like any web page.

## Reproduction Steps

1) Create a basic Ionic app
2) Set any external website in allowNavigation in capacitor.config.json
3) Create a link to that website within the Ionic app
4) Run the Ionic app on an Android device or emulator
5) Click the link within the Ionic app to open the external website
6) Hit the Android back button and note that it does nothing
7) Navigate deeper into the external website and note that the back button does not work at all, as it normally would in a browser.

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.16.3

**Comment by jcesarmobile** [comment]
I can't reproduce in an app that doesn't use any framework.
Your framework is probably adding an event listener to backButton, and if Capacitor detects a listener for backButton, then it doesn't do the default back and let the app handle it.
