### ISSUE TITLE
issue: capacitor sync forces podfile to install new version of library which has been archived 

### ISSUE THREAD

**Issue by barrcodes** [ionic-team/capacitor#2242]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Installed Dependencies:

  @capacitor/cli 1.3.0

  @capacitor/ios 1.3.0

  @capacitor/core 1.3.0

  @capacitor/android 1.3.0

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
**this is particularly an issue on CI agents where I must sync every time**

`npx cap sync` nukes any attempt I make to force a lower podspec version of a cordova plugin.

AppCenter SDK has archived a build (version 2.5.2), which causes the following error during pod install:

```
Installing AppCenter (2.5.2)

[!] Error installing AppCenter
[!] /usr/local/opt/curl/bin/curl -f -L -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20191212-872-147z9/file.zip https://github.com/microsoft/appcenter-sdk-apple/releases/download/2.5.2/AppCenter-SDK-Apple-2.5.2.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

 My project includes:
- cordova-plugin-appcenter-analytics
- cordova-plugin-appcenter-crashes

A full build, running `npx cap sync` to ensure dependencies are up-to-date on my build agent results in the following pod files:

**CordovaPluginsStatic.podspec**

```
  Pod::Spec.new do |s|
    ...
    s.dependency 'AppCenter', '~> 2.5.0'
    s.dependency 'AppCenter/Analytics', '~> 2.5.0'
    s.dependency 'AppCenter/Crashes', '~> 2.5.0'
  end
```

Which says >= 2.5.0 up to 2.5.X. This generates the following **podfile.lock**:

```
PODS:
  - AppCenter (2.5.2):
    - AppCenter/Analytics (= 2.5.2)
    - AppCenter/Crashes (= 2.5.2)
  - AppCenter/Analytics (2.5.2):
    - AppCenter/Core
  - AppCenter/Core (2.5.2)
  - AppCenter/Crashes (2.5.2):
    - AppCenter/Core
  - Capacitor (1.3.0):
    - CapacitorCordova (= 1.3.0)
  - CapacitorCordova (1.3.0)
  - CordovaPlugins (1.3.0):
    - CapacitorCordova
  - CordovaPluginsStatic (1.3.0):
    - AppCenter (~> 2.5.0)
    - AppCenter/Analytics (~> 2.5.0)
    - AppCenter/Crashes (~> 2.5.0)
    - CapacitorCordova
```

## Expected Behavior
I would like to be able to specify the pod version to install (2.5.1) in some way. Perhaps this functionality is already available in the package.json, but I've been doing a lot of googling today, and not finding what I need.

## Reproduction Steps

- Create project
- npx cap plugin add cordova-plugin-appcenter-analytics
- npx cap plugin add cordova-plugin-appcenter-crashes
- ionic build && npx cap copy && npx cap sync
- version will always be 2.5.2

## Other Technical Details

`npm --version` output:
6.10.2

`node --version` output:
12.9.1

`pod --version` output (iOS issues only):
1.8.4

**Comment by bryplano** [comment]
As of 1.4.0 you can make use of the `--deployment` flag for `npx cap sync` and `npx cap update`, which prevents your Podfile from being removed. That should help with your scenario - from the GH issue on AppCenter, sounds like 2.5.1 is a bad build.

See https://github.com/ionic-team/capacitor/pull/2222 and https://github.com/ionic-team/capacitor/issues/2200

**Comment by barrcodes** [comment]
Thank you @bryplano. I also ensured that my pod files are not ignored in the git repo (they are by default). I think this may work!

git diff:
```
-# Cordova plugins for Capacitor
-capacitor-cordova-ios-plugins
-
+!App/Podfile.lock
+capacitor-cordova-ios-plugins/*
+!capacitor-cordova-ios-plugins/CordovaPlugins.podspec
+!capacitor-cordova-ios-plugins/CordovaPluginsResources.podspec
+!capacitor-cordova-ios-plugins/CordovaPluginsStatic.podspec
```

**Comment by bryplano** [comment]
Awesome, glad to see it! Will close this one out.
