### ISSUE TITLE
feat: docs (update keyboard plugin documentation)

### ISSUE THREAD

**Issue by mesqueeb** [ionic-team/capacitor#2243]
# Feature Request

## Describe the Feature Request

I'm new to capacitor. I'm confused about how to change the keyboard configuration on ios:
- [docs](https://capacitor.ionicframework.com/docs/apis/keyboard/#keyboard-configuration-ios-only-)

> **Keyboard configuration (iOS only)**

This shows a JSON code snippet, but it **doesn't explain where** we should add this code snippet in our capacitor folder.

My request:

- add information on **where to add the configuration JSON**
- add a small note on which "resize" value is the default one on iOS

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

**Comment by bryplano** [comment]
I already commented on your PR, but yeah, this is unfortunate - there **is** an example of how to set this up on the API page, but it doesn't specify what file to put said config into ([link](https://capacitor.ionicframework.com/docs/apis/keyboard/#keyboard-configuration-ios-only-)):

<img width="754" alt="Screen Shot 2019-12-13 at 7 05 46 AM" src="https://user-images.githubusercontent.com/39273819/70802417-09be4680-1d77-11ea-84bf-dfa639cf0b15.png">

Will be looking to make sensible updates like this to the docs in the near future. Thanks for pointing it out.
