### ISSUE TITLE
bug: iOS 13 - iPad landscape - input box refocus is broken after keyboard closes

### ISSUE THREAD

**Issue by mesqueeb** [ionic-team/capacitor#2244]
![2019-12-13 15 30 12](https://user-images.githubusercontent.com/3253920/70775499-a952f780-1dbe-11ea-94aa-dad9f560a320.gif)

# Bug Report
Similar but not the same bug: https://github.com/ionic-team/capacitor/issues/1366
That issue is for iOS12 and iPhone. Mine is for iOS 13 and iPad.

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.3.0

  @capacitor/core 1.3.0

  @capacitor/ios 1.3.0


  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

input box is not refocussed correctly after keyboard closes

## Expected Behavior

input box to be refocussed

## Sample Code or Sample Application Repo

Focus input box on iPad landscape iOS 13.
Then close keyboard.

## Other Technical Details

`npm --version` output: 6.12.1

`node --version` output: v12.13.1

`pod --version` output (iOS issues only): 1.7.5

**Comment by jcesarmobile** [comment]
Sadly this is the webview behaviour, we can't know where the input box was to reposition.
This is usually handled pretty well by frameworks such as Ionic Framework, they use javascript for that.
You can also try to play around with the Keyboard plugin which has events for when the keyboard appears and disappears and allows different resize modes.
