### ISSUE TITLE
capacitor Local Notifications how to show image

### ISSUE THREAD

**Issue by armanhadifatah** [ionic-team/capacitor#2248]
# Feature Request

## Describe the Feature Request
Documentation are very limited and don't know how to use attachment url 
` attachments: [
            { id: 'face', url: 'res://public/assets/icon.png' }
          ],`
I tried a lot of url but non worked. 

The main thing i like is to show image  on notification and i think it should work for both ios and android also pwa.

**Comment by jcesarmobile** [comment]
closing as duplicate of https://github.com/ionic-team/capacitor/issues/2300
