### ISSUE TITLE
Support status bar tap event

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#225]

**Comment by mlynch** [comment]
https://stackoverflow.com/a/18953439/32140

**Comment by jcesarmobile** [comment]
This is a bit hackish, I would recommend to use the Cordova plugin for that.

What's the purpose of it anyway? 
if it's for scroll to top on tap, that is provided by the webview (we might need to enable it)

**Comment by mlynch** [comment]
It's needed for nested overflow areas that don't automatically scroll to the top from the webview (because they are not the `body` scrolling areas)
