### ISSUE TITLE
bug: library causing javascript errors only on iOS --prod builds.

### ISSUE THREAD

**Issue by mxdmedia** [ionic-team/capacitor#2251]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:
  @capacitor/cli: 1.4.0
  @capacitor/core: 1.4.0
  @capacitor/android: 1.4.0
  @capacitor/ios: 1.4.0

Installed Dependencies:
  @capacitor/android not installed
  @capacitor/cli 1.4.0
  @capacitor/core 1.4.0
  @capacitor/ios 1.4.0

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

The bug involves the use of an ngrx-based library called `ngrx-auto-entity`.  The problem I am seeing (and the reason I am posting it to the capcitor team) is that if I do a production build for ios:
```
ionic build --prod
ionic cap copy
ionic cap open ios
```
and then run the app on an iOS device, when one of auto-entities selectors are fired, I get the following non-descriptive error:
```
[error] - ERROR {"line":1,"column":442539,"sourceURL":"capacitor://localhost/main-es2015.24b639144b74affc753b.js"}
```
and the selector fails to return.  If the build is not production (`ionic build`) and run on an iOS device, or if a production build is run a web browser, everything runs as expected.  It only fails for prod builds on iOS devices.

First- are there any suggestions for how to get a more descriptive error with a production build (perhaps with a stack trace)?  I've tried doing production builds with source maps (`--source-map`), but there is no change in the error output.  

## Expected Behavior
I would expect that if an angular/javascript library runs without issue in the browser for a production build, it would run on an iOS device as well.

## Sample Code or Sample Application Repo
Here is a repo with a simple 1-page ionic app, ngrx, and ngrx-auto-entity which exhibits the issue.
https://github.com/mxdmedia/ionic-ngrx-ae-issue

## Reproduction Steps
after grabbing the repo:
```
npm install
ionic build --prod
npx cap copy
npx cap open ios
```
then build the app in xcode run on the device, and watch the xcode console.  If looking at the ngrx vs. auto-entity code- if you get rid of the calls to the sampleFacade, and just use the vanilla ngrx counter feature, everything works fine. It is the call on the home page to `this.samples.all$.subscribe(samples => console.log(samples))` that is causing the error.

## Other Technical Details
`npm --version` output: 6.13.2
`node --version` output: v10.13.0
`pod --version` output (iOS issues only): 1.6.1

## Other Information
Here is the issue I've opened with the ngrx-auto-entity project:
https://github.com/briebug/ngrx-auto-entity/issues/81

**Comment by jcesarmobile** [comment]
by reading the ngrx-auto-entity issue it looks like the bug is theirs, so closing the issue.
