### ISSUE TITLE
feat: [Storage Plugin] Support for iOS suites

### ISSUE THREAD

**Issue by ThomasKientz** [ionic-team/capacitor#2253]
# Feature Request

## Describe the Feature Request
While developing extensions in iOS, you may find a need to share application or user data between the host app and the extension.

To do so, we need to pass a "suite name" at the initialization of the [userDefaults](https://github.com/ionic-team/capacitor/blob/8158d910905790dd98bfffe3b927e445ecfb8c6e/ios/Capacitor/Capacitor/Plugins/Storage.swift#L14)

[`init?(suiteName suitename: String?)` ](https://developer.apple.com/documentation/foundation/userdefaults/1409957-init)

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Possibility to initialize the store with a suite name.

## Describe Alternatives

An old cordova plugin is doing the job : https://github.com/apla/me.apla.cordova.app-preferences

## Additional Context

May concerns Android as well.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Or if you are really interested and have the knowledge to implement this, you can send a PR.

**Comment by ryanflores79** [comment]
I just started looking into created an iOS widget to show some data on the home screen from within my ioinic capacitor app.  I'm going to need a way of defining a suiteName so that when I store some data in the app, the widget extension can read the data and display it.  Is there any plan to work on this now that iOS 14 beta is out?

**Comment by jgirdner** [comment]
Let's go fellas! iOS 14 is here. No time to delay.

**Comment by hocococaspar** [comment]
Pretty please implement this! :)
