### ISSUE TITLE
Android, Splashscreen: System and Capacitor screen are positioned/sized slightly different on Nexus 5

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#226]
I made a pretty gif:
![nexus5](https://user-images.githubusercontent.com/183673/36858588-cd515d56-1d7b-11e8-931f-359da50c5f82.gif)
Pretty proiud of it! 
(Used http://gifmaker.me/ ...)

Source pictures:
![1](https://user-images.githubusercontent.com/183673/36858454-7ea7c1b8-1d7b-11e8-8878-eb4c6d033c23.png)
![2](https://user-images.githubusercontent.com/183673/36858456-7ec4beda-1d7b-11e8-9db9-e48f7f77edf2.png)

**Comment by mlynch** [comment]
Yea, this is something people will have to live with for now, unfortunately. It's not possible to use the same scaling algorithm _exactly_ for the launch screen image as for showing it later as a drawable. It's annoying but it's a tradeoff. I misplaced the issue that talked about why this is.

**Comment by arnaud-zad** [comment]
I had the same issue on my Nexus 5X. 

I changed the scaletype to FIT_XY in Splash.java. I don't have this effect anymore.

**Comment by peterpeterparker** [comment]
@arnaud-zad you deserve a cookie, that fixed the glitch for me too respectively changing the following in `Splash.java` fix it

from

      splashImage.setScaleType(ImageView.ScaleType.CENTER_CROP);

to
      splashImage.setScaleType(ImageView.ScaleType.FIT_XY);

@mlynch if you are agree that that could be the default, I could provide a PR, let me know

**Comment by mlynch** [comment]
My only concern with that is if people have splash screens that aren't the exact right size, but I suppose that shouldn't happen. Yea, I'd be open to that

**Comment by peterpeterparker** [comment]
@mlynch I guess most of the people gonna generate their splash with a tool and therefore there is a chance that the images will be often the right size, but well only my guess

Anyhow cool if you are up to, there you go the PR https://github.com/ionic-team/capacitor/pull/929

**Comment by jcesarmobile** [comment]
Closing as #929 has been merged.

**Comment by sbannigan** [comment]
@mlynch this still seems like a problem. With a new capacitor project the splashscreen still is distorted. This screenshot is from a Pixel 2 XL: 
![screenshot_1548274576](https://user-images.githubusercontent.com/15218748/51634441-40525f00-1f22-11e9-9b86-1da77b11f9da.png)
Reverting the FIT_XY change displays the splashscreen correctly, but still shows the distorted one when launching the app. The only way I see around both of these issues is to use a 9 patch image for the splashscreen: https://developer.android.com/studio/write/draw9patch
