### ISSUE TITLE
bug: window.scrollTo not working

### ISSUE THREAD

**Issue by AdrianaSaty** [ionic-team/capacitor#2260]
I'm using ionic capacitor with vue, and trying to use window.scrollTo(0.0) but it's not working.
Anyone knows what can cause this?

**Comment by jcesarmobile** [comment]
Can you provide a sample app or some sample code?
Also, in which platform are you facing this issue?

**Comment by jcesarmobile** [comment]
Closing as it looks like an user error and didn't answer.

BTW, the proper way of scrolling is `window.scrollTo(0,0)` (notice that is uses a `,`, not a `.`
