### ISSUE TITLE
iOS Simulator showing blank white screen - Capacitor - Vue.js

### ISSUE THREAD

**Issue by Fijiannn** [ionic-team/capacitor#2263]
Thanks for taking the time to check out my post. A little stuck here with my mobile app project using Capacitor and Vue.js

Long story short, I've got a proper Vue.js set up correctly because I tested with Node server and it functions exactly how we set it up. But when we use Capacitor plugin to boot our Vue.js product with Xcode the simulator shows blank. It does show the Capacitor splash screen and logs mention "Loading app at capacitor://localhost..." and "Web View Loaded" but nothing. I know I installed Capacitor right because I've retried multiple times and it's not rocket science either. It must be my main.js file

I've also attempted to debug the app using Safari web inspector and fixed all errors that Terminal showed me. We printed "hello" from our index.html file and it does show up on the debugger log when we boot the app and we also sneaked a quick label on the top left corner that says "hi" so we're seeing it read the index.html file but not getting any info from our main.js file. We tried to get console outputs and nothing. At first the safari debugger gave us a google fonts error but we fixed that and still nothing showing up. 

![QwXI0](https://user-images.githubusercontent.com/58959378/70950826-86228500-2016-11ea-908c-3e4414dd76e5.jpg)

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing since there was no response.

Next time fill the template and provide a sample app

**Comment by shikhardb** [comment]
@Fijiannn  How did you solve this issue?

**Comment by Nemesis19** [comment]
give to webDir property in capacitor file the value "dist" then do `npx cap copy`

**Comment by TimVdWalle** [comment]
> give to webDir property in capacitor.config.json file the value "dist" then do `npx cap copy`

this solution worked for me :)
