### ISSUE TITLE
IOS Push listeners not working

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#2268]
I am on the latest Ionic and Capacitor and have had push notifications working perfectly for months now, however today when debugging on ios device, the push listeners dont seem to be emitting anything.

```
PushNotifications.addListener('registration', (token: PushNotificationToken) => {
      console.log('PUSH TOKEN FOUND')
      this.deviceToken.next(token.value);
    });
```

the logs clearly show them being called and created but nothing is ever emitted:

⚡️  To Native ->  PushNotifications addListener 100376724
⚡️  To Native ->  PushNotifications addListener 100376725
⚡️  To Native ->  PushNotifications addListener 100376726
⚡️  To Native ->  PushNotifications addListener 100376727

Any ideas as to why this is happening.

Push capabilities are enabled and all the keys are set up as before, nothing has changed in regards to the push service.

**Comment by jcesarmobile** [comment]
I can't reproduce on latest version.

Please, when reporting issues don't delete the template.

**Comment by aspoonemore** [comment]
I’m still seeing this issue on the latest version of ionic.
