### ISSUE TITLE
bug: Read file unable to read from content

### ISSUE THREAD

**Issue by lim-enhui** [ionic-team/capacitor#2270]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Unable to read file from File chooser.
<img width="845" alt="Screenshot 2019-12-19 at 3 15 43 AM" src="https://user-images.githubusercontent.com/13527348/71115906-f9dab280-220d-11ea-86ef-f4a192d81590.png">

## Expected Behavior

Should be able to read from file chooser

## Sample Code or Sample Application Repo

<img width="979" alt="Screenshot 2019-12-19 at 3 22 29 AM" src="https://user-images.githubusercontent.com/13527348/71116288-d2381a00-220e-11ea-9606-068cb61e9c89.png">

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by bryplano** [comment]
Sample app to reproduce the exact problem please.

**Comment by lim-enhui** [comment]
> Sample app to reproduce the exact problem please.
i will share a repo on sample?

**Comment by bryplano** [comment]
Yes, please share a publicly-accessible sample application repo and provide specific steps to reproduce the error with the app. Can host on Github or elsewhere.

**Comment by lim-enhui** [comment]
> Yes, please share a publicly-accessible sample application repo and provide specific steps to reproduce the error with the app. Can host on Github or elsewhere.

https://github.com/lim-enhui/sampleApp

**Comment by lim-enhui** [comment]
i just need to place this reference the linked that I followed through but without solution.. the difference it is read from file:// and also from camera api

https://github.com/ionic-team/capacitor/issues/393

**Comment by lim-enhui** [comment]
Can anyone just let me know what have I missed?

**Comment by jcesarmobile** [comment]
File plugin doesn't allow to just pass an url, it also requires the directory, which is the root "directory". Each OS have different logical filesystems and that's what the directory option is.

Also, content urls are not supported neither.
