### ISSUE TITLE
Image can not show in web view page in Android platform

### ISSUE THREAD

**Issue by EllisonYe** [ionic-team/capacitor#2279]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
  @capacitor/cli 1.4.0
  @capacitor/android 1.4.0
  @capacitor/core 1.4.0
  @capacitor/ios 1.4.0

## Affected Platform(s)

- [ Y] Android

## Current Behavior

Image can not show in web view page with https security in Android System WebView (66.0.3359.158), but it can show in Android System WebView(76.0.3809.111)

## Expected Behavior

it can show in Android System WebView(76.0.3809.111)

## Other Technical Details

`npm --version` output:
5.6.0

`node --version` output:
v8.10.0

## Other Information

Network request info(Not work):
Status: (canceled)
Header:
Referer: http://localhost/hazard-detail
User-Agent: Mozilla/5.0 (Linux; Android 9; ONEPLUS A6010 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36

Network request info(work):
Status: (200)
Header:
Referer: http://localhost/hazard-detail
**### _sec-fetch-mode: no-cros_**
User-Agent: Mozilla/5.0 (Linux; Android 9; ONEPLUS A6010 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36

**Comment by jcesarmobile** [comment]
can you provide a sample app?

Also, can you clarify the  "Expected Behavior" section, as you say you expect it to work on chrome 76 and in the "Current Behavior" you say it works in chrome 76.

**Comment by jcesarmobile** [comment]
Closing since there was no response and the problem is unclear
