### ISSUE TITLE
Android: Generated `android` project is missing `.gitignore` file(s)

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#228]
Currently both `/.gradle` and `/build` are committed to the source code repo.

There already are `.npmignore` files both in `android` and `android/app` - copying those into `.gitignore` pretty much does the job already, but probably you want to tailor that a bit more.

**Comment by vishal-bluesys** [comment]
worked

**Comment by jcesarmobile** [comment]
This was added in https://github.com/ionic-team/capacitor/commit/a25c8c9e136134f41f3d9d41f36ec4592369ade6#diff-59ebe2e0fda1b29d2b294846cebb8073 long time ago
