### ISSUE TITLE
bug: GPS coordinates stripped from camera images

### ISSUE THREAD

**Issue by Alain1405** [ionic-team/capacitor#2283]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/android 1.4.0

  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0


[success] Android looking great! 👌
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
No matter whether I take a picture with the Capacitor camera plugin or I get a picture from the gallery, GPS information is only partially retrieved in the EXIF data.
The following fundamental fields are missing: `GPSLatitude`, `GPSLatitudeRef`, `GPSLongitude`, `GPSLongitudeRef`

Here is the EXIF data I get:
```
{
  exif:
  {
    FNumber: "1.75",
    DateTime: "2019:12:28 20:27:07",
    ExposureTime: "0.02",
    Flash: "16",
    FocalLength: "4070/1000",
    GPSAltitude: "73872/1000",
    GPSAltitudeRef: "0",
    GPSDateStamp: "2019:12:28",
    GPSProcessingMethod: "GPS",
    GPSTimeStamp: "11:27:06",
    ImageLength: "3000",
    ImageWidth: "4000",
    ISOSpeedRatings: "100",
    Make: "Xiaomi",
    Model: "Mi A2",
    Orientation: "6",
    WhiteBalance: "0"
}
```

## Expected Behavior

`GPSLatitude`, `GPSLatitudeRef`, `GPSLongitude` and `GPSLongitudeRef` should be in the EXIF data.

## Sample Code or Sample Application Repo

Take a photo using basic plugin configurations:
```
...
cameraOptions = {
      allowEditing: false,
      source: CameraSource.Prompt,
      resultType: CameraResultType.Uri
    };
...
public takePhoto(): Promise<CameraPhoto> {
    return Plugins.Camera.getPhoto(cameraOptions).then(
      (photo) => {
        console.log('Photo exif: ', photo.exif);
        return photo;
      },
      (err) => {
        console.log(err);
        throw(err);
      });
  }
```

## Reproduction Steps
- Take a photo
- Log exif data

## Other Technical Details

`npm --version` output:
```
$ npm --version
6.12.1
```
`node --version` output:
```
$ node --version
v13.1.0
```

## Other Information

Some GPS related tags are stripped out:

https://github.com/ionic-team/capacitor/blob/8158d910905790dd98bfffe3b927e445ecfb8c6e/android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ExifWrapper.java#L74

Those appear to be for API level 24 only though. The missing tags should be `TAG_GPS_LATITUDE`, `TAG_GPS_LATITUDE_REF`, `TAG_GPS_LONGITUDE`, `TAG_GPS_LONGITUDE_REF`.

**Comment by Alain1405** [comment]
@mlynch mentioning you as that was your PR. Any reason why `TAG_GPS_LATITUDE`, `TAG_GPS_LATITUDE_REF`, `TAG_GPS_LONGITUDE` and `TAG_GPS_LONGITUDE_REF` were not included in the Exif info?

**Comment by sandstrom** [comment]
Could be due to geo-permissions, or that some platforms will stripe these values themselves (I think iOS may do that). Just a thought though. I'm not sure.
