### ISSUE TITLE
bug: error: package android.support.v7.app does not exist & cannot find symbol class AppCompatActivity

### ISSUE THREAD

**Issue by Aravin** [ionic-team/capacitor#2289]
# Bug Report

## Capacitor Version
cap core - 1.4.0
npm v 6.12.1
node v 12.13.1

`npx cap doctor` output:
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\itara\AppData\Roaming\npm-cache\_npx\240\node_modules\cap
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\itara\AppData\Roaming\npm-cache\_logs\2019-12-29T08_33_41_087Z-debug.log
Install for [ 'cap@latest' ] failed with code 1

## Affected Platform(s)
- [x ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Getting follow 3 error while building Android Project. This happens after adding the storage plugin to the cordova.
Before that I am able to build and publish the APK.

1. error: package android.support.v7.app does not exist
2. error: cannot find symbol class AppCompatActivity
3. error: cannot find symbol class AppCompatActivity (same as 2)

![image](https://user-images.githubusercontent.com/4869265/71554382-40b57d00-2a44-11ea-8b91-017fd60285e3.png)

![image](https://user-images.githubusercontent.com/4869265/71554384-4a3ee500-2a44-11ea-8f22-8469944fee03.png)

## Expected Behavior
I should have to build the Android Project with Capacitor

## Sample Code or Sample Application Repo

Repo: https://github.com/Aravin/emi-calculator

## Other Information

* Some online forum suggested upgrading to AndroidX will resolve this issue, but it didn't worked.
* Some online forum suggested invalidating cache and restrating the ide will work, but it didn't worked.

**Comment by jcesarmobile** [comment]
I confirm the app you provided doesn't work, but if I remove android folder and run `npx cap add android` and `npx cap open android` I get the default Capacitor project and it works fine.
So it's probably some problem in your app or dev environment.
