### ISSUE TITLE
why ios must version 11+?  

### ISSUE THREAD

**Issue by match08** [ionic-team/capacitor#2291]
why ios must version 11+?

**Comment by bryplano** [comment]
> As a rule, the latest version of Capacitor always supports the last two iOS versions. For example, iOS 11 and iOS 12. For support for older versions of iOS, use an older version of Capacitor (if available).

Several reasons (and probably more) for this:

- Xcode 10 is minimum (which defaulted to iOS 12 SDK + Swift 4+)
- Encourages developers try to keep their projects up-to-date
- The latest version(s) of Xcode require your project to use a certain version of iOS or higher (usually it's 3 versions back but two ensures you're up-to-date)
- iOS users are almost all using the last two major versions per Apple's documentation: https://developer.apple.com/support/app-store/

**Comment by jcesarmobile** [comment]
You have left out the only real reason why iOS 11+ is required, Capacitor needs `WKURLSchemeHandler` to work and that was included on iOS 11.
https://developer.apple.com/documentation/webkit/wkurlschemehandler

**Comment by bryplano** [comment]
Thanks for the additional info @jcesarmobile

**Comment by match08** [comment]
Thanks
