### ISSUE TITLE
feat: Ability to specify androidDir iosDir and electronDir like webDir

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/capacitor#2294]
Hi. In the configuration options here: https://capacitor.ionicframework.com/docs/basics/configuring-your-app I see webDir being used to specify different location of the web project and that works great.

Would be great if we have the ability to specify custom directories for the built files as well like androidDir, electronDir, iosDir, etc. so that we can have them somewhere else.

Thanks.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

**Comment by dwieeb** [comment]
Just adding a note that `webDir` isn't for the web platform, but the directory Capacitor looks for web assets to copy into the native projects. What would make more sense is a `path` option in each platform's configuration object (`ios.path`, `android.path`). 

In Capacitor 3 we _may_ be introducing a new directory for the web platform (probably `web/`) that Capacitor uses to copy web assets into if it were to manage service workers, etc (see the discussion in https://github.com/ionic-team/capacitor/pull/1892).

**Comment by tvvignesh** [comment]
@dwieeb That would be awesome. I just have one question. May I know if it would be good to start off with Capacitor 3 beta today? Would there be major breaking changes after today? I am launching my product on Sept 15th and I wanted to do all the migration asap so that I don't have to do breaking migration atleast for 2-3 months.

**Comment by dwieeb** [comment]
@tvvignesh I would not recommend using Capacitor 3 for any production app. We will be doing regular alpha and beta releases, but they're meant to be used in a development setting for feedback.

I'm not entirely sure what you're asking about Electron, but each third-party platform can use their own object in `capacitor.config.json` for configuration.
