### ISSUE TITLE
storage does not have web implementation ?

### ISSUE THREAD

**Issue by AndresHades** [ionic-team/capacitor#2295]
Thats the error im having in an Ionic+Angular project when I test it in chrome browser.

It takes a few minutes to reproduce:

_ionic start testApp (with angular and blank choices)
ng build
ionic capacitor add android
ionic serve_

Everything ok until here. Now if I try to store and retrieve some information from storage:

**home.page.ts**

```
import { Component, OnInit } from '@angular/core';
import { HomeService } from './home.service';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit{

  constructor(private homeService: HomeService) {}

  ngOnInit() {
    debugger;
    this.homeService.setStoredUser().then( storedData => {
      debugger;
      console.log('Stored: '+storedData);
      this.homeService.getStoredUser().then( storedData => {
        debugger;
        console.log('Retrieved: '+storedData);
      });
    });
  }
}
```

**home.service.ts (added to app.module.ts in provided array)**

```
import { Injectable } from '@angular/core';
import { Plugins } from '@capacitor/core';
import { Platform } from '@ionic/angular';

@Injectable()
export class HomeService {

    constructor(private platform: Platform) {}

    getStoredUser() {
        let p = null;
        try {
            debugger;
            console.log(this.platform);
            p = Plugins.Storage.get({key: 'authData'});
            console.log(p);
        } catch (error) {
            debugger;
            console.log(error);
        }
        return p;
    }

    setStoredUser() {
        let p = null;
        try {
            debugger;
            console.log(this.platform);
            p = Plugins.storage.set({key: 'authData', value: 'Hello!'});
            console.log(p);
        } catch (error) {
            debugger;
            console.log(error);
        }
        return p;
    }

}
```
And here is the error in developer console:

> ZoneAwarePromise {__zone_symbol__state: 0, __zone_symbol__value:
> "storage does not have web implementation."}__zone_symbol__state:
> false__zone_symbol__value: "storage does not have web
> implementation."Symbol(Symbol.toStringTag): (...)__proto__: Object
> core.js:9110 ERROR Error: Uncaught (in promise): storage does not have
> web implementation.
>     at resolvePromise (zone-evergreen.js:797)
>     at resolvePromise (zone-evergreen.js:754)
>     at zone-evergreen.js:858
>     at ZoneDelegate.invokeTask (zone-evergreen.js:391)
>     at Object.onInvokeTask (core.js:34182)
>     at ZoneDelegate.invokeTask (zone-evergreen.js:390)
>     at Zone.runTask (zone-evergreen.js:168)
>     at drainMicroTaskQueue (zone-evergreen.js:559)

Is anything else i need to configure that i have not seen in the documentation?

**Comment by AndresHades** [comment]
In the case that someone faces the same problem. Found a working version of Storage plugin with the latests versions of Angular and Ionic.

Same example as before, but changing the service for this other one class and the consequent changes in the component:

```
import { Plugins } from '@capacitor/core';
 
const { Storage } = Plugins;
 
export async function set(key: string, value: any): Promise<void> {
  await Storage.set({
    key: key,
    value: JSON.stringify(value)
  });
}
 
export async function get(key: string): Promise<any> {
  const item = await Storage.get({ key: key });
  return JSON.parse(item.value);
}
 
export async function remove(key: string): Promise<void> {
  await Storage.remove({
    key: key
  });
}
```

I don't know why this works for me and the first example not.

**Comment by dotNetkow** [comment]
That's correct, as [detailed here](https://capacitor.ionicframework.com/docs/apis). Import Plugins from Capacitor Core, then retrieve from a plugin from the Plugin Registry:

`const { Storage } = Plugins;`

The above is what you were missing.

**Comment by jcesarmobile** [comment]
Both `const { Storage } = Plugins;` and `Plugins.Storage` work, the problem was using storage instead of Storage, plugin names are case sensitive.
