### ISSUE TITLE
How to communicate between InappBrowser and my capacitor app?

### ISSUE THREAD

**Issue by JoshuvaGeorge03** [ionic-team/capacitor#2298]
I want to send message from inappbrowser back to my app. 

We can do that with cordova inappbrowser plugin using postMessage. (window.parent.postMessage).

But in Capacitor Browser Plugin there is no doc for that, also there is no api to listen to that messages? So I can't able to send data back to my app also.

### Current Scenario
I was hoisting my website using firebase. And I was loading that website inside of inappbrowser. 
And After user did some action, I want to send message to my app to run some code.

`window.parent.postMessage(JSON.stringify('message', '*')`

This is my code to send the message from inappbrowser to app. That is not working at all.

### Expected

Kindly advice, If I am doing something wrong. And kindly tell me, how to achieve it.

Also, Kindly advice how to hide url bar in the inappbrowser?

**Comment by digaus** [comment]
> I want to send message from inappbrowser back to my app.
> 
> We can do that with cordova inappbrowser plugin using postMessage. (window.parent.postMessage).
> 
> But in Capacitor Browser Plugin there is no doc for that, also there is no api to listen to that messages? So I can't able to send data back to my app also.
> 
> ### Current Scenario
> I was hoisting my website using firebase. And I was loading that website inside of inappbrowser.
> And After user did some action, I want to send message to my app to run some code.
> 
> `window.parent.postMessage(JSON.stringify('message', '*')`
> 
> This is my code to send the message from inappbrowser to app. That is not working at all.
> 
> ### Expected
> Kindly advice, If I am doing something wrong. And kindly tell me, how to achieve it.
> 
> Also, Kindly advice how to hide url bar in the inappbrowser?

This is documented in the inappbrowser plugin. 

Just call `browserRef.addEventListener('message', (message: any) => { console.log(message});`

`browserRef` is the reference if the opened iab.

**Comment by JoshuvaGeorge03** [comment]
@digaus I am not talking about cordova-plugin-inappbrowser.

I am talking about Capacitor Browser Plugin api, is it not inappbrowser we should use in capacitor apps?

kindly check the link and advice.
[https://capacitor.ionicframework.com/docs/apis/browser](url)

**Comment by digaus** [comment]
> @digaus I am not talking about cordova-plugin-inappbrowser. I have gone through that documentation and I know how to do using cordova-plugin-inappbrowser.
> 
> I am talking about Capacitor Browser Plugin api, And I want to know how to do like that thing in this plugin?
> 
> Should we not use this plugin for inappbrowser requirements?
> 
> kindly check the link and advice.
> [https://capacitor.ionicframework.com/docs/apis/browser](url)

The capacitor browser plugin is very limited. It is only for basic usage and if you want to do more you should use the inappbrowser plugin. You can write a feature request but it would need a major rework since on android capacitor uses the `Chrome Custom Tabs` and these do not seem to support features needed for such a communitcation:

https://developer.chrome.com/multidevice/android/customtabs

**Comment by JoshuvaGeorge03** [comment]
@digaus Thanks, will use cordova-plugin-inappbrowser.

**Comment by bryplano** [comment]
Sounds like this one is 👍, will close

**Comment by JoshuvaGeorge03** [comment]
@digaus I have used cordova-plugin-inappbrowser and it seems to be working fine in android.

But in ios, it throws run time error.  when I try to open 

`      Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1039d784c)
`

Kindly find the image for your reference.

![image](https://user-images.githubusercontent.com/39693066/72143641-11e0c480-33bd-11ea-9797-d215aa26b2dd.png)

**Comment by digaus** [comment]
> @digaus I have used cordova-plugin-inappbrowser and it seems to be working fine in android.
> 
> But in ios, it throws run time error. when I try to open
> 
> ` Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1039d784c)`
> 
> Kindly find the image for your reference.
> 
> ![image](https://user-images.githubusercontent.com/39693066/72143641-11e0c480-33bd-11ea-9797-d215aa26b2dd.png)
> 
> What to do? In cordova powered apps, it seems to work.
> 
> In android, it work perfectly well even using capacitor as runtime.

Don't know, it works for me. Maybe create an issue on inappbrowser plugin.
