### ISSUE TITLE
Move `windowsAndroidStudioPath` to a gitignored file?

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#230]
`windowsAndroidStudioPath` is by definition dependent on the machine you are using. Committing this configuration to git so doesn't really make sense, as you probably would have to change it on every machine you are checking out the project.

A better idea might be to have another configuration file for machine dependent settings that is ignored via `.gitignore`.

**Comment by mlynch** [comment]
Hmm, good idea. Yea I hate that that's a thing.

**Comment by mlynch** [comment]
I think a `.capacitorrc` in your home folder could work

**Comment by janpio** [comment]
What does the `rc` at the end stand for?

**Comment by jcesarmobile** [comment]
Now if the default or configured path doesn't exist, it will autodetect the path from windows registry. So there is no need to set the `windowsAndroidStudioPath` anymore. Closing.

**Comment by andressoop** [comment]
> 
> 
> Now if the default or configured path doesn't exist, it will autodetect the path from windows registry. So there is no need to set the `windowsAndroidStudioPath` anymore. Closing.

Auto detect does not work when Android Studio is installed through JetBrains Toolbox (for me at least).

**Comment by jcesarmobile** [comment]
The change is not released yet

**Comment by bleuscyther** [comment]
same issue here , based on my attempts and this comment (https://github.com/desktop/desktop/issues/7195#issuecomment-479964589)  Jetbrain does not have a fixed path for its tools. 😅
