### ISSUE TITLE
 call.resolve ? Multiple failures in a row

### ISSUE THREAD

**Issue by match08** [ionic-team/capacitor#2301]
https://github.com/triniwiz/capacitor-zip

code error：   call.resolve(statusObject);   Multiple failures in a row

  while (monitor.getState() == ProgressMonitor.STATE_BUSY) {
                progress = monitor.getPercentDone();
                statusObject.put("status", "progressing");
                statusObject.put("progress", progress);
                statusObject.put("completed", false);
                call.resolve(statusObject);
            }

**Comment by bryplano** [comment]
Report this on the repository for the plugin, not here.
