### ISSUE TITLE
capacitor open android return unhandled 'error' event (resolution)

### ISSUE THREAD

**Issue by Mburusakc** [ionic-team/capacitor#2303]
hello everyone, as the title says I was faced with an error during the execution of the command 

> "npx cap open android" 

(under linux) then the console returns an error of the type:

> [info] Opening Android project at /home/yourUserName/yourProjectName/android
> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> Error: spawn /usr/local/android-studio/bin/studio.sh ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
>     at onErrorNT (internal/child_process.js:415:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> Emitted 'error' event at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
>     at onErrorNT (internal/child_process.js:415:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> [ERROR] An error occurred while running subprocess capacitor.
> 

In fact the problem is quite simple and to solve it just move the android studio folder under the directory "/ user / local /" then relaunch the command ...
PS: the error was displayed because capacitor could not find android studio in the default directory provided to it, that's all.

Here I hope to have help someone good continuation

**Comment by RavinduSachintha** [comment]
Any solution ?:thinking: I got the same issue.

**Comment by keo9ren** [comment]
Same issue for me

**Comment by Mburusakc** [comment]
> Any solution ?thinking I got the same issue.

Hello and thanks for your request so like i wrote the solution is in the post, you just need to move your android studio folder the /user/local/ and then the error will be resolved

**Comment by Mburusakc** [comment]
> Same issue for me

In fact the problem is quite simple and to solve it just move your android studio folder installation under the directory `**"/user/local/"**`, then relaunch the command

the problem occurred because the default Android Studio directory (for capacitor) is empty because you have install your android studio to another directory, so just move your folder and i'll work

**Comment by jcesarmobile** [comment]
You don't need to move Android Studio, just configure Capacitor to use a different path.
The CLI is supposed to tell you how, but there was a bug preventing it and showing your error, I've sent a PR that will fix it.
