### ISSUE TITLE
feat: Keyboard animation curve & duration

### ISSUE THREAD

**Issue by piotrblasiak** [ionic-team/capacitor#2304]
# Feature Request

## Describe the Feature Request

Provide the keyboard animation curve (UIViewAnimationCurve for iOS) and duration for when keyboard is hiding & showing so that we can react accordingly in the app instead of having "jumpy" UIs.

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Additional Context

[Blog post about getting the curve](https://spin.atomicobject.com/2014/01/08/animate-around-ios-keyboard/)

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

But feel free to send a PR if you know how to add this.

**Comment by piotrblasiak** [comment]
> @piotrblasiak did you found a way to manage that ?

No I'm afraid not. This is still something that gives away that my app is hybrid - if you find a solution please let me know.
