### ISSUE TITLE
docs: unclear what BrowserPrefetchOptions can accept

### ISSUE THREAD

**Issue by mesqueeb** [ionic-team/capacitor#2305]
BrowserPrefetchOptions
```
interface BrowserPrefetchOptions {
urls : any;
}
```
can we pass a single URL as a string? Can we pass multiple URLs as a string?

`any` without any further information isn't very helpful 😢

**Comment by jcesarmobile** [comment]
where do you see that? I see `urls: string[];`

https://github.com/ionic-team/capacitor/blob/master/core/src/core-plugin-definitions.ts#L255

**Comment by dotNetkow** [comment]
Julio - the docs page for Browser API here
<https://capacitor.ionicframework.com/docs/apis/browser#type-279>.

**Comment by jcesarmobile** [comment]
then it looks like a bug on the docs generation
