### ISSUE TITLE
Meta: roadmap & issue gardening

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#2306]
Happy 2020 Ionic! 🎉 

We've recently moved our Cordova app over to Capacitor. Overall we're very happy with the transition! 😄 

However, we've opened some smaller issues ([this](https://github.com/ionic-team/capacitor/issues/2265), [this](https://github.com/ionic-team/capacitor/issues/872#issuecomment-548047623) and [here](https://github.com/ionic-team/capacitor/pull/2050)) that we haven't gotten much response to. 

Capacitor is great overall, and I understand that things are busy for you, but I think you could so some high-level things to help the community focus on the same things + know where things are heading.

So, I have some high-level ideas for the this upcoming year:

1. **Add a roadmap** Right now the readme info is from 2018 with a small link for 2019. It looks somewhat dated and doesn't do this project justice. Removing the old details altogether (and add nothing for 2020), or updating with a roadmap for 2020 would be good either way.

2. **Setup a structure for PRs and Issues** If you want to reap the benefits of an open-source community I think it would help if you responded to PRs and issues more quickly. You don't necessarily have to act on everything, but just mentioning that you've read an issue/PR and what the next steps will be, would help contributors with expectations.
    
    For example, some common (canned) responses could be:
      - Good feature idea, but we don't have bandwidth. Are you willing to work on it?
      - Thanks for this bug fix. We need a test case too, can you help?
      - We're not sure about adding this to core. We'd suggest experimenting with this in a plugin first. If it proves popular we may consider moving it to core in the future.
    
    If responses are delayed too much you lose momentum, people may have monkey-patched or moved on already.

3. **Bring in some large apps** Identify some popular (large dev teams) Cordova apps on iOS/Android, approach them and ask if we've considered moving. Perhaps there may be no (or only small) roadblocks. With more users you'd get more critical mass.

4. **Bring in outside maintainers/collaborators** See if you can find some responsible people that are willing to help with issues and PRs. Perhaps you can ask them to start with issue gardening and triaging, with you still having the final say before merging code.

Let me know what you think! 

cc @jcesarmobile @mlynch

**Comment by dotNetkow** [comment]
Hi, Matt from Ionic DevRel here. Thanks so much for the detailed feedback - we really appreciate it! Some thoughts on your comments:

**Outside Maintainers:** This is something we're working on right now so stay tuned. We're a small team, so bringing on some folks to assist will for sure help. We'll be figuring out the process as we go along and learn, but it'll likely be issue and PR grooming to start, and plugin/core contributions where appropriate.

**Roadmap:** Thanks for pointing out the outdated README, I'll get that updated. As for the roadmap itself, we likely won't be publishing one. Capacitor Core is very stable, so moving forward most new functionality will likely be created via plugins. Of course, what's being worked on will still be public. Right now, you can follow v2.0 milestone tasks [here](https://github.com/ionic-team/capacitor/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0). I'll review how we can make this more obvious/visible.

**PR/issue structure:** Visibility could be improved, but today we do have this in place with issue labels like "docs", "good first issue", "need help", etc. We also do try to respond to most issues with basically the same suggestions you made. 

**Bring in large apps**: We're pretty happy with the number of teams/companies moving over from Cordova. Some are public (Sworkit) and others aren't. Highlighting apps hasn't been a focus just yet, but that could change in 2020 as more teams move over - thanks for the suggestion. Capacitor's growth has been fantastic, [see here](https://npmcharts.com/compare/@capacitor/core?interval=30). Besides the typical winter holiday lull, it's been rising and steady.

Overall, we're excited for Capacitor's growth in 2020 and beyond. Rest assured, it's a key part of the Ionic Platform, so it's going to continue to be a focus for us. Cheers!

**Comment by sandstrom** [comment]
@dotNetkow Sounds good, looking forward to it! 😄
