### ISSUE TITLE
feat: Sign In With Apple plugin

### ISSUE THREAD

**Issue by gentlemanjohn** [ionic-team/capacitor#2308]
# Feature Request
Sign In With Apple plugin

## Describe the Feature Request

Any mobile app that uses a third-party login must also offer Sign In With Apple in order to be approved for the App Store.  Existing apps must support Sign In With Apple by April 2020.  

There doesn't seem to be a community Capacitor plugin available and the two Cordova plugins I've found won't work with Capacitor ([cordova-plugin-apple-login](https://github.com/pscsrv/cordova-plugin-apple-login) and [cordova-plugin-sign-in-with-apple](https://github.com/twogate/cordova-plugin-sign-in-with-apple).  

**Can we get an official plugin?**

From Apple:

> 4.8 Sign in with Apple
> 
> Apps that exclusively use a third-party or social login service (such as Facebook Login, Google Sign-In, Sign in with Twitter, Sign In with LinkedIn, Login with Amazon, or WeChat Login) to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option. A user’s primary account is the account they establish with your app for the purposes of identifying themselves, signing in, and accessing your features and associated services.

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [x] Web

## Describe Preferred Solution
An official Sign In With Apple Capacitor plugin or someone who is available to start a community project.

## Describe Alternatives
Unfortunately there doesn't seem to be a good one.  As I offer Google sign in, I won't be able to get approved for the App Store.  I could drop it and only offer email account creation, but that would be a blow to adoption on both platforms.

## Related Code
N/A

## Additional Context
N/A

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.

**Comment by jcesarmobile** [comment]
BTW, just saw this one https://github.com/htorbov/capacitor-apple-login

**Comment by htorbov** [comment]
Yeah, I had to make the plugin since my new app got rejected for not having the Apple button, lol... It supports iOS only for now (I've just updated the [README.md](https://github.com/htorbov/capacitor-apple-login/blob/master/README.md)). Good luck!

**Comment by romanstark** [comment]
https://github.com/htorbov/capacitor-apple-login is offline. Any reason?

**Comment by sean118** [comment]
Seems to live here now:
https://github.com/rlfrahm/capacitor-apple-login

**Comment by AlvinTCH** [comment]
The plugin is working well for now. But still requires maintenance. All I know is that the creator for the capacitor-oauth package is working on it to integrate apple sign in to the existing capacitor-oauth package

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/14. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
