### ISSUE TITLE
Cordova Plugin InappBrowser causing run time error in Ios 

### ISSUE THREAD

**Issue by JoshuvaGeorge03** [ionic-team/capacitor#2315]
# Bug Report

## Capacitor Version
`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/android 1.4.0

  @capacitor/core 1.4.0

  @capacitor/ios 1.4.0

## Affected Platform(s)

- [ ] Android
-  iOS
- [ ] Electron
- [ ] Web

## Current Behavior
 I was using Cordova-plugin-inappbrowser in my app, In runtime, when i try to open the inappbrowser,  it throws runtime error CAPbridge.swift file.

I have used cordova-plugin-inappbrowser and it seems to be working fine in android.

But in ios, it throws run time error.  when I try to open it.

`      Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1039d784c)
`

Kindly find the image for your reference.

![image](https://user-images.githubusercontent.com/39693066/72143641-11e0c480-33bd-11ea-9797-d215aa26b2dd.png)

What to do? In cordova powered apps, it seems to work. 

In android, it work perfectly well even using capacitor as runtime. 

## Expected Behavior
I want Cordova inappbrowser plugin to work well with Ios also

## Sample Code or Sample Application Repo

import { InAppBrowser } from '@ionic-native/in-app-browser/ngx';

 constructor(iab: InappBrowser) {}

const browserRef = this.iab.create(`https://us-central1-cinch-eu.cloudfunctions.net/stripeClient?a=ac`, '_blank', {
          location: 'no',
          footer: 'no',
          clearcache: 'yes',
          clearsessioncache: 'yes',
          toolbar: 'no',
        });
        browserRef.show();

## Reproduction Steps
 Create a Sample Capacitor project and include Cordova-plugin-inappbrowser and run the project in Ios and try to open the web page using inappbrowser 

## Other Technical Details
   Ionic CLI                     : 5.4.13 (C:\Users\Joshuva\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.22
   @angular-devkit/schematics    : 8.3.22
   @angular/cli                  : 8.3.22
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10

**Comment by jcesarmobile** [comment]
I can't reproduce with your code. Can you provide a sample app?

**Comment by JoshuvaGeorge03** [comment]
Kindly check this repo.

https://github.com/JoshuvaGeorge03/cordova-inappbrowser-tes

**Comment by jcesarmobile** [comment]
Uggg, super weird issue.
Only happen if you call `browserRef.show();`, which you don't really need as create shows the InAppBrowser by default.
Also, it only happens randomly, but once it happens, it will happen in all subsequent calls, even if you delete the app and reinstall. But gets "unlocked" if you call create without show.

I've a simple fix that I hope won't cause other issues.
