### ISSUE TITLE
feat: Live update of an app

### ISSUE THREAD

**Issue by htorbov** [ionic-team/capacitor#2321]
Instead of publishing new updates all the time, it would be cool if we can do it remotely (for example, to fetch the www files from a web server).

I've seen Ionic's Appflow, but the price is high for our situation, since our apps are non-profit.

**Comment by jcesarmobile** [comment]
You can create your own server and implement the downloading yourself, the plugin used by Appflow is open source, you can take a look https://github.com/ionic-team/cordova-plugin-ionic

**Comment by htorbov** [comment]
@jcesarmobile one last thing - I'm actually using Capacitor + Bootstrap + Vue, instead Capacitor + Ionic + Angular. Do you think that would be a problem? I was just curious to know, before diving into tests and tryouts... Thank you!

**Comment by jcesarmobile** [comment]
The download and capacitor configuration to start from a downloaded folder is framework agnostic, so you shouldn’t have problems.

**Comment by htorbov** [comment]
@jcesarmobile, thank you so much for the `cordova-plugin-ionic` tip! I've installed it with `npm install`, changed the `endpoint` to my server, created a `.php` to handle the API and returned the new `manifest` if the user's been using an old app version (I traced the responses returned by ionicjs). Capacitor is so cool! Thanks, Ionic Team!
