### ISSUE TITLE
bug: Nothing to build in android studio when following the docs

### ISSUE THREAD

**Issue by nikita-fuchs** [ionic-team/capacitor#2323]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊 
Latest Dependencies:
  @capacitor/cli: 1.4.0
  @capacitor/core: 1.4.0
  @capacitor/android: 1.4.0
  @capacitor/ios: 1.4.0
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/cli 1.4.0
  @capacitor/android 1.4.0
  @capacitor/core 1.4.0
[success] Android looking great! 👌
```
## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
After following the docs till this point: https://capacitor.ionicframework.com/docs/basics/running-your-app I run `npx cap open android`, but the project can't be built, the button is greyed out. I Used this example: https://market.ionicframework.com/starters/test-your-first-ionic-4

## Expected Behavior
Starting android studio and building the app.

## Sample Code or Sample Application Repo: 
https://github.com/nikita-fuchs/capacitor-issue-cant-build

`npm --version` output: 6.13.6

`node --version` output: v10.16.2

**Comment by jcesarmobile** [comment]
I was able to run your app without problems.

Try the android troubleshooting docs, in particular this one about gradle sync
https://capacitor.ionicframework.com/docs/android/troubleshooting#error-please-select-android-sdk

**Comment by nikita-fuchs** [comment]
That solved the issue, thank you!
