### ISSUE TITLE
bug: can not download a file from url from a <a /> tag.

### ISSUE THREAD

**Issue by aleleba** [ionic-team/capacitor#2331]
# Bug Report

## Capacitor Version

npx cap doctor output:
Capacitor Doctor

Latest Dependencies:

@capacitor/cli: 1.3.0

@capacitor/core: 1.3.0

@capacitor/android: 1.3.0

@capacitor/ios: 1.3.0

Installed Dependencies:

@capacitor/ios 1.3.0

@capacitor/android 1.3.0

@capacitor/cli 1.3.0

@capacitor/core 1.3.0

`npx cap doctor` output:

## Affected Platform(s)

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

You cannot download a PDF file from an API that returns this file in the query from a <a /> tag inside app. It works on web navigator.

## Expected Behavior

I hope you can download a PDF file of an API that returns this file in the query from a <a /> tag in the app

## Sample Code or Sample Application Repo

```html
<a href="/url/of/API" target="_blank" rel="noopener noreferrer" >Link for download pdf file</a>
```

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
this is not possible on webviews, you need to use a plugin that allows file downloads

**Comment by aleleba** [comment]
Thanks, @jcesarmobile, what plugin do you recomend to achieve it? 😁
