### ISSUE TITLE
feat: Allow iOS ScrollView bounce to be enabled

### ISSUE THREAD

**Issue by mattjennings** [ionic-team/capacitor#2334]
# Feature Request

## Describe the Feature Request
The "rubber band" effect for scrolling the entire view in iOS is disabled. I would like to opt-in to keeping that effect.

https://github.com/ionic-team/capacitor/blob/69f589b7803c8ca9ec5801be690a1d725e06be8f/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L75

If I change this to true then it's enabled, but of course isn't permanent (I don't know much about Xcode; I assume the next pod install will overwrite it).

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Could this be toggled with an iOS setting in capacitor.config.json?

**Comment by mattjennings** [comment]
I see there's Plugins.Keyboard.setScroll()

https://capacitor.ionicframework.com/docs/apis/keyboard#method-setScroll-0

but it doesn't seem to do anything... and I'm also unsure why it's under the Keyboard plugin

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Note that since plugins have access to the webview, they can easily change this kind of property values

**Comment by littke** [comment]
@mattjennings Where you able to find a solution to this? Writing a plugin is a bit over my head at the moment.

**Comment by mattjennings** [comment]
@littke Unfortunately, no. My plan was to make the plugin but I just haven't gotten to it.

**Comment by littke** [comment]
Got it. Thanks for the quick reply. I guess I'll just change the prop for now and ... not install any pods for a while 😊

**Comment by j-jalving** [comment]
I wonder what's the reason behind disabling it? The rubber band effect is default iOS behaviour.

**Comment by littke** [comment]
Agreed.

**Comment by dwieeb** [comment]
This is a very old addition to Capacitor. I'm guessing it has something to do with Ionic Framework.

**Comment by seanaye** [comment]
Is there a solution or plugin for this issue?

**Comment by samwillis** [comment]
This would be a really good feature to have, I have a use case if that helps to justify it:

My app has a large scrolling `contenteditable`. iOS Safari / wkwebkit has a bug that when you scroll an `overflow: scroll` (like all scrollable areas in Ionic) container with a text selection or visible cursor in it the selection or cursor remain stationary fading out then jump to the final position when you stop scrolling (whereas the cursor/selection stays visible and moves nicely when it is the `<body>` scrolling). This is an un-appealing and unsightly "glitch" for an app which is primarily about text editing and so I'm hoping to use the main `<body>` scrolling (using a Vue 3 `<teleport>` to position my content behind the `<Ion-App>` and setting the ion-app to `position: fixed`), but I need to re-enable the scroll bounce for this to work nicely.

**Comment by calvinwoo** [comment]
I was able to follow @jcesarmobile 's suggestion and hook up a plugin to my app using the instructions here: https://capacitorjs.com/docs/plugins/ios

I only needed to define the `load` function for the plugin to get it working:
`WebViewPlugin.swift`
```
import Capacitor

@objc(WebViewPlugin)
public class WebViewPlugin: CAPPlugin {
    @objc override public func load() {
        // Called when the plugin is first constructed in the bridge
        self.bridge.getWebView()?.scrollView.bounces = true
    }
}
```

`WebViewPlugin.m`
```
#import <Capacitor/Capacitor.h>

CAP_PLUGIN(WebViewPlugin, "WebViewPlugin",
)
```

**Comment by jcesarmobile** [comment]
In capacitor 3 you can use your own WebView, so you can configure it the way you want

for changing values during runtime, better create a plugin of your own that exposes the properties you need

**Comment by ryaa** [comment]
> I was able to follow @jcesarmobile 's suggestion and hook up a plugin to my app using the instructions here: 

I tried this approach with capacitor 3 and it does not seem to work. The bounce is still present even though i set .scrollView.bounces = false
Not sure why this is not working. Any ideas?

**Comment by boycce** [comment]
Thanks @calvinwoo i got it working with the following


`WebViewPlugin.swift`
```
import Capacitor

@objc(WebViewPlugin)
public class WebViewPlugin: CAPPlugin {
    @objc override public func load() {
        // Called when the plugin is first constructed in the bridge
        self.bridge?.webView?.scrollView.bounces = true
    }
}
```
`WebViewPlugin.m`
```
#import <Capacitor/Capacitor.h>

CAP_PLUGIN(WebViewPlugin, "WebViewPlugin",)
```
