### ISSUE TITLE
bug: cordova-plugin-advanced-http isn't carried over when migrating to a capacitor project

### ISSUE THREAD

**Issue by Scottd125** [ionic-team/capacitor#2346]
# Bug Report

## Capacitor Version

1.4.0

`npx cap doctor` output:
```
Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0

  @capacitor/android 1.4.0

  @capacitor/ios 1.4.0
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When I take an existing ionic 4 cordova project and start the migration process to capacitor, the cordova-plugin-advanced-http isn't listed as being found for either being added or as an incompatible when running the `npx cap add android` command

```
√ Installing android dependencies in 21.55s
√ Adding native android project in: C:\Users\FoorBar\FoorBar\FoorBar\FoorBar
√ Syncing Gradle in 584.30μp
√ add in 21.65s
√ Copying web assets from www to android\app\src\main\assets\public in 832.18ms
√ Copying native bridge in 3.67ms
√ Copying capacitor.config.json in 2.66ms
/ copy  Found 13 Cordova plugins for android
    cordova-clipboard (1.3.0)
    cordova-plugin-app-version (0.1.9)
    cordova-plugin-device (2.0.3)
    cordova-plugin-facebook4 (6.2.0)
    cordova-plugin-nativestorage (2.3.2)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.4)
    cordova-plugin-x-socialsharing (5.6.3)
    cordova-sqlite-storage (3.4.1)
    es6-promise-plugin (4.2.2)
    onesignal-cordova-plugin (2.8.1)
    phonegap-plugin-barcodescanner (8.1.0)
√ copy in 1.31s
√ Updating Android plugins in 69.27ms
  Found 0 Capacitor plugins for android:
  Found 13 Cordova plugins for android
    cordova-clipboard (1.3.0)
    cordova-plugin-app-version (0.1.9)
    cordova-plugin-device (2.0.3)
    cordova-plugin-facebook4 (6.2.0)
    cordova-plugin-nativestorage (2.3.2)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-whitelist (1.3.4)
    cordova-plugin-x-socialsharing (5.6.3)
    es6-promise-plugin (4.2.2)
    onesignal-cordova-plugin (2.8.1)
    phonegap-plugin-barcodescanner (8.1.0)
| update android  Found 3 incompatible Cordova plugins for android, skipped install
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-ionic-webview (4.1.3)
    cordova-plugin-splashscreen (5.0.3)
√ update android in 470.50ms

Now you can run npx cap open android to launch Android Studio
```

I am able to successfully build and run the application however when I attempt to send a HTTP request using the cordova-plugin-advanced-http plugin, I get the following warning in the console

```
Native: tried calling HTTP.post, but the HTTP plugin is not installed.
Install the HTTP plugin: 'ionic cordova plugin add cordova-plugin-advanced-http'
```

I have ensured that the plugin has been installed by running both the commands
```
ionic cordova plugin add cordova-plugin-advanced-http
npm install @ionic-native/http
```
and removing the Android platform and rerunning the command `npx cap add android`
but I run into the same issue

## Expected Behavior

Migrating an ionic 4 project to capacitor and including the cordova-plugin-advanced-http plugin to be able to successfully make HTTP calls within the application

## Sample Code or Sample Application Repo

N/A

## Reproduction Steps

1.) Take an existing Ionic 4 project which makes use of the cordova-plugin-advanced-http plugin
2.) Migrating the project to a capacitor project 
3.) Running the built application on a device and attempt to make a HTTP call with the plugin

## Other Technical Details

`npm --version` output:
6.13.1

`node --version` output:
v10.16.3

`pod --version` output (iOS issues only):
N/A

## Other Information

Not currently listed as a known incompatible plugin in the capacitor docs
https://capacitor.ionicframework.com/docs/cordova/known-incompatible-plugins

**Comment by jcesarmobile** [comment]
can you provide a sample app? I've used cordova-plugin-advanced-http in the past without problems

**Comment by Scottd125** [comment]
Hi,

Sorry for the long duration without a reply. Our team decided to stick with using cordova for the time being with our project. I'll close this issue for now and if we end up migrating to capacitor in the future and run into the same issue i'll add a reply or create a new issue regarding this :)
