### ISSUE TITLE
Randomly stored cookies

### ISSUE THREAD

**Issue by naturalfreak** [ionic-team/capacitor#2347]
When I set cookies from my backend everything works as expected in application, but when I close the application ( both android and ios ) cookies are not stored, If I don't wait 20-30 seconds. If I set cookie and immediately close the application cookies are not stored. If I wait 20-30 seconds before   close the application, cookies are stored.

**Comment by jcesarmobile** [comment]
Please, use the template when creating issues.

On WKWebView there has always been problems like this, not really a Capacitor issue.
I've never seen something like this on Android, but it's probably also an Android WebView issue.
