### ISSUE TITLE
bug: Camera input stream is mirrored on MS Surface

### ISSUE THREAD

**Issue by keo9ren** [ionic-team/capacitor#2348]
# Bug Report

## Capacitor Version
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/ios not installed

  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0

[fatal] Platform electron is not valid.

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [x] Electron
- [ ] Web

## Current Behavior
Execute the following code on MS Surface.
```
Camera.getPhoto({
    quality: 90,
    allowEditing: true,
    resultType: CameraResultType.Uri
  });
```
The camera opens as expected, but the picture is mirrored, thinks that are on the left are shown on the right and vice versa.

Also the switch camera button doesn't switch between front and back camera.

## Expected Behavior
The camera opens and shows the pictured without the mirroring and the switch camera button switches the camera

## Sample Code or Sample Application Repo
I can provide one if neccessary

## Reproduction Steps
Execute Camera.getPhoto() in an electron app on MS Surface.

## Other Technical Details

`npm --version` output: 6.3.14

`node --version` output: v13.6.0

`pod --version` output (iOS issues only): -

**Comment by jcesarmobile** [comment]
known pwa-elements issue, already reported on it's repo https://github.com/ionic-team/pwa-elements/issues/11
