### ISSUE TITLE
Getting a javascript File from filesystem using any of the available plugin

### ISSUE THREAD

**Issue by LouAdrien** [ionic-team/capacitor#2350]
Hello, I am trying to get a File instance returning from a path in the filesystem, following the standard javascript API, but I am struggling.

https://capacitor.ionicframework.com/docs/apis/filesystem seems to only return custom type, no idea of 1) how to access the binary stream or binary data from there and or 2) how to create a File from binary if its available.

It seem that the previous plugin (https://ionicframework.com/docs/native/file) was returning a normal javascript file object, however all the documentation was removed, is there any docs available anywhere?

Regards

**Comment by jcesarmobile** [comment]
Capacitor doesn't return File objects, just the data.

If you have the file path, you can use `Capacitor.convertFileSrc('path/here');` and use XHR or fetch to get the data or blob too

**Comment by LouAdrien** [comment]
Thx,  made the trick
