### ISSUE TITLE
bug: Capacitor overrides window.File constructor

### ISSUE THREAD

**Issue by LouAdrien** [ionic-team/capacitor#2355]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/android 1.4.0

  @capacitor/ios 1.4.0

  @capacitor/core 1.4.0

## Affected Platform(s)

- [ x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When loading, capacitor exports and override the default browser [windows.File](https://developer.mozilla.org/en-US/docs/Web/API/File) constructor, which will generate File from blobs, and replace it with it s custom File method which is nothing like a real file. This is quite problematic as File creations is quite useful in real life.
Does not happen in the browser, but can be reproduced at least on Android 

## Expected Behavior

Please find a way to not override default types with capacitor?

**Comment by jcesarmobile** [comment]
No, Capacitor doesn't do that.
