### ISSUE TITLE
[Question] Apple News (2020.01.21) - App Updates for HTML5 Apps

### ISSUE THREAD

**Issue by smollweide** [ionic-team/capacitor#2359]
What does this means for Capacitor Apps?

https://developer.apple.com/news/?id=01212020a

**Comment by sandstrom** [comment]
The short answer is nothing. 

That update is primarily for apps that "browse out" to circumvent the AppStore guidelines. Capacitor apps will generally include all the HTML/JS/CSS bundled within the app/binary.
