### ISSUE TITLE
bug: App freezes on splash screen with error: Library not loaded: @rpath/Capacitor.framework/Capacitor

### ISSUE THREAD

**Issue by hanifnouhi** [ionic-team/capacitor#2360]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/cli 1.2.1

  @capacitor/core 1.2.1

  @capacitor/android 1.1.0

  @capacitor/ios 1.4.0

[success] Android looking great! 👌
  Found 11 Capacitor plugins for ios:
    @jonoj/capacitor-fused-location (1.2.1)
    cordova-plugin-add-swift-support (2.0.1)
    cordova-plugin-device (2.0.2)
    cordova-plugin-file (6.0.2)
    cordova-plugin-geolocation (4.0.2)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-ionic-webview (4.1.2)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-whitelist (1.3.3)
    cordova-plugin-zeroconf (1.4.0)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I tried to build my iOS app with capacitor. The app build and install successfully but when app try to running, it freezes in splash screen and I get this error:

dyld: Library not loaded: @rpath/Capacitor.framework/Capacitor
  Referenced from: /var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/App
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/Frameworks/Capacitor.framework/Capacitor: code signature in (/private/var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/Frameworks/Capacitor.framework/Capacitor) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/private/var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/Frameworks/Capacitor.framework/Capacitor: code signature in (/private/var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/Frameworks/Capacitor.framework/Capacitor) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/private/var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/Frameworks/Capacitor.framework/Capacitor: stat() failed with errno=1
	/private/var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/Frameworks/Capacitor.framework/Capacitor: code signature in (/private/var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/Frameworks/Capacitor.framework/Capacitor) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/private/var/containers/Bundle/Application/9AFD28DC-C86C-426F-BEEE-1A1B6D0EA41E/App.app/Frameworks/Capacitor.framework/Capacitor: stat() failed with errno=1

I got this error even with ionic conference app! 

## Expected Behavior

Just running my app in iOS like in Android!

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: 10.16.0

`pod --version` output (iOS issues only): 1.9.0.beta.2

## Other Information

`ionic info` output:
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   capacitor (Capacitor CLI) : 1.2.1
   @capacitor/core           : 1.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by jcesarmobile** [comment]
Try updating @capacitor/cli and @capacitor/core, they should match the @capacitor/ios version.

But looks like a problem in your installation, try reinstalling Xcode

**Comment by hanifnouhi** [comment]
I just installed new version of Xcode 11.3 and as I said I try to build ionic conference app but I'm facing the same issue even with same version of @capacitor/cli, @capacitor/core and @capacitor/ios!

**Comment by jcesarmobile** [comment]
Try not using beta version of CocoaPods, might be a bug there, but it’s not a capacitor issue.

**Comment by jcesarmobile** [comment]
looks similar to https://github.com/ionic-team/capacitor/issues/2383

**Comment by Narek-99** [comment]
I have the same issue. I reinstalled and updated Xcode. It doesn't work. 
Is the problem with capacitor ? 
idn what to do...

**Comment by hanifnouhi** [comment]
> I have the same issue. I reinstalled and updated Xcode. It doesn't work.
> Is the problem with capacitor ?
> idn what to do...

I don't know if it's a capacitor problem or not! @jcesarmobile  said that was not capacitor issue. I already installed new version of xcode and then reinstalled CocoaPods with stable version but nothing has changed!  
It seems that CocoaPods can't embed the capacitor and other dependents frameworks.

**Comment by bstrobach** [comment]
Deleting `node_modules` and reinstall all packages, helped me.

**Comment by Narek-99** [comment]
> Deleting `node_modules` and reinstall all packages, helped me.

it doesn't work for me. :(

**Comment by hanifnouhi** [comment]
> Deleting `node_modules` and reinstall all packages, helped me.

Not work for me!

**Comment by aschwersenz** [comment]
Same problem here, I set up a fresh ionic project with the blank template and capacitor support. Everything runs fine on the ios simulators but not on my ios device.

**Comment by adrianorsouza** [comment]
Im facing the same problem, Im able to build the App on Simulator, but not on my device getting the same error, even with the Ionic v5.

**Comment by aschwersenz** [comment]
For me, switching to a paid apple developer id magically solved the problem...

**Comment by Narek-99** [comment]
> For me, switching to a paid apple developer id magically solved the problem...

Yes but i have a normal Apple Id, also not apple developer id. But It should be work.

**Comment by adrianorsouza** [comment]
@aschwersenz Yes! After enroll for Apple Developer Program I could fix the problem as well.

**Comment by Narek-99** [comment]
> @aschwersenz Yes! After enroll for Apple Developer Program I could fix the problem as well.

it costs 100 Dollar a year ?

**Comment by hanifnouhi** [comment]
I already have a payed developer account and for me it's not working.

**Comment by ozholob** [comment]
Same issue here. Any updates?

**Comment by levytskyy** [comment]
Same issue here. Waiting for update
