### ISSUE TITLE
bug: Unable to empty the clipboard on Android

### ISSUE THREAD

**Issue by jrdnp** [ionic-team/capacitor#2363]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
💊   Capacitor Doctor  💊 

Latest Dependencies:
  @capacitor/cli: 1.4.0
  @capacitor/core: 1.4.0
  @capacitor/android: 1.4.0
  @capacitor/ios: 1.4.0

Installed Dependencies:
  @capacitor/cli 1.4.0
  @capacitor/core 1.4.0
  @capacitor/android 1.4.0
  @capacitor/ios 1.4.0

[success] Android looking great! 👌
  Found 5 Capacitor plugins for ios:
    cordova-plugin-badge (0.8.8)
    cordova-plugin-camera (4.1.0)
    cordova-plugin-email (1.2.7)
    cordova-plugin-mediapicker-dmcsdk (2.4.7)
    cordova-plugin-simple-image-resizer (0.2.0)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Clipboard cannot be emptied using empty string / null. The clipboard stays unchanged.

## Expected Behavior
The OS clipboard "string" entry should be "cleared" when calling
`Clipboard.write({ string: "" })`

## Sample Code or Sample Application Repo

```
Clipboard.write({ string: "ABCD" });
Clipboard.write({ string: ""});
```

## Reproduction Steps

1. Use the following code to set something in the clipboard :
```
Clipboard.write({ string: "ABCD" });
```
2. Paste the clipboard anywhere. Result is ABCD
3. Use the following code to empty the clipboard :
```
Clipboard.write({ string: ""});
```
4. Paste the clipboard anywhere. Result should be empty but got ABCD instead

## Other Technical Details

`npm --version` output: 6.13.2

`node --version` output: v11.0.0

`pod --version` output (iOS issues only):

## Other Information

**Comment by jcesarmobile** [comment]
I can reproduce, but only if using the web version of the plugin, not the native version, so looks like you are doing something wrong.
If you do `Device.getInfo()` do you get android or web on the platform?

**Comment by jrdnp** [comment]
Yes, it's Android platform. `Device.getInfo()` give me :
```
{
  memUsed: 19430728
  diskFree: 84848640
  diskTotal: 3084054528
  model: "SM-A510F"
  operatingSystem: "android"
  osVersion: "7.0"
  appVersion: "1.9.1"
  appBuild: "2001011300"
  platform: "android"
  manufacturer: "samsung"
  uuid: "<uuid>"
  batteryLevel: 0.5
  isCharging: true
  isVirtual: false
}
```

**Comment by jcesarmobile** [comment]
and if you use 
```
Clipboard.read({
  type: "string"
});
```
Do you still get ABCD?

**Comment by jrdnp** [comment]
I tried this code :
```
await Clipboard.write({ string: "ABCD0" });
console.log(await Clipboard.read({ type: "string" }));
await Clipboard.write({ string: "" });
console.log(await Clipboard.read({ type: "string" }));
```

And it logged :
```
{ string: "ABCD" }
{ string: "" }
```

Console logs seem fine BUT if I go paste my clipboard anywhere like the search field of a message app, it pastes ABCD instead of an empty string. So my Capacitor tells me the OS clipboard is empty but it's not.

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce.

Clipboard is a heap, so it's not really possible to delete value, it just add a new one on top of the heap, and read return the last one. It's possible that samsung devices pick the previous value if the last one is `""`.
