### ISSUE TITLE
bug: inconsistency in Clipboard.read

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#2365]
on iOS the type of Clipboard.read defaults to string
on Android the type is not used
on web/electron the type is required

all platforms should behave the same way

**Comment by nphyatt** [comment]
what is the purpose of the `type` ?  shouldn't it just always be a string?

**Comment by jcesarmobile** [comment]
Type can be string, url or image
https://github.com/ionic-team/capacitor/blob/b650880df3cf92e112799b4ae4cfdf7f6b342132/core/src/core-plugin-definitions.ts#L394
