### ISSUE TITLE
Ionic 4 / Capacitor : Password autofill option not displaying in iPhone for ion-input types email / text

### ISSUE THREAD

**Issue by hgomatum** [ionic-team/capacitor#2367]
After migrating our app to Ionic 4, password autofill option in iPhone not displaying for email / text input types except for password input (ion-input) . It was working in Ionic 3 apps. Have configured the property **autocomplete="on"** as well but it doesn't seem to work. 

![Email - Password Autofill](https://user-images.githubusercontent.com/2988863/72944648-5c076580-3d2e-11ea-8156-ed7f5664f1cf.png)
![Password Autofill](https://user-images.githubusercontent.com/2988863/72944650-5c076580-3d2e-11ea-9028-aeddfd8de528.png)

**Environment Details:**
iOS Version: 12x, 13x.

**Ionic:**

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

**Capacitor:**

   capacitor (Capacitor CLI) : 1.1.1
   @capacitor/core           : 1.1.1

**Comment by jcesarmobile** [comment]
was your Ionic 3 app a Capacitor app or a Cordova app?

**Comment by hgomatum** [comment]
Yes we are using capacitor app only.

**Comment by bryplano** [comment]
There is a related issue (currently closed to prevent additional unrelated comments) on the Ionic repo: https://github.com/ionic-team/ionic/issues/19478

Relates to a Webkit bug, see my comment here: https://github.com/ionic-team/ionic/issues/19478#issuecomment-559126738

Are you nesting your input fields? Might be able to get around this by simply pulling them to a higher level in your HTML. Don't believe this is a Cap issue myself...

**Comment by jcesarmobile** [comment]
agree with bryplano, this isn't a Capacitor bug, closing
