### ISSUE TITLE
bug: APIs App plugin bug when navigating through hardware back button.

### ISSUE THREAD

**Issue by mentorkadriu** [ionic-team/capacitor#2370]
# Bug Report

## Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0

  @capacitor/android 1.4.0
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When pressing hardware (device) back button. It goes back sometimes two, one or more screens.

## Expected Behavior

When pressing hardware (device) back button it should go back one step on history and navigate to respective screen.

## Sample Code or Sample Application Repo
[Repository](https://github.com/mentorkadriu/ionic-app-plugin-bug)

```
  import {Plugins} from "@capacitor/core";
  
  const {App} = Plugins;
  
  App.addListener("backButton", () => {
    switch (window.location.pathname) {
      case "/tab1":
          console.log('you are on tab1');
          window.history.back();
        break;
      default:
        window.history.back();
    }
  });
```

## Other Technical Details

`npm --version` output:
6.4.1
`node --version` output:
v10.6.0
`pod --version` output (iOS issues only):

**Comment by mentorkadriu** [comment]
Hi @jcesarmobile 
Did you have time to check issue? Would be of great help if could check into it.

Thanks.

**Comment by jcesarmobile** [comment]
I'm pretty sure Ionic already have a backButton handler and it's probably messing with yours. Not sure if you can disable/not use the Ionic one, but this isn't a Capacitor issue.

**Comment by OoDeLally** [comment]
I had the same issue. 
If you use Ionic, you need to disable Ionic's default handler:
angular: https://ionicframework.com/docs/angular/config
react: https://ionicframework.com/docs/react/config
Set `hardwareBackButton` to false.
