### ISSUE TITLE
bug: Native platform not recognized when fetching app from remote url

### ISSUE THREAD

**Issue by aalvarez255** [ionic-team/capacitor#2373]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios not installed

  @capacitor/cli 1.4.0

  @capacitor/android 1.4.0

  @capacitor/core 1.4.0

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When using `server.url` to fetch my app from a public web server, the current native platform is not detected and `Capacitor.platform` always outputs `web`. That makes android plugins not execute.

If `server.url` is not used, `Capacitor.platform` shows `android` and native plugins are successfully executed.

## Expected Behavior

When fetching the app from a remote `server.url`, `Capacitor.platform` should output `android` when running on Android platform.

## Reproduction Steps

To reproduce it, I created an empty app using `create-react-app`. Then, I built it and deployed to a local IIS on my computer with the url http://localhost:80.

Finally, I set up `capacitor.config.json` to fetch the react app from this url and run the app on android.

```
{
  "appId": "test.app",
  "appName": "test-app",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "build",
  "cordova": {},
  "server": {
    "url": "http://10.0.2.2:80"
  }
}
```

(`10.0.2.2` is used instead of `localhost` to proxy android emulator).

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.16.0

**Comment by jcesarmobile** [comment]
Can you inspect the index.html and check the head to see if the Capacitor javascript was injected?
Also, check logcat and see if there are errors telling you that capacitor failed to be injected.

Could be an misconfiguration of the IIS server not providing the proper mime type for the html files, I can't reproduce with a node server.

**Comment by aalvarez255** [comment]
@jcesarmobile Definetly, it has something to do with web server configuration. I uploaded the SAME app to two different hosting platforms:

- Google cloud: https://storage.googleapis.com/pos-core/index.html
- Azure: https://aalvarezstorage.z6.web.core.windows.net/index.html

With Google Cloud, `Capacitor.platform` always outputs `web`, even in Android platform. On the other hand, Azure works fine.

I compared HTTP headers and Content-Type seems fine in both urls. Do you guys expect any specific HTTP configuration from server when fetching url from capacitor webview? 

I'm kind of stuck here, I'll appreciate any help I could get. Thanks :/

**Comment by jcesarmobile** [comment]
It's working on both, but just the fist time, the second time the app is loaded from the service worker so Capacitor doesn't get injected

**Comment by aalvarez255** [comment]
I see.. so this approach where I fetch the app from `server.url` and use a service worker to have offline caching is not supported with capacitor right?
I guess I'll have to just package the web with the native apps. Thanks.

**Comment by jcesarmobile** [comment]
Well, `server.url` is meant for development, not Apple nor Google like apps that just point to a remote url and might reject your app if they notice.

But maybe this helps, is to make the service worker load the local assets (didn't try)
 https://stackoverflow.com/questions/55894716/how-to-package-a-hosted-web-app-with-ionic-capacitor

**Comment by aalvarez255** [comment]
I know, but there are many enterprise apps, like mine, where publishing to store is not requirement. I think `server.url` could be a lot more helpful on those situations (just a suggestion :P). 

Thanks for the link, I'll take look :)
