### ISSUE TITLE
bug: cordova preferences are not set in the internal config.xml on iOS

### ISSUE THREAD

**Issue by slajar** [ionic-team/capacitor#2375]
# Bug Report

## Capacitor Version
`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.4.0

  @capacitor/ios 1.4.0

  @capacitor/core 1.4.0

## Affected Platform(s)

- [ ] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
I provide a cordova pref in the capacitor.config.json
like:
 "cordova": { 
    "preferences": { 
      "APP_SECRET": "XXXXXXXXXXXX" 
    }
  }

Those prefs are not shown in the platform specific config.xml only the auto generated parts for the plugins are visible.

## Expected Behavior
I expect to see it in config.xml on iOS in the App folder.

## Sample Code or Sample Application Repo

it is the same like this issue: #1944 

## Reproduction Steps

it is the same like this issue: #1944 

## Other Technical Details

`npm --version` output: 6.13.6

`node --version` output: v10.15.0

`pod --version` output (iOS issues only): 1.7.5

## Other Information
it is the same like this issue: #1944

**Comment by jcesarmobile** [comment]
You have to run copy, update or sync commands after adding the preference. Just tried and it's working fine.
