### ISSUE TITLE
bug: LocalNotifications not canceled when scheduled with options every

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/capacitor#2377]
# Bug Report

## Affected Platform(s)
- [X] Android
- [ ] iOS (not tested)

## Current Behavior
`LocalNotifications` are not canceled on Android when `scheduled` with the options `every`. 

Even if the function `cancel()` is called, notifications are still going to be triggered.

## Expected Behavior
Being able to cancel local notifications.

## Sample Code or Sample Application Repo

Full implementation: https://github.com/peterpeterparker/tietracker/blob/master/src/services/notifications/notifications.service.ts

Schedule:

```
await LocalNotifications.schedule({
                notifications: [
                    {
                        title: 'yolo',
                        body: 'body',
                        id: new Date().getTime(),
                        schedule: {
                            every: 'minute',
                            count: 30
                        }
                    }
                ]
            });
```

Cancel: 

```
const pendingList: LocalNotificationPendingList = await LocalNotifications.getPending();

            if (!pendingList || !pendingList.notifications || pendingList.notifications.length <= 0) {
                return;
            }

            await LocalNotifications.cancel(pendingList);
```

## Sample project

My app: https://github.com/peterpeterparker/tietracker

## Capacitor Version

> ❯ npx cap doctor
> 💊   Capacitor Doctor  💊 
v
> Latest Dependencies:
> 
> @capacitor/cli: 1.4.0
> 
> @capacitor/core: 1.4.0
> 
> @capacitor/android: 1.4.0
> 
> @capacitor/ios: 1.4.0
> 
> Installed Dependencies:
> 
> @capacitor/cli 1.4.0
> 
> @capacitor/ios 1.4.0
> 
> @capacitor/android 1.4.0
> 
>  @capacitor/core 1.4.0
>  
>  
>  [success] Android looking great! 👌
>    Found 3 Capacitor plugins for ios:
>      cordova-plugin-file (6.0.2)
>      cordova-plugin-x-socialsharing (5.6.3)
>      es6-promise-plugin (4.2.2)
>  [success] iOS looking great! 👌

**Comment by jcesarmobile** [comment]
looks similar to this previous issue of yours https://github.com/ionic-team/capacitor/issues/948

**Comment by peterpeterparker** [comment]
@jcesarmobile I didn't remembered that one. Yes looks similar, specially as I wrote in the previous issue:

> Furthermore, on Android, seems that cancel doesn't work.

Should we close this one. 

The other issue is > 1 year old. I'm the only one facing this problem or I do something wrong?

**Comment by peterpeterparker** [comment]
Just saw this ticket and workaround from @corysmc:  https://github.com/ionic-team/capacitor/issues/844

Maybe it is still a thing and the problem. Will try a version without `await` as pointed out.

**Comment by peterpeterparker** [comment]
@jcesarmobile I think I found the problem.

In capacitor the method `cancel` of the Android `manager` is called, reference https://github.com/ionic-team/capacitor/blob/080910153faa33e6e119ee5ff25658434ffd0947/android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java#L79

According the Android documentation, cancel could be used to cancel a specific id only. To remove all notification, `cancelAll` should be used, reference: https://developer.android.com/training/notify-user/build-notification

**Comment by peterpeterparker** [comment]
Also, which would maybe solve https://github.com/ionic-team/capacitor/issues/844, isn't a `call.success();` missing at the end of the implementation of the method cancel?

**Comment by peterpeterparker** [comment]
So one error is that, to randomize the Id, I use `new Date().getTime()` which produce a too big number as Android Capacitor is expecting an `Integer`

That being said, there still another issue as I faced the same problem when using the id value `1`.

**Comment by peterpeterparker** [comment]
Duplicate of already existing issue #948

Looks like the problem happens when the cancel is called after at least one notifications has been triggered

Ugly workaround: in the manager, replace `notificationManager.cancel(notificationId);` with `notificationManager.cancelAll();`

**Comment by prabhashibuddhima** [comment]
> Duplicate of already existing issue #948

Hi, have you solved the issue? can you please kindly help me?

**Comment by peterpeterparker** [comment]
@prabhashibuddhima I debugged a bit but was never able to reproduce the pattern. I the end of the day I think I used the cordova plugin for that feature.

**Comment by peterpeterparker** [comment]
I give it a try again, still buggy.

Pattern:

- schedule a notification every 1 minute
- close app
- wait for notification
- click on notification to open app
- in app, list pending notifications
- cancel these notifications
- close app

=> notification will still happen

**Comment by jcesarmobile** [comment]
please, don't reopen ancient issues, create a new issue and provide all the required and up to date information including a sample app that reproduces the issue, the provided sample app doesn't use @capacitor/local-notifications plugin but a cordova one.
