### ISSUE TITLE
bug: Error when open iOS App

### ISSUE THREAD

**Issue by arielhernandezmusa** [ionic-team/capacitor#2383]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

💊   Capacitor Doctor  💊 

Latest Dependencies:
  @capacitor/cli: 1.4.0
  @capacitor/core: 1.4.0
  @capacitor/android: 1.4.0
  @capacitor/ios: 1.4.0

Installed Dependencies:
  @capacitor/cli 1.4.0
  @capacitor/ios 1.4.0
  @capacitor/core 1.4.0
  @capacitor/android 1.4.0

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

App close immediately after opens, and on Xcode we get this error

`
dyld: Library not loaded: @rpath/Capacitor.framework/Capacitor
  Referenced from: /private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/App
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/Frameworks/Capacitor.framework/Capacitor: code signature invalid for '/private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/Frameworks/Capacitor.framework/Capacitor'

	/private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/Frameworks/Capacitor.framework/Capacitor: code signature invalid for '/private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/Frameworks/Capacitor.framework/Capacitor'

	/private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/Frameworks/Capacitor.framework/Capacitor: stat() failed with errno=1
	/private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/Frameworks/Capacitor.framework/Capacitor: code signature invalid for '/private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/Frameworks/Capacitor.framework/Capacitor'

	/private/var/containers/Bundle/Application/BA056E17-46F0-4B84-AEB1-6D3B7D85FEA6/App.app/Frameworks/Capacitor.framework/Capacitor: stat() failed with errno=1
(lldb) 
`

## Expected Behavior

App open without problems

## Sample Code or Sample Application Repo
https://github.com/arielhernandezmusa/capacitor-camera-preview-demos/tree/master/ccpd-react

## Reproduction Steps
run npx open ios and start the app on a device

## Other Technical Details

`npm --version` output: 6.12.1

`node --version` output: v12.13.1

`pod --version` output (iOS issues only): 1.8.4

**Comment by heda** [comment]
Same error on 2 iPhone7 after updating to iOS 13.3.1 (Same version of app worked before iOS update)

On Multiple iPads with iOS 13.3 no error, runs perfectly fine.

**Comment by jcesarmobile** [comment]
It's some CocoaPods problem, a lot of projects are affected.
In one of the issues I saw this

> Are you using a non-developer Apple ID to install the app to your phone? It looks like iOS 13.3.1 has broken apps installed with free Apple IDs, but only if they contain embedded frameworks. 

Are you using a free or paid account?

I've been using 13.3.1 beta for a while without problems

**Comment by heda** [comment]
For me it‘s the free account.

**Comment by arielhernandezmusa** [comment]
Yep, if’s the free account, with a paid account the app runs without problems

**Comment by jcesarmobile** [comment]
going to close with Apple bug tag, it's either an Xcode bug or CocoaPods bug, nothing we can do from Capacitor.

I've seen some suggestions of removing `use_frameworks!` from the Podfile, but not sure if Capacitor will work without it

**Comment by erichstark** [comment]
I suggest you to use iOS simulator and wait when Apple fix this.

**Comment by tiagomsmagalhaes** [comment]
I have just encountered this same bug. Meanwhile iOS 13.4, macOS 10.15.4 and Xcode 11.4 has been released and the bug appears to be fixed. Could you check again @arielhernandezmusa @heda ?

**Comment by SSuarezBrooktec** [comment]
I have the same issue i think: https://github.com/ionic-team/capacitor/issues/2638

**Comment by aaqibkhorasi** [comment]
I am having a same issue. 
Can someone help?. I am using paid account and despite that I am getting same error.

**Comment by SSuarezBrooktec** [comment]
Upgrading to Capacitor 2.0
