### ISSUE TITLE
bug: Icons aren't being changed for android or ios when running npx cap copy.

### ISSUE THREAD

**Issue by sergiotapia-papa** [ionic-team/capacitor#2386]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
$ npx capacitor doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/ios 1.4.0

  @capacitor/cli 1.4.0

  @capacitor/android 1.4.0

  @capacitor/core 1.4.0


[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

This is for a Ionic Framework 4, React, Capacitor application.

Changed the 512x512 default icon for a different 512x512 png icon, ran `ionic build`, then `npx cap copy`, finally ran on ios and android with `npx open ios/android`.

The application icon doesn't change no matter what I do.

```
$ npx cap copy
✔ Copying web assets from build to android/app/src/main/assets/public in 292.39ms
✔ Copying native bridge in 1.72ms
✔ Copying capacitor.config.json in 1.23ms
✔ copy in 307.61ms
✔ Copying web assets from build to ios/App/public in 252.97ms
✔ Copying native bridge in 1.09ms
✔ Copying capacitor.config.json in 2.52ms
✔ copy in 272.43ms
✔ copy in 546.76μp
```

Checking in my Git client, not changes are made to the ios or android apps to the icons.

![image](https://user-images.githubusercontent.com/52164116/73382393-65944e80-4295-11ea-89d3-dbdaadabd440.png)

## Expected Behavior

I expect the icons to change.

## Sample Code or Sample Application Repo

No code sample, this is just a brand new app. First steps I changed the app name, then got stuck changing the icon.

## Reproduction Steps

Create a new project, and change the icon. Run the commands above.

**Comment by jcesarmobile** [comment]
Capacitor doesn't support changing the app icons from the CLI, you have to generate and copy them manually.
There is an issue already https://github.com/ionic-team/capacitor/issues/229

**Comment by ShayanJavadi** [comment]
@jcesarmobile would there be an interest in adding this functionality? I can make a PR. Would love to see asset generating added to Capacitor
