### ISSUE TITLE
bug: Unable to launch Android Studio on Windows

### ISSUE THREAD

**Issue by TheLazyHatGuy** [ionic-team/capacitor#2390]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
λ npx cap doctor
ERROR: The system was unable to find the specified registry key or value.
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0

  @capacitor/ios 1.4.0

  @capacitor/android 1.4.0

[success] Android looking great! �
[error] Xcode is not installed

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Attempting to open the android project using `npx cap open android` fails every time.
I have android studio install via Jetbrains Toolbox.

## Expected Behavior

Android studio opens the project.

## Sample Code or Sample Application Repo
I'm just using the standard ionic tabs template

## Reproduction Steps

Run the command `npx cap open android`
Get the following output: 
```
ERROR: The system was unable to find the specified registry key or value.
[info] Opening Android project at C:\Users\USER\Documents\PROJECT\android
[error] Unable to launch Android Studio. Make sure the latest version of Android Studio is installed
```

## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.14.1

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
was fixed already https://github.com/ionic-team/capacitor/pull/2364
