### ISSUE TITLE
feat: Secure Storage API

### ISSUE THREAD

**Issue by TehNrd** [ionic-team/capacitor#2394]
# Feature Request

## Describe the Feature Request
Provide a simple and secure way to store secrets in a Capacitor application.

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

Web would not be supported. Electron, I am not familiar enough with to know if there is a secure storage mechanism.

## Describe Preferred Solution
It would be very similar to the existing Storage API. In fact, the API interface would be nearly identical if not exactly the same. The difference would be where the values are stored. On iOS it would be in the [Keychain](https://developer.apple.com/documentation/security/keychain_services). On Android, it would be in [EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences).

One potential issue is that EncryptedSharedPreference currently requires Android API version 23 (Android 6.0 Marshmallow) and Capacitor is still supporting 5.0.

## Describe Alternatives
There is an existing secure storage plugin, https://github.com/martinkasa/capacitor-secure-storage-plugin, but it does not use EncryptedSharedPrefences and implements its own encryption process.

There is also Identify Vault provided by Ionic. It does cost money and is focused on identity and sessions. It does not work as well for simple non-identity secure storage use cases.

## Additional Context

Storing secrets is a core tenet of many applications and this feels like a hole in the current Capacitor Platform. I am probably going to take a stab and building a stand-alone plugin anyway but I wanted to at least suggest the idea of building this into core since nearly every app will need this.

I also completely understand if there is a strategic business decision for not wanting to add this to core in order to get people to use Identify Vault, but I still think that does so much more than this API would.

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.

But as you say, it's not likely to be implemented in core since there are two paid plugins for secure storage (IV and offline-storage)

Anyway, the plugin request tag is also good for 3rd parties interested in developing capacitor plugins (free or paid), they can easily see which plugins have more people interested based on the number of 👍 reactions

**Comment by dwieeb** [comment]
@Tehnrd Would you mind re-creating this in our new [Capacitor Community proposals repo](https://github.com/capacitor-community/proposals)?

**Comment by TehNrd** [comment]
@dwieeb Done! https://github.com/capacitor-community/proposals/issues/25

**Comment by dwieeb** [comment]
Thank you! 🎉
