### ISSUE TITLE
Add handleOnDestroy for an Android plugin

### ISSUE THREAD

**Issue by jlebras** [ionic-team/capacitor#2399]
# Add handleOnDestroy for an Android plugin

## Describe the Feature Request
The Android Plugin class has some android activity lifecycle methods which can be overwritten like handleOnResume, handleOnPause, etc...

Would it be possible to add a method handleOnDestroy to the Plugin which is called when the bridge activity's onDestroy is called ?

My use case is the need to clean up things when the app is killed (like programatically generated windows which persist even when the app is killed by the user...).

I'm aware that in some cases the onDestroy activity's method may not be called but I think it doesn't hurt to add it to the plugin Api.

## Platform Support Requested

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Related Code
For the meantime I edited the capacitor code to handle this (in the node_modules...).  
Because those are  simple modifications , I'm writting them here.

BridgeActivity.java
```
 @Override
 public void onDestroy() {
   super.onDestroy();
   this.bridge.onDestroy();
   if (this.mockWebView != null) {
     mockWebView.handleDestroy();
   }
   Log.d(LogUtils.getCoreTag(), "App destroyed");
 }
```

Bridge.java
```
/**
 * Handle onDestroy lifecycle event and notify the plugins
 */
 public void onDestroy() {
   for (PluginHandle plugin : plugins.values()) {
     plugin.getInstance().handleOnDestroy();
   }
 }
```
Plugin.java
```
/**
 * Handle onDestroy
 */
protected void handleOnDestroy() {}
```

**Comment by jcesarmobile** [comment]
sounds good, maybe you can send a PR with those changes?

**Comment by jlebras** [comment]
Yes sure, here is the PR #2421
