### ISSUE TITLE
Site: Display of anchors is flakey

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#241]
Sometimes the anchor links to link to headlines is displayed, sometimes it's not:

![no-anchors](https://user-images.githubusercontent.com/183673/36910297-98a85292-1e40-11e8-93ef-f8ad6ae9eec5.PNG)
![anchors](https://user-images.githubusercontent.com/183673/36910298-99032ca8-1e40-11e8-963c-180bee4c079b.PNG)

(Chrome 64.0.3282.167 on Windows 10)

**Comment by janpio** [comment]
For some pages I can't make it work not matter how much I navigate around:
https://capacitor.ionicframework.com/docs/web/ is one example.

**Comment by mlynch** [comment]
Fixed
