### ISSUE TITLE
feat: Automatic Community Plugin Registration on Android

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [ionic-team/capacitor#2413]
# Feature Request

## Describe the Feature Request

Capacitor Community Plugins should be automatically registrated on Android as it already happens in iOS.

## Platform Support Requested

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Assuming that when `npx cap sync` is running, Capacitor plugins are automatically registered on iOS, the same should done on Android.

## Related Code

```java
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
    }});
  }
}
```

**Comment by jcesarmobile** [comment]
Would be nice, but it’s not possible (or at least we didn’t figure out how)
