### ISSUE TITLE
bug: Splash screen does not respect navigationBar color setting

### ISSUE THREAD

**Issue by IljaDaderko** [ionic-team/capacitor#2422]
# Bug Report

## Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/cli 1.5.0

  @capacitor/ios 1.5.0

  @capacitor/core 1.5.0

  @capacitor/android 1.5.0


[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
I have custom code in my `MainApplication.java` file that sets android's navbar color to black.
It works initially when I launch my app, but after it goes to capacitor splash screen, color is changed back to default android one, which in my case happens to be light grey (samsung galaxy s8). Gif below demonstrates this: notice how it goes from black -> default gray

![giphy](https://user-images.githubusercontent.com/3154053/74054834-7193b500-49e7-11ea-94fd-64fa4814da1b.gif)

## Expected Behavior

Should keep navbar black all the time.

## Sample Code or Sample Application Repo

This is my `MainApplication.java` and `setAndroidUiColor();` is what sets color of navbar to be black.

```java
package com.asimetriq.skimitar;

import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;

public class MainActivity extends BridgeActivity {


  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    setAndroidUiColor();

    /**
     * Initialize capacitor bridge
     */
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
    }});
  }

  @Override
  public void onWindowFocusChanged(boolean hasFocus) {
    super.onWindowFocusChanged(hasFocus);
    if (hasFocus) {
      setAndroidUiColor();
    }
  }

  private void setAndroidUiColor() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
      getWindow().setNavigationBarColor(Color.rgb(0, 0, 0));
    }

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
      getWindow().setNavigationBarDividerColor(Color.rgb(0, 0, 0));
    }
  }
}

```
## Reproduction Steps

You can add `setAndroidUiColor();` implementation to default capacitor app and launch it in simulator on a samsung galaxy s8 device, or perhaps newer model, I assume they will run similar version of android.

## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output:v12.14.1

`pod --version` output (iOS issues only): 1.8.4

## Other Information
 
This is happening on android 9 for me. I also don't see it on all devices i.e. simulator for pixel 3 seems ok, but I think default color for navbar there is transparent, so it could be setting it back to transparent and blending with black background.

**Comment by jcesarmobile** [comment]
this would need a new configuration option for Splash plugin to set the Navigation Bar color

**Comment by IljaDaderko** [comment]
Alright, will work on it tomorrow 👍 I guess something like `splashImmersive` so it aligns with `splashFullScreen`.  I assume all logic for this is just in this file?: https://github.com/ionic-team/capacitor/blob/9521e0a777760dcf0a824f670007ddb974f33e6c/android/capacitor/src/main/java/com/getcapacitor/Splash.java

And besides `Config.getString` I don't need anything extra to add these flags? (Will likely add one for #2422 as well then).

**Comment by IljaDaderko** [comment]
I'm having few issues implementing this inside `Splash.java` atm. It requires `getWindow()` which is only available on activity. I can see that methods `showOnLaunch` and `show` expose it. so I tried to add following in all of these methods, but it seems that it doesn't have any effect. Can I access `getWindow` earlier somewhere?

```java
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
      a.getWindow().setNavigationBarColor(Color.rgb(0, 0, 0));
    }

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
      a.getWindow().setNavigationBarDividerColor(Color.rgb(0, 0, 0));
    }
```

**Comment by jcesarmobile** [comment]
looks like it got fixed by https://github.com/ionic-team/capacitor/pull/2603

**Comment by IljaDaderko** [comment]
Nice! I'll test this tomorrow. I think `splashImage.setFitsSystemWindows(true);` might also fix "jump" effect I had in this PR https://github.com/ionic-team/capacitor/pull/2425 but I will confirm for sure once I'm next to my mac.

**Comment by jcesarmobile** [comment]
yes, it does
