### ISSUE TITLE
feat: Allow fullscreen immersive mode in splash screen

### ISSUE THREAD

**Issue by IljaDaderko** [ionic-team/capacitor#2423]
# Feature Request

## Describe the Feature Request
Android has an option to hide navigation bar and action bar to allow for full screen experience, they call it immersive: https://developer.android.com/training/system-ui/immersive

This is common for many apps and we can do it now in MainActivity.java however while splash screen is launching, it is still showing the navbar. Recent changes with addition of `splashFullScreen` allow us to hide action bar however.

## Platform Support Requested

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
ideally we could make another flag that allows to hide it?

## Describe Alternatives
Not sure if any exist

## Related Code
I was able to implement this in my `MainActivity.java` file like this:

```java
package com.asimetriq.skimitar;

import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.view.View;

import com.asimetriq.skimitar.ASQPlugins.GoogleAuth;
import com.asimetriq.skimitar.ASQPlugins.SafeArea;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;

public class MainActivity extends BridgeActivity {


  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    hideSystemUI();

    /**
     * Initialize capacitor bridge
     */
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(GoogleAuth.class);
      add(SafeArea.class);
    }});
  }

  @Override
  public void onWindowFocusChanged(boolean hasFocus) {
    super.onWindowFocusChanged(hasFocus);
    if (hasFocus) {
      hideSystemUI();
    }
  }

  /**
   * Hide android navbar and toolbar for full screen experience
   */
  private void hideSystemUI() {
    final int flags = View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_FULLSCREEN
            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
    View decorView = getWindow().getDecorView();

    decorView.setSystemUiVisibility(flags);
    decorView.setOnSystemUiVisibilityChangeListener((int visibility) ->  {
      if((visibility & View.SYSTEM_UI_FLAG_FULLSCREEN) == 0) {
        decorView.setSystemUiVisibility(flags);
      }
    });
  }
}
```

**Comment by IljaDaderko** [comment]
I am open to implement this if you give me some pointers and we agree on how this implementation looks.

**Comment by jcesarmobile** [comment]
so, what's the problem with `splashFullScreen`? 
I see the splash image at full screen with no bars

**Comment by IljaDaderko** [comment]
On pixel 3 with API 28 emulator, it only hides that top bar that holds your time / signal strength etc. Navigation bar (bottom one) stays intact. When it goes into my app (I assume hits MainActivity?) it hides it.

<img width="332" alt="Screenshot 2020-02-07 at 20 48 33" src="https://user-images.githubusercontent.com/3154053/74056793-51fe8b80-49eb-11ea-97f9-fe9e59753471.png">

**Comment by IljaDaderko** [comment]
I also edited my styles xml to look like this, but no luck

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:background">@drawable/splash</item>
        <item name="android:windowLayoutInDisplayCutoutMode" tools:targetApi="27">shortEdges</item>
        <item name="android:colorPrimary">@android:color/black</item>
        <item name="android:colorPrimaryDark">@android:color/black</item>
        <item name="android:navigationBarColor">@android:color/black</item>
        <item name="android:navigationBarDividerColor" tools:targetApi="27">@android:color/black</item>
        <item name="android:statusBarColor">@android:color/black</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowFullscreen">true</item>
    </style>
</resources>
```

**Comment by jcesarmobile** [comment]
Ah, yeah, sorry, I tested on devices with physical nav "bar", so didn't get you at first.

Feel free to send a PR with a new "inmersive" (or similar name) option for the Splash, similar to the "splashFullScreen" one.

**Comment by IljaDaderko** [comment]
Alright, will work on it tomorrow 👍 I guess something like splashImmersive so it aligns with splashFullScreen. I assume all logic for this is just in this file?: https://github.com/ionic-team/capacitor/blob/9521e0a777760dcf0a824f670007ddb974f33e6c/android/capacitor/src/main/java/com/getcapacitor/Splash.java

And besides `Config.getString` I don't need anything extra to add these flags? (Will likely add one for #2422 as well then).

**Comment by jcesarmobile** [comment]
Yeah, everything should go there in that file. Also document it on https://capacitor.ionicframework.com/docs/apis/splash-screen

And if you are also going to add another preference for #2422, do it as separate PRs

**Comment by Pacjonek** [comment]
I had to add the following line to get immersive mode working properly (style.xml). Otherwise a grey bar was displayed
```xml
        <item name="android:fitsSystemWindows">true</item>
```
