### ISSUE TITLE
Capacitor and @ionic-native/web-intent not building Android

### ISSUE THREAD

**Issue by fabiobeoni** [ionic-team/capacitor#2424]
Hello everyone,

in Capacitor/Ionic documentation I read I can install the `@ionic-native/web-intent`, but unfortunately if do that the android build breaks with the following error:

> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86
	is also present at [**com.android.support:support-compat:28.0.**0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-48:19 to override.

Looks like there is an issue with the `android/app/capacit.build.gradle` dependencies:

```
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-compat:28.0.0'
```

Thanks.

**Comment by jcesarmobile** [comment]
Your problem is the plugin uses Android X dependencies, Capacitor doesn't support Android X yet, see https://github.com/ionic-team/capacitor/issues/1937
