### ISSUE TITLE
bug: sync android keeps adding cordova

### ISSUE THREAD

**Issue by xenoterracide** [ionic-team/capacitor#2428]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Calebs-MBP:warmaster calebcushing$ npx capacitor doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.5.0

  @capacitor/android 1.5.0

  @capacitor/core 1.5.0


[fatal] Platform electron is not valid.
[success] Android looking great! 👌
```
side topic, what does it mean electron is not valid...

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
when I run `npx cap sync`,  it keeps changing this

```diff
diff --git a/android/app/src/main/res/xml/config.xml b/android/app/src/main/res/xml/config.xml
index 1e5c193..1b1b0e0 100644
--- a/android/app/src/main/res/xml/config.xml
+++ b/android/app/src/main/res/xml/config.xml
@@ -1,6 +1,6 @@
 <?xml version='1.0' encoding='utf-8'?>
-<widget version="1.0.0" xmlns="http://www.w3.org/ns/widgets">
-  <access origin="*"/>
-
-
-</widget>
+<widget version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
+  <access origin="*" />
+  
+  
+</widget>
\ No newline at end of file
```

however android studio seems very unhappy about these changes (it's fine beforehand)

> Compilation is not supported for following modules: capacitor-cordova-android-plugins, capacitor-android. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

## Sample Code or Sample Application Repo

https://github.com/xenoterracide/capacitor-android-issue-repro

## Reproduction Steps

```
yarn start:android
```

## Other Technical Details
Android Studion 3.5.3
```
Calebs-MBP:warmaster calebcushing$ npm --version
6.13.4
Calebs-MBP:warmaster calebcushing$ node --version
v12.15.0
```

**Comment by jcesarmobile** [comment]
when you run npx cap sync some files are removed and added again and that sometimes confuses Android Studio, if that happens you have to click the "Sync project with gradle files"

About the electron not valid, I've created a separate issue https://github.com/ionic-team/capacitor/issues/2429
