### ISSUE TITLE
Capacitor - Camera image flipped when taking a picture

### ISSUE THREAD

**Issue by smartin281092** [ionic-team/capacitor#2432]
Hi everybody,

I noticed a strange behaviour of the Camera API from capacitor when taking pictures. All photos taken are flipped (and the final image is a bit larger than when the camera is live). 
A simple CSS rule like transform: scaleX(-1) could to the trick, however, as the UI for validating the image is in a shadow root called through the function Camera.getPhoto(), it is not possible to modify it (or at least I didn't find a proper way to achieve it).
To reproduce the issue, just follow the tutorial at : https://ionicframework.com/docs/angular/your-first-app and serve the app.
Is it an intentional behaviour or am I missing a configuration ? If not, could it be possible to change it in the package ? It's quite disturbing...

Best regards,

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/pwa-elements/issues/11
