### ISSUE TITLE
"npx cap add android" gives error

### ISSUE THREAD

**Issue by ragavanrandy** [ionic-team/capacitor#2437]
Adding **capacitor** to existing project gives error.

# npx cap doctor

Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/core 1.5.0

  @capacitor/cli 1.5.0

  @capacitor/ios 1.5.0

  @capacitor/android 1.5.0

# npx cap add android

i Installing android dependencies – Skipping: already installed
√ Adding native android project in: E:\Projects\ionic\others\yIpro\android in 155.63ms
√ Syncing Gradle in 504.10μp
√ add in 165.75ms
√ Copying web assets from www to android\app\src\main\assets\public in 326.42ms
√ Copying native bridge in 1.09ms
√ Copying capacitor.config.json in 620.90μp
× copy: ENOENT: no such file or directory, open 'E:\Projects\ionic\others\yIpro\android\capacitor-cordova-android-plugins\src\main\AndroidManifest.xml'
[error] { [Error: ENOENT: no such file or directory, open 'E:\Projects\ionic\others\yIpro\android\capacitor-cordova-android-plugins\src\main\AndroidManifest.xml']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'E:\\Projects\\ionic\\others\\yIpro\\android\\capacitor-cordova-android-plugins\\src\\main\\AndroidManifest.xml' }
√ Updating Android plugins in 3.64ms
  Found 0 Capacitor plugins for android:
√ update android in 12.04ms

Now you can run npx cap open android to launch Android Studio

# Environment

ionic : 6.1.0

Angular CLI: 9.0.1
Node: 10.15.3
OS: win32 x64

Angular: 9.0.0
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

**Comment by tlancina** [comment]
I just got this on a fresh install as well, will take a look when I get a chance

**Comment by tlancina** [comment]
Looks like it was fixed already in https://github.com/ionic-team/capacitor/pull/2400, should be out in the next release.

Also I don't believe it breaks anything, even though it looks a little scary.
