### ISSUE TITLE
feat: How to turn off native capacitor plugin logging

### ISSUE THREAD

**Issue by Reiss-Cashmore** [ionic-team/capacitor#2438]
# Feature Request

## Describe the Feature Request
My console gets filled with lots of logs coming from my capacitor plugin. It logs out 

<PluginName>.addListener
<PluginName>.subscribe

Calls from my plugin

I have tried both of the below in my `capacitor.config.json` from these links:
https://github.com/ionic-team/capacitor/pull/1640
https://github.com/ionic-team/capacitor/issues/1431

```
{
  "production": true,
  "useLog": false,
}
```

![Screenshot 2020-02-12 at 16 11 18](https://user-images.githubusercontent.com/17616211/74353799-55f72880-4db2-11ea-9b77-cd2ead7566a8.png)
![Screenshot 2020-02-12 at 16 12 00](https://user-images.githubusercontent.com/17616211/74353861-6d361600-4db2-11ea-9fbe-2dab06910973.png)

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
Config option for disabling all CAPLogs

## Describe Alternatives
A console flag ?

**Comment by jcesarmobile** [comment]
it's 
```
"ios": {
    "hideLogs": false
}
```

leaving open to document it

**Comment by j0nT** [comment]
Good work on CAPLog ... as well as optino to disable all it would be helpful on all platforms to be able to configure a logLevel (CRIT, WARN, INFO, etc)

**Comment by biesbjerg** [comment]
Noticed the docs are not updated: https://capacitor.ionicframework.com/docs/apis/console/

> Currently it's not possible to disable it, but that feature is coming.

**Comment by inorganik** [comment]
@j0nT We currently have an all-or-nothing situation - where if we silence plugin logs we also silence logs in our code (at least in the Xcode console). Is there a way to just disable a specific plugin's logs? I would like to disable logs for @capacitor/storage (super noisy) but I still need to see my logs.
