### ISSUE TITLE
bug: CORS when loading local files on iOS

### ISSUE THREAD

**Issue by lucasfernog** [ionic-team/capacitor#2439]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0

  @capacitor/android 1.4.0

  @capacitor/ios 1.5.0
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When I try fetching a local file transformed with `convertFileSrc`, it fails due to CORS on iOS, but works properly on Android, as reported on issue #2042 

## Expected Behavior

I can fetch my local file properly from my app.

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
I can't reproduce, can you provide a sample app with reproduction instructions?

**Comment by jcesarmobile** [comment]
closing as there was no response and I can't reproduce
