### ISSUE TITLE
bug: sendUserActionEvent() mView returned

### ISSUE THREAD

**Issue by qu1ckdry** [ionic-team/capacitor#2442]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
  @capacitor/cli 1.5.0
  @capacitor/core 1.5.0
  @capacitor/android 1.5.0
  @capacitor/ios 1.5.0

## Affected Platform(s)

- [-] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

On load I get a flash where the screen images disappears for a fraction of a second.  This happens on my S10 phone but not my Pixel C tablet (so maybe it’s a Samsung issue?).

When I attach the debugger to my S10 phone in Android Studio I get this error:
> E/ViewRootImpl: sendUserActionEvent() mView returned

## Expected Behavior

For the app to load without the images disappearing briefly.

## Sample Code or Sample Application Repo
I get the issue when using any of the default ionic templates.

## Reproduction Steps

Create a new ionic app using a default template. Debug on an S10 phone via Android Studio

## Other Technical Details

`npm --version` output:
6.13.7
`node --version` output:
v12.16.0
`pod --version` output (iOS issues only):

## Other Information

The only place I've seen this issue raised is [here](https://medium.com/@WeselyOng/a-nasty-webview-error-comes-along-with-senduseractionevent-error-82887cdb1627)
but I can't work out how to implement the logic into an ionic/capacitor app

**Comment by nghiepnq-dgh** [comment]
same problem :'(

**Comment by jcesarmobile** [comment]
I don't think the "flash" was caused by that message, most places say that the message can be ignored.
There have been a few "flash" related issues reported over time and they have been fixed, so try updating your app to capacitor 3, specially making sure all the androidX dependencies are using the latest versions as most flashes where caused by them.
