### ISSUE TITLE
bug: Capacitor not use cordova-plugin-ios-keychain?

### ISSUE THREAD

**Issue by CodeDreamfy** [ionic-team/capacitor#2446]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
@capacitor/cli 1.5.0
@capacitor/core 1.5.0
@capacitor/ios 1.5.0
@capacitor/android 1.5.0

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

**Ionic version:**
ionic/react : ^4.11.0

## Current Behavior

When I added Keychain according to the official instructions, I found that it was not found in the plugins

## Expected Behavior

Expect to be able to register successfully and use Keychain,
```js
Keychain.get(key);
Keychain.set(key, value);
```

## Reproduction Steps

I used the following commands to install:
```shell
npm install -s @ ionic-native/keychain

npm install cordova-plugin-ios-keychain

npx cap sync

#  use: npx cap ls
Found 0 Capacitor plugins for ios:
  Found 1 Cordova plugins for ios:
   cordova-plugin-ios-keychain（3.0.1）
```

After installation
On the page

```js
import {Plugins} from '@ capacitor/core';
const {Keychain} = Plugins;
```

But print  `Keychain` to be undefied,

**Then I changed the way to introduce it, but I don't know how to instantiate it and call his api method**
 
```js
import { Keychain } from '@ionic-native/keychain/ngx';
```

## Other Technical Details

`npm --version` output: 6.7.0

`node --version` output: v11.14.0

`pod --version` output (iOS issues only): 1.8.3

**Comment by jcesarmobile** [comment]
Only Capacitor plugins get added to Plugins object, for Cordova plugins, just use them are the plugin docs explain.

https://ionicframework.com/docs/native/keychain
