### ISSUE TITLE
Unable to load native-bridge.js

### ISSUE THREAD

**Issue by vincent-herlemont** [ionic-team/capacitor#245]
This troubleshooting is report [here](https://github.com/ionic-team/capacitor/blob/1.0.0-alpha.6/site/docs-md/android/troubleshooting.md). 
But when I run the fixing command ```npx cap copy android``` at origin of the example project. I have the following issues.
```Stage not set, please call something such as `cap production deploy`, where production is a stage you have defined.```

capacitor : 1.0.0-alpha.6

**Comment by vincent-herlemont** [comment]
Found it. You can have a conflict of command if you use [capistrano](http://capistranorb.com/) in the same environment.

**Comment by mlynch** [comment]
Did you have `cap` as an npm script pointing to `capistrano`? If so, is that common?
