### ISSUE TITLE
Incompatible Cordova plugin for ios: com-badrit-base64

### ISSUE THREAD

**Issue by nboussarsaracn** [ionic-team/capacitor#2453]
Hi,

I am trying to use the Cordova plugin `com-badrit-base64` in Ionic 4/Capacitor. Unfortunately, the plugin is not compatible with Capacitor. Could you please check? Thanks.

Best regards,
Nizar Boussarsar

**Comment by jcesarmobile** [comment]
Can you provide a sample app using it?
Why is it not compatible?

**Comment by jcesarmobile** [comment]
I can't reproduce and there was no answer, closing.

What the plugin does is to put the url into a canvas to do the base64 conversion, so you have to use an url that the webview understand (meaning, you have to use `Capacitor.convertFileSrc()`)
