### ISSUE TITLE
hide scrollview for android

### ISSUE THREAD

**Issue by matamune94** [ionic-team/capacitor#2456]
I search google much time but I could not find solution for capacitor. have idea ? like flutter,  default is hide all scrollbar,

**Comment by jcesarmobile** [comment]
can you provide a sample app with the scrollbar you want to hide?

**Comment by matamune94** [comment]
I use quasar to build by capacitor, just i want hide it.

**Comment by jcesarmobile** [comment]
can you provide a sample quasar app where the scrollbar is visible?

**Comment by jcesarmobile** [comment]
closing since it's unclear what the problem is and the reporter didn't provide a sample app
