### ISSUE TITLE
feat: Pluggable Notification solutions

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2469]
I am trying to integrate One Signal with Capacitor which is a far superior solution for handling push notifications within hybrid apps as oposed to Firebase, APN i.e multiple sources etc as everything is handled under the hood by one free easy to use reliable service.

Im coming up against a lot of issues thus far, I can integrate the OneSignal Swift code for receiving the notification however I cannot make use of capacitors event listeners for processing the push notifications that are received I had logged the following issue but was suggested to open an issue with one signal (which I did) however I would argue that this is something which should be achievable within capacitor, 

A service agnostic push notifications delegate would be more than ideal and expected or at least some instruction on how to override/hook into capacitors so that we can create the one signal push notification extension service and then hook it into capacitors event listeners - I am no expert on Swift nor Java but I have done a review of the code and I do believe this is achievable in such a manner to provide instructions for "hooking" into the listeners 

https://github.com/ionic-team/capacitor/issues/2441#issuecomment-588259366
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/618

**Comment by jcesarmobile** [comment]
Capacitor has a delegate but allows to use your own delegate (or service delegate), but then it's your responsibility (or the service) to forward the data to Capacitor if you want to use Capacitor's events.
Sadly there can't be 2 delegates.

**Comment by REPTILEHAUS** [comment]
Is there any official docs on how one would forward the data, I will be looking into it again later but Im basically doing a lot of source code review trying to figure out how your PN events work
