### ISSUE TITLE
feat: video support for Camera plugin

### ISSUE THREAD

**Issue by diachedelic** [ionic-team/capacitor#2470]
# Feature Request

## Describe the Feature Request
I have used [`Camera` plugin](https://capacitor.ionicframework.com/docs/apis/camera) to get photos from the user's media gallery (on Android), and it worked very well - however, I would also like for users to be able to import & capture videos.

## Platform Support Requested
- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
```javascript
Camera.getMedia({
  mediaTypes: [CameraMediaType.Photo, CameraMediaType.Video],
  ...
})
```

When `CameraMediaType.Video` and `CameraSource.Photos` (or should it be `CameraSource.Library`?) is specified, list videos in the gallery feed alongside photos (like they appear when you use the Samsung Gallery app or similar).

## Describe Alternatives
Currently I am using `<input capture>` (see [spec](https://w3c.github.io/html-media-capture/#the-capture-attribute)) but this is painfully inefficient as the media's binary data must cross the bridge as Base64 (which can take tens of seconds on slower devices).

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

**Comment by diachedelic** [comment]
Does the proposed API seem sane? We were thinking of developing this and submitting a PR.

**Comment by BorntraegerMarc** [comment]
I'd vote for an additional option `CameraMediaType.PhotoAndVideo`

The camera can both take pics + record video. Why not let the user choose in the camera app what to do? Messaging apps like WhatsApp, etc. do this...
