### ISSUE TITLE
Testing Camera plugin in Android Studio Emulator (win10) fails

### ISSUE THREAD

**Issue by Tommertom** [ionic-team/capacitor#249]
Hi

trying to run Camera plugin on the Android Emulator (win10) but it does not run (Camera preview does not show). The camera plugin does kick off using the Camera app on the emulator. And the app does work on a physical device (Samsung Tab A 10,1)

Relevant code used:
https://github.com/Tommertom/capitest/blob/master/src/pages/home/home.ts

Tom

**Comment by mlynch** [comment]
Thanks, I don't think this is a Capacitor issue, could just be your emulator or the emulation of the Camera on Android.
