### ISSUE TITLE
feat: Get linuxAndroidStudioPath out of capacitor.config.json

### ISSUE THREAD

**Issue by OoDeLally** [ionic-team/capacitor#2493]
# Feature Request

## Describe the Feature Request

The location of Android Studio is specific to a particular machine, not to a project. Every collaborator may use a different Android Studio path.
Therefore `linuxAndroidStudioPath` should not be committed into the repo.

## Describe Preferred Solution
Machine-dependent settings should be in an environment variable, or in a gitignored file.

**Comment by jcesarmobile** [comment]
We have an issue for automatic detection https://github.com/ionic-team/capacitor/issues/560
If it's possible and somebody implements it, then there is no need to use `linuxAndroidStudioPath `

**Comment by OoDeLally** [comment]
Indeed, automatic detection is a hard thing to do, given the many setups to cover.
That is why an environment variable such as `$CAPACITOR_ANDROID_STUDIO_PATH`, or a gitignored file `.capacitor-local-config.json` solve the problem. It is easy to implement, and would cover all use cases.

**Comment by mirkonasato** [comment]
I agree with @OoDeLally, the Android Studio location is not a project-level settings, it's a user-specific one.

Capacitor could simply try launching `studio.sh` by default on Linux, and assume it's in the `PATH`. Users can set their `PATH` as desired in their `.profile` or similar.
