### ISSUE TITLE
bug: Background Tasks on iOS not working :(

### ISSUE THREAD

**Issue by SSuarezBrooktec** [ionic-team/capacitor#2494]
# Bug Report

## Capacitor Version
    "@capacitor/android": "^1.5.0",
    "@capacitor/core": "1.5.0",
    "@capacitor/ios": "^1.5.0",

`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/cli 1.5.0

  @capacitor/ios 1.5.0

  @capacitor/android 1.5.0

  @capacitor/core 1.5.0

[success] Android looking great! 👌
  Found 8 Capacitor plugins for ios:
    capacitor-fcm (1.0.0)
    capacitor-secure-storage-plugin (0.3.1)
    cordova-plugin-advanced-http (2.4.1)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-fingerprint-aio (3.0.1)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-webview-checker (1.0.1)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [ X] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
When i upload app to Testflight and put in background, background services not work

## Sample Code or Sample Application Repo
We are using Background Tasks -> https://capacitor.ionicframework.com/docs/apis/background-task/

## Other Technical Details

`npm --version` output: 6.13.7

`node --version` output: v13.0.1

`pod --version` output (iOS issues only): 1.8.4

## Other Information

We add to this config to info.plist on IOS proyect.

```
	<key>BGTaskSchedulerPermittedIdentifiers</key>
	<array>
		<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	</array>
```

Has anyone else had this issue? I think it must be a configuration problem :(

**Comment by jcesarmobile** [comment]
See the [docs](https://capacitor.ionicframework.com/docs/apis/background-task)

> The Background Task API makes it easy to run background tasks. Currently, this plugin supports running a task when the app is backgrounded, and soon will support periodic background fetch operations.

The "running a task when the app is backgrounded" means you have some extra time to finish a task, it's up to 3-10 minutes (depends on the iOS version and device), but not a background task that will continue running forever, that's not really possible on iOS.

**Comment by SSuarezBrooktec** [comment]
This app have maximum 120 seconds in background

**Comment by SSuarezBrooktec** [comment]
i see this error on ios console:

2020-02-26 21:28:43.430571+0100 APP [8176:1553289] [ProcessSuspension] Background task expired while holding WebKit ProcessAssertion (isMainThread? 1).
