### ISSUE TITLE
appboy-cordova-sdk - Push Notification Issue

### ISSUE THREAD

**Issue by asangadev** [ionic-team/capacitor#2499]
Hi there,

I'm having an issue with appboy-cordova-sdk plugin. You can find all the info here: https://github.com/Appboy/appboy-cordova-sdk/issues/49

Could you please have a look?

**Comment by asangadev** [comment]
### Found the solution!

For anyone who is planning to use AppBoy Cordova plugin with a capacitor project, follow below steps.

**1. in your capacitor.config.json file add below** 

```
{
  "appId": "com.yourapp.app",
  "appName": "Sample App",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "www",
  "plugins": {
    "PushNotifications": {
      "presentationOptions": ["badge", "sound", "alert"]
    }
  },
  "cordova": {
    "preferences": {
      "com.appboy.api_key": "**CHANGE-THIS:**XXXXX-XXXXXX-XXXXXX-XXXXXX",
      "com.appboy.ios_api_endpoint": "**CHANGE-THIS:**YOUR-END-POINT(see below link)",
      "com.appboy.ios_disable_automatic_push_registration": "YES"
    }
  }
}
```

Available endpoints (com.appboy.ios_api_endpoint): https://www.braze.com/docs/api/basics/#endpoints

**2. In your app JS do below to trigger the push permission popup**

```
import {Plugins} from '@capacitor/core'
const { PushNotifications } = Plugins;

setTimeout(function(){
  //register user
  AppboyPlugin.changeUser("ABC001")
  
  PushNotifications.register();
  
  PushNotifications.addListener('registration',
        (PushNotificationToken) => {
          alert('Push registration success, token: ' + PushNotificationToken.value);
      );
}, 4000);
```

**3. Modify you AppDelegate.swift in Xcode (I did this manually: still need to find a better way to implement this with CLI)**

add import Appboy_iOS_SDK here: https://github.com/asangadev/temp-app/blob/master/ios/App/App/AppDelegate.swift#L3

add Appboy.sharedInstance()?.registerDeviceToken(deviceToken) here: https://github.com/asangadev/temp-app/blob/master/ios/App/App/AppDelegate.swift#L66

This is it guys!

**Comment by asangadev** [comment]
### Found the solution!

For anyone who is planning to use AppBoy Cordova plugin with a capacitor project, follow below steps.

**1. in your capacitor.config.json file add below** 

```
{
  "appId": "com.yourapp.app",
  "appName": "Sample App",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "www",
  "plugins": {
    "PushNotifications": {
      "presentationOptions": ["badge", "sound", "alert"]
    }
  },
  "cordova": {
    "preferences": {
      "com.appboy.api_key": "**CHANGE-THIS:**XXXXX-XXXXXX-XXXXXX-XXXXXX",
      "com.appboy.ios_api_endpoint": "**CHANGE-THIS:**YOUR-END-POINT(see below link)",
      "com.appboy.ios_disable_automatic_push_registration": "YES"
    }
  }
}
```

Available endpoints (com.appboy.ios_api_endpoint): https://www.braze.com/docs/api/basics/#endpoints

**2. In your app JS do below to trigger the push permission popup**

```
import {Plugins} from '@capacitor/core'
const { PushNotifications } = Plugins;

setTimeout(function(){
  //register user
  AppboyPlugin.changeUser("ABC001")
  
  PushNotifications.register();
  
  PushNotifications.addListener('registration',
        (PushNotificationToken) => {
          alert('Push registration success, token: ' + PushNotificationToken.value);
      );
}, 4000);
```

**3. Modify you AppDelegate.swift in Xcode (I did this manually: still need to find a better way to implement this with CLI)**

add import Appboy_iOS_SDK here: https://github.com/asangadev/temp-app/blob/master/ios/App/App/AppDelegate.swift#L3

add Appboy.sharedInstance()?.registerDeviceToken(deviceToken) here: https://github.com/asangadev/temp-app/blob/master/ios/App/App/AppDelegate.swift#L66

This is it guys!

**Comment by dipankarmedhi91** [comment]
@asangadev Trying to integrate braze appboy cordova sdk into capacitor and facing number of issues
Do you have a sample repo for reference by any chance, that will really help

**Comment by asangadev** [comment]
Unfortunately no. I no longer use this service/plugin

**Comment by dipankarmedhi91** [comment]
@asangadev will it be possible for you to point me towards any direction/blog/people for guidance on how to integrate this [plugin](https://github.com/Appboy/appboy-cordova-sdk) with capacitor

**Comment by asangadev** [comment]
@dipankarmedhi91 You should check this thread: Appboy/appboy-cordova-sdk#49

You have to ask the Braze Cordova Support Team (https://github.com/radixdev) about this.

**Comment by Nico-code** [comment]
@dipankarmedhi91 did you find a solution? I'm trying to integrate that plugin into my capacitor app too and the solutions that I've read don't work

**Comment by dipankarmedhi91** [comment]
I have tried a few approaches and none of them seem to be working, the integration should be possible as per this post, but no luck as of yet! 😞

**Comment by dsteinel** [comment]
@dipankarmedhi91 @Nico-code I am facing exactly the same issue. The integration does not work with my capacitor (Ionic 6) setup. Where you able to solve it?
