### ISSUE TITLE
iOS custom native code

### ISSUE THREAD

**Issue by HardikDG** [ionic-team/capacitor#250]
As per the [documentation](https://capacitor.ionicframework.com/docs/ios/custom-code/) of Capacitor. We can add the custom swift code in the project as Private Native Code. How Capacitor(web view) and this native code will communicate? 

For example, I want to transfer from the Webview to native code/view or vice versa how this will work? 

I don't want to use the native method  in the JS/TS code I just want to have the native code and execute it

As far as I know, in Cordova/Ionic, the native code is of no use except use in the Plugin, Will it be the same here as well or we can write and execute the native code without the JS/TS implementation?

**Comment by mlynch** [comment]
If you need custom native code just add it directly to your project! We don’t blow away your Xcode or android studio projects, so feel free to add whatever you need. If you do need to call that code from a plugin just write a plugin that calls it.

Does that help?

**Comment by HardikDG** [comment]
Thanks for the quick reply. But my question is how that code will work. 

As per the current implementation when I run my code. It is starting the ionic app and opens the web view. So my question is how can It run my native code without communication of javascript or web view? 
If I write some native how it can be executed if it has no connection with the web view? 

If I am correct we can add a new controller to Storyboard or add new swift file code in the project so how it will work with web view code? 

If you have some sample code where the native code usage is shown except the plugin it will be great.

**Comment by HardikDG** [comment]
I have good knowledge of iOS development with Xcode and Objective-C/Swift. So if required you can provide details or customization in the Xcode/iOS development. It will be helpful.

**Comment by janpio** [comment]
As I understood it: 
a) Write native code e.g. in `AppDelegate.swift` as you normally would to attach to a "lifecycle event". 
b) If you want to trigger the native code you wrote from JS, use a (Capacitor or Cordova) plugin.

**Comment by HardikDG** [comment]
Okay. so we can write native code only in the AppDelegate.swift lifecycle method. We can't write any native code at any other place. 
If we want to write code at any other place like a separate file or like that we still need to write the plugin as before like we are doing in the Ionic. 

I was hoping we can write some custom native code and mix it with the web view code. Something like what React-native is providing.

**Comment by jcesarmobile** [comment]
No, you can write code on any class you create, the app only brings AppDelegate.swift, but you can create new view controllers and write your code there, but for the JS<--> native communication is still recommended to use plugins.

**Comment by HardikDG** [comment]
Okay. So I can write any custom native code in swift/Storyboard controllers. For the transfer from web view to native I need to use the plugin, something like a single method which will call the native code and transfer the control to native code. 
I will try with that update if I face any issue with it. 

So the major improvement point in Capacitor is before we need to write all the native code in the plugin file itself. Now we can write it anywhere and call it from the plugin method.

**Comment by jcesarmobile** [comment]
BTW, from native to JS you can always call evaluateJavaScript on the webview, but from js to native we only support plugins so far.

**Comment by HardikDG** [comment]
Another question with this, Which I am facing with the current Ionic project, For one feature I have added a new target in the iOS project. so I need to manually add this after I add iOS platform. 

 So in this case also If I add native iOS code to the project I need to manually add it to every developer's iOS project. As `cap sync/cap copy` or `npx cap add ios` will not add this code in the iOS project as it is not aware of this.

**Comment by jcesarmobile** [comment]
The idea is that you commit the whole ios and android folders, they are not build artifacts as in Cordova, as we allow changes and we won't overwrite anything, you have to commit them.

**Comment by HardikDG** [comment]
Okay. Thanks for all your quick help looks like Capacitor will more interesting and useful to use with Native development. 

For the Native to JS, Yes I can already see some use of 'evaluateJavaScript' in the CAPBridge.swift.
