### ISSUE TITLE
feat: How to access Capacitor bridge from within iOS App Delegate

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2502]
I am integrating OneSignal native code into a capacitor app. 

I can receive notifications and process them on the swift side of things, I now want to pass the notification data over to Capacitor, my receive notification logic all resides in my AppDelegate file, is there a way to launch a capacitor event from app delegate using bridge ?

Or have you any tips for passing this data over to a plugin class from AppDelegate. All I need is to pass over some information to an event handler so that the app can process what route to take.

Trying some things Ive found in other issues like this but no luck

```
    // Do your custom handling here
    let capVC = self.window?.rootViewController as? CAPPlugin
    capVC?.bridge.triggerDocumentJSEvent(eventName: "myCustomEvent", data: "my custom data")
```

This page mentions app delegate and custom event handlers but no info 

https://capacitor.ionicframework.com/docs/ios/custom-code/

and here but it only relates to within a plugin
https://capacitor.ionicframework.com/docs/ios/custom-code/

Is there any information on how to pass to one of capacitors plugin methods from AppDelegate

` CAPBridge.triggerDocumentJSEvent(eventName: "myCustomEvent")`

**Comment by jcesarmobile** [comment]
Event docs are here
https://capacitor.ionicframework.com/docs/plugins/ios#events

But please, don’t create issues to ask questions, you can check the source code to see how capacitor does it or ask on the forums or slack for help, but GitHub issues is not the place.

**Comment by REPTILEHAUS** [comment]
I have read those docs but the events do not fire from the app, Im not sure if the documentation is incorrect as it has been before a couple of times, this is what I am using but the app never receives an event 

AppDelegate.swift
```
  func applicationDidBecomeActive(_ application: UIApplication) {
    let nc = NotificationCenter.default
    nc.post(name: Notification.Name("TestingEvents"), object: nil)
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was
  }
```



MyPlugin.swift
```
    public override func load() {
        let nc = NotificationCenter.default
            nc.addObserver(self, selector: #selector(handleSignal), name: Notification.Name("TestingEvents"), object: nil)
    }

    @objc func handleSignal() {
        self.bridge.triggerWindowJSEvent(eventName: "myCustomEvent")
        self.notifyListeners("myPluginEvent", data: [:])
    }
```  

and my app.component.ts

```
      window.addEventListener('myCustomEvent', () => {
        console.log("ATTEMPTILE PUSH")
        alert("myCustomEvent 2 ")
      });            
      Plugins.myPlugin.addListener("myPluginEvent", (info: any) => {
        console.log("myPluginEvent was fired");
        alert("myPluginEvent 2 ")
      });
```
