### ISSUE TITLE
feat: Processing an event that happens before Capacitor is initialised 

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2503]
Ive read through the capacitor docs related to processing and firing events. I have an edge case and I am wondering is there any way to pass an event using notification center post to capacitor if it happens within `didFinishLaunchingWithOptions` in  `AppDelegate.swift` I am basically trying to build a Capacitor plugin for OneSignal notifications, my code works so long as the app is in the forground, it does not work when a notification is received and clicked on, I figure it is because AppDelegate loads before Capacitor and my plugin so the `NotificationCenter.default.post` gets posted but is lost as the plugin is not ready. 

Does capacitor have any kind of functionality that might be able to help with catching this request or at least storing it until Capacitor is ready and then processing the data ? 

I have read your related docs extensively and I have been tinkering with all kinds of solutions for the past few days. So far the idea of using `NotificationCenter.default.post` to pass the notification onto my plugin seems to make the most sense, and it works - but capacitor is not ready at the time of a notification click.

AppDelegate.swift
```
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    
    
        let notificationOpenedBlock: OSHandleNotificationActionBlock = { result in
           // This block gets called when the user reacts to a notification received
           let payload: OSNotificationPayload = result!.notification.payload

           var fullMessage = payload.body

            let nc = NotificationCenter.default
                nc.post(name: Notification.Name("TestingEvents"), object: nil)
            
           if payload.additionalData != nil {
              if payload.title != nil {
                 let messageTitle = payload.title
                    print("Message Title = \(messageTitle!)")
              }

              let additionalData = payload.additionalData
              if additionalData?["actionSelected"] != nil {
                 fullMessage = fullMessage! + "\nPressed ButtonID: \(additionalData!["actionSelected"])"
              }
           }
        }
        

    return true
  }
```

MyPlugin.swift
```
    public override func load() {
        let nc = NotificationCenter.default
            nc.addObserver(self, selector: #selector(handleSignal), name: Notification.Name("TestingEvents"), object: nil)
    }

    @objc func handleSignal() {
        self.bridge.triggerWindowJSEvent(eventName: "myCustomEvent")
        self.notifyListeners("myPluginEvent", data: [:])
    }
```  

and my app.component.ts

```
      window.addEventListener('myCustomEvent', () => {
        alert("myCustomEvent ")
      });            
      Plugins.myPlugin.addListener("myPluginEvent", () => {
        alert("myPluginEvent ")
      });
```

**Comment by jcesarmobile** [comment]
Again, please, don’t use github issues for asking questions.

Listeners can retain the event until it’s consumed, check the plugins source code, some of them do that.

**Comment by REPTILEHAUS** [comment]
@jcesarmobile How can the listener retain it if Capacitor has not even loaded yet ?

Can you please give an example ? I would not be asking here if I could find these examples and I have been going over the code.
