### ISSUE TITLE
feat: Don't keep platforms in source control, generate them from a file

### ISSUE THREAD

**Issue by Finesse** [ionic-team/capacitor#2505]
# Feature Request

## Describe the Feature Request

At the moment Capacitor requires the native platforms (iOS, Android, etc.) code to be included into source control of the project. We find it inconvenient because:

- Editing native code requires the native IDEs that aren't always available (e.g. Xcode can't be used on Windows). Editing the code manually is not an option because some code is designed to be edited by IDE and therefore isn't human-friendly, and the other isn't JS/TS.
- Sometimes it's hard to find the desired option control in an IDE and the native code.
- Many meaningless (for us, web developers) files get to source control.
- Resolving a source control merge conflicts can be very hard due to the notes above.
- Installing the IDEs itself just to change configuration is cumbersome because building native applications for all platforms is required not by all team developers.
- Version change requires a [manual action](https://stackoverflow.com/a/59072775/1118709) for each platform.

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [x] Web

## Describe Preferred Solution

A Cordova-like approach. There is a single configuration file that keeps a minimum data required to make a directories with platforms code. The file is added to source control. For example:

```js
{
  "name": "MyApp",
  "webDir": "build",
  "webBuildCommand": "npm run build",
  "platforms": {
    // Platform specific configuration
    "ios": {
      "icons": {/* ... */}
    },
    "android": {} // Default settings
  }
}
```

And there is a CLI command that makes/updates a platform directory from this file. The algorithms of converting the parameters from the file to the native code can be provided via plugins, for example, a plugin that handles the `icons` parameter.

If the current approach is chosen for a reason and a Cordova-like approach won't be implemented, than **could you please clarify why it was chosen and what benefits over the Cordova approach does it give us**?

**Comment by jcesarmobile** [comment]
It's not mandatory to put the platforms into source control, just recommended, but Capacitor's CLI will never modify users projects, so if you need changes in the native projects you'll have to create node scripts yourself.

**Comment by Finesse** [comment]
@jcesarmobile Platforms contain important files like icons and splashes so I can't exclude them from version control. I can make a script that calls `capacitor add ...` and copies icons to the projects but I expect an out-of-the-box experience from tools like Capacitor and Ionic.

Could you please clarify why the current approach was chosen and what benefits over the Cordova approach does it give to developers?

**Comment by jcesarmobile** [comment]
We did it this way because Ionic users were constantly complaining about Cordova plugins messing with their native projects, so we decided to never edit the user project.

If you want Cordova's behavior, just use Cordova or create the scripts you need.

**Comment by Finesse** [comment]
Thank you for the response

**Comment by dotNetkow** [comment]
Read more about Caps philosophy here:
https://capacitor.ionicframework.com/docs/cordova
