### ISSUE TITLE
bug: Problem to add platform on Capacitor

### ISSUE THREAD

**Issue by mauricioduqueorozco** [ionic-team/capacitor#2509]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.5.0

  @capacitor/core 1.5.0

  @capacitor/android 1.5.0

## Affected Platform(s)

- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Current Behavior
Problem to locate "www" folder, I tried 'ionic build', after that 'npx cap add android' but it rejects with:
looking www folder, but after ionic build, this (www) folder never appear.

## Expected Behavior

Should present android folder
## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Are you using angular or react?
Can you provide a sample project?

**Comment by jcesarmobile** [comment]
Closing since there was no response.

You are probably using react, which uses `build` as folder instead of `www`, but you changed the `webDir` to `www` in `capacitor.config.json`. So just change it again to `build`
