### ISSUE TITLE
Capacitor.framework: errSecInternalComponent

### ISSUE THREAD

**Issue by guntercn** [ionic-team/capacitor#2515]
# Bug Report

## Capacitor Version

Latest Dependencies:
@capacitor/cli: 1.5.0
@capacitor/core: 1.5.0
@capacitor/android: 1.5.0
@capacitor/ios: 1.5.0

Installed Dependencies:
@capacitor/cli: not installed
@capacitor/core: 1.5.0
@capacitor/android: 1.5.0
@capacitor/ios: 1.5.0

## Affected Platform(s)
- [ ] Android
- [X ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
There is an error compiling or the action of the xcode called "Product->Archive"

## Expected Behavior
the correct compilation

## Sample Code or Sample Application Repo
 Showing Recent Messages
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/USUARIO/Library/Developer/Xcode/DerivedData/App-cdvbskvksfveosfzcnrumhkoxmbn/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/APPNAME.build/Release-iphoneos/APPNAME.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh (in target 'APPNAME' from project 'APPNAME')
    cd /Users/USUARIO/Desktop/APPNAME/ios/App
    /bin/sh -c /Users/USUARIO/Library/Developer/Xcode/DerivedData/App-cdvbskvksfveosfzcnrumhkoxmbn/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/APPNAME.build/Release-iphoneos/APPNAME.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh

mkdir -p /Users/USUARIO/Library/Developer/Xcode/DerivedData/App-cdvbskvksfveosfzcnrumhkoxmbn/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/APPNAME.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/USUARIO/Library/Developer/Xcode/DerivedData/App-cdvbskvksfveosfzcnrumhkoxmbn/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Capacitor.framework" "/Users/USUARIO/Library/Developer/Xcode/DerivedData/App-cdvbskvksfveosfzcnrumhkoxmbn/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/APPNAME.app/Frameworks"
building file list ... done
Capacitor.framework/
Capacitor.framework/Capacitor
Capacitor.framework/Info.plist

sent 4980515 bytes  received 70 bytes  9961170.00 bytes/sec
total size is 4979677  speedup is 1.00
Code Signing /Users/USUARIO/Library/Developer/Xcode/DerivedData/App-cdvbskvksfveosfzcnrumhkoxmbn/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/APPNAME.app/Frameworks/Capacitor.framework with Identity Apple Development: USEREMAL@EMAIL.com (DBWV4AR346)
/usr/bin/codesign --force --sign 22C16FEB7008062BB27AA9AFC57C40963C5B7CA4  --preserve-metadata=identifier,entitlements '/Users/USUARIO/Library/Developer/Xcode/DerivedData/App-cdvbskvksfveosfzcnrumhkoxmbn/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/APPNAME.app/Frameworks/Capacitor.framework'
/Users/USUARIO/Library/Developer/Xcode/DerivedData/App-cdvbskvksfveosfzcnrumhkoxmbn/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/APPNAME.app/Frameworks/

**Capacitor.framework: errSecInternalComponent
Command PhaseScriptExecution failed with a nonzero exit code**

## Reproduction Steps

once I have configured the application in apple developer, certificates and the basic xcode settings..., I try to compile the application to upload it, but the error shows up 
Capacitor.framework: errSecInternalComponent
Command PhaseScript Execution failed with a nonzero exit code

## Other Technical Details
`npm --version` output:  6.13.4
`node --version` output: v12.16.1
`pod --version` output (iOS issues only): 1.8.4

**Comment by jcesarmobile** [comment]
does this help?
https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen

**Comment by guntercn** [comment]
the solution worked.
thanks
