### ISSUE TITLE
bug: capacitor is preventing the Airship SDK from receiving any push events

### ISSUE THREAD

**Issue by florianchevallier** [ionic-team/capacitor#2518]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊
Latest Dependencies:
  @capacitor/cli: 1.5.0
  @capacitor/core: 1.5.0
  @capacitor/android: 1.5.0
  @capacitor/ios: 1.5.0

Installed Dependencies:
  @capacitor/cli 1.5.0
  @capacitor/core 1.5.0
  @capacitor/android 1.5.0
  @capacitor/ios 1.5.0

[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    urbanairship-cordova (10.1.0)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Following this issue : #2511 I'm not able to get background notifications with the urban-airship plugin on Android

## Expected Behavior
Well I would be pleased if this would work on android as well

## Sample Code or Sample Application Repo

You can clone, configure and launch this app : 

https://github.com/florianchevallier/test-ionic-app-notif

## Reproduction Steps

- You'll need an [UrbanAirship account](https://go.airship.com/accounts/register/plan/starter/), to [setup firebase for the project](https://capacitor.ionicframework.com/docs/guides/push-notifications-firebase/#android), [create an app](https://go.airship.com/apps/new/) in Airship, [setup the app for android](https://docs.airship.com/platform/android/getting-started/#fcm-setup) and add the Airship credentials in `Home.tsx`.
- Open Postman, and make a POST request to : https://go.urbanairship.com/api/push (with Basic Auth) with this payload : 

```json
{
    "audience": "all",
    "notification": {
        "alert": "Hey Android and iOS!!"
    },
    "device_types": [
        "android",
        "ios"
    ]
}
```

## Other Technical Details

`npm --version` output: 6.12.1

`node --version` output: v12.13.1

`pod --version` output (iOS issues only):

## Other Information
You'll find the investigation on what lead to this bug here : https://github.com/urbanairship/urbanairship-cordova/issues/337

**Comment by jcesarmobile** [comment]
As explained in the linked issue, you are using capacitor listener instead of theirs, and they explained how to use theirs, so do what they told you.
