### ISSUE TITLE
create: "Next steps" slightly wrong when creating project in subdirectory

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#252]
```
C:\Projects
λ npx @capacitor/cli create Capacitor/createTest createTest de.janpiotrowski.capacitor.createtest
npx: installed 212 in 32.944s

...

Next steps:
cd ./createTest
Get to work by following the Capacitor Development Workflow: https://capacitor.ionicframework.com/docs/basics/workflow
```

The `cd ./createTest` is missing the `Capacitor` directory where it created `createTest`.

**Comment by janpio** [comment]
This could be solved by doing the following:

Replace `basename(config.app.rootDir)` here with `dir`:
https://github.com/ionic-team/capacitor/blob/f2cc94377fdc8cdf51d3ecd5010d515616b8ea45/cli/src/tasks/create.ts#L165-L170

by giving this method a second param `dir` here:
https://github.com/ionic-team/capacitor/blob/f2cc94377fdc8cdf51d3ecd5010d515616b8ea45/cli/src/tasks/create.ts#L75

Don't know about the side effects yet - don't know how to setup the CLI locally to test this :/

**Comment by mlynch** [comment]
Fixed
