### ISSUE TITLE
feat: Improve Browser API

### ISSUE THREAD

**Issue by MPdevelopers** [ionic-team/capacitor#2522]
# Feature Request

## Describe the Feature Request
We are missing abilities to:
1. get current location,
2. listen to location change event,
3. close browser on Android via close()

## Platform Support Requested
- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Additional Context
https://capacitor.ionicframework.com/docs/apis/browser/

**Comment by dotNetkow** [comment]
Thanks for the issue. There's some challenges here - for example, the Browser plugin uses Chrome Custom Tabs, which don't provide a way of programmatically closing them.

What are the use cases you're trying to tackle using the Browser API?

**Comment by MPdevelopers** [comment]
We are using it for opening payment gateway. Flow is:
1) Open URL,
2) wait for user's payment and redirect back to some _redirectURL_,
3) wait for location change (to _redirectURL_),
4) close browser.

**Comment by jcesarmobile** [comment]
This is not possible with Android Custom tabs nor with SFSafariViewController, which Browser plugin uses, so can't be implemented.

You can use Cordova's InAppBrowser plugin instead
