### ISSUE TITLE
"Plugin does not have web implementation." could mention which plugin

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#253]
```
capacitor.js:2
 Uncaught (in promise) 
Plugin does not have web implementation.
```

could mention which plugin triggered this console log.

**Comment by IT-MikeS** [comment]
Realistically this can be handled by the user very simply.
```
    const { Keyboard } = Plugins;
    Keyboard.show().then(() => {
      console.log('Keyboard shown');
    }).catch((e) => {
      console.error('Keyboard plugin:', e);
    });
```

that will output `Keyboard plugin: Plugin does not have web implementation.` when running in npx cap serve

**Comment by janpio** [comment]
Why should the user have to do any extra implementation when the library can just handle this and help the user to actually find out which of the several plugins he just added is generating this output?

(In my case this is the default state after creating a project - that is using the Splashscreen APIs)

**Comment by IT-MikeS** [comment]
I can look into doing this but the reason is not so simple at the moment is how it uses a Noop Plugin for plugins that dont have an impl. for web/android/ios

**Comment by jcesarmobile** [comment]
done in #276
