### ISSUE TITLE
Documentation Site: Bad Link

### ISSUE THREAD

**Issue by alexsasharegan** [ionic-team/capacitor#2535]
# Bug Report

Visiting the [Push Notification doc page](https://capacitor.ionicframework.com/docs/apis/push-notifications), there is a cross link to the Local Notifications page. Currently, the link is broken. The cause of the break is both a bad path and a case sensitive issue. Note the difference:

- **Linked Page:** `https://capacitor.ionicframework.com/docs/local-notifications`
- **Actual Page:** `https://capacitor.ionicframework.com/docs/apis/local-Notifications/`

I see that the markdown docs use the lower-cased directory names, but I imagine something in the deploy chain is case-insensitive. Also, it's a bit confusing how the directory of md pages resolves the built html and their paths. The directory walk up in the source file appears to be unnecessary: `site/docs-md/apis/push-notifications/index.md`.

**Comment by jcesarmobile** [comment]
I've fixed the `local-notifications` vs `local-Notifications` thing.

The other problem is a known issue on our relative urls. 

If you go to Push Notifications page, it loads `https://capacitor.ionicframework.com/docs/apis/push-notifications` url and the link is broken, but if while being there you refresh, it becomes `https://capacitor.ionicframework.com/docs/apis/push-notifications/` and then the link works.

We should probably make the plugin urls to always finish with `/`
