### ISSUE TITLE
Define browser for `cap serve`

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#254]
Current Firefox  doesn't seem to support custom elements:

```
TypeError: window.customElements is undefined
```

Would be neat if one could specify somehow that Chrome should be used to view the app on `cap serve`.

**Comment by SonnyCampbell** [comment]
Hey @janpio, I have submitted a [PR](https://github.com/ionic-team/stencil-dev-server/pull/25) to [stencil-dev-server](https://github.com/ionic-team/stencil-dev-server) to allow the browser of choice to be passed in with an `--app browser` argument.

When/If that gets merged it would allow us to specify that Chrome is the required browser to run `cap serve`.

**Comment by mlynch** [comment]
Going to close because we should just fix the starter project to optionally load a polyfill or just use stencil instead
