### ISSUE TITLE
feat: readPartOfFile for large files

### ISSUE THREAD

**Issue by digaus** [ionic-team/capacitor#2541]
# Feature Request

## Describe the Feature Request

Allow `readPartOfFile` for larger files.

Writing files with custom size is possible with using appendFile option. That way we can store a large blob by splitting it into parts. However reading the file all at once will result in a crash. Therefore on should be able to retrieve parts of the file so we can reconstruct the blob part by part.

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Describe Alternatives

Directly implement blob support and handle all the stuff internally. (Will lock into that. Maybe I can see if I can implement that myself if I find the time)

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

BTW, if you have a "web url" (the ones returned by `Capacitor.convertFileSrc`), you can easily get the `Blob` without using `Filesystem` plugin.

**Comment by digaus** [comment]
> Issues tagged with feature request are closed but tracked for reactions to gauge interest.
> 
> BTW, if you have a "web url" (the ones returned by `Capacitor.convertFileSrc`), you can easily get the `Blob` without using `Filesystem` plugin.

Thanks for the hint. Now I use `fetch` to retrieve the Blob from the filesystem :) now I am able to store and retrieve large blobs
