### ISSUE TITLE
bug: Geolocation - Network location provider at 'https://www.googleapis.com/' : No response received.

### ISSUE THREAD

**Issue by FabioZumbi12** [ionic-team/capacitor#2545]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/ios not installed

  @capacitor/cli 1.5.1

  @capacitor/core 1.5.1

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [x] Electron
- [ ] Web

## Current Behavior

On try to use Geolocation from capacitor with Electron + Qausar, i got this message: `Network location provider at 'https://www.googleapis.com/' : No response received.`

## Sample Code or Sample Application Repo

```
import { Geolocation } from '@capacitor/core'
function recuperaLocalizacao (base) {
  console.log('Current', Geolocation.getCurrentPosition())
}
```

## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.16.1

`pod --version` output (iOS issues only):

**Comment by josx** [comment]
I think it is a problem on the browser behind electron.

I have the same problem on Chromium Versión 80.0.3987.116

But it is working on the same notebook with:

- Chrome Versión 68.0.3440.75 (Build oficial) (64 bits)
- Chrome Versión 79.0.3945.88 (Build oficial) (64 bits)
- Firefox 68.5.0esr (64-bit)

**Comment by jcesarmobile** [comment]
electron is now a community platform, so you can report the problem in the new repo
https://github.com/capacitor-community/electron/issues

but looks like a chromium issue to me
