### ISSUE TITLE
bug: iOS splash logo resizes then goes to normal position

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2549]
# Bug Report
My apps splash screen does some kind of weird resize or scale when you open the app after some milliseconds scales to the expected size

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/core 1.5.0

  @capacitor/ios 1.5.0

  @capacitor/android 1.5.0


  Found 1 Capacitor plugin for ios:
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌
```

Capacitor config:
```
....
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 2000,
      "launchAutoHide": true,
      "backgroundColor": "#4a69bd",
      "androidSplashResourceName": "splash",
      "androidScaleType": "CENTER_CROP",
      "showSpinner": false
    }
  },
...
```

app.component.ts
```
        SplashScreen.show({
          showDuration: 2000,
          autoHide: true
        });   
```

## Affected Platform(s)
- [ ] Android
- [ X] iOS
- [ ] Electron
- [ ] Web

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by REPTILEHAUS** [comment]
I can in a day or 2 yeah

**Comment by jcesarmobile** [comment]
Did you close the issue?
It appears as closed, but there is no close message.
Feel free to reopen once you provide the sample app.

**Comment by rizzla22** [comment]
It seems that you have to delete the app entirely each time you regenerate the splash screen or you get this double up effect
