### ISSUE TITLE
Camera, Web: Modal is always opened at 0,0 even when page is scrolled

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#255]
I played around with the web fallback of `Capacitor.Plugins.Camera` a bit. 

This all works fine when the page being displayed is not high enough to be scrolled or is just displayed scrolled up to the top. But as soon as the page is scrolled down, only part of the modal is visiable as the modal is still displayed at 0,0.

![image](https://user-images.githubusercontent.com/183673/36950954-ab710464-1ffd-11e8-8896-d965d44fa68c.png)

**Comment by mlynch** [comment]
Thanks, closing as this is an Ionic issue and I've notified the team. Cheers

**Comment by janpio** [comment]
Ah, so this is actually part of the PWA elements thing that doesn't really exist 🙈 Makes sense of course, Cap only hands over to that for the UI.
