### ISSUE TITLE
Feature Request: Add light Electron Alternative Tauri

### ISSUE THREAD

**Issue by maxcodefaster** [ionic-team/capacitor#2574]
I recommend checking out Tauri. A new very light weight but powerful alternative to electron. It would be awesome to have a straight and easy app building process in capacitor with tauri. 

https://github.com/tauri-apps/tauri

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

But tauri doesn’t seem to have a powerful API unlike electron, so even if we add this, most plugins can’t be implemented.

**Comment by jcesarmobile** [comment]
capacitor now support community platforms, so anybody can create a tauri platform if they want 
take a look at the electron one
https://github.com/capacitor-community/electron

removing the label as we won't be developing a tauri platform ourselves, but anybody can create it and even put it in the https://github.com/capacitor-community/ org
