### ISSUE TITLE
feat: Custom push notifications icons on Android

### ISSUE THREAD

**Issue by vvche69** [ionic-team/capacitor#2580]
# Feature Request

Is it possible to implement custom push notification icons like in cordova plugin "cordova-plugin-firebasex" ?

## Platform Support Requested

- [x ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
Using cordova-plugin-firebasex, I can define additional sets of notification icons and  then specify the icon name in the android.notification section, for example:

{
  "name": "my_notification",
  "notification": {
    "body": "Notification body",
    "title": "Notification title"
  },
  "android": {
    "notification": {
      "icon": "my_icon",
    }
  },
  "data": {
    "notification_foreground": "true",
  }
}

Or it's possible to reference these icons in data messages, for example:

{
  "name": "my_data",
  "data" : {
    "notification_foreground": "true",
    "notification_body" : "Notification body",
    "notification_title": "Notification title",
    "notification_android_icon": "my_icon",
  }
}

It could be useful feature in Capacitor.

Thank you.

**Comment by jcesarmobile** [comment]
Capacitor push plugin doesn't handle showing the notifications, that's up to you, you can use local notifications plugin to show them, and local notifications plugin allows custom icons.
