### ISSUE TITLE
Entering Android Multi-Window mode restarts app

### ISSUE THREAD

**Issue by Proper-Job** [ionic-team/capacitor#2582]
## Capacitor Version
@capacitor/cli 1.5.0
@capacitor/core 1.5.1
@capacitor/ios 1.5.1
@capacitor/android 1.5.1

## Affected Platform(s)
- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Entering multi-window mode on Android restarts the app. The splash screen shows and the last place in the app (navigation) is lost.

## Expected Behavior
The splash screen is not shown and the app retains the current navigation state. 

## Sample Code or Sample Application Repo
Can be reproduced with starter template: ``ionic start multiWindowTest tabs --capacitor``

## Reproduction Steps
Create a starter template: 

``ionic start multiWindowTest tabs --capacitor``

Add capacitor Android project: 

``cap add android``

Open and launch Android Project with Android Studio.
Navigate to tab 3
Enter multi-window mode.
Watch the app restart and launch tab 1

## Other Technical Details
Tested on Android API Level 25 and 29

**Comment by jcesarmobile** [comment]
I've sent a PR that add the required changes to the app template, but you'll have to apply it to your own apps, the changes will only apply to new apps after it's released.

see https://github.com/ionic-team/capacitor/pull/2584
