### ISSUE TITLE
feat: Implement CDVScreenOrientationDelegate in CAPBridgeViewController

### ISSUE THREAD

**Issue by jsheetzati** [ionic-team/capacitor#2591]
# Feature Request

## Describe the Feature Request
Is it possible to implement the CDVScreenOrientationDelegate in CAPBridgeViewController? There are a couple Cordova plugins that rely on that delegate such as [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/ios/CDVInAppBrowserNavigationController.m#L66). 

Our application is landscape only. Because that delegate is not implemented in CAPBridgeViewController, we are unable to use cordova-plugin-inappbrowser. That method I linked is returning Portrait by default when there is not a CDVScreenOrientationDelegate available. This causes a runtime error because InApp Browser is returning Portrait, and we only have Landscape Right defined

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
CAPBridgeViewController implements the CDVScreenOrientationDelegate

## Describe Alternatives
Will need to remove all Cordova plugins that rely on the delegate

## Related Code
N/A

## Additional Context
N/A

**Comment by jcesarmobile** [comment]
this can't be done, since the delegate methods are called the same way that the UIViewController methods and Capacitor uses Swift.
If I add the delegate and add the required implementation for shouldAutorotate
```
public func shouldAutorotate() -> Bool {
   return false
}
```
I get 
> Method 'shouldAutorotate()' with Objective-C selector 'shouldAutorotate' conflicts with getter for 'shouldAutorotate' from superclass 'UIViewController' with the same Objective-C selector

**Comment by jsheetzati** [comment]
FYI for anyone else running into this issue. I fixed it by swizzling the two methods I needed to override.

```
import Foundation

extension CDVWKInAppBrowserViewController {
    @objc dynamic var _orientation_supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return UIInterfaceOrientationMask.landscapeRight
    }
    
    @objc dynamic var _orientation_shouldAutorotate: Bool {
        return false
    }
    
    static func swizzle() {
        if (self != CDVWKInAppBrowserViewController.self) {
            return
        }
        
        let originalAutorotate = class_getInstanceMethod(self, #selector(getter: shouldAutorotate))
        let swizzledAutorotate = class_getInstanceMethod(self, #selector(getter: _orientation_shouldAutorotate))
        method_exchangeImplementations(originalAutorotate!, swizzledAutorotate!)
        
        let originalSupportedOrientations = class_getInstanceMethod(self, #selector(getter: supportedInterfaceOrientations))
        let swizzledSupportedOrientations = class_getInstanceMethod(self, #selector(getter: _orientation_supportedInterfaceOrientations))
        method_exchangeImplementations(originalSupportedOrientations!, swizzledSupportedOrientations!)
    }
}
```

**Comment by jcesarmobile** [comment]
Next Capacitor release will implement CDVScreenOrientationDelegate https://github.com/ionic-team/capacitor/pull/5070
