### ISSUE TITLE
feat: Unregister Push Notifications(question)

### ISSUE THREAD

**Issue by MaratYuma** [ionic-team/capacitor#2596]
Related to #1777 
At first, Im very sorry if my question is not enough clever and should not be in issues.

Related issue was closed because, as I understand, was proposed to send requests to server for removing firebase registration id. But could be situation, when user don't have access to the internet and want, for example, log out from your app. In this case we can't remove firebase token from the app and user will receive notification, when he will connected to the internet, even if in app he is not logged in.

**Comment by andysousa** [comment]
you will likely have to build in some retry logic in your app to keep trying to unregister until you have connectivity.

I guess the good thing about this is that your user won't have internet so they won't be getting the push notifications anyways.

There really isn't much you can do about your scenario that you are asking about.  If the phone can't communicate with firebase you can't really do much.  The OS won't let you disable the notification channel as that is the right of the user to control.

**Comment by MaratYuma** [comment]
Maybe I don't completely understand what kind of "retry logic" should be. But I think, that it won't help, because if app is killed, main javascript(angular or other) part is not working. And firebase push notifications are receiving by device OS -> will be displayed. Will be nice to have functionality with offline unsubscribing from push notifications, so they won't appear, when internet connection become available.

For now, I think, that can do only one thing: restrict log out without internet connection.

**Comment by MaratYuma** [comment]
Closing, because no other comments.
