### ISSUE TITLE
Utilise help labels for issues

### ISSUE THREAD

**Issue by Ryan-Gordon** [ionic-team/capacitor#260]
A lot of us are excited for capacitor to be ready and would like to help speed things up by contributing. 
The problem with this is some issues require a big investment of time to get up to speed to solve an issue.

Simple issues and issues which don't require a great amount of time to complete should use either a good-first-issue label, or a help-wanted label or both to signal this.

**Comment by mlynch** [comment]
Great call, will try to triage some today. Cheers!
