### ISSUE TITLE
feat: name and description parameters for `npx cap add electron`

### ISSUE THREAD

**Issue by mandolyte** [ionic-team/capacitor#2604]
# Feature Request

## Describe the Feature Request
When the command is run, it creates a package.json with hard-coded values for name and description:
```
$ cat package.json 
{
  "name": "capacitor-app",
  "version": "1.0.0",
  "description": "An Amazing Capacitor App",
... elided ...
```
And when the packager is run, it generates folders based on the “name” value. This is a request for  arguments to set these values so that they don’t have to be edited by hand (or sed in a Github Action).

So something like:
`npx cap add electron --name "myApp" --description "A bit of description"`

Thanks for your consideration.

## Platform Support Requested

- [ ] Android
- [ ] iOS
- [x] Electron
- [ ] Web

## Related Code
Note the `--web_dir` argument for `npx cap init` is similar in spirit.

**Comment by mandolyte** [comment]
Some notes...
1. The `package.json` appears to copied [here](https://github.com/ionic-team/capacitor/blob/e783d150af6cd7a07b1ca00da862f0d33749f342/cli/scripts/copy-assets.js#L43)
2. The source shows a similar problem solved for Android by an update function to the copied data [here](https://github.com/ionic-team/capacitor/blob/e783d150af6cd7a07b1ca00da862f0d33749f342/cli/scripts/copy-assets.js#L48) 

A similar solution may work for electron... as long as we can access the argument values provided by the user.

**Comment by jcesarmobile** [comment]
For the name, it should use the name on `capacitor.config.json`, so that's a bug.
