### ISSUE TITLE
Support .aab build android

### ISSUE THREAD

**Issue by dalepo** [ionic-team/capacitor#2605]
# Feature Request
## Describe the Feature Request
It's not possible to generate .aab files through capacitor build. I would like to build as .aab instead of apk.
## Platform Support Requested
- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
An config option to build the project as Android app bundle when using the cli

## Additional Context

https://developer.android.com/guide/app-bundle

**Comment by jcesarmobile** [comment]
Capacitor doesn't build apk or aab, just a native project.
From the native project you can generate the apk or aab if you open it in Android Studio and go to `Build -> Build Bundle(s) / APK(s) -> Build Bundle(s)`
