### ISSUE TITLE
bug: Incorrect network status for Electron on Windows 10

### ISSUE THREAD

**Issue by cumbiman** [ionic-team/capacitor#2610]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/core 1.5.0

  @capacitor/android 1.5.0

  @capacitor/ios 1.5.0

  @capacitor/cli 1.5.0

[fatal] Platform electron is not valid.
[success] Android looking great! 👌
[error] Xcode is not installed

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [x] Electron
- [ ] Web

## Current Behavior

In Electron app, Network.getStatus returns true regardless of whether the computer is connected to a network or not. This behavior has been replicated on multiple different computers. The plugin works fine on Android.

## Sample Code or Sample Application Repo

import { Plugins, SplashScreenHideOptions, ConfirmResult } from '@capacitor/core';

const { Network, SplashScreen, SplashScreenHideOptions, Modals, App } = Plugins;

.......

    public async attachNetworkStatus() {

        // Listen to Capacitor's network plugin
        // Let the different parts of the UI know the status
        Network.addListener('networkStatusChange', (netstatus) => {
            AppRuntime.ui.homePage.networkConnected = netstatus.connected;
            AppRuntime.ui.loginPage.networkConnected = netstatus.connected;
            AppRuntime.networkConnected = netstatus.connected;
            AppRuntime.ui.appPage.networkConnected = netstatus.connected;
        })

        const netstatus = await Network.getStatus();
        AppRuntime.networkConnected = netstatus.connected;
        AppRuntime.ui.homePage.networkConnected = netstatus.connected;
        AppRuntime.ui.loginPage.networkConnected = netstatus.connected;
        AppRuntime.ui.appPage.networkConnected = netstatus.connected;
    }

## Reproduction Steps

No reproduction steps beyond adding Network plugin and testing the connection with Network.getStatus() or adding the listener.

## Other Technical Details

`npm --version` output: 6.12.1

`node --version` output: 12.13.1

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Thanks for the issue, I've been able to reproduce.
But it looks like a windows or chrome/chromium issue, the plugin just checks navigator.onLine, and for some reason, on windows it returns true.
I've tested on a regular electron app, on chrome and on firefox, all of them returned true despite wifi was disconnected and I had airplane mode enabled.
Only Internet Explorer returned false.

I've found an electron issue about it but was closed because they don't overwrite the browser objects, so should be reported to chromium team
