### ISSUE TITLE
Issue launching on iOS

### ISSUE THREAD

**Issue by Madlani** [ionic-team/capacitor#2612]
Hello!

I'm trying to develop an app with ionic and launch it using capacitor/xcode. I've started with a template app, but run into 2 issues that I haven't been able to resolve. My steps/errors are below.
1). ionic start myApp sidemenu (and add capacitor in the options menu)
2) ionic capacitor add ios
---this gives me an error [error] Capacitor could not find the web assets directory.
In order to try to fix this, I then try to run "ionic build"
3) ionic build
---this gives me an error An unhandled exception occurred: [BABEL] Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. 

I appreciate the help.

**Comment by Madlani** [comment]
After running "npx cap init", I can now build to iOS, but then get stuck with a thread 1 sig abrt with payload error - as far as I know, I haven't added any frameworks since I'm working from a template app provided, so adding them into embedded content hasn't helped!

**Comment by priyankpat** [comment]
Are you able to share the repo so we can take a look at your implementation?

**Comment by jcesarmobile** [comment]
was it a react app? looks like react apps had problems building on Friday, but seems fixed now. 
It was really a babel bug, not sure if it also affected Angular apps.
can you try again now?

**Comment by Madlani** [comment]
it was an angular app @jcesarmobile , I just attempted to run ionic build and got the same error. @priyankpat I can push it into a repo, although I haven't really modified the code - just used the ionic sidemenu template.

**Comment by jcesarmobile** [comment]
Ah, sorry, when I searched on google your error message last Friday all information was about React.

But second result today is this angular CLI issue https://github.com/angular/angular-cli/issues/17262

Read the comments, there are a few workarounds. 

I personally tried this one and worked `npm install --save-dev --save-exact @babel/compat-data@7.8.0`

**Comment by Madlani** [comment]
@jcesarmobile that fix worked for me, thank you! I do still run into the error when running ionic capacitor add ios, as I'm missing an index.html file in my www folder - I thought that ionic build was supposed to fix this? Sorry if i'm missing something very obvious here!

**Comment by jcesarmobile** [comment]
ionic build is supposed to create the www folder with the index.html inside, so if it didn't create it, report it in ionic CLI repo

**Comment by lhonest** [comment]
I had the same problem, and I resolved by using your method.Thank you! @jcesarmobile @Madlani
