### ISSUE TITLE
bug: Camera.getPhoto sends photo to editor on android

### ISSUE THREAD

**Issue by nulven** [ionic-team/capacitor#2615]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0

  @capacitor/ios 1.5.0

  @capacitor/android 1.5.0

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

The camera takes the picture, then sends it to a photo editor

## Expected Behavior

The camera should take the picture, send the picture to the server, and return the app without the additional prompt

## Sample Code or Sample Application Repo
```
  async takePicture() {
    var image = await Camera.getPhoto({
      quality: 90,
      allowEditing: false,
      resultType: CameraResultType.DataUrl,
      width: 128
    });

    var imageUrl = image.webPath;
    this.setState({
      photo: imageUrl
    });

    var data = {
      session_id: localStorage.getItem('session_id'),
      photo: image
    };

    this.setState({'load': true});
    this.render();

    fetch(`${API_URL}/save`, {
      method: 'post',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data)
    })  
      .then(() => this.reloadReadings())
      .catch(error => {
        console.error(error);
      });
  }
```

## Reproduction Steps

Send an app to android with a button that runs Camera.getPhoto on click. Try taking a picture.

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
I can't reproduce, can you provide a sample app?
What's the Android version of the device? and vendor/model?
also, can you test with capacitor 2.0 (still beta) just in case? `npm install @capacitor/android@next`

**Comment by jcesarmobile** [comment]
closing as there was no response
