### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by fildidi** [ionic-team/capacitor#2616]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

  @capacitor/cli 1.5.0

  @capacitor/android 1.5.0

  @capacitor/core 1.5.0

  @capacitor/ios 1.5.0

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Currently having an issue with Splash screen. Im trying to replace the default splash screens from capacitor with others, by replacing them directly in the folder. Then what happens is that is shows the Splash screen twise. First - it shows it, resized and oddly looking, and then it shows it how is suppose to be. I had exactly the same issue on iOS and solved it by restaring the device.

## Expected Behavior

It should show the Splash screen taking into account the  value inside ```androidScaleType``` immediately.
## Sample Code or Sample Application Repo
Here is a sample of the configs in capacitor.config.json

```
"plugins": {
        "Keyboard": {
            "resize": "body"
        },
        "SplashScreen": {
            "launchAutoHide": true,
            "backgroundColor": "#ff0000",
            "androidSplashResourceName": "splash",
            "androidScaleType": "CENTER_INSIDE",
            "splashFullScreen": true
        }
```

If this ```androidScaleType``` is set to "FIT_XY" then the Splash screen doesn't resize at all.
<!-- 

NOTE: Issues with sample projects are prioritized higher than ones without because they are easier to reproduce and fix.

If you are able to illustrate the bug or feature request with an example, please provide sample code snippets or a sample application via a public GitHub or Bitbucket repo.

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/1627#issuecomment-582975393
