### ISSUE TITLE
%PUBLIC_URL% does not get updated and causing white screen

### ISSUE THREAD

**Issue by leogetzit** [ionic-team/capacitor#2617]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

  @capacitor/ios not installed

  @capacitor/cli 1.5.1

  @capacitor/android 1.5.1

  @capacitor/core 1.5.1

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by leogetzit** [comment]
**Current Behavior**
WHITESCREEN.
This behavior is new and not present in older app.
I add Nothing  to change the template. It is unable to servce
http://localhost/%PUBLIC_URL%/favicon.ico

**Expected Behavior**
The sample app should show the default page

**Sample Code or Sample Application Repo**
There was NO CHANGE MADE TO THE REPO
It is the default template as of today 23 March 2020

**Reproduction Steps**
npx create-react-app theresto-user
npm i -S react-router react-router-dom
npm install -g @ionic/cli
npm i -S @ionic/react @ionic/react-router
ionic init
ionic integrations enable capacitor
ionic build
npx cap sync
npx cap open android

**build and launch the app in any emulating device**
nexus 5, Pixel 3XL, Samsung Note 9

**Other Technical Details**
npm --version output:
6.13.7
node --version output:
13.11.0
pod --version output (iOS issues only):
n/a

**Other Information**
Same process is working for app I started a week ago works fine.
Why am I posting the bug here? Upon inspecting the 
android>app>src>main>assets>public>index.html
I see that %PUBLIC_URL% is still there in index.html

When I look at older app, this has been removed.

Also interesting to know that in index.html in the build path by ionic build does NOT have the %PUBLIC_URL%

Maybe I am a wrong. Not an expert. Any help if I am wrong is appreciated.

**Comment by leogetzit** [comment]
Package JSON for help:
{
  "name": "test-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@capacitor/android": "^1.5.1",
    "@capacitor/core": "1.5.1",
    "@ionic/pwa-elements": "^1.5.1",
    "@ionic/react": "^5.0.5",
    "@ionic/react-hooks": "0.0.6",
    "@ionic/react-router": "^5.0.5",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@capacitor/cli": "1.5.1"
  }
}

**Comment by leogetzit** [comment]
Note, I case it was lost in translation:
The sample app serves fine with 
ionic serve or npm start

**Comment by jcesarmobile** [comment]
I can't reproduce following the steps you provided.
Also, the bug is not related to Capacitor, Capacitor just serves what you tell it to serve, and you can't have the `PUBLIC_URL` in the Capacitor files because Capacitor doesn't understand what that is.

The problem is in your build tools or a misconfiguration in your app.

Make sure that your "webDir"` entry in `capacitor.config.json` is set to `"build"` and not to `"public"`.

If that's set to `"build"`, then you'll have to figure out why the build folder has the references to `PUBLIC_URL`

**Comment by leogetzit** [comment]
> I can't reproduce following the steps you provided.
> Also, the bug is not related to Capacitor, Capacitor just serves what you tell it to serve, and you can't have the `PUBLIC_URL` in the Capacitor files because Capacitor doesn't understand what that is.
> 
> The problem is in your build tools or a misconfiguration in your app.
> 
> Make sure that your "webDir"`entry in`capacitor.config.json`is set to`"build"`and not to`"public"`.
> 
> If that's set to `"build"`, then you'll have to figure out why the build folder has the references to `PUBLIC_URL`

Thank you for a quick reply. I will follow my own steps again and see if I can replicate this.
