### ISSUE TITLE
Get changelogs working

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#262]
Supposedly lerna has a changelog plugin we can use for this? https://github.com/lerna/lerna-changelog

**Comment by IT-MikeS** [comment]
So far I can tell, we add the config to the `lerna.json` and then it will generate a markdown changelog from closed PR's with labels that match the config below. Just need to export a repo access token in terminal and run `lerna-changelog`. I haven't had any luck getting it to output anything but then again I cant test it on a proper repo with PR's at this moment.

```
"changelog": {
  "labels": {
    "enhancement": ":rocket: Enhancement",
    "bug": ":bug: Bug Fix"
  }
},
```

**Comment by jcesarmobile** [comment]
removing the priority low tag, this is something that should be part of the final release, on every beta release we do, people ask for the changelog
