### ISSUE TITLE
feat(LocalNotification):  ability to generate localNotification when app is in background (from service)

### ISSUE THREAD

**Issue by dwlrathod** [ionic-team/capacitor#2626]
# Feature Request

## Describe the Feature Request
Not able to generate a local notification when the app is in the background because activity is needed to create [LocalNotificationManager](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java#L53) instance.

## Platform Support Requested

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
We should remove the activity as param and add context in the constructor. 
We can remove usage of activity from [LocalNotificationManager](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java#L249) and can be replace `activity` with `MainActivity.class`.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

**Comment by BorntraegerMarc** [comment]
@jcesarmobile the issue received reactions. How should we proceed? We're happy to provide a PR for the feature. But I would like to get a 👍 from the capacitor team to know that you support the PR
