### ISSUE TITLE
feat: iOS Project. Replace public with open to make it easier to override the BrideViewController with custom code

### ISSUE THREAD

**Issue by dungi** [ionic-team/capacitor#2628]
# Feature Request

## Describe the Feature Request
Need to replace "public" with "open" to make it easier to override the code in CAPBrideViewController

## Platform Support Requested

- [ ] Android
- [x ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
Need to replace "public" with "open" to make it easier to override the code in CAPBrideViewController

## Related Code
CAPBrideViewController.swift

**Comment by dungi** [comment]
Created a Pullrequest for that https://github.com/ionic-team/capacitor/pull/2635

**Comment by jcesarmobile** [comment]
why do you want/need to override CAPBrideViewController code?

**Comment by dungi** [comment]
Cause we want some own behaviour for some WebKit Things and add an Offline Screen and something like this.

**Comment by jcesarmobile** [comment]
can you expand?

**Comment by dungi** [comment]
The Problem with Extensions are, that you can't store  stored properties. We want to handle some custom things for us, that would be more complex if we can't just inherit from the normal code base.
