### ISSUE TITLE
bug: App crashes when trying to register the plugin

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [ionic-team/capacitor#2630]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
❯ npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/ios 1.4.0

  @capacitor/core 1.4.0

  @capacitor/android 1.5.0


[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    capacitor-camera-preview (0.2.0)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Had the bug #2383 and tried to check if updating iOS (13.4), macOS (10.15.4) and Xcode (11.4) versions would solve the issue. Apparently it did but a new bug appeared

## Expected Behavior

Run the app through Xcode
## Reproduction Steps

I guess trying to run any app on Xcode 11.4 would have the same issue. There's a post in the [forums](https://forum.ionicframework.com/t/xcode-11-4/185770) and other one on [Capacitor  Slack](https://getcapacitor.slack.com/archives/C94SE07NJ/p1585088660049800)

## Other Technical Details

`npm --version` output: 6.13.7

`node --version` output: 10.15.3

`pod --version` output (iOS issues only): 1.9.1

**Comment by jcesarmobile** [comment]
Update to capacitor 2.0.0-beta.1 (npm install @capacitor/ios@next)

**Comment by parthnayak7448** [comment]
@jcesarmobile 
I tried the npm install @capacitor/ios@next but still same issue. 

Can you share all packages detail
Or some other way it will be great help. 

I have production app to update

**Comment by jcesarmobile** [comment]
It should be just that. Try npx cap sync and do a clean on Xcode just in case

**Comment by parthnayak7448** [comment]
@jcesarmobile Finally done. 

> Deleting node_modules -> npm install 

work for me

Thanks
