### ISSUE TITLE
bug: ios xcode build width error "library not found for -ljcore-ios-2.1.4"

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/capacitor#2632]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/electron: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.0.0-beta.0

  @capacitor/core 2.0.0-beta.0

  @capacitor/ios 2.0.0-beta.1

  @capacitor/android 2.0.0-beta.0

[success] Android looking great! 👌
  Found 11 Capacitor plugins for ios:
    cordova-plugin-camera (4.1.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-jcore (1.3.1)
    cordova-plugin-media-capture (3.0.3)
    cordova-plugin-network-information (2.0.3-dev)
    cordova-plugin-qrscanner (3.0.1)
    cordova-plugin-streaming-media (2.2.0)
    jpush-phonegap-plugin (3.7.3)
    phonegap-plugin-mobile-accessibility (1.0.5)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [ x ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

xcode build error

## Expected Behavior
xcode build success

## Other Technical Details

`npm --version` output:  6.13.4

`node --version` output: 12.16.1

`pod --version` output (iOS issues only): 1.9.1

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by AlwaysLoveme** [comment]
> Can you provide a sample app?

there is https://github.com/AlwaysLoveme/ionic5DemoApp.git

**Comment by AlwaysLoveme** [comment]
> Can you provide a sample app?

I tried 2.0.0@beta.1, but also build error

**Comment by jcesarmobile** [comment]
I can't reproduce the `library not found for -ljcore-ios-2.1.4` error, just the other one you reported yesterday

**Comment by AlwaysLoveme** [comment]
> 我无法重现该`library not found for -ljcore-ios-2.1.4`错误，仅是您昨天报告的另一个错误

since I add plugin "jpush-phonegap-plugin", Xcode build with error "library not found for -ljcore-ios-2.1.4"

**Comment by AlwaysLoveme** [comment]
> I can't reproduce the `library not found for -ljcore-ios-2.1.4` error, just the other one you reported yesterday

so, the other one error can resolved?

**Comment by jcesarmobile** [comment]
there is something wrong with the jcore-ios.a file, I've reported it in their repository and proposed a possible solution they can implement
https://github.com/jpush/cordova-plugin-jcore/issues/7

**Comment by jcesarmobile** [comment]
so, the problem is CocoaPods doesn't allow .a libraries without lib prefix in the name, I've patched the CLI to prepend lib to .a files if they didn't have it already.

**Comment by AlwaysLoveme** [comment]
> so, the problem is CocoaPods doesn't allow .a libraries without lib prefix in the name, I've patched the CLI to prepend lib to .a files if they didn't have it already.

Hi, i copy this commit change to my local @capacitor/cli which is "fix(cordova): Add lib prefix to .a library names (#2636)", now Xcode build success width no errors, but the app  in my iphone can not  running, it is crashed, here is my demo: https://github.com/AlwaysLoveme/demo_.git
