### ISSUE TITLE
feat (Android): LocalNotification control removal of notification

### ISSUE THREAD

**Issue by Juarrow** [ionic-team/capacitor#2637]
# Feature Request

## Describe the Feature Request

It would be good being able to have a `autoCancel`-property in the in the `LocalNotification` interface for being able to control wether a notification disappears on click or not.
This would control the following line https://github.com/ionic-team/capacitor/blob/0bfa0bfeb7607e987b1a497bc8f5e0b64e9ca17d/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java#L153

## Platform Support Requested

- [x] Android
- [?] iOS
- [?] Electron
- [?] Web
(i only checked the behavior for Android, so i don't know wether this is applicable to the other platforms as well)

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
