### ISSUE TITLE
feat: Enable Customized Error Handling In Native Code

### ISSUE THREAD

**Issue by fkirc** [ionic-team/capacitor#2645]
# Feature Request

When a JavaScript error happens in the WebView, it gets logged to the native environment.
For example, JavaScript errors appear in the Logcat of Android Studio.
This is fine, but there are two use cases where I want to customize the native error handling:

- I have some native UI tests that use native APIs to interact with the WebView. If a JavaScript error happens during these native UI tests, then I want to immediately crash the native app and fail my UI test.
- I might want to log JavaScript errors to remote services with the help of native logging libraries (e.g. Sentry Android).

## Platform Support Requested

- [X] Android
- [X] iOS

## Describe Preferred Solution

There are different places where native error handling could be customized.
One place is Android's `BridgeWebViewClient.onConsoleMessage()`, which receives error logs as well as all other `console`-messages.
Another place is Android's `MessageHandler.postMessage()`, which receives error objects from `native-bridge.js`.
To achieve the maximum flexibility, it might be a good idea to allow customized subclasses of `BridgeWebChromeClient`.

Please let me know how you would implement the above-mentioned use cases.
I would be willing to submit a PR if I know what solution to implement.

**Comment by fkirc** [comment]
I was now able to implement a solution without any Capacitor changes.
Firstly, I added a subclass of `BridgeWebChromeClient` to my own Android sub-project:

```Kotlin
import android.webkit.ConsoleMessage
import com.getcapacitor.Bridge
import com.getcapacitor.BridgeWebChromeClient;
import timber.log.Timber

class CustomWebChromeClient(bridge: Bridge) : BridgeWebChromeClient(bridge) {

    override fun onConsoleMessage(consoleMessage: ConsoleMessage?): Boolean {
        // Check whether we want to do some customized error handling.
        if (consoleMessage?.isErrorMessage() == true) {
            doCustomizedErrorHandling(consoleMessage = consoleMessage)
        }

        // Let Capacitor do it's default stuff for handling console messages.
        return super.onConsoleMessage(consoleMessage)
    }

    private fun doCustomizedErrorHandling(consoleMessage: ConsoleMessage) {
        // Call customized logging infrastructure.
        Timber.e(consoleMessage.message())
    }

    private fun ConsoleMessage.isErrorMessage(): Boolean {
        if (!isValidMsg(this.message())) {
            return false
        }
        val level = this.messageLevel().name
        return "ERROR".equals(level, ignoreCase = true)
    }
}
```

Then I injected an instance of this subclass into my Android WebView.
I did this in my MainActivity's `onCreate()`, after initializing the Capacitor bridge:

```Kotlin
import android.webkit.WebView
import com.getcapacitor.BridgeActivity
import com.getcapacitor.Plugin

class MainActivity : BridgeActivity() {
    public override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Initializes the Bridge
        init(savedInstanceState, object : ArrayList<Class<out Plugin?>?>() {
            init {}
        })

        // Obtain a reference to the webView, then inject our custom WebChromeClient.
        val webView = findViewById<WebView>(com.getcapacitor.android.R.id.webview)
        webView.webChromeClient = CustomWebChromeClient(this.bridge)
    }
}
```

**Comment by jcesarmobile** [comment]
Yeah, you can use your subclass of WebViewChromeClient

**Comment by sanjaynishad** [comment]
I wanted to show a custom error HTML page with WebView instead of "web page not available".

I used `Bridge.addWebViewListener()` method for the same and added `onReceivedError` handler with WebView, below is the working `MainActivity` class

```
public class MainActivity extends BridgeActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // custom plugins
        registerPlugin(com.getcapacitor.community.admob.AdMob.class);
    }

    @Override
    public void onStart() {
        super.onStart();

        this.getBridge().addWebViewListener(new WebViewListener() {
            @Override
            public void onReceivedError(WebView webView) {
                webView.loadUrl("file:///android_asset/error.html");
            }
        });
    }
}
