### ISSUE TITLE
POST request fails on iOS

### ISSUE THREAD

**Issue by mullinsmikey** [ionic-team/capacitor#2647]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
**@capacitor/android** not installed
**@capacitor/cli** 1.5.1
**@capacitor/core** 1.5.1
**@capacitor/ios** 2.0.0-beta.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

fetch() and axios successfully perform GET requests to the backend while POST requests are always failing.
• Tested with `@capacitor/ios@1.5.1` and mocky.io.
• Tested on iOS simulator, iOS real device.
• Not tested on Android platform.

## Sample Code

```typescript
const axConf: AxiosRequestConfig = {
    url: query, // string
    method: m, // string
    baseURL: global.base_uri + 'api/' + global.api_version + '/',
    headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json'
    },
    data: r, // object
    validateStatus: function (status) { return status >= 200 && status < 300; }
};
return new Promise(resolve => {
    axios(axConf)
        .then(response => resolve(successRes(r, i, response.data)))
        .catch(function (error) {
                console.log(error);
                if (error.response) {
                    resolve(errorRes(i, error.response));
                } else if (error.request) {
                    resolve(errorRes(i, error.request));
                } else {
                    resolve(errorRes(i, error.message));
                }
            }
        );
});
```

## Other Technical Details

`pod --version` output (iOS issues only):
1.8.4

## Other Information

fetch() returns `"cancelled"` which tells me nothing but a failure meanwhile axios generates a more descriptive error:
```json
{
  "message": "Network Error",
  "name": "Error",
  "stack": "capacitor://localhost/static/js/8.98344607.chunk.js:2:168604\ncapacitor://localhost/static/js/8.98344607.chunk.js:2:167548",
  "config": {
    "url": "auth",
    "method": "post",
    "data": "{\"email\":\"email-here\",\"password\":\"111111\"}",
    "headers": {
      "Accept": "application/json",
      "Content-Type": "application/json"
    },
    "baseURL": "https://website.com/api/1.3/",
    "transformRequest": [null],
    "transformResponse": [null],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  }
}
```

**Comment by jcesarmobile** [comment]
Capacitor doesn’t handle of affect the network connections, so if it fails is an Apple bug or a server configuration problem, usually the later. Make sure you have properly configured CORS to allow POST from capacitor://localhost

**Comment by mullinsmikey** [comment]
CORS already checked on my backend. Furthermore mocky is configured to accept all pre-flight requests.

**Comment by mullinsmikey** [comment]
Update: found the solution. In case anyone would ever need this: https://stackoverflow.com/a/60911038/3909488

**Comment by adnanalbeda** [comment]
> Update: found the solution. In case anyone would ever need this: https://stackoverflow.com/a/60911038/3909488

It didn't help me. This solution is working when using fetch methods, not axios. 
After lots of research, I found that axios don't work with capacitor on iOS. 
I don't know why, but that's a conclusion I'm sure of.
