### ISSUE TITLE
bug: File google-services.json is missing.

### ISSUE THREAD

**Issue by ga27** [ionic-team/capacitor#2650]
Description of the problem:
When i try to run an app on android i get this error:
"File google-services.json is missing. The Google Services Plugin cannot function without it.", the problem appear after installing this package "cordova-plugin-fcm-with-dependecy-updated" and using "import { FCM } from '@ionic-native/fcm/ngx';.".
The google-services.json file is in "/android/app/" folder, i already put it on many folders to test, but, sadly, it dont work :/

**Comment by jcesarmobile** [comment]
what version of the plugin are you using?
I made 4.1.1 it work with [this workaround](https://github.com/ionic-team/capacitor/issues/2483) a month ago

**Comment by ga27** [comment]
@capacitor/cli 1.5.2
npm 6.3.14
node 12.16.1
cordova-plugin-fcm-with-dependecy-updated@4.4.1
@ionic-native/fcm@5.23.0

**Comment by jeroScript** [comment]
Sorry, did you work with ionic? Because i am having problems to install the plugin with version 4.1.1. I am using Ionic with capacitor
