### ISSUE TITLE
bug:  add cordova plugin "jpush-phonegap-plugin",  IOS app crashed 

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/capacitor#2653]
# Bug Report
Hi, there is still a problem with plugin "jpush-phonegap-plugin",  since I download this commit change to replace my local files which is "https://github.com/ionic-team/capacitor/pull/2636", Xcode build success width no errors, but it can not running on my phone, the app crashed
# Capacitor Version

`npx cap doctor` output:
```
Latest Dependencies:

  @capacitor/cli: 1.5.2

  @capacitor/core: 1.5.2

  @capacitor/android: 1.5.2

  @capacitor/electron: 1.5.2

  @capacitor/ios: 1.5.2

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/electron not installed


  @capacitor/cli 1.5.2

  @capacitor/ios 1.5.2

  @capacitor/core 1.5.2

  Found 3 Capacitor plugins for ios:
    cordova-plugin-device (2.0.3)
    cordova-plugin-jcore (1.3.1)
    jpush-phonegap-plugin (3.7.3)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Xcode build success, but app crashed.

## Expected Behavior
app can running normal

## Sample Code or Sample Application Repo
there is sample code https://github.com/AlwaysLoveme/demo_.git

## Reproduction Steps
1. create a blank project with "@ionic/cli"
2. add cordova plugin "npm i jpush-phonegap-plugin"
3. download "https://github.com/ionic-team/capacitor.git" files which is included ""fix(cordova): Add lib prefix to .a library names (#2636)", and build @capacitor/cli, then copy dist to replace local file
4. run "ionic build --prod && ionic cap add ios && ionic cap open ios"
5. Xcode running

## Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: 12.16.1
`pod --version` output (iOS issues only): 1.9.1

## Other Information
 
#2632

**Comment by jcesarmobile** [comment]
Closing as known incompatible plugin

Since Capacitor projects are Swift projects, plugins with categories to AppDelegate won't work and in this case it crash the app because it swizzle a method in the category.

**Comment by sertal70** [comment]
Hi, @jcesarmobile why the "Known Incompatible Cordova Plugins" page does not report this? My work for implementing push notifications in a Capacitor app is resulting in an incredible amount of time wasted...
