### ISSUE TITLE
feat: can statusbar plugin add a function that get the statusbar height on Android

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/capacitor#2655]
# Feature Request

## Describe the Feature Request

my project need Immersive status bar, but i can not get the statusbar height, cause the statusbar hide some content of ion-header, so,  i hope that statusbar plugin can get this. something like Plugins.Statusbar.getHeight().
## Platform Support Requested

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

**Comment by aolsx** [comment]
Why isn't this function available yet?
