### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by novaknole** [ionic-team/capacitor#2659]
## Capacitor Version 1.5.2

`npx cap doctor` output:

```
@capacitor/cli 1.5.2

  @capacitor/core 1.5.2

  @capacitor/ios 1.5.2

  @capacitor/android 1.5.2
```

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Electron
- [x] Web

## Current Behavior

I have the following code in my app.js.

```js
import {
    Plugins
} from '@capacitor/core'

const { PushNotifications } = Plugins;
PushNotifications.register();
PushNotifications.addListener('registration', function(e){
    console.log("eee ", e);
})
PushNotifications.addListener('registrationError', function(e){
    console.log("err ", e);
});

```

After using `npx add ios` and running app from xcode, it works fine. At least it says that remote notifications are not supported in simulator. Now, I run the website in browser and it says: 
`Uncaught (in promise) PushNotifications does not have web implementation.`.

**Question 1)** Why the above error? does this mean that I have to use  `PushAPI`  of the browser to have this working? i also have service worker where I listen `push` events. How do I make these work for both PWA web version and in  also native version?

**Question 2)** I don't have ionic. So I use `capacitor` only just to convert my PWA web app to native app and also to use push notifications on ios , because `pushapi` is not supported on ios. Now, because of this, in my `app.js` , I have to import `capacitor plugins`. This means that my bundle size in web increases . If I can't use `capacitor` plugins in web, why to have import at all in `app.js` at all? Any idea how I can tackle this?

**Comment by Unkn0wn0x** [comment]
Your issue is not related to the PushNotification Plugin itself, did you added the following code to your `app.components.ts`?

```
import { Component } from '@angular/core';
import { Plugins } from '@capacitor/core';
import { registerWebPlugin } from "@capacitor/core";

const { PushNotifications } = Plugins;

@Component({
   selector: 'app-root',
   templateUrl: 'app.component.html'
})
export class AppComponent {

    constructor() {
        this.initializeApp();
    }

    initializeApp() {
        this.platform.ready().then(() => {
            registerWebPlugin(PushNotifications);
        });
    }

}
```

Hope it helps.

Cheers
Unkn0wn0x
