### ISSUE TITLE
bug: fcm.onNotification() dont work

### ISSUE THREAD

**Issue by ga27** [ionic-team/capacitor#2661]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.5.2

  @capacitor/core: 1.5.2

  @capacitor/android: 1.5.2

  @capacitor/ios: 1.5.2

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.5.1

  @capacitor/android 2.0.0-beta.1

  @capacitor/core 1.5.1
## Affected Platform(s)

- [ X ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I'm trying to use "fcm.onNotification" in a ionic 5 test app but it don't return the notification to the html page, i've tried different sintaxes in many ways, but i've couldn't do it. 

## Expected Behavior

I want to build a notification center page later.

## Sample Code or Sample Application Repo
<b>home.page.html</b>

```
<ion-content>
  <div>
    <ion-list>
      <ion-item *ngFor="let not of notificacoes">
        <ion-label text-wrap>
          <ion-text color="primary">
            <h3>{{not.title}}</h3>
          </ion-text>
          <p>{{not.body}}</p>
        </ion-label>
      </ion-item>
    </ion-list>
  </div>
  <div *ngIf="!notificacoes.length" class="empty">
    Sem novas notificacoes
  </div>
</ion-content>
```

<b> home.page.ts </b>
```
import { Component } from '@angular/core';
import { FCM } from '@ionic-native/fcm/ngx';
import { Platform } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  notificacoes: any = [];
  constructor(public plt: Platform, private fcm: FCM) {
    this.plt.ready()
      .then(() => {
        this.fcm.onNotification().subscribe(dados => {
          if (dados.wasTapped) {
            this.notificacoes.push({
              body: dados.body,
              title: dados.title
            })
          } else {
            this.notificacoes.push({
              body: dados.body,
              title: dados.title
            })
          };
        });
      }
      )}
    }

```
<b> app.module.ts </b>

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';
import { FCM } from '@ionic-native/fcm';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule],
  providers: [
    StatusBar,
    SplashScreen,
    FCM,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

## Other Technical Details

`npm --version` output: 6.13.7

`node --version` output:12.16.0

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Capacitor ships with push support and declares a FirebaseMessagingService and there can be only one, so if you are using other plugin for push you'll have to overwrite the FirebaseMessagingService

**Comment by ga27** [comment]
> Capacitor ships with push support and declares a FirebaseMessagingService and there can be only one, so if you are using other plugin for push you'll have to overwrite the FirebaseMessagingService

Sorry, i'm a beginner, how can i do that?
