### ISSUE TITLE
bug: Thread 1: EXC_BAD_INSTRUCTION in "registerPlugins" function

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/capacitor#2662]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```bash
Latest Dependencies:

  @capacitor/cli: 1.5.2

  @capacitor/core: 1.5.2

  @capacitor/android: 1.5.2

  @capacitor/ios: 1.5.2

Installed Dependencies:

  @capacitor/cli 1.5.2

  @capacitor/ios 1.5.2

  @capacitor/core 1.5.2

  @capacitor/android 1.5.2


[success] Android looking great! 👌
  Found 5 Capacitor plugins for ios:
    cordova-plugin-actionsheet (2.3.3)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-tts (0.2.3)
    cordova-sqlite-storage (5.0.0)
    uk.co.workingedge.phonegap.plugin.launchnavigator (5.0.4)
[success] iOS looking great! 👌
```

## Affected Platform(s)
- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I upgraded my project to the latest Capacitor version and also XCode. After that I'm unable to run (not build) my project. I commented the failing line of code in the `CAPBridge.swift` file. The error happens before the splash screen could hide.

## Expected Behavior

The application should run without runtime errors.

## Sample Code or Sample Application Repo

```swift
func registerPlugins() {
    let classCount = objc_getClassList(nil, 0)
    let classes = UnsafeMutablePointer<AnyClass?>.allocate(capacity: Int(classCount))

    let releasingClasses = AutoreleasingUnsafeMutablePointer<AnyClass>(classes)
    let numClasses: Int32 = objc_getClassList(releasingClasses, classCount)

    for i in 0..<Int(numClasses) {
      if let c: AnyClass = classes[i] {
        if class_getSuperclass(c) == CDVPlugin.self {
          injectCordovaFiles = true
        }
        // the error happens here
        if class_conformsToProtocol(c, CAPBridgedPlugin.self) {
          let pluginClassName = NSStringFromClass(c)
          let pluginType = c as! CAPPlugin.Type
          let bridgeType = c as! CAPBridgedPlugin.Type

          registerPlugin(pluginClassName, bridgeType.jsName(), pluginType)
        }
      }
    }
    classes.deallocate()
  }
```

## Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: 12.6.0

`pod --version` output (iOS issues only): 1.8.4

**Comment by jcesarmobile** [comment]
Can you do a `Product -> Clean Build Folder`?
1.5.2 only fix is precisely this problem.

**Comment by danielsogl** [comment]
Jup, cleaning the projected fixed the issue. Thanks for you quick reply

**Comment by jcesarmobile** [comment]
Do you have this line in your Podfile?
https://github.com/ionic-team/capacitor/blob/master/ios-template/App/Podfile#L7

If not, add it to prevent the caching of CocoaPods local libraries. If you do, then we might need something else.
