### ISSUE TITLE
feat: Should the Push Notification Guide direct the user to subscribe to FCM token updates?

### ISSUE THREAD

**Issue by dminkovsky** [ionic-team/capacitor#2665]
# Feature Request

## Describe the Feature Request

In the Push Notification Guide, it says the user can get the FCM token by querying `InstanceID`:

```
Messaging.messaging().apnsToken = deviceToken
InstanceID.instanceID().instanceID { (result, error) in
	if let error = error {
		NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
	} else if let result = result {
		NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: result.token)
	}
}
```

However, in the FCM docs about setting up an iOS client, it says you can also monitor the token to find out when it changes:

https://firebase.google.com/docs/cloud-messaging/ios/client?authuser=1#monitor-token-refresh

Practically, does it make a difference? Should the docs direct the user to this second approach?

## Platform Support Requested

- [x] iOS
- [ ] Android
- [ ] Electron
- [ ] Web

**Comment by 2bona** [comment]
Am really sorry, This is out of the question , but someone using **vuejs** and capacitor how do i **implement the push notification API** on my app all the syntax from the docs are **Typescript** and i cant seem to access the API use the **PushNotifications** method from the **Plugin** I hv been trying to get this to work for days now i hv sent a tweet to @capacitor but i got no response, please help me out guys, i know i sound desperate that's cos i am.

**Comment by dminkovsky** [comment]
Also maybe this is all beyond the scope of these docs, but in terms of FCM token lifecycle, not only can you monitor as mentioned above, but on server-side message sending you have to watch out for the error `messaging/registration-token-not-registered` in case a token has become invalid (https://stackoverflow.com/a/54870854/741970). Per the docs:

```
The provided registration token is not registered. A previously valid registration token can be unregistered for a variety of reasons, including: 

  | The provided registration token is not registered. A previously valid       registration token can be unregistered for a variety of reasons,       including:                           The client app unregistered itself from FCM.                             The client app was automatically unregistered. This can happen if           the user uninstalls the application or, on iOS, if the APNS Feedback           Service reported the APNS token as invalid.                             The registration token expired. For example, Google might decide to           refresh registration tokens or the APNS token may have expired for           iOS devices.                             The client app was updated, but the new version is not configured to           receive messages.                       For all these cases, remove this registration token and stop using it to       send messages.
-- | --
