### ISSUE TITLE
bug: Attempting to change `androidScheme` removes hostname suffix

### ISSUE THREAD

**Issue by yoojene** [ionic-team/capacitor#2669]
# Bug Report

## Capacitor Version

Installed Dependencies:
 `@capacitor/cli 1.5.1`
 `@capacitor/core 1.5.1`
 `@capacitor/android 1.5.1`
  `@capacitor/ios 1.5.1`

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I have changed the `androidScheme` property in `capacitor.config.json` to `capacitor`.  When debugging the Android build, I get a CORS header issue on origin `capacitor://` even though it looks as if the content is being served on `capacitor://localhost`

I have `capacitor://localhost` open to CORS on my server - the iOS build works as expected

## Expected Behavior

I would expect the CORS check to be on `capacitor://localhost` and not `capacitor://`

## Sample Code or Sample Application Repo

```
{
  "appId": "xx.xx.xx",
  "appName": "My App",
  "bundledWebRuntime": false,
  "npmClient": "yarn",
  "webDir": "dist",
    "server": {
      "androidScheme": "capacitor"
    }
}
```
```
Access to fetch at 'https://xxxx.xxx.xxxx.xx/countries' from origin 'capacitor://' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

<img width="1260" alt="logs" src="https://user-images.githubusercontent.com/14247260/78020193-e4b30b00-7348-11ea-9499-f60a51260968.png">

## Other Technical Details

`npm --version` output: 6.4.1

`node --version` output: 10.15.0

`pod --version` output (iOS issues only):

Android version: 10 Security patch level 5

## Other Information

https://stackoverflow.com/questions/59319882/capacitor-set-origin-for-cors

I have also tried setting the `hostname` property as described here to `localhost` which did not change the outcome

**Comment by jcesarmobile** [comment]
That's an Android webview "feature", it has been reported, but doesn't looks like Google is going to change it.

https://bugs.chromium.org/p/chromium/issues/detail?id=1029487
