### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by krushn** [ionic-team/capacitor#2679]
# Bug Report

Deeplink working in Android but not on iPhone 

## Capacitor Version

  @capacitor/cli 1.5.2

  @capacitor/ios 2.0.0-beta.1

  @capacitor/android 1.5.2

  @capacitor/core 1.5.2

## Affected Platform(s) 
- iOS 

## Current Behavior

opening `https://employer.dev.pogi.io/update-password/1234` from email in android open update password page in app, but show home page in iPhone. 

## Expected Behavior

Clicking on link in email/html page should open update password page in installed app 

## Sample Code or Sample Application Repo

**AppDebug.entitlements** 

`
<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:employer.dev.pogi.io</string>
        <string>applinks:employer.pogi.io</string>
        <string>applinks:localhost:8100</string> 
</array>
`

**app.component.ts** 

`
_handleDeeplinks() {
   this.deeplinks.route({
      '/update-password': 'update-password',
      '/update-password/:token': 'update-password',
      '/verify-email': 'verify-email',
      '/verify-email/:email': 'verify-email',
      '/verify-email/:email/:code': 'verify-email',
    }).subscribe((match) => {
 
      this.router.navigateByUrl(match.$link.path);

    }, (nomatch) => {  
      //console.error('Got a deeplink that didn\'t match', nomatch);
      //return true;
    });
}
`

## Reproduction Steps

build app in Xcode and add content given above to files and run in ios, create html file with link `https://employer.dev.pogi.io/update-password/1234`  and clicking on that link should open update password page in ios app,  working in android.
 
`npm --version` output:

6.14.4

`node --version` output:

v10.16.0

`pod --version` output (iOS issues only):

1.8.4

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce, in this cases the problem is usually something not configured correctly.
You can check this guide and see if you missed some step:
https://capacitor.ionicframework.com/docs/guides/deep-links
