### ISSUE TITLE
feat: Push notifications plugin does not have #areEnabled method

### ISSUE THREAD

**Issue by dminkovsky** [ionic-team/capacitor#2683]
# Feature Request

## Describe the Feature Request

The local notifications plugin features an `areEnabled` method. This would be useful for push notifications as well. On iOS this can be supported with:

```
UNUserNotificationCenter.current().getNotificationSettings { (settings) in
   print("Notification settings: \(settings)")
   // return authorizationstatus to plugin
}
```
(https://developer.apple.com/documentation/usernotifications/unnotificationsettings/1648391-authorizationstatus)

Not sure about other platforms, but I suspect it's possible.

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

A method like `LocalNotifications#areEnabled()`

**Comment by jcesarmobile** [comment]
There is a permissions plugin where you can check the permissions, or you can use the new requestPermissions that will prompt if not prompted before and return the result of the prompt, or you can use the LocalNotifications one since the result is the same as the underlying native framework is the same.

**Comment by dminkovsky** [comment]
Yes, I'm on 2.0.0 beta and am using the new `requestPermission()`. I am not seeing the Permissions plugin though... 

<img width="173" alt="Screen Shot 2020-04-03 at 10 30 40 AM" src="https://user-images.githubusercontent.com/218725/78371589-2c7aa200-7596-11ea-85b6-c42e3d4b498f.png">

**Comment by jcesarmobile** [comment]
yeah, it's not documented, I have it on my TODO list for the final 2.0

**Comment by dminkovsky** [comment]
I found `Permissions` in the code. Assuming it's on the Plugins object like the others.

https://github.com/ionic-team/capacitor/blob/ee8f63af8bf9d493e34396f44dbb53ef65ec0c38/ios/Capacitor/Capacitor/Plugins/Permissions.swift

And also, yes, `LocalNotifications#areEnabled()` is, indeed, that same native call. Why not just copy paste it for `PushNotifications`?

**Comment by dminkovsky** [comment]
> yeah, it's not documented, I have it on my TODO list for the final 2.0

Oh okay. Thank you.

**Comment by dminkovsky** [comment]
Can I use the API in the Permissions plugin or is that planned to change?

**Comment by jcesarmobile** [comment]
You can use it, it's been available for a long time, but just not documented

**Comment by jcesarmobile** [comment]
the page was created when the plugin was implemented back in August, but was not added to the side menu, just added it 
https://github.com/ionic-team/capacitor/pull/2684
