### ISSUE TITLE
bug: [Error] [blocked] Access to geolocation was blocked over insecure connection to capacitor://localhost.

### ISSUE THREAD

**Issue by felixerdy** [ionic-team/capacitor#2692]
# Bug Report
I switched my ionic app from cordova to capacitor lately as capacitor provides more accurate geolocation readings with the Geolocation Plugin. 

I'm using mapbox-gl-js and its geolocation plugin. The plugin itself catches the current geolocation and visualizes it on the map. As my app is running on `capacitor://localhost`, the plugin is unable to get the current geolocation

<img width="1020" alt="Bildschirmfoto 2020-04-04 um 13 57 57" src="https://user-images.githubusercontent.com/12086004/78450083-4c849100-767c-11ea-8cdd-20e02d8f51e2.png">

The plugin itself is using the `navigator.geolocation` function to access geolocations.

This did work when using cordova but doesn't work anymore after switching to capacitor.

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.0.0

  @capacitor/core: 2.0.0

  @capacitor/android: 2.0.0

  @capacitor/electron: 2.0.0

  @capacitor/ios: 2.0.0

Installed Dependencies:


  @capacitor/cli 2.0.0

  @capacitor/core 2.0.0

  @capacitor/android 2.0.0

  @capacitor/ios 2.0.0

  @capacitor/electron 1.5.2

[success] Android looking great! 👌
  Found 9 Capacitor plugins for ios:
    cordova-plugin-device-orientation (2.0.1)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-insomnia (4.3.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-splashscreen (5.0.3)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.4)
[success] iOS looking great! 👌
[success] electron looking great! 👌
```

This did also not work with capacitor 1.5.2

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

 [Error] [blocked] Access to geolocation was blocked over insecure connection to capacitor://localhost.

## Expected Behavior

`navigator.geolocation` can access geolocations on `capacitor://localhost`

## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.16.1

`pod --version` output (iOS issues only): 1.8.4

**Comment by jcesarmobile** [comment]
This is a limitation in the custom schemes, Apple doesn’t consider them secure.

**Comment by ebellempire** [comment]
Can you provide more info about the Apple limitations? 

I'm using Capacitor Geolocation and it works in some contexts but not others. 

For example, this works fine to sort lists by proximity:

```
  getUserLocation() {
    return new Promise(resolve => {
      Geolocation.getCurrentPosition().then(
        position => {
          this.userLocation = {
            lat: position.coords.latitude,
            lon: position.coords.longitude
          };
          resolve(this.userLocation);
        },
        _err => {
          this.userLocation = false;
          resolve(this.userLocation);
        }
      );
    });
  }
```

But when used with a third-party map (MapBoxGL JS) in my app, this fails on iOS:

```
      var geolocation_control = new MapboxGL.GeolocateControl({
        positionOptions: {
          enableHighAccuracy: true
        },
        trackUserLocation: true
      });
      map.addControl(geolocation_control);
      geolocation_control.on("geolocate", g => {
        console.log("OK:", g);
      });
      geolocation_control.on("error", err => {
        console.log("ERROR:", err); // [blocked] Access to geolocation was blocked over insecure connection to capacitor://localhost.
      });
```

Why does Capacitor's Geolocation API work differently in these two contexts?

**Comment by sebastianovide** [comment]
@ebellempire did you find a solution for this ?

**Comment by ebellempire** [comment]
> did you find a solution for this ?

Sorta. See: https://github.com/mapbox/mapbox-gl-js/issues/9680
