### ISSUE TITLE
bug: Plugins.Modals.confirm in electron doesnt awaits for response

### ISSUE THREAD

**Issue by LukaszGrela** [ionic-team/capacitor#2693]
# Bug Report
Following code run in React app with electron:
```
              onClick={async (): Promise<void> => {
                let confirmRet = await Plugins.Modals.confirm({
                  title: 'Confirm',
                  message: 'Are you sure you want to reset your changes?',
                });
                console.log('Confirm ret', confirmRet);
              }}
```
Yields to the `Confirm ret {value: false}` all the time, in the browser it works fine, returning correct value. The console prints this immediatelly, not waiting for user interaction with dialog.

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊 

Latest Dependencies:
  @capacitor/cli: 2.0.0
  @capacitor/core: 2.0.0
  @capacitor/android: 2.0.0
  @capacitor/electron: 2.0.0
  @capacitor/ios: 2.0.0

Installed Dependencies:
  @capacitor/android not installed
  @capacitor/ios not installed
  @capacitor/core 2.0.0
  @capacitor/electron 2.0.0
  @capacitor/cli 2.0.0

[success] electron looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [x] Electron
- [ ] Web

## Current Behavior

In the electron app the values from the confirm dialogue are not returned as the code doesnt "Await" for the response. The promise is imediatelly resolved as the Promise version shows:

```
                Plugins.Modals.confirm({
                  title: 'Confirm',
                  message: 'Are you sure you want to reset your changes?',
                }).then((result: ConfirmResult): void => {
                  console.log('Confirm ret', result);
                });
```

## Expected Behavior

Would work like in the web version, the response will be issued after user interacts with the confirm dialogue.

## Sample Code or Sample Application Repo

```
              onClick={async (): Promise<void> => {
                let confirmRet = await Plugins.Modals.confirm({
                  title: 'Confirm',
                  message: 'Are you sure you want to reset your changes?',
                });
                console.log('Confirm ret', confirmRet);
              }}
```
or
```
              onClick={ (): void => {
                Plugins.Modals.confirm({
                  title: 'Confirm',
                  message: 'Are you sure you want to reset your changes?',
                }).then((result: ConfirmResult): void => {
                  console.log('Confirm ret', result);
                });
              }}
```

## Other Technical Details

`npm --version` output:
`6.14.3`
`node --version` output:
`v8.10.0`

**Comment by jcesarmobile** [comment]
Electron’s dialog changed on electron 6, our code should be changed to use the sync version or change current one to be used in the promisified way
