### ISSUE TITLE
bug: Testing with Karma returns "StatusBar does not have web implementation."

### ISSUE THREAD

**Issue by smelzer** [ionic-team/capacitor#2696]
# Bug Report

## Capacitor Version
Latest Dependencies:
  @capacitor/cli: 2.0.0
  @capacitor/core: 2.0.0
  @capacitor/android: 2.0.0
  @capacitor/ios: 2.0.0
Installed Dependencies:
  @capacitor/cli 1.2.1
  @capacitor/core 1.2.1
  @capacitor/android 1.2.1
  @capacitor/ios 1.2.1

## Affected Platform(s)
- [ ] Android
- [ ] iOS
- [ ] Electron
- [ X] Web

## Ionic Version
4.12.0

## Angular Version
Angular CLI: 7.3.9
Node: 10.16.3
OS: darwin x64
Angular: 7.2.15
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

## Current Behavior
I am trying to execute the out of the box app.component Karma test for app.component:
`  it('should initialize the app', async () => {
    TestBed.createComponent(AppComponent);
    expect(platformSpy.ready).toHaveBeenCalled();
    await platformReadySpy;
    expect(statusBarSpy.setStyle).toHaveBeenCalled();
  });`

and I am getting:
Error: Uncaught (in promise): StatusBar does not have web implementation.
    at resolvePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:831:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:741:1
    at rejected (http://localhost:9876/_karma_webpack_/webpack:/node_modules/tslib/tslib.es6.js:71:88)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)

The difference is I am using the Capacitor plugins for StatusBar and SplashScreen and not the Ionic ones:
`const { SplashScreen, StatusBar } = Plugins;
`
The app works fine in the browser when it is run through ng serve and reports no errors related to the Status Bar or Splash Screen in the console.

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Can you provide a sample app? I have no idea about karma.
But web doesn’t have a status bar plugin implemented, so the error makes sense, not sure why it doesn’t appear when running with serve

**Comment by smelzer** [comment]
Nevermind.  You can close this.  I set up my test spy wrong and we not properly stubbing out the StatusBar.  Very sorry to waste your time.

**Comment by anilsam90** [comment]
@smelzer I am having the same problem. How did you stub the StatusBar?

**Comment by gklasen** [comment]
Same here. It is not even part of https://github.com/ionic-team/capacitor/tree/master/core/src/web so there is nothing to resolve?

**Comment by smelzer** [comment]
I never did solve the issue, I just removed the tests.

**Comment by robingenz** [comment]
You can do it this way, for example:

```
import { Plugins } from '@capacitor/core';

Plugins.StatusBar = jasmine.createSpyObj('StatusBar', ['setStyle', 'setBackgroundColor']);

expect(Plugins.StatusBar.setStyle).toHaveBeenCalledTimes(1);
expect(Plugins.StatusBar.setBackgroundColor).toHaveBeenCalledTimes(1);
```

**Comment by danielzen** [comment]
You must refer to the plugins directly from the Plugins object. i.e.:
```
Plugins.StatusBar.setStyle({style: StatusBarStyle.Light})
```

Because, unfortunately, if you do this:
```
const {StatusBar} = Plugins;

StatusBar.StatusBar.setStyle({style: StatusBarStyle.Light})
```

You will get `Error: Expected spy SplashScreen.setStyle  to have been called`. It took me way too long to learn this.

**Comment by erikkemperman** [comment]
@danielzen And can I ask how you then created the spy?

**Comment by danielzen** [comment]
@erikkemperman Sorry, just seeing this, but I do have code for you, hope it is helpful:

```
import { Plugins } from '@capacitor/core';

describe('AppComponent', () => {
  let platformSpy;

 beforeEach(async(() => {
    Plugins.SplashScreen = createSpyObj('SplashScreen', ['hide']);
    Plugins.StatusBar = createSpyObj('StatusBar', ['setStyle']);
    platformSpy = jasmine.createSpyObj('Platform', {ready: Promise.resolve()});

    TestBed.configureTestingModule({
      providers: [
        {provide: Platform, useValue: platformSpy},
...
}
```

and 

```
  it('should initialize the app', fakeAsync(() => {
    TestBed.createComponent(AppComponent);
    expect(platformSpy.ready).toHaveBeenCalled();
    tick() // await platformReadySpy;
    expect(Plugins.SplashScreen.hide).toHaveBeenCalled();
    expect(Plugins.StatusBar.setStyle).toHaveBeenCalled();
  }
```

**Comment by jstienne** [comment]
@danielzen Thanks for the code. Your code is for a plugin already existing in capacitor, but is it working for our own plugin ? Because I need to spy my own plugin, by I can't succeed it with your method.

I added the import like this: 
```
import { Plugins } from '@capacitor/core';
```

I also added the spy:
```
Plugins.MyPlugin = jasmine.createSpyObj('MyPlugin',
    [ 'myFirstMethod', 'mySecondMethod' ]);
```

And finally I want to check that my method was called: 
```
expect(Plugins.MyPlugin.myFirstMethod).toHaveBeenCalled();
```

I have logs in the method when it's not mocked, and the logs appears when I launch my test, so the spy is not well, but I don't understand why.

Thanks in advance !

**Comment by danielzen** [comment]
@jstienne Not sure how to help you. The `createSpyObj` method creates a mock object. Perhaps you have to find a way to inject the modified Plugins object with the new MyPlugin property? 

I am not coding my own plugin so haven't encountered your problem yet.
