### ISSUE TITLE
bug: not work requestPermissions() at Motion in iOS13+

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/capacitor#2697]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.0.0

  @capacitor/core: 2.0.0

  @capacitor/android: 2.0.0

  @capacitor/electron: 2.0.0

  @capacitor/ios: 2.0.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/electron not installed


  @capacitor/cli 2.0.0

  @capacitor/core 2.0.0

  @capacitor/ios 2.0.0

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Motion Plugin don't work in iOS13+, because requestPermissions() is not work.

## Expected Behavior

requestPermissions() can work and Motion Plugin work in iOS13+.

## Sample Code or Sample Application Repo
```typescript
  async watchAccel() {
    Plugins.Motion.requestPermissions().then(requestState => {
      const motionListener = Plugins.Motion.addListener('accel', (accel: MotionEventResult) => {
        console.log(accel);
      });
      const gyroListener = Plugins.Motion.addListener('orientation', (gyro: MotionOrientationEventResult) => {
        console.log(gyro);
      });
    }).catch(error => console.log('requestPermission error'));
  }
```

iOS13+ require `DeviceOrientationEvent.requestPermission()`.

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
See https://github.com/ionic-team/capacitor/issues/2054

Also, requestPermissions is really an android thing, it’s not implemented in the other platforms and motion is pure web plugin
