### ISSUE TITLE
Error: "Parent folder doesn't exist" when using FileSystem.Write   in  Ios

### ISSUE THREAD

**Issue by manisi** [ionic-team/capacitor#2699]
Latest Dependencies:

  @capacitor/cli: 2.0.0

  @capacitor/core: 2.0.0

  @capacitor/android: 2.0.0

  @capacitor/electron: 2.0.0

  @capacitor/ios: 2.0.0

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.0.0

  @capacitor/android 2.0.0

  @capacitor/ios 2.0.0-beta.1

  @capacitor/core 2.0.0

[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

**Comment by jcesarmobile** [comment]
Update to 2.0.0, it was fixed before the final release, you are using the beta.

**Comment by manisi** [comment]
Hi,
thats OK.
THanks

**Comment by manisi** [comment]
> Update to 2.0.0, it was fixed before the final release, you are using the beta.

Hi, thats OK Thanks
