### ISSUE TITLE
[cordova-android] webView.getView() returns null

### ISSUE THREAD

**Issue by wf9a5m75** [ionic-team/capacitor#270]
`webView.getView()` should return the view of the webview.

```java
  @Override
  public void initialize(final CordovaInterface cordova, final CordovaWebView webView) {
    super.initialize(cordova, webView);

    View view = webView.getView();  <-- this method returns null always

    Log.d(TAG, "--->view = " + view);
  }
```

**Comment by jcesarmobile** [comment]
You are not using latest version, I already fixed this
https://github.com/ionic-team/capacitor/pull/238

**Comment by wf9a5m75** [comment]
I installed the packages 30 minutes ago.

**Comment by wf9a5m75** [comment]
OK, please tell me how to install the `latest version` always `without npm install`. Because capacitor is very unstable, and the code changes quickly, and undocumented so much.

**Comment by jcesarmobile** [comment]
Arg, with the Alpha we bumped the version to 1.0.0, but in the build.gradle we still have `implementation 'ionic-team:capacitor-android:0.0.+'`, so it's not getting latest android files.

Please, change 0.0.+ to 1.0.0-alpha.7 and sync gradle to get latest Android code.

**Comment by wf9a5m75** [comment]
ok

**Comment by wf9a5m75** [comment]
Thanks. That worked.

**Comment by mlynch** [comment]
@wf9a5m75 the project is currently in alpha and is not stable. You are helping test/improve Capacitor so we can reach a stable, production ready point in the coming weeks/months.

**Comment by wf9a5m75** [comment]
@mlynch I decided `cordova-plugin-googlemaps` won't support the Capacitor. It means `@ionic-native/google-maps` won't work in the Capacitor.

**Comment by mlynch** [comment]
Okay, appreciate the feedback. Hope you change your mind in the future once this project is in production.
