### ISSUE TITLE
bug: pushNotificationActionPerformed not fired

### ISSUE THREAD

**Issue by tebantebanteban** [ionic-team/capacitor#2701]
# Bug Report

```
 @capacitor/cli: 2.0.0
  @capacitor/core: 2.0.0
  @capacitor/android: 2.0.0
  @capacitor/electron: 2.0.0
  @capacitor/ios: 2.0.0
```

pushNotificationActionPerformed and pushNotificationReceived not fired on ios (Not tested on android yet) when  handled notification, someone with same problem?

registration fired perfect

**Comment by armanhadifatah** [comment]
for me it is working i use firebase Cloud Messaging 
did you register the notification like below 

 ```
PushNotifications.requestPermission().then(result => {
      if (result.granted) {
        // Register with Apple / Google to receive push via APNS/FCM
        PushNotifications.register();
      } else {
        // Show some error
      }
    });
```

**Comment by tebantebanteban** [comment]
Hi! thanks for your answer,

mi code looks like this

```
async ngOnInit() {
    

    PushNotifications.requestPermission().then( result => {
      if (result.granted) {
        // Register with Apple / Google to receive push via APNS/FCM
        PushNotifications.register()
      } else {

      }
    });

    PushNotifications.addListener('registration',
      (token: PushNotificationToken) => {
        console.log(token.value);
      }
    );  

    PushNotifications.addListener('pushNotificationActionPerformed',
      (notification: PushNotificationActionPerformed) => {
        alert('Push action performed: ' + JSON.stringify(notification));
      } 
    );
}
```

I'm using firebase cloud messaging too and pushNotificationActionPerformed never fired

**Comment by armanhadifatah** [comment]
for ios you should do alot of setting for in xcode and also on your apple developer account 

for example in Xcode you in `Signing & Capabilities` you should add push notifications.
in firebase  **console setting -> could messing**  you should add APNs certificate
and also add GoogleService-Info.plist to your Xcode project but do not copy the file in Xcode you should choose file and add file from there...

**Comment by tebantebanteban** [comment]
I have followed all the steps outlined in the documentation and I receive notifications correctly, the problem occurs when I want to take an action when opening the notification

**Comment by jcesarmobile** [comment]
Capacitor uses APNS, how are you using FCM? with some plugin? Custom implementation? Looks like you (or a plugin) are overriding capacitor’s Notification handler

**Comment by tebantebanteban** [comment]
Hello! No, before I started implementing Capacitor Push, I had OneSignal implemented, but I have removed all traces of that plugin. Now the register works perfectly and throws me the corresponding Token, but I cannot receive the notifications 😩😩😩😩 y need to implement capacitor-fm for refresh tokens?

**Comment by tebantebanteban** [comment]
Finally, I have completely removed the capacitor ios app, ran the npx cap add ios command again and the notifications work without problem. Thank you very much for your intention to help!
