### ISSUE TITLE
bug: capacitor on android No listeners found for event

### ISSUE THREAD

**Issue by armanhadifatah** [ionic-team/capacitor#2703]
# Bug Report

I created capacitor plugin on android for firebaseDynamicLink from the plugin in ts file i can fire a method for example `this.firebaseDynamicLinkPlugin.echo({'value':'got it'};` but when i try to add listener on my plugin.java class like below :

` notifyListeners(EVENT_FIREBASE_DYNAMIC_LINK, ret,true);`

i get error in log when using it 
```
Notifying listeners for event onOpenWithDynamicLink
No listeners found for event onOpenWithDynamicLink
```

## Capacitor Version
Installed Dependencies:
```
  @capacitor/cli 2.0.0

  @capacitor/core 2.0.0

  @capacitor/android 2.0.0

  @capacitor/ios 2.0.0

  @capacitor/electron 1.4.0
```

## Affected Platform(s)
Android 

## Current Behavior
not returning event value 

## Expected Behavior
should return event value when listen to in my app.component.ts
```
 FirebaseDynamicLink.addListener('onOpenWithDynamicLink',(value)=>{
      let deeplink = value.deeplink;
      console.log(deeplink);
     this.parsDynamicLink(deeplink);
    });
```

**Comment by jcesarmobile** [comment]
Can you provide a sample app using your custom plugin?

**Comment by armanhadifatah** [comment]
**I didn't change a lot on android so this is my MainActivity**

p```
ackage com.codex.khanoo;

import android.net.Uri;
import android.os.Bundle;
import android.util.Log;

import androidx.annotation.NonNull;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.dynamiclinks.FirebaseDynamicLinks;
import com.google.firebase.dynamiclinks.PendingDynamicLinkData;

import java.util.ArrayList;

public class MainActivity extends BridgeActivity {
  FirebaseDynamicLink firebaseDynamicLink = new FirebaseDynamicLink();
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
       add(FirebaseDynamicLink.class);
    }});

    this.checkForDynamicLink();
  }

  @Override
  public void onStart() {
    super.onStart();
    this.checkForDynamicLink();
  }


  private void checkForDynamicLink() {
    FirebaseDynamicLinks.getInstance()
            .getDynamicLink(getIntent())
            .addOnSuccessListener(this, new OnSuccessListener<PendingDynamicLinkData>() {

              @Override
              public void onSuccess(PendingDynamicLinkData pendingDynamicLinkData) {

                // Get deep link from result (may be null if no link is found)
                Uri deepLink = null;
                if (pendingDynamicLinkData != null) {
                  deepLink = pendingDynamicLinkData.getLink();
                }

                if(deepLink != null){
                  Log.i("message","my dynamic link:\n"+deepLink.toString());
                  firebaseDynamicLink.sendDynamicLink(deepLink.toString());
                }
              }
            })
            .addOnFailureListener(this, new OnFailureListener() {
              @Override
              public void onFailure(@NonNull Exception e) {
                Log.i("message", "getDynamicLink:onFailure", e);
              }
            });
  }
}

```


**This is my plugin file FirebaseDynamicLink.java**
```

package com.codex.khanoo;


import android.app.NotificationManager;
import android.content.Context;
import android.util.Log;

import com.getcapacitor.Bridge;
import com.getcapacitor.JSObject;
import com.getcapacitor.NativePlugin;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.plugin.notification.NotificationChannelManager;

@NativePlugin()
public class FirebaseDynamicLink extends Plugin {

    private static final String EVENT_FIREBASE_DYNAMIC_LINK = "onOpenWithDynamicLink";

    @PluginMethod()
    public void getData(PluginCall call) {
        String value = call.getString("value");
        Log.i("welcome","good "+value);

        JSObject ret = new JSObject();
        ret.put("value", value);
        call.resolve(ret);
    }

//    Send data to my plugin
    public void sendDynamicLink(String url) {
        JSObject ret = new JSObject();
        ret.put("deeplink", url);
       Log.i("deeplink",url);
        notifyListeners(EVENT_FIREBASE_DYNAMIC_LINK, ret,true);
    }
}
```


**This is my ngOnInit()**
```

 async ngOnInit() {
    this.firebasePush();
    // this.listenToDynamicLink()
    this.initDarkMode();
    this.checkUpdate();
    // this.parsDynamicLink('ss');
    FirebaseDynamicLink.addListener('onOpenWithDynamicLink',(value)=>{
      let deeplink = value.deeplink;
      console.log(deeplink);
     this.parsDynamicLink(deeplink);
    });
    FirebaseDynamicLink.getData({'value':"arman"}).then(value => {
      console.log(value);
    });
  }
```

My problem is just with **onOpenWithDynamicLink**

**Comment by jcesarmobile** [comment]
Please, provide a sample app I can clone and run

**Comment by armanhadifatah** [comment]
Please check this which i just created 

https://github.com/armanhadifatah/capacitorTest

**Comment by jcesarmobile** [comment]
You are creating a new instance of the plugin in the MainActivity.java, but the event was retained on the plugin Capacitor created, so that's why it doesn't get fired.
Instead of creating a new plugin instance, use the one created by Capacitor like this:
```
PluginHandle appHandle = this.bridge.getPlugin("FirebaseDynamicLink");
FirebaseDynamicLink firebaseDynamicLink = (FirebaseDynamicLink) appHandle.getInstance();
```

**Comment by armanhadifatah** [comment]
thank you very much , but it is good to add that to documentation or to add
a very simple but complete example of how to do those things i think it
will help a lot of developer link me which i am angular developer not
android.

**Comment by Andriah91** [comment]
i have a same issue using capacitor 3. if some one can give an example. Thanks
