### ISSUE TITLE
bug: App Crashes launching Camera Plugin (Capacitor v2.0.0)

### ISSUE THREAD

**Issue by nereolopez** [ionic-team/capacitor#2712]
# Bug Report

## Capacitor Version
`npx cap doctor` output:
Latest Dependencies:
  @capacitor/cli: 2.0.0
  @capacitor/core: 2.0.0
  @capacitor/android: 2.0.0
  @capacitor/electron: 2.0.0
  @capacitor/ios: 2.0.0

Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/electron not installed
  @capacitor/cli 2.0.0
  @capacitor/core 2.0.0
  @capacitor/android 2.0.0
[success] Android looking great! 👌

## Affected Platform(s)
- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Going back to a project where the Camera Plugin was working, I upgraded Capacitor to v2. The plugin works correctly on the Browser, but when testing the app on the Android emulator, when launching the Camera, the emulator crashes and closes.

## Expected Behavior
The camera should open correctly.

## Sample Code or Sample Application Repo
I started an application from 0 (I am using Angular and Capacitor) in case it was related to mismatch of dependencies' versions. In this new app I only have this and still facing the same behavior as described above:

AppComponent Template
```html
<button (click)="takePicture()">Take Picture</button>
<img [src]="photo" *ngIf="photo">
```

AppComponent
```ts
import { Component } from '@angular/core';

import { Plugins, CameraResultType } from '@capacitor/core';
import { SafeResourceUrl, DomSanitizer } from '@angular/platform-browser';
const { Camera } = Plugins;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  photo: SafeResourceUrl;

  constructor(private sanitizer: DomSanitizer) {  }

  async takePicture() {
    const image = await Camera.getPhoto({
      quality: 90,
      allowEditing: true,
      resultType: CameraResultType.DataUrl
    });
    
    this.photo = this.sanitizer.bypassSecurityTrustResourceUrl(image && (image.dataUrl));
  }
}
```
Package.json dependencies
```json
"dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@capacitor/android": "^2.0.0",
    "@capacitor/cli": "^2.0.0",
    "@capacitor/core": "^2.0.0",
    "@ionic/pwa-elements": "^1.5.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
```
## Reproduction Steps
1. Launch the app
2. Click on the Take Picture button
3. Select "Take Picture" on the Bottom Sheet
4. App Crashes and Emulator Closes

## Other Technical Details

`npm --version` output:
6.14.2

`node --version` output:
v12.13.0

## Other Information

--

**Comment by jcesarmobile** [comment]
can you provide a sample app?
what's the Android version of the emulator?
what's the crash message you get?

**Comment by nereolopez** [comment]
Thanks @jcesarmobile for your answer. 

I am using Android 9 API 28 and this is the trace of the emulator right after clicking on the Bottom Sheet  to select if Picture should come from the Gallery or from the Camera.
![image](https://user-images.githubusercontent.com/5878234/78668148-720ed600-78da-11ea-8681-ddc7784c7902.png)

I uploaded a [Github repo](https://github.com/nereolopez/capacitor-camera-bug-sample) with the code.

Thanks again!

**Comment by nereolopez** [comment]
I just created a new Emulator in case there were some restrictions with the Android API Level and Capacitor version, but I have a similar behavior with the Android Q API 29. In this case, when opening the Camera, the application closes, but not the emulator.

**Comment by jcesarmobile** [comment]
did you test your sample app? I can't reproduce and you didn't commit the android folder

**Comment by nereolopez** [comment]
... 
that question... 
As said, I deployed it in two different emulators with two different Android images, and also attached the output of Android Studio when the Emulator crashes... I don't discard the issue can be on my side, but that question with all the info I shared...
Anyway, I committed and pushed the `android` and `.gradle` folders. 
So I understand that you deployed it to the emulator and you cannot reproduce it? Which API level?

Once again, I appreciate your support :)

**Comment by jcesarmobile** [comment]
Well, I think it is a reasonable question since you didn't commit the android folder, and that makes me think you didn't add it, and if you didn't add it, you couldn't test it.
You said you have tested, but could be in a different app, not the sample app. 
I've tested on a real device with Android 9(SDK 28), and two emulators with Android 10 (SDK 29) and another one with SDK 25.

**Comment by nereolopez** [comment]
Thanks for the quick answer. It is strange to me because I tested it on actual devices and it works, but not in the emulators. 
I will grab another repo with a previous version of Capacitor (1.5.x) and check if maybe my environment just got corrupted?
Will update the thread tomorrow the latest. Thanks again!

**Comment by priyankpat** [comment]
How much memory is configured in your emulator? I've experienced crash with picture on devices with 2gb ram.

**Comment by nereolopez** [comment]
I tested both approaches with same exact result:
- Tested the Camera Plugin in another project using Capacitor 1.5.2 and the Camera crashes and the App closes
- Created a new Emulator with 3Gb of RAM, and tested, both the test app linked here and the one with Capacitor 1.5.2 and same result for both...

I don't know. I thought it was the upgrade to v2 as it was working for me before, but seems to be something on my environment as it works on the real device.
I am closing it @jcesarmobile. If I find the root cause, I will update the thread in case someone faces the same.

**Comment by seanharr11** [comment]
@nereolopez we are seeing this in production as well with Capacitor@1.5.2. Have you had any success in resolving?

1. It seems to occur without any rhyme or reason...sometimes the app recovers, other times it goes full white screen and closes.
2. It appears too happen more frequently in older devices (iPhone 8 happens about 3x more than iPhone X)
3. The same issue occurs on Capacitor 2.0.0

**Comment by nereolopez** [comment]
Hi @seanharr11,

I am only facing the issue with the Android emulator. Despite I created a new image and updated to Capacitor 2.x. I think it might be an issue of my environment as my colleagues do not face it. So far I am testing directly on a physical device using live reload to speed it up. 

I am not facing any issue on real devices so far.  Did you have it working in previous versions or is this your first version and fails?

**Comment by Aarbel** [comment]
@nereolopez @seanharr11 

Looks like this issue is a Camera plugin issue. Looks like a native problem with Android that "blocks" temporary the app when RAM is low. Rebooting the android device seems to solve the problem.

Have you found a way to make the Camera plugin stable ?

Cf https://github.com/apache/cordova-plugin-camera/issues/665

**Comment by nereolopez** [comment]
Hi @Aarbel, I haven't touched this since last year. I think I was directly testing against the real device. There are newer Capacitor versions since then. Maybe the latest one solves the issue? I haven't tried it myself.

**Comment by ebuyuran-m** [comment]
I can confirm this is happening now on Xiaomi red mi 5 plus Android 8.1.0

**Comment by Aarbel** [comment]
To resolve the issue, i force WebRtc image capture on Android devices, this problem is a really core thing on many android devices, i think Capacitor team should investigate more how to fix it / ask good fix from Android teams.
