### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by dungi** [ionic-team/capacitor#2715]
# Bug Report

## Capacitor Version 1.5.4

`npx cap doctor` output:

> 💊   Capacitor Doctor  💊 
> 
> Latest Dependencies:
> 
>   @capacitor/cli: 2.0.0
> 
>   @capacitor/core: 2.0.0
> 
>   @capacitor/android: 2.0.0
> 
>   @capacitor/ios: 2.0.0
> 
> Installed Dependencies:
> 
>   @capacitor/android not installed
> 
>   @capacitor/cli 1.5.2
> 
>   @capacitor/core 1.5.2
> 
>   @capacitor/ios 1.5.2

## Affected Platform(s)
- [ ] Android
- [x ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Website with Spotify iFrame Embedded. User goes into another page and swipes back. iFrame autoplays. 

## Expected Behavior
No autoplay. Not reproducible on simulator or when device is hanging on Xcode debugger. Happens every time on first start of the app, when user swipes back to the page where the iFrame is located. On first launch of the iFrame there is no iFrame, only when user swipes back to that page.

## Sample Code or Sample Application Repo
<iframe src="https://open.spotify.com/embed-podcast/episode/IDHERE" width="100%" height="232" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

## Reproduction Steps
Open page with iFrame included.
Click on an link and enter other page.
Swipe back to the last page.
iFrame autoplays.

**Comment by jcesarmobile** [comment]
Sorry but this doesn't look like a Capacitor issue, more like a WKWebView issue, report it to Apple.

**Comment by dungi** [comment]
If I use it without Capacitor there is no autoplay. So it must be something in Capacitor.

**Comment by dungi** [comment]
Currently I guess its something in the CAPBridge.swift, but don't know exactly what.

**Comment by dungi** [comment]
Please reopen this bug again.
