### ISSUE TITLE
bug:Capacitor 2.0.0 IOS plugin Use of Unresolved Identifier TmpViewController in CAPBridge.swift

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/capacitor#2716]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Capacitor 2.0.0

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Updating from 2.0.0-beta1 to 2.0.0, i cannot build my plugin capacitor-data-storage-sqlite, i got a Swift Compiler Error Use of Unresolved Identifier TmpViewController in CAPBridge.swift. I use XCode 11.4

## Expected Behavior

Should build the Plugin successfully
## Reproduction Steps

```
git clone https://github.com/jepiqueau/capacitor-data-storage-sqlite.git
npm i --save @capacitor/core@latest
npm i --save-dev  @capacitor/ios@latest
npm i --save-dev @capacitor/android@latest
npm run build
``` 
open the project in Xcode
build the project
## Other Technical Details

`npm --version` output:
6.14.4
`node --version` output:
12.14.1
`pod --version` output (iOS issues only):
1.9.1

**Comment by jcesarmobile** [comment]
do a `pod intall` inside ios folder and do a Product -> Clean Build Folder from Xcode before running
