### ISSUE TITLE
feat: [Android] Add iconColor to PushNotifications in capacitor.config.json

### ISSUE THREAD

**Issue by jcarignan** [ionic-team/capacitor#2720]
# Feature Request

## Describe the Feature Request
Now that we can change the small icon's color for LocalNotifications, can we get the same for PushNotifications? I use both so it looks weird that some of my notifications are colored and some aren't.

## Platform Support Requested

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
Add the "iconColor" key of plugins.PushNotifications in capacitor.config.json

## Describe Alternatives
Would love to know if there are

## Related Code
`"plugins": {`
`    "PushNotifications": {`
`        "smallIcon": "ic_notification",`
`        "iconColor": "#009FE3"// here`
`    },`
`    "LocalNotifications": {`
`        "smallIcon": "ic_notification",`
`        "iconColor": "#009FE3"`
`    }`
 `}`

## Additional Context
![Screenshot_20200407-135214](https://user-images.githubusercontent.com/1685432/78702869-48a07b00-78d7-11ea-92c7-073f5a8913e5.png)

**Comment by jcesarmobile** [comment]
Push notifications are displayed by the OS, not by Capacitor.
You can configure a default color like this `<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/your_color" />`, but not change it per notification [more info](https://firebase.google.com/docs/cloud-messaging/android/client)
