### ISSUE TITLE
bug: requests for local extension-less files fail

### ISSUE THREAD

**Issue by diachedelic** [ionic-team/capacitor#2725]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.0.0

  @capacitor/core: 2.0.0

  @capacitor/android: 2.0.0

  @capacitor/electron: 2.0.0

  @capacitor/ios: 2.0.0

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.0.0

  @capacitor/android 2.0.0

  @capacitor/ios 2.0.0

  @capacitor/core 2.0.0

[success] Android looking great! 👌
  Found 9 Capacitor plugins for ios:
    @mauron85/cordova-plugin-background-geolocation (3.1.0)
    capacitor-data-storage-sqlite (1.5.2-1)
    cordova-plugin-android-permissions (1.0.2)
    cordova-plugin-app-version (0.1.9)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-whitelist (1.3.4)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

In a Capacitor app under iOS, 

```javascript
fetch('capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/XXX/Documents/myfile')
```
resolves with the contents of `/index.html`, rather than the contents of `myfile`.

## Expected Behavior

I would expect to get the contents of `myfile`, (like how Capacitor behaves on Android)

## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.16.1

`pod --version` output (iOS issues only): 1.9.1

## Other Information

The code to blame is [here](https://github.com/ionic-team/capacitor/blob/e010a2833ae7077e869ef89af0d24432db503fb9/ios/Capacitor/Capacitor/CAPAssetHandler.swift#L17).

**Comment by diachedelic** [comment]
I just noticed that the webserver uses the file extension to set the `Content-Type` header - so it is understandable that file extensions would be required. However, it would still be nice for Android & iOS to have consistent behaviour in that regard.

**Comment by jcesarmobile** [comment]
what kind of extension-less files are you saving?

**Comment by diachedelic** [comment]
Audio, video and images - which I now realise is a bad idea, as the webserver on iOS requires file extensions to properly stream media, in addition to serving correct `Content-Type` headers.

Perhaps it should be an error to write an extension-less file to disk?

**Comment by jcesarmobile** [comment]
I think the change makes sense, so I've merged it, but yeah, not having extension on media files will cause other problems
