### ISSUE TITLE
[cordova-android] `<config-file target="AndroidManifest.xml" parent="/manifest/application">` is ignored

### ISSUE THREAD

**Issue by wf9a5m75** [ionic-team/capacitor#273]
The capacitor ignores this definition of the plugin.xml file.

```xml
<config-file target="AndroidManifest.xml" parent="/manifest/application">
    <meta-data
      android:name="com.google.android.geo.API_KEY"
      android:value="$API_KEY_FOR_ANDROID" />
    <!-- Google Play Services SDK -->
    <meta-data android:name="com.google.android.gms.version"
               android:value="@integer/google_play_services_version" />
</config-file>
```

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/ef954fa22b74434226acf8b9312b2ec34bfbb4e4/plugin.xml#L206-L213

-------

This is generated AndroidManifest.xml. As you can see, ` <meta-data       android:name="com.google.android.geo.API_KEY" />` is not existed in the file.

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="ionic.googlemaps.quickdemo">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale"
            android:name="ionic.googlemaps.quickdemo.MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/custom_url_scheme" />
            </intent-filter>

        </activity>

        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>
    </application>

    <!-- Permissions -->

    <uses-permission android:name="android.permission.INTERNET" />
    <!-- Camera, Photos -->
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <!-- Geolocation API -->
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />
    <!-- Network API -->
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>

```

**Comment by jcesarmobile** [comment]
In Capacitor, the native projects are not build artifacts and we are not doing any modification on them from the tooling, so this won't be implemented.
I'm working on displaying messages to tell the users they have to do it manually per this docs https://capacitor.ionicframework.com/docs/android/configuration/

**Comment by wf9a5m75** [comment]
Ok, in that case, please remove `@ionic-native/google-maps` plugin from `@ionic-native` immidiately, which is top class popular plugin.

**Comment by wf9a5m75** [comment]
Even current `@ionic-native/4.x`, right now.

**Comment by wf9a5m75** [comment]
If you guys don't implement the same installation as `Cordova`, you guys should not say `keep compatibility  with Cordova as much as possible`.
Because it's already lie.

I construe `as much as possible` is the capacitor keeps the same installation mechanism as cordova, but in the native side code are different implementation.

Because from the plugin developer, we can not do anything about the installation process.
(I don't prefer to use hook scripts)
In native side, I can adjust the code to accept the capacitor, but keeping the installation process as same as cordova is your role, not plugin's developer role, or even users role.

So if you won't implement it, I don't support `@ionic-native/google-maps` plugin as `cordova-googlemaps-plugin` developer.
It means I will refuse all questions, supports, and issues regarding of the capacitor. (Ask to max what happends in the past)

And I don't want to receive that claims in the future, so please remove the `@ionic-native/google-maps` soon.

**Comment by jcesarmobile** [comment]
ionic-native is a different project, please, report that you want your plugin removed on the ionic-native repo https://github.com/ionic-team/ionic-native/issues
