### ISSUE TITLE
incompatible cordova plugin: cordova.plugin.zoom

### ISSUE THREAD

**Issue by andysousa** [ionic-team/capacitor#2737]
Just a heads up that the corova zoom plugin that is listed on the ionic native docs is incompatible.

https://ionicframework.com/docs/native/zoom/

It doesn't build in ios or android with errors from the zoom sdk.  Someone from zoom confirmed it is incompatible with Capcaitor.

https://devforum.zoom.us/t/ionic-4-capacitor-build/12262

**Comment by jcesarmobile** [comment]
I've found this workarounds:

For iOS:
Disable bitcode for your app scheme (from Xcode on build settings search for `ENABLE_BITCODE` and change value to no)

Disable bitcode for Capacitor, CapacitorCordova and CapacitorPlugins by adding this in the Podfile and running `npx cap update ios`

```
# BITCODE bug fix
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```
For Android add this in the root `build.gradle` in the ->  `repositories` section that is inside `allprojects` section.

```
flatDir{
    dirs '../capacitor-cordova-android-plugins/src/main/libs/android'
}
```

**Comment by andysousa** [comment]
@jcesarmobile thanks for the tip! That got past the errors from the MobileRTC but now i am getting this error?

Have you seen this 

```
ld: '/Users/sousaan/Library/Developer/Xcode/DerivedData/App-clcapqxhskxtsrcohbkemmpurhvm/Build/Products/Debug-iphoneos/Capacitor/Capacitor.framework/Capacitor' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/sousaan/Library/Developer/Xcode/DerivedData/App-clcapqxhskxtsrcohbkemmpurhvm/Build/Products/Debug-iphoneos/Capacitor/Capacitor.framework/Capacitor' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jcesarmobile** [comment]
Doesn't look like you disabled bitcode properly, check the build settings for your app target and for the Pods targets and search for `ENABLE_BITCODE`, double check that every value is set to No

**Comment by andysousa** [comment]
hmm, it is definitely setting the flag correctly across all the targets. 

![image](https://user-images.githubusercontent.com/42151009/78922247-37d14000-7a64-11ea-8e46-5f46e730d330.png)

**Comment by andysousa** [comment]
ugh, you were right of course @jcesarmobile, wasn't set in my app target! Thanks as always for the help

**Comment by jcesarmobile** [comment]
and for your app target?

**Comment by sandyricardo** [comment]
Hi @jcesarmobile 
I am able to solve the integration error using your workaround.
But when i try to join a meeting, i get crash.

I am using xcode 11.4 and zoom said that they don't support xcode 11 yet
https://devforum.zoom.us/t/swift-sdk-crash-on-join-meeting-and-error-150-when-i-try-to-create-a-meeting/6278

Do you have any workaround on this?
