### ISSUE TITLE
feat: Support font sizes from accessibility settings in ios

### ISSUE THREAD

**Issue by MayKikuchiThrive** [ionic-team/capacitor#2748]
# Feature Request

## Describe the Feature Request
ios apps do not support preferred font sizes set though Settings > Accessibility by default. Support for adjustable font sizes is requested. 

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Add support for ios adjustable font size, perhaps as a function in the Accessibility API

## Describe Alternatives

Allow pinch-to-zoom in android and ios

**Comment by mhartington** [comment]
Are you using Ionic? If so, this is an issue with the framework, not capacitor.

**Comment by jcesarmobile** [comment]
It's unclear if you use Ionic, so not sure if it might be an Ionic issue, but definitely not a Capacitor issue or feature request.
Capacitor apps use a WebView, so the accessibility should be handled by the app developer, i.e, by using `font: -apple-system-body` on the texts you want to resize based on the adjustable font size.

More information about `font: -apple-system-body` on https://webkit.org/blog/3709/using-the-system-font-in-web-content/
