### ISSUE TITLE
feat: Network Interface

### ISSUE THREAD

**Issue by ruudboon** [ionic-team/capacitor#2754]
# Feature Request

## Describe the Feature Request
A component to show the available network interfaces and ip configuration

## Platform Support Requested
- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Describe Preferred Solution
Create new plugin like https://ionicframework.com/docs/native/network-interface

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
