### ISSUE TITLE
feat: ICMP handeling

### ISSUE THREAD

**Issue by ruudboon** [ionic-team/capacitor#2755]
# Feature Request

## Describe the Feature Request
A plugin to allow sending ICMP packets (ping)

## Platform Support Requested
- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Describe Preferred Solution
Create a new plugin

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
