### ISSUE TITLE
feat: Contact Tracing on Capacitor

### ISSUE THREAD

**Issue by cmorillo** [ionic-team/capacitor#2760]
# Feature Request
Contact Tracing integration for Capacitor
## Describe the Feature Request

Apple and Google are creating a common API for contact tracing (https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ContactTracing-FrameworkDocumentation.pdf) would it be possible to create a plugin to integrate this when they release?
## Platform Support Requested

- [X] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Just a plugin to integrate the native API for this.

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for 👍 reactions to gauge interest.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/13. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
