### ISSUE TITLE
feat: Ability to rename capacitor project

### ISSUE THREAD

**Issue by mesqueeb** [ionic-team/capacitor#2761]
# Feature Request

## Describe the Feature Request
I want to, just as any developer, be able to rename my XCode project, so it shows up with a different name than "App" on iOS.

I succeeded by renaming by doing as said on SO here:
https://stackoverflow.com/a/60375182/2697506

But the thing is, if you rename the project like that, when trying to update capacitor related packages/pods, there's often errors saying that it can't find `App.xcodeproj`...

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

I would really love a method to be able to rename a Capacitor iOS project more easier, without having to go through hoops and loops and rename it back to App every time I want to update things.

## Describe Alternatives

The only alternative is to switch back and forward between your preferred name and "App".

**Comment by jcesarmobile** [comment]
see my answer on the link you provided
https://stackoverflow.com/a/57097066/1351469
rename the target and not the project

**Comment by mesqueeb** [comment]
@jcesarmobile Thank you very much. What do you mean by this part of your answer:

> But if you add new targets, or rename the existing one, you have to also modify the Podfile to add the new targets or to rename the current target accordingly.

Is there any guide you could provide on how we can do this? Sorry, I'm not super familiar with pods and podfiles 😅

**Comment by jcesarmobile** [comment]
The Podfile has an ‘App’ target

https://github.com/ionic-team/capacitor/blob/master/ios-template/App/Podfile#L16

If you rename the target you have to change App with the new target name, or if you add a new target you have to duplicate that block

**Comment by dwieeb** [comment]
Related: https://github.com/ionic-team/capacitor/issues/2848
