### ISSUE TITLE
bug: FileProvider update documentation missing from Upgrade instructions

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor#2762]
# Bug Report

## Capacitor Version
2.x

This page:
https://capacitor.ionicframework.com/docs/android/updating/

## Affected Platform(s)

- [ X ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Assuming all other upgrade steps from 1.5.x to 2.x have been followed, and the project builds successfully.

The current instructions for updating Capacitor Android 1.5.x -> 2.0.x omits the need to change the following section in AndroidManifest.xml:
````
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>
````

should be:

````
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>
```` 

Note, this error will only occur until permissions have been granted.

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
the `Refactor -> Migrate to AndroidX` should handle that, did you follow that step?

**Comment by lincolnthree** [comment]
Yes, I did.

**Comment by lincolnthree** [comment]
I'll try running it again.

**Comment by lincolnthree** [comment]
Interesting. I think I did not see the "Do refactor" button at the bottom of intelliJ. Looks like I missed that step previously, as I assumed the output had already made the changes. But this makes sense. Thanks. False alarm.

**Comment by lincolnthree** [comment]
(If it weren't clear, that did successfully update the AndroidManifest.xml file)

**Comment by jcesarmobile** [comment]
yeah, happened to me the first time too, the "Do refactor" is a bit hidden.
