### ISSUE TITLE
bug: iOS Keyboard hides input when "resize" is set to "none"

### ISSUE THREAD

**Issue by gbresciano** [ionic-team/capacitor#2770]
# Bug Report

## Capacitor Version

`npx cap doctor`

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Expected Behavior

When the input is blocked as the virtual keyboard comes up, the screen should move (without resizing) to make it visible, as happens on safari.

## Sample Code or Sample Application Repo

This could be avoided by not removing the `UIKeyboardWillHideNotification` and `UIKeyboardWillChangeFrameNotification` observators  on `Keyboard.m` if "resize" is set to "none"

https://github.com/ionic-team/capacitor/blob/ee5e2837d6f626d0ccc830ee6cf65727a996b72e/ios/Capacitor/Capacitor/Plugins/Keyboard.m#L92

https://github.com/ionic-team/capacitor/blob/ee5e2837d6f626d0ccc830ee6cf65727a996b72e/ios/Capacitor/Capacitor/Plugins/Keyboard.m#L94

## Reproduction Steps

Set `"resize": "none"` in the Keyboard plugin settings and try to write in an input that is fixed near the bottom of the screen.

## Other Technical Details

`npm --version`  6.9.0

`node --version` v10.16.0

`pod --version` 1.9.1

## Other Information

iOS: 13.4

**Comment by jcesarmobile** [comment]
This is not a bug, that's the expected behavior of none.

You can use the keyboard events to position your input field so it's visible.

**Comment by gbresciano** [comment]
Hi @jcesarmobile,

I tried using `scrollIntoView()` for the input, but it doesn't work because it's fixed. The regular safari solution is to shift the whole view without resizing.

Do you think this can be done with the current API?

Thanks

**Comment by christianhengst** [comment]
Yes! Please add a setting for this! It should be quite easy to implement and reduces a lot of trouble with shifting inputs into view...
