### ISSUE TITLE
bug: cap sync android destroyes project if opened

### ISSUE THREAD

**Issue by FSDRE** [ionic-team/capacitor#2771]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Latest Dependencies:
  @capacitor/cli: 2.0.1
  @capacitor/core: 2.0.1
  @capacitor/android: 2.0.1
  @capacitor/electron: 2.0.1
  @capacitor/ios: 2.0.1

Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/electron not installed
  @capacitor/cli 2.0.0
  @capacitor/core 2.0.0
  @capacitor/android 2.0.0

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

If you run (or accidentally run) `cap sync android` and you have the project open in Android Studio at the same time, the sync completes. But if you close and open Android Studio again, the project dependencies are completely messed up and the project does not build anymore. The build process adds a new `android-capacitor-cordova-android-plugins` module and neglects the old `capacitor-cordova-android-plugins` module.

## Expected Behavior

The opened project should not get rendered unusable when `cap sync android` is called while the project is open in Android Studio. I don't know if there is even a solution due to the fact that Android Studio caches some files. Interestingly enough the errors only pop up after a restart of Android Studio when the project files are loaded in from scratch.

Fact is, sometimes you just forget to close Android Studio when you run npm scripts. But everytime you need to delete the entire `.idea` folder in order to get the project working again. And since the `.idea` folder is not included into source control, you cannot just do a quick discard on the git changes.

## Reproduction Steps

* Make capacitor project (e.g. Angular)
* `cap add android`
* Open project in Android Studio and let it finish the initial build
* Make changes to the angular app so there are changes
* `cap sync android` while Android Studio is open

**Comment by doup** [comment]
I think I'm having the same issue. I'm adding the error here so it's easier to search for it:
```
Unsupported Modules Detected: Compilation is not supported for following modules: capacitor-cordova-android-plugins, android-capacitor-cordova-android-plugins. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project
```

**Comment by FSDRE** [comment]
Yup, that's the error message, I can confirm. forgot to add it, sry...

**Comment by vvche69** [comment]
Moreover, it destroys the project even when Android Studio is closed.
Each subsequent run of "cap sync android" adds a new module with names like "projectname>-<projectname>-android-capacitor-cordova-android-plugins" and so on.

By the way, as a temporary workaround  you don't need to delete the entire .idea folder. Just delete  modules.xml file and reopen Android Studio.   (Anyway, it's quite annoying...)

**Comment by FSDRE** [comment]
@vvche69 I cannot confirm that it happens on every `cap sync android` but in the meantime I also had random occurances where the project was destroyed even if Android Studio was closed. I cannot pinpoint what causes it, though.

**Comment by doup** [comment]
To avoid the hastle for now I was removing the `.idea` folder each time I open Android Studio via a NPM task: `"android:dev": "rm -rf android/.idea && npm run build && npx cap sync android && npx cap open android"`.

I'll try just removing `modules.xml`. Thanks! 👍

**Comment by jcesarmobile** [comment]
I've not seen this happen for a long time in my projects, so probably google fixed it in Android Studio, make sure you are using latest version

**Comment by FSDRE** [comment]
I can confirm this does not happen anymore. Kinda forgot about the open issue... that's a good sign that it works.
