### ISSUE TITLE
Camera plugin does not work anymore on web plattform (pwa)

### ISSUE THREAD

**Issue by waterkamp** [ionic-team/capacitor#2775]
# Bug Report

## Capacitor Version
`npx cap doctor` output:
 @capacitor/android not installed
  @capacitor/ios not installed
  @capacitor/electron not installed
  @capacitor/core 2.0.1
  @capacitor/cli 2.0.1

## Affected Platform(s)
- [ ] Android
- [ ] iOS
- [ ] Electron
- [ X] Web

## Current Behavior
Calling the getPhoto() method ends up in following error:
`Requested device not found`

**Code example:**
const image = await Plugins.Camera.getPhoto({
      quality: 100,
      allowEditing: false,
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Camera
    }).catch(reason => {
      console.error('error while taking picture', reason);
    });

## Expected Behavior
The camera-UI for web (pwa) should appear provided by the @ionic/pwa-elements package.

## Sample Code or Sample Application Repo
[Sample camera app:](https://github.com/waterkamp/camera-test-app.git)

## Reproduction Steps

1. Just clone the repo above.
2. Start the app
3. Click on the camera-button once the app started
4. See the error in the console output of the browser

## Other Technical Details

Ionic:

   Ionic CLI                     : 5.4.6 (/Users/oliverwaterkamp/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.0 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina

**Comment by jcesarmobile** [comment]
I've run your sample app without problems. 
In which browser did you test?

**Comment by waterkamp** [comment]
I really don't understand it...
Suddenly it works everywhere again...
In my private project and also my sample app on github (I cloned it again and it worked!!!???)

I really don't know what the issue was on my machine...
It's magically gone in the same way as it came !!!???

Sorry for opening this bug and wasting your time.

But thanks for helping anyway.

Regards,
Oliver

**Comment by waterkamp** [comment]
As I wrote above...
It works again....maaaagic!!!
