### ISSUE TITLE
Documentation: Inaccurate documentation for Browser Plugin

### ISSUE THREAD

**Issue by pgerhard** [ionic-team/capacitor#2779]
The typescript documentation currently states that "Browser.close()" only works on iOS (https://github.com/ionic-team/capacitor/blob/master/core/src/core-plugin-definitions.ts#L249). However after trying it in the browser this also seems to work perfectly fine. Is the documentation out date or is it just a coincidence.
If it is outdated, I'd be happy to change it and create a PR.

**Comment by jcesarmobile** [comment]
yeah, docs were created when "web" platform didn't have Browser plugin implemented, and when it was implemented it wasn't documented, so a PR could be helpful.
