### ISSUE TITLE
bug: NPX cap sync ios does not update project bundle identifier

### ISSUE THREAD

**Issue by pgerhard** [ionic-team/capacitor#2782]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.0.1

  @capacitor/core 2.0.1

  @capacitor/ios 2.0.1

  @capacitor/android 2.0.1

[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I have added the iOS platform to my app and tried to execute it on a device. After setting up the development team, XCode notified me that the bundle identifier was not available and that I should change it. After changing it in the capacitor.config.json contained in the root of my project I:
1. Executed ionic build
2. Executed npx cap sync ios
3. Executed npx cap copy ios (this was probably redundant to sync)
4. Executed npx cap open ios

`ios/App/App/capacitor.config.json` has been correctly updated, however the `ios/App/App.xcodeproj/project.pbxproj` has not. Based on the document behaviour of npx cap sync ios I would have expected this.

## Expected Behavior

After executing `npx cap sync ios` the `ios/App/App.xcodeproj/project.pbxproj` is updated with the correct values from `ios/App/App/capacitor.config.json`

## Other Technical Details

`npm --version` output: 6.12.1

`node --version` output: v12.13.1

`pod --version` output (iOS issues only): 1.9.1

**Comment by jcesarmobile** [comment]
It's not a bug, it's the intended behavior, Capacitor doesn't modify user's projects after creation, once you create the project you can edit things in Xcode.

**Comment by mirko77** [comment]
@jcesarmobile  What is the point of `capacitor.config.js` then?

**Comment by ondokuzz** [comment]
i have the same problem and agree that ios/App/App.xcodeproj/project.pbxproj should have been updated from capacitor.config.json.
