### ISSUE TITLE
bug: Push Docs don't appear to be loading

### ISSUE THREAD

**Issue by acurrieclark** [ionic-team/capacitor#2790]
# Bug Report

The push documentation on the capacitor site doesn't seem to load correctly.

`SyntaxError: Unexpected end of JSON input` is thrown

https://capacitor.ionicframework.com/docs/apis/push-notifications/

**Comment by dotNetkow** [comment]
Hi Alex, can you try a hard refresh of the page to clear the cache? Seems ok over here.

**Comment by acurrieclark** [comment]
Hi Matt,
My apologies, I should have checked another browser before reporting. I am using the Brave browser, which has automatic tracker blocking built in. It doesn't like the `https://capacitor.ionicframework.com/assets/docs-content/apis/push-notifications/index.json` url, so blocked it. 

As you said, works perfectly well everywhere else. Thanks for the swift reply and apologies again.

**Comment by dotNetkow** [comment]
No apology needed! Thanks for letting us know about Brave - haven't heard of that blocking our docs. Very strange - as you can see, it's just the page's content in JSON format. Nothing fishy going on.  :)

**Comment by acurrieclark** [comment]
I would imagine it is as simple as the `push-notifications` part of the url. It causes problems with browser push notifications on lots of sites too. It's not particularly forgiving as blockers go!

**Comment by rebron** [comment]
Hi @acurrieclark Still an issue for you with Brave 1.13.82 our current release version? I couldn't reproduce on 1.13.82 and our current version in beta 1.14.x
