### ISSUE TITLE
feat: Add catalyst/desktop mode info to Device.getInfo

### ISSUE THREAD

**Issue by piotrblasiak** [ionic-team/capacitor#2792]
# Feature Request

## Describe the Feature Request
In xcode you can now target your app for desktop by using catalyst. Device.getInfo currently returns the model info but that is currently set to "iPad" for catalyst, and no other way of detecting if the app is being run on desktop.

## Platform Support Requested
- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
I suggest adding a "desktop" field or similar.
It is easy to do following this article (I've tried and verified it): https://www.hackingwithswift.com/example-code/catalyst/how-to-detect-your-ios-app-is-running-on-macos-catalyst

## Describe Alternatives
There are no other good ways of doing this that I know of.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.
