### ISSUE TITLE
Does SplashScreen plugin require Cordova Splashscreen plugin?

### ISSUE THREAD

**Issue by sertal70** [ionic-team/capacitor#2793]
Hi all,
I've followed instructions on Capacitor [documentation page](https://capacitor.ionicframework.com/docs/apis/splash-screen) to use SplashScreen on my app but when I run it on emulator (both Android and iOS) I get the console message:

```
Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.
Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen'
```

Since Capacitor documentations [says](https://capacitor.ionicframework.com/docs/apis) that Capacitor plugins replace Cordova plugins, I cannot understand the cause of these console message, can you please point me in the right direction to sort it out?

**Comment by tntwist** [comment]
Hi,

it seems that you call the cordova splashscreen plugin somewhere in your ionic app. Maybe you still have some references to the ionic native plugin for splashscreen:
https://ionicframework.com/docs/native/splash-screen

Cloud look like this:
```
import { SplashScreen } from '@ionic-native/splash-screen/ngx';

constructor(private splashScreen: SplashScreen) { }

...

this.splashScreen.show();

this.splashScreen.hide();
```

**Comment by jcesarmobile** [comment]
Yeah, some ionic templates still have cordova code, you have to remove it and replace it with the capacitor code.

**Comment by sertal70** [comment]
Hi @tntwist, thank you so much for your help! Indeed my `app.component.ts` was importing `@ionic-native` and referencing both Splashscreen and Statusbar plugins. The root cause is the Ionic CLI which creates the file when a new project is started even if you don't specify the `--cordova` option.

**Comment by tntwist** [comment]
Glad I could help you. 😄
