### ISSUE TITLE
Support Advertising Identifier in Device

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#28]
But only if they've enabled ad framework, such that it won't trigger a deny from Apple

**Comment by mlynch** [comment]
Will wait for interest from the community before adding this. Both iOS and Android can expose an advertising identifier. iOS support should be added in a way that doesn't explicitly force a link with your app, to avoid app store rejections

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
