### ISSUE TITLE
Example, `copy` script: Should clean `public` in projects before copying

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#280]
The `copy` script in the example project should probably clean `public` in the native projects before copying  `www` (and `native-bridge.js`) over to make sure no random files can influence the app (like a stray `cordova.js` being there).

**Comment by jcesarmobile** [comment]
he means the copy in package.json for the example app, `npx cap copy` do delete the public folder before copying

**Comment by janpio** [comment]
Exactly @jcesarmobile, @SonnyCampbell.

(Another option of course would be to somehow enable the CLI for the example, but that might have its own set of challenges and side effects - @jcesarmobile can probably explain why they didn't do that anyway)

**Comment by jcesarmobile** [comment]
we didn't do it because the example was mostly to work on the native parts, so the public folder was copied only the fist time

**Comment by SonnyCampbell** [comment]
Ok I can take a look at this, should be straightforward enough using `rimraf`. 

The one issue I did run into is that I believe `cp` is a Unix specific command, and throws a `'cp' is not recognized as an internal or external command` error on my windows machine. It should probably be changed to something that's system independent. There are two npm packages [copy-dir-cli](https://www.npmjs.com/package/copy-dir-cli) and [ncp](https://www.npmjs.com/package/ncp) that could be used to make it agnostic, however copy-dir-cli uses the `copy` command in the cli which would probably cause issues. Do you guys have any thoughts on this?

**Comment by jcesarmobile** [comment]
example project is gone now, so closing

**Comment by dwieeb** [comment]
For context, we are going to be building up this TestApp as we split out the plugins: https://github.com/ionic-team/capacitor-testapp
