### ISSUE TITLE
Build CommonJS instead of ES6

### ISSUE THREAD

**Issue by flogy** [ionic-team/capacitor#2807]
Hi all,

I am using Capacitor together with [Gatsby](https://github.com/gatsbyjs/gatsby). This works without any problems.

However, I have some trouble when using the [capacitor-fcm](https://github.com/stewwan/capacitor-fcm) and it seems that the module type of the build output is causing it, as it is ES6 and not CommonJS.

The plugin's source code looks like it was created with the [plugin-template](https://github.com/ionic-team/capacitor/blob/master/plugin-template/tsconfig.json) in this repository.

**So my questions are:**

1. What was the reason to decide to go with ES6 modules and not CommonJS? As far as I have seen most libraries seem to use CommonJS, probably to make it widely available.
2. Would it be a possibility to use CommonJS instead? I could create a PR to migrate the plugin template if this is an option.

Don't get me wrong. I am not very familiar with the JS standards and babel, etc. Maybe I just use it in a wrong way..?

Thanks in advance and keep up the great work!

**Comment by DimosthenisK** [comment]
I assume ES6 modules were chosen because capacitor is written in TS.

**Comment by flogy** [comment]
Thanks for your reply. I understand, but still it would be no problem to transpile TS to CommonJS and thus make it widely available without problems. Wouldn't this be a good idea?
