### ISSUE TITLE
Unclear Browser Plugin Document or Bug

### ISSUE THREAD

**Issue by pgerhard** [ionic-team/capacitor#2808]
I am building an Ionic app and implemented authentication via OAuth2 on an external OAuth2 authentication server. I want to display the authentication prompt using the Capacitor BrowserPlugin. 
However from the documentation it is unclear how to properly work with the available events.
I can see that the browserPageLoaded and browserFinished being fired when the window is closed. But I can not figure out how to add additional information to them
If I try to manually fire the event from the created page using
```
    function browserFinished() {
        console.log(`Firing Browser Finished`)
        let event = new CustomEvent('browserFinished', { detail: 'This is the content' });
        window.dispatchEvent(event);
        console.log(`Fired Browser Finished`)
    }
```
I do not see the event being registered back in the Ionic app. Is this a bug or am I not using the API correclty?

**Comment by jcesarmobile** [comment]
Please, when reporting issues don't delete the template and provide all the requested details.

Plugin events are not window events, and you can't add additional information to them.

**Comment by pgerhard** [comment]
I selected the "Custom issue template" from the list of available templates. This is a blank template so I did not remove any information.

If they are not window events, then what are they and how can I pass information from the opened browser window back to my app?

**Comment by jcesarmobile** [comment]
you can't

**Comment by pgerhard** [comment]
@jcesarmobile Ok, thats helpful to know. Is this by design? Otherwise I would create a new ticket allowing the extension to BrowserPlugin allowing either
* the modification of the information of the provided events
* attaching additional custom listeners

If this is by design it would be helpful to get some pointers on how the documented usage of "handle authentication flows..." should be implemented.
