### ISSUE TITLE
Xcode build bug OneSignal.h not found

### ISSUE THREAD

**Issue by pyummm** [ionic-team/capacitor#281]
'OneSignal/OneSignal.h' file not found
at
#import "OneSignal.h"

`/Volumes/hard/IOS/Savehere/capasitor/PremoveExpert/node_modules/@capacitor/cli/assets/capacitor-cordova-ios-plugins/sources/OnesignalCordovaPlugin/OneSignalPush.h:32:9: 'OneSignal/OneSignal.h' file not found`

/Volumes/hard/IOS/Savehere/capasitor/PremoveExpert/node_modules/@capacitor/cli/assets/capacitor-cordova-ios-plugins/sources/OnesignalCordovaPlugin/OneSignalPush.m:31:9: In file included from /Volumes/hard/IOS/Savehere/capasitor/PremoveExpert/node_modules/@capacitor/cli/assets/capacitor-cordova-ios-plugins/sources/OnesignalCordovaPlugin/OneSignalPush.m:31:

find OneSignal.h result:
/Users/macbook/IOS/Savehere/capasitor/PremoveExpert/platforms/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Versions/A/Headers/OneSignal.h
/Users/macbook/IOS/Savehere/capasitor/PremoveExpert/platforms/ios/Pods/Headers/Public/OneSignal/OneSignal/OneSignal.h
/Users/macbook/IOS/Savehere/capasitor/PremoveExpert/ios/App/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Versions/A/Headers/OneSignal.h

**Comment by janpio** [comment]
Which plugin exactly are you using, and which command did you run to install it?

**Comment by jcesarmobile** [comment]
It's probably `onesignal-cordova-plugin`, I was able to reproduce with it.

**Comment by pyummm** [comment]
npm install onesignal-cordova-plugin

**Comment by jcesarmobile** [comment]
Fixed in #290
