### ISSUE TITLE
I use the last version like，but also “ITMS-90809: Deprecated API Usage”

### ISSUE THREAD

**Issue by clotee** [ionic-team/capacitor#2811]
I use the last version like，but also “ITMS-90809: Deprecated API Usage”
![image](https://user-images.githubusercontent.com/11476395/79958596-b216b100-84b5-11ea-9fb2-8c6a29cd2b4b.png)
![image](https://user-images.githubusercontent.com/11476395/79958790-eee2a800-84b5-11ea-89c0-68e32d8d9a43.png)
![image](https://user-images.githubusercontent.com/11476395/79958891-0588ff00-84b6-11ea-874a-773f3d389a81.png)

**Comment by jcesarmobile** [comment]
Apple looks for UIWebView usage, not for UIWebView string, your problem is probably some plugin using it in a frameworks, so you can't find it in a text search.
Check that your cordova plugins are updated, the ones that usually have problems are google analytics, fcm, facebook, linkedin.
