### ISSUE TITLE
bug: Unable to launch Android because dependency missed

### ISSUE THREAD

**Issue by ElRochito** [ionic-team/capacitor#2814]
# Bug Report

## Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.0.1
  @capacitor/core: 2.0.1
  @capacitor/android: 2.0.1
  @capacitor/electron: 2.0.1
  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/electron not installed
  @capacitor/cli 2.0.1
  @capacitor/core 2.0.1
  @capacitor/android 2.0.1
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
When opening android project on Android Studio and I do a build, I've got multiple errors.

![image](https://user-images.githubusercontent.com/1737307/79994619-7fb98380-84b6-11ea-9592-da051d10687a.png)

## Expected Behavior
App can be launch on Android :)

## Reproduction Steps

```
ionic start hello-world-with-local-notification tabs --capacitor
npm install cordova-plugin-local-notification
npm install @ionic-native/local-notifications
ionic cap sync
npx cap add android
ionic capacitor build android

```

**Comment by nikmartin** [comment]
Somewhat related, did you know capacitor has a native Local Notifications plugin? No need for cordova or ionic-native plugins: https://capacitor.ionicframework.com/docs/apis/local-notifications

**Comment by ElRochito** [comment]
Indeed !! :) Sorry

**Comment by jcesarmobile** [comment]
Anyway, the problem is that plugin is not updated for AndroidX, but Capacitor uses AndroidX, so you can use jetifier to patch it or use Capacitor plugin

**Comment by ElRochito** [comment]
Thank you! 
I try the `Refactor -> Migrate to Android X` but some packages are not well replaced
