### ISSUE TITLE
Filesystem not working on iOS device

### ISSUE THREAD

**Issue by kevinclarkadstech** [ionic-team/capacitor#2816]
I have followed multiple tutorials, including on the Ionic website, and am not getting expected results.

Repo: https://github.com/kevinclarkadstech/capacitor-issues

This repo attempts two things related to the Filesystem:

1) It downloads an existing image from Wikipedia with fetch, converts the blob to a data url, and saves the file.  However, linking to the FileWriteResult uri, even after passing to Capacitor.convertFileSrc, does not work.  The image just shows as a little square gray box, instead of the image.

2) I pretty much follow https://www.joshmorony.com/using-the-capacitor-filesystem-api-to-store-photos/, in which attempts to take a picture or choose a photo from the file system and move it to permanent storage.  There seems to be an issue with readFile as this is the part it throws an error at.  Logging the error shows {}.

I just updated my iOS version on my phone before trying any of this, and am wondering if Capacitor is not working with the latest version of iOS.  As of this writing I am on: 13.4.1

P.S. everything code related in the repo is in components/app-home

**Comment by jcesarmobile** [comment]
You are using the web plugins instead of the native plugins, when doing 
`import { Network, Camera, Filesystem } from '@capacitor/core';` it uses the web version, to use the native version use `import { Plugins } from '@capacitor/core';` and then `Plugins.Filesystem` or `const { Filesystem} = Plugins`

**Comment by kevinclarkadstech** [comment]
> You are using the web plugins instead of the native plugins, when doing
> `import { Network, Camera, Filesystem } from '@capacitor/core';` it uses the web version, to use the native version use `import { Plugins } from '@capacitor/core';` and then `Plugins.Filesystem` or `const { Filesystem } = Plugins;`

Doh!!!!!!!!!!!!!  Thank you!!  Now it suddenly makes more sense.  Thanks for the quick feedback @jcesarmobile !
