### ISSUE TITLE
bug: Camera picker on IOS is not dismissing after selecting a photo or cancel

### ISSUE THREAD

**Issue by qduborper** [ionic-team/capacitor#2817]
# Bug Report

## Capacitor Version
2.0.1

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.0.1

  @capacitor/ios 2.0.1

  @capacitor/core 2.0.1

  @capacitor/android 2.0.1

[success] Android looking great! 👌
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
On IOS (13.3) when using getPhoto function of Camera plugin and taking a photo, select it from library or cancel, the picker stays open without creating any error or crash. 

## Expected Behavior
The picker should dismiss after choosing a photo or cancelling

## Sample Code or Sample Application Repo

```
    try{
            const { Camera } = Plugins
            const image = await Camera.getPhoto({
                quality: 90,
                allowEditing: false,
                saveToGallery: false,
                resultType: CameraResultType.Base64,
                source: CameraSource.Prompt
            });

            console.log(image.base64String)
        } catch(e) {
            console.error(e)
        }
```

## Reproduction Steps

Run the previous code on IOS platform, and try take / select a photo or cancel after opening the camera / choosing file from library. The picker stays opened.

## Other Technical Details

It seems that `picker.dismiss(animated: true, completion: nil)` from Capacitor Camera plugin on IOS doesn't work anymore even if it creates no error.

## Other Information

Replacing `picker.dismiss(animated: true, completion: nil)` with `self.bridge.viewController.dismiss(animated: true, completion: nil)` then the picker can dismiss

**Comment by jcesarmobile** [comment]
I can’t reproduce, can you provide a sample app?

**Comment by qduborper** [comment]
Thanks for your answer, I just realised that with a fresh install it works, but the dismiss is not animated (cut transition) don't know if it's normal. After that, adding a cordova plugin I use, Gigya (https://developers.gigya.com/display/GD/Cordova) for login management it fails. The plugin works well but it creates maybe a conflict with the Camera plugin. Is it possible to look why ? I know that gigya use webviews maybe to display some screensets. Please find attached example fresh starter app with the plugin setup, and camera code failing on App init (you just need to npm install)
[myApp.zip](https://github.com/ionic-team/capacitor/files/4522072/myApp.zip)

**Comment by jcesarmobile** [comment]
I confirm the problem comes from gigya plugin, might be a problem in their SDK. 
The one used by the plugin is deprecated, so I wouldn't use that plugin until they update, not sure if a newer SDK would fix the problems, marking the plugin as incompatible

**Comment by qduborper** [comment]
Indeed with the updated plugin taken from the website, there is still this issue. I created an issue on the git plugin. 

But do you know why doing `self.bridge.viewController.dismiss(animated: true, completion: nil)` instead of `picker.dismiss(animated: true)` works ? Also, for example, if we remove the "imagePickerControllerDidCancel" method and let built-in cancel behavior from Apple it works also. So I'm wondering if the implementation can be updated or not, because otherwise the plugin works well with capacitor.

Thanks

**Comment by jcesarmobile** [comment]
The problem is that they have a Category for UINavigationController that does a custom dismiss and it messes with the regular dismiss.

The file is called `UINavigationController+CustomDismissNavigation.m` and looks like this
```
//
//  UINavigationController+CustomDismissNavigation.m
//  GigyaSDK
//
//  Created by Shmuel, Sagi on 20/06/2019.
//  Copyright © 2019 Gigya. All rights reserved.
//
#import "UINavigationController+CustomDismissNavigation.h"

@implementation UINavigationController (CustomDismissNavigation)

- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^)(void))completion {
    if (self.presentedViewController)
    {
        [super dismissViewControllerAnimated:flag completion:completion];
    }
}

@end
```
You can get it here https://developers.gigya.com/display/GD/Objective-C+SDK

If you download latest SDK, pick that file and the `UINavigationController+CustomDismissNavigation.h`, drag them to your app and change it to look like 


```
//
//  UINavigationController+CustomDismissNavigation.m
//  GigyaSDK
//
//  Created by Shmuel, Sagi on 20/06/2019.
//  Copyright © 2019 Gigya. All rights reserved.
//
#import "UINavigationController+CustomDismissNavigation.h"

@implementation UINavigationController (CustomDismissNavigation)

- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^)(void))completion {
       [super dismissViewControllerAnimated:flag completion:completion];
}

@end
```
it will work.

But as I said, their Objective-C SDK is deprecated, they have a new Swift SDK, they should update the plugin to use that new SDK (it's not a drop in replacement, they have to rebuild the whole plugin), and I think that SDK doesn't have this category nor nothing similar that could mess with modals, so that should fix the problem too.

**Comment by qduborper** [comment]
Many thanks for your help. Indeed this workaround is very useful and fix the issue. I'll follow the plugin update status with Swift SDK.
