### ISSUE TITLE
bug: iOS - addListener pushNotificationReceived and pushNotificationActionPerformed does not working

### ISSUE THREAD

**Issue by pedroclericuzi** [ionic-team/capacitor#2821]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

> Latest Dependencies:
> 
>   @capacitor/cli: 2.0.1
>   @capacitor/core: 2.0.1
>   @capacitor/android: 2.0.1
>   @capacitor/electron: 2.0.1
>   @capacitor/ios: 2.0.1
> 
> Installed Dependencies:
> 
>   @capacitor/electron not installed
>   @capacitor/cli 2.0.0
>   @capacitor/core 2.0.1
>   @capacitor/ios 2.0.1
>   @capacitor/android 1.5.1
> 
> [success] Android looking great! 👌
>   Found 1 Capacitor plugin for ios:
>     capacitor-fcm (2.0.0)
> [success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Not is entrying in addListener pushNotificationReceived and pushNotificationActionPerformed in no moment neither when arrive a push notification and in android it is working.

## Expected Behavior

Only show a console log when arrive a push notification or tapping it.

## Sample Code or Sample Application Repo

```
  PushNotifications.addListener('pushNotificationReceived', (notification: PushNotification) => {
      console.log('pvbc - Push received: ' + JSON.stringify(notification));
    }
  );

  // Tap in push notification
  PushNotifications.addListener('pushNotificationActionPerformed', async (notification: PushNotificationActionPerformed) => {
      console.log('pvbc - Push action performed: ' + JSON.stringify(notification));
      var obj = JSON.stringify(notification);
      var toParse = JSON.parse(obj);
      console.log('pvbc - tap in notification. Title: ' + toParse.notification.titile);
    }
  );

```

**Comment by jcesarmobile** [comment]
I can’t reproduce

**Comment by pedroclericuzi** [comment]
I am using the capacitor-fcm to fire the push notification. The plugin is working the registring normally, but with the pushNotificationReceived and pushNotificationActionPerformed does not happen anything. Is as whether them not to be are called when the app receive the notification or when tapping in it :(

**Comment by pedroclericuzi** [comment]
> I can’t reproduce

I am using the capacitor-fcm to fire the push notification. The plugin is working the registring normally, but with the pushNotificationReceived and pushNotificationActionPerformed does not happen anything. Is as whether them not to be are called when the app receive the notification or when tapping in it :(
