### ISSUE TITLE
bug: “error: package android.support.v4.content does not exist” 

### ISSUE THREAD

**Issue by Hansel03** [ionic-team/capacitor#2822]
# Bug Report

## Capacitor Version
2.0.1

`npx cap doctor` output:

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

error: package android.support.v4.content does not exist

## Expected Behavior

https://ionicframework.com/docs/native/camera

## Sample Code or Sample Application Repo

https://github.com/Hansel03/photoApp

## Reproduction Steps

`ionic build 
`
`ionic capacitor add android`
`ionic capacitor open android`
## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.16.1

`pod --version` output (iOS issues only): 1.9.1

`ionic/angular` 5.0.0

`Android Studio` 3.6.3
<img width="1606" alt="Captura de Pantalla 2020-04-22 a la(s) 4 38 15 p  m" src="https://user-images.githubusercontent.com/8334348/80253131-50358300-863e-11ea-8713-c3ee1deb5922.png">

## Other Information

https://github.com/ionic-team/capacitor/issues/1663

**Comment by jcesarmobile** [comment]
This is a problem on plugins not using old android support dependencies instead of AndroidX equivalent.
Capacitor 2 requires AndroidX dependencies.
It's documented on the migration guide, but since some people can face this in new apps that are not migrated from Capacitor 1, I've added some information about it on the android troubleshooting guide

**Comment by deborahjames** [comment]
@jcesarmobile Thank you so much . was getting error :

error: package android.support.v4.content does not exist 
import android.support.v4.content.FileProvider;

using jetify helped to solve .

from jcesarmobile' s post --- >

## Error: "package android.support.* does not exist"

This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent.
You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.

As workaround you can also patch the plugin using jetifier

```bash
npm install jetifier
npx jetify
npx cap sync android

**Comment by thesurya9** [comment]
> @jcesarmobile Thank you so much . was getting error :
> 
> error: package android.support.v4.content does not exist
> import android.support.v4.content.FileProvider;
> 
> using jetify helped to solve .
> 
> from jcesarmobile' s post --- >#2832
> 
> ## Error: "package android.support.* does not exist"
> This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent.
> You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.
> 
> As workaround you can also patch the plugin using jetifier
> 
> ```shell
> npm install jetifier
> npx jetify
> npx cap sync android
> ```

Thank you so much.

**Comment by sasithahtl** [comment]
> @jcesarmobile Thank you so much . was getting error :
> 
> error: package android.support.v4.content does not exist
> import android.support.v4.content.FileProvider;
> 
> using jetify helped to solve .
> 
> from jcesarmobile' s post --- >#2832
> 
> ## Error: "package android.support.* does not exist"
> This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent.
> You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.
> 
> As workaround you can also patch the plugin using jetifier
> 
> ```shell
> npm install jetifier
> npx jetify
> npx cap sync android
> ```

Thanks. This works.

**Comment by tirrth** [comment]
> @jcesarmobile Thank you so much . was getting error :
> 
> error: package android.support.v4.content does not exist
> import android.support.v4.content.FileProvider;
> 
> using jetify helped to solve .
> 
> from jcesarmobile' s post --- >#2832
> 
> ## Error: "package android.support.* does not exist"
> This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent.
> You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.
> 
> As workaround you can also patch the plugin using jetifier
> 
> ```shell
> npm install jetifier
> npx jetify
> npx cap sync android
> ```

Thanks. This works just fine for me!!!

**Comment by marvinero1** [comment]
> Thank you so much . was getting error :
> 
> error: package android.support.v4.content does not exist
> import android.support.v4.content.FileProvider;
> 
> using jetify helped to solve .
> 
> from jcesarmobile' s post --- >#2832
> 
> ## Error: "package android.support.* does not exist"
> This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent.
> You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.
> 
> As workaround you can also patch the plugin using jetifier
> 
> ```shell
> npm install jetifier
> npx jetify
> npx cap sync android
> ```

Thanks!!!!!

**Comment by mamta-99** [comment]
error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;

**Comment by mamta-99** [comment]
> Thank you so much . was getting error :
> 
> error: package android.support.v4.content does not exist
> import android.support.v4.content.FileProvider;
> 
> using jetify helped to solve .
> 
> from jcesarmobile' s post --- >#2832
> 
> ## Error: "package android.support.* does not exist"
> This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent.
> You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.
> 
> As workaround you can also patch the plugin using jetifier
> 
> ```shell
> npm install jetifier
> npx jetify
> npx cap sync android
> ```

i'am still getting same error


 error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;

**Comment by mamta-99** [comment]
> Thank you so much . was getting error :
> 
> error: package android.support.v4.content does not exist
> import android.support.v4.content.FileProvider;
> 
> using jetify helped to solve .
> 
> from jcesarmobile' s post --- >#2832
> 
> ## Error: "package android.support.* does not exist"
> This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent.
> You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.
> 
> As workaround you can also patch the plugin using jetifier
> 
> ```shell
> npm install jetifier
> npx jetify
> npx cap sync android
> ```

\platforms\android\app\src\main\java\org\apache\cordova\camera\CordovaUri.java:25: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;

platforms\android\app\src\main\java\org\apache\cordova\camera\FileProvider.java:21: error: package android.support.v4.content does not exist
public class FileProvider extends android.support.v4.content.FileProvider {}

platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:303: error: cannot find symbol
        this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
                                                   ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
