### ISSUE TITLE
bug: iOS's Password Autofill feature built-in to the native keyboard produces an error in Xcode since Capacitor 2.0.1.

### ISSUE THREAD

**Issue by kenny-line** [ionic-team/capacitor#2823]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
💊  Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.0.1

  @capacitor/android 2.0.1

  @capacitor/ios 2.0.1

  @capacitor/core 2.0.1

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
[success] Android looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

iOS's Password Autofill feature built-in to the native keyboard no longer works. The issue has only appeared since updating to Capacitor 2.0.1. Attempting to utilise the feature for a password input results in the following Xcode error:

```
App[19533:6293454] Keyboard cannot present view controllers (attempted to present <UIKeyboardHiddenViewController_Autofill: 0x10a510120>)
```

## Expected Behavior

iOS's native password manager, Keychain, should appear; allowing the user to select from a list of their credentials to autofill the HTML inputs.

## Sample Code or Sample Application Repo
```
<ion-label position="floating">Password</ion-label>
<ion-input required autocomplete clearInput type="password" inputmode="password"></ion-input>
```

## Reproduction Steps

Implement a standard HTML input or Ionic input with the _type_ attribute set to "password", and attempt to access the native keyboard's Password Autofill feature.

## Other Technical Details

`npm --version` output:
`6.14.4`

`node --version` output:
`13.12.0`

`pod --version` output (iOS issues only):
`1.9.1`

`ionic --version`
`6.6.0`

Xcode version:
`11.4.1`

iOS version:
`13.4.1`

**Comment by jcesarmobile** [comment]
I can see the `Keyboard cannot present view controllers (attempted to present <UIKeyboardHiddenViewController_Autofill: 0x10531a130>)` error, but the password manager appears in my case.
I can see that message on any capacitor version. Also tried different Xcode versions, and googling about it, looks like it's been around since 2018.
Going to close as "Apple bug" because it's not related to Capacitor

**Comment by danielehrhardt** [comment]
> I can see the `Keyboard cannot present view controllers (attempted to present <UIKeyboardHiddenViewController_Autofill: 0x10531a130>)` error, but the password manager appears in my case. I can see that message on any capacitor version. Also tried different Xcode versions, and googling about it, looks like it's been around since 2018. Going to close as "Apple bug" because it's not related to Capacitor

Did someone found a Solution?
