### ISSUE TITLE
bug: Filesystem doesn't create directory or write files. overall write fails for everything. even with the permissions allowed

### ISSUE THREAD

**Issue by qanuj** [ionic-team/capacitor#2827]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:
  @capacitor/cli: 2.0.1
  @capacitor/core: 2.0.1
  @capacitor/android: 2.0.1
  @capacitor/electron: 2.0.1
  @capacitor/ios: 2.0.1

Installed Dependencies:
  @capacitor/electron not installed
  @capacitor/ios 2.0.0
  @capacitor/core 2.0.0
  @capacitor/cli 2.0.0-beta.1
  @capacitor/android 2.0.0

## Affected Platform(s)

- [x] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Filesystem.mkdir({ directory: FilesystemDirectory.Data, path: "pictures"}).catch(err => {
    console.log('folder create warning', err.message);
});
doesn't create any folder, doesn't write any files. even after asking for permissions and permission defined from app info, yet fails to do so. I though I was paranoid, so I picked up old project which was working fine, and downloading on device, I uninstalled the app, rebuild it and then it stopped working. no npm install. plain ionic build --prod to run it on device.  and this code based was not changed in last week or so.

## Expected Behavior

It should be able to write files or create directories.
## Other Technical Details

`npm --version` output:
6.11.3
`node --version` output:
v12.16.1
`pod --version` output (iOS issues only):

**Comment by snow-drop** [comment]
Hi. I'm currently playing with the `Filesystem` plugin and seems to work fine. I'm testing it on Android 6.0 Marshmallow with the latest capacitor dependencies all in 2.0.1. It might help them if you put your device's OS also on `Other Technical Details`.

**Comment by qanuj** [comment]
I have tested with 3 different devices, 2 Android, 1 iOS. All fails writing file to storage.

**Comment by snow-drop** [comment]
May I see how you import `Filesystem` and `FilesystemDirectory`? I also encountered that same behavior yesterday but the issue in mine was wrong import of the plugin's modules.

**Comment by snow-drop** [comment]
By your statement "create the same folder again and it shows success. and then create again fails.", you mean, you allow the app to create the folder and it successfully created one? and then when you do it again, it displays the error that the folder already exists?

Also, could you try running the following code in Android? I omitted the `directory` option and manually set the `path` there to make sure that the `directory` option can't conflict with the `mkdir()`.
```
await Filesystem.mkdir({
    path: '/storage/self/primary/NewFolder',
    recursive: true
})
```
I also encountered this error several hours ago:
```
{"message":"Unable to create directory, unknown reason"}
```
But mine was, instead of `FilesystemDirectory.Documents`, i wrote `FilesystemDirectory.DOCUMENTS`.

**Comment by qanuj** [comment]
I am able to narrow down that fact that folders and files are created yet.  even this, results in error in the catch method. though using the adb-shell command I can see the files and folders are all created fine in data director. (this is private folder).

    ```
Filesystem.stat({ directory: FilesystemDirectory.Data, path: '' }).then(result => {
      console.log(result.uri);
    }).catch(err => {
      console.log('Error', err.message);
    });
```

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing as there was no answer
