### ISSUE TITLE
cordova-hot-code-push cannot be use incapacitor

### ISSUE THREAD

**Issue by q5222777** [ionic-team/capacitor#2828]
Because ionic react's capacitor project doesn't even have config.xml anymore,and Ionic react doesn't have the WWW folder, just the build folder

So can't set in config.xml like:
![1587834994940](https://user-images.githubusercontent.com/35521129/80286125-325e4000-875c-11ea-8ee1-490408ee2b60.jpg)

And the command cordobia-hcp build will not live in the WWW files

**Comment by jcesarmobile** [comment]
the plugin is deprecated
marking as known incompatible plugin

**Comment by q5222777** [comment]
> the plugin is deprecated
> marking as known incompatible plugin

Are there alternatives?
