### ISSUE TITLE
bug: filesystem permissions not requested for file: URL

### ISSUE THREAD

**Issue by mohd-akram** [ionic-team/capacitor#2829]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed


  @capacitor/core 2.0.1

  @capacitor/android 2.0.1

  @capacitor/cli 2.0.1

[success] Android looking great! 👌
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

`Filesystem.readFile` does not request permission when given a `file:` URL.

## Expected Behavior

`Filesystem.readFile` requests permission when given a `file:` URL.

## Sample Code or Sample Application Repo

```typescript
import { MediaCapture } from "@ionic-native/media-capture";
import { Plugins } from "@capacitor/core";
const { Filesystem } = Plugins;

const files = await MediaCapture.captureVideo({ duration: 30, limit: 1 });
if (Array.isArray(files) && files.length) {
  console.log(await Filesystem.readFile({ path: files[0].fullPath }));
}
```

## Reproduction Steps

Install the `@ionic-native/media-capture` library. Create a page that runs the code above.

## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.16.1

## Other Information

This is problematic when the path is used in a `video` element via `Capacitor.convertFileSrc`. The web server fails to read the file. There is also no check for when a `file:` URL is provided as `path` and `directory` is provided as well (I tried this to trigger the permission request), causing the file path to look like `/storage/emulated/0/file:/storage/emulated/0/DCIM/100MEDIA/VIDEO0138.mp4`.

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing as there was no answer
