### ISSUE TITLE
[Android] SplashScreen + StatusBar: Statusbar customization doesn't apply to Splashscreen

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#283]
Super edge case: When you used StatusBar to change the style of the Statusbar, showing the Splashscreen again doesn't apply these changes but shows the default Statusbar. Only when the Splashscreen is hidden again do the customizations show again.

**Comment by mlynch** [comment]
Did you change the `View controller-based status bar appearance` in `Info.plist` to `YES`?

**Comment by janpio** [comment]
I should have specified that this was on Android, and again the project from `example`.

**Comment by jcesarmobile** [comment]
Closing in favour of https://github.com/ionic-team/capacitor/issues/1761 as it has a bit more information
