### ISSUE TITLE
bug: LocalNotifications are not persisted between device reboot on Android

### ISSUE THREAD

**Issue by meltuhamy** [ionic-team/capacitor#2830]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.0.1

  @capacitor/core 2.0.1

  @capacitor/ios 2.0.1

  @capacitor/android 2.0.1

[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

## Affected Platform(s)

- Android

## Current Behavior
Local notifications that have been previously shceduled on Android aren't triggering after the device re-boots.

## Expected Behavior
Local notifications that have been previously shceduled on Android should trigger after the device reboots.

## Sample Code or Sample Application Repo

Sample app: I've created [a new ionic app](https://github.com/meltuhamy/cap-local-notification-persistence-bug), here's the scheduling code:  https://github.com/meltuhamy/cap-local-notification-persistence-bug/blob/master/src/pages/Home.tsx

```
import { Plugins } from '@capacitor/core';
const { LocalNotifications } = Plugins;

LocalNotifications.schedule({
  notifications: [
    {
      title: "Title",
      body: "Body",
      id: 1,
      schedule: { at: new Date(Date.now() + 1000 * 60 * 5) },
      sound: null,
      attachments: null,
      actionTypeId: "",
      extra: null
    }
  ]
});
```

## Reproduction Steps
1. Schedule a local notification (using the snippet above) to be 5 minutes in the future. This should be enough time to reboot the device.
2. Once the notification is scheduled, reboot the device.
3. Wait for the notification to trigger (even though the app has not started)

- **Expected**: the notification should trigger.
- **Actual**: the notification is no longer scheduled

## Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: v13.12.0

`pod --version` output (iOS issues only): N/A

## Other Information
It turns out that the notifications have to be re-scheduled on Android, otherwise Android will clear them on device boot.

**Comment by jcesarmobile** [comment]
this happens on Android only? you didn't check the platform checkbox

can you provide a sample app?

**Comment by meltuhamy** [comment]
Hey, thanks for the reply. I am pretty sure it's Android only. I'll test it on iOS and get back to you. I'll try and create a sample app that repros but it should be as straight forward as what I mentioned in the issue.

**Comment by rarespop95** [comment]
I have the same problem. The notifications won't trigger after I reboot the device. I've tested it on Android 10 device and also on emulators(Android 10-7).

**Comment by tntwist** [comment]
Same here. Tested on device and emulators (Android 9 and 10).

**Comment by MedaiP90** [comment]
Same problem, this is annoying

**Comment by meltuhamy** [comment]
@jcesarmobile I won't be able to provide a sample app soon. In the meantime, this issue has gathered enough feedback to prove it's a real issue. The repro steps are enough to trigger the issue here.

**Comment by rakeshprakash91** [comment]
I am building an application, in which one of the key features is scheduling reminders, I faced the same issue in cordova(apparently the bug is open since 2017). Hope capacitor will fix the issue sooner.

**Comment by meltuhamy** [comment]
Just updated this with a sample app. https://github.com/meltuhamy/cap-local-notification-persistence-bug

**Comment by meltuhamy** [comment]
^ not sure why those labels got added. It's android only.

**Comment by XtreZz** [comment]
I am also have issues with this. I hope will be fixed soon!
