### ISSUE TITLE
bug: Android: cookie handling for proxied requests + avoid creating a new connection to check the contentType

### ISSUE THREAD

**Issue by goapilz** [ionic-team/capacitor#2831]
# Bug Report

## Capacitor Version
master 

## Affected Platform(s)

- [ ] Android

## Current Behavior
When using the "**server.url**" parameter in the capacitor.config.json to retrieve the app data from an external server incoming cookies are not saved to the CookieManager. Also an additional connection is opened in handleProxyRequest to check the contentType.

see: **WebViewLocalServer**:handleProxyRequest
see: **JSInjector**:getInjectedStream

My scenario:
Currently I use capacitor to add a native barcode scanner to my PWA app.
When running as simple PWA, the "browser camera api" is used, but when running in the capacitor app the native barcode scanner should be used.
Therefore capacitor seems to be the perfect framework.
But currently i have the described problem when the authentication cookie should be saved.

I would be happy if my change would be included in the project.

## Expected Behavior
save incoming cookies (also when getting text/html files)

## Sample Code or Sample Application Repo
see fix.zip

## Reproduction Steps
[fix.zip](https://github.com/ionic-team/capacitor/files/4536164/fix.zip)

**Comment by jcesarmobile** [comment]
can you send a pull request with the changes?
spotting the proposed changes in a zip file is harder

**Comment by goapilz** [comment]
I created a pull request. Hope i made no mistake.
https://github.com/ionic-team/capacitor/pull/2836

**Comment by goapilz** [comment]
> 
> 
> can you send a pull request with the changes?
> spotting the proposed changes in a zip file is harder

I created a pull request. Hope i made no mistake.

**Comment by goapilz** [comment]
There is still the needs-reply label on this issue.
Also the push request displays "Review required".
Is there something i must do to get the pull request merged ?

**Comment by jcesarmobile** [comment]
Sorry, I forgot to remove the label.
Can you provide a sample app where the cookies issue can be reproduced?

**Comment by goapilz** [comment]
I added a zip with the capacitor config and a test server in node that delivers a simple page that will set and check the cookie.

Because you need a https connection to call this server from the android webview a quick solution is using a proxy like ngrok.

Download and start ngrok:
https://ngrok.com/download
start via: ngrok http 3000

Start the node server via: node server.js

Then enter the ngrok https address in capacitor.config.json and build a new android app.
// e.g.: https://f97410f4.ngrok.io/?authToken=secretAuthTokenABC789

Hope this is enough input.

[example.zip](https://github.com/ionic-team/capacitor/files/4598020/example.zip)

**Comment by goapilz** [comment]
It is possible to merge the pull request. I think the changes are marginal and will result in a better "connection and cookie handling". Currently for all get requests a new connection is opened to check the contentType for "text/html" This is not really needed because the header of the request still contains the contentType. Also the cookie is saved to the CookieManager when the server sends new cookies via the "Set-Cookie" header.

Due to this bug i must always patch my local installation after a fresh "npm install" which is very inconvenient.

**Comment by IlCallo** [comment]
> When using the "server.url" parameter in the capacitor.config.json to retrieve the app data from an external server incoming cookies are not saved to the CookieManager

@goapilz do you have any idea about why this happens?
Could https://github.com/ionic-team/capacitor/issues/3012 be related?

**Comment by jcesarmobile** [comment]
fixed by #3078 and #3076
