### ISSUE TITLE
bug: showing warnings for  CapacitorCordova, Capacitor and CordovaPlugins in IOS Xcode

### ISSUE THREAD

**Issue by sachintavant** [ionic-team/capacitor#2833]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.0.1

  @capacitor/android 2.0.1

  @capacitor/core 2.0.1

  @capacitor/ios 2.0.1

[success] Android looking great! 👌
[error] electron not installed

## Affected Platform(s)

- [ ] iOS

## Current Behavior

showing warnings for  CapacitorCordova, Capacitor and CordovaPlugins Groups IOS Xcode as shown in attached screenshot.
<img width="274" alt="Screen Shot 2020-04-27 at 3 38 04 PM" src="https://user-images.githubusercontent.com/54265320/80361570-cafcd900-889e-11ea-957b-530b7b16617a.png">

## Expected Behavior

Should not show any warning messages for CapacitorCordova, Capacitor and CordovaPlugins Groups

## Reproduction Steps

1. npm run build
2. npm cap copy ios
3. npm cap open ios
4. run project
5. showing warning message in Xcode

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.16.0

`pod --version` output (iOS issues only): 1.7.4

**Comment by jcesarmobile** [comment]
warnings are harmless, won't fix
