### ISSUE TITLE
There is no hot update plugin to replace the unavailable cordobia-hot-code-push

### ISSUE THREAD

**Issue by q5222777** [ionic-team/capacitor#2834]
Is there a hot update plug-in to replace the unavailable cordobia-hot-code-push?

for ionic react

**Comment by jcesarmobile** [comment]
you can use ionic appflow

**Comment by match08** [comment]
Update to Capacitor:
https://github.com/match08/cordova-hot-code-push
npm install git+https://github.com/match08/cordova-hot-code-push.git
