### ISSUE TITLE
Make plugins Configurable

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#284]
It'd be great if plugins could be configurable.

For example, currently the splash screen is shown for 3 seconds, then hidden (if not hidden sooner via manual call to `SplashScreen.hide()`). There should be a way to configure this timeout to be longer for slow devices or apps.

**Comment by mlynch** [comment]
This is a good question in general for how we want to do plugin configuration. 

One idea:

Allow `plugins` in `capacitor.config.json` to configure each plugin, example:
```json
{
  "plugins": {
     "SplashScreen": {
       "launchShowDuration": 5000
     },
     "MyCustomPlugin": {
       "clientId": "asdf"
     }
   }
}
```

Then we could copy that config into the runtime on `copy` before building the app.

Thoughts @jcesarmobile @adamdbradley? I know you two had opinions on configuration

**Comment by mlynch** [comment]
The other idea is, of course, to force configuration to happen in the native layer, like

<img width="619" alt="screen shot 2018-03-10 at 3 45 19 pm" src="https://user-images.githubusercontent.com/11214/37247013-0e9f7e64-247a-11e8-8125-977ac6e15348.png">

**Comment by jcesarmobile** [comment]
I think the json file is a better approach, asking people to write native code to configure the apps is too much

**Comment by mlynch** [comment]
iOS Side of this working. Need to add `capacitor.config.json` to the default ios project.

Will do Android next

**Comment by mlynch** [comment]
Cool, all done for iOS and Android 🤙

**Comment by janpio** [comment]
Awesome 🥇
