### ISSUE TITLE
Browser Plugin Tint Color

### ISSUE THREAD

**Issue by ghernagon** [ionic-team/capacitor#2841]
# Browser Plugin Tint Color

## Describe the Feature Request
for iOS using SFSafariViewController there is another property we can use to customize the buttons tint color, that property is preferredControlTintColor, so we can use preferredBarTintColor to set the background color and the preferredControlTintColor for buttons tint color, otherwise the system uses the default blue tint color.

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
Something like this:

`
let toolbarTintColor = call.getString("toolbarTintColor")

DispatchQueue.main.async {
   ...
   if toolbarTintColor != nil {
      self.vc!.preferredControlTintColor = toolbarTintColor
   }
}
`

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.
