### ISSUE TITLE
feat: Filesystem readFile return size and name

### ISSUE THREAD

**Issue by ThomasKientz** [ionic-team/capacitor#2845]
# Feature Request

## Describe the Feature Request

Currently with the filesystem API it's not possible to retrieve informations about a file.

I proposed to include the file's size and file's name in addition of the datas.

It would solve issues were you must check the file size before uploading to a server and read the filename.

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [x] Web

## Describe Preferred Solution

Proposed result interface
```
export interface FileReadResult {
    data: string;
    name?: string;
    size?: number;
}
```

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.


BTW, there is a stat function that returns 

```
export interface StatResult {
  type: string;
  size: number;
  ctime: number;
  mtime: number;
  uri: string;
}
```
I know it's an extra call, but it's something

**Comment by ThomasKientz** [comment]
@jcesarmobile Is there a way to get the file's name ?
