### ISSUE TITLE
bug: Protocol mismatch error when attempting to access iframe's content in iOS

### ISSUE THREAD

**Issue by erikkadv** [ionic-team/capacitor#2847]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/electron not installed

  @capacitor/cli 2.0.1

  @capacitor/core 2.0.1

  @capacitor/ios 2.0.1

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

We have an app that we're building using Capacitor and Sencha Touch, and we can't get iframes to fully work in our iOS build.

The content in our iframe loads just fine, but when we try to access the contentDocument in our JS, we get the following error:

Blocked a frame with origin "capacitor://localhost" from accessing a frame with origin "https://oursite.com".  The frame requesting access has a protocol of "capacitor", the frame being accessed has a protocol of "https". Protocols must match.

## Expected Behavior

I would expect the iframe to behave the same way as it does in android, which uses the http:// protocol. Is there a way to configure our iOS build to get around this error?

## Sample Code or Sample Application Repo

var f = document.querySelector('iframe[name='+name+']');
var d = f.contentDocument; /* Throws error */

## Other Technical Details

`npm --version` output:
6.14.4
`node --version` output:
v12.16.2
`pod --version` output (iOS issues only):
1.9.1

**Comment by jcesarmobile** [comment]
capacitor apps use capacitor protocol for serving the content. It can be configured to use a different protocol, but WKWebView doesn't allow to use http or https. So I don't think you can workaround this.
