### ISSUE TITLE
feat: Update appId if appId is changed in capacitor.config.json

### ISSUE THREAD

**Issue by eduboxgithub** [ionic-team/capacitor#2848]
# Feature Request

## Describe the Feature Request
When a init or add command is executed (to add a android or ios platform)the appId is read from the capacitor.config.json and used to setup the native platforms. If for some reason the appId needs to be diferent there's a need to update it manualy in a lot of native files. The same seems to be happening to the "appName".

## Platform Support Requested
- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Describe Preferred Solution
npx cap copy or other command to update native platforms from the capacitor.config.json.

## Related Code
`{
    "appId": "com.app.versiondev",
    "appName": "Dev App Sample",
    "bundledWebRuntime": false,
    "webDir": "www",
    "npmClient": "npm",
    "plugins": {
        "PushNotifications": {
            "presentationOptions": [
                "badge",
                "sound",
                "alert"
            ]
        }
    }
}`

**Comment by losciur** [comment]
I completely agree.
It is very misleading that in the file strings.xml that appears:
`<resources>
    <string name="app_name">appName</string>
    <string name="title_activity_main">appName</string>
    <string name="package_name">appId</string>
    <string name="custom_url_scheme">appId</string>
</resources>`
If you change appName it works...
If you change appId no...

I strongly suggest that these strings and more (like appVersion number and version Code) have to be modified only compiling the "capacitor.config.json" and with the command "npx cap copy"

**Comment by IT-MikeS** [comment]
Maybe not the intended pattern going forward, we'd have to ask a core team member like @jcesarmobile or @dwieeb 

However the few times I have had to change my apps name or the ID for it, I have deleted the platform folders and re-added them.
Is there a reason you would like to avoid that?

**Comment by dwieeb** [comment]
It is highly tedious to change the Bundle ID and we can't guarantee the process would work in 100% of apps. This is a feature that belongs in Android Studio or Xcode, not Capacitor.

**Comment by hatsantos** [comment]
> Maybe not the intended pattern going forward, we'd have to ask a core team member like @jcesarmobile or @dwieeb
> 
> However the few times I have had to change my apps name or the ID for it, I have deleted the platform folders and re-added them.
> Is there a reason you would like to avoid that?

Probably for the same reason. I'ts also difficult to setup each individual file.... If I delete the "platform" I need to redo all the individual file setup (AndroidManifest, MainActivity, PLists, etc) for every custom plugin, native API, external API keys, etc.

At this moment I have built my own nodejs/build CLI on top of Capacitor/Ionic CLI.  I had to manage some "default" native files (AndroidManifest, MainActivity, PLists, etc). When I run my CLI commands I run my scripts that load/edits/save files (changes bundle ID/app name, stores API Keys, add code entries on MainActivity.java, etc.) and only after that the Capacitor CLI commands > Ionic CLI commands are executed.

I understand this is out of the Capacitor philosophy, I totally get it... this is more like the "config.xml" behavior... But it would be great if some of this small things could be taken care by the capacitor.config.json.

**Comment by barocsi** [comment]
ok so first you do a cap sync, it generates a target with name App then you rename App to something different, do another cap sync and whoa Unable to find a target named `App`... is this reasonable?

**Comment by damienromito** [comment]
I'd like to generate several app from the same base code.  This feature would be very helpful !

**Comment by martin-braun** [comment]
Same, now we have to search replace? Wow.

`cap sync` should update the projects, so they match the `capacitor.config.json`

**Comment by jcesarmobile** [comment]
This is not going to be implemented in Capacitor as Capacitor's policy is to never edit the user's native project after creation.

Users interested in changing the bundle identifier, package name and some other properties programmatically or with yaml files can take a look at capacitor-configure project
https://github.com/ionic-team/capacitor-configure

**Comment by martin-braun** [comment]
@jcesarmobile I don't get it though. Capacitor IS updating the user's native project after creation. For instance, it is copying the `capacitor.config.json` as well as the public assets of the web project into the native projects. 

There are clever ways to make this possible without replacing bits. For instance, take a look at Flutter. They overwrite a `local.properties` file in the Android project (as well as a plist file for iOS) to load parameters in, so other generated files won't be touched. 

If this is not the concern here, what is the reason for this decision exactly, please?
