### ISSUE TITLE
bug: window is not defined when using server rendering

### ISSUE THREAD

**Issue by flogy** [ionic-team/capacitor#2850]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Latest Dependencies:
  @capacitor/cli: 2.0.2
  @capacitor/core: 2.0.2
  @capacitor/android: 2.0.2
  @capacitor/electron: 2.0.2
  @capacitor/ios: 2.0.2

Installed Dependencies:
  @capacitor/cli 2.0.2
  @capacitor/core 2.0.2
  @capacitor/ios 2.0.2
  @capacitor/android 2.0.2
```

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Electron
- [x] Web

## Current Behavior
When using server rendering (e.g. with [Gatsby](https://www.gatsbyjs.org/)), a `window is not defined` error appears:

```
WebpackError: ReferenceError: window is not defined

  - web-runtime.js:12 new CapacitorWeb
    node_modules/@capacitor/core/dist/esm/web-runtime.js:12:1

  - global.js:8 
    node_modules/@capacitor/core/dist/esm/global.js:8:1

  - global.js:9 Module../node_modules/@capacitor/core/dist/esm/global.js
    node_modules/@capacitor/core/dist/esm/global.js:9:2

  - index.js:1 Module../node_modules/@capacitor/core/dist/esm/index.js
    node_modules/@capacitor/core/dist/esm/index.js:1:1
```

## Expected Behavior
Server rendering should work fine.

## Sample Code or Sample Application Repo

CodeSandbox: https://codesandbox.io/s/github/flogy/gatsby-starter-capacitor
GitHub Repo: https://github.com/flogy/gatsby-starter-capacitor

Run `npx gatsby build` to see the error in the sample project.

## Reproduction Steps

- Use Capacitor together with a SSR tool like Gatsby.
- Run the SSR process (e.g. build the Gatsby project).
- Error appears in the log.

## How to fix

The problem appears because a `window` variable was introduced in this PR: https://github.com/ionic-team/capacitor/pull/2759

To fix it, we could just add another check if `window` is actually defined:

```javascript
if (typeof window !== `undefined` && 'Proxy' in window) {
```

(This is actually how Gatsby recommends solving such problems: https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined)

**Comment by laurentgoudet** [comment]
Uh right, sorry about that. The issue with:

```ts
if (typeof window !== `undefined` && 'Proxy' in window) {
````

is that it effectively disables the usage of `Proxy` on the server, where it's actually supported (since Node.js v6 apparently), although yeah that's not terribly bad since calling any of the Capacitor API on the server would fail anyway.

Another option would be to do:

```ts
if ('Proxy' in (typeof window === 'undefined' ? global : window)) {
```

which would work both on the server and in the browser:

<img width="441" alt="Screen Shot 2020-04-30 at 14 58 23" src="https://user-images.githubusercontent.com/2169585/80713002-0f80b280-8af3-11ea-9935-23927aa9245b.png">

<img width="386" alt="Screen Shot 2020-04-30 at 14 58 02" src="https://user-images.githubusercontent.com/2169585/80713014-14456680-8af3-11ea-8f05-fcb2dddc6662.png">

**Comment by flogy** [comment]
Hi @laurentgoudet 

Thanks for the hint! Added it to the PR: https://github.com/ionic-team/capacitor/pull/2851

**Comment by jcesarmobile** [comment]
can you provide a sample app using Capacitor in the server?

**Comment by flogy** [comment]
@jcesarmobile my app is not actually using Capacitor in the server. To be clarify, I am using the [Gatsby](https://www.gatsbyjs.org/) framework which renders the initial state of the web app to static sites. This is especially beneficial for web app page speed.

To build my mobile apps, I then pass the build output from Gatsby to Capacitor.

The problem here is happening because Gatsby renders the static sites using Node and not an actual browser, so there is no `window` defined. 

I know it is not (yet) a widely known problem, but with JAMstack sites becoming more popular, I think it would be beneficial for Capacitor to be useable in server site rendered environments.

Unfortunately, the project I am building is for a client and the source code therefore not public. Is this explanation helpful to ubderstand the cause of the issue and why it woukd be great to include this check as proposed by the lonked PR? Or is a sample project still required?

Thanks in advance.

**Comment by jcesarmobile** [comment]
sample project is still required

**Comment by flogy** [comment]
@jcesarmobile Created a sample project now: https://codesandbox.io/s/github/flogy/gatsby-starter-capacitor
The issue can be reproduced by running `npx gatsby build` in the console.
