### ISSUE TITLE
How to `console.log/.warn` (via Webview console) from native code?

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#286]
To fully implement #285 I could use a way to call `console.log` or `console.warn` (etc.) from inside a plugin (core plugin SplashScreen in this case). The use case here would be to have a method of communicating stuff to the developer via the webview's console instead of only via the device log (which tends to be quite noisy).

I looked through `native-bridge.js` of course, but couldn't really figure out all the console stuff. The original webview console seems to get replaced, communication from native to JS/webview quite limited to plugins and their "message" passing. I guess one could create a "WebviewConsole" plugin, that would fit in that existing logic and somehow would end up calling the appropriate console function as a callback - but that seems to hacky to even start.

Did I miss something obvious how to get what I was thinking about?  
How do you think this should be implemented?

I think the native plugins being able to tell the developer about some things could be very useful functionality also for other plugins to use.

**Comment by mlynch** [comment]
Added in e8264022d895ecd4b86c5c043f76a4f96ed0dcb8

**Comment by janpio** [comment]
Whoop whoop 💯
