### ISSUE TITLE
feat: Schedule notifications relative from now

### ISSUE THREAD

**Issue by snow-drop** [ionic-team/capacitor#2862]
# Feature Request

## Describe the Feature Request
Add a function to schedule notifications relative from now.

## Platform Support Requested

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Related Code
```
LocalNotifications.schedule({
    notifications: [
      {
        body: 'Watch Kaguya-sama: Love is War',
        id: 1,
        schedule: {
          in: 3,
          unit: 'hour'
        }
      }
    ]
  })
```

## Additional Context
This feature has been taken from `cordova-plugin-local-notifications`.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.


Or if you are really interested and have the knowledge to implement this, you can send a PR.

Also, it can be accomplished with javascript using the `at` like 
`schedule: { at: new Date(Date.now() + 1000 * 3 * 60 * 60) }`
