### ISSUE TITLE
bug: Apple reject capacitor app with ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by mirzailhami** [ionic-team/capacitor#2863]
# Bug Report

## Capacitor Version
`npx cap doctor` output:
![Screen Shot 2020-05-04 at 03 41 39](https://user-images.githubusercontent.com/8240895/80925334-307a2980-8db9-11ea-87c0-d9c50c7024ee.png)

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Apple keep rejected my app due to UIWebView deprecation. I used latest capacitor, no cordova plugin at all. Only ionic 4 and capacitor. I used capacitor-firebase-auth plugin.
![Screen Shot 2020-05-04 at 03 38 44](https://user-images.githubusercontent.com/8240895/80925389-84850e00-8db9-11ea-98db-cd6b8ac8c055.png)

## Other Technical Details

`npm --version` output:
6.13.7

`node --version` output:
v10.16.2

`pod --version` output (iOS issues only):
1.8.4

**Comment by PatrickDFFY** [comment]
Hey mirzailhami,

Im currently running into the same problem as you. I think this might be something to do with the CapacitorCordova pod that the Capacitor pod depends on. I have not yet figured out how to work around this, but I will let you know if I do find something.

**Comment by jcesarmobile** [comment]
it's the capacitor-firebase-auth plugin https://github.com/baumblatt/capacitor-firebase-auth/issues/76

**Comment by mirzailhami** [comment]
> Hey mirzailhami,
> 
> Im currently running into the same problem as you. I think this might be something to do with the CapacitorCordova pod that the Capacitor pod depends on. I have not yet figured out how to work around this, but I will let you know if I do find something.

Replacing TwitterKit will fixed the issue, have you tried it? I will try and update this issue.

**Comment by mirzailhami** [comment]
> it's the capacitor-firebase-auth plugin [baumblatt/capacitor-firebase-auth#76](https://github.com/baumblatt/capacitor-firebase-auth/issues/76)

Thanks bro will try.
