### ISSUE TITLE
bug: default project has stretched splash screen on certain devices

### ISSUE THREAD

**Issue by silviogutierrez** [ionic-team/capacitor#2873]
# Bug Report

## Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.0.2

  @capacitor/core: 2.0.2

  @capacitor/android: 2.0.2

  @capacitor/electron: 2.0.2

  @capacitor/ios: 2.0.2

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed


  @capacitor/cli 2.0.2

  @capacitor/android 2.0.2

  @capacitor/core 2.0.2

[success] Android looking great! 👌
   Done in 6.20s.
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Use `cap create` then `cap add android` to create an empty Android project. Run the project on a **Pixel 3a**, **Pixel 4** or similar devices. The default splash screen is incorrectly stretched. On a Pixel 2 it looks file. Note: the Android Studio emulator can reproduce the bug, you don't need a real device.

## Expected Behavior

Splash screen, at least on default Capacitor projects, should be correct ratio.

## Reproduction Steps
See above. Brand new project, no changes to it.

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

## Other Information

Could be related to https://github.com/ionic-team/capacitor/issues/1627 but this isn't customized in any way. This is the default Capacitor template. Trying some of the tips listed there can make it show stretched first then correctly. But that's still a poor experience.

Thanks for all your work! This is a great library, and this is jus a small annoyance.

**Comment by jcesarmobile** [comment]
as explained on https://github.com/ionic-team/capacitor/issues/1627#issuecomment-582975393, this can't be fixed

**Comment by silviogutierrez** [comment]
@jcesarmobile : thanks for looking into this. I read through that thread and understand the challenges.

If indeed this is unfixable, I *strongly* recommend looking at different ways to start the default app. This affects not just capacitor's default app, but Ionic Native as well.

Just imagine a first-time developer checking out Ionic Native vs say React Native or other native development. They follow all the steps on the getting started out guide, changing nothing. And the *first* thing they *ever* see on their stock Android device is a stretched out Splash Screen? It's a very poor first experience for what is otherwise an amazing framework.

But the default should be sensible. There are other options for the default: getting rid of Splash Screens, using a loader, or something else. Ultimately it's not my call, but I would consider this to be high priority. First impressions matter.

@mlynch : I know your work on the Android/iOS native HTTP plugin will greatly improve the developer experience with Ionic/Capacitor. Curious what your thoughts are on this one.

**Comment by daveshirman** [comment]
> @jcesarmobile : thanks for looking into this. I read through that thread and understand the challenges.
> 
> If indeed this is unfixable, I _strongly_ recommend looking at different ways to start the default app. This affects not just capacitor's default app, but Ionic Native as well.
> 
> Just imagine a first-time developer checking out Ionic Native vs say React Native or other native development. They follow all the steps on the getting started out guide, changing nothing. And the _first_ thing they _ever_ see on their stock Android device is a stretched out Splash Screen? It's a very poor first experience for what is otherwise an amazing framework.
> 
> But the default should be sensible. There are other options for the default: getting rid of Splash Screens, using a loader, or something else. Ultimately it's not my call, but I would consider this to be high priority. First impressions matter.
> 
> @mlynch : I know your work on the Android/iOS native HTTP plugin will greatly improve the developer experience with Ionic/Capacitor. Curious what your thoughts are on this one.

Could not agree more.  Awaiting response from dev advocate at Ionic please.
