### ISSUE TITLE
bug: iOS / Xcode Cannot find interface declaration for 'UIStatusBarManager'

### ISSUE THREAD

**Issue by kkarkos** [ionic-team/capacitor#2874]
Hi, I created a simple `@ionic/vue 0.0.9` app and added `"@capacitor...": "2.0.2",`. For the UI I use `@ionic/vue` and `@ionic/core`

After `npx cap add ios` and `npx cap open ios` I get the following errors in Xcode `Version 10.2.1 (10E1001)` 

- _Cannot find interface declaration for 'UIStatusBarManager'; did you mean 'UIStatusBarWindow'?_
- _No known class method for selector 'class'_
- _Receiver type 'UIStatusBarWindow' for instance message is a forward declaration_

Followed all steps as per docs: https://capacitor.ionicframework.com/docs/getting-started/dependencies/

Build in XCode not working. 

`npx cap doctor`:

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

![Screenshot 2020-05-06 at 13 48 29](https://user-images.githubusercontent.com/1100387/81136943-50b80d00-8fa0-11ea-989d-7c4aeeacabd5.png)

**Comment by jcesarmobile** [comment]
Capacitor 2 only supports Xcode 11
Supposedly Apple was going to require Xcode 11 in April, so we dropped support, now they have extended the deadline until June, but we are not going to make changes to support it again just for a few more months.

**Comment by BossunxD** [comment]
I had the same problem, I'm building my ionic app in Xcode 11.5
![Screen Shot 2020-06-26 at 3 22 04 PM](https://user-images.githubusercontent.com/25877141/85831452-ec0b7880-b7c0-11ea-978b-a114a11b599a.png)

**Comment by vitorventurin** [comment]
I am having the same struggle here... (using Xcode 10.2.1)
Tried to downgrade Capacitor to version 1.5.1 but no success.

**Comment by rajasekarsp** [comment]
Facing same issue. Any pointers?
