### ISSUE TITLE
Rename `/ios` and `/android` to `/capacitor-ios` and `/capacitor-android`

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#288]
Right now the native Capacitor implementations can be found in `/ios` and `/android`. For someone new coming to the project, this can be confusing as the native projects generated by the Capacitor CLI end up in identically named folders. That could lead to confusion as what these 2 folders here actually are - I sure needed a bit to learn and understand the difference.

I suggest renaming them to `/capacitor-ios` and `/capacitor-android` to make clearer what those folder actually contain.

**Comment by jcesarmobile** [comment]
I don't dislike the idea, or even having a common capacitor folder and then ios and android folders inside.
Also, this will allow to add cordova platforms to the project

**Comment by janpio** [comment]
Haha, unfortunately not: You got confused in the exact same way I did (I think). 

The `ios` and `android` in this repo are the what is loaded into the actual iOS and Android projects (that are generated per the templates) via Gradle dependency or Cocoapod, they have nothing to do with the generated `ios` and `android` folders if you use Capacitor CLI in one of your projects.

**Comment by janpio** [comment]
Good point. 

My confusion was mainly when working in `example` where the same folder names also exist. The same would of course happen when a user that already used Capacitor in a normal project becomes a contributor. 

So I agree, that renaming the "Capacitor native projects" folders that are created would probably also solve the problem.

A `capacitor` folder with `capacitor/ios` and `capacitor/android` inside would actually clean up the project quite nicely. But is that extra layer worth it? Not sure.

**Comment by mlynch** [comment]
And I don't like either idea 😛

Will keep an eye out and see what other feedback we get. For now I don't see a need to change anything, we could just do a better job documenting
