### ISSUE TITLE
feat: Support bundling GeckoView with the android package

### ISSUE THREAD

**Issue by abuassar** [ionic-team/capacitor#2881]
# Feature Request

## Describe the Feature Request
now Ionic 5 needs at least chrome v55 to run flawlessly, yet some android 5.0+ devices can't update their WebView due to variuos issues, and android 5.0 is shipped with WebView 39 which is eons old.

so the solution is to bundle the runtime with the app package, that was possible before thanks to project crosswalk, unfortunatly it is now out of date and no longer supported.

Good news is mozilla released a new WebView compatible component called [GeckoView](https://mozilla.github.io/geckoview/) with very similar API to android system webview, and it is only 23 MB in size.

## Platform Support Requested
- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
giving us the option in capacitor to bundle GeckoView in order to support older android devices and/or unifying the runtime engine that our app runs on across all the devices.

## Describe Alternatives
cut the support for older devices which doesn't meet the minimum webview version required.

## Additional Context
check this comment in HackerNews: 
https://news.ycombinator.com/item?id=23105056
it contains real use case scenario and its advantages,

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.


Anyway, should be possible to use whatever webview you want, there were people using turbolinks, but of course would require a lot of work on your part.
