### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by arochet** [ionic-team/capacitor#2886]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
Latest Dependencies:
  @capacitor/cli: 2.1.0
  @capacitor/core: 2.1.0
  @capacitor/android: 2.1.0
  @capacitor/electron: 2.1.0
  @capacitor/ios: 2.1.0
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/electron not installed
  @capacitor/cli 2.0.2
  @capacitor/android 2.0.2
  @capacitor/core 2.0.2
```
## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I execute the same code with FileSystem plugin 2 times but i don't get the same result.

**First case I use**
`import { Filesystem, FilesystemDirectory } from '@capacitor/core';` 
I execute saveFile(). When I click button display File I get : "This is a test" but I have no File save in Document in Android.

**Seconde case I use** 
```
import { Plugins, FilesystemDirectory } from '@capacitor/core';
const { Filesystem } = Plugins;
```
I execute saveFile(). When I click button display File I get a weird text. However the txt File is saved correctly in Document in Android.

## Expected Behavior

The result have to be the same in both case ?
In the first case, i would like to have my Document File saved.

## Sample Code 

```
async saveFile(name: string) {
    //Save in Data
    await Filesystem.writeFile({
      path: 'test.txt',
      data: "this is a test",
      directory: FilesystemDirectory.Data
    });
    
    //Save in Document
    await Filesystem.writeFile({
      path: 'test.txt',
      data: "this is a test",
      directory: FilesystemDirectory.Documents
    });

    this.listMsg.push(name);
  }

  async displayFile(name: string) {
    const result = await Filesystem.readFile({
      path: 'test.txt',
      directory: FilesystemDirectory.Data
    });

    this.listMsg.push("text.txt : " + result.data);
  }
```

## Reproduction Steps

Copy the code with 2 types of import FileSystem. Execute on an Android device.

## Other Technical Details

`npm --version` output: 6.14.2

`node --version` output: v12.16.1

**Comment by jcesarmobile** [comment]
I don't really understand what you are saying, can you provide a sample app and steps to reproduce?

The code in "First case I use" it uses the web version of the plugin, the "Seconde case I use" uses the native plugin. 
If you don't provide an encoding then base64 is used, you have to pass `encoding: FilesystemEncoding.UTF8` to the writhe function to write as text

**Comment by arochet** [comment]
I didn't know there were a difference between : `import { Filesystem, FilesystemDirectory } from '@capacitor/core';` and `import { Plugins, FilesystemDirectory } from '@capacitor/core'; const { Filesystem } = Plugins;`.

Thank you for answer.
