### ISSUE TITLE
bug: Error: Cannot find module 'C:\Users\xmazzuce\@capacitor\cli\bin\capacitor'

### ISSUE THREAD

**Issue by emazzu** [ionic-team/capacitor#2888]
# Bug Report

## Capacitor Version

I install with this line, and I have Windows 10
npm install --save @capacitor/core @capacitor/cli

package.json says !!!
"@capacitor/android": "^2.0.2",

`npx cap doctor` output:

## Affected Platform(s)

- [X ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

when I wnat to use cap or capacitor : npx cap init or copy, or etc.

the message is: 
'Production' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:985
  throw err;
  ^
Error: Cannot find module 'C:\Users\xmazzuce\@capacitor\cli\bin\capacitor'

and capacitor, is into the each project, in node_modules !!!

I uninstall and install all again, and the problem continue !!!

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Unkn0wn0x** [comment]
First of all, you need to install the `@capacitor/core` dependency globally (to make it available in the `\bin\` and executable):
* `npm install -g @capacitor/core`

Then you should be able to run your command.

And you don't need to install the `@capacitor/cli` as a client dependency, you can move it to the dev dependencies to save a few bytes in the bundle at the end.

Hope it helps.

Cheers
Unkn0wn0x

**Comment by jcesarmobile** [comment]
No, don’t install @capacitor/core globally

**Comment by emazzu** [comment]
Thanks a lot

**Comment by jcesarmobile** [comment]
what are your node and npm versions?
I can't reprodue

**Comment by emazzu** [comment]
node --version
v12.16.1

npm --version
6.13.4

**Comment by jcesarmobile** [comment]
I've tried with those versions and can't reproduce.

Looks like something is wrong in your nodejs install, try reinstalling it
