### ISSUE TITLE
Ionic Native `deviceready` warning

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#289]
While testing `example/ios` I always get the Ionic Native `deviceready` warning:

![screen shot 2018-03-07 at 2 02 21 pm](https://user-images.githubusercontent.com/183673/37093653-602dc3ec-2210-11e8-8623-0f18a76e7549.png)

This probably makes sense as there is no `deviceready` event in Capacitor, but should this maybe be added if some implementation depends on it?

Update: On further thoughts, might I be getting this because `example` is not set up to include `cordova.js` etc.?

**Comment by mlynch** [comment]
Yea this looks like an issue with cordova in that project. `deviceready` will fire when using Cordova plugins because many apps rely on that

**Comment by janpio** [comment]
Any instructions on how to initially set up `cordova.js` and `cordova_plugins.js` in the example project? What has to be copied from where to where?

**Comment by mlynch** [comment]
You shouldn't have to do anything if you're running `npx cap update` and `npx cap copy`

**Comment by janpio** [comment]
This all refers to the example project where I don't use the CLI. 
(Or is this wrong?)
