### ISSUE TITLE
bug: Camera Plugin Crashes on iOS with `processAssertionWasInvalidated`

### ISSUE THREAD

**Issue by seanharr11** [ionic-team/capacitor#2897]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/electron: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/electron not installed

  @capacitor/cli 2.1.0

  @capacitor/ios 2.1.0

  @capacitor/core 2.1.0

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Take a picture using the Camera plugin via `getPhoto()`,  tap "Use Photo", app crashes intermittently (oftentimes within 3 attempts of taking the photo). XCode console logs include:
```TO JS {"webPath":"capacitor:\/\/localhost\/_capacitor_file_\/private\/var\/mobile\/Containers\/Data\/Application\/AC94AED7-A1D6-4D43-AB94-0AFA9712803C\/tmp\/photo-2.jpg","exif":{"ColorSpace":65535,"PixelYDimension":3024,"ExposureProgram":2,"OffsetTime":"-04:00",
2020-05-09 18:12:03.311351-0400 App[35271:9064095] [ProcessSuspension] 0x10b0d4300 - ProcessAssertion::processAssertionWasInvalidated()
2020-05-09 18:12:03.311491-0400 App[35271:9064095] [ProcessSuspension] 0x10b0d42d0 - ProcessAssertion::processAssertionWasInvalidated()
2020-05-09 18:12:03.312651-0400 App[35271:9064095] [assertion] Error acquiring assertion: <NSError: 0x28321ebb0; domain: RBSAssertionErrorDomain; code: 2; reason: "Specified target process does not exist">
2020-05-09 18:12:03.313488-0400 App[35271:9064095] [assertion] Error acquiring assertion: <NSError: 0x28326ff90; domain: RBSAssertionErrorDomain; code: 2; reason: "Specified target process does not exist">
```

## Expected Behavior
The photo should be captured successfully

## Sample Code or Sample Application Repo
[https://github.com/seanharr11/capacitor-camera-crash](https://github.com/seanharr11/capacitor-camera-crash
)

## Reproduction Steps

1. Take a picture
2. Tap "Use Photo"
3. After 1-5 tries, expect a quick "whitescreen + reload". In example app, `Tab2` swipes back in if the app is able to recover.

## Other Technical Details

`npm --version` output: `6.9.0`

`node --version` output: `v12.3.1`

`pod --version` output (iOS issues only): `1.8.4`

## Other Information
This seems to be more reproducible on older phones, namely our iPhone 7+ test device. It has been occurring in our production mobile app across many different version of iPhones.

**Comment by seanharr11** [comment]
**Update**: Confirmed this problem also exists on pre-2.0 versions of Capacitor.

**Comment by priyankpat** [comment]
I just tested the repo on my test iPhone 6 (12.4.6) and have no issue with the picture capture.

**Comment by jcesarmobile** [comment]
This is a known issue on the native component used by the Camera plugin (`UIImagePickerController`), it sometimes fails to release the memory if a lot of pictures are taken sequently and ends up restarting the app, in addition in some iOS versions the WebView didn't handle the memory well can caused even more frequent restarts. 
The WebView issue was fixed a few versions back, not sure about the Camera component, but sadly there is nothing we can do about it, keep reporting it on Apples radar and maybe they fix it if they haven't done already.

**Comment by abarax** [comment]
Is there the possibility of using a difference component to UIImagePickerController?
