### ISSUE TITLE
feat(android): proper offline handling for server apps 

### ISSUE THREAD

**Issue by jabczyk** [ionic-team/capacitor#2899]
# Feature Request

## Describe the Feature Request

- Server apps are not cached, meaning it's impossible to use them without an internet connection.
- When the app fails to load, the default Android "Web page not available" screen is shown.

## Platform Support Requested

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

- Server apps should be cached and loaded when user doesn't have a stable internet connection.
- A more user-friendly error should be shown when the cached version doesn't exist. (It should only happen if the app is opened for the first time and the user is offline)

## Related Code

- Caching should be set to `WebSettings.LOAD_DEFAULT` by default and changed to `WebSettings.LOAD_CACHE_ELSE_NETWORK` when offline, 
- We can fallback to the local index.html, so developers will be able to
a) show a customized error message.
b) provide an alternative app without live updates.

**Comment by jcesarmobile** [comment]
Capacitor is for loading local assets, if you load external sites you should build the caching yourself.
