### ISSUE TITLE
[Windows] Some consoles don't display `npx cap` output

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#291]
The left one is Cmder, the right one Powershell:

![image](https://user-images.githubusercontent.com/183673/37109549-9c75d022-223a-11e8-9aef-26bbb4194a55.png)

Somehow the coloring of `Capacitor - Cross-Platform apps with JavaScript and the Web`  messes with Cmder output and makes it invisible - I have to select the text to make it visible.

(No idea what is causing this and what can be done to fix it)

**Comment by jcesarmobile** [comment]
It's a chalk issue
https://github.com/chalk/chalk/issues/241

**Comment by IT-MikeS** [comment]
Not sure what this is about, I ran the command you did, and `npx cap add electron` and got colors out in cmder.

![capture](https://user-images.githubusercontent.com/20338451/37424828-d75f1754-2797-11e8-8a4f-813d3fbffb60.PNG)

**Comment by jcesarmobile** [comment]
Closing as for Mike the colors are good, so might be fixed or a configuration problem

Also chalk closed the issue saying there is nothing to do.

**Comment by janpio** [comment]
Can confirm seems fixed, possibly in Cmder:

![image](https://user-images.githubusercontent.com/183673/59522814-e69e0180-8ecf-11e9-9936-92fb12a18e52.png)

**Comment by jcesarmobile** [comment]
nice
