### ISSUE TITLE
bug: Errors running project with phonegap-plugin-push

### ISSUE THREAD

**Issue by davidecampello** [ionic-team/capacitor#2914]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/electron: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed

  @capacitor/cli 2.1.0

  @capacitor/core 2.1.0

  @capacitor/android 2.1.0

[success] Android looking great! 👌

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Hi, I started a new ionic app using capacitor. I need to receive push notifications from aws so I installed the phonegap-plugin-push following the https://ionicframework.com/docs/native/push instructions for capacitor.
Now, opening Android studio and Running the application I'm having this errors:
_capacitor-cordova-android-plugins/src/main/java/com/adobe/phonegap/push/PushPlugin.java
cannot find symbol class NotificationCompat
cannot find symbol class NotificationManagerCompat
cannot find symbol variable NotificationCompat
cannot find symbol variable NotificationManagerCompat
cannot find symbol variable NotificationManagerCompat_

And lot of others.

Am I doing something wrong?

I'm using the last Android studio. I'm not sure if it's interesting for the problem but under Android SDK only Android 9.0 and Android 8.1 are selected.

I can provide more informations.

Thanks.
Davide

**Comment by jcesarmobile** [comment]
see https://capacitor.ionicframework.com/docs/android/troubleshooting#error-package-android-support-does-not-exist

anyway, capacitor has push support, you don't need that plugin and it's not maintained.
