### ISSUE TITLE
bug: Filesystem not finding file on android

### ISSUE THREAD

**Issue by aaronksaunders** [ionic-team/capacitor#2916]
# Bug Report
Filesystem not finding file on android 29 work fine on Android 28
## Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/electron: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/core 2.1.0

  @capacitor/android 2.1.0

  @capacitor/cli 2.1.0

  @capacitor/ios 2.1.0

[success] Android looking great! 👌
  Found 2 Capacitor plugins for ios:
    cordova-plugin-file (6.0.2)
    cordova-plugin-media-capture (3.0.4-dev)
[success] iOS looking great! 👌
Aarons-iMac:simple-file-upload-hook-master aaronksaunders$ 
```

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
File is not found

## Expected Behavior
File to be found

## Sample Code or Sample Application Repo

```
    const files = await MediaCapture.captureVideo({ duration: 30, limit: 1 });
    try {
      
[simple-file-upload-hook-master 2.zip](https://github.com/ionic-team/capacitor/files/4624249/simple-file-upload-hook-master.2.zip)
[simple-file-upload-hook-master 2.zip](https://github.com/ionic-team/capacitor/files/4624251/simple-file-upload-hook-master.2.zip)

// FAILS ON IOS AND ANDROID
      if (Array.isArray(files) && files.length) {
        console.log("full path: ", files[0].fullPath);
        console.log(await Filesystem.readFile({ path: files[0].fullPath }));
      }
    } catch (error) {
      console.log(error);
    }


    try {
      // FAILS ON  ANDROID
      if (Array.isArray(files) && files.length) {
        console.log("full path: ", files[0].fullPath);
        const blob = await fetch(Capacitor.convertFileSrc(files[0].fullPath)).then(r =>
          r.blob()
        );
        console.log(blob.size);
      }
    } catch (error) {
      console.log(error);
    }
```

## output

```
2020-05-13 15:18:00.901 17299-17299/io.ionic.starter I/Capacitor/Console: File: http://localhost/static/js/main.9e6dc3ff.chunk.js - Line 1 - Msg: full path:  file:///storage/emulated/0/DCIM/Camera/20200513_151754.mp4
2020-05-13 15:18:00.917 17299-17299/io.ionic.starter I/Capacitor/Console: File: http://localhost/static/js/main.9e6dc3ff.chunk.js - Line 1 - Msg: Error: File does not exist.
2020-05-13 15:18:00.918 17299-17299/io.ionic.starter I/Capacitor/Console: File: http://localhost/static/js/main.9e6dc3ff.chunk.js - Line 1 - Msg: full path:  file:///storage/emulated/0/DCIM/Camera/20200513_151754.mp4
2020-05-13 15:18:00.922 17299-17359/io.ionic.starter D/Capacitor: Handling local request: http://localhost/_capacitor_file_/storage/emulated/0/DCIM/Camera/20200513_151754.mp4
2020-05-13 15:18:00.922 17299-17359/io.ionic.starter E/Capacitor: Unable to open asset URL: http://localhost/_capacitor_file_/storage/emulated/0/DCIM/Camera/20200513_151754.mp4
2020-05-13 15:18:00.923 17299-17363/io.ionic.starter E/Capacitor: Unable to open asset URL: http://localhost/_capacitor_file_/storage/emulated/0/DCIM/Camera/20200513_151754.mp4
2020-05-13 15:18:00.925 17299-17363/io.ionic.starter E/Capacitor: Unable to open asset URL: http://localhost/_capacitor_file_/storage/emulated/0/DCIM/Camera/20200513_151754.mp4
2020-05-13 15:18:00.929 17299-17299/io.ionic.starter I/Capacitor/Console: File: http://localhost/static/js/main.9e6dc3ff.chunk.js - Line 1 - Msg: [object Blob]
```

**Comment by aaronksaunders** [comment]
[simple-file-upload-hook-master 2.zip](https://github.com/ionic-team/capacitor/files/4624254/simple-file-upload-hook-master.2.zip)

**Comment by jcesarmobile** [comment]
sadly this is not a Capacitor bug, it's just google tightening up security

**Comment by aaronksaunders** [comment]
What does that mean? So there is no mechanism in the existing ionic or capacitor framework to address this issue? Then at a minimum I think you should document this somewhere instead of just saying it doesn’t work. This is a plug-in that is listed as compatible when in fact it isn’t

**Comment by jcesarmobile** [comment]
It means Google doesn't allow to get files located at certain places on Android 10 devices when the app targets SDK 29 anymore.

It's not a Capacitor issue nor an incompatibility with the Cordova plugins.

If you try the plugins in Cordova apps targeting SDK 29 it doesn't work neither, so the plugins will need to be updated.

**Comment by aaronksaunders** [comment]
my point is that it is listed as a plugin in @ionic-native, there is nothing stating that is doesn't work other than what you just wrote here... so it is up to the developers to just stumble into the plugins that work and dont work.

I understand the issue but my point here is about simply updating the documentation to reflect that the plugin, and I am not sure what other ones, that are clearly listed on the ionic website, simply don't work on specific versions of android

**Comment by jcesarmobile** [comment]
ionic-native is just a set of wrappers around cordova plugins maintained by 3rd parties, and there are hundreds of them. And anybody can add new wrappers for new plugins in ionic-native repository.
It's impossible for us to test every possible plugin with every possible Android and iOS versions to add a note if there is any problem.
But if you are unhappy with the docs, you can report an issue here https://github.com/ionic-team/ionic-docs/issues

When we know for sure that a plugin is not compatible, or if an user reports it, we add a note like this one:
https://ionicframework.com/docs/native/splash-screen#capacitor

But for cordova-plugin-media-capture we won't be doing that, because the plugin is compatible, the Android 10 problem is a plugin problem that needs to be solved in the plugin code, just because nobody noticed and reported on the official repository doesn't mean it's not a plugin problem. 

BTW, there is a workaround to allow Android 10 to still access the now "forbidden" locations, you can add this line `android:requestLegacyExternalStorage="true"` to the `application` tag of the `AndroidManifest.xml`. But will probably not work on Android 11. At least gives some time for the cordova plugins to update.

More information: https://developer.android.com/preview/privacy/storage

**Comment by aaronksaunders** [comment]
thanks for the explanation, I was aware of the workaround which i found eventually during my search for a solution.

The issue looks like it has been resolved with this PR, where all of the permissions are granted when capacitor loads? I tested my project without the change to the manifest and it works fine

https://github.com/ionic-team/capacitor/pull/2936

I had tried to request permissions using the Capacitor API but it never worked

**Comment by skr-maag** [comment]
hi, I have the same problem with FileSystem of capacitor, Is there any solution for this problem in Ionic?

**Comment by wingo7** [comment]
@jcesarmobile, I am using cordova and after adding android:requestLegacyExternalStorage="true" to the application tag of the AndroidManifest.xml I have an error AAPT: error: attribute android:requestLegacyExternalStorage not found. Any workaround here? I tried to set build tool version 29 in the build.gradle, but that doesn't help
