### ISSUE TITLE
[CLI] plugin.ts printPlugins() is used in a broken way (maybe)

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#292]
I think I just found a bug while reading the source, which could lead to confusing output on the command line. See this method here:

https://github.com/ionic-team/capacitor/blob/aab0c41d8b1796b4d2c30a0aa138bf4db6dc7210/cli/src/plugin.ts#L100-L110

Per what it outputs this method is meant for "Capacitor Plugins".

But one of its usages is this one:

https://github.com/ionic-team/capacitor/blob/aab0c41d8b1796b4d2c30a0aa138bf4db6dc7210/cli/src/ios/update.ts#L38-L49

The `plugins` given to the method includes **both** Capacitor and Cordova plugins here.

I think its usage in `doctor` has similar problems.

Now the question is what this should actually output: 
* If only Capacitor plugins, then the list would have to be filtered before given to the method (see line 49 for an example)
* If all plugins, then the output could just be updated to fix this

**Comment by jcesarmobile** [comment]
yeah, good catch, in ios update it first logs the cordova plugins as capacitor plugins and then there is another log for cordova plugins and show the same plugin again, so I would say to show only Capacitor plugins, but filter inside the printPlugins, not before.

**Comment by janpio** [comment]
Another thing I noticed: 
In `android/update.ts` currently `printPlugins` is not called at all to output the plugins. Why only for iOS?
Also the `console.log` and `printPlugins` is duplication, right?

**Comment by janpio** [comment]
I think the filter might be before printPlugins as the code should be similar to the android one, where the result of the filtering is also used for additional. other things

**Comment by mlynch** [comment]
Just printing Capacitor plugins now because the cordova ones get printed later anyways
