### ISSUE TITLE
”safe-area-inset-top“  delay about 300ms to have value

### ISSUE THREAD

**Issue by eliot-ye** [ionic-team/capacitor#2920]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

@capacitor/cli 2.1.0
@capacitor/core 2.1.0
@capacitor/android 2.1.0
@capacitor/ios 2.1.0

## Affected Platform(s)

- [ ] Android
- [ x ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

To get the height of a div with "safe area inset top", you can only get the height of the div itself at the beginning, without the height of "safe-area-inset-top". After about 300ms, you can get the height of the div as your own height + "safe-area-inset-top"

## Expected Behavior

The height of the div should be the height of itself + the height of "safe-area-inset-top" at the beginning

## Other Technical Details

`npm --version` output:
6.12.1
`node --version` output:
v12.13.1
`pod --version` output (iOS issues only):
1.9.1

**Comment by eliot-ye** [comment]
???

**Comment by kainosnoema** [comment]
@eliot-ye I discovered that it's due to this bug in WKWebView: https://bugs.webkit.org/show_bug.cgi?id=191872.

My solution is to keep app UI hidden until the window `load` event, or until `window.readyState === "complete"`, and the `safe-area-inset-*` values will be ready.
