### ISSUE TITLE
bug: push notification docs not showing

### ISSUE THREAD

**Issue by roja** [ionic-team/capacitor#2925]
https://capacitor.ionicframework.com/docs/apis/push-notifications/

shows a blank page in chrome.

**Comment by roja** [comment]
ad-blocker caused the issue. apologies.

**Comment by dotNetkow** [comment]
Some ad blockers (or the Brave browser) have been aggressively blocking lately. Our best guess is that they see the string "push-notifications" and block the page. (face palm)
