### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by savgiannis** [ionic-team/capacitor#2926]
# Feature Request

## Describe the Feature Request
 
In the camera plugin there should be an option for multiple selection when picking an image from gallery. Of course it can be workarounded with a cordova plugin or with input type="file" with multiple attribute, but since capacitor is so close to achieving this functionality its a pitty not to do it. Also the input type file cannot be forced to open the gallery, and cordova plugins have different approach. It would be very nice to be included in capacitor's camera plugin.

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

**Comment by jcesarmobile** [comment]
the native component used for the gallery picking on iOS doesn't allow that, on Android could be possible, but not going to add it for Android only.
