### ISSUE TITLE
CLI: Code duplication for "copy plugins to native project" logic

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#293]
Remember how I was confused by the difference between `copy` and `update` in #265? 
I think I found out why:

* `copy` starts in `tasks/copy.ts` where it calls `copyCordovaJSFiles()` from `cordova.ts`. That gets all the plugins, filters by `Cordova`, and then hands the result over to `handleCordovaPluginsJS` in the same file. 
* `update` starts in `tasks/update.ts` where it calls `updateIOS()|updateAndroid()` from `ios|android/update.ts`. In there it gets all the plugins, filters them by type (`Cordova` vs. `Capacitor`) and then hands the Cordova ones over to `handleCordovaPluginsJS` in `cordova.ts` as well.

Now this is probably duplicated as `android/update.ts` also use the Capacitor plugins for something, and both `android|ios/update.ts` the Cordova plugins for something else.

Can/should this somehow be simplified?
Should maybe the other things from `update` also be done in `copy` (or is this a conscious decision as I think)?

**Comment by jcesarmobile** [comment]
Both copy and update call handleCordovaPluginsJS consciously, because copy nuke the public folder and we have to recreate the cordova plugins files.
But only update handles the native code.
We don't want copy to handle the native code because it takes too much time on iOS.

**Comment by janpio** [comment]
Yes, logic wise this all makes sense. 
I only now understood why I didn't get that when first looking at the code: `copyCordovaJSFiles` being in `cordova.ts` threw me off and made me miss that this also calls `handleCordovaPluginsJS` - so is functionally identical to what happens on `update`.

**Comment by mlynch** [comment]
So we're good? Closing for now

**Comment by janpio** [comment]
The code works fine, it is just not the "cleanest" code functionality wise as what `copyCordovaJSFiles` does is in `cordova.ts` for `copy` but in the update files for `update`.
