### ISSUE TITLE
bug: SplashScreen.splashImmersive does not hide status bar

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor#2934]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
❯ npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/electron: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/electron not installed


  @capacitor/cli 2.1.0

  @capacitor/ios 2.1.0

  @capacitor/core 2.1.0

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Enabling `splashImmersive` does not hide the status bar on app start up. I had to manually set `UIStatusBarHidden` to true but this causes another error where the status bar appears a millisecond between start up and showing the splash screen with the spinner.

![Bildschirmvideo aufnehmen 2020-05-15 um 18 07 32](https://user-images.githubusercontent.com/11534760/82071939-143e8c80-96d7-11ea-9bf8-e5a143e063a7.gif)

## Expected Behavior

Enabling this option should hide the status bar until ready state is called.

## Reproduction Steps

With any ionic starter:

1. Set `splashImmersive` to true
2. Run with `ionic capacitor run ios --livereload`
3. Run on device
4. Status bar is visible
5. Set `UIStatusBarHidden` in Plist to true
6. Re-run app
7. Flickering seen but Status bar hidden

## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: 12.16.1

`pod --version` output (iOS issues only): 1.8.3

**Comment by jcesarmobile** [comment]
that is Android only preference, should be documented

**Comment by muuvmuuv** [comment]
Oh, okay. But why? iOS provides such functionality as I can see and mentioned above. Maybe I turn this into a feature request then?

**Comment by muuvmuuv** [comment]
Okay, I understand that. Then how do I enable this functionality for iOS? Manually through `UIStatusBarHidden` works not so great (as you can see in the GIF) and I can not figure out where this flickering come from.

**Comment by jcesarmobile** [comment]
iOS app are already full screen, the status bar is "transparent",
so what you say sounds like a different issue, can you provide a sample app?

**Comment by muuvmuuv** [comment]
You can simply run any starter and try to remove the status bar with `UIStatusBarHidden`.

**Comment by ramseyfeng** [comment]
Does this bug really fixed? I'm still facing the issue with latest capacitor.
I tried it with latest capacitor 3.0.0-rc.0 with below configuration, and I still got the issue. 
Neither status bar nor the nav bar is hidden.
```
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 3000,
      "launchAutoHide": true,
      "backgroundColor": "#ffffffff",
      "androidSplashResourceName": "splash",
      "androidScaleType": "CENTER_CROP",
      "androidSpinnerStyle": "large",
      "iosSpinnerStyle": "small",
      "spinnerColor": "#999999",
      "showSpinner": true,
      "splashFullScreen": true,
      "splashImmersive": true
    }
  },
```
