### ISSUE TITLE
feat: StatusBar Overlay Webview and SetBackgroundColor on iOS

### ISSUE THREAD

**Issue by hoangtrann** [ionic-team/capacitor#2942]
# Feature Request

## Describe the Feature Request
Capacitor has its own Status Bar plugin but those features like Overlay Webview and SetBackgroundColor are not available on iOS, while cordova statusbar plugin is now incompatible with capacitor and can't be sync.

## Platform Support Requested

- [ ] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
iOS should have those features implemented or capacitor is compatible with cordova statusbar plugin

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/777

but I don't think we will implement it, iOS doesn't allow it and doing what the cordova plugin does is hacky and causes a lot of problems, the way to go is using css with the safe areas.
