### ISSUE TITLE
feat: compatible with cordova-plugin-iosrtc

### ISSUE THREAD

**Issue by polfernandez** [ionic-team/capacitor#2943]
# Feature Request
Make the cordova plugin  cordova-plugin-iosrtc compatible
https://github.com/cordova-rtc/cordova-plugin-iosrtc

## Describe the Feature Request

WebRTC is not available for iOS devices (PWA apps). Would be nice to have a plugin to access that natively such as  cordova-plugin-iosrtc

## Platform Support Requested

- [ ] Android
- [X ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Access to getUserMediadevices() for webrtc or compatibility for the cordova plugin  cordova-plugin-iosrtc

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/2063

**Comment by danielehrhardt** [comment]
Why did you closed both? @jcesarmobile

**Comment by jcesarmobile** [comment]
Please, don’t ping me.

The other one is closed as known incompatible plugin
