### ISSUE TITLE
feat: WebRTC Capacitor Plugin

### ISSUE THREAD

**Issue by polfernandez** [ionic-team/capacitor#2944]
# Feature Request
Capacitor plugin to access MediaDevices.getUserMedia() natively for iOS to work with WebRTC.

## Describe the Feature Request

Currently iOS PWA apps don't support access to video or voice recorder using MediaDevices.getUserMedia().
Would be very useful to have a plugin to access video and voice streaming capture.

## Platform Support Requested

- [ ] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

With native iOS apps being able to stream video and audio working with WebRTC

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for 👍 reactions to gauge interest.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/11. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
