### ISSUE TITLE
bug: Not working with nuxt.js

### ISSUE THREAD

**Issue by azs06** [ionic-team/capacitor#2946]
# Bug Report

## Capacitor Version: 2.1.0

`npx cap doctor` output:

```
Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/electron: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed


  @capacitor/cli 2.1.0

  @capacitor/core 2.1.0

  @capacitor/android 2.1.0

[success] Android looking great!
```

## Affected Platform(s)
- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
The app is not loading properly and seeing these errors on Android Studio. `Unable to open asset URL`.
![image](https://user-images.githubusercontent.com/1593663/82232196-1d865e00-9950-11ea-808a-8da9a1608110.png)
App gets stuck on nuxt.js loading screen 
![image](https://user-images.githubusercontent.com/1593663/82232288-4149a400-9950-11ea-8e58-b7dd3d839888.png)

## Expected Behavior
Should load the nuxt web app as an android application.

## Sample Code or Sample Application Repo
Repo of the web app I am trying to convert on to an android app https://github.com/azs06/ramadan-time
`capactitor.config.json`

```
{
  "appId": "com.ramdantime.com",
  "appName": "ramadan-time",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "dist",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
  },
  "cordova": {}
}
```

## Reproduction Steps
Just clone the repo, 
`npm install`
`npx cap add android`
`npx cap open android`
On Android studio hit the play button.

## Other Technical Details

`npm --version` output: 6.14.5

`node --version` output: v10.16.0

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/1750
