### ISSUE TITLE
Docs: Anchors don't work (or just under special conditions)

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#295]
When you open a docs URL with an anchor in a new tab, it will first jump to the linked headline but then go back to the top:
https://capacitor.ionicframework.com/docs/basics/workflow/#4-periodic-maintenance

If you then open the same URL again, it will go to the headline and stay there.

**Comment by mlynch** [comment]
There's a stencil bug that is causing this that I'm tracking
