### ISSUE TITLE
Is it possible to add a config file for default features?

### ISSUE THREAD

**Issue by qq1037305420** [ionic-team/capacitor#2953]
# Feature Request
Adding config file to config default deatures like notification, geolocation, .etc.

## Describe the Feature Request
Google is block in China, so geolocation, firebase related features would not work.

## Platform Support Requested
- [ * ] Android
- [ * ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
Adding a config file.

## Describe Alternatives
The code blcoks to customize each features.

## Related Code
None

**Comment by jcesarmobile** [comment]
Capacitor ships with all plugins, but it's up to you which ones you use, if some of the core plugins don't work in China you'll have to create your custom plugins that replaces them
