### ISSUE TITLE
bug: WKWebView does not scale down after sharing

### ISSUE THREAD

**Issue by dabaaaz** [ionic-team/capacitor#2955]
# Bug Report

## Capacitor Version
`npx cap doctor` output:

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/cli 2.1.0

  @capacitor/core 2.1.0

  @capacitor/ios 2.1.0

  Found 3 Capacitor plugins for ios:
    cordova-plugin-keyboard (1.2.0)
    cordova-plugin-screen-orientation (3.0.2)
    onesignal-cordova-plugin (2.9.1)
[success] iOS looking great! 👌

## Affected Platform(s)
- [ ] Android
- [X] iOS (iPhone XR and iPhone 7)
- [ ] Electron
- [ ] Web

## Current Behavior
When I share a picture with the long touch pressure of iOS in my app, then I try to share on Facebook or any external application, I get back to my app which is zoomed ! Just look the video to see how looks the html : [https://streamable.com/uwl48x](https://streamable.com/uwl48x)

As you can see if I share via SMS it's getting back..

The webview is scaled on sharing but does not come back when the share window is closed.

I've seen too that the height of the body has been changed (around +100px for the offsetHeight) on sharing but it does not get back when I close the sharing window while it works well with native app like Message (see the attached video).

## Sample Code or Sample Application Repo
```
<html>
    <head>
        <style type="text/css">
            * {
              margin: 0px;
              padding: 0px;
              box-sizing: border-box;
            }

            html, body {
              height: 100%;
            }

            body {
              border: 10px solid red;
            }
        </style>
    </head>
    <body>
        <img src="IMG" />
    </body>
</html>
```

## Other Technical Details
`npm --version` output: 6.14.5

`node --version` output: v10.16.3

`pod --version` output (iOS issues only): 1.8.3

**Comment by jcesarmobile** [comment]
sorry, this looks like a WKWebView bug, report it to Apple

**Comment by dabaaaz** [comment]
@jcesarmobile nope, it looks Capacitor does not work well.

Please watch that video : [https://streamable.com/918e75](https://streamable.com/918e75)
