### ISSUE TITLE
feat: Compatibility with http / https in iOS

### ISSUE THREAD

**Issue by pnaylor** [ionic-team/capacitor#2957]
# Feature Request

## Describe the Feature Request

Due to Capacitor serving content in iOS using the novel `capacitor://` protocol, it is incompatible with frameworks that only handle http / https, such as Elm:

<img width="400" alt="elm-cap-ios" src="https://user-images.githubusercontent.com/1429712/82503826-d95d9f80-9aae-11ea-9b58-fa9d3a8a35eb.png">

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Support http / https protocol restrictions for web frameworks using Capacitor iOS.

## Describe Alternatives

This may be addressed from the Elm side at some point as well, but my thought is it could easily be an issue for other web frameworks will run into as well.

## Related Code

Any Elm + Capacitor + iOS project.

## Additional Context

This person describes trying to get around the issue from the Elm side:

https://discourse.elm-lang.org/t/elm-0-19-single-page-app-with-capacitor/3988

**Comment by jcesarmobile** [comment]
it's not possible
