### ISSUE TITLE
feat: dont show errors if plugin isn't supported on the current platform

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/capacitor#2959]
It seems like capacitor should be able to handle exceptions like the following and prevent us from having to wrap calls like this in platform checks.

<img width="625" alt="Screen Shot 2020-05-21 at 7 47 34 AM" src="https://user-images.githubusercontent.com/39473/82556358-9267bc80-9b37-11ea-95cf-056ba5d7b8de.png">

More generally, if a native capacitor plugin isn't supported on [some platform]:
1) show a warning
2) resolve true

**Comment by jcesarmobile** [comment]
this would be a breaking change, so in case it's done it should wait until we have more breaking changes and do a 3.0 release

added the needs discussion tag as should be discussed

**Comment by indraraj26** [comment]
instead of error just throw console.warn that this plugin doesnt support for web

**Comment by josh-m-sharpe** [comment]
I'd suggest implementing some kind of no-op implementation in the platform where the plugin isn't supported.  The warning could be added there.  Then you can probably pitch any platform-detection logic.
