### ISSUE TITLE
feat: remove jasmine and protractor dependencies

### ISSUE THREAD

**Issue by philly-vanilly** [ionic-team/capacitor#2960]
# Feature Request

## Describe the Feature Request
As a framework user I want to decide myself which testings frameworks I use. For example, Jest or Cypress. So commands like `npx cap add android` should not fail when jasmine or protractor are missing

## Current Behavior
On the above command the android directory gets created, but with an error `[error] Unable to find node_modules/.... Are you sure ... is installed?`

## Tested with
Angular 9.1
Capacitor 2.1

**Comment by jcesarmobile** [comment]
don't know where that comes from, but not jasmine nor protractor are dependencies of any of the capacitor packages and I can `npx cap add android` without them installed

**Comment by dotNetkow** [comment]
@philly-vanilly - The Ionic app starters include Jasmine, Karma, etc in devDependencies.

You can find and remove them as needed in `package.json`.
