### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ionic-team/capacitor#2961]
# Bug Report

## Capacitor Version
2.0.1

## Affected Platform(s)

- [x] Android
- [x] iOS
- [x] Electron
- [x] Web

## Current Behavior
When implementing the Keyboard Plugin according to the documentation there is a method on the Keyboard Plugin to call removeAllListeners (https://capacitor.ionicframework.com/docs/apis/keyboard#method-removeAllListeners-0).

When referencing this in my project this method doesn't exist. 

## Expected Behavior
The method would exist and remove the listeners that ahve been added. 

## Sample Code or Sample Application Repo

import { Component, OnInit } from "@angular/core";
import { Plugins, KeyboardInfo } from "@capacitor/core";

const { Keyboard } = Plugins;

export class Page implements OnInit {
  keyboard = {
    isVisible: false,
  };

  constructor() {}

  ngOnInit() {
    Keyboard.addListener("keyboardDidShow", (info: KeyboardInfo) => {
      this.keyboard.isVisible = true;
    });
    Keyboard.addListener("keyboardDidHide", () => {
      this.keyboard.isVisible = false;
    });
  }

  ngOnDestory() {
    Keyboard.removeAllListeners();
  }
}

![Screen Shot 2020-05-21 at 9 10 56 AM](https://user-images.githubusercontent.com/28204537/82568069-e4164400-9b43-11ea-9bed-4967edf29207.png)

**Comment by jcesarmobile** [comment]
Did you update @capacitor/core to 2.0.1 too?

**Comment by selected-pixel-jameson** [comment]
I just updated capacitor/core to 2.1.0 and that seemed to resolve the issue. I didn't see it addressed in any of the release notes so I didn't realize it was fixed.
