### ISSUE TITLE
bug: Android Plugin - No listeners found for event

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2962]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/electron: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.0.2

  @capacitor/ios 2.1.0

  @capacitor/android 2.1.0

  @capacitor/core 2.1.0

```

## Affected Platform(s)

- [ X] Android

## Current Behavior
Im making a plugin to handle push notifications from One Signal service, I cant pass the notification data to capacitor via event notifier, it states that `No listeners found for event OneSignalNotificationEvent` - event is fired from a custom android plugin

## Expected Behavior
Expecting to receive an event via the event listener in my app 

## Sample Code or Sample Application Repo

Repository is here, i pruned the repo down to just the essential files
https://github.com/REPTILEHAUS/capacitor-events

Waiting in the app for an event using 
```

import { Plugins } from '@capacitor/core';
const {  demoPlugin  } = Plugins;

demoPlugin.addListener("OneSignalNotificationEvent", (data: any) => {
    alert(JSON.stringify(data))
});      

Plugins.demoPlugin.addListener("OneSignalNotificationEvent", (data: any) => {
    alert(JSON.stringify(data))
});
```

Some further info which might be useful, this is a plugin for integrating OneSignal into capacitor apps, and following their guide I have added an Application Class to my main apps codebase see below and in the repo, you will see it calls 2 methods, these are in my plugin and basically they are where i want to fire the event from (new com.demo.app.NotificationOpenedHandler() and new com.demo.app.NotificationReceivedHandler() )

```
package com.demo.app;

import android.app.Application;

import com.onesignal.OneSignal;

public class ApplicationClass extends Application {
  @Override
  public void onCreate() {
    super.onCreate();
    // TODO: Add OneSignal initialization here
    // OneSignal Initialization
    OneSignal.startInit(this)
      .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
      .unsubscribeWhenNotificationsAreDisabled(true)
      .setNotificationOpenedHandler(new com.demo.app.NotificationOpenedHandler() )
      .setNotificationReceivedHandler(new com.demo.app.NotificationReceivedHandler() )
      .init();
  }
}
```

this ApplicationClass is referenced in the main app modules manifest like so 
```
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:name=".ApplicationClass"
        android:theme="@style/AppTheme">
```

the class which processes a received notification and the one which I want to pass data onto my main plugin class is the one below, when I pass data to the processnotification2 method it does not pass it to the app.component.ts which is waiting for the event, it just outputs `V/Capacitor/demoPlugin: Notifying listeners for event OneSignalNotificationEvent` and then `D/Capacitor/demoPlugin: No listeners found for event OneSignalNotificationEvent`

```
public class NotificationReceivedHandler implements OneSignal.NotificationReceivedHandler {

  @Override
  public void notificationReceived(OSNotification notification) {

    JSONObject data = notification.payload.toJSONObject();
    String customKey;
    try {

      JSObject ret = new JSObject();
               ret.put("value", data );

      demoPlugin plugin = new demoPlugin();

      plugin.notifyListeners2(ret);
    }
    catch(Exception e) {
      Log.e("Err", e.getMessage() );
    }
  }
}
```

**Comment by jcesarmobile** [comment]
don't do `new demoPlugin();`, that creates a new plugin object that doesn't have the listeners set, use 
```
PluginHandle appHandle = getPlugin("demoPlugin");
demoPlugin plugin = (demoPlugin) appHandle.getInstance();
```

**Comment by REPTILEHAUS** [comment]
Thanks, I changed it to this but im getting the following error, I dont suppose it makes sense to you ?

`Err: Attempt to invoke virtual method 'com.getcapacitor.PluginHandle com.getcapacitor.Bridge.getPlugin(java.lang.String)' on a null object reference`


```
import com.getcapacitor.JSObject;
import com.getcapacitor.NativePlugin;
import com.getcapacitor.PluginHandle;
import com.getcapacitor.Bridge;
import com.onesignal.OSNotification;
import com.onesignal.OneSignal;

import org.json.JSONObject;

@NativePlugin()
public class NotificationReceivedHandler implements OneSignal.NotificationReceivedHandler {

  Bridge bridge;

  @Override
  public void notificationReceived(OSNotification notification) {
//    JSONObject data = notification.payload.additionalData;
    JSONObject data = notification.payload.toJSONObject();
    String customKey;
    try {

      JSObject ret = new JSObject();
               ret.put("value", data );



      PluginHandle appHandle = this.bridge.getPlugin("demoPlugin");
      demoPlugin plugin = (demoPlugin) appHandle.getInstance();

      plugin.notifyListeners2(ret);
    }
    catch(Exception e) {
      Log.e("XXXXXXXX Err", e.getMessage() );
    }
  }
}
```

**Comment by REPTILEHAUS** [comment]
Also @jcesarmobile I can see that the type that the getPlugin method is expecting is the pluginId, im unsure is that the reverse domain like notation or is that the name of the plugins main class ? I am using the mainclass name but still it doesnt seem to accept it.
