### ISSUE TITLE
Issues with .captureVideo()

### ISSUE THREAD

**Issue by Gmart9** [ionic-team/capacitor#2966]
*** These plugins are skipped during     ionic cap sync 

 Found 2 incompatible Cordova plugins for ios, skipped install
    cordova-plugin-compat (1.2.0)
    cordova-plugin-video-player (1.0.1)

let capture:any = await VideoCapturePlus.captureVideo(options);

***** ERROR ON     .captureVideo       error states that .captureVideo is not a property of VideoCapturePlus

**Comment by jcesarmobile** [comment]
Those plugins are android only, so appear as incompatible on iOS and obviously don’t work on iOS.

**Comment by Gmart9** [comment]
so how do you capture a video on IOS?
