### ISSUE TITLE
bug: Android Plugin - No listeners found for event

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2967]
I reported this yesterday, a solution was provided and the issue was immediately closed - however it did not work.

Now I don’t know if this is a bug or if there is a way to achieve this and as the docs are not up to date this is the only place I can ask or report

https://github.com/ionic-team/capacitor/issues/2962

**Comment by jcesarmobile** [comment]
The issue was closed because the problem was in your code, if there are still new problems report a proper bug, this is not.
