### ISSUE TITLE
bug: Plugins.Browser.open({...}) closes opened website immediately

### ISSUE THREAD

**Issue by philly-vanilly** [ionic-team/capacitor#2968]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
  @capacitor/cli: 2.1.0
  @capacitor/core: 2.1.0
  @capacitor/android: 2.1.0
  @capacitor/electron: 2.1.0
  @capacitor/ios: 2.1.0
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/electron not installed
  @capacitor/cli 2.1.0
  @capacitor/android 2.1.0
  @capacitor/core 2.1.0

```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
I have created a fresh capacitor app with the tabs template. my first tab code looks like this (I am trying to open an external website):

```
import { Component } from '@angular/core';
import {Plugins} from '@capacitor/core';
@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {
    onClicked() {
        Plugins.Browser.open({url: 'https://www.google.com/search?q=hello'});
    }
}
```
It works in the browser, but when I do `npx cap add android` and run from Android Studio, every time I navigate to google, I get thrown back.

## Expected Behavior
Either get navigated to `https://www.google.com/search?q=hello` or get an error message that some security policy is not set or why exactly it fails.

## Sample Code or Sample Application Repo
see above

## Reproduction Steps
see above

## Other Information
Sorry if I am missing something, but I asked about this on slack and SO before, with no success

**Comment by jcesarmobile** [comment]
I can't reproduce

**Comment by philly-vanilly** [comment]
In case someone else stumbles upon this issue:

the problem was only on an Android Emulator, not on a real device. Wiping data in the AVD manager made it work in the Emulator as well.

**Comment by mdledoux** [comment]
I just resolved a similar problem for @capacitor/browser@^1.0.6, with Cap 3 - in my case **the app was crashing when instead of the browser oepning** I tried to open certain URLs, but not others.  Turns out, I had a leading and trailing space on the URL that I copied from someone....bug ever, I'm kicking myself for not seeing it.
