### ISSUE TITLE
bug: Keyboard on iOS devices keeps black area when app goes to background with the keyboard opened

### ISSUE THREAD

**Issue by polfernandez** [ionic-team/capacitor#2969]
# Bug Report
With iOS devices (version 13.4) sometimes when the app goes to background with the keyboard opened, when it resumes it shows a black area where the keyboard was opened. This area only dissappears when the keyboard is opened again.
## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/core 1.5.2

  @capacitor/cli 1.5.2

  @capacitor/android 1.5.2

  @capacitor/ios 1.5.2

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Open the keyboard on <ion-textarea> and put the app in background. Whait some minutes and reload the app. Then sometimes it shows a blackscreen where the keybaord was placed.
see image:
![D699EDFB-8F29-45D2-93EE-1F7DD84AE80D](https://user-images.githubusercontent.com/32094365/82668785-8153a400-9c3a-11ea-957a-491d31d6a096.png)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/32094365/82668913-beb83180-9c3a-11ea-82b9-0b78952a982c.gif)

## Expected Behavior

The expected behavior would be when the app reloads keep the keyboard open.

## Other Technical Details

`npm --version` output:
6.13.4

`node --version` output:
v10.19.0

`pod --version` output (iOS issues only):
1.8.4

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
just noticed you are on 1.5.2, it was fixed in 2.0.2

**Comment by polfernandez** [comment]
thanks
