### ISSUE TITLE
bug: Camera/file picker fails on Android when minifyEnabled is true

### ISSUE THREAD

**Issue by arnotixe** [ionic-team/capacitor#2973]
# Bug Report

## Capacitor Version
`npx cap doctor` output:
Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/cli 1.3.0

  @capacitor/core 1.3.0

  @capacitor/android 1.5.2

  @capacitor/ios 1.5.2

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

✓Camera works when app is run from Xcode (and 
✓Camera works when app is run from Android Studio (
✓Camera actionsheet "take picture/show picture" does not show when run as a release APK in android, and logcat says:

> 05-22 22:26:22.264 25160 25160 E Capacitor/Console: File: http://localhost:8100/vendor.js - Line 40525 - Msg: ERROR Error: Uncaught (in promise): TypeError: cameraModal.componentOnReady is not a function
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console: TypeError: cameraModal.componentOnReady is not a function
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at CameraPluginWeb.<anonymous> (http://localhost:8100/vendor.js:132886:70)
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at step (http://localhost:8100/vendor.js:154264:23)
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at Object.next (http://localhost:8100/vendor.js:154245:53)
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at http://localhost:8100/vendor.js:154238:71
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at new ZoneAwarePromise (http://localhost:8100/polyfills.js:3882:29)
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at __awaiter (http://localhost:8100/vendor.js:154234:12)
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at http://localhost:8100/vendor.js:132878:142
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at new ZoneAwarePromise (http://localhost:8100/polyfills.js:3882:29)
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at CameraPluginWeb.<anonymous> (http://localhost:8100/vendor.js:132878:39)
> 05-22 22:26:22.264 25160 25160 E Capacitor/Console:     at step (http://localhost:8100/vendor.js:154264:23)

## Expected Behavior

Should open the camera also on release-android

## Sample Code or Sample Application Repo
Used the exact code from the Capacitor Camera web page.

## Reproduction Steps
Use the example code on Capacitor Camera documentation page, and set **enableMinify** to **true** in android/app/build.gradle

**To fix, just set enableMinify to false. I have reproduced both break and fix reliably**

## Other Technical Details

`npm --version` output:
6.14.4
`node --version` output:
v10.20.1
`pod --version` output (iOS issues only):

## Other Information

See temporary fix above. Doesn't hurt me to disable minify at this moment, but it could be fixed :)

I caught the error by rewriting the example code slightly with catch instead of await:
```
Camera.getPhoto({<options>})
.then(<upload, etc>)
.catch(err => console.log(`cameraerror ${JSON.stringify(err)}`);
```

**Comment by jcesarmobile** [comment]
it's a known issue https://github.com/ionic-team/capacitor/issues/739
