### ISSUE TITLE
bug: WKWebView is not resized properly after the native Share modal has been closed

### ISSUE THREAD

**Issue by snapeuh** [ionic-team/capacitor#2979]
# Bug Report

## Capacitor Version
`npx cap doctor` output:

Latest Dependencies:

@capacitor/cli: 2.1.0

@capacitor/core: 2.1.0

@capacitor/ios: 2.1.0

Installed Dependencies:

@capacitor/cli 2.1.0

@capacitor/core 2.1.0

@capacitor/ios 2.1.0

Found 3 Capacitor plugins for ios:
cordova-plugin-keyboard (1.2.0)
cordova-plugin-screen-orientation (3.0.2)
onesignal-cordova-plugin (2.9.1)
[success] iOS looking great! ok_hand

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
We are using the [Share](https://capacitor.ionicframework.com/docs/apis/share) API in our app and since the latest iOS update there's a bug that appears to be from Capacitor. 

When the Share Sheet opens and you select a third-party app to share the content with, it scales my app in the background to get a slide-over effect with the share modal from the third-party app (can be Facebook, Twitter or whatever).

However when canceling that modal and going back to my app, WKWebView is not scaled down to its original scale resulting in some of my UI being outside the screen and thus inaccessible to my users. If you share via Apple apps (like Messages) it works as expected.

My co-worker already created an issue #2955 about this but it was closed saying that the bug was related with WKWebView. So we investigated a bit more and we did a very simple Swift project with WKWebView and loaded our app inside it. Everything works as expected so our guess is that the behaviour is caused by Capacitor somehow.

Here's the behaviour in Capacitor : https://streamable.com/b2k4l0

The same workflow in our sample WKWebView swift app : https://streamable.com/sglxzn

In both case the app is scaled down by the third-party app share modal but when not running with Capacitor the app is scaled down as expected.

Can you please take some time to explore this issue ? Thanks a lot for your work with Capacitor ! 

## Expected Behavior
The WKWebView should scale down after a successful or canceled third-party app share using Share Sheet.

## Sample Code or Sample Application Repo

https://codepen.io/snapeuh/pen/GRpPyeN

## Reproduction Steps

- User action that triggers the [Share](https://capacitor.ionicframework.com/docs/apis/share) API or long-press the image on the sample code and press Share
- Choose a non-Apple app on the Share Sheet
- Share or cancel
- Close the Share Sheet

## Other Technical Details

npm --version output: 6.14.5

node --version output: v10.16.3

pod --version output (iOS issues only): 1.8.3

## Other Information
Issue #2955 posted by one of my co-worker

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing as there was no response and I don't see anything strange if I load the code in the codepen
