### ISSUE TITLE
Capacitor App Api - Passing parameter within openUrl in ionic app

### ISSUE THREAD

**Issue by peepsilog** [ionic-team/capacitor#2981]
I am trying to implement an SSO from app 1 to app 2 but cant seem to catch the paramaters within the deeplink from app 1. I have tried different ways of adding parameter within deeplink but none works. I am checking on ngOnInit if I get parameters but I dont get any. Any help would be much appreciated. Thank you!

App 1 code snippet:
```
let ret = await App.canOpenUrl({ url: 'com.mcp.deeplink' });
let reta = await App.openUrl({ url: 'com.mcp.deeplink://post?test?username=user1&password=pass1' });

```
App 2 code snippet within my route there's this:
`path: 'post/:username/:password'`

Ionic info:
Ionic:
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0
Capacitor:
   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0
Utility:
   cordova-res (update available: 0.14.0) : 0.9.0
   native-run (update available: 1.0.0)   : 0.3.0
System:
   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Comment by jcesarmobile** [comment]
how are you checking the params?

**Comment by peepsilog** [comment]
Upon entering ngOnInit(), I am alertring the username and password

```
  ngOnInit() {
    this.username = this.route.snapshot.paramMap.get('username');
    alert(this.username);
    this.password = this.route.snapshot.paramMap.get('password');
    alert(this.password);
  }
```

**Comment by jcesarmobile** [comment]
when you open an app from another app, the app doesn't automatically navigates to that url, so checking the route won't work. You have to use `App.getLaunchUrl()` or 
```
App.addListener('appUrlOpen', (data: any) => {
  console.log('App opened with URL: ' +  data.url);
});
```

**Comment by peepsilog** [comment]
@jcesarmobile I have tried adding the `App.getLaunchUrl()` and  `App.addListener` but it is still not working. Can I get another help?

I tried two(2) things on app2(destination of app of deeplink):

**First**:
```
  ngOnInit() {
    // tslint:disable-next-line:prefer-const
     this.getLaunch();
  }
  async getLaunch() {
    // tslint:disable-next-line:prefer-const
    let rety = await App.getLaunchUrl();
    alert('rety' + JSON.stringify(rety) + '= ' + rety.url);
    // {} = undefined
    if (rety && rety.url) {
    alert('t' + rety.url);
    }
  }

```
With the **first** approach, when I opened the app 2 _(which is the destination app of deeplink)_ , it is always triggered since it is on ngOnInit, so I closed app2 and clicked the deeplink from app1, so I tried checking the value of `rety` and `rety.url`, the values are :
`rety` = {} and `rety.url` = undefined

I checked https://github.com/ionic-team/capacitor/blob/master/core/src/web/app.ts and saw that it `getLaunchUrl()` does not have argument/s. Am I missing something on the **first** approach?

**Second**:
 ```
 ngOnInit() {
    this.listener();
  }
  async listener() {
    alert('listeners');
    App.addListener('appUrlOpen', (data: any) => {
      alert('App opened with URL: ' +  data.url);
    });
    alert('listeners end');
  }
```
As you can see I tried adding alert before and after `App.addListener`. But it is still not going through, also I closed my **app2** to make sure that it always go through `ngOnInit`.

Final thoughts:
I know ticket has been closed but any help is appreciated. Thank you!

**Comment by jcesarmobile** [comment]
Yeah, it doesn’t work on web, deep links are a native thing.

That’s why you are not supposed to delete the bug template where it ask about the affected platforms, if you don’t provide all the information from the beginning my answers are not accurate.
