### ISSUE TITLE
bug: push notification promises never finish on iOs

### ISSUE THREAD

**Issue by sebge2emasphere** [ionic-team/capacitor#2982]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

> 💊   Capacitor Doctor  💊 
> Latest Dependencies:
> @capacitor/cli: 2.1.0
> @capacitor/core: 2.1.0
> @capacitor/android: 2.1.0
> @capacitor/ios: 2.1.0
> Installed Dependencies:
> @capacitor/cli 1.4.0
> @capacitor/core 1.4.0
> @capacitor/ios 1.5.2
> @capacitor/android 1.5.2

iOs env: 
> iPhone 8, iOs 13.4.1 simulator
> iPhone 8, iOs 13.3.1 real device
> push notification enabled

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

This code works on Android, but on iOs the only output is 'before permission' and 'after permission'.

````
console.log('before permission');

try {
       this.push.hasPermission()
            .then((res: any) => {
                if (res.isEnabled) {
                    console.log('We have permission to send push notifications');
                } else {
                    console.log('We do not have permission to send push notifications');
                }
            })
            .catch(error => {
                console.error(error);
            })
            .finally(() => {
                console.log('has permission finally block');
            });
}
catch(e){
   console.log('error', e);
}

console.log('after permission');
````

I also tried to display a toast notification using my function 'displayError' like this:
````
        const pushObject: PushObject = this.push.init(options);

        pushObject.on('notification').subscribe((notification: any) => this.displayError('Received a notification', [JSON.stringify(notification)]));

        pushObject.on('registration').subscribe((registration: any) => this.displayError('Device registered', [JSON.stringify(registration)]));

        pushObject.on('error').subscribe(error => this.displayError('Error with Push plugin', [JSON.stringify(error)]));
````

But nothing happens. When I debug the app running in the simulator using Safari, I can see that the event is emitted to the window, but the success and the error callback are never used. In Xcode, the  console output of the simulator does not provide any relevant information.

## Expected Behavior

The promise should answer something and a console log should be generated.

## Other Technical Details

`npm --version` output:
> 6.13.4

`node --version` output:
> v12.14.0

`pod --version` output (iOS issues only):
> 1.9.1

**Comment by jcesarmobile** [comment]
this is not capacitor push code, so the problem might be in the plugin you use for push

**Comment by sebge2emasphere** [comment]
Thank you, let's create an issue on the phonegap-plugin-push project.
