### ISSUE TITLE
feat: `weekday` support in LocalNotifications

### ISSUE THREAD

**Issue by littke** [ionic-team/capacitor#2991]
# Feature Request

## Describe the Feature Request
I'd like to schedule recurring local notifications on Tuesdays and Thursdays at a given hour.

## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
I'd like to schedule it using the `on` keyword together with a (new) `weekday` (0-6) keyword. 

## Describe Alternatives
I don't see a way around this, as `day` is only 0-30. I could use `every` — but that doesn't let me set the hour of delivery. https://github.com/ionic-team/capacitor/issues/2752 goes into further detail.

## Related Code
```...
schedule: {
  on: {
    hour: 20,
    weekday: 2
  }
},
...
schedule: {
  on: {
    hour: 20,
    weekday: 4
  }
},
```

## Additional Context
- iOS: [DateComponent](https://developer.apple.com/documentation/foundation/datecomponents) has [`weekday`](https://developer.apple.com/documentation/foundation/datecomponents/1780094-weekday), support so it could easily be added in [`LocalNotifications.swift`](https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift#L276) from what I gather. 
- Android: I don't know Java but it seems in [`LocalNotificationsSchedule.java`](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationSchedule.java) we are using [`SimpleDateFormat`](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationSchedule.java) which has a [`u` — day number of week](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) (1-7) support.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.


Or if you are really interested and have the knowledge to implement this, you can send a PR.
