### ISSUE TITLE
feat: Speedup app launch time - Make core plugin registrations optional

### ISSUE THREAD

**Issue by fkirc** [ionic-team/capacitor#2992]
# Feature Request

## Describe the Feature Request

Every app developer knows that the launch time is critical for user experience, which is why every millisecond matters in our launch code.
In a recent Android profiling, I revealed that the "core plugin registration" of Capacitor took several milliseconds. This "core plugin registration" is done in `Bridge.java` as follows:

```Java
/**
   * Register our core Plugin APIs
   */
  private void registerAllPlugins() {
    this.registerPlugin(App.class);
    this.registerPlugin(Accessibility.class);
    this.registerPlugin(BackgroundTask.class);
    this.registerPlugin(Browser.class);
    this.registerPlugin(Camera.class);
    this.registerPlugin(Clipboard.class);
    this.registerPlugin(Device.class);
    this.registerPlugin(LocalNotifications.class);
    this.registerPlugin(Filesystem.class);
    this.registerPlugin(Geolocation.class);
    this.registerPlugin(Haptics.class);
    this.registerPlugin(Keyboard.class);
    this.registerPlugin(Modals.class);
    this.registerPlugin(Network.class);
    this.registerPlugin(Permissions.class);
    this.registerPlugin(Photos.class);
    this.registerPlugin(PushNotifications.class);
    this.registerPlugin(Share.class);
    this.registerPlugin(SplashScreen.class);
    this.registerPlugin(StatusBar.class);
    this.registerPlugin(Storage.class);
    this.registerPlugin(com.getcapacitor.plugin.Toast.class);
    this.registerPlugin(com.getcapacitor.plugin.WebView.class);

    for (Class<? extends Plugin> pluginClass : this.initialPlugins) {
      this.registerPlugin(pluginClass);
    }
  }
```

Now the thing is that I do not even use most of these core plugins.
Therefore, I would like to make these core plugin registrations optional.
Instead of registering all these plugins, I would like to selectively register only the plugins that my app uses.

## Platform Support Requested

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

To retain backwards compat, we might introduce a new config option that skips the core plugin registration.
However, loading `capacitor.config.json` from the Android assets is another task that might be bad for launch performance. Therefore, I suggest to replace the Android-specific `capacitor.config.json` with a generated Java-file that gets compiled into the Android app (while still leaving the root-level `capacitor.config.json` unchanged).

**Comment by fkirc** [comment]
@jcesarmobile if this is something that interests you, then I would be willing to submit a potential PR (if we are able to settle on implementation details and new config details).

**Comment by TekinGomes37** [comment]
I think it lacks the cordova approach here, we install the plugin we need, but the application becomes too heavy, because capicitor ships all the plugin cores. I know the user doesn't see it all. Unless there is a way to specify which plugins to keep.

Imagine that there will be other new plugins, will they all be on board? It is not possible, there is something missing in the documentation.

**Comment by fkirc** [comment]
> I think it lacks the cordova approach here, we install the plugin we need, but the application becomes too heavy, because capicitor ships all the plugin cores. I know the user doesn't see it all. Unless there is a way to specify which plugins to keep.
> 
> Imagine that there will be other new plugins, will they all be on board? It is not possible, there is something missing in the documentation.

I am not sure if I understand you correctly.
The developers should know the plugins that are used by their app.
Moreover, a missing plugin registration should lead to an immediate app-crash.
Therefore, I think that it is highly unlikely to accidentally forget a plugin registration, even if there were no default plugins at all.

**Comment by JumBay** [comment]
I did migrate my app from cordova to capacitor, here you can see the difference.
https://imgur.com/NGpuApn

In cordova the app launches right away, with a grey screen though, while it takes some time to capacitor to launch.

**Comment by AE1NS** [comment]
Its because of <item name="android:windowIsTranslucent">true</item> in your styles.xml. This waits for your splash to be ready. You can remove it and set a backgroundColor inside the capacitor.config so you have the same result as your cordova example.

**Comment by JumBay** [comment]
It's already like this.

### styles.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:background">@null</item>
    </style>


    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">@drawable/splash</item>
    </style>
</resources>
```

### capacitor.config.json
```json
{
...
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 10000,
      "showSpinner": false,
      "backgroundColor": "#000000",
      "androidScaleType": "CENTER_CROP",
      "splashFullScreen": false,
      "splashImmersive": false
    }
  },
....
```

**Comment by AE1NS** [comment]
Is @drawable/splash a xml Layout? It should be a png file (/res/drawable/splash.png). With this setup the app should start immediately.

**Comment by JumBay** [comment]
It is a png

![image](https://user-images.githubusercontent.com/216573/96242627-f5a13200-0fa3-11eb-8b1e-3d1552801bc1.png)

**Comment by jcesarmobile** [comment]
please, don't comment out of topic things, this has nothing to do with the reported issue

I'm closing the issue since Capacitor 3 is removing all plugins from core and would need to be installed separately, so that covers the requested feature.

for splash issues you can use the [discussions](https://github.com/ionic-team/capacitor/discussions) section

**Comment by JumBay** [comment]
Thx.
I'll wait for capacitor 3 and see if there is still this start up delay

**Comment by fkirc** [comment]
Just one more comment on the splashscreen plugin: It would be nice if Capacitor 3 also removes the splashscreen plugin from the core, because this would give a "performance-by-default" -experience.
