### ISSUE TITLE
call-number fails in capacitor on iOS

### ISSUE THREAD

**Issue by DouglasLapsley** [ionic-team/capacitor#2993]
Please see: https://forum.ionicframework.com/t/ionic-5-capacitor-call-number-failing/190184

Either I'm missing something (I'm new to Capacitor) or the call-number plugin doesn't work in capacitor.

Thanks.

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by DouglasLapsley** [comment]
I could do, although that would take some time.  Is the sample code not sufficient?

**Comment by jcesarmobile** [comment]
the plugin is working fine on my app

**Comment by DouglasLapsley** [comment]
Wooo, you closed that very quickly.  I'm building a test app now.  Any idea why it wasn't working please?

**Comment by DouglasLapsley** [comment]
I just built a blank test app and it's working in that, so must be something in my main app.  Any pointers would be appreciated, but will dig in the main app and see if I can find the problem.

**Comment by DouglasLapsley** [comment]
I can confirm that this was a syntax error in my code. Apologies for wasting your time.
