### ISSUE TITLE
bug: Camera.getPhoto() never returns on Android 10.0 with allowEditing: true

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/capacitor#2994]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Latest Dependencies:
  @capacitor/cli: 2.1.0
  @capacitor/core: 2.1.0
  @capacitor/android: 2.1.0
  @capacitor/electron: 2.1.0
  @capacitor/ios: 2.1.0
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/electron not installed
  @capacitor/cli 2.1.0
  @capacitor/android 2.1.0
  @capacitor/core 2.1.0
[success] Android looking great! 👌
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Calling `Camera.getPhoto({ allowEditing: true })` causes the app to wait forever after the user edits the photo.

## Expected Behavior

It should return to the app after selecting the picture.

## Sample Code or Sample Application Repo

[mirkonasato/capacitor-camera-editing](https://github.com/mirkonasato/capacitor-camera-editing) calls `Camera.getPhoto()` in `src/pages/Home.tsx`

## Reproduction Steps

Run the app, take a picture, edit with Photos. See [this 30-seconds video](https://youtu.be/kTLVW4bsKVg).

## Other Technical Details

`npm --version` output: 6.14.5

`node --version` output: v14.2.0

`pod --version` output (iOS issues only):

Happens when running in Android 10.0 in the Emulator. (Have not tried on a real phone.) Android 8.1 works fine.

**Comment by andirsun** [comment]
I faced same error.

**Comment by nikosdouvlis** [comment]
Facing the same issue. 

Also not completely related to this issue, I've found that the image editor is crashing on every Xiaomi device I tried. It seems to open and crash immediately after with the error message "Unable to edit photo". I've found that the the photo editor is crashing even with the old cordova camera plugin but it does return the (unedited) image data  - just noting it in case you want to handle it like that too (so we dont need to make the user pick another image on crash)

**Comment by Nuajan** [comment]
It is quite weird the behaviour: it is working for me on multiple xiaomi devices using CamerSource.Camera (and allowEditing as true) as @mirkonasato  sample, but failing using any other source (Photo or Prompt -if you choose gallery or photo again - ).

**Comment by 0xfe2f** [comment]
> It is quite weird the behaviour: it is working for me on multiple xiaomi devices using CamerSource.Camera (and allowEditing as true) as @mirkonasato sample, but failing using any other source (Photo or Prompt -if you choose gallery or photo again - ).

I'm facing the same issue

**Comment by TekinGomes37** [comment]
I have the same problem with onePlus 7 Pro Android 10

**Comment by heyitsbalazs** [comment]
Facing the same issue myself.

**Comment by jcesarmobile** [comment]
since plugins are in another repository I'm going to close this issue

there are two different issues reported about allowEditing not working there, you can subscribe to those or create a new one if none of those covers your issue
https://github.com/ionic-team/capacitor-plugins/issues/307
https://github.com/ionic-team/capacitor-plugins/issues/306
