### ISSUE TITLE
bug: Remove Warnings in Xcode

### ISSUE THREAD

**Issue by andirsun** [ionic-team/capacitor#2996]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/electron: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.1.0

  @capacitor/android 2.1.0

  @capacitor/core 2.1.0

  @capacitor/ios 2.1.0
## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Im faced a lot of warnings in the xcode project, Android studio doesnt show any. 
I Dont know how danger are these warning for my project

## Sample Code or Sample Application Repo

![Screen Shot 2020-05-27 at 10 18 30 AM](https://user-images.githubusercontent.com/22928302/83040309-bc702180-a004-11ea-8bb1-ff7a5344cfc5.png)

## Other Technical Details

`npm --version` output:
6.14.4
`node --version` output:
v12.16.0
`pod --version` output (iOS issues only):
1.8.4

**Comment by jcesarmobile** [comment]
warnings are harmless, if they become a problem will be fixed

**Comment by shpasser** [comment]
I think I should be not about "harmless" but about "clean". I was able to cleanup most of these warning in 10 minutes and I think that the Ionic team could do it in less. Please keep up good work.

**Comment by andirsun** [comment]
> I think I should be not about "harmless" but about "clean". I was able to cleanup most of these warning in 10 minutes and I think that the Ionic team could do it in less. Please keep up good work.

I think the same thing, but i dont know swift to handle the warnings, could you help with PR to fix a bunch of these warnings ?

**Comment by shpasser** [comment]
Sure.

**Comment by shpasser** [comment]
It will take some time before I can do it. In order to fix these warnings and submit a PR I will need to setup the development environment for capacitor. It is not the same like fixing those warnings in a project generated by capacitor.
