### ISSUE TITLE
feat: Capacitor Logo in SVG format?

### ISSUE THREAD

**Issue by karol-depka** [ionic-team/capacitor#3005]
Hi.
Is there a Capacitor Logo in SVG format?

If not, I can make it - please attach source materials.

**Comment by mlynch** [comment]
Yep, here you are:


[capacitor-logo-color.svg.zip](https://github.com/ionic-team/capacitor/files/4699720/capacitor-logo-color.svg.zip)

**Comment by karol-depka** [comment]
Thank You. Nice. I saw this one as PNG on https://capacitor.ionicframework.com/ but I could not find the SVG for it. Is there a press kit page, for example?

Capacitor is potentially such a game-changing technology... and any improvements in promoting it (like press kit, logos, etc.) could be useful :).
