### ISSUE TITLE
bug: LocalNotifications text body is truncated

### ISSUE THREAD

**Issue by snow-drop** [ionic-team/capacitor#3006]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 
Latest Dependencies:
  @capacitor/cli: 2.1.1
  @capacitor/core: 2.1.1
  @capacitor/android: 2.1.1
  @capacitor/electron: 2.1.1
  @capacitor/ios: 2.1.1
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/electron not installed
  @capacitor/cli 2.1.1
  @capacitor/core 2.1.1
  @capacitor/android 2.1.1

[success] Android looking great! 👌
[error] Xcode is not installed

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
LocalNotifications text body is truncated

## Expected Behavior
LocalNotifications text body should be expandable to view the whole text body esp. for longer text.

## Sample Code or Sample Application Repo

```
const text = 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.'

const notif = {
    id: 1,
    title: 'Test',
    body: text,
    schedule: {
        at: new Date(Date.now() + 5000)
    }
}

LocalNotifications.schedule({
    notifications: [notif]
})
```
## Reproduction Steps

Execute the above code. The notification text is currently truncated for longer text.

## Other Technical Details

`npm --version` output: 6.14.5

`node --version` output: v12.16.1

`pod --version` output (iOS issues only):

## Other Information

Screenshot of the truncated text:
[https://imgur.com/a/02RqB5v](url)

**Comment by jcesarmobile** [comment]
I've tested in two different devices and the whole text is displayed, or if the screen is locked it's cut but expandable, so it's probably some vendor customization.
