### ISSUE TITLE
bug: Camera.getPhoto can't reject promise when close image picker by swipe down.

### ISSUE THREAD

**Issue by taxibae** [ionic-team/capacitor#3008]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:
  @capacitor/cli: 2.1.1
  @capacitor/core: 2.1.1
  @capacitor/android: 2.1.1
  @capacitor/electron: 2.1.1
  @capacitor/ios: 2.1.1

Installed Dependencies:
  @capacitor/android not installed
  @capacitor/electron not installed
  @capacitor/cli 2.1.1
  @capacitor/core 2.1.1
  @capacitor/ios 2.1.1

  Found 0 Capacitor plugins for ios:

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

1. Call Camera.getPhoto with "source: CameraSource.Photos" option.
2. Present ImagePicker
3. Close ImagePicker by swipe down.
4. Camera.getPhoto return anything.

## Expected Behavior

Camera.getPhoto should reject promise with error message :"User cancelled photos app"

## Sample Code or Sample Application Repo
Ionic-angular project
[bitbucket repo](https://bitbucket.org/taxibae/taxibae-capacitor-camera-issue/src/master/)

## Reproduction Steps
1. Run the app on **iOS 13.4.1**
2. click "Open PhotoLibrary" button
3. close picker modal by swipe down

[See 30-second Video](https://youtu.be/SFj1fsFMKbo)

## Other Technical Details

`npm --version` output: 6.13.4
`node --version` output: v12.16.1
`pod --version` output (iOS issues only): 1.8.4

## Other Information

I need exception handling code for when the user closes the ImagePicker using the close button, or when the modal is swiped down to close.
The close button worked as intended, but not for swipe down actions.
As a test, I replaced line 199 of the Camera.swift :
```
public func popoverPresentationControllerDidDismissPopover(_ popoverPresentationController: UIPopoverPresentationController) {
  self.call?.error("User cancelled photos app")
}
```
with
```
public func presentationControllerDidDismiss(_ presentationController: UIPresentationController) {
  self.call?.error("User cancelled photos app")
}
```
to see it work as intended.
But I don't know much about iOS, so I don't know what side effects this code will cause.
If there are no problems, can I create a pull request?

**Comment by jcesarmobile** [comment]
Hi, thanks for the pointers, I've sent the PR already.

`popoverPresentationControllerDidDismissPopover` is still needed for iOS 11-12, `presentationControllerDidDismiss` is new on iOS 13.

**Comment by taxibae** [comment]
Thanks for your explanation!
