### ISSUE TITLE
bug: Local notifications won't receive

### ISSUE THREAD

**Issue by robertnicjoo** [ionic-team/capacitor#3020]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
Latest Dependencies:

  @capacitor/cli: 2.1.0
  @capacitor/core: 2.1.0
  @capacitor/android: 2.1.0
  @capacitor/electron: 2.1.0
  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.1.0
  @capacitor/core 2.1.0
  @capacitor/android 2.1.0

```
## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Local notifications will fire only if both users are in same component at the same time, if one of the users is in another component (activity) OR his app is inactive (backgrounded) local notification will not receive.

## Expected Behavior

Regardless of notification receiver location (`another activity` or `closed app`) he/she has to receive the notification.

## Sample Code or Sample Application Repo

**app.components.ts**

```
import {
  Plugins,
  LocalNotificationScheduleResult, //here
  NetworkStatus,
  PluginListenerHandle,
  PushNotification,
  PushNotificationToken,
  PushNotificationActionPerformed } from '@capacitor/core';

export class AppComponent implements OnInit, OnDestroy {

  notifs: LocalNotificationScheduleResult; //here
  pendingNotifs: LocalNotificationScheduleResult; //here

  constructor(...){...}

  async ngOnInit() {
    // local notifications
    await Plugins.LocalNotifications.requestPermissions();
    try {
      Plugins.LocalNotifications.addListener('localNotificationReceived', (notification) => {
        console.log('Notification: ', notification);
      });

      Plugins.LocalNotifications.addListener('localNotificationActionPerformed', (notification) => {
        console.log('Notification action performed', notification);
      });

    } catch (e) {
      console.log(e);
    }
  }
```

**myTab.page.ts that pushes notifications**

```
import { Plugins } from '@capacitor/core';
const { Toast } = Plugins;

ngOnInit() {
  this.socket.fromEvent('message').subscribe(async (message: any) => {
    // notif (should push notifications)
      const notifs = await Plugins.LocalNotifications.schedule({
        notifications: [
          {
            title: message.msg.message.user.username,
            body: message.msg.message.note,
            id: Math.floor(Math.random() * 10),
            schedule: { at: new Date(Date.now() + 1000 * 1) },
            sound: 'beep.aiff',
            attachments: null,
            actionTypeId: 'OPEN_CHAT',
            extra: null
          }
        ]
      });
      console.log('scheduled notifications', notifs);
  });
}
```

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v12.5.0

`pod --version` output (iOS issues only):

## Other Information

**What do you think is wrong with this configuration?**

**Comment by jcesarmobile** [comment]
this is not a capacitor issue, the local notifications, once they are scheduled, they will fire no matter what, doesn't matter in which page the user is or if the app is open or not, your problem is your `socket.fromEvent` is not getting called, so no notification gets scheduled, but that's your code, you'll have to figure out how to make sure it's getting called when you need it or switch to push notifications
