### ISSUE TITLE
feat: Make Plugins.Storage.set return the value in promise

### ISSUE THREAD

**Issue by UltraCakeBakery** [ionic-team/capacitor#3021]
# Feature Request

## Describe the Feature Request
Like the title says, make [.set()](https://capacitor.ionicframework.com/docs/apis/storage/) return the value in the promise.

## Platform Support Requested
- [x] Android
- [x] iOS
- [x] Electron
- [x] Web

## Describe Preferred Solution
Make it return the value in the promise.

## Describe Alternatives
Make it return the value given, not what is stored in the storage. 

## Related Code
```
return await Plugins.Storage.set({ key: 'someKey', value: JSON.stringify({ someObject: 'iWantToReturnStringified' }) })
```
## Additional Context
None unless requested.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.
