### ISSUE TITLE
feat: add "skipSslCertificateCheck" to capacitor.config

### ISSUE THREAD

**Issue by glebmachine** [ionic-team/capacitor#3023]
# Feature Request

## Describe the Feature Request
Could you please add ability to disable ssl check in capacitor.config.
This need to use self-signed certificates in dev mode.

## Platform Support Requested
- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution
`skipSslCertificateCheck` option in `server` part of config

## Describe Alternatives
Who knows

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.

**Comment by boycce** [comment]
Would be very handy in development if you are using sessions rather than JWT's

**Comment by Txiag** [comment]
for anyone who still has this problem,
https://github.com/jcesarmobile/ssl-skip may be useful
