### ISSUE TITLE
feat: Really background tasks

### ISSUE THREAD

**Issue by nicobytes** [ionic-team/capacitor#3032]
# Feature Request

Hello! 

The current background task is limited only run tasks in IOS for short time I understand the limitations but how the timer apps?

But in IOS my timer stops in Cordova I use the background-mode-plugin and works but with Capacitor what is the better approach?

I tried to use cordova-background-mode plugin in IOS with Cordova works but with the same code in Capacitor doesn't work

Capacitor App: https://github.com/nicobytes/capacitor-background
Cordova App: https://github.com/nicobytes/cordova-background

There is the branch https://github.com/ionic-team/capacitor/tree/wip-background-task but is inactive but has a method RegisterScript, that idea is possible?

Is there any native API for Background Tasks in IOS?

## My context

What is the better approach for background task for a timer, I'm making an app for sleep routines with sounds when the user wants to start to sleep start a sequence.

I have a timer for each phase when the time is up should continue with the next phase automatically with a new sound.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.

**Comment by ptmkenny** [comment]
I'm a bit confused.  I arrived at this issue from the [Capacitor 3 upgrade guide](https://capacitorjs.com/docs/v3/updating/3-0#background-task-permissions-and-photos-plugins-removed), which states "subscribe to #3032 for updates."  Is this the correct issue?

**Comment by pete-mcwilliams** [comment]
I also arrived at this issue from the Capacitor 3 upgrade guide, I'm concerned that the plugin has been just removed for all users even those that have been using it correctly to complete some short lived tasks prior to exiting, I do not agree that this this feature request relates to the existing capacitor 2 functionality.

I do not agree with the assertion that devs using the plugin did not understand it.

> This plugin appeared to be rarely used and didn’t quite work as most devs expected. The core team will readdress background functionality in the future. Subscribe to #3032 for updates.

**Comment by pete-mcwilliams** [comment]
I also arrived at this issue from the Capacitor 3 upgrade guide, I'm concerned that the plugin has been removed, I do not agree that this this feature request relates to the existing capacitor 2 functionality.

**Comment by fhrbek** [comment]
Same here, I came here from the Capacitor 3 upgrade guide. Unfortunately, the removal of this plugin blocks me from upgrading unless I find a way how to do the same thing with a different, non-capacitor plugin.
I use the Background Task to schedule local notifications when the user quits the application, sends the application to the background, or switches the phone to standby mode. The task finishes in a few seconds so it perfectly matches my needs and I don't have to care about the background task limitations.
Is there anyone who could give me advice on how to replace this (from my perspective) perfectly working plugin that has been removed?
Thanks!

**Comment by jeffersonveloso** [comment]
I also need the plugin to work in the background for my app, my app is for inventory management and needs to receive events via websocket even in the background.

**Comment by robingenz** [comment]
My app also uses the Background Task plugin. To be able to migrate to Capacitor 3, I've created a Background Task plugin for Capacitor 3. It has the same limitations as the Capacitor 2 plugin. 
Feel free to use it: https://github.com/robingenz/capacitor-background-task

**Comment by pete-mcwilliams** [comment]
Very nice, would you consider adding it to the community plugins?

**Comment by robingenz** [comment]
Yes

**Comment by rhyek** [comment]
@robingenz As someone who is completely new to capacitor, what are the limitations of your plugin? I see under quirks it mentions `There is currently no ready implementation on Android. It's planned to add the support in the near future.`. What does that mean in practical terms? Thanks.

**Comment by robingenz** [comment]
@rhyek Welcome! This means that there is no Android support yet, even if no errors are thrown when calling the methods on Android. The API exists and can be called. However, the actual implementation is missing (see [here](https://github.com/robingenz/capacitor-background-task/blob/02e35e08fe763e56a60bc5bae587ba038b8e461c/android/src/main/java/dev/robingenz/capacitor/backgroundtask/BackgroundTaskPlugin.java#L16)).

**Comment by fhrbek** [comment]
@robingenz it means that I cannot use it now (I want to support both iOS and Android). I'll postpone the capacitor upgrade then and, if I have some time in the future, I may try to help to add the android support (but not now, sorry, too many things to solve ATM, I'm feeling a bit overwhelmed).

**Comment by robingenz** [comment]
As I said above, it has the same limitations as the Capacitor 2 plugin.
The Capacitor 2 plugin does not have a real Android implementation (see [here](https://github.com/ionic-team/capacitor/blob/975bc200d3d2d5cf7490dcb573f1dce31b18d896/android/capacitor/src/main/java/com/getcapacitor/plugin/background/BackgroundTask.java#L55)) and neither does this one.
I created it to make migration easier and since I was planning to create a background task plugin with Android support anyway.
Let's address further questions in the plugin repo please.

**Comment by patrickmetz** [comment]
I just wanted to point out, as a side note, that there's a plugin 
for scheduling repeated [background fetch](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh) tasks.


It seems to be up-to-date, but has fairly limited functionality:
[capacitor version](https://github.com/transistorsoft/capacitor-background-fetch)
[cordova version](https://github.com/transistorsoft/cordova-plugin-background-fetch)

**Comment by pete-mcwilliams** [comment]
That's a good solution for the original issue

I don't think it helps those of us arriving at this issue from the link on Ionic's release notes for capacitor 3 where this issue is conflated with the removal of the Capacitor plugin (background task) which provided a little time to complete tasks on closing the app.

**Comment by 5hee75** [comment]
I'm coming from the v2 -> v3 upgrade guide, so I'll explore some of the options here.  A real background plugin would be amazing, I think.

I've also submitted a SO question about how to do long-running uploads with Ionic and Capacitor, which is why I'm using the BackgroundTask plugin.  Is this plugin even truly needed for that, or is there a different/better approach?

https://stackoverflow.com/questions/68675651/what-is-the-best-way-to-manage-long-running-uploads-with-ionic-and-capacitor

**Comment by Sibi4** [comment]
Hi @robingenz

> My app also uses the Background Task plugin. To be able to migrate to Capacitor 3, I've created a Background Task plugin for Capacitor 3. It has the same limitations as the Capacitor 2 plugin. Feel free to use it: https://github.com/robingenz/capacitor-background-task

I installed and used it by my task doesn't work when I close the application, it works only when I minimize it. 

```
App.addListener("appStateChange", async ({ isActive }) => {
  if (isActive) {
    return;
  }
  // The app state has been changed to inactive.
  // Start the background task by calling `beforeExit`.
  const taskId = await BackgroundTask.beforeExit(async () => {
    // Run your code...
    Notifications.showNotification();
    // Finish the background task as soon as everything is done.
    BackgroundTask.finish({ taskId });
  });
});
```
I want to send some local notifications even when the app is closed. Could you please tell me what am I doing wrong?

**Comment by khilnani** [comment]
It would really be good to have this - without this building a whole category of apps (scheduling, meeting, timers, event-based apps) that leverage local notifications are not really possible

**Comment by jrochel** [comment]
I wanted to migrate from Cordova to Capacitor, but background tasks (specifically background upload) is crucial to my project.

**Comment by notflip** [comment]
Does anyone know if there's a workaround at this time? I need to **handle 5MB photo uploads** (on Android), and I feel like I won't be able to do it without background tasks

**Comment by sandstrom** [comment]
@notflip 5 mb should be ~13 seconds on 3G (3 mbit). I'd just show a progress bar.

**Comment by notflip** [comment]
@sandstrom That's what I'm going to do indeed, I'm going to see how low I can turn the Capacitor Camera quality property until it looks good.

**Comment by kevnk** [comment]
Do you know if Background Tasks are 100% necessary if I need to play audio natively when the phone is locked or when they leave the app?

**Comment by gldstrrbt** [comment]
Please integrate this feature. Currently in need of it to deliver local notifications after users close the application/on boot. 

It's beyond a headache working with other solutions which don't have the best documentation or issues sections, especially when alert settings are kinda crucial for certain applications.

**Comment by robingenz** [comment]
For anyone stumbling across this issue, there are currently the following Capacitor plugins that can be combined:
- https://github.com/transistorsoft/capacitor-background-fetch: Periodic callbacks in the background for both iOS and Android (e.g. Sync data).
- https://github.com/capawesome-team/capacitor-background-task: Capacitor plugin for running a short background task on iOS after exiting the app (e.g. Finish upload). 
- https://github.com/capawesome-team/capacitor-android-foreground-service: Capacitor plugin to run a foreground service on Android (e.g. Finish upload). Can be used for longer tasks in the background as well as to finish a task after exiting the app.

I will soon publish a blog post with a guide on how to best combine which plugins to run Background Tasks on Android and iOS.

**Comment by peitschie** [comment]
A few more plugins that have some helpful hints:

* Registering app to auto-start on phone boot: [cordova-plugin-autostart](https://github.com/ToniKorin/cordova-plugin-autostart)
* A maintained [cordova-plugin-run-in-background](https://bitbucket.org/TheBosZ/cordova-plugin-run-in-background)

The `cordova-plugin-run-in-background` is especially useful as the `disableWebViewOptimizations` function there is a way of ensuring timers continue to fire reliably in the background even after the app is pushed to the background: https://bitbucket.org/TheBosZ/cordova-plugin-run-in-background/src/master/#markdown-header-quirks

This works by sending a "VISIBLE" state to the WebView a few seconds after the app is pushed to the background, which seems to restart all the timers back to their normal interval. With this technique, I've been able to keep an app reliably executing in the background (at least until doze mode kicks in) on a variety of phones.
