### ISSUE TITLE
bug: Camera plugin does not set image.path as described in docs

### ISSUE THREAD

**Issue by gmaughan** [ionic-team/capacitor#3033]
# Bug Report

## Capacitor Version

  @capacitor/cli 2.1.1
  @capacitor/core 2.1.1
  @capacitor/ios 2.1.1
  @capacitor/android 2.1.1

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Electron
- [x] Web

## Current Behavior

Documentation for the Camera plugin states that the `image.path` will be set to a file path that can be passed to the Filesystem API to read the raw data of the image.

No matter what CameraResultType I try, this property is always `undefined`.

## Expected Behavior

The `image.path` property should contain a path to the image file.

## Sample Code or Sample Application Repo

```typescript
  const { Camera, Filesystem } = Plugins;

    const image = await Camera.getPhoto({
      quality: 70,
      allowEditing: true,
      resultType: CameraResultType.Base64
    });

    const file: FileReadResult = await Filesystem.readFile({ path: image.path })

    // previous line results in 'file not found' error because `image.path` is undefined
}
```

## Other Technical Details

`npm --version` output: 6.4.1

`node --version` output: v10.15.3

`pod --version` output (iOS issues only): N/A

**Comment by gmaughan** [comment]
My workaround for this is to convert the Base64 into a Blob. But this isn't very efficient.

```typescript

      const image = await Camera.getPhoto({
        quality: 90,
        allowEditing: true,
        resultType: CameraResultType.Base64
      });

      // convert Base64 into binary. See: https://stackoverflow.com/a/62144916/473881
      const rawData = atob(image.base64String);
      const bytes = new Array(rawData.length);
      for (let x = 0; x < rawData.length; x++) {
        bytes[x] = rawData.charCodeAt(x);
      }
      const arr = new Uint8Array(bytes);

      const blob = new Blob([arr], { type: 'image/' + image.format });
```

**Comment by jcesarmobile** [comment]
resultType is for specifying the type of result you want, so if you use CameraResultType.Base64 you get the base64 and not the path, if you use CameraResultType.Uri then you'll get the path

**Comment by gmaughan** [comment]
As I mentioned above "No matter what CameraResultType I try, this property is always undefined."

I have since switched to using Base64 for my workaround and copied that incorrectly as my example. I will edit my original post.

If I use `CameraResultType.Uri` the only properties that are returned in the `CameraPhoto` result are `format` and `webPath`. Property `path` is undefined.

**Comment by jcesarmobile** [comment]
Yeah, path is optional, so it might be empty, on web, since the images are not on the filesystem, there is no path, only webPath, which is a blob url.

**Comment by gmaughan** [comment]
Understand now. Perhaps this needs an update to the docs.

**Comment by BunnyTheLifeguard** [comment]
This is pretty inconvenient for testing during development.
I'm trying to develop a solution to pass images from frontend to backend where they should be saved to a cloud storage.
Do I have to deploy my frontend and test the solution via a mobile device to make it work? Or does anyone have an idea how to solve this?
Ideally I want to show the user a preview of their image in the frontend (webPath would be ideal) while in the background the file gets saved to the storage.

**Comment by BunnyTheLifeguard** [comment]
Currently the only option I see would be to set the resultType to DataUrl, set the dataUrl as img-src and manually convert the b64 string to a file?
