### ISSUE TITLE
bug: java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp

### ISSUE THREAD

**Issue by reatailret** [ionic-team/capacitor#3039]
# Bug Report
Xiaomi Redmi Note 8 Pro
## Capacitor Version

`npx cap doctor` output:
 Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 2.1.2

  @capacitor/core: 2.1.2

  @capacitor/android: 2.1.2

  @capacitor/electron: 2.1.2

  @capacitor/ios: 2.1.2

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed

  @capacitor/cli 2.0.2

  @capacitor/core 2.0.2

  @capacitor/android 2.1.0

## Affected Platform(s)

- [X ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

angular http  requests to https not worked. 
When load GET https://api.instagram.com/oauth/authorize error in Android studio console 
java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
## Expected Behavior

Open intstagram auth page, load data

**Comment by jcesarmobile** [comment]
looks like it's some problem in your device
https://stackoverflow.com/a/54985015/1351469

**Comment by reatailret** [comment]
> 
> 
> looks like it's some problem in your device
> https://stackoverflow.com/a/54985015/1351469

Ok. Say to app users open StackOverflow? This Is not answer. But now how to use Capacitor? If it not working out of the box. With Cordova not problem. This is bug.

**Comment by priya212698** [comment]
@reatailret I am facing same issue with cordova as well. How did you manage to fix this ?

**Comment by reatailret** [comment]
> @reatailret I am facing same issue with cordova as well. How did you manage to fix this ?

i had this error when using capacitor, no problem in cordova. unfortunately the problem has not been solved and I cannot help.
