### ISSUE TITLE
bug: iOS Pluggin doesn't include resource files in the bundle Framework

### ISSUE THREAD

**Issue by cepages** [ionic-team/capacitor#3043]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Latest Dependencies:

  @capacitor/cli: 2.1.2

  @capacitor/core: 2.1.2

  @capacitor/android: 2.1.2

  @capacitor/electron: 2.1.2

  @capacitor/ios: 2.1.2

Installed Dependencies:


  @capacitor/cli 2.0.1

  @capacitor/android 2.0.1

  @capacitor/core 2.0.1

  @capacitor/ios 2.0.1

  @capacitor/electron 2.0.1
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When I add extra files to the plugin in XCode and I use the plugin in the main project ( after the plugin being published), these extra files are not present in the main project.

In my case it's a certificate file, when I add it to the plugin project in XCode, I can see it's in the Framework bundle:

![Screenshot 2020-06-03 at 11 31 15](https://user-images.githubusercontent.com/5259830/83629202-97922600-a591-11ea-80a6-9b51cbe9e06f.png)

Back to the main project, I can see the certificate file in the folder plugin in the `node_modules` folder, and if I open the XCode project in the same location I also can see that the file is in the bundle framework :

![Screenshot 2020-06-02 at 17 44 23](https://user-images.githubusercontent.com/5259830/83624431-8265c900-a58a-11ea-8bc8-38c64c84c710.png)

The problem if I open the XCode workspace in the main project. I can see the file is missing in the framework for the plugin in the Pod project:

![Screenshot 2020-06-02 at 17 45 42](https://user-images.githubusercontent.com/5259830/83625634-2c922080-a58c-11ea-9886-9361a502a4a2.png)

I figure out that if I add the following line:
```
s.resources = 'ios/Plugin/ca.der'
```
 in the podspec of the plugin in the node_modules folder ( after synchronise the main ios project with `npx cap sync ios` ) I can see the file in the plugin Framework bundle.

The problem is the podspec is auto-generated, any updates or installation may remove my modification. 

## Expected Behavior

The file added to the project in the plugin that is not a swift or objective file class should be added as a resource. 

## Sample Code or Sample Application Repo

I created this dummy project bases in the camera template. This project has a plugin with an empty `emptyCer.der` file. 

https://github.com/cepages/EmptyCertificateExample

## Other Technical Details

`npm --version` output:6.10.0

`node --version` output: v12.7.0

`pod --version` output (iOS issues only): 1.7.5

**Comment by jcesarmobile** [comment]
The plugin is not correctly configured to copy the certificate, so it's not a capacitor issue

I think you need the resource/resources tag
https://guides.cocoapods.org/syntax/podspec.html#resources

**Comment by cepages** [comment]
Oh, I realised my problem was I editing the wrong file, instead of editing the `.podspec` in `node/modules` I should have changed the `.podspec` in the plugin ( which I just realised there is one, I guess the location it's a bit difficult to come across )

Thanks, that made to think :)
