### ISSUE TITLE
bug: crashing instantly failed to capture with adb logcat

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/capacitor#3046]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
npx cap doctor
   Capacitor Doctor 
  
Latest Dependencies:
  @capacitor/cli: 2.1.2
  @capacitor/core: 2.1.2
  @capacitor/android: 2.1.2
  @capacitor/ios: 2.1.2

Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/cli 1.4.0
  @capacitor/core 2.1.2
  @capacitor/android 2.1.2
[success] Android looking great! 👌
```

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

It is crashing instantly when i am trying to open application.
I had some error in building apk so that i added this in gradle.properties
```
android.useAndroidX=true
android.enableJetifier=true
```
Repo :  https://github.com/indraraj26/capacitor-advanced-http-formData

Apk : https://github.com/indraraj26/capacitor-advanced-http-formData/blob/master/app-debug.apk

## Expected Behavior

It should not crash

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.16.3

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
you have `"@capacitor/cli": "1.4.0"`
update it to 2.1.2, remove android folder and run `npx cap android` again

or if you made manual changes and can't remove android folder, migrate the project to capacitor 2 following this instructions 
https://capacitor.ionicframework.com/docs/android/updating#from-1-5-1-to-2-0-0
