### ISSUE TITLE
feat: ability to set Icon in Share dialog

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/capacitor#3049]
# Feature Request

## Describe the Feature Request
The interface that opens from the [Share plugin](https://capacitor.ionicframework.com/docs/apis/share/) `Share.share(...)` on iOS appears to have a default icon and there's no way to configure it.

This feature request is to update the plugin such that the default Icon doesn't appear.

![ionic_share](https://user-images.githubusercontent.com/39473/83764763-53ae2800-a648-11ea-8dee-75375e9cae24.jpg)

## Platform Support Requested

I've specifically noticed the issue on iOS and not on the Android devices and emulators that we use.   However, I suppose it's Android has the same issue and we just haven't seen it.

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Default to the app icon

## Describe Alternatives
1) Ability to pass an icon to `Share.share(...)`
2) No Icon at all

**Comment by jcesarmobile** [comment]
That is really automatic, that icon means you are sharing text, if you share a http/https url you'll see the safari icon first and then the favicon of the website you are sharing, and if you share a file url like the one you get from the camera plugin when you take a picture a preview of the image appears.
But if you share both text and url, then the text icon appears.

**Comment by josh-m-sharpe** [comment]
@jcesarmobile Okay.  Docs currently state: `Each platform uses a different set of fields, but you should supply them all.` - It seems that supplying text, overrides things in a negative or unclear way.  Maybe the docs should be updated?

**Comment by jcesarmobile** [comment]
Yeah, that sentence is wrong, I've removed it in https://github.com/ionic-team/capacitor/pull/3051

In ShareOptions section you can see the ? on all params, that means they are optional. It also says `dialogTitle` is Android only, the other 3 work on both iOS and Android.

**Comment by josh-m-sharpe** [comment]
It also seems that by not setting text, then when sharing by Gmail/Mail apps the the email subject is not populated.  So that lets me choose between:

1) no subject in email (poor user UX)
2) no brand icon (poor marketing UX) -- for a Marketing feature.

I see other apps with sharing links that seem to have both a custom icon and populated email subjects.
