### ISSUE TITLE
Compatibility with Ionic 1, 2, 3?

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/capacitor#306]
Hello Ionic team,

Thanks for your hard work.

I have a question regarding Capacitor.
I know it will ship with Ionic 4, stencil.js but there are still a lot of AngularJS 1.x projects... as well as Ionic 1 jobs. Are we going to be able to use Ionic 1, 2 with AngularJS 1.x on Capacitor too? 
I hope using old project on capacitor will be possible...

**Comment by mlynch** [comment]
Hello there,

Capacitor does not ship with Ionic. It’s a stand-alone tool like Cordova that will work with any web projects, including ionic 1 through 4!

We will be integrating Capacitor into the Ionic CLI for a more fluid experience though.

Hope that helps!
