### ISSUE TITLE
callback from (android) plugin never received in code

### ISSUE THREAD

**Issue by Nasicus** [ionic-team/capacitor#3061]
# Bug Report / Question

## Capacitor Version
2.1.2

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [x] Web

### Behavior / issue

We have react app for which we implemented some native plugins.
One of these plugins is required for the authentication, which is done via open id.
Basically from the react / typescript code we call `acquireToken` which then calls the plugin.
The plugin then either returns a new `accessToken`  (with a  `refreshToken`) or if required does a login (starts a _new activity_ with an _intent_) and then after successful login returns the token.

This flow works _most_ of the time. However sometimes when a login is required and the user logged in successfully and the callback comes back to the app, the promise of the `acquireToken` call is _never_ resolved and the app is therefore hanging forever.

Let me give you a simplified version of our code (if you need more details, just ask).

The android plugin code (simplified, and partly pseudo code)

```
@NativePlugin(requestCodes = {100})
public class OpenIdClient extends Plugin {
  private static final int RC_AUTH = 100;

  @PluginMethod()
  public void acquireToken(final PluginCall call) {

    try {
      var result = performTokenRequest(call);
      JSObject result = new JSObject();
       result.put("accessToken", result.accessToken);
       call.success(result);
    } catch (Exception ex) {
      login(call);
    }
  }

  public void login(final PluginCall call) {
         startActivityForResult(call, <intent>, RC_AUTH);
  }

@Override
  protected void handleOnActivityResult(int requestCode, int resultCode, Intent data) {
    super.handleOnActivityResult(requestCode, resultCode, data);

    final PluginCall savedCall = getSavedCall();

    if (savedCall == null) {
      return;
    }

    if (requestCode == RC_AUTH) {
        JSObject result = new JSObject();
        result.put("accessToken", data.accessToken);
        call.success(result);
    }
  }
}
```

JS / TS code:

```
// these variables are used for "caching" so there is always only one active promise
let currentAcquireTokenPromise: Promise<string>;
let isCurrentAcquireTokenPromisePending: boolean;

export class MobileOpenIdService extends BaseAuthService {
  private readonly openIdClient: OpenIdClientPlugin = Plugins.OpenIdClient;

async acquireToken(): Promise<string> {
    if (currentAcquireTokenPromise && isCurrentAcquireTokenPromisePending) {
      return currentAcquireTokenPromise;
    }

    return (currentAcquireTokenPromise = this.acquireTokenInternal());
  }

  private async acquireTokenInternal() {
    isCurrentAcquireTokenPromisePending = true;

    try {
     // this is the actual call to the plugin
      const result = await this.openIdClient.acquireToken(this.config);
     // even though the call works, i.e. the plugins returns `call.success` this is SOMETIMES not called
      return result.accessToken;
    } finally {
     // same for this, sometimes this is NEVER called, the "app" is shown, but the promise is never resolved
      isCurrentAcquireTokenPromisePending = false;
    }
  }
}
```

I find it especially troubling that the code in the `finally` is never executed (tested via log statements) and the variable `isCurrentAcquireTokenPromisePending ` stays forever on `true` (because the promise is never resolved).

Any help or pointers are greatly appreciated!

**Comment by Nasicus** [comment]
Ok turns out I'm just stupid I forgot to call `saveCall(call);` before calling ` startActivityForResult(call, <intent>, RC_AUTH);` 

What still surprises me though is:
- Why does it work sometimes?
- Why does `getSavedCall()` always return an instance? I debugged a lot and it was NEVER null.

Would nice if someone could enlighten me here :)

**Comment by dwieeb** [comment]
@Nasicus Would you mind creating [a new discussion](https://github.com/ionic-team/capacitor/discussions) for your question(s)? Thanks 💙
