### ISSUE TITLE
bug: Adding router backButton Listener slows down navigation

### ISSUE THREAD

**Issue by updatesvc** [ionic-team/capacitor#3065]
#  Possible Bug 
Capacitor adding listener on each navigation request, slowing down navigation.
## Capacitor Version
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.1.2

  @capacitor/core: 2.1.2

  @capacitor/android: 2.1.2

  @capacitor/electron: 2.1.2

  @capacitor/ios: 2.1.2

Installed Dependencies:

  @capacitor/cli not installed

  @capacitor/core not installed

  @capacitor/android not installed

  @capacitor/ios not installed

  @capacitor/electron not installed

## Affected Platform(s)
- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
From my logcat I can see capacitor adding a listener multiple times

> 2020-06-06 20:02:18.022 13785-13785/app.xxx.xxx I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
> 2020-06-06 20:02:18.152 13785-13940/app.xxx.xxx V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 121754449, pluginId: App, methodName: addListener
> 2020-06-06 20:02:18.153 13785-13940/app.xxx.xxx V/Capacitor: callback: 121754449, pluginId: App, methodName: addListener, methodData: {"eventName":"backButton"}
> 2020-06-06 20:02:49.801 13785-13785/app.xxx.xxx I/Capacitor/Console: File: http://localhost/js/app.4e43e749.js - Line 1 - Msg: Navigation: feed
> 2020-06-06 20:02:49.802 13785-13785/app.xxx.xxx I/Capacitor/Console: File: http://localhost/js/app.4e43e749.js - Line 1 - Msg: Navigation:end
> 2020-06-06 20:02:50.907 13785-13940/app.xxx.xxx V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 121754450, pluginId: App, methodName: addListener
> 2020-06-06 20:02:50.908 13785-13940/app.xxx.xxx V/Capacitor: callback: 121754450, pluginId: App, methodName: addListener, methodData: {"eventName":"backButton"}
> 2020-06-06 20:02:56.768 13785-13785/app.xxx.xxx I/Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
> 2020-06-06 20:02:56.782 13785-13785/app.xxx.xxx I/Capacitor/Console: File: http://localhost/js/app.4e43e749.js - Line 1 - Msg: Navigation: chatList

More specifically from
**2020-06-06 20:02:49.802** to **2020-06-06 20:02:50.907**
There is a substantial delay before the page loads, my intuition tells me that probably this (adding the listener) is causing the load delay - also is there reason for capacitor to add the listener on every page load?

## Sample Code or Sample Application Repo
I don't have a sample, but its worth mentioning I have a a vue-ionic project
With **history mode** for routing

## Reproduction Steps

Happens on navigation

**Comment by jcesarmobile** [comment]
Capacitor doesn't add any listeners by default, your code (or vue-ionic code) is probably adding them
