### ISSUE TITLE
what is alternative for cordova-plugin-iosrtc in capacitor

### ISSUE THREAD

**Issue by pradeepmdk** [ionic-team/capacitor#3066]
cordova-plugin-iosrtc doesnot work on capacitor because of hooks. so i need iosrtc for capacitor in my project

**Comment by pradeepmdk** [comment]
cordova-plugin-iosrtc  doesnot work on capacitor  because of hooks. so i need iosrtc for capacitor in my project

**Comment by KyDenZ** [comment]
Try run extra/hooks/iosrtc-swift-support.js with node in module root folder. Then delete the line with the hook in plugin.xml

**Comment by jcesarmobile** [comment]
if a plugin doesn't work, best thing is probably creating a Capacitor plugin

**Comment by pradeepmdk** [comment]
> Try run extra/hooks/iosrtc-swift-support.js with node in module root folder. Then delete the line with the hook in plugin.xml



Showing All Messages
Undefined symbol: _OBJC_CLASS_$_RTCMediaConstraints

![Screen Shot 2020-06-20 at 10 03 47 PM](https://user-images.githubusercontent.com/16595846/85206785-eede1780-b341-11ea-8169-5e3bacefe9d8.png)
