### ISSUE TITLE
Failed to instantiate module ngCordova after migrated from ionic v1 to Capacitor

### ISSUE THREAD

**Issue by 19317362** [ionic-team/capacitor#3069]
I've an old project based on ionic v1.  The build env makes me crazy every time I want to change something.  npm & gulp & plugins , problems come here and there.

So I want try Capacitor to release me.

After my migration is done ,the build is ok with Xcode.  But error throwed when I tring to run.
The error info is 
```bash
Error: [$injector:modulerr] Failed to instantiate module starter due to:
[$injector:modulerr] Failed to instantiate module ngCordova due to:
[$injector:nomod] Module 'ngCordova' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

[WARN] Bad integration name: gulp

Ionic:

   Ionic CLI         : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.22

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 1.1.1, (and 16 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/wps/Library/Android/sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v14.4.0 (/usr/local/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina

**Comment by jcesarmobile** [comment]
this is not a Capacitor issue

**Comment by JaviDev08** [comment]
Try removing the package from the **ngCordova** ```bower uninstall ngCordova``` library and then install it again ```bower install ngCordova```.

If there are any errors related to the libraries, just remove the specific library and install it again.
