### ISSUE TITLE
bug: electron display nothing 

### ISSUE THREAD

**Issue by evalsxonted** [ionic-team/capacitor#3071]
# Bug Report
electron opened with empty screen 

## Capacitor Version
  @capacitor/cli: 2.1.2
  @capacitor/core: 2.1.2
  @capacitor/electron: 2.1.2

## Affected Platform(s)
- [ ] Android
- [ ] iOS
- [x ] Electron
- [ ] Web

## Current Behavior
nothing displayed
![Capture](https://user-images.githubusercontent.com/43685413/84051251-84c78900-a9b7-11ea-9bb0-0aca714708e6.PNG)

## Expected Behavior
this screen should be displayed
![Capture2](https://user-images.githubusercontent.com/43685413/84051278-914be180-a9b7-11ea-9533-1c7b9e1b05a8.PNG)

## Sample Code or Sample Application Repo
just a simple blank app created using this commands
`ionic start testapp blank --type=react --capacitor`
`npx cap add electron`

## Reproduction Steps
`ionic start testapp blank --type=react --capacitor`
`npx cap add electron`
Update the base href in the index.html file in public folder to `<base href="./" />`
In React projects package.json file, add `"homepage": "./",`
`ionic build`
`npx cap copy`
`npx cap open electron`

## Other Technical Details
"@ionic/react": "^5.0.7"
"react": "^16.13.0"
"typescript": "3.8.3"
"ionic": "5.4.16"
"npm": "6.13.4"
"node" : "v12.14.0"

## Other Information
so as a test i tried to replace the `ReactDOM.render(<App />, document.getElementById('root'));`
from `index.tsx` to `ReactDOM.render(<div>hola</div>, document.getElementById('root'));`
and then running `ionic build`, `npx cap copy`, `npx cap open electron`
the electron app started now with the word **hola** in the screen.
it looks like electron could load `index.tsx` file but not `app.tsx`  (in my opinion)

**Comment by jcesarmobile** [comment]
This is not a Capacitor issue, Capacitor just loads your app in electron, if you load your app in electron without using Capacitor you'll face the same problem.

The problem is ionic and IonReactRouter not working well when loaded from file protocol, you can use IonReactHashRouter instead, that seems to work. 
You can report the problem on ionic repository, but ionic doesn't officially support electron.

**Comment by IT-MikeS** [comment]
I have a fix for this and fixing the need to play with base-href settings that I am testing out for the next iteration of the electron platform but its not ready yet.

**Comment by evalsxonted** [comment]
IonReactHashRouter worked as charm. thanks 
`<IonApp>
    <IonReactHashRouter >
      <IonRouterOutlet>
        <Route path="/home" component={Home} exact={true} />
        <Route exact path="/" render={() => <Redirect to="/home" />} />
      </IonRouterOutlet>
    </IonReactHashRouter >
  </IonApp>`
