### ISSUE TITLE
feat: more specific device object 

### ISSUE THREAD

**Issue by bommariusser** [ionic-team/capacitor#3072]
# Feature Request

## Describe the Feature Request
We would like to be able to specify which device the users are on, and not just which platform they are on. So instead of iPhone we would like to get "iPhone X" back.

https://capacitor.ionicframework.com/docs/apis/device/#example

## Platform Support Requested

- [ ] Android
- [ ] iOS

**Comment by jcesarmobile** [comment]
Device object has a model property

**Comment by bommariusser** [comment]
woops thanks @jcesarmobile ! :D

**Comment by bommariusser** [comment]
@jcesarmobile although it says it only shows "iphone"? I'm pretty sure thats the one we're using already :)

**Comment by jcesarmobile** [comment]
On iOS it’s not possible to get the “marketing” name, only the “technical” name, so iPhone X would be iPhone10,3 (cdma) or iPhone10,6 (GSM)

**Comment by bommariusser** [comment]
Thanks for clarifying. Thats the one we're using but we only get "iPhone" back. Also we get "Macintosh" on tablet. You have any information on that?

**Comment by jcesarmobile** [comment]
by tablet you mean iPad?
iPads return iPad, unless you are testing on safari or using the web version of the plugin, in that case we try to guess the model from the user agent, but on iOS 13 the iPad user agent changed to be like safari desktop, so it returns the wrong value

**Comment by bommariusser** [comment]
@jcesarmobile This is what we get of information. Model is only which manufacturer and name is the name you have given your phone which by default is the model name (if you dont change it). in my own case this is Marvin's iPhone. 

Can you help us?
![Skærmbillede 2020-06-19 kl  14 50 21](https://user-images.githubusercontent.com/49033002/85134088-3aa69900-b23c-11ea-8ed6-eca3114234de.png)

**Comment by bommariusser** [comment]
but i guess we're using the web version of the plugin :D
