### ISSUE TITLE
Open external html in Capacitor Browser plugin

### ISSUE THREAD

**Issue by BadiuAlexandru** [ionic-team/capacitor#3075]
Hi there, I want to open an HTML string (coming from the server) using Browser plugin.

In ionic 3 I was doing something like this: 

```
  let htmlScript = "data:text/html;base64," + btoa(html);

  const browser: InAppBrowserObject = this.iab.create(htmlScript, "_blank", {
            location: "no",
            clearcache: "yes",
            hardwareback: "no",
            toolbar: "no"
  });
```

but now I use ionic 5 with Capacitor, and this approach doesn't work anymore. Is there any way to achieve this?

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.1.2

  @capacitor/core: 2.1.2

  @capacitor/android: 2.1.2

  @capacitor/electron: 2.1.2

  @capacitor/ios: 2.1.2

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed


  @capacitor/cli 2.1.0

  @capacitor/core 2.1.2

  @capacitor/android 2.1.2
```

**Comment by jcesarmobile** [comment]
SFSafariViewController only allows programmatically load http or https urls
It might work if you initially load a http or https url that redirects to the data url
not sure about android

but anyway, InAppBrowser and Browser plugins are different, if you need InAppBrowser plugin you can keep using it
