### ISSUE TITLE
[Camera, Features] Photos and pictures from the Gallery on Android too + Separate actions choices

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/capacitor#308]
[X] I would to submit two feature requests

**Current behavior**

When I use the Capacitor camera plugin, on iOS, I have the choice between importing a photo from the gallery or taking a picture. On Android, right now, I could "only" take a photo respectively I can't import from the gallery

Furthermore, with Cordova, the two actions should be called separately respectively the plugin doesn't handle the display of the choice (import or take photo, see `sourceType ` of https://github.com/apache/cordova-plugin-camera) to the user, it's him/her responsibility to do so. This is specially handy to let users customize their GUI and also to be able to handle internationalization themselves.

**Expected behavior**

It would be cool, in my point of view if

1. It would be also possible on Android to import pictures from the gallery too

2. I suggest to also separate the actions and therefore let the users handle themselves the display and internationalization of the two actions. Otherwise I think someday some requests like "Plz let us change the text in french or I want to display "Take photo" right to left in that language" will for sure popup

**Code**

Maybe something like:

    const imageUrl = await Camera.getPhoto({
          allowEditing: false,
          correctOrientation: false,
          height: 1080,
          width: 1080,
          quality: 90,
          resultType: CameraResultType.Base64,
          saveToGallery: false,
          sourceType: CameraSourceType. PHOTOLIBRARY | CameraSourceType. CAMERA
        });

**PWA**

Don't know if a source type photo gallery would work with a PWA too? Should just be the fallback camera with pwa?

**Screenshots**

<img width="406" alt="capture d ecran 2018-03-11 a 10 47 13" src="https://user-images.githubusercontent.com/16886711/37251987-3524e5a6-251a-11e8-9d3c-bc3467430d0e.png">

And what I meant with customizable GUI, here's a screenshot of my app where user has the choice to take a photo or import one from the gallery

![screenshot_20180311-105106](https://user-images.githubusercontent.com/16886711/37251994-55b43f10-251a-11e8-85ff-987e3b99e6de.png)

**Comment by mlynch** [comment]
Funny you should mention this was just thinking about it yesterday. Definitely will do this

**Comment by mlynch** [comment]
Cool just pushed this to master. I need to figure out what is up with the scaling issue #307 and test on device tomorrow, but will try to get a new release out with this feature tomorrow 🍻
