### ISSUE TITLE
bug: 'npx cap init' should add capacitor to integrations in 'ionic.config.json'

### ISSUE THREAD

**Issue by danielzen** [ionic-team/capacitor#3080]
# Bug Report
My specific problem is that I cannot run `ionic deploy add ...` after `npx cap init`.

However, in general, adding capacitor to an ionic project should add:
```
  "integrations": {
    "capacitor": {}
  },
```
to `ionic.config.json` 

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.1.2

  @capacitor/core: 2.1.2

  @capacitor/android: 2.1.2

  @capacitor/electron: 2.1.2

  @capacitor/ios: 2.1.2

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/electron not installed


  @capacitor/cli 2.1.2

  @capacitor/core 2.1.2

  @capacitor/ios 2.1.2
```

## Affected Platform(s)

- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Current Behavior

Attempts to run `ionic deploy add ...` reports an error with:
`It looks like your app isn't integrated with Capacitor or Cordova.`
despite the fact it was just done.

## Expected Behavior

`ionic.config.json` would now register that it was integrated with an ionic project.

## Reproduction Steps
  1. Create an Ionic project (do not integrate with Capacitor)
  2. Integrate with Capacitor using `npx cap init`

## Other Technical Details

`npm --version` output:
6.14.5

`node --version` output:
v12.16.1

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Capacitor is framework agnostic, so knows nothing about the framework you use.
If you use ionic use the ionic CLI to integrate capacitor, there are different commands to create ionic apps with capacitor integrated or to integrate it in existing apps, like `ionic integrations enable capacitor`
