### ISSUE TITLE
bug: Navigating to the app from an embedded WebView doesn't work in Android

### ISSUE THREAD

**Issue by cesalberca** [ionic-team/capacitor#3084]
## Bug Report

We are integrating a payments system with our app. It works perfectly on iOS, but navigating back to the app in Android doesn't work. We would like to open the payment system web page inside our app. To do that we have set this configuration in `capacitor.config.json`:

```json
{
  "server": {
    "allowNavigation": ["sis-t.redsys.es", "*.redsys.es"]
  }
}
```

Now, to integrate system is a bit tricky. We need a form component that triggers a post:

```html
<form ngNoForm #myFormPost action="https://sis-t.redsys.es:25443/sis/realizarPago" method="post">
  <input type="hidden" name="Ds_SignatureVersion" [value]="dsSignatureVersion" />
  <input type="hidden" name="Ds_MerchantParameters" [value]="dsMerchantParameters" />
  <input type="hidden" name="Ds_Signature" [value]="dsSignature" />
</form>
```

In our `app.component.ts` we have the following code:

```typescript
import { Component } from '@angular/core'
import { Router } from '@angular/router'
import { Capacitor, Plugins } from '@capacitor/core'

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss']
})
export class AppComponent {
  private url = new URL(window.location.href)

  constructor(private readonly router: Router) {}

  async ngOnInit() {
    if (this.url.searchParams.has('r')) {
      if (Capacitor.isNative) {
        await Plugins.App.openUrl({ url: this.url.href })
        await this.getLaunchUrl()
      } else {
        await this.router.navigateByUrl(this.url.href.split('.com').pop()!)
      }
    }
  }

  async getLaunchUrl() {
    const urlOpen = await Plugins.App.getLaunchUrl()
    if (urlOpen && urlOpen.url) {
      await this.router.navigateByUrl(this.url.href.split('://localhost').pop()!)
    }
  }
}
```

All of this works, as it opens the payment systems app. Now, this system allows us to set a redirect page in order to navigate back to our app. We have set `capacitor://localhost/store?r=ko`. As stated in the documentation the scheme for iOS is `capacitor://` and in Android is `http://`. So when we finish the operation and try to go back to app by clicking on the button on iOS it goes back to the app perfectly but with Android no.

We tried setting the url when we are in iOS to `capacitor://localhost/store?r=ko` and in Android to `http://localhost/store?r=ko`, however in Android, it tries to open the browser, which we don't want.

We have tried setting the `androidScheme` to `capacitor`, but it breaks the http requests. We also tried changing the `AndroidManifest.xml` property `android:launchMode` to `singleTop` as stated in [this issue](https://github.com/ionic-team/capacitor/issues/674#issuecomment-463987128). We tried changing the `strings.xml` as [stated in the documentation](https://capacitor.ionicframework.com/docs/android/configuration/#changing-custom-url) to the following:

```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">app</string>
    <string name="title_activity_main">app</string>
    <string name="package_name">com.app</string>
    <string name="custom_url_scheme">com.app</string>
</resources>
``` 

And set the callback url to `com.app://localhost/store?r=ko` but nothing.

We have tried some configuration with Deep links, but because we are inside the app it does not navigate to the app, as we are not coming from an external site.

### Capacitor Version

```
❯ npx cap doctor  
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.1.2

  @capacitor/core: 2.1.2

  @capacitor/android: 2.1.2

  @capacitor/electron: 2.1.2

  @capacitor/ios: 2.1.2

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.1.2

  @capacitor/ios 2.1.2

  @capacitor/core 2.1.2

  @capacitor/android 2.1.2

[error] Main Acitivity "com.technologyenergychain.MainActivity" is not in manifest package "test". Please update the packages to be the same.
```

### Platform(s)

- Android

### Expected Behavior

It should be able to navigate from an embedded WebView to the app in Android.

### Other Technical Details

`npm --version` output:
6.14.4

`node --version` output:
v12.17.0

**Comment by lorenzodianni** [comment]
I've the same problem but i detected that this happens only when a cordova plugin is used, so if I use a built in plugin like Geolocation the back button works fine.
If I use for example `cordova-plugin-insomnia`, `cordova-plugin-ble-central` or any `cordova-plugin-*` the go back button doesn't work properly.

It seems that when using cordova plugins, the navigation does not trigger angular lifecycle hooks (OnChanges, OnInit, etc...), only constructor is called.

If you try with a simple component to log the OnInit hook, it won't be triggered on navigation back

```ts
@Component({
  selector: 'app-foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FooComponent implements OnInit {
  public ngOnInit(): void {
    console.log('ngOnInit', this.constructor.name);
  }
}
```

**Comment by viktor-berezin** [comment]
I've the same problem. My case is: I have opened some external URL in the Webview (for the oauth2). the HTTP request that created from this external URL returns response with location header. Location header has custom url scheme url for redirect back to the application Webview.
Problem is that custom URLs are not working from the capacitor WebViews.

Hi @cesalberca, did you find any workaround for this moment?

**Comment by DSergiu** [comment]
Seems related to this issue https://github.com/ionic-team/capacitor/issues/4240 .
