### ISSUE TITLE
bug: Unable to get http request using Angular HttpClient when using capacitor build in android

### ISSUE THREAD

**Issue by joeldacuma** [ionic-team/capacitor#3087]
## Bug Report
I can't GET http request when I am building my ionic app in android using angular httpClient

### Capacitor Version

  @capacitor/cli: 2.2.0

  @capacitor/core: 2.2.0

  @capacitor/android: 2.2.0

  @capacitor/electron: 2.2.0

  @capacitor/ios: 2.2.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed

  @capacitor/cli 2.1.2

  @capacitor/core 2.1.2

  @capacitor/android 2.1.2

```
Failed to load resource: net::ERR_CONNECTION_REFUSED
```
### Platform(s)
Android 10  & below...

### Current Behavior
I am trying to do get request using httpClient from angular. It is working fine on browser but when I build the app in android the request is not working.

### Expected Behavior
Retrieve my data from my external api.

### Other Technical Details

`npm --version` output: 6.4.1

`node --version` output:v10.14.2

**Comment by jcesarmobile** [comment]
> Android 9 & below...

So it works in Android 10 but not in older versions?
Do you use http or https?
Do you have cors configured?

**Comment by joeldacuma** [comment]
> > Android 9 & below...
> 
> So it works in Android 10 but not in older versions?
> Do you use http or https?
> Do you have cors configured?

I also tried API 29 - android 10 and API 22 - lollipop and seems it is also not working.
I used both http and https.
I configured cors in my server that is my it is working fine in browser but not working when I build it in android.

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by joeldacuma** [comment]
Already resolved the issue I enable SSL to my server. Just wondering why http didn't work.

**Comment by jcesarmobile** [comment]
http connections don't work on Android 9+ unless you enable cleartext traffic, but you said it didn't work on android lolipop nor on https connections
