### ISSUE TITLE
bug: Crashlytics could not find the manifest.

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/capacitor#3100]
Hi,

I use FirebaseX on Ionic 5 capacitor app: https://ionicframework.com/docs/native/firebase-x

It gives 2 errors on the Android studio build.

`file google-services.json is missing. the google services plugin cannot function without it. `

`Crashlytics could not find the manifest. Not found at D:\Clients\android\capacitor-cordova-android-plugins\build\intermediates\merged_manifests\debug\AndroidManifest.xml`

package.json

```
{
  "name": "my",
  "version": "1.0.0",
  "author": "my",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "9.1.6",
    "@angular/core": "9.1.6",
    "@angular/fire": "6.0.0",
    "@angular/forms": "9.1.6",
    "@angular/platform-browser": "9.1.6",
    "@angular/platform-browser-dynamic": "9.1.6",
    "@angular/router": "9.1.6",
    "@capacitor/android": "^2.1.0",
    "@capacitor/core": "2.2.0",
    "@ionic-native/core": "5.26.0",
    "@ionic-native/firebase-x": "^5.26.0",
    "@ionic-native/screen-orientation": "^5.26.0",
    "@ionic/angular": "5.1.1",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular2-signaturepad": "^2.11.0",
    "cordova-plugin-androidx": "^2.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.1",
    "cordova-plugin-firebasex": "^9.1.2-cli",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "dayjs": "^1.8.27",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "7.15.0",
    "rxjs": "6.5.1",
    "signature_pad": "^3.0.0-beta.3",
    "tslib": "1.10.0",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": "<0.900 || ^0.900.0-0 || ^9.0.0-0",
    "@angular-devkit/build-angular": "^0.901.7",
    "@angular/cli": "9.1.5",
    "@angular/compiler": "9.1.6",
    "@angular/compiler-cli": "9.1.6",
    "@angular/language-service": "9.1.6",
    "@capacitor/cli": "2.1.0",
    "@ionic/angular-toolkit": "2.1.1",
    "@types/node": "12.11.1",
    "codelyzer": "5.1.2",
    "firebase-tools": "8.4.2",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "ts-node": "8.3.0",
    "tslint": "6.1.0",
    "typescript": "3.8.3"
  },
  "description": "my"
}
```

**Comment by jcesarmobile** [comment]
please, when reporting issues provide al the information requested by the template.

looks like that plugin has some problems with capacitor, here you can see some workarounds
https://stackoverflow.com/a/61281829/1351469

For the first problem do: `cp android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml android/capacitor-cordova-android-plugins/build/intermediates/merged_manifests/debug/AndroidManifest.xml`

then you'll get a complain about accent color not found, so create a `colors.xml` resource file in your app and add `<color name="accent">#hex_color_here</color>` value

**Comment by Sampath-Lokuge** [comment]
Ok sure. Thanks for the feedback. 
I have used the `Firebase Authentication` plugin and it is working fine on Android/Capacitor.  I'll update my experience here with iOS later. https://ionicframework.com/docs/native/firebase-authentication
