### ISSUE TITLE
bug: Android Studio offline mood

### ISSUE THREAD

**Issue by pioneersingh321** [ionic-team/capacitor#3101]
### Capacitor Version
latest vrsion 2.20

PASTE OUTPUT HERE
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-location:16.+.
Disable offline mode and sync project
Show Details
Affected Modules: app

### Platform(s)
android

**Comment by jcesarmobile** [comment]
please, when creating issues provide all the information requested by the template and a sample project.

some plugin is adding a dependency to `com.google.android.gms:play-services-location:16.+`, which is very old and doesn't support Android X, the plugin should be updated to use a newer version version
