### ISSUE TITLE
feat: configure path for index.html

### ISSUE THREAD

**Issue by devpascoe** [ionic-team/capacitor#3104]
### Description
As a vendor, I'd like to wrap up a Capacitor app as a standalone cocoapod library so other native iOS users can implement my pod without ever knowing about capacitor. ie, wrap dependencies and assets etc. in the podspec. I can create a podspec with a dependency on Capacitor and CapacitorCordova however i still need to copy capacitor.config.json, config.xml and public to the root of the consuming app.

Likely a similar process for android / gradle & maven.

Here is something similar to what i'd like to achieve. https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-c---embed-application-and-plugin-frameworks-in-xcode-and-flutter-framework-with-cocoapods

**Comment by dwieeb** [comment]
Merging into "Embedded Capacitor" issue: https://github.com/ionic-team/capacitor/issues/3182
