### ISSUE TITLE
bug: adding listener on each navigation request, slowing down navigation.

### ISSUE THREAD

**Issue by updatesvc** [ionic-team/capacitor#3108]
#  Possible Bug 
Capacitor adding listener on each navigation request, slowing down navigation.
Had opened similar issue here  #3065 

## Capacitor Version
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.1.2

  @capacitor/core: 2.1.2

  @capacitor/android: 2.1.2

  @capacitor/electron: 2.1.2

  @capacitor/ios: 2.1.2

Installed Dependencies:

  @capacitor/cli not installed

  @capacitor/core not installed

  @capacitor/android not installed

  @capacitor/ios not installed

  @capacitor/electron not installed

## Affected Platform(s)
- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
From my logcat I can see capacitor adding a listener multiple times

> 2020-06-06 20:02:18.022 13785-13785/app.xxx.xxx I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
> 2020-06-06 20:02:18.152 13785-13940/app.xxx.xxx V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 121754449, pluginId: App, methodName: addListener
> 2020-06-06 20:02:18.153 13785-13940/app.xxx.xxx V/Capacitor: callback: 121754449, pluginId: App, methodName: addListener, methodData: {"eventName":"backButton"}
> 2020-06-06 20:02:49.801 13785-13785/app.xxx.xxx I/Capacitor/Console: File: http://localhost/js/app.4e43e749.js - Line 1 - Msg: Navigation: feed
> 2020-06-06 20:02:49.802 13785-13785/app.xxx.xxx I/Capacitor/Console: File: http://localhost/js/app.4e43e749.js - Line 1 - Msg: Navigation:end
> 2020-06-06 20:02:50.907 13785-13940/app.xxx.xxx V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 121754450, pluginId: App, methodName: addListener
> 2020-06-06 20:02:50.908 13785-13940/app.xxx.xxx V/Capacitor: callback: 121754450, pluginId: App, methodName: addListener, methodData: {"eventName":"backButton"}
> 2020-06-06 20:02:56.768 13785-13785/app.xxx.xxx I/Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
> 2020-06-06 20:02:56.782 13785-13785/app.xxx.xxx I/Capacitor/Console: File: http://localhost/js/app.4e43e749.js - Line 1 - Msg: Navigation: chatList

More specifically from
**2020-06-06 20:02:49.802** to **2020-06-06 20:02:50.907**
There is a substantial delay before the page loads, my intuition tells me that probably this (adding the listener) is causing the load delay - also is there reason for capacitor to add the listener on every page load?

## Sample Code or Sample Application Repo
I don't have a sample, but its worth mentioning I have a a vue-ionic project
With **history mode** for routing

After doing some more investigation searched every where the code was adding listeners and added console.log to help tracing
Found this part in the native-bridge
**core/native-bridge.js**
https://github.com/ionic-team/capacitor/blob/d4b8457bda57fdbc58fdc8d107eb14b37fd6edfc/core/native-bridge.js#L14

https://github.com/ionic-team/capacitor/blob/d4b8457bda57fdbc58fdc8d107eb14b37fd6edfc/core/native-bridge.js#L124

From the comments, it says its for Cordova compatibility.
Just curious what implications are there in removing/commenting it out.
Also does adding multiple listeners all the time affect/bloats the event queue?

## Reproduction Steps

Happens on navigation

![image](https://user-images.githubusercontent.com/18010106/84660270-42ef9300-af21-11ea-86ac-cc113dbabba9.png)

**Comment by jcesarmobile** [comment]
As I said in the other issue, Capacitor doesn't add any listener, your app does (or probably ionic-vue)
what the code you point out does is to "convert" existing calls of `document.addEventListener("backbutton");` to `Capacitor.Plugins.App.addListener('backButton', function() {});`, so if you see that call is because there is some call to `document.addEventListener("backbutton");`

I think you can configure ionic to not add that event listener with this config option https://github.com/ionic-team/ionic/blob/master/core/src/utils/config.ts#L25, but don't know if it works in vue projects.

**Comment by updatesvc** [comment]
Thanks
