### ISSUE TITLE
Ionic CLI Integration

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#311]
Placeholder for integration of Capacitor into Ionic CLI for the beta

**Comment by mlynch** [comment]
Made good progress on this today, follow along at home here: https://github.com/ionic-team/ionic-cli/pull/3037

**Comment by dwieeb** [comment]
Further progress can be tracked in the Capacitor milestone of the CLI repo: https://github.com/ionic-team/ionic-cli/milestone/40
