### ISSUE TITLE
feat: hostname and scheme name

### ISSUE THREAD

**Issue by videmort** [ionic-team/capacitor#3113]
### Description
Posibility to edit hostname and scheme name serving the application like 
https://github.com/ionic-team/cordova-plugin-ionic-webview

### Platform(s)
iOS
Android

### Preferred Solution
Same as --> https://github.com/ionic-team/cordova-plugin-ionic-webview

### Additional Context
It's important to serve different schemes in order for example to enable or disable google maps api key.

Serving localhost using for example google services such maps is very risky.

More info in this fixed issue 
https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/283

**Comment by jcesarmobile** [comment]
it's already configurable, check https://capacitor.ionicframework.com/docs/basics/configuring-your-app#common-configuration for `iosScheme`, `androidScheme` and `hostname`

**Comment by videmort** [comment]
@jcesarmobile  gracias
