### ISSUE TITLE
Barcode Scanner Plugin

### ISSUE THREAD

**Issue by nehajaideep** [ionic-team/capacitor#3114]
Kindly add barcode scanner plugin for capacitor.

**Comment by dwieeb** [comment]
Issues tagged with plugin request are closed but tracked for 👍 reactions to gauge interest.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/6. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
