### ISSUE TITLE
bug: peerDependency versions wrong in 2.2.0

### ISSUE THREAD

**Issue by tomwidmer** [ionic-team/capacitor#3118]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/core 2.2.0

  @capacitor/ios 2.2.0

  @capacitor/cli 2.2.0

  @capacitor/android 2.2.0

```

### Platform(s)

iOS, Android

### Current Behavior

peerDependency version of @capacitor/core in both @capacitor/ios@2.2.0 and @capacitor/android@2.2.0 is set to ~2.1.0.
As a result warnings occur during installation, and `npm list` errors (causing my CI build to fail).

### Expected Behavior

Obviously it should be ~2.2.0. The peer dependency versions need to be incremented before every minor release. Probably the release script should be updated to check this, since it also was a bug in the prior version (#2893 etc.)

### Other Technical Details

`npm --version` output: 6.14.4
`node --version` output: v12.18.0

**Comment by jcesarmobile** [comment]
it's already fixed, but not released yet
