### ISSUE TITLE
Manifest.xml not found

### ISSUE THREAD

**Issue by vishal-bluesys** [ionic-team/capacitor#312]
Error:Android Source Generator: [parent] AndroidManifest.xml file not found

**Comment by jcesarmobile** [comment]
Can you provide a bit more information?
How did you create the project?
What command did you run before getting that error?
Which Capacitor version are you using?

**Comment by vishal-bluesys** [comment]
step1 ionic start myApp tabs ---to create ionic project
          then I selected N (No) when asked to install cordova libs 
step 2 npm run build
step 3 installed capacitor 
           npm install --save @capacitor/cli @capacitor/core
step 4  initialize capcitor 
           npx cap init parent  com.ibluesys.parent
step 5 add android platform
          npx cap add android
step 6 configured capicitor.cofig.json
          {
             "appId": "com.ibluesys.parent",
             "appName": "parent",
             "bundledWebRuntime": false,
             "webDir": "www",
             "windowsAndroidStudioPath": "C:\\Program Files\\Android\\Android Studio1\\bin"
         }
step 7 : opened in android studio IDE 
            npx cap open android
step 8 : npx cap copy
           then I tried to build apk

**Comment by mlynch** [comment]
Can you copy and paste the output of running this command in your app folder:

`ls android/app/src/main`
