### ISSUE TITLE
bug: ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by hanung** [ionic-team/capacitor#3124]
### Capacitor Version

@capacitor/cli 2.1.2

  @capacitor/android 2.1.2

  @capacitor/ios 2.1.2

  @capacitor/core 2.1.2

### Platform(s)

iOS

### Current Behavior

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

### Other Technical Details

`npm --version` output: 6.14.4

`node --version` output:v12.16.2

`pod --version` output (iOS issues only):1.9.1

### Additional Context

"dependencies": {
    "@angular/common": "^9.1.4",
    "@angular/core": "^9.1.4",
    "@angular/fire": "6.0.0",
    "@angular/forms": "^9.1.4",
    "@angular/platform-browser": "^9.1.4",
    "@angular/platform-browser-dynamic": "^9.1.4",
    "@angular/router": "^9.1.4",
    "@angular/service-worker": "^9.1.4",
    "@capacitor/android": "^2.1.2",
    "@capacitor/cli": "^2.1.2",
    "@capacitor/core": "^2.1.2",
    "@capacitor/ios": "^2.1.2",
    "@ionic-native/core": "^5.26.0",
    "@ionic-native/db-meter": "^5.26.0",
    "@ionic/angular": "^5.1.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@rdlabo/capacitor-firebase-crashlytics": "^1.0.1",
    "angular-pipes": "^10.0.0",
    "capacitor-firebase-auth": "^0.3.1",
    "cordova-plugin-dbmeter": "^2.1.0",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "core-js": "^2.6.11",
    "dayjs": "^1.8.26",
    "firebase": "^7.14.2",
    "google-libphonenumber": "^3.2.9",
    "jetifier": "^1.6.5",
    "npm": "^6.14.5",
    "rxjs": "6.5.5",
    "tslib": "^1.11.2",
    "videogular2": "^7.0.2",
    "zone.js": "~0.10.2"
  }

I am using a capacitor. I don't know where I am using UIWebView. How do I fix it?

**Comment by jcesarmobile** [comment]
Capacitor doesn't use reference UIWebView since 1.4.0
The problem is capacitor-firebase-auth
https://github.com/baumblatt/capacitor-firebase-auth/issues/76

**Comment by hanung** [comment]
@jcesarmobile Thank you!
