### ISSUE TITLE
bug: Default keyboard appears on numeric inputs

### ISSUE THREAD

**Issue by sergiocarneiro** [ionic-team/capacitor#3130]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.2.0

  @capacitor/core: 2.2.0

  @capacitor/android: 2.2.0

  @capacitor/electron: 2.2.0

  @capacitor/ios: 2.2.0

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.2.0

  @capacitor/core 2.2.0

  @capacitor/ios 2.2.0

  @capacitor/android 2.2.0

[success] Android looking great!
[error] Xcode is not installed
```

### Platform(s)
* Android

_(Haven't tested others)_

### Current Behavior
Default keyboard opens.

### Expected Behavior
Numeric keyboard opens.

### Code Reproduction
* Add an `<ion-input>` or `<input>` element
* Regardless of the _type_, _pattern_, _inputmode_, it will always open the default keyboard.

### Other Technical Details
* Android Version: 7.0

**Comment by jcesarmobile** [comment]
just tried with `<input  type="number">` and it's showing the number keyboard

**Comment by achakra21** [comment]
I am facing same issue the default keyboard open for the first-time
