### ISSUE TITLE
bug: Switch must be exhaustive (Xcode 12)

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/capacitor#3134]
## Bug Report

Compiling an Capacitor app with Xcode 12 causes some build error like not exhaustive switch statements in the `Permissions.swift` file

**Comment by jcesarmobile** [comment]
was fixed in https://github.com/ionic-team/capacitor/pull/3160

**Comment by Abhi0725** [comment]
For others having this issue run:

`npm install @capacitor/ios@latest`

then sync the project:

`npx cap sync ios`

**Comment by gubbigubbi** [comment]
> For others having this issue run:
> 
> `npm install @capacitor/ios@latest`
> 
> then sync the project:
> 
> `npx cap sync ios`

Confirmed - fixed for me
