### ISSUE TITLE
Camera use with one time user permission.

### ISSUE THREAD

**Issue by pooriaPoorsarvi** [ionic-team/capacitor#3136]
Camera use with one-time user permission.

There might be lots of scenarios in which a service might be done using the image captured automatically to do automatic computations. This is common in computer vision projects. So can there be a feature where we ask the user permission for taking pictures once and then use the camera as a webcam at specific times?

I know that some platforms have specific solutions for this such as android: https://stackoverflow.com/questions/9752730/take-a-photo-automatically-without-user-interaction/11771325, but can there be a universal solution to this in ionic?

**Comment by IT-MikeS** [comment]
@dwieeb perhaps as a community plugin?

**Comment by dwieeb** [comment]
Yeah, if I'm understanding this correctly, this should be a plugin proposal. Capacitor will not have this functionality in core.

@pooriaPoorsarvi Please create a plugin proposal for this: https://github.com/capacitor-community/proposals/
