### ISSUE TITLE
Error while using camera plugin:

### ISSUE THREAD

**Issue by mu250234** [ionic-team/capacitor#314]
![image](https://user-images.githubusercontent.com/12996089/37290843-5133d3c8-2633-11e8-8937-eb9a2890c1e2.png)
Hi, I followed https://capacitor.ionicframework.com/docs/apis/camera/ tutorial to accomplish camera app through ionic capacitor.Please anyone suggest me what went wrong.

**Comment by jcesarmobile** [comment]
Can you provide more details?
In which platform were you testing?
You mean the Capacitor camera plugin or the Cordova camera plugin?
What error message did you get?

**Comment by mu250234** [comment]
Hi Thanks for quick response, testing with capacitor camera.

**Comment by mlynch** [comment]
You need to import `CameraResultType` and use the param now:

```
import { CameraResultType } from '@capacitor/core';

Camera.getPhoto({
  resultType: CameraResultType.Base64
})
```
