### ISSUE TITLE
Remove electron platform

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3140]
The provided electron platform needs to be removed from the repo and the CLI (and wherever else). 

- We are recommending the Capacitor Community electron platform: https://github.com/capacitor-community/electron
- We could add a message when people do `npx cap add electron` and `@capacitor-community/electron` is not installed.

**Comment by Berkmann18** [comment]
Is there a reason why `@capacitor/cli@2.4.0` still uses that electron platform and yet prints
```
[success] electron looking great! 👌
[warn] The electron platform is deprecated!
```
?
I'm confused as to why the latest version does that when I suppose it would have used the right platform.

**Comment by dwieeb** [comment]
I'm not sure I understand the question, but the Electron platform is deprecated in 2.x and will be removed in Capacitor 3. We're not going to remove it in 2.4 or any future 2.x release because it would be a breaking change.

**Comment by Berkmann18** [comment]
That makes sense, it just odd.
