### ISSUE TITLE
bug: Android Keyboard Input Type not working 

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/capacitor#3168]
### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 2.2.0

  @capacitor/core: 2.2.0

  @capacitor/android: 2.2.0

  @capacitor/electron: 2.2.0

  @capacitor/ios: 2.2.0

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.2.0

  @capacitor/ios 2.2.0

  @capacitor/android 2.2.0

  @capacitor/core 2.2.0

[success] Android looking great! �
```

### Platform(s)
Android

### Current Behavior
![image](https://user-images.githubusercontent.com/19570043/85959386-72c87d00-b99c-11ea-89ec-f0fdfc5fdda6.png)
![image](https://user-images.githubusercontent.com/19570043/85959396-8d025b00-b99c-11ea-882a-ad4adaa3e436.png)
I try to use the Android Input Keyboard Types e.g. for the E-Mail Address. 

### Expected Behavior
![image](https://user-images.githubusercontent.com/19570043/85959426-d0f56000-b99c-11ea-9e89-090aba7373c1.png)
The Keyboard Type never changes. 

### Code Reproduction
Screenshot above.

**Comment by jcesarmobile** [comment]
Please, when providing code reproduction, provide it as text, not as an image.

I've tested this three fields, ion-input with inputmode set to email, ion-input with type set to email and regular input with type email and all 3 worked fine.

```
<ion-input inputmode="email"></ion-input>
<ion-input type="email"></ion-input>
<input type="email">
```

Anyway, Capacitor doesn't handle the keyboard, that's handled by the WebView and we can't control it, so if you are having this problem, report it in the chromium issue tracker.
