### ISSUE TITLE
feat: ability to set values on WKWebViewConfiguration for iOS WebView

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3179]
### Description

Ability to modify `WKWebViewConfiguration` values such as `ignoresViewportScaleLimits`.

### Platform(s)

iOS

### Preferred Solution

Configuration-based approach.

### Alternatives

Ability to Subclass top-level Capacitor objects like BridgeViewController

### Additional Context

Initial PR for this feature is here: https://github.com/ionic-team/capacitor/pull/2028

**Comment by jcesarmobile** [comment]
It's possible now by subclassing `CAPBridgeViewController` and overriding [`webViewConfiguration(for:)`](https://github.com/ionic-team/capacitor/blob/bd59fa3637ec32280864cee4d649267274109e5a/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L101) to modify the configuration before the web view gets created.
