### ISSUE TITLE
feat: Update path when opening from WSL

### ISSUE THREAD

**Issue by chopfitzroy** [ionic-team/capacitor#3186]
## Feature Request

When opening Android Studio from a WSL instance it would be useful to be able to remove `C:\mnt\...` from the file path, this would allow uses to use the `open` command from WSL.

### Description

I am running WSL 1 and have the project files stored on my window partition.

I have added the following line to my `capacitor.config.js`:

```
"linuxAndroidStudioPath": "/mnt/c/Program Files/Android/Android Studio/bin/studio64.exe"
```

But when I run:

```
cap open android
```

I get the following:

![image](https://user-images.githubusercontent.com/2978850/86186174-82a6b380-bb8c-11ea-957d-2b9eb3a16cf1.png)

### Platform(s)

- Windows (This is a dev experience update)

### Preferred Solution

This solution allows the user to still run "Android Studio" on their host (Windows) machine.

### Alternatives

Other solutions tend to involve running "Android Studio" in the WLS instance itself (using WLS 2 and binding the X Server) see this [comment](https://github.com/ionic-team/capacitor/issues/2691#issuecomment-648097816) for more info.

### Additional Context

I think the solution provides a nice middle ground for handling this, in theory it should be a relatively minimal change in terms of changing the file path handed to "Android Studio" however I realize it may not be this simple.

**Comment by birnam** [comment]
A complication on this (much desired) feature is that some people use a modified mount point. For instance I have C: at /c instead of /mnt/c. (It's an easy configuration change that saves typing and makes paths easier for me to read.)  https://blog.davidjeddy.com/2019/02/25/moving-where-wsl-mounts-the-windows-c-drive

**Comment by lpil** [comment]
> A complication on this (much desired) feature is that some people use a modified mount point. 

In this case could we add an additional configration option for the path prefix?

**Comment by jcesarmobile** [comment]
linuxAndroidStudioPath config option no longer exists on capacitor 3, closing
