### ISSUE TITLE
[Camera] App crash on Android if source=Photos and correctOrientation=true

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/capacitor#319]
[X] I would to submit a bug

**Current behavior**

I just tested the new option which let import photos from the gallery on Android. It works just fine except if the developer set `correctOrientation` to `true` in case he would like to import only photos from the gallery

    const imageUrl = await Camera.getPhoto({
      allowEditing: false,
      correctOrientation: true, // <------------ oups
      height: 1080,
      width: 1080,
      quality: 90,
      resultType: CameraResultType.Base64,
      saveToGallery: false, 
      source: CameraSource.Photos
    });

This will crash the app, once the photo has been selected in the gallery and we go back to the app

**Expected behavior**

No crash

**Side note**

I could reproduce this error on both Android 8.1 and 7.0

**Comment by mlynch** [comment]
Fixed, will be in the next release. Thanks!

**Comment by peterpeterparker** [comment]
@mlynch so fast, thx for the fix 👍

**Comment by mlynch** [comment]
🚀 we're wasting no time getting Capacitor to production ready, it's gotta be :100: or no one will use it

**Comment by peterpeterparker** [comment]
I like this spirit 👍

I'll try to find time later on this end of week to continue to play with the 📷

**Comment by alaswer** [comment]
I'm facing this issue, I'm allowing users to select from photos or take camera and editing is allowed

`await Camera.getPhoto({
      quality: 70,
      width: 800,
      allowEditing: true,
      correctOrientation: true,
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Prompt
    })`

I'm using the following capacitor dependencies:

`"@capacitor/android": "^1.4.0",
    "@capacitor/core": "1.4.0",
    "@capacitor/ios": "^1.4.0",`

**Comment by snow-drop** [comment]
Same here with the following configuration in Android:

```
cameraOptions () {
    return {
        quality: 25,
        allowEditing: true,
        correctOrientation: true,
        resultType: CameraResultType.Uri
    }
}
```
Just when the file is going to be saved from Camera or a photo being selected from the gallery. So far I can't find any resources that can help get through it.
