### ISSUE TITLE
Support subclassing of CAPBridgeViewController on iOS

### ISSUE THREAD

**Issue by ikeith** [ionic-team/capacitor#3191]
Allow for subclassing CAPBridgeViewController.
Provide override points to child classes for customization and configuration that don't make sense in plugins or the configuration file.
Related to [embedded Capacitor](https://github.com/ionic-team/capacitor/issues/3182)

**Comment by dwieeb** [comment]
resolved by https://github.com/ionic-team/capacitor/pull/3973
