### ISSUE TITLE
bug: cannot upgrade @capacitor packages to latest with yarn

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/capacitor#3196]
Related: https://github.com/ionic-team/capacitor/issues/3188

I've upgraded all 4 `@capacitor` packages to 2.2.1 and this command still fails. I would expect this command to work (e.g. exit 0) regardless if there is an upgrade available.  It seems that even now, when there isn't an upgrade, it's throwing an error.

```
yarn add @capacitor/core@latest @capacitor/android@latest @capacitor/ios@latest @capacitor/cli@latest

yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@ionic/angular-toolkit > copy-webpack-plugin@5.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > @capacitor/android@2.2.1" has incorrect peer dependency "@capacitor/core@~2.2.0".
warning " > @capacitor/ios@2.2.1" has incorrect peer dependency "@capacitor/core@~2.2.0".
error An unexpected error occurred: "expected manifest".
```

It's worth noting that similar commands work just fine for `@ionic` `@ionic-native` `@angular` `@angular-devkit` packages - something still isn't right with the `@capacitor` packages.

**Comment by jcesarmobile** [comment]
This looks like a yarn bug to me.
I use npm and I no longer get the warnings after updating ios and android to 2.2.1

**Comment by josh-m-sharpe** [comment]
Don't think that last comment was very helpful.

1) This is a yarn problem not npm
2) The issue results in errors, not warnings
3) Upgrading multiple packages with yarn works for all other package groups (across multiple projects).  Capacitor is the only exception I've seen.

**Comment by jcesarmobile** [comment]
> 1. This is a yarn problem not npm

agreed, is a yarn issue, you should report it in yarn repository
