### ISSUE TITLE
bug: Altitude is always returning null

### ISSUE THREAD

**Issue by kpm563** [ionic-team/capacitor#3199]
### Capacitor Version

```
npx cap doctor output:

-- Capacitor Doctor --

Latest Dependencies:

  @capacitor/cli: 2.2.1       
  @capacitor/core: 2.2.1      
  @capacitor/android: 2.2.1   
  @capacitor/electron: 2.2.1  
  @capacitor/ios: 2.2.1       

Installed Dependencies:       

  @capacitor/ios not installed
  @capacitor/cli 2.2.1    
  @capacitor/core 2.2.1   
  @capacitor/android 2.2.1
  @capacitor/electron not installed 
```

### Platform(s)

platform: android

### Current Behavior

Altitude is always returning null in the android device(eg: Redmi Note 8) as well as browser.

![altitude](https://user-images.githubusercontent.com/30753279/86351026-34bfa780-bc81-11ea-9dc3-605f5157aae7.png)

### Expected Behavior

Plugins.Geolocation.getCurrentPosition(options); method should return current altitude of device.

Sample Code:
```
  async locate() {
    const options: GeolocationOptions = {
      enableHighAccuracy: true,
    };

    const location: GeolocationPosition = await Plugins.Geolocation.getCurrentPosition(options);
    console.log(location);
  }
```

### Code Reproduction

1. Create a new ionic project based on capacitor
2. Use the example code to check the result.

### Other Technical Details

`npm --version` output:
6.14.5
`node --version` output:
v12.11.0
`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
altitude might not be available, in that case it returns null and there is nothing we can do about it.

Tf you check the types, it's mentioned that might not be available

```
    /**
     * The altitude the user is at (if available)
     */
    altitude?: number;
```

https://github.com/ionic-team/capacitor/blob/26e5e7415a1b61e374997d9a4a18003746fa0704/core/src/core-plugin-definitions.ts#L896-L899

The docs site is not showing the types information correctly, I've reported it here https://github.com/ionic-team/capacitor-site/issues/49
