### ISSUE TITLE
bug: ionic appflow wont compile due to missing android strings configuration

### ISSUE THREAD

**Issue by skibaalex** [ionic-team/capacitor#3221]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.2.0

  @capacitor/core 2.2.0

  @capacitor/android 2.2.0

  @capacitor/ios 2.2.0

[success] Android looking great! 👌
  Found 5 Capacitor plugins for ios:
    @mauron85/cordova-plugin-background-geolocation (3.1.0)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-device (2.0.3)
    cordova-plugin-whitelist (1.3.4)
    phonegap-plugin-barcodescanner (8.1.0)
[success] iOS looking great! 👌
```

### Platform(s)

Android

### Current Behavior
Everything  work great on the local environment but wont compile on the Appflow dashboard

### Code Reproduction

ERROR:
`error: resource string/mauron85_bgloc_content_authority (aka capacitor.android.plugins:string/mauron85_bgloc_content_authority) not found.`
 
need to add the following code to the strings.xml file
`<string name="mauron85_bgloc_account_name">@string/app_name</string>
<string name="mauron85_bgloc_account_type">$PACKAGE_NAME.account</string>
<string name="mauron85_bgloc_content_authority">$PACKAGE_NAME</string>`

### Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: v12.16.3

**Comment by dwieeb** [comment]
Please use our [customer support](https://ionicframework.com/support) for Appflow issues. Thanks!
