### ISSUE TITLE
feat(iOS): Support initWithSuiteName in Storage plugin

### ISSUE THREAD

**Issue by BorntraegerMarc** [ionic-team/capacitor#3223]
### Description

In iOS `UserDefaults` one can init it with a `suiteName`. This is needed e.g. when different `Extensions` want to share data between them. Capacitor should support this.

Example: https://github.com/TheCocoaProject/cordova-plugin-nativestorage#ios-specific-features

### Platform(s)

- iOS

### Preferred Solution

Having an `init` function where the optional property `suiteName` can be specified.

**Comment by jcesarmobile** [comment]
closing as duplicate of https://github.com/ionic-team/capacitor/issues/2253

**Comment by BorntraegerMarc** [comment]
I completely forgot to search through existing issues. Sorry about this! Thanks!
