### ISSUE TITLE
Capacitor 3.x Plugins

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3227]
Welcome to the plugin planning issue! Subscribe to this issue for updates. It will be updated periodically until the launch date (TBD). We've locked this issue, but we highly encourage you to [open a discussion](https://github.com/ionic-team/capacitor/discussions) if you have questions or suggestions.

---

As part of planning for Capacitor 3, the team has rethought core plugins. The concept of Capacitor being "batteries-included" is attractive, but additional use cases (e.g. "Embedded Capacitor"), App Store warnings and rejections and app bloating and slowdowns (e.g. #4038, #2992, #1942), and better available alternatives (e.g. community or third-party plugins that are better than a core plugin), have caused us to reevaluate including the core plugins in Capacitor.

While we may be splitting plugins into their own packages, the Capacitor CLI may still offer a set of plugins to be installed by default (and optionally excluded or uninstalled). We call these **included** plugins (✅).

See **Rethinking Plugins** in the [**Capacitor 3 Upgrade Guide**](https://github.com/ionic-team/capacitor/issues/3320) to learn more about how apps and plugins will be affected by these changes.

### Decision Legend

Icon | Meaning
:--:|--
:white_circle: | Keep plugin in Capacitor core (API may change).
:black_circle: | Move plugin from Capacitor core into a new official plugin (import will change, API may change).
:red_circle: | Delete the plugin.

### Plugins

Plugin | Decision | Included | Assignee | Status
-- |:--:|:--:| -- | --
**Accessibility** | ⚫ |  | @dwieeb | published ([`@capacitor/screen-reader`](https://www.npmjs.com/package/@capacitor/screen-reader))
**App** | :black_circle: | ✅ | @jcesarmobile | published ([`@capacitor/app`](https://www.npmjs.com/package/@capacitor/app))
**Background Task** | 🔴 |  | 
**Browser** | ⚫ | | @ikeith | published ([`@capacitor/browser`](https://www.npmjs.com/package/@capacitor/browser))
**Camera** | ⚫ | | @ikeith | in progress (https://github.com/ionic-team/capacitor-plugins/pull/33)
**Clipboard** | ⚫ |  | @carlpoole | published  ([`@capacitor/clipboard`](https://www.npmjs.com/package/@capacitor/clipboard))
**Console** | ⚪ |  | 
**Device** | ⚫ |  | @jcesarmobile | published  ([`@capacitor/device`](https://www.npmjs.com/package/@capacitor/device))
**Filesystem** | ⚫ |  | @jcesarmobile | in progress (https://github.com/ionic-team/capacitor-plugins/pull/19)
**Geolocation** | ⚫ |  | @carlpoole  | in progress (https://github.com/ionic-team/capacitor-plugins/pull/13)
**Haptics** | ⚫ |  | @jcesarmobile | published ([`@capacitor/haptics`](https://www.npmjs.com/package/@capacitor/haptics))
**Keyboard** | ⚫ | ✅ | @jcesarmobile | published ([`@capacitor/keyboard`](https://www.npmjs.com/package/@capacitor/keyboard))
**Local Notifications** | ⚫ |  | @dwieeb | in progress (https://github.com/ionic-team/capacitor-plugins/pull/94) 
**Modals** | ⚫ |  |  | split into [`@capacitor/action-sheet`](https://www.npmjs.com/package/@capacitor/action-sheet) and [`@capacitor/dialog`](https://www.npmjs.com/package/@capacitor/dialog)
**Motion** | ⚫ |  | @jcesarmobile | published ([`@capacitor/motion`](https://www.npmjs.com/package/@capacitor/motion))
**Network** | ⚫ |  | @ikeith | published  ([`@capacitor/network`](https://www.npmjs.com/package/@capacitor/network))
**Permissions** | 🔴 |  | @jcesarmobile | done (https://github.com/ionic-team/capacitor/pull/3386)
**Photos** | 🔴 |  | @jcesarmobile | done (https://github.com/ionic-team/capacitor/pull/3385)
**Push Notifications** | ⚫ |  | @dwieeb | in progress (https://github.com/ionic-team/capacitor-plugins/pull/126)
**Share** | ⚫ |  | @jcesarmobile | published  ([`@capacitor/share`](https://www.npmjs.com/package/@capacitor/share))
**Splash Screen** | ⚫ | ✅ | 
**Status Bar** | ⚫ | ✅ | @jcesarmobile | published ([`@capacitor/status-bar`](https://www.npmjs.com/package/@capacitor/status-bar))
**Storage** | ⚫ |  | @dwieeb | published ([`@capacitor/storage`](https://www.npmjs.com/package/@capacitor/storage))
**Toast** | ⚫ |  | @jcesarmobile | published  ([`@capacitor/toast`](https://www.npmjs.com/package/@capacitor/toast))
**WebView** | ⚪ |  | 

### Plugin Transfer Checklist

Use this checklist as a guide when transferring plugin source code to the [Capacitor Plugins repo](https://github.com/ionic-team/capacitor-plugins).

- [ ] I have added the plugin package to `lerna.json`
- [ ] If it makes sense for this plugin, I have split out the functionality of the plugin such that it is easily reusable in native code and created a thin wrapper for the Capacitor plugin itself, as per the changes in https://github.com/ionic-team/capacitor/pull/3315.
- [ ] I have fully documented the plugin interface (`src/definitions.ts`) with [JSDoc](https://jsdoc.app), including adding tags such as `@since`, `@param` w/ descriptions, `@return` comments, `@typeParam` (see https://typedoc.org/guides/doccomments/#supported-tags), etc and adding notes about platform support and quirks.
- [ ] I have added a destroy/unload handler which removes listeners and performs other memory cleanups that would otherwise lead to memory leaks.
- [ ] I have removed all the `TODO`s (for example, in `rollup.config.js`)
- [ ] I have switched all deprecated `.success()` calls to use `.resolve()`.
- [ ] I have added verify scripts to `package.json` so the plugin can be verified in CI. (see [this example](https://github.com/ionic-team/capacitor-plugins/blob/main/text-zoom/package.json#L9-L12))
- [ ] I have added `publishConfig` to `package.json` so lerna can properly publish scoped packages (see [this example](https://github.com/ionic-team/capacitor-plugins/pull/8/commits/8ff3e15319580c8867fe4771eece2d94bbf5e2c5))
- [ ] I have added `README.md` (with a good description) and `LICENSE` files (see https://github.com/ionic-team/capacitor-plugins/pull/8/commits/6413d3a5137fd305b2f18ea9b34c88c38ca4a923 and https://github.com/ionic-team/capacitor-plugins/pull/8/commits/156dee89141553a0e2217c1faa8669086b7756cf)
- [ ] I have set up the `README.md` for [`@capacitor/docgen`](https://github.com/ionic-team/capacitor-docgen) and have generated the markdown docs using `npm run docgen`
- [ ] I have added upgrade instructions to https://github.com/ionic-team/capacitor/issues/3320 for my plugin.
- [ ] I added the plugin to the [Capacitor TestApp](https://github.com/ionic-team/capacitor-testapp) so it can be manually validated now and in the future.

### Discussions/Things to Remember

- "Make plugins usable for native code." https://github.com/ionic-team/capacitor/discussions/3222
- Evaluate permissions. ref: https://github.com/ionic-team/capacitor/pull/3204
- `hasPermission` can be expanded to return more values. https://github.com/ionic-team/capacitor/discussions/3239

**Comment by dwieeb** [comment]
**Accessibility** is now in progress: https://github.com/ionic-team/capacitor-plugins/pull/1
**Clipboard** is now in progress: https://github.com/ionic-team/capacitor-plugins/pull/6
**Haptics** is now in progress: https://github.com/ionic-team/capacitor-plugins/pull/5

**Comment by jcesarmobile** [comment]
I've sent PRs to remove **Photos** https://github.com/ionic-team/capacitor/pull/3385 and **Permissions** https://github.com/ionic-team/capacitor/pull/3386 plugins. Since we are doing a few refactors, the sooner we remove those files the better.

**Comment by carlpoole** [comment]
**Geolocation** is in progress: https://github.com/ionic-team/capacitor-plugins/pull/13

**Comment by dwieeb** [comment]
**Storage** is in progress: https://github.com/ionic-team/capacitor-plugins/pull/15

**Comment by ikeith** [comment]
Browser is in progress: https://github.com/ionic-team/capacitor-plugins/pull/16

**Comment by dwieeb** [comment]
Published the following plugins to npm:
- [`@capacitor/haptics`](https://www.npmjs.com/package/@capacitor/haptics)
- [`@capacitor/motion`](https://www.npmjs.com/package/@capacitor/motion)
- [`@capacitor/screen-reader`](https://www.npmjs.com/package/@capacitor/screen-reader)
- [`@capacitor/storage`](https://www.npmjs.com/package/@capacitor/storage)
- [`@capacitor/text-zoom`](https://www.npmjs.com/package/@capacitor/text-zoom)

**Comment by ikeith** [comment]
Camera is in progress: https://github.com/ionic-team/capacitor-plugins/pull/33

**Comment by jcesarmobile** [comment]
share is in progress: https://github.com/ionic-team/capacitor-plugins/pull/39

**Comment by jcesarmobile** [comment]
dialog: https://github.com/ionic-team/capacitor-plugins/pull/44
action sheet: https://github.com/ionic-team/capacitor-plugins/pull/42
device is in progress

**Comment by jcesarmobile** [comment]
toast is in progress: https://github.com/ionic-team/capacitor-plugins/pull/52
Statusbar is in progres

**Comment by jcesarmobile** [comment]
keyboard https://github.com/ionic-team/capacitor-plugins/pull/59

**Comment by dwieeb** [comment]
Published the following to npm:

     - @capacitor/action-sheet@0.1.0
     - @capacitor/clipboard@0.1.0
     - @capacitor/device@0.1.0
     - @capacitor/dialog@0.1.0
     - @capacitor/haptics@0.0.2
     - @capacitor/motion@0.0.2
     - @capacitor/network@0.1.0
     - @capacitor/screen-reader@0.0.2
     - @capacitor/share@0.1.0
     - @capacitor/storage@0.0.2
     - @capacitor/text-zoom@0.0.2
     - @capacitor/toast@0.1.0

**Comment by dwieeb** [comment]
Published the following to npm:
- @capacitor/app
- @capacitor/browser
- @capacitor/keyboard
- @capacitor/status-bar

Additionally, Local Notifications is in progress: https://github.com/ionic-team/capacitor-plugins/pull/94

**Comment by dwieeb** [comment]
Published the following to npm:
- @capacitor/local-notifications
- @capacitor/push-notifications

This issue can now be closed. We have ported all the plugins! 3.0.0-beta.0 will be released shortly.
