### ISSUE TITLE
bug: Android Keyboard should apply Dark style if dark mode is enabled

### ISSUE THREAD

**Issue by ryaa** [ionic-team/capacitor#3235]
## Bug Report
Capacitor keyboard plugin setStyle does not seem to work on Android. It seems that it has not even been implemeneted
```
  @PluginMethod()
  public void setStyle(PluginCall call) {
    call.unimplemented();
  }
```

### Capacitor Version

```
Alexs-MacBook-Pro-2:feat-keyboard-dark-mode alexryltsov$ npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.2.1

  @capacitor/core: 2.2.1

  @capacitor/android: 2.2.1

  @capacitor/electron: 2.2.1

  @capacitor/ios: 2.2.1

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.1.2

  @capacitor/core 2.1.2

  @capacitor/android 2.2.0

  @capacitor/ios 2.2.0

[success] Android looking great! 👌
  Found 3 Capacitor plugins for ios:
    capacitor-dark-mode (0.0.9)
    cordova-plugin-device (2.0.3)
    cordova-sqlite-storage (5.0.0)
[success] iOS looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Keyboard.setStyle method does not work on Android

### Expected Behavior

It should apply the appropriate style (dark or light) as required. It seems to be working on iOS only

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
On Android there are no APIs for styling the Keyboard from an app.
Also users can install different keyboards that might or might not support dark mode.

But Gboard supports dark mode now, if you device has a dark theme selected the keyboard will be dark, if it's disabled then it will be light.
