### ISSUE TITLE
feat: npx cap open android - Intellij IDEA

### ISSUE THREAD

**Issue by TensorTom** [ionic-team/capacitor#3242]
`npx cap open android` will open the Android project in Android Studio. After that, you can `npx cap sync android` and build with Android Studio. I would rather do this in Intellij IDEA and/or WebStorm. Please add a flag to change the IDE to open in if possible. Also, maybe there's a trick we could use in the meantime?

I have tried and failed to mirror the project settings from Android Studio in Intellij IDEA. I can't seem to get it.

**Comment by HackPoint** [comment]
npx cap open android --ide=intellij would be great! Can it be done?

**Comment by ericlentz** [comment]
If you are running on Linux, this works by setting linuxAndroidStudioPath in capacitor.config.json. See https://stackoverflow.com/a/64717551/687647 for slightly more detail.

**Comment by jcesarmobile** [comment]
In Capacitor 3 you can use `CAPACITOR_ANDROID_STUDIO_PATH` environment variable.
I've just tried with this command and worked `CAPACITOR_ANDROID_STUDIO_PATH=/Applications/IntelliJ\ IDEA\ CE.app npx cap open android`, you can also set it globally so you don't have to pass it every time to the open command.

Not sure if it will work with other IDEs as they are very different from Android Studio, but we don't plan to support other IDEs.

In Capacitor 2, `windowsAndroidStudioPath` config option should work for windows and `linuxAndroidStudioPath` should work for linux, as ericlentz mentioned, but there is no option for macOS.

**Comment by iamromec** [comment]
It doesn't work with Android Studio Preview. Any way around?

**Comment by iamromec** [comment]
> It doesn't work with Android Studio Preview. Any way around?
> 
> Using macOS 11.4 and the latest version of Android Studio Preview.

Lol. U just deleted the old Android Studio and renamed Android Studio Preview -> Android Studio in Applications and ran command: ionic cap open android, it worked!
