### ISSUE TITLE
feat: add save button to Camera.getPhoto (when allowEditing is set to true)

### ISSUE THREAD

**Issue by tafelnl** [ionic-team/capacitor#3246]
Current behaviour of `Camera.getPhoto` with `allowEditing` set to `true`

- Open camera using Camera plugin.
- Take picture
- Accept picture -> navigates to edit screen
- Try and continue without editing picture
- **The Image is returned**

This behaviour was designed after this bug report: https://github.com/ionic-team/capacitor/issues/2020

I do not think that it is quite user friendly UX wise.

If I click the back button / cancel button / close button, I expect my taken image to be gone.

So how do we save an *un*edited image then? Well.. My proposal would be by simply providing a 'save' button. I am not sure if this is possible with the current code (as it looks like a native plugin or something is being used). But maybe the maintainers of that plugin can be of any help here?

**Comment by jcesarmobile** [comment]
The image edit is done by a 3rd party app, so we can't put buttons in 3rd party apps.
The plugin just launches an edit intent and any app that register an edit intent can be opened and we don't have any control over it.
I personally would avoid to use the `allowEditing`
