### ISSUE TITLE
bug: LocalNotifications.requestPermission always returns success on android

### ISSUE THREAD

**Issue by kheftel** [ionic-team/capacitor#3252]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.2.1
  @capacitor/core: 2.2.1
  @capacitor/android: 2.2.1
  @capacitor/electron: 2.2.1
  @capacitor/ios: 2.2.1

Installed Dependencies:

  @capacitor/cli 2.2.1
  @capacitor/android 2.2.1
  @capacitor/core 2.2.1
  @capacitor/ios 2.2.1
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 7 Capacitor plugins for ios:
    @capacitor-community/native-audio (0.1.3)
    cordova-plugin-advanced-http (2.5.1)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-file (6.0.2)
    cordova-plugin-insomnia (4.3.0)
    cordova-plugin-network-information (2.0.2)
    cordova-plugin-purchase (10.2.0)
[success] iOS looking great! 👌
```

### Platform(s)
Android

### Current Behavior
`LocalNotifications.requestPermission` is [hardcoded to return success](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java#L95).
```
{
  "granted": true
}
```

### Expected Behavior
when I turn notifications off in settings, I should get:
```
{
  "granted": false
}
```

### Code Reproduction
https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java#L95

### Other Technical Details

`npm --version` output:
6.14.5

`node --version` output:
v12.17.0

### Additional Context
an easy fix would be to copy from [`areEnabled`](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java#L120). will submit a PR now to do so.

**Comment by kheftel** [comment]
I understand on android it's not really necessary to request permission from the user like iOS, but this would unify the API... I understand if it's working as intended.

**Comment by dwieeb** [comment]
Yes, it's working as intended. Thanks for the issue and PR!
