### ISSUE TITLE
bug: App is blank white – Ionic is not running

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/capacitor#3256]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.2.1
  @capacitor/core: 2.2.1
  @capacitor/android: 2.2.1
  @capacitor/electron: 2.2.1
  @capacitor/ios: 2.2.1

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.2.1
  @capacitor/ios 2.2.1
  @capacitor/core 2.2.1
  @capacitor/electron not installed

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```
### Platform(s)
- iOS
### Current Behavior
The app is just white blank. Ionic is not running in the app. If I inspect the app using Safari Webtools `<ion-nav>` is empty. It does not happens on Android or using `npx cap serve`.

### Expected Behavior
App should not be blank.

### Other Technical Details

`npm --version`: **6.14.4**

`node --version`: **v12.18.0**

`pod --version`: **1.9.0**

**Comment by jcesarmobile** [comment]
can you provide a sample app?

white screens are usually caused by javascript errors, so after you open safari tools, you can reload the app and see errors that were displayed before you opened them

**Comment by BerkeAras** [comment]
-- Issue gets closed. It was my fault, there was an typo in the path of ionic 😂 I'm sorry --
