### ISSUE TITLE
Feature request: NativeScript plugin compatibility layer?

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/capacitor#326]
Hi Ionic team,

This request may sound strange but I'm wondering if it's possible for you guys to create a compatibility layer for NativeScript plugins? 
https://market.nativescript.org/plugins/

NativeScript plugins (2015-2017) are newer than Cordova plugins (2011-2014) and NativeScript uses Angular 5 and TypeScript just like Ionic... so I'm thinking making a compatibility layer for NativeScript plugins on Capacitor would be possible? 

This will solve aging plugin issues of Cordova. The majority of cordova plugins are no longer managed.. and many ionic users are interested in trying a different set of plugins. Given that NativeScript is an open source software, using its plugin on Capacitor is not a bad idea. 

Thanks in advance,

**Comment by mlynch** [comment]
Sounds fun, not a priority by any means but not opposed to it. Unsure how it would work

**Comment by jamesharvey2** [comment]
Thank you for giving attention and your efforts!
I found a guy who was trying to make a cordova plugin adapter for React Native:
https://www.npmjs.com/package/react-native-cordova-plugin

So I was thinking maybe making a plugin adapter is possible.

**Comment by jcesarmobile** [comment]
That is for using Cordova plugins in React Native, what he did is similar to what we did to support Cordova plugins in Capacitor.

**Comment by jamesharvey2** [comment]
Plugins which need native UI rendering will not work obviously... but the ones which work with Android Java API (.java files), Objective C API could be transplanted? I don't know.

**Comment by jamesharvey2** [comment]
or you guys can create a brand new Capacitor plugin layer which can work with cordova plugins, nativescript plugins, react native plugins at the same time...

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.
