### ISSUE TITLE
bug: Fresh Android project template generated from Windows 10 will not build in Ionic Appflow

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/capacitor#3260]
### Capacitor Version

```
@capacitor/ios not installed
  @capacitor/cli 2.2.1
  @capacitor/core 2.2.1
  @capacitor/android 2.2.1
  @capacitor/electron not installed
```

### Platform(s)

Android

### Current Behavior
A brand new Android project (generated via `npx cap add android` on Windows - Mac works fine) will not build on Ionic Appflow.

### Expected Behavior
The project should build.

### Code Reproduction
Repo: https://github.com/dotNetkow/appflow-android-bug/

Or, reproduce by:
`ionic start` to create a new ionic project.
`ionic build` to build it.
`npx cap add android` to add an Android project.

Next, connect the app to Appflow. Within Appflow, build the app with "Android" and "debug" mode. Alternatively, here's [a failed build log](https://dashboard.ionicframework.com/app/84fb7e80/build/builds/6921469) in our internal Ionic instance.

details:
```
[16:18:38]: fastlane finished with errors
/usr/local/bundle/bin/fastlane: [!] Permission denied - /builds/dotNetkow/appflow-android-bug/android/gradlew (Errno::EACCES)
/usr/local/lib/ruby/2.6.0/open3.rb:213:in `spawn': Permission denied - /builds/dotNetkow/appflow-android-bug/android/gradlew (Errno::EACCES)
	from /usr/local/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /usr/local/lib/ruby/2.6.0/open3.rb:208:in `popen2e'
	from /usr/local/bundle/gems/fastlane-2.148.1/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	from /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
```

The `gradlew` file is to blame - it's not executable so Appflow fails. When generated on Windows, permissions are:
`-rw-r--r--`
but they should be:
`-rwxr-xr-x`

### Other Technical Details
n/a

**Comment by jcesarmobile** [comment]
windows and unix permissions are different, so despite the file has proper permissions, when copied in windows they get lost

I don't think this is a Capacitor issue per se, nor can't be fixed in Capacitor, you should grant permissions again when adding gradlew file in git, should probably be documented in Appflow

**Comment by jcesarmobile** [comment]
closing since Appflow added a fix for this
