### ISSUE TITLE
Plugin Template updates for 3.0

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3267]
- [x] class names are inconsistent between native and web "I entered MyPlugin and that created a plugin that's accessible via Capacitor.Plugins.MyPlugin"
- [x] provide an initial separation between functionality and bridge communication (see https://github.com/ionic-team/capacitor/discussions/3222 and https://github.com/ionic-team/capacitor/pull/3315)
- [ ] ~implement a better example for a plugin~ https://github.com/ionic-team/capacitor/issues/3353
- [x] verify that unit tests work 
- [x] change how the plugin is imported (see [Plugin Import Proposal](https://github.com/ionic-team/capacitor/issues/3306) and https://github.com/ionic-team/capacitor/pull/3305)
- [x] remove extraneous xml files for Android (see https://github.com/ionic-team/capacitor/pull/3351)
- [x] update min java version to 8 (see https://github.com/ionic-team/capacitor/pull/3350)
- [x] update gradle (see https://github.com/ionic-team/capacitor/pull/3310)
- [x] investigate adding kotlin support
  - We are going to keep it Java for now and document how to add Kotlin to a Capacitor plugin. See https://github.com/ionic-team/capacitor-site/issues/77
- [x] registerPlugin.getImplementation can provide a proxy fallback that logs warnings for unimplemented platforms (see https://github.com/ionic-team/capacitor/pull/3352)
- [x] add fmt script (see https://github.com/ionic-team/capacitor/pull/3354)

**Comment by jcesarmobile** [comment]
gradle should be updated to latest on android plugin template, see https://github.com/ionic-team/capacitor/pull/3310

**Comment by carlpoole** [comment]
All 3 xml files in the `values` dir can be removed if desired, the template functions fine without them.
