### ISSUE TITLE
Remove serve command

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3276]
`cap serve` isn't aligned with the core experience of Capacitor. Many people are using JS Frameworks (and thus Framework CLIs which provide a much more integrated experience), so this command's existence can be a little confusing. For those that aren't using JS Frameworks, we can document an alternative (one we don't have to maintain) such as `serve` (https://github.com/vercel/serve).

ref: https://github.com/ionic-team/capacitor/issues/3275#issuecomment-659637786

**Comment by TensorTom** [comment]
Beware that this moves against https://github.com/ionic-team/capacitor/discussions/3259

**Comment by TensorTom** [comment]
Seems good at first try.
