### ISSUE TITLE
bug: Capacitor indicates that cordova-plugin-whitelist@1.3.4 is not compatible for ios 13.0 - Any idea what to replace it with

### ISSUE THREAD

**Issue by ETanefo** [ionic-team/capacitor#3279]
### Capacitor Version

```
PASTE OUTPUT HERE
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
The plugins that the CLI show as incompatible it’s not only when they cause problems, it’s also when there is no code for that platform, and whitelist plugin removed iOS code long ago because it was integrated into cordova-ios, so it’s not needed.

**Comment by ETanefo** [comment]
Thank you!

________________________________
