### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3289]
We should set up CI for continuous delivery. 

- New branch?
- Nightlies?

Lerna docs for `version` and `publish`:
https://github.com/lerna/lerna/tree/master/commands/version
https://github.com/lerna/lerna/tree/master/commands/publish

**Comment by IT-MikeS** [comment]
What will define that an update should take place, just time?

If yes, should we maybe do it on a weekly basis, that way people can play with cutting edge on weekends when it may be easier, rather than updating every night?

**Comment by dwieeb** [comment]
I think it might be manual whenever dev releases make sense. We'll have a `dev` dist-tag so people can do `npm install @capacitor/<package>@dev`.

**Comment by IT-MikeS** [comment]
Makes sense, just have to make sure the `dev` tagged `cli` installs/uses the dev tagged `platforms` ect.
