### ISSUE TITLE
Archive CLI assets

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3290]
npm can do weird things when publishing files (see https://github.com/ionic-team/capacitor/pull/3285). This isn't the only place where we rename/move files when applying the templates. If we ship tar.gz archives of the assets, it'll be cleaner and more reliable (probably).

**Comment by IT-MikeS** [comment]
So the idea would be to take a template, let's say the android one, and before release to npm you would archive it, then ship the archive while the template folder as it is now gets added to the .npmignore file?

**Comment by dwieeb** [comment]
The CLI assets (`android-template/`, `ios-template/`, `app-template/`, `capacitor-cordova-android-plugins`, `capacitor-cordova-ios-plugins`, and `plugin-template`) are copied into `cli/assets/` before it's published. This change would ship tar.gz archives instead.

**Comment by IT-MikeS** [comment]
Okay, and then on the users system it would just do an extract on `add` which will use an npm package for the function, or roll one into the cli common functions lib?

**Comment by dwieeb** [comment]
The tar.gz archives would still be in the `@capacitor/cli` package.

**Comment by IT-MikeS** [comment]
Yeah I meant what is the idea for extraction, a built in extract lib or an npm package?

**Comment by dwieeb** [comment]
tar: https://www.npmjs.com/package/tar

**Comment by top1st** [comment]
no such file or directory, stat node_modules\@capacitor\cli\assets\capacitor-cordova-android-plugins.tar.gz

Why I am getting this problem?
