### ISSUE TITLE
bug: Capacitor Geolocation Plugin freeze

### ISSUE THREAD

**Issue by Lugash** [ionic-team/capacitor#3293]
## Bug Report

Hi there !

I’m using ‘Geolocation’ (plugin) from Capacitor on my Ionic project.
I use watchPosition() for tracking the user progression.
We have some isssues, because a lot of users (of the application) are saying that the geolocation isnt working.

For some reasons, it seems that after a while, when my app is put in background and then reopened, the app has no internet connection nor GPS. If I go on the Google Map App for example, I have an internet connection and GPS is working. It looks like my app is in “plane mode” after a while, but don’t understand why… Someone already have a similar issue?

These bugs are on Android most of the case

In the majority of cases, people restart the app and the bug is fixed.

Thank you!

### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.3.0

  @capacitor/core: 2.3.0

  @capacitor/android: 2.3.0

  @capacitor/electron: 2.3.0

  @capacitor/ios: 2.3.0

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.1.0

  @capacitor/core 2.1.0

  @capacitor/ios 2.1.0

  @capacitor/android 2.1.0

[success] Android looking great! 👌
  Found 22 Capacitor plugins for ios:
    cordova-plugin-advanced-http (2.4.0)
    cordova-plugin-android-permissions (1.0.2)
    cordova-plugin-camera (4.1.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-file (6.0.2)
    cordova-plugin-geolocation (4.0.2)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-ionic-webview (4.1.1)
    cordova-plugin-market (1.2.0)
    cordova-plugin-media (5.0.3)
    cordova-plugin-nativeaudio (3.0.9)
    cordova-plugin-nativegeocoder (3.2.2)
    cordova-plugin-navigationbar (1.0.31)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-splashscreen (5.0.2)
    cordova-plugin-statusbar (2.4.2)
    cordova-plugin-vibration (3.1.1)
    cordova-plugin-whitelist (1.3.3)
    cordova.plugins.diagnostic (5.0.1)
    es6-promise-plugin (4.2.2)
    onesignal-cordova-plugin (2.9.1)
    phonegap-plugin-barcodescanner (8.1.0)
[success] iOS looking great! 👌

### Platform(s)
A lot of case on Android

### Code Reproduction
This is not ease to reproduce, because, we can't..
We just have feedback from users who say that geolocation isn't working anymore. It looks like, it's freezing, or lost..

### Other Technical Details
npm 6.14.4
node v10.16.3
pod 1.8.4

**Comment by darron1217** [comment]
I'm experiencing same issue

**Comment by Lugash** [comment]
Edit: I have updated my packages '@capacitor/...' to 2.3.0. 
Now, i need to build, test and push an update to the App (Android and Ios).

And wait... if there is some issues reported from the users.

Still need help, if anyone has an answer or something :)

**Comment by battika** [comment]
Hello, I've never used the Capacitor Geolocation plugin but using the Cordova one which I believe is basically doing the same thing hence I'm writing this post. So, I used watchPosition() found that when the user left the app and returned later, watchPosition() stopped providing data with no error message. What worked for me was to stop watching location when the app goes to background and restart watching it when on the resume app lifecycle event. It solved the issue for me on Cordova, give it go it might be a solution with Capacitor too. Good luck!

**Comment by Lugash** [comment]
Thank you very much for your message. In fact, i've tested that (kill and relaunch process after wake up) but it's not working a lot. It takes maybe 30s.. It seems the process is dead and 'un-restartable' except if you kill the app.
I'm currently looking on the side of 'Background Mode' to maintain connection between the app and phone (so GPS)

**Comment by Riveloper** [comment]
Same issue, and attempted similar fixes as others mentioned. This isn't the only plugin that has this problem I've discovered. 

I use the keep awake when the app is in use and it also gets pauses after a period of time.

Best thing is to use the before exit handler and stop all plugins when app is inactive, then resume when resumed. I understand why the phone is trying to manage resources, but you would think they would pause and resume without it needing coded.

**Comment by jcesarmobile** [comment]
In Capacitor 2.5.0 we have changed the way the geolocation works, the new way might have fixed this too.

It was also changed in @capacitor/geolocation 1.1.0.

If the bug is still present on @capacitor/geolocation 1.1.0 report a new issue on https://github.com/ionic-team/capacitor-plugins/issues
