### ISSUE TITLE
bug: Geolocation Plugin doesn't works if GPS disabled before launching the app

### ISSUE THREAD

**Issue by Ahhsan** [ionic-team/capacitor#3296]
### Capacitor Version
2.2.0

```
Geolocation plugin doesn't fetch the Location
```

### Platform(s)
Android

### Current Behavior

Geolocation plugin only works if the GPS is already enabled and connected, if I enable it after launching my app, it never works.

### Expected Behavior

It should work when GPS is enabled after launching the app.

### Code Reproduction

    if (Capacitor.isPluginAvailable('Geolocation')) {

      Plugins.Geolocation.getCurrentPosition().then(location => {

        this.alertCtrl.create({

          animated: true,

          header: `Platform: ${Capacitor.getPlatform()}`,

          subHeader: 'Coordinates: ',

          message: `Latitude: ${location.coords.latitude}\n Longitude: ${location.coords.longitude}`

        }).then(alertEl => alertEl.present());

      }).catch(error => {

        console.log('Error:', error);

        this.alertCtrl.create({

          animated: true,

          header: `Error Occured`,

          // subHeader: error,

          message: error.message

        }).then(alertEl => alertEl.present());

      })

    }

### Other Technical Details

`npm --version`  6.14.5

`node --version` 12.3.1

### Additional Context

Works great on browser, but on actual device doesn't fetch location

**Comment by jcesarmobile** [comment]
I can't reproduce on Capacitor 3 and @capacitor/geolocation, so might be fixed and updating `com.google.android.gms:play-services-location` version to 17.1.0. 
If you still face the issue, create a new issue on https://github.com/ionic-team/capacitor-plugins/issues and provide a sample app where it can be reproduced

**Comment by shopin-dev** [comment]
I'm facing the same issue. in my ionic app with capacitor 3 it ask for permissions but if gps is deabled it wont ask for enable it, yo have to exit the app, then enable gps and open the app again. How can i check if gps is on/off and ask for enabling it??
