### ISSUE TITLE
Plugin Import Proposal

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3306]
Please feel free to comment on this proposal. Thanks!

---

`@capacitor/core` should provide a `registerPlugin` function that takes an object of implementations for each platform. For Android and iOS, the plugins proxy can be used. For web, the web implementation will need to be provided.

`registerPlugin` will return a `RegisteredPlugin` object with a `getImplementation` method that returns the instance of the plugin for the current platform.

The "echo" example will be used for this proposal.

`echo-plugin/index.ts`
```typescript
import { Plugins, registerPlugin } from '@capacitor/core';
import { EchoPluginWeb } from './web';

export interface EchoPlugin {
  echo: (something: string) => string;
}

const Plugin = registerPlugin<EchoPlugin>('Echo', {
  android: Plugins.EchoPlugin,
  ios: Plugins.EchoPlugin,
  web: new EchoPluginWeb(),
}).getImplementation();

export { Plugin };
```

`echo-plugin/web.ts`
```typescript
import { WebPlugin } from '@capacitor/core';
import type { EchoPlugin } from '.';

export class EchoPluginWeb extends WebPlugin implements EchoPlugin {
  constructor() {
    super({ name: 'Echo' });
  }

  ...
}
```

`my-app/some-page.tsx`
```typescript
import { Echo } from 'echo-plugin';

await Echo.echo('hello world');

// TODO: Figure out testing.
export class Foo {
  constructor() {
    Echo.echo();
  }
}
```

This shouldn't be a breaking change because plugins will need to opt-in to using `registerPlugin` in order for the new plugin import to work. (Previously, users of the plugin would have to `import { Plugins } from '@capacitor/core';`).

**Comment by IT-MikeS** [comment]
Shouldn't 
```typescript
export class EchoPluginWeb extends WebPlugin implements EchoPlugin {
  constructor() {
    super({ name: 'Echo' });
  }
}
```

have an `echo` method? 🤔

**Comment by dwieeb** [comment]
Yeah, but not super important to the proposal, I'll add `...` to make it clear there's more implementation details.

**Comment by IT-MikeS** [comment]
Just didn't want people trying it with your code and going "why isn't this working?!?!" I know most people will see the issue but I've been there before where its a small little thing I screw up that takes me far too long to figure out... 😅

**Comment by dwieeb** [comment]
If you want, you can try the PR: https://github.com/ionic-team/capacitor/pull/3305

It's meant to be a working example. 😄
