### ISSUE TITLE
[BUILD IOS FAIL] Module compiled with Swift 5.1 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by danbn-100295** [ionic-team/capacitor#3330]
Hey guys
I started build Ionic5 with capcitor on ios,But i have this error "Module compiled with Swift 5.1 cannot be imported by the Swift 5.0 compiler" when open Xcode. Here is my info
`Xcode 10.2
Build version 10E125`

`"@capacitor/cli": "^2.2.0",
 "@capacitor/core": "^2.2.0",
 "@capacitor/ios": "^2.2.0",`

**Comment by danbn-100295** [comment]
Here is image for this error
<img width="628" alt="Ảnh chụp Màn hình 2020-07-25 lúc 10 59 39 SA" src="https://user-images.githubusercontent.com/61224981/88448269-26227580-ce66-11ea-9510-dd706aafb920.png">

**Comment by jcesarmobile** [comment]
Capacitor requires Xcode 11 to build

https://capacitorjs.com/docs/getting-started/dependencies#ios-development
