### ISSUE TITLE
Background Geolocation plugin not working 

### ISSUE THREAD

**Issue by devopriyo85** [ionic-team/capacitor#3333]
I am using Background geolocation plugin but when tried to build it in android studio , I am getting compile error .
 resource string/mauron85_bgloc_content_authority (aka com.dev.ionicappin:string/mauron85_bgloc_content_authority) not found

**Comment by musps** [comment]
Add these variables inside `android/app/src/main/res/values/strings.xml`:

```
<string name="mauron85_bgloc_account_name">$ACCOUNT_NAME</string>
<string name="mauron85_bgloc_account_type">$ACCOUNT_TYPE</string>
<string name="mauron85_bgloc_content_authority">$CONTENT_AUTHORITY</string>
```

**Comment by jcesarmobile** [comment]
Yeah, you have to manually provide those values as explained.

**Comment by devopriyo85** [comment]
Thank you for your response . I did what was suggested but now getting below error . Any suggestion for this 
package android.support.annotation does not exist
import android.support.annotation.VisibleForTesting;
                                 ^

**Comment by jcesarmobile** [comment]
see https://capacitorjs.com/docs/android/troubleshooting#error-package-android-support-does-not-exist

**Comment by devopriyo85** [comment]
Thank you , I followed the doc now getting blow error .
confidence = activity.getConfidence();                             ^
  class file for com.google.android.gms.internal.zzbfm not found
