### ISSUE TITLE
bug: React: deviceready event not firing when cordova plugins are ready

### ISSUE THREAD

**Issue by yacut** [ionic-team/capacitor#3345]
### Capacitor Version

```
✗ npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/android 2.4.0
  @capacitor/core 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/electron not installed
```

### Platform(s)

- Web

### Current Behavior

```js
document.addEventListener("deviceready", () => {
    console.log("==> Never appears ");
}, false);
```

### Expected Behavior

```js
document.addEventListener("deviceready", () => {
    console.log("==> Always appears ");
}, false);
```

### Other Technical Details

`npm --version` output: 6.13.7

`node --version` output: v13.10.1

### Additional Context

As capacitor user, I want to understand when Cordova plugins are ready to use in my React based project, so I can start using it when my component is rendered.

**Comment by jcesarmobile** [comment]
Cordova plugins are not supported on web/pwa, there is an issue open about it 
https://github.com/ionic-team/capacitor/issues/769

**Comment by yacut** [comment]
@jcesarmobile Thank you for the information
