### ISSUE TITLE
App Module conflict with ionic App module

### ISSUE THREAD

**Issue by gibbsvjy007** [ionic-team/capacitor#335]
import { Nav, Platform, ToastController, **App** } from 'ionic-angular';
import { Plugins } from '@capacitor/core';
const { Storage, **App** } = Plugins;

Capacitor app module is conflicting with ionic App module while building app.
The workaround is to use Plugins.App.addLinstner......

This is a minor issue but I thought to inform as I faced this issue while ionic build.

**Comment by mlynch** [comment]
Thanks. I will leave this open for discussion but seeing as we're going to be supporting other frameworks in Ionic that won't have the `App` import, this might end up being an increasingly small problem in the future.

**Comment by IT-MikeS** [comment]
@gibbsvjy007 for now as a work around you cab use an alias for the import from either: `import {App as IonicApp} from 'ionic-angular' `

**Comment by jcesarmobile** [comment]
`App` doesn't seem to be on `@ionic/angular` (Ionic 4), so for Ionic 3 users I would recommend what @IT-MikeS said.
