### ISSUE TITLE
Offset at the bottom after app launch on iOS devices

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/capacitor#337]
There is a small offset at the bottom of the webview directly after the splash-screen disappeared. On reals devices the offset quickly vanishes (see gif), in the simulator it stays. I've tried with the example app and with one of our apps (both are Ionic projects). It happens on the iPhoneX (where the offset is biggest) and other devices too (see screenshot).

```
@capacitor/cli: 1.0.0-alpha.13
@capacitor/core: 1.0.0-alpha.13
```

![offset-iphonex](https://user-images.githubusercontent.com/7592254/37464989-48956ea6-285a-11e8-895a-0051fd504829.gif)

![offset-sim-iphone8_x](https://user-images.githubusercontent.com/7592254/37465026-6373e112-285a-11e8-838a-cb77d11d1b2e.png)

**Comment by mhartington** [comment]
Hey there! I'll take a look and see whats up. Do you have a sample project to test against?

**Comment by mlynch** [comment]
@DavidStrausz what CSS are you using to style that background layer? I want to test with it and also see if it's the correct selector to get the right look

**Comment by DavidStrausz** [comment]
I tested it with the [Capacitor Example App](https://github.com/ionic-team/capacitor/tree/master/example) (with `ion-content` set to black).

**Comment by mlynch** [comment]
Thanks. I've seen this in Cordova as well so I wonder if it's a WKWebView issue. Anyways, investigating still

**Comment by mlynch** [comment]
Clearly not fixed yet

**Comment by sbannigan** [comment]
Just opened a PR (#856) for a possible fix for this issue.

**Comment by mlynch** [comment]
Thanks to @sbannigan this should be resolved on the next release (probably Monday).

**Comment by roychoo** [comment]
Hi is this fix released yet?
