### ISSUE TITLE
bug: Camera Plugin Web webUseInput: true ignored

### ISSUE THREAD

**Issue by ikerllorens** [ionic-team/capacitor#3372]
## Bug Report

Hi,

I am trying to add the newly added webUseInput property to true, however it is ignored on Web because the browser opens the webcam. 

Right now I I use the plugin like this: 
```
const photo = await Camera.getPhoto({
      allowEditing: false,
      webUseInput: true,
      quality: 70,
      resultType: CameraResultType.Base64,
      saveToGallery: false,
      source: CameraSource.Prompt
    });
```

And fetch the plugin from the registry with:
```
import {CameraResultType, CameraSource, Plugins} from '@capacitor/core';
const { Camera } = Plugins;
```

Everything works fine in mobile with this, but on web it opens the modal and uses the webcam ignoring the webUseInput boolean. 

But, when I add the Camera like this: 

```
import {CameraResultType, CameraSource, Camera} from '@capacitor/core';
```
the web plugin acts correctly and prompts for a file, but on mobile it also prompts it as a file input, not through the Action Sheet.

I tried changing the `source: CameraSource.Prompt` to `source: CameraSource.Photos` but it has the same behavior. Of what I can see, if I import directly the Camera from the plugins I am fetching the web plugin and using it as web even if the device is a mobile phone. I am aware that the correct way is fetching it from the plugin registry, but in that way the boolean is ignored and the webcam opens up.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 20 Capacitor plugins for ios:
    @capacitor-community/apple-sign-in (0.0.12)
    @capacitor-community/firebase-analytics (0.2.0)
    capacitor-rate-app (0.0.2)
    capacitor-stripe (1.0.0-beta.4)
    cordova-plugin-android-permissions (1.0.2)
    cordova-plugin-androidx (1.0.2)
    cordova-plugin-androidx-adapter (1.1.0)
    cordova-plugin-app-version (0.1.9)
    cordova-plugin-camera (5.0.0-dev)
    cordova-plugin-crop (0.4.0)
    cordova-plugin-facebook4 (6.4.0)
    cordova-plugin-file (6.0.2)
    cordova-plugin-geolocation (4.0.2)
    cordova-plugin-googleplus (8.5.0)
    cordova-plugin-inappbrowser (3.1.0)
    cordova-plugin-media-capture (3.0.3)
    cordova-plugin-nativegeocoder (3.4.1)
    cordova-plugin-video-editor (1.1.3)
    cordova-support-android-plugin (1.0.1)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌

```

### Platform(s)
PWA, iOS, Android, Web

### Current Behavior
Setting the boolean `webUseInput: true` in the Camera getPhoto method doesn't prevent the modal with the webcam to show up. Changing the property does not have an effect and neither changing the `source: CameraSource.Prompt` to `source: CameraSource.Photos` . This behavior is when fetching the plugin from the registry with `const { Camera } = Plugins;` If I import the Camera directly from plugins, `import {CameraResultType, CameraSource, Camera}` from '@capacitor/core';` the behavior is correct on Web but not in mobile (it prompts as an HTML input)

### Expected Behavior
The boolean `webUseInput` should not show the modal with the webcam, it should open the input, preserving the functionality of the plugin in native.

### Code Reproduction

This opens the modal with the camera, even changing the source to `CameraSource.Photos`
```
import {Component, OnInit} from '@angular/core';
import {CameraResultType, CameraSource, Plugins} from '@capacitor/core';
const { Camera } = Plugins;

@Component({
  selector: 'app-profile-complete',
  templateUrl: './profile-complete.page.html',
  styleUrls: ['./profile-complete.page.scss']
})
export class ProfileCompletePage implements OnInit {

openCamera() {
  const photo = await Camera.getPhoto({
      allowEditing: false,
      webUseInput: true,
      quality: 70,
      resultType: CameraResultType.Base64,
      saveToGallery: false,
      source: CameraSource.Prompt
    });
}
```

Importing directly the Camera, the modal won't pop and the file prompt appears, however on device it asks for a file as an HTML input type="file"
```
import {Component, OnInit} from '@angular/core';
import {CameraResultType, CameraSource, Camera} from '@capacitor/core';

@Component({
  selector: 'app-profile-complete',
  templateUrl: './profile-complete.page.html',
  styleUrls: ['./profile-complete.page.scss']
})
export class ProfileCompletePage implements OnInit {

openCamera() {
  const photo = await Camera.getPhoto({
      allowEditing: false,
      webUseInput: true,
      quality: 70,
      resultType: CameraResultType.Base64,
      saveToGallery: false,
      source: CameraSource.Prompt
    });
}
```

### Additional Context

Using Ionic/Angular 
"@ionic/angular": "^5.3.1",

**Comment by jcesarmobile** [comment]
can you provide a sample app?

to be clear, webUseInput is only used on web/pwa, not on native, on native it will always use the camera or image picked (depending on the source you used).
`CameraSource.Prompt` is not supported on web at the moment

**Comment by ikerllorens** [comment]
Yes, I can do a sample app, but I can have it at the end of the day. 

I am aware that the boolean is only for use in PWA/Web. What I can be doing wrong, and maybe this could be resolved by resolving this doubt is: Is there something I have to do for the web plugin? or use it as it is in the docs and adding the webUseInput and get the plugin from the Plugin registry?

For the meantime I made a short video. 
https://drive.google.com/file/d/1eC4qI3oleDc-su63Zii51QsIBTL4o9v8/view?usp=sharing

In my spare time I will create the sample app

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
