### ISSUE TITLE
bug: 'Cordova/CDVPlugin+Resources.h' file not found when using plugin for MediaRecorder API on iOS

### ISSUE THREAD

**Issue by dallastjames** [ionic-team/capacitor#3379]
### Capacitor Version

```
@capacitor/android 2.4.0
@capacitor/cli 2.4.0
@capacitor/ios 2.4.0
@capacitor/core 2.4.0
@capacitor/electron not installed
```

### Platform(s)

@capacitor/ios

### Current Behavior

After installing and configuring the https://github.com/phonegap/phonegap-plugin-media-recorder plugin into a Capacitor project, when building the project, the build in XCode errors with `'Cordova/CDVPlugin+Resources.h' file not found` error message.

### Expected Behavior

The cordova files should be found correctly and the build should complete as expected.

### Code Reproduction

https://github.com/dallastjames/cap-media-api-issue

### Other Technical Details

`npm --version` output: `6.14.7`

`node --version` output: `14.6.0`

`pod --version` output (iOS issues only): `1.8.4`

**Comment by jcesarmobile** [comment]
closing as the linked PR is merged

**Comment by manel00** [comment]
Hello,

Having the same issue with cordova-SQL plugin on XCode, Capacitor2 + Ionic5
