### ISSUE TITLE
(Custom) URL schemes do not work

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/capacitor#339]
Using `mailto:` or `tel:` (or any other custom URL scheme) leads currently to an error:
```
⚡️  WebView failed provisional navigation
⚡️  Error: unsupported URL
```

This is probably because custom URL schemes are currently not handled. By implementing [`decidePolicyFor`](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455641-webview?language=swift) this could be fixed. It would be great if the allowed URL schemes are configurable via a plugin or `capacitor.config.json`.

**Comment by mlynch** [comment]
Thanks will get this resolved today

**Comment by mlynch** [comment]
Cool, fixed, will be available in the next release (alpha.16)

**Comment by ipehimanshu** [comment]
@mlynch can you help me how to add so it will work into capacitor 3 please ?
We are now migrating from cordova so we don't have much idea for that.
Thanks in advance,
