### ISSUE TITLE
bug: Cordova plugin installed from other sources not being found by cap sync

### ISSUE THREAD

**Issue by cabassi** [ionic-team/capacitor#3395]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 7 Capacitor plugins for ios:
    cordova-annotated-plugin-android (1.0.4)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-opener2 (3.0.4)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-geolocation (4.0.2)
    cordova-plugin-purchases (1.2.0)
    cordova-plugin-whitelist (1.3.4)
[success] iOS looking great! 👌

```

### Platform(s)

Android, iOS

### Current Behavior

I have a capacitor project built with quasar.
A cordova plugin installed from github with npm install github:ddssch/cordova-plugin-mbtiles is not being seen by npx cap sync.

The plugin in question is cordova-plugin-mbtiles
These are my dependencies in package.json: 
```
"dependencies": {
    "@capacitor/android": "^2.4.0",
    "@capacitor/cli": "^2.4.0",
    "@capacitor/core": "^2.4.0",
    "@capacitor/ios": "^2.4.0",
    "cordova-annotated-plugin-android": "^1.0.4",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^3.0.4",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-mbtiles": "github:ddssch/cordova-plugin-mbtiles",
    "cordova-plugin-purchases": "^1.2.0",
    "cordova-plugin-whitelist": "^1.3.4"
  }
```
The plugin get installed without issues with npm install, but when I do npx cap sync capacitor finds all the other cordova plugins, but not mbtiles.

If i use a local reference in package.json like the following, It works and the plugin got found by the sync.
```
  "dependencies": {
    "@capacitor/android": "^2.4.0",
    "@capacitor/cli": "^2.4.0",
    "@capacitor/core": "^2.4.0",
    "@capacitor/ios": "^2.4.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^3.0.4",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-mbtiles": "file:../../cordova-plugin-mbtiles",
    "cordova-plugin-whitelist": "^1.3.4"
  }
```

### Expected Behavior

Plugin installed from other sources than npm should get recognized.

### Other Technical Details

`npm --version` output: 6.14.7

`node --version` output: v12.14.0

**Comment by jcesarmobile** [comment]
The problem is the plugin has a files entry https://github.com/ddssch/cordova-plugin-mbtiles/blob/master/package.json#L16-L18
That makes npm only copy www folder to node_modules, but not the `plugin.xml` nor the native code. Remove that and capacitor should detect it. I've tried with a few apache plugins, installed like you did with this plugin and they all work.

**Comment by cabassi** [comment]
Thanks @jcesarmobile, that fixed my issue!
