### ISSUE TITLE
TMS-90809: Deprecated API Usage UIWebView can not remove

### ISSUE THREAD

**Issue by berkayoztunc** [ionic-team/capacitor#3415]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/core 2.4.0
  @capacitor/electron not installed

  Found 6 Capacitor plugins for ios:
    cordova-admobsdk (7.49.0)
    cordova-plugin-admobpro (2.49.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-extension (1.5.4)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-nativeaudio (3.0.9)
[success] iOS looking great! 👌

```
PASTE OUTPUT HERE
```

### Platform(s)
iOS

### Current Behavior
Reject many time. 

### Other Technical Details
All updateded

`npm --version` output: 6.14.7

`node --version` output: v14.7.0

`pod --version` output (iOS issues only):1.9.3

### Additional Context
i can not find the what is the plugin use that UIWebView

How can ı change that def ? 

![Image](https://i.hizliresim.com/Xxuufa.png)

**Comment by jcesarmobile** [comment]
the problem is the admob plugin, it uses and old admob SDK version that used UIWebView
https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/QuZMbjIyxn8%5B1-25%5D
