### ISSUE TITLE
bug: Static page with base route - Nuxtjs

### ISSUE THREAD

**Issue by shidcordero** [ionic-team/capacitor#3417]
### Capacitor Version
```
Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 2.4.0

  @capacitor/core: 2.4.0

  @capacitor/android: 2.4.0

  @capacitor/electron: 2.4.0

  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed


  @capacitor/android 2.2.0

  @capacitor/cli 2.2.0

  @capacitor/core 2.2.0

[success] Android looking great! �
```

### Platform(s)
No specific since I can't run it in my app

### Current Behavior

When my app includes a base route for example I use locale "en-us". The build was successfull and I can use `npx cap copy`. But when I run my app it show the following error
![image](https://user-images.githubusercontent.com/26376208/90113446-f2ab7a80-dd83-11ea-9849-d5b697b7ab86.png)
what I know is, because even I add base url on the route. the generated file on the dist folder does not include the locale as parent folder
![image](https://user-images.githubusercontent.com/26376208/90113514-0ce55880-dd84-11ea-8a0b-99f66e437f71.png)
and when I change to add the "en-us" folder to generate my file. 
![image](https://user-images.githubusercontent.com/26376208/90114027-bb899900-dd84-11ea-85ca-b8a44ad52a97.png)
I can't use npx copy because the index.html file is not found on the root folder
![image](https://user-images.githubusercontent.com/26376208/90115261-6cdcfe80-dd86-11ea-89cc-c359dd86faba.png)

in my nuxt.config.js
![image](https://user-images.githubusercontent.com/26376208/90111689-96dff200-dd81-11ea-87e3-c0338bd37831.png)

### Expected Behavior
I should be able to copy the file with a subfolder so that I can able to run the app.

### Other Technical Details

`npm --version` output:  6.14.4

`node --version` output: v13.13.0

**Comment by dwieeb** [comment]
The Capacitor Web View will still try to load your app at the root path. It won't know to use `/en-US`, for example. How do you plan to redirect to `/en-US` without an `index.html` file in the root of `www`?

I think there's a feature request for a custom base path in Capacitor somewhere... I can't seem to find the issue.

**Comment by shidcordero** [comment]
> The Capacitor Web View will still try to load your app at the root path. It won't know to use `/en-US`, for example. How do you plan to redirect to `/en-US` without an `index.html` file in the root of `www`?
> 
> I think there's a feature request for a custom base path in Capacitor somewhere... I can't seem to find the issue.

Well, I need a feature like in `npx cap copy` it can detect a base router set and copy the files to the correct folder leaving the `index.html` at the root.

**Comment by dwieeb** [comment]
Closed in favor of https://github.com/ionic-team/capacitor/issues/3912
