### ISSUE TITLE
Support for Secure Context

### ISSUE THREAD

**Issue by tafelnl** [ionic-team/capacitor#3418]
I am not sure if this is something that Capacitor is meaning to support, but I think it is missing a Secure Context (https://www.w3.org/TR/secure-contexts/#examples-top-level)

Why is this needed?

Imagine I want to set a Cookie to keep someone logged in. I do not want this Cookie to be accessible from JavaScript, so I'll have to set it from the server side (Cookie flag: `HttpOnly;`) ([OWASP article](https://owasp.org/www-community/HttpOnly)).

Since the Cookie is being set from a server, the following Cookie flag needs to be set: `SameSite=None;` For `SameSite` to be able to have the value `None` the following Cookie flag needs to be set as well: `Secure;` ([Chromium Blog](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html)). But since Capacitor's custom scheme is not considered a Secure Context, one will get the following error in the most recent version of Chrome: 

> This Set-Cookie has the "Secure" attribute but was not received over a secure connection.

![image](https://user-images.githubusercontent.com/35837839/90135748-6e50fb80-dd73-11ea-9024-978c2ae5290b.png)

This is not the only things that relies on a secure context. The Contacts plugin for example requires one as well: [StackOverflow](https://stackoverflow.com/questions/60240957/contacts-not-in-navigator-google-chrome-80#comment109463043_60240957)

Is this something we can make a workaround for, or something Capacitor is planning to support?

**Comment by jcesarmobile** [comment]
does it work if you set Capacitor scheme to https instead of using a custom scheme?

**Comment by tafelnl** [comment]
I do not have access to a computer right now. But I am quite sure that that would work, as I have a working version of this concept on a website in production (https).

When I get access to a computer I will test it out. Does it have any drawbacks to use https instead of a custom scheme? And does it work on both iOS and android?

**Comment by jcesarmobile** [comment]
https will only work on Android

I don't think it has any drawbacks, custom schemes are not really recommended on Android

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by tafelnl** [comment]
@jcesarmobile 

I am about to test this out. But I cannot find any documentation on how to use http**s**:// Can you point me to it?

**Comment by jcesarmobile** [comment]
https://capacitorjs.com/docs/reference/config

Search for`androidScheme`

**Comment by tafelnl** [comment]
Okay, so I did a few discoveries.

On Android chrome will accept the url `http://localhost` as a Secure Context. So as long as your domain has an SSL, the following combination of cookie flags should just work: `SameSite=None;Secure;HttpOnly;`

On iOS however, cookies do not work anyhow (https://github.com/ionic-team/capacitor/issues/1373 and https://github.com/ionic-team/capacitor/discussions/3537). Cookies which will only be handled from the server-side (set through header from the server-side, and only get from server) can be fixed by https://github.com/ionic-team/capacitor/discussions/3537#discussioncomment-80373. Client-side cookies however do not seem to have a solid workaround for now. I think this is a shame, this is a crucial feature. One workaround would be to use the cookies methods of the (not very well documented) https://github.com/capacitor-community/http.

@jcesarmobile can you maybe tell us anything about the intention of Ionic/Capacitor to tackle this issue?
