### ISSUE TITLE
bug: Unable do debug Android app

### ISSUE THREAD

**Issue by edn9** [ionic-team/capacitor#3422]
## Bug Report
I'm trying to debug my application with the `chrome://inspect/#devices` of Chrome, I always was able to user with Cordova but with Capacitor it give me those erros:

![bug1](https://i.imgur.com/0p9iBPL.png)

I have tried <a href="https://github.com/ionic-team/capacitor/issues/715#issuecomment-460919602">Ryaa</a> solution and I was able to not get any errors:

![bug2](https://i.imgur.com/Rb76zPm.png)

But i'm still not able to use the mouse to interact with buttons, input, etc.

### Capacitor Version

```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed

[success] Android looking great!
```

### Platform(s)

Android

### Current Behavior

After I compile the project (just a blank capacitor ionic project) with `npm run debug` (ng build --eval-source-map --plugin ~build-customization-plugin.js, <a href="https://github.com/ionic-team/capacitor/issues/715#issuecomment-460919602">Ryaa</a> solution), I compile to open in Android Studio with `npx cap copy; npx open android` and then I compile the debug version and install in my mobile phone samsung galaxy j5 sm500.

I open the app, connect usb in mobile and note, open chrome, open `chrome://inspect/#devices`, open inspect and I get the window with the app and console log, but i am unable of interacting with mouse in the components, etc.

### Expected Behavior

Work just normal with interactive mode using mouse.

### Code Reproduction

 - `ionic start blank blank --capacitor`
 - `npm run debug` (ng build --eval-source-map --plugin ~build-customization-plugin.js, <a href="https://github.com/ionic-team/capacitor/issues/715#issuecomment-460919602">Ryaa</a> solution)
- `npx cap add android`
- `npx cap copy`
- `npx cap open android`

Build android debug:

- `adb install path/to/app/debug.apk`

### Other Technical Details

`npm --version` output: 6.14.6

`node --version` output: v12.18.3

**Comment by izeryab** [comment]
May be this can help:
![image](https://user-images.githubusercontent.com/51020585/157383192-8428a3c1-a289-4b2c-9811-f6f4e2c81921.png)
![image](https://user-images.githubusercontent.com/51020585/157383367-bffaa8c4-1528-4de6-afb7-8d0d53e26301.png)

**Comment by jcesarmobile** [comment]
Since Capacitor 4.1.0 you can run `npx cap sync --inline` and it will inline the source maps
