### ISSUE TITLE
bug: Unable to set an image preview in iOS share sheet

### ISSUE THREAD

**Issue by adrianvyskoc** [ionic-team/capacitor#3426]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 2.4.0

  @capacitor/core: 2.4.0

  @capacitor/android: 2.4.0

  @capacitor/electron: 2.4.0

  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.2.0

  @capacitor/core 2.2.0

  @capacitor/android 2.2.0

  @capacitor/ios 2.2.0

[success] Android looking great! 👌
  Found 5 Capacitor plugins for ios:
    @capacitor-community/fcm (1.0.7)
    capacitor-fingerprint-auth (0.0.2)
    cordova-plugin-ionic (5.4.7)
    cordova-plugin-whitelist (1.3.4)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌

### Platform(s)
iOS

### Current Behavior
There isn't a possibility to set an image preview when using share functionality (https://capacitorjs.com/docs/apis/share) on iOS. There is always the "T" icon.
![IMG_2683](https://user-images.githubusercontent.com/22477545/90388523-2f2eed00-e088-11ea-90b9-c4b0bbcbaee4.jpg)

### Expected Behavior
There should be an option to set this image.

**Comment by jcesarmobile** [comment]
the icon is automatic, based on what you share and can't be configured, see https://github.com/ionic-team/capacitor/issues/3049#issuecomment-638879765 for more details
