### ISSUE TITLE
Push plugin on android does not work

### ISSUE THREAD

**Issue by sujith97** [ionic-team/capacitor#3428]
Followed steps present in https://capacitorjs.com/docs/guides/push-notifications-firebase on a brand new ionic capacitor project.
When I ran build on Android studio, it threw following error:
```
android/capacitor-cordova-android-plugins/src/main/java/com/adobe/phonegap/push/PushPlugin.java:15: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
```

**Comment by dwieeb** [comment]
See https://capacitorjs.com/docs/android/troubleshooting#error-package-android-support-does-not-exist

cc @dotNetkow

**Comment by sujith97** [comment]
@dwieeb It did not solve the issue.
```
❯ npx jetify
Jetifier found 0 file(s) to forward-jetify. Using 12 workers...
❯ npx cap sync android
```
Is it that the Jetifier found no files and it made no difference?

**Comment by dwieeb** [comment]
@sujith97 Pretty sure you have to sync and _then_ run jetify, but not exactly sure what's going on.

Just FYI we will probably replace that guide soon because the Capacitor Community has an [FCM plugin](https://github.com/capacitor-community/fcm/) that is preferred going forward.

**Comment by sujith97** [comment]
I did not know about this plugin. I just tried FCM plugin and it works like a charm for both Android and iOS.

Thanks much
