### ISSUE TITLE
Event Support

### ISSUE THREAD

**Issue by leoiii12** [ionic-team/capacitor#343]
Will capacitor support different types of event in UIResponder, such as touchesBegan, touchesMoved? 

https://github.com/leoiii12/capacitor/commit/b4fa404c217a45c666994a48acb322281593d34f

**Comment by mlynch** [comment]
Seems like something we could support. Do you have a use case for this so I can better understand why you'd use this over doing JS events in the web view?

**Comment by leoiii12** [comment]
I am trying to make a plugin for Apple Pencil for note taking app or something else. I need to access the UITouch objects.

**Comment by mlynch** [comment]
@leoiii12 I see. We can try to expose those events. The plugin in this case wouldn't be necessary.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

**Comment by mxye** [comment]
Is this feature request closed? I'm also looking for UITouch support, so that I can estimate the "size" of the touch area -- so that I can distinguish different users based on how they touch the screen in different ways. I trust this is not possible with the current version of Capacitor?

**Comment by mlynch** [comment]
Well it’s certainly possible. You have full native access but we don’t have a built-in feature for this. Perhaps you could overlay a transparent UIView and handle these events yourself in swift and expose this with some custom native code? https://capacitorjs.com/docs/ios/custom-code
