### ISSUE TITLE
bug: [iPad] incorrect content size after keyboard closed with dismiss button

### ISSUE THREAD

**Issue by Proper-Job** [ionic-team/capacitor#3430]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/android 2.4.0
  @capacitor/core 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/electron not installed
```

### Platform(s)

iOS - iPad

### Current Behavior

1. Open the keyboard, for instance by focusing a form input. (01_iPad_no_keyboard.png)
2. Observe how the ```<main>``` shadow node of the ```<ion-content>``` tag gets a padding-bottom value of 290px. (02_iPad_keyboard_did_show.png)
3. Close the keyboard by clicking the dismiss button on the keyboard.
4. Observe how the ```<main>``` shadow node of the ```<ion-content>``` tag still has the padding-bottom value of 290px that was added in step 1. (03_iPad_keyboard_did_hide.png) 

Do not dismiss the keyboard by tapping the body. When the body is tapped, the padding-bottom is correctly removed.

### Expected Behavior

When the keyboard is dismissed using the dismiss button, the padding-bottom value is removed from the  ```<main>``` shadow node of the ```<ion-content>``` tag.

### Code Reproduction

https://github.com/Proper-Job/keyboardBugIpad

### Other Technical Details

`npm --version` output:
6.14.4

`node --version` output:
v12.16.2

`pod --version` output (iOS issues only):
1.9.3

```
Ionic:

   Ionic CLI                     : 6.11.0
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.6
   @angular-devkit/schematics    : 10.0.6
   @angular/cli                  : 10.0.6
   @ionic/angular-toolkit        : 2.3.0
```

### Additional Context

**01_iPad_no_keyboard.png**
![01_iPad_no_keyboard](https://user-images.githubusercontent.com/5182820/90504622-a4b2c000-e151-11ea-8723-61d1164af2a8.png)

**02_iPad_keyboard_did_show.png**
![02_iPad_keyboard_did_show](https://user-images.githubusercontent.com/5182820/90504634-a8464700-e151-11ea-866f-66e60b99237e.png)

**03_iPad_keyboard_did_hide.png**
![03_iPad_keyboard_did_hide](https://user-images.githubusercontent.com/5182820/90504637-a9777400-e151-11ea-9012-0f0e441666a6.png)

**Comment by jcesarmobile** [comment]
I can't reproduce on Capacitor 5 with @capacitor/keyboard 5 installed, so it was probably fixed.

If somebody still faces this or a similar issue, please, create a new issue on https://github.com/ionic-team/capacitor-plugins/issues and provide a sample app that reproduces it
