### ISSUE TITLE
feat: support for swift codables

### ISSUE THREAD

**Issue by sisoje** [ionic-team/capacitor#3434]
## Feature Request
using swift codables for call.resolve()

### Description
using swift codables for call.resolve()

### Platform(s)
ios

### Preferred Solution
using swift codables for call.resolve()

**Comment by jcesarmobile** [comment]
can you elaborate?

**Comment by sisoje** [comment]
Ican, currently resolve takes a dictionary [String:Any] as an argument here:

```
  func resolve(_ data: PluginResultData = [:]) {
    successHandler(CAPPluginCallResult(data), self)
  }
```

So I have to make a dictionary even though in reality we dont need a dictionary but a json object (json data/string) shown here:

```
  public func toJson() throws -> String {
    do {
      if JSONSerialization.isValidJSONObject(result) {
        let theJSONData = try JSONSerialization.data(withJSONObject: result, options: [])
        
        return String(data: theJSONData,
                      encoding: .utf8)!
      } else {
        CAPLog.print("[Capacitor Plugin Error] - \(call.pluginId) - \(call.method) - Unable to serialize plugin response as JSON." +
          "Ensure that all data passed to success callback from module method is JSON serializable!")
        throw JSProcessingError.jsonSerializeError(call: call)
      }
    } catch let error as JSProcessingError {
      throw error
    } catch {
      CAPLog.print("Unable to serialize plugin response as JSON: \(error.localizedDescription)")
    }
    
    return "{}"
  }
}
```

But in Swift it is much better to use structures that conform to Codable (Encodable) so we can have compile time type safety.

I made an quick extension for that, but I'm not sure if its the best solution:

```
extension CAPPluginCall {
    /**
     Converting swift encodable to the [String: Any] needed by capacitor
     */
    static func makePluginResultData<T: Encodable>(encodable: T) -> PluginResultData {
        let data = try! JSONEncoder().encode(encodable)
        return try! JSONSerialization.jsonObject(with: data) as! PluginResultData
    }

    func resolve<T: Encodable>(encodable: T) {
        resolve(Self.makePluginResultData(encodable: encodable))
    }
}
```

**Comment by sisoje** [comment]
BTW call,error()  also uses dictionaries, that could be extended to codables

**Comment by ikeith** [comment]
This makes sense to me and I've had a similar thought. We do support Obj-C but prefer/encourage Swift so adding first-class support for its conventions where we can is valuable. I have started on updating some of the JS<->Native type wrangling [here](https://github.com/ionic-team/capacitor/pull/3384) but intend to tackle some bigger refactoring after [we have split apart the plugins](https://github.com/ionic-team/capacitor/issues/3227). The extra serialization proposed here definitely has some drawbacks but I think it should be possible to build in a more efficient solution when updating the related code. I'm adding this to the 3.0 roadmap.

**Comment by mzekrallah** [comment]
any update on this guys ? it's really important to have this flexibility i think.

**Comment by finnp** [comment]
Are there any downsides of using JSON Encoder? Is it slower? It would save me some headaches if it just worked with `Codable`

**Comment by ettore** [comment]
Any update on supporting Codable in Capacitor? It is definitely less than ideal to not being able to use it in CAPPluginCalls and notifications. [Official docs](https://capacitorjs.com/docs/core-apis/data-types) do not mention it, I'm wondering if there is still a plan to support it. If not, it would be good to describe a workaround to be able to use Codable somehow (I'm guessing using `JSONSerialization.data(withJSONObject:options:)` and then `JSONDecoder().decode()`, although it seems very inefficient assuming it even works reliably.)

**Comment by jcesarmobile** [comment]
implemented on https://github.com/ionic-team/capacitor/pull/7119
