### ISSUE TITLE
bug: cannot remove hardware back button handler

### ISSUE THREAD

**Issue by eric-horodyski** [ionic-team/capacitor#3444]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

While working with a community member, we set out to create an event handler on the `backButton` event that could be removed when a user completed a particular action; effectively preventing them from navigating out of the current view if they did not meet a specific criteria.

To proof this out, a blank Ionic Framework React app was created with a single page. It set the event listener in a `useEffect` and contained a button that on click, would call the `remove` method of the instance of the listener:

```TypeScript
let handle: PluginListenerHandle;
const { App } = Plugins;

useEffect(() => {
  handle = App.addListener("backButton", () => { alert("You are blocked"); });
}, []);

const removeHandler = () => { handle.remove(); };
```

While running the code, the following behavior was observed:
1. `native App.addListener` was printed to the console twice, both with differing `callbackId` values (X and Y) and the same `options.eventName` of `backButton`.
2. Pressing the hardware back button, `result App.addListener` was printed to the console, once for X and once for Y.
3. Tapping the button to remove the handler printed `native App.removeListener` with `options.callbackId` set to X.
4. Pressing the hardware back button, the listener intended to be removed was fired again, and `result App.addListener` was printed to the console, once for X and once for Y. 

### Expected Behavior

Upon calling the `remove` method of an instance of `PluginListenerHandle` it should not run the listener nor log it to the console. It is unknown if adding a listener to the `backButton` event should generate two separate callbackIds.

### Code Reproduction

https://github.com/ehorodyski-ionic/cap-android-back-listener

### Other Technical Details

`npm --version` output: 6.14.7

`node --version` output: 12.16.1

`pod --version` output (iOS issues only): N/A

**Comment by ehorodyski-ionic** [comment]
Thanks for the clarification on how the event listeners are registered. Is there any more information you need that could assist in isolating the edge case?

**Comment by Christina1701** [comment]
I have the same experience with Angular (version 10.0.2): 
Removing event listeners this way:
```
let handle: PluginListenerHandle;
const { App } = Plugins;

useEffect(() => {
  handle = App.addListener("backButton", () => { alert("You are blocked"); });
}, []);

const removeHandler = () => { handle.remove(); };
```
will not remove the listener. I´ve tested with listeners on "backButton" & "appStateChanged" and both event listeners won´t be removed.
The only workaround (currently) for me is to use ```App.removeAllListeners(); ``` which works as expected, but this has many side effects and can´t be used in every app...
