### ISSUE TITLE
bug: Android crashes when calling exitApp();

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor#3445]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

I wanted to implement the 'close app on native back button' feature.
When I call the `exitApp()` method the app closes and crashes. The app is still in the list of apps running in the background, but when the user re-opens the app the splash screen is shown and the app boots freshly.

Debugger output:
![9592f21b88cc660262b786244638290855042c5d](https://user-images.githubusercontent.com/1294854/90806385-39b5e480-e31d-11ea-935a-eabe7f64c7c0.png)

### Expected Behavior

I'd expect the app to not crash. It should pause in the background and resume when re-opened. (Just like it was with Cordova in the past).

### Code Reproduction

```
    if (!this.platform.is('android')) {
      return;
    }

    this.platform.backButton.subscribeWithPriority(1, () => {
      if (!this.routerOutlet.canGoBack()) {
        App.exitApp();
      }
    });
```

I've also created a minimal demo app, which reproduces the issue:
https://github.com/burningparrot/ionic-exit-app-crash-demo

### Reproduction steps:

1.) clone the repo above
2.) `ionic cap open android`
3.) run the app in debug mode on a physical device
4.) push the device's native back button to close the app
5.) Carefully observe the debugger output on android studio
6.) re-open the app from the background

**Comment by laclance** [comment]
For me App.exit(); does nothing, I am using react and not ionic.

**Comment by achyuthkodalipages** [comment]
Same issue for me with Angular and Capacitor

**Comment by jcesarmobile** [comment]
I've tested on 3 different devices and I can't reproduce the crash, and by the message it looks like a chrome bug, not a Capacitor bug.

`App.exitApp();` kills the app activity, it does exactly the same as Cordova's `navigator.app.exitApp();`. After calling any of them the app's activity is killed, and if you open it again, it will reload the whole app, not resume it.
It remains in "recent items", but that doesn't mean it's backgrounded, recent items shows any app that was recently closed.
If you don't want the app to appear when it has been closed you can add `android:autoRemoveFromRecents="true"` to the `activity` tag in `AndroidManifest.xml`.

**Comment by tobiasmuecksch** [comment]
@jcesarmobile Allright. Is there any way to only pause the app instead of killing it? It would be nice, if the decision was up to the developer which behavior he prefers.

**Comment by jcesarmobile** [comment]
I tested on Android 6, 9 and 11, all real devices. But as I said, this looks like a Chrome bug, not a Capacitor bug, so would be good to know the chrome version you have installed (just execute navigator.userAgent javascript in your app, the version is part of the user agent)

It's not possible to pause the app at the moment, there is this feature request, you can add the 👍  reaction to it if interested
https://github.com/ionic-team/capacitor/issues/1933
