### ISSUE TITLE
The default path capacitor looks at for Android Studio on windows is incorrect

### ISSUE THREAD

**Issue by jgw96** [ionic-team/capacitor#345]
The default installation path on windows for Android Studio is `C:\Program Files\Android\Android Studio\bin\studio64.exe`. Capacitor seems to be looking at the wrong path by default https://github.com/ionic-team/capacitor/blob/master/cli/src/config.ts#L12

**Comment by jcesarmobile** [comment]
I can confirm this, in a freshly installed W10, the default path that appeared when asked me for the install location was `C:\Program Files\Android\Android Studio`
