### ISSUE TITLE
feat: detect iphones with a notch at the top

### ISSUE THREAD

**Issue by michael-soorys** [ionic-team/capacitor#3450]
## Feature Request
Detect iPhones that have a notch at the top of the screen (X, XS, XR, 11...)

### Description

I would like a nicer way to detect if the device has a notch at the top or not since it changes some of the UI interactions. As of now the only way I could detect the actual model of the phone is with the cordova plugin https://github.com/apache/cordova-plugin-device

Besides the notched screen issue, the native Device capacitor plugin does not display the model of the device with getInfo()

### Platform(s)

Android, iOS

### Preferred Solution

The notch itself would be a nice addition but the fact that you can't detect the model of the device from the app without the use of external plugins is kind of strange.

**Comment by jmadelaine** [comment]
I agree. It's strange that `Device.getInfo().model` comes out as `iPhone`. That's not the model, that's the product line. Please implement this feature.

**Comment by michi7801** [comment]
Any updates on that? I cannot get the Cordova version to work and this is a feature which is absolutely mandatory for every developer! Or is there any workaround I am not aware of? (Turning the notch off for example?)

**Comment by jcardus** [comment]
Yes, I'm struggling with that also

**Comment by thewhtrabbt22** [comment]
+1

**Comment by oneclickwebstudio** [comment]
Same problem. how could we receive exact model version of device?  Could you implement this feature in `@capacitor/device` please? It would be great!

**Comment by michi7801** [comment]
Since a lot of people seem to struggle with this:
CSS has a constant which gives you the needed spacing to avoid the notch. It is called `safe-area-inset-top` (or `safe-area-inset-right`, `safe-area-inset-left`, etc...). 

For example:
```
.root-div {
    margin-top: env(safe-area-inset-top);
}
```

It is described here:
https://developer.mozilla.org/en-US/docs/Web/CSS/env()

**Comment by ilindaniel** [comment]
I think we can close this issue, no?
Like michi7801 suggested, just use the env variables provided by iOS WebKit.

Add viewport-fit=cover to viewport meta in your index.html:
`<meta name="viewport" content="viewport-fit=cover" />`

Add this to your css:
```
:root {
  --sat: env(safe-area-inset-top);
  --sar: env(safe-area-inset-right);
  --sab: env(safe-area-inset-bottom);
  --sal: env(safe-area-inset-left);
}
```

Then check if safe area is not 0px:
```
const safeAreaTop = getComputedStyle(document.documentElement).getPropertyValue("--sat")
if (safeAreaTop !== " 0px") {
    console.log("I'm on iOS")
}
```
Make sure there is a space before 0px
