### ISSUE TITLE
bug: "NPX CAP SERVE" Stucked

### ISSUE THREAD

**Issue by manel00** [ionic-team/capacitor#3453]
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed

### Platform(s)
PWA

### Current Behavior
NPX CAP SERVE Stucked and loading all the time on website localhost:3333

### Expected Behavior
Should work

### Other Technical Details

`npm --version` output: 6.13.0

`node --version` output: v14.6.0

**Comment by jcesarmobile** [comment]
We have removed serve command, if you use a framework, they usually have a dev server option. If not, you can use https://www.npmjs.com/package/serve
