### ISSUE TITLE
bug: ionic cap sync android --watch, watch is not working.

### ISSUE THREAD

**Issue by p770820** [ionic-team/capacitor#3454]
### Capacitor Version
5.4.5

### Platform(s)
Android

`npm --version` output: 6.14.6

`node --version` output: v12.18.3

my command: ionic cap sync android --watch
but it not watching and just finish.

![image](https://user-images.githubusercontent.com/9010279/91025837-7b4fd380-e62c-11ea-9f75-34cf72540c20.png)

**Comment by jcesarmobile** [comment]
This is an ionic cli bug, not a Capacitor bug.

Please, report it on https://github.com/ionic-team/ionic-cli/issues

Not sure what do you mean by version 5.4.5, but Capacitor is in version 2.x and the ionic CLI is in 6.x
