### ISSUE TITLE
bug: "npx cap update" automatically downgrades Podfile ios platform from 12.0 to 11.0

### ISSUE THREAD

**Issue by sisoje** [ionic-team/capacitor#3475]
## Bug Report
First line in my Podfile:
`platform :ios, '12.0'`
always changes  into
`platform :ios, '11.0'`

every time I do "npx cap update"

### Capacitor Version
2.x

```
PASTE OUTPUT HERE
```

### Platform(s)

ios

### Current Behavior

`platform` in the Podfile is downgraded after `npx cap update`

### Expected Behavior

`platform` in the Podfile should not be downgraded

### Other Technical Details

`npm --version` output:

`node --version` output: 12.x

`pod --version` output (iOS issues only): 1.9.3

**Comment by jcesarmobile** [comment]
Capacitor sets the Podfile iOS version from `ios.minVersion` value in `capacitor.config.json`, if not set it defaults to 11.

https://capacitorjs.com/docs/reference/config
