### ISSUE TITLE
bug: Ask permission when using Filesystem.readFile or add permission into the Permission plugin

### ISSUE THREAD

**Issue by mwyld** [ionic-team/capacitor#3492]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/electron not installed
  @capacitor/cli 2.2.0
  @capacitor/core 2.2.0
  @capacitor/android 2.2.0
  @capacitor/ios 2.2.0

[success] Android looking great! 👌
  Found 4 Capacitor plugins for ios:
    @capacitor-community/fcm (1.0.8)
    @capacitor-community/firebase-analytics (0.2.0)
    @capacitor-community/media (1.0.1)
    cordova-plugin-camera (4.1.0)
[success] iOS looking great! 👌

### Platform(s)
iOS

### Current Behavior
When reading a file using the Filesystem plugin I am getting a permission issue. I can't find a solution

### Expected Behavior
Prompt for permission when using the Filesystem plugin or add an extra functionality to do this in capacitor Permission plugin

### Code Reproduction
When calling `await Filesystem.readFile({ path })` I am receiving:

> [error] - Error: Uncaught (in promise): Error: The file “123.MOV” couldn’t be opened because you don’t have permission to view it.

### Other Technical Details
none

### Additional Context

Is there a quick workaround for this issue I could implement now?

**Comment by jcesarmobile** [comment]
iOS don't require permissions to read files, but can only read files inside its own sandbox, so you are probably trying to open a file outside the sandbox. Hard to tell because you didn't provide a sample app.

**Comment by mwyld** [comment]
Apologies. Here is a bit more detail:

I am trying to grab a video but it doesn't seem possible in capacitor so I am using the cordova Camera plugin and the mediaType of VIDEO. I'm then using the returned FILE_URI to get the video so later I can upload it to vimeo

```
this.camera.getPicture({
        destinationType: this.camera.DestinationType.FILE_URI,
        sourceType: this.camera.PictureSourceType.SAVEDPHOTOALBUM,
        mediaType: this.camera.MediaType.VIDEO
      }).then(async (path) => {


        let video;
        try {
          video = await Filesystem.readFile({
            path
          })
        } catch (err) {
           console.log(err)
        }
});
```

**Comment by mwyld** [comment]
I still haven't found a solution to this, but will post here if I do. Would you let me know if you do too? Ideally this ticket could do with being re-opened

**Comment by calls9-mattwyld** [comment]
Hey @spasma and @agomezmoron 

I've had another crack at this, if you copy the video into cache then read from that it seems to work okay. 
Here's my code snippet

```
let video;
await Filesystem.copy({
            from: path,
            to: 'my-apps-video.MOV',
            toDirectory: FilesystemDirectory.Cache
    }).then(async () => {
         video = await Filesystem.readFile({
              directory: FilesystemDirectory.Cache,
              path: 'my-apps-video.MOV'
         })
})
```

**Comment by spasma** [comment]
Hi @mwyld, thank you for sharing your findings. A few days ago I found this issue on the camera plug-in, but I haven't checked the solution yet. My client postponed the options to select videos from the library due to the issue.

https://github.com/apache/cordova-plugin-camera/issues/506#issuecomment-534070130
