### ISSUE TITLE
Bug: [Filesystem] Can't see saved images on iOS Photos Gallery, while on Android is working fine

### ISSUE THREAD

**Issue by masterbd** [ionic-team/capacitor#3494]
### Capacitor Version
```
@capacitor/cli 2.4.0
@capacitor/ios 2.4.0
@capacitor/android 2.4.0
@capacitor/core 2.4.0
@capacitor/electron not installed
```

### Platform(s)
iOS

### Current Behavior
Currently I'm not able to see the saved images in the Photos. For Android after I save an image I can see it in the gallery, on iOS the image is saved, i can see it in the directory but is not shown in the Photo Gallery.

### Expected Behavior
All saved photos should be available in the iOS Photos Gallery exact as it is on Android.

### Code Reproduction
```
async savePhoto() {
  try {
    const { Filesystem } = Plugins;
    const base64Data = await this.readAsBase64(this.imageFull);
    const fileName = `${new Date().getTime()}.jpg`;

    const image = await Filesystem.writeFile({
      path: fileName,
      data: base64Data,
      directory: FilesystemDirectory.Data // I've tried with all types
    });

    if (image.uri) {
       console.log('Image has been saved into your gallery');
    }
  } catch (e) { console.error(e);  }
}

private async readAsBase64(url: string): Promise<string> {
   const response = await fetch(url);
   const blob = await response.blob();
   return await this.convertBlobToBase64(blob) as string;
}

private async convertBlobToBase64(blob: Blob): Promise<string | ArrayBuffer> {
   return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onerror = () => reject();
      reader.onload = () => resolve(reader.result);
      reader.readAsDataURL(blob);
   });
}
```

### Other Technical Details
npm: 6.14.6
node: 14.6.0
pod: 1.8.4

**Comment by jcesarmobile** [comment]
Neither iOS or Android have any code to make Filesystem write the images to the gallery, and they won't have it.

On Android, by how the OS works, if you write in some locations, the images can appear on the gallery, but they are getting stricter about it, so you shouldn't rely on it as it doesn't work on Android 10 unless you enable legacy filesystem and won't work on Android 11 or newer.

For making images appear on the gallery you should use some plugin that "writes" explicitly to the gallery, such as https://github.com/capacitor-community/media

**Comment by masterbd** [comment]
Thank's @jcesarmobile! 
I've tried that plugin but didn't work. I will create an issue in their respective repository then.
I do appreciate your work! Best!

**Comment by tiankai329** [comment]
is there any other way to save image to gallery by ionic capacitor for ios?
