### ISSUE TITLE
bug: PushNotifications on Android, if the app is killed will not show 

### ISSUE THREAD

**Issue by mariokandut** [ionic-team/capacitor#3500]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/electron not installed
```

### Platform(s)

- Android 10

### Current Behavior

The push notifications (setup via [tutorial](https://capacitorjs.com/docs/guides/push-notifications-firebase)) and send via firebase console do not work if the application is closed (not minimized) on the phone.

### Expected Behavior

The sent push notifications should be in the system tray.

### Other Technical Details

`npm --version` output: 6.12.1

`node --version` output: v12.13.1

`pod --version` output (iOS issues only): --

**Comment by rubenstolk** [comment]
Even when the app is in the background, the notifications don't show up.

**Comment by iepur1lla** [comment]
@rubenstolk: In the android debugger mode (chrome with connected device) you will see that the push notification with payload is received and you can trigger an in app notification (snackbar, ...) or LocalNotification for this. This bug ticket is when the app is killed. Any idea how to fix?

**Comment by rubenstolk** [comment]
I have no clue... this is painful though, just moved over from cordova push plugin and was expecting things to be similar...

**Comment by rubenstolk** [comment]
I figured this had to do with the payload of the notification, I had to explicitly add `gcm.notification.title` and `gcm.notification.body` in my payload.

**Comment by iepur1lla** [comment]
The issue in my case was that the default channel for local notifications and/or push notifications had to be created, see [push-notifcations](https://capacitorjs.com/docs/apis/push-notifications#method-createChannel-0) and [local-notifications](https://capacitorjs.com/docs/apis/local-notifications#method-createChannel-0).

So I would refer from bug to missing documentation.

**Comment by nourkrimesh** [comment]
I had the same issue and fixed it with the following lines in AndroidManifest.xml

<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id" />
<service
android:name="com.getcapacitor.CapacitorFirebaseMessagingService"
android:exported="false">
<intent-filter>
<action android:name="com.google.firebase.MESSAGING_EVENT" />
</intent-filter>
</service>

**Comment by bolivir** [comment]
I had the problem that i didnt receive the push message on android too (Ios working).
After some digging, and tried to send the message directly over the FCM console ... and voilla the notification was received in the background on android. Sending it again from our server did not receive it (Not in background, in foreground it was ok).

Now i noticed some difference the way the payload was sended between FCM and our server. We send the notification as data and the title and body field is inside the data. FCM sends an empty data object, but the title and body are outside of the data.

So fcm sends:
`{"id":"","data":{},"title":"Test","body":"Test"}`

And we are sending:
`{"id":"","data":{"title": "Test", "body": "test"}}`

I need to look some further into this, but for me it looks like it cannot handle the push when the title/body field is not present directly in the payload. (We are migrating our app, and the cordova push handled this implementation correct)

**Comment by bolivir** [comment]
Ok, it seems that only the phonegap push plugin had a custom implementation for handling data only pushes. Then it makes sense for me too see this behaviour when sending the payload as i described above.

So for anyone with the described problem verify that youre not sending data only pushes as they wont trigger the notification when the app is closed or in te background.

I think some better documentation on the capacitor site would prevend users for this ... huh moment. Some payloads examples would help and as a side note notice that data only pushes dont trigger the notification wenn the app is closed or in the background.

**Comment by Avareto** [comment]
receiving message in the background and when the app was close on Android works with capacitor push plugin ony if you send the following firebase cloud message payload:

```
{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "notification":{
      "title":"Portugal vs. Denmark",
      "body":"great match!"
    },
    "data" : {
      "Nick" : "Mario",
      "Room" : "PortugalVSDenmark"
    }
}
```
See here: https://firebase.google.com/docs/cloud-messaging/concept-options?hl=en

**Comment by bolivir** [comment]
> receiving message in the background and when the app was close on Android works with capacitor push plugin ony if you send the following firebase cloud message payload:
> 
> ```
> {
>     "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
>     "notification":{
>       "title":"Portugal vs. Denmark",
>       "body":"great match!"
>     },
>     "data" : {
>       "Nick" : "Mario",
>       "Room" : "PortugalVSDenmark"
>     }
> }
> ```
> 
> See here: https://firebase.google.com/docs/cloud-messaging/concept-options?hl=en

Thats just what i said in my comment. But i think people coming from the phonegap plugin and use data only pushes wont notice that the phonegap veraion has an custom implementation that handles data only pushes.

Therefore most of them including me would think the capacitor one isnt working as expected

**Comment by Avareto** [comment]
The important point is that background notifictions are not received properly when you ommit the "notification" property (missing in your payload description), when the App is cloesed or in background mode. 
Also, the "id" property is not defined and should be replaced by the "token" property, which is optional anyway.

**Comment by Junich10** [comment]
It is finally working for me.

for my situation, it was two problems combined. I had to add the notification part to the payload as described in above comments and I had to enable the autostart configuration in autostart manager. without those two, I could not receive notification when the app was killed. I spent days searching for the solution..

Not sure if this is related but I also changed the firebaseMessagingVersion in variable.gradle.
https://github.com/ionic-team/capacitor/issues/3187

There are few articles on power saving options and notification option for each phone manufacturers so you should look there too if above steps didnt help. this page has some useful information.
https://help.pushwoosh.com/hc/en-us/articles/360028478751-Android-device-cannot-receive-push-notifications-when-an-application-is-force-stopped-killed-

**Comment by dimosmertzanidis** [comment]
> I figured this had to do with the payload of the notification, I had to explicitly add `gcm.notification.title` and `gcm.notification.body` in my payload.

That was a life saving!
