### ISSUE TITLE
bug: Geolocation.getCurrentPosition() not working (Promisse keeps in pending status)

### ISSUE THREAD

**Issue by andrewl94** [ionic-team/capacitor#3505]
### Capacitor Version

```
PASTE OUTPUT HERE
```

λ npx cap doctor
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/android 2.4.0
  @capacitor/core 2.4.0
  @capacitor/electron not installed

[success] Android looking great! �
[error] Xcode is not installed

### Platform(s)

Android  - Quasar Framework

### Current Behavior

The getCurrentPosition() keeps on pending status forever

### Expected Behavior

The getCurrentPosition() resolves and returns de geocode data

### Code Reproduction

![image](https://user-images.githubusercontent.com/23385661/92175750-8d432a80-ee13-11ea-96bf-7c38cda3b3e8.png)

![image](https://user-images.githubusercontent.com/23385661/92175683-7a305a80-ee13-11ea-8f64-e37fca0c3121.png)

### Other Technical Details

`npm --version` output:6.14.4

`node --version` output:v12.18.0

`pod --version` output (iOS issues only):

### Additional Context

Was working as intended before without problems and with no changes in the current development build.

**Comment by andrewl94** [comment]
Error on my side: Fake GPS enabled, but closed.

**Comment by lpyedge** [comment]
the same error with my project.
Geolocation plugin worked fine in ios,but can not work in android.
