### ISSUE TITLE
bug: Local Notification channel creation not working

### ISSUE THREAD

**Issue by MInesGomes** [ionic-team/capacitor#3506]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/android 2.4.0
  @capacitor/core 2.4.0
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Current Behavior
Sound only works if I define in capacitor.config.json.
Doesn't work if I want to create a dynamic channel sound (for api 26+) 
And it doesn't play custom sound for api < 26

### Expected Behavior
I have a working app with cordova where I can set dynamically the sound
I  just need to set a name for the channel and the sound and plays custom sound
For api 26+ uses the channel & sound, for api < 26 uses just the sound 

It would be nice to have something similar
Cordova code is here:
https://github.com/Steffaan/cordova-plugin-local-notifications/blob/06863a7b453706a1335119ac7cdd7cc157f765de/src/android/notification/Manager.java#L120

### Code Reproduction

**capacitor.config.json**  
bebep.mp3 is working
```
 "LocalNotifications": {
      "smallIcon": "ic_stat_icon_config_sample",
      "iconColor": "#488AFF",
      "sound": "bebep.mp3"
    }
```

**home.ts**

```
 const channel: NotificationChannel = {
      id: '12',
      name: 'channel1',
      importance: 5,
      sound: 'emergency.mp3' 
    };

    Plugins.LocalNotifications.createChannel(channel); // <- give an error if api < 26

   LocalNotifications.schedule({
      notifications: [{
        title: 'Test',
        body:  'testing sound', 
        id: 1,
        channelId: '12' // <- If I comment works the default sound set in capacitor.config.json
      }]
    });
```

If I print the list of channels it gives me this:

```
Array(2)
0:
description: ""
id: "12"
importance: 5
lightColor: "#000000"
lights: false
name: "channel1"
sound: "android.resource://io.ionic.starter/raw/emergency"
vibration: false
visibility: -1000
1:
description: "Default"
id: "default"
importance: 3
lightColor: "#000000"
lights: false
name: "Default"
sound: "android.resource://io.ionic.starter/2131623936"
vibration: false
visibility: -1000
```

this
`sound: "android.resource://io.ionic.starter/raw/emergency"`
doesn't have an extension

### Other Technical Details

 npm -v.  6.14.5
 node -v.  v12.18.2

**Comment by jcesarmobile** [comment]
please, provide a sample app, custom sounds work fine on my testing.

**Comment by MInesGomes** [comment]
https://github.com/MInesGomes/mRes/blob/99aa9db6457ab197392cb975d45845e0e7affd5f/src/app/tab1/tab1.page.ts#L94

**Comment by jcesarmobile** [comment]
please, a public sample app

**Comment by MInesGomes** [comment]
> please, a public sample app

@cesarmobile Changed to public :-)
Thanks for the help

**Comment by jcesarmobile** [comment]
what should I be looking at? When I run the app it ask for location permission, I accept and see a notification with "Test" text and emergency.mp3 sound playing, the line you linked about `const sound = 'bebep';`, the constant is not used and it's missing the mp3 extension

**Comment by MInesGomes** [comment]
So strange @ jcesarmobile ...
I don't hear the sound....
I changed the code above to set a notification on tab 1, with custom sound **emergency** 
and on tab 2 with default sound **bebep**.
https://github.com/MInesGomes/mRes/blob/f765a06e66dad426787729e91f995332570b58b2/src/app/tab2/tab2.page.ts#L10

On tab 1 I don't listen nothing.
On tab 2 I listen to **bebep** custom sound.

My testing device is samsung Galaxy Cover 4 SM-G390F, Android version 9.

Can you hear a sound in both tabs?

**Comment by jcesarmobile** [comment]
What is probably happening is that you installed the app before setting the default sound.
Most Android channel properties can't be changed after the channel creation (sound included), and the plugin creates the default channel on first launch of the app, so configuring the sound after first launch will have no effect. It works on custom channels because you create them with the sound.

**Comment by MInesGomes** [comment]
Thank you for the reply @jcesarmobile . I uninstalled and installed several times with different sounds and the result is always the same the sound that is on config plays. But if I try to set a sound with channelId. Nothing plays. Do you have any example app of a working change channel ?

**Comment by jcesarmobile** [comment]
I don't have any example, your app is working fine on my devices, I hear emergency sound on tab1 and bepbep sound on tab 2, tested on Android 8.1 and 9.0 devices.
Listing the channels shows the same values as yours

```
channels: Array(2)
0:
description: ""
id: "12"
importance: 5
lightColor: "#000000"
lights: false
name: "channel1"
sound: "android.resource://io.ionic.starter/raw/emergency"
vibration: false
visibility: -1000
__proto__: Object
1:
description: "Default"
id: "default"
importance: 3
lightColor: "#000000"
lights: false
name: "Default"
sound: "android.resource://io.ionic.starter/2131623936"
vibration: false
visibility: -1000
```

**Comment by MInesGomes** [comment]
@jcesarmobile Thank you for the help. What device are you testing?

**Comment by Maraaghib** [comment]
@MInesGomes  I have fixed this issue by creating first a channel:

![image](https://user-images.githubusercontent.com/25940227/102218381-2804d800-3ede-11eb-88da-ccb1ba3f5f5a.png)
The 'slap.wav' file is stored in `android\app\src\main\res\raw\` folder

Then, I schedule my notification without speciying the sound path:

![image](https://user-images.githubusercontent.com/25940227/102218721-b24d3c00-3ede-11eb-835f-ae6124b0d34c.png)

**PS: I did not do any configuration on capcitor.config.json**

It works perfectly on Samsung Galaxy A71 (SM-A715F) - Android 10

If you want to change dynamically the notification sound, you delete this channel and create another one with only a different id
