### ISSUE TITLE
Confusing StatusBar Native Plugin

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/capacitor#3511]
I am not sure this a bug but... I just created today with the latest ionic CLI with `ionic start appName blank --capacitor` a new project. After my first `ionic serve` i wonder alot about the console error: 

```
common.js:284 Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
common.js:284 Native: tried calling SplashScreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
```

I expected that my project is now only using capacitor because the `--capacitor` param?

Then i checked app.component and saw this:

```
import {StatusBar} from '@ionic-native/status-bar/ngx';

initializeApp() {
    this.platform.ready().then(() => {
        this.statusBar.styleDefault();
        this.splashScreen.hide();
    });
}
```

Then i checked the docs: https://ionicframework.com/docs/native/status-bar

When i click there on **Installation > Capacitor** i get this:

```
npm install cordova-plugin-statusbar
npm install @ionic-native/status-bar
ionic cap sync
```

Why i need to install cordova-plugin-statusbar? is this a bug in the docs?
A bit more down: https://ionicframework.com/docs/native/status-bar#capacitor **Capacitor > Not compatible**
If it is not compatible... why i can install it then?

then i opend: https://capacitorjs.com/docs/apis/status-bar and realize that there is a plugin for statusBar from Capacitor...
But the syntax in app.component is `this.statusBar.styleDefault();` and `styleDefault;` dont exist there... Hell what is going on here? :D

Then i checked https://github.com/apache/cordova-plugin-statusbar and understand that `styleDefault;` is a part of the cordova plugin... 

can someone help me to understand what is going on here and how to kick this cordova 100% out of my app and use instead capacitor for the statusbar?

**Comment by jcesarmobile** [comment]
Ionic angular templates are still cordova templates and include some cordova plugins. For now you have to manually replace those plugin usages with capacitor plugin equivalents until the templates are updated.
