### ISSUE TITLE
bug: Camera plugin: requestPermissions emits and empty object when called

### ISSUE THREAD

**Issue by lcatania** [ionic-team/capacitor#3541]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.1
  @capacitor/android 2.4.1
  @capacitor/core 2.4.1
  @capacitor/electron not installed
```

### Platform(s)

Android

### Current Behavior

When the Camera.requestPermissions()  is called the response is just a empty object.

### Expected Behavior

I expected that the android permission dialog opens.

### Other Technical Details

`npm --version` 6.13.4:

`node --version` v12.14.1:

`pod --version` output (iOS issues only):

**Comment by dwieeb** [comment]
@lcatania Does the camera work? Are permissions already granted? How are you importing `Camera`?

**Comment by lcatania** [comment]
@dwieeb Yeah the camera does work and the what i did is.

Im importing the camera like in the exmaple 
`import { Plugins, StatusBarStyle } from "@capacitor/core";`
`const { SplashScreen, Network, Device, StatusBar } = Plugins;`

1. Open Camera
2. Deny permission
3. Try to ask for permission with requestPermission()

thank you

**Comment by jcesarmobile** [comment]
requestPermissions is available for all plugins, but only implemented for Filesystem and Geolocation, so yeah, should be implemented for Camera too.

**Comment by manel00** [comment]
Hello,

Apple is asking me about why i don't request permission for the camera on Ionic (capacitor). Cannot find how to solve it...

Thank you
