### ISSUE TITLE
feat: Build Safety - Detect outdated apps to increase release safety and prevent common mistakes

### ISSUE THREAD

**Issue by fkirc** [ionic-team/capacitor#3544]
### Description

Now that Capacitor is becoming a mature project, I feel we should not only focus on features and bugfixes, but also on the day-to-day workflows of app developers.
One thing that has always annoyed me is the risk to produce _outdated apps_, that is, native apps where the web-assets originate from a different commit/branch than the current commit/branch.
For example, outdated apps can happen if a developer forgot to run `npx cap sync` after a `git pull`.
The damage of outdated apps can vary:

- If a developer does not discover the mistake immediately, then this might waste quite a lot of time (e.g. if manual tests have to be repeated).
- In the worst case, a broken release gets published to app stores.

### Platform(s)

iOS (template project), Android (template project)

### Preferred Solution

I created the tool [capsafe](https://github.com/fkirc/capacitor-build-safety) to solve the issue for all my projects: https://github.com/fkirc/capacitor-build-safety
You can give `capsafe` a try with:

`npm install --save-dev capacitor-build-safety`

`capsafe`'s [README](https://github.com/fkirc/capacitor-build-safety/blob/master/README.md) does not only describe how to integrate `capsafe`, but also describes my philosophy on how the issue should be solved.

However, although I believe that `capsafe` is a great fit for most development teams, `capsafe` is still too opinionated for a merge into Capacitor. To merge those safety checks into Capacitor, I aim to establish a "minimum-viable-compromise", that is, the least opinionated solution that still creates value.

### Proposed Solution: prebuild.sh scripts

I propose the following solution to be integrated into Capacitor's template projects (iOS/Android):

- Add two new scripts `prebuild.sh` to the iOS/Android template projects.
- During each iOS/Android-build, `prebuild.sh` checks whether a web-asset directory exists at the right location. If not, then `prebuild.sh` prints a meaningful warning message. This warning message will accompany the following error ("404: could not load from localhost...").
- `prebuild.sh` will be an extension point for developers who want to add actual safety-checks instead of warning messages (e.g. `capsafe verify-commit-evidence`).

See [README](https://github.com/fkirc/capacitor-build-safety/blob/master/README.md) for platform-specific details on how the `prebuild.sh` scripts could be executed.

### Alternatives

If we are not changing the iOS/Android template projects, then we might at least add some guidance to the documentation.

In theory, `capsafe` could be replaced with dead-simple shell scripts.
However, `capsafe` provides more relaxed safety checks than a simple shell script (e.g. a fast `capsafe disable` command, looking at tree-hashes in addition to commit hashes, better error messages).

**Comment by fkirc** [comment]
EDIT: Updated the proposal to print a warning message instead of aborting the build. Aborting the build could be too restrictive because of the following:

- Developers want to see whether their native builds are doing something. 
- Developers might run an app without any web-build (in which case a warning message is warranted, see https://github.com/ionic-team/capacitor/discussions/1478 for details).

**Comment by fkirc** [comment]
I created a PR to implement the proposed solution: https://github.com/ionic-team/capacitor/pull/3555

**Comment by jcesarmobile** [comment]
Closing as won't do, people interested in this feature can use capsafe package
