### ISSUE TITLE
bug: Black gap when iOS keyboard type changes

### ISSUE THREAD

**Issue by dminkovsky** [ionic-team/capacitor#3547]
### Capacitor Version

```
$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.1
  @capacitor/core: 2.4.1
  @capacitor/android: 2.4.1
  @capacitor/electron: 2.4.1
  @capacitor/ios: 2.4.1

Installed Dependencies:

  @capacitor/cli 2.4.1
  @capacitor/core 2.4.1
  @capacitor/android 2.4.1
  @capacitor/ios 2.4.1
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 5 Capacitor plugins for ios:
    cordova-open-native-settings (1.5.2)
    cordova-plugin-facebook4 (6.2.0)
    cordova-plugin-googleplus (8.2.1)
    cordova-plugin-purchase (10.1.2)
    cordova-plugin-sign-in-with-apple (0.1.2)
[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

A black box appears when the keyboard type is changed. Looks like this:

![ezgif-6-e572595a3684](https://user-images.githubusercontent.com/218725/93011215-45827880-f562-11ea-85c3-b6f2c4b2e12c.gif)

### Expected Behavior

No black gap

### Other Technical Details

`npm --version` output: 6.1.4

`node --version` output: v12.16.3

`pod --version` output (iOS issues only): 1.9.1

**Comment by jcesarmobile** [comment]
This happens because of the Keyboard plugin native resize mode (default mode), as it resizes the webview on the keyboard hide/show, when changing fields the resize is slower than a full hide/close and the black background appears.

In Capacitor 3 we are moving plugins out, so will be "fixed" if you don't install @capacitor/keyboard.

**Comment by dminkovsky** [comment]
I looked into this and yes it happens because the window doesn’t resize at
the same rate as the keyboard hides. The black barn is empty space where
the app window is not there.  Sadly I didn’t/don’t know enough about iOS
development to figure out how to control animation easings on the window.

But regarding closing this issue:

If you don’t install @capacitor/keyboard, won’t you not have a keyboard?

If you do install @capacitor/keyboard, won’t you have the same issue?

пн, 30 нояб. 2020 г. в 2:06 PM, jcesarmobile <notifications@github.com>:
