### ISSUE TITLE
bug: Android Studio cannot find "android.support.v4.content.FileProvider". Unable to fix it with previous suggested fixes.

### ISSUE THREAD

**Issue by Zerokk** [ionic-team/capacitor#3554]
### Capacitor Version
```
  @capacitor/cli 2.2.0
  @capacitor/core 2.2.0
  @capacitor/android 2.2.0
  @capacitor/ios 2.2.0
```

### Platform(s)
Android (so far; didn't test on iOS yet)

### Current Behavior
Gradle isn't capable of finding a package that I need to use Camera/File plugins for Capacitor. The error is here:

```
C:\Projects\My_Project\android\capacitor-cordova-android-plugins\src\main\java\org\apache\cordova\camera\CameraLauncher.java:40: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;

```

### Expected Behavior
These plugins should be working fine and letting me build an APK in order to test the imagePicker feature of the Camera plugin, so the users can upload pictures from their phones.

### Code Reproduction
- Make an Ionic Capacitor project.
- Prepare it for Android
- Install the Camera and File plugins for Capacitor.
- Wrap them into the Angular Module's providers in which you're going to use them.
- ionic cap sync
- npx cap open android
- Build -> "Build APK"

There, the error should arise.

### Other Technical Details

`npm --version` output: 6.14.7

`node --version` output: v14.8.0

### Additional Context

After being totally unable to use the Cordova's ImagePicker plugin for Capacitor (for a very similar reason, actually), I decided to switch to [the Camera/File option that I saw in this article](https://enappd.com/blog/camera-and-image-picker-in-ionic-apps/148/). But then, this error arose. I tried to fix it using the Android Studio's "Refactor -> Migrate to AndroidX" solution that many people suggested in StackOverflow and this same GitHub Issues, but it didn't help.

The problem seems to be in this import: 

![imagen](https://user-images.githubusercontent.com/10697745/93097387-cbf3a300-f6a5-11ea-839a-3ce4b635e434.png)

The import doesn't change after the refactor, which is weird. It doesn't throw any other error whatsoever; it just keeps being the same error that I said before.

Any help with this issue, please?

**Comment by Zerokk** [comment]
Okay, I managed to fix this thing, although the fix is the total inverse of a "clean" solution; let me explain why.

As I said, I used the Android Studio's tool to migrate to AndroidX (Refactor -> Migrate to AndroidX), but it didn't do much. But after doing so, and reading [this solution ](https://stackoverflow.com/questions/48534293/android-support-v4-content-fileprovider-not-found) (the second one, with ~138 upvotes) I saw that the path for the FileSystem import that was failing, was "androidx.core.content.FileProvider".

Then, I just replaced the previous:

`android.support.v4.content.FileProvider

... with:

`import androidx.core.content.FileProvider`

I had to do it in 3 files, accounting the one that was giving the error. Afterwards, building the APK gave no errors, and the Camera Plugin seemed to work perfectly well (I still have to finish the implementation, but it does indeed retrieve a base64 string when choosing a picture, which sounds like a win!)

Anyways, I think that the Ionic & Capacitor team should tackle this issue and try to fix these unclean errors to avoid other developers to spend a big chunk of their work fixing this stuff.

**Comment by Zerokk** [comment]
Correction: **no, the upper post is NOT a valid solution**.

Not only something's failing when correctly retrieving the images, but also using "ionic cap sync" will delete the package corrections that I stated before. Therefore, you'd need to manually change them every time you make a new APK to test.

This is a serious issue. Still hoping someone can lend a helping hand here.

**Comment by jcesarmobile** [comment]
The problem is that cordova plugin doesn't use AndroidX, Capacitor 2 uses AndroidX and you can't mix AndroidX with non AndroidX dependencies.

The solution we recommend for those plugins is using jetifier, see https://capacitorjs.com/docs/android/troubleshooting#error-package-android-support-does-not-exist

**Comment by Zerokk** [comment]
Thank you, that helped fixing the package problem.
