### ISSUE TITLE
onesignal-cordova-plugin 

### ISSUE THREAD

**Issue by edy-ap** [ionic-team/capacitor#357]
Android dependency 'com.android.support:customtabs' has different version for the compile (26.1.0) and runtime (27.0.2) classpath. You should manually set the same version via DependencyResolution

**Comment by jcesarmobile** [comment]
I think best way of handling this is to add the dependency to the app's build.gradle with the version you want to use. (i.e. `implementation 'com.android.support:customtabs:27.1.1'`). That should get rid of this problem.

Another option is to add something linke

```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}
```
