### ISSUE TITLE
bug: quasar build -m capacitor -T android  fails to build apk

### ISSUE THREAD

**Issue by abbjoafli** [ionic-team/capacitor#3571]
## Bug Report
When i try to build my Quasar code with capacitor then it comes upp with an error

BUILD SUCCESSFUL in 29s
46 actionable tasks: 21 executed, 25 up-to-date
(node:6840) UnhandledPromiseRejectionWarning:   Error: ENOENT: no such file or directory, stat 'C:\Users\joafli\Documents\projs\AdaApp\src-capacitor\android\app\build  \outputs'

i have manually created the folders to see if something is different but still the same error.

### Capacitor Version

```
PASTE OUTPUT HERE
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Quasar is the one doing the build, so you should report it to them
