### ISSUE TITLE
TypeError: cameraModal.componentOnReady is not a function

### ISSUE THREAD

**Issue by mu250234** [ionic-team/capacitor#358]
TypeError: cameraModal.componentOnReady is not a function getting this error while trying to use camera with ionic capacitor

**Comment by jcesarmobile** [comment]
In which platform are you testing?
Steps to reproduce?
Code you used?

**Comment by mu250234** [comment]
hi thanks,

I am testing in windows platform,(deskstop).

please find code snipet:
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
const { Camera } = Plugins;


  takePicture() {
    Camera.getPhoto({
      quality: 90,
      allowEditing: true,
      resultType: CameraResultType.Base64
    }).then(imageData => {
      //this.image = this.sanitizer.bypassSecurityTrustResourceUrl(imageData );

      console.log('IMAGEURL', this.image, imageData)

    })
    // image.base64_data will contain the base64 encoded result as a JPEG, with the data-uri prefix added
    // can be set to the src of an image now
  }.

**Comment by mlynch** [comment]
You need to include the ionic PWA elements script. See the example/src/index.html in this repo. We will be fixing this and making it easier soon

**Comment by cdarken** [comment]
Sorry for reviving this thread, but it's the closest one I've found to my issue. [Here](https://capacitor.ionicframework.com/docs/getting-started/pwa-elements/) you state this:
```
Or by installing and then importing from @ionic/pwa-elements:
npm install @ionic/pwa-elements
import '@ionic/pwa-elements';
```
I installed it, but where do I import it?
I have a new app created with ionic like this:
```
ionic start my-app sidemenu --type=angular --capacitor
```

**Comment by TaiJinYuan** [comment]
Check this [document](https://capacitor.ionicframework.com/docs/pwa-elements/).

> npm install @ionic/pwa-elements

**in main.ts,**

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

_import { defineCustomElements } from '@ionic/pwa-elements/loader';_

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

// Call the element loader after the platform has been bootstrapped
_defineCustomElements(window);_
```
Hope this will help.
Thank  you.

**Comment by StevieWag** [comment]
@TaiJinYuan , thanks for the advice. That fixed it for me.

**Comment by obendesmond** [comment]
Simple add 

<script type="module" src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"></script>
<script nomodule src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"></script>


 in your index.html

**Comment by DeepaPrasanna** [comment]
> Simple add
> 
> <script type="module" src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"></script> <script nomodule src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"></script>
> in your index.html

thanks it worked

**Comment by obendesmond** [comment]
@DeepaPrasanna welcome

**Comment by bleuscyther** [comment]
😁😅
I saw this in the official Capacitor documentation and i forgot about it.
If someone needs this for React or Angular her is the link

[https://capacitor.ionicframework.com/docs/pwa-elements/](https://capacitor.ionicframework.com/docs/pwa-elements/)

**Comment by anRoswell** [comment]
Gracias @busihelper me sirvió mucho...

**Comment by Carsen-Busette** [comment]
Thanks to you all !

**Comment by Jwendo** [comment]
@business-helper thank you! that fixed it for me
