### ISSUE TITLE
feat: Browser Plugin executeScript

### ISSUE THREAD

**Issue by jonathan-chin** [ionic-team/capacitor#3581]
## Feature Request

I was looking over the capacitor documentation for the Browser plugin and noticed there was no access point to insert javascript and css into the loaded page. with the Cordova version, there are executeScript and insertCSS functions which accomplish this.

is there any way to achieve these things with the existing capacitor API?
if not, is there a reason it wasn't included (eg security concerns)?
if not, is there any interest in implementing such access points?

**Comment by jcesarmobile** [comment]
Capacitor uses SFSafariViewController on iOS and Chrome Custom Tabs on Android and none of those have APIs for doing what you want.
So if you need those features, better keep using cordova-plugin-inappbrowser of create a similar Capacitor plugin
