### ISSUE TITLE
bug: Browser Plugin not opening app url scheme on direct redirect

### ISSUE THREAD

**Issue by telpat0298** [ionic-team/capacitor#3583]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.1

  @capacitor/core: 2.4.1

  @capacitor/android: 2.4.1

  @capacitor/electron: 2.4.1

  @capacitor/ios: 2.4.1

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed


  @capacitor/cli 2.0.1

  @capacitor/android 2.4.1

  @capacitor/core 2.4.1

[success] Android looking great! 👌
```

### Platform(s)

Android (Not tested yet on iOS)

### Current Behavior

I'am using keycloak as authentication service. When opening keycloaks login page with capacitors Browser-plugin i'm able to submit the login-form an get the needed information's through a configured app url scheme on android. But when the users already logged in, keycloak redirect's to the configured app url scheme but the app does not open.
Usually, when the user is already logged in, the login page doesn't/shouldn't open. But if the user, in some way, loses his local session data, but the session on keycloak is still active, this behavior happens.

### Expected Behavior

The app should open when the browser redirects to the configured app url scheme. 

### Other Technical Details

`Manifest configuration:`
```
<intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:scheme="http"
                    android:host="odis.com" />
            </intent-filter>
```
`npm --version` output:
{
  apptwo: '0.0.1',
  npm: '6.14.8',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '36.1',
  icu: '66.1',
  llhttp: '2.0.4',
  modules: '79',
  napi: '6',
  nghttp2: '1.40.0',
  node: '13.14.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '7.9.317.25-node.32',
  zlib: '1.2.11'
}

`node --version` output:
v13.14.0

**Comment by telpat0298** [comment]
Ok, i've got it working. I changed the scheme to app:// and it works even on a direct redirect

**Comment by virginiadepaula** [comment]
Hi, i have the same problem and change the scheme to app, but don't redirect to app and if I back by the phone return, the error **E/Capacitor/BrowserPlugin: Error binding to custom tabs service** is show

AndroidManifest:
 **<data
          android:scheme="app"
          android:host="io.ionic.starter"
          android:path="/assets/public/callback" />**
