### ISSUE TITLE
bug: AndroidManifest.xml not receiving the strings from strings.xml correctly for Cordova Plugins

### ISSUE THREAD

**Issue by andrewl94** [ionic-team/capacitor#3588]
### Capacitor Version

```
Latest Dependencies:              
                                  
  @capacitor/cli: 2.4.1           
  @capacitor/core: 2.4.1          
  @capacitor/android: 2.4.1       
  @capacitor/electron: 2.4.1      
  @capacitor/ios: 2.4.1           
                                  
Installed Dependencies:           
                                  
  @capacitor/ios not installed    
  @capacitor/cli 2.4.0            
  @capacitor/android 2.4.0        
  @capacitor/core 2.4.0           
  @capacitor/electron not installe
                                  
[success] Android looking great! �
[error] Xcode is not installed    
```

### Platform(s)

Android

### Current Behavior

Throws error 

* What went wrong:
Execution failed for task ':capacitor-cordova-android-plugins:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     C:\xampp\htdocs\xtraining\app\src-capacitor\android\capacitor-cordova-android-plugins\src\main\AndroidManifest.xml:20:1-199: AAPT: error: resource string/mauron85_bgloc_content_authority (aka capacitor.android.plugins:string/mauron85_bgloc_content_authority) not found.

Even with the strings.xml set:
```
<string name="mauron85_bgloc_account_name">@string/app_name</string>
<string name="mauron85_bgloc_account_type">$PACKAGE_NAME.account</string>
<string name="mauron85_bgloc_content_authority">$PACKAGE_NAME</string>
```

### Expected Behavior

The build runs and loads the string mauron85_bgloc_content_authority

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
this is the same as the issue you created yesterday and that I turned into a discussion https://github.com/ionic-team/capacitor/discussions/3587

**Comment by andrewl94** [comment]
Just now I saw it was moved to Discussion, since there was notification, I even thought I maybe did not even sent the issue.
