### ISSUE TITLE
bug: npx cap sync does not return a non zero status on update failure

### ISSUE THREAD

**Issue by dan-overton** [ionic-team/capacitor#3592]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 2.4.1
  @capacitor/core: 2.4.1
  @capacitor/android: 2.4.1
  @capacitor/electron: 2.4.1
  @capacitor/ios: 2.4.1

Installed Dependencies:

  @capacitor/cli 2.4.1
  @capacitor/android 2.4.1
  @capacitor/core 2.4.1
  @capacitor/ios 2.4.1
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

### Platform(s)
ios, android

### Current Behavior
When running `npx cap sync <platform>`, if the update fails the command does not exit with a non zero status. 
This means that our CI system thought the sync had completed successfully when in fact it had failed.
The subsequent iOS build failed as relevant cocoapods had not been installed.

Rerunning the build worked as the error was transient.

Relevant logging:

![Screenshot 2020-09-22 at 11 59 02](https://user-images.githubusercontent.com/846955/93874319-18a13480-fccb-11ea-8e97-9c7f2a583ae8.png)

### Expected Behavior

The command should exit with a non zero status, so we can tell if the command errored in CI.

### Code Reproduction

n/a

### Other Technical Details

The exception that would show us the error is caught and not re-thrown at https://github.com/ionic-team/capacitor/blob/d7bf775dfb3857e5fc0edb2b24cbe32f56b821b0/cli/src/tasks/update.ts#L89 (I think!)

**Comment by dwieeb** [comment]
I believe the current behavior is for when the command is run as `npx cap sync` and it syncs multiple platforms, but I think it makes more sense to fail early if any error is encountered.

Thanks for the report!

**Comment by dan-overton** [comment]
No problem! Many thanks for taking a look at this so quickly.

**Comment by jcesarmobile** [comment]
this was fixed on 2.4.2
