### ISSUE TITLE
feat: ability to hook into cap commands

### ISSUE THREAD

**Issue by buschtoens** [ionic-team/capacitor#3593]
### Description

Enable users to hook into any `cap` command to run before and after hooks. This is useful, e.g. to allow users to run custom scripts when running `cap sync`.

#### `.ts` file
Allow users to add a `.ts` file in the project root that contains hooks.

#### `capacitor.config.ts`
As the `capacitor.config.json` will be generated on-the-fly in Capacitor 3, we could also export the hooks here to avoid adding another file.

#### `package.json` scripts
Check the `scripts` defined in the `package.json`. Scripts named `cap:${command}:(before|after)` are executed, e.g. `cap:copy:before`.

**Comment by EinfachHans** [comment]
As long as my PR #4536 isn't merged this would be awesome for me, otherwise i can't use AppFlow 😕

**Comment by EinfachHans** [comment]
I created a PR: #4739
