### ISSUE TITLE
bug: Android splashscreen flickers on startup

### ISSUE THREAD

**Issue by AE1NS** [ionic-team/capacitor#3601]
### Capacitor Version
```
@capacitor/cli 2.4.1
@capacitor/core 2.4.1
@capacitor/android 2.4.1
```

### Platform(s)
Android

### Current Behavior
Samsung Galaxy S7 Edge
![20200918_095420](https://user-images.githubusercontent.com/47378799/93577156-fbebc080-f99b-11ea-86ed-765dc836c3e2.gif)

Google Pixel 4
![ezgif-1-d8efc1c48460](https://user-images.githubusercontent.com/47378799/93577433-55ec8600-f99c-11ea-8137-fde54d66a4e1.gif)

### Expected Behavior
Seemless transition without the flickering effect between native start splashscreen and ionic splashscreen.

### Code Reproduction
```
ionic start ionic-flicker-reproduce blank
```
- Choose: Angular
- Choose: Include Capacitor

Update capacitor.config:
Add "backgroundColor": "red" (to see the issue more clear)
Replace "launchShowDuration": 0 with "launchShowDuration": 3000

```
ionic build
npx cap add android
npx cap open android
```

https://github.com/AE1NS/ionic-flicker-reproduce

**Comment by jcesarmobile** [comment]
was fixed on 2.4.2
