### ISSUE TITLE
feat: configurable `pod` command / try local `bundle exec pod`

### ISSUE THREAD

**Issue by buschtoens** [ionic-team/capacitor#3603]
### Description

Some projects may chose to not install `pod` globally, but locally via [`bundle`](https://bundler.io/). In this case, `pod` is normally not in the `$PATH`. However, it would be accessible via `bundle exec pod`.

Because `cap` expects `pod` to be accessible from the `$PATH`, any command using `pod` would fail with that setup.

Currently we work around this in our project by generating a binstub for pod (`bundle binstubs cocoapods`) and adding it to the `$PATH` using an [`.envrc`](https://direnv.net/) file like this:

```sh
# Add the gem binstubs directory to `PATH`.
export PATH="$PWD/bin:$PATH"
```

### Platform(s)

macOS / iOS

### Preferred Solution

Not entirely sure.

It would be nice, if the command for `pod` could be configured or alternatively the path to the bin could be configured explicitly. Both solutions could be supported simultaneously. I would not put this in the `capacitor.config.json`, but rather add a `capacitor` key to the `package.json`:

```js
{
  "capacitor": {
    "pod": "bundle exec pod"
    // or alternatively:
    "pod": "./bin/pod"
  }
}
```

**Comment by dwieeb** [comment]
Just curious, where is your `Gemfile` in your project?

**Comment by buschtoens** [comment]
We use a monorepo setup that looks like this:

```
.
├── bin
│  ├── pod
│  └── sandbox-pod
├── gems
│  └── ruby/
├── packages
│  ├── capacitor-app/
│  ├── debug-ui/
│  ├── plugin.auth/
│  ├── plugin.pdf/
│  └── scripts/
├── .envrc
├── .gitignore
├── .ruby-version
├── Brewfile
├── Gemfile
├── Gemfile.lock
├── lerna.json
├── package.json
├── README.md
└── yarn.lock
```

For our tool chain version management we have (among others) these entries in our `Brewfile`:

```sh
brew "direnv"
brew "volta"
brew "rbenv"
brew "openjdk@11"
```

And this `.envrc`:

```sh
# Add the gem binstubs directory and the JDK@11 to the `PATH`.
export PATH="$(dirname "$0")/bin:$(brew --prefix openjdk@11)/bin:$PATH"
```

**Comment by dwieeb** [comment]
@buschtoens Take a look at https://github.com/ionic-team/capacitor/pull/3811--this should be the feature you're looking for (coming in Capacitor 3). For system/environment configuration, we would prefer to use environment variables rather than a file that gets checked into source control. This feature is most similar to the environment variable we added for configuring the path of Android Studio: https://github.com/ionic-team/capacitor/pull/3755

**Comment by buschtoens** [comment]
@dwieeb this is perfect! Thank you.

FWIW for anyone following along at home or future Googlers: [`direnv`](https://github.com/direnv/direnv) is a fantastic tool to automatically set env vars when entering a directory, e.g. your repo.

**Comment by dwieeb** [comment]
Forgot to mention, the environment variable will only work for file paths, e.g: `export CAPACITOR_COCOAPODS_PATH="./bin/pod"`

(You can't do `CAPACITOR_COCOAPODS_PATH="bundle exec pod"`)

**Comment by buschtoens** [comment]
Thanks for mentioning. That'd be fine as well though. If users for some reason cannot use [binstubs](https://bundler.io/man/bundle-binstubs.1.html), they could create an executable (`chmod +x`) shell script instead:

```sh
#!/usr/bin/env sh
bundle exec pod $@
```

```sh
export CAPACITOR_COCOAPODS_PATH="./bin/custom-pod"
```
