### ISSUE TITLE
bug: Missing Push Notification Entitlement error when push is not used and USE_PUSH is true

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/capacitor#3619]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.2

  @capacitor/core: 2.4.2

  @capacitor/android: 2.4.2

  @capacitor/electron: 2.4.2

  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.1.0

  @capacitor/core 2.4.1

  @capacitor/ios 2.4.1

  @capacitor/android 2.4.1

[success] Android looking great! 👌
  Found 2 Capacitor plugins for ios:
    es6-promise-plugin (4.2.2)
    phonegap-plugin-barcodescanner (8.1.0)
[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

When submitting my app to the App Store I get this error while I don't use push notifications

> ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
> 

### Expected Behavior

No warning

### Code Reproduction

it turned out that the warning is caused by

```
  #if USE_PUSH

  func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
  }

  func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
  }

  #endif
```
in `App/AppDelegate.swift`. When this part is removed there are no warnings. It looks like somehow `USE_PUSH` becomes `true` even though push is not being used by the app.

### Other Technical Details

`npm --version` output: 6.14.5

`node --version` output: v12.13.0

`pod --version` output (iOS issues only): 1.9.3

**Comment by jcesarmobile** [comment]
It’s not an error, just a warning, you can disable the code like explained in the push docs
https://capacitorjs.com/docs/apis/push-notifications#disabling-push-notifications-plugin

**Comment by basvdijk** [comment]
> It’s not an error, just a warning, you can disable the code like explained in the push docs
> https://capacitorjs.com/docs/apis/push-notifications#disabling-push-notifications-plugin

Thanks! I would recommend to add this to the more general sections of the docs.
