### ISSUE TITLE
Filesystem.appendFile broken for web 

### ISSUE THREAD

**Issue by diachedelic** [ionic-team/capacitor#3620]
### Platform(s)

Web

### Current Behavior

Error: Current directory does already exist.

### Expected Behavior

The file to be appended without error.

### Code Reproduction

```sh
git clone git@github.com:diachedelic/capacitor-append-file-repro.git &&
  cd capacitor-append-file-repro &&
  npm install &&
  open index.html
```

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v14.4.0

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
closing since https://github.com/ionic-team/capacitor/pull/3629 was merged, will be available on next 2.x release

**Comment by diachedelic** [comment]
May I ask when the next 2.x release is planned? The last one was in September.

**Comment by dwieeb** [comment]
2.4.3 is out with this fix.

**Comment by hussainarthuna** [comment]
> May I ask when the next 2.x release is planned? The last one was in September.

V2.4.3 Released today
