### ISSUE TITLE
bug: Android 11 - Unable to resolve camera activity

### ISSUE THREAD

**Issue by andreaskas** [ionic-team/capacitor#3627]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.2

  @capacitor/core: 2.4.2

  @capacitor/android: 2.4.2

  @capacitor/electron: 2.4.2

  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.1.0

  @capacitor/core 2.4.2

  @capacitor/android 2.4.2

  @capacitor/ios 2.4.2
```

### Platform(s)

- Android

### Current Behavior
Setting on android studio _compileSdkVersion_ and _targetSdkVersion_ to _30_ (android 11) results in the exception mentioned everytime the camera tries to open. Reverting to version _29_ (android 10) camera works as expected,

### Expected Behavior
Open front/rear facing camera and take picture

### Code Reproduction
`
const image = await Plugins.Camera.getPhoto({
      quality: 60,
      allowEditing: false,
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Prompt
    })
`

### Other Technical Details

`npm --version` output: **6.14.6**

`node --version` output: **v12.18.4**

### Additional Context
`
ERROR Error: Uncaught (in promise): Error: Unable to resolve camera activity
Error: Unable to resolve camera activity
    at Object.fromNative (capacitor-runtime.js:226)
    at <anonymous>:1:18
    at T (polyfills-es2015.ecc57152156a3ef652c7.js:1)
    at polyfills-es2015.ecc57152156a3ef652c7.js:1
    at a (main-es2015.962c5164b39c7ec6b75d.js:1)
    at l.invoke (polyfills-es2015.ecc57152156a3ef652c7.js:1)
    at Object.onInvoke (main-es2015.962c5164b39c7ec6b75d.js:1)
    at l.invoke (polyfills-es2015.ecc57152156a3ef652c7.js:1)
    at i.run (polyfills-es2015.ecc57152156a3ef652c7.js:1)
    at polyfills-es2015.ecc57152156a3ef652c7.js:1
    at l.invokeTask (polyfills-es2015.ecc57152156a3ef652c7.js:1)
    at Object.onInvokeTask (main-es2015.962c5164b39c7ec6b75d.js:1)
`

**Comment by zsyphon** [comment]
@andreaskas have you been able to resolve this issue yet? I'm having a similar issue. Any suggestions on what to do?

**Comment by andreaskas** [comment]
@zsyphon no I haven't. I reverted back to SDK 29

**Comment by DomClaxton** [comment]
I'm having similar issues too. I haven't tried to fall back to sdk 29, but it's hardly ideal

**Comment by jcesarmobile** [comment]
If you target SDK 30, you have to add the intents your app queries in `AndroidManifest.xml`, in this case

```
<queries>
  <intent>
    <action android:name="android.media.action.IMAGE_CAPTURE" />
  </intent>
</queries>
```
