### ISSUE TITLE
Evaluate using @discardableResult for public Swift API

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#363]
Some of our public swift APIs probably return values that can be discarded if the caller desires. We're not using this decorator at all, so this task would require reviewing existing swift code to see where we could use it.

**Comment by jcesarmobile** [comment]
Closing as won't do.
The APIs are for us, and they return what we need.
If somebody else uses them but don't want the returned results they'll have to deal with the warnings, but it's not a concern to us.
