### ISSUE TITLE
bug: Firebase dynamic links plugin class not found after build

### ISSUE THREAD

**Issue by karen1au** [ionic-team/capacitor#3631]
## Bug Report

I'm using vue on capacitor, and got the error below when running the app in Android studio:
```
2020-09-29 16:25:55.570 6627-6734/? W/System.err: java.lang.ClassNotFoundException: by.chemerisuk.cordova.firebase.FirebaseDynamicLinksPlugin
2020-09-29 16:25:55.571 6627-6734/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "by.chemerisuk.cordova.firebase.FirebaseDynamicLinksPlugin" on path...
```
When I look for the actual plugin file, I only see the FirebaseAuthenticationPlugin in the folder, even when I uninstall that plugin, that file still exists.
![image](https://user-images.githubusercontent.com/43124859/94712372-69daa500-0317-11eb-9177-c1eb4e3e53a4.png)

In the terminal it seems Capacitor is correctly identifying the plugin:
![image](https://user-images.githubusercontent.com/43124859/94712425-78c15780-0317-11eb-9f10-98b8158e0f7a.png)

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed

```

### Platform(s)

Android

### Current Behavior

After clicking dynamic link from email, app is opened but plugin is not listening to the dynamic link received
(Plugin is not found at all in Android)

### Expected Behavior

Plugin should subscribe and handle dynamic link 

### Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: v12.16.3

### Additional Context

I've followed the installation at https://ionicframework.com/docs/native/firebase-dynamic-links

Other related dependecies:
```
    "@ionic-native/core": "^5.28.0",
    "@ionic-native/firebase-dynamic-links": "^5.28.0",
    "@ionic/cli": "^6.11.1",
    "cordova-plugin-firebase-dynamiclinks": "^4.6.0",
    "cordova-plugin-ionic": "^5.4.7",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-support-android-plugin": "^1.0.2"
```

**Comment by jcesarmobile** [comment]
are you running `npx cap sync` or `npx cap update` after installing the plugin?

**Comment by karen1au** [comment]
i did `cap sync`, and that should also run `cap update` right?
