### ISSUE TITLE
Duplicate entries in changelog

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#3651]
https://github.com/ionic-team/capacitor/blob/main/CHANGELOG.md

"3.0.0-alpha.3 (2020-09-15)" and a few more entries occur twice. Just wanted to let you know!

**Comment by jcesarmobile** [comment]
Also the changelog itself is wrong, there were no fixes on beta 5, the one that appears is from 2.4.2 
I used to also publish the chores, otherwise beta 5 should be empty cc @dwieeb

**Comment by dwieeb** [comment]
This is happening because we've been merging 2.x changes into `main` and it's confusing our changelog generator. It won't be an issue once we stop pulling in changes from 2.x. 

I fixed the most recent release changelog. Thanks!
