### ISSUE TITLE
bug: After first install/launch, capacitor doesn't seem to be running native_bridge.js... I have to uninstall and reload to get it to load.

### ISSUE THREAD

**Issue by namello-zmtp** [ionic-team/capacitor#3665]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/core 2.4.2
  @capacitor/android 2.4.2
  @capacitor/electron not installed
```

### Platform(s)

Android

### Current Behavior

Install from Android Studio (Fresh, uninstall from simulator first)
native_bridge.js executes like expected. window.Capacitor IS defined.

Quit app in simulator

Relaunch app, window.Capacitor == undefined.

Only way to fix for me was to uninstall and reload. (Force quit didn't work either)

### Expected Behavior

window.Capacitor should always be defined.

### Code Reproduction

A stock project seems to break for me. I haven't customized anything but the splash. I am using server::url property in config.
Edit: Just tried not using the server url and straight index.html, same logic...

### Other Technical Details

Latest android studio, android simulator api 28/30 has same effect.

**Comment by namello-zmtp** [comment]
Did some debugging... Looks like it may be when WebView loads from service worker cache? as in the cache doesn't have the capacitor injected code... May need to handle this case!!

**Comment by jcesarmobile** [comment]
yeah, if you load the app content from a service worker then Capacitor won't be injected. You can try this workaround
https://github.com/ionic-team/capacitor/issues/2373#issuecomment-578893789

**Comment by namello-zmtp** [comment]
@jcesarmobile So I just tried this. Unfortunately, it seems that the callback is also only called before the service worker loads (fresh install)... After relaunching, the callback doesn't execute... Any ideas?
