### ISSUE TITLE
Safe area inset is not recognized with Live Reload ONLY 

### ISSUE THREAD

**Issue by damienromito** [ionic-team/capacitor#3669]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/android 2.4.0
  @capacitor/electron not installed

### Platform(s)
IOS 14.0.1 (iPhone X)
Android 10  (Galaxy A10)

### Current Behavior
`env(safe-area-inset-top);` is not recognized (equal to 0) in the native app with livereload

-When I simply build the app and launch it with XCode or Android Studio  => padding is visible ✅

-When I launch the app as PWA => padding is visible ✅ 

-When I run `ionic capacitor run android --livereload --external` to test the app => no visible padding ❌

### Code Reproduction
```
.my-navbar {
 padding-top: constant(safe-area-inset-top);
}
```

**Comment by damienromito** [comment]
Update : 
I notice the safe area is working when I simply build with :
webpack --mode production && npx cap sync ios && npx cap open ios

BUT NOT with livereload 
webpack --mode production && npx cap sync ios && ionic capacitor run ios --livereload --external

any idea ?

**Comment by damienromito** [comment]
The solution was to not use Ionic CLI as mentionned here https://capacitorjs.com/docs/guides/live-reload#using-with-framework-clis

**Comment by mhartington** [comment]
```
.my-navbar {
 padding-top: constant(safe-area-inset-top);
}
```

Just an FYI, `constant()` has long since been deprecated in the browser. Not sure if what you have is a copy/paste error, but thought I'd point that out.
Also worth noting that the Ionic CLI it self is for projects using the framework.

**Comment by damienromito** [comment]
Thank you or you comment. I use constant() and env(). 
The problem was also because I use style-components and `@import myIonicStyle` inside `createGlobalStyle` wich is deprecated...

**Comment by Igor4505** [comment]
I'm developing a plugin that sends the device insets, at the moment works only on android, and send only top, its for a emergency.
`// Configurar a Status bar
StatusBar.setOverlaysWebView({ overlay: true });
StatusBar.setStyle({ style: StatusBarStyle.Dark });

// Injetar o top inset
InsetsPlugin.top()
    .then((resp: { value: number }) => {
        document.documentElement.style.setProperty('--top-inset', `${resp.value}px`);
    });`
