### ISSUE TITLE
file.path in readAsBase64() says the file doesn't exist

### ISSUE THREAD

**Issue by theGeekyLad** [ionic-team/capacitor#3674]
### Capacitor Version

```
@capacitor/ios not installed
@capacitor/core 2.4.0
@capacitor/cli 2.4.0
@capacitor/android 2.4.0
@capacitor/electron not installed
```

### Platform(s)

- [x] Android

### Current Behavior

I followed the official guide [here](https://ionicframework.com/docs/angular/your-first-app/5-adding-mobile#platform-specific-logic) _as is_, to implement functionalities of capturing pictures and saving them to `FileSystem`. Turns out `readAsBase64()`, encounters an error inside the following block:

```JS
const file = await Filesystem.readFile({
    path: cameraPhoto.path
});
```

The error is like so:

```
Error in readAsBase64(): Error: File does not exist.
```

### Expected Behavior

Ideally, with Capacitor's support, the `FileSystem` should be able to read the platform-specific path of the file with `file.path` against `file.webPath` as on web or PWAs. What's expected is that `file.path` **should not** error out indicating a plausibly missing file.

### Code Reproduction

`readAsBase64()` is implemented exactly as described [here](https://ionicframework.com/docs/angular/your-first-app/5-adding-mobile#platform-specific-logic).

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v14.13.0

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by gp559** [comment]
i think you have to pass the path of file to readAsBase64() function. It can be based on platform you are using it for. in example provided they have used hybrid.

**Comment by theGeekyLad** [comment]
Turns out I didn't pay attention to the imports.

It's important to note that `Ctrl+.` to auto-import classes is not always a good idea unless you check _from where_ it gets imported.

The `Camera` and `Filesystem` classes were coming from some sub-package of `@capacitor` and not `Plugins` which clearly was the issue. The Ionic example source from GitHub shows the correct imports like so:

```JS
import { CameraPhoto, CameraResultType, CameraSource, Capacitor, FilesystemDirectory, Plugins } from '@capacitor/core';

const { Camera, Filesystem } = Plugins
```

Let's safely close this issue. Thanks!
