### ISSUE TITLE
feat: camera plugin return asset.localIdentifier

### ISSUE THREAD

**Issue by geraldapeoples** [ionic-team/capacitor#3691]
### Description

When taking or attaching a photo, we don't get the identifier back which makes it impossible to move images in and out of photo albums.

### Platform(s)

iOS

### Preferred Solution

Return the asset.localIdentifier along with existing items in the call return

**Comment by jcesarmobile** [comment]
That's out of the scope of Camera plugin

There is a media plugin that has some functions for handling albums, you can request it there
https://github.com/capacitor-community/media
