### ISSUE TITLE
bug: Keyboard.setAccessoryBarVisible() not implemented

### ISSUE THREAD

**Issue by mifo111** [ionic-team/capacitor#3696]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2        
  @capacitor/electron: 2.4.2       
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/ios 2.4.2
  @capacitor/cli 2.4.2
  @capacitor/android 2.4.2
  @capacitor/core 2.4.2
  @capacitor/electron not installed

### Platform(s)

- [X]  Android
- [ ]  iOS
- [ ]  Electron
- [ ]  Web

### Current Behavior

Calling Keyboard.setAccessoryBarVisible({ isVisible: true }); on Android device does not work:

Capacitor: Sending plugin error: {"save":false,"callbackId":"12922319","pluginId":"Keyboard","methodName":"setAccessoryBarVisible","success":false,"error":{"message":"not implemented"}}

### Expected Behavior

According to the documentation this should also be available for Android.

### Code Reproduction

Call Keyboard.setAccessoryBarVisible({ isVisible: true }); on Android device.

### Other Technical Details

`npm --version` output:
6.14.4

`node --version` output:
v12.16.2

**Comment by jcesarmobile** [comment]
The accesoryBar is iPhone only.
The docs don’t say it’s supported, only says the plugin is available, but not all methods.
For capacitor 3 we are moving plugins out and it has been properly documented 
https://github.com/ionic-team/capacitor-plugins/blob/main/keyboard/src/definitions.ts#L103

**Comment by mifo111** [comment]
Ok, thank you!

 

Regarding issue #3013 is it possible to re-open it, because the problem still exists and reproducing it with the repo mentioned in issue is also possible.

https://github.com/ionic-team/capacitor/issues/3013

 

Best regards,

Michael

 

Von: jcesarmobile <notifications@github.com> 
Gesendet: Montag, 19. Oktober 2020 10:22
An: ionic-team/capacitor <capacitor@noreply.github.com>
Cc: mifo111 <michaelwilk@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [ionic-team/capacitor] bug: Keyboard.setAccessoryBarVisible() not implemented (#3696)

 

The accesoryBar is iPhone only.
The docs don’t say it’s supported, only says the plugin is available, but not all methods.
For capacitor 3 we are moving plugins out and it has been properly documented
https://github.com/ionic-team/capacitor-plugins/blob/main/keyboard/src/definitions.ts#L103
