### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by tanjentman** [ionic-team/capacitor#3721]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/core 2.4.2
  @capacitor/cli 2.4.2
  @capacitor/android 2.4.2
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
Trying to use the Filesystem writeFile(...) command with the "DOCUMENTS" directory and it returns E/Capacitor/Console: File: capacitor-runtime.js - Line 231 - Msg: Uncaught (in promise) Error: Directory does not exist.  It works fine on the "DATA" directory.

### Expected Behavior
Should work

### Code Reproduction
var SETTINGS = {
    "path" : "test.txt"
    "data" : "test"
    "directory" : "DOCUMENTS",
    "encoding" : "utf8",
    "recursive" : false //neither true or false worked
    }
Capacitor.Plugins.Filesystem.writeFile(SETTINGS).then(function(result){})
    

### Other Technical Details
`npm --version` output: 6.13.4

`node --version` output: v12.14.1

`pod --version` output (iOS issues only): N/A

**Comment by jcesarmobile** [comment]
what's the Android version of the device where it fails?

**Comment by tanjentman** [comment]
Android version 8.1.0

Steve Bjorkman

**Comment by jcesarmobile** [comment]
I can't reproduce, can you provide a sample app?

**Comment by tanjentman** [comment]
Don't worry about it.  I'll just use the DATA directory.

Steve Bjorkman
CEO & Founder
O: (248) 459-5180
C: (480) 236-1461
www.Realtyzam.com

Signature
