### ISSUE TITLE
bug: Capacitor has so many console messages

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/capacitor#3723]
Hi,

Why Capacitor has so many console messages? It directly affects the performance of the native build. i.e. poor performance. So it is very bad and against the clean code pattern and practices too. I hope you'll remove all of those in the future version.

![c](https://user-images.githubusercontent.com/5206526/97080027-10178300-1616-11eb-95d0-c5a59529bfee.png)

Ionic:

   Ionic CLI                     : 6.11.11 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.1001.2
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.1.2
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.1

Utility:

   cordova-res : 0.14.0
   native-run  : 1.2.1

System:

   NodeJS : v12.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.1
   OS     : Windows 10

**Comment by EKashpersky** [comment]
There's `"hideLogs"` boolean key for capacitor.config.json

https://capacitorjs.com/docs/config#configuration-file

**Comment by KevinKelchen** [comment]
Do we know if `hideLogs` is automatically disabled in release builds or is it just used in debug builds?

Looking at the source code I did not find evidence of it being disabled in release builds.

**Comment by Sampath-Lokuge** [comment]
Yes, that is not working.
