### ISSUE TITLE
bug: [iOS] CAPNotifications.ContinueActivity does not fire on iOS 13/14

### ISSUE THREAD

**Issue by namello-zmtp** [ionic-team/capacitor#3724]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/android 2.4.2
  @capacitor/electron not installed

  Found 2 Capacitor plugins for ios:
    @msepena/capacitor-plugin-sirishortcuts (0.0.4)
    phonegap-plugin-barcodescanner (8.1.1-dev)
[success] iOS looking great! 👌
```

### Current Behavior

Registering an event to monitor for this notification never fires:

```swift
        NotificationCenter.default.addObserver(self, selector: #selector(self.onOpenAppByUserActivity(notification:)),
                                               name: Notification.Name(CAPNotifications.ContinueActivity.name()), object: nil)
```

onOpenAppByUserActivity never called, log:
```
[Application] -[App.AppDelegate application:continueUserActivity:restorationHandler:] <NSUserActivity: 0x600001391e40> has an interaction attached but it is not handled
```

### Code Reproduction

https://github.com/msepena/capacitor-plugin-sirishortcuts Plugin, I have forked to see if I could get it working but have not been able too, possible Capacitor issue?

### Other Technical Details

`npm --version` output: N/A

`node --version` output: N/A

`pod --version` output (iOS issues only): 1.8.4

**Comment by namello-zmtp** [comment]
Ok, traced it myself and added support CAPBridge.swift:

```swift
  public static func handleContinueActivity(_ userActivity: NSUserActivity, _ restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    if userActivity.activityType != NSUserActivityTypeBrowsingWeb && userActivity.webpageURL != nil {
        let url = userActivity.webpageURL
        CAPBridge.lastUrl = url
        NotificationCenter.default.post(name: Notification.Name(CAPNotifications.UniversalLinkOpen.name()), object: [
          "url": url
        ])
        return true
    } else if userActivity.activityType == Bundle.main.bundleIdentifier {
        // This is a siri shortcut / resume pass
        NotificationCenter.default.post(name: Notification.Name(CAPNotifications.ContinueActivity.name()), object: userActivity.userInfo)
        return true
    }
    
    return false
  }
```

Modified to actually forward the notification. When passed from shortcuts, the activity type == bundle id. Plugin now works as expected.

**Comment by codal-sbelim** [comment]
@namello-zmtp, I am also facing this issue. Could you please share a fix for this? Where can I find this CAPBridge.swift file? Did you made above changes in `./node_modules/@capacitor/ios/Capacitor/Capacitor/CAPBridge.swift`?

**Comment by jcesarmobile** [comment]
Capacitor only handles Universal links, but we let users handle the `application(_:continue:restorationHandler:)` method the way they want in the `AppDelegate.swift`. 

https://github.com/ionic-team/capacitor/blob/main/ios-pods-template/App/App/AppDelegate.swift#L42-L47

It would be recommended to keep the existing Capacitor call first and if it returns false then handle it in a different way, unless you also want to change the way the universal links are handled
