### ISSUE TITLE
Keyboard not showing

### ISSUE THREAD

**Issue by TrayserCassa** [ionic-team/capacitor#373]
I was testing the example App and tested the Keyboard Plugin. The Keyboard was not opening when I press the show Button. So I looked up into Keyboard.java and debugged it. When I set a break Point and wait a few seconds it works, if I unset the break point, then it doesn't work.   

I know that the Native Keyboard Util class in our company has more Lines. I will test and create a pull request if I find a good solution, as you wish.

**Modell**
Nexus 5X

**Android-Version**
8.1.0

**Comment by TrayserCassa** [comment]
If I run a postDelayed Handler it works. My workmate sad this is a Life cycle Problem in Android. The View must be rendered or the Keyboard will not open. Why this is only happens on Nexus 5X ... I don't know.

**Comment by mlynch** [comment]
@TrayserCassa thanks for debugging. Where should the `postDelayed` handler go?

**Comment by TrayserCassa** [comment]
@mlynch  

In the _Keyboard.java_ file in the Plugin method _show_

`  @PluginMethod()
  public void show(final PluginCall call) {
    execute(new Runnable() {
      @Override
      public void run() {
        new Handler().postDelayed(new Runnable() {
          @Override
          public void run() {
            ((InputMethodManager) getActivity().getSystemService(Context.INPUT_METHOD_SERVICE)).toggleSoftInput(0, InputMethodManager.HIDE_IMPLICIT_ONLY);
            call.success(); // Thread-safe.
          }
        }, 350);
      }
    });
  }`

I read about 350 ms is the ideal way, because if the screen ist locked, it will take more time to render the View.

**Comment by mlynch** [comment]
Thanks for the snippet! Fixed in master
