### ISSUE TITLE
PDF Opener - Question

### ISSUE THREAD

**Issue by TrayserCassa** [ionic-team/capacitor#374]
For our company it is really important, that we can Display PDF's. I didn't found a class which can handle that. Am I missed something or is it not implemented yet?

**Comment by jcesarmobile** [comment]
It's not implemented

**Comment by AwsmOli** [comment]
just a longshot - but could you not just open the pdf file like any other url? 
This might display a pdf - but i don't think you would have much control over it

**Comment by jcesarmobile** [comment]
Well, that will work on iOS, but Android doesn't have a PDF renderer. Also, just loading the url "destroys" the app with no way of going back.
 
In the Browser plugin we use custom tabs for Android, not sure it that will be able to open PDF

**Comment by TrayserCassa** [comment]
With the Plugin cordova-plugin-file-opener2 you can open a pdf with the default pdf-viewer. But if no pdf-Viewer was installed or the default was uninstalled the code crashed. 

Thanks for the fast answers, I will keep my eyes on this project :+1:

**Comment by jcesarmobile** [comment]
So you just want to launch another app to open the file?
I though you wanted an actual PDF renderer in the app.

**Comment by TrayserCassa** [comment]
@jcesarmobile 
Yes sorry for my way of writing.. 
I didn't found a solution for that and maybe I missed something.  

@mlynch 
I think you are totally fine with opening an other app to Display Documents or Pictures or PDF's in Android.
For IO's the normal way is a Document Controller or Webview component for PDF's.

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/374. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
