### ISSUE TITLE
By Default FRONT Camera is getting activated , but we want REAR Camera 

### ISSUE THREAD

**Issue by jmriyaz84** [ionic-team/capacitor#3740]
WE want REAR Camera should be the default one , but FRONT camera is getting activates by default .
Even though we set direction as REAR , only FRONT camera is getting opened when we click the icon.
Code is given below.
  const image1 = await Camera.getPhoto({
          quality: 90,
          allowEditing: true,
          resultType: CameraResultType.Uri,
          direction: CameraDirection.REAR
        });
        this.imageSrc1 = image1.webPath;
Please help.

**Comment by jcesarmobile** [comment]
please, when reporting issue, don't delete the template, and provide all the required information

**Comment by jmriyaz84** [comment]
Ok , Please find all required information below.
I am developing the application using  Quasar which is build on top of Vue Js , in that one requirement is user has to capture the field image for that I used your capacitor library . In that by default Front camera is getting opened in chrome.

Please let me know if you want any other infomation.

I have added the code below.
**Template**
 ``` Code
<template>
      <div>
        <q-btn align="right" flat 
           round color="primary" icon="camera_alt" dense 
           @click="captureImage">            
        </q-btn>
     </div>
    <div class="row">
          <div class="col-12 col-md" style="max-width:200px">
            <q-img :src="imageSrc1" /> 
          </div>
        </div>
    <script>
       import { required } from "vuelidate/lib/validators";
       import { Plugins, CameraResultType, CameraDirection } from "@capacitor/core";
      const { Camera } = Plugins;
       import { Screen } from "quasar";
     export default {
        data() {
          return {
               imageSrc1: null,
              },
 methods: {
    async captureImage() {
       const image1 = await Camera.getPhoto({
          quality: 90,
          allowEditing: true,
          resultType: CameraResultType.Uri,
          direction: CameraDirection.Rear
        });
        this.imageSrc1 = image1.webPath;
 }
}
</template>
```
**Package.json**
```
  "dependencies": {
    "@capacitor/core": "^2.4.0",
    "@ionic/pwa-elements": "^3.0.1",
    "@quasar/cli": "^1.1.2",
    "@quasar/extras": "^1.9.9",
    "axios": "^0.19.2",
    "core-js": "^3.6.5",
    "plotly.js-dist": "^1.55.1",
    "quasar": "^1.14.1",
    "v-viewer": "^1.5.1",
    "vuelidate": "^0.7.5"
  },
  "devDependencies": {
    "@quasar/app": "^2.1.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.9.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-vue": "^6.1.2"
  },
```

**Comment by jcesarmobile** [comment]
Sorry, that’s not all the required information.
Please, create a new issue and don’t delete the template.

**Comment by jmriyaz84** [comment]
Can you please explain what more information required ? Also what you meant by template ?

**Comment by jcesarmobile** [comment]
When you hit the new issue button and choose bug, there are a prefilled template that ask for the required information, you have to provide all the information that is asked on that template

**Comment by jmriyaz84** [comment]
ok Thanks
