### ISSUE TITLE
Move native-bridge.js into core

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3742]
Today, the Capacitor CLI copies `native-bridge.js` (and `cordova.js`) from `node_modules/@capacitor/core` into place as assets in the iOS and Android projects.

For Embedded Capacitor, the Capacitor CLI won't be used, but we still need this file to be available during runtime. 

We plan to integrate this file as part of `@capacitor/core` TS library which is now included by plugins and thus will be bundled into apps in the appropriate order.

**Comment by jcesarmobile** [comment]
> the Capacitor CLI won't be used

If not the CLI, I think we should still have some tooling that configures the cordova plugins project, helps with setting the capacitor plugins, etc.
If not, what’s the plan? Make users copy files and configure everything manually?

Also, on iOS, the native-bridge.js gets injected into the webview so it’s available before the app content loads, making it part of core could slow down the startup of iOS apps.

**Comment by dwieeb** [comment]
> helps with setting the capacitor plugins

I'm not sure what part you're referring to, but if it's configuring the native projects, we're planning on distributing the Capacitor core and plugins as pods/packages. This should make it easier for the native teams to work with. 

> If not, what’s the plan? 

As for Cordova, we were going to address it sometime after the 3.0.0 release.

> making it part of core could slow down the startup of iOS apps

I have yet to test any of this, but if this is true, we can fall back to our original plan, which was to make `native-bridge.js` a resource/asset of `@capacitor/ios`/`@capacitor/android`.

**Comment by nphyatt** [comment]
> As for Cordova, we were going to address it sometime after the 3.0.0 release.

What does this mean exactly? That as of 3.0.0 cordova plugins won't "work out of the box" without manual intervention? Or something else?

> I have yet to test any of this, but if this is true, we can fall back to our original plan, which was to make native-bridge.js a resource/asset of `@capacitor/ios`/`@capacitor/android`

Out of curiosity why did the plans shift from this to it being part of the `@capacitor/core`? 

Are there pros & cons for either approach from a technical perspective?

Are there pros & cons for either approach from a app/plugin developer perspective?

**Comment by jcesarmobile** [comment]
This is about the embedded use case, in regular Capacitor apps Cordova plugins will work, in embedded use case it would require some tooling to create and configure the plugins module
