### ISSUE TITLE
bug: By Default Camera FRONT View is getting enabled  instead of REAR 

### ISSUE THREAD

**Issue by jmriyaz84** [ionic-team/capacitor#3745]
### Capacitor Version

```
dependencies
@capacitor/core: 2.4.0,
@ionic/pwa-elements: 3.0.1
```

### Platform(s)

Web Browser (Chrome)

### Current Behavior

Camera's Front view(direction) is getting enabled

### Expected Behavior

As per below document Camera's Rear View should be enabled by default. 
[Cameradirection](https://capacitorjs.com/docs/apis/camera#cameradirection)

### Code Reproduction

```
<template>
     <div>
       <q-btn align="right" flat 
          round color="primary" icon="camera_alt" dense 
          @click="captureImage">            
       </q-btn>
    </div>
   <div class="row">
         <div class="col-12 col-md" style="max-width:200px">
           <q-img :src="imageSrc1" /> 
         </div>
       </div>
   <script>
      import { required } from "vuelidate/lib/validators";
      import { Plugins, CameraResultType, CameraDirection } from "@capacitor/core";
     const { Camera } = Plugins;
      import { Screen } from "quasar";
    export default {
       data() {
         return {
              imageSrc1: null,
             },
methods: {
   async captureImage() {
      const image1 = await Camera.getPhoto({
         quality: 90,
         allowEditing: true,
         resultType: CameraResultType.Uri,
         direction: CameraDirection.Rear
       });
       this.imageSrc1 = image1.webPath;
}
}
</template>
```
### Other Technical Details

`npm --version` output:6.14.5

`node --version` output:12.18.2

`pod --version` output (iOS issues only):

### Additional Context

I am using Capacitor Camera in my web page .

**Comment by jcesarmobile** [comment]
It's a known issue, web version of Camera plugin doesn't support most of the options yet, it's reported on https://github.com/ionic-team/capacitor/issues/2709
