### ISSUE TITLE
feat: add support to allow `MainActivity` as a Kotlin file (instead of just Java)

### ISSUE THREAD

**Issue by ahsanz024** [ionic-team/capacitor#3749]
### Description

Currently, if you convert your Capacitor app's `MainActivity.java` to `MainActivity.kt` doctor (`cap doctor android`) fails because it only supports `MainActivity` with `.java` extension.

https://github.com/ionic-team/capacitor/blob/main/cli/src/android/doctor.ts#L208

### Preferred Solution

Allow both extensions [.java, .kt]

**Comment by TadeoArmenta** [comment]
any known workaround for this?
