### ISSUE TITLE
bug: vendor.camera.aux.packagelist Android Camera

### ISSUE THREAD

**Issue by tpharaoh** [ionic-team/capacitor#3750]
## Bug Report
```
E/chromium: [ERROR:web_contents_delegate.cc(224)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
    [ERROR:web_contents_delegate.cc(224)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
W/cr_media: Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
I/CameraManagerGlobal: Connecting to camera service
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/ThreadPoolSingl: type=1400 audit(0.0:17196): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=21599 scontext=u:r:untrusted_app:s0:c27,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
```

I have an app, which originally was built with Cordova, vuejs. Ported to Capacitor.

Everything was working. A few days ago my android device (Nokia 7 sirroco) got a google security patch and since then accessing camera gets the above errors.

I tested in older samsung devices, it still works. (Android 8&9 respectively). So, it seems related to security patch. I'll try to test some more devices and report back.

### Capacitor Version
npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/android 2.4.2
  @capacitor/core 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron 2.4.2

[success] Android looking great! 👌
[success] electron looking great! 👌
[warn] The electron platform is deprecated!

Please use the Capacitor Community Electron Platform: https://github.com/capacitor-community/electron

  Found 1 Capacitor plugin for ios:
    phonegap-plugin-barcodescanner (8.1.0)
[success] iOS looking great! 👌

### Platform(s)
Android

### Current Behavior
camera usually black screen or sometimes delays then crashes

### Expected Behavior
Well, my main goal is the Phonegap barcode scanner, but this is irrelevant in replicating bug, even copy paste from your website on getPhoto failed (with changes needed for plain VueJS

`npm --version` output:
6.14.4

`node --version` output:
v12.18.0

**Comment by tpharaoh** [comment]
https://github.com/ionic-team/capacitor/commit/f502a9964e28012980d636014043e86e918031d7

Is this related to similar issue? So is it possible it’s fixed in 3 alpha?

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by tpharaoh** [comment]
My point is, it seems its a global issue on camera since this patch.

1) my cordova app also crashes
2) my ionic app crashes
3) even cloned repos from your site, like this https://github.com/ionic-team/ionic-conference-app.git

All 3, my cordova, my ionic and you test apps all worked. Google had a security patch which was published to my Nokia device a few days ago. Since that patch, camera stopped working.

So its not related to my sample code. Even your sample app, and other tutorials I tried fail. It all started after the security patch.

**Comment by tpharaoh** [comment]
I will close this issue for now, I reset camera settings after the upgrade and it started to work...

**Comment by shantanunautiyal** [comment]
Ahem me faced same issue in realme 5 , just define aux package list in build.prop it will resolve

**Comment by rajubera** [comment]
Hello @justanubhere 
Can you please share which aux package you defined in which file? I am also facing this same issue in multiple devices on a ionic app.
