### ISSUE TITLE
Docker Ionic/Vue iOS build fails due to missing Capacitor module.

### ISSUE THREAD

**Issue by michaelalhilly** [ionic-team/capacitor#3752]
# Bug Report

**Ionic version:**
@ionic/vue: 5.4.1

**Current behavior:**

Can not build ios app based on the Ionic Vue guide [here](https://ionicframework.com/docs/vue/your-first-app/6-deploying-mobile).

Is this issue caused by using Ionic inside Docker?

I'm receiving errors in Xcode stating there are missing pod files. When I attempt to generate the pod files using pod update and install I'm receiving the following error:

```
No podspec found for `Capacitor` in `../../node_modules/@capacitor/ios`
```

The node module and podspec both exist.

In Xcode I'm seeing the following error:

```
Swift Compiler error: No such module 'Capacitor'
```

**Expected behavior:**

The project should build without needing to manually generate pod files according to the Ionic guide.

**Steps to reproduce:**

Download repo below
Install node modules
Build ios project
Build Xcode project

**Related code:**

Here's the link to the repo:
https://github.com/michaelalhilly/photoly

**Other information:**

Everything is building with no errors and running in the browser.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.1

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.2

System:

   NodeJS : v12.18.3 (/usr/local/bin/node)
   npm    : 6.14.6
   OS     : Linux 4.19 (this is the Docker OS)
   macOS: 10.15.7
```

**Comment by jcesarmobile** [comment]
when you clone a capacitor app, a few folders are not included because they are auto generated, so they are ignored by default

so the steps to be able to build a capacitor apps are

```
git clone app
npm install
ionic build
ionic cap sync ios
ionic cap open ios
```

**Comment by michaelalhilly** [comment]
@jcesarmobile Yes. Unfortunately ionic cap open ios can not be run from within Docker. It seems the auto generated files happen within this open process.

Is that correct?

**Comment by jcesarmobile** [comment]
no, they are generated on sync command

**Comment by michaelalhilly** [comment]
Ah I’ll give it a shot. Thx!
