### ISSUE TITLE
bug: brotli header not sent on android?

### ISSUE THREAD

**Issue by spassvogel** [ionic-team/capacitor#3753]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2..2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/electron not installed
  @capacitor/cli 2.2.0
  @capacitor/android 2.2.0
  @capacitor/core 2.2.0
  @capacitor/ios 2.4.1

[success] Android looking great! 👌
  Found 3 Capacitor plugins for ios:
    cordova-plugin-inappbrowser (4.0.0)
    cordova-plugin-screen-orientation (3.0.2)
    es6-promise-plugin (4.2.2)

### Platform(s)
Tested on Android 9 

### Current Behavior
I'm serving content on my CDN compiled with brotli compression. On regular browsers (mobile/laptop) I can fetch and display this content. On my iOS capacitor build I can also display this content. On Adroid however I'm not seeing the content and I'm noticing these errors in the console:

```
FlashCards.loader.js:1 GET https://.../Build/FlashCards.framework.js.unityweb 
net::ERR_CONTENT_DECODING_FAILED
FlashCards.loader.js:1 GET https://.../Build/FlashCards.wasm.unityweb 
net::ERR_CONTENT_DECODING_FAILED
```

This could very well be because the webview does not send the correct `accept-encoding` header.  This is the header that gets sent:

`accept-encoding: gzip, deflate`

<img width="940" alt="image" src="https://user-images.githubusercontent.com/985892/97885299-7774b780-1d27-11eb-95c8-efd67c0606b9.png">

The request is being sent from a https:// domain. Apparently botli doesn't work in http but this is not the case here.

### Expected Behavior
I expect brotli decompression to work in Android WebView.

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by spassvogel** [comment]
Okay here it is: https://github.com/spassvogel/brotli

When I run this on my Android S8 I see the following headers: "gzip, deflate".
When I visit the [page in the iframe](https://www.cylog.org/headers/) in the chrome browser on that same device, I get "gzip, deflate, br"

**Comment by jcesarmobile** [comment]
Thanks for the app, was very helpful.

Turns out brotli is not enabled on the Android WebView.
The feature was added back in May of 2019
https://bugs.chromium.org/p/chromium/issues/detail?id=961735&q=brotli&can=2
but disabled by default
https://chromium.googlesource.com/chromium/src/+/refs/tags/77.0.3855.0/android_webview/browser/aw_feature_list.cc#47

There is a feature request for enabling it by default
https://bugs.chromium.org/p/chromium/issues/detail?id=1074697&q=brotli&can=2

**Comment by spassvogel** [comment]
That is a bummer. Is there no way for capacitor to enable this feature on WebView?

**Comment by jcesarmobile** [comment]
Nope, not possible.

You, as user, can enable the experimental flag in the WebView settings, but not something other app users will do.

Docs about how to enable experimental flags on webview
https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/developer-ui.md
