### ISSUE TITLE
XHR request from capacitor doesn't sent Cookies

### ISSUE THREAD

**Issue by zvitek** [ionic-team/capacitor#3757]
## Bug Report
My application communicate with external API endpoint on server. At the first request the server create a cookie `refreshToken` and returns `authToken`. Every request contains bearer `authToken` and it's work good.
Every minute is necessary to refresh `refreshToken`.
Application make a request for refresh. (On the server compare sent `authToken` with the cookie to regenerate). In this endpoint it's a problem because the request doesn't contain cookies. 

### Capacitor Version
@capacitor/core 2.4.1
@capacitor/cli 2.4.1
@capacitor/android 2.4.1
@capacitor/ios 2.4.1
@capacitor/electron not installed

### Current Behavior
The requests doesn't contains cookies

### Devices

- [x] iOS
- [x] Android

### Expected Behavior
Every request on same domain will contains existing cookies.

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v12.19.0

**Comment by loburets** [comment]
Have the same issue and used solution from this conversation
https://github.com/ionic-team/capacitor/issues/1373#issuecomment-722215355

But it did not really help as we need to use services like stripe which don't allow to make requests from HTTP but they worked well for localhost

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
