### ISSUE TITLE
setOverlaysWebView not available on iOS

### ISSUE THREAD

**Issue by githubowl** [ionic-team/capacitor#3765]
Hello

I am trying to set the OverlaysWebView to false on an iOS device and have the following issues:

setOverlaysWebView is not available in the capacitor plugin on iOS.

The cordova statusbar plugin is list as having compatibaility issues with capacitor.

Can you tell me how to do this with capacitor please?

Thank you
Best regards
Paul

**Comment by jcesarmobile** [comment]
You have to do it with css, taking safe areas into account, read this article to know more 
https://webkit.org/blog/7929/designing-websites-for-iphone-x/
