### ISSUE TITLE
bug: Capacitor.convertFileSrc unable to serve local media files on iOS (unsafe isssue)

### ISSUE THREAD

**Issue by brospars** [ionic-team/capacitor#3767]
### Capacitor Version

```
Capacitor:
   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2
```

### Platform(s)
ios

### Current Behavior

I am using `this.rootFolder = Capacitor.convertFileSrc(this.file.dataDirectory)` to serve local files (data, images and videos) by using `<img [src]="rootFolder + filename" />`. It works on Android but I am unable to make it work on iOS.

Data are loaded but media files aren't due to `unsafe resource`

```
unsafe:capacitor://localhost/_capacitor_file_/Users/Library/Developer/CoreSimulator/Devices/1C70960A-1C78-4E70-AAC1-16C37138B/data/Containers/Data/Application/2930A9F0-C7E6-4C61-A0C7-A07717/Documents/images/MOTION_PPST1.png
[Error] Failed to load resource: unsupported URL (MOTION_PPST1.png, line 0)
unsafe:capacitor://localhost/_capacitor_file_/Users/Library/Developer/CoreSimulator/Devices/1C70960A-1C78-4E70-AAC1-16C37138B/data/Containers/Data/Application/2930A9F0-C7E6-4C61-A0C7-A07717/Documents/images/MOTION_PPST2.png
[Error] Failed to load resource: unsupported URL (MOTION_PPST2.png, line 0)
unsafe:capacitor://localhost/_capacitor_file_/Users/Library/Developer/CoreSimulator/Devices/1C70960A-1C78-4E70-AAC1-16C37138B/data/Containers/Data/Application/2930A9F0-C7E6-4C61-A0C7-A07717/Documents/images/MOTION_PPST2.mp4
[Error] Failed to load resource: unsupported URL (MOTION_PPST2.mp4, line 0)
```

### Expected Behavior

Locally stored files should be accessible by an http request in dev and prod environment.

### Code Reproduction

1. Clone and install https://github.com/brospars/capacitor-bugreport-convertfilesrc
2. Run `ionic cap run ios`

### Other Technical Details

`npm --version` output: `6.9.0`

`node --version` output: `v10.16.3`

`pod --version` output: `1.9.2`

### Additional Context

Maybe related to #2042 and #2439

**Comment by jcesarmobile** [comment]
This is not a Capacitor issue, it's Angular not considering capacitor scheme safe and appending the unsafe prefix, you have to tell angular it's secure, in example, by using dom sanitizer.

**Comment by brospars** [comment]
Thanks a lot for the quick response.

A note could be added on : https://capacitorjs.com/docs/basics/utilities#convertfilesrc
