### ISSUE TITLE
[Android] "Unable to edit" Promise in Camera when allowediting is true. bug: 

### ISSUE THREAD

**Issue by dhwalin** [ionic-team/capacitor#3782]
const options = {
      quality: 90,
      allowEditing: false,
      width:300,
      height:300,
      resultType: CameraResultType.DataUrl
    };

This settings give output.

    const options = {
      quality: 90,
      allowEditing: true,
      width:300,
      height:300,
      resultType: CameraResultType.DataUrl,
      correctOrientation:true
    };

These options return promise "Unable to Edit" promise, specially in Old devices of Android.

In latest mobiles, Photo editor opens but It is never restrict user to stay in 300x300 image.

**Comment by rajashekarreddy2222** [comment]
yes Having same issue and also not able to get data after choosing from file system

**Comment by jcesarmobile** [comment]
That happens when it tries to edit but it's not able. What would you expect to happen if it's not able to edit the photo?

**Comment by dhwalin** [comment]
It should open android photo editor. New devices are opening photo editor but old devices are giving error that cannot edit photo.

In cordova camera plugin opens editor in old devices, just wanted to know can capacitor does same thing?

**Comment by jcesarmobile** [comment]
"Unable to edit" error is returned when the editor couldn't be opened for some reason. That's why I ask what would you expect to happen when the app is not able to open the editor.

To identify what might be preventing from opening, can you provide a sample app and more information about the Android OS and device model of the devices where you get the error?

**Comment by dhwalin** [comment]
Let me tell what is happening:

I made two projects, one in cordova, one in capacitor.

In both projects, I have used Camera Plugin.

Then I ran both projects in same mobile. Both Camera Options have allowEditing: true. Now in Cordova project Photo Editor is opening. But in Capacitor project "Unable to edit" error is coming.

So I expect capacitor also should open photo editor like cordova project.

**Comment by jmsavani** [comment]
I am facing same issue.
When try to click image and select image.

I want to allow user to edit image after selecting and capture image.

Android OS : android 11
Device: Samsung Galaxy M31, Asus

Capacitor information

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/core 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/android 2.4.2
  @capacitor/electron not installed

```

Ionic Info

```
Ionic:

   Ionic CLI                     : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.2

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v12.18.4 (/usr/local/bin/node)
   npm    : 6.14.6
   OS     : macOS Big Sur
   Xcode  : Xcode 12.3 Build version 12C33
```

Sample Code:


```
	async takePicture() {
		const image = await Camera.getPhoto({
			quality: 90,
			allowEditing: true,
			resultType: CameraResultType.DataUrl,
			source: CameraSource.Camera,
		})
		return image
	}

	async choosePictureFromGallery() {
		const image = await Camera.getPhoto({
			quality: 90,
			allowEditing: true,
			resultType: CameraResultType.DataUrl,
			source: CameraSource.Photos,
		})
		return image
	}
	
```

Screen Shot:

![Error.png](https://user-images.githubusercontent.com/52349823/113259561-e3654700-92ea-11eb-90b6-813879f18fd0.png)

**Comment by jcesarmobile** [comment]
closing in favor of https://github.com/ionic-team/capacitor-plugins/issues/307
