### ISSUE TITLE
bug: Geolocation.getCurrentPosition throws error on new permission dialog on iOS 14.2

### ISSUE THREAD

**Issue by abarax** [ionic-team/capacitor#3789]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron not installed

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

### Platform(s)

iOS 14.2

### Current Behavior

Calling the getCurrentPosition API results in failure during the permission check on iOS 14.2 only.  Seemingly the call times out after 2 seconds of waiting on the permission dialog. Console Output from XCode via emulator:

To Native ->  Geolocation getCurrentPosition 80463459
APP INACTIVE
ERROR MESSAGE:  {"message":"The operation couldn’t be completed. (kCLErrorDomain error 1.)","errorMessage":"The operation couldn’t be completed. (kCLErrorDomain error 1.)"}
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: The operation couldn’t be completed. (kCLErrorDomain error 1.)

<img width="1116" alt="CleanShot 2020-11-11 at 17 47 37@2x" src="https://user-images.githubusercontent.com/124785/98783892-01b6cd00-2446-11eb-8d50-96afcfed6ad8.png">

### Expected Behavior

getCurrentPosition should wait until an option has been selected on the permission dialog.

### Code Reproduction

Basic reproduction. Simply hit the 'test' button on tab 1 and you will see the above error in the xcode console.
https://github.com/abarax/capacitor-bug

Only Code added is here:

https://github.com/abarax/capacitor-bug/blob/main/src/app/explore-container/explore-container.component.ts

https://github.com/abarax/capacitor-bug/blob/main/src/app/explore-container/explore-container.component.html

To run:

> npm run build
> npx cap sync
> npx cap open ios

Run via XCode using iOS 14.2 simulator

**Comment by zsyphon** [comment]
@abarax Have you made any progress on this issue? I am getting the same error.

**Comment by abarax** [comment]
@zsyphon Right now our workaround is to sit in a loop checking permissions using the query permission API (https://capacitorjs.com/docs/apis/permissions) Once the permission is recognised, only then do we use getCurrentPosition. 

I would love to dig in and figure out the cause here, I suspect something changed in the iOS operating system update.  I actually think this was not happening on 14.2 beta as well, which is interesting.

**Comment by abarax** [comment]
Looks like jcesarmobile has a fix though!

**Comment by jcesarmobile** [comment]
It was happening on iOS 13 too, just took a bit longer to timeout. My PR should fix the problem.

**Comment by zsyphon** [comment]
@jcesarmobile Thank you!!

**Comment by zsyphon** [comment]
> @zsyphon Right now our workaround is to sit in a loop checking permissions using the query permission API (https://capacitorjs.com/docs/apis/permissions) Once the permission is recognised, only then do we use getCurrentPosition.
> 
> I would love to dig in and figure out the cause here, I suspect something changed in the iOS operating system update. I actually think this was not happening on 14.2 beta as well, which is interesting.

Thank you!!

**Comment by RopFoo** [comment]
Having the same issue..

> @zsyphon Right now our workaround is to sit in a loop checking permissions using the query permission API (https://capacitorjs.com/docs/apis/permissions) Once the permission is recognised, only then do we use getCurrentPosition.
> 
> I would love to dig in and figure out the cause here, I suspect something changed in the iOS operating system update. I actually think this was not happening on 14.2 beta as well, which is interesting.

@abarax have you used this approach on ios as well? I'm getting this log:
⚡️  [log] - This browser does not support the Permissions API

**Comment by dwieeb** [comment]
2.4.3 is out with this fix.

**Comment by DwieDima** [comment]
@jcesarmobile this issue seems to persist in version `1.3.1`.
If you reject Geolocation Services and then call `Geolocation.getCurrentPosition()`, you'll get the error message in XCode:

`Operation could not be completed(KCLErrorDomain error 1.)`.

expected: `GeolocationPositionError`
