### ISSUE TITLE
bug: I Can't Cancel Taked Photo when I click on repeat.

### ISSUE THREAD

**Issue by FeehGb** [ionic-team/capacitor#3804]
### Capacitor Version

**6.12.0**

### Platform(s)
Android

### Current Behavior

> When we take a picture, and then click on repeat, if I cancel the action, it remains in cache, then if click cancel, the picuture is returned as if I took the picture insted cancel

### Expected Behavior

> If I clicked on reapeat and cancel, It should return cancel actions.

### Code Reproduction
```
try {

      const capturedPhoto = await Camera.getPhoto({
        resultType: CameraResultType.Base64,
        source: CameraSource.Camera,
        quality: 90,
        width: 800,
        direction: CameraDirection.Front
      });
      console.log({ capturedPhoto })
      //console.log(capturedPhoto.base64String)
      return `data:image/jpeg;base64,${capturedPhoto.base64String}`
    } catch (error) {
      console.log({error})
    }
```

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by FeehGb** [comment]
I will create one soon.

**Comment by FeehGb** [comment]
I upload in my github an example of code:  
**https://github.com/FeehGb/ionic-camera**

To test the issue you need click on CAMERA so take a picuture, then click on repeat to take another photo.
but instead of take a new picture, go back to the page and do not take another photo.
You will se that the canceled photo will be shown as if you have taked a photo.

**Comment by jcesarmobile** [comment]
I can't reproduce, tested on Android 5, 7 and 9 devices.
What's the Android version and device where you tested?

Anyway, the Camera plugin just launches the Camera app, and the camera app is the one in charge of telling us if the user accepted or canceled the photo. If your Camera app somehow returns a picture despite the user cancelled, there is nothing we can do about it.

**Comment by FeehGb** [comment]
My device is Galaxy S8 Android 9.
I will show what happens.
REPETIR = REPEAT
Looks when I clicked on repeat then I go back to the main page, so that photo that I Took returned

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/43045359/100386480-3f9a2080-3004-11eb-987e-4e27b2b55979.gif)

**Comment by jcesarmobile** [comment]
I got a device that allows to cancel after retake and I can't reproduce in Capacitor 3 with @capacitor/camera plugin, so might be fixed.
If you move to Capacitor 3 and still face the issue, please, report a new issue on 
https://github.com/ionic-team/capacitor-plugins/issues
