### ISSUE TITLE
bug: Ionic 5, Capacitor 2.4.0, cordova-sqlite-storage: 5.1.0 issue during Android release build creation

### ISSUE THREAD

**Issue by marshall86** [ionic-team/capacitor#3820]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/android 2.4.2
  @capacitor/core 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/cli 2.4.0
  @capacitor/electron not installed

[success] Android looking great! 

Npm Version 6.14.6
Node Version 10.16.0

Good morning, I did the porting of my Ionic 3 App to Ionic 5 with Capacitor. 
I need to preserve the storage of the old App and read it in the new one.

Below my package.json file

"dependencies": {
    "@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@capacitor/android": "^2.4.0",
    "@capacitor/core": "^2.4.0",
    "@capacitor/ios": "^2.4.0",
    "@ionic-native/call-number": "^5.29.0",
    "@ionic-native/core": "^5.29.0",
    "@ionic-native/deeplinks": "^5.29.0",
    "@ionic-native/email-composer": "^5.29.0",
    "@ionic-native/fingerprint-aio": "^5.29.0",
    "@ionic-native/in-app-browser": "^5.29.0",
    "@ionic-native/market": "^5.29.0",
    "@ionic-native/secure-storage": "^5.29.0",
    "@ionic/angular": "^5.4.4",
    "@ionic/storage": "^2.3.1",
    "@teamhive/capacitor-email": "^2.1.2",
    "call-number": "^1.0.1",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-email-composer": "^0.9.2",
    "cordova-plugin-fingerprint-aio": "^4.0.1",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "cordova-plugin-market": "^1.2.0",
    "cordova-plugin-secure-storage": "^3.0.2",
    "cordova-sqlite-storage": "^5.1.0",
    "crypto-js": "^3.0.0",
    "es6-promise-plugin": "^4.2.2",
    "ionic-plugin-deeplinks": "^1.0.20",
    "jetifier": "^1.6.6",
    "rxjs": "~6.6.2",
    "tslib": "^2.0.1",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler": "~9.1.6",
    "@angular/compiler-cli": "~9.1.6",
    "@angular/language-service": "~9.1.6",
    "@capacitor/cli": "2.4.0",
    "@ionic/angular-toolkit": "^3.0.0",
    "@types/crypto-js": "^3.1.47",
    "@types/jasmine": "^3.5.12",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^14.0.27",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.2",
    "karma": "^5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "^4.0.0",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~7.0.0",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.3",
    "typescript": "~3.8.3"
  },

If i try to run the app in debug mode it works as expected, from the new App i can read the storage of the Ionic 3 App, the problem is when i switch from debug to release.

In release mode, as soon as i launch the App i get the following error:

2020-11-18 10:19:47.876 9818-9976/appname E/appname: No implementation found for int o.createRatingBar.d(int) (tried Java_o_createRatingBar_d and Java_o_createRatingBar_d__I)
2020-11-18 10:19:47.886 9818-9976/appname E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: appname, PID: 9818
    java.lang.UnsatisfiedLinkError: No implementation found for int o.createRatingBar.d(int) (tried Java_o_createRatingBar_d and Java_o_createRatingBar_d__I)
        at o.createRatingBar.d(Native Method)
        at o.isOngoing.<init>(:10)
        at io.sqlc.SQLiteConnectorDatabase.<clinit>(:39)
        at io.sqlc.SQLitePlugin.openDatabase(:212)
        at io.sqlc.SQLitePlugin.access$000(:28)
        at io.sqlc.SQLitePlugin$DBRunner.run(:328)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run

So far I'm testing this behaviour only on Android, I can't tell if there's a similar error on iOS as well.

Any idea why i'm getting this error and how i can fix it please? Thanks

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by marshall86** [comment]
I can't provide you a sample app but what I do is to check in the storage using ionic/storage if there's the key I need, if there is i copy it in the new storage using the capacitor Storage. Set

The logic is quite simple, the problem occurs when I switch in release mode in android studio, the issue is most probably related to cordova-plugon-sqlite and the integration with capacitor

**Comment by marshall86** [comment]
plus without "cordova-plugin-dialogs": "^2.0.2", i get the following error:

java.lang.UnsatisfiedLinkError: No implementation found for int o.createMultiAutoCompleteTextView.e(int) (tried Java_o_createMultiAutoCompleteTextView_e and Java_o_createMultiAutoCompleteTextView_e__I)
        at o.createMultiAutoCompleteTextView.e(Native Method)
        at o.LocalNotificationSchedule.<init>(:10)
        at io.sqlc.SQLiteConnectorDatabase.<clinit>(:39)
        at io.sqlc.SQLitePlugin.openDatabase(:212)
        at io.sqlc.SQLitePlugin.access$000(:28)
        at io.sqlc.SQLitePlugin$DBRunner.run(:328)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

I'm trying the following:

import { Injectable } from '@angular/core';
// import { Plugins } from '@capacitor/core';
// const { Storage } = Plugins;
import { AESEncryptDecryptService } from '../encryption/aesencrypt-decrypt.service';
import { Storage } from '@ionic/storage';

@Injectable({
  providedIn: 'root'
})
export class StoreDataService {

  constructor(private encryption: AESEncryptDecryptService, private cvStorage: Storage) { }

  set(key: string, value: any): Promise<void> {
    return this.cvStorage.set(key, this.encryption.encrypt(JSON.stringify(value)));
    // return Storage.set({ key, value: this.encryption.encrypt(JSON.stringify(value)) });
  }

  async get(key: string): Promise<string | any> {

    /* const checkData = await Storage.get({ key });
    console.log(key, checkData);
    return checkData.value ? JSON.parse(this.encryption.decrypt(checkData.value)) : ''; */

    let checkData = await this.cvStorage.get(key);
    console.log(key, checkData);

    if (checkData) {
      const decData = this.encryption.decrypt(checkData);
      console.log(decData);
      return JSON.parse(decData);
    } /* else {
      checkData = await Storage.get({ key });
      return checkData.value ? JSON.parse(this.encryption.decrypt(checkData.value)) : '';
    } */

  }

  delete(key: string): Promise<void> {

    if (key) {
      this.cvStorage.remove(key);
      // return Storage.remove({ key });
    } else {
      return this.cvStorage.clear();
      // return Storage.clear();
    }
  }

}

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
