### ISSUE TITLE
bug: Capacitor podspec not updated since 2.1.1

### ISSUE THREAD

**Issue by typeoneerror** [ionic-team/capacitor#3821]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.3
  @capacitor/core: 2.4.3
  @capacitor/android: 2.4.3
  @capacitor/electron: 2.4.3
  @capacitor/ios: 2.4.3

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/android 2.4.2
  @capacitor/core 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 3 Capacitor plugins for ios:
    @capacitor-community/fcm (1.0.8)
    @precision-nutrition/capacitor-device-model (0.17.0-rc.0)
    cc.fovea.cordova.purchase (8.1.1)
[success] iOS looking great! 👌
```

### Platform(s)

- All

### Current Behavior

Updating one of our plugins and the following occurs when attempting to lint our podspec...

```
pod lib lint

    - ERROR | [iOS] unknown: Encountered an unknown error (CocoaPods could not find compatible versions for pod "Capacitor":

None of your spec sources contain a spec satisfying the dependency: `Capacitor (= 2.4.2)`.
```

### Expected Behavior

Capacitor spec should be published past 2.1.1.

https://github.com/CocoaPods/Specs/tree/master/Specs/f/2/b/Capacitor

### Code Reproduction

None

### Other Technical Details

`npm --version` output: 6.14.6

`node --version` output: v12.18.3

`pod --version` output (iOS issues only): 1.10.0

**Comment by dwieeb** [comment]
@typeoneerror What happens if you take the CocoaPods dependency out? https://github.com/PrecisionNutrition/capacitor-device-model/blob/master/PrecisionNutritionCapacitorDeviceModel.podspec#L15

Capacitor packages are distributed through npm (and have been for quite a while). This is the first we've heard someone being affected by no longer publishing to CocoaPods and the maven repo.

**Comment by typeoneerror** [comment]
@dwieeb oh, word, I guess I just need to remove it. it may have been removed after I initially created this plugin. I'll try to compare with the later plugin template. Thanks!

**Comment by jcesarmobile** [comment]
Not the dependency, but the version, the dependency needs to be there, just don't specify a version
