### ISSUE TITLE
bug: CAPLog crashes iOS debugger when printing big cordova calls

### ISSUE THREAD

**Issue by pwandl** [ionic-team/capacitor#3824]
## Bug Report
Currently all cordova plugin calls are logged. If those contain huge strings, the Debugger just crashes due to the amount of logs. 
Printing all this data does not provide any benefit anyway, it can just be truncated.
On Android Logcat seems to take care of that on its own.
### Capacitor Version

```
Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/android 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron not installed
```

### Platform(s)

ios

### Current Behavior

Call a cordova plugin with a huge parameter, e.g. a blob to write into a file.

### Expected Behavior

Call should be logged, extra long strings should be truncated.

### Code Reproduction

tbd

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context

Suggest to just truncate all items in CAPLog, will provide a pull request.

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by pwandl** [comment]
Unfortunately not this week, maybe I can find time next week if the PR is not sufficient.

**Comment by phellmayr1** [comment]
Indeed, we have the same issue, the iOS Debugger can not handle long base64 logs and just crashes for iOS Apps. The fix would be very much appreciated.
