### ISSUE TITLE
bug: iOS - TextArea is not focused when Keyboard is showing

### ISSUE THREAD

**Issue by hborjaille** [ionic-team/capacitor#3826]
### Capacitor Version

```
Installed Dependencies:
  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/android 2.4.2
  @capacitor/ios 2.4.2
```

### Platform(s)

iOS

### Current Behavior

Not focusing on TextArea when selected.

<img src="https://user-images.githubusercontent.com/8645455/99689437-4a463a00-2a87-11eb-8e1f-12c90354bc25.gif" width="250"/>

### Expected Behavior

Android: Same Item, but it is focused once selected.

<img src="https://user-images.githubusercontent.com/8645455/99689852-c2acfb00-2a87-11eb-9285-46c017cca137.gif" width="250"/>

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
This is caused by Keyboard plugin as it removes the WebView default behavior to implement the custom resize modes.

Capacitor 3 has moved the plugins out, so once it's released, all you need to do is to not install @capacitor/keyboard.
