### ISSUE TITLE
Feature request: add cordova-plugin-firebase functionality

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/capacitor#383]
The cordova-version of the plugin does not work with capacitor because the implementation relies on extending `AppDelegate` (there are probably more issues but that was the first show-stopper I encountered). 
I've seen that the Messaging (push-notification) part is handled in another issue (#380 ), so I will limit this one to the remaining functionality:
- Analytics
- RemoteConfig
- Auth
- Crash

At least for our apps (and most probably other enterprise apps) Analytics and RemoteConfig are two very essential parts and it would be nice to see them integrated along with the push-notifaction plugin.

**Comment by wtrocki** [comment]
pinging @jcesarmobile - from our chat this works on Android and there was fix available for IOS.

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by kaimallie** [comment]
I was looking for a solution and did this, I can now track Analytics in Firebase:

1. Add the [Firebase SDK](https://firebase.google.com/docs/ios/setup) to your capacitor ios project with pods
2. Add 'import' firebase to AppDelegate.swift + FirebaseAnalyticsPlugin.m file (inside Pods):
```
import FirebaseCore
import FirebaseAnalytics
import FirebaseInstanceID
```
3. Add `FirebaseApp.configure()` to didFinishLaunchingWithOptions
4. Add GoogleService-Info.plist file from Firebase to 'App' folder in xcode

Now it's working :)

**Comment by bw7432** [comment]
Hi, is there any update on this? I can't seem to get the above working. It still says 'module "Firebase"' or "module 'FirebaseCore'" not found.

**Comment by stewwan** [comment]
Just released this for analytics, for those who are struggled

https://github.com/stewwan/capacitor-analytics

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/21. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
