### ISSUE TITLE
bug: convertFileSrc does not work with Filesystem

### ISSUE THREAD

**Issue by roblouie** [ionic-team/capacitor#3840]
### Capacitor Version

```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.3
  @capacitor/core: 2.4.3
  @capacitor/android: 2.4.3
  @capacitor/electron: 2.4.3
  @capacitor/ios: 2.4.3

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.3
  @capacitor/core 2.4.3
  @capacitor/android 2.4.3
  @capacitor/electron not installed

[success] Android looking great! �
```

### Platform(s)

Android

### Current Behavior

Using image files saved via Filesystem as img src attributes is not possible. Following [the documentation](https://capacitorjs.com/docs/basics/utilities#convertfilesrc) simply results in a "404 (OK)" error, and no file loads. Logcat also states: `Capacitor: Unable to open asset URL: http://localhost/_capacitor_file_/DOCUMENTS/myFile.png`

### Expected Behavior

I should be able to use image files I've saved as img src [per the documentation
](https://capacitorjs.com/docs/basics/utilities#convertfilesrc)

### Code Reproduction

https://github.com/roblouie/file-src-broken

### Other Technical Details

I have verified that the file is saved using file system, i can read it back. I simply cannot use convertFileSrc. Based on errors, it is doing the thing the docs says it does: "must be rewritten as http://localhost/_capacitor_file_/path/to/device/file before being used in the Web View.". The failed request is in that format.

`npm --version` : 6.14.4

`node --version` : v13.12.0

`pod --version` (iOS issues only):

### Additional Context

There's an open issue here with discussion: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/380
Nothing really seemed to help me there though.

**Comment by jcesarmobile** [comment]
You are using web version of the plugin, not the native version

instead of `import { Filesystem } from "@capacitor/core";` use 
```
import { Plugins } from "@capacitor/core";
const { Filesystem } = Plugins;
```
