### ISSUE TITLE
bug: npx cap add android

### ISSUE THREAD

**Issue by dprem06** [ionic-team/capacitor#3845]
[error] The web directory (..\build) must contain a "index.html".
    It will be the entry point for the web portion of the Capacitor app.

npx cap add android
While try to add android platform in next js shows me error, can you help me how to copy build folder to assets and convert android apk?

**Comment by jcesarmobile** [comment]
In your `capacitor.config.json` file you should have a `webDir` entry that must point to a folder where your web assets are built and it should contain an `index.html` file.
