### ISSUE TITLE
feat: BridgeWebViewClient method override in plugins

### ISSUE THREAD

**Issue by ribizli** [ionic-team/capacitor#3852]
### Description
I need to do client certificate authentication (I used the Cordova plugin `cordova-client-cert-authentication`), which was hooked into WebView's `onReceivedClientCertRequest` method.
An other use-case we have is to handle SSL error hooking into the method `onReceivedSslError`, and proceed with untrusted (e.g. self signed) certificates.

### Platform(s)
We use Ionic only on Android currently (no iOS needed currently).

### Preferred Solution
I'm not fully aware of the internals of capacitor, I don't have any suggestion at the moment. Maybe a delegation to `Plugin` would be a good idea?

### Alternatives
Our current solution is to patch `Bridge` and `BridgeWebViewClient` during build, to perform the desired actions:
* `onReceivedSslError`: proceed on untrusted
* `onReceivedClientCertRequest`: call Cordova's PluginManager, which have the correct delegation to the `cordova-client-cert-authentication` plugin.

### Additional Context
We'd be very thankful.

**Comment by aparajita** [comment]
You can do it now without a custom build. Create a subclass of `BridgeWebChromeClient`:

```java
public class MyBridgeWebChromeClient extends BridgeWebChromeClient {

    public MyBridgeWebChromeClient(Bridge bridge) {
        super(bridge);
    }

    // Override any methods you need
}
```

Then create a plugin with a `patchWebViewClient` call:

```java
    @PluginMethod
    public void patchWebViewClient(PluginCall call) {
        class Runner implements Runnable {

            public void run() {
                bridge.getWebView().setWebChromeClient(new MyBridgeWebChromeClient(bridge));
            }
        }

        bridge.executeOnMainThread(new Runner());
        call.success();
    }
```

Call `patchWebViewClient` at startup.

**Comment by jcesarmobile** [comment]
As aparajita commented, it's already possible.
You can do it with a custom plugin (I would suggest doing it in plugins load method instead of in a custom plugin method as load is executed on app start up).
You can also override the `WebViewClient` from `MainActivity.java` instead of using a plugin.
