### ISSUE TITLE
feat: add missing GPS tags to exif data (iOS)

### ISSUE THREAD

**Issue by ryaa** [ionic-team/capacitor#3860]
### Description
GPSLatitude, GPSLatitudeRef, GPSLongitude and GPSLongitudeRef should be in the EXIF data. Right now exif does not include those on iOS platform

### Platform(s)
iOS

### Preferred Solution
It seems that this is enabled for Android platform only. See https://github.com/ionic-team/capacitor/pull/2284/

### Alternatives
N/A

### Additional Context
N/A

**Comment by jcesarmobile** [comment]
is this for pictures taken by the camera? picked from the gallery? both?
Can you provide a sample app?

**Comment by ryaa** [comment]
> is this for pictures taken by the camera? picked from the gallery? both?

I had the GPS tags missing when picking up a photo from the gallery however it seems that this is for both. There have already been the bug describing this problem - see https://github.com/ionic-team/capacitor/issues/2283

> Can you provide a sample app?

Yes. However this should be easily reproducible with the basic sample ionic angular application with camera/image picker support as described here https://ionicframework.com/docs/angular/your-first-app or see **Sample Code or Sample Application Repo** section here https://github.com/ionic-team/capacitor/issues/2283

I think the problem is with makeExif method in Camera.swift plugin class (https://github.com/ionic-team/capacitor/blob/2.4.3/ios/Capacitor/Capacitor/Plugins/Camera.swift#L371). Out of all the metadata fetched it returns only what is under **Exif** key

For example, for one of my test photos, when I use a picker the metadata read is as follows:
```
{
    ColorModel = RGB;
    DPIHeight = 72;
    DPIWidth = 72;
    Depth = 8;
    Orientation = 6;
    PixelHeight = 3024;
    PixelWidth = 4032;
    ProfileName = "sRGB IEC61966-2.1";
    "{Exif}" =     {
        ApertureValue = "2.275007047547454";
        BrightnessValue = "-0.1063010076140975";
        ColorSpace = 1;
        ComponentsConfiguration =         (
            1,
            2,
            3,
            0
        );
        DateTimeDigitized = "2020:11:23 14:52:11";
        DateTimeOriginal = "2020:11:23 14:52:11";
        ExifVersion =         (
            2,
            3,
            1
        );
        ExposureBiasValue = 0;
        ExposureMode = 0;
        ExposureProgram = 2;
        ExposureTime = "0.125";
        FNumber = "2.2";
        Flash = 24;
        FlashPixVersion =         (
            1,
            0
        );
        FocalLenIn35mmFilm = 29;
        FocalLength = "4.15";
        ISOSpeedRatings =         (
            125
        );
        LensMake = Apple;
        LensModel = "iPhone 6s Plus back camera 4.15mm f/2.2";
        LensSpecification =         (
            "4.15",
            "4.15",
            "2.2",
            "2.2"
        );
        MeteringMode = 5;
        OffsetTime = "+03:00";
        OffsetTimeDigitized = "+03:00";
        OffsetTimeOriginal = "+03:00";
        PixelXDimension = 4032;
        PixelYDimension = 3024;
        SceneCaptureType = 0;
        SceneType = 1;
        SensingMethod = 2;
        ShutterSpeedValue = "3.058989872418782";
        SubjectArea =         (
            2015,
            1511,
            2217,
            1330
        );
        SubsecTimeDigitized = 330;
        SubsecTimeOriginal = 330;
        WhiteBalance = 0;
    };
    "{GPS}" =     {
        Altitude = "160.676113127124";
        AltitudeRef = 0;
        DestBearing = "44.44742582897033";
        DestBearingRef = T;
        HPositioningError = 10;
        ImgDirection = "44.44742582897033";
        ImgDirectionRef = T;
        Latitude = "56.24760833333333";
        LatitudeRef = N;
        Longitude = "44.03646383333334";
        LongitudeRef = E;
        Speed = 0;
        SpeedRef = K;
    };
    "{MakerApple}" =     {
        1 = 12;
        12 =         (
            "0.3203125",
            "0.4960938"
        );
        13 = 14;
        14 = 4;
        15 = 2;
        16 = 1;
        2 = {length = 512, bytes = 0xfe001f01 68004000 7f003d00 4200b600 ... b9004f00 6300bd00 };
        20 = 5;
        23 = 0;
        25 = 0;
        28 = 3;
        3 =         {
            epoch = 0;
            flags = 1;
            timescale = 1000000000;
            value = 468076701523458;
        };
        31 = 0;
        32 = "A3282019-BF6D-47B8-962E-161427FA82D5";
        37 = 0;
        38 = 0;
        39 = 0;
        4 = 1;
        43 = "A37DF476-104E-4425-987E-00D9EFBD3092";
        47 = 137;
        5 = 116;
        54 = 48;
        59 = 0;
        6 = 124;
        60 = 0;
        7 = 1;
        8 =         (
            "0.02434131",
            "-0.4496751",
            "-0.8739341"
        );
        9 = 4627;
    };
    "{TIFF}" =     {
        DateTime = "2020:11:23 14:52:11";
        Make = Apple;
        Model = "iPhone 6s Plus";
        Orientation = 6;
        ResolutionUnit = 2;
        Software = "14.1";
        XResolution = 72;
        YResolution = 72;
    };
}
```
and the exif returned contains only part of the above and no GPS tags

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by ryaa** [comment]
Why is this closed? I think provided the required details...

**Comment by sebastianovide** [comment]
I have the same problem... @ryaa , did you find a solution ?

**Comment by ryaa** [comment]
> I have the same problem... @ryaa , did you find a solution ?

well. as a workaround i use forked version of this lib https://github.com/exif-js/exif-js to read the required data.

**Comment by sebastianovide** [comment]
thanks @ryaa . I'll keep our old cordova plugin "cordova-plugin-camera-with-exif" https://github.com/remoorejr/cordova-plugin-camera-with-exif until when the capacitor bug will be fixed.

**Comment by craigstanton** [comment]
+1 this is still needed as far as I am concerned. Other useful Exif details include GPSImgDirection and GPSImgDirectionRef for finding out which way the camera was pointing at the time it was taken. Without reading that from the photo we're stuck with recording the value when the photo is selected and the device is very likely to have changed between the shutter button and the confirmation button.
