### ISSUE TITLE
PhotoLibraryService.swift issues compiling

### ISSUE THREAD

**Issue by AlvaroFalcon** [ionic-team/capacitor#3861]
PhotoLibraryService.swift is giving compile issues, is there any already issue related to this or any fix? Right now we can't compile on iOS.

Podfile:

```
platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  # Do not ### delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

```

from /
cordova-plugin-photo-library

**Comment by jcesarmobile** [comment]
It's a plugin problem, not a Capacitor problem, it uses Swift 3, which is not supported on Xcode 10.2 or newer, doesn't build in Cordova neither.

There is a PR that solves the issue, but it's not merged https://github.com/terikon/cordova-plugin-photo-library/pull/190
