### ISSUE TITLE
feat: add support for accessing registered plugin from native code

### ISSUE THREAD

**Issue by tafelnl** [ionic-team/capacitor#3867]
It would be helpful to be able to access a plugin from the native side as well. For example, I want to trigger a `notifyListeners`. But this is only possible from inside a plugin (correct ?). It would be great if there is a way to call certain methods from outside the plugin (inside MainActivity.java) for example.

**Comment by jcesarmobile** [comment]
It’s already possible to get a plugin and call it’s methods.
And in addition, in capacitor 3.0 we are moving plugins out and most of them have an implementation class that can be used in an easier way than at the moment.

**Comment by tafelnl** [comment]
That sounds great! Is there any documentation available for this?
