### ISSUE TITLE
bug: globalThis is not defined

### ISSUE THREAD

**Issue by aerodynamics-digital** [ionic-team/capacitor#3871]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.4.3
  @capacitor/core: 2.4.3
  @capacitor/android: 2.4.3
  @capacitor/electron: 2.4.3
  @capacitor/ios: 2.4.3

Installed Dependencies:

  @capacitor/cli 2.4.3
  @capacitor/core 2.4.3
  @capacitor/ios 2.4.3
  @capacitor/android 2.4.3
  @capacitor/electron not installed

```
PASTE OUTPUT HERE
```

### Platform(s)
android

### Current Behavior
in the emulator i get the error: E/Capacitor/Console: File: capacitor-runtime.js - Line 361 - Msg: ReferenceError: globalThis is not defined

in the chrome inspector i can see more details about it: ReferenceError: globalThis is not defined

### Expected Behavior
app should load correctly

### Code Reproduction
ionic app with angular 11 and angularfire 6.1.1 installed (but any other service that caches on globalThis will get this error)

### Other Technical Details

`npm --version` output:
6.14.9

`node --version` output:
v12.15.0

`pod --version` output (iOS issues only):

**Comment by rmakash** [comment]
Hi,
I faced the same problem after updating @angular/fire to the latest version!
I downgraded @angular/fire to version 6.0.4 and all worked fine.
Hope this helps.

**Comment by aerodynamics-digital** [comment]
yes i know, we would like to use the new functionalities added in 6.1, does anyone have a workaround? i tried adding it in polyfills but i could'd get it to work

**Comment by jcesarmobile** [comment]
this is not a Capacitor issue, moving to discussions so maybe somebody can help you
