### ISSUE TITLE
feat: Change platform when ios app is running on MacOs

### ISSUE THREAD

**Issue by nathantaal** [ionic-team/capacitor#3881]
### Description
Capacitor should be able to detect when the app is running on iOS but actually on a Mac. For example, Ionic Native functionality like fingerprint and facial recognition probaly won't work on Mac while capacitor detected iOS.

### Platform(s)
iOS

### Preferred Solution
Make capacitor return something like ios-mac

**Comment by jcesarmobile** [comment]
If you mean `Capacitor.platform`, that will always return the capacitor platform (i.e, ios, android, electron)

If you mean in `Device.getInfo` returned information, we should fix that, but there is another issue already https://github.com/ionic-team/capacitor-plugins/issues/438
