### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Schwankenson** [ionic-team/capacitor#3890]
`npx cap serve` generates this error

    ✖ Serving web content in: www: 
    [error] glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'scandir',
    path: '/root/.npm/_logs'
    }
    npm ERR! code EACCES
    npm ERR! syscall open
    npm ERR! path /root/.npm/_cacache/index-v5/ff/42/270a815fb1e3babf1a7e15c6822e64cf5bedc2d8dfb54cfa2450d956ffa8
    npm ERR! errno -13
    npm ERR! 
    npm ERR! Your cache folder contains root-owned files, due to a bug in
    npm ERR! previous versions of npm which has since been addressed.
    npm ERR! 
    npm ERR! To permanently fix this problem, please run:
    npm ERR!   sudo chown -R 1000:1000 "/root/.npm"

    npm ERR! code 1
    npm ERR! path /app
    npm ERR! command failed
    npm ERR! command sh -c cap serve

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2020-12-02T15_39_29_165Z-debug.log

On this dockerfile:

    FROM node:15.3.0-buster

    # Install angular cli
    RUN npm install -g @angular/cli@^10.2

    # Install ionic
    RUN npm install -g @ionic/cli@6.12.2 native-run@1.2.2 cordova-res@0.15.2

    # Install local web server
    RUN npm install -g local-web-server@4.2.1

    # Make angular cli available
    RUN ln -s /app/node_modules/\@angular/cli/bin/ng /usr/bin

**Comment by jcesarmobile** [comment]
The error message says:
> Your cache folder contains root-owned files, due to a bug in
>  previous versions of npm which has since been addressed.

so doesn't look like a Capacitor bug

also we have removed serve command in Capacitor 3, so no more work will be done on it, if you are using Ionic you can use ionic serve instead of cap serve
