### ISSUE TITLE
bug: Browser plugin does not trigger browserFinished event correctly for Android

### ISSUE THREAD

**Issue by fohlin** [ionic-team/capacitor#3896]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.4
  @capacitor/core: 2.4.4
  @capacitor/android: 2.4.4
  @capacitor/electron: 2.4.4
  @capacitor/ios: 2.4.4

Installed Dependencies:

  @capacitor/cli 2.4.4
  @capacitor/core 2.4.4
  @capacitor/ios 2.4.4
  @capacitor/android 2.4.4
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

### Platform(s)

Android (tested on Emulator API 29)

### Current Behavior

For Capacitor 2.x, the Browser plugin should trigger the `browserFinished` event as the in-app browser is dismissed. On Android it does not. Instead, the app needs to become inactive and then resumed again. Only then does the `browserFinished` event listeners get called.

### Expected Behavior

iOS displays the expected behavior: `browserFinished` event listeners get called immediately.

**[This video expected behavior (iOS) vs. buggy behavior (Android)](https://github.com/fohlin/cap-browser-events-repro/blob/main/bug-report.mov)**.

### Code Reproduction

A small project reproducing this issue can be found at [@fohlin/cap-browser-events-repro](https://github.com/fohlin/cap-browser-events-repro).

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v14.15.0

`pod --version` output (iOS issues only):

### Additional Context

Possibly related to: https://github.com/ionic-team/capacitor/pull/2332

---

I realize that development is focus on Capacitor v3, but it would be extremely appreciated if someone has an idea for a fix for this. 🙏

**Comment by jcesarmobile** [comment]
I can't reproduce.
Tested on real devices:
Android 5.0.1
Android 9
Android 11
Emulators:
SDK 25
SDK 29
SDK 30 

could be a bug on the emulator
