### ISSUE TITLE
bug: Local Notification does not fire on first scheduling

### ISSUE THREAD

**Issue by wal0x** [ionic-team/capacitor#3908]
### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.4
  @capacitor/core: 2.4.4
  @capacitor/android: 2.4.4
  @capacitor/electron: 2.4.4
  @capacitor/ios: 2.4.4

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.4
  @capacitor/core 2.4.4
  @capacitor/android 2.4.4
  @capacitor/electron not installed

[success] Android looking great! �
```

### Platform(s)

Android

### Current Behavior
When scheduling a Local Notification in the first time I run my app and I close the app completly, the notification does not fire. If I repeate the same thing for a second time and quit the app, the notification fires.

Steps To reproduce the issue :

1. Run the app for the first time
2. Schedule a notification in 5 seconds
3. Exit fast the application
4. Delete quickly the app from the Running apps list
5. Notification does not fire after 5 seconds from clicking the button
6. If you repeat the 4 first steps the notification will fire this time.

### Expected Behavior
Notification should fire in the first time too

### Code Reproduction
I have created a simple Repo based on an Ionic template with a few added code only for local notifications to reproduce the bug. 
https://github.com/wal0x/capacitorNotifBug

### Other Technical Details

npm --version output: 6.14.8

node --version output: v12.19.0

### Additional Context
I have used the same code to schedule a local notification as the one in Capacitor offical documentation.
https://capacitorjs.com/docs/apis/local-notifications#example

**Comment by jcesarmobile** [comment]
I've tested on Android 9 And android 11 devices and couldn't reproduce
