### ISSUE TITLE
bug: IOS - App crashes when image is taken on landscape mode and the screen orientation set to portrait

### ISSUE THREAD

**Issue by zivanvizer** [ionic-team/capacitor#3910]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.4.4
  @capacitor/core: 2.4.4
  @capacitor/android: 2.4.4
  @capacitor/electron: 2.4.4
  @capacitor/ios: 2.4.4

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/android 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 24 Capacitor plugins for ios:
    cordova-android-support-gradle-release (3.0.1)
    cordova-custom-config (5.1.0)
    cordova-plugin-android-permissions (1.1.0)
    cordova-plugin-background-mode (0.7.3)
    cordova-plugin-bluetooth-serial (0.4.6)
    cordova-plugin-bluetoothClassic-serial (0.9.8)
    cordova-plugin-chooser (1.3.2)
    cordova-plugin-chrome-apps-common (1.0.7)
    cordova-plugin-chrome-apps-iossocketscommon (1.0.2)
    cordova-plugin-chrome-apps-sockets-tcp (1.3.8-dev)
    cordova-plugin-device (2.0.3)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-opener2 (3.0.5)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-filepath (1.5.8)
    cordova-plugin-inappbrowser (4.0.0)
    cordova-plugin-locusview-trimble (1.0.0)
    cordova-plugin-telerik-imagepicker (2.3.5)
    cordova-sqlite-storage (5.1.0)
    cordova.plugins.diagnostic (6.0.2)
    es6-promise-plugin (4.2.2)
    phonegap-plugin-barcodescanner (8.1.0)
    v3-gps-bluetooth-serial (0.4.7)
    com.telerik.plugins.nativepagetransitions (0.6.5)
[success] iOS looking great!

### Platform(s)
iOS

### Current Behavior
The app crash when a picture is taken in landscape mode after clicking on "Use Photo". The app orientation set to portrait.

{"webPath":"ionic:\/\/localhost\/_capacitor_file_\/private\/var\/mobile\/Containers\/Data\/Application\/23ADF8ED-8118-45E0-8D3D-530DD36EC26A\/tmp\/photo-1.jpg","format":"jpeg","path":"file:\/\/\/private\/var\/mobile\/Containers\/Data\/Application\/23ADF8ED
2020-12-07 12:20:38.979693+0200 App[1193:1125508] *** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'preferredInterfaceOrientationForPresentation 'landscapeRight' must match a supported interface orientation: 'portrait'!'
*** First throw call stack:
(0x19ac5a878 0x1af1b0c50 0x19ab534a4 0x19cefedd0 0x19cdd14a8 0x19cdc6abc 0x19cefa0d0 0x19cef9458 0x19cef8ca0 0x19cef86ec 0x19cef8044 0x19cefad40 0x104c893b0 0x104c8994c 0x19ce064d8 0x1d82b9628 0x1c3d595b4 0x1c3d58e64 0x19d60f190 0x19cf45fc4 0x19cf46318 0x19cf44b7c 0x19d64d868 0x19d64f1d0 0x19d6284ec 0x19d6b2488 0x19d6b5440 0x19d6ac8ec 0x19abd676c 0x19abd6668 0x19abd5960 0x19abcfa8c 0x19abcf21c 0x1b1c4e784 0x19d608200 0x19d60da74 0x1047636dc 0x19a88f6c0)
libc++abi.dylib: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'preferredInterfaceOrientationForPresentation 'landscapeRight' must match a supported interface orientation: 'portrait'!'

### Expected Behavior

The app shouldn't crash.

### Code Reproduction
From capacitor.config.json:
 "cordova": {
    "preferences": {
      "ScrollEnabled": "false",
      "android-minSdkVersion": "22",
      "android-targetSdkVersion": "29",
      "BackupWebStorage": "none",
      "Orientation": "portrait",
      "SplashMaintainAspectRatio": "true",
      "SplashScreen": "screen",
      "AutoHideSplashScreen": "false",
      "ShowSplashScreenSpinner": "false",
      "FadeSplashScreen": "true",
      "FadeSplashScreenDuration": "400",
      "SplashShowOnlyFirstTime": "true",
      "StatusBarBackgroundColor": "#121032",
      "KeyboardResize": "true",
      "KeyboardResizeMode": "native"
    }
  }

### Other Technical Details

`npm --version` output: 6.14.5

`node --version` output: v14.3.0

`pod --version` output (iOS issues only): 1.9.3

**Comment by kensodemann** [comment]
Using this sample repo to test on my devices: https://github.com/gnesher/capacitor-camera-bug

The issue does not occur on my iPhone 11 (iOS 14.2)
The issue does occur on my iPad (iPadOS 14.2)

Steps:

1. Open the app 
1. Navigate to the camera tab 
1. Tap on the camera’s icon -> camera will open 
1. Rotate your device to landscape mode 
1. Take a pic 
1. Click on use photo

**Comment by jcesarmobile** [comment]
this was fixed on 2.4.5, closing
