### ISSUE TITLE
bug: Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by mobilityvalley** [ionic-team/capacitor#3919]
## Bug Report

I added Android platform with Capacitor.

I tried various version of "@angular/fire": "^6.1.4".

The app is crashing when launched with log:

E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught ReferenceError: globalThis is not defined","url":"http://localhost/vendor-es2015.js","line":68336,"col":1,"errorObject":"{}"}}

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.4.4
  @capacitor/core: 2.4.4
  @capacitor/android: 2.4.4
  @capacitor/electron: 2.4.4
  @capacitor/ios: 2.4.4

Installed Dependencies:

  @capacitor/cli 2.4.3
  @capacitor/core 2.4.3
  @capacitor/android 2.4.3
  @capacitor/ios 2.4.3
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    @capacitor-community/fcm (1.0.8)
[success] iOS looking great! 👌

```
PASTE OUTPUT HERE
```

### Platform(s)
Android 

### Current Behavior
White screen 

### Expected Behavior
The app should launch

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Try downgrading angular fire to 6.0.4

https://github.com/ionic-team/capacitor/issues/3907

Closing as it’s not a capacitor issue

**Comment by mobilityvalley** [comment]
I did it but it changes nothing. Do you have a clue ?

I have these dependenices too:

"firebase": "^8.1.1",
"@capacitor-community/fcm": "^1.0.8",

**Comment by jcesarmobile** [comment]
There is a related thread on discussions
https://github.com/ionic-team/capacitor/discussions/3871
