### ISSUE TITLE
bug: watchPosition with high accuracy doesn't send events often enough

### ISSUE THREAD

**Issue by csurbier** [ionic-team/capacitor#3925]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.4
  @capacitor/core: 2.4.4
  @capacitor/android: 2.4.4
  @capacitor/electron: 2.4.4
  @capacitor/ios: 2.4.4

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/ios 2.4.3
  @capacitor/core 2.4.2
  @capacitor/android 2.4.3
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 15 Capacitor plugins for ios:
    cordova-plugin-actionsheet (2.3.3)
    cordova-plugin-advanced-http (3.1.0)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-email-composer (0.9.2)
    cordova-plugin-file (6.0.2)
    cordova-plugin-geolocation (4.1.0)
    cordova-plugin-inappbrowser (4.0.0)
    cordova-plugin-nativegeocoder (3.4.1)
    cordova-plugin-network-information (2.0.2)
    cordova-plugin-request-location-accuracy (2.3.0)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-sqlite-storage (5.1.0)
    es6-promise-plugin (4.2.2)
    uk.co.workingedge.phonegap.plugin.launchnavigator (5.0.5)
[success] iOS looking great! 👌
```

### Platform(s)
iOS
Android

### Current Behavior
I start watching position with high accurracy to true and need to do some math calculations with values received. The problem is that i don't receive events very often even if i move my phone with different positions to get different heading values. I receive events every 10 seconds

**2020-12-10 10:53:12.833** 15498-15498/com.minha.android I/Capacitor/Console: File: http://localhost/15-es2015.1cc0a6e2ddf9c1106b20.js - Line 1 - Msg: coords watching  {"latitude":41.3733447,"longitude":2.125232,"accuracy":500,"altitude":0,"altitudeAccuracy":0,"speed":0,"heading":90}

**2020-12-10 10:53:22.832** 15498-15498/com.minha.android I/Capacitor/Console: File: http://localhost/15-es2015.1cc0a6e2ddf9c1106b20.js - Line 1 - Msg: coords watching  
{"latitude":41.3736193,"longitude":2.1250329,"accuracy":600,"altitude":0,"altitudeAccuracy":0,"speed":0.37687915563583374,"heading":331.4454345703125}

**2020-12-10 10:53:32.828** 15498-15498/com.minha.android I/Capacitor/Console: File: http://localhost/15-es2015.1cc0a6e2ddf9c1106b20.js - Line 1 - Msg: coords watching  {"latitude":41.3738661,"longitude":2.1248539,"accuracy":600,"altitude":0,"altitudeAccuracy":0,"speed":0.8538589477539062,"heading":331.4454345703125}

### Expected Behavior

I expected to received events at least every seconds or better each time i move my phone.
I don't have this problem with the cordova plugin : 
https://ionicframework.com/docs/native/geolocation

I receive events very fast while moving. 

[log] - coords watching  {"coords":{"latitude":41.3739237765698,"longitude":2.123969402357855,"accuracy":65,"altitude":37.78940963745117,"heading":-1,"speed":-1,"altitudeAccuracy":10},"timestamp":1607593119440.765}
[log] - coords watching  {"coords":{"latitude":41.373848213842656,"longitude":2.1240788494203353,"accuracy":65,"altitude":37.206485748291016,"heading":-1,"speed":-1,"altitudeAccuracy":10},"timestamp":1607593133249.218}
[log] - coords watching  {"coords":{"latitude":41.3739726587826,"longitude":2.123965280012247,"accuracy":65,"altitude":37.117008209228516,"heading":-1,"speed":-1,"altitudeAccuracy":10},"timestamp":1607593139850.398}

But i would like to use the Capacitor plugin and not cordova plugin anymore.

### Code Reproduction

Start watching your position and move your phone with different angles (from 0 to 360)

this.idWatch = Geolocation.watchPosition({enableHighAccuracy:true}, (position, err) => {
         if (position){
          let coords = position.coords;
           console.log("coords watching ",JSON.stringify(coords))
          let latitude = coords.latitude;
          let longitude = coords. longitude;
          let angleActuel = coords.heading
          let angle = this.calcBearingWithLatitude(latitude,longitude)
          this.showImageBoussole(angle,angleActuel)
         }
      })

### Other Technical Details

`npm --version` output: 6.14.9

`node --version` output: v14.15.1

`pod --version` output (iOS issues only): 1.10.0

**Comment by csurbier** [comment]
ok i got it. Missing methods possibilities in the Geolocation plugin. 
For iOS, you should add a method 

- (void)locationManager:(CLLocationManager *)manager didUpdateHeading:(CLHeading *)newHeading {
}

And we should be able to listen to this events in our app, something like Geolocation.watchHeading() 
More info here : 
https://developer.apple.com/documentation/corelocation/getting_heading_and_course_information

I don't know what is the method for Android to do it.

**Comment by jcesarmobile** [comment]
closing in favor of this feature request on plugins repository https://github.com/ionic-team/capacitor-plugins/issues/538
