### ISSUE TITLE
Set Action Buttons language (Modal, Camera)

### ISSUE THREAD

**Issue by douglaszaltron** [ionic-team/capacitor#394]
An initial solution to not leave the action buttons with the English language set, to get the language of the "localization native development region" @mlynch 

https://gist.github.com/douglaszaltron/e2a03cbb5b51e8579e71f3e62b7789f4

https://gist.github.com/douglaszaltron/c64e29c4728ebdba6ba859aeaed2c938

https://gist.github.com/douglaszaltron/c0b579e2fff9f47e14a7f135c667f124

**Comment by mlynch** [comment]
Cool, would love that as a PR if you're up for it!

**Comment by jcesarmobile** [comment]
closing as we also have https://github.com/ionic-team/capacitor/issues/872 for the same problem
