### ISSUE TITLE
feat: Capacitor v3 configuration file: Add version and android-versionCode fields

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/capacitor#3943]
### Description
While Capacitor tries to avoid changes to users' native projects, I've seen this requested by the community several times and it's a feature Cordova has. A lot of configuration details (like setting permission details or choosing an App's name) are set once, so manual project changes aren't a big deal. However, each time you ship an update to a native iOS/Android app in the app stores, the Version Number must be incremented. So, having "cap sync" update the version number (found in Cap config) in each native project would be a nice workflow improvement.

Current workflow (app is on version 1.0 for example):
- Finish new feature
- Submit to app stores (manually or via Appflow's Deploy to app stores feature)
- It fails, due to version number not incremented
- Manually open Xcode and Android Studio, increment version number to v1.1.
- repackage binary, resubmit to app stores

### Platform(s)
ios, android

### Preferred Solution
Supported fields could look something like:

```
// capacitor.config.json
{ 
  version: "1.2.5", 
  android-versionCode: "3"
}
```

New workflow:
- Feature complete
- Increment version number in capacitor.config.json.
- npx cap sync to update native android/ios projects with new version number and code
- profit (deploy to app stores)

### Alternatives
Update android/ios projects manually.

**Comment by distante** [comment]
I wanted to a for android PR for this but I was not sure where.

What I do is synchronize my `package.json`  `version` field with the version used in android. So everything is unified. I also put there a `versionCode` field.

**Comment by jcesarmobile** [comment]
I think this is a bad idea, if Capacitor's philosophy is to NEVER update the user project, adding "just a tiny thing" will just open the door to bigger things and will end up like Cordova, with the problem that in Cordova you can wipe platforms folder and restore if something goes bad, but in Capacitor, if you did any manual change, it will be lost.

If people use tools such as fastlane to submit the apps, it can be configured to autoincrement the versions.

**Comment by distante** [comment]
But using a configuration file is something that is also done a lot on Android (AFAIK), That is also what is done with the `variables.gradle` file that is shipped with capacitor.

**Comment by jcesarmobile** [comment]
`variables.gradle` is fully managed by the user, so not sure what the your point is in that comparison, you can put the version/versionCode there if you want

**Comment by distante** [comment]
I do this there:

```
import groovy.json.JsonSlurper

def jsonSlurper = new JsonSlurper()
def packageJson = jsonSlurper.parseText( file('../package.json').text)

ext {
    minSdkVersion = 23
    compileSdkVersion = 29
    ...
    ...
    cordovaAndroidVersion =  '7.0.0'
    appVersionCode = packageJson["versionCode"]
    appVersionName = packageJson["version"]
}
```

and my `Android` app version is central in my `package.json` so I can globally track version changes but maybe in `capacitor.json` instead of `package.json` (although I find `package.json` more central).

That is what I wanted to offer as PR.

**Comment by arzyu** [comment]
Hi guys, I have implemented the tool [capacitor-sync-version](https://github.com/arzyu/capacitor-sync-version) for syncing versions from package.json.

**Comment by nakrout** [comment]
Hi guys,
I recommend also [Capacitor Project API and Configuration Tool](https://github.com/ionic-team/capacitor-configure) from ionic-team.

**Comment by jcesarmobile** [comment]
Yeah, Capacitor CLI is not supposed to change the user project. We recommend using projects such as the mentioned Capacitor Project API and Configuration Tool
