### ISSUE TITLE
bug: Camera Plugin not working in Electron with contextIsolation

### ISSUE THREAD

**Issue by tbockConId** [ionic-team/capacitor#3946]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.4
  @capacitor/core: 2.4.4
  @capacitor/android: 2.4.4
  @capacitor/electron: 2.4.4
  @capacitor/ios: 2.4.4

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/ios not installed
  @capacitor/cli 2.4.3
  @capacitor/core 2.4.3
  @capacitor/electron not installed
 @capacitor-community/electron:  1.3.2
```

### Platform(s)

Electron on macOS

### Current Behavior

Throws error when calling "Camera.getPhoto()"

'Uncaught (in promise) TypeErrror: Cannot read property 'get' of null
at r.<anonymous> electron-bridge.js:113
at Object.next electron-bridge.js:111
at electron-bridge.js:111
at new Promise (<anonymous>)
at L  electron-bridge.js:111
at electron-bridge.js:113
at new Promise (<anonymous>):13
at electron-bridge.js:111

### Expected Behavior

open Camera dialog

### Code Reproduction

Configured the Electron App with context isolation:

in index.html:

```
  <script type="module" src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"></script>
  <script nomodule src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"></script>
```

in index.js: 
```
mainWindow: {
    windowOptions: {
      webPreferences: {
        nodeIntegration: false,
        nodeIntegrationInWorker: false,
        nodeIntegrationInSubFrames: false,
        contextIsolation: true,
        enableRemoteModule: true, // we need this to get prelaoder to work
        preload: path.join(__dirname, "../preloader.js"),
      }
    }
  }
```

in preloader.js
```
getCameraPicture: async (args) => {
        try {
            const { Camera, Permissions } = Plugins;
            const hasPermission = await Permissions.query({ name: "camera"});

            const base64data = await Camera.getPhoto({
              quality: 80,
              allowEditing: true,
              resultType: CameraResultType.Base64
            });
            return { result: base64data };
        }
        catch (e) {
            return {success: false, stack: e};
        }
    }
```

in renderer.js

```
window.cap.getCameraPicture().then(base64data => {
                editorInstance.insertHtml( '<img src="data:image/jpeg;base64,' + base64data + '">' );
            }).catch(e => {
                console.debug("Unable to obtain picture: " + e, "app");
            })
```

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v12.13.0

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
We are not making any changes @capacitor/electron, you can use the community maintained platform.

Since you have already reported the issue in the community repository I'm closing this one.
https://github.com/capacitor-community/electron/issues/74

But the problem makes sense to me, plugins communicate the web part with the native part, if you set `contextIsolation` to true, the bridge can not communicate them anymore and plugins won't work. The electron platform will probably need to switch to `contextBridge` for the communication.
