### ISSUE TITLE
feat:add Tailwindcss 

### ISSUE THREAD

**Issue by rudyhadoux** [ionic-team/capacitor#3952]
### Description
Hi,

In an Ionic Angular (Capacitor) app, 'ng add @ngneat/tailwind' fails. Because of a bad default webpack configuration I think. It would be nice to be able to add it easily.

**Comment by jcesarmobile** [comment]
If `ng add` fails, you should report it to angular team or whoever handles that tooling, it's not related to capacitor, capacitor is framework agnostic, can be used with any framework or none at all.
Or if you think it's a problem on ionic angular template you can report it here https://github.com/ionic-team/starters/issues

**Comment by rudyhadoux** [comment]
Angular is a front-end framework too. 
It is better to be able to add a variety of css frameworks. 
If you think that CSS is not your problem or concern, your choice is bad.

**Comment by jcesarmobile** [comment]
I'm saying capacitor is framework agnostic, that means it doesn't care which one you use or if you don't use any.
If something framework related fails, it's not a capacitor problem.
Just saying you have reported the problem in the wrong repository, not that it's not a problem.

**Comment by rudyhadoux** [comment]
OK. I am french... I add a stater issue.

**Comment by rudyhadoux** [comment]
I have found that.
https://blog.andrewbrey.com/2020-07-06-using-tailwindcss-with-ionic-5-and-angular-10/

**Comment by rudyhadoux** [comment]
I got a wonderful reply for the starter option ...
Very cool....
