### ISSUE TITLE
bug: configure iosScheme to http not working

### ISSUE THREAD

**Issue by mikeyyyzhao** [ionic-team/capacitor#3954]
## Bug Report
When changing iosScheme to http, the simulator's origin is still capacitor://localhost. If I change iosScheme to ionic, the origin changes to ionic://localhost.

```
 "server": {
    "iosScheme": "http",
    "androidScheme": "http",
    "hostname": "localhost"
  },
```

I need this change for google auth since google's Authorized JavaScript origins only takes in http and https. I've read from other posts that changing iosScheme to https does not work and was wondering if changing it to http works but I need to change other configs?

**Comment by jcesarmobile** [comment]
WKWebView doesn't allow to use https nor http for serving local assets
