### ISSUE TITLE
bug: Unable to find file for attachment with url

### ISSUE THREAD

**Issue by SalahAdDin** [ionic-team/capacitor#3957]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/cli 2.4.4
  @capacitor/core 2.4.4
  @capacitor/ios 2.4.4
  @capacitor/android 2.4.4
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 8 Capacitor plugins for ios:
    @capacitor-community/fcm (1.0.8)
    @capacitor-community/firebase-analytics (0.2.0)
    @capacitor-community/http (0.2.1)
    @diachedelic/capacitor-background-geolocation (0.3.4)
    capacitor-firebase-auth (2.3.2)
    card.io.cordova.mobilesdk (2.1.0)
    com.darktalker.cordova.screenshot (0.1.6)
    cordova-plugin-inappbrowser (4.1.0)
[success] iOS looking great! 👌

```

### Platform(s)

- [x]  iOS

### Current Behavior
At clicking in the Local Notification, it does not do anything. Loggin it we find:
`{message: "Unable to make notification", errorMessage: "Unable to find file /tabs/package-details/413489549886035301 for attachment"}`

### Expected Behavior
At clicking on the Local Notification it must redirect us to the proper route in the view.

### Code Reproduction
```ts
const doLocalNotification = (notification: PushNotification) => {
  if (notification.title && notification.body) {
    const localNotification = {
      title: notification.title,
      body: notification.body,
      id: UUID_NUM(),
      attachments: notification.data.jobNum
        ? [
            {
              id: notification.id,
              url: `/tabs/package-details/${notification.data.jobNum}`,
            },
          ]
        : [],
    }
    localNotificationInstance.makeLocalNotification(localNotification)
  }
}
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context
This code was made thinking in solve [this](https://github.com/ionic-team/capacitor/discussions/3286#discussioncomment-134859) problem.

**Comment by jcesarmobile** [comment]
url should be a real url, but you are passing `/tabs/package-details/${notification.data.jobNum}`, which is a virtual url that doesn't exist, only your router understand, but not the native code
