### ISSUE TITLE
Selective API import

### ISSUE THREAD

**Issue by scriptPilot** [ionic-team/capacitor#396]
Hey guys, very promising project, I think about its integration in the new version of https://github.com/scriptPilot/app-framework. My question to the plugins / core ... is there a possibility only to include needed APIs? If I include all plugins the code will be bloated unnecessarily I assume.

**Comment by mlynch** [comment]
Yes and no. The web plugins should (in theory) be pulled out from your code if you're not using them, but the core plugins are baked into the native code. This probably adds a minuscule amount of compiled code

**Comment by scriptPilot** [comment]
@mlynch - Ok, thanks for the explanation.
