### ISSUE TITLE
[Question] Toast options

### ISSUE THREAD

**Issue by scriptPilot** [ionic-team/capacitor#397]
Dear team, in the docs, there is described an options argument for toasts. Wherer do I find allowed options documented?

https://capacitor.ionicframework.com/docs/apis/toast/

**Comment by janpio** [comment]
Looking at the current implementation there seems to be `text` and `durationType` (which can be `short` or `long`, latter being the default): 
https://github.com/ionic-team/capacitor/blob/04562432e531052e3f89187e25536c6b902ddb9e/android/capacitor/src/main/java/com/getcapacitor/plugin/Toast.java#L19
https://github.com/ionic-team/capacitor/blob/912cf7522f060289eaf6f4913f3b4924161647aa/ios/Capacitor/Capacitor/Plugins/Toast.swift#L9-L13

**Comment by scriptPilot** [comment]
Thanks a lot. But anyway, in my opinion, all options for the API should be documented as well. Or what do you think?

**Comment by mlynch** [comment]
Toast is served: https://capacitor.ionicframework.com/docs/apis/toast/
