### ISSUE TITLE
bug: enum in native plugins definition break tests (jest)

### ISSUE THREAD

**Issue by distante** [ionic-team/capacitor#3972]
### Capacitor Version
```
  @capacitor/ios not installed
  @capacitor/cli 2.4.5
  @capacitor/android 2.4.5
  @capacitor/core 2.4.5
  @capacitor/electron not installed```
```
### Current Behavior
Plugin definitions with enums can not be mapped to unit tests

### Expected Behavior
`enum` plugin definitions should not depend of any global variables or functions to work in unit tests.

### Code Reproduction
You can install [this plugin](https://github.com/distante/capacitor-plugin-headset-detection/) (work in progress!) using this commit: `97f11851da876be494fcbc274a89d9cc73fe944a` 

That commit contains enums definitions inside the `definitions.ts` file and also contains a `Web` implementation.

If you try to unit test a component or service that uses the defined `enums` it break with this error:

>  ReferenceError: capacitorExports is not defined

### Other Technical Details
One can manually re export `capacitorExports` using this in a jest environment: 
```
import * as capacitorExports from '@capacitor/core/dist/esm';
global['capacitorExports'] = capacitorExports;
``` 
but that just hides the first error and the enum declarations are not available, error like `can not read Value of undefined` will happen for a enum usage of  `MyEnum.Value`

`npm --version` output: 6.14.8

`node --version` output: v12.13.0

### Additional Context
A complete workaround is to declare the enums in an external file (see `[989a173af812c74a5bcf8eb02d5d5e9336bf4f73](https://github.com/distante/capacitor-plugin-headset-detection/commit/989a173af812c74a5bcf8eb02d5d5e9336bf4f73)`)  but then you can not import from `capacitor-plugin` but you have to use something like `capacitor-plugin\dist\esm\external-file` (which sometimes is not available right away as import autocomplete.

## IMPORTANT!
Even with the workaround detailed, importing web versions of the plugin like the documentation says, break jests in the exact same way.

**Comment by Elvincth** [comment]
Same, after exporting enum can't access it through import

**Comment by Elvincth** [comment]
`export enum SensorManager {
  SENSOR_DELAY_FASTEST = 0, //get sensor data as fast as possible
  SENSOR_DELAY_GAME = 1, //rate suitable for games
  SENSOR_DELAY_UI = 2, //rate suitable for the user interface
  SENSOR_DELAY_NORMAL = 3, //rate (default) suitable for screen orientation changes
}`

`      import { Plugins } from "@capacitor/core";

const {SensorManager } = Plugins;
console.log(SensorManager); //Get undefined
`

**Comment by Elvincth** [comment]
Same here, after exporting enum in definitions.ts and import it will get undefined

```
export enum SensorManager {
  SENSOR_DELAY_FASTEST = 0, //get sensor data as fast as possible
  SENSOR_DELAY_GAME = 1, //rate suitable for games
  SENSOR_DELAY_UI = 2, //rate suitable for the user interface
  SENSOR_DELAY_NORMAL = 3, //rate (default) suitable for screen orientation changes
}

import { Plugins } from "@capacitor/core";

const {SensorManager } = Plugins;
console.log(SensorManager); //Get undefined

```

**Comment by pwespi** [comment]
Changing the main entry point of the plugin to a commonjs output should fix this problem, see https://github.com/capacitor-community/bluetooth-le/pull/14 or https://github.com/ionic-team/create-capacitor-plugin/pull/46.

**Comment by jcesarmobile** [comment]
should be fixed on capacitor 3 plugins after the changes made on the generator
