### ISSUE TITLE
Consider deprecating ios/android configuration objects

### ISSUE THREAD

**Issue by imhoffd** [ionic-team/capacitor#3978]
With the onset of dynamic configuration files, we should discuss deprecating ios/android specific objects in the Capacitor configuration.

Today, values such as `userAgent` are split between a "base" key and platform-specific key. App developers are expected to configure overrides in the platform-specific key. But, working with nested objects and long configuration files can get unwieldy, and the same configuration can get spread out to the point where context is lost.

```typescript
const config: CapacitorConfig = {
  userAgent: "some general string",
  .. other values
  ios: {
    userAgent: "some string for ios",
    ... other values
  },
  android: {
    userAgent: "some string for android",
  },
};
```

It would be easier to maintain and better for users if we didn't have these objects, and instead offered a way to select values based upon platform, e.g. with `Platform.select()` (re-implemented for CLI): https://github.com/ionic-team/capacitor/issues/3977

Example using `Platform.select()`:

```typescript
import { Platform } from '@capacitor/cli';

const config: CapacitorConfig = {
  userAgent: Platform.select({
    ios: "some string for ios",
    android: "some string for android",
    default: "some general string",
  }),
  ... other values
};
```

**Comment by jcesarmobile** [comment]
But you need to have in mind that not everybody is going to migrate to the dynamic configuration files

**Comment by dwieeb** [comment]
Yeah, this can be at a later point. I hope we see JSON config file usage dwindle during 3.x, JS/TS is much better to work with.

**Comment by dwieeb** [comment]
We also need to think about what to do with truly platform-specific values, such as `cordovaSwiftVersion`.

**Comment by jcesarmobile** [comment]
closing as won't do, there hasn't been a lot of interest on the feature after 3 years and a lot of people is still using json files
