### ISSUE TITLE
[QUESTION] CAP Init

### ISSUE THREAD

**Issue by BKHines** [ionic-team/capacitor#398]
What exactly does this command do: "npx cap init [appName] [appId]"?  The reason I ask is because I have built an app where the app id and name are not determined until I create a build.  

My config.xml looks like this:

<widget defaultLocale="en-US" id="com.eventhyped.appidcomesfromconfiguration" version="1.0.6" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:vs="http://schemas.microsoft.com/appx/2014/htmlapps">
    <name>App Name Comes From Configuration</name>
    ...

Since I'm using Visual Studio 2017 at the moment, I get the app name and id via a configuration name.  Then I run a gulp task that takes the configuration name and fills in the appropriate pieces of the config.  "com.eventhyped.appidcomesfromconfiguration" becomes "com.eventhyped.cincychristmas".  Would the cap init command still work if I initialized "com.eventhyped.appidcomesfromconfiguration" and then changed it when I was building for the stores?  Is that command simply to initialize for development purposes or does that initialize it for the app to use capacitor?

**Comment by mlynch** [comment]
This command creates the `capacitor.config.json` file with the values you provide, which Capacitor then uses when creating new app projects. It does not stay in sync, so if you create the app project and want to change/customize an ID, you have full control over that

**Comment by BKHines** [comment]
Perfect.  Thanks so much for the quick reply.  I appreciate it.
