### ISSUE TITLE
bug: @capacitor/android@2.4.5 - Android build error due to gradle v3.6.1

### ISSUE THREAD

**Issue by joboyx** [ionic-team/capacitor#3982]
### Capacitor Version
```
$ ionic cap -v
6.12.13
```

### Platform(s)
Android

### Current Behavior
- When creating new android project from scratch with `ionic cap add android`
- then open Android Studio
- then build the app
- Gradle error occurs as shown below

![image](https://user-images.githubusercontent.com/920888/102914287-fc27ba80-44ba-11eb-8385-f457fad4c83e.png)

### Expected Behavior
- android app build successfuly in Android Studio

### Code Reproduction
- create an ionic app
- When creating new android project from scratch with `ionic cap add android`
- then open Android Studio
- then build the app
- Gradle error occurs as shown below

![image](https://user-images.githubusercontent.com/920888/102914287-fc27ba80-44ba-11eb-8385-f457fad4c83e.png)

### Other Technical Details

`npm --version` output: 7.0.8

`node --version` output: v15.2.1

`pod --version` output (iOS issues only): NA

### Additional Context

ℹ️ WORKAROUND
I found a workaround and possible fix once this is applied to template or boilerplate code.

To fix the issue manually update the following files by updating `com.android.tools.build:gradle:3.6.1` to `com.android.tools.build:gradle:3.+`. I also tried using `3.6.4` and that also fixes the issue.

- android/build.gradle
![image](https://user-images.githubusercontent.com/920888/102914678-a1db2980-44bb-11eb-835a-d682948f1270.png)
- ../node_modules/@capacitor/android/capacitor/build.gradle (npm: @capacitor/android@2.4.5)
![image](https://user-images.githubusercontent.com/920888/102915015-11e9af80-44bc-11eb-946e-ca5527bc4eb2.png)
- android/capacitor-cordova-android-plugins/build.gradle
![image](https://user-images.githubusercontent.com/920888/102914752-bcad9e00-44bb-11eb-855c-23791b13d5f8.png)

Doing the updates above will fix the build error and you would be able to launch the Android app from Android Studio.

![image](https://user-images.githubusercontent.com/920888/102915314-8ae90700-44bc-11eb-98ad-b1f1852360a1.png)

**Comment by jcesarmobile** [comment]
closing as won't fix, capacitor 3 is now out with newer gradle versions
