### ISSUE TITLE
Add configuration option for iOS target(s)

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3993]
We can add a configuration option which could use the configured target/scheme in `sync` and `run`.

**Comment by MortenGregersen** [comment]
This is not always so simple. We have 8 targets (variations) of the same app.

**Comment by dwieeb** [comment]
I think the best we can do is add a configuration option. When combined with `capacitor.config.ts` files (see https://capacitorjs.com/docs/v3/config), you can use an environment variable to switch targets.

**Comment by dwieeb** [comment]
@MortenGregersen Related: please see https://github.com/ionic-team/capacitor/pull/4002 which moves `public` into the target directory. `sync` should take the configured target into account when copying web assets into place

**Comment by MortenGregersen** [comment]
> I think the best we can do is add a configuration option. When combined with `capacitor.config.ts` files (see https://capacitorjs.com/docs/v3/config), you can use an environment variable to switch targets.

Yes, with a dynamic config file this would work. This is awesome!

> @MortenGregersen Related: please see #4002 which moves `public` into the target directory. `sync` could use the configured target when copying web assets into place

As I see it, the `public` directory is moved a level up. How does this relate to the configured target?

**Comment by MortenGregersen** [comment]
> I think the best we can do is add a configuration option. When combined with `capacitor.config.ts` files (see https://capacitorjs.com/docs/v3/config), you can use an environment variable to switch targets.

Yes, with a dynamic config file this would work. This is awesome!

> @MortenGregersen Related: please see #4002 which moves `public` into the target directory. `sync` could use the configured target when copying web assets into place

As I see it, the `public` directory is moved a level up. How does this relate to the configured target? @dwieeb

**Comment by dwieeb** [comment]
> Yes, with a dynamic config file this would work. This is awesome!

Great to hear! 😊

After some investigation, the configuration option will likely be a scheme (aka Xcode build configuration), not a target. This is required for 'run' to invoke 'xcodebuild', and we can use it to discover the target, because every scheme has an associated target (usually by the same name). 

> How does this relate to the configured target?

Only in that it organizes the project folder a bit. Not entirely related.
