### ISSUE TITLE
Convert HTML Components to Native Components?

### ISSUE THREAD

**Issue by RiyadKhalifeh** [ionic-team/capacitor#400]
Hello Ionic team
Does capacitor convert HTML components to Native components same as what ReactNative does, or HTML components still HTML and application run above WebView?
Thanks ^-^

**Comment by mlynch** [comment]
No and yes. No, in that most of your app will be built with cross-platform web content, which you can then use with Capacitor to deploy to Electron and PWA with the same code.

Yes, in that our roadmap has native UI shell as an option, letting you use components like a native menu through HTML tags that will fall back to web friendly options in Electron/PWA (but this isn't ready yet).

We're 100% web focused here.

**Comment by arihantdaga** [comment]
@mlynch  It's still running above webview, like ionic ? Right ?

**Comment by jcesarmobile** [comment]
Yes, it uses WKWebView on iOS and, and the WebView component on Android (which uses System WebView in Android 5 and 6 and Chrome on Android 7+)
