### ISSUE TITLE
bug: WebAssembly is not available after ios build - Can't find variable: WebAssembly

### ISSUE THREAD

**Issue by nickewansmith** [ionic-team/capacitor#4006]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/cli 2.4.5
  @capacitor/core 2.4.5
  @capacitor/android 2.4.5
  @capacitor/ios 2.4.5
  @capacitor/electron not installed

```

### Platform(s)

ios

### Current Behavior

When using argon2-browser npm package in the ios app build, on execution of `argon2.hash(...` I receive error as Web
Assembly is not defined. Specifically `Can't find variable: WebAssembly`. The `WebAssembly` variable should be available globally and on the `window` object, but upon inspecting the app with xcode emulation and safari dev tools, `WebAssembly` is also not defined.

### Expected Behavior

I expect that the WebAssembly variable be available in the mobile applications built for ios and andriod

### Code Reproduction

https://github.com/nickewansmith/ionic-capacitor-webassembly-bug

### Other Technical Details

`npm --version` output:  6.14.9

`node --version` output: v14.15.1

`pod --version` output (iOS issues only): 1.10.0

**Comment by jcesarmobile** [comment]
I can't reproduce.
If testing on simulators, have in mind that due to a simulator bug, it only works on iOS 14+ simulators.
On real devices it should work on iOS 11+.
I don't have any iOS 11-12 to test anymore, but works fine on my iOS 13 and 14 devices.

**Comment by aleacevedo** [comment]
Did u make it works?

**Comment by AndreasGassmann** [comment]
I am having the same issue on my iPad, which runs iOS 16.1 beta. The same build from TestFlight works on my iPhone with iOS 15. Was there a change in iOS 16 that could affect this?

Was this issue ever reproduced and/or fixed? Depending on the fix, maybe it is somehow related.
