### ISSUE TITLE
bug: Getting a white screen when building on Android (when including AWS Amplify framework)

### ISSUE THREAD

**Issue by HamzaLJ** [ionic-team/capacitor#4008]
## Bug Report

After updating to Angular 10, I tried to build the app, the build stops at the following stage : 

`Generating ES5 bundles for differential loading...` 

I then, modified the target on **tsconfig.json** to disable `differential loading` by going from `es2015` to `es5` : 

`"target": "es2015"`

It worked! But, when building for **Android** opening the app on the simulator/device, I got a blank white screen.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/core 2.4.5
  @capacitor/android 2.4.5
  @capacitor/cli 2.4.5
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Showing a white screen

### Expected Behavior

It should show the app content instead of the white screen while building for Android.

### Code Reproduction

You may checkout the Github repo to reproduce the problem : 

[https://github.com/HamzaLJ/awsApp](https://github.com/HamzaLJ/awsApp)

### Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: v12.16.3

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dwieeb** [comment]
If you open the Chrome DevTools for the Web View, what errors do you see?

**Comment by jcesarmobile** [comment]
I can't reproduce on the sample app. I had to install `aws-amplify` package because it wasn't included in the sample app, tried with latest and with 3.3.13 as I think was latest when the issue was created.

White screens are usually caused by javascript errors, you can check on Chrome DevTools.
