### ISSUE TITLE
bug: Plugins Not Being Added to Android

### ISSUE THREAD

**Issue by swernimo** [ionic-team/capacitor#4012]
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/cli 2.4.5
  @capacitor/android 2.4.5
  @capacitor/core 2.4.5
  @capacitor/ios 2.4.5
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    @capacitor-community/date-picker (0.2.3)
[success] iOS looking great! 👌

### Platform(s)
Android

### Current Behavior
When I install a new plugin via npm (npm i @community-capacitor/date-picker for this example) the plugin doesn't appear in android. I have to remove android platform and readd it again before the plugin appears in Android Studio.

Here is the Android Studio for my project after adding a new project.
![Screen Shot 2021-01-04 at 3 00 53 PM](https://user-images.githubusercontent.com/11137058/103583814-a6c9b100-4e9d-11eb-9b68-e57d0579c5c1.png)

### Expected Behavior
I expect the plugin to appear in Android without having to remove and readd the platform.

### Code Reproduction
Create a new ionic capacitor side menu app. Add Android & iOS platforms. Add a new plugin (npm i @capacitor-community/date-picker). Snyc both platforms with npx cap sync. Then npx cap open android. The new plugin will appear in iOS but not Android. 

### Other Technical Details
VS Code 1.52.1 on a Mac with 11.1 Big Sur. Android Studio version: 4.1.1

Output from npx cap sync
![Screen Shot 2021-01-04 at 3 10 36 PM](https://user-images.githubusercontent.com/11137058/103584678-03799b80-4e9f-11eb-9cb1-f4b19b8b4a7c.png)

I've also tried ionic cap build android, but the results are the same.

`npm --version` output: 6.14.9

`node --version` output: 14.15.3

**Comment by dwieeb** [comment]
@swernimo Try clicking the "Sync Project with Gradle Files" button:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/236501/103586344-bd6e0900-4e99-11eb-9357-526e9fea5860.png">

**Comment by swernimo** [comment]
That worked. Will I have to do that every time a plugin is added or removed from the project?

**Comment by dwieeb** [comment]
Yes. This is because Capacitor changes the underlying gradle files but Android Studio doesn't know about it unless you click that button.

Unfortunately there's no way to trigger a "sync" to update the UI from the command-line (that I'm aware of). Since this is an Android Studio issue, I'll close this.
