### ISSUE TITLE
Capacitor Keyboard Plugin's pod file not changing to use correct deployment target

### ISSUE THREAD

**Issue by JoshuaRileyDev** [ionic-team/capacitor#4018]
Hello, I'm having issues adding the Capacitor Keyboard plugin to my project, I get this error:

[!] CocoaPods could not find compatible versions for pod "CapacitorKeyboard":
  In Podfile:
    CapacitorKeyboard (from `../../node_modules/@capacitor/keyboard`)

Specs satisfying the `CapacitorKeyboard (from `../../node_modules/@capacitor/keyboard`)` dependency were found, but they required a higher minimum deployment target.

I'm on Latest Capacitor

Doctor:

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.4.5
  @capacitor/core 2.4.5
  @capacitor/ios 2.4.5
  @capacitor/electron not installed

  Found 1 Capacitor plugin for ios:
    @capacitor/keyboard (0.3.1)
[success] iOS looking great! 👌

**Comment by dwieeb** [comment]
`@capacitor/keyboard` (and all the plugins from [this repo](https://github.com/ionic-team/capacitor-plugins/)) are for Capacitor 3. You're using Capacitor 2. What docs are you following?

**Comment by JoshuaRileyDev** [comment]
Ah ok, I'm following the default docs on Capacitor's website which seems like it's v2, all I'm trying to do is add the Accessory Bar so I can have the "Done" button appear, I'm using normal HTML, JS with no bundler

**Comment by dwieeb** [comment]
I think `window.Capacitor.Keyboard.setAccessoryBarVisible({isVisible: true});` should work (untested)

**Comment by JoshuaRileyDev** [comment]
Sadly that didn't work 👎

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by JoshuaRileyDev** [comment]
Why does it have to be so simple 😂 thanks @jcesarmobile that fixed it!

**Comment by dwieeb** [comment]
oops, I missed a word 😂
