### ISSUE TITLE
feat: Add telemetry to Capacitor 3

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/capacitor#4020]
## Overview

This issue is to track changes to allow for telemetry in the Capacitor CLI.
We will be introducing an opt-in strategy for gathering events.

### Telemetry Command
We will need to introduce a telemetry command to allow for individuals to opt-in or opt-out of analytics at any point in time. This would affect a global config.
- `npx cap telemetry off` - turn telemetry off
- `npx cap telemetry` - provide status of telemetry as to whether it is on or off
- `npx cap telemetry on` - turn telemetry on

### Init questions
We will ask if they would like to opt-in to telemetry on the first run of `npx cap init` on a machine. Subsequent executions of `cap init` will not ask if they want to use telemetry and will adhere to their previous answer (Question B). If they DO NOT opt-in to telemetry we will not collection framework or any events, but we will send an event that they did opt-out. This event should only provide the Capacitor machine ID and the fact that they opted-out.

Question A: **What framework are you using for this application?**
Answers: 
- React
- React / Next
- Angular
- Vue
- Other (*Is it possible to allow an open text entry for this*)

Question B: **Would you like to help improve Capacitor by sharing anonymous usage data? You can read more about what is being collected and why here: [https://capacitorjs.com/telemetry](https://capacitorjs.com/telemetry). You can change your decision on this later by running the `telemetry` command.**
Answers: (Y/n)

Subsequent question C: **How long have you worked on this application?**
Answers:
- This is a new application
- 0-3 months
- 3-6 months
- More than 6 months

### Event Data
The following data will need to be captured when a command is executed if telemetry is turned on.

- Name of command (`add`, `list`, `open`, etc)
- Timestamp
- Capacitor machine ID: This is an anonymous UUID that is stored in a global config.
- Your operating system (Mac, Linux, Windows) and its version.
- Node Version
- @capacitor/core Version
- @capacitor/cli Version
- @capacitor/android Version
- @capacitor/ios Version
- Name and Version of Official Capacitor Plugins installed in your project

**Comment by jcesarmobile** [comment]
telemetry was partially implemented, if we want to track more things a new issue can be created providing more information
