### ISSUE TITLE
Feature request: .obb file generator CLI

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/capacitor#403]
Hello Ionic team,

As we aware, Play Store's apk file size limit is 100MB. Any app exceeding 100MB should come with .obb files which are expansion files of core APK file. 
Is it possible for you guys to make Capacitor build CLI automatically detect apk file's size and generate .obb files if apk file is larger than 100MB? 
That will make the job a lot easier!  
Cordova's CLI doesn't care about apk's file size but you can't really use an apk file larger than 100MB anywhere. 

Thanks in advance.

**Comment by jamesharvey2** [comment]
Actually, I think this feature should be included in capacitor CLI.
On Cordova, you can follow these steps to integrate .obb expansion files:
https://iphonedevlog.wordpress.com/2014/12/12/adding-an-android-apk-expansion-file-to-a-cordova-project/

If Capacitor comes with a better solution than this, it would be appreciated... 
Some offline apps are several hundred megabytes.

**Comment by janpio** [comment]
Capacitor's CLI doesn't build your app. You do that yourself. 
So you can build it whatever way you want with the native tooling.

**Comment by jcesarmobile** [comment]
yeah, I agree with janpio.

But it looks like we might need to add some code to handle the obb files on the apps, all what the xapkreader plugin does.

**Comment by jamesharvey2** [comment]
Well.. I don't know if capacitor has build command or not but on Cordova, `ionic cordova build android --release --prod` will not care about APK's size and just build apk in any size although you can't use an apk file beyond 100MB in size. 
What if `capacitor build android --release --prod` command can detect apk file size and create .obb files accordingly?
I don't know.. I though this will be useful.

**Comment by jcesarmobile** [comment]
Capacitor apps are built from Android Studio, not with a CLI command.

Also, I don't think creating an obb file with random files would be a good idea, it's something the user should create based on what he wants on the extension

**Comment by jamesharvey2** [comment]
hmm I see. It works with Android Studio. 

Well maybe locate "expansion" folder to create .obb files based on files in that folder? 

Anyways, thanks

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by aabdolla** [comment]
Something to solve the over 100mb problem would be nice. The most popular plugin for doing this is a little funky and I have never got it to work.
