### ISSUE TITLE
bug: Removing location from Android manifest still loads the permission in app

### ISSUE THREAD

**Issue by modemlooper** [ionic-team/capacitor#4038]
## Bug Report

I remove these from the Manefest but they are still being loaded by capacitor. Google will delete apps targeted to children if location services are enabled. Further more, why are these being loaded and ignored by the manifest?

```
<!- Geolocation API ->
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-feature android:name="android.hardware.location.gps" />
```

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/cli 2.4.5
  @capacitor/android 2.4.5
  @capacitor/core 2.4.5
  @capacitor/ios 2.4.5
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 4 Capacitor plugins for ios:
    cordova-plugin-inapppurchase (1.2.0)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-streaming-media (2.3.0)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌

```
PASTE OUTPUT HERE
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by modemlooper** [comment]
The error in Play when I try to upload the app

<img width="849" alt="error" src="https://user-images.githubusercontent.com/867885/104106293-8a48c280-5269-11eb-839f-b4321826dbd8.png">

**Comment by dwieeb** [comment]
This was an architecture issue of Capacitor which we are addressing for v3. We are very close to a public beta. The [v3 docs](https://capacitorjs.com/docs/v3) should be ready if you want to give it a try. If you've put significant work into your app, there's an [upgrade guide](https://capacitorjs.com/docs/v3/updating/3-0) as well. I would love to hear your feedback either in [this discussion](https://github.com/ionic-team/capacitor/discussions/3994) or you can just reply to this issue. Thanks!

**Comment by modemlooper** [comment]
Google sent a notice they were deleting Apps in 90 days so got a bit of time to fix, but can't even upload a new build of app until this issue is resolved, guess I'll try using V3 to update it.

**Comment by dwieeb** [comment]
Because the Geolocation plugin (and all other plugins) are bundled into Capacitor core, we can't fix this without breaking every Capacitor app. The migration to v3 may be the only solution. 

Are you by chance using any third-party Capacitor (not Cordova) plugins?

**Comment by modemlooper** [comment]
No other plugins, I try to use web API's as much as possible.

**Comment by thomasvidas** [comment]
FYI @modemlooper the first beta of Capacitor 3 was released yesterday. You can install it with `npm i @capacitor/core@next`

There is an upgrade guide [here](https://capacitorjs.com/docs/v3/updating/3-0). None of the official plugins are bundled into the core package now (including geolocation) so you should be able to start migrating to v3 and not get this flag from Google

**Comment by modemlooper** [comment]
Yup, going to update app and do testing. 🤗

**Comment by modemlooper** [comment]
So, I went through the whole process of updating to Cap3 and I'm still getting this from google:

`You must remove the request for location permissions from your app if your target audience only includes children under 13`

What could be still asking for this permission?

**Comment by jcesarmobile** [comment]
I've created an app on Google Play targeted for children under 13, submitted a Capacitor 2 app and I got the error.
Then submitted the same app with Capacitor 3 and I didn't get the error.
Then went back to Capacitor 2, but removing the geolocation permissions from `AndroidManifest.xml` and I didn't get the error.
I've also tried installing the 4 plugins your capacitor doctor output shows and didn't get the error.

You say that you have removed the permissions from `AndroidManifest.xml`, but that Capacitor adds them back.
Capacitor don't add the geolocation permissions, they are included in the app template on `npx cap add android`, but if you remove them, Capacitor don't add them back (unless you remove android folder and run `npx cap add android` again).

If you open the `AndroidManifest.xml`, at the bottom there is a "Merged Manifest" tab, can you click it and check what is adding the permissions?
