### ISSUE TITLE
Think about `pod repo update`

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#4049]
`pod repo update` needs to run periodically, which usually CocoaPods users do themselves(?) but Capacitor abstracts the usage of CocoaPods, so it's unclear that this needs to happen.

I believe the CLI used to have a note about this, but it was removed.
The v2 docs have a note about this upon project creation, but that was removed in hopes of addressing it in another way.

Issues:
- https://github.com/ionic-team/capacitor/issues/730
- https://github.com/ionic-team/capacitor-plugins/issues/181

**Comment by jcesarmobile** [comment]
Since CocoaPods 1.8, the default registry is the online registry that don't need `pod repo update` anymore (supposedly)
but users that were using older versions might need some additional steps to use the online registry apart from updating CocoaPods

**Comment by dwieeb** [comment]
Nice! I'll include that info in the upgrade guide. 👍
