### ISSUE TITLE
Bug: When entering a new page, the  bottom of button will have a bouncing effect from the bottom, Only ios

### ISSUE THREAD

**Issue by PeiJueChen** [ionic-team/capacitor#4052]
Bug: When entering a new page, the  bottom of button will have a bouncing effect from the bottom, Only ios... Please help....

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
