### ISSUE TITLE
bug: Custom capacitor plugin can't match app's iOS deployment target due to Capacitor target discrepancy

### ISSUE THREAD

**Issue by Cloov** [ionic-team/capacitor#4071]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.4.6
  @capacitor/core 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/electron not installed

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

```

### Platform(s)
iOS

### Current Behavior
Creating a custom Capacitor plugin using `npm init @capacitor/plugin`, and attempting to install it in a brand new Ionic-angular-Capacitor iOS project, results in a discrepancy between iOS minimum deployment targets 12.0 and 11.0, seemingly because the plugin uses iOS 12 Capacitor pods, and the `npx cap sync` command in the importing Capacitor app forces the podfile to work for iOS 11, and so the podfile sync fails because it contains my custom plugin, which I had to deploy for iOS 12.

### Code Reproduction
I'm creating a native plugin, that currently has no requirement for a particular deployment target. Since it looks as though my newly created Capacitor app has a deployment target of iOS 11 (because that's what appears in _ios/App/Podfile_), I decided I'd work towards that same target in my custom Capacitor plugin. However, when I create the Capacitor plugin and set its deployment target 11, and then try to build, the Plugin Framework target in Xcode yields this build error: 'Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0.

Given that I'm not fussy about the 11.0 target, I decided then to up my plugin's deployment target to 12 also. That allowed it to build. But then, when I try to npm-install that plugin and do an `npx cap sync` in my importing project, the sync fails because Cocoapods explains that my deployment target is 11.0 and I'm trying to import something with a minimum target of 12.0. I changed the iOS platform directive in the Podfile to 12.0, but each time I run `npx cap sync`, it looks like this is being changed back to 11.0.

Is there a way I can control the iOS version that gets fed into `npx cap sync`?

`npm --version` output: 6.13.4
`node --version` output: v12.14.1
`pod --version` output: 1.10.0

**Comment by jcesarmobile** [comment]
`npm init @capacitor/plugin` is for Capacitor 3 plugins (still in beta stage)

for 2.x plugins use `npx @capacitor/cli plugin:generate`

https://capacitorjs.com/docs/plugins/creating-plugins

**Comment by Cloov** [comment]
@jcesarmobile thanks. I see that using this method still results in typings and a web plugin being created, but they don't seem to be carried through with the plugin. My node modules folder for the plugin, in the destination project, only contains the ios and android directories. Is it possible to configure the plugin to carry over the typings too?
