### ISSUE TITLE
bug: indexeddb not available in iOS 12.4

### ISSUE THREAD

**Issue by glu000** [ionic-team/capacitor#4074]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.3
  @capacitor/android 2.4.5
  @capacitor/ios 2.4.5
  @capacitor/core 2.4.3
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 3 Capacitor plugins for ios:
    cordova-plugin-screen-orientation (3.0.2)
    cordova-sqlite-storage (5.1.0)
    es6-promise-plugin (4.2.2)
```

### Platform(s)
iOS

### Current Behavior
Following Error-Message is thrown to XCode when trying to use indexeddb in iOS 12.4

⚡️  [error] - ERROR Error: Uncaught (in promise): Error: No available storage method found.
capacitor://localhost/main-es2015.ef70f599b96a0ee2b184.js:1:377524
onInvoke@capacitor://localhost/main-es2015.ef70f599b96a0ee2b184.js:1:273959
run@capacitor://localhost/polyfills-es2015.91389ecfa80f1063947d.js:1:2112
capacitor://localhost/polyfills-es2015.91389ecfa80f1063947d.js:1:13041
onInvokeTask@capacitor://localhost/main-es2015.ef70f599b96a0ee2b184.js:1:273852
runTask@capacitor://localhost/polyfills-es2015.91389ecfa80f1063947d.js:1:2731
m@capacitor://localhost/polyfills-es2015.91389ecfa80f1063947d.js:1:9313
promiseReactionJob@[native code]

### Expected Behavior
indexeddb should work with iOS 12.4

### Code Reproduction

app.module.ts

@NgModule, imports section:

    IonicStorageModule.forRoot({
      name: '_ralph',
      driverOrder: ['indexeddb']
    }),

### Other Technical Details

`npm --version` output: 7.0.8

`node --version` output: V15.1.0

`pod --version` output (iOS issues only): 1.10.0

**Comment by jcesarmobile** [comment]
I have no iOS 12.4 device to test, but `window.indexedDB` is available on both a real iOS 13.6.1 and iOS 12.2 simulator.

As far as I remember, there were some `indexedDB` related issues on some iOS 12 versions. They were fixed on iOS 13, but nothing we can do about it on Capacitor. If `indexedDB` is crucial for your app, you'll have to target iOS 13+.
