### ISSUE TITLE
feat: Dark Mode & WebRTC

### ISSUE THREAD

**Issue by BroadBrander** [ionic-team/capacitor#4086]
## Feature Request
1. Add support for dark mode.
2. Add webrtc support to access media devices from html instead of opening another native app.

### Description
1. Dark mode is a must have thing nowadays. But Capacitor 2 doesn’t support the preferred color scheme media query so implementation of dark mode is a little hard. Adding this little feature will make developers life a little easier 😅
(`
@media (prefers-color-scheme: dark) {}
`)

2. I have tried to implement WebRTC in Capacitor 2 (Android) but wasn’t able to. Adding this to Capacitor 3 will help a lot to implement better and custom in-app experience. 

### Platform(s)
Android 
IOS

**Comment by dwieeb** [comment]
@BroadBrander 

1. Capacitor definitely supports the `prefers-color-scheme` query. If it doesn't, open a bug report with a reproduction.
2. WebRTC is being discussed here: https://github.com/capacitor-community/proposals/issues/11

**Comment by BroadBrander** [comment]
Then it must be a bug because prefers-color-scheme is always light mode. 

Capacitor version 2.4.6 (Fresh project.)

**Device:**
Samsung OneUI 2 (Android 10)

```js
if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
    console.log('dark');
} else if(window.matchMedia('(prefers-color-scheme: light)').matches) {
    console.log('light');
} // it is always light
```

**Comment by BroadBrander** [comment]
Then it must be a bug because prefers-color-scheme is always light mode.

Capacitor version 2.4.6 (Fresh project.)
Edit: Same problem on Capacitor 3 beta.

Device:
Samsung OneUI 2 (Android 10)

```js
if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
    console.log('dark');
} else if(window.matchMedia('(prefers-color-scheme: light)').matches) {
    console.log('light');
} // it is always light
```
