### ISSUE TITLE
app is not opening in emulator

### ISSUE THREAD

**Issue by mu250234** [ionic-team/capacitor#411]
I’ve initiated capacitor to my ionic project. and run the npx cap open android, it opens the project in android studio then I run the app. Whenever I run the app, the emulator opens but the app doesn’t run. Is there something else I should be doing/have installed in order for the emulator to load the app?

i did,
npm remove --save @capacitor/core @capacitor/cli
npm install --save @capacitor/core @capacitor/cli
ionic build --prod
npx cap copy
npx cap open android

**Comment by mlynch** [comment]
Sorry this isn't enough information to go on. If you have a stack trace or something else we can debug.

In the meantime, try restarting or creating a new emulator.

**Comment by janpio** [comment]
Can you create a new native app in Android Studio (choose any in the wizard and just click Next until you get to the IDE) and run it in the emulator?

**Comment by mu250234** [comment]
How to get stack trace , I mean command to get it
