### ISSUE TITLE
Error on npx cap update

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#412]
<img width="1719" alt="screenshot 2018-03-29 09 05 48" src="https://user-images.githubusercontent.com/11214/38093392-6dc22b98-3330-11e8-9143-7b5d540cbb57.png">

**Comment by mlynch** [comment]
I can't reproduce this, I'm thinking it's when a plugin doesn't have the `ios` folder provided or checked in. Not a high priority issue at all

**Comment by jcesarmobile** [comment]
Closing as you can't reproduce it and nobody else has seen this issue.
