### ISSUE TITLE
Pollfish plugin for Ionic

### ISSUE THREAD

**Issue by khaledov** [ionic-team/capacitor#4129]
Migrate from  <a href="https://github.com/pollfish" target="_blank">Cordova-Plugin-Pollfish</a> to  **Capacitor**

**Comment by jcesarmobile** [comment]
We are not adding more plugins at the moment, you can create a proposal on the community plugin proposals repository
https://github.com/capacitor-community/proposals

Or you can also ask to pollfish, I guess they would like to own such plugin.
