### ISSUE TITLE
bug: No such module 'Capacitor' for second target on ios bundling (v3)

### ISSUE THREAD

**Issue by mburger81** [ionic-team/capacitor#4132]
## Bug Report
We have to targets configured in our ios configuration, mainly when we bundle our second target which is not the default we run into this already known error

![image](https://user-images.githubusercontent.com/3778892/106293096-e2159080-624d-11eb-982e-94debbd9ab83.png)

Sometimes it is also happening on our first target but normally not. If we open, clean, polish or recreate the ios structure from scratch sometimes we can get it work. But today we have tried so many times without success.

Not sure if this is coming from v3 or we have this already before, because we used only android on v2, after we have testet v3 which works like a charm on android, we decided some days ago to go also for the ios platform.

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.1
  @capacitor/core: 3.0.0-beta.1
  @capacitor/android: 3.0.0-beta.1
  @capacitor/ios: 3.0.0-beta.1


[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
ios

### Other Technical Details

`npm --version` output: 6.14.11

`node --version` output: v14.11.0

`pod --version` output (iOS issues only): 1.8.4

**Comment by jcesarmobile** [comment]
how does your Podfile look like?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by mburger81** [comment]
@jcesarmobile  Sorry I saw this only now, anytime we are syncing the project after we have to recreate the second target

That's our Podfile, which is default and not changed by us.

```
platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

```

**Comment by mburger81** [comment]
It seems adding this
```
target 'EV' do
  capacitor_pods
  # Add your Pods here
end
```
and then also run `npx cap sync ios` is resolving the issue?

**Comment by jcesarmobile** [comment]
yeah, if you add a new target in the project you also have to add it in the Podfile
