### ISSUE TITLE
feat: Skip user confirmation while using npx cap init

### ISSUE THREAD

**Issue by camilacanhete** [ionic-team/capacitor#4143]
### Description
```npx cap init``` command asks for name and package confirmation and currently we can't skip it. For CI/CD convenience, I suggest a --yes flag to skip this confirmation. 

### Platform(s)
All

### Alternatives
Any other flag that can skip mandatory user interactive content

**Comment by dwieeb** [comment]
Can I ask why you're using `init` in CI/CD?

**Comment by camilacanhete** [comment]
@dwieeb I generate the app content and build dynamically (my users can select their build settings), sometimes I use capacitor, sometimes I don't (for web-based build only).

**Comment by dwieeb** [comment]
The `init` command isn't particularly special. It just creates a configuration file, which you could easily do yourself. The command isn't really intended for CI.

**Comment by camilacanhete** [comment]
@dwieeb Ok, I'll preset some variables inside a file instead. Thanks.

**Comment by dwieeb** [comment]
Good luck! Thanks for understanding.
