### ISSUE TITLE
Switch to npm 7

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#4144]
npm 7 is GA: https://github.blog/2021-02-02-npm-7-is-now-generally-available/

Let's switch all Capacitor repos to using npm 7 and the new lockfile format.

**Comment by jcesarmobile** [comment]
I think we only use lockfiles in the test app
https://github.com/ionic-team/capacitor-testapp/pull/116
and the plugin generator
https://github.com/ionic-team/create-capacitor-plugin/pull/54

**Comment by dwieeb** [comment]
Yeah, just making sure we don't need to update anything because of the peer dep change.
