### ISSUE TITLE
feat: Combine LocalNotification and PushNotifications or Notifications Actions in background

### ISSUE THREAD

**Issue by spennyf** [ionic-team/capacitor#4146]
### Description
I would like to be able to send a push notification with a category set on iOS and then have those actions appear on the notification on the device (so far I can do this), and then be able to click that action and run code without the app being brought to the foreground.

### Platform(s)

iOS

### Preferred Solution
I should be able to set up a listener that when the action is clicked the listener will be called and my code executed

### Alternatives
I have tried setting this up with both LocalNotifications and PushNotifications, and I can remotely send an notification and specify the category so I see the actions show up, but unless I set the action as `foreground: true ` no code is executed

**Comment by digaus** [comment]
Afaik it is not possible to execute start the webview in the background. You would need to implement "Notification Service Extension" in Swift for iOS but again, you can only execute code there and not inside the webview.

**Comment by spennyf** [comment]
@digaus thank you for the reply, I am quite sure it can be done as this plugin does it [firebasex](https://www.npmjs.com/package/cordova-plugin-firebasex#ios-actionable-notifications) and I have looked though the swift logic of firebasex and capacitor and when I look at this file and section of code where it would be handled in capacitor [CAPUNUserNotificationCenterDelegate.swift](https://github.com/ionic-team/capacitor/blob/2.4.6/ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift#L83-L126) it looks like there was some logic written but then the `completionHandler ()` is called at the start of the function so none of the logic is executed that is on v2.4.6 and I just looked at main branch and it looks like the plugins have been reorganized and there is some work being done to handle it [here](https://github.com/ionic-team/capacitor/blob/main/ios/Capacitor/Capacitor/NotificationRouter.swift#L49-L59 ) possibly by @ikeith and @dwieeb, maybe they will be able to provide some insight if this feature is coming?

**Comment by jcesarmobile** [comment]
WKWebView pauses the javascript execution as soon as the app is put into the background

There is a new plugin for executing javascript in the background, but outside the WKWebView that might do what you need
https://github.com/ionic-team/capacitor-background-runner

If still doesn't work you can request the feature there.
Closing it here since the plugins are not part of Capacitor itself anymore but separate packages.
