### ISSUE TITLE
bug: capacitor sync ios exited with exit code 1

### ISSUE THREAD

**Issue by phdjsep** [ionic-team/capacitor#4147]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/core 2.4.6
  @capacitor/android 2.4.6
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 13 Capacitor plugins for ios:
    cordova-connectivity-monitor (1.2.2)
    cordova-libgoogleadmobads (7.13.1)
    cordova-play-services-version-adapter (1.1.0)
    cordova-plugin-camera (4.1.0)
    cordova-plugin-googleplus (8.5.0)
    cordova-plugin-ionic (5.4.7)
    cordova-sqlite-storage (5.0.1)
    cordova-plugin-device (2.0.3)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-ionic-webview (4.2.1)
    cordova-plugin-splashscreen (5.0.4)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.4)
[success] iOS looking great! 👌
```

### Platform(s)

ios only. android seems to work fine.

### Current Behavior

Running `ionic cap build ios --verbose` OR `ionic cap sync` results in exit code 1 during `capacitor sync ios` portion. Not an issue with android equivalent commands.

### Expected Behavior

Expected behavior is for it to complete sync successfully.

### Other Technical Details

`npm --version` output: 7.4.0

`node --version` output: v15.6.0

`pod --version` output (iOS issues only): Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
1.9.3

### Additional Context

I'm not certain, but this was working before and I suspect it might be related to a recent XCode update. Current version I'm on (Version 12.4 (12D4e))

**Comment by jcesarmobile** [comment]
can you provide a sample app?
can you run `npx cap sync ios` diretly instead of using the ionic command?

Did you open Xcode 12.4 after updating? after updating, the first time you open it, it prompts you to install additional components and if they are missing cocoapods can fail to run.

**Comment by phdjsep** [comment]
Thanks for the reply.

Tried to create a new project, but that failed as well. Might be related...

```> npm i --save -E @capacitor/core
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ionic-app-base@0.0.0
npm ERR! Found: typescript@4.1.3
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">=4.0 <4.2" from @angular/compiler-cli@11.1.2
npm ERR!   node_modules/@angular/compiler-cli
npm ERR!     peer @angular/compiler-cli@"^11.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"~4.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```

`npx cap sync ios` also fails

Log from that...
```
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.6.0/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'cap',
0 verbose cli   'sync',
0 verbose cli   'ios'
0 verbose cli ]
1 info using npm@7.4.0
2 info using node@v15.6.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/phdjsep/Documents/engineering/ionic/skorkard/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/phdjsep/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 11ms
19 verbose npm-session f03f026037ed37f7
20 timing npm:load Completed in 25ms
21 timing command:exec Completed in 18134ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:379:20)
22 verbose stack     at maybeClose (node:internal/child_process:1065:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
23 verbose pkgid skorkard@1.1.0
24 verbose cwd /Users/phdjsep/Documents/engineering/ionic/skorkard
25 verbose Darwin 20.1.0
26 verbose argv "/usr/local/Cellar/node/15.6.0/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "cap" "sync" "ios"
27 verbose node v15.6.0
28 verbose npm  v7.4.0
29 error code 1
30 error path /Users/phdjsep/Documents/engineering/ionic/skorkard
31 error command failed
32 error command sh -c cap "sync" "ios"
33 verbose exit 1
```

Ya, I'd opended XCode and installed any components.

**Comment by jcesarmobile** [comment]
The problem creating apps is an angular scripts problem with npm 7, you can downgrade to npm 6 or run `npm install --force` or `npm install --legacy-peer-deps` on the folder where you created the app

**Comment by phdjsep** [comment]
Thanks for the creating apps tip. Downgrading npm solved that. Also seems to have solved the capacitor issue, but only if I use the `npx` method. The `ionic cap sync ios` method still fails.

**Comment by jcesarmobile** [comment]
Going to close since the `npx cap` command works, so it's not a Capacitor issue.
If you still face the issue with `ionic cap` commands, you can report it on ionic CLI repository
https://github.com/ionic-team/ionic-cli/issues
