### ISSUE TITLE
Allow ios plugins to specify additional dependencies

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#415]
Right now we aren't allowing Capacitor plugins to have transitive cocoapods dependencies. We should fix that

**Comment by mlynch** [comment]
Basically what we need to do is read the dependencies for the podspec that a plugin author will create (we could/should require this), and then put that in the generated podspec. Also support static_frameworks.

Speaking of which, why don't we just slurp their podspec instead of generating one?

**Comment by jcesarmobile** [comment]
Yeah, we should use the podspec provided by the user.

I think we should make it mandatory for Capacitor plugins, and on the CLI, the part where we delete the existing podspec to regenerate it, do it only for Cordova plugins

**Comment by jcesarmobile** [comment]
With https://github.com/ionic-team/capacitor/pull/428, the plugins will be generated with a .podspec file, so the users will just have to add the dependencies to it as explained in https://guides.cocoapods.org/syntax/podspec.html#dependency
