### ISSUE TITLE
feat: Can we support hybrid plugin? (Cordvoa for iOS & Capacitor for Android) 

### ISSUE THREAD

**Issue by leo6104** [ionic-team/capacitor#4152]
## Feature Request
for Android, it is easy to migrate cordova plugin to capacitor plugin because same programming lanugage 'Java' used.
However, for iOS, it is difficult to migrate Obj-C code to Swift code because Plugin developer should know both Obj-C & Swift language. And it requires lots of time to reimplement & validate plugin function.

If we can use cordova implementation for iOS and partially support Capacitor plugin for android, it would be better to migrate cordova plugin to capacitor community plugin. 

### Description

Now i'm trying to support CodePush feature in Capacitor. 
https://github.com/mapiacompany/capacitor-codepush

### [capacitor-codepush](https://github.com/mapiacompany/capacitor-codepush) Plugin Status
For Android, it works in common case. 
For iOS, Capacitor doesn't inject CodePush variable to import { Plugins } from '@capacitor/core'; so it doesn't work.

### Problems in iOS
Now, it has Cordova implementation. but It detected to Capacitor plugin. So, Capacitor doesn't read CDVPlugin implementation in the code. It seems Capacitor CLI only detect CDVPlugin implementation within capacitor-cordova-ios-plugins folder.

### Platform(s)

iOS & Android.

### Preferred Solution

According to Capacitor CLI implementation, if package.json has "capacitor" value, it stop to extract plugin.xml.
https://github.com/ionic-team/capacitor/blob/e148e67c6061be35db361496444d5fa85544a068/cli/src/plugin.ts#L90-L110
It will make Capacitor search Plugin.swift file and CAPPlugin implementation. (Not CDVPlugin implementation)

My expectation of Capacitor CLI implementation should be
```
    const plugin = {
        id: name,
        name: fixName(name),
        version: meta.version,
        rootPath,
        repository: meta.repository,
    };
    if (meta.capacitor) {
      plugin.manifest = meta.capacitor;
    }
    if (meta.cordova) {
      const pluginXMLPath = join(rootPath, 'plugin.xml');
      const xmlMeta = await readXML(pluginXMLPath);
      plugin.xml = xmlMeta.plugin; // Maybe we should consider meta.capacitor's support platform to be excluded
    }
    return plugin;
```

All cordova plugin has "cordova" plugin configuration in package.json. 

Then i will set package.json to 
```
  "capacitor": {
    "android": {
      "src": "android"
    }
  },
  "cordova": {
    "id": "capacitor-codepush",
    "platforms": [
      "ios"
    ]
  },
```

### Additional Context

https://github.com/capacitor-community/proposals/issues/43

**Comment by jcesarmobile** [comment]
You don’t need to use swift to build capacitor plugins, keyboard plugin is built with  objective-c

https://github.com/ionic-team/capacitor-plugins/tree/main/keyboard/ios/Plugin

**Comment by leo6104** [comment]
Oh.. I didn't know about that. Then, i can do more progress on `capacitor-codepush` with Obj-C code pattern. 

Thank you for reply. @jcesarmobile
