### ISSUE TITLE
feat: Cache HTML/JS from remote server

### ISSUE THREAD

**Issue by lukemovement** [ionic-team/capacitor#4163]
### Description
When I have to deploy a bug fix (JavaScript code) for an application, the most time-consuming part of this process is deploying the applications to the Play/App stores. Given that we are already able to use `capacitor.config.json` to live reload the content of the app (HTML/JS), I would like to put the URL of my remote server in the config. This would mean that no deployment needs to be made for HTML/JS changes.

However, every my app also need to be able to work offline and Capacitor does not seem to cache the HTML/JS files that it loads from my server.

### Platform(s)
All / Any - Sorry, not up to date with native implementations or platform limitations anymore.

### Preferred Solution
![image](https://user-images.githubusercontent.com/1868429/107030780-0969e180-67a9-11eb-84bb-e2f1b31a1f72.png)
Add a value to the capacitor.config.json file to enable caching in the WebViews.
Maybe use an object with value for things like max-life if we feel more flexibility is needed.

An option to hide the 'Using app server' toast would go very well with this as well.
`
{
    "server": {
        "hidetoast":true
    }
}
`

**Comment by jcesarmobile** [comment]
We strongly recommend not using server url in production, so this is a feature we will not provide.

The toast is automatically hidden in production builds, and it's being removed in Capacitor 3 for development builds too
