### ISSUE TITLE
bug: Android plugins aren't accessible in allowNavigation urls

### ISSUE THREAD

**Issue by jgoux** [ionic-team/capacitor#4164]
Hello,

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.1
  @capacitor/ios: 3.0.0-beta.1
  @capacitor/core: 3.0.0-beta.1
  @capacitor/android: 3.0.0-beta.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

We intend to load a remote PWA in production (I know it's not recommended but we take the risk anyway).

To have a better UX, we don't want to go with `server.url` directly but provide a local `index.html` which will display a fallback error if the user start the app while offline.

This is what the logic looks like : 

```ts
// index.ts included in my local index.html

import "@capacitor/core";

import { Network } from "@capacitor/network";

void main();

async function main() {
  try {
    const status = await Network.getStatus();
    if (status.connected) {
      window.location.href = process.env.APP_URL!;
    }
  } catch (e) {
    console.error(e);
  }
}
```

At this point, the plugins are usable (we're still in local).

When the webview is redirected to the `process.env.APP_URL`, which is listed in the `server.allowNavigation` array of the capacitor config, the PWA is started as intended, directly in the webview. Here is the logic in my `capacitor.config.ts` to build the `server` option : 

```ts
function getServerConfig(): CapacitorConfig["server"]  {
  if (process.env.CAPACITOR_PLATFORM === "android") {
    return {
      cleartext: true,
      allowNavigation: [getInternalIp.v4.sync()],
    };
  }

  if (process.env.CAPACITOR_PLATFORM === "ios") {
    return {
      allowNavigation: ["localhost"]
    };
  }

  return {};

}
```

The issue at this point is that the capacitor's plugins aren't accessible anymore when in the PWA, I hit `<PluginName> is not implemented on android`.

The issue is only present on Android, I do the same with ios and the plugins are all accessible from the PWA.

If I use `server.url` directly, **it works** as intended on Android.

So I guess there is a special treatment on the native side for the `server.url`.

### Expected Behavior

I'd like to be able to access the plugins from a url listed in `server.allowNavigation`, or at least being able to define one special URL to proceed like `server.url`, but having control over when this particular url will be displayed in the webview.

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context

I suppose if there is a modification to make it will be in this [function](https://github.com/ionic-team/capacitor/blob/194ae8699944bf016132fb64fe48010679a6d64e/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L173-L226)

**Comment by jcesarmobile** [comment]
how does the `process.env.APP_URL` looks like? I guess it has a port, right?

If it has a port, I've [reported a new issue](https://github.com/ionic-team/capacitor/issues/4244) that appears when using `allowNavigation` and the url has a port

I've created a sample app and [deployed it](https://capacitordevicetest.web.app/), and plugins work fine, this one has only the Device plugin installed, but you can check that it works
