### ISSUE TITLE
bug: "npx cap run ios" does not work, when schema was renamed

### ISSUE THREAD

**Issue by ilblog** [ionic-team/capacitor#4166]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.0.0-beta.1
  @capacitor/core: 3.0.0-beta.1
  @capacitor/ios: 3.0.0-beta.1

[success] iOS looking great! 👌
```

### Platform(s)

ios

### Current Behavior

Running `npx cap run` expects scheme to be named `App` and does not considers, that scheme can be renamed. 

I have renamed `App` to `Windy` as shown in Capacitor documentation.

```
$ npx cap run 
✔ Please choose a platform to run: › ios
✔ Copying web assets from www to ios/App/App/public in 4.00s
✔ Creating capacitor.config.json in ios/App/App in 1.23ms
[info] Found 1 Cordova plugin for ios:
       cordova-plugin-inapppurchase@1.2.0
✔ copy ios in 4.02s
✔ Updating iOS plugins in 6.82ms
[info] Found 5 Capacitor plugins for ios:
       @capacitor/app@0.3.1
       @capacitor/geolocation@0.3.1
       @capacitor/splash-screen@0.3.1
       @capacitor/storage@0.3.1
       capacitor-rate-app@0.1.1
[info] Found 1 Cordova plugin for ios:
       cordova-plugin-inapppurchase@1.2.0
✔ Updating iOS native dependencies with pod install in 12.09s
✔ update ios in 12.15s
✔ Please choose a target device: › Ivo’s iPhone 11 (00008030-001110D61A38802E)
✖ Running xcodebuild - failed!
[error] Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace App.xcworkspace
        -scheme App -configuration Debug -destination id=00008030-001110D61A38802E
        -derivedDataPath
        /Users/ivo/windyty/capacitor-ios/ios/DerivedData/00008030-001110D61A38802E
        
        User defaults from command line:
        IDEDerivedDataPathOverride =
        /Users/ivo/windyty/capacitor-ios/ios/DerivedData/00008030-001110D61A38802E
        
        xcodebuild: error: The workspace named "App" does not contain a scheme named "App". The
        "-list" option can be used to find the names of the schemes in the workspace.
```

### Expected Behavior

`npx cap run` will detect schema or default schema can be passed to the `xcodebuild` as CL argument

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
When you rename the scheme you also have to edit the Podfile with the new scheme name.
Capacitor doesn’t really care about the scheme name, but it runs por install and if the Podfile contains a scheme that no longer exists, it fails to run.

**Comment by ilblog** [comment]
Yes that is what I have did. My Pod contains correct scheme. I guess the `App` scheme is hardcoded in `run.js`

```
    const xcodebuildArgs = [
        '-workspace',
        path_1.basename(await config.ios.nativeXcodeWorkspaceDirAbs),
        '-scheme',
        'App',
        '-configuration',
        'Debug',
        '-destination',
        `id=${target.id}`,
        '-derivedDataPath',
        derivedDataPath,
    ];
```

**Comment by ilblog** [comment]
U R right. In the latest sources on GitHub it is already fixed:

```js
 const xcodebuildArgs = [
    '-workspace',
    basename(await config.ios.nativeXcodeWorkspaceDirAbs),
    '-scheme',
    config.ios.scheme,
    '-configuration',
    'Debug',
    '-destination',
    `id=${target.id}`,
    '-derivedDataPath',
    derivedDataPath,
  ];
```

**Comment by lirbank** [comment]
For anyone running CLI 3.0.0-rc.0 - you also have to update your `capacitor.config.ts` file and rerun 'cap sync'.

```ts
import { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.example.myapp",
  appName: "My App",
  webDir: "www",

  // Add this:
  ios: {
    scheme: "My App",
  },
};

export default config;
```

**Comment by francocores** [comment]
> > For anyone running CLI 3.0.0-rc.0 - you also have to update your `capacitor.config.ts` file and rerun 'cap sync'.
> > ```ts
> > import { CapacitorConfig } from "@capacitor/cli";
> > 
> > const config: CapacitorConfig = {
> >   appId: "com.example.myapp",
> >   appName: "My App",
> >   webDir: "www",
> > 
> >   // Add this:
> >   ios: {
> >     scheme: "My App",
> >   },
> > };
> > 
> > export default config;
> > ```
> 
> I still end up running into a follow up issue:
> 
> ```
> > capacitor run ios --no-sync --target 00008027-001E40590A6A402E
> [react-scripts] Compiling...
> 
> [capacitor] ✔ Running xcodebuild in 90.18s
> [capacitor] ✖ Deploying MyApp.app to 00008027-001E40590A6A402E - failed!
> [capacitor] [error] ERR_UNKNOWN: Path '/......./app/ios/DerivedData/00008027-001E40590A6A402E/Build/Products/Debug-iphoneos/MyApp.app' not found
> [capacitor]         
> [ERROR] An error occurred while running subprocess capacitor.
> ```

in my case something similar happened but having the name and scheme "App", what has solved the problem for me is, add in capacitor.config.ts

`
ios: {
    scheme: "App",
  }
`

-Replace in ios/App/App.xcodeproj/project.pbxproj all references YourBadNameApp.app to App.app

![image](https://user-images.githubusercontent.com/19616858/150544861-e7366a5b-c77f-4ebe-ac00-1fb1de361cad.png)

![image](https://user-images.githubusercontent.com/19616858/150544932-d4c4f474-6c3a-4079-9191-a9aaa551e37d.png)


-Delete ios/DerivedData folder

![image](https://user-images.githubusercontent.com/19616858/150544988-f9345645-bd77-46ff-a9a8-5e214a5062d5.png)


-Open Xcode and run project or execute "ionic cap run ios"

**Comment by adampwright** [comment]
@francocores Would you mind clarifying your comments about replacing ProductReferece and Children value in project.pbxproj please? I'm having this same issue. What should I be putting where you have xxxx? I don't know if I'm being dumb right now or just too hungover. Thanks
