### ISSUE TITLE
bug: /node_modules/@capacitor/app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java:13: error: package com.getcapacitor.annotation does not exist import com.getcapacitor.annotation.CapacitorPlugin;                                   ^

### ISSUE THREAD

**Issue by togro** [ionic-team/capacitor#4168]
## Bug Report

I can't build app , android studio report this :

/node_modules/@capacitor/app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java:13: error: package com.getcapacitor.annotation does not exist
import com.getcapacitor.annotation.CapacitorPlugin;
                                  ^

### Capacitor Version

```
npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-beta.1
  @capacitor/core: 3.0.0-beta.1
  @capacitor/android: 2.4.6

[success] Android looking great! 👌
```

### Platform(s)
android

### Current Behavior
/node_modules/@capacitor/app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java:13: error: package com.getcapacitor.annotation does not exist
import com.getcapacitor.annotation.CapacitorPlugin;

### Other Technical Details

`npm --version` output:  6.13.4

`node --version` output: v12.16.1

**Comment by jcesarmobile** [comment]
To use the new plugins you also need to use capacitor/android beta, but you are using 2.4.6

**Comment by togro** [comment]
Right this was the problem, thanks

**Comment by Krisslk** [comment]
hey, can I know how did you solve it, I have the same issue and struggling for 4 days. please

**Comment by jcesarmobile** [comment]
All the plugins with the `@capacitor` scope in the name are Capacitor 3 plugins, so you have to use Capacitor 3.

If you don't want to move to Capacitor 3 yet, then don't use the plugins with `@capacitor` scope, they were already included in Capacitor 2 without installing anything extra.

**Comment by Krisslk** [comment]
hey, I just updated into capacitor 3 and it works, I am just curious, when I type npx cap doctor it says the latest version is 2.0.7 (something) 

my question is if we are downloading the latest capacitor version when initializing the project, why we should update it to 3.0,0 beta?

**Comment by jcesarmobile** [comment]
Capacitor 3 is still not final, it's at RC stage.

You can use `@next` tag to get latest RC instead of beta.

I'm not saying you should use Capacitor 3, I'm saying you should not use the plugins with the `@capacitor` scope yet, unless you are willing to use Capacitor 3.

I guess you are looking at the Capacitor 3 docs instead of the Capacitor 2 docs, there is a version switcher on the left. Capacitor 2 docs won't tell you to install the plugins with the `@capacitor` scope.

**Comment by Krisslk** [comment]
ooo I see, thank you bro, you saved me. thanks a lot.

for any of you in the future who suffer from the same problem use this doc https://capacitorjs.com/docs/v3
