### ISSUE TITLE
feat: public ios getPlugin()

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/capacitor#4174]
### Description

Android exposes the public `getPlugin()` method on the Bridge instance here: https://github.com/ionic-team/capacitor/blob/002f1e55173a50b9fe918b4eda73b5113b713282/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L477

And we're able to use that to grab the plugin instance from other plugins, with something like:

```
PluginHandle pluginHandle = getBridge().getPlugin("SomePlugin");
```

However, ios does not expose this method, and we should ensure the consistency between the two platforms.

### Platform(s)
ios

### Preferred Solution

add `@objc public` to https://github.com/ionic-team/capacitor/blob/7bb9e0f22fdea369a6522c2d63a5b56baab9f5ca/ios/Capacitor/Capacitor/CapacitorBridge.swift#L286

**Comment by jcesarmobile** [comment]
I think this was on purpose, on capacitor 2 it was public, but @dwieeb preferred that all (or most) plugins had an implementation class with the main logic that people could easily use instead of getting a plugin instance.
But for consistency, it should probably be made private on Android.
