### ISSUE TITLE
feat: Make Firebase and Google Services dependencies optional

### ISSUE THREAD

**Issue by Mageek627** [ionic-team/capacitor#4176]
### Description
I believe it would be a good thing to give the developers the possibility to opt-out of these dependencies. In the open source community, it is a frequent goal to make apps as minimalist and independent as possible, which does not appear to be currently achievable with Capacitor (see https://github.com/veloce/lichobile/issues/1121).

### Platform(s)
Android and iOS

### Preferred Solution
A flag to opt-out.

### Additional Context
This came up following an issue with the Lichess mobile app, which is flagged as "Contains trackers" on F-droid and Aurora Store, despite not having added any explicitly.

**Comment by jcesarmobile** [comment]
Capacitor 3 moved all plugins out, so it doesn’t require any external dependency (only a few AndroidX for older OS version support).
It’s still in beta, but you can give it a try using next tag on npm

**Comment by LongJohn-Silver** [comment]
So do you think you'll be able to mantain a libre version on Lichess, @Mageek627 ?

**Comment by Mageek627** [comment]
Quite possible @LongJohn-Silver, if you wanna add something I suggest continuing in the Lichess repo ;)
