### ISSUE TITLE
bug: App closes without warning when chrome is updated

### ISSUE THREAD

**Issue by beruic** [ionic-team/capacitor#4179]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/core 2.4.2
  @capacitor/android 2.4.2
  @capacitor/cli 2.4.3
  @capacitor/electron not installed
```

### Platform(s)

- Android

### Current Behavior

If Chrome updates while the app is running, the app just closes without warning.

### Expected Behavior

Would be nice if update install could be postponed till the app was closed, or at lease restart the app.
My optimal solution would be to be able to postpone the update of Chrome until the app determines that a it is in a non-critical state, and a restart can be done without issues.

### Code Reproduction

No special code needed.

### Other Technical Details

`npm --version` output: 6.14.10

`node --version` output: v12.20.1

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Thanks for the issue, but there is nothing we can really do about it.
Capacitor apps use the System WebView or Chrome internally and if updating them makes apps that use WebViews restart, that's something at OS level, not app level. We can't block updates neither, you should report it to Google.
