### ISSUE TITLE
Support Ionic 3 Events and Features

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#418]
<img width="327" alt="screen shot 2018-03-31 at 12 50 09 pm" src="https://user-images.githubusercontent.com/11214/38166016-2d3f6cee-34e2-11e8-80e5-7e39b682b56f.png">

iOS

- [x] click
- [x] deviceready 
- [x] error
- [x] hashchange
- [x] keydown
- [x] mousedown
- [x] keyboardWillHide
- [x] keyboardDidHide
- [x] keyboardWillShow
- [x] keyboardDidShow
- [x] offline
- [x] online
- [x] orientationchange
- [x] popstate
- [x] resize
- [x] statusTap
- [x] touchstart

Android

- [x] click
- [x] deviceready 
- [x] error
- [x] hashchange
- [x] keydown
- [x] mousedown
- [x] keyboardWillHide
- [x] keyboardDidHide
- [x] keyboardWillShow
- [x] keyboardDidShow
- [x] offline
- [x] online
- [x] orientationchange
- [x] popstate
- [x] resize
- [ ] statusTap
- [x] touchstart

Electron

- [ ] click
- [ ] deviceready 
- [ ] error
- [ ] hashchange
- [ ] keydown
- [ ] mousedown
- [ ] keyboardWillHide
- [ ] keyboardDidHide
- [ ] keyboardWillShow
- [ ] keyboardDidShow
- [ ] offline
- [ ] online
- [ ] orientationchange
- [ ] popstate
- [ ] resize
- [ ] statusTap
- [ ] touchstart

**Comment by mlynch** [comment]
Need to support the platform features in v3

**Comment by jcesarmobile** [comment]
Going to close since all the iOS and Android events are supported and electron is not officially supported by Ionic.
Also, most of those events are regular web events and work on electron without any changes.
