### ISSUE TITLE
bug: Android - Performance issue after scrolling

### ISSUE THREAD

**Issue by AE1NS** [ionic-team/capacitor#4187]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.6
  @capacitor/android 2.4.6
  @capacitor/core 2.4.6
  @capacitor/electron not installed

[success] Android looking great!
```

### Platform(s)
Android

### Framework(s)
Angular, Ionic

### Current Behavior
When you open the app in Android and don't scroll, you can open a page and return back with fluid transitions. When you just scroll around a bit and open the page again und go back, the transition isn't as fluid as in the beginning.

### Expected Behavior
Always fluid navigation transitions.

### Code Reproduction
Starter project with two demo pages. The home page contains some sliders and another test page has just red background to better demonstrate the issue.
https://github.com/AE1NS/android-performance-issue

### Other Technical Details
`npm --version` output: 6.14.8
`node --version` output: v13.8.0

Tested on: Samsung Galaxy S7 edge

### Additional Context
In a more complex application we have significant performance issues with Android as also described here: https://github.com/ionic-team/capacitor/discussions/3899

### Visual example
You will see it more clear on a real device, as in the low frames gif below.
| Without scrolling | After scrolling |
| ------------- |:-------------:|
| Example project | |
| ![20210210_084216](https://user-images.githubusercontent.com/47378799/107481030-d1ceb100-6b7d-11eb-96d7-531bbd25ff6a.gif) | ![20210210_084318](https://user-images.githubusercontent.com/47378799/107481034-d2ffde00-6b7d-11eb-9078-cc1b21a60097.gif) |
| Productive project | |
| ![20210212_073250](https://user-images.githubusercontent.com/47378799/107737374-96122380-6d04-11eb-936e-862b7b4c7e46.gif) | ![20210212_073344](https://user-images.githubusercontent.com/47378799/107737429-b04c0180-6d04-11eb-883f-46f75f3bfac4.gif) |

**Comment by lincolnthree** [comment]
We are also experiencing slow app performance on Android Capacitor. The exact same app & code deployed and installed through chrome as a PWA is buttery smooth. When installed in Capacitor 3, there are laggy/jittery transitions, animations, etc. We are still trying to find the root cause, but so far nothing has revealed itself.

**Comment by lincolnthree** [comment]
@AE1NS Try setting `android:largeHeap="true"` in your AndroidManifest.xml - Does that make any difference for you? It seemed to make an improvement for us. We also added `android:immersive="true"` (fits our app) and `android:hardwareAccelerated="true"` (defaults to true, but... just in case.)

https://developer.android.com/guide/topics/manifest/application-element#largeHeap

**Comment by lincolnthree** [comment]
Also try setting `android:hardwareAccelerated` on the `MainActivity`

`<activity android:configChanges="keyboardHidden|keyboard|locale|orientation|screenLayout|screenSize|smallestScreenSize|uiMode" android:name="com.maritlabs.topdecked.mtg.MainActivity" android:label="@string/title_activity_main" android:theme="@style/AppTheme.NoActionBarLaunch" android:launchMode="singleTask" android:hardwareAccelerated="true">`

**Comment by AE1NS** [comment]
I tried out your approaches but it does not fixed the issue.

**Comment by lincolnthree** [comment]
@AE1NS Alas, we initially saw an improvement, but after a few more days of testing it has not solved our issue either :( There is something else going on.

**Comment by antonioberetini** [comment]
We are also experiencing issues on Android which are not present on iOS or web.

**Comment by lincolnthree** [comment]
After months of testing, I can only say that there is a definitely performance degradation when using Capacitor vs. native Chrome. I do not know why. This is reproducible. It may not be something typical people experience because their apps are too "simple", but the repro clearly demonstrates the issue. Our users have also reported that switching to our PWA has improved their experience.

**Comment by antonioberetini** [comment]
This may also be related to the web view differences between web view and chrome itself. If this is the cause this is out of control of Capacitors team.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thequailman** [comment]
Venting my frustration here--I had a TWA on Google Play but there isnt a way to do IAP with a TWA per Google's requirement, so I had to switch to Capacitor.  The TWA was blazing fast compared to WebView, but due to Google's payment ~monopoly~ requirement my users have to suffer.

I found this StackOverflow that has some options, I'm not sure how to add them without breaking capacitor though:

https://stackoverflow.com/questions/7422427/android-webview-slow

**Comment by AE1NS** [comment]
Just another example, running on a Samsung Galaxy S20+.
Web version (Fullscreen Chrome, started from shortcut on home screen):

https://user-images.githubusercontent.com/47378799/119254196-48377200-bbb5-11eb-9664-9d93e4a23d45.mp4

Android version:

https://user-images.githubusercontent.com/47378799/119254201-4ff71680-bbb5-11eb-927b-6bb355a29863.mp4

On iOS its also running fine, same as in the web version. Just Android makes trouble.

**Comment by thomasvidas** [comment]
A couple things,

1. I can't get your repro to work on my machine with a couple of different node or npm versions I've tried. Can you update your repro to work with node 14 or 16 with npm 7? The angular devkit version is giving me problems on install.

2. Can you go into the Android Developer options and force Chrome instead of the system webview? Or try the beta or canary web view implementations (installed via play store)? You could also try using Firefox, Brave, or some other browser engine rather than the system webview too via the same "Developer Options" setting

**Comment by lincolnthree** [comment]
@thomasvidas 

> Can you go into the Android Developer options and force Chrome instead of the system webview?

Is that something we could prompt users to do programatically?

**Comment by AE1NS** [comment]
1. I updated the repository and can run it with node 14.17.0 and npm 7.14.0.
2. I cant change this value on my Galaxy S20+. Its the only entry in the list, although Firefox is installed. But this cant be a solution, because the users will not change any version in the developer mode of their devices. Btw: On the Galaxy S7 edge (mentioned in the first thread, please test the repository on an older device like this to see the issue clearly) I have two entries in the list, a disabled "Android System Webview" entry and a selected "Chrome" entry.

**Comment by thomasvidas** [comment]
Thanks for updating your repo, I'll get around to testing it when I get a chance. My intent was to ask you if you saw a performance change when switching between browser engines on Android, not for your users to do so. I would not ask a user "hey go into this developer setting and change this setting." I have an old LG G6 lying around somewhere which is probably similar spec wise to the Samsung S7 so I will use that to test.

@lincolnthree You could probably prompt them to go to developer settings with a clever Android Intent but that would be terrible UX, require them to have other webviews installed, and might get you flagged by Google Play

**Comment by lincolnthree** [comment]
@thomasvidas Makes sense. I figured I'd ask. Definitely do not want to send users down that path, but if it could be requested at the app-level, would have been something.

Also FWIW, on the Google Pixel 2 XL, I do not have any other choice in the menu. Only "Android System WebView" (version 90.0.xxxx)

**Comment by lincolnthree** [comment]
@thomasvidas Makes sense. I figured I'd ask. Definitely do not want to send users down that path, but if it could be requested at the app-level, would have been something.

Also FWIW, on the Google Pixel 2 XL, I do not have any other choice in the menu. Only "Android System WebView" (version 90.0.xxxx)

**Comment by antonioberetini** [comment]
> 1. I updated the repository and can run it with node 14.17.0 and npm 7.14.0.
> 2. I cant change this value on my Galaxy S20+. Its the only entry in the list, although Firefox is installed. But this cant be a solution, because the users will not change any version in the developer mode of their devices. Btw: On the Galaxy S7 edge (mentioned in the first thread, please test the repository on an older device like this to see the issue clearly) I have two entries in the list, a disabled "Android System Webview" entry and a selected "Chrome" entry.

I am not sure I get what the end goal is. WebView on Android is sluggish. Using standalone Chrome standalone mode to me is a better approach but that would mean loosing some of the system API access. Am i reading this wrong?

**Comment by AE1NS** [comment]
I do not understand your question if its addressed to me :)

**Comment by AE1NS** [comment]
@thomasvidas Did you investigate it yet?

**Comment by AE1NS** [comment]
Well, I was really happy to be heard by the dev team. Now another month is gone and we still got no response to the topic.

**Comment by madmacc** [comment]
I am having the same issues.
For me the animation is smooth if I use pure html as a test but if I add conditional html and styles in Ionic/Angular (*ngIf) is really starts to slow down.  However this only seems to be part of the picture.
It would be great to have a solution for this or at least an answer.

**Comment by madmacc** [comment]
I think a lot of Ionic users will start to have this issue as ion-slides has been deprecated and developers will now have to use Swiper.js directly which is what I am having the issues with.

**Comment by AE1NS** [comment]
I intentionally created the reproduction repository in this ticket with a minimal set of code. There is no ion-slides/js swiper, but just a horizontal html scrolling. The issue could be the fontawesome icons, but I am not sure what exactly is causing the performance issue.

If this issue would be fixed (somehow), I would break down our code again if there is still an existing performance issue. Maybe the slider would cause the next performance problem here, but I am not at the point right now to confirm this.

It would be a great thing, if all this problems are caused by a single fixable chromium bug, but it seems to me that its not as easy as it looks ... I think we can only get ahead with the help of competent developers, that can investigate/debug this on some deeper level.

**Comment by AE1NS** [comment]
I just used the [LiveReload](https://capacitorjs.com/docs/guides/live-reload) feature to run the app with reference to my machine. Inside the chrome browser (most recent stable), I also opened the application.
Inside the browser the app is running flawless without any problems, but inside the webview I get always huge framedrops on my Galaxy S20 (and also on a Galaxy S7 edge). _(Btw: I also used the Angular dev tools profiler, and we dont have any change detection issues.)._ I especially see the frame drops while the ionic page animations. When I run the app on a Pixel 4 or a 3 year old Motorola, the app is running fine. This seems to be a problem with Samsung devices. The S20 uses the same webview implementation (I see this inside the dev options in the settings) as the chrome browser. Its the latest version. Android System WebView 94.0.4606.61

**Comment by fabmesto** [comment]
I have the same problem with my app. Transactions are a mess on Android.

**Comment by mitschmidt** [comment]
My team and I were having the same issues with performance on Android, while iOS was really smooth even on older devices.

We figured this was due to resources (i.e. number of DOM nodes) in combination with animations, my colleague @derbenoo found an elegant solution for our App. We plan to share our insights on our blog in the future, would that be interesting for anybody?

**Comment by fabmesto** [comment]
> My team and I were having the same issues with performance on Android, while iOS was really smooth even on older devices.
> 
> We figured this was due to resources (i.e. number of DOM nodes) in combination with animations, my colleague @derbenoo found an elegant solution for our App. We plan to share our insights on our blog in the future, would that be interesting for anybody?

surely!

**Comment by skout90** [comment]
@falkenhawk  In mi a2(snapdragon 660), lg v35(snapdragon 835), performnce bad😣

**Comment by madmacc** [comment]
Motorola G6 (XT1925-5) Android 8.0.0.  Pretty jerky.  🐢

**Comment by maxcodefaster** [comment]
Also experiencing performance problems with ionic page transitions on webview android on a Pixel 5. In chrome browser on Android the App works snappy. Same goes for iOS. Hardware acceleration is turned on by default. Best practices are applied. Heavy dom writes are avoided. Seems to be a capacitor issue.

**Comment by AE1NS** [comment]
I think this issue depends to the webview implementation and the capacitor team cant do anything right now, because they are using the native webview without any special configuration.

@lincolnthree thank you for creating the issue in the chromium bug tracker
https://bugs.chromium.org/p/chromium/issues/detail?id=1289741
In my understanding, this is the correct place right now, where it "could" be fixable.

**I found out, that the password manager LastPass was causing the issue in my case. When I go to "Settings > Accessibility > Installed apps" and disable LastPass there, the app and its transitions are running well again.**

So in general it could be just accessibility tools, that are blocking the UI thread or something, thats causing our issue. Unfortunately the chromium developers confirmed the following:
"In general you should *not* expect WebView to perform equivalently to Chrome. That doesn't mean there isn't an issue in this case, but Chrome and WebView use different rendering paths and have other important configuration differences that can result in slower performance in WebView."
It would be more helpful for such great frameworks like capacitor, to not have that kind of limitations, but thats the state of things right now.

Therefore I will close this ticket. Thank you for all your participation to get closer to a solution.

**Comment by visuallization** [comment]
@AE1NS thanks for digging into this! Would be really cool if android manage to fix it's webview rendering implementation (or if capactior goes with a different solution)
