### ISSUE TITLE
feat: cordova plugin dependency validation/check

### ISSUE THREAD

**Issue by ryaa** [ionic-team/capacitor#4188]
### Description
It seems that if, in capacitor project, you remove a cordova plugin that another existing/installed cordova plugin depends on, there is no warning.
For example, I have cordova-plugin-actionsheet and uk.co.workingedge.phonegap.plugin.launchnavigator installed (the latter depends on the former). If I run `run uninstall cordova-plugin-actionsheet` there is no warning.
Is there any way to make sure that the cordova plugin dependency is not broken if I remove a specific cordova plugin in a capacitor project?

### Platform(s)
Android/iOS

### Preferred Solution
Display the warning if a cordova plugin is removed which might break things.

### Alternatives
There is a warning displayed if you try to remove a cordova plugin which is used by another one using cordova cli.

### Additional Context
N/A

**Comment by jcesarmobile** [comment]
Capacitor 2 installs plugin dependencies, if you uninstall a dependency, next time you run `npx cap update` it will install it again. You should run `npx cap update` after `npm install` and after `npm uninstall`.

Capacitor 3 no longer installs dependencies, but if you uninstall a dependency, when you run `npx cap update` it warns you that the dependency is missing.
