### ISSUE TITLE
bug: Capacitor permissions query for android returns true when permission has not been given

### ISSUE THREAD

**Issue by cambronjay** [ionic-team/capacitor#4189]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/core 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/android 2.4.6
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 11 Capacitor plugins for ios:
    @capacitor-community/fcm (1.0.8)
    @codetrix-studio/capacitor-google-auth (2.1.3)
    capacitor-apple-login (0.0.6)
    capacitor-firebase-auth (2.3.2)
    capacitor-rate-app (0.1.1)
    cordova-documentpicker (1.2.2)
    cordova-open-native-settings (1.5.2)
    cordova-plugin-filechooser (1.2.0)
    cordova-plugin-ios-disableshaketoedit (1.0.0)
    cordova-plugin-screen-orientation (3.0.2)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌
```

### Platform(s)

Android

### Current Behavior
When I query the notifications permission in android it always returns true even though I have not yet requested permission. 

### Expected Behavior

Permissions query for notifications should return false for android when permission has never been granted. 

### Code Reproduction

import { Plugins, PermissionType } from '@capacitor/core';
const { Permissions } = Plugins;

            const permissionGranted = await Permissions.query({
                name: PermissionType.Notifications
            });

### Other Technical Details

`npm --version` output: 6.14.5

`node --version` output: 12.18.2

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
That's because Android doesn't have a notifications permission, you can enable them or disable them, but never prompt for a permission.
Permission plugin is going away in Capacitor 3 anyway, plugins will have a way of checking the status
