### ISSUE TITLE
Share API - Unable to share images, videos and files.

### ISSUE THREAD

**Issue by andrewl94** [ionic-team/capacitor#4192]
### Capacitor Version

   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed

[success] Android looking great! �

### Platform(s)
Android

### Current Behavior
On docs (https://capacitorjs.com/docs/apis/share) it states:  
"The Share API works on iOS, Android, and the Web (using the new Web Share API), though web support is currently spotty."

Web Share API are able to Share Images, Videos, Files. (Web Share Api Doc: https://web.dev/web-share/)

I wasn't able to make it work on Share API nor I found anywhere on docs an example or documentation of that possibility.

### Expected Behavior
Being able to share Images, videos and files.
Also, an review on the docs of the Share API

### Other Technical Details

Developing with Quasar Framework

**Comment by jcesarmobile** [comment]
you can share files by passing a file url in the url parameter, doesn't work with some apps, there are a few issues reported here https://github.com/ionic-team/capacitor-plugins/issues
