### ISSUE TITLE
bug: Cordova plugins no longer sync during 'npx cap sync' (Capacitor 3)

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor#4193]
### Capacitor Version

```
sharktop:topdecked-unified lincoln$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.2
  @capacitor/core: 3.0.0-beta.2
  @capacitor/android: 3.0.0-beta.2
  @capacitor/ios: 3.0.0-beta.2

[success] iOS looking great! 👌
[error] Unable to read: /Users/lincoln/projects/maritlabs/topdecked-unified/android/app/src/main/AndroidManifest.xml

```

NOTE: I'm not sure why `cap doctor` is complaining about AndroidManifest.xml. It's there and readable. I've even tried copying a "clean" one in from a sample project.

`-rw-r--r--  1 lincoln  staff   2.4K Feb 11 18:52 /Users/lincoln/projects/maritlabs/topdecked-unified/android/app/src/main/AndroidManifest.xml`

### Platform(s)

ios, android, web

### Current Behavior

Cordova plugins that were previously synced to the native Android and iOS plugins project are now completely ignored: `cordova-plugin-purchase`, `cordova-plugin-file-opener2`

I'd expect to see those plugins synced, but instead, it seems to be skipping all cordova plugins entirely. Things stopped working somewhere during the 3.0 upgrade process.

```
sharktop:topdecked-unified lincoln$ npx cap sync
✔ Copying web assets from www to android/app/src/main/assets/public in 1.17s
✔ Creating capacitor.config.json in android/app/src/main/assets in 1.43ms
✔ copy android in 1.22s
✔ Updating Android plugins in 19.67ms
[info] Found 15 Capacitor plugins for android:
       @capacitor/app@0.3.3
       @capacitor/app-launcher@0.5.3
       @capacitor/browser@0.4.3
       @capacitor/clipboard@0.4.3
       @capacitor/filesystem@0.4.0
       @capacitor/geolocation@0.4.0
       @capacitor/haptics@0.3.3
       @capacitor/keyboard@0.5.3
       @capacitor/local-notifications@0.4.0
       @capacitor/network@0.4.3
       @capacitor/push-notifications@0.3.3
       @capacitor/share@0.5.0
       @capacitor/splash-screen@0.3.3
       @capacitor/status-bar@0.4.3
       capacitor-firebase-auth@2.3.5
✔ update android in 127.85ms
✔ Copying web assets from www to ios/App/App/public in 1.23s
✔ Creating capacitor.config.json in ios/App/App in 838.20μp
✔ copy ios in 1.27s
✔ Updating iOS plugins in 18.93ms
[info] Found 15 Capacitor plugins for ios:
       @capacitor/app@0.3.3
       @capacitor/app-launcher@0.5.3
       @capacitor/browser@0.4.3
       @capacitor/clipboard@0.4.3
       @capacitor/filesystem@0.4.0
       @capacitor/geolocation@0.4.0
       @capacitor/haptics@0.3.3
       @capacitor/keyboard@0.5.3
       @capacitor/local-notifications@0.4.0
       @capacitor/network@0.4.3
       @capacitor/push-notifications@0.3.3
       @capacitor/share@0.5.0
       @capacitor/splash-screen@0.3.3
       @capacitor/status-bar@0.4.3
       capacitor-firebase-auth@2.3.5
✔ Updating iOS native dependencies with pod install in 8.67s
✔ update ios in 8.72s
✔ copy web in 278.08μp
✔ update web in 60.64μp
[info] Sync finished in 11.344s
sharktop:topdecked-unified lincoln$ 
```
As you can see, no mention of `cordova-plugin-purchase`.

### Expected Behavior

Cordova plugins should continue to sync to the native workspaces/filesystem.

Output from the example project, below. These same plugins are installed in my primary project (with the issue). The package.json entries and all configs I could find, are the same:
```

sharktop:example lincoln$ npx cap sync
✔ Copying web assets from www to android/app/src/main/assets/public in 685.01ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 822.73μp
⠼ copy android [info] Found 2 Cordova plugins for android:
       cordova-plugin-file-opener2@3.0.5
       cordova-plugin-purchase@10.5.3
✔ copy android in 738.37ms
✔ Updating Android plugins in 8.25ms
[info] Found 15 Capacitor plugins for android:
       @capacitor/app@0.3.3
       @capacitor/app-launcher@0.5.3
       @capacitor/browser@0.4.3
       @capacitor/clipboard@0.4.3
       @capacitor/filesystem@0.4.0
       @capacitor/geolocation@0.4.0
       @capacitor/haptics@0.3.3
       @capacitor/keyboard@0.5.3
       @capacitor/local-notifications@0.4.0
       @capacitor/network@0.4.3
       @capacitor/push-notifications@0.3.3
       @capacitor/share@0.5.0
       @capacitor/splash-screen@0.3.3
       @capacitor/status-bar@0.4.3
       capacitor-firebase-auth@2.3.5
⠙ update android [info] Found 2 Cordova plugins for android:
       cordova-plugin-file-opener2@3.0.5
       cordova-plugin-purchase@10.5.3
✔ update android in 89.75ms
[warn] Using the iOS project root for the public directory is deprecated.
       Please follow the Upgrade Guide to move public inside the iOS target directory:
       https://capacitorjs.com/docs/v3/updating/3-0#move-public-into-the-ios-target-directory
✔ Copying web assets from www to ios/App/public in 799.86ms
✔ Creating capacitor.config.json in ios/App/App in 380.95μp
⠦ copy ios [info] Found 2 Cordova plugins for ios:
       cordova-plugin-file-opener2@3.0.5
       cordova-plugin-purchase@10.5.3
✔ copy ios in 818.02ms
✔ Updating iOS plugins in 6.98ms
[info] Found 15 Capacitor plugins for ios:
       @capacitor/app@0.3.3
       @capacitor/app-launcher@0.5.3
       @capacitor/browser@0.4.3
       @capacitor/clipboard@0.4.3
       @capacitor/filesystem@0.4.0
       @capacitor/geolocation@0.4.0
       @capacitor/haptics@0.3.3
       @capacitor/keyboard@0.5.3
       @capacitor/local-notifications@0.4.0
       @capacitor/network@0.4.3
       @capacitor/push-notifications@0.3.3
       @capacitor/share@0.5.0
       @capacitor/splash-screen@0.3.3
       @capacitor/status-bar@0.4.3
       capacitor-firebase-auth@2.3.5
[info] Found 2 Cordova plugins for ios:
       cordova-plugin-file-opener2@3.0.5
       cordova-plugin-purchase@10.5.3
✔ Updating iOS native dependencies with pod install in 5.80s
✔ update ios in 5.83s
✔ copy web in 324.65μp
✔ update web in 51.71μp
[info] Sync finished in 7.478s
```

### Code Reproduction

I've tried creating a sample project that reproduces the issue. It seems to work in the example.

### Other Technical Details

`npm --version` output: 6.14.9
`node --version` output: v14.15.0
`pod --version` output (iOS issues only): 1.10.0

### Additional Context

As I said, I've tried creating a sample project that reproduces the issue. I cannot identify a difference between my primary project and this.

I've tried copying all the configs I know to copy (package.json dependencies, capacitor.config.json, ionic.config.json, etc) over from the sample project. Same result. I'm starting to wonder if that `AndroidManifest.xml` error is actually related. (I've copied a clean version of that in, too)

I've deleted `node_modules` and re-run `npm i`. I've deleted `node_modules` and `package-lock.json` and re-generated them both.

I've even tried removing the native ios/android platforms and re-adding them.

Is there some kind of capacitor CLI cache I can clear? How would I "reset" the Cordova plugin detection? Where should I start debugging this for more info? Happy to dig in on it, just need to know where to start.

Wasn't able to find any similar issues, so submitting this here.

**Comment by lincolnthree** [comment]
After deleting the following files and directories:

```
.gradle/
android/
ios/
node_modules/
package-lock.json
```

Then running:
 ```
npx cap init` again.         # (even though it was already initalized)
npx cap add android
npx cap add android
```

I have gotten things back into working order, with a bunch of setup/verification to do over again. Will update if I learn anything more. 

Still no idea what caused this but i'll be watching closely to see if it happens again, and what caused it, as I get things current.

**Comment by lincolnthree** [comment]
This file is new (was not present prior to wipe/reinstall):

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	android/app/.gitignore

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by lincolnthree** [comment]
After restoring all of the old configuration and project files from git, things are still working. Seems like something in the capacitor project files or some cached data stuck somewhere.

**Comment by dotNetkow** [comment]
I'm seeing this on both upgraded Cap 2 projects and fresh Cap 3 projects (Cap 3 beta 3).
Cordova plugins in use: cordova-plugin-ionic, @ionic-enterprise/auth, and Identity Vault.

Agreed that it's not detecting and/or syncing the plugins. Sample output that is missing:

```
Found 1 Cordova plugin for ios
    @ionic-enterprise/auth (3.3.1)
```

Repo here: https://github.com/ionic-team/demo-authconnect-auth0/tree/cap3

**Comment by jcesarmobile** [comment]
it's the same problem as on https://github.com/ionic-team/capacitor/issues/4223

will be fixed on next release, but as workaround you can install latest version of xml2js
