### ISSUE TITLE
feat: Aesthetic modals at PWA

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/capacitor#4194]
## Feature Request
Aesthetic modals at PWA

### Description
I understand that Capacitor components are native to each device and browser. But in the cases of the PWA of for example Chrome or Mozilla, the "Alerts" that appear dirty all the context and aesthetics of the application or web.

### Platform(s)
PWA/WEB

### Preferred Solution
I propose to put the modals only in the PWA cases as they are in ionic: https://ionicframework.com/docs/api/alert

### Alternatives
Leave it as it is

### Additional Context
Sorry if my English is not very good, it is not my native language :)

**Comment by jcesarmobile** [comment]
it's planned on https://github.com/ionic-team/capacitor-plugins/issues/55
