### ISSUE TITLE
feat: setting badge for local notifications

### ISSUE THREAD

**Issue by csurbier** [ionic-team/capacitor#4195]
### Description
Need to be able to set the badge number when scheduling a local notification.
Missing a content.badge in your LocalNotificationsPlugin

### Platform(s)
iOS

For Android don't know if this feature exists. Please check it.

### Preferred Solution
In the Interface LocalNotification please add a badge parameter

**Comment by jcesarmobile** [comment]
there is another issue open about it
https://github.com/ionic-team/capacitor-plugins/issues/228
