### ISSUE TITLE
bug: Capacitor 3 adds the 'cordova' and 'hybrid' platforms to web

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor#4198]
### Capacitor Version

```
sharktop:example lincoln$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.2
  @capacitor/core: 3.0.0-beta.2
  @capacitor/android: 3.0.0-beta.2
  @capacitor/ios: 3.0.0-beta.2


```

### Platform(s)

Web, PWA

### Current Behavior

Fairly simple issue. After upgrading to Capacitor 3.x, we noticed that Native plugin wrappers were attempting (and failing) to activate in our Web & PWA platform builds, across the board.

After a night of investigation, we've determined that Capacitor is incorrectly adding the 'cordova' and 'hybrid' platforms when running in the 'web' platform.

See screenshot of printed platforms running with `ionic serve --port 8101` (port 8100 was taken):

![image](https://user-images.githubusercontent.com/362329/107789462-9f5cb980-6d1f-11eb-8bcc-2a114fb638b5.png)

### Expected Behavior

As with Capacitor 2.4.6, we'd expect the additional platforms to be added only when running in the actual environments to which they represent. Like so: 

![image](https://user-images.githubusercontent.com/362329/107789722-f5c9f800-6d1f-11eb-9f97-2c9417868407.png)

### Code Reproduction

##Demonstrates the breaking behavior:
```
git clone git@github.com:lincolnthree/capacitor-3-platforms-incorrect.git
npm i
ionic serve
# Open browser dev tools and view printed platforms in console
```
https://github.com/lincolnthree/capacitor-3-platforms-incorrect

##Demonstrates the expected behavior:
```
git clone git@github.com:lincolnthree/capacitor-3-platforms-incorrect.git
git checkout 2.4.6
npm i
ionic serve
# Open browser dev tools and view printed platforms in console
```
https://github.com/lincolnthree/capacitor-3-platforms-incorrect/tree/2.4.6

### Other Technical Details

`npm --version` output: 6.14.9

`node --version` output: v14.15.0

`pod --version` output (iOS issues only):

### Additional Context

We have not been able to find a suitable workaround, but if one exists, we'd love to hear it! If this behavior is intended, how can we disable it for backwards compatibility with our already implemented platform detection checks?

**Comment by dwieeb** [comment]
Fixed in https://github.com/ionic-team/capacitor/pull/4214
