### ISSUE TITLE
bug: Capacitor 3 typescript config breaks `ionic capacitor run`

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor#4199]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.2
  @capacitor/core: 3.0.0-beta.2
  @capacitor/android: 3.0.0-beta.2
  @capacitor/ios: 3.0.0-beta.2

```

### Platform(s)

iOS, Android

### Current Behavior

Use the capacitor.config.ts config specification breaks the funcitonality of `ionic capacitor run [platform] --livereload --external`

The CLI appears to ignore the ts file and generate a blank `capacitor.config.json` which it then also appears to ignore.

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)\
	capacitor.config.json
```

### Expected Behavior

run from dev server should work. Capacitor CLI should be able to modify the TS config to support this functionality.

### Code Reproduction

```
git clone https://github.com/lincolnthree/capacitor-3-platforms-incorrect
git checkout ts-config-run
npm i
ionic capacitor run android --livereload --external
# Then debug the project on a native device. You will notice the files are loading from localhost, not port 10.0.0.3:8100
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
this is something ionic CLI needs to handle, it's a work in progress 
https://github.com/ionic-team/ionic-cli/pull/4610
