### ISSUE TITLE
npx: command not found

### ISSUE THREAD

**Issue by MELAS007** [ionic-team/capacitor#421]
USING Windows 10.

i installed and ran npx cap init..... it told  me npx: command not found

hoow can I solve this?

thanks in advance!

**Comment by jcesarmobile** [comment]
Which node version do you have installed?
Are you using something like nvm-windows?

**Comment by gibbsvjy007** [comment]
Could you please try again with npm install -g npx and then reopen your cmd terminal.

It should work

**Comment by jcesarmobile** [comment]
yeah, if he installs npx it will work, but he shouldn't need to install it

**Comment by MELAS007** [comment]
Node : v.6.10.2

**Comment by MELAS007** [comment]
I didnt know that should be installed and It doesn't mention to in ionic
page

**Comment by jcesarmobile** [comment]
The base requirements for Capacitor are Node v8.6.0 or later, and NPM version 5.6.0 or later. That node/npm versions already include npx by default.

https://capacitor.ionicframework.com/docs/getting-started/dependencies/

**Comment by kensodemann** [comment]
In light of this, it may make sense to put the "Required Dependencies" before the "Installation" in the "Getting Started" section. Create a quick PR for that: https://github.com/ionic-team/capacitor/pull/422

**Comment by MrDatastorage** [comment]
Easy to resolve, just add 

    alias npx='/usr/local/Cellar/node/10.11.0/bin/npx'

In your `.bash_profile` and refresh your profile with this command

    source ~/.bash_profile

I hope this will resolve your issue. On my side, it is already working :)
