### ISSUE TITLE
cannot find symbol import com.getcapacitor.PermissionState

### ISSUE THREAD

**Issue by manisi** [ionic-team/capacitor#4217]
Hi,
Build fail in android studio, 
/node_modules/@capacitor/geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/GeolocationPlugin.java:7: error: cannot find symbol
import com.getcapacitor.PermissionState;
                       ^
  symbol:   class PermissionState
  location: package com.getcapacitor

geolocation plugin not compile.

💊 Capacitor Doctor 💊

Latest Dependencies:

@capacitor/cli: 2.4.6
@capacitor/core: 2.4.6
@capacitor/android: 2.4.6
@capacitor/electron: 2.4.6
@capacitor/ios: 2.4.6

Installed Dependencies:

@capacitor/cli 2.4.4
@capacitor/android 2.4.6
@capacitor/ios 2.4.4
@capacitor/core 2.4.6
@capacitor/electron not installed

node  : v14.15.1
npm :v7.5.4
Thanks

**Comment by manisi** [comment]
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.4
  @capacitor/android 2.4.6
  @capacitor/ios 2.4.4
  @capacitor/core 2.4.6
  @capacitor/electron not installed

**Comment by jcesarmobile** [comment]
`@capacitor/geolocation` is a Capacitor 3 plugin, doesn't work on Capacitor 2. Capacitor 2 has Geolocation plugin built-in in core

**Comment by manisi** [comment]
> `@capacitor/geolocation` is a Capacitor 3 plugin, doesn't work on Capacitor 2. Capacitor 2 has Geolocation plugin built-in in core

Thanks to you

**Comment by golinskiSt** [comment]
I also have the same problem and i am using @capacitor/core for Permissions
import { Plugins } from '@capacitor/core';
const { Geolocation } = Plugins;

Problem with ```
error: cannot find symbol
import com.getcapacitor.PermissionState;
``` still occures

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.6
  @capacitor/core 2.4.6
  @capacitor/android 2.4.6
  @capacitor/electron 2.4.7
