### ISSUE TITLE
bug:  window.Capacitor.Plugins.<pluginName> undefined with 3.0.0-beta.2

### ISSUE THREAD

**Issue by sebdoby** [ionic-team/capacitor#4218]
## Bug Report
Hello team !

First, thanks for this super project ;)

I'm using an Angularjs application to build an IOS hybrid app with 3.0.0-beta.1. 
I would like to switch to 3.0.0-beta.2 but I have a problem to access plugins : window.Capacitor.Plugins.PushNotifications or any others plugins is undefined.

window.Capacitor.isPluginAvailable('PushNotifications') -> return true
but :
$window.Capacitor.Plugins.PushNotifications.requestPermissions() ->
TypeError: undefined is not an object (evaluating 'window.Capacitor.Plugins.PushNotifications.requestPermissions')

Same problem with :
window.Capacitor.Plugins.Device.getInfo()

When i go back to capacitor/ios@3.0.0-beta.1. It's ok

Is there a change to use plugins ?

Thanks for your help
Sébastien

### Capacitor Version 3.0.0-beta.2

@capacitor/app@0.3.3
├── @capacitor/camera@0.4.0
├── @capacitor/cli@3.0.0-beta.2
├── @capacitor/core@3.0.0-beta.2
├── @capacitor/device@0.5.3
├── **@capacitor/ios@3.0.0-beta.2**
├── @capacitor/keyboard@0.5.3
├── @capacitor/network@0.4.0
├── @capacitor/push-notifications@0.3.3
├── @capacitor/splash-screen@0.3.3
└── @capacitor/status-bar@0.4.3

### Platform(s)
WEB / IOS

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by sebdoby** [comment]
Thanks for your answer.
Not easy to share reliable code reproduction.

In the module @capacitor/ios between 3.0.0-beta.2 and 3.0.0-beta.1, you have added a new concept of "PluginHeaders" : I think there is a regression on Plugins object of window.Capacitor.

I have tested the same code, with the same versions of librairies except @capacitor/ios 3.0.0-beta.1 and @capacitor/ios 3.0.0-beta.2
With the beta.2, window.Capacitor.Plugins.<PluginName> is not set as you can see on the screenshots.

![3 0 0 beta 1](https://user-images.githubusercontent.com/79212486/108238734-82721d00-7149-11eb-8b0e-667b8e34d67e.png)
![3 0 0 beta 2](https://user-images.githubusercontent.com/79212486/108238738-843be080-7149-11eb-8da6-3ebac5433b78.png)

**Comment by alanxp** [comment]
Why nobody can't seem to help, this is making people downgrade versions..

**Comment by alanxp** [comment]
- [ ] 

- [ ] 

> Thanks for your answer.
> Not easy to share reliable code reproduction.
> 
> In the module @capacitor/ios between 3.0.0-beta.2 and 3.0.0-beta.1, you have added a new concept of "PluginHeaders" : I think there is a regression on Plugins object of window.Capacitor.
> 
> I have tested the same code, with the same versions of librairies except @capacitor/ios 3.0.0-beta.1 and @capacitor/ios 3.0.0-beta.2
> With the beta.2, window.Capacitor.Plugins. is not set as you can see on the screenshots.
> 
> ![3 0 0 beta 1](https://user-images.githubusercontent.com/79212486/108238734-82721d00-7149-11eb-8b0e-667b8e34d67e.png)
> ![3 0 0 beta 2](https://user-images.githubusercontent.com/79212486/108238738-843be080-7149-11eb-8da6-3ebac5433b78.png)

I've tested with 3.0.0beta.1 and not even there, it only has the object webView

**Comment by jcesarmobile** [comment]
I've deployed [this sample app](https://capacitordevicetest.web.app/home) to firebase, it only contains Device plugin.
calling `await window.Capacitor.Plugins.Device.getInfo();` from Chrome console properly returns the device information. Same information as if you click the only button the web has.

It used Capacitor beta 3, so not sure if it was fixed. But I can't reproduce so I'll close.

**Comment by alanxp** [comment]
> I've deployed [this sample app](https://capacitordevicetest.web.app/home) to firebase, it only contains Device plugin.
> calling `await window.Capacitor.Plugins.Device.getInfo();` from Chrome console properly returns the device information. Same information as if you click the only button the web has.
> 
> It used Capacitor beta 3, so not sure if it was fixed. But I can't reproduce so I'll close.

@jcesarmobile  Its not about **device getInfo**, we are talking about the **plugins** we **cant** use them, Not even with await, can you reproduce that instead?

**Comment by jcesarmobile** [comment]
The issue is about `window.Capacitor.Plugins.PluginName` not working.
I've provided a sample app where `window.Capacitor.Plugins.Device` is working.

Other plugins are not working on my app because I only installed Device plugin.

I've asked for a sample app and none was provided.

**Comment by sebdoby** [comment]
Hello
Thanks for your test jcesarmobile. It is build for IOS ?

I have always the problem with **ios@3.0.0.beta.3** : object Plugins is filled only with "WebView" whereas PluginHeaders is OK with all plugins.

**Comment by alanxp** [comment]
> Hello
> Thanks for your test jcesarmobile. It is build for IOS ?
> 
> I have always the problem with **ios@3.0.0.beta.3** : object Plugins is filled only with "WebView" whereas PluginHeaders is OK with all plugins.

i already told him that even beta 3 doesnt let the plugins works, he wants you to do a sample not working,

**Comment by jcesarmobile** [comment]
I tested on both iOS and web as those where the platforms where you said it wasn't working.

**Comment by sebdoby** [comment]
Hello @jcesarmobile ,

I know how to reproduce the bug and it's very easy:
Create sample app following the tutorial with npm init @capacitor/app and npm install @capacitor/core@next @capacitor/cli@next and @capacitor/ios@next (so 3.0.0-beta.3)

1) npx cap add ios
2) npx cap sync
3) npx cap open ios

Use for example simulator iphone 11 : when the app is starting, you get an error javascript on the line Capacitor.Plugins.SplashScreen.hide(); => **undefined**

After, if you do: 
npm install @capacitor/ios@3.0.0-beta.1
npx cap sync
Use simulator iphone 11 -> it's OK ! 

So I'm sure now you have a regression since @capacitor/ios@3.0.0-beta.2 if you use capacitor plugins.

**Comment by mburger81** [comment]
@sebdoby & @alanxp do you have resolved it?
I have opened a new bug for this

**Comment by mburger81** [comment]
reopened as #4280

**Comment by sebdoby** [comment]
No, it's not resolved.
I see with your comment that the problem is the same on Android

I must use the @capacitor/ios@3.0.0-beta.1 to build my app.
