### ISSUE TITLE
feat: [Capacitor 3] npx cap sync fails if no Android project present

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/capacitor#4225]
### Description
In Capacitor 3, running `npx cap sync` fails if there is an iOS project present but no Android project. This is because it syncs Android first, can't find it, and stopping executing (thus the iOS project isn't synced).

### Platform(s)
Cap CLI v3

### Preferred Solution
Devs may not have an Android project and since `npx cap sync` is less to type than `npx cap sync ios`, it would be nice to sync any platforms that are found without error.

**Comment by jcesarmobile** [comment]
I can't reproduce, if you don't pass any platform it's supposed to check which ones are present, so if android is not present it should just skip it

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dotNetkow** [comment]
Tried to repo in a fresh project but can't. If it happens again in the other project, I'll reopen with more details.
