### ISSUE TITLE
Whitelist domains with Capacitor...?

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#425]
Hi.

With Cordova one does it like this:
https://cordova.apache.org/docs/en/latest/guide/appdev/whitelist/

How to do similar configurations in Capacitor?

**Comment by mlynch** [comment]
We don’t have that feature and I’m hesitant to add it as I don’t think it really provides much. Open to thoughts

**Comment by jcesarmobile** [comment]
It supposedly adds security as it only allows connections to the configured urls.
But the truth is, most people just * everything.
Also, on iOS it's just used to configure ATS exceptions, and on Capacitor you can do it by manually editing the info.plist

**Comment by mlynch** [comment]
Leaving this open but unsure if we should do a whitelist option like cordova did. I believe react native doesn't have one?

**Comment by ryaa** [comment]
Not sure if this is related, but file transfer cordova plugin does not seem to be working on Android and the culprit seems to be related to whitelisting (see https://github.com/ionic-team/capacitor/issues/1199).

**Comment by jcesarmobile** [comment]
Closing as we now have the `server.allowNavigation` that is some sort of whitelist that allows some external urls to be opened inside the webview (similar to Cordova's allow-navigation).
For other connection restrictions such as image loading or script execution I would recommend to configure the CSP in your index.html. 

https://capacitor.ionicframework.com/docs/basics/configuring-your-app

**Comment by RipRyness** [comment]
I need to download files onto the device. FileTranfer works great in iOS.

`server.allowNavigation` has nothing to do with the functionality that the `cordova-plugin-whitelist` provides. I do not see any mechanism to use that plugin without a `config.xml` file. Some guidance on this issue from the ionic team would be greatly appreciated.

**Comment by silviasecco** [comment]
I have this problem, too

**Comment by tpharaoh** [comment]
question: I am using the app for configuring a local network device, the embedded server runs on http://192.168.1.1 however, multiple posts tell me android blocks all non https requests.

My IOS app can post to the above IP, but android gets network error response.
@mlynch is there another way to accomplish this?

**Comment by tpharaoh** [comment]
@silviasecco I used https://stackoverflow.com/questions/55074899/internet-permission-not-working-in-oreo-and-pie and edited the androidManifest, it worked. I am not sure if that will affect the approval from google, thats a whole other topic :)
