### ISSUE TITLE
bug: there is a black screen before lanuchScreen on IOS

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/capacitor#4256]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.0.0-beta.3
  @capacitor/core: 3.0.0-beta.3
  @capacitor/ios: 3.0.0-beta.3

[success] iOS looking great! 👌

```

### Platform(s)

IOS

### Current Behavior

every time open APP there is a black screen before lanuchScreen on IOS

### Expected Behavior

When the APP is opened, the startup page is displayed directly, instead of displaying a black screen first, and then displaying the startup page

### Other Technical Details

`npm --version` output: 7.5.6

`node --version` output:  v14.15.4

`pod --version` output (iOS issues only): 1.10.1

**Comment by jcesarmobile** [comment]
https://github.com/ionic-team/capacitor/issues/3589
