### ISSUE TITLE
bug: npx cap add android brings old build.gradle file.

### ISSUE THREAD

**Issue by hm-lee** [ionic-team/capacitor#4257]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/core 2.4.6
  @capacitor/android 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/electron not installed
```

### Platform(s)

Android platform

### Current Behavior

The app/build.gradle file of the android template currently listed in the capacitor github has an add-option 'aaptOption' inside. However, the Android template installed with the npx cap add android command does not have that option. I think the old version of the template is being downloaded.

This issue disables normal operation of the js file when building a front-end template using nextjs with capacitorjs.

### Expected Behavior

I expected the same version of the template as the Android template on the GitHub to be downloaded.

### Code Reproduction

just use `npx cap add android`

### Other Technical Details

`npm --version` output: 7.5.2

`node --version` output: v14.8.0

**Comment by jcesarmobile** [comment]
those changes are only there on the Capacitor 3 template, not on the Capacitor 2 template
https://github.com/ionic-team/capacitor/blob/2.x/android-template/app/build.gradle
