### ISSUE TITLE
Android - Remove geolocation permission request from BridgeWebChromeClient

### ISSUE THREAD

**Issue by carlpoole** [ionic-team/capacitor#4261]
Google's analysis reveals the geolocation permission request during app submission and can result in apps being denied if targeted towards children or if Google doesn't want the app to use location services.

Provide a hook for plugins/native code to provide the permission check manually as needed. Needs documentation to support the change.

**Comment by jcesarmobile** [comment]
I tested and looks like as long as the app doesn't have geolocation permissions in the `AndroidManifest.xml` they pass validation, so it was probably a bad report. Closing for now.
