### ISSUE TITLE
What is the back button in Android supposed to do?

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#427]
The behaviour I personally expect is that it should traverse navigation history.

Found the following:

```
Implement Back Navigation for WebViews
If a part of your application is contained in a WebView, it may be appropriate for Back to traverse browser history. To do so, you can override onBackPressed() and proxy to the WebView if it has history state:

@Override
public void onBackPressed() {
    if (mWebView.canGoBack()) {
        mWebView.goBack();
        return;
    }

    // Otherwise defer to system default behavior.
    super.onBackPressed();
}
```

https://developer.android.com/training/implementing-navigation/temporal.html#back-webviews

At the moment the button does nothing on my app. How to implement the above?

**Comment by solojuve1897** [comment]
@mlynch It's a Vue.js-project. Still waiting for Ionic 4 to use that in the future. Can I do anything with my current setup to get the button to traverse the navigation history (at least going back one step)?

**Comment by mlynch** [comment]
Okay, fixed this and made it work with Ionic 3 which does rely on overriding the backbutton, while working with apps that use traditional routing. Also backwards compatible w/ cordova apps that rely on the backbutton event.

Will be in the next release!

**Comment by solojuve1897** [comment]
Cool. Can't wait to try it out! :-)
