### ISSUE TITLE
bug: Attempt to invoke virtual method 'boolean com.getcapacitor.PluginCall.isReleased()' on a null object reference

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#4277]
### Capacitor Version
beta 6

```
PASTE OUTPUT HERE
```

### Platform(s)
android

### Current Behavior
test app crash on after first install if clicking the "take picture and save" button, after the permission prompt, with error

`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.getcapacitor.PluginCall.isReleased()' on a null object reference`

### Expected Behavior

to not crash

### Code Reproduction

https://github.com/ionic-team/capacitor-testapp

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by theproducer** [comment]
Related: https://github.com/ionic-team/capacitor/issues/2837

**Comment by vaReliy** [comment]
Hi there!

I my project this bug still present. 

The same error (android) with option `allowEditing: true`

Pkg versions:
```
"@capacitor/android": "^3.0.0-beta.6",
"@capacitor/camera": "^0.4.2", 
"@capacitor/cli": "^3.0.0-beta.6",
"@capacitor/core": "^3.0.0-beta.6",
```

Original comment:
https://github.com/ionic-team/capacitor/issues/2837#issuecomment-786853074

Demo project:
https://github.com/vaReliy/cap3-camera-ex

[Full error text](https://github.com/vaReliy/cap3-camera-ex/blob/main/src/app/app.component.html)

**Comment by jcesarmobile** [comment]
This was fixed yesterday, latest beta is beta 6, which was released 6 days ago. Which means, this is not released yet.
