### ISSUE TITLE
bug: npm init @capacitor/app is broken for ios (3.0.0.beta-6)

### ISSUE THREAD

**Issue by sebdoby** [ionic-team/capacitor#4280]
### Capacitor Version @3.0.0-beta.6

when you use npm init @capacitor/app, the app is broken on IOS

### Platform(s)
IOS

### Current Behavior

When you create a new app with command:
npm init @capacitor/app and you add ios platform, you have an error when you launch the simulator (ex Iphone 11) and the device:

TypeError: undefined is not an object (evaluating 'Capacitor.Plugins.SplashScreen.hide')
⚡️  URL: capacitor://localhost/js/capacitor-welcome.js
⚡️  capacitor-welcome.js:7:37

### Expected Behavior
SplashScreen must be defined

### Other Technical Details
 @capacitor/cli@3.0.0-beta.6
├── @capacitor/core@3.0.0-beta.6
├── @capacitor/ios@3.0.0-beta.6
└── @capacitor/splash-screen@0.3.5

### Additional Context
if you rollback only the version of ios to @capacitor/ios@3.0.0-beta.1, no problem!
@capacitor/cli@3.0.0-beta.6
├── @capacitor/core@3.0.0-beta.6
├── **@capacitor/ios@3.0.0-beta.1**
└── @capacitor/splash-screen@0.3.5

**Comment by sebdoby** [comment]
Hello Team

Someone can see this regression ?

The impact is critical : all web apps created with init @capacitor/app have no plugin available on IOS since ios@3.0.0-beta.2

**Comment by mburger81** [comment]
@sebdoby we tried to generate a new app, and downgrade packages to beta1. version. But there is still the same error.
I think the problem is how init @capacitor/app is creating the scaffold, in this case we can not downgrade again.
But on the other side there is no way to create a new app passing the version we would like from the beginning,

do you have some ideas?

**Comment by sebdoby** [comment]
Hello Team,

@jcesarmobile : Any news to fix this bug ?

**Comment by sebdoby** [comment]
@mburger81 : 
To quick fix the problem on android waiting the official fix, you can use 3.0.0-rc.0 et replace the com.getcapacitor.JSExport.java in module capacitor-android with this:

`package com.getcapacitor;

import static com.getcapacitor.FileUtils.readFile;

import android.content.Context;
import android.text.TextUtils;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class JSExport {

    private static String CATCHALL_OPTIONS_PARAM = "_options";
    private static String CALLBACK_PARAM = "_callback";

    public static String getGlobalJS(Context context, boolean isDebug) {
        return "window.Capacitor = { DEBUG: " + isDebug + ", Plugins: {} };";
    }

    public static String getCordovaJS(Context context) {
        String fileContent = "";
        try {
            fileContent = readFile(context.getAssets(), "public/cordova.js");
        } catch (IOException ex) {
            Logger.error("Unable to read public/cordova.js file, Cordova plugins will not work");
        }
        return fileContent;
    }

    public static String getCordovaPluginsFileJS(Context context) {
        String fileContent = "";
        try {
            fileContent = readFile(context.getAssets(), "public/cordova_plugins.js");
        } catch (IOException ex) {
            Logger.error("Unable to read public/cordova_plugins.js file, Cordova plugins will not work");
        }
        return fileContent;
    }

    public static String getPluginJS(Collection<PluginHandle> plugins) {

        List<String> lines = new ArrayList<>();

        lines.add("// Begin: Capacitor Plugin JS");

        for (PluginHandle plugin : plugins) {
            lines.add(
                    "(function(w) {\n" +
                            "var a = (w.Capacitor = w.Capacitor || {});\n" +
                            "var p = (a.Plugins = a.Plugins || {});\n" +
                            "var t = (p['" +
                            plugin.getId() +
                            "'] = {});\n" +
                            "t.addListener = function(eventName, callback) {\n" +
                            "  return w.Capacitor.addListener('" +
                            plugin.getId() +
                            "', eventName, callback);\n" +
                            "}"
            );

            Collection<PluginMethodHandle> methods = plugin.getMethods();

            for (PluginMethodHandle method : methods) {
                if (method.getName().equals("addListener") || method.getName().equals("removeListener")) {
                    // Don't export add/remove listener, we do that automatically above as they are "special snowflakes"
                    continue;
                }

                lines.add(generateMethodJS(plugin, method));
            }
            lines.add("})(window);\n");
        }


        JSONArray pluginArray = new JSONArray();

        for (PluginHandle plugin : plugins) {
            pluginArray.put(createPluginHeader(plugin));
        }

        lines.add("window.Capacitor.PluginHeaders = " + pluginArray.toString() + ";\n");

        return TextUtils.join("\n", lines);

    }

    public static String getCordovaPluginJS(Context context) {
        return getFilesContent(context, "public/plugins");
    }

    public static String getFilesContent(Context context, String path) {
        StringBuilder builder = new StringBuilder();
        try {
            String[] content = context.getAssets().list(path);
            if (content.length > 0) {
                for (String file : content) {
                    builder.append(getFilesContent(context, path + "/" + file));
                }
            } else {
                return readFile(context.getAssets(), path);
            }
        } catch (IOException ex) {
            Logger.error("Unable to read file at path " + path);
        }
        return builder.toString();
    }

    private static JSONObject createPluginHeader(PluginHandle plugin) {
        JSONObject pluginObj = new JSONObject();
        Collection<PluginMethodHandle> methods = plugin.getMethods();
        try {
            String id = plugin.getId();
            JSONArray methodArray = new JSONArray();
            pluginObj.put("name", id);

            for (PluginMethodHandle method : methods) {
                methodArray.put(createPluginMethodHeader(method));
            }

            pluginObj.put("methods", methodArray);
        } catch (JSONException e) {
            // ignore
        }
        return pluginObj;
    }

    private static JSONObject createPluginMethodHeader(PluginMethodHandle method) {
        JSONObject methodObj = new JSONObject();

        try {
            methodObj.put("name", method.getName());
            if (!method.getReturnType().equals(PluginMethod.RETURN_NONE)) {
                methodObj.put("rtype", method.getReturnType());
            }
        } catch (JSONException e) {
            // ignore
        }

        return methodObj;
    }

    private static String generateMethodJS(PluginHandle plugin, PluginMethodHandle method) {
        List<String> lines = new ArrayList<>();

        List<String> args = new ArrayList<>();
        // Add the catch all param that will take a full javascript object to pass to the plugin
        args.add(CATCHALL_OPTIONS_PARAM);

        String returnType = method.getReturnType();
        if (returnType.equals(PluginMethod.RETURN_CALLBACK)) {
            args.add(CALLBACK_PARAM);
        }

        // Create the method function declaration
        lines.add("t['" + method.getName() + "'] = function(" + TextUtils.join(", ", args) + ") {");

        switch (returnType) {
            case PluginMethod.RETURN_NONE:
                lines.add(
                        "return w.Capacitor.nativeCallback('" +
                                plugin.getId() +
                                "', '" +
                                method.getName() +
                                "', " +
                                CATCHALL_OPTIONS_PARAM +
                                ")"
                );
                break;
            case PluginMethod.RETURN_PROMISE:
                lines.add(
                        "return w.Capacitor.nativePromise('" + plugin.getId() + "', '" + method.getName() + "', " + CATCHALL_OPTIONS_PARAM + ")"
                );
                break;
            case PluginMethod.RETURN_CALLBACK:
                lines.add(
                        "return w.Capacitor.nativeCallback('" +
                                plugin.getId() +
                                "', '" +
                                method.getName() +
                                "', " +
                                CATCHALL_OPTIONS_PARAM +
                                ", " +
                                CALLBACK_PARAM +
                                ")"
                );
                break;
            default:
                // TODO: Do something here?
        }

        lines.add("}");

        return TextUtils.join("\n", lines);
    }
}
`
I have merged old version and last version to retrieve the method "getPluginJS" which fill window.Capacitor.Plugins

I don't understand why it has been removed with the pluginHeader concept.

**Comment by sebdoby** [comment]
file joined is better
[JSExport.java.zip](https://github.com/ionic-team/capacitor/files/6197093/JSExport.java.zip)

**Comment by jcesarmobile** [comment]
this is no longer an issue on capacitor 3.0.0-rc.1
