### ISSUE TITLE
bug: iphone use writeFile(…)

### ISSUE THREAD

**Issue by todayandyesterday** [ionic-team/capacitor#4288]
hi:
I wrote the picture in Base64 to Documents, but I can't find the picture written in Album。
I hope God can answer it。thanks！
![1614825397(1)](https://user-images.githubusercontent.com/70627671/109903855-558c4100-7cd7-11eb-8a7b-989869ecc9e6.png)

**Comment by jcesarmobile** [comment]
answered on the discussion
https://github.com/ionic-team/capacitor/discussions/4287
