### ISSUE TITLE
Better error when webDir is not set up on npx cap add

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#430]
If you add a new platform but your webdir isn't configured properly, `update` will fail, which is confusing because then `npx cap open android` will lead to a gradle error with a missing `capacitor.settings.gradle` file

**Comment by jcesarmobile** [comment]
Closing as duplicate of https://github.com/ionic-team/capacitor/issues/232
BTW, what fails is copy, so update is not even run.
So we should change it for:
1. Show a better error message
2. Run update anyways
