### ISSUE TITLE
bug: android back button not working on capacitor 3 with ionic.

### ISSUE THREAD

**Issue by RaphaelWoude** [ionic-team/capacitor#4300]
### Capacitor Version

```
Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-beta.6
  @capacitor/core: 3.0.0-beta.6
  @capacitor/android: 3.0.0-beta.6
```

### Platform(s)

Android

### Current Behavior

The app closes when tapping the android back button instead of going back to the last route. In this case that's the tab1 route.

### Expected Behavior

The app should go to the last route when tapping the android back button. In this case that's the tab1 route.

### Code Reproduction

1. Clone: https://github.com/RaphaelWoude/Example
2. Run the following commands:
```
npm install
npm run build
npm run sync
npm run copy
npm run android
```
3. Build with android studio.
4. Start the app.
5. Click on the test button.
6. Press the hardware back button.

### Other Technical Details

`npm --version` output:
6.14.10
`node --version` output:
v14.15.4
`pod --version` output (iOS issues only):

### Additional Context

I have provided a v2 version branch of the app in the same repository. This one does exactly what the app should do by going back to the last route. 
Here is also a video running on version 3 that shows that the ionic back button works but as soon as I tap the android back button it closes the app.

https://user-images.githubusercontent.com/47354694/110136780-610f6300-7dd0-11eb-896c-d305e8f65f05.mp4

**Comment by jcesarmobile** [comment]
In Capacitor 3 the plugins have been moved out, so now you have to install the ones you need.

It's mentioned on the upgrade guide that ionic users need to install `@capacitor/app`, `@capacitor/haptics` and `@capacitor/keyboard`

https://capacitorjs.com/docs/v3/updating/3-0#migrating-your-app-to-use-the-new-official-plugin-packages

**Comment by RaphaelWoude** [comment]
I have added `@capacitor/app`, `@capacitor/haptics` and `@capacitor/keyboard` to the [app](https://github.com/RaphaelWoude/Example) and the android back button is still broken. Am I missing something?

**Comment by dennisameling** [comment]
Can confirm this isn't working in the demo repo provided (`v3` branch). The packages you mentioned have indeed been added and it doesn't seem to make any difference. Please do let us know if you need more info for reproducing @jcesarmobile 👍🏼

**Comment by anRoswell** [comment]
backbutton dont work, i try in capacitor 2.4.7 and not work...

**Comment by KirstenStake** [comment]
@RaphaelWoude I am experiencing this same issue. what was your fix?

**Comment by ZXERSTON** [comment]
Hi, have you resolved this issue? I upgrade to Capacitor 3.0, and the back button quits the app completely too.

**Comment by KirstenStake** [comment]
@ZXERSTON yes, what fixed it for me was installing the dependencies below (even if not referencing them directly in the app):

npm install @capacitor/app @capacitor/haptics @capacitor/keyboard @capacitor/status-bar

i had all of them already apart from @capacitor/app and as soon as I installed that one as well all was working again.

**Comment by manaskumar-syon** [comment]
npm install @capacitor/app @capacitor/haptics @capacitor/keyboard @capacitor/status-bar  


install all but getting error on device back button

device back button closes the app
