### ISSUE TITLE
feat: Support retrieval of NSNumber data types from iOS CAPPluginCall options

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor#4304]
### Description

There is no current shortcut to retrieve `NSNumber` data types from the CAPPluginCall options parameter. This data type should probably be supported. Sent a PR with a proposed resolution.

### Platform(s)

ios

### Preferred Solution

See PR: https://github.com/ionic-team/capacitor/pull/4303

**Comment by jcesarmobile** [comment]
this is now supported on latest release after https://github.com/ionic-team/capacitor/pull/4309 was merged
