### ISSUE TITLE
bug: ionic build creates empty capacitor.config.json also for cap@3.-beta.6

### ISSUE THREAD

**Issue by mburger81** [ionic-team/capacitor#4311]
### Capacitor Version

```
  @capacitor/cli: 3.0.0-beta.6
  @capacitor/core: 3.0.0-beta.6
  @capacitor/android: 3.0.0-beta.6
  @capacitor/ios: 3.0.0-beta.6
```

### Platform(s)
android & ios

### Current Behavior
We are testing the new capacitor 3, where the configuration file is a typescript file. But when we run **ionic build** there is always created a new capacitor.config.json file which in version 3 is not used any more.
If we run commands like **npx cap sync** the file is not created

Not sure if should open this on capacitor or ionic cli

**Comment by jcesarmobile** [comment]
ionic cli is still not ready for Capacitor 3

you can use the testing version that includes some Capacitor 3 changes `npm i @ionic/cli@testing`

if you find problems while using the testing version, please, report them on https://github.com/ionic-team/ionic-cli/issues

**Comment by mburger81** [comment]
This is still happening on final release

**Comment by jcesarmobile** [comment]
did you update @ionic/cli to latest version (6.16.1)?
The bug was there and I fixed it last week.

**Comment by mburger81** [comment]
Yes I did, perhaps the uncommited file was created in our project between updating cap3 and updating ionic cli

I tested it on a new project right now and it seems fine

thx

👍
