### ISSUE TITLE
feat: Add synchronous platform check

### ISSUE THREAD

**Issue by mesqueeb** [ionic-team/capacitor#4313]
### Description
In so many cases throughout my apps I need to implement different behaviour wether or not the user is in Android/iOS or on the web.

The issue is that its _only_ async currently:
```js
const { Device } = Plugins;

const info = await Device.getInfo();
console.log(info);
```

Especially the `operatingSystem` and `appVersion` I often need synchronously...

Is there any way we can have a synchronous method for these?

### Platform(s)
Web, iOS, android

### Preferred Solution
Synchronous platform check.

### Alternatives
I'm not sure, would love to know!

**Comment by IT-MikeS** [comment]
Would not reading the info using async await on app start then storing the info in something like a global state prop or some other global local storage then just referencing that stored info for your checks though-out the app, work?

So sudo code is:

- app starts
- first call before render is the async function to get system info and store globally
- every subsequent check that needs to be preformed references the global info. IE: `if globalInfo.operatingsystem equals iOS do X`

**Comment by jcesarmobile** [comment]
Inside `Capacitor` object there is a `platform` property.
In Capacitor 3, it will be a function `Capacitor.getPlatform()`

**Comment by mesqueeb** [comment]
@jcesarmobile thanks! this worked. however `platform` seems to be typed with just `string`.
Is there any way the next version can type it with a string literal instead? That way I can easier know how to write my if statements.
