### ISSUE TITLE
Splash Screen invalid when using CLI + documentation outdated

### ISSUE THREAD

**Issue by fikkatra** [ionic-team/capacitor#4316]
Using CLI & capacitor **v2.4.7**

**Observed behaviour:**
When creating a new app with the CLI (npx @capacitor/cli create), the default Splash Screen of the application is not rendering correctly:

- on iOS, a black screen is shown instead of the image (tested on simulator iPhone 12 Pro Max and real device iPhone X)
- on Android, the image is stretched (tested on emulator Pixel 3a API 28)

In addition, the official [documentation on Splash Screen](https://capacitorjs.com/docs/apis/splash-screen) points to an [example guide](https://www.joshmorony.com/adding-icons-splash-screens-launch-images-to-capacitor-projects/) that contains outdated documentation, as Launch Images are no longer supported on iOS. Instead, a Launch Screen Storyboard should be used (the CLI creates a default storyboard).

**Expected behaviour:** 
The CLI should create a working storyboard for iOS and a 9-patch file for Android (or alternatively, provide configuration that renders the splash screens correctly, i.e. not stretched).

**Comment by jcesarmobile** [comment]
Despite the blog talks about "launch images" it's really using the assets of the launch storyboard. 
The black screen problem is an iOS 14 bug already reported https://github.com/ionic-team/capacitor/issues/3589
The images stretched on some devices on Android is also a know problem, but the splash images used by default are supposed to be replaced by the users, so we won't be doing any work on that.
