### ISSUE TITLE
bug: Plugins seems not to be loaded @cap3

### ISSUE THREAD

**Issue by mburger81** [ionic-team/capacitor#4323]
### Capacitor Version

```
  @capacitor/core: 3.0.0-rc.0
  @capacitor/cli: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0
```

### Platform(s)
android

### Current Behavior
we tried to build a simple capacitor app outside of angular, starting from a plain cap javascript scaffold doing like described in the documentation

```
npm init @capacitor/app
cd testapp
npm install
npx cap sync
npm install @capacitor/android@next
npm install @capacitor/ios@next
npx cap add android
npx cap add ios
npx cap sync
```

this should a plain capacitor app with javascript, no bundler or something else.

If we run this android app we run into this issue:
`Cannot read property 'hide' of undefined`

It seems now capacitor plugin expecting WebView is loaded and the issue is comming from **SplashScreen** is not available.
`Capacitor.Plugins.SplashScreen.hide();`

![image](https://user-images.githubusercontent.com/3778892/110796449-40d02000-8278-11eb-98ee-766c4c7aec6c.png)

We tried also other Plugins with always the same result. Looking from the documentation anything seems fine, and also it is already not working from the default starter project.
We have not tested it for ios, but only for android

Is it the same issue as #4218?

### Other Technical Details

`npm --version` output: 6.14.11

`node --version` output: v14.15.5

`pod --version` output (iOS issues only): 1.10.1

**Comment by jcesarmobile** [comment]
it's the same as https://github.com/ionic-team/capacitor/issues/4280
