### ISSUE TITLE
bug: error running capacitor ionic app from XCode

### ISSUE THREAD

**Issue by haikyuu** [ionic-team/capacitor#4328]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/android: 3.0.0-rc.0
  @capacitor/cli: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
- iOS

### Current Behavior

After running `ionic cap run ios -l --external`, Xcode opens up and when I run in simulator:
![image](https://user-images.githubusercontent.com/8558836/110920806-1d5fb080-831e-11eb-8e2c-e6fcb8859490.png)

### Expected Behavior
Build should succeed

### Other Technical Details
`npm --version` output: `6.14.10`

`node --version` output: `v14.15.4`

`pod --version` output (iOS issues only): `1.10.1`

### Additional Context
`npx cap run ios` works fine and here is its output:
```
✔ Copying web assets from build to ios/App/App/public in 882.85ms
✔ Creating capacitor.config.json in ios/App/App in 1.49ms
⠇ copy ios [info] Found 1 Cordova plugin for ios:
       cordova-plugin-firebase-analytics@4.5.0
✔ copy ios in 1.19s
✔ Updating iOS plugins in 22.16ms
[info] Found 5 Capacitor plugins for ios:
       @capacitor/app@0.3.6
       @capacitor/haptics@0.3.6
       @capacitor/keyboard@0.5.6
       @capacitor/push-notifications@0.3.6
       @capacitor/storage@0.3.6
⠙ update ios [info] Found 1 Cordova plugin for ios:
       cordova-plugin-firebase-analytics@4.5.0
✔ Updating iOS native dependencies with pod install in 19.63s
[info] Found 1 incompatible Cordova plugin for ios, skipped install:
       cordova-support-android-plugin@1.0.2
✔ update ios in 19.83s
✔ Please choose a target device: › iPhone 12 Pro (simulator) (D411778A-A01C-48A6-81A7-C3C1976172B3)
✔ Running xcodebuild in 32.37s
✔ Deploying App.app to D411778A-A01C-48A6-81A7-C3C1976172B3 in 35.84s
```

**Comment by jcesarmobile** [comment]
what's your Xcode version?

**Comment by haikyuu** [comment]
`Version 12.4 (12D4e)`

**Comment by jcesarmobile** [comment]
It should work then, can you provide a sample app?

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by haikyuu** [comment]
I was able to fix it by deleting `./ios/DerivedData` folder. It was containing conflicting files from using capacitor 2. I think the target version upgrade caused it. We might want to add that to the upgrade guide.

Thanks @jcesarmobile

**Comment by skotturi** [comment]
@haikyuu do you have a working version of how to use `PushNotifications` plugin with capacitor v3. I've been trying to get the breaking changes from `requestPermission()` to `requestPermissions()` but running into type issues. Would love to see a working example! 

![image](https://user-images.githubusercontent.com/4960284/110994768-25275100-832e-11eb-8959-d23f29a84e94.png)

**Comment by skotturi** [comment]
swapping to: `if (result.receive === 'granted') { ... }` works. I was confused by the docs, thinking result was of type PermissionStatus but I believe PermissionStatus is the promise which returns an object with receive which is a PermissionState. 
This ended up working:
```
        PushNotifications.requestPermissions().then(
          (result: {receive: PermissionState}) => {
            console.log('[NOTIFICATIONS] permission: ', result);
            if (result.receive === 'granted') {
```
