### ISSUE TITLE
bug: Capacitor platform detection works wrong if html and js stored in Filesystem

### ISSUE THREAD

**Issue by DmitrySkripkin** [ionic-team/capacitor#4329]
## Bug Report
I save html and js to Filesystem (html and bundled js with Capacitor dependency included), then I use `location.replace('Capacitor.convertFileSrc('some_file_url.html'))`. Everything works as expected, no errors. But after location replace to on Android platform is not detected correctly. I tried different `capacitor.config.json` options to fix this, but no success yet. Looks like WebView restricts something when using local files.

### Capacitor Version
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    capacitor-secure-storage-plugin (0.5.0)
[success] iOS looking great! 👌
```

### Platform(s)
Android 9.x, but i believe any other version works too

### Current Behavior
`Capacitor.platform === 'web'` and `Capacitor.isNative === false`

### Expected Behavior
`Capacitor.platform === 'android'` and `Capacitor.isNative === true`

**Comment by jcesarmobile** [comment]
I can't reproduce.

A few points: 
- `Capacitor.convertFileSrc('some_file_url.html')` just returns `some_file_url.html`, you don't need to use convertFileSrc to redirect to a local file.
- Make sure `some_file_url.html` has a `<head>` tag, if there isn't one Capacitor's bridge doesn't get injected and uses the web plugins, looks like that's what is happening here.
https://capacitorjs.com/docs/getting-started#adding-capacitor-to-an-existing-web-app

**Comment by DmitrySkripkin** [comment]
Thanks for quick reply, I checked everything again - no success.
I have [minimal example here](https://github.com/DmitrySkripkin/capacitor_example).

Just install node modules, run webpack and add platforms.
```
npm i

npx cap add ios
npx cap add android

npx webpack
npx cap sync
npx cap open ios
npx cap open android
```

When I run application on iOS it works as expected:
[x] .html file is written to Filesystem
[x] redirected to file from Filesystem
[x] `Capacitor.platform === 'ios'`

When I ran application on Android it doesn't:
[x] .html file is written to Filesystem
[x] redirected to file from Filesystem
[ ] `Capacitor.platform === 'android'`

**Comment by DmitrySkripkin** [comment]
@jcesarmobile, do I have to create new issue?

**Comment by jcesarmobile** [comment]
Yeah, I missed the part where you were saving the file using Filesystem plugin. By the example code it looked like the file was in the `public` folder.

That use case is not supported, if you use `convertFileSrc` in a filesystem url it will return a url with `_capacitor_file_` on it, and urls with that in the path won't get Capacitor scripts injected (by design).

If you want to load html files from the filesystem, you have to use `WebView` plugin to set a base path, instead of doing the `indow.location.replace` do `Capacitor.Plugins.WebView.setServerBasePath({path:'/storage/emulated/0/Documents/'})`.

I would recommend not using Documents folder on Android, it's not local to your app, any app can read/write there and can change the purpose of your app.

**Comment by DmitrySkripkin** [comment]
Thanks for explanation. `Capacitor.Plugins.WebView.setServerBasePath()` might be the solution for me.
BTW, I don't see any mention of WebView Plugin in the [docs](https://capacitorjs.com/docs/apis).

**Comment by DmitrySkripkin** [comment]
Yep, `Capacitor.Plugins.WebView.setServerBasePath()` is much better than my solution with `location.replace()`. Hopefully we can update docs (maybe i should contribute), so nobody will have to spend hours debugging :)
Thanks again, this saved my day.
