### ISSUE TITLE
feat: update xmldom dependency

### ISSUE THREAD

**Issue by hardmaster92** [ionic-team/capacitor#4337]
### Description
I hope this is the correct form for reporting an issue like this. After installing the new version of capacitor, npm detected vulnerability. It's a low severity vulnerability but yet it should be fixed before getting worse.

```
  Low             Misinterpretation of malicious XML input                      
  Package         xmldom                                                        
  Patched in      >=0.5.0                                                       
  Dependency of   @capacitor/cli [dev]
  Path            @capacitor/cli > plist > xmldom
  More info       https://npmjs.com/advisories/1650
```

### Platform(s)
Web (bot probably applies to all)

### Preferred Solution
Update the xmldom package to version 0.5.0 or higher as suggested in the npm audit security report

**Comment by jcesarmobile** [comment]
this has to be fixed on plist package, we are using latest plist version available

**Comment by nathanb21** [comment]
https://github.com/TooTallNate/plist.js/issues/105
