### ISSUE TITLE
cordova-plugin-email-composer incompatible Cordova plugin for android, skipped install

### ISSUE THREAD

**Issue by jlunaoax** [ionic-team/capacitor#4347]
Task :capacitor-cordova-android-plugins:compileDebugJavaWithJavac FAILED
android/capacitor-cordova-android-plugins/src/main/java/de/appplant/cordova/emailcomposer/Provider.java:22: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;

**Comment by jcesarmobile** [comment]
https://capacitorjs.com/docs/v3/android/troubleshooting#error-package-androidsupport-does-not-exist
