### ISSUE TITLE
Bug: capacitor-camera not working in iOS

### ISSUE THREAD

**Issue by Schneider96** [ionic-team/capacitor#4350]
### Capacitor Version 
2.4.2

### Platform
iOS 14.4

### Tested devices
iPhone XR, iPhone 11, iPhone 12

### Current Behaviour
I use capacitor 2.4.2 with Angular and Ionic Appflow for Cloud Build. The camera was setup as said in the official docs and implemented as seen below. When starting the camera over the button I get an error "No camera found" and the close button is hidden behind the status bar. The button can't be pressed and it's only possible to take a picture with "Choose image" and then select the System Camera.

`const image = await Camera.getPhoto({ resultType: CameraResultType.DataUrl });`
`this.image = image.dataUrl;`

![40407 (1)](https://user-images.githubusercontent.com/30416770/111307522-dc3b0980-8659-11eb-9e21-fd15b5dc664e.jpg)

### Expected Behavior
The camera is shown without status bar overlap and I see a preview of the camera.

**Comment by jcesarmobile** [comment]
You are using the web version of the plugin, not the native version.
Web version uses `getUserMedia`, which is not available on the WKWebView, that's why it says there is no camera available.
Hard to tell what are you doing wrong to use the web version with the little information you provided.

**Comment by Schneider96** [comment]
How can I switch to native version. Which information do you need to further assist?

**Comment by jcesarmobile** [comment]
a sample app
