### ISSUE TITLE
npm audit shows plist > xmldom has vulnerable dependencies

### ISSUE THREAD

**Issue by SilentEsper** [ionic-team/capacitor#4359]
│ low           │ Misinterpretation of malicious XML input                     │
    ├───────────────┼──────────────────────────────────────────────────────────────┤
    │ Package       │ xmldom                                                       │
    ├───────────────┼──────────────────────────────────────────────────────────────┤
    │ Patched in    │ >=0.5.0                                                      │
    ├───────────────┼──────────────────────────────────────────────────────────────┤
    │ Dependency of │ @capacitor/cli                                               │
    ├───────────────┼──────────────────────────────────────────────────────────────┤
    │ Path          │ @capacitor/cli > plist > xmldom                              │
    ├───────────────┼──────────────────────────────────────────────────────────────┤
    │ More info     │ https://www.npmjs.com/advisories/1650                        │
    └───────────────┴──────────────────────────────────────────────────────────────┘
    1 vulnerabilities found - Packages audited: 2374
    Severity: 1 Low
    Done in 2.18s.

**Comment by jcesarmobile** [comment]
https://github.com/ionic-team/capacitor/issues/4337
