### ISSUE TITLE
feat: Provide documentation on how to embed capacitor 3 into an existing native app.

### ISSUE THREAD

**Issue by sundeepdev** [ionic-team/capacitor#4370]
## Feature Request
Provide documentation on how to embed capacitor into an existing native app.

### Description
Provide documentation on how to embed capacitor into an existing native app.
Some native app may need to present capacitor powered webview.
This would be with a capability of native <-> web interaction.
It was mentioned in 2019 that capacitor 3 may have that capability. Is it a possibility now?
Worst case can it be done with Ionic Cordova stack as Cordova does support this feature.

### Platform(s)

- [ ] iOS
- [ ] Android

**Comment by fkirc** [comment]
I would like to support this issue 👍 
I am already using Capacitor-3.0.0-rc.0 in an embedded capacity, and things are still unclear.

My preliminary results:
- iOS works similar to Capacitor 2.X.
- Android's embedded "BridgeFragment" seems to be broken right now, see https://github.com/ionic-team/capacitor/issues/4343 for more details.

**Comment by jthoms1** [comment]
We have a separate effort underway for using Capacitor in Native applications. We will provide more info on the topic in coming months. This effort is a commercialization and will not be made available as open source.

**Comment by fkirc** [comment]
I have launched a parallel effort with the release of https://github.com/fkirc/embedded-capacitor.
It is good to hear that some work is being done, but I believe that we need an immediate short-term solution that works right now, which is why https://github.com/fkirc/embedded-capacitor is available on npm right now.
