### ISSUE TITLE
bug: Documentation is incorrect regarding triggering events from native to JS

### ISSUE THREAD

**Issue by daveshirman** [ionic-team/capacitor#4375]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
```

### Platform(s)
Android / Web / iOS not tested

### Current Behavior
Following example is an audio player. This plugin `RemoteAudioPlugin` was generated following the V3 docs.  I did nothing differently.  Everything is fine, except events from native Java back to JS.

1) Java does not compile when written as stated in the documentation here, i.e no extra info on extending classes or whatever: https://capacitorjs.com/docs/v3/core-apis/ios#triggerjsevent

2) If I add to my class definition `extends Plugin` so that it will at least compile, then when it tries to fire the event, I get a fatal exception:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.Bridge.triggerWindowJSEvent(java.lang.String)' on a null object reference
```

### Example code

Note: 
[Plugin classes Java.zip](https://github.com/ionic-team/capacitor/files/6171599/Plugin.classes.Java.zip)

I've attached my test plugin for reference.

```
public class RemoteAudio extends Plugin {

    boolean wasPaused = false;
    final MediaPlayer mp = new MediaPlayer();

    public boolean play(String url) {
        try {
            Log.i("RemoteAudio:", "play");

            mp.start();
            wasPaused = false;

            mp.setOnCompletionListener(mediaPlayer -> {
                wasPaused = false;
                Log.i("RemoteAudio:", "finished playing");
                bridge.triggerWindowJSEvent("finishedPlaying");
            });

            return mp.isPlaying();

        }
        catch (Exception e) {
            Log.i("RemoteAudio:", "play failed");
        }

        return false;
    }

}
```

### Expected Behavior
1) App should not crash sending events to JS layer/

2) Documentation should CLEARLY show how to trigger events from plugin to JS, with necessary import statements, class extensions applied to the respective java/m files etc.

**Comment by jcesarmobile** [comment]
I'm curious, why are you looking at iOS docs while working on Android?

The iOS docs error is already reported https://github.com/ionic-team/capacitor/issues/2852

**Comment by daveshirman** [comment]
I am not, I simply pasted the wrong link from the search field.  This should not be closed without discussion.

**Comment by jcesarmobile** [comment]
Read the linked issue and the Android docs.
Despite it's a string, it should be convertible to JSON, your sample code isn't, the Android docs example is convertible, the iOS example isn't.
There is another issue about it, feel free to subscribe and chime in.

**Comment by daveshirman** [comment]
I did read the issue, it's nothing to do with what I'm saying.

Read my explanation again, you are incorrectly assuming what the problem is here.

I'm saying that simply following the Android docs and trying to trigger a JS event doesn't work, it either doesn't compile, or it crashes depending on how you set it up.

I'm not passing any data at all.

**Comment by jcesarmobile** [comment]
Apart from extending `Plugin` class, you also need the `@CapacitorPlugin` annotation, which you don't have on the class that triggers the event, which is probably why the bridge is null and causes a null pointer exception.

But `RemoteAudio` is supposed to be an implementation class, not a `Plugin` subclass, so you shouldn't extend `Plugin` there at all, you should fire the events from the `RemoteAudioPlugin` class, which is a proper `Plugin` class with the `@CapacitorPlugin` annotation, and you shouldn't have 2 `Plugin` classes.

Using the implementation class is not mandatory, you can just remove it and do all the work on `RemoteAudioPlugin`, but if you do, you'll have to create a way of communicating the plugin class and the implementation class.

**Comment by daveshirman** [comment]
Right! So I have just removed the implementation class entirely and done as suggested.  The event now fires and connects to JS as expected.

So the issue here is that the docs are not clear.  Also, that implementation class was auto-generated and I expected I was supposed to use it.

Please ensure that the docs are amended, thanks for your help.
