### ISSUE TITLE
bug: IllegalStateException during app-initialization related to BroadcastReceiver of notification-plugin

### ISSUE THREAD

**Issue by fkirc** [ionic-team/capacitor#4379]
### Capacitor Version

This bug only affects Capacitor 2.X (it is solved with 3.X).
Nevertheless, I still report it because it may affect a large number of users.

```
@capacitor/android 2.4.7
@capacitor/cli 2.4.7
@capacitor/core 2.4.7
```

### Platform(s)

Android

### Current Behavior

The bug can lead to a high number of `IllegalStateException`s that are reported by Google Play Console.
It happens during app-initialization before any Activity is launched, presumably via a BroadcastReceiver that is included _by default_ within Capacitor 2.X. 
A broadcast receiver seems to initialize the app while the screen seems to be locked, which triggers a crash when trying to access shared preferences.
Not all apps are affected, but I assume that many apps need to access shared preferences during initialization.

Please see https://stackoverflow.com/questions/53823032/pie-only-sharedpreferences-illegalstateexception for more details.
Stacktraces in Google Play Console are looking similar to the following:

> java.lang.RuntimeException: 
>   at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5876)
>   at android.app.ActivityThread.access$1100 (ActivityThread.java:199)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1650)
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>   at android.os.Looper.loop (Looper.java:193)
>   at android.app.ActivityThread.main (ActivityThread.java:6669)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
> Caused by: java.lang.IllegalStateException: 
>   at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:419)
>   at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:404)
>   at android.content.ContextWrapper.getSharedPreferences (ContextWrapper.java:174)
>   at com.nbc.news.utils.SharedPreferences.<init> (SharedPreferences.java:27)
>   at com.nbc.news.utils.SharedPreferences.init (SharedPreferences.java:44)
>   at com.nbc.news.NbcNews.onCreate (NbcNews.java:122)
>   at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1154)
>   at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5871)

Capacitor 2.X contains the following [AndroidManifest.xml](https://github.com/ionic-team/capacitor/blob/2.x/android/capacitor/src/main/AndroidManifest.xml) in the path `node_modules/@capacitor/android/capacitor/src/main/AndroidManifest.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.getcapacitor.android">
    <uses-feature android:name="android.hardware.camera"
        android:required="false" />

    <application>
        <service android:name="com.getcapacitor.plugin.background.BackgroundTaskService" android:exported="false" />
        <receiver android:name="com.getcapacitor.plugin.notification.TimedNotificationPublisher" />
        <receiver android:name="com.getcapacitor.plugin.notification.NotificationDismissReceiver" />
        <meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false" />
        <service android:name="com.getcapacitor.CapacitorFirebaseMessagingService" android:stopWithTask="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <receiver android:name="com.getcapacitor.plugin.notification.LocalNotificationRestoreReceiver" android:directBootAware="true" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED"/>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
            </intent-filter>
        </receiver>
    </application>

    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
</manifest>
```

In this Manifest, we see a suspicious BroadcastReceiver that is related to the plugin `com.getcapacitor.plugin.notification`, and I guess that many Capacitor-users are not even using this notification-plugin.
If we replace this Manifest with the following content, then the crashes seem to disappear:

````xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.getcapacitor.android">
</manifest>
````

### Expected Behavior

No crashes.

### Code Reproduction

I cannot guarantee reproduction, but you can solve the problem by replacing Capacitor with my new fork https://github.com/fkirc/embedded-capacitor.

**Comment by BigBerny** [comment]
This is still an issue with Capacitor 3
