### ISSUE TITLE
feat: Add a way so "cap copy" does not copy the sourcemaps into the Android / iOS project

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/capacitor#4381]
### Description

When using sentry you have to generate sourcemaps e.g. `ionic build --prod --source-map` When running `cap copy` these generated sourcemaps are copied into the Android/iOS project which increase the final build size.

### Platform(s)

n/a

### Preferred Solution

An `--ignore *.js.map` or something similar could help with this.

**Comment by jcesarmobile** [comment]
Copy copies the full webDir, what’s on the webDir is up to you
