### ISSUE TITLE
R ‘UIWebView’ is deprecated: first deprecated in iOS 12.0 - No longer supported 

### ISSUE THREAD

**Issue by AnasProgrammer2** [ionic-team/capacitor#4393]
hello , i am try to build my app for IOS but i get this message warning 

‘UIWebView’ is deprecated: first deprecated in iOS 12.0 - No longer supported; please adopt WKWebView.

Why i get this warning error and i am using capacitor so it must by default is using WKWebView?

**Comment by jcesarmobile** [comment]
Some plugin you use is still using UIWebView, make sure all of them are up to date and if some of them have not been updated for a long time review their github repositories in case they have issues open about it.

**Comment by AnasProgrammer2** [comment]
> Some plugin you use is still using UIWebView, make sure all of them are up to date and if some of them have not been updated for a long time review their github repositories in case they have issues open about it.

hello , how to update all plugin to last-update
