### ISSUE TITLE
Geolocation failure in Android 11 (API 30)

### ISSUE THREAD

**Issue by ebellempire** [ionic-team/capacitor#4406]
Targeting SDK 30 will be required starting in August 2021. Right now, as far as I can tell, the Geolocation plugin (Capacitor 2.4.7) is not functional in that environment, presumably because it asks for both foreground and background location in the same permissions request (see below). Is there (or will there be) a way for app devs to request only "while in use..." permissions? Or is there some other issue here?

From the Android documentation:
>“Caution: If your app targets Android 11 (API level 30) or higher, the system enforces this best practice [asking for foreground and background access in separate requests]. If you request a foreground location permission and the background location permission at the same time, the system ignores the request and doesn’t grant your app either permission.” – [Source](https://developer.android.com/training/location/permissions)

Related post from Ionic Forum:
https://forum.ionicframework.com/t/geolocation-fails-in-android-11-api-30/207332/3

**Comment by jcesarmobile** [comment]
Capacitor doesn't support background geolocation nor request its permission, only foreground location.
If you use some plugin that uses background location it would need to be updated.

I've tested Capacitor's Geolocation plugin and works fine on Android 11 devices when targeting SDK 30.

**Comment by ebellempire** [comment]
@jcesarmobile, thanks for the clarification on the Ionic Forum and apologies for the dumb oversight (of not having Google Play Services installed on the emulator in question).

**Comment by jcesarmobile** [comment]
Well, it's not really well documented that it uses google services under the hood, so it's our fault. On Capacitor 3 docs it's mentioned now.
