### ISSUE TITLE
bug: v3 AppFlow auto-updates do not get applied

### ISSUE THREAD

**Issue by lzoubek** [ionic-team/capacitor#4419]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0
  @capacitor/cli: 3.0.0-rc.0

[error] Xcode is not installed
[success] Android looking great! 👌

```

### Platform(s)

android, ios

### Current Behavior

AppFlow auto-updates do not get applied. 

I am using `cordova-plugin-ionic` to auto-update app, when plugin downloads update it tries to reload app. But app reload does not occur, after I restart app, it still runs original code, but it should run latest code pulled from AppFlow

### Expected Behavior

AppFlow auto-update gets correctly applied and restarts application which starts to serve updated code.

### Additional Context

The issue is in  `Deploy.reloadApp()` which relies on `Ionic.WebView.setServerBasePath`. `Ionic.WebView` object seems to be provided by capacitor, but the implementation is missing. As the result `Ionic.WebView.setServerBasePath` has no effect, `Ionic.WebView.getServerBasePath()` returns `undefined`. 

I think `Capactior.Plugins.WebView` should be populated. `Capacitor.isPluginAvailable('WebView')` returns `true` but `Capacitor.Plugins.WebView` returns `undefined` instead of Proxy

**Comment by chetanbansal019** [comment]
Had raised a [discussion](https://github.com/ionic-team/capacitor/discussions/4387#discussion-3286499) for the same problem

Here is the test code repository where the issue can be reproduced.
[Repository](https://github.com/chetanbansal019/testappflow)

**Comment by jcesarmobile** [comment]
should be fixed on rc.1
