### ISSUE TITLE
bug: ionic build creates capacitor.config.json when using ts version

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/capacitor#4422]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0
```

### Current Behavior

I'm unsure if this is an Capacitor or Ionic CLI Bug. I have a `capacitor.config.ts` to configure my Capacitor v3 Project. Running **ionic build** always creates a `capacitor.config.json` with an empty JSON at project base directory.

### Expected Behavior

To not create this File.

### Other Technical Details

`npm --version` output: 7.6.3

`node --version` output: v14.15.4

`pod --version` output (iOS issues only):

### Additional Context

**ionic info**
```
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1102.4
   @angular-devkit/schematics    : 11.2.4
   @angular/cli                  : 11.2.4
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 3.0.0-rc.0
   @capacitor/core : 3.0.0-rc.0

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : 1.3.0

System:

   NodeJS : v14.15.4 (/usr/local/bin/node)
   npm    : 7.6.3
   OS     : macOS Big Sur

```

**Comment by jcesarmobile** [comment]
Ionic CLI needs to be updated to properly support Capacitor 3
there is a "testing" version that has some initial support
`npm install -g @ionic/cli@testing`
