### ISSUE TITLE
bug: linuxAndroidStudioPath in capacitor.config.json only allows absolute paths

### ISSUE THREAD

**Issue by notbryan** [ionic-team/capacitor#4423]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌

### Platform(s)

Android

### Current Behavior

The linuxAndroidStudioPath option in capacitor.config.json only allows absolute paths to studio.sh. It will produce incorrect output when a relative path is used.

### Expected Behavior

Either the linuxAndroidStudioPath option should allow both absolute and relative paths to studio.sh or a fix would be needed in both the documentation and the relevant message to note this.

### Code Reproduction

Please try both an absolute and a relative path to studio.sh in the linuxAndroidStudioPath option.

**Comment by jcesarmobile** [comment]
Capacitor 3 won't use the `linuxAndroidStudioPath` config option anymore, so we won't fix this in Capacitor 2.
