### ISSUE TITLE
bug: @capacitor/cli create checks directory existence at an incorrect moment

### ISSUE THREAD

**Issue by notbryan** [ionic-team/capacitor#4424]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

```

### Platform(s)

All

### Current Behavior

Currently, while creating a new project using `@capacitor/cli create `, it displays an error after selecting the npm client if a directory to deploy the project already exists.

### Expected Behavior

The error-handling should happen after entering the directory for the new app. If it doesn't exists, it should continue. If it does, it should show the error.

### Code Reproduction

1. Create an directory (named _test_ for this purpose)
2. Run `npx @capacitor/cli create`
3. Enter proper values for the first two questions
4. When asked for a _Directory for new app_, enter the directory from step 1
5. An error should be displayed at this stage.

**Comment by jcesarmobile** [comment]
`@capacitor/cli create` command is gone in Capacitor 3, so we won't be fixing this in Capacitor 2
