### ISSUE TITLE
bug: Android Cordova Plugins Module Kotlin Support

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/capacitor#4426]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
```

### Platform(s)

- Android

### Current Behavior

I'm currently integrating a Cordova Plugin into my Capacitor Project. This Plugin uses a Library written in Kotlin, so i can't build my App as Kotlin is not defined in this Module. 

Temp Workaround: Open **Android Studio** --> **Tools** --> **Kotlin** --> **Configure Kotlin in Project**. Then select the "capacitor-cordova-android-plugins" Module and configure. This adds three Lines in to the Module which are needed to make this work.

But after an "npx cap sync" the File is resetted. 

### Expected Behavior

As i want to build my App with Appflow later this Workaround is not really working for me. A Option to automatically configure Kotlin in this Module would be needed here.

### Code Reproduction

If you want to try, i'm using this Plugin (my own): https://github.com/EinfachHans/cordova-plugin-advanced-imagepicker

### Other Technical Details

`npm --version` output: 7.6.3

`node --version` output: v14.15.4

**Comment by EinfachHans** [comment]
Can some check this? This is really annoying for me and my CI builds

**Comment by jcesarmobile** [comment]
Implemented on https://github.com/ionic-team/capacitor/pull/5438
