### ISSUE TITLE
bug: hook "capacitor:sync:after":"./hooks/file.js" not working after calling npm cap sync

### ISSUE THREAD

**Issue by bhandaribhuminpfizer** [ionic-team/capacitor#4430]
I am trying to replace file contains using HOOK, file.js but hook is not run.

My goal is : after `npx cap sync` i want to call file.js but non was call.

my ionic.config.json
```
 "hooks": {
    "capacitor:sync:after":"./hooks/capacitor/update_androidx_imports.js" // "build:after" works but "capacitor:sync:after" not works
  }
```

NOTE: Also I wan to run this on my CI piplin some idea

**Comment by jcesarmobile** [comment]
Capacitor doesn't provide any hooks 

there is a feature request here https://github.com/ionic-team/capacitor/issues/3593
