### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Errabaany** [ionic-team/capacitor#4435]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/android 2.4.7
  @capacitor/core 2.4.7
```

### Platform(s)
Android (I didn't test in any other platform)

### Current Behavior
cannot find symbol import com.getcapacitor.PermissionState;
symbol:   class PermissionState
location: package com.getcapacitor

<!----------------------------------------------------!>

I'm using the the plugin FileSystem which is provided on capacitor v2 documentations 
but the plugin have decencies:  PermissionState which is provided only in version 3 Beta

is there anyway to fix this ?

`npm --version` : 6.4.1

`node --version` : v10.15.1

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Filesystem is a Capacitor 3 plugin.
In Capacitor 2, Filesystem was part of Capacitor itself, we moved all plugins out in Capacitor 3.
