### ISSUE TITLE
bug: Camera Becomes Unresponsive on Android Chrome

### ISSUE THREAD

**Issue by stefanhk31** [ionic-team/capacitor#4436]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.4.7     
  @capacitor/core: 2.4.7    
  @capacitor/android: 2.4.7 
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7     

Installed Dependencies:

  @capacitor/cli 2.4.3
  @capacitor/android 2.4.3
  @capacitor/core 2.4.3
  @capacitor/ios 2.4.3
  @capacitor/electron not installed
```

### Platform(s)
Web (only on Android device)

### Current Behavior
When using the camera plugin in Chrome on an Android device, the app becomes unresponsive after clicking on any of the camera buttons. Camera works as expected on Android Firefox and on native platforms.

### Expected Behavior
Camera should respond on Android Chrome like it does on other clients/platforms.

### Code Reproduction
https://github.com/stefanhk31/photo-gallery
--This app was created using [Ionic's guide](https://ionicframework.com/docs/angular/your-first-app)

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v14.15.1

`pod --version` output (iOS issues only):

### Additional Context
Video of bug:
https://user-images.githubusercontent.com/42074868/113597905-60a1fc00-960a-11eb-8a49-e3acba0c9647.mp4

**Comment by jcesarmobile** [comment]
what's the Android version of the device?

**Comment by stefanhk31** [comment]
@jcesarmobile Version 11.

**Comment by jcesarmobile** [comment]
this is a pwa-elements bug, it's already reported
https://github.com/ionic-team/pwa-elements/issues/77
