### ISSUE TITLE
bug:  Error: "Haptics" plugin is not implemented on android     

### ISSUE THREAD

**Issue by Rosadojonathan** [ionic-team/capacitor#4447]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0
```
### Platform(s)

Android

### Current Behavior

I get an "Error: "Haptics" plugin is not implemented on android     " error when I try to use the Haptics plugin after updating capacitor to v3 since it didn't seem to work on v2

### Expected Behavior

Haptics should work on android

### Code Reproduction

https://github.com/Rosadojonathan/capacitor-haptics-bugreport
run
```yarn dev:android```
Run it on an Android phone, open chrome remote device debugger, console shows  "Error: "Haptics" plugin is not implemented on android " when clicking on "haptic test" button

### Other Technical Details

`npm --version` output: 

`node --version` output: 12.4.0

`pod --version` output (iOS issues only):

### Additional Context

https://github.com/ionic-team/capacitor/issues/3406 this issue suggested that by upgrading to capacitor v3 I would have Haptics work on android but it doesn't seem to be the case after upgrading

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Rosadojonathan** [comment]
Here's the link to reproduce the bug: https://github.com/Rosadojonathan/capacitor-haptics-bugreport
Run
``` yarn dev:android```

**Comment by jcesarmobile** [comment]
Since Capacitor 3 has moved plugins out, you need to register them in order to work by adding the plugin in the init method like `add(HapticsPlugin.class);`

Or even better, enable the automatic plugin registration by deleting the init method or the whole onCreate

https://github.com/Rosadojonathan/capacitor-haptics-bugreport/blob/main/src-capacitor/android/app/src/main/java/org/capacitor/quasar/app/MainActivity.java#L16-L19

**Comment by merganon** [comment]
@jcesarmobile (sorry for pinging)
What about iOS?

My MainActivity.java looks like this:
```
package com.example.app;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {}
```

Still, only `Haptics.vibrate();` is working as described here: https://github.com/ionic-team/capacitor/issues/3406

**Comment by merganon** [comment]
Every function mentioned in https://capacitorjs.com/docs/apis/haptics works for Android
However on iOS only Haptics.vibrate(); is working

Is this intentional? If yes, we should update the documentation
