### ISSUE TITLE
bug: LiveReload is not working when using .ts file for config (V3)

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/capacitor#4449]
### Capacitor Version

```
  @capacitor/cli: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0
```

### Platform(s)

iOS

### Current Behavior

The CLI runs without any error. Xcode opens and I'm able to run the app on my iPhone 12. The problem is, that changes aren't being detected. The app is not reloading. **I noticed, that the server config isn't added to `./ios/App/App/capacitor.config.json` when using `capacitor.config.ts` (.ts) instead of `capacitor.config.json`(.json).** Using the .json file for config instead of the .ts file, everything works fine.

### Expected Behavior

Server config should be written to `./ios/App/App/capacitor.config.json`.

### Code Reproduction

Sample Code: https://github.com/mariusbolik/capacitor-3-sample-project
Run the following command: `npm i && npx cap sync ios && ionic cap run ios -l --external`

### Other Technical Details

`npm --version` output: 7.8.0

`node --version` output: 14.16.0

`pod --version` output (iOS issues only): 1.10.0

**Comment by jcesarmobile** [comment]
Ionic CLI needs to be updated to properly support Capacitor 3
there is a "testing" version that has some initial support
npm install -g @ionic/cli@testing

**Comment by Sampath-Lokuge** [comment]
Do I still need to use this CLI `npm install -g @ionic/cli@testing` or? Because I still have this issue. Any clue? https://github.com/ionic-team/ionic-cli/issues/4653

**Comment by jcesarmobile** [comment]
no, use @latest

**Comment by Sampath-Lokuge** [comment]
Sorry, I didn't get you?

```
 ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.13
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.12
   OS     : Windows 10
```
