### ISSUE TITLE
Check if client using capacitor-app to hide/show html-element

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#445]
As the topic title. Is this possible?

I'm using a Vuejs-application and I want to show some HTML-code only if the client is using the app (which will be on Appstore and Google Play).

**Comment by EWBears** [comment]
Can’t you import the Cordova-platform plugin and do a platform check?

I’m not sure if that Cordova-plugin is cross compatible with capacitor or not (since I’m waiting for public release to move over to capacitor), but that’s the route that I would explore

**Comment by solojuve1897** [comment]
Found this: https://capacitor.ionicframework.com/docs/apis/device

Works great :-)

**Comment by solojuve1897** [comment]
The following produces an error in IE11 about proxy not being defined:
```
import { Plugins } from '@capacitor/core'
const { Device } = Plugins
```
Will this be fixed?

**Comment by janpio** [comment]
(You should open a new issue about this new problem)

**Comment by solojuve1897** [comment]
Will do

**Comment by mlynch** [comment]
I'm not sure we're going to support IE. I know teams are still supporting it but it could significantly hold us back from making Capacitor better for everyone else. It also has zero support for any PWA APIs

**Comment by mlynch** [comment]
@solojuve1897 you can check if `window.Capacitor` exists
