### ISSUE TITLE
bug: platform.ready() not working in android device

### ISSUE THREAD

**Issue by dipankarmondal** [ionic-team/capacitor#4465]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/cli: 3.0.0-rc.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

`this.platform.ready()` not working in android device
when doing ionic serve => this.platform.ready() working fine
when checking android device => this.platform.ready() not working

### Expected Behavior

this.platform.ready() should be work on android device too.

### Code Reproduction

I am sharing the code written in app component
`constructor(
    private statusBar: StatusBar,
    private platform: Platform,
    public storage: Storage,
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(async () => {
      console.log('platform ready')   // <-- not working in android device
      await this.storage.create();  // <-- not working in android device
    });
  }`

### Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.16.0

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dipankarmondal** [comment]
my Application is Very simple. I have created a project using ionic start then chooses tab theme. I am using angular. then followed instructions from [https://capacitorjs.com/docs/v3/updating/3-0](url). 
then used this 'npm install @capacitor/cli@next @capacitor/core@next'
after that I have installed ionic statusBar from ionic native plugin
after that ionic storage is also installed by using this command 'npm install @ionic/storage-angular'
after that when I am using these inside platform.ready, these are not working
when I am using console log only inside platform ready that one also not firing

here is my code written inside app component
`

import { Component } from '@angular/core';
import { StatusBar } from '@ionic-native/status-bar/ngx';
import { Platform } from '@ionic/angular';
import { Storage } from '@ionic/storage-angular';
import { ThemeService } from './services/theme/theme.service';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
})
export class AppComponent {
  constructor(
    private statusBar: StatusBar,
    private platform: Platform,
    public storage: Storage,
    public themeService: ThemeService
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(()=>{
      console.log('platform is ready'); // <-- firing in browser with ionic serve but in android app it is not firing
    });
  }
}

`
I am sharing my package.json file also
[package.docx](https://github.com/ionic-team/capacitor/files/6322673/package.docx)

**Comment by riderx** [comment]
@dipankarmondal i'm not sure, but the point to use capacitor is for me to don't need platform.ready anymore !

**Comment by dipankarmondal** [comment]
Thanks for your reply. 
currently, I am doing this also. but my concern is if I call native plugin directly within constructor, will it hamper the performance

**Comment by dotNetkow** [comment]
Platform ready is a Cordova concept, so it won't work here by design. [More detail here.](https://capacitorjs.com/docs/cordova#plugin-management). 

Your code looks correct. Here's [my app](https://github.com/ionic-team/ionifits/blob/main/src/app/app.component.ts#L15) with a similar setup.
