### ISSUE TITLE
bug:  Capacitor CLI requires Node >=8.3.0 (but version is 16.0.0-head)

### ISSUE THREAD

**Issue by elsni** [ionic-team/capacitor#4466]
### Capacitor Version
npx cap doctor returns:
`Capacitor CLI requires Node >=8.3.0`
### Platform(s)

node 16.0.0-head

MacOs BigSur 11.2.1, Apple M1

### Current Behavior
`npx cap init`
returns
`Capacitor CLI requires Node >=8.3.0`

### Expected Behavior
initialization wizard starts

### Other Technical Details

`npm --version` output:
7.9.0

`node --version` output:
v16.0.0-head

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
the `-head` part probably confuses the version check.
Do you know if it's possible to install `16.0.0-head` while using nvm? I don't really want to break my dev environment to test this.
