### ISSUE TITLE
bug: Push notification alert not received on first installation of the app 

### ISSUE THREAD

**Issue by weiz18** [ionic-team/capacitor#4476]
### Capacitor Version

```
    "@capacitor/android": "^2.4.7",
    "@capacitor/cli": "^2.4.7",
    "@capacitor/core": "^2.4.7",
```

### Platform(s)

```
Android

```
### Current Behavior

Set up a simple push notification test app, and then send a notification from firebase console. 
The push notification does not appear (native android alert) for the first install (meaning,  if you are opening the app for the first time and then kill the app, the push notification doesn't come through).  And the second time (so open the app and close the app again), the push notification comes through fine. 
NOTE: In both case, the firebase token has been registered 

### Expected Behavior

Should be able to receive push notification even on first install

### Code Reproduction

https://github.com/weiz18/test-push

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by weiz18** [comment]
code sample added

**Comment by jcesarmobile** [comment]
I've run your app and I can't reproduce, might be a connectivity problem on your part.

Try updating the `firebaseMessagingVersion` value to 20.3.0 or even 21.1.0 in `variables.gradle` to use latest SDK.
