### ISSUE TITLE
Add WebView Plugin

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#448]
~This is the function we use in ionic's WKWebView plugin for cordova, and we should probably find a way to export this function as a way to map file urls to our expected URL format without the user having to know about the details of that mapping~

see https://github.com/ionic-team/capacitor/issues/448#issuecomment-411797620

**Comment by dwieeb** [comment]
`window.Ionic.normalizeURL` is now `window.Ionic.WebView.convertFileSrc()` for Web View plugin v2, but for Ionic 4 the user will import the function right from the Ionic Native wrapper.

**Comment by dwieeb** [comment]
Hijacking this issue.

We need the following in Capacitor:

* New Web View plugin: `Plugins.WebView`
* Support `convertFileSrc()`, `setServerBasePath()`, `getServerBasePath()` via `Plugins.WebView`
* Copy `Plugins.WebView` to global `window.Ionic.WebView` to support Ionic Deploy
    * https://github.com/ionic-team/cordova-plugin-ionic/blob/64be7acf92dcfd2e0dcafe5c9e7f2bf4b08a9ecd/www/common.ts#L390
    * https://github.com/ionic-team/cordova-plugin-ionic/blob/64be7acf92dcfd2e0dcafe5c9e7f2bf4b08a9ecd/www/common.ts#L407
