### ISSUE TITLE
bug: V3 importation of Filesystem not importing via @capacitor/core

### ISSUE THREAD

**Issue by hunterInt** [ionic-team/capacitor#4482]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0

[success] Android looking great! 👌

```

### Platform(s)
Android

### Current Behavior
I can't use anything with that requires `Filesystem` when I import it like the [documentation says](https://capacitorjs.com/docs/v3/apis/filesystem#example):
```
import { Filesystem, FilesystemDirectory, FilesystemEncoding } from '@capacitor/core';
//......
const permission = await Filesystem.checkPermissions();//<------- Filesystem undefined
```
However, when I import it like so 
```
import { Filesystem } from '@capacitor/filesystem';
```
`Filesystem` works correctly, but `FilesystemDirectory` and `FilesystemEncoding` obviously don't.
### Expected Behavior

I would expect it to work the way the documentation says. 

### Other Technical Details

`npm --version` output: 7.10.0

`node --version` output: v12.15.0

**Comment by jcesarmobile** [comment]
In Capacitor 3 all the plugins have been moved out, so all the imports should be done from the plugin, not from core.
Both `FilesystemEncoding` and `FilesystemDirectory` are in `@capacitor/filesystem`, and BTW, they are deprecated now, the new names are just `Encoding` and `Directory`
