### ISSUE TITLE
bug: browser plugin will not open mailto link

### ISSUE THREAD

**Issue by richardshergold** [ionic-team/capacitor#4485]
## Bug Report

Trying to open a mailto link using the Browser plugin and (on iOS and Android) I get an "invalid URL" error and the mail window does not open

```
Browser.open({url: "mailto:feedback@mydomain.co.uk",windowName: "_system",});
```

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/android 2.4.2
  @capacitor/core 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 13 Capacitor plugins for ios:
    cordova-plugin-apprate (1.7.2)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-calendar (5.1.5)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-opener2 (3.0.4)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-fingerprint-aio (3.0.1)
    cordova-plugin-inappbrowser (4.0.0)
    cordova-plugin-ionic (5.4.7)
    cordova-plugin-market (1.2.0)
    cordova-plugin-nativestorage (2.3.2)
    cordova-plugin-whitelist (1.3.4)
[success] iOS looking great! 👌
```

### Platform(s)
ios
Android

### Current Behavior
window does not open - console shows "invalid url"

### Expected Behavior
the window should open to a mail dialog

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Do you mean Capacitor's browser plugin or cordova-plugin-inappbrowser?

can you provide a sample app for clarity?

**Comment by richardshergold** [comment]
@jcesarmobile I mean the capacitor plugin - here is my code:

```
import { Plugins } from "@capacitor/core";
const { Browser } = Plugins;

@Injectable()
export class feedbackService {
  constructor(public appRate: AppRate, public platform: Platform) {}

  sendFeedback() {
    Browser.open({
      url: "mailto:feedback@mydomain.co.uk",
      windowName: "_system",
    });
  }
}

```
when I run this method nothing opens and I see this in the console:

```
ERROR MESSAGE:  {"message":"Invalid URL","errorMessage":""}
⚡️  [error] - Unhandled Promise rejection: Invalid URL ; Zone: <root> ; Task: null ; Value: {"originalStack":"ZoneAwareError@capacitor://pmx/vendor-es2015.js:159271:42\nfromNative@user-script:2:224:23","zoneAwareStack":"fromNative@user-script:2:224:23 [<root>]","message":"Invalid URL","errorMessage":""} fromNative@user-script:2:224:23 [<root>]
```

**Comment by jcesarmobile** [comment]
Capacitor browser plugin can only open http/https urls.
It’s not like Cordova’s InAppBrowser, it doesn’t have the _blank, _self, _system options, the windowName you are using is a different thing and only used on the web version of the plugin.

if you want to open non http/https urls you can use App plugin
https://capacitorjs.com/docs/apis/app#openurl

**Comment by ipehimanshu** [comment]
ok then how to open mailto and tel: link ? 
i am using capacitor 3

**Comment by jcesarmobile** [comment]
use app-launcher plugin https://capacitorjs.com/docs/apis/app-launcher

**Comment by sanderschnydrig** [comment]
@jcesarmobile I'm getting the following error message when using the function canOpenUrl with a mailto link:

`ERROR MESSAGE:  {"message":"Unable to display URL","errorMessage":"Unable to display URL"}`
