### ISSUE TITLE
bug: cordova.platformId is always undefined

### ISSUE THREAD

**Issue by danilf16** [ionic-team/capacitor#4494]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android, iOS

### Current Behavior

`cordova.platformId` is always `undefined`

### Expected Behavior

`cordova.platformId` should have correct value for platforms (`android`, `ios`, etc)

**Comment by jcesarmobile** [comment]
I can't reproduce, do you have some cordova plugin installed? if not the cordova.js code doesn't get injected

**Comment by danilf16** [comment]
@jcesarmobile I can't reproduce this problem in `3.0.0-rc.1`. Seems It already fixed.
