### ISSUE TITLE
bug: monorepo (Angular) support

### ISSUE THREAD

**Issue by alexciesielski** [ionic-team/capacitor#4508]
### Capacitor Version
Both 2 and 3

### Current Behavior
A separate package.json in the `projects/app/` subfolder needs to be maintained with Capacitor's core and plugin features, lessening the advantages of a single package.json monorepo approach.

### Expected Behavior
Capacitor is able to detect plugins from the root package.json.

### Code Reproduction
- Create a Angular monorepo application, install Capacitor's core features and (at-least) one 3rd party plugin.
- Try to run `ionic capacitor sync` in the root folder. (Error that `package.json` could not be found)
- Add `package.json` under `projects/app` with all of Capacitor's plugins and run `sync` again: works.

**Comment by spicemix** [comment]
PLUS ONE.

**Comment by jase88** [comment]
Would be helpful for tools like nx

**Comment by WetCouch** [comment]
Still happening in v4 with nx, any chance for update? Capacitor seems to not resolve plugins from root package.json

**Comment by WhatsThatItsPat** [comment]
Does this really need a reproduction?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
