### ISSUE TITLE
bug: IOS capacitor inApp browser plugin crashes for presentationStyle  'fullscreen' | 'popover'

### ISSUE THREAD

**Issue by wanderer3912** [ionic-team/capacitor#4511]
### Capacitor Version

```
<img width="947" alt="Screen Shot 2021-04-28 at 1 19 14 PM" src="https://user-images.githubusercontent.com/44648066/116445858-55ff0f00-a824-11eb-9f81-6d15a835e882.png">
```

### Platform(s)
IOS

### Current Behavior
1.Open a link using inApp browser, slide and close the browser.
2. Open same link/another link. browser crashes with error message:  {message: "Unable to display URL", errorMessage: "Unable to display URL"}
(anonymous function) — logger.js:17
(anonymous function) — logger.js:83
(anonymous function) — bridge.js:110
Global Code — Script Element 2:1
dispatchException — runtime.js:567

### Expected Behavior
Sliding and closing the browser should not crash browser.

### Code Reproduction

git repo: https://github.com/wanderer3912/TEST_Capacitor_InAppBrowser

Launch the app using Xcode.

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v14.15.1

`pod --version` output (iOS issues only): 1.10.1

**Comment by jcesarmobile** [comment]
thanks for the issue, but it's already reported https://github.com/ionic-team/capacitor-plugins/issues/352
