### ISSUE TITLE
bug: Android Browser API behavior on an Ionic capacitor app

### ISSUE THREAD

**Issue by GiacomoVeneir** [ionic-team/capacitor#4512]
### Capacitor Version

```
@capacitor/cli 2.4.6
@capacitor/ios 2.4.6
@capacitor/android 2.4.6
@capacitor/core 2.4.6
@capacitor/electron not installed
```

### Platform(s)

Android

### Current Behavior

When I'm in the app, I open a Browser page inside the app. Then I put the app in the background and go to the homepage of the phone.
When I reopen the app from the homepage of the phone, the browser page has been closed. This does not happen if I open the app from the "open apps tabs". Video: https://twitter.com/giacomovenier/status/1387764918347255810?s=20
This is causing issues with the 3D Secure check for credit cards in the Stripe Capacitor plugin. 
Is there anything I can do?

### Expected Behavior

The app should not close the InAppBrowser page automatically on reopen. (As it does on iOS)

### Other Technical Details

`npm --version` output:6.14.11

`node --version` output:v12.13.0

`pod --version` output (iOS issues only):1.10.1

https://user-images.githubusercontent.com/39464036/116566527-2117b880-a907-11eb-8d8a-1573a7c5f61f.MP4

**Comment by jcesarmobile** [comment]
Capacitor apps by default have `android:launchMode="singleTask"` in their activity, that means when you launch an activity it replaces the current activity, Browser plugin is an activity of Chrome custom tabs, and when you tap your icon, the icon launches an activity to your app's main activity, which closes the Browser activity.

You can remove `android:launchMode="singleTask"`, but will probably cause problems with local/push notifications and custom schemes/deep links or any other thing that launches an app intent.
