### ISSUE TITLE
bug: app crashing when using cordova package EmailComposer with Capacitor 3

### ISSUE THREAD

**Issue by csurbier** [ionic-team/capacitor#4516]
## Bug Report

The package EmailComposer (https://github.com/katzer/cordova-plugin-email-composer) which was working fine with Capacitor 2.x is now crashing apps with Capacitor 3

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.1
  @capacitor/core: 3.0.0-rc.1
  @capacitor/android: 3.0.0-rc.1
  @capacitor/ios: 3.0.0-rc.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Now with Capacitor 3, the following simple code is crashing the application :

` let email = {
          to: 'contact@hophopfood.org',
          subject: 'Contact application HopHopFood Pro',
          body: '',
          isHtml: true
        }
    
        // Send a text message using default options
        this.emailComposer.open(email); let email = {
          to: 'contact@hophopfood.org',
          subject: 'Contact application HopHopFood Pro',
          body: '',
          isHtml: true
        }
    
        // Send a text message using default options
        this.emailComposer.open(email);`

and the log : 

2021-04-30 18:08:43.948 13932-14040/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: io.ionic.starter, PID: 13932
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.remove(ArrayList.java:503)
        at de.appplant.cordova.emailcomposer.Impl.getDraft(Impl.java:90)
        at de.appplant.cordova.emailcomposer.EmailComposer$4.run(EmailComposer.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

### Expected Behavior

Open the smartphone native email composer like before

### Code Reproduction

Here is a sample repository with android app ready to test

https://github.com/csurbier/DemoCrashEmailComposer

### Other Technical Details

`npm --version` output: 7.5.2

`node --version` output: 14.15.1

**Comment by jcesarmobile** [comment]
This is not a Capacitor issue, it's a new restriction for Android 11+ devices when the app targets SDK 30+, you need to put in the manifest the intents/apps that your app will query, in this case you need to add this to your manifest.

```
    <queries>
        <intent>
            <action android:name="android.intent.action.SEND"/>
            <data android:mimeType="*/*" />
        </intent>
    </queries>
```

You should report it on the plugin repository and should be added there so users don't have to, but looks like it's abandoned.

**Comment by csurbier** [comment]
Thank you for the information
