### ISSUE TITLE
bug: iOS user-agent is missing Mobile/15E148 when appendUserAgent is used

### ISSUE THREAD

**Issue by webuniverseio** [ionic-team/capacitor#4517]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0

```

### Platform(s)

iOS

### Current Behavior

After adding `appendUserAgent` (with `MY_APP` as value) as described in https://capacitorjs.com/docs/v3/config I get following user-agent
```
Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) MY_APP
```

### Expected Behavior

I expect to see following user-agent, which contains `Mobile/15E148` as part of user-agent
```
Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MY_APP
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by webuniverseio** [comment]
Thanks for working on this @thomasvidas ! Do you know when the fix will be ready for public (when new release will be published)? 🙏

**Comment by thomasvidas** [comment]
We are planning on releasing `3.0.0-rc2` sometime in the near future but we don't have an exact date yet. Sometime within the next week or so though
