### ISSUE TITLE
Background Task send data only when again open the app

### ISSUE THREAD

**Issue by ramay2088** [ionic-team/capacitor#4518]
### Capacitor Version

version 2

### Platform(s)
Android

### Current Behavior
Not Sending data in background

### Expected Behavior
I should keep send data

### Code Reproduction

This plugin should send data as app is in background but is keep data to itself when I again open the then it sends data .
```
  App.addListener("appStateChange", (state) => {
       setInterval(this.getLocation, 120000);
      if (!state.isActive) {
        BackgroundTask.beforeExit(async () => {
          setInterval(this.getLocation, 120000);
          console.og('Why')
        });
      }
      if (state.isActive) {
        setInterval(this.getLocation, 120000);
        console.log('Active')
      }
    });
```

**Comment by ramay2088** [comment]
Sorry Background task wasn't the culprit

here is solution
Android 8+ doesn't allow continue watch user's location for a longer period of time in order to do that we need to create a foreground service.

https://ionicframework.com/docs/native/foreground-service

**Comment by jcesarmobile** [comment]
BackgroundTask plugin has been removed from Capacitor 3, and even on Capacitor 2, it's not intended to do any background work, just extend it a few minutes when you close the app (it's for iOS mostly, on Android doesn't really do anything)
