### ISSUE TITLE
bug: [Deprecation] SharedArrayBuffer 

### ISSUE THREAD

**Issue by Philipp-Sc** [ionic-team/capacitor#4520]
## Bug Report
Not able to use the SharedArrayBuffer.
I am using the stockfish.js library https://github.com/niklasf/stockfish.wasm

To enable it the following is required:

These HTTP headers on the top level response:

Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin

And the following header on the included files:

Cross-Origin-Embedder-Policy: require-corp

I could not find a way to set the headers for the android build. As result the app does not start.

stockfish.worker.js:1 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

**Comment by jcesarmobile** [comment]
I've tried to add those headers and still didn't work.
Then I checked the chromium issue tracker and looks like it can't be used on Android WebView yet, so you can subscribe to their issue
https://bugs.chromium.org/p/chromium/issues/detail?id=1179201

**Comment by Philipp-Sc** [comment]
@jcesarmobile thank you for investigating,I found the developer of lichess created a native interface with capacitor.
https://github.com/veloce/capacitor-stockfish
