### ISSUE TITLE
bug: Capacitor3 Status Bar breaks android build

### ISSUE THREAD

**Issue by nsauter** [ionic-team/capacitor#4521]
### Capacitor Version

```
$ npx cap doctor
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.1
  @capacitor/android: 2.4.7
  @capacitor/core: 3.0.0-rc.1

[success] Android looking great! 👌

```

### Platform(s)
Android

### Current Behavior

Since i cant get the status bar plugin on the current capacitor version to work, i tried migrating to the capacitor3 status-bar Plugin. I installed the plugin exactly the way it is described [here](https://capacitorjs.com/docs/v3/apis/status-bar). Whan building with android studio the build breaks. With errors like "com.getcapacitor.annotation.CapacitorPlugin; does not exist", "cannot find symbol class WebColor", "cannot find class CapacitorPlugin", "cannot find symbol variable WebColor".

```
> Task :capacitor-status-bar:compileDebugJavaWithJavac FAILED
C:\Users\Nico\Projects\peyday-react\node_modules\@capacitor\status-bar\android\src\main\java\com\capacitorjs\plugins\statusbar\StatusBarPlugin.java:7: error: package com.getcapacitor.annotation does not exist
import com.getcapacitor.annotation.CapacitorPlugin;
                                  ^
C:\Users\Nico\Projects\peyday-react\node_modules\@capacitor\status-bar\android\src\main\java\com\capacitorjs\plugins\statusbar\StatusBarPlugin.java:8: error: cannot find symbol
import com.getcapacitor.util.WebColor;
                            ^
  symbol:   class WebColor
  location: package com.getcapacitor.util
C:\Users\Nico\Projects\peyday-react\node_modules\@capacitor\status-bar\android\src\main\java\com\capacitorjs\plugins\statusbar\StatusBarPlugin.java:10: error: cannot find symbol
@CapacitorPlugin(name = "StatusBar")
 ^
  symbol: class CapacitorPlugin
C:\Users\Nico\Projects\peyday-react\node_modules\@capacitor\status-bar\android\src\main\java\com\capacitorjs\plugins\statusbar\StatusBarPlugin.java:49: error: cannot find symbol
                        final int parsedColor = WebColor.parseColor(color.toUpperCase());
                                                ^
  symbol:   variable WebColor
  location: class StatusBarPlugin
Note: C:\Users\Nico\Projects\peyday-react\node_modules\@capacitor\status-bar\android\src\main\java\com\capacitorjs\plugins\statusbar\StatusBar.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors
```

### Expected Behavior

Build does not break on capacitor status-bar plugin.

### Code Reproduction
```
import { StatusBar, StatusBarStyle } from '@capacitor/status-bar';
const setStatusBarStyleDark = async () => {
  await StatusBar.setStyle({ style: StatusBarStyle.Dark });
};
setStatusBarStyleDark();

```

### Other Technical Details

`npm --version` output: 7.7.6

`node --version` output: v15.14.0

`pod --version` output (iOS issues only):

**Comment by pwespi** [comment]
>   @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.1
  @capacitor/android: 2.4.7
  @capacitor/core: 3.0.0-rc.1

@capacitor/android should also be 3.0.0-rc.1

**Comment by nsauter** [comment]
Well, i didnt even notice that. How can i upgrade this package too?

**Comment by pwespi** [comment]
There is an upgrade guide in the Capacitor documentation: https://capacitorjs.com/docs/v3/updating/3-0

**Comment by nsauter** [comment]
Thats what i used, but there is no explanation on how to update the android package. But i got it now and it works perfectly. Thanks.

**Comment by jcesarmobile** [comment]
it's explained here
https://capacitorjs.com/docs/v3/updating/3-0#update-the-capacitor-android-platform
