### ISSUE TITLE
bug: Filesystem.writeFile logs full file content to the Android logcat

### ISSUE THREAD

**Issue by kirillgroshkov** [ionic-team/capacitor#4525]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/android 2.4.7
  @capacitor/core 2.4.7
  @capacitor/electron not installed
```

### Platform(s)
Android

### Current Behavior

We have got a report from a security researcher, who pointed out that Capacitor by default logs full file content of a file that is saved via its Filesystem plugin. E.g we call `Filesystem.writeFile` in our code, saving `state.json` (which is a Redux state).

Full content of the saved file is then visible in Android logs via `logcat`, example/screenshot:

![image](https://user-images.githubusercontent.com/4757745/116930073-9533c280-ac5f-11eb-939f-c80f7ffbe87b.png)

Providing a second screenshot where it's seen that it is logged not "from the Filesystem plugin code", but from some generic code that logs generic Plugin input/output (possibly in the `V` verbose level):

![image](https://user-images.githubusercontent.com/4757745/116930862-99141480-ac60-11eb-8470-6b0585836fb1.png)

### Expected Behavior

We expect to be able to disable this automatic logging functionality via some flag/setting, as it can leak some PII/sensitive data to someone who has access to `logcat`.

**Comment by kirillgroshkov** [comment]
Actually, I just found a `hideLogs` option documented there: https://capacitorjs.com/docs/v3/config

There's a chance that it will help, but need to try first.

**Comment by jcesarmobile** [comment]
Yeah, hideLogs will prevent those messages from appearing on logcat.

FYI, in capacitor 3 hideLogs is being deprecated, there will be an alternative way, check https://github.com/ionic-team/capacitor/pull/4416
