### ISSUE TITLE
feat: npm script hooks

### ISSUE THREAD

**Issue by karlvr** [ionic-team/capacitor#4572]
### Description

I'd like to be able to write npm script hooks like `precapcopy` and `postcapcopy` to be able to have an opportunity to do things, like correct for a `package.json` `homepage:` setting that I might need for the web version of my app. I could just write an npm script to do the `cap copy` but I'd like to just use the standard `cap` commands.

**Comment by EinfachHans** [comment]
What about [these](https://ionicframework.com/docs/cli/configuration#hooks)?

**Comment by jcesarmobile** [comment]
there is already an issue about it 
https://github.com/ionic-team/capacitor/issues/3593

**Comment by karlvr** [comment]
@EinfachHans I think maybe those are if I'm using ionic but I'm just using cap? I gave them a try but didn't immediately get any joy. @jcesarmobile thank you, I'm following that issue now.
