### ISSUE TITLE
Can not access the capacitorjs.com website ?

### ISSUE THREAD

**Issue by davidce** [ionic-team/capacitor#4574]
Hi guys, I can not visite the capacitorjs.com website with error of ERR_CONNECTION_RESET in  the Chinese mainland，Is anybody there have the same issues, thanks!

**Comment by AlwaysLoveme** [comment]
the same problem

**Comment by jcesarmobile** [comment]
not sure if it could be related to https://github.com/ionic-team/capacitor-site/issues/296

anyway, closing since the problem is on the site, you can subscribe to that other issue for updates and if that problem gets resolved maybe yours too

**Comment by netsesame2** [comment]
Can't visit these days. still in blocklist?

**Comment by eliot-ye** [comment]
The same question

**Comment by AlwaysLoveme** [comment]
> Can't visit these days. still in blocklist?

open VPN if you are in China
