### ISSUE TITLE
Failed to construct 'Notification': Illegal constructor

### ISSUE THREAD

**Issue by NicoGorenflo** [ionic-team/capacitor#4584]
I am importing this cdn (https://cdn.jsdelivr.net/npm/@capacitor/core@2.4.7/dist/capacitor.js) into my script and then I try to execute the following code:

```javascript
    var today = new Date();
    today.setSeconds(today.getSeconds() + 10);
    LocalNotifications.schedule({
        notifications: [
            {
                title: 'Some Title',
                body: 'Some Content',
                schedule: {
                    at: today,
                }
            },
        ],
    }).then(notifs => {
        console.log('scheduled notifications', notifs);
    });
```
And then I get this bug
![capacitor_bug](https://user-images.githubusercontent.com/50376228/118674312-f92abf00-b7f9-11eb-8da3-cf874bde4eec.png)

![capacitor_bug_2](https://user-images.githubusercontent.com/50376228/118674346-02b42700-b7fa-11eb-9192-144f0f28068f.png)

What is the problem here?

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/3472#issuecomment-797553465
