### ISSUE TITLE
bug: Plugin with @capacitor/android 3.0.0 verify failed

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/capacitor#4587]
### Capacitor Version

```
"@capacitor/android": "3.0.0",
"@capacitor/core": "3.0.0",
"@capacitor/docgen": "0.0.10",
"@capacitor/ios": "3.0.0",
```

### Platform(s)

- Android

### Current Behavior

I just migrated the Capacitor Dev Dependencies in a Plugin of mine to 3.0.0 and run `npm run verify:android`, which runs the predefined `cd android && ./gradlew clean build test && cd ..`. This fails:

```
Execution failed for task ':capacitor-android:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:
  
  /Users/.../IdeaProjects/capacitor/file-select/node_modules/@capacitor/android/capacitor: Error: Unknown issue id "AndroidGradlePluginVersion", found in /Users/.../IdeaProjects/capacitor/file-select/node_modules/@capacitor/android/capacitor/lint.xml [LintError]

```

### Expected Behavior

To not fail the Android Linting

**Comment by jcesarmobile** [comment]
which gradle version is your plugin using? we had to add that after the gradle 7 update, but if your plugin doesn't understand it, it's probably because it wasn't available on older versions

**Comment by EinfachHans** [comment]
Yes you'r right, thanks 😊
