### ISSUE TITLE
bug: IonDatetime not working on a new Ionic React project created with Ionic CLI

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/capacitor#4588]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/core: 3.0.0

[success] Android looking great! 👌
```

### Platform(s)

Android (at least)

### Current Behavior

When running an app using an `IonDatetime` on Android, tapping the date field opens the date selector, but it's frozen and it's impossible to change the date.

Looking at the JS console with Chrome Remote Debugging shows this error:

```TypeError: t.Capacitor.isPluginAvailable is not a function```

which suggests IonDatetime is trying to use some Capacitor plugin but it hasn't been loaded properly.

### Expected Behavior

IonDateTime should allow selecting a different date.

### Code Reproduction

Create a new Ionic React project with

```ionic start my-app blank --type=react```

Add the Android platform:

```
ionic capacitor add android
```

Add an `IonDatetime` to `Home.tsx`, build and run on Android.

Edit: here's a repo: [mirkonasato/ionic-capacitor3-datetime](https://github.com/mirkonasato/ionic-capacitor3-datetime)

### Other Technical Details

`npm --version` output: 6.14.12

`node --version` output: v14.16.1

`pod --version` output (iOS issues only):

### Additional Context

Adding this to `index.tsx` makes the problem go away:

```import '@capacitor/core';```

I think at some point (around 3.0.0-rc0) this was documented in the [Installing Capacitor](https://capacitorjs.com/docs/getting-started) page, but looks like it has been removed now and can't see it anywhere else in the docs.

Therefore I'm assuming the import shouldn't be required and this is an issue with Capacitor.

If the import is required then it should be documented and ideally the Ionic CLI should already include when generating a project.

**Comment by mirkonasato** [comment]
Here's when the import was removed from the docs: [ionic-team/capacitor-site#274](https://github.com/ionic-team/capacitor-site/pull/274/files)

**Comment by jcesarmobile** [comment]
can you try with @ionic/cli@6.16.0?

**Comment by mirkonasato** [comment]
@jcesarmobile that is indeed what I used

```
% ionic --version
6.16.0
```

**Comment by mirkonasato** [comment]
@jcesarmobile incidentally, there's another issue with the Ionic CLI where it installs the wrong `@capacitor/core` version: [ionic-team/ionic-cli#4699](https://github.com/ionic-team/ionic-cli/issues/4699)

So if you try to reproduce this one you may want to explicitly run `npm install @capacitor/android@3.0.0` before `ionic capacitor add android`
