### ISSUE TITLE
feat: Different bundle-ids for android and iOS

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/capacitor#4599]
### Description
Would be very useful to be able to set bundle Ids for different platforms, the feature is related to [this ticket](https://github.com/ionic-team/capacitor/issues/340)

### Platform(s)
iOS & Android

### Preferred Solution
```
{
  "appId": {
    "ios":"xxx",
    "android":"xxx"
  }
}
```

**Comment by jcesarmobile** [comment]
The id is only used when you use add command, which is supposed to be an one time command, so you can add ios, change the id and then add android.
Also in Capacitor 3 you can use a `capacitor.config.ts` file, which means you can use any logic you want to set the value.

**Comment by jongbonga** [comment]
Thanks @jcesarmobile, what about Appflow users? Doesn't the build process add the plaforms each time it is called?

**Comment by jcesarmobile** [comment]
I don’t thinks so, at least if you commit the ios/android folders, not sure what happens if you don’t commit them
