### ISSUE TITLE
bug: cannot build native-bridge.js not installed 

### ISSUE THREAD

**Issue by nhhockeyplayer** [ionic-team/capacitor#4607]
I would have thought native-bridge.js would exist beneath node_modules since I installed @capacitor/core

these are my commands

```
nx generate @nxtend/ionic-angular:application mobile-app --capacitor true
nx build mobile-app
nx run mobile-app:add:android
```

this one fails nx run mobile-app:add:android

node_modules/@capacitor/core/native-bridge.js'

doesn't exist

I cannot add a platform using
`nx run mobile-app:add:android`
Copying native bridge: ENOENT: no such file or directory, lstat

thanks for any assist

```
✔ Copying web assets from mobile-app to android/app/src/main/assets/public in 459.96ms
✖ Copying native bridge: ENOENT: no such file or directory, lstat '/Users/meanstack02/new/energy/node_modules/@capacitor/core/native-bridge.js'
✖ copy: ENOENT: no such file or directory, lstat '/Users/meanstack02/new/energy/node_modules/@capacitor/core/native-bridge.js'
[error] [Error: ENOENT: no such file or directory, lstat '/Users/meanstack02/new/energy/node_modules/@capacitor/core/native-bridge.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/meanstack02/new/energy/node_modules/@capacitor/core/native-bridge.js'
}
✔ Updating Android plugins in 1.07ms
  Found 0 Capacitor plugins for android:
✔ update android in 28.24ms
```

**Comment by nhhockeyplayer** [comment]
Im closing until it persists

**Comment by nhhockeyplayer** [comment]
this remains an issue with angular 
if someone can look into this

Ionic:

   Ionic CLI : 6.16.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.16.1
   npm    : 7.14.0
   OS     : macOS Big Sur

**Comment by jcesarmobile** [comment]
no idea how nx works and wasn't able to run the command you provided, but looks like it's installing capacitor cli 2, while it should be using capacitor cli 3, so the package should be updated

**Comment by corysmc** [comment]
We had a similar issue with nx in a monorepo, and deploying to appflow. I just fixed it by updating our appflow CI settings to install in both places:

```
{
    "apps": [
        {
            "appId": "your-app-id",
            "root": "client-apps/apps/your-app",
            "dependencyInstallCommand": "yarn install && cd ../../ && yarn install",
            "webBuildCommand": "cd ../../ && yarn build:your-app"
        }
    ]
}
```
