### ISSUE TITLE
bug: ionic date picker and haptics not working

### ISSUE THREAD

**Issue by caem1420** [ionic-team/capacitor#4609]
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
ios

### Current Behavior
When i use the date picker from ionic, it gets stuck and in the console of xcode appear this message 
also happen when trying to make the phone vibrate with the haptics plugin, i dont know if the error also happen with other plugins

⚡️  ------ STARTUP JS ERROR ------

⚡️  TypeError: win.Capacitor.isPluginAvailable is not a function. (In 'win.Capacitor.isPluginAvailable('Haptics')', 'win.Capacitor.isPluginAvailable' is undefined)
⚡️  URL: capacitor://localhost/common.js
⚡️  common.js:467:83
⚡️  [error] - {}

⚡️  See above for help with debugging blank-screen issues

### Expected Behavior
The date picker should work without problems

### Code Reproduction

1. Create basic app with ionic and capacitor
2.  install haptics plugin
3. use ionic date picker
4. compile and run in ios

### Other Technical Details

`npm --version` output:6.14.12

`node --version` output:v14.16.1

`pod --version` output (iOS issues only): 1.10.1

**Comment by jcesarmobile** [comment]
it was fixed [here](https://github.com/ionic-team/capacitor/pull/4589), still not released
