### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by brucelane** [ionic-team/capacitor#4610]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0

[success] Android looking great! 👌
```

### Platform(s)

Ionic React Typescript on Windows 10

### Current Behavior

On npm start, I got this TS error

TypeScript error in C:/dev/_current/PowerPlatformTDB/Application/PowerTDB/node_modules/@capacitor/device/dist/esm/index.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { DevicePlugin } from './definitions';

### Expected Behavior

Being able to compile and run my app

### Code Reproduction

```
import { Storage } from '@capacitor/storage';
import { Device } from '@capacitor/device';
import { Geolocation } from '@capacitor/geolocation';
```

### Other Technical Details

`npm --version` output: 7.11.2

`node --version` output: v14.15.5

`pod --version` output (iOS issues only):

### Additional Context

My app is built from the Ionic conference app, using React Typescript.
Capacitor cli and core version 1.3.0 worked fine
I want to update to version 3.0

**Comment by brucelane** [comment]
using https://github.com/mhartington/react-notes as a template, capacitor 3 works fine

**Comment by thomasvidas** [comment]
On Capacitor 3 applications we require [typescript 3.8+](https://capacitorjs.com/docs/updating/3-0#typescript-38). Are you on an older version of TypeScript?

Also can you update the title `bug:` isn't exactly very descriptive 😅

**Comment by brucelane** [comment]
yes "typescript": "3.8.3" 
I guess it's about npm which got crazy, closing this

**Comment by davicedraz** [comment]
I am facing the same problem here. Any solution?
