### ISSUE TITLE
bug: Capacitor 3 Splash screen capacitor.configuration.json settings ignored

### ISSUE THREAD

**Issue by casper5822** [ionic-team/capacitor#4611]
## Bug Report
Capictor 3 Splash screen settings in capacitor.config.json are ignore. 
Settings like launchAutoHide but also the other settings like showSpinner etc.

With Capacitor 2 it works well (we upgrade our code from capacitor 2 to 3.0 according the official guide).

Configuration:

"plugins": {
    "SplashScreen": {
      "launchAutoHide": false,
      "showSpinner": true,
      "spinnerColor": "#b33c12",
      "iosSpinnerStyle": "small"
    },
    "Keyboard": {
      "resize": "ionic"
    }
  },

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

```
  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
```

### Platform(s)
Android app.

### Current Behavior
On android app the splash screen automatically disappears in 3 seconds because capacitor.config.json is ignored.

### Expected Behavior
Splash screen must be shown until SplashScreen.hide() is called in the code according capacitor.config.json settings.

### Code Reproduction
Just try if splash screen config settings work if you upgrade to capacitor 3.0 on an existing capacitor 2 app.

### Other Technical Details

`npm --version` output:
7.12.1

`node --version` output:
v14.17.0
`pod --version` output (iOS issues only):

### Additional Context
The same code works with capacitor 2.4.7.

**Comment by casper5822** [comment]
We fix the issue. When upgrade from capacitor 2 to 3.0 it's crucial to remove android platform and run ionic cap add android again otherwise there wil be encounter errors with plugins.

**Comment by jcesarmobile** [comment]
No, you should never remove android platform, never.

You probably missed this step on the migration guide
https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading

**Comment by casper5822** [comment]
@jcesarmobile we fix the MainActivity when we add again the platform. So maybe you are right. Thank you for the feedback

**Comment by coldiary** [comment]
Still facing this issue on a newly created project.
Looks indeed like the capacitor.config.json is ignored, if say not to autohide or if i put a delay, it does not change anything, splashscreen still flicker from black to white then app.
