### ISSUE TITLE
bug: "Browser" plugin is not implemented on android Capacitor 3.0

### ISSUE THREAD

**Issue by casper5822** [ionic-team/capacitor#4612]
## Bug Report
"Browser" plugin is not implemented on android logcat error log.

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0

```

### Platform(s)
Android app

### Current Behavior
Browser official plugin works on capacitor 2. We move our app to Capacitor 3 and Browser plugin not work. We get an error when we call Browser.open({})  in logcat: 

Capacitor/Console
Line 1 - Msg: ERROR Error: Uncaught (in promise): Error: "Browser" plugin is not implemented on android
    Error: "Browser" plugin is not implemented on android

### Expected Behavior
Broswer plugin is an official plugin. In the documentation v3 there is no specification on Android unsopperted.

### Code Reproduction
Just try Browser on a capacitor 2 app (upgrading it to 3.0).

### Other Technical Details

`npm --version` output:
7.12.1
`node --version` output:
v14.17.0
`pod --version` output (iOS issues only):

**Comment by casper5822** [comment]
We fix the issue. When upgrade from capacitor 2 to 3.0 it's crucial to remove android platform and run ionic cap add android again otherwise there wil be encounter errors with plugins.

**Comment by jcesarmobile** [comment]
No, you should never remove android platform, never.

You probably missed this step on the migration guide
https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading
