### ISSUE TITLE
feat: Touchmove gesture smooth enhancement

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/capacitor#4613]
### Description
`touchmove` event is still not smooth enough on high-dpi devices, despite the fact that first mention of this issues was 7 years ago. 
`touchmove` event is implementation which extends `pointermove` as base class. 

Bug is related to webkit: TouchEvent co-ordinates should be float/double instead of long http://trac.webkit.org/browser/trunk/Source/WebCore/dom/Touch.idl
```c
readonly attribute long clientX;
readonly attribute long clientY;
readonly attribute long screenX;
readonly attribute long screenY;
readonly attribute long pageX;
readonly attribute long pageY;
```
By the way, Chrome returned float co-ordinates which makes drag gestures more smooth. 

### Platform(s)
iOS, WebKit

### Preferred Solution
Create some type of a bridge:
1. Set a native iOS drag gesture listener 
2. Raplace all `touchmove` event callbacks with native drag listener events
3. Send all co-ordinates from native drag listener right to webview on place where `touchmove` should happen

### Additional Context
Related [Issue on WebKit Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=133180)

**Comment by jcesarmobile** [comment]
It would be possible to attach native gesture recognizers to the WKWebView, but what you propose is very hacky and can lead to other problems, so I don't think it fits into Capacitor core.

Could be done in a separate plugin for those interested.

I've tried doing something like this and seems to work

Put this in the plugin's load method:
```
let longPress = UILongPressGestureRecognizer(target: self, action: #selector(self.handleLongPress(_:)))
self.webView!.addGestureRecognizer(longPress)
self.webView?.isUserInteractionEnabled = true
```

and then this function to handle the gesture
``` 
@objc func handleLongPress(_ sender: UILongPressGestureRecognizer) {
    let touchLocation = sender.location(in: self.webView!)
    print("touch location \(touchLocation)")
}
```

of course this only prints the coordinates, the plugin would need a ton of js work to listen for this event and replace the web listeners with custom ones.
