### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by iamanandacharya** [ionic-team/capacitor#4618]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 2.2.1
  @capacitor/ios: 2.2.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

1> Cannot find 'ApplicationDelegateProxy' in scope in AppDelegate.swift
2> Type 'NSNotification.Name' has no member 'capacitorStatusBarTapped'  in AppDelegate.swift
![cap-error-1](https://user-images.githubusercontent.com/22565937/119390405-a154f200-bcea-11eb-8e17-fe6f93ac6aa5.png)
-
![cap-error-2](https://user-images.githubusercontent.com/22565937/119390387-98fcb700-bcea-11eb-9b77-8933ac49a88f.png)
 

### Current Behavior

Current Behavior is app is failed to debug in Xcode (version- Version 12.4)

### Expected Behavior

The app needs to debug successfully

### Other Technical Details

`npm --version` output: 7.6.0

`node --version` output: v15.11.0

`pod --version` output (iOS issues only): 1.10.1

Ionic-version - 5.5.2

**Comment by jcesarmobile** [comment]
You have to update @capacitor/android and  @capacitor/ios to 3.0.0
