### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by iamanandacharya** [ionic-team/capacitor#4619]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 2.2.1
  @capacitor/ios: 2.2.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Gradle sync failed: Cause: org.gradle.api.artifacts.result.ComponentSelectionReason.getDescription()Ljava/lang/String;
				Consult IDE log for more details 
![cap-error-3](https://user-images.githubusercontent.com/22565937/119391249-c138e580-bceb-11eb-852b-bd3ef66e0f9a.png)

### Current Behavior

Failed Bug in android studio ( 4.0) 
Gradle version - 7.0
Android Gradle Plugin Version - 4.2.0

### Expected Behavior

Build successfully

### Other Technical Details

`npm --version` output: 7.6.0

`node --version` output: v15.11.0

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Gradle 7 seems to require latest android studio 4.2

also you need to update  @capacitor/android to 3.0.0, not sure if related to the problem

**Comment by iamanandacharya** [comment]
This bug in @capacitor/android 3.0.0 and I have already added Gradle 7 and in android-studio 4.2

**Comment by jcesarmobile** [comment]
Well, that’s not what your report says, it says you are using android studio 4.0 and that you have @capacitor/android 2.2.1 installed
