### ISSUE TITLE
Camera options not having effect

### ISSUE THREAD

**Issue by joshuamorony** [ionic-team/capacitor#462]
**Current behavior**

When supplying options to the Camera plugin, it seems to only take on the default behaviour (only tested on iOS). Supplying the `source` option with `CameraSource.Camera` still prompts the user to select an option, and supplying the `resultType` with `CameraResultType.Uri` only returns an object with the `format` and `base64_data` for the photo.

**Expected behavior**

Options should change the behaviour of the modal and the returned data.

**Code**

```javascript

        let options = {
          quality: 100,
          allowEditing: true,
          resultType: CameraResultType.Uri,
          source: CameraSource.Camera
        };
    
        Camera.getPhoto(options).then(
    
            (photo) => {
                console.log(photo);

                Filesystem.readFile({
                    path: photo.path // Triggers error because path is not defined
                }).then((result) => {

                }, (err) => {

                });
        
            }, (err) => {

            }

        );
```

**Comment by mlynch** [comment]
Hmm, are you sure you have a recent version of @capacitor/ios? Can you run npx cap doctor?

**Comment by joshuamorony** [comment]
I believe so, this was a fresh install. Here are the results of `doctor`:

```
💊   Capacitor Doctor  💊

Dependencies:

  @capacitor/cli: 1.0.0-alpha.34

  @capacitor/core: 1.0.0-alpha.34

  @capacitor/android: 1.0.0-alpha.34

  @capacitor/ios: 1.0.0-alpha.34

  Capacitor iOS: 0.0.99

  Found 0 Capacitor plugins for ios:
[success] Everything looking great! 👌
```

**Comment by mlynch** [comment]
Weird looks like it’s finding a very old iOS version alongside the newer one. Not a camera issue as I suspected, but still it shouldn’t be doing this...

**Comment by joshuamorony** [comment]
I was able to fix the issue by manually running:

```
pod install --repo-update
```

inside of the ios platform. Here was the output of that if it is of any interest:

```
CocoaPods 1.5.0 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0

Analyzing dependencies
Downloading dependencies
Installing Capacitor 1.0.0-alpha.14 (was 0.0.99)
Installing CapacitorCordova 1.0.0-alpha.14 (was 0.0.99)
Using GCDWebServer (3.4.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

and then running `npx cap doctor` again:

```
💊   Capacitor Doctor  💊

Dependencies:

  @capacitor/cli: 1.0.0-alpha.34

  @capacitor/core: 1.0.0-alpha.34

  @capacitor/android: 1.0.0-alpha.34

  @capacitor/ios: 1.0.0-alpha.34

  Capacitor iOS: 1.0.0-alpha.14

  Found 0 Capacitor plugins for ios:
[success] Everything looking great! 👌
```

Tested on the device and the `path` is returned successfully (although, I am still getting prompted to choose between Photos/Take a Picture even though I supply the source property as CameraSource.Camera)

**Comment by mlynch** [comment]
Yea it shouldn’t be pulling from cocoa pods remote at all. The alpha.14 is also incorrect. Hmm

**Comment by jcesarmobile** [comment]
Does your Podfile looks like this?

```
pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
```

That should pick latest ones directly from `@capacitor/ios`

**Comment by joshuamorony** [comment]
It did not, it looked like this:

```
platform :ios, '10.0'
use_frameworks!

target 'App' do

  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', '1.0.0-alpha.14'
  # Do not delete
end
```

I did a fresh install to make sure that this wasn't because of anything I had messed with in trying to fix the issue, and this is what the podfile looks like after doing a clean install of an `@ionic/angular` `4.0.0-alpha.1` project, installing capacitor, and adding the iOS platform. On a fresh project this is the result of `npx cap doctor`:

```
  @capacitor/cli: 1.0.0-alpha.34

  @capacitor/core: 1.0.0-alpha.34

  @capacitor/android: 1.0.0-alpha.34

  @capacitor/ios: 1.0.0-alpha.34

  Capacitor iOS: 0.0.99
```

After updating the podfile to reflect what you suggested @jcesarmobile (which is also what older projects I have generated a couple of days ago have), and installing pods, the result of `doctor` looked like this:

```
  @capacitor/cli: 1.0.0-alpha.34

  @capacitor/core: 1.0.0-alpha.34

  @capacitor/android: 1.0.0-alpha.34

  @capacitor/ios: 1.0.0-alpha.34

  Capacitor iOS: 1.0.0-alpha.33
```

which seems accurate compared to the older projects I generated, it's just new projects that are getting alpha.14.

**Comment by mlynch** [comment]
How are you doing that fresh install? What commands?

**Comment by joshuamorony** [comment]
I did a complete reinstall to be sure, so I uninstalled Ionic and then (this is also still in my command line history fortunately :D):

```
npm install -g ionic@rc
ionic config set -g features.project-angular true
ionic start
cd testapp
npm install (this ran automatically before, but I got some notice about not being an Ionic project and to report the issue - but it seems this is a known/fixed issue)
npm install --save @capacitor/core @capacitor/cli
npx cap init
npx cap add ios
npx cap doctor
```

**Comment by jcesarmobile** [comment]
Got it, the template has that version set
https://github.com/ionic-team/capacitor/blob/master/ios-template/App/Podfile#L8

does it change if you run `npx cap update ios`?

npx cap add should change that as it runs update, not sure why it might be failing

**Comment by joshuamorony** [comment]
Yeah that seems to do the trick:

```
Joshuas-MacBook-Pro:testapp joshuamorony$ npx cap update ios
✔ Updating iOS plugins in 6.38ms
  Found 0 Capacitor plugins for ios:
✔ Updating iOS native dependencies in 8.60s
✔ update ios in 8.61s
Update finished in 8.628s
Joshuas-MacBook-Pro:testapp joshuamorony$ npx cap doctor
💊   Capacitor Doctor  💊

Dependencies:

  @capacitor/cli: 1.0.0-alpha.34

  @capacitor/core: 1.0.0-alpha.34

  @capacitor/android: 1.0.0-alpha.34

  @capacitor/ios: 1.0.0-alpha.34

  Capacitor iOS: 1.0.0-alpha.33
```

Capacitor iOS was 0.0.99 before running the update command, 1.0.0-alpha.33 afterward.

**Comment by mlynch** [comment]
Good catch! We will get that fixed

**Comment by jcesarmobile** [comment]
If I create an app with www folder it works fine, but if I follow your steps, it fails with an error 

> ✖ copy: Web dir doesn't exist. Verify webDir is set to your built web assets folder in capacitor.config.json, and make sure you've run `npm build` and `npx cap copy`
> [error] Error: Web dir doesn't exist. Verify webDir is set to your built web assets folder in capacitor.config.json, and make sure you've run `npm build` and `npx cap copy`

As copy fails, update is not run and the path isn't updated.

Is it possible that you forgot to run `ionic build`?
