### ISSUE TITLE
bug: Didn't find class "com.google.firebase.iid.FirebaseInstanceId"

### ISSUE THREAD

**Issue by iyasilias** [ionic-team/capacitor#4622]
## Bug Report
Didn't find class "com.google.firebase.iid.FirebaseInstanceId"
when using Push Notification on Android (publish success, but the app will crash when entering page with Push Notification code. When debugging, the error above appears).

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/electron: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/ios 2.4.2
  @capacitor/android 2.4.2
  @capacitor/core 2.4.2
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 2 Capacitor plugins for ios:
    @capacitor-community/barcode-scanner (1.2.1)
    @capacitor-community/fcm (1.1.0)
[success] iOS looking great! 👌
```

### Platform(s)
Android

### Current Behavior

Problem with Firebase Instant ID 

### Expected Behavior

Should use the new one since FirebaseInstanceId is deprecated.

### Other Technical Details

`npm --version` output: 6.12.1

`node --version` output: v12.13.1

`pod --version` output (iOS issues only): 1.10.1

### Additional Context

Actually similar bug also appears on ios, but I fix with the guide from here.
https://medium.com/nerd-for-tech/how-to-solve-capacitor-error-no-such-module-firebaseinstanceid-9c142933b589

Upon inspecting the debug message, I came across this code

```
    FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(getActivity(), new OnSuccessListener<InstanceIdResult>() {
      @Override
      public void onSuccess(InstanceIdResult instanceIdResult) {
        sendToken(instanceIdResult.getToken());
      }
    });
    FirebaseInstanceId.getInstance().getInstanceId().addOnFailureListener(new OnFailureListener() {
      public void onFailure(Exception e) {
        sendError(e.getLocalizedMessage());
      }
    });
    call.success();
```

Now I'm pretty sure I just have to change FirebaseInstanceId.getInstance().getInstanceId() with new implementation, but I do not know how.. I've tried `FirebaseInstallations.getInstance().getId()` but seems to have problem with addOnSuccessListener.

I really can't afford Capacitor 3 at this time. Please help.

TQ.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by iyasilias** [comment]
I'll try to reply asap. I've got some errands to do first.

**Comment by iyasilias** [comment]
I wasn't able to reproduce the error. Maybe it is the result of the complexity of my app. Anyhow, I was able to fix the problem. So I think I would like to share it here.

And yes, it has to do with the deprecation of FirebaseInstanceId.

In PushNotifactions.java from line 84:
Change this 

```
public void register(PluginCall call) {
    FirebaseMessaging.getInstance().setAutoInitEnabled(true);
    FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(getActivity(), new OnSuccessListener<InstanceIdResult>() {
      @Override
      public void onSuccess(InstanceIdResult instanceIdResult) {
        sendToken(instanceIdResult.getToken());
      }
    });

      FirebaseInstanceId.getInstance().getInstanceId().addOnFailureListener(new OnFailureListener() {
        public void onFailure(Exception e) {
          sendError(e.getLocalizedMessage());
        }
      });
    call.success();
  }
```

 to this
```
public void register(PluginCall call) {
    FirebaseMessaging.getInstance().setAutoInitEnabled(true);

    FirebaseMessaging.getInstance().getToken().addOnSuccessListener(getActivity(), new OnSuccessListener<String>() {
        @Override
        public void onSuccess(String s) {
          sendToken(s);
        }
      });

    FirebaseMessaging.getInstance().getToken().addOnFailureListener(new OnFailureListener() {
      @Override
      public void onFailure(@NonNull Exception e) {
        sendError(e.getLocalizedMessage());
      }
    });

    call.success();
  }
```

**Comment by sanderschnydrig** [comment]
I don't know why you closed this. You found a workaround but the issue still persists. Also the workaround didnt work for me on Capacitor v2.4.7.

**Comment by iyasilias** [comment]
does your issue same as mine? if so, i think the workaround should fix the problem.. how about you open a new issue then paste the error message, may be yours a bit different?

**Comment by gvcambraia** [comment]
Hello @iyasilias , I'm trying to apply your workaround, but I'm receiving 
`Cannot resolve method 'getToken' in 'FirebaseMessaging'`

Any ideas?

**Comment by sanderschnydrig** [comment]
@iyasilias I think its because I was using PushNotifications.requestPermission() according to older documentation. I found someone was using requestPermissions() with an "s" and it seemed to work now. I will get back to you when I have at this again.

**Comment by scottwilson312** [comment]
I can confirm that the documentation for Capacitor 2 is wrong. you need that extra "s" on `requestPermission`. This issue should not be closed.

**Comment by caragonFagor** [comment]
> I wasn't able to reproduce the error. Maybe it is the result of the complexity of my app. Anyhow, I was able to fix the problem. So I think I would like to share it here.
> 
> And yes, it has to do with the deprecation of FirebaseInstanceId.
> 
> In PushNotifactions.java from line 84: Change this
> 
> ```
> public void register(PluginCall call) {
>     FirebaseMessaging.getInstance().setAutoInitEnabled(true);
>     FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(getActivity(), new OnSuccessListener<InstanceIdResult>() {
>       @Override
>       public void onSuccess(InstanceIdResult instanceIdResult) {
>         sendToken(instanceIdResult.getToken());
>       }
>     });
> 
>       FirebaseInstanceId.getInstance().getInstanceId().addOnFailureListener(new OnFailureListener() {
>         public void onFailure(Exception e) {
>           sendError(e.getLocalizedMessage());
>         }
>       });
>     call.success();
>   }
> ```
> 
> to this
> 
> ```
> public void register(PluginCall call) {
>     FirebaseMessaging.getInstance().setAutoInitEnabled(true);
> 
>     FirebaseMessaging.getInstance().getToken().addOnSuccessListener(getActivity(), new OnSuccessListener<String>() {
>         @Override
>         public void onSuccess(String s) {
>           sendToken(s);
>         }
>       });
> 
>     FirebaseMessaging.getInstance().getToken().addOnFailureListener(new OnFailureListener() {
>       @Override
>       public void onFailure(@NonNull Exception e) {
>         sendError(e.getLocalizedMessage());
>       }
>     });
> 
>     call.success();
>   }
> ```

this worked for me

**Comment by rbloor97** [comment]
> Check this out: https://stackoverflow.com/questions/68320549/flutter-java-lang-noclassdeffounderror-failed-resolution-of-lcom-google-fireb
> 
> It says you just have to add
> 
> ```groovy-gradle
> implementation 'com.google.firebase:firebase-iid'
> ```
> 
> to the gradle file of your app.
> 
> It worked for me 👍

This worked for me

**Comment by tryroach** [comment]
> Check this out: https://stackoverflow.com/questions/68320549/flutter-java-lang-noclassdeffounderror-failed-resolution-of-lcom-google-fireb
> 
> It says you just have to add
> 
> ```groovy-gradle
> implementation 'com.google.firebase:firebase-iid'
> ```
> 
> to the gradle file of your app.
> 
> It worked for me 👍

this worked for me  👍
