### ISSUE TITLE
feat: Open Main Browser instead of WebView

### ISSUE THREAD

**Issue by sanderschnydrig** [ionic-team/capacitor#4624]
## Capacitor Doctor
```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Description

Since updating from Capacitor v2.4.7 to v3.0.0 the Browser Plugin opens links in a WebView instead of the main Browser like before. This breaks my functionality of opening the website in a Browser and using deeplinks to return back to the App, because WebView treats all links as if they should be opened in the WebView itself.

### Platform(s)

Android and iOS

### Preferred Solution

Make it possible to use a flag when using the Browser Plugin to specify if the WebView should be opened or like in Version 2.4.7 the main browser should be used.

### Alternatives

I didn't find an alternative to this, I consider this functionality to be standard and the change a breaking change.

### Additional Context

Reproduction can be found in this repository:
https://github.com/sanderschnydrig/capacitorFeatureRequestBrowser

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by sanderschnydrig** [comment]
Umm.. Sure. Here you go!

https://github.com/sanderschnydrig/capacitorFeatureRequestBrowser

**Comment by jcesarmobile** [comment]
Browser plugin is supposed to open the url you pass in an "In App" Browser, it's always been like that, if if was opening Safari/Chrome for you, you were probably using the web version that uses `window.open` instead of the native code.

If you want to open Safari/Chrome you can use `window.open`, or you can use [app-launcher's plugin openUrl method](https://capacitorjs.com/docs/apis/app-launcher#openurl)

**Comment by sanderschnydrig** [comment]
@jcesarmobile window.open worked for opening the main browser, thanks!
