### ISSUE TITLE
bug:  Impossible to install com-badrit-base64 on capacitor iOS

### ISSUE THREAD

**Issue by c3d4ic** [ionic-team/capacitor#4625]
Imposible to install com-badrit-base64 (0.2.0).

Here is the message when I create the iOS platform with capacitor. It's normal for filechooser and filepath because there are only available for android but for base64 it's suppose to work with iOS.

✔ Updating iOS native dependencies with "pod install" (may take several minutes) in 8.61s
  Found 3 incompatible Cordova plugins for ios, skipped install
    com-badrit-base64 (0.2.0)
    cordova-plugin-filechooser (1.2.0)
    cordova-plugin-filepath (1.6.0)

And there is my npx cap doctor result : 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/electron: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/electron not installed

**Comment by jcesarmobile** [comment]
all those plugins are android only, that's why they appear as incompatible on iOS

`com-badrit-base64`, despite it says it supports iOS, it doesn't have ios section in the `plugin.xml`.

The plugin only uses a canvas to create the base64, you don't need a plugin for that
