### ISSUE TITLE
bug: npx cap copy creates empty capacitor.config.json file in ios/App/App

### ISSUE THREAD

**Issue by victorgatto** [ionic-team/capacitor#4633]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: not installed (i think this is installed globally)
  @capacitor/android: not installed
  @capacitor/core: 3.0.0
  @capacitor/ios: 3.0.0

### Platform(s)

macOS

### Current Behavior

Running npx cap copy creates empty capacitor.config.json file in ios/App/App. This is shown in Xcode as well as finder.

### Expected Behavior

ios/App/App/capacitor.config.json should reflect identical source as project root config file.

### Code Reproduction

 npx cap copy or  npx cap copy ios

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jcesarmobile** [comment]
I don't think @capacitor/cli works fine if installed globally, it should be local to your project. And even if it's global, it should make sure it's 3.0.0, all capacitor packages should have the same version

**Comment by victorgatto** [comment]
> I don't think @capacitor/cli works fine if installed globally, it should be local to your project. And even if it's global, it should make sure it's 3.0.0, all capacitor packages should have the same version

Thanks, i'll do a local install and see if it helps.
