### ISSUE TITLE
bug: Live reload is not working in ionic

### ISSUE THREAD

**Issue by Gabriel-des** [ionic-team/capacitor#4643]
## Ionic Info

```
Ionic CLI                     : 6.16.1 (C:\Users\Gabriel Vieira\AppData\Roaming\npm\node_modules@ionic\cli)
  Ionic Framework               : @ionic/angular 5.6.7
  @angular-devkit/build-angular : 0.1102.10
  @angular-devkit/schematics    : 11.2.13
  @angular/cli                  : 11.2.13
  @ionic/angular-toolkit        : 3.1.1

Capacitor:
  Capacitor CLI      : 3.0.0
  @capacitor/android : 3.0.0
  @capacitor/core    : 3.0.0
  @capacitor/ios     : not installed

Utility:
  cordova-res : 0.15.3
  native-run  : 1.3.0

System:
  NodeJS : v14.16.1 (C:\Program Files (x86)\nodejs\node.exe)
  npm    : 6.14.12
  OS     : Windows 10
```

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
```

### Platform(s)
I tested only in android.

### Current Behavior
I created a new app using capacitor 3, in this app I tried to use the [`capacitor run`](https://ionicframework.com/docs/cli/commands/capacitor-run).

When usign the command `ionic capacitor run android -l --external` to run my app, the console returns:
> `Which device would you like to target? (Use arrow keys)`
And nothing appears in console, if I type "Enter", this message is show:
> `TypeError: Cannot read property 'value' of undefined`

### Expected Behavior
Open app in a device

### Code Reproduction
`ionic capacitor run android -livereload --external`

### Other Technical Details

I tried install `@ionic/cli@testing` as mentioned in THIS ISSUE, but didn't work. The only way to test my app is using `ionic cap build android`, but it is very time consuming.

I also tried to use `ionic capacitor run android -l --address=myIp`, as mentioned in [Ionic Forum](https://forum.ionicframework.com/t/ionic-capacitor-live-reload-not-working-on-android/190767/3?u=leonardofmed), but this didn't work either.

`npm --version` output: 6.14.12

`node --version` output: v14.16.1

### Additional Context
https://github.com/ionic-team/capacitor/issues/4449

**Comment by alexedwalvarado** [comment]
I'm having right the same problem!

**Comment by jcesarmobile** [comment]
the problem is the same as https://github.com/ionic-team/capacitor/issues/4571

capacitor run command searches for connected devices and configured emulators, but for some reason it's not finding yours, so shows an empty list

**Comment by kunalchikte** [comment]
I had the same issue, using this command resolve it:
`ionic capacitor run android -l --external --open`

P.S. I am replying to this question after the year, all of you should get the solution already. but it might help new users who might hit here from google in the search for the solution.

**Comment by Topiya** [comment]
> I had the same issue, using this command resolve it: `ionic capacitor run android -l --external --open`
> 
> P.S. I am replying to this question after the year, all of you should get the solution already. but it might help new users who might hit here from google in the search for the solution.

I am getting below error while live reload in ionic capacitor app.
`net::ERR_CONNECTION_TIMED_OUT`

Can anyone please help me t solve this error?
