### ISSUE TITLE
bug: Capacitor CLI Launches new instance of android studio on build

### ISSUE THREAD

**Issue by Mozart-Alkhateeb** [ionic-team/capacitor#4653]
### Capacitor Version

```
[warn] The hideLogs configuration option has been deprecated. Please update to use loggingBehavior instead.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌
```

### Platform(s)
Android on macOS

### Current Behavior
each time I run **ionic cap build android** it launches a new instance of android studio

### Expected Behavior
As before update in current instance

### Code Reproduction

- Make changes 
- ionic cap build android (Launches an instance of Android Studio)
- Make more Changes
- ionic cap build android (Launches another Instance)

### Other Technical Details

- Using android studio from InteliJ Idea
- `bashrc` : export CAPACITOR_ANDROID_STUDIO_PATH="/Users/myuser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app"

`npm --version` output: 7.14.0

`node --version` output: v14.16.0

**Comment by Saqib92** [comment]
Same issue on Windows 10.

**Comment by jcesarmobile** [comment]
Sadly we can't know if Android Studio is open or not to not open it if already open, it's the OS or the own Android Studio what should detect that is already open and not open it again.

If you don't want to open Android Studio you can use `--no-open` option on build command `ionic cap build android --no-open`

**Comment by Mozart-Alkhateeb** [comment]
In capacitor 2 this was not the behavior, but problem solved with `--no-open`
