### ISSUE TITLE
bug: Keyboard plugin throws error when running in browser in responsive design mode

### ISSUE THREAD

**Issue by ldikmans** [ionic-team/capacitor#4655]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Running an hybrid app in responsive design mode in Browser on my desktop (MacBook)

### Current Behavior

Import the Keyboard plugin. 
Add some code

1. Type 'ionic serve'
2. Go to the Browser window that opened (http://localhost:8100)
3. Open responsive mode and set it to iPhone)

Uncaught (in promise) Error: "Keyboard" plugin is not implemented on web
    at createPluginMethod (runtime.js:70)
    at runtime.js:77

### Expected Behavior

I would expect an undefined Keyboard, that I can check for in the code , not an exception to be run.

```
import {Keyboard, KeyboardInfo} from '@capacitor/keyboard';
`if(Keyboard)`
```

### Code Reproduction
 [https://github.com/ldikmans/Keyboardbug](https://github.com/ldikmans/Keyboardbug)

```
import { getPlatforms, IonContent, IonHeader, IonPage, IonTitle, IonToolbar } from '@ionic/react';
import ExploreContainer from '../components/ExploreContainer';
import './Home.css';
import { Keyboard, KeyboardInfo } from '@capacitor/keyboard';

const Home: React.FC = () => {

  if (getPlatforms().indexOf('mobile') !== -1 && Keyboard) {
    console.log('mobile platform detected');
    Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
      console.log('keyboard will show');
    });

    Keyboard.addListener('keyboardWillHide', () => {
      console.log('keyboard will hide');
    });
  };
  
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Blank</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Blank</IonTitle>
          </IonToolbar>
        </IonHeader>
        <ExploreContainer />
      </IonContent>
    </IonPage>
  );
};

export default Home;
```

1. Download the code
2. Run npm install
3. run ionic serve
4. open a browser window (Chrome or Firefox)
5. Set it to responsive mode (iPhone X for example)
6. Open the application: http://localhost:8100 (or whatever port it is running on)
7. Error shows up

### Other Technical Details

`npm --version` output: 6.14.10
`node --version` output: v14.15.4
`pod --version` output (iOS issues only): 1.10.1

### Additional Context
Before we migrated to capacitor 3.0 we used an additional check: 
```
import { Capacitor, Plugins, KeyboardInfo } from '@capacitor/core';

if (isDevice() && Capacitor.isPluginAvailable("Keyboard")) {
    Keyboard = Plugins.Keyboard;
    Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
      setIsKeyboardVisible(true);
    });
 
    Keyboard.addListener('keyboardWillHide', () => {
      setIsKeyboardVisible(false);
    });
  };
```

we would like an opportunity to get similar functionality

**Comment by jcesarmobile** [comment]
`Capacitor.isPluginAvailable("Keyboard")` is still available in Capacitor 3

**Comment by ldikmans** [comment]
Thanks for the quick response. I initially did not find this in the documentation. 
Here it is for anybody who is interested [https://capacitorjs.com/docs/v2/basics/utilities#ispluginavailable](https://capacitorjs.com/docs/v2/basics/utilities#ispluginavailable)

Because of the import error, we do end up with more code:

```
 async function getKeyboard(){
    if(!Keyboard){
      Keyboard = (await import('@capacitor/keyboard')).Keyboard;
      Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
        setIsKeyboardVisible(true);
      });
  
      Keyboard.addListener('keyboardWillHide', () => {
        setIsKeyboardVisible(false);
      });
    }
  }

 if (Capacitor.isPluginAvailable("Keyboard")){
    getKeyboard();
  };
```
It would be nice if there was no error, but an undefined after the Keyboard has been imported.

**Comment by jcesarmobile** [comment]
I've created an issue to document isPluginAvailable and other utilities in v3 docs, looks like we lost them then v3 docs were generated
https://github.com/ionic-team/capacitor-site/issues/312

Sadly all plugins are proxies, so they are always defined in all the platforms, you have to rely on isPluginAvailable
