### ISSUE TITLE
bug: ion-picker TypeError: win.Capacitor.isPluginAvailable is not a function.

### ISSUE THREAD

**Issue by MB-Jan** [ionic-team/capacitor#4660]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/ios: 3.0.0-rc.4
```

### Platform(s)
- iOS

### Current Behavior
ion-picker does not work on iOS devices. It shows up but is unresponsive. Only the cancel and select buttons are working, but swiping through the available options is not possible. Xcode shows the following error when trying swipe through the available options in the picker element:
`TypeError: win.Capacitor.isPluginAvailable is not a function. (In 'win.Capacitor.isPluginAvailable('Haptics')', 'win.Capacitor.isPluginAvailable' is undefined)
⚡️  URL: capacitor://localhost/common.js
⚡️  [error] - {}
⚡️  common.js:154:83
`

### Expected Behavior
ion-picker element should function without issues. 

### Code Reproduction
It is very easy to reproduce. Simply install any of the ionic starter apps with Angular (I used the tabs app) and then add the ion-picker element anywhere. 
I for instance only adjusted two files in the tabs starter app for testing:
**tab1.page.ts**
```
import { Component } from '@angular/core';
import { PickerController } from '@ionic/angular';
import { PickerOptions } from "@ionic/core";

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {

  constructor(private picker: PickerController) {

  }

  async pickerPresent() {
    let options: PickerOptions = {
      buttons: [
        {
          text: "Cancel",
          role: 'cancel'
        },
        {
          text:'Select',
          handler:(value:any) => {
            console.log(value);
          }
        }
      ],
      columns:[{
        name:'Language',
        options:[{
          text: "Test 1",
          value: 'test1'
        },
        {
          text: "Test 2",
          value: 'test2'
        },
        {
          text: "Test 3",
          value: 'test3'
        }
        ]
      }]
    };

    let picker = await this.picker.create(options);
    picker.present()
  }

}
```

**tab1.page.html**
```
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-title>
      Tab 1
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Tab 1</ion-title>
    </ion-toolbar>
  </ion-header>

  <app-explore-container name="Tab 1 page"></app-explore-container>
  <ion-button (click)="pickerPresent()">Trigger Picker</ion-button>
</ion-content>
```

### Other Technical Details
`npm --version` output: 7.7.5

`node --version` output: v16.2.0

`pod --version` output (iOS issues only): 1.9.3

### Additional Context
I tested it with iOS Simulator and with a real iOS device. Both behave identically. The ion-picker works fine when the app is being run through the browser, incl. Ionic lab.

### Possible Duplicates
I found the following two issues that are similar:

1. [4609](https://github.com/ionic-team/capacitor/issues/4609)
2. [4589](https://github.com/ionic-team/capacitor/issues/4589): This is supposed to be a fix, but it is not yet part of the main branch. If this is indeed an approved/valid fix please add it to the master branch and/or confirm here that it is safe to use.

**Comment by jcesarmobile** [comment]
Our main branch is main, not master, that’s merged into main, but not released on npm yet.

as workaround you can add import '@capacitor/core'; in your main.ts file until the fix is published

**Comment by aiglesiasn** [comment]
> Our main branch is main, not master, that’s merged into main, but not released on npm yet.
> 
> as workaround you can add import '@capacitor/core'; in your main.ts file until the fix is published

Hi!! One question about this.
I see that in npm the latest release of @capacitor/core is 3.0.1, but date-picker is still not working unless I include:
import '@capacitor/core'; 

in the main.ts.

I asume that somehow npm still doesn't have the correct release  or something.

How do I now when npm has the correct release?

Thanks for your time!

**Comment by jcesarmobile** [comment]
It really depends on your app, did you install @capacitor/core 3.0.1 in your app? check your package.json and package-lock.json files and see if you are using 3.0.1, the import should not be needed anymore

**Comment by aiglesiasn** [comment]
Gracias jcesarmobile! To double check, I reinstalled capacitore/core capacitor/cli and capacitor/ios (which I didn't update the first time and was still on 3.0.0) and everything start working without the import.
Have a great weekend!
