### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by systemlord01** [ionic-team/capacitor#4666]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0

  @capacitor/core: 3.0.0

  @capacitor/android: 3.0.0

  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.3.0

  @capacitor/core 2.4.7

  @capacitor/ios 2.4.7


[success] iOS looking great! 👌

```

### Platform(s)
IOS

### Current Behavior
when in console of iframe the window element in iframes:
window.Capacitor.platform === 'web' is true.
The top frame has the expected behaviour
window.Capacitor.platform === 'ios'is true

### Expected Behavior
both should be 'ios'

### Code Reproduction
Make a simple app displaying a page with an iframe

### Other Technical Details

`npm --version` output: 6.14.6

`node --version` output: v12.18.3

`pod --version` output (iOS issues only): 1.10.0

### Additional Context
I think this can possible break any plugin interaction from the iframe page to Capacitor itself. All plugins could be broken when called from within the iframe.

**Comment by jcesarmobile** [comment]
this is by design, plugins are only available in the main frame, iframes should never use your plugins
