### ISSUE TITLE
bug: `cap update` Fails when using Yarn v2 and Custom Plugins in a Workspace

### ISSUE THREAD

**Issue by PowerOfM** [ionic-team/capacitor#4682]
## Bug Report

The command `cap update` fails when in a workspace using Yarn v2 and one of the plugins is a local package in the workspace.

### Capacitor Version
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android, iOS

### Current Behavior
When running `yarn cap update` inside an app within a workspace, if the app depends on a custom plugin that is also in the workspace, the script updates the `capacitor.settings.gradle` and `Podfile` with virtual paths instead of relative paths to the local folders. Other packages that are installed from the npm registry are unaffected.

Example `capacitor.settings.gradle` output:
```
include ':my-custom-plugin'
project(':my-custom-plugin').projectDir = new File('../../../.yarn/$$virtual/my-custom-plugin-virtual-a1a16c7b75/1/packages/my-custom-plugin/android')
```

Example `Podfile` output:
```
  pod 'MyCustomPlugin', :path => '../../../../.yarn/$$virtual/my-custom-plugin-virtual-a1a16c7b75/1/packages/my-custom-plugin/ios''
```

The result of these outputs is the following errors:
```
[error] Analyzing dependencies
        [!] No podspec found for `MyCustomPlugin` in
        `../../../../.yarn/$$virtual/my-custom-plugin-virtual-a1a16c7b75/1/packages/my-custom-plugin/ios'`
```

### Expected Behavior
The script should update with a relative path to the folder directly in the workspace. For example:
```
../../../.yarn/$$virtual/my-custom-plugin-virtual-a1a16c7b75/1/packages/my-custom-plugin/android
```
should be
```
../../my-custom-plugin/android
```

### Code Reproduction
In this example, the workspace contains 2 packages, `echo` (a capacitor plugin), and `app` (a react app with capacitor). The `app` depends on `echo`. When running `cap sync` the path to `echo` resolves to a virtual path that gradle/pod cannot access, instead of just using the relative path to the local `echo` folder.
https://github.com/PowerOfM/cap-test-workspace

### Other Technical Details
`yarn --version` output: `2.4.1`

`npm --version` output: `6.14.8`

`node --version` output: `v14.15.0`

`pod --version` output (iOS issues only): `1.10.0`

### Additional Context
Simply changing the paths fixes the problem. Perhaps a simple fix would be to have an optional `path` value in the config entry for each plugin.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jcesarmobile** [comment]
the issue is caused by `@yarnpkg/pnpify`, if I uninstall it, it works.

considering that package says
> Due to how PnPify emulates the node_modules directory, some problems are to be expected, especially with tools that watch directories inside node_modules.

I consider it a bug there and not in Capacitor
