### ISSUE TITLE
[documentation question] - Capacitor 3 permissions prompt-with-rationale

### ISSUE THREAD

**Issue by jonathan-chin** [ionic-team/capacitor#4686]
hi all, I'm migrating from Capacitor 2.x to 3.x and on nearly all of the plugins I've seen with a checkPermission() method, they return a PermissionStatus that could take the value of `prompt-with-rationale`

I've tried doing a lot of research but I can't seem to find any explanation of this permission state. how is it different than `prompt`?

**Comment by jcesarmobile** [comment]
It's explained here, maybe not the best place
https://capacitorjs.com/docs/plugins/web#aliases

In Android the same permission can be requested multiple times, so the flow is something like this:
First time you check the status -> prompt
If the permission was already prompted but the user denied it, next time you check the permission status will be prompt-with-rationale
It will remain in prompt-with-rationale unless the user checked the "Do not ask again", in that case will change to denied.

prompt with rationale means you should try to convince the user to grant the permission

android docs about it, check the point 5
https://developer.android.com/training/permissions/requesting
