### ISSUE TITLE
bug: Facebook post video not working on iOS

### ISSUE THREAD

**Issue by sanderschnydrig** [ionic-team/capacitor#4688]
### Capacitor Version

```
💊   Capacitor Doctor  💊 
 
Latest Dependencies:
 
  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0
 
Installed Dependencies:
 
  @capacitor/cli: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/ios: 3.0.0
 
[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

When embedding a Facebook post via XFBML.parse in accordance to the Facebook Javascript SDK ( https://developers.facebook.com/docs/reference/javascript/FB.XFBML.parse/ ) the videos are not playable on iOS. Android works just fine.

### Expected Behavior

The video in an embedded Facebook post should be playable in the app on iOS.

### Code Reproduction

https://github.com/sanderschnydrig/capacitorFacebookVideo

### Other Technical Details

`npm --version` output:
7.16.0

`node --version` output:
v16.0.0

`pod --version` output (iOS issues only):
1.10.1

**Comment by jcesarmobile** [comment]
If you inspect the app in safari remote inspector you'll see different errors thrown by facebook SDK.

```
ErrorUtils caught an error:
Minified invariant #11793;  Params: capacitor
Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
ErrorUtils caught an error:
Minified invariant #11793;  Params: capacitor [Caught in: Module "__inst_b449bc2b_0_0_io"]
Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
ErrorUtils caught an error:
Minified invariant #11793;  Params: capacitor [Caught in: Module "__inst_b449bc2b_0_0_io"] [Caught in: Requiring module "__inst_b449bc2b_0_0_io" which threw an exception]
Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
```

So looks like a problem on their SDK or some incompatibility.

**Comment by sanderschnydrig** [comment]
If I run the Facebook post with the video in a WebView with Browser.open() it works however. So it must be an issue with the specific version of WKWebView capacitor is using, no?

**Comment by jcesarmobile** [comment]
Sadly not all web SDKs that work on web work on WKWebView apps and in those cases you need to use plugins that use the native SDK instead of the web SDK and this looks like the case.

It's usually caused because WKWebView apps load from file:// or a custom scheme (capacitor:// in Capacitor apps) and some web SDKs don't work from there.
Sometimes the problem is in the server and they can fix it, so probably better to ask them if their SDK is supported in WKWebView apps
