### ISSUE TITLE
Instant launch UI

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#469]
We could do some really awesome stuff to have an instant launch screen with UI skeleton instead of splash screen. @manucorporat has some thoughts

**Comment by jamesharvey2** [comment]
I recommend SVG UI animations: 
http://animejs.com/

https://codepen.io/juliangarnier/pen/RRKEoB

**Comment by jcesarmobile** [comment]
@manucorporat can you elaborate on your thoughts?

**Comment by dwieeb** [comment]
I would also like to chime in and say that both iOS and Android seem to be moving away from splash screens.

@manucorporat ping!
