### ISSUE TITLE
feat: firebase push notification not showing image when quasar framework with capacitor.

### ISSUE THREAD

**Issue by chris-yeung** [ionic-team/capacitor#4696]
firebase push notification not showing image when quasar framework with capacitor.

I am quasar to build the mobile app, when i try to set up firebase push notification in the app, it work in the mobile. however, when i add the image path to it, it didn't show in the notification but the message can also push. Is the feature exist?

**Comment by thomasvidas** [comment]
There is nothing in Capacitor that should prevent this. Check the [Firebase Docs](https://firebase.google.com/docs/cloud-messaging/android/send-image) on how to send an image with a notifcation
