### ISSUE TITLE
bug: Getting Object.cap.fromNative not implemented error in Android after upgrading to Capacitor 3

### ISSUE THREAD

**Issue by jesperbjerke** [ionic-team/capacitor#4698]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior

After having upgraded and gone through the migration guide from Capacitor 2 to 3 I am getting the following error as soon as the app initializes (running on a real device), only on Android:

From logcat:
```
E/Capacitor/Console: File: http://localhost/main-es2015.c00bfc67f6056215629c.js - Line 1 - Msg: Error: Uncaught (in promise): Error: not implemented
    Error: not implemented
        at Object.cap.fromNative (http://localhost/:422:32)
        at <anonymous>:1:18
```

### Expected Behavior
This error did not occur with Capacitor 2. It also does not happen in iOS and not in web.

### Code Reproduction
Not possible to provide unfortunately. Hopefully maybe you can guide me in the right direction where to debug this anyway.

### Other Technical Details

`npm --version` output: 6.14.11

`node --version` output: v14.15.0

`npx cap ls output:`
```
[info] Found 12 Capacitor plugins for android:
       @capacitor/app@1.0.0
       @capacitor/camera@1.0.0
       @capacitor/device@1.0.0
       @capacitor/filesystem@1.0.0
       @capacitor/geolocation@1.0.0
       @capacitor/haptics@1.0.0
       @capacitor/keyboard@1.0.0
       @capacitor/network@1.0.0
       @capacitor/push-notifications@1.0.0
       @capacitor/share@1.0.0
       @capacitor/splash-screen@1.0.0
       @capacitor/status-bar@1.0.0
[info] Found 1 Cordova plugin for android:
       cordova-sqlite-storage@6.0.0
```

**Comment by jcesarmobile** [comment]
I can't reproduce, so unfortunately if you can't provide a sample app we won't be able to help you.

**Comment by jesperbjerke** [comment]
I found the issue. I was calling `Keyboard.setAccessoryBarVisible({isVisible: true});` upon app initialization, without checking if it's iOS or not.

It would be really helpful if the "not implemented" error would say which method was called, so it's easier to debug. I'll post a feature request for this.
