### ISSUE TITLE
Figure out plan to support Ionic Native wrappers

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#470]

**Comment by jcesarmobile** [comment]
I have only tested a few, but looks like they just work (as long as the Cordova plugin works fine with Capacitor)

Or you mean Ionic wrappers to wrap Capacitor plugins instead of Cordova ones?

**Comment by jcesarmobile** [comment]
Closing as they already work if the Cordova plugin works, we don't need to do anything.
If the issue was about having similar wrappers for Capacitor plugins, I think it should be a separate project to make it less confusing.
