### ISSUE TITLE
bug: capacitor.config.json does not have the feature of integrating to multiprojects monorepo

### ISSUE THREAD

**Issue by Radecom** [ionic-team/capacitor#4710]
### Current Behavior

Hello, first of all, congratulations on your excellent work, I have admired you for more than 5 years.

I was so excited about your [Ionic Angular monorepos with NX publication](https://ionicframework.com/blog/ionic-angular-monorepos-with-nx/) that I went ahead trying to move my angular projects (angular and ionic) to a monorepo with Nx.

I am trying to get the plugin to work:

`'@codetrix-studio/capacitor-google-auth';`

in an ionic-angular project inside an Nx workspace:
But, once installed I get this error:

`Error: Module not found: Error: Can't resolve '../../../../../capacitor.config.json'`

and I had patched it by specifying the capacitor.config.json file location, but when developers work with multiple ionic projects. How are we going to patch it?

The question here is:
Will the capacitor.config.json file need to be re-constructed to be multi-project?

or the developers of the plugin @codetrix-studio/capacitor-google-auth should modify their logic thinking that there are already many multi-application projects and that they do not have the capacitor.config.json file at the root of the project

**Thank you very much in advance for your time.**

**Comment by jcesarmobile** [comment]
They will need to rethink, specially now that it can be a .ts or .js file too

looks like there is a draft pr already 

https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/114/files
