### ISSUE TITLE
bug: Domain Whitelisting issue

### ISSUE THREAD

**Issue by iamtarun1993** [ionic-team/capacitor#4711]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/electron: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 6 Capacitor plugins for ios:
    @capacitor-community/camera-preview (1.0.6)
    cordova-plugin-googleplus (8.5.0)
    cordova-plugin-inappbrowser (4.0.0)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-telerik-imagepicker (2.3.5)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌
```

### Platform(s)
Android and iOS

### Current Behavior
Both Android and iOS app is allowing all domain to run in an iframe

### Expected Behavior
The app should block running external scripts from untrusted domains.

### Code Reproduction

I’m working on an app and using ionic 5, capacitor 2, and angular 10. for security reasons, I need to add domain white listing.
So I modified config.xml file and changed <access origin="*"/> to <access origin="https://*.something.com" in both android and iOS.

After running the app live on a device using ionic capacitor run android -l --external --configuration=staging I can still load an iframe and access content from “abc.com” or any other domain?

Is domain whitelisting not possible in ionic capacitor?

**Comment by jcesarmobile** [comment]
Capacitor doesn't have whitelist functionality and doesn't use config.xml, that's for Cordova
