### ISSUE TITLE
bug: Capacitor plugin Http sends encoded parameter wrongly

### ISSUE THREAD

**Issue by arasrezaei** [ionic-team/capacitor#4716]
## Bug Report

  @capacitor/cli: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

```
PASTE OUTPUT HERE
```

### Platform(s)
Tested on android (device and emulator)

### Current Behavior
this code retrieves tweets from twitter by graphql cursor. it works on NodeJS with "nodejs-fetch" and other environments. but in capacitor http plugin twitter responses with 'BAD REQUSET'. may be there is some problems with encoding or decoding.

```
       const { data } = await Http.request({
            url: 'https://twitter.com/i/api/2/timeline/conversation/${id}.json?',
            headers: {
                'content-type': 'application/json',
                "authorization": BEARER,
                "x-guest-token": guestToken,
            },
            params: {
                ...cursor && { cursor: encodeURIComponent(cursor) }
            },
            method: 'GET'
        });
```
and the one of the cursor values is "LBlmgMC4tbGCiMsmhMC9sZ+NhcsmgICysfXii8smgMC96c/Gi8smhMC5lf2OissmgMC44fizgssmJQISAAA=" which needs to be encoded.

### Expected Behavior
should work fine like other environments;

### Code Reproduction
may be encoding and decoding!

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
What do you mean by “capacitor plugin http”?

**Comment by jcesarmobile** [comment]
What do you mean by “capacitor plugin http”?

**Comment by arasrezaei** [comment]
This plugin:
https://github.com/capacitor-community/http

I investigated it and think there is a problem with encode/decode parameters in that plugin/or may be the capacitor itself?

**Comment by arasrezaei** [comment]
> What do you mean by “capacitor plugin http”?

This plugin:
https://github.com/capacitor-community/http

I investigated it and think there is a problem with encode/decode parameters in that plugin/or may be the capacitor itself?

**Comment by jcesarmobile** [comment]
Yeah, it’s probably a bug in the plugin, I can’t transfer the issue because it’s a different org, so can you create it there?
