### ISSUE TITLE
cordova-plugin-ibeacon doesn't list cordova-plugin-device as dependency

### ISSUE THREAD

**Issue by sdetweil** [ionic-team/capacitor#4718]
trying to add ibeacon support to inonic vue app .

https://ionicframework.com/docs/native/ibeacon

**Comment by jcesarmobile** [comment]
I see it listed on add/update/sync commands

```
[warn] Plugins are missing dependencies.
       Cordova plugin dependencies must be installed in your project (e.g. w/ npm install).
       
       cordova-plugin-ibeacon is missing dependencies:
       - cordova-plugin-device (*)
```

If you mean that it's not automatically installed, capacitor 3 no longer installs any package because there are a lot and each one of them is different, so the CLI just warns that it's missing and tell the users they have to install it manually
