### ISSUE TITLE
ion-icon shows both ios and material icons

### ISSUE THREAD

**Issue by cleversolutions** [ionic-team/capacitor#472]
Including https://unpkg.com/@ionic/pwa-elements@0.0.11/dist/ionicpwaelements.js in index.html causes ion-icon to render two icons stacked on top of the other when using ionic serve. 

You can reproduce by adding <ion-icon name="camera"></ion-icon> to any page (ie camera) in the example project. 

It seems to be picking up both the current (css :before) and future (svg image) implementations for the icons. It's easy to work around it. I've just added this to my app.scss file
```
.icon-inner{
    display: none;
}
```

**Comment by lolaswift** [comment]
@cleversolutions Thx for the workaround Evan. I had the same issue.

**Comment by jcesarmobile** [comment]
Updating to ionic pwa elements 1.0.0 fixes the problem.
