### ISSUE TITLE
bug: iOS platform detection wrong, when WKAppBoundDomains is in Info.plist

### ISSUE THREAD

**Issue by gerritvanaaken** [ionic-team/capacitor#4721]
### Capacitor Version
```

  @capacitor/cli: 3.0.0-rc.4
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1
```

### Platform(s)
iOS

### Current Behavior

Capacitor detects platform as "web" although it is clearly synced and running on iOS Simulator.

### Expected Behavior

platform should be "ios", when built for and running on iOS.

### Code Reproduction

Add key "WKAppBoundDomains" to the Info.plist in the ios/App folder

You don’t even have to add domain entries.

````
<key>WKAppBoundDomains</key>
<array>
	<string>mydomain.com</string>
</array>
````

**Comment by jcesarmobile** [comment]
Adding `WKAppBoundDomains` key blocks JavaScript injection and other WKWebView features unless `limitsNavigationsToAppBoundDomains` is set to `true` (which is not possible at the moment, will be after the linked PR gets merged).
Without the JavaScript injection, native plugins don't work and the web version is used instead.

More information about App Bound Domains and how they affect the WKWebView can be found [here](https://webkit.org/blog/10882/app-bound-domains/)
