### ISSUE TITLE
feat: Camera preview display overlay component while taking picture

### ISSUE THREAD

**Issue by sinkingtitanic** [ionic-team/capacitor#4722]
## Feature Request
Is there a way to display text and shapes (another Angular component) while taking a picture. (please see screenshot below) 
### Description

Possible display Angular component above camera preview to guide user in specific cases. 

### Platform(s)

All (web, iOS and Android) 

### Preferred Solution

Displaying overlay component 

### Alternatives

This is doable through [community camera preview](https://github.com/capacitor-community/camera-preview) but it has a lot of bugs and does not support latest capacitor version as of this moment. It is also not very development friendly as you have to make your own "capture" buttons. 

### Additional Context

![ionic-camera](https://user-images.githubusercontent.com/20634657/122001589-9826e480-cdc1-11eb-8fda-a963eae73d2a.png)

**Comment by oneclickwebstudio** [comment]
+1  

`@capacitor-community/camera-preview` brakes my working app.

**Comment by jcesarmobile** [comment]
This is not possible on the Capacitor Camera plugin since the native components it uses don't allow it
