### ISSUE TITLE
Native wrapper for SDK packages?

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/capacitor#473]
Hello Capacitor team, 

Is it possible for you guys to make Ionic native wrapper for popular open source Android & iOS SDK packages like Superpowered? 

http://superpowered.com

Functionality of this SDK package beats any cordova plugin.

Sorry for wanting too much.

Thanks,

**Comment by janpio** [comment]
Are you aware that you posted this in the Capacitor repository and not for Ionic Native?

**Comment by jamesharvey2** [comment]
sorry, moving the topic now
