### ISSUE TITLE
feat: (Capacitor 3) Custom swift code on push notification action triggered 

### ISSUE THREAD

**Issue by yacut** [ionic-team/capacitor#4735]
### Description
I would like to run custom swift code on push notification action

### Platform(s)
iOS

### Preferred Solution
Add notification center message each time notification response received, so everybody can subscribe to the queue:
https://github.com/ionic-team/capacitor/blob/b893a57aaaf3a16e13db9c33037a12f1a5ac92e0/ios/Capacitor/Capacitor/NotificationRouter.swift#L49-L57
```
NotificationCenter.default.post(name: .capacitorDidReceiveNotificationResponse, object: notification)
```

### Additional Context
 related to https://github.com/ionic-team/capacitor/issues/1631#issuecomment-515117202

**Comment by jcesarmobile** [comment]
You can define your own notification handlers as push and local notification plugins do
https://github.com/ionic-team/capacitor-plugins/blob/main/local-notifications/ios/Plugin/LocalNotificationsPlugin.swift#L31

**Comment by yacut** [comment]
@jcesarmobile But what if I want use both? My App uses Remote and Local Notifications plugins and additionally I want to run native code. Is it possible too?

**Comment by jcesarmobile** [comment]
no, it's not possible to have 2 handlers, you can fork the plugins and add any code you want in them.

**Comment by yacut** [comment]
That's what I was afraid of. Well, since this is the only solution, I have no choice. Thank you.

**Comment by aidan2129** [comment]
Did anyone get anywhere with this? I tried making my own NotificationHandler setting pushNotificationHandler on load  but the capacitor/push-notifications implematation is fired after mine overwriting it.

Commenting out the line in capacitor/pish-notifications makes it use my own one but I dont think this is ideal. Is there anyway to make it priorities the first handler set?
[self.bridge?.notificationRouter.pushNotificationHandler = self.notificationDelegateHandler](https://github.com/ionic-team/capacitor-plugins/blob/5bebfefe9bdca4d49f0e02dab74b02a692d3ed86/push-notifications/ios/Plugin/PushNotificationsPlugin.swift#L22)
