### ISSUE TITLE
bug: Camera Options doesn't work

### ISSUE THREAD

**Issue by BrunoAwdd** [ionic-team/capacitor#4737]
## Bug Report
Capacitor settings don't seem to work. I change the quality, but the image is still the same size. I limit the width, and nothing happens. I cannot upload uploads larger than 1MB to my server as this is not viable. Any suggestion?

### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 2.4.7

```

### Platform(s)

Android and Web

### Code Reproduction
```
public async addNewToGallery() {
        const options = {
            resultType: CameraResultType.Uri,
            source: CameraSource.Camera,
            quality: 1,
            width: 720,
            webUseInput: true,
        };
        const capturedPhoto = await Camera.getPhoto(options);
        // tslint:disable-next-line:no-non-null-assertion
        const response = await fetch(capturedPhoto.webPath!);
        const blob = response.blob().then(data => {
            console.log(data.size / (1024 * 1024));
        });


        console.log(capturedPhoto, options);
        return capturedPhoto;
    }
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
On web is a known issue already reported.
For android, can you update to @capacitor/android 3.0.1 and install @capacitor/camera plugin?
If you still face the issue, report it on https://github.com/ionic-team/capacitor-plugins/issues

**Comment by BrunoAwdd** [comment]
The @capacitor/camera plugin: 1.0.1 is installed. @capacitor/android is updated
