### ISSUE TITLE
feat: [android] remove default titles from `JsAlert`, `JsConfirm` and `JsPrompt`

### ISSUE THREAD

**Issue by tafelnl** [ionic-team/capacitor#4738]
### Description
The following code:
```js
alert('Something to alert')
```
results in an alert like this:
![image](https://user-images.githubusercontent.com/35837839/122538031-724e4980-d026-11eb-84e3-cc32d10beb56.png)

Mind the  "Alert" title. I do not think it makes sense to show that title here. I know that custom alerts are already supported by Capacitor. But I still think 'normal' alerts should also be allowed and be shown without a title.

### Platform(s)
Android

### Preferred Solution
Remove the titles from `JsAlert`, `JsConfirm` and `JsPrompt` so it will be shown like this:

![image](https://user-images.githubusercontent.com/35837839/122537783-31eecb80-d026-11eb-839a-1b31745783d4.png)

This can be achieved by removing the following lines:
- https://github.com/ionic-team/capacitor/blob/883c0fe4a8a33d2e14894d9b307f4d7ce6d13bad/android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java#L145
- https://github.com/ionic-team/capacitor/blob/883c0fe4a8a33d2e14894d9b307f4d7ce6d13bad/android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java#L185
- https://github.com/ionic-team/capacitor/blob/883c0fe4a8a33d2e14894d9b307f4d7ce6d13bad/android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java#L234

**Comment by jcesarmobile** [comment]
This was fixed and released in Capacitor 4
https://github.com/ionic-team/capacitor/pull/5653
