### ISSUE TITLE
APK filename and buildpath hardcoded in capacitor/cli

### ISSUE THREAD

**Issue by mrambow** [ionic-team/capacitor#4740]
Hi,

we're using ionic 5 with capacitor 3 and having difficulties to get the livereload to work for our debug app. 
We get following error from `capacitor run android --livereload`:
`native-run Caught fatal error: [Error: ENOENT: no such file or directory, open 'MyProjectPath\android\app\build\outputs\apk\debug\app-debug.apk']`

After some digging (and failing to understand the gradle config build steps) I saw following lines in the capacitor run code:

https://github.com/ionic-team/capacitor/blob/9a6e74e2eee1f8fd09f915fe7651b09df52e96b5/cli/src/android/run.ts#L32
https://github.com/ionic-team/capacitor/blob/9a6e74e2eee1f8fd09f915fe7651b09df52e96b5/cli/src/config.ts#L230

Is there any possibility to change the name of the APK and the build path from the outside?

**Comment by jcesarmobile** [comment]
Yeah, they are hardcoded because that's where capacitor apps get build with gradle command. 
Did you change something in your gradle files to build somewhere else or with a different name?

**Comment by mrambow** [comment]
Yes, we added productFlavours in gradle, but didn't touch the build part.
Gradle is generating the files in 
`MyProjectPath\android\app\build\outputs\apk\%flavorName%\debug|release\something.apk`

**Comment by jcesarmobile** [comment]
Can you be more specific?

**Comment by mrambow** [comment]
Sure, just tell me what you want to see!

partial build.gradle:

```
buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }

  flavorDimensions 'stage'

  productFlavors {
    beta {
      dimension 'stage'
      versionNameSuffix '-beta'
      applicationId "de.com.stuff"
      signingConfig signingConfigs.beta
      manifestPlaceholders = [appLabel: "Name", customUrlScheme: "de.com.stuff"]
    }

    qa {
      dimension 'stage'
      versionNameSuffix '-beta'
      applicationId "de.com.stuff.beta"
      signingConfig signingConfigs.beta
      manifestPlaceholders = [appLabel: "Name QS", customUrlScheme: "de.com.stuff.beta"]
    }

    production {
      dimension 'stage'
      applicationId "de.com.stuff.prod"
      signingConfig signingConfigs.production
      manifestPlaceholders = [appLabel: "Name Prod", customUrlScheme: "de.com.stuff.prod"]
    }
  }
}
```

**Comment by gabides** [comment]
I have the same issue, we have several flavors and the path to our built APKs is not the one hardcoded so none of our flovors are building with the `capacitor run android` command.

One solution would be to make this path customizable in the capacitor.config.json, or as a CLI argument when running `capacitor run android`.

**Comment by gabides** [comment]
I have opened a PR with solution 1 which solves the issue on my side (https://github.com/ionic-team/capacitor/pull/4757), @jcesarmobile would something like this be acceptable?

with my changes @mrambow could set in the capacitor config : 
```
config.android. buildOutputApkName = "something.apk"
config.android.buildOutputDirCustom = "build\outputs\apk\%flavorName%\debug|release"

**Comment by jcesarmobile** [comment]
I've sent a similar PR that only adds `flavor` configuration option in the capacitor config file and build the apk name and directory based on it, I think that's simpler for users.
Tested with the flavor examples provided by mrambow  and works fine.

**Comment by gabides** [comment]
Nice, I have tested my project with @capacitor/cli on your branch and it works as expected, I agree it's simpler to just set the flavor inside the config.

**Comment by dragermrb** [comment]
Hi! 

Sorry to comment on a closed issue.

I usually rename outputs apk with this gradle config:

```
// File android/app/build.gradle
android{
   // ...
   // Rename outputs apk
    applicationVariants.all {
        variant ->
            variant.outputs.each {
              output->
                  output.outputFileName  = "AppName-${variant.name}-v${variant.versionName}.apk"
            }
    }
   // ...
}
```

This produces apk files like `MyApp-debug-v1.0.0.apk` which cannot be deployed with `ionic cap run android`. 

Capacitor could get final `apkName` from `android/app/build/outputs/apk/debug/output-metadata.json` so it will always be accurate. For example

```
  // File cli/src/android/run.ts, line ~32

  const metadata = require(`${config.android.buildOutputDirAbs}/output-metadata.json`);
  const apkName = metadata.elements[0].outputFile;

  const apkPath = resolve(
    config.android.buildOutputDirAbs,
    apkName
  );

  //...

  await runTask(
    `Deploying ${c.strong(apkName)} to ${c.input(target.id)}`,
    async () => runNativeRun(nativeRunArgs),
  );
```

I can make a PR if you want. What do you think?
