### ISSUE TITLE
bug: Android Capacitor3 call.getArray with null value failed

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/capacitor#4746]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/android: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/cli: 3.0.0
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

  npm: '7.6.0',
  node: '14.15.4',

**Comment by jepiqueau** [comment]
if an array values is passed ie [10,null,null,null]
call.getArray("values") return [10,null,"...","..."] instead of [10,null,null,null]

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
