### ISSUE TITLE
Service Worker issue ios protocol change from "capacitor://" to "http://"

### ISSUE THREAD

**Issue by phoenix503** [ionic-team/capacitor#4752]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1
```

### Code Reproduction
```
const config: CapacitorConfig = {
  appId: 'com.maximl.testapp',
  appName: 'demoapp',
  webDir: 'dist/CapacitorExperiments/',
  bundledWebRuntime: false,
  server: {
    iosScheme: "http",
    androidScheme: "http",
    allowNavigation: [
      "*",
    ],

  }
};
```

### Other Technical Details

`npm --version` output: 6.14.13

`node --version` output: v14.17.0

`pod --version` output (iOS issues only): 1.10.1

### Additional Context

`Please suggest any way to work with Service worker in iOS as android default uses http:// so no issue is coming in that part.`

**Comment by jcesarmobile** [comment]
It’s not possible to use http nor https on iOS, unless you use the server url option and point to a remote server, which is discouraged
