### ISSUE TITLE
npx cap open android just opens android directory in Windows Explorer

### ISSUE THREAD

**Issue by Wintermute79** [ionic-team/capacitor#4755]
### Capacitor Version
```
  @capacitor/ios: not installed
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/cli: 3.0.2

[success] Android looking great! 👌
```

### Platform(s)
Windows 10
Build 19041.1052

### Current Behavior
`npx cap open android` just opens the app's android directory in Windows Explorer instead of starting Android Studio.
I upgraded my Angular project from capacitor 2.4.7 to 3.0.2. Before upgrade, this worked.
When I start Android Studio manually, everything works fine, too.

### Expected Behavior
Should open Android Studio instead of Windows Explorer.

### Other Technical Details
`npm --version` output: 7.0.3
`node --version` output: v15.0.1
Android Studio version: 4.2.1
Android API level: 30

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by diegocloudstorm** [comment]
@Wintermute79 I was experiencing the same problem after upgrading from 2.4.7 to 3.0.0. Tracked down the issue to the `open` node module.

Running `npm install --save-dev open@7.4.2` did the trick for me.

**Comment by Wintermute79** [comment]
@dhernando Thank you! That solved it!
