### ISSUE TITLE
bug: Publishing iOS App gives error: Code signing "Capacitor.framework" failed.

### ISSUE THREAD

**Issue by simarpreetsinghkalra** [ionic-team/capacitor#4768]
### Capacitor Version

```

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.0.2
  @capacitor/ios: 3.0.2
  @capacitor/core: 3.0.2

```

### Platform(s)

iOS

### Current Behavior
Steps:
1. Running command `ionic capacitor open ios`
2. Xcode opens.
3. Click Product > Archive from toolbar
4. Build succeeds and Organizer window opens.
5. Click Distribute App
6. This happens. (Please see screenshot). 
![Screenshot 2021-06-28 at 11 40 53 AM](https://user-images.githubusercontent.com/28017507/123588868-0cbc4300-d806-11eb-9204-f28069e191b0.png)
7. [Here are the logs](https://drive.google.com/drive/folders/1k3vDkQliA12ILy_yOKpiOPSKqpWYQUK5?usp=sharing). 

### Expected Behavior
Should get published successfully.

### Code Reproduction

[Check my demo repository](https://github.com/simarpreetsinghkalra/ionic-cap-3-demo.git
)

### Other Technical Details

`npm --version` output:
6.14.11

`node --version` output:
v14.15.5

`pod --version` output (iOS issues only):
1.10.1

### Additional Context
`ionic version` output:
6.16.3

**Comment by jcesarmobile** [comment]
I've tried your test app, changed the id and submitted to the app store without problems.

What's your macOS version? Xcode version? are you on M1 mac or intel?

**Comment by simarpreetsinghkalra** [comment]
Thanks @jcesarmobile for you valuable response. I figured out what the issue was.

### macOS and Xcode version:
macOS: macOS 12.0 (21A5248p)
Model Name: MacBook Air
Model Identifier: MacBookAir7,2
Processor Name: Dual-Core Intel Core i5
Processor Speed: 1.6 GHz

### What was the problem?
On this screen the first option i.e. _Include bitcode for iOS content_  was automatically checked. I unchecked it and the problem got resolved.

![Screenshot 2021-06-28 at 10 00 32 PM](https://user-images.githubusercontent.com/28017507/123672061-926add80-d85c-11eb-91ae-c7032391296e.png)
