### ISSUE TITLE
feat: Lint/check `capacitor.config.json` for errors on `cap copy`

### ISSUE THREAD

**Issue by qpwo** [ionic-team/capacitor#4770]
### Description

An invalid setting in the config could raise an error or warning when you run `cap copy`. This is a common mistake, forgetting to put "url" under "server":

```json
{
    "appId": "com.splashcall.app",
    "appName": "SplashCall",
    "webDir": "build",
    "bundledWebRuntime": false,
    "url": "http://192.168.12.209:3000",
    "cleartext": true
}
```

### Platform(s)

Should happen on basically any `cap action` for any platform

### Preferred Solution

Give a warning.

### Alternatives

N/A

### Additional Context

N/A

**Comment by jcesarmobile** [comment]
You can now use a `capacitor.config.ts` file that has this feature built in, so we are not going to add any checks, sorry.

**Comment by qpwo** [comment]
Thanks I somehow missed that on the docs
