### ISSUE TITLE
bug: `allowNavigation` broken on 3.0.1 or 3.0.2?

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/capacitor#4775]
## Bug Report
I was using Capacitor 3.0.0 when I implemented a working `allowNavigation` logic. Recently I've upgraded to 3.0.1 and then to 3.0.2. Today I've noticed that my `allowNavigation` logic is no longer working.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS and Android

### Current Behavior

External URLs on the `allowNavigation` list are still being opened in the external browser.

### Expected Behavior

External URLs on the `allowNavigation` list should be navigated to on the Web View.

### Code Reproduction

On the `capacitor.config.ts` file add `allowNavigation: ['https://www.google.com/']` to the `server` object. Navigate to the URL on the `allowNavigation` list like, for example:

Angular template: `<button (click)="navigateAway()">navigate away</button>`
Angular TS:
```
  navigateAway(): void {
    window.location.href = 'https://www.google.com/';
  }
```

### Other Technical Details

`npm --version` output: 6.14.13

`node --version` output: v14.17.0

`pod --version` output (iOS issues only): 1.10.1

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dustinc701x** [comment]
I have been running into this same issue and i created a very small project to demonstrate when trying to navigate in the webview it opens an external browser instead of navigating the webview.
code can be found at https://github.com/dustinc701x/capacitor-navigation-bug

**Comment by jcesarmobile** [comment]
I've tested the sample app with Capacitor iOS 3.0.0 and 2.4.7 and it also opens the site in the browser so it's not a new bug.

The app loads `https://google.com` but has `"allowNavigation": ["https://www.google.com/"]`, which doesn't match.
If you change the code to load `https://www.google.com` and use ` "allowNavigation": ["www.google.com"]` then it works.
If you don't add the www it fails because google redirects itself to the www page.

**Comment by nunoarruda** [comment]
@jcesarmobile Sorry if I initially pointed you in the wrong direction. After a deeper look at the problem on my end, it looks like this does not work `allowNavigation: ['*://*.google.com/*']` but this works `allowNavigation: ['*.google.com']`. I've created an isolated demo project to test that: https://github.com/nunoarruda/capacitor-allow-navigation

If this is intentional then feel free to close this issue but I would still suggest improving the documentation to let developers know what URL patterns and/or glob patterns are expected/allowed.

Thanks!

**Comment by dustinc701x** [comment]
sorry about that it seems i was confused about what to put in the allowNavigation, thank you for the response and everything seems to be working now.

**Comment by nunoarruda** [comment]
Tip: Use a glob tester tool to test your URLs and/or globs like, for example, https://www.digitalocean.com/community/tools/glob

**Comment by jcesarmobile** [comment]
I think it works as expected, but to be honest, it's a feature a user created and was not properly documented when introduced and we have had to patch it multiple times over time, so I might be wrong.
