### ISSUE TITLE
bug(Android 5 & 6): Capacitor injects not-well-transpiled native-bridge into index.html 

### ISSUE THREAD

**Issue by crixx** [ionic-team/capacitor#4786]
## Bug Report
Capacitor's nativeBridge JS (/android/capacitor/src/main/assets/native-bridge.js) is injected into the `<HEAD>` part of the loaded index.html file. On older Android versions, especially 5 and 6, where users disabled the auto-update mechanism or didn't use their devices for a looooong time (or devs using simulators without google services installed), this leads to a JS parsing error which terminates all JS execution.

The underlying problem is, that those users or the simulators are shipped with a System WebView, that doesn't support es2017 (as defined in capacitor/core/package.json build:nativebridge). Thus, the proposed fix is to transpile the native-bridge.js to a supported version (es5?).

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/ios: 3.0.0
```

### Platform(s)

- Android 5 and 6 **with non-updated System WebView** e.g. 39.0.0 on Android API Level 22.

### Current Behavior

 - src/main/assets/native-bridge.js is transpiled to es2016, which is not supported by old System WebViews

### Expected Behavior

- src/main/assets/native-bridge.js is transpiled to a language level, which is supported by old System WebViews

### Steps for Reproduction

- install a simulator with API Level 22
- run an App with Capacitor 3
- inspect the chrome-console of the connected simulator
- find `Uncaught SyntaxError: Unexpected strict mode reserved word`

**Comment by jcesarmobile** [comment]
Capacitor requires Chrome/Chromium/System WebView 60 or newer

**Comment by crixx** [comment]
@jcesarmobile if this is not supported, how can I determine that state and inform the user accordingly? What can I do for users with an unsupported WebView? Is there a way to prevent the webview from loading and configure another site to load or to start an other intent instead of the webview?

**Comment by jcesarmobile** [comment]
You can check the navigator.userAgent to check the Chrome/Chromium/System WebView version and show some error message or redirect to some internal page that don't use plugins or external site (you'll need to add the external site to allowNavigation array or it will fail to navigate). Other than that I have no other ideas.

In real world most people have them up to date, it's mostly a problem on the emulators as those old versions don't include google play, so you can't update them.

**Comment by crixx** [comment]
Regarding 
> You can check the navigator.userAgent to check the Chrome/Chromium/System WebView version and show some error  message or redirect to some internal page that don't use plugins or external site (you'll need to add the external site to allowNavigation array or it will fail to navigate). 

That was of course also my first thought, but as said, does the JS Parsing abort as soon as there is a parsing error. Thus, I've no chance to execute any JS. Am I missing something? @jcesarmobile how would you implement that in practice?

In my world I have bad reviews in the store because of this. So there may exist some world, where people have their devices up-to-date, but as it seems, not in mine...

**Comment by crixx** [comment]
@jcesarmobile any ideas? How would you detect this situation and act from native code to show a adequate information to the user?

**Comment by crixx** [comment]
yes, still interested in an any ideas... also from other people?
