### ISSUE TITLE
bug: main activity theme is wrongly set up and the background is the splash screen 

### ISSUE THREAD

**Issue by rpanadero** [ionic-team/capacitor#4787]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/ios: 3.0.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

- Android

### Current Behavior

The main activity theme of my application is not set properly on Capacitor 3 by BridgeActivity and the background of the main activity is the splash screen.

I found this issue after upgrading to Capacitor 3 and you can reproduce it by opening the application keyboard. While the keyboard is being opened, pay attention to the gap that appears between the keyboard and your application content during 1s approx. because if your splash screen is pink, this gap will look pink. On Capacitor 2 this gap was black and that is the expected behavior. Please, have a look at the video:

https://user-images.githubusercontent.com/6747277/124247199-ece89000-db21-11eb-890b-1de712b1934b.mov

After a deep investigation on the bridge activity tasks, I think that the activity theme is set up too late to '@style/AppTheme.NoActionBar', whose background is set up to black by default, what makes the activity still use the theme that says AndroidManifest which is '@style/AppTheme.NoActionBarLaunch', whose background is set up with the splash screen.

https://github.com/ionic-team/capacitor/blob/3.0.2/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java#L65

If you have a look at the implementation, you can realize that the theme is set up during the 'onStart' life cycle because it is there where the bridge and its plugins are initialized automatically.

https://github.com/ionic-team/capacitor/blob/3.0.2/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java#L111
https://github.com/ionic-team/capacitor/blob/3.0.2/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java#L65

Before Capacitor 3, this doesn't happen because it was necessary to invoke 'init' (BridgeActivity method) from 'onCreate' of the application main activity to initialize all Capacitor plugins. Apart from configuring the plugins, this 'init' method also sets up the activity theme, etc. And it seems correct the place and moment where/when the theme should be set up.

To sum up, the difference between Capacitor 2 and Capacitor 3 is that the Capacitor 2 sets up the theme during 'onCreate' method and Capacitor 3 during 'onStart'. In fact, if I force to set the activity theme into the 'onCreate' method of my main activity works:

```java

public class MainActivity extends BridgeActivity {
  
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setTheme(R.style.AppTheme_NoActionBar);
  }
  
}

```
And calling the 'init' method into the 'onCreate' of the main activity also works properly, although it is highly discouraged by Capacitor because the plugins are not registered automatically by doing this. (NOT TO DO THIS)
```java
public class MainActivity extends BridgeActivity {
  
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      add(SplashScreenPlugin.class);
    }});
  }
  
}
```

### Expected Behavior

From my point of view, Capacitor 2 behavior is right and the main activity background should be dark or the value configured in the '@style/AppTheme.NoActionBar' theme.

### Code Reproduction

Not provided.

### Other Technical Details

`npm --version` output:
6.14.8

`node --version` output:
v14.15.0

`pod --version` output (iOS issues only):
1.10.1

### Additional Context

While the issue is being investigated I suggest to set the activity theme into the 'onCreate' method of your main activity.

```java

public class MainActivity extends BridgeActivity {
  
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setTheme(R.style.AppTheme_NoActionBar);
  }
  
}

```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by rpanadero** [comment]
This is the Code Reproduction that demonstrates the issue described in my first comment.

Steps to reproduce the issue:
- Open the app
- Touch the input

Then, you will see the behavior/issue described while the keyboard is being opened.
