### ISSUE TITLE
bug: Unable to generate plugins for Capacitor 2

### ISSUE THREAD

**Issue by scottwilson312** [ionic-team/capacitor#4794]
## Bug Report

According to the documentation for Capacitor 2 , you use `npx @capacitor/cli plugin:generate` to generate a plugin. If you try this command, npx tells you ```[error] The plugin:generate command has been removed.
        Use npm init @capacitor/plugin```

However if you look up that command, it is only supposed to be used for Capacitor 3. So either plugins are broken for Cap 2 or the documentation is wrong.

Cap 2 documentation on plugins: https://capacitorjs.com/docs/v2/plugins/creating-plugins

NPM package saying npm init @capacitor/plugin is only for Cap 3: https://www.npmjs.com/package/@capacitor/create-plugin

### Capacitor Version 2.4.7

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/electron: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:```

### Platform(s)
iOS


### Current Behavior
```
[error] The plugin:generate command has been removed.
        Use npm init @capacitor/plugin
``

### Expected Behavior
I expect the command to run

**Comment by jcesarmobile** [comment]
You can probably specify the CLI version when using the command like this: `npx @capacitor/cli@2.4.7 plugin:generate`.

But we are in Capacitor 3 now, we don't expect people to create capacitor 2 plugins at this point.

**Comment by scottwilson312** [comment]
So capacitor 2 is not supported anymore? I would suggest noting that in the docs - perhaps I should create a separate issue? AFAIK Cap 3 was only officially released less than two months ago. That's a very short amount of time to go from stable release ---> unsupported and deprecated !!
