### ISSUE TITLE
bug: Request to Graphql API but show response with capacitor code

### ISSUE THREAD

**Issue by josprimasihombing** [ionic-team/capacitor#4796]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/cli: 3.0.2
```

### Platform(s)

Android

### Current Behavior

I have an graphql api, with cors rule applied that only allow request from spesific origin.
let say as example, my graphql api is `https://mydomain.com/api/graphql`
and allow request from origin `https://client.mydomain.com`

so to able to make request, i change my capacitor.config.json like this:
```
...
server: {
    hostname: 'client.mydomain.com,
    androidScheme: 'https',
}
...
```
And this is success to change origin request. But the request is not success and show response like this :
<img width="965" alt="Screen Shot 2021-07-07 at 15 55 19" src="https://user-images.githubusercontent.com/57883217/124731339-57436b00-df3c-11eb-86a8-0ad5a9aefd72.png">

### Expected Behavior

The request is success and not show response capacitor code.

**Comment by jcesarmobile** [comment]
capacitor injects the javascript it needs to work on every html request, does graphql returns html?

**Comment by josprimasihombing** [comment]
@jcesarmobile The expected return is json, but in my case the response is capacitor js code like the screenshot that i provide above.

**Comment by josprimasihombing** [comment]
I try to fetch another public graphql and the request is success.

<img width="735" alt="Screen Shot 2021-07-07 at 16 59 53" src="https://user-images.githubusercontent.com/57883217/124740270-d472de00-df44-11eb-9a99-6ff5766d8f4b.png">

Is this because my origin is same with api url that cause request failed and show response capacitor js code ?

**Comment by jcesarmobile** [comment]
yeah, they can't be the same, in your example they were different

**Comment by josprimasihombing** [comment]
Thanks @jcesarmobile 
You are right, the origin and api url can't same.
After make the origin different from api url, the request is success.
