### ISSUE TITLE
bug: Capacitor androidBridge.postMessage converting `null` to `"..."`

### ISSUE THREAD

**Issue by chriswep** [ionic-team/capacitor#4798]
originally posted here but closed due to inactivity: https://github.com/ionic-team/capacitor/issues/4746

the method `safeStringify` in https://github.com/ionic-team/capacitor/blob/0429905efcf69097e7759b8d21d74459b8dd42c5/android/capacitor/src/main/assets/native-bridge.js#L175 does not account for `null` values when checking for circular references (`null` has the type `object` as well). therefore `[10,null,null,null]` is converted to `[10,null,'...','...']` (as posted in the original issue).

bug was introduced here: https://github.com/ionic-team/capacitor/commit/0429905efcf69097e7759b8d21d74459b8dd42c5#diff-8afda3e2bce7fb91a14a66d96d63a89f112b852cf39223e6f820a1575cbdafebR175

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by chriswep** [comment]
@jcesarmobile paste this into console (this is the method used to post data to native android):

```
        const safeStringify = (value) => {
            const seen = new Set();
            return JSON.stringify(value, (_k, v) => {
                if (seen.has(v)) {
                    return '...';
                }
                if (typeof v === 'object') {
                    seen.add(v);
                }
                return v;
            });
        };
        
        safeStringify([null,null]);
        
        // output: "[null,\"...\"]"
 ```

**Comment by jcesarmobile** [comment]
Sorry, I still need an app where it can be reproduced

**Comment by chriswep** [comment]
ok, someone posted one in the original issue: https://github.com/gabrielcursino/capacitor-sqlite-test

however i think you might save some time by just running the method directly, since it is obviously treating `null` values as circular object references. this is an issue wherever this method is used.

**Comment by jepiqueau** [comment]
@jcesarmobile @chriswep you can find the app in `https://github.com/jepiqueau/angular-sqlite-141.git` Go to the README.md to find the explanation on how to reproduce. The application works with the workaround of @capacitor-community/sqlite you have to remove the workaround to reproduce the problem

**Comment by jepiqueau** [comment]
@jcesarmobile @chriswep  Sorry i provided the wrong app i am busy on different bugs so i will come back with the right one

**Comment by jepiqueau** [comment]
@jcesarmobile @chriswep you can find the app to reproduce the issue `https://github.com/jepiqueau/capacitor-sqlite-test.git`

**Comment by jepiqueau** [comment]
@jcesarmobile @chriswep seems that if you modify in assets/native-bridge.js the constant `safeStringify` by
```js
const safeStringify = (value) => {
    const seen = new Set();
    return JSON.stringify(value, (_k, v) => {
        if (typeof v === 'object') {
            seen.add(v);
        }
        return v;
    });
};
``` 
it works , but i do not know what is the impact of doing that on the rest of the code and what the reason to have these lines
```js
                if (seen.has(v)) {
                    return '...';
                }
``` 
Hope this will help

**Comment by chriswep** [comment]
@jepiqueau the purpose of the method is to remove circular references in an object since `JSON.stringify` would throw an error otherwise. with your change of `safeStringify`, circular refs stay in the object, making the method basically the same as `JSON.stringify`. The correct fix of the method is to replace `if (typeof v === 'object')` with `if (typeof v === 'object' && v !== null)`.

**Comment by jepiqueau** [comment]
@chriswep your proposed fix is working Any progress status from @jcesaremobile

**Comment by emirtb** [comment]
same problem, two days lost ... and there is no way to solve it because it is the base framework

**Comment by jepiqueau** [comment]
@emirtb I am sorry for this time lost but there is nothing I can do it is in the hands of the Ionic Capacitor team

**Comment by emirtb** [comment]
> @jcesarmobile @chriswep seems that if you modify in assets/native-bridge.js the constant `safeStringify` by
> 
> ```js
> const safeStringify = (value) => {
>     const seen = new Set();
>     return JSON.stringify(value, (_k, v) => {
>         if (typeof v === 'object') {
>             seen.add(v);
>         }
>         return v;
>     });
> };
> ```
> 
> it works , but i do not know what is the impact of doing that on the rest of the code and what the reason to have these lines
> 
> ```js
>                 if (seen.has(v)) {
>                     return '...';
>                 }
> ```
> 
> Hope this will help



> @jcesarmobile @chriswep seems that if you modify in assets/native-bridge.js the constant `safeStringify` by
> 
> ```js
> const safeStringify = (value) => {
>     const seen = new Set();
>     return JSON.stringify(value, (_k, v) => {
>         if (typeof v === 'object') {
>             seen.add(v);
>         }
>         return v;
>     });
> };
> ```
> 
> it works , but i do not know what is the impact of doing that on the rest of the code and what the reason to have these lines
> 
> ```js
>                 if (seen.has(v)) {
>                     return '...';
>                 }
> ```
> 
> Hope this will help

To modify this file as a workaround, where is it located? in the node_modules?

Thanks

**Comment by jepiqueau** [comment]
@elylucas @thomasvidas @chriswep Seems it is always there in 3.1.2 despite the Changelog.md core: Modify safeStringify to allow multiple null values (#4853) (854539b). If i look in https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/assets/native-bridge.js it is still
```js
        const safeStringify = (value) => {
            const seen = new Set();
            return JSON.stringify(value, (_k, v) => {
                if (seen.has(v)) {
                    return '...';
                }
                if (typeof v === 'object') {
                    seen.add(v);
                }
                return v;
            });
        };

```
and not the proposed solution by @thomasvidas
