### ISSUE TITLE
bug: Local Notification Popup not working in Capacitor v3

### ISSUE THREAD

**Issue by suda-amir** [ionic-team/capacitor#4801]
### Capacitor Version
Latest Dependencies:
```
  @capacitor/cli: 3.1.0
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.1.0

Installed Dependencies:

  @capacitor/core: 3.0.2
  @capacitor/cli: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2
```
### Platform(s)

- Android

### Current Behavior
On using the Local Notifications plugin, the scheduled notification gets called but the popup doesn't seem to work

### Expected Behavior
Scheduled notification gets called along with the popup

### Code Reproduction
```
LocalNotifications.schedule({
	notifications: [
		{
			title: "Title",
			body: "Body",
			id: 1,
			schedule: { at: new Date(Date.now() + 1000) },
		}
	]
})
```

### Issue
I am getting the notification in the notification tray when the app is in foreground, but not getting it as a popup notification

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by suda-amir** [comment]
I was able to resolve the issue by creating a channel and giving Importance of 5 for Popups in Android.
