### ISSUE TITLE
How to use CapacitorBridge Class

### ISSUE THREAD

**Issue by skqew** [ionic-team/capacitor#4804]
### Capacitor Version

```
@capacitor/cli: 3.0.2
@capacitor/core: 3.0.2
@capacitor/ios: 3.0.2
```

### Platform(s)

iOS

### Current Behavior

I want to call CapacitorBridge
But CapacitorBridge  is internal class
How do I call the CapacitorBridge class and use getCommandInstance() ?

### Code Reproduction

    func getCommandInstance(pluginName: String) -> CDVPlugin? {

        if let viewController = UIApplication.shared.keyWindow?.rootViewController as? CAPBridgeViewController {
            
            return (viewController.bridge?.cordovaPluginManager?.getCommandInstance(pluginName))!
            -> error : Value of type 'CAPBridgeProtocol' has no member 'cordovaPluginManager'
        }

        return nil
    }

### Other Technical Details

`npm --version` output: 7.19.1

`node --version` output:16.4.1

`pod --version` output (iOS issues only):1.10.1

**Comment by jcesarmobile** [comment]
This belongs to discussions, you already created it, so going to close the issue
https://github.com/ionic-team/capacitor/discussions/4806
