### ISSUE TITLE
mac M1 capacitor run android fails

### ISSUE THREAD

**Issue by eliassparagis** [ionic-team/capacitor#4807]
**Description:**

In my M1 Mac with Big Sur 11.4 when I run `ionic cap run android` build fails

**Output:**
`[fatal] TypeError: Cannot read property 'stack' of undefined
[capacitor]     at runCommand (/Users/ilias/source/repos/njection-app/node_modules/@capacitor/cli/dist/tasks/run.js:65:40)
[capacitor]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[capacitor]     at async /Users/ilias/source/repos/njection-app/node_modules/@capacitor/cli/dist/index.js:94:9
[capacitor]     at async /Users/ilias/source/repos/njection-app/node_modules/@capacitor/cli/dist/telemetry.js:26:13
[capacitor]     at async Command.<anonymous> (/Users/ilias/source/repos/njection-app/node_modules/@capacitor/cli/dist/util/cli.js:12:13)`

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.9
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.0.4
   @angular/cli                  : 12.0.4
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI      : 3.0.1
   @capacitor/android : 3.0.1
   @capacitor/core    : 3.0.1
   @capacitor/ios     : 3.0.2

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.1 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur

```

**Other Information:**

Also when I run the app from Android Studio it works fine.

I use a Galaxy S9+ with Android 10.0 as a device.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by eliassparagis** [comment]
Sry for my late feedback.


> can you update @capacitor/cli to 3.1.1? It should provide better error messages now.
> 
> Did you add android platform in windows by any chance? that will produce permission errors on other OSs.

Sorry for my late feedback.
Actually yes I added the android platform in win machine and I continue working in my mac. What should I check?

**Comment by eliassparagis** [comment]
I run `chmod 755 android/gradlew` and problem solved.
Thank you
