### ISSUE TITLE
bug: Input tags with type date or month or select tags have dark backgrounds instead of white

### ISSUE THREAD

**Issue by mishrasatyam** [ionic-team/capacitor#4808]
### Capacitor Version

```
  Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Why does input type="date" or input type="month" or select tag has dark background? It should be white by default.

### Expected Behavior

input type="date" or input type="month" or select tag should have white background

### Other Technical Details

`npm --version` output: 7.18.1

`node --version` output: v16.4.0

Why this:
![WhatsApp Image 2021-07-08 at 16 58 58 (1)](https://user-images.githubusercontent.com/31180325/124914403-ec626480-e00d-11eb-8344-2ae0dc2475f9.jpeg)
instead of this:
![WhatsApp Image 2021-07-08 at 16 58 58](https://user-images.githubusercontent.com/31180325/124914414-ee2c2800-e00d-11eb-83b0-bbf75008c1df.jpeg)

**Comment by jcesarmobile** [comment]
Default Capacitor theme is `Theme.AppCompat.NoActionBar`. If you want light native views (date/time selectors, alerst, etc), switch to `Theme.AppCompat.Light.NoActionBar` in `res/values/styles.xml`, the style with name `AppTheme.NoActionBar`
