### ISSUE TITLE
Unable to update to 

### ISSUE THREAD

**Issue by t4tapas** [ionic-team/capacitor#4809]
I am trying to update the Capacitor version from 3.0.2 to 3.1.1
`Capacitor/cli` updated successfully to 3.1.1
When trying to update Capacitor core with `npm install @capacitor/core`, it's not updating.
When trying to force update with `npm install @capacitor/core@latest`, it's throwing the following error.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @capacitor/core@3.1.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"3.1.1" from the root project
npm ERR!   peer @capacitor/core@"^3.0.0-rc.0" from @capacitor-community/firebase-crashlytics@1.0.0
npm ERR!   node_modules/@capacitor-community/firebase-crashlytics
npm ERR!     @capacitor-community/firebase-crashlytics@"^1.0.0" from the root project
npm ERR!   16 more (@capacitor-community/sqlite, @capacitor/app, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"~3.0.0" from @capacitor/android@3.0.2
npm ERR! node_modules/@capacitor/android
npm ERR!   @capacitor/android@"^3.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

All 16 plugins are facing dependency issues. 
Please help fixing this.

**Comment by jcesarmobile** [comment]
npm 7 is a pain, since @capacitor/ios and @capacitor/android 3.0.x require @capacitor/core 3.0.x it won't let you update @capacitor//core. Even if you try to install the three packages on the same command it will complain. You'll have to use the `--force` option as the error message is telling you to do.

**Comment by t4tapas** [comment]
@jcesarmobile - It worked with --force and so far didn't break anything. Thanks!!! for the quick response.
Please close this.
