### ISSUE TITLE
CapacitoeException on iOS device

### ISSUE THREAD

**Issue by seweryn-vibbe** [ionic-team/capacitor#4814]
Hi,

I have problem with error logs from capacitor. I don't know where it come from. 

```
Ionic:

   Ionic CLI                     : 6.15.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.9
   @angular-devkit/build-angular : 0.1102.14
   @angular-devkit/schematics    : 11.2.8
   @angular/cli                  : 11.2.14
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 3.1.1
   @capacitor/core : 3.1.1
```

<img width="1515" alt="Zrzut ekranu 2021-07-9 o 16 00 48" src="https://user-images.githubusercontent.com/77148649/125089934-1760bd00-e0cf-11eb-8e29-907fb74d5268.png">

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
