### ISSUE TITLE
bug: iOS with Nuxt JS no build command in Capacitor JS docs?

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor#4822]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.1.1
  @capacitor/ios: 3.1.1
  @capacitor/core: 3.1.1

[success] iOS looking great! 👌
```

### Platform(s)

- iOS

### Current Behavior

When running `npm run generate` and then `npx cap open ios` in my Nuxt JS project, I don't see any new changes coming through onto my connected iOS device when running the app via Xcode on my phone.

### Expected Behavior

- It appears that there's potentially some kind of `build` command missing from the [documentation](https://capacitorjs.com/docs/ios#ios-support) as when I make my changes and run the app on my phone I don't see any new changes other than the changes I made when I compiled the project initially when adding the iOS platform.

### Other Technical Details

`npm --version` output: 6.14.12

`node --version` output: v12.22.1

`pod --version` output (iOS issues only): 1.10.1

### Additional Context

I'm using Nuxt JS for my project which outputs to a `dist` directory containing my project, but it seems the `open` command for iOS only ever seems to do just that, where's the build command?

**Comment by jcesarmobile** [comment]
check the workflow docs https://capacitorjs.com/docs/basics/workflow

When you build your assets you need to copy them to the native project with `npx cap copy` or `npx cap sync`
