### ISSUE TITLE
feat: disable native-bridge injection on android webviews < 60 to prevent JS parsing errors and application crash

### ISSUE THREAD

**Issue by crixx** [ionic-team/capacitor#4831]
### Description

Android webview < 60 is currently not supported. Although Capacitor Team says this does not happen in the real world, I have bad reviews in the store just because of this. (people cannot start the app and only see a white screen after the loading screen is hidden by the default time - not the app)

### Platform(s)

- Android 5 and 6 with webview < 60

### Preferred Solution

- Transpile native-Bridge.js to supported JS level --> this (#4786) was closed without alternative
- Disable injection of native bridge
- At least allow framework-users to detect such states e.g. #4530

**Comment by thomasvidas** [comment]
We don't have any plans to support Android WebView/Chrome < 60 at the moment. Its [referenced in our docs](https://capacitorjs.com/docs/android#android-support) that WebView/Chrome 60+ is our minimum version we support:.

#4530 has been merged in so you can detect when there has been an error on the webview. This will be released in 3.1.2.
