### ISSUE TITLE
bug: Logs are no longer visible

### ISSUE THREAD

**Issue by MSchutt** [ionic-team/capacitor#4835]
### Capacitor Version
```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

Installed Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

[success] Android looking great! �
```

### Platform(s)
Android

### Current Behavior
I just updated my App from Version 2 to Version 3 - when running the command: `ionic capacitor run android --livereload --consolelogs --serverlogs --host <IP>` in the previous version (2+) Android Studio opened automatically and logs were visible via logcat. 
Since in Version 3 only the emulator starts (which itself is really awesome) I am unable to see the logs / open logcat which makes it impossible for me to debug my App. 
How can I inspect the logs with the run command?

### Expected Behavior
Logs are visible in the command

### Code Reproduction
`console.log("Hello")`

### Other Technical Details

`npm --version` output: `6.14.13`

`node --version` output: `v14.17.3`

### Additional Context
A question on stackoverflow has been raised already about this issue: [Stackoverflow](https://stackoverflow.com/questions/68262475/ionic-capacitor-android-emulator-make-console-log-visible-in-terminal)

**Comment by jcesarmobile** [comment]
You can use --open param to get the old behavior where android studio is opened and you run from there

You can also see the logs in chrome
https://stackoverflow.com/a/68349257/1351469
