### ISSUE TITLE
bug: Unable to compile with version 3.0.0-rc.0

### ISSUE THREAD

**Issue by prosperva** [ionic-team/capacitor#4836]
I have been trying to compile an Android app for two days now when I was to do so a few days ago. Below are the components I have installed:

@capacitor/core": "^3.0.0-rc.0" 
@capacitor/cli": "^3.0.0-rc.0."
@capacitor/android@3.0.0-rc.0.

I keep getting this error 

**AndroidManifest.xml app/build/intermediates/packaged_manifests/debug/debug 1 error
Android resource linking failed :71**

See attached image below
<img width="624" alt="Screen Shot 2021-07-14 at 9 58 57 PM" src="https://user-images.githubusercontent.com/1531271/125727447-69ad78bc-091e-491c-aa2f-d8b4e4a93944.png">

Can someone guide me on how to fix this. I have tried deleting the manifest file but to no avail.

Much appreciated.

**Comment by jcesarmobile** [comment]
Latest version is 3.1.1, don’t use rc versions at this point
