### ISSUE TITLE
Admob pro plugin issues

### ISSUE THREAD

**Issue by monusingheipl** [ionic-team/capacitor#4842]
Admob pro plugin is supported in capacitor v3 or not?

**Comment by jcesarmobile** [comment]
I don't know, you should ask on the plugin repository.

**Comment by monusingheipl** [comment]
https://capacitorjs.com/docs/v2/cordova/known-incompatible-plugins

**Comment by monusingheipl** [comment]
cordova-plugin-admobpro  is present in the list, it means its incompatible.

**Comment by jcesarmobile** [comment]
ah, yeah, if you meant the cordova plugin and it's in the list, then it's not compatible, I thought you meant a Capacitor Admob plugin, such as https://github.com/capacitor-community/admob, which seems to be compatible with Capacitor 3.

**Comment by monusingheipl** [comment]
thanks
