### ISSUE TITLE
feat: Add support for emulators outside of .android folder

### ISSUE THREAD

**Issue by nvispute** [ionic-team/capacitor#4846]
## Bug Report
When I run ```ionic capacitor run --livereload --external``` by default it lists and uses the emulator from ```%USERPROFILE%/.andriod```

### Capacitor Version
version:3.0

### Platform(s)
Windows 

### Current Behavior
It opens an emulator which Is not connected to android studio and also not listed in the AVD Manager

### Expected Behavior
IT should list the emulators created using AVD manager and use one of the selected emulators to output the app.

### Code Reproduction
STEP1: move your .android folder to any custom location including that hosts the avd folder for all your emulators
use ```ionic capacitor run --livereload --external ```  then use android as a platform. Then the console prompts you to select an emulator with a blank list as it is unable to locate the custom location.

STEP2: If you put a copy of .andriod folder back to its original location with different emulators inside of the avd folder then those emulators will be available when you re-try the above steps. However, this emulator that you added in step 2 will not be listed in the avd manager as your SDK home is a custom location.

**Comment by nvispute** [comment]
Here is what i found, over last few days while troubleshooting..
<ol>
I create a fresh blank template vue project

**Comment by jcesarmobile** [comment]
You should be able to configure `$ANDROID_EMULATOR_HOME`, that allows to configure where native-run searches for the AVD images

If that still doesn't solve your issue or you find new issues when running, please, report on 
https://github.com/ionic-team/native-run
