### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by CarlosNano** [ionic-team/capacitor#4852]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

Installed Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/ios: 3.1.1
```

### Platform(s)
Android

### Current Behavior

I have a plugin made in Kotlin and working with capacitor 2.3.0 but when I've update it to capacitor 3.1.1 and use `CapacitorPlugin` instead of the deprecated `NativePlugin` .

When I build the Android studio project, I get:
```
Unresolved reference: CapacitorPlugin
```

![image](https://user-images.githubusercontent.com/72921935/126314762-52eb583b-06ac-4417-b058-b031f1db7f9c.png)

I tried invalidating cache and restart in Android studio but it didn't work.

### Expected Behavior

Android code will compile

### Other Technical Details

`npm --version` output: 7.8.0

`node --version` output: v14.11.0

**Comment by thomasvidas** [comment]
Re-running a gradle sync (elephant button in the top left of Android Studio) will cause this error to go away
