### ISSUE TITLE
feat: Don't sync IOS dependencies if on windows.

### ISSUE THREAD

**Issue by Lizard-King101** [ionic-team/capacitor#4860]
### Description
Don't sync IOS dependencies if on windows.

### Platform(s)
Windows

### Preferred Solution
Ignore IOS platform.

### Alternatives
allow removing platforms

### Additional Context
none needed.

**Comment by jcesarmobile** [comment]
The update command (the one that updates the dependencies) is skipped on windows already, make sure you are using latest Capacitor version
