### ISSUE TITLE
BridgeWebChromeClient.java - Error: Unnecessary line

### ISSUE THREAD

**Issue by hecko** [ionic-team/capacitor#4865]
## Bug Report

```
  Errors found:
  
  /home/runner/work/xxx/xxx-uploader-capacitor/Client/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java:102: Error: Unnecessary; SDK_INT is always >= 29 [ObsoleteSdkInt]
          boolean isRequestPermissionRequired = android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M;
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/runner/work/xxx/xxx-uploader-capacitor/Client/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java:340: Error: Unnecessary; SDK_INT is always >= 29 [ObsoleteSdkInt]
          boolean isVideoCaptureSupported = android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N;
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  



marcel@mikrotik android % cat variables.gradle| grep Ver
    minSdkVersion = 29
    compileSdkVersion = 29
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.3.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.3'
    androidxEspressoCoreVersion = '3.4.0'
    cordovaAndroidVersion = '7.0.0'
```

### Capacitor Version

```
marcel@mikrotik Client % cat package.json| grep capac
    "@capacitor/android": "^3.0.2",
    "@capacitor/cli": "^3.1.1",
    "@capacitor/core": "^3.0.2",
    "@capacitor/ios": "^3.0.2",
    "capacitor": "^0.5.5",
```

### Platform(s)

GitHub Actions /  runs-on: ubuntu-latest (Mon Jul 26 12:44:59 CEST 2021)

### Current Behavior

build does not finish when warnings are treated as errors (default in GitHub Actions)

### Expected Behavior

remove the warning

### Code Reproduction

I assume setting the android toolchain versions:

```
    minSdkVersion = 29
    compileSdkVersion = 29
    targetSdkVersion = 30
```

**Comment by thomasvidas** [comment]
Capacitor, by default, supports down to a `minSdkVersion` of `android.os.Build.VERSION_CODES.LOLLIPOP` (API level 21) so this is still required for most apps.

**Comment by hecko** [comment]
I understand but this fails the builds when warnings are treated as errors, which is on by defaul on github actions.

**Comment by jcesarmobile** [comment]
It happens because you have set `minSdkVersion = 29`, then the code becomes unnecessary, but Capacitor supports 21+, so we can't remove that code. Any reason for only target Android 29+ in your app? that's a really low percentage of devices.

**Comment by Samsonroyal** [comment]
I received a similar error in the BridgeWebChromeClient.java file although this time it's on line 288;
## A screenshot of the error message
![error](https://user-images.githubusercontent.com/26835888/185112177-b11470cb-9397-48c1-9e10-b007c575cc15.png)
The error looks like this `Cannot resolve symbol 'S':288`

I visited StackOverflow and all they display are answers about importing flutter apps and not ionic/capacitor apps. I also tried installing the android support plugin in vain

Kindly help me solve this.
