### ISSUE TITLE
bug: Error running subprocess capacitor right after starting project

### ISSUE THREAD

**Issue by Evand3r** [ionic-team/capacitor#4870]
There is an error showing up right after starting a new ionic app with capacitor integration just by following commands in the [tutorial](https://ionicframework.com/docs/angular/your-first-app).

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/ios: not installed
  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2

### Platform(s)

OpenSuse Leap 15.2

### Current Behavior

Get this error when creating a new app:
`
error: unknown option '--npm-client'
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor init myApp io.ionic.starter --web-dir www --npm-client npm exited with exit code 1.
`

### Expected Behavior

The app should be created without any issues if I have @ionic/cli and @capacitor/cli on their latests versions.

### Code Reproduction

Either
`
$ ionic start myApp sidemenu --type=angular --capacitor
or
$ ionic start myApp sidemenu
`
will produce the same output.

### Other Technical Details

`npm --version` output: v6.14.13

`node --version` output: v14.17.3

`pod --version` output (iOS issues only):

### Additional Context

![bug capacitor](https://user-images.githubusercontent.com/14034664/127343684-b379619c-16df-4e6f-bbf4-6bbbf9beb85c.png)

**Comment by thomasvidas** [comment]
`--npm-client` is not an option in the Capacitor 3 CLI so does removing it fix this issue? I can take a look at the docs and update them accordingly

**Comment by Evand3r** [comment]
> `--npm-client` is not an option in the Capacitor 3 CLI so does removing it fix this issue? I can take a look at the docs and update them accordingly

Yes, running it witout `--npm-client` fixes the issue. Thanks, appreciate it.
