### ISSUE TITLE
bug: CSS gap/row-gap/column-gap does not work

### ISSUE THREAD

**Issue by hinryd** [ionic-team/capacitor#4875]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/cli: 3.1.2

[success] Android looking great! 👌
```

### Platform(s)

I've only tested on Android emulator (sdk_gphone_arm64)

### Current Behavior

I ran the app using `npx cap run android`.
All flexbox and grid layout in the app are ignoring CSS properties `gap`, `row-gap`, `column-gap`.

### Expected Behavior

Should be visible gap in between the children elements

### Code Reproduction

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Testing</title>
    </head>
    <body>
        <div style="display: flex; flex-direction: column; gap: 100px">
            <div style="background-color: aqua">Testing</div>
            <div style="background-color: aqua">Testing</div>
            <div style="background-color: aqua">Testing</div>
            <div style="background-color: aqua">Testing</div>
            <div style="background-color: aqua">Testing</div>
        </div>
    </body>
</html>
```

### Other Technical Details

`npm --version` output: 7.18.1

`node --version` output: v16.4.0

`pod --version` output (iOS issues only):

### Additional Context

None

**Comment by thomasvidas** [comment]
What version of the System webview are you using? The `gap` properties were not added until Chrome 84 for flexbox and Chrome 66 for grid. The minimum Chrome version that Capacitor supports for Android is Android System Webview 60 so you may be on a version that does not support the gap property

**Comment by hinryd** [comment]
> What version of the System webview are you using? The `gap` properties were not added until Chrome 84 for flexbox and Chrome 66 for grid. The minimum Chrome version that Capacitor supports for Android is Android System Webview 60 so you may be on a version that does not support the gap property

My version of the webview on 83, I will close the issue now.

However, if Capacitor is relying on system's webview, how does it ensure cross-platform compatibility and reliability?

**Comment by alexandermorgan** [comment]
I'm hitting the same problem. @hinryd how do you update (or even check) the system webview for the capacitor build?
