### ISSUE TITLE
Feedback on the Upgrade Guide for Capacitor 3

### ISSUE THREAD

**Issue by namrata-Zimbaroos** [ionic-team/capacitor#4882]
I had upgraded my app to capacitor 3 and Now I am trying to use "ionic cap run android --l --external" And It is showing below error.
[ERROR] An error occurred while running subprocess capacitor.
Please help me to solve this. How can I use livereload?
livereload Error

![livereload Error](https://user-images.githubusercontent.com/77039798/127963955-b3c6334c-1023-4fd1-8d92-6d7bfaab1772.JPG)

**Comment by jcesarmobile** [comment]
I answered you on the thread
