### ISSUE TITLE
feat: Minimum WebView version on Android

### ISSUE THREAD

**Issue by grigorig** [ionic-team/capacitor#4884]
### Description
It would be useful to be able to require a specific minimum WebView version on Android to avoid the "white screen of death" if the application won't work due to lack of newer JS feature support.

### Platform(s)
Android

### Preferred Solution
If the WebView is too old, Capacitor could, for example, display a (localized) error dialog, advise the user to update WebView and abort.

**Comment by grigorig** [comment]
By the way, I noticed that Capacitor just crashes silently on startup if no WebView is available, e.g. if the user disabled/removed both Chrome and the System WebView. Maybe both availability and version should be checked at the same time.

**Comment by nathantaal** [comment]
In my opinion this are two seperate issues. I agree that it would be nice that capacitor checks for the minimum required webview, but if you decide to use 2022 javascript only supported by an bleeding edge version of Chrome, it's up to you to poly fill this JS. Having said that, what JS are you using, what problem do you have, and have you tried poly filling?

**Comment by grigorig** [comment]
I'm not really using "bleeding edge" JavaScript. Just es6 basically. However, on old Android smartphones you may easily find WebViews that are older than four years if user don't update (e.g. Play Store updates disabled)! Those have issues with current Angular and Ionic, not sure if there is any way to workaround that.

I agree that these are two issues - version check and availability are different problems.

**Comment by grigorig** [comment]
Documentation on https://capacitorjs.com/docs/android actually states that version 60+ of a Chrome-based WebView is a hard requirement, so maybe there are more basic WebView API requirements that possibly cause failures on startup. If that is true, it's even more strange that Capacitor doesn't actually check for a supported WebView version!

**Comment by contact-literalword** [comment]
I'm also running into the white screen on older Androids (API 23). It would be nice if Capacitor natively detected this situation and displayed an error message describing the situation and workaround (to update System WebView).

**Comment by deniscesar** [comment]
In the v2 documentation

`Also, Capacitor requires an Android WebView with Chrome version 50 or later. On Android 5 and 6, the Capacitor uses the System WebView. On Android 7+, Google Chrome is used.`

https://capacitorjs.com/docs/v2/getting-started/dependencies#requirements

I have an android 7.1.1 with webview 52.

This would be necessary to work with v2

**Comment by buschtoens** [comment]
I agree, that it would be pretty neat for Capacitor to automatically detect an outdated / unsupported WebView and display instructions for how to update.

This raises some immediate questions for me:

- How could the error message / instructions be displayed and internationalized? We can't rely on the WebView to implement the logic for such things, as all other plugins do.
  - What instructions are displayed?
  - What if the device is using a custom ROM that doesn't have a Google Play Store?
- How is an outdated / unsupported WebView detected?
  - Plain version / user agent comparison? Catching fatal errors? ...?
  - What if some unexpected WebView gets incorrectly blocked, but would work just fine? Could the user by-pass the error?
- Should the dev be able to tweak / configure the requirements or should this be forbidden / discouraged?

**Comment by grigorig** [comment]
@RRGT19 This bug is closed. Capacitor 4.0.0 and newer now include an "error page", see #5723.
