### ISSUE TITLE
bug:  capacitor 3 - android studio errors

### ISSUE THREAD

**Issue by marshall86** [ionic-team/capacitor#4888]
### Capacitor Version
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/android: 3.1.2
  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/ios: 3.1.2

[success] Android looking great! 👌

### Platform(s)
Android

### Current Behavior
When a create the build in Android Studio I get the following errors:

> Task :capacitor-cordova-android-plugins:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.

> Task :capacitor-android:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: node_modules\@capacitor\android\capacitor\src\main\java\com\getcapacitor\BridgeWebChromeClient.java uses unchecked or unsafe operations.

> Task :capacitor-status-bar:compileDebugJavaWithJavac
Note: node_modules\@capacitor\status-bar\android\src\main\java\com\capacitorjs\plugins\statusbar\StatusBar.java uses or overrides a deprecated API.

> Task :capacitor-splash-screen:compileDebugJavaWithJavac
Note: node_modules\@capacitor\splash-screen\android\src\main\java\com\capacitorjs\plugins\splashscreen\SplashScreen.java uses or overrides a deprecated API.

> Task :capacitor-keyboard:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.

> Task :capacitor-app:compileDebugJavaWithJavac
Note: node_modules\@capacitor\app\android\src\main\java\com\capacitorjs\plugins\app\AppPlugin.java uses or overrides a deprecated API.

> Task :capacitor-network:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.

### Other Technical Details
Gradle version 7.0.1
Android Gradle Version 7.0
`npm --version` output: 7.20.2
`node --version` output: v14.17.0

Can you tell me if those errors are something to worry about or not? is there a solution or maybe I have to wait a bit before upgrading to capacitor 3?

Thanks

**Comment by jcesarmobile** [comment]
those are warnings, not errors, and most of them come from plugins, not from Capacitor itself.

**Comment by marshall86** [comment]
Capacitor plugins though
