### ISSUE TITLE
bug: Plugins do not load. Error: "plugin is not implemented on android" MainActivity.java looks correct. Example repository given

### ISSUE THREAD

**Issue by stevebrowndotco** [ionic-team/capacitor#4891]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/ios: 3.1.2
```

### Platform(s)

Android ONLY (iOS is perfect)

### Current Behavior

Upon installing some plugins, capactitor ceases to recognise plugins and displays the following error in runtime: 
`Error: <PLUGIN> plugin is not implemented on android`

### Expected Behavior

The plugin should load!

### Code Reproduction

I have created a very base bones of both a WORKING example and a NON WORKING example, and I can't figure out why it breaks! MainActivity.java looks correct as per the ionic documentation.

You can view the WORKING example here (please follow the steps)

https://github.com/stevebrowndotco/broken-capacitor-plugins-demo 

You can view the NON working example here, as a pull request showing the changes

https://github.com/stevebrowndotco/broken-capacitor-plugins-demo/pull/1

### Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.16.1

### Additional Context

My example demonstrates that the plugin capacitor google maps does not work, but this can be reproduced for every plugin I have tried

**Comment by jcesarmobile** [comment]
I've commented on your pull request, you removed all `@capacitor/` plugins from package.json, can you provide a simpler PR that breaks the plugin but doesn't remove everything?

**Comment by stevebrowndotco** [comment]
Hi @jcesarmobile , thank you for taking a look!

Well... I have already done this separately, and it makes no difference

I don't need those capactior plugins apart from I assume @capactitor/app ?

**Comment by stevebrowndotco** [comment]
Also providing a simpler PR which breaks the plugin but doesn't remove everything is easier said than done :/ As I dont know exactly what is breaking the PR at the moment...

**Comment by jcesarmobile** [comment]
Ionic need those, but removing them won't cause any issue on Capacitor itself, just some Ionic things won't work properly.

Anyway, my point is, you are adding dozens of cordova plugins in the PR, not just adding the google maps plugin and removing the capacitor plugins, it's a massive change.
The problem might be some Cordova plugin not being compatible and breaking the injection.

**Comment by stevebrowndotco** [comment]
Thank you again. Yes I suspect the same thing, but I thought capacitor is supposed to have some way of disabling cordova plugins that are not compatible? Because the docs say that I can use both together

**Comment by jcesarmobile** [comment]
it skips the ones that are known to cause build failures, but there can be unknown plugins

**Comment by stevebrowndotco** [comment]
Ok - Is there a way of finding out what breaks the injection at the point where it happens?

**Comment by jcesarmobile** [comment]
the problem was on sentry plugin as it provides a map file and we were injecting it, but maps are not proper javascript, so that broke the injection, I've sent a PR that skips map files

**Comment by stevebrowndotco** [comment]
I can confirm that removing cordova-sentry fixes the project! For now I can deal with that, better to have it building, but I will add back when your PR appears in the next release. Thanks again!
