### ISSUE TITLE
bug: WebGL Errors When Wrapping Jeeliz AR Library Project with Capacitor

### ISSUE THREAD

**Issue by ccaleb** [ionic-team/capacitor#4892]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/electron: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/android 2.4.6
  @capacitor/core 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)

Android v7.0 and above

### Current Behavior

I have created a project that uses the [Jeeliz Face Filter AR library](https://github.com/jeeliz/jeelizFaceFilter). It works on both iOS and Android devices via their respective web browsers. I’ve successfully created an iOS app version using Capacitor and it works as expected on iOS14.5 devices and above. However, whenever I run the Android version, my Capacitor app fails to render any camera video to the screen and repeatedly reports the following series of WebGL errors on each frame update:

```
[ERROR:gles2_cmd_decoder.cc(18881)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[ERROR:gles2_cmd_decoder.cc(8621)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: Attachment textarget doesn't match texture target
[ERROR:gles2_cmd_decoder.cc(4993)] [.RendererMainThread-0x400b3e800]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
```

These errors appear in the Android Logcat window in Android Studio.

This issue happens with every Android device that I’ve tested with across various versions of Android. At the moment I’m testing with a Samsung Galaxy S6 running Android 7.0. I suspect there is an issue within Capacitor that is causing these WebGL errors.

Summary
* The exact same project runs within Chrome on my Samsung Galaxy S6
* The exact same project runs within Safari on all iOS devices that I’ve tested with (iPhone 7, iPhone 8, iPhone X, iPad)
* The exact same project also runs when running in a local web server on my development machine (Mac OSX)
* It’s only when being wrapped into a native app using Capacitor that it fails on Android
* Wrapping the same code into a native iOS app using Capacitor works
* I receive the above WebGL errors with all the Jeeliz demos that I’ve tested from the jeelizFaceFilter repo

### Expected Behavior

The app should show a live camera feed and also draw a yellow detection rectangle around your face.

#### How to Reproduce
I’ve created a sample Capacitor project that wraps a simple Jeeliz FaceFilter API demo into an app. The project can be found [here](https://github.com/ccaleb/jeeliz-capacitor).

##### Clone the source from the repo
Get the source from [here](https://github.com/ccaleb/jeeliz-capacitor)

##### Install packages
`> npm install`

##### Test the project works on your local development computer’s browser
`> npm start`

This will start a secure web server session.
Open your web browser and enter “localhost” into the address bar.

##### Also test the project by running it on your Android device’s web browser
Open Google Chrome on your Android device
Obtain the IP address from your development computer
Enter your IP address into the address bar of your device’s web browser

##### Wrapping into a Capacitor app
Follow these steps to wrap your project into a native app using Capacitor

##### Add the Android Platform
`> npx cap add android`

##### Open Android Studio
`> npx cap open Android`

##### Set Camera App Permissions
The following permissions need to be added to the app’s AndroidManifest.xml file.

Within Android Studio open the following file: app/manifests/AndroidManifest.xml

Add the following entries near the end of the file:

```
<uses-feature android:name="android.hardware.camera" android:required="false" />
<uses-feature android:name="android.hardware.camera.front" android:required="false" />
```

Save the file.

##### Build Project
Connect an Android device to your computer.
From Android Studio, select the Run > Run App drop-down menu.

After a short time the app will build and deploy to your device.

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v14.15.0

**Comment by jcesarmobile** [comment]
WebGL errors come from Android or the WebView, not from Capacitor, so try reporting it in Android bug tracker or chromium bug tracker.
It could be some incompatibility on how the jeeliz library works, so you can also try to report it to them.

Using the commented code for the video tag, the video works correctly, so Capacitor's code to make the camera work is correct.
