### ISSUE TITLE
bug: Share API does not share URL when sharing using iOS's copy

### ISSUE THREAD

**Issue by KirstenStake** [ionic-team/capacitor#4909]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2
```

### Platform(s)

- iOS

### Current Behavior

- When using the share functionality and choosing the option "copy" (where you then paste the copied info where desired), it does not include the url. Only the text gets copied across. This is only an issue in iOS, Android working correctly.
- Every other share option working correctly on iOS and copies both

### Expected Behavior

- "copy" option via share should be copying across all fields specified, not leaving out the url

### Code Reproduction

` await Share.share({
        text: 'Hello testing this copy issue',
        url: this.shareUrl
      });`

### Other Technical Details

`npm --version` output: 6.14.13

`node --version` output: v14.17.0

`pod --version` output (iOS issues only): 1.10.1

### Additional Context

There is a previously created issue report with the same issue which was closed. [#2129](https://github.com/ionic-team/capacitor/issues/2129)

**Comment by jcesarmobile** [comment]
The plugin works by adding different items to a native UIActivityViewController, but sadly we can’t control how the UIActivityViewController actions will handle those items, in the case of the copy action, it only copies the first item.
