### ISSUE TITLE
platform.is("capacitor") should return true while "cordova" should return false

### ISSUE THREAD

**Issue by cleversolutions** [ionic-team/capacitor#493]
this.platform._platforms contains "cordova" and not "capacitor", thus platform.is("cordova") returns true while platform.is("capacitor") returns false.  Since this isn't Cordova, should this get updated? Should platform.is respond true to something more generic like webview or native? I'm not even sure if that is part of capacitor or not, but since capacitor is a stakeholder in this decision, this seems the best place to kick this question off.

**Comment by janpio** [comment]
You are running an Ionic project with Capacitor?

**Comment by ghenry22** [comment]
As capacitor is compatible with cordova plugins it should return true for platform.is cordova as some plugins may check that cordova is available or refuse to run.  A platform.is capacitor would potentially be useful though to confirm that you are running on capacitor and not cordova under the hood and allow any platform specific logic vs PWAs etc.

**Comment by mlynch** [comment]
Are you referring to the Platform service in Ionic 3? If so let’s do this in #418

**Comment by ghenry22** [comment]
I would presume the Platform service in an Ionic app as that is where you would use the platform.is() method.
