### ISSUE TITLE
bug: appUrlOpen not fired in ios 13-14

### ISSUE THREAD

**Issue by TheNemus** [ionic-team/capacitor#4933]
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.2
  @capacitor/core: 3.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
ios 12.4 (real device) 13.3 (simulator) 14.5 (simulator)

### Current Behavior
Deep link correctly open the app instead of the webpage, but the **appUrlOpen** event is not fired

### Expected Behavior
appUrlOpen event should be fired

### Code Reproduction
```
App.addListener('appUrlOpen', (data: any) => {
      this.zone.run(() => {
        const slug = data.url.split("/app").pop();
        this.router.navigateByUrl(slug);
      });
    });
```

### Other Technical Details
In android 11 (simulator) works perfectly

`npm --version` output: 6.13.14

`node --version` output: 12.14.1

`pod --version` output (iOS issues only): 1.10.1

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
