### ISSUE TITLE
bug: ActionPerformed object miss the PushNotificationSchema object

### ISSUE THREAD

**Issue by TheNemus** [ionic-team/capacitor#4934]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.2
  @capacitor/core: 3.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
Android 8 (real device) Android 11 (simulator)

### Current Behavior
After receiving a push notification, event **pushNotificationReceived** gives a pushNotificationSchema object:
![image](https://user-images.githubusercontent.com/9430669/129713600-722bd087-a1fb-4e4f-be6a-5da798175402.png)
with 'title', 'body' and 'data' fields
When I tap the notification, **pushNotificationActionPerformed** gives an **ActionPerformed** object whose **notification** fields miss all these fields, giving the app no chance to know what to do:
![image](https://user-images.githubusercontent.com/9430669/129714102-aecdac94-a9ef-4d4b-a81e-c68547b96b8b.png)

### Expected Behavior
Having the notification object both from **pushNotificationReceived** event and **pushNotificationActionPerformed** event

### Code Reproduction
```
    // Show us the notification payload if the app is open on our device
    PushNotifications.addListener('pushNotificationReceived',
      (notification: PushNotificationSchema) => {
        console.log('new notif', notification);
      }
    );

    // Method called when tapping on a notification
    PushNotifications.addListener('pushNotificationActionPerformed',
      (action: ActionPerformed) => {
        console.log('new notif action', action);
      }
    );

```

### Other Technical Details
This code perfectly works on iOS 14.5 (simulator)

`npm --version` output: 6.13.4

`node --version` output: 12.14.1

**Comment by jcesarmobile** [comment]
When your app is backgrounded or closed the OS takes those fields to display the notification, but don't pass them to the app when the notification is tapped

**Comment by TheNemus** [comment]
@jcesarmobile this should be noted in plugin documentation
