### ISSUE TITLE
Cordova Plugin not working

### ISSUE THREAD

**Issue by kumarsunil0007** [ionic-team/capacitor#4946]
### cordova-plugin-openwith-ios
This plugin is not working with capacitor. If I use same with cordova app, it is working fine but with capacitor app, it is not registering the share extension and files are also not copied properly.

**Comment by jcesarmobile** [comment]
The plugin uses hooks to create the share extension, capacitor doesn’t run cordova hooks, you’ll need to create the share extension manually or write similar code of the hooks but adapted to capacitor project structure and run it.
