### ISSUE TITLE
bug: Help Needed!! SalesforceHybridSDK (Cordova plugin) crashes with any capacitor project.

### ISSUE THREAD

**Issue by sriramappnovation** [ionic-team/capacitor#4949]
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/ios: 3.2.0

[success] iOS looking great! 👌

### Platform(s)
ios, not yet tested on Android

### Current Behavior
iOS application Crashes with the following error

```
dyld: Symbol not found: _OBJC_CLASS_$_CDVPluginManager

  Referenced from: 
/Users/admin/Library/Developer/CoreSimulator/Devices/B09786F9-CAAE-4299-A293-98E1B4AC105C/data/Containers/Bundle/Application/B2E5CD5E-B58D-49B6-AC8F-42E60351B821/App.app/Frameworks/Capacitor.framework/Capacitor

  Expected in:
 /Users/admin/Library/Developer/CoreSimulator/Devices/B09786F9-CAAE-4299-A293-98E1B4AC105C/data/Containers/Bundle/Application/B2E5CD5E-B58D-49B6-AC8F-42E60351B821/App.app/Frameworks/Cordova.framework/Cordova

 in 
/Users/admin/Library/Developer/CoreSimulator/Devices/B09786F9-CAAE-4299-A293-98E1B4AC105C/data/Containers/Bundle/Application/B2E5CD5E-B58D-49B6-AC8F-42E60351B821/App.app/Frameworks/Capacitor.framework/Capacitor

dyld: launch, loading dependent libraries

DYLD_SHARED_CACHE_DIR=/Users/admin/Library/Developer/CoreSimulator/Caches/dyld/19H1217/com.apple.CoreSimulator.SimRuntime.iOS-14-4.18D46

DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot

DYLD_LIBRARY_PATH=/Users/admin/Library/Developer/Xcode/DerivedData/App-djyfdzootemmjocgeemfralmkphi/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection

DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/P
```

### Expected Behavior
ios Application does not crash and successfully shows SalesforceHybridSDK login page.

### Code Reproduction

Create a new capacitor App  
`ionic start ionic-capacitor --capacitor`

Install SalesforceHybridSDK - cordova plugin 
`npm i https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin.git#v9.1.1`

open Podfile and set platform as **platform :ios, '13.0'**

`ionic cap sync ios`

open xcode and delete the below files under **Pods>Development Pods > CordovaPluginsStatic**

<img width="487" alt="Screen Shot 2021-08-20 at 11 52 31 AM" src="https://user-images.githubusercontent.com/37552938/130280825-a084663a-bd5d-4f22-a047-4b220535c721.png">

In xcode **set deployment target to 13.0**

![Screen Shot 2021-08-20 at 11 59 20 AM](https://user-images.githubusercontent.com/37552938/130281278-3af7010a-2bf9-4afb-bc38-78b967e89413.png)

Run the app in xcode

### Other Technical Details

`npm --version` output: 6.14.14

`node --version` output: v14.17.5

`pod --version` output (iOS issues only): 1.10.1

**Comment by jcesarmobile** [comment]
I've been trying to make it work without success, but I've not been able to make it work on Cordova apps neither, so not sure if it's a plugin issue or a Capacitor issue. I tested 9.0.0, 9.1.0 and 9.1.1 versions of the plugin without success.

Anyway, I'm marking it as incompatible cordova plugin since the salesforce team said they don't support Capacitor
https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/552
