### ISSUE TITLE
cordova-plugin-nordic-update not working

### ISSUE THREAD

**Issue by swendleysprott** [ionic-team/capacitor#4957]
Hi,
 the [plugin](https://bitbucket.org/TheBosZ/cordova-plugin-nordic-update/src/master/) is working for Android on capacitor. But i'm having problems with IOS. When building the IOS app im getting an error stating that the CDVFile.h can't be found.

**Comment by jcesarmobile** [comment]
Capacitor no longer install plugin dependencies, that plugin depends on `cordova-plugin-file`, you need to install it and run `npx cap sync`, then it should work.
If you check the CLI output it should be noted there.

**Comment by swendleysprott** [comment]
Its already added but im still having the error. 
` Updating iOS plugins in 82.03ms
  Found 1 Capacitor plugin for ios:
@capacitor-community/bluetooth-le (0.5.1)
  Found 12 Cordova plugins for ios
    cordova-plugin-advanced-http (3.2.0)
    cordova-plugin-app-version (0.1.12)
    cordova-plugin-ble-central (1.3.1)
    cordova-plugin-dfu-update (1.3.0)
    cordova-plugin-file (6.0.2)
    cordova-plugin-inappbrowser (5.0.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-fingerprint-aio (4.0.2)
    cordova-plugin-taptic-engine (2.2.0)
    cordova-plugin-wifiwizard2 (3.1.1)
    es6-promise-plugin (4.2.2)
    phonegap-plugin-barcodescanner (8.1.0)
`
In X-code im getting the following errors:

<img width="1040" alt="Schermafbeelding 2021-08-24 om 16 02 54" src="https://user-images.githubusercontent.com/60102287/130630895-2add1dea-69cb-4ff2-aea3-8339d8c3215c.png">

**Comment by jcesarmobile** [comment]
can you report a new issue but filling out the whole template instead of removing it and providing a sample app?
