### ISSUE TITLE
bug: Browser.addListener browserFinished not fired on android

### ISSUE THREAD

**Issue by Torone** [ionic-team/capacitor#4959]
### Capacitor Version
2.4.7

### Platform(s)
Android

### Current Behavior
https://capacitorjs.com/docs/v2/apis/browser#addlistener
This is not working at all.
```
Browser.addEventListener('browserFinished', () => { // it never get here... })
```
I see you added a fix on `Browser.java` using the `fireFinished` Boolean, but that is not enough.
The Browser opens correctly, the prefetch is working fine. Once a user clase the Browser it is impossible to catch the event and perform further actions. This is super annoying because I need to fetch several things on my API once the browser is closed.
Is there an alternative way?

### Expected Behavior
Once the Browser get closed, the event `browserFinished` should work and allow further actions.

### Code Reproduction
Create Android app, open internal browser, catch the event when it is closed and voilà. It does't work.

**Comment by jcesarmobile** [comment]
I can't reproduce in Capacitor 3 and @capacitor/browser plugin, if you update to Capacitor 3 and still face the issue, report a new issue on https://github.com/ionic-team/capacitor-plugins/issues and provide a sample app where it can be reproduced.

**Comment by Torone** [comment]
It is not on Capacitor 3, it is on Capacitor 2. That is supposed to work...

**Comment by jcesarmobile** [comment]
I know, you are using an old version of Capacitor, you should update to the latest version.

**Comment by Torone** [comment]
It is not like that things should work. All versions should always work, no matter you create new versions...

**Comment by jcesarmobile** [comment]
I've just tested on Capacitor 2.4.9 and it's also working fine.
First thing you should do when you report an issue is prove that the problem exists and can be reproduced (by providing a sample app), thing that you didn't do.
Anyways, we don't offer free support for old Capacitor versions.
