### ISSUE TITLE
Integrating 3rd party SDK

### ISSUE THREAD

**Issue by anto-rupak** [ionic-team/capacitor#4975]
### Discussed in https://github.com/ionic-team/capacitor/discussions/4973

<div type='discussions-op-text'>

<sup>Originally posted by **anto-rupak** August 27, 2021</sup>
Hello Team,

Is there any way where I can Integrate the 3rd party Android SDK(Agora android) in to custom plugin in capacitor and then use it in my Ionic project? Please let me know if there is any way I can do it.

Thanks 
Anto</div>

**Comment by mlynch** [comment]
Hi @anto-rupak, follow the plugin guide for Android which describes how to build a plugin. You'd specify this SDK as a dependency in your gradle config: https://capacitorjs.com/docs/plugins/android.

Closing as this is not an issue.
