### ISSUE TITLE
bug: Modification of MainActivity prevents core plugins from working on Android

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor#4985]
## Bug Report

I'm not sure whether this is related to Sentry's Capacitor integration, Capacitor, or both, so a [similar issue](https://github.com/getsentry/sentry-capacitor/issues/83) has been opened on Sentry's Github but more specific Capacitor related processes I will attach here.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

I also have these plugins installed...

```
"@capacitor/camera": "1.0.4",
"@capacitor/push-notifications": "1.0.3",
"@capacitor/splash-screen": "1.1.1",
"@capacitor/storage": "1.0.3",
```

### Platform(s)

- Android

### Current Behavior

The modification of `MainActivity` when `@sentry/capacitor` is installed is preventing the Capacitor plugins from working, despite being installed, the modification of the `MainActivity` states to change...

```java
package com.stsonline.beacon;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {}
```

to...

```java
package com.stsonline.beacon;

import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import io.sentry.capacitor.SentryCapacitor;
import java.util.ArrayList;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      add(SentryCapacitor.class);
    }});
  }
}
```

However, in changing this, none of the Capacitor plugins that I've got installed work on Android, the app doesn't crash, it build successfully, but they all fail to function with an error such as:

> "SplashScreen" plugin is not implemented on android
> "Storage" plugin is not implemented on android
> "Push Notifications" plugin is not implemented on android
> "Camera" plugin is not implemented on android

If I revert the `MainActivity` back to the original, then my plugins all work again correctly for Android.

### Expected Behavior

With some core Capacitor plugins installed, along with Sentry's Capacitor integration, after running `npx cap sync android` and re-syncing Android studio with my gradle files, I should expect all of Capacitor's core plugins that are installed to continue to work.

### Code Reproduction

1. I installed `@sentry/capacitor` into my project which contains Capacitor v3
2. I updated `MainActivity.java` from:

```java
package com.stsonline.beacon;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {}
```

to...

```java
package com.stsonline.beacon;

import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import io.sentry.capacitor.SentryCapacitor;
import java.util.ArrayList;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      add(SentryCapacitor.class);
    }});
  }
}
```

3. I run `npx cap sync android` and open my project in Android studio, there's no errors, and deploy to emulator and physical phone.

### Other Technical Details

`npm --version` output: 7.21.0

`node --version` output: v14.17.4

**Comment by jcesarmobile** [comment]
Capacitor 3 auto register plugins, for that you need to remove the init method.
It should auto register sentry plugin too, so you shouldn't add the init method.

If you add the init method you have to register all the plugins and not just sentry one, but it's not recommended to use the init method anymore.

**Comment by sts-ryan-holton** [comment]
Great! Thanks for that, is this documented anywhere? I couldn't find anything on first glance.

I'm still keeping the `super` part and everything else, just remove the `this.init` part right?

**Comment by jcesarmobile** [comment]
It's documented on the [upgrade guide](https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading)

You can keep the onCreate if you want, as long as you remove the init, but you don't really need it unless you want to add some custom code to be run on onCreate.
