### ISSUE TITLE
bug: @capacitor/ios 3.2.1 creates cocoapods error

### ISSUE THREAD

**Issue by nowrap** [ionic-team/capacitor#4995]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.1
  @capacitor/core: 3.2.1
  @capacitor/android: 3.2.1
  @capacitor/ios: 3.2.1

Installed Dependencies:

  @capacitor/core: 3.2.1
  @capacitor/android: 3.2.1
  @capacitor/ios: 3.2.1
  @capacitor/cli: 3.2.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

iios

### Current Behavior

npx cap update ios fails on the following cocoapods error. a downgrade to @capacitor/ios: 3.2.0 solves this issue

````
 Errno::ENOENT - No such file or directory @ realpath_rec - /my-hidden-folder/node_modules/@capacitor/ios/ios
````

it seems to be the doubled ios path. this doesn't exist

### Expected Behavior

update without error

### Other Technical Details

`npm --version` output: 7.21.1

`node --version` output: v14.16.1

`pod --version` output (iOS issues only): 1.11.0

**Comment by DavidBowdoin** [comment]
I had the same issue and downgrading to 3.2.0 fixed it.

**Comment by elashpear** [comment]
Can reproduce as well, I'm not sure how to get around this for a brand new project as there appears to be no way to specify a version when running `ionic capacitor add ios`.

**Comment by markterrill** [comment]
hi, same. Can downgrade to sidestep it.
capacitor/iOS/iOS doesn't exist.

**Comment by markterrill** [comment]
@elylucas imho it appears the podspec edits added an extraneous iOS/ at the start of the paths.

https://github.com/ionic-team/capacitor/commit/ab960a86a720bf2df5590fd0c359e5f6e67c8def#diff-48ee046028069a9c6ded9844911eab9020389ac067e2a8772244b99be182e063

**Comment by jcesarmobile** [comment]
3.2.2 is out with the fix
