### ISSUE TITLE
bug: cordova-plugin-streaming-media crashes in landscape

### ISSUE THREAD

**Issue by MatthewPringle** [ionic-team/capacitor#5000]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.1
  @capacitor/core: 3.2.1
  @capacitor/android: 3.2.1
  @capacitor/ios: 3.2.1

Installed Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/ios: 3.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS

### Current Behavior

When the app is set to portrait only, opening a landscape video crashes the app.

Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [LandscapeAVPlayerViewController shouldAutorotate] is returning YES'
terminating with uncaught exception of type NSException

### Expected Behavior

The same app, with the same settings in Cordova works fine. The app is locked to Portrait but the video is allowed to be played in Landscape.

### Code Reproduction
Build a new app, portrait only, install cordova-plugin-streaming-media and attempt to open a video

```
var options = {
  orientation: 'landscape',
  shouldAutoClose: true,
  controls: true,
  successCallback: function() {
  },
  errorCallback: function() {
  }
};
                
window.plugins.streamingMedia.playVideo( video , options );
```

### Other Technical Details
Maybe related to this? https://github.com/ionic-team/capacitor/issues/2591#issuecomment-608572792

**Comment by jcesarmobile** [comment]
I don't think it's related since the plugin you mention doesn't use CDVScreenOrientationDelegate.
Can you provide a sample app?

**Comment by MatthewPringle** [comment]
Here is a basic iOS app with a button to press to launch the video and crash the app

https://www.dropbox.com/s/znkun06cprtp7rq/bug%235000.zip?dl=0

**Comment by MatthewPringle** [comment]
As a quick fix I managed to cobble the below amend to AppDelegate which allows the LandscapeAVPlayerViewController class to use allButUpsideDown which works in my case.

```
func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        var presentedVC = application.keyWindow?.rootViewController
        while let pVC = presentedVC?.presentedViewController
        {
            presentedVC = pVC
        }
        if let pVC = presentedVC
        {
            let name = String(describing: type(of: pVC.self))
            if name == "LandscapeAVPlayerViewController" {
                return UIInterfaceOrientationMask.allButUpsideDown
            }
        }
        return UIInterfaceOrientationMask.portrait
    }
```

**Comment by jcesarmobile** [comment]
As your app only supports portrait, then it crash when you try to open a ViewController in Landscape, that's expected.
In Cordova it might work because you probably didn't restrict the orientation to portrait.

You can allow all orientations and then use `cordova-plugin-screen-orientation` or some other plugin to block Capacitor's ViewController in portrait, but allow other ViewControllers to have different orientations, or use the workaround you have mentioned, but there is nothing we can do about this problem.

Could also be fixed in the plugin if they didn't allow the LandscapeAVPlayerViewController to rotate by adding
```
-(BOOL) shouldAutorotate {
    return NO;
}
```

**Comment by MatthewPringle** [comment]
> As your app only supports portrait, then it crash when you try to open a ViewController in Landscape, that's expected.
> In Cordova it might work because you probably didn't restrict the orientation to portrait.
> 
> You can allow all orientations and then use `cordova-plugin-screen-orientation` or some other plugin to block Capacitor's ViewController in portrait, but allow other ViewControllers to have different orientations, or use the workaround you have mentioned, but there is nothing we can do about this problem.
> 
> Could also be fixed in the plugin if they didn't allow the LandscapeAVPlayerViewController to rotate by adding
> 
> ```
> -(BOOL) shouldAutorotate {
>     return NO;
> }
> ```

Problem was the Cordova app was restricted to portrait using both the xcode plist settings and also using cordova-plugin-screen-orientation to lock the app to portrait on boot ( to fix an old Android issue ) and the video plugin worked fine rotating the view to landscape.
