### ISSUE TITLE
bug: Share API not available in firefox browser

### ISSUE THREAD

**Issue by papansarkar101** [ionic-team/capacitor#5014]
Not working on firefox. got this error on the console. 
![image](https://user-images.githubusercontent.com/36565033/132203492-5278fade-db65-44d7-b6f7-d13ca7675c82.png)

**Comment by jcesarmobile** [comment]
Yeah, if the browser doesn’t have the share api available it throws that error.

**Comment by papansarkar101** [comment]
Whats the solution then? I can not use this on firefox?

**Comment by jcesarmobile** [comment]
Yeah, you can’t use an API that isn’t available, you catch the error and show the user some message that says that isn’t possible to share in that browser.
