### ISSUE TITLE
bug: datalist autocomplete doesn't work on Android

### ISSUE THREAD

**Issue by thequailman** [ionic-team/capacitor#5023]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Platform(s)

Android

### Current Behavior

When running on Android, `<input>` elements with a `<datalist>` do not show an autocomplete menu below the input when a user focuses on the input.  This works fine in Chrome on Android and PWAs installed on Android.

### Expected Behavior

Autocomplete menu with datalist objects is shown to the user.

### Code Reproduction

```
<input list="my-datalist">
<datalist id="my-datalist">
<option value="1">1</option>
<option value="2">2</option>
</datalist>
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
I've tested the provided example and it's working fine on my device.

Anyway, Capacitor doesn't take part on the rendering of the html on any way, if you find issues where the WebView doesn't behave the same way as Chrome you should report them to Google/Chromium.

**Comment by thequailman** [comment]
Sorry to reopen this, but can you tell me what version of Android/hardware you're using?  I've tested this on multiple devices now and I can't get the datalist menu to pop up or show any autocomplete.
