### ISSUE TITLE
bug: node-tar should be updated to 6.1.9 at least

### ISSUE THREAD

**Issue by aseques** [ionic-team/capacitor#5026]
## Bug Report

@capacitor/cli has a dev dependency on tar 6.0.5, there's an advisory ([here](https://www.npmjs.com/advisories/1781)) requesting it to be upgraded to 6.1.9 in order to have the fixes included.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0

```

### Platform(s)

Windows, but node audit triggers the error on every platform

### Current Behavior

It's a security bug that affects windows.

### Expected Behavior

There shouldn't be any security warnings

### Code Reproduction

Doing a npm audit will just highlight the issue

**Comment by jcesarmobile** [comment]
already sent the PR yesterday
https://github.com/ionic-team/capacitor/pull/5022
