### ISSUE TITLE
bug: no such file or directory, stat '.../node_modules/@capacitor/cli/assets/ios-template.tar.gz'

### ISSUE THREAD

**Issue by echan00** [ionic-team/capacitor#5029]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/core: 3.2.2
  @capacitor/cli: 3.2.2
  @capacitor/ios: 3.2.2

[success] iOS looking great! 👌
✨  Done in 2.54s.
```

### Platform(s)
Mac OS 11.5.2

### Current Behavior
% yarn cap add ios

yarn run v1.22.10
$ /Users/xxx/Workspace/yyy/node_modules/.bin/cap add ios
✖ Adding native Xcode project in ios - failed!
✖ add - failed!
[error] Error: ENOENT: no such file or directory, stat
        '/Users/xxx/Workspace/yyy/node_modules/@capacitor/cli/assets/ios-template.tar.gz'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Expected Behavior
Should add ios folder and create iOS xcode project?

**Comment by echan00** [comment]
Following the 'getting started' instructions, I first installed the capacitor core and cli library without any issues:
`yarn add @capacitor/core @capacitor/cli`

Then afterwards running `yarn cap add ios`gives me the error:
`no such file or directory, stat
'/Users/xxx/Workspace/yyy/node_modules/@capacitor/cli/assets/ios-template.tar.gz'`

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by echan00** [comment]
I was able to solve the problem by using `sudo yarn cap add ios` i'm surprised there was no error when some files weren't added
