### ISSUE TITLE
Camera don't ask for permissions. Camera.requestPermissions() gives an error

### ISSUE THREAD

**Issue by sbellver** [ionic-team/capacitor#5030]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2
  @capacitor/cli: 3.2.2
```

### Platform(s)
iOS

### Current Behavior
I want to take a picture from camera or upload from gallery.

```
await Camera.getPhoto({
          resultType: 'base64',
          direction: CameraDirection.Rear,
        }).then((res) => {
        ...
```

But when I click on button, nothin happens.

I check mi Privacy in iOS, and my app don't have permissions in Camera or Gallery.

My plist have the NS Privacy... (3 items related to camera/gallery)

Then, I want to check/ask permissions to user before get the photo

```
const permiso = Camera.requestPermissions();
console.log(permiso);
this.captureImage(image, direction);
...
```

Then, when I click on button to take photo, debug show me an error

⚡️  [error] - {}

### Expected Behavior
Ask about Camera & gallery permissions if user doesn't have 

### Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.18.3

`pod --version` output (iOS issues only): 1.10.2

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by sbellver** [comment]
Don't worry, I'm previously on Capacitor 2, and now in Capacitor 3.

I need to change core to camera in import
