### ISSUE TITLE
Capacitor uses iOS scheme names as iOS target identifiers forcing you to create multiple targets

### ISSUE THREAD

**Issue by LukeGrossmann** [ionic-team/capacitor#5036]
Versions for reference:
<img width="883" alt="Screen Shot 2021-09-10 at 7 26 15 PM" src="https://user-images.githubusercontent.com/33207911/132933184-67cb6fc6-b228-43ce-a63b-e30efe58fb3d.png">

Capacitor forces you to create multiple Targets in xCode for each scheme. The reason for this is due to them using your scheme option that you pass in the **capacitor.config.ts** file as the name of the executable or **target**. This does not make much sense as most configurations would consist of a single target or main target with **multiple schemes**; ie: **QA**, **Staging**, **Production** and each scheme would have **1 configuration** that is used with them. An example would be a project (App) which is called **"demo-app"** that has a main target called **"demo-app"**, this main target has **multiple schemes** and each scheme has **one configuration** which allows the target to be updated at build time dynamically. This is not possible with Capacitor. Instead you would have to have a project called **"demo-app"**, multiple targets called **"staging"**, **"QA"**, **"Production"**, each target would have 1 scheme associated with it and each scheme have 1 configuration. this would result in **Project: "demo-app" -> target: "staging" -> scheme: "staging" -> configuration: "staging"**.   

This is all due to one line of code in Capacitor's run.js script: **NOTE LINE 33**
<img width="1280" alt="Screen Shot 2021-09-10 at 7 37 06 PM" src="https://user-images.githubusercontent.com/33207911/132933439-1f6e991e-bf5e-4962-b6fd-307654b93a1f.png">

As you can see above Capacitor uses the scheme name as the target name ?

Here I will run you through an example of what happens if you use a target and scheme with different names.
These next screenshots will follow the example of using a scheme called **"staging2"** against a target called "Transform".
**First the config:**
<img width="601" alt="Screen Shot 2021-09-10 at 7 41 36 PM" src="https://user-images.githubusercontent.com/33207911/132933558-5e9d3a0c-64b2-403a-8de1-44f78ee70be1.png">

**Next the scheme and target in xCode:**
<img width="928" alt="Screen Shot 2021-09-10 at 7 42 20 PM" src="https://user-images.githubusercontent.com/33207911/132933554-15fab427-55d3-4d74-8306-65a8469c38d2.png">

**Now lets run capacitors ios-simulator command from the terminal which activates Capacitor's run.js file:**

<img width="1831" alt="Screen Shot 2021-09-10 at 7 43 57 PM" src="https://user-images.githubusercontent.com/33207911/132933605-3ee8b939-77d8-4b6f-a16d-5a18fca454ca.png">

Notice how it fails to run because it's trying to use the scheme name as a scheme and a target name. If I were to reverse this and give it the target name instead of the scheme it would say that the scheme doesn't exist. The only way to satisfy this is to create multiple targets to adhere to each scheme which is not good practice.

What I recommend is adding a setting in the iOS portion of the capacitor config to select a target and while we are at it why not give the user the ability to select the configuration as well ?. Notice in the above picture of Capacitor's run.js they are automatically assuming you're using a debug config ? What about if I have created several duplicates of the debug config that all have dynamic settings ? on a side side note, why are you only allowed to set flavours and not build types on the android side of the config ?

These are the fundamentals of Native development that should be tied into hybrid development. These should be the first settings that are applied as you dynamically swap environments in your angular / ionic application prior to the capacitor config being applied.

I am happy to help with any code changes or pull requests although I have never done that before for a third party company :)

**Comment by jcesarmobile** [comment]
scheme is used for what xcodebuild command considers a scheme, you don't need to add new targets, but to create a new scheme, but if you create a new target, Xcode automatically creates a scheme too.
To create a new scheme use Product -> Scheme -> New Scheme
If you run `xcodebuild -list` you'll see the available schemes

Only Debug configuration is supported at the moment and will probably not support others for now as run command was added only for debug builds.

**Comment by LukeGrossmann** [comment]
@jcesarmobile 
I am sorry I am not following this, I understand how to make schemes in xCode - I had 5 schemes under one target called 'Transform', however this will not work as seen above in your run.js file you actively take the scheme name in the capacitor config and try and match it with a target. I don't think your explanation is good enough as there are no code examples or screenshots or videos of what you saying working. Having 1 target and multiple schemes with different names does not work based on the above explanation I gave you.

I understand debug is the only configuration snd that's the problem that we need to change. What if I am building using a 30,000 dollar enterprise subscription in Appflow which is made for Capacitor and it uses the config file to generate app store builds. You're telling me I am going to have a debug config for that ? How come I can't select my other buildTypes in Android ? This doesn't make any senes but most importantly having multiple schemes and 1 target does not work

**Comment by jcesarmobile** [comment]
The scheme from capacitor config file is used as the scheme parameter of xcodebuild command, that can be seen in the screenshot you provided. Is solely used for that, that’s why it’s called scheme and not target.

**Comment by LukeGrossmann** [comment]
hi @jcesarmobile ,

Thanks for your reply and I am in talks with Appflow regarding some other issues. However, AppFlow does use the config file as Appflow runs sync-ios and sync-android during builds, this is one of the reasons capacitor added functionality for a ts/js cap config file, so that the variables could be switched dynamically otherwise there is about zero point in the config file since all those settings can be manually changed in the native IDE's.

In regards to the multiple target / scheme issue, I am still not following you. If you look at line 33 of the screenshot I provided in capcitor's run.js you'll notice **const appName = `${config.ios.scheme}.app** -> this is run.js trying to match the scheme name you provided with a target. Imagine I have one target called **appTarget** and a scheme named **appScheme** and a run the ios-simulator right from the terminal which calls the run.js file. This will break as my scheme name won't be the exact same as my target name.

**Comment by jcesarmobile** [comment]
At the moment for run command the target name has to match the scheme name, it’s not supported to have different names, you’ll have to run from Xcode.

Appflow doesn’t use the config file for anything, sync command will build the config files, but it’s capacitor what handles the logic. And the scheme values is not used by capacitor when run in appflow, it’s only used for run command and appflow doesn’t run you app.
Appflow allows to build debug and release builds generating the ipa, but that’s inside appflow logic and not related to capacitor.

**Comment by LukeGrossmann** [comment]
@jcesarmobile 
The difference between your first reply and this previous reply is quite different. Now you're saying it isn't possible after reexplaining the main post, with this said the goal here was not to identify an issue, I already knew there was an issue. The goal was to adjust code so that the run.js file worked the same as the native IDE's so we wouldn't have to make a choice between having multiple targets or not using the capacitor feature to run simulators from the terminal. I think this ticket should be reopened and a pull request should be attempted.

In regards to Appflow, I could be wrong and I have a meeting with the director of product on Monday as I am running team to release a enterprise app and from what they have said and what I have seen is that Fastlane, which is used by Appflow does in fact compile the config file for the native folder (**which you stated**), however then uses the configurations to select things like flavors, schemes, bundle ID etc. Otherwise how else would Appflow be able to automate the build and release process if it didn't use anything to pick the native configs ?

Proposed changes:
1. Make run.js work like the rest of the native IDE normal configs (BUG) (MAIN POST)
2. Add buildTypes, ios configurations, ios targets into the cap config to have all settings

@jcesarmobile is there a director at Capacitor I can get in contact with regarding these and can we focus on goal 1. I think this would be possible if we reopend the ticket and made a PR

**Comment by jcesarmobile** [comment]
Not being supported is not the same thing as being an issue.
Run command was added as a quick way of doing debug builds, it cover most cases as is, but you are doing non standard things.
If you are a paying customer you can talk with support and request the feature, then it will be evaluated and might be added in the future.

**Comment by LukeGrossmann** [comment]
@jcesarmobile  I'm sorry I don't agree with that. If you have a script that operates away from the rest of native development and forces the client to either continue with standard practices and have a great capacitor feature unusable or navigate away from standard native practices and have a capacitor feature useable. I would call this an **issue**.
The only thing not standard here is your run script, I don't think you quite understand either, I debug build won't work either as it will require a debug target not just a scheme. The goal of this whole post was to find a solution as it's probably an easy fix I could do. I asked above is there a senior or director I can speak to or do I need to bring them into this chat from other posts ?

**Comment by LukeGrossmann** [comment]
@imhoffd ccing you into this post as I've seen you do great work in other capacitor PR's / open issues. I would be more than happy to work together to figure this out

**Comment by jcesarmobile** [comment]
In Build Settings -> Packaging -> Product Name you can set the name of the executable that will be built. By default it's `$(TARGET_NAME)`, which is also the default scheme name.
Since you don't want to create multiple targets but a single target with multiple build configuration, just set the name for each built configuration to match the scheme where you use that build configuration and run command will work.

**Comment by LukeGrossmann** [comment]
@jcesarmobile Thanks for the suggestion, I tested this out and unfortunately this doesn't work. 
However it's good that you mentioned this as this should be the default standard behaviour. If I have 1 target called myTarget and let's say 5 schemes S1, S2, S3, S4 and S5. The standard would be to set the target as the executable through the manage schemes section or via your navigation to dynamically setting the product name per scheme. 

This is auto done for you as you mentioned because it is **standard** practice. This is why this is an issue, because back to the original issue, Capacitor run.js goes against every other practice by capacitor and xCode. It uses the scheme name as the executable no matter what and this is why you need **a target for each scheme** when the fix should be getting the actual executable which is set for each scheme instead of assuming it's the scheme name
