### ISSUE TITLE
feat: Capacitor v3 lottie splashscreen 

### ISSUE THREAD

**Issue by liho00** [ionic-team/capacitor#5037]
### Description
how to replace default splashscreen with lottie splashscreen in capacitor 3? 
i tried this native plugin
https://ionicframework.com/docs/native/lottie-splash-screen

Instead of manually call show method in the web app project, its should be done in top level right in capacitor config?

### Platform(s)
Android
IOS

### Preferred Solution
setting the lottie raw value in the capacitor.config.json

**Comment by jcesarmobile** [comment]
You can request community plugins here
https://github.com/capacitor-community/proposals
