### ISSUE TITLE
feat: Web Intent for Android and iOS to receive Data from other Applications. 

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor#5039]
### Description
Application Should Received Data from other Applications. When User try to share application should show in Share List of native Android and IOS to receive Data. 

### Platform(s)
Android 
IOS

### Alternatives

[Web intent](https://ionicframework.com/docs/native/web-intent)
[Cordova-plugin-openwith](https://github.com/j3k0/cordova-plugin-openwith)
[Capacitor send Intent](https://github.com/carsten-klaffke/send-intent)

### Additional Context
Capacitor Should have Built in Feature to Receive Data From other Applications

**Comment by jcesarmobile** [comment]
This can’t be built in because it requires some configuration too specific and that most people won’t use.

you can request community plugins here
https://github.com/capacitor-community/proposals
