### ISSUE TITLE
Capacitor.js does not work with Android API 21-23 (Lollipop and Marshmallow)

### ISSUE THREAD

**Issue by codeconsole** [ionic-team/capacitor#5043]
## Bug Report - capacitor.js does not load with Android API 21-23

npx cap add android creates
```
android/variables.gradle:    minSdkVersion = 21
```
but Android API 21-23 does not work.

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

```
### Platform(s)
    Name: Pixel_2_API_21
  Device: pixel_2 (Google)
    Path: ~/.android/avd/Pixel_2_API_21.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 5.0 (Lollipop) Tag/ABI: google_apis/x86_64
  Sdcard: 512 MB
---------
    Name: Pixel_2_API_22
  Device: pixel_2 (Google)
    Path: ~/.android/avd/Pixel_2_API_22.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 5.1 (Lollipop) Tag/ABI: google_apis/x86_64
  Sdcard: 512 MB
---------
    Name: Pixel_2_API_23
  Device: pixel_2 (Google)
    Path: ~/.android/avd/Pixel_2_API_23.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 6.0 (Marshmallow) Tag/ABI: google_apis/x86_64
  Sdcard: 512 MB
```

### Current Behavior
App Startup fails `chrome://inspect/#devices`
```
capacitor.js:2 Uncaught SyntaxError: Use of const in strict mode.
```

### Expected Behavior
Expect capacitor.js to load.

### Code Reproduction
https://github.com/codeconsole/exiftest/tree/capacitor
```
git clone https://github.com/codeconsole/exiftest
cd exiftest
git checkout capacitor
npm install
npx cap add ios
npx cap add android
cp conf/Info.plist ios/App/App/Info.plist
cp conf/AndroidManifest.xml android/app/src/main/AndroidManifest.xml
npx cap sync
sdkmanager 'system-images;android-21;google_apis;x86_64'
avdmanager create avd --name Pixel_2_API_21 --package 'system-images;android-21;google_apis;x86_64' --device 'pixel_2'
cap run android --target=Pixel_2_API_21 
```

### Other Technical Details
`npm --version` output:
```
7.20.3
```
`node --version` output:
```
v16.7.0
```

**Comment by codeconsole** [comment]
![Android Error](https://raw.githubusercontent.com/codeconsole/exiftest/capacitor/screenshots/android-22-error.jpg)

**Comment by DoveAz** [comment]
yeah, I think this needs to be modified (android 7+)
![image](https://user-images.githubusercontent.com/15158280/132990530-11f3bd75-1cde-405a-88ef-e72686b4ae9d.png)

**Comment by DoveAz** [comment]
If you use 23+ you need some polyfill
copy this in your index.html,
```javascript
 <script src="https://polyfill.io/v3/polyfill.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/proxy-polyfill@0.3.2/proxy.min.js"></script>
```

if you use webpack,you also need to modify transpileDependencies,add all capacitor plugins

**Comment by codeconsole** [comment]
> If you use 23+ you need some polyfill
> copy this in your index.html,
> 
> ```js
>  <script src="https://polyfill.io/v3/polyfill.min.js"></script>
>  <script src="https://cdn.jsdelivr.net/npm/proxy-polyfill@0.3.2/proxy.min.js"></script>
> ```
> 
> if you use webpack,you also need to modify transpileDependencies,add all capacitor plugins

I updated the example with the polyfill and it still does not work.
https://github.com/codeconsole/exiftest/tree/capacitor

I get a different error with Android 23:
![Android Error](https://raw.githubusercontent.com/codeconsole/exiftest/capacitor/screenshots/android-23-error.jpg)

**Comment by codeconsole** [comment]
I've also created angular, vue, and react apps and they all experience the exact same issues:
https://github.com/codeconsole/ionic-playground

**Comment by jcesarmobile** [comment]
Capacitor requires chrome/chromium/system webview 60+.
Since android 5 (SDK level 21) the system webview/chrome/chromium can be updated from google play. So it would work on android 5-6 devices as long as the webview is up to date, which is not the case for the android 5-6 emulators, they are not up to date and can’t be updated because they don’t have google services.

**Comment by codeconsole** [comment]
@jcesarmobile 

Is there a way of gracefully handling this so that if they aren't up to date? Maybe at least deliver a nice screen that tells them to update?

Is there a recommended way to configure an emulator to simulate these devices?

What is the highest webview android 5 can update to?   According to wikipedia, it is no longer supported.
https://en.wikipedia.org/wiki/Android_version_history
