### ISSUE TITLE
Unable to find node_modules/appname. Are you sure appname is installed?

### ISSUE THREAD

**Issue by prosperva** [ionic-team/capacitor#5047]
I am trying to add iOS and every time I run into this error:

**ionic capacitor add ios** throws the following error:

**Unable to find node_modules/appname. Are you sure appname is installed?**

I have done the following commands with no issues

npm install --force
npm build

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by prosperva** [comment]
I run the same command with --verbose flag and I got this:

 ionic:lib Terminal info: { ci: false, shell: '/bin/zsh', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'capacitor', 'add', 'ios' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +2ms
  ionic:lib:project Project type from config: @ionic/angular (angular) +0ms
  ionic:lib:project Project details: { context: 'app', type: 'angular', errors: [], configPath: 'userpath/app/ionic.config.json' } +0ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/local/lib/node_modules/@ionic/cli', execPath: 'userpath', version: '6.17.1' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic capacitor add' [ 'ios', '--verbose', '--interactive', '--color' ] +0ms
  ionic:lib:integrations:capacitor Getting config with Capacitor CLI: [ 'config', '--json' ] +0ms
  ionic:lib:integrations:capacitor Could not get config from Capacitor CLI (probably old version) +212ms
> capacitor add ios
[capacitor] [error] Unable to find node_modules/appname. Are you sure appname is installed?
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor add ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +67ms

**Comment by prosperva** [comment]
ionic --version
6.17.1
npm -v 
7.19.1

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by prosperva** [comment]
I am trying to add iOS support for an existing ionic app. I did run the same commands and it worked but on the existing project it is failing.

**Comment by prosperva** [comment]
Weird way I solved this:

I installed android and it worked then installed ios platform and got it to go through
