### ISSUE TITLE
Capacitor uses iOS scheme names as iOS target identifiers forcing you to create multiple targets

### ISSUE THREAD

**Issue by LukeGrossmann** [ionic-team/capacitor#5050]
Versions for reference:
<img width="883" alt="Screen Shot 2021-09-10 at 7 26 15 PM" src="https://user-images.githubusercontent.com/33207911/132933184-67cb6fc6-b228-43ce-a63b-e30efe58fb3d.png">

Capacitor forces you to create multiple Targets in xCode for each scheme. The reason for this is due to them using your scheme option that you pass in the **capacitor.config.ts** file as the name of the executable or **target**. This does not make much sense as most configurations would consist of a single target or main target with **multiple schemes**; ie: **QA**, **Staging**, **Production** and each scheme would have **1 configuration** that is used with them. An example would be a project (App) which is called **"demo-app"** that has a main target called **"demo-app"**, this main target has **multiple schemes** and each scheme has **one configuration** which allows the target to be updated at build time dynamically. This is not possible with Capacitor. Instead you would have to have a project called **"demo-app"**, multiple targets called **"staging"**, **"QA"**, **"Production"**, each target would have 1 scheme associated with it and each scheme have 1 configuration. this would result in **Project: "demo-app" -> target: "staging" -> scheme: "staging" -> configuration: "staging"**.   

This is all due to one line of code in Capacitor's run.js script: **NOTE LINE 33**
<img width="1280" alt="Screen Shot 2021-09-10 at 7 37 06 PM" src="https://user-images.githubusercontent.com/33207911/132933439-1f6e991e-bf5e-4962-b6fd-307654b93a1f.png">

As you can see above Capacitor uses the scheme name as the target name ?

Here I will run you through an example of what happens if you use a target and scheme with different names.
These next screenshots will follow the example of using a scheme called **"staging2"** against a target called "Transform".
**First the config:**
<img width="601" alt="Screen Shot 2021-09-10 at 7 41 36 PM" src="https://user-images.githubusercontent.com/33207911/132933558-5e9d3a0c-64b2-403a-8de1-44f78ee70be1.png">

**Next the scheme and target in xCode:**
<img width="928" alt="Screen Shot 2021-09-10 at 7 42 20 PM" src="https://user-images.githubusercontent.com/33207911/132933554-15fab427-55d3-4d74-8306-65a8469c38d2.png">

**Now lets run capacitors ios-simulator command from the terminal which activates Capacitor's run.js file:**

<img width="1831" alt="Screen Shot 2021-09-10 at 7 43 57 PM" src="https://user-images.githubusercontent.com/33207911/132933605-3ee8b939-77d8-4b6f-a16d-5a18fca454ca.png">

Notice how it fails to run because it's trying to use the scheme name as a scheme and a target name. If I were to reverse this and give it the target name instead of the scheme it would say that the scheme doesn't exist. The only way to satisfy this is to create multiple targets to adhere to each scheme which is not good practice.

What I recommend is adding a setting in the iOS portion of the capacitor config to select a target and while we are at it why not give the user the ability to select the configuration as well ?. Notice in the above picture of Capacitor's run.js they are automatically assuming you're using a debug config ? What about if I have created several duplicates of the debug config that all have dynamic settings ? on a side side note, why are you only allowed to set flavours and not build types on the android side of the config ?

These are the fundamentals of Native development that should be tied into hybrid development. These should be the first settings that are applied as you dynamically swap environments in your angular / ionic application prior to the capacitor config being applied.

I am happy to help with any code changes or pull requests although I have never done that before for a third party company :)

**Adding this issue as the last reply was no where near adequate for the explanation I provided**
https://github.com/ionic-team/capacitor/issues/5036

**Comment by jcesarmobile** [comment]
Please, don’t create duplicate issues.
