### ISSUE TITLE
bug: Firebase JS SDK incompatible with Capacitor 3 on iOS14

### ISSUE THREAD

**Issue by roldyclark** [ionic-team/capacitor#5059]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/ios: 3.2.2
  @capacitor/android: 3.2.2

[success] iOS looking great! 👌

### Platform(s)
iOS 14 

### Current Behavior

in iOS14, Firebase calls hang indefinitely (getAuth(), getDocs(), etc) 

### Expected Behavior

Firebase calls should resolve.

### Code Reproduction
Requires Firebase account and setup, can't post mine here.

### Other Technical Details

`npm --version` output: 7.22.0

`node --version` output: v14.17.0

`pod --version` output (iOS issues only): 1.11.0

### Additional Context
Other discussion: https://github.com/firebase/firebase-js-sdk/issues/5019

**Comment by roldyclark** [comment]
FIXED! Here's the solution: https://harryherskowitz.com/2021/08/23/firebase-capacitor.html

**Comment by ejirocodes** [comment]
Fixed here: https://stackoverflow.com/a/69793220/12624390

**Comment by tobium** [comment]
it only works with the firebase JS SDK, not with AngularFire :(

**Comment by mauriceackel** [comment]
@roldyclark Thanks for writing about this issue and sharing the solution. I am facing the same issue, however the proposed solution did not work. Only once I used the `browserLocalPersistence` persistence strategy, the initialization worked as expected on iOS. Do you have any idea why this could be or how to get the default indexedDB persistence to work?
