### ISSUE TITLE
Builds error when running `ionic cap run ios` or `npx cap run ios`. 

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ionic-team/capacitor#5060]
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
iOS

### Current Behavior
If I run `ionic cap run ios` or `npx cap run ios` I get the following error. 

✔ Running xcodebuild in 14.28s
✖ Deploying KeyCollector.app to 00008101-001C0C921438001E - failed!
[error] ERR_UNKNOWN: Path
        '/Users/........../ios/DerivedData/00008101-001C0C921438001E/Build/Products/Debug-iphoneos/xxxxxxxxx.app'
        not found

### Expected Behavior
I expect the app to build and run on iOS.

### Other Technical Details

`npm --version` output: 6.14.13

`v14.17.0` output:

`1.11.2` output (iOS issues only):

### Additional Context
The app itself builds fine. If I manually run it in XCode the app works fine. The problem is that I'm unable to do a livereload so therefore I have to rebuild every time I need to check something on iOS.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by selected-pixel-jameson** [comment]
My app had no issues doing a live reload before I followed your guide on updating to capacitor 3. Now it's borked and it's my responsibility to figure out the issue? If I could create a project I could share that replicated the issue I would probably also be able to identify the issue and there's no way I can share my clients source code.

**Comment by selected-pixel-jameson** [comment]
FYI. I've restarted my computer and updated every dependency to the latest version I can. I've updated all the config files as well to match the starter projects also. 

My guess is there is something that got hosed in the XCode project due to the Capacitor 3 migration and I'm going to have to delete that and rebuild it, which is really not ideal.

**Comment by LukeGrossmann** [comment]
@jcesarmobile I see you have added a reproduction tag on this PR when I this exactly the same issue that I've been trying to confront with you. 

@selected-pixel-jameson

**Comment by selected-pixel-jameson** [comment]
@LukeGrossmann thank you for the suggestion. My scheme is definitely not named App. I'll take a look at this and update here.

**Comment by selected-pixel-jameson** [comment]
@LukeGrossmann Your suggestion definitely lead me to the solution.  

The problem was that my Scheme was named AppName and the Product defined in the XCode build Settings was App Name. 
Whats I matched these two values the issue was resolved. So to your point in issue #5036 this was the exact issue because I had appName and scheme both defined correctly in my capacitor.config.json, yet the problem was still happening. It wasn't until I made sure the scheme and the product name matched that it built successfully.

**Comment by LukeGrossmann** [comment]
@selected-pixel-jameson Glad my post helped, please give it an upvote to get more attention as I believe it's getting overlooked. The problem is that your solution is non standard and temporary. If you end up wanting different environments (schemes, configs user-defined settings) you're going to have to create a target for each one which makes native development a mess and over cluttered.

@jcesarmobile I am happy I was able to solve the issue but this a clear indication that other people are following good practices and running into this issue.
