### ISSUE TITLE
bug: Iframe showing white screen when loading content from web or local in Android

### ISSUE THREAD

**Issue by ik-rssce** [ionic-team/capacitor#5063]
## Bug Report
I have added pdf in iframe and tried to load from web and local. But in both cases, in Android its showing white black screen.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3

```

### Platform(s)

Android

### Current Behavior

Pdf not rendering in iframe. i have attached the sample project.

### Expected Behavior

Pdfs should be rendered in iframe.

### Code Reproduction

`  <iframe src="/assets/pdf-test.pdf" width="100%" height="600px"></iframe>
`
This does work in iOS and Web browser but not inside an Android emulator and device.

**Comment by jcesarmobile** [comment]
Android WebView is not able to render PDF files, for external urls you can use google docs viewer by loading this url `http://docs.google.com/gview?embedded=true&url=https://yourserver.com/yourfile.pdf`, but for local files there is nothing you can do.

**Comment by ik-rssce** [comment]
Is this Capacitor limition ? Any workaround / customization possible instead of google docs ?

**Comment by jcesarmobile** [comment]
It’s an android limitation
