### ISSUE TITLE
Value of type 'WKWebViewConfiguration' has no member 'limitsNavigationsToAppBound Domains' on build of iOs app

### ISSUE THREAD

**Issue by eliottlenud** [ionic-team/capacitor#5067]
## Bug Report

I haven't found nothing about this problem on the web so I am creating this issue because the only solution I have found is to remove this condition of the code but I need it to be solved. 

### Capacitor Version
  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

```
"Value of type 'WKWebViewConfiguration' has no member 'limitsNavigationsToAppBound Domains'"
```

### Platform(s)
iOs

### Current Behavior
This error is related to the code : 
```
if #available(iOS 14.0, *) {
            webViewConfiguration.limitsNavigationsToAppBoundDomains = instanceConfiguration.limitsNavigationsToAppBoundDomains
        }
```
line 108 in file CAPBridgeViewController.swift
Build failed

### Expected Behavior
Build successfull

`npm --version` output: 6.13.6

`node --version` output: v12.14.1

`pod --version` output (iOS issues only): 1.9.0

**Comment by jcesarmobile** [comment]
what's your Xcode version?

**Comment by jcesarmobile** [comment]
Capacitor 3 requires Xcode 12
https://capacitorjs.com/docs/ios#ios-support

**Comment by eliottlenud** [comment]
Thank you very much ! @jcesarmobile
