### ISSUE TITLE
feat: How to Detect if app is installed or not in PWA / Web.

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor#5068]
### Description
I want to show a Prompt to my users to open app with 2 options continue in browser or open in app. Is there any way to determine if App is installed on device. If installed open in app if not redirect user to `Playstore` or `App Store`. i have integrated `AppLauncher` API and it is working But when the app is not installed it redirect users to `myUrlScheme://page=abc`. 

I want o achieve something same as https://www.reddit.com/

### Platform(s)
WEB
Android
IOS

### Preferred Solution
Not a Preferred Solution but might help.
https://ionicframework.com/docs/native/app-availability

### Alternatives
https://ionicframework.com/docs/native/app-availability
This plugin is for native platform. (Android / IOS). 

### Additional Context
https://ionicframework.com/docs/native/app-availability
Can we have a web version for this plugin to Achieve this feature.

**Comment by jcesarmobile** [comment]
there is no way of knowing if an app is installed or not without trying to open it
you can use workarounds like the mentioned here
https://stackoverflow.com/questions/13044805/how-can-i-check-if-an-app-is-installed-from-a-web-page-on-an-iphone
