### ISSUE TITLE
bug: Progressive Web App with Capacitor 3 and Ionic 5

### ISSUE THREAD

**Issue by GosuMania** [ionic-team/capacitor#5072]
Hi all, I have developed a progressive web app with Capacitor 3.2.3, there are several things that don’t work especially on IOS, including:

- Clipboard (^1.0.3) - not work only on IOS:

![Schermata 2021-09-23 alle 09 17 20](https://user-images.githubusercontent.com/63244629/134524553-e2ffa557-1927-47cb-a31f-10019cd5b530.png)

```
     Clipboard.write({string: this.deal.discountCodeSingle}).then(value => {
        console.log('Codice Sconto Copiato');
      });
```

- Dialog.confirm (^1.0.3) - not work on all devices, it’s not change button, and the title doesn’t appear:
```
        Dialog.confirm({
          title: 'SCARICA L\'APP',
          message: `Stai utilizzando la versione web dell'app di GosuMania, dove non sono disponibili tutte le funzionalità.<br>
          Se possiedi un dispositivo android scarica la nostra app oppure continua con questa.`,
          okButtonTitle: 'Scarica l\app',
          cancelButtonTitle: 'Continua'
        }).then((response) => {
          console.log('response SCARICA L\'APP: ', response.value);
          if(response !== null && response !== undefined && response.value) {
            window.open('https://play.google.com/store/apps/details?id=com.gosumania.app', '_blank')
          }
          this.ds.setStringToStorage('alertWebApp','true');
        });
```
Link of my APP : https://web-app.gosumania.it/ (I know it’s not responsive for desktop)

I have updated everything to the latest version because it is a new installation of both Ionic and the different plugins.

Many thanks in advance

**Comment by jcesarmobile** [comment]
Sadly not all the native features are available for web/PWA, that's why native platforms exist.

safari requires user interaction to copy to clipboard, which looks like you are already doing, but hard to tell without actually seeing your code
