### ISSUE TITLE
Help on iOS app

### ISSUE THREAD

**Issue by smelzer** [ionic-team/capacitor#508]
I am working on a capacitor app for iOS and I am running into some issues and have some general questions:

My goal is to have an app that has a few custom native UIViewControllers to handle some native things. The code I want to create is using OpenCV, which is C++ so right now all my custom code is Objective-C since Swift doesn't easily support C++ integration yet.

I have much of it working with Capacitor in general but now I am running into roadblocks due to my ignorance of how it all works in XCode.  I have the native code in the "App" project

```
App (Project)
   App (Group)
      MyUIViewController.mm (and .h)
      Main.storyboard

```
and the Capacitor stuff in the "Pods" project
```
Pods (Project)
   Development Pods (some kind of group but I am unfamiliar with the symbol)
      Capacitor (Group)
         Plugins (Group)
            MyCustomPlugin.swift (and .m for bridging)

```
MyCustomPlugin.swift has the following code:
```
@objc(MyCustomPlugin)
public class MyCustomPlugin: CAPPlugin {
    
    @objc func capture(_ call: CAPPluginCall) {
        let value = call.getString("value") ?? ""   // left in for testing
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let controller = storyboard.instantiateViewController(withIdentifier: "myUIViewController")
        DispatchQueue.main.async {
            self.bridge.viewController.present(controller, animated: true, completion: nil)
        }
        // left in for testing
        call.success([
            "value": value
        ])
    }
}
```

When I run this on my iPhone it all works.  I have a button in an Angular Component and when I click it I get my UIViewController view.  All the Objective-C code works and all the OpenCV magic also happens just fine.  BTW - This is COOL AS HELL and I really like Capacitor.

Now I need to real return data back to Angular after a user does something in MyUIViewController.  From my plugin (in the Pod project) I need to get a concrete handle to MyUIViewController (not just the Storyboard's UIViewController interface).  But the Pod project does not see MyUIViewController.  If I try to import it in the plugin class I get "No such module".  I though maybe it was a Swift/Objective-C thing but I tried a dummy Swift class in the App project and the plugin still could not see it.  I do not know how to share the UIViewControllers (and related classes) with the plugin.

I tried to copy the references of the classes I need from App to Pods in the same Plugin group as the MyCustomPlugin class and Xcode has no issue with the classes, but then Xcode complained about the OpenCV framework (which BTW I added to the Podfile with the 'App' target as the documentation recommends).  I am guessing I can get everything working by adding the OpenCV framework to the 'Pods' target, but it feels like I am doing something wrong.  So I want to reach out and find out the "correct" way to do this.

Thank you,
Steve

**Comment by mlynch** [comment]
Great issue and glad the native integration is working well!

The plugin is isolated to its own module, so unless you have dependencies in that plugin pointing to your custom native code, you won’t be able to access that code through static means. This is different from how Cordova worked where all plugin code wasn’t copied to your project, but that hasn’t other pitfalls.

However, you should be able to get that view controller dynamically using objective-c dynamism.

For example, try NSClassFromString to get MyUIViewController and instantiate it, probably can even replace the storyboard code with this: https://stackoverflow.com/a/32265287

Let me know how that goes! Closing as this is not a big but rather a conceptual question. Cheers

**Comment by jcesarmobile** [comment]
You shouldn't add your own code to the Capacitor pod. If you update @capacitor/ios all the changes you made will be deleted.
Instead of that, create your own Capacitor plugin (there is a command to help you with that `npx cap plugin:generate`)
Then you can put all your code/files there, including a storyboard or xib for the view controller and all classes should be accesible as they are all part of the plugin.

**Comment by smelzer** [comment]
I am not sure where to post general information.  If you have a general better place please let me know.  I'd like to keep you up to date on my findings as I go along.

The reason I put my Plugin class into Pods/Development Pods/Capacitor/Plugins in the first place was based on the EXCELLENT example written by Josh Morony at https://www.joshmorony.com/running-custom-native-ios-code-in-ionic-with-capacitor/.  I could not have gotten this far without him.  In his example though, he puts his plugin in this location.  So I decided to just move the plugin into App module and it worked just fine.  Now I am able to write all my code in App, and not have to worry about updates as jcesarmobile mentioned above.  I also didn't want to make this a separate plugin right now.

Once I got this working I ran into all kinds of issues which I wanted to relay and find out best practices.  Swift hates C++ as far as I can tell.  I spent a good 2 hours futzing with this problem.  I have a View Controller that has the C++ OpenCV framework referenced in it.  Swift just refused to deal with instantiating this View Controller.  I know there are workarounds mentioned on the web but instead I opted to just move my plugin code from Swift to Objective-C.

This caused an interesting catch-22.  As an Objective-C class, it was able to see the View Controllers with the references to OpenCV and the .mm extension (required to compile as C++ as they need to link with OpenCV), but the linker now failed as insisting the plugin class needed to be Objective-C++.  If you added .mm to the plugin, the #import <capacitor/capacitor-swift> would throw errors.  So I got different problems whether the plugin class was .m or .mm.  And I needed the import to get a handle to the bridge controller.

So I split out the code.  The plug-in is now regular objective-c and I have a "handler" class that is objective-c++.  The plugin gets the bridge controller and passes it off to the handler as a UIViewController.  Everything is happy again!

I don't know how many people are going to be using C++ in their plugins, but it is a PITA.

**Comment by seemaks** [comment]
Hi,

I have an ionic app created , have created ios folder successfully. But I want to change my app directly in native code. How to do that.
Please suggest
