### ISSUE TITLE
feat: Exclude plugin from platform build

### ISSUE THREAD

**Issue by davidecampello** [ionic-team/capacitor#5084]
### Description
Is it possible to exclude a plugin installed in noe_modules from capacitor platform build?
I have a situation where the ios pod throw some errors but I really need only a typescript file of this plugin.

### Platform(s)
ios / android

**Comment by jcesarmobile** [comment]
It's not possible to "exclude" one plugin, but you can specify the plugins to include, so you should add all the plugins except the ones you want to exclude in `includePlugins` object.

https://capacitorjs.com/docs/config
