### ISSUE TITLE
bug: Forms with an external action are posted to the  internal webview

### ISSUE THREAD

**Issue by giudicelli** [ionic-team/capacitor#5085]
### Capacitor 3.2.3
```
   Capacitor Doctor

Latest Dependencies:       

  @capacitor/cli: 3.2.4    
  @capacitor/core: 3.2.4   
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4    

Installed Dependencies:    

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/ios: 3.2.4
  @capacitor/android: 3.2.3        
```

### Platform(s)
Android

### Current Behavior
Forms with an external action to the app are posted to the  internal webview. No matter what the target is.

### Expected Behavior
We would expect the form to be posted either on an inApp browser or an system browser.

### Code Reproduction
```
<!-- https://lorem.ipsum is outside the URI scope of the app -->
<form action="https://lorem.ipsum" taget="_blank" method="post">
<input type="submit" value="send" />
</form>
```

### Other Technical Details
We're using VueJS 2.6.

`npm --version` output: 6.14.13

`node --version` output: v14.17.0

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
