### ISSUE TITLE
bug: ionic capacitor run returning error

### ISSUE THREAD

**Issue by kenchambers** [ionic-team/capacitor#5092]
## Bug Report

Greetings! when running:

`ionic capacitor run ios --livereload --external`

It fails to build, i get this message: 

```
 error: Provisioning profile "iOS Team Provisioning Profile: myappname" doesn't include the currently selected device "iPhone" (identifier 00008030-000304E10C90). (in target 'App' from project 'App')
```

I saw this thread saying that you must add:
https://developer.apple.com/forums/thread/668952
` -destination 'generic/platform=iOS`

to xcodebuild command line

But we don't have access to this when running the ionic capacitor run command.

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.2.0
  @capacitor/core: 3.1.2

[success] iOS looking great! 👌
```

### Platform(s)
```
Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir10,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	6723.120.36

```

### Current Behavior
when i run :
`ionic capacitor run ios --livereload --external`

### Expected Behavior

to build correctly

`npm --version` output:
`7.19.1`
`node --version` output:
`v16.3.0`
`pod --version` output (iOS issues only):
`1.11.0`

**Comment by jcesarmobile** [comment]
Does it work if you run from Xcode?
