### ISSUE TITLE
Run Capacitor project with cordova plugin in Web: cordova_not_available error

### ISSUE THREAD

**Issue by leocharrua** [ionic-team/capacitor#5097]
I have a Ionic 5 with Capacitor 3 project.

I need to use this plugin:

https://ionicframework.com/docs/native/barcode-scanner

This plugin is supposed compatible with Browser platform.

But when I run in browser:

         ionic build --prod
         http-server www

And the plugin is called, I get:

Native: tried calling BarcodeScanner.scan, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

How I can run a project with capacitor that includes cordova plugins (compatible) in the browser?

Thanks

**Comment by jcesarmobile** [comment]
cordova plugins are not supported on web platform at the moment

You can subscribe to
https://github.com/ionic-team/capacitor/issues/769
