### ISSUE TITLE
bug: cordova-plugin-intercom 10.2.0 fails to compile for Android with Capacitor 3

### ISSUE THREAD

**Issue by abesiemsen** [ionic-team/capacitor#5108]
## Bug Report

**Please note that while the steps to reproduce are identical to closed issue #5019, the fix implemented in #5019 does not actually result in a successful build, it just reveals a different error.**

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: unknown
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/core: 3.2.4

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

A blank Ionic project compiles correctly, until cordova-plugin-intercom is added. Then the build in Android Studio fails with error message noted below.

### Steps to reproduce:

Create a new Ionic project with `ionic start`, using the 'blank' app template.
Add the android platform: `ionic cap add android`.
Sync, `ionic cap sync`, open `ionic cap open android`, and build in Android Studio, it is successful.

Now, install cordova-plugin-intercom, per https://ionicframework.com/docs/native/intercom.
```
npm install cordova-plugin-intercom
npm install @ionic-native/intercom
ionic cap sync
```

Now in Android Studio, the build fails:
```
A problem occurred configuring project ':capacitor-cordova-android-plugins'.
> com.android.builder.errors.EvalIssueException: Library projects cannot set applicationId. applicationId is set to 'capacitor.android.plugins' in default config.
```

### Expected Behavior

I expect a successful build.

Granted, this is almost certainly an issue with cordova-plugin-intercom, but [this page](https://capacitorjs.com/docs/plugins/cordova) suggests letting you know when a cordova plugin is incompatible... so you're welcome? 😉

### Code Reproduction

https://github.com/abesiemsen/cordova-plugin-intercom-fails

### Other Technical Details

`npm --version` output: 6.14.15

`node --version` output: v14.18.0

`ionic info` output:
```
Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.2
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.2.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v14.18.0 (/usr/local/Cellar/node@14/14.18.0_1/bin/node)
   npm    : 6.14.15
   OS     : macOS Big Sur
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by abesiemsen** [comment]
Code reproduction added to original post, also here:
https://github.com/abesiemsen/cordova-plugin-intercom-fails

**Comment by abesiemsen** [comment]
@jcesarmobile, I was actually able to build successfully with your suggested modification. I'll see if I can get further with Intercom (my client is a paying customer) to initiate an official fix.

Thank you, I really appreciate your investigation and response!

**Comment by vokamut** [comment]
My fix: https://github.com/ionic-team/capacitor/issues/2511#issuecomment-1290020640
