### ISSUE TITLE
[IOS] Focusing an input crashes the app

### ISSUE THREAD

**Issue by theomathieubhvr** [ionic-team/capacitor#511]
Hi,

When focusing an input, I get EXC_BAD_ACCESS

![screen shot 2018-05-01 at 3 43 07 pm](https://user-images.githubusercontent.com/24896997/39490357-9ec39ae8-4d56-11e8-948a-b7fd073c183d.png)

### Behaviours

Works on the simulator, crash on iphone SE and 5S.

### Steps to reproduce

1) Create an app using angular cli
2) Add an input in the app component
3) [Add capacitor ios](https://capacitor.ionicframework.com/docs/ios/)
4) Run the app
5) Tap the input

### Environment

Capacitor : 1.0.0-alpha.36
Iphone 5S : 10.1.1
Iphone SE : 11.2.2

Thanks !

**Comment by jcesarmobile** [comment]
Do you see something on the console?
Are you using some custom keyboard?

**Comment by theomathieubhvr** [comment]
Hi,

Does anyone else get this major bug ?

**Comment by jcesarmobile** [comment]
You mean an input like this?

'<input [(ngModel)]="title" placeholder="title">`

I've tried in two devices, iPad 4 with iOS 10.3.3 and iPhone X with iOS 11.2.6 and couldn't reproduce on any of them.

**Comment by theomathieubhvr** [comment]
I am only adding an `<input type="text">`

https://github.com/theomathieubhvr/test-capacitor

**Comment by theomathieubhvr** [comment]
Thanks !

**Comment by mlynch** [comment]
Ah good catch. I could see that method being problemstic

**Comment by theomathieubhvr** [comment]
@jinleime thanks !

You fix works.
