### ISSUE TITLE
bug: capacitor/geolocation added 32 vulnerabilities (20 moderate, 12 high)

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/capacitor#5111]
_Doctor_
```
Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/ios: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.1.2

[success] Android looking great!
```

_package.json_

{
  "name": "mobile",
  "version": "0.0.1",
  "author": "Networks",
  "homepage": "Networks",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/cdk": "^12.2.1",
    "@angular/common": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/fire": "^6.1.5",
    "@angular/forms": "~12.1.1",
    "@angular/google-maps": "^12.2.5",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@capacitor/android": "^3.1.2",
    "@capacitor/browser": "^1.0.2",
    "@capacitor/core": "^3.2.0",
    "@capacitor/device": "^1.0.2",
    "@capacitor/geolocation": "^1.1.0",
    "@capacitor/haptics": "^1.0.2",
    "@capacitor/ios": "^3.2.0",
    "@capacitor/keyboard": "^1.0.2",
    "@capacitor/local-notifications": "^1.0.5",
    "@capacitor/push-notifications": "^1.0.3",
    "@capacitor/splash-screen": "^1.1.1",
    "@capacitor/status-bar": "^1.0.2",
    "@capacitor/storage": "^1.0.3",
    "@ionic-native/call-number": "^5.35.0",
    "@ionic-native/core": "^5.35.0",
    "@ionic-native/in-app-browser": "^5.36.0",
    "@ionic-native/open-native-settings": "^5.36.0",
    "@ionic-native/screen-orientation": "^5.35.0",
    "@ionic-native/social-sharing": "^5.35.0",
    "@ionic/angular": "^5.5.2",
    "@types/lodash": "^4.14.172",
    "call-number": "^1.0.1",
    "chart.js": "^2.9.4",
    "cordova-open-native-settings": "^1.5.5",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-x-socialsharing": "^6.0.3",
    "dayjs": "^1.10.6",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^8.9.0",
    "lodash": "^4.17.21",
    "ng2-charts": "^2.2.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.1200.5",
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@angular/language-service": "~12.0.1",
    "@capacitor/cli": "3.1.2",
    "@ionic/angular-toolkit": "^4.0.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "prettier": "^2.3.2",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  },
  "description": "Networks"
}

_Bug/Issue_

```
+ @capacitor/geolocation@1.1.0
added 1 package from 1 contributor, removed 1 package and audited 1612 packages in 47.909s

130 packages are looking for funding
  run `npm fund` for details

found 32 vulnerabilities (20 moderate, 12 high)
```
When I run `npm audit fix`

```
fixed 11 of 32 vulnerabilities in 1612 scanned packages
  21 vulnerabilities required manual review and could not be updated
```

**Comment by jcesarmobile** [comment]
Sorry, but this is not true, the plugin doesn't add any vulnerabilities, every time you run `npm install` it tells you all the vulnerabilities your project have, but all those were there before you installed @capacitor/geolocation@1.1.0.
Run `npm audit` and it will tell you where the vulnerabilities come from.
