### ISSUE TITLE
Common repository for plugins

### ISSUE THREAD

**Issue by speedfl** [ionic-team/capacitor#512]
Hello.

I don't know if it is on your road map but it could be nice to have a unique repository for the plug-ins. 
In fact a big issue we have with Cordova is the compatibility between plug-ins. 
Cordova version, Cordova ios and android versions, pods, jars etc etc...
À unique plug-in repository gives the possibility to have plug-ins which can work all together. Then for build on pr. A Jenkins job could try to integrate all the plug-ins on both platforms and check if both platforms build

Anyway thanks for your work!!

**Comment by mubasshir** [comment]
+1

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.
