### ISSUE TITLE
feat: support .ejs files to build for Android

### ISSUE THREAD

**Issue by bachonk** [ionic-team/capacitor#5128]
### Description
I have an `index.ejs` at the root of my build directory, but Capacitor seems to require an `index.html` file.

When running `npx cap add android`, I receive the following error:
```
✖ copy android - failed!
[error] The web assets directory (./www) must contain an index.html file.
        It will be the entry point for the web portion of the Capacitor app.
```

### Platform(s)
Android

### Preferred Solution
Index.html or Index.ejs should be supported

### Alternatives
Open to other ways to get this to work!

**Comment by mlynch** [comment]
Hey @bachonk, you'll want to transform that `.ejs` file to raw html before loading it, as part of a build step. Capacitor does not and will not handle non-standard template files, but that's okay you just need to build your app as part of an `npm run build` process or the like.
