### ISSUE TITLE
Should there be a "Why" section in the README?

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/capacitor#514]
For those of us that have caught glimpses of the headlines relating to capacitor it may be difficult to understand why Ionic has made the decision to build a replacement for cordova.  Maybe there was a blog post or a tweet or a conversation in slack -- wherever that happened it's not apparent from the README of this repo.  Given that this is a (seemingly) monumental change for those of us with production cordova/ionic apps it would be very helpful to understand why this change is happening.

Thanks!

**Comment by mlynch** [comment]
We will have more info soon, thanks.
