### ISSUE TITLE
bug: Capacitor 3 breaks ES5 compatibility (Android)

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [ionic-team/capacitor#5141]
### Capacitor Version

```
~/es5Tester master !3 ?1 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
❯ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5

[success] Android looking great! 👌

```

### Platform(s)

Android API 24

### Current Behavior

I have a capacitor app that needs to support Android 7.  Therefore I target ES5. Capacitor 3 includes code that is not ES5-compatible, causing SyntaxError in this line: https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/assets/native-bridge.js#L45

### Expected Behavior

Capacitor 3 should emit ES5-compatible code.

### Code Reproduction

1. Create emulator with API 24 in Android Studio
1. `ionic start es5Tester tabs --capacitor`
1. select angular
1. `cd es5Tester`
1. `ionic capacitor add android`
1. set `"target": "es5"` in `tsconfig.json`
1. `ionic cap sync android`
1. `ionic cap open android`
1. Run app in emulator
1. Inspect with chrome --> SyntaxError

### Other Technical Details

```
~/es5Tester master !3 ?1 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 27s
❯ npm --version
6.14.15

~/es5Tester master !3 ?1 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
❯ node --version
v14.17.6
```

**Comment by jcesarmobile** [comment]
Capacitor requires chrome/chromium/system webview >= 60.
Emulators can't be updated, but real devices can. Capacitor supports Android 5+ as long as they have the webview up to date.
