### ISSUE TITLE
bug: Live reload not working with https server.url

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/capacitor#5149]
### Capacitor Version

```
3.2.5
```

### Platform(s)
Android
iOS

### Current Behavior
- Android (and iOS) doesn't show my app url in wkwebview. 
- I just have a little <body> in the html
- No errors, when i just try to reach my app network url (`https://192.168.1.11:3000`) it show me that the request is "canceled"
![image](https://user-images.githubusercontent.com/25119847/137650525-0aef57f3-bf2b-4223-9c42-05c8490ecd1b.png)
![image](https://user-images.githubusercontent.com/25119847/137650557-59a75371-ec56-4c95-940b-54e17edcbab3.png)

### Code

`$ npx cap run android -l --host=0.0.0.0 --address=0.0.0.0 --consolelogs --external --ssl`

```JS
{
  appId: 'XXXX',
  appName: 'XXX',
  backgroundColor: '#ffffff',
  bundledWebRuntime: false,
  plugins: {
    Keyboard: { resize: 'native', style: 'dark' },
    SplashScreen: { launchShowDuration: 500 }
  },
  server: {
    cleartext: true,
    url: 'https://192.168.1.11:3000',
    hostname: '192.168.1.11:3000',
    androidScheme: 'https',
    iosScheme: 'https',
    allowNavigation: [
      '*',
    ]
  },
  webDir: './dist'
}
```
![image](https://user-images.githubusercontent.com/25119847/137650672-6ea29299-95fc-4fac-8d09-c09fbe615935.png)

### Expected Behavior
Live reload should work well with https

### Other Technical Details
Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true

**Comment by Aarbel** [comment]
These issues didn't solved my problem:
- https://github.com/ionic-team/capacitor/discussions/3672
- https://github.com/ionic-team/capacitor/issues/1809

**Comment by Aarbel** [comment]
@jcesarmobile i'm using https://www.npmjs.com/package/vite-plugin-mkcert to generate a local dev certificate.

Which solution would you suggest to have a valid certificate under dev ?

**Comment by lotestudio** [comment]
You must find the certificate generated from mkcert in your keychain and install it on your device (ipad, iphone). After that go to Settings>General>About. Enable full trust for the certificate you installed and live reload will work!

**Comment by Aarbel** [comment]
Thanks a lot @lotestudio do you have an example ?
