### ISSUE TITLE
feat: Possibility to override/change access origin

### ISSUE THREAD

**Issue by lmsmanish** [ionic-team/capacitor#5152]
### Description
When we add/sync a android or iOS platform. Automatically access origin='*' is added to the config.xml. There is not way to override/change this value.

### Platform(s)
capacitor:android, capacitor:ios

### Preferred Solution
We can have these as part of capacitor.config.ts then it will be easy to have configurations related to whitelisting of urls.

### Additional Context
We can find it in autoGernerateConfig of cordova.js
![Access Origin](https://user-images.githubusercontent.com/89903992/137696257-842a1432-56ca-474b-a7f7-7b68fe23aa18.png)

**Comment by jcesarmobile** [comment]
Can you elaborate on why do you need this?

The access tag is not really used in Capacitor WebView, Capacitor allows to connect anywhere, if you want to restrict the connections you can use a [CSP](https://developer.mozilla.org/es/docs/Web/HTTP/CSP).

**Comment by lmsmanish** [comment]
@jcesarmobile 

I saw your pull request(https://github.com/ionic-team/capacitor/pull/1206) for resolving the one of issue with file plugin. I also checked that the file transfer plugin is no longer using the whitelist configurations. 

I think we can remove this access origin='*' from the autoConfig method now.
