### ISSUE TITLE
bug: Live Reload not working on Android with Auth0 https login

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/capacitor#5153]
### Capacitor Version
```
3.2.5
```

### Platform(s)
Android

### Current Behavior
- Everything works well on iOS (wkwebview doesn't block https on http)
- Everything works well with live reload (http://192.168.1.11:3000 is well fetched), but Auth0 is blocked by http:// of Capacitor
`auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.`

![image](https://user-images.githubusercontent.com/25119847/137714705-2295dac1-c107-4eeb-bd87-2b15c87433b3.png)
![image](https://user-images.githubusercontent.com/25119847/137717711-601efb17-bd8e-4d56-9b40-08b3756f15b4.png)

### Expected Behavior
Opening my url `http://192.168.1.11:3000`

### Code Reproduction

`npx cap copy android && npx cap run android`

```JS
{
  appId: 'XXXXX',
  appName: 'XXXXXX',
  backgroundColor: '#ffffff',
  bundledWebRuntime: false,
  plugins: {
    Keyboard: { resize: 'native', style: 'dark' },
    SplashScreen: { launchShowDuration: 500 }
  },
  ios: { path: './.capacitor/platforms/ios' },
  android: { path: './.capacitor/platforms/android' },
  server: {
    cleartext: true,
    url: 'http://192.168.1.11:3000',
    allowNavigation: [
      '*',
    ]
  },
  webDir: './dist'
}

```

### Other Technical Details

Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true

### Additional doc
Cf 
- https://github.com/ionic-team/capacitor/issues/5149
- https://auth0.com/docs/quickstart/native/ionic-angular/01-login
- https://forum.ionicframework.com/t/capacitor-3-run-livereload-with-with-ssl/210477/2

**Comment by RobSchilderr** [comment]
How did you solve this @Aarbel?
