### ISSUE TITLE
bug: Error message thrown when user cancels taking picture

### ISSUE THREAD

**Issue by beruic** [ionic-team/capacitor#5166]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/electron: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.5.0
  @capacitor/core 2.5.0
  @capacitor/android 2.5.0
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

An error is sent at the console every time a user cancels taking a picture initiated by `Capacitor.Plugins.Camera.getPhoto()`.

### Expected Behavior

I'd expect the error to be sent as a rejection to the resulting promise by `Capacitor.Plugins.Camera.getPhoto()`.

### Code Reproduction

As stated below by @GabySotirova: https://github.com/GabySotirova/capacitor-error-message
The steps for reproducing it are in the README.md file.

### Other Technical Details

`npm --version` output: 6.14.15

`node --version` output: v14.18.1

`pod --version` output (iOS issues only):

### Additional Context

The main issue of this from our perspective where I work, is that the console gets an error, which is caught by error reporting frameworks (Sentry in our case), and with many users canceling, we get spammed. It would be nice to at least be able to control the level with an option.

Also, without a promise rejection it is difficult to react when a picture not taken.

**Comment by Teo27** [comment]
@jcesarmobile I am sorry for the necro, but I am not sure why this is closed. This is still an issue with Capacitor 3.

Yes, you can detect and catch the error inside a try-catch and even then-catch. However, a console error is still triggered internally. This means that if you use an error tracking software like Sentry as OP stated, said error would be caught even if gracefully handled.
