### ISSUE TITLE
bug: white screen for 2 seconds on app open. On IOS only happens in light mode.

### ISSUE THREAD

**Issue by DaanOolbekkink** [ionic-team/capacitor#5185]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/ios: 3.2.5

### Platform(s)
IOS, Andoird

### Current Behavior
When the app opens and a IOS device is in light mode, a white screen is shown for 1-2 seconds. When the app opens and an Android device is in light or dark mode, a white screen is shown for 1-2 seconds. 

I am trying to always force the app to use dark mode, so a flashing white screen is not preferable.

### Expected Behavior
On Android I think it should at least work as IOS, a white screen on light mode and a dark screen on dark mode.
Preferable I would like a dark screen on both devices in both modes.

### Code Reproduction
1. clone from https://github.com/DaanOolbekkink/ionic-test
2. build the app for ios: `ionic cap build ios` or android: `ionic cap build android`
3. from xcode or android studio run/debug the app on a device (haven't tested on a simulator) and when the app loads a white screen appears before the content appears.
4. Change the color mode in the device (not in the app), in android the white screen appears in light and dark mode. in ios the white screen appears only in light mode.
5. rerun the app

### Other Technical Details

`npm --version` output: 7.24.0

`node --version` output: v16.7.0

`pod --version` output (iOS issues only): 1.10.1

**Comment by jcesarmobile** [comment]
Thanks for the sample app, I've noticed that you are not using @capacitor/splash-screen.
I think what happens in your app is that angular takes those seconds to load and while it loads the WebView is empty, so the screen is white.
Try installing @capacitor/splash-screen and configure it following this to Hide when Angular is ready:
https://capacitorjs.com/docs/apis/splash-screen#hiding-the-splash-screen

**Comment by DaanOolbekkink** [comment]
Okay, so the problem is resolved. I had used the @ionic-native/splash-screen, https://ionicframework.com/docs/native/splash-screen. But for some reason this does not work. Using the plugin @capacitor/splash-screen fixed my problem by adding 
```plugins: {
    SplashScreen: {
      launchShowDuration: 3000,
      launchAutoHide: true,
      backgroundColor: "#000000",
      androidSplashResourceName: "splash",
      androidScaleType: "CENTER_CROP",
      showSpinner: false,
      androidSpinnerStyle: "large",
      iosSpinnerStyle: "small",
      spinnerColor: "#000000",
      splashFullScreen: true,
      splashImmersive: true,
      layoutName: "launch_screen",
      useDialog: true,
    },
  },```
 to the `capacitor.config.ts`.

Thank you so much @jcesarmobile !
