### ISSUE TITLE
feat: Disable analytics

### ISSUE THREAD

**Issue by saschpe** [ionic-team/capacitor#5191]
## Feature Request

Disable metrics collection (analytics) by third parties by default.

### Description

Certain components track build time dependency resolution and other metrics by default. This should be opt-in per the GDPR in Europe and is generally unwanted as it might expose confidential information in proprietary projects. Finally, metrics collection implies additional network requests that might have an effect on built time.

### Platform(s)
Android and iOS.

#### CocoaPods
CocoaPods analytics sends network stats synchronously affecting build latency. Thus, the following should be added to each `Podfile`:

```ruby
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
```

#### Android Testing

The following should be part of every `build.gradle` file:

```groovy
    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments disableAnalytics: "true"
    }
```

Quoting the testing library source code: 

        The Android Testing Support Library collects analytics to continuously improve the testing
        experience. More specifically, it uploads a hash of the package name of the application
        under test for each invocation. If you do not wish to upload this data, you can opt-out by
        passing the following argument to the test runner: disableAnalytics "true".

### Alternatives
Have a config flag to allow opt-in into metrics collection in case a user wants to support

**Comment by thomasvidas** [comment]
Copying my response for the PR for more visibility...

> Changing the analytics defaults of the projects is something that we're not going to do since its modifying the environment of a tool we don't control. Based on your PR, its easy to opt out of and I'm not opposed to adding a snippet in the Capacitor docs on how to opt out of analytics for third party tooling. If this is actually a GDPR or CCPA problem, then you should open issues with the upstream tools of [Cocoapods](https://github.com/cocoapods/cocoapods) and [Gradle](https://github.com/gradle/gradle) and not Capacitor.
