### ISSUE TITLE
bug: @capacitor/filesystem Unable to save file

### ISSUE THREAD

**Issue by elvisgraho** [ionic-team/capacitor#5206]
### Capacitor Version
```json
    "@capacitor/android": "^3.3.0",
    "@capacitor/camera": "^1.2.0",
    "@capacitor/cli": "^3.3.0",
    "@capacitor/core": "^3.3.0",
    "@capacitor/filesystem": "^1.0.6",
    "@capacitor/ios": "^3.3.0",
```

### Platform(s)
iOS

### Current Behavior
Cant create new .png File from Canvas blob.

```ts
      const canvas = document.getElementsByTagName('canvas');
      canvas[0].toBlob(myStoreFunction, 'image/png', 1);
  ```

```ts
    await Filesystem.writeFile({
      directory: Directory.Data,
      path: `test.png`,
      data: `${blob}`, // or just blob
    }
```

I get - 'Error: Unable to save file' or if it is not a string Error: Data must be provided and must be a string.

I tried encoding: Encoding.UTF8, but then it is not an image anymore

### Expected Behavior
With '@ionic-native/file/ngx' i had no issues
```ts
 await this.file.writeFile(pathToFile, 'test.png', blob);
 ```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by elvisgraho** [comment]
Seems to be a missing functionality? Wrote a feature request.
