### ISSUE TITLE
feat: @capacitor/filesystem support Blob type for writing

### ISSUE THREAD

**Issue by elvisgraho** [ionic-team/capacitor#5207]
### Description
'@ionic-native/file/ngx' allows me to write BLOB into a file. @capacitor/filesystem seems to only allow string to be written.
Please add ability to write BLOB into a file.

### Additional Context
I wrote an [Issue](https://github.com/ionic-team/capacitor/issues/5206) where I encountered the problem.

**Comment by Ionitron** [comment]
Issue detected as duplicate of https://github.com/ionic-team/capacitor/issues/984
