### ISSUE TITLE
bug: googleanalytic - The 'Pods-App' target has transitive dependencies that include

### ISSUE THREAD

**Issue by cyril-colin** [ionic-team/capacitor#5219]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.1
  @capacitor/core: 3.3.1
  @capacitor/android: 3.3.1
  @capacitor/ios: 3.3.1

Installed Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.3.1
  @capacitor/android: 3.3.1
  @capacitor/ios: 3.3.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)
ios

### Current Behavior
The command `npx cap sync ios` failed with error:
```
[!] The 'Pods-App' target has transitive dependencies that include statically linked binaries: (/Users/user/repo/ios/App/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a and /Users/user/repo/ios/App/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a)
``` 

### Expected Behavior
The command should build as usual.

### Other Technical Details
- This error occurs since capacitor/cli@3.2.5
- This is related to the cordova plugin: `cordova-plugin-google-analytics` version 1.9.0

### Additional Context
This issue https://github.com/ionic-team/capacitor/issues/5158#issuecomment-948369681 tells that we have to make request to get our plugin working again. So I do it 😄 

Thanks for reading !

**Comment by jcesarmobile** [comment]
I've added the plugin to the list, but FYI, since capacitor 3.3.0 you can add any cordova plugin to the static list by adding it to the capacitor config file inside the cordova object https://github.com/ionic-team/capacitor/pull/5175

**Comment by media4learning** [comment]
> I've added the plugin to the list, but FYI, since capacitor 3.3.0 you can add any cordova plugin to the static list by adding it to the capacitor config file inside the cordova object #5175

Hi jcesarmobile. Is there documentation for this? I added a "staticPlugins" array woth "cordova-plugin-google-analytics" to the "cordova" object in capacitor.config.json and I get the same error. This is with @capacitor/core 3.3.1.

**Comment by jcesarmobile** [comment]
It should be inside cordova object
https://capacitorjs.com/docs/config
