### ISSUE TITLE
activity needs android:exported value when targeting SDK 31

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#5237]
### Capacitor Version
4

### Platform(s)
android

### Current Behavior
android template doesn't have a value for android:exported and it's required if targeting SDK 31

### Expected Behavior
we should update the template to make the MainActivity entry to include `android:exported="true"`

**Comment by beruic** [comment]
Will this be backported to Capacitor 2 and 3?

**Comment by jcesarmobile** [comment]
no, but this is the starting template, any user that wants to target SDK 31 can just do this on their own app, for users migrating from 3 to 4 will be documented on the upgrade guide

**Comment by productdevbook** [comment]
some problem Capacitor 3

**Comment by piotr-cz** [comment]
@jcesarmobile
In that case Capacitor 3 docs should be upgraded to clarify that SDK 31+ target isn't supported

**Comment by jcesarmobile** [comment]
this has been addressed [here](https://github.com/ionic-team/capacitor/pull/5351) and available on capacitor 4.0.0 beta 0
