### ISSUE TITLE
bug:  addListener never fired

### ISSUE THREAD

**Issue by riderx** [ionic-team/capacitor#5248]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
-ios

### Current Behavior
on web this event work but it's never fired on mobile
```
  App.addListener('appStateChange', async(state) => {
    console.log('App state changed. Is active?', state.isActive)
  })
```

### Expected Behavior
should fire when leave the app and come back

`npm --version` output: 6.14.15

`node --version` output: v14.18.1

`pod --version` output (iOS issues only): 1.11.2

**Comment by Christophe-re** [comment]
Hello @riderx 

I see you closed this issue the same day as you opened it.. it's because you found the solution ? 
I've got the same behavior on my app and I don't understand what I'm doing wrong..

**Comment by riderx** [comment]
@Christophe-re yes i found it, but i don't remember, i should have wrote it. maybe forgot to install the module?
