### ISSUE TITLE
feat: add productFlavor support to --livereload --external

### ISSUE THREAD

**Issue by sandor-biro** [ionic-team/capacitor#5252]
### Description
Currently `assembleDebug` is hardcoded so there's no possibility to `--livereload --external` a given `productFlavor`.

```
productFlavors {
        versionA {
            applicationId "com.company.versionA"
        }

        versionB {
            applicationId "com.company.versionB"
        }

        versionC {
            applicationId "com.company.versionC"
        }
    }
```

### Platform(s)
Android

### Preferred Solution
Change the hardcoded `const gradleArgs = ['assembleDebug'];` (https://github.com/ionic-team/capacitor/blob/main/cli/src/android/run.ts#L22)

to a dynamic one, so various `productFlavors` can be generated correctly when using `--livereload --external` build args.

App should generate `gradleArgs` based on the given productFlavor i.e. `assembleVersionADebug` etc.

```
const arg = `assemble${flavour}Debug`;
const gradleArgs=[arg];
```

### Alternatives
... remove extra product flavours from `build.gradle` while working, then remember copy them back.

### Additional Context
I'm happy to submit a PR for this.

Something similar was reported here also: https://github.com/ionic-team/capacitor/issues/5104

**Comment by jcesarmobile** [comment]
assembleDebug is supposed to build a debug apk for all the configured flavors, isn’t it working? Maybe you have some setting that prevents it from working?

**Comment by sandor-biro** [comment]
I understand all flavors are supposed to be built at every save. Is this what you meant?

My question is: what if there are more than 10 flavors? All of them will (i.e. should) be built into the .apk at every save?

**Comment by jcesarmobile** [comment]
No at every save, as you are using live reload the native app is not rebuilt on every save, just the web part and it reloads the WebView without rebuilding the native part.

**Comment by adrianpunkt** [comment]
Our use case here is to build one flavor at a time since we do some additional configuration for that flavor. The build process fails since it cannot build all of them at the same time. Since the `capacitor.config.ts` includes one flavor, it would make sense to build only one, hence the need to call `assembleFlavorDebug` instead of `assembleDebug` which builds all:

```
const config: CapacitorConfig = {
 ...
  },
  ios: {
    scheme: 'XCODE_SCHEME',
  },
  android: {
    flavor: 'ANDROID_FLAVOR'
  }
};
```

**Comment by adrianpunkt** [comment]
For livereload, it also doesn't make sense to build multiple flavors at once.

**Comment by carlpoole** [comment]
Would it make sense to just build the flavor specified in the config, such that the control of what gets built is dictated by the config, or is there a benefit to also making it configurable in the live reload command?

**Comment by adrianpunkt** [comment]
I think using what's in config is a good start. Adding that to the livereload is also a nice feature.

For example we have a gulp task that will update the `capacitor.config.ts` before the livereload command, and having a param would improve the process and not require a gulp task for this.

**Comment by jcesarmobile** [comment]
`--livereload` is an option on ionic CLI, so should be done/requested [there](https://github.com/ionic-team/ionic-cli/issues)

**Comment by jcesarmobile** [comment]
closing since the linked PR is merged
