### ISSUE TITLE
Custom plugin is not being called for Android platform

### ISSUE THREAD

**Issue by dchappelle** [ionic-team/capacitor#5254]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/electron: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli 2.5.0
  @capacitor/ios 2.5.0
  @capacitor/core 2.5.0
  @capacitor/android 2.5.0
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    call-svc-plugin (0.0.1)
[success] iOS looking great! 👌
```

### Platform(s)
Android

### Current Behavior
I have created a CallSvcPlugin as described in [creating-plugins](https://capacitorjs.com/docs/v2/plugins/creating-plugins) that only has the echo functionality at this point. When I go to test the plugin,  the iOS implementation is called when executed on an iOS device as expected. However the Android implementation is never called; instead the web implementation is being called. I am importing the plugin as follows...
```
import { Plugins } from '@capacitor/core';
const { CallSvcPlugin } = Plugins;

const reply1 = await CallSvcPlugin.echo({ value: 'You should not see this!' });
console.log(`[capacitor]: echo: ${reply1.value}`);
```
The plugin executed should just return "Hi from web!", "Hi from iOS!", or "Hi from Android!" depending on the platform used for test purposes.

### Expected Behavior
Android custom plugin should be called. Device.getInfo() should return "android" when executed on Android device.

### Code Reproduction
The code I'm testing is the same that was generated following [creating-plugins](https://capacitorjs.com/docs/v2/plugins/creating-plugins)

### Other Technical Details
`npm --version` output: 6.14.15

`node --version` output: v14.17.6

`pod --version` output (iOS issues only): 1.9.2

### Additional Context
1) I noticed that Device.getInfo().platform always returns "web" instead of expected "android" result
2) I noticed the `npx cap doctor` command results above show "Found 1 Capacitor plugin for ios" but not for Android. Although I see the following for` npx cap sync`...
```
✔ Copying web assets from www to android/app/src/main/assets/public in 8.25ms
✔ Copying native bridge in 1.11ms
✔ Copying capacitor.config.json in 1.12ms
✔ copy in 22.77ms
✔ Updating Android plugins in 941.74μp
  Found 1 Capacitor plugin for android:
    call-svc-plugin (0.0.1)
✔ update android in 38.17ms
✔ Copying web assets from www to ios/App/public in 2.91ms
✔ Copying native bridge in 988.84μp
✔ Copying capacitor.config.json in 1.67ms
✔ copy in 9.65ms
✔ Updating iOS plugins in 2.31ms
  Found 1 Capacitor plugin for ios:
    call-svc-plugin (0.0.1)
✔ Updating iOS native dependencies with "pod install" (may take several minutes) in 4.44s
✔ update ios in 4.46s
✔ copy in 255.52μp
✔ update web in 4.48μp
Sync finished in 4.537s
```
3) I am calling EnableHttpsSelfSigned.enable(this.bridge); in my MainActivity.java as shown [here](https://github.com/ionic-team/capacitor/issues/2751#issuecomment-612857772)

4) Output from Platform plugin...
Platform.is.android: true
Platform.is.capacitor: undefined
Platform.is.chrome: true

**Comment by jcesarmobile** [comment]
> * I am calling EnableHttpsSelfSigned.enable(this.bridge); in my MainActivity.java as shown [here](https://github.com/ionic-team/capacitor/issues/2751#issuecomment-612857772)


Hello.
Why are you doing that? The problem is related to that, the bridge is not being injected and the platform is being detected as web, all android plugins will use the web version because of that.

**Comment by dchappelle** [comment]
> Why are you doing that?
Thanks for your feedback! I'm doing that because my test system is running locally using https. I'm confused.. according to #2751, I thought using the _bridge_ version for this method (instead of _R.id.webview_) was the correct way to handle this.

How can I test Android on my local host using https?

**Comment by jcesarmobile** [comment]
Not sure what quasar team did with their local server, but as far as I remember that change was enough for them to work, but when I've tried with my own local server that uses a self signed certificate, that change allowed the navigation, but as the certificate was not trusted the bridge was not able to inject itself, and if the bridge is not injected the android plugins use the web version.
One thing that I think that works is to install on the device the certificate you are using for the server that way it trust the connections and the bridge gets injected.
Another way is to totally ignore SSL errors, even on native connections, which is not recommended https://github.com/ionic-team/capacitor/issues/3707#issuecomment-718965440

**Comment by dchappelle** [comment]
I should add that I am using Quasar as well. Unfortunately, the self signed certificate is not working for me nor is the solution in [#3707 (comment)](https://github.com/ionic-team/capacitor/issues/3707#issuecomment-718965440). With each I get 
`https://github.com/ionic-team/capacitor/issues/3707#issuecomment-718965440`
and the page doesn't load :/

**Comment by dchappelle** [comment]
Using both [#3707 (comment)](https://github.com/ionic-team/capacitor/issues/3707#issuecomment-718965440) and this [stackoverflow answer](https://stackoverflow.com/a/62602396/420008) I was able to get it to work. I would think there has to be an easier way for test purposes?

**Comment by dchappelle** [comment]
> Using both #3707 (comment) and this stackoverflow answer I was able to get it to work.

@jcesarmobile I'm trying to move to Capacitor v3 now. Android is running ok with the above changes but iOS now has the invalid certificate error in v3...

_2021-12-02 17:30:02.763236-0500 App[4293:847602] [Process] 0x10383e018 - [pageProxyID=5, webPageID=6, PID=4294] WebPageProxy::didFailProvisionalLoadForFrame: frameID=3, domain=NSURLErrorDomain, code=-1202
⚡️  WebView failed provisional navigation
⚡️  Error: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.1.247” which could put your confidential information at risk._

I implemented the iOS version of the [stackoverflow answer](https://stackoverflow.com/a/57811110/420008) but it still won't work. Do you know if there is an iOS version of [#3707 (comment) ](https://github.com/ionic-team/capacitor/issues/3707#issuecomment-718965440)?

**Comment by dchappelle** [comment]
To use a self signed certificate in Capacitor v3 with iOS I had to override the following WKNavigationDelegate method for dev purposes (Pods --> DevelopmentPods --> Capacitor --> WebViewDelegationHandler.swift)

```
    public func webView(_ webView: WKWebView, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        guard let serverTrust = challenge.protectionSpace.serverTrust else { return completionHandler(.useCredential, nil) }
        let exceptions = SecTrustCopyExceptions(serverTrust)
        SecTrustSetExceptions(serverTrust, exceptions)
        completionHandler(.useCredential, URLCredential(trust: serverTrust))
    }

```

**Comment by jcesarmobile** [comment]
Disabling SSL checks is a security vulnerability that leads to app rejections just for being there (even if not used in production), so code to do that won't be part of Capacitor.

I've created a [Capacitor plugin](https://github.com/jcesarmobile/ssl-skip) that disables ssl checks on both iOS and Android.
Notice that it's a personal plugin (@jcesarmobile/ssl-skip), not official from Ionic Team.

For tooling that provides dev servers with self signed certificates such as quasar, they should handle the SSL errors themselves, as they did for Capacitor 2, they can install/uninstall the plugin or use a similar code directly put into users projects.
