### ISSUE TITLE
bug: Capacitor silently crashes if no Android WebView is available

### ISSUE THREAD

**Issue by grigorig** [ionic-team/capacitor#5257]
### Platform(s)
Android

### Current Behavior
If no WebView implementation is available on Android, Capacitor silently crashes on app startup. You can test this by disabling WebView "apps" in Android settings. Not all phones allow you to disable the Android System WebView, though.

### Expected Behavior
Capacitor should display a warning of some sort that advises affected users what's wrong.

**Comment by jase88** [comment]
Ideally the user gets a hint what he/she needs to do to fix this.

Is this catchable on native side or is a change to the framework itself mandatory?

**Comment by sarahnx** [comment]
Any update on this issue?

**Comment by opindia123** [comment]
Any update on this.

**Comment by alex-steinberg** [comment]
The whole "do something async before Capacitor launches the webview" seems a useful feature, and might help with [this bug](https://github.com/ionic-team/capacitor/issues/6974).
