### ISSUE TITLE
bug: Android theme settings get overridden

### ISSUE THREAD

**Issue by NePheus** [ionic-team/capacitor#5258]
### Capacitor Version
3.1.2

### Platform(s)
Android

### Current Behavior
Theme settings in the styles.xml get overriden. i.e.
```
<item name="android:windowTranslucentStatus">true</item>
<item name="android:windowTranslucentNavigation">true</item>
```
are not working, maybe because they are 'resetted' anywhere programmatically? In capacitor 3.1.1 it works fine and after updating to 3.1.2 this settings are not working anymore. Maybe depending to https://github.com/ionic-team/capacitor/pull/4841?

### Expected Behavior
Custom theme settings in styles.xml should be working.

**Comment by jcesarmobile** [comment]
can you provide a sample app where the issue can be reproduced?

**Comment by NePheus** [comment]
Basically you can take any capacitor sample app and just add the lines from my first ticket:
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="AppTheme.NoActionBarLaunch" parent="Theme.AppCompat.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowTranslucentStatus">true</item> <!-- <- add this line -->
        <item name="android:windowTranslucentNavigation">true</item> <!-- <- add this line -->
        <item name="android:background">@drawable/splashscreen</item>
        <item name="android:navigationBarColor">@color/bg</item>
    </style>
</resources>
```

And when you run it on Android with capacitor <= 3.1.1 everything works fine and you see that the system status und navigation bar are transparent. When updating to capacitor >= 3.1.2 the settings are ignored and the status und navigation bar are not transparent anymore.

**Comment by jcesarmobile** [comment]
Please, can you create any sample app and introduce those changes and share the app?

**Comment by NePheus** [comment]
Ok, yes of course.

**Comment by jcesarmobile** [comment]
Just noticed that you are adding the changes to `NoActionBarLaunch` theme, which is the theme used for the splash screen, once the splash screen is dismissed the app switches to `NoActionBar` theme, that's the App theme. So it makes sense that your changes get overridden, you should add those lines to `NoActionBar` theme instead.

In your example there is no `NoActionBar` theme, it should be there
https://github.com/ionic-team/capacitor/blob/b893a57aaaf3a16e13db9c33037a12f1a5ac92e0/android-template/app/src/main/res/values/styles.xml#L12-L16

**Comment by AE1NS** [comment]
You are right, Im sorry. I dont know why my styles.xml has ended like this... Thanks for your help.

**Comment by NePheus** [comment]
You are correct, sorry for that. Didnt know why my file ended like this. Thank you!
