### ISSUE TITLE
bug: can't compile ios app with FirebaseDynamicLinksPlugin

### ISSUE THREAD

**Issue by woyteck** [ionic-team/capacitor#5269]
### Capacitor Version
💊   Capacitor Doctor  💊.

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
ios

### Current Behavior
I'm getting a "Swift CompileError":
/Users/me/projects/myproject/ios/capacitor-cordova-ios-plugins/sources/CordovaPluginFirebaseDynamiclinks/FirebaseDynamicLinksPlugin.h:4:9: Include of non-modular header inside framework module 'CordovaPlugins.FirebaseDynamicLinksPlugin': '/Users/me/projects/myproject/ios/App/Pods/Headers/Public/Firebase/Firebase.h'

FirebaseDynamicLinksPlugin.h:4:9:
#import <Firebase/Firebase.h>

### Expected Behavior
Should compile.

### Other Technical Details
`npx cap ls` output:
(node:16748) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/me/projects/myproject/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
[info] Found 5 Capacitor plugins for android:
       @capacitor/app@1.0.6
       @capacitor/keyboard@1.1.3
       @capacitor/push-notifications@1.0.7
       @capacitor/status-bar@1.0.6
       capacitor-native-biometric@3.0.3
[info] Found 8 Cordova plugins for android:
       cordova-plugin-android-permissions@1.1.2
       cordova-plugin-firebase-analytics@6.1.0
       cordova-plugin-firebase-dynamiclinks@6.1.1
       cordova-plugin-geolocation@4.1.0
       cordova-plugin-request-location-accuracy@2.3.0
       cordova-plugin-sms-retriever-manager@1.0.3
       cordova-plugin-theme-detection@1.3.0
       cordova-support-android-plugin@1.0.2
[info] Found 5 Capacitor plugins for ios:
       @capacitor/app@1.0.6
       @capacitor/keyboard@1.1.3
       @capacitor/push-notifications@1.0.7
       @capacitor/status-bar@1.0.6
       capacitor-native-biometric@3.0.3
[info] Found 6 Cordova plugins for ios:
       cordova-plugin-android-permissions@1.1.2
       cordova-plugin-firebase-analytics@6.1.0
       cordova-plugin-firebase-dynamiclinks@6.1.1
       cordova-plugin-geolocation@4.1.0
       cordova-plugin-request-location-accuracy@2.3.0
       cordova-plugin-theme-detection@1.3.0
[info] Found 2 incompatible Cordova plugins for ios, skipped install:
       cordova-plugin-sms-retriever-manager@1.0.3
       cordova-support-android-plugin@1.0.2
[info] Listing plugins for web is not possible.

`npm --version` output: 8.1.3

`node --version` output: v16.10.0

`pod --version` output (iOS issues only): 1.11.2

### Additional Context
The ios project is freshly generated using `ionic capacitor sync ios`, no manual tinkering.

**Comment by jcesarmobile** [comment]
I can't reproduce that problem, but I get

> Undefined symbols for architecture arm64:
> "_OBJC_CLASS_$_FIRAnalytics", referenced from:
> objc-class-ref in FirebaseAnalyticsPlugin.o
> ld: symbol(s) not found for architecture arm64

Can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing due to the lack of response

**Comment by marshall86** [comment]
i'm getting the same error, any news about how to fix it please?
