### ISSUE TITLE
bug: Android windowSoftInputMode:adjustPan not working

### ISSUE THREAD

**Issue by sawaca96** [ionic-team/capacitor#5272]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5
  @capacitor/cli: 3.2.5

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

android

### Current Behavior

`windowSoftInputMode:adjustPan` not working in android

### Expected Behavior

I think that setting up adjustPan would work like ios, but it actually works like adjustNothing.

### Code Reproduction

I add adjustPan setting to `AndroidManifest.xml` 
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.xxx.yyy">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="${displayName}"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name="com.xxx.yyy.MainActivity"
            android:label="${displayName}"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustPan"
            android:hardwareAccelerated="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>
    </application>

    <!-- Permissions -->

    <uses-permission android:name="android.permission.INTERNET" />
</manifest>

```

### Other Technical Details

`npm --version` output: 8.0.0

`node --version` output: v12.8.2

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
can you provide a sample app where the issue can be reproduced?

**Comment by david-webill** [comment]
I am experiencing the same thing.
My versions
  @capacitor/cli: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/ios: 3.3.4

**Comment by jcesarmobile** [comment]
Can you provide the sample app?

**Comment by david-webill** [comment]
Not sure if this helps.
Otherwise I will have to create a sample repo when I have time.
On IOS when focusing on an input, it works as expected, but on android, it just covers up the content like using adjustNothing.

Im using Vuejs3 if that matters
![focus](https://user-images.githubusercontent.com/76940540/151772228-72b2829d-2245-4b1b-9d7a-8546dda7ad9e.png)
![before_focus](https://user-images.githubusercontent.com/76940540/151772249-a16b6e74-5716-4780-9905-4323a34e5948.png)

**Comment by jcesarmobile** [comment]
It doesn't, I need a sample app I can run

**Comment by jcesarmobile** [comment]
Thanks for the app.

I've been able to reproduce, but with the same app content, the behavior is the same if I put it in a Cordova app and even in a native app that just contains a WebView (with no Cordova or Capacitor involvement), so it looks like a bug on the WebView itself, not in Capacitor.

If in the native app I put some native edit text fields it scrolls properly to them, but doesn't work with web input fields.

If I remove the `windowSoftInputMode` or set it to `adjustResize` then it focus properly, but resizing the content a bit. If you don't want that behavior you'll have to use the keyboard plugin for listening for the show/hide events and scroll to the inputs yourself.
