### ISSUE TITLE
bug:  Swift Compiler Error

### ISSUE THREAD

**Issue by melicard** [ionic-team/capacitor#5276]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.3.1
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
IOS

### Current Behavior
I get a swift compiler error with the followings after updating to capacitor 3
-Extraneous '}' at top level
-override' can only be specified on class members
-'super' cannot be used outside of class members
-Cannot find 'self' in scope

All in "override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) "

### Expected Behavior
Works

### Code Reproduction
  override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
    super.touchesBegan(touches, with: event)

    let statusBarRect = UIApplication.shared.statusBarFrame
    guard let touchPoint = event?.allTouches?.first?.location(in: self.window) else { return }

    if statusBarRect.contains(touchPoint) {
      NotificationCenter.default.post(name: .capacitorStatusBarTapped, object: nil)
    }
  }

     func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
     }

     func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
     }

}

### Other Technical Details

`npm --version` output: 8.1.0
`node --version` output:v16.13.0

`pod --version` output (iOS issues only):1.8.4

**Comment by jcesarmobile** [comment]
What's your Xcode version? Capacitor 3 requires Xcode 12 or newer.

If you are in Xcode 12, can you provide a sample app where the issue can be reproduced?

**Comment by jcesarmobile** [comment]
closing due to the lack of response
