### ISSUE TITLE
bug: Cant cap open android - EACCES -13 Error

### ISSUE THREAD

**Issue by Pijuli** [ionic-team/capacitor#5281]
### Capacitor Version
```
npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/core: 3.3.2

[success] Android looking great! 👌

```

### Platform(s)
Ubuntu 20.04.3 LTS and Android

### Current Behavior
On a fresh install of ionic project, having executed all the commands from the documentation on https://ionicframework.com/docs/vue/quickstart

It fails with the error on the screenshot

### Expected Behavior
To run properly as **ionic cap run android** does

### Code Reproduction
npm install -g @ionic/cli
ionic start myApp blank --type vue
ionic integrations enable capacitor
ionic build
ionic cap add android 
ionic cap open android 

### Other Technical Details

`npm --version` output:
6.14.13

`node --version` output:
v14.17.3

### Additional Context
ENV PATHS
![image](https://user-images.githubusercontent.com/1220004/143850175-11732eb6-f112-4282-a732-208e4fbb589c.png)

ACTUAL ERROR
![image](https://user-images.githubusercontent.com/1220004/143848665-2f19df3e-3102-4a4f-995b-3a3647d22adc.png)

I know it might be an issue with my local config, although I haven't been playing with any npm permissions anytime nor executed anything with sudo...

**I have been able to reproduce the same error with a work mate on it's Linux. Might not be a local issue**

Any fix direction would be much appreciated. T_T

**Comment by jcesarmobile** [comment]
Can you try changing the `CAPACITOR_ANDROID_STUDIO_PATH` variable to point to the studio.sh file and not just to bin folder?

If that doesn't help, can you provide the sample app you created?

**Comment by Pijuli** [comment]
That was it. Shame on me. I thought it could find it...
Although I'm having some config issues when trying to launch it from android-studio.
Anyway, I think I'll stick to the command line with local gradlew :shrug: 

Thank you Julio!

**Comment by CrazyOptimist** [comment]
Thanks guys!
