### ISSUE TITLE
bug: Getting warning when building Android "Using flatDir should be avoided because it doesn't support any meta-data formats."

### ISSUE THREAD

**Issue by MortenGregersen** [ionic-team/capacitor#5287]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/ios: 3.3.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior

When I build the Android app, I get the following warnings:

```
> Configure project :app
WARNING:: Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :capacitor-cordova-android-plugins
WARNING:: Using flatDir should be avoided because it doesn't support any meta-data formats.
```

### Expected Behavior

I expects to not get the warnings.

### Code Reproduction

I suspect it comes from these lines in my `build.gradle`, coming from the Capacitor template.

```
repositories {
    flatDir {
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}
```

### Other Technical Details

`npm --version` output: 7.24.1

`node --version` output: v14.16.0

**Comment by jcesarmobile** [comment]
That's just a warning, nothing to worry about yet.
`flatDir` is needed for cordova plugins support as some plugins require it to work. We will remove it once `flatDir` support is removed in a future gradle release, but would need to be in a major release as that would be a breaking change.

You can remove the entries if you don't use cordova plugins with .jar/.so libraries.

**Comment by haysquareA** [comment]
And now it's no longer working
