### ISSUE TITLE
bug: cannot move camera result file to data directory "unknown reason"

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor#5299]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/core: 3.3.0
  @capacitor/android: 3.3.0
  @capacitor/ios: 3.3.0
```

### Platform(s)

- Android

### Current Behavior

Newer android devices cannot move a file from the camera result path to the apps' data directory.

```
E/Capacitor/Console: File: http://localhost/main.js - Line 11433 - Msg: FileStorageService Error: moveFile error [file:///storage/emulated/0/Android/data/com.entergon.entergon/files/Pictures/JPEG_20211208_093551_9076438581670552951.jpg -> lead-files/a7c9cc78dfa336b70f9e9661a55606db863441ea97d35bfed38d328a311c2895_2140_951642.jpeg] [3x13] Error: Unable to rename, unknown reason
```

### Code Reproduction

```ts
const result = await Camera.getPhoto()
await Filesystem.rename({
        from: result.path,
        to: "images/text-image.jpg",
        toDirectory: Directory.Data,
      })
```

### Other Technical Details

`npm --version` output: 8.1.0

`node --version` output: 16.13.0

`pod --version` output (iOS issues only):

### Additional Context

I read these post recommending reading and writing the camera result. I am refactoring an old app and we have used that approach successfully over years so I wonder why its just not working on newer devices?

- https://devdactic.com/ionic-image-upload-capacitor/
- https://www.joshmorony.com/using-the-capacitor-filesystem-api-to-store-photos/

**Comment by jcesarmobile** [comment]
Can you provide more information about your environment? (device or emulator, android version, etc.)

Can you provide a sample app?

**Comment by muuvmuuv** [comment]
It seems that this only affects newer android devices with latest SDK where the camera tmp folder is read only, so moving does not work. For now, I followed the two posts and refactored the code to read the picture contents and write it in the apps data dir.

Before I create a repl, maybe this is just because of platform incompatibilities, so out of scope? A note in the camera docs would be enough I guess, saying that on android SDK X and above the camera output file is read only so moving to the apps dir does not work. Or I am entirely wrong at that point, but that is what I was experiencing.

**Comment by jcesarmobile** [comment]
If you are taking a new photo, the photo is written into the app's internal storage.
If you are picking an existing image, the plugin saves a copy also into the app's internal storage, at least when you use Google Photos as the app to pick images from.
Either way, internal app storage doesn't require any permissions to copy/read/move files, permissions are only needed for public storage and it's not possible to read/write on Android 10 and newer.

If you are using a different gallery app to pick images from, then it's possible that it returns a file path that is no longer accessible.

**Comment by muuvmuuv** [comment]
> If you are taking a new photo, the photo is written into the app's internal storage.

Yes, and that path seems to be read only, I cannot move that image from there into the apps data dir.

**Comment by jcesarmobile** [comment]
No, it’s not

**Comment by muuvmuuv** [comment]
So, we experienced that but replaced the logic with mentioned articles because _it was not possible_ to move the image out of the place where it was saved after capturing a photo. I will close it as fixed.
