### ISSUE TITLE
Capacitor is not a good term when searching in google

### ISSUE THREAD

**Issue by RezaRahmati** [ionic-team/capacitor#530]
Hey

I have issue when trying to find something (or issue) about Capacitor on web, since capacitor is already there as an electronic term, even if you search with combination like 'capacitor mobile' results are related how to charge your mobile phone with capacitors or....

Since it's early may be it's good idea to rename it to something unique.

**Comment by mlynch** [comment]
Once this project grows I don’t expect this to be a problem

**Comment by RezaRahmati** [comment]
you might be right, but of course this problem slow down your growth.
Most of devs try to find solution for their issues in google and I would give it up if it wasn't search friendly.

**Comment by mlynch** [comment]
Time will tell I suppose
