### ISSUE TITLE
Android app using Capacitor 3 is restarting every time it re-enters the foreground

### ISSUE THREAD

**Issue by dchappelle** [ionic-team/capacitor#5306]
### Discussed in https://github.com/ionic-team/capacitor/discussions/5305

<div type='discussions-op-text'>

<sup>Originally posted by **dchappelle** December  9, 2021</sup>

### Capacitor Version
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/ios: 3.3.3

Installed Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/ios: 3.3.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Issue

We have an app that uses the Quasar platform with Capacitor. Whenever the Android app is put into the background and then brought to the foreground again it is restarted?

- This is not a problem when using Capacitor 2
- I'm using _android:launchMode="singleTask"_ in the AndroidManifest.xml
- The iOS app is not restarted
- It restarts on a real Android device or emulator

Here are the logs I'm seeing... 

```
D/Capacitor: App paused
D/AAudio: AAudioStream_requestStop(s#1) called
D/AAudioStream: setState(s#1) from 4 to 9
D/AudioTrack: stop(274): called with 348296 frames delivered
D/AAudioStream: setState(s#1) from 9 to 10
D/Capacitor/AppPlugin: Firing change: false
V/Capacitor/AppPlugin: Notifying listeners for event appStateChange
D/Capacitor: App stopped
D/Capacitor: Saving instance state!
I/Capacitor/Console: File: https://<domain>/app.js - Line 5042 - Msg: [capacitor] - appStateChange, active: false
D/AAudio: AAudioStream_close(s#1) called ---------------
D/AAudioStream: setState(s#1) from 10 to 11
D/AAudioStream: setState(s#1) from 11 to 12
    ~AudioStream(s#1) mPlayerBase strongCount = 2
D/AAudio: AAudioStream_close(s#1) returned 0 ---------
D/Capacitor: App restarted
D/Capacitor: App started
D/Capacitor/AppPlugin: Firing change: true
V/Capacitor/AppPlugin: Notifying listeners for event appStateChange
D/Capacitor: App resumed
I/Capacitor/Console: File: https://<domain>/app.js - Line 5042 - Msg: [capacitor] - appStateChange, active: true
```
Any help would be greatly appreciated!</div>

**Comment by jcesarmobile** [comment]
What do you mean by restarted?
I see the App restarted message, but that's called on android's `onRestart` method, which gets called when the app comes back from background, but the app remains on the same page it was before putting it into the background.

Can you provide a sample app?

**Comment by dchappelle** [comment]
@jcesarmobile thanks for the reply. If I remember correctly, the Android app itself restarted. It's been awhile (before the holidays) since I tried this. I'll double check as soon as I can get back to it and let you know for sure.

**Comment by dchappelle** [comment]
@jcesarmobile starting to look at this again.. the Android app doesn't restart but the page is reloading every time the app comes back into the foreground.

**Comment by dchappelle** [comment]
@jcesarmobile I found out that the **jcesarmobile/ssl-skip** Capacitor plugin for skipping ssl checks is causing this behavior
