### ISSUE TITLE
Is Chrome bundled with the app installation?

### ISSUE THREAD

**Issue by wondering639** [ionic-team/capacitor#5318]
On Android, is Chrome bundled with the app installation? What about users that use their smartphone without the Google Apps (like some custom ROMs)? Thanks!

**Comment by thomasvidas** [comment]
For questions, [the Ionic Forum](https://forum.ionicframework.com) is usually the better place to ask, but to answer your question; no. Capacitor does not bundle Chrome and requires Google Chrome to be the system webview.
