### ISSUE TITLE
"ngx cap ..." commands do nothing :(

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor#532]
Hi! I'm on Windows 10 and when I try to execute some capacitor commands, nothing happen :(

I get that:
```
PS E:\tmp> npx cap init
npx: installed 1 in 2.555s
Path must be a string. Received undefined
Path must be a string. Received undefined
```

Do you have any idea that could help me 😄 ? 

Thanks

EDIT: I saw that others have this message "Path must be a string. Received undefined" because of being on a Windows OS but they have then messages about ngx doing some things...

**Comment by sneko** [comment]
That's so strange... It does not work at all in PowerShell, but in the old "cmd" terminal it works well... moreover, without the known error "Path must be a string. Received undefined".

I leave that opened since I did not find a solution for PowerShell.

**Comment by jgw96** [comment]
Not sure if there was a release today or not, but i installed capacitor yesterday and ran the same commands on my Surface using powershell and it worked fine. What version of node are you running @sneko ?

**Comment by sneko** [comment]
@jgw96 2 hours ago I had Node v8.10.x but since it was not working I also tried v8.11.1

**Comment by mlynch** [comment]
Are you in the directory of an app? I see `E:\tmp`, you need to be in the directory of the app in order to run `npx cap`

**Comment by sneko** [comment]
@mlynch you're right, because of an issue I was trying to setup a project from scratch with: 
`npx @capacitor/cli create`

And forgot to go in the subfolder made. My bad 👎 

However, when I was trying on a existing Vue.js project it was the same issue but it seems it was related to #533 because I installed Capacitor modules with yarn instead of npm.

Thanks to both of you 👍

**Comment by mlynch** [comment]
Glad it's working now! I have a feeling this is going to trip up a lot of people, especially because `npx cap` doesn't _fail_ when you're not in the directory. hmmm

**Comment by sneko** [comment]
May you could check the presence of an "capacitor.config.json" file in current and parent folders?

**Comment by sneko** [comment]
@mlynch Oh ok, I just checked "npx aaaaaaaa" and it triggers no error. It's not on your side, sorry I misunderstood
