### ISSUE TITLE
feat: Add Enums for "NoCloud" Directories

### ISSUE THREAD

**Issue by allidoisace** [ionic-team/capacitor#5321]
### Description

It would be nice to have an enum for the Directories that have "NoCloud" sub directories.

### Platform(s)

iOS

### Preferred Solution

Add to the Directory enums.

### Alternatives

Utilizing `path` to be `NoCloud/` in addition to specifying the `Directory.Documents` when writing a file.

**Comment by jcesarmobile** [comment]
NoCloud directories are a thing Cordova made up, cordova-plugin-file creates those folders and mark them for not being backed up, but if Capacitor apps, if you don't install cordova-plugin-file, those folders won't exist, and if you create those folders with @capacitor/filesystem they will still be backed up.
