### ISSUE TITLE
bug: Form submit with method post and action to external url in ios is redirected to external browser.

### ISSUE THREAD

**Issue by josprimasihombing** [ionic-team/capacitor#5323]
### Capacitor Version 3.2.0

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/ios: 3.3.3

Installed Dependencies:

  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/cli: 3.2.5
  @capacitor/ios: 3.2.5
```

### Platform(s)

```
iOS
```

### Current Behavior

```
HTML form with action to external url, and method POST is opened external browser.
```

### Expected Behavior

Should not open external browser like in android.

### Additional Context

Maybe relevant issue:
https://developer.apple.com/forums/thread/108385

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by josprimasihombing** [comment]
Hi @jcesarmobile ,

Here i provide a repository that can reproduce this bug:
[https://github.com/josprimasihombing/capacitor-reproduce-sample](https://github.com/josprimasihombing/capacitor-reproduce-sample)

And also, i attach a video to demonstrate:

https://user-images.githubusercontent.com/57883217/146361104-42dde02d-a918-4616-98dd-5d23e8b15eca.mp4

Thanks

**Comment by jcesarmobile** [comment]
In fact, iOS behavior is good, Capacitor doesn't allow apps to navigate to external sites unless you added them in the `allowNavigation` array and the form POST is trying to navigate to google.

If you add this to your capacitor config file it will work as you want.

```
"server": {
    "allowNavigation": ["*.google.com"]
}
```

On the other hand, Android should not navigate to the external site, the form navigation should call `shouldOverrideUrlLoading`, but it doesn't, so it navigates, we should fix that.

Also, note that we don't recommend using `allowNavigation`, apps should never navigate out to an external site, the recommended way of doing a POST is to use XHR or fetch or HTTP plugin.

**Comment by josprimasihombing** [comment]
So the right behavior is on ios ?

**Comment by jcesarmobile** [comment]
yes, iOS behavior is correct, we should fix Android behavior, Capacitor should not navigate to an external sites unless the url is on the allowNavigation entry

**Comment by josprimasihombing** [comment]
okay, thanks @jcesarmobile for your explanation. will close this issue.
