### ISSUE TITLE
Change Motion API to use native heading/compass (i.e. "device orientation") 

### ISSUE THREAD

**Issue by arielhasidim** [ionic-team/capacitor#5327]
### Description
As stated in the docs: "This plugin is currently implemented using Web APIs. Most browsers require permission before using this API". Unfortunately, since iOS 13+ the permission flow is very non-native and results in poor user experience. Native implementation will save the need for user interaction before asking for permission (one time only).

**Hence, for better UX, Motion API should use native implemantation.**

For more details and refrences see full discussion at [cordova-plugin-device-orientation repo: "Should deprecation status be removed?"[Accepted]](https://github.com/apache/cordova-plugin-device-orientation/issues/52) issue.

**Comment by thomasvidas** [comment]
There is an open PR that fixes the permissions issue with the web implementation here: #5317

**Comment by arielhasidim** [comment]
Couldn't ask for more 😅
Sorry for missing this.

**Comment by thomasvidas** [comment]
No worries! 😄

**Comment by jcesarmobile** [comment]
In fact, we are considering using native code for the plugin as it seems that the web results are not as accurate as the native results
https://github.com/ionic-team/capacitor-plugins/issues/718

**Comment by arielhasidim** [comment]
> In fact, we are considering using native code for the plugin as it seems that the web results are not as accurate as the native results
> [ionic-team/capacitor-plugins#718](https://github.com/ionic-team/capacitor-plugins/issues/718)

I think the discussion in the mentioned issue on Cordova's plugin above is valuable here with the references + maybe the code itself can be used partially to create the native implementation (check my comment there). I use it for navigation feature in my app, and I prefer native implementation for better performance and permission flow which will result in better user experience overall.

**Comment by arielhasidim** [comment]
In the last week I experienced with Motion API and [cordova-plugin-device-orientation](https://github.com/apache/cordova-plugin-device-orientation) as alternatives for getting compass-orientation, and sadly Motion-API is no good for me as alternative right now:

- In the docs, though the subtitle states _"The Motion API tracks accelerometer and device orientation (**compass heading**, etc.)"_, [in the bottom](https://capacitorjs.com/docs/apis/motion#addlistenerorientation) is looks like you get only relative acceleration and rotation rate and no "compass" feature.
- Even if Motion-API is implemented exactly like the Web-API, and actually has "compass feature", there are big differences with implementation for different browsers and iOS versions. [Check this example](https://stackoverflow.com/a/58660055/7224607)
- Asking for compass permission every launch upon user gesture is not an acceptable UX for me, and shouldn't be for every developer wishes to create native experience
- [cordova-plugin-device-orientation](https://github.com/apache/cordova-plugin-device-orientation) works great out of the box for me, I don't ask for premission over and over, I have really nice and simple method to listen for changes in compass reads with filtering by minimal change in degrees with very accurate resolution!

**That's why I think Motion-API should implement native methods to get "devices compass", and even adopt the methods used in the old Cordova's plugin.**

My project info:
"@capacitor/cli": "3.3.2",
"@capacitor/ios": "^3.3.2",
"@capacitor/angular": "^2.0.0",
"@angular/cli": "^13.1.1",
"@capacitor/motion": "^1.0.4", // not in use
"cordova-plugin-device-orientation": "^2.0.1",

BTW - Be aware that heading and compass used sometimes interchangeably to describe relative deviation from the magnetic north, while sometimes heading is used to to describe the vector of change in position relative to the north. **I'm talking about implementing digital compass in my app and not the other kind of heading**.

**Comment by jcesarmobile** [comment]
As I said, we are considering using native implementation instead of web implementation and it's being tracked [here](https://github.com/ionic-team/capacitor-plugins/issues/718), so please, don't reopen your issue, if you want to add additional information, add it there.
