### ISSUE TITLE
"npx cap add android" remove files from CLI module

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor#533]
Hi,

When I'm running `npx cap add android` it starts to install dependencies but after few seconds I get this error:
```
E:\meta-front\app\node_modules\@capacitor\cli\bin\capacitor
√ Installing android dependencies in 32.43s
× Adding native android project in: E:\meta-front\app\android: ENOENT: no such file or directory, lstat 'E:\meta-front\app\node_modules\@capacitor\cli\assets\android-template'
× add: ENOENT: no such file or directory, lstat 'E:\meta-front\app\node_modules\@capacitor\cli\assets\android-template'
[error] { Error: ENOENT: no such file or directory, lstat 'E:\meta-front\app\node_modules\@capacitor\cli\assets\android-template'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'E:\\meta-front\\app\\node_modules\\@capacitor\\cli\\assets\\android-template' }
```

I checked the "@capacitor\cli" module folder and found that it was empty except its node_modules/ subfolder.

I decided to run:
`yarn remove @capacitor/core @capacitor/cli`
`yarn add @capacitor/core @capacitor/cli`

Every files were added. So I just retried `npx cap add android` and got the same error and got  "@capacitor\cli" folder empty again.

That's really strange since it seems by running adding android platform it cleans the folder 😆 .

Any idea?

**Comment by mlynch** [comment]
I would recommend not using yarn, we haven't tested it at all

**Comment by sneko** [comment]
In many cases yarn still works better than npm for me (when dependencies conflicts). Is testing it on your roadmap?

Thanks
