### ISSUE TITLE
Network does not have web implementation.

### ISSUE THREAD

**Issue by ix-xerri** [ionic-team/capacitor#534]
I am using the Network API but getting a console error with:

`ERROR Error: Uncaught (in promise): Network does not have web implementation.`

This is on v1.0.0-alpha.37

**Comment by ix-xerri** [comment]
I thought it was working since there is paw written on Network docs. Any idea when it will be available on the web?

**Comment by mlynch** [comment]
Re-opening to track since we need to add this

**Comment by IT-MikeS** [comment]
At the moment this may not be possible with out doing a fetch to test connectivity and connectionType being `unknown` a lot of the time due to the acceptance of the `Network Information API` in current browsers.

https://caniuse.com/#feat=netinfo

**Comment by ix-xerri** [comment]
Seems like all was fixed in `alpha.38`

**Comment by ix-xerri** [comment]
Any plans of having an implementation in the browser soon? It hit beta and the error still persists.
Thanks

**Comment by mburger81** [comment]
Same for me, not sure why there is a discrimination between `PWA` and `ionic serve` or `browser apps`. We are always running in a browser and we have always to use web apis, so or it work or doesn't.
Right?
Ionic Native Network (cordova) is working well (not for all properties)
Thx!

**Comment by ix-xerri** [comment]
Since its currently on beta, I don't think this feature will be implemented on web soon, right?

**Comment by ix-xerri** [comment]
Since its currently on beta, I don't think this feature will be implemented on web soon, right?

**Comment by mlynch** [comment]
Added a basic network plugin that is ported from the Electron one. It won't really do anything on browsers that don't support it but at least it won't throw a bunch of errors.
