### ISSUE TITLE
plugin is not implemented on android

### ISSUE THREAD

**Issue by pioneersingh321** [ionic-team/capacitor#5340]
### Capacitor Version

```
PASTE OUTPUT HERE
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Please, when creating issues, provide all the information requested by the template, including a sample app where the issue can be reproduced.

Here you can find the common errors that can cause plugin not implemented

https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented
