### ISSUE TITLE
Local notifications core plugin

### ISSUE THREAD

**Issue by meltuhamy** [ionic-team/capacitor#535]
Although there is a [cordova plugin](https://github.com/katzer/cordova-plugin-local-notifications), I believe local notifications should be a **core** plugin - it would be great to have a unified API for displaying, scheduling and interacting with notifications on all platforms including PWAs. Also, notification APIs are constantly improving on each platform, and although the cordova plugin tries to keep up, it often _breaks_ between platform releases. Having it a core plugin would hopefully ensure proper maintenance. 

I was wondering if such a plugin would appear on the roadmap any time soon?

**Comment by jcesarmobile** [comment]
It's already implemented for iOS, but still missing for web, Android and Electron

**Comment by chuckgreenman** [comment]
I've got some open time coming up this weekend.  Will take a crack at notifications on Android.
