### ISSUE TITLE
npm link plugins fail to find source_files on iOS

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#536]
When developing a plugin and using `npm link`, `npx cap update ios` finds the plugin and runs the install, but none of the source files copy over from cocoapods.

I'm guessing this is a cocoapods issue but wanted to file it here so we can figure out exactly where things are breaking

![screen shot 2018-05-11 at 4 20 14 pm](https://user-images.githubusercontent.com/11214/39947381-4a514bfc-5537-11e8-9d45-1bb04a240048.png)

![screen shot 2018-05-11 at 4 20 35 pm](https://user-images.githubusercontent.com/11214/39947383-4bfa1f42-5537-11e8-8cc3-758eae2d7bae.png)

**Comment by mlynch** [comment]
I can get it to work by putting the `podspec` into the `ios` folder in the plugin, but that ends up with some other weird behavior:

![screen shot 2018-05-11 at 4 32 50 pm](https://user-images.githubusercontent.com/11214/39947852-0b83fdbe-5539-11e8-9c94-f85ef6bf403d.png)
![screen shot 2018-05-11 at 4 32 58 pm](https://user-images.githubusercontent.com/11214/39947853-0d0bc3e2-5539-11e8-9967-756105f65099.png)
![screen shot 2018-05-11 at 4 31 32 pm](https://user-images.githubusercontent.com/11214/39947855-0eb2d348-5539-11e8-9ae7-6d246fab5f6d.png)

**Comment by jcesarmobile** [comment]
are you using master or latest release?
Because I fixed a problem we had that publish was ignoring the .podspec, not sure if it also affects npm link.

**Comment by mlynch** [comment]
Latest release. Just tested and that doesn't appear to be the issue

**Comment by jcesarmobile** [comment]
<img width="305" alt="captura de pantalla 2018-05-12 a las 0 16 20" src="https://user-images.githubusercontent.com/1637892/39949214-cf341e48-5579-11e8-889b-c8102a7ac6b7.png">

This is what I get when using a plugin generated from master. Seems ok to me.

BTW, the problem was on the plugin generator, so if your plugin is already generated it won't be fixed by updating, you have to add the .podspec to the files section of the plugin's package.json manually

**Comment by mlynch** [comment]
K I’ll try again, I thought those nested folders seemed off when I tried correcting for it

**Comment by jcesarmobile** [comment]
Should be fixed by https://github.com/ionic-team/capacitor/pull/1077
