### ISSUE TITLE
bug: How to access other domains in the same window (in app) with capacitor ?

### ISSUE THREAD

**Issue by PavanTank4631** [ionic-team/capacitor#5364]

**Comment by PavanTank4631** [comment]
I want to show external website (other domains) in my capacitor app, when I try to do so I was not able to show it in app but it redirects me to browser. 

if there any solution regarding it, please let me know.

**Comment by jayenashar** [comment]
what happens if you try allowNavigation in https://capacitorjs.com/docs/config ?

**Comment by jcesarmobile** [comment]
Yeah, you need to add the domains to the allowNavigation.

please, don’t create issues to ask questions, there is a discussions section where you can ask questions.
