### ISSUE TITLE
bug: Issue with renaming the capacitor app

### ISSUE THREAD

**Issue by Laktik228** [ionic-team/capacitor#5365]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
IOS

### Current Behavior
When renaming the app from xcode, it changes the name of the project everywhere. When I try to sync with 'npx cap sync ios' it gives me error that 'App.xcodeproj is not found'. I tried to look into why it was happening and found out that in the 'node_modules/@capacitor/cli/dist/config.js' in loadIOSConfig() it looks like its not adapted for xcodeproj name change and "hard-codedly" specifies the 'App.xcodeproj' on the line with 'nativeXcodeProjDir' variable definition:
<img width="833" alt="Screenshot 2022-01-11 at 12 41 41" src="https://user-images.githubusercontent.com/22400584/148928070-f1058e76-6676-4387-a551-1cd9fde7fa8b.png"> 

### Expected Behavior
The current change i have to make my code work is directly load the name from capacitor.config.ts, but I understand this is not the best decision as the app name can vary from the project name. What I would do is in capacitor.config.ts add in ios object a field to specify project name and on sync it would change the project name automatically if it is possible. If not then make sure to document that add this field only if your app name is different from the default one.
<img width="818" alt="Screenshot 2022-01-11 at 12 49 54" src="https://user-images.githubusercontent.com/22400584/148929288-911f3028-9474-4d92-a496-8983157740dd.png">

### Code Reproduction
async function loadIOSConfig(rootDir, extConfig) {
    var _a, _b, _c, _d;
    const name = 'ios';
    const podPath = determineCocoapodPath();
    const platformDir = (_b = (_a = extConfig.ios) === null || _a === void 0 ? void 0 : _a.path) !== null && _b !== void 0 ? _b : 'ios';
    const platformDirAbs = path_1.resolve(rootDir, platformDir);
    const scheme = (_d = (_c = extConfig.ios) === null || _c === void 0 ? void 0 : _c.scheme) !== null && _d !== void 0 ? _d : 'App';
    const nativeProjectDir = 'App';
    const nativeProjectDirAbs = path_1.resolve(platformDirAbs, nativeProjectDir);
    const nativeTargetDir = `${nativeProjectDir}/App`;
    const nativeTargetDirAbs = path_1.resolve(platformDirAbs, nativeTargetDir);
    **const nativeXcodeProjDir = `${nativeProjectDir}/App.xcodeproj`;**
    const nativeXcodeProjDirAbs = path_1.resolve(platformDirAbs, nativeXcodeProjDir);
    const nativeXcodeWorkspaceDirAbs = promise_1.lazy(() => determineXcodeWorkspaceDirAbs(nativeProjectDirAbs));
    const webDirAbs = promise_1.lazy(() => determineIOSWebDirAbs(nativeProjectDirAbs, nativeTargetDirAbs, nativeXcodeProjDirAbs));
    const cordovaPluginsDir = 'capacitor-cordova-ios-plugins';
    return {
        name,
        minVersion: '12.0',
        platformDir,
        platformDirAbs,
        scheme,
        cordovaPluginsDir,
        cordovaPluginsDirAbs: path_1.resolve(platformDirAbs, cordovaPluginsDir),
        nativeProjectDir,
        nativeProjectDirAbs,
        nativeTargetDir,
        nativeTargetDirAbs,
        nativeXcodeProjDir,
        nativeXcodeProjDirAbs,
        nativeXcodeWorkspaceDir: promise_1.lazy(async () => path_1.relative(platformDirAbs, await nativeXcodeWorkspaceDirAbs)),
        nativeXcodeWorkspaceDirAbs,
        webDir: promise_1.lazy(async () => path_1.relative(platformDirAbs, await webDirAbs)),
        webDirAbs,
        podPath,
    };
}

### Other Technical Details

`npm --version` output:
7.12.1

`node --version` output:
v14.15.4

`pod --version` output (iOS issues only):
1.11.2

**Comment by jcesarmobile** [comment]
renaming the app is not supported, you can rename the target like [explained on the docs](https://capacitorjs.com/docs/ios/configuration#renaming-your-app)
