### ISSUE TITLE
feat: any plan to add live preview in https://capacitorjs.com/docs

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/capacitor#5367]
### Description

It is good to have live preview of basic what some of plugins can do 
We can add some dropdown to choose and see the output.

That may can be used to test as well for regression.

### Platform(s)

Both

**Comment by jcesarmobile** [comment]
Most plugins are not visual, so there won't be anything to see, and would only be possible for web versions of the plugins, which are most times not implemented or limited, so I don't see a lot of value on it. Maybe for the visual ones (modals, action-sheets, etc.) we could add some screenshots or gifts.

We have a test app that everybody can run and see all plugins working, not the same, but might be helful
https://github.com/ionic-team/capacitor-testapp


Anyway, the site repository is [this one](https://github.com/ionic-team/capacitor-site/issues), you can request it there
