### ISSUE TITLE
bug: Accessing Specific Server

### ISSUE THREAD

**Issue by HaoboZ** [ionic-team/capacitor#5370]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

android

### Current Behavior

I'm trying to access an aws ec2 server with capacitor on android API 25 using axios calls.
However, it returns a network error that I can't figure out why it's showing. 
Using the exact same code, I can hit another server I was testing just fine. 
Using it on API 30 works fine, so I'm not sure what's wrong or how to fix. 
The ec2 server is already configured with https and cors and no problems on both web and ios. 
I added allowMixedContent and cleartext in the config as well. 

### Expected Behavior

Be working on android. 

### Code Reproduction

Here's an [endpoint](https://ec2-54-245-193-62.us-west-2.compute.amazonaws.com:4000/test) that returns hello world.

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Different android versions trust different certificates/issuers, so your android 25 device/emulator might not trust the certificate you use in that server. 
Also, looks like the certificate is not correctly installed, if you put the url an port [here](https://www.geocerts.com/ssl-checker) it tells you “A valid Root CA Certificate could not be located, the certificate will likely display browser warnings.”

It says “likely”, which means it will work on some but fail in others.
