### ISSUE TITLE
NSAppTransportSecurity setting in iOS

### ISSUE THREAD

**Issue by chrisdelambert** [ionic-team/capacitor#5372]
In Capacitor 3, when an iOS project is created, the setting for NSAllowsArbitraryLoads is set to true in NSAppTransportSecurity in Info.plist. This is considered insecure by Apple, as it allows http connections. Any security review of an app will also highlight this as a red flag, which causes problems for certain clients.

My issue is why is part of a default Capacitor app? Will removing the NSAppTransportSecurity key have any effect on the functionality of the app? If it's required to load localhost for the app's web server then fine, however, some documentation or rationale for this would be appreciated. Especially for those of us that have our apps run through stringent security tests.

**Comment by chrisdelambert** [comment]
Thanks for the clarification. By live reload, are you referring to loading an update using Appflow? We use this in all our Ionic/Capacitor based apps. 

It would be great if this could be removed in V4. When running an IPA of an app using Capacitor 3 through [MOBSF (Mobile Security Framework)](https://github.com/MobSF/Mobile-Security-Framework-MobSF), this is highlighted as insecure. There are several other Capacitor/Ionic issues as well which you might be interested in. I'd be happy to share those if you are interested. Many of our clients are government agencies and they require basic security analysis of the IPAs and APKs. 

![Screenshot 2022-01-19 at 12 53 14 PM](https://user-images.githubusercontent.com/19525279/150037796-a39cda73-6c82-4497-ac0b-eebae4c05462.png)

**Comment by jcesarmobile** [comment]
No, live reload is when you (our a dev CLI) configures the app to load from a local web server, in example if you run ionic cap run ios —livereload, so the changes you make in the code are automatically compiled and the app content reloaded, is intended to be used for development only and it’s unrelated to appflow’s deploy feature. Deploy feature connects to a https server and download the files and load them from the filesystem, so it’s not affected by ATS.

If you are not using live reload you can safely remove the entry from the info.plist, if we remove it in capacitor 4 we would remove from the app template, so existing users will still have the entry in their apps (we would recommend to remove it in the capacitor 4 upgrade guide)

I will check the MOBSF tool, but the automated security analyzers are not very accurate and usually catch false positives (didn’t test this one, but it’s been my experience with others and reported issues I’ve seen in different repositories)

**Comment by chrisdelambert** [comment]
Understood, thanks for the clarification. I'll keep an eye out when Capacitor 4 is announced.

**Comment by jcesarmobile** [comment]
This has been addressed [here](https://github.com/ionic-team/capacitor/pull/5641)
Newly capacitor 4.0.0 beta 0 or newer apps won't include NSAppTransportSecurity setting, existing apps can remove it if desired.
For live reload, if using ionic CLI they should update to 6.20 or newer as it handles the case where NSAppTransportSecurity is not present.
