### ISSUE TITLE
bug: After jcenter shutdown and upgrade to Capacitor 3.x, Android app is crashing.

### ISSUE THREAD

**Issue by damienstanton** [ionic-team/capacitor#5375]
### Capacitor Version

```
[warn] The hideLogs configuration option has been deprecated. Please update to use loggingBehavior instead.
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

Android

### Current Behavior

The `jcenter` bintray repo hosting Cordova 7.0.0 is gone, and we cannot use `jcenter` as a source 
 for artifacts anymore.

After upgrading our application from Capacitor 2.5 to Capacitor 3.x and manually removing `jcenter` repositories, and updating the Cordova framework dependency to 10.1.1, the application has a hard crash on start due to an NPE in a private Cordova constructor method:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{<elided>MainActivity}: 
java.lang.NullPointerException: Attempt to invoke virtual method
'void org.apache.cordova.g.privateInitialize(
  java.lang.String,
  org.apache.cordova.e,
  org.apache.cordova.k,
  org.apache.cordova.i)' on a null object reference
``` 

### Expected Behavior

The upgrade to Capacitor 3.x, update of Cordova from 7.0.0 to 10.1.1, and correlated removal of `jcenter` should not cause an app crash. Is there some other way to mitigate the Cordova 7.0.0 dependency hosting issue?

### Other Technical Details

`npm --version` output:
```
8.1.2
```

`node --version` output:
```
v16.13.1
```

Other Notes:

We'd have no issues sticking with Cordova 7.0.0 if an alt hosting for the artifact which was in jcenter/bintray and is known to resolve in Android Studio. Otherwise we need some path forward for getting Cordova framework 10.x working here.

**Comment by jcesarmobile** [comment]
Can you provide a sample app? Using cordova-android 10 is perfectly possible since capacitor 3.2.5 so the crash must be caused by some plugin.

**Comment by cromefire** [comment]
While I also can't provide you with a sample right now, it seems to ovvurr when trying to run instrumentation tests:
```
   > Could not resolve com.google.errorprone:error_prone_annotations:2.3.2.
     Required by:
         project :capacitor-cordova-android-plugins > com.android.tools.build:gradle:4.2.1 > com.android.tools.build:bundletool:1.1.0
      > Could not resolve com.google.errorprone:error_prone_annotations:2.3.2.
         > Could not get resource 'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.google.errorprone:error_prone_annotations:2.3.2.
     Required by:
         project :capacitor-cordova-android-plugins > com.android.tools.build:gradle:4.2.1 > com.google.protobuf:protobuf-java-util:3.10.0
         project :capacitor-cordova-android-plugins > com.android.tools.build:gradle:4.2.1 > com.android.tools.build:aaptcompiler:4.2.1 > com.google.guava:guava:28.1-jre
      > Could not resolve com.google.errorprone:error_prone_annotations:2.3.2.
         > Could not get resource 'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.pom'. Received status code 502 from server: Bad Gateway
```

Basically regardless any [references to `jcenter()`](https://github.com/ionic-team/capacitor/search?q=jcenter%28%29) should be removed, because jCenter just doesn't work at all anymore, replace it with `mavenCentral()` where needed.

**Comment by damienstanton** [comment]
@cromefire's comment was useful as a debugging step for us. Is there a reason that comment was deleted?

**Comment by jcesarmobile** [comment]
You are talking about a runtime exception in your app, while their comment was about not being able to run the tests with jcenter still in their repository list as the error messages indicated that it was searching for dependencies there.

That was due to reachability problems on jcenter during the weekend and totally unrelated.

**Comment by damienstanton** [comment]
Okay understood.

However, I'm confused, how are any jcenter repos resolving at all, including Cordova 7.x? The service is shut down with a permanent 403 error: https://jcenter.bintray.com/

**Comment by cromefire** [comment]
> Okay understood.
> 
> However, I'm confused, how are any jcenter repos resolving at all, including Cordova 7.x? The service is shut down with a permanent 403 error: https://jcenter.bintray.com/

You have to go to the package URL directly. If it's malfunctioning again it'll show a 502 and not a 403.

**Comment by damienstanton** [comment]
Closing this as we decided to move faster by simply porting our Ionic 5 app content into a new Ionic 6 / Capacitor 3 blank template app.
