### ISSUE TITLE
bug:  Execution failed for task ':app:checkDebugAarMetadata'. [capacitor] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/capacitor#5378]
Hi,

 Capacitor Doctor   

Latest Dependencies:       

  @capacitor/cli: 3.3.4    
  @capacitor/core: 3.3.4   
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4    

Installed Dependencies:    

  @capacitor/core: 3.3.0
  @capacitor/cli: 3.3.0 
  @capacitor/android: 3.3.1
  @capacitor/ios: 3.3.0

[success] Android looking great! 👌

**Error**

ionic cap run android -l --host=0.0.0.0
? Which device would you like to target? samsung SM-M325FV (RF8R70STFHP)
> capacitor.cmd sync android
[capacitor] √ Copying web assets from www to android\app\src\main\assets\public in 15.16s
[capacitor] √ Creating capacitor.config.json in android\app\src\main\assets in 4.94ms
[capacitor] [info] Found 9 Cordova plugins for android:
[capacitor]        call-number@1.0.1
[capacitor]        cordova-open-native-settings@1.5.5
[capacitor]        cordova-plugin-apprate@1.7.2      
[capacitor]        cordova-plugin-dialogs@2.0.2      
[capacitor]        cordova-plugin-inappbrowser@5.0.0
[capacitor]        cordova-plugin-nativestorage@2.3.2
[capacitor]        cordova-plugin-screen-orientation@3.0.2
[capacitor]        cordova-plugin-x-socialsharing@6.0.3
[capacitor]        es6-promise-plugin@4.2.2
[capacitor] √ copy android in 16.07s
[capacitor] √ Updating Android plugins in 95.12ms
[capacitor] [info] Found 13 Capacitor plugins for android:
[capacitor]        @capacitor/app@1.0.6
[capacitor]        @capacitor/browser@1.0.6
[capacitor]        @capacitor/camera@1.2.2
[capacitor]        @capacitor/device@1.0.6
[capacitor]        @capacitor/geolocation@1.1.3
[capacitor]        @capacitor/haptics@1.1.3
[capacitor]        @capacitor/keyboard@1.1.3
[capacitor]        @capacitor/local-notifications@1.0.9
[capacitor]        @capacitor/push-notifications@1.0.7
[capacitor]        @capacitor/splash-screen@1.1.6
[capacitor]        @capacitor/status-bar@1.0.6
[capacitor]        @capacitor/storage@1.2.3
[capacitor]        @sentry/capacitor@0.4.1
[capacitor] [info] Found 9 Cordova plugins for android:
[capacitor]        call-number@1.0.1
[capacitor]        cordova-open-native-settings@1.5.5
[capacitor]        cordova-plugin-apprate@1.7.2
[capacitor]        cordova-plugin-dialogs@2.0.2
[capacitor]        cordova-plugin-inappbrowser@5.0.0
[capacitor]        cordova-plugin-nativestorage@2.3.2
[capacitor]        cordova-plugin-screen-orientation@3.0.2
[capacitor]        cordova-plugin-x-socialsharing@6.0.3
[capacitor]        es6-promise-plugin@4.2.2
[capacitor] √ update android in 1.03s
[capacitor] [info] Sync finished in 17.115s
> ng.cmd run app:serve --host=0.0.0.0 --port=8100
[ng] Warning: This is a simple server for use in testing or debugging Angular applications
[ng] locally. It hasn't been reviewed for security issues.
[ng] Binding this server to an open connection can result in compromising your application or
[ng] computer. Using a different host than the one passed to the "--host" flag might result in
[ng] websocket connection issues. You might need to use "--disableHostCheck" if that's the
[ng] case.
[ng] - Generating browser application bundles (phase: setup)...
[ng] ✔ Browser application bundle generation complete.
[ng] Initial Chunk Files                                                                                     | Names              |      Size
[ng] vendor.js                                                                                               | vendor             |   6.93 MB
[ng] polyfills.js                                                                                            | polyfills          | 638.33 kB
[ng] styles.css, styles.js                                                                                   | styles             | 379.18 kB
[ng] main.js                                                                                                 | main               |  69.30 kB
[ng] runtime.js                                                                                              | runtime            |  14.59 kB
[ng] | Initial Total      |   8.00 MB
[ng] Lazy Chunk Files                                                                                        | Names              |      Size
[ng] src_app_modules_reports_reports_module_ts.js                                                            | -   
               |   1.18 MB
[ng] default-src_app_modules_shared_shared_module_ts.js                                                      | -   
               | 471.49 kB
[ng] src_app_modules_map_map_module_ts.js                                                                    | -   
               | 211.41 kB
[ng] node_modules_ionic_core_dist_esm_swiper_bundle-95afeea2_js.js                                           | -   
               | 200.19 kB
[ng] default-node_modules_angular_fire___ivy_ngcc___fesm2015_angular-fire-storage_js-node_modules_-7644f8.js | -   
               | 188.37 kB
[ng] node_modules_firebase_auth_dist_index_esm_js.js                                                         | -   
               | 181.90 kB
[ng] src_app_modules_auth_auth_module_ts.js                                                                  | -   
               | 138.32 kB
[ng] Warning: D:\Clients\node_modules\ng2-charts\__ivy_ngcc__\fesm2015\ng2-charts.js depends on 'chart.js'. CommonJS or AMD dependencies can cause optimization bailouts.
[ng] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ng] polyfills-core-js.js                                                                                    | polyfills-core-js  |  92.37 kB
[ng] node_modules_ionic_core_dist_esm_ion-datetime_3_entry_js.js                                             | -   
               |  72.13 kB
[ng] node_modules_ionic_core_dist_esm_ion-item_8_entry_js.js                                                 | -   
               |  71.17 kB
[ng] src_app_modules_archived_archived_module_ts.js                                                          | -   
               |  64.43 kB
[ng] node_modules_ionic_core_dist_esm_ion-app_8_entry_js.js                                                  | -   
               |  62.29 kB
[ng] node_modules_ionic_core_dist_esm_ion-slide_2_entry_js.js                                                | -   
               |  56.07 kB
[ng] src_app_modules_leads_leads_module_ts.js                                                                | -   
               |  55.50 kB
[ng] src_app_modules_alerts_alerts_module_ts.js                                                              | -   
               |  55.14 kB
[ng] node_modules_ionic_core_dist_esm_ion-alert_entry_js.js                                                  | -   
               |  47.23 kB
[ng] node_modules_ionic_core_dist_esm_ion-refresher_2_entry_js.js                                            | -   
               |  46.56 kB
[ng] src_app_modules_sold-leads_sold-leads_module_ts.js                                                      | -   
               |  42.92 kB
[ng] src_app_modules_academy_academy_module_ts.js                                                            | -   
               |  41.83 kB
[ng] node_modules_ionic_core_dist_esm_ion-segment_2_entry_js.js                                              | -   
               |  36.98 kB
[ng] src_app_modules_introduction_introduction_module_ts.js                                                  | -   
               |  33.73 kB
[ng] node_modules_ionic_core_dist_esm_ion-nav_2_entry_js.js                                                  | -   
               |  32.34 kB
[ng] node_modules_ionic_core_dist_esm_ion-button_2_entry_js.js                                               | -   
               |  32.26 kB
[ng] node_modules_ionic_core_dist_esm_ion-menu_3_entry_js.js                                                 | -   
               |  31.85 kB
[ng] node_modules_ionic_core_dist_esm_ion-searchbar_entry_js.js                                              | -   
               |  31.70 kB
[ng] node_modules_ionic_core_dist_esm_ion-item-option_3_entry_js.js                                          | -   
               |  30.68 kB
[ng] node_modules_firebase_functions_dist_index_esm_js.js                                                    | -   
               |  30.29 kB
[ng] node_modules_ionic_core_dist_esm_ion-action-sheet_entry_js.js                                           | -   
               |  29.60 kB
[ng] src_app_modules_activity_activity_module_ts.js                                                          | -   
               |  29.02 kB
[ng] common.js                                                                                               | common             |  26.98 kB
[ng] node_modules_ionic_core_dist_esm_ion-modal_entry_js.js                                                  | -   
               |  26.49 kB
[ng] node_modules_ionic_core_dist_esm_ion-fab_3_entry_js.js                                                  | -   
               |  26.25 kB
[ng] node_modules_ionic_core_dist_esm_ion-range_entry_js.js                                                  | -   
               |  26.24 kB
[ng] node_modules_ionic_core_dist_esm_ion-select_3_entry_js.js                                               | -   
               |  24.21 kB
[ng] src_app_modules_claims_claims_module_ts.js                                                              | -   
               |  24.09 kB
[ng] node_modules_ionic_core_dist_esm_ion-route_4_entry_js.js                                                | -   
               |  23.52 kB
[ng] src_app_modules_support_support_module_ts.js                                                            | -   
               |  23.40 kB
[ng] node_modules_ionic_core_dist_esm_ion-tab-bar_2_entry_js.js                                              | -   
               |  23.28 kB
[ng] node_modules_ionic_core_dist_esm_ion-toast_entry_js.js                                                  | -   
               |  21.61 kB
[ng] src_app_modules_tabs_tabs_module_ts.js                                                                  | -   
               |  21.54 kB
[ng] node_modules_ionic_core_dist_esm_ion-progress-bar_entry_js.js                                           | -   
               |  21.18 kB
[ng] node_modules_ionic_core_dist_esm_ion-popover_entry_js.js                                                | -   
               |  20.93 kB
[ng] src_app_modules_settings_settings_module_ts.js                                                          | -   
               |  20.75 kB
[ng] polyfills-dom.js                                                                                        | polyfills-dom      |  19.45 kB
[ng] node_modules_ionic_core_dist_esm_ion-input_entry_js.js                                                  | -   
               |  19.34 kB
[ng] default-src_app_core_services_utils_loading_service_ts-src_app_modules_services_firebase_sold-552e2e.js | -   
               |  18.17 kB
[ng] node_modules_ionic_core_dist_esm_ion-virtual-scroll_entry_js.js                                         | -   
               |  17.89 kB
[ng] node_modules_ionic_core_dist_esm_ion-textarea_entry_js.js                                               | -   
               |  17.35 kB
[ng] node_modules_ionic_core_dist_esm_ion-toggle_entry_js.js                                                 | -   
               |  16.98 kB
[ng] node_modules_ionic_core_dist_esm_shadow-css-58508bb5_js.js                                              | -   
               |  15.94 kB
[ng] node_modules_ionic_core_dist_esm_ion-back-button_entry_js.js                                            | -   
               |  15.81 kB
[ng] node_modules_ionic_core_dist_esm_ion-card_5_entry_js.js                                                 | -   
               |  15.63 kB
[ng] node_modules_ionic_core_dist_esm_ion-col_3_entry_js.js                                                  | -   
               |  15.63 kB
[ng] node_modules_ionic_core_dist_esm_ion-radio_2_entry_js.js                                                | -   
               |  15.63 kB
[ng] node_modules_ionic_core_dist_esm_input-shims-bc550f99_js.js                                             | -   
               |  15.22 kB
[ng] node_modules_ionic_core_dist_esm_ion-loading_entry_js.js                                                | -   
               |  14.99 kB
[ng] node_modules_ionic_core_dist_esm_ion-infinite-scroll_2_entry_js.js                                      | -   
               |  12.91 kB
[ng] node_modules_ionic_core_dist_esm_ion-reorder_2_entry_js.js                                              | -   
               |  12.02 kB
[ng] node_modules_ionic_core_dist_esm_ion-checkbox_entry_js.js                                               | -   
               |  11.45 kB
[ng] polyfills-css-shim.js                                                                                   | polyfills-css-shim |  10.65 kB
[ng] node_modules_capacitor_camera_dist_esm_web_js.js                                                        | -   
               |  10.44 kB
[ng] node_modules_ionic_core_dist_esm_ion-chip_entry_js.js                                                   | -   
               |   9.83 kB
[ng] node_modules_ionic_core_dist_esm_ion-split-pane_entry_js.js                                             | -   
               |   9.38 kB
[ng] src_app_modules_listen_listen_module_ts.js                                                              | -   
               |   8.04 kB
[ng] node_modules_ionic_core_dist_esm_ion-spinner_entry_js.js                                                | -   
               |   7.92 kB
[ng] node_modules_ionic_core_dist_esm_ion-tab_2_entry_js.js                                                  | -   
               |   7.65 kB
[ng] src_app_modules_chat_chat_module_ts.js                                                                  | -   
               |   6.64 kB
[ng] node_modules_capacitor_device_dist_esm_web_js.js                                                        | -   
               |   6.46 kB
[ng] node_modules_ionic_core_dist_esm_ion-ripple-effect_entry_js.js                                          | -   
               |   6.09 kB
[ng] node_modules_ionic_core_dist_esm_ion-avatar_3_entry_js.js                                               | -   
               |   5.81 kB
[ng] node_modules_ionic_core_dist_esm_tap-click-71d2324a_js.js                                               | -   
               |   5.61 kB
[ng] node_modules_capacitor_local-notifications_dist_esm_web_js.js                                           | -   
               |   5.52 kB
[ng] node_modules_ionic_core_dist_esm_keyboard-5742b5da_js.js                                                | -   
               |   5.38 kB
[ng] node_modules_ionic_core_dist_esm_ion-backdrop_entry_js.js                                               | -   
               |   3.45 kB
[ng] node_modules_ionic_core_dist_esm_ion-img_entry_js.js                                                    | -   
               |   3.32 kB
[ng] node_modules_capacitor_storage_dist_esm_web_js.js                                                       | -   
               |   3.02 kB
[ng] node_modules_ionic_core_dist_esm_swipe-back-2154c9a7_js.js                                              | -   
               |   2.77 kB
[ng] node_modules_capacitor_geolocation_dist_esm_web_js.js                                                   | -   
               |   2.33 kB
[ng] node_modules_ionic_core_dist_esm_focus-visible-f4ad4f1a_js.js                                           | -   
               |   2.02 kB
[ng] node_modules_ionic_core_dist_esm_ion-text_entry_js.js                                                   | -   
               |   1.74 kB
[ng] node_modules_capacitor_browser_dist_esm_web_js.js                                                       | -   
               |   1.58 kB
[ng] node_modules_capacitor_app_dist_esm_web_js.js                                                           | -   
               |   1.58 kB
[ng] node_modules_ionic_core_dist_esm_status-tap-b46a1b02_js.js                                              | -   
               |   1.50 kB
[ng] node_modules_capacitor_splash-screen_dist_esm_web_js.js                                                 | -   
               |   1.12 kB
[ng] Build at: 2022-01-17T17:32:08.313Z - Hash: 58cb750cbc974a72f626 - Time: 80761ms

[INFO] Development server running!

       Local: http://localhost:8100
       External: http://192.168.8.145:8100

       Use Ctrl+C to quit this process

[ng] √ Compiled successfully.
> capacitor.cmd run android --no-sync --target RF8R70STFHP
[ng] ✔ Browser application bundle generation complete.
[ng] 89 unchanged chunks
[ng] Build at: 2022-01-17T17:32:17.087Z - Hash: f27060ff4f6cd02e3aed - Time: 5075ms
[ng] √ Compiled successfully.
[ng] ✔ Browser application bundle generation complete.
[ng] 89 unchanged chunks
[ng] Build at: 2022-01-17T17:32:21.083Z - Hash: f27060ff4f6cd02e3aed - Time: 2914ms
[ng] √ Compiled successfully.
[capacitor] × Running Gradle build - failed!
[capacitor] [error] WARNING:: Using flatDirs should be avoided because it doesn't support any meta-data formats.
[capacitor]         Currently detected usages:
[capacitor]         - repository flatDir used in: project ':app', project ':capacitor-cordova-android-plugins'     
[capacitor]         WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
[capacitor]         This repository is deprecated and it will be shut down in the future.
[capacitor]         See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
[capacitor]         Currently detected usages in: root project 'android', project ':app', project ':capacitor-android', ...
[capacitor]         WARNING:: The specified Android SDK Build Tools version (29.0.3) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.1.
[capacitor]         Android SDK Build Tools 30.0.2 will be used.
[capacitor]         To suppress this warning, remove "buildToolsVersion '29.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
[capacitor]         > Task :app:preBuild UP-TO-DATE
[capacitor]         > Task :app:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-android:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-android:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-android:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-app:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-app:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-app:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-browser:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-browser:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-browser:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-camera:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-camera:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-camera:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-cordova-android-plugins:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-device:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-device:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-device:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-geolocation:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-geolocation:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-geolocation:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-haptics:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-haptics:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-haptics:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-keyboard:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-keyboard:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-keyboard:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-local-notifications:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-local-notifications:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-local-notifications:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-push-notifications:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-push-notifications:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-push-notifications:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-splash-screen:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-splash-screen:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-splash-screen:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-status-bar:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-status-bar:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-status-bar:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-storage:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-storage:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-storage:compileDebugAidl NO-SOURCE
[capacitor]         > Task :sentry-capacitor:preBuild UP-TO-DATE
[capacitor]         > Task :sentry-capacitor:preDebugBuild UP-TO-DATE
[capacitor]         > Task :sentry-capacitor:compileDebugAidl NO-SOURCE
[capacitor]         > Task :app:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-android:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-app:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-browser:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-camera:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-cordova-android-plugins:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-device:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-geolocation:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-haptics:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-keyboard:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-local-notifications:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-push-notifications:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-splash-screen:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-status-bar:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-storage:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :sentry-capacitor:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :app:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :app:generateDebugBuildConfig UP-TO-DATE
[capacitor]         > Task :app:javaPreCompileDebug UP-TO-DATE
[capacitor]         > Task :capacitor-android:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-app:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-browser:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-camera:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-device:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:writeDebugAarMetadata
[capacitor]         > Task :capacitor-geolocation:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-haptics:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-keyboard:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-local-notifications:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-push-notifications:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-splash-screen:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-status-bar:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-storage:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :sentry-capacitor:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :app:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :app:generateDebugResources UP-TO-DATE
[capacitor]         > Task :app:processDebugGoogleServices UP-TO-DATE
[capacitor]         > Task :capacitor-android:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-android:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-android:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-android:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-app:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-app:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-app:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-app:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-browser:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-browser:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-browser:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-browser:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-camera:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-camera:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-camera:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-camera:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-cordova-android-plugins:generateDebugResValues
[capacitor]         > Task :capacitor-cordova-android-plugins:generateDebugResources
[capacitor]         > Task :capacitor-cordova-android-plugins:packageDebugResources
[capacitor]         > Task :capacitor-device:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-device:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-device:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-device:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-geolocation:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-geolocation:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-geolocation:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-geolocation:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-haptics:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-haptics:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-haptics:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-haptics:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-keyboard:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-keyboard:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-keyboard:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-keyboard:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-local-notifications:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-local-notifications:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-local-notifications:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-local-notifications:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-push-notifications:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-push-notifications:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-push-notifications:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-push-notifications:packageDebugResources UP-TO-DATE
[capacitor]         > Task :app:checkDebugAarMetadata
[capacitor]         > Task :app:checkDebugAarMetadata FAILED
[capacitor]
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]
[capacitor]         * What went wrong:
[capacitor]         Execution failed for task ':app:checkDebugAarMetadata'.
[capacitor]         > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[capacitor]         > Could not resolve com.google.android.play:core:1.+.
[capacitor]         Required by:
[capacitor]         project :app
[capacitor]         project :app > project :capacitor-cordova-android-plugins
[capacitor]         > Failed to list versions for com.google.android.play:core.
[capacitor]         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/play/core/maven-metadata.xml.
[capacitor]         > Could not HEAD 'https://jcenter.bintray.com/com/google/android/play/core/maven-metadata.xml'.[capacitor]         > Read timed out
[capacitor]
[capacitor]         * Try:
[capacitor]         Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[capacitor]
[capacitor]
[capacitor]         Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.    
[capacitor]         * Get more help at https://help.gradle.org
[capacitor]
[capacitor]         BUILD FAILED in 1m 42s
[capacitor]         Use '--warning-mode all' to show the individual deprecation warnings.
[capacitor]         See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings[capacitor]         42 actionable tasks: 4 executed, 38 up-to-date
[capacitor]         42 actionable tasks: 4 executed, 38 up-to-date
[capacitor]
[ERROR] An error occurred while running subprocess capacitor.

        capacitor.cmd run android --no-sync --target RF8R70STFHP exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 12.1.1
   @angular-devkit/schematics    : 12.1.1
   @angular/cli                  : 12.1.1
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.3.0
   @capacitor/android : 3.3.1
   @capacitor/core    : 3.3.0
   @capacitor/ios     : 3.3.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.12
   OS     : Windows 10

`Note`

I can build the project using Android studio and then run that on my native device. The only issue here is with the CLI. 

> ionic build --prod

> npx cap sync android

> npx cap open android

**Comment by jcesarmobile** [comment]
can you provide a sample app where the issue can be reproduced?

**Comment by Sampath-Lokuge** [comment]
Hi JC,

Due to this issue, I turned off my PC and went to sleep at night yesterday. After that, I tried that today and now I'm working on the same app without any issue. Maybe a Windows PC Software issue. Thanks for contacting me.
