### ISSUE TITLE
feat: Switch away from jcenter

### ISSUE THREAD

**Issue by cromefire** [ionic-team/capacitor#5382]
### Description
jcenter seems to become unstable lately (I've been getting 502 errors from time to time) and I don't think anybody will invest a lot of resources in keeping it alive. Adding to that the shutdown is on hold, but it might not be like that forever.

### Platform(s)
Android

### Preferred Solution
Update packages where needed and switch to mavenCentral.

### Alternatives
Using jcenter indefinitely and hoping it'll hold up until all dependencies are upgraded to versions that aren't on jcenter anymore.

### Additional Context
https://blog.gradle.org/jcenter-shutdown

**Comment by jcesarmobile** [comment]
we are removing jcenter in capacitor 4, can't be done sooner because it's a breaking change

we already have an issue for it
https://github.com/ionic-team/capacitor/issues/4266
