### ISSUE TITLE
bug: typescript as a devDependency

### ISSUE THREAD

**Issue by zdrr** [ionic-team/capacitor#5385]
### Current Behavior

When adding a new platform, capacitor cli installs ios and android npm packages which depend on `capacitor/core`, which now has as a `"devDependencies":` `typescript`. When npm tries to install typescript from the`"devDependencies"` it triggers the `prepare` script which depends on global `gulp`. Of course this triggers an error on systems without `gulp` globally installed.

### Expected Behavior
To not depend on libs in `"dependencies": ` and `"devDependencies":` that have `"prepare"` scripts that require globally installed packages.

### Code Reproduction
`npx cap add ios`

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

typescript has always been a devDependency, but devDependencies should not be installed by npm when you install packages.
What are your node/npm versions?

**Comment by zdrr** [comment]
![image](https://user-images.githubusercontent.com/5707490/150788512-623e24a9-7aaf-4e62-b9f5-57f773420369.png)

`node`: `v16.13.2`
`npm`: `8.3.1`

Hi, please excuse my miss understanding regarding the devDeps, I was watching another package. 
It seems that this errors was somehow related to ionic too, not sure why and how. The setup is inside a NX monorepo, thats why we were using the ionic prefix to run capacitor scripts. After multiple tries of re-adding and building the app, re-installing node_modules etc, we are able to build it now without the ionic prefix with the new `capacitor.config`. 

Thanks for the response!
