### ISSUE TITLE
Capture Image(PWA)

### ISSUE THREAD

**Issue by abhibly** [ionic-team/capacitor#539]
Hello I am building a PWA , so user will be able to my app add to his home screen(we dont have plans to use playstore ,no apk generation). And my app should have access to mobile camera. Basically user of my app should be able to take picture and upload the picture to my server just taken.
I have Implememted the following steps to capture my pwa
Created a new app by the below command( Didn't integrate my new app with Cordova)
`ionic start my-app`
`cd my-app`
`npm install --save @capacitor/core @capacitor/cli`
`npx cap init`
`ionic serve`

Below is the code used to capture image
`
              import { Component, NgZone } from '@angular/core';
              import { NavController } from 'ionic-angular';
              import { Plugins, CameraResultType } from '@capacitor/core';

              import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
              import { IonicPage, NavParams } from 'ionic-angular';
              import { CameraSource } from '@capacitor/core';

           @Component({
                 selector: 'page-home',
               templateUrl: 'home.html'
            })
            export class HomePage {

           image: SafeResourceUrl;

          constructor(public navCtrl: NavController, public navParams: NavParams, private zone: NgZone, 
             private sanitizer: DomSanitizer) {
            }

       async takePicture() {
          const { Camera } = Plugins;

         const image = await Camera.getPhoto({
            quality: 90,
            allowEditing: true,
            resultType: CameraResultType.Base64,
             source: CameraSource.Photos
         });

           this.image = this.sanitizer.bypassSecurityTrustResourceUrl(image && (image.base64Data));

            console.log(this.image);
          }

      }
`

As mentioned in this issue https://github.com/ionic-team/capacitor/issues/358 i have included the below line in my index.html
`<script src='https://unpkg.com/@ionic/pwa-elements@0.0.11/dist/ionicpwaelements.js'></script>`

If i run my app using ionic serve and using the system IP address i access the app in my mobile browser. when i click on button to capture the image it just shows a black screen 

Is there anything i am doing wrong.Can anyone please help me to capture image from pwa

**Comment by mlynch** [comment]
Can you get console output and share that? Without it it's not possible to tell what is going on here. Thanks.

**Comment by abhibly** [comment]
@mlynch Sorry for the late reply. I dont see any error in the console when i open camera, but i get this error when try to capture the image `Unable to take photo! DOMException: setOptions failed` .

**Comment by jcesarmobile** [comment]
I don't think it's the same problem. I had the opacity problem, but not the DOMException problem

**Comment by abhibly** [comment]
@jcesarmobile How did you solve the opacity problem?

**Comment by jcesarmobile** [comment]
I didn't, just changed the opacity using chrome dev tools, but that is only useful to see that everything else was working fine.
The fix should be probably done on Ionic 3 or on the PWA elements.

**Comment by abhibly** [comment]
Ok this is how i get when i open camera from my pwa.
![screenshot_20180522-144744](https://user-images.githubusercontent.com/15784815/40353607-87119420-5dcf-11e8-8ace-12e75dc0e1ac.png)

**Comment by jcesarmobile** [comment]
No, I had a light gray screen, no buttons.
What template did you choose when you created the project? and project type? 
Can you share your project?

**Comment by abhibly** [comment]
I opted black template when starting the app(`ionic start myapp blank`).
And this is the project config 
`cli packages: (C:\Users\Shiva\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.9
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Misc:

    backend : legacy`

For reproducing this issue please follow the steps i have mentioned at the beginning of this topic.

**Comment by jcesarmobile** [comment]
Ok, I used that and got a `DOMException: Only secure origins are allowed`. 
That's because ionic serve uses http and for accessing the camera you need https.
If you try in the computer it works because it's localhost and localhost is allowed, but when you try to run on a real device it fails because you use the local IP.

What I've done to make it work is to use a proxy that redirects the http port 8100 to https 8101 and worked fine on Android 8.1 and iOS 11.
Another option would be to host it on internet on a server with https configured.

**Comment by abhibly** [comment]
@jcesarmobile I will have a look at the project and try as u have mentioned. Thank you

**Comment by koshkakosh** [comment]
> @jcesarmobile Ok this is how i get when i open camera from my pwa.Did you get similar kind of error
> ![screenshot_20180522-144744](https://user-images.githubusercontent.com/15784815/40353607-87119420-5dcf-11e8-8ace-12e75dc0e1ac.png)

Hello,
I have the same display problem with a black background without the image of the camera. But this problem only occurs when the pwa application is launched from the ios home screen, not directly from the safari explorer.
I specify that this occurs while the app is hosted on a secure firebase server ...

Here are the features of my app:
    "@capacitor/cli": "^1.0.0-beta.17",
    "@capacitor/core": "^1.0.0-beta.17",
    "@ionic/angular": "4.0.0",
    "@angular/core": "^7.2.2",
    "@angular/pwa": "^0.13.1",
     ...

In index.html : <script src="https://unpkg.com/@ionic/pwa-elements@1.0.1/dist/ionicpwaelements.js"></script>

my code :
1/ page.ts
async uploadPicture(): Promise<void> {
  const { Camera } = Plugins;
  const pic = await Camera.getPhoto({
    quality: 90,
    allowEditing: true,
    resultType: CameraResultType.Base64,
    source: CameraSource.Prompt
  });
  this.avatar.takeAvatarPhoto(pic.base64Data);
  }

2/ avatar.service.ts
... upload to firebase...

![img_0721](https://user-images.githubusercontent.com/41581576/52524436-69127c80-2cb6-11e9-916d-24aee50e6a4f.JPG)
