### ISSUE TITLE
 feat: Native GNU/Linux support

### ISSUE THREAD

**Issue by rzr** [ionic-team/capacitor#5393]
Origin: https://github.com/ionic-team/ionic-framework/issues/24659

### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Supporting regular GNU/Linux OS would be desirable

### Describe the Use Case

Deploy to embedded device (using wayland graphics stack)

**Comment by jcesarmobile** [comment]
Capacitor rely on system provided web views and I don't think there is a standard linux one shipped on all distros.

Linux is supported at the moment by using electron with https://github.com/capacitor-community/electron

We don't plan to add support for other platforms at the moment, but custom platforms are supported, you can take a look at the provided link to see an example of a custom platform and create it yourself if you thing it's possible.
