### ISSUE TITLE
feat: Handle Android dependency version upgrades better

### ISSUE THREAD

**Issue by beruic** [ionic-team/capacitor#5395]
### Description

I just realized that `variables.gradle` in our project contains version numbers that we don't really updates, besides from `minSdkVersion`, `compileSdkVersion` and `targetSdkVersion`. It would be nice if there wwas an easy way to safely upgrade these version.

### Platform(s)
Android

### Preferred Solution

A guide to what each version is required for, and perhaps some command to upgrade all but `minSdkVersion`, `compileSdkVersion` and `targetSdkVersion` to the latest stable.

I can see that the current template at https://github.com/ionic-team/capacitor/blob/main/android-template/variables.gradle is both lacking some we have, an containing some we don't have, so a guide on which to have would be highly appreciated.

### Alternatives

Alternatively I guess they could just have a default version that is maintained by the package.

**Comment by jcesarmobile** [comment]
The capacitor 3 upgrade guide contains that information
https://capacitorjs.com/docs/updating/3-0#update-android-variables

Then, each plugin contains the variables the plugin uses and their default version
i.e. camera https://capacitorjs.com/docs/apis/camera#variables

We recommend using the default versions explained on those guides because google doesn't seem to follow semver and they make breaking changes in minor versions sometimes, so the versions on the upgrade guide and plugin docs are the ones we tested

**Comment by beruic** [comment]
@jcesarmobile How about for Capacitor 3?
Should I even upgrade at all?

**Comment by beruic** [comment]
What I have is:
```
ext {
    minSdkVersion = 28
    compileSdkVersion = 31
    targetSdkVersion = 31
    androidxAppCompatVersion = '1.1.0'
    androidxCoreVersion =  '1.2.0'
    androidxMaterialVersion =  '1.1.0-rc02'
    androidxBrowserVersion =  '1.2.0'
    androidxLocalbroadcastmanagerVersion =  '1.0.0'
    androidxExifInterfaceVersion = '1.2.0'
    firebaseMessagingVersion =  '20.1.2'
    playServicesLocationVersion =  '17.0.0'
    junitVersion =  '4.12'
    androidxJunitVersion =  '1.1.1'
    androidxEspressoCoreVersion =  '3.2.0'
    cordovaAndroidVersion =  '7.0.0'
}
```

**Comment by beruic** [comment]
Sorry, should have mentioned that it was Capacitor 2.

**Comment by beruic** [comment]
@jcesarmobile I just realized I should look at https://github.com/ionic-team/capacitor/blob/2.x/android-template/variables.gradle instead :man_facepalming:
No changes there. Sorry for the inconvenience.
