### ISSUE TITLE
bug: Unable to upgrade an Aurelia app to Capacitor 3

### ISSUE THREAD

**Issue by tcihak-fqa** [ionic-team/capacitor#5396]
## Bug Report
I have followed the "Upgrading to 3.0" migration guide and am unable to get the plugins to work.

### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

Installed Dependencies:

  @capacitor/core: 3.4.0
  @capacitor/cli: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

[success] Android looking great! 👌
```

### Platform(s)

Web
Android

### Current Behavior

For Web:
The following exception is thrown when a plugin method is called.
```
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:9009/scripts/web
```
I can call methods on the Capacitor global such as Capacitor.isNativePlatform() in the Chrome console.

For Android, the app hangs on the splash screen and the following Capacitor errors are in logcat:
```
E/Capacitor: Unable to read file at path public/plugins
E/Capacitor/Console: File: http://localhost/ - Line 286 - Msg: SyntaxError: Unexpected token .
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught SyntaxError: Unexpected token .","url":"http://localhost/scripts/app-bundle.js","line":24206,"col":20,"errorObject":"{}"}}
E/Capacitor/Console: File: http://localhost/scripts/app-bundle.js - Line 24206 - Msg: Uncaught SyntaxError: Unexpected token .
E/Capacitor/Console: File: http://localhost/ - Line 286 - Msg: TypeError: Cannot read property '__useDefault' of undefined
```

### Other Technical Details

The app is written in Aurelia V1
Bundler: Aurelia bundler
Module Loader: requirejs

`npm --version` output:
6.14.8

`yarn --version` output:
1.22.5

`node --version` output:
v14.15.1

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by izeryab** [comment]
Seems like your issue is not really related to Capacitor and i think the problem is you are trying to log something which is undefined(the problem can be your requirejs configuration may be you are unable to load modules and trying to use them). please share if how to reproduce this error

**Comment by tcihak-fqa** [comment]
It may not be but I'm no expert when it comes to bundlers and loaders.
I have attached a very simple Aurelia app that demonstrates the issue in case someone wants to look at it. 
In app.js, it calls Device.getId() and displays the error.

[AureliaCapacitorApp.zip](https://github.com/ionic-team/capacitor/files/7961676/AureliaCapacitorApp.zip)

**Comment by izeryab** [comment]
@tcihak-fqa  load capacitor plugin as script(ambient object) like:
`<script src='./lib/@capacitor/device/dist/plugin.js'></script>`
and then use like:
`declare var capacitorDevice
capacitorDevice.Device.getId()`

**Comment by jcesarmobile** [comment]
the provided project is building to the root, but has www configured as the webDir, so it doesn't work

I changed the aurelia.json like explained in [this SO answer](https://stackoverflow.com/a/46158123/1351469) to build to a different folder (used www instead of OUTPUT) and everything is working as expected. It displays [Object object] as getId returns an object, if I change app.html to `<h4>${deviceId.uuid}</h4>` then it shows the actual id.

**Comment by tcihak-fqa** [comment]
Thanks @jcesarmobile for taking the time to look into this.
I'm pretty sure I followed the SO instructions accurately, but I still have the issue.
I've attached aurelia.json with my changes.

[aurelia.json.zip](https://github.com/ionic-team/capacitor/files/7971687/aurelia.json.zip)

**Comment by jcesarmobile** [comment]
It looks good.
Sorry, I can't be of more help, but this doesn't look like a Capacitor bug.

If it was working fine in Capacitor 2, make sure you are testing in Chrome version 60 or newer as Capacitor 3 had some features that aren't compatible with older versions and that can cause the white screens if you are testing on old emulators or devices with a chrome/chromium/System WebView versions older than 60.

**Comment by tcihak-fqa** [comment]
That's strange that it works for you.
I'm running Version 97.0.4692.99 (Official Build) (64-bit) on Windows.

**Comment by jcesarmobile** [comment]
How are you testing? 
I assumed it was on Android as you included logcat messages, I didn't try on the browser

**Comment by tcihak-fqa** [comment]
I was testing for web only. I simply am doing an 'au run'.

**Comment by jcesarmobile** [comment]
with au run it's also working for me
I attach your project with my modifications
[AureliaCapacitorAppUpdated.zip](https://github.com/ionic-team/capacitor/files/7978429/AureliaCapacitorAppUpdated.zip)

**Comment by tcihak-fqa** [comment]
I'm still getting the same exception with your version.
(I simply downloaded it, ran 'npm install' and ran 'au run')

The vendor-bundle.js has a dynamic import when a DeviceWeb instance is constructed. (line 3686)

```
  var Device = (0, _core.registerPlugin)('Device', {
    web: function web() {
      return import('./web').then(function (m) {
        return new m.DeviceWeb();
      });
    }
  });
```

That seems to be the source of the exception.
```
TypeError: Failed to fetch dynamically imported module: http://localhost:9009/scripts/web
```
I noticed that the DeviceWeb class isn't included in any of the 'www/script' bundle files.

**Comment by jcesarmobile** [comment]
might be some problem with your node version, I tested with node 15 and 16 and it's working fine on both, just tested my zip in a different computer and also worked

**Comment by tcihak-fqa** [comment]
A co-worker tested it out and had the same error. It was a Windows box with node 16. I don't have access to a mac at the moment.
Can you tell where the DeviceWeb class is being loaded from? It's not being bundled for me.

**Comment by jcesarmobile** [comment]
It's the web part of the Device plugin
https://github.com/ionic-team/capacitor-plugins/blob/main/device/src/web.ts

**Comment by tcihak-fqa** [comment]
I wasn't clear. Where in the 'www' folder does it exist after the app is built?

**Comment by jcesarmobile** [comment]
I have no idea, sorry, the bundler you are using is supposed to pick the code and put it into one of the .js files it builds.
BTW, I also tested yesterday on a windows computer with node 14 and also worked, with my zip I just ran `npm install` and `npm start`

**Comment by tcihak-fqa** [comment]
I agree that it's a bundler issue. However, it's strange that we get different results.

I tried a few other project configurations and found that:
- It works in an Aurelia 1 + WebPack app.
- It works in an Aurelia 2 + Dumber (bundler) app.

So it looks like I may have to migrate to a different bundler.
Thanks for your help.

**Comment by tcihak-fqa** [comment]
I was able to get it working by prepending the capacitor.js file and adding an explicit dependency to the Device's CommonJS module in the aurelia.json file.

[AureliaCapacitorApp.zip](https://github.com/ionic-team/capacitor/files/8062210/AureliaCapacitorApp.zip)
