### ISSUE TITLE
bug: Type org.apache.commons.io.input.ReversedLinesFileReader$1 is defined multiple times

### ISSUE THREAD

**Issue by CoooWeee** [ionic-team/capacitor#5399]
## Bug Report

Building an android bundled will fail with:

Type org.apache.commons.io.input.ReversedLinesFileReader$1 is defined multiple times: ./android/capacitor-cordova-android-plugins/build/.transforms/0dd9ea981f0bce90b48eeb353eb5138d/transformed/release/org/apache/commons/io/input/ReversedLinesFileReader$1.dex, ./android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes.dex

### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/ios: 3.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
android

### Current Behavior
can not create bundle or apk in android

### Expected Behavior
builds apk or bundle

### Code Reproduction
Not sure what could cause it. 

### Other Technical Details
osx 12.2, android studio bumblebee

**Comment by jcesarmobile** [comment]
Can you provide a sample app? 
Looks like it's a problem with one of your cordova plugins

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
