### ISSUE TITLE
Input element with capture on android

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#540]
It would be nice if `<input type="file" accept="image/*" capture>` would work on Android.

- Currently works just nice on builds for iOS running in the capacitor webview.
- Also works just fine running on Chrome in Android.
- But doesn't work when running a Capacitor build for Android (in the webview).

For easy testing, this page contains a few html snippets with file input + accept + capture:
http://anssiko.github.io/html-media-capture/

**Comment by mlynch** [comment]
Should be fixed in the next release

**Comment by sandstrom** [comment]
@mlynch Awesome! 🥇
