### ISSUE TITLE
bug: App restarts when taking picture on Android 11

### ISSUE THREAD

**Issue by lucasrleandro** [ionic-team/capacitor#5402]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

Installed Dependencies:

  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/cli: 3.1.2
  @capacitor/ios: 3.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
App restarts after taking picture in Android 11. 
Gallery works fine, but when using CameraSource.Camera, it takes the picture but restarts the app instead of resuming it.

**Comment by jcesarmobile** [comment]
I can't reproduce, but it's documented that it can happen, the OS can kill your app while launching another app (camera plugin launches Camera app using an Intent)

> Additionally, because the Camera API launches a separate Activity to handle taking the photo, you should listen for appRestoredResult in the App plugin to handle any camera data that was sent in the case your app was terminated by the operating system while the Activity was running.

https://capacitorjs.com/docs/apis/camera#android
