### ISSUE TITLE
action buttons for push notification from post request

### ISSUE THREAD

**Issue by MarwaAbuEssa** [ionic-team/capacitor#5404]
### Description
Hi,

I'm using capacitor push notification with google fcm service using https post request from our backend API and everything is working perfect . now I need to add action buttons with input . ex: I need the user when hold on the push notification to display aa button named reply and when select it an input display for the user to reply to the push notification.

like the attached images from  MSteams 

below is a sample of json data sent at the https post request

`{
"to":"cwSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl",
 "notification" : {
     "id":"123545",
     "badge":1,
  "sound" : "short.wav",
  "body" :  "test body",
  "title" : "test title",
  "subtitle":"test again"
 },
 "data" : {
 "page" : "chat"
 }
}`

how can I add the action buttons and the input 

### Platform(s)
ios
capacitor 3.3.4
ionic5

### Preferred Solution
![MicrosoftTeams-image (25)](https://user-images.githubusercontent.com/7272394/152175935-da8da360-c8e7-4ca1-a923-2464aaeac0d1.png)

**Comment by jcesarmobile** [comment]
closing in favor of https://github.com/ionic-team/capacitor-plugins/issues/213
