### ISSUE TITLE
Slow user interactions performance with Svelte js bug: 

### ISSUE THREAD

**Issue by jb-thery** [ionic-team/capacitor#5406]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0
```

### Platform(s)

Ios

### Current Behavior

I try to create a starter app with Capacitor and Svelte. Everything works fine except one thing, when I use native html anchor ( with svelte-routing) for navigate the there is a slow respond time to user interaction, maybe 400ms before app react on my Iphone 13 pro (real device) Ios 15. Same issue for native html buttons across my starter.

### Code Reproduction

the starter repos -> [https://github.com/flameapp-io/svelte-capacitor-tailwind-starter](https://github.com/flameapp-io/svelte-capacitor-tailwind-starter)

My navigation component : 
```javascript
<script lang="ts">
	import ThemeSwitch from '$lib/ThemeSwitch.svelte';
	import { Link } from 'svelte-routing';
	type NavLink = {
		name: string;
		url: string;
	};
	const navLinks: Array<NavLink> = [
		{
			name: 'Home',
			url: '/'
		},
		{
			name: 'Example',
			url: 'example'
		}
	];
</script>

<nav class="flex items-center">
	{#each navLinks as link}
		<Link to={link.url} class="mx-5">{link.name}</Link>
	{/each}

	<ThemeSwitch />
</nav>
```

### Other Technical Details

`npm --version` output: 8.4.0

`node --version` output: v16.13.2

`pod --version` output (iOS issues only): 1.11.2

**Comment by jcesarmobile** [comment]
Does it also happen on Android? you only mention an iOS device but added both.
Does it also happen when testing on a mobile web browser?

**Comment by jb-thery** [comment]
I've not tested on Android, web version is fast but ios simulator or real device not

**Comment by jcesarmobile** [comment]
Can you also test on chrome for iOS?

**Comment by jcesarmobile** [comment]
Historically there has been a 300ms delay on clicks that gets removed if your app is not scalable, looking at your app, it has initial scale of 1, but doesn't prevent scaling.
Check this article from Google
https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

In example Ionic official templates have this viewport
`<meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>`

https://github.com/ionic-team/starters/blob/main/vue/base/public/index.html#L10-L13

try using that and see if the problem goes away

**Comment by jb-thery** [comment]
It's work ! thanks
