### ISSUE TITLE
bug: All installed capacitor plugins suddenly not working

### ISSUE THREAD

**Issue by ryansyrl** [ionic-team/capacitor#5407]
### Capacitor Version

```
"@capacitor/android": "3.3.3",
    "@capacitor/app": "1.0.7",
    "@capacitor/camera": "^1.2.4",
    "@capacitor/core": "3.3.3",
    "@capacitor/device": "^1.1.1",
    "@capacitor/filesystem": "^1.0.6",
    "@capacitor/geolocation": "^1.3.0",
    "@capacitor/haptics": "1.1.3",
    "@capacitor/keyboard": "1.2.0",
    "@capacitor/network": "^1.0.6",
    "@capacitor/status-bar": "1.0.6",
    "@capacitor/storage": "^1.2.4",

"@ionic/vue": "^6.0.1",
"vue": "^3.2.21",
```

### Platform(s)

Android

### Current Behavior

so when i run the emulator on my device suddenly all my installed capacitor plugins not working. few hours before all of it works just fine. what went wrong??

![image](https://user-images.githubusercontent.com/67872022/152349657-f80439e9-0aae-45d7-bb1a-aa666fa5c004.png)
![image](https://user-images.githubusercontent.com/67872022/152349648-331b4f71-86c3-4480-bb12-b966560acced.png)

### Expected Behavior

when i start the emulator on my device, my device is not even asking for permission for using camera or geolocation (after i delete the app and try to install it again using android studio).

### Code Reproduction

CAMERA PERMISSION
import { Camera } from '@capacitor/camera';
import { ref } from 'vue'

const CAMERA_PERMISSION = () => {
    const camPermission = ref('')
    const photosPermission = ref('')
    const GET_PERMISSION = async () => {
        const permission = await Camera.requestPermissions();
        camPermission.value = permission.camera
        photosPermission.value = permission.photos
    }
    return { GET_PERMISSION, camPermission, photosPermission }
};
export default CAMERA_PERMISSION

USING CAMERA PERMISSION API
import CAMERA_PERMISSION from "@/native-function/camera/permission";
    const { GET_PERMISSION } = CAMERA_PERMISSION();
const getPermission = async () => {
      await GET_PERMISSION();
    };
    getPermission();

GEOLOCATION PERMISSION
import { ref } from 'vue'
import { Geolocation } from "@capacitor/geolocation";

const USER_GEOLOCATION = () => {
    const userPosition = ref('');
    const FETCH_GEOLOCATION = async () => {
        let pos = await Geolocation.getCurrentPosition();
        userPosition.value = pos.coords
    }
    return { userPosition, FETCH_GEOLOCATION }
};

export default USER_GEOLOCATION

USING GEOLOCATION API
import USER_GEOLOCATION from "@/native-function/userGeoLocation";
    const { FETCH_GEOLOCATION, userPosition } = USER_GEOLOCATION();
const positions = async () => {
      await FETCH_GEOLOCATION();
    };
    positions();

USING STORAGE API
import { Storage } from "@capacitor/storage";
const checkUser = async () => {
      let getUser = await Storage.get({ key: "credentials" });
      let user = JSON.parse(getUser.value);
      if (user) {
        password.value = user.password;
        username.value = user.username;
      }
    };
    checkUser();

### Other Technical Details

`npm --version` output:
6.14.15
`node --version` output:
v14.18.2
`pod --version` output (iOS issues only):

### Additional Context

I am using XIAOMI POCOPHONE F1 for the physical emulator & running on ANDROID 10

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
Thanks for the sample app

The problem is that the url you are using is invalid, it should contain the scheme too (http or https), i.e. `http://192.168.2.105:8100`. It's not the first time that an user faced a similar issue, so I've created a new issue to show some error when the url is incorrect instead of loading the app that won't work properly.

https://github.com/ionic-team/capacitor/issues/5408
