### ISSUE TITLE
After Capacitor migration from 2.3.0 to 3.4.0 - Cordova plugins for android, skipped install

### ISSUE THREAD

**Issue by SatheeshKumarBalu** [ionic-team/capacitor#5409]
update android [info] Found 3 incompatible Cordova plugins for android, skipped install:
       Keychain@2.0.1
       com.shazron.cordova.plugin.keychainutil@2.0.1
       cordova-plugin-ionic-keyboard@2.2.0

**Comment by jcesarmobile** [comment]
Keyboard plugin has always been in the incompatible list, you have to use the @capacitor/keyboard one

the others appear as incompatible because they don’t have android code, they are iOS only

**Comment by SatheeshKumarBalu** [comment]
Yes.. As you said I have skipped the android platform and its working fine for android. 

**Thank You..!**

For iOS I'm getting this error any idea ?

![image](https://user-images.githubusercontent.com/34299834/152527364-9c4a5bdf-1ce5-4840-a88d-ab798076c7e6.png)

**Comment by jcesarmobile** [comment]
looks like some permission problem with CocoaPods, are you using sudo in the commands?
Googling "You cannot run CocoaPods as root" I find a lot of approaches, not sure which one might be the best one, but here you have one of them
https://stackoverflow.com/questions/65944484/you-cannot-run-cocoapods-as-root-claidehelp-flutter
