### ISSUE TITLE
bug: Accessing backButton event from Capacitor Object

### ISSUE THREAD

**Issue by Danbardo** [ionic-team/capacitor#5413]
### Capacitor Version
  @capacitor/android: 3.3.3
  @capacitor/cli: 3.3.3
  @capacitor/core: 3.3.3

### Platform(s)
Android

### Current Behavior
The backButton event is instantly triggered when registering the event via the Capacitor object.

### Expected Behavior
The backButton event to be triggered when the backButton is pressed.

### Code Reproduction
I have built a Capacitor application with Vanilla JS and no compiler. I have successfully created an application with working push notifications and several other plugins.

`npm install @capacitor/core`
`npm install @capacitor/android`
`npm install @capacitor/push-notifications`

An example project could consist of a html file with an individual JavaScript dependency.

Within this JavaScript file I can access each of the plugins from the Capacitor object directly (no importing), for example:

`Capacitor.Plugins.PushNotifications.register();`

I am trying to register the backButton listener in a similar manner.

I have tried to call addListener from the Capacitor object itself, and other plugins, but they do not catch the backButton press.

`Capacitor.addListener('App','backButton',function(){});`

`Capacitor.Plugins.Device.addListener(''backButton',function(){});`

I believe the issue is that the Plugins object does not contain an "App" property in which the addListener method seems to be called in the answers provided within the Capacitor documentation.

How can I add the backButton listener using the above approach?

With Cordova the backButton event is transmitted through the DOM, so it is very easy to setup a listener, is that possible here?

I would very much appreciate an answer in line with the problem I pose, I am deliberately using Capacitor in this way.

Thanks in advance

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Danbardo** [comment]
I have added more details to the reproduction

**Comment by Danbardo** [comment]
The issue was that I didn't install the App plugin. For some reason I thought it was apart of the core.
