### ISSUE TITLE
Deep Links Support

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#542]
Deep links are useful for many things (linking from emails into app content, for single sign-on flows, etc). Since Capacitor / Ionic are focusing on PWAs and the ability to write apps for native + web, being able to control where/how content is opened is even more useful.

Is deep links support on the radar?

The two Cordova plugins that support this today are:
- https://github.com/nordnet/cordova-universal-links-plugin
- https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking

There is also this custom url scheme plugin (somewhat related to deep links):
https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by mlynch** [comment]
They’re already supported. See the App API’s https://capacitor.ionicframework.com/docs/apis/app#method-addListener-1

**Comment by sandstrom** [comment]
Awesome @mlynch! 🎉 🌟

**Comment by WB3Tech** [comment]
@mlynch, is there an example of how to do this? I'm new to Ionic and Ionic Capacitor and am looking to set this up on for my Angular 7 app.

**Comment by sandstrom** [comment]
@WB3Tech This isn't the right forum for support question. Stackoverflow or similar would be better.

That said, it's fairly well documented in the docs referenced above.

**Comment by mlynch** [comment]
@WB3Tech use the `App.getLaunchUrl` method to get any URL used to launch the app, then listen for the `App.addListener('appUrlOpen', (data) => data.url...)` event

**Comment by seanharr11** [comment]
@mlynch when using Ionic, we are able to capture the `appUrlOpen` event and get the URL for the universal link that opened the app. How do we navigate to this URL? I have tried this:

```
  IonicApp.addListener("appUrlOpen", (data) => {
    console.log("Opened app via universal link", data);
    const path = data.url.replace("http://", "").replace("https://", "").split("/").slice(1);
    const page = path.join("/");
    console.log("In APP! Navigating to: ", page);
    history.push({pathname: `/${page}`});
  });
```

...but there is currently [no way to inject a custom `history` prop into the `IonRouter`](https://github.com/ionic-team/ionic/issues/20297), thus we don't have a handle on `history` in these listeners. 

In the React case, do you suggest we nest these listeners within a routed React component (_e.g. to access the `history` prop_)? I have tried, and gotten app crashes...

More than happy to move this to StackOverflow, but this was the only place that I landed when google searching this topic.

**Comment by tx-tim** [comment]
@seanharr11 Were you able to get this figured out?

**Comment by madmacc** [comment]
Looks like the guide is not linked to in here so I thought I would add it:
https://capacitorjs.com/docs/guides/deep-links
