### ISSUE TITLE
bug: Error "Storage" plugin is not implemented on android

### ISSUE THREAD

**Issue by joshuaGnol** [ionic-team/capacitor#5430]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/ios: 3.3.1
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5

```

### Platform(s)
Android

### Current Behavior

Hi, there's errors from Sentry for Android. the plugin is working fine for both iOS and Android, just that there's errors that reported on Sentry. Could not simulate the error, only received the error from Sentry. Below is the sentry log, capacitor config and Main Activity. The Main Activity is just extend the BridgeActivity. Thank you.

**Sentry log**
````
{
arguments: [
{
code: UNIMPLEMENTED, 
message: "Storage" plugin is not implemented on android, 
name: Error, 
stack: 
Error: "Storage" plugin is not implemented on android
    at http://localhost/main.5b7ba08311886afb1ae8.js:1:1904058
    at http://localhost/main.5b7ba08311886afb1ae8.js:1:1904349
    at l.invoke (http://localhost/polyfills.2dc45994e1360d070fed.js:1:15322)
    at Object.onInvoke (http://localhost/main.5b7ba08311886afb1ae8.js:1:1446849)
    at l.invoke (http://localhost/polyfills.2dc45994e1360d070fed.js:1:15262)
    at a.run (http://localhost/polyfills.2dc45994e1360d070fed.js:1:10734)
    at http://localhost/polyfills.2dc45994e1360d070fed.js:1:21667
    at l.invokeTask (http://localhost/polyfills.2dc45994e1360d070fed.js:1:15940)
    at Object.onInvokeTask (http://localhost/main.5b7ba08311886afb1ae8.js:1:1446665)
    at l.invokeTask (http://localhost/polyfills.2dc45994e1360d070fed.js:1:15861)
    at a.runTask (http://localhost/polyfills.2dc45994e1360d070fed.js:1:11349)
    at y (http://localhost/polyfills.2dc45994e1360d070fed.js:1:17934)
}
], 
logger: console
}

````
**capacitor config**

````
{
    webDir: 'dist/qnnect-desktop',
    bundledWebRuntime: false,
    loggingBehavior: 'production',
    plugins: {
        SplashScreen: {
            launchAutoHide: false,
            splashFullScreen: true,
            layoutName: 'activity_splash',
            useDialog: true,
        },
        LocalNotifications: {
            smallIcon: 'notification_icon',
        },
    },
}
````

MainActivity.java

````
package com.example;
import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {}

````

### Expected Behavior
Should not have error reported.

### Other Technical Details

`npm --version` output: 6.14.5

`node --version` output: v12.18.2

### Additional Context

similar issue - https://github.com/ionic-team/capacitor/issues/4791#issuecomment-892729756

document found - https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading

**Comment by jcesarmobile** [comment]
Check https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented, it contains a few things that can cause the issue.
Also try updating all the capacitor packages to the latest ones and use the same version on all of them.

**Comment by tobias-kuendig** [comment]
I was able to resolve the issue by removing the compiled frontend files and plugins and running `npx cap sync android` again:

```bash
rm -rf android/app/src/main/assets/*
rm -rf android/capacitor-cordova-android-plugins
npx cap sync android
```

If this is not enough, try running the `Clean project` action in Android Studio

**Comment by aschwerdt** [comment]
I resolved this issue by disabling minify.
```
 buildTypes {
        release {
            ...
            minifyEnabled false
            ...
        }
    }
```
version:
"@capacitor/core": "^3.5.0"
"@capacitor/storage": "^1.2.5"

**Comment by vikicoder007** [comment]
@capacitor/storage was working perfectly fine but after updating it to @capacitor/preferences its throwing "Storage" plugin is not implemented on android

**Comment by MaxWeisen** [comment]
@vikicoder007 I have the same exact issue except on iOS
`"Storage" plugin is not implemented on ios`
<img width="1239" alt="Screen Shot 2022-09-29 at 3 13 22 PM" src="https://user-images.githubusercontent.com/71942151/193151539-fc996f1f-5497-4034-8405-229be19a8bd8.png">

**Comment by arnodchirivi08** [comment]
Hello friends
I am also getting this error but with share plugin.
I have the version
"@capacitor/android": "^4.1.0",
"@capacitor/cli": "^4.1.0",
"@capacitor/ios": "^4.1.0",
I have done everything that they say in this forum but nothing has worked for me, does anyone know what can be done
