### ISSUE TITLE
StartActivityForResult doestn't work if service is started on intent

### ISSUE THREAD

**Issue by Apiyo4** [ionic-team/capacitor#5433]
I would like to return some data after the service stops, I'm using startActivityForResult to start the service and I'm getting this error :   Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.app/com.example.app.BtnClickedService}; have you declared this activity in your AndroidManifest.xml?
The service has been declared in the manifest and I'm not sure if startActivityForResults only works with Activities and not Service and if it only works with Activities what is the alternative for when you want to get results returned to the plugin after the service finishes.

Here is a link of the same: https://github.com/Apiyo4/activityCallbackApp-capacitor

**Comment by angeloraso** [comment]
- Hi @Apiyo4. I think you have to use a ServiceConnection 
- Something like that

```
private ServiceConnection mConnection = new ServiceConnection() {
        public void onServiceConnected(ComponentName className, IBinder iBinder) {
            // Something
        }

        public void onServiceDisconnected(ComponentName className) {
            // Something
        }
    };
```

**Comment by Apiyo4** [comment]
@angeloraso, thanks, for the above, added the same but still not sure how to return data once the service as ended, that is once the the buttons have been clicked.

**Comment by jcesarmobile** [comment]
`startActivityForResults` is for starting activities only, for services you'll have to use something else, the what will depend on the service and your android development knowledge.
I would use callbacks or listeners
Those are not services, but maybe it can help you to see how to use listeners from a class that is not a plugin class
https://github.com/ionic-team/capacitor-plugins/blob/main/network/android/src/main/java/com/capacitorjs/plugins/network/Network.java#L22-L38
https://github.com/ionic-team/capacitor-plugins/blob/main/network/android/src/main/java/com/capacitorjs/plugins/network/NetworkPlugin.java#L24-L34
