### ISSUE TITLE
bug: New local plugin doesn't compile

### ISSUE THREAD

**Issue by Cyral** [ionic-team/capacitor#5436]
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

### Platform(s)
N/A

### Current Behavior
Newly created plugin should compile with `npm run build`

### Expected Behavior
Compilation fails:

```
> test@0.0.1 build
> npm run clean && npm run docgen && tsc && rollup -c rollup.config.js


> test@0.0.1 clean
> rimraf ./dist


> test@0.0.1 docgen
> docgen --api testplPlugin --output-readme README.md --output-json dist/docs.json


✔️ DocGen Output: /frontend/app/testpl/dist/docs.json
✔️ DocGen Output: /frontend/app/testpl/README.md

../node_modules/@types/eslint-scope/node_modules/@types/eslint/helpers.d.ts:1:6 - error TS2300: Duplicate identifier 'Prepend'.

1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
       ~~~~~~~

  ../node_modules/@types/eslint/helpers.d.ts:1:6
    1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
           ~~~~~~~
    'Prepend' was also declared here.

../node_modules/@types/eslint/helpers.d.ts:1:6 - error TS2300: Duplicate identifier 'Prepend'.

1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
       ~~~~~~~

  ../node_modules/@types/eslint-scope/node_modules/@types/eslint/helpers.d.ts:1:6
    1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
           ~~~~~~~
    'Prepend' was also declared here.


Found 2 errors.

```

### Code Reproduction
Create a new plugin with `npm init @capacitor/plugin`, then run `npm run build`

### Other Technical Details
NPM Version: 8.3.1
Node Version: v16.14.0
Tested on Mac

**Comment by Cyral** [comment]
I'm realizing that the error involves ../node_modules which is the node_modules of the parent app. Upon creating a blank capacitor app with a local plugin, the issue doesn't occur. I will keep looking to see why it is happening on my app and not a new one.

**Comment by simonwalsh** [comment]
Ah! Thanks

@Cyral you just saved my ass 😄
