### ISSUE TITLE
bug: After App Update, App always opens in dark mode

### ISSUE THREAD

**Issue by iamkbkarthikeyan** [ionic-team/capacitor#5441]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1

### Platform(s)
 Android

### Current Behavior

I have 10+ ionic projects on my phone, After getting Google Play update. All apps are opening only on dark mode. If i remove dark mode related media queries. It works. But When app initialization. 1-2 sec(s) the dark screen shows. If anybody face this same issue. Please let me know. How we resolve this.

**Comment by jcesarmobile** [comment]
what's your Android version?
What's your chrome/system WebView version?

I've seen this happen in the past, but seems solved on latest System WebView update (version 98.0.4758.101)

**Comment by lajith111** [comment]
> ## Bug Report
> ### Capacitor Version
> Latest Dependencies:
> 
> @capacitor/cli: 3.4.1 @capacitor/core: 3.4.1 @capacitor/android: 3.4.1 @capacitor/ios: 3.4.1
> 
> Installed Dependencies:
> 
> @capacitor/ios: not installed @capacitor/cli: 3.4.1 @capacitor/core: 3.4.1 @capacitor/android: 3.4.1
> 
> ### Platform(s)
> Android
> 
> ### Current Behavior
> I have 10+ ionic projects on my phone, After getting Google Play update. All apps are opening only on dark mode. If i remove dark mode related media queries. It works. But When app initialization. 1-2 sec(s) the dark screen shows. If anybody face this same issue. Please let me know. How we resolve this.

**Comment by lajith111** [comment]
I am also using the latest version of capacitor in one of ionic  project..App installed in Android 11 device(my friend)  automatically turns to dark mode...in my device Android 8.1 there is no issues are found...Thanks .

**Comment by gion-andri** [comment]
> I've seen this happen in the past, but seems solved on latest System WebView update (version 98.0.4758.101)

I still see this issue in Android System WebView version 98.0.4758.101

**Comment by distante** [comment]
I am also having this problem but a little bit more extreme.

Yes the app starts on Dark Mode and it **forces** the dark mode on the phone. I can not change dark mode anymore unless I run `adb shell settings put global low_power_sticky 0`. and **reboot the phone**.

This is happening with a Poco F3 with MIUI 12.5.7 (Android 11).

My app has all the latest Capacitor updates until today.

**Comment by lajith111** [comment]
Is ther any temp fix? Which lower version it is is working fine..please le me know

**Comment by jcesarmobile** [comment]
This is a bug on System WebView 98, that appears to be fixed on System WebView 99, it's still in dev at the moment, the final release is scheduled for March 1st.

For Ionic users, you can disable the dark theme entirely for your app as explained here
https://github.com/ionic-team/ionic-framework/issues/24771#issuecomment-1050038347

But that will also remove the automatic light-dark mode change based on user settings for iOS.

**Comment by Sibi4** [comment]
@lajith111

In index.html, remove 'dark' from `<meta name="color-scheme" content="light dark" />`

In variables.css, remove completely `@media (prefers-color-scheme: dark) { body { . . . } }` section.

Further Info: https://github.com/ionic-team/ionic-framework/issues/24771

**Comment by jcesarmobile** [comment]
We [reported a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1312074) on chromium repository and looks like the WebView will now match the theme of the app. 
Capacitor apps use a dark theme by default, so all Capacitor apps will have dark mode enabled by default.

If you want to force light mode you can set a light theme by changing this line in `res/values/styles.xml`

`<style name="AppTheme.NoActionBar" parent="Theme.AppCompat.NoActionBar">`
to
`<style name="AppTheme.NoActionBar" parent="Theme.AppCompat.Light.NoActionBar">`
or if you want it to automatically change based on the user setting you can use
`<style name="AppTheme.NoActionBar" parent="Theme.AppCompat.DayNight.NoActionBar">

note that the theme change also affects other system dialogs such as web alert/prompt/confirm and the native equivalents  from @capacitor/dialog plugin.

**Comment by JorisDebonnet** [comment]
For what it's worth, installing [@robingenz/capacitor-android-dark-mode-support](https://github.com/robingenz/capacitor-android-dark-mode-support/) successfully fixes this issue.

**Comment by sinan92** [comment]
> For what it's worth, installing [@robingenz/capacitor-android-dark-mode-support](https://github.com/robingenz/capacitor-android-dark-mode-support/) successfully fixes this issue.

This works. But it's sad to have to install a plugin to make Ionic work the way it is supposed to work. Hopefully this gets fixed soon.

**Comment by JorisDebonnet** [comment]
> > For what it's worth, installing [@robingenz/capacitor-android-dark-mode-support](https://github.com/robingenz/capacitor-android-dark-mode-support/) successfully fixes this issue.
> 
> This works. But it's sad to have to install a plugin to make Ionic work the way it is supposed to work. Hopefully this gets fixed soon.

I read that it should natively work now, in Capacitor 4. (Didn't try it myself yet.)
