### ISSUE TITLE
bug: Cilico device uses wrong WebView (version 52)

### ISSUE THREAD

**Issue by OscarBouwmans** [ionic-team/capacitor#5450]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android 7.1.1, on a Cilico scanner device.

### Current Behavior

Via _chrome://inspect_ on a computer, it is clear that the WebView used is version 52. However, Chrome and Android System WebView are both at version 98, installed via Google Play.

<img width="480" alt="Cilico Chrome vs WebView version" src="https://user-images.githubusercontent.com/22990260/154956038-78de980c-d253-4b8d-a64d-82a3ac588400.png">

The Android app builds just fine and launches, but then it shows a white screen and no web view content is loaded (because the build output includes an async function, which is not supported in this wrong WebView).

### Expected Behavior

The Capacitor app uses Chrome or Android System WebView.

### Code Reproduction

There is not a code reproduction for this.

### Other Technical Details

Cilico device used: F880
Android version: 7.1.1
Kernel version: 4.4.15
Installed Chrome version: 98.0.4758.101
Installed Android System WebView version: 98.0.4758.101

`npm --version` output: 6.14.13 (same results with 8.3.1)

`node --version` output: v14.17.2 (same results with v16.14.0)

### Additional Context

I understand the Capacitor team cannot support every single flavour of Android software/hardware out there, especially when it comes to niche products like scanners. But perhaps a similar issue was seen in the past, or maybe there are ideas on how to 'force' Capacitor to use the correct WebView?

**Comment by jcesarmobile** [comment]
Sadly there is nothing we can do about this, the device vendors are supposed to use the updatable WebView, but some don't follow Google's rules and use their own fixed version, which in this case is very old for Capacitor to work.

There is an issue open for showing an error instead of the white screen when the WebView version is too old, but won't fix your problem anyway.
https://github.com/ionic-team/capacitor/issues/4884

**Comment by OscarBouwmans** [comment]
That's unfortunate, but I totally get it…
Thanks for the quick reply!
