### ISSUE TITLE
Add allowsInlineMediaPlayback to WKWebViewConfiguration

### ISSUE THREAD

**Issue by maxcodefaster** [ionic-team/capacitor#5453]
## Bug Report
When playing html5 videos in webview we get this error:
```
ProcessAssertion: Failed to acquire RBS assertion 'WebKit Media Playback' for process with PID=540, error: Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)" UserInfo={NSLocalizedFailureReason=(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)}
```

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/ios: 3.3.4

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

When playing html5 videos (does not matter if with inline, muted, autplay tag etc.) we get the above error, until the app crashes eventually. It does not crash right away, but throws this error multiple times. Video sometimes get scaled to a very small size and then the app crashes. 

### Expected Behavior

Video should just play

### Other Technical Details

`npm --version` output:
8.1.2

`node --version` output:
v16.13.1

`pod --version` output (iOS issues only):
1.11.2

### Additional Context

Possible solution can be to add this https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1614793-allowsinlinemediaplayback?language=objc to WKWebViewConfiguration

**Comment by jcesarmobile** [comment]
It’s already set to true
https://github.com/ionic-team/capacitor/blob/2b7016f3b4d62fd8c9d03fde2745b3d515bf08b2/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L104

can you provide a sample app?

**Comment by maxcodefaster** [comment]
It seems to be related to a WebViewIssue loading Object Urls into the video Tag. See:

https://bugs.webkit.org/show_bug.cgi?id=232076
https://bugs.webkit.org/show_bug.cgi?id=232195

**Comment by vycoder** [comment]
Encountering the same issue but on audio players. I'm using `tone.js` to play sounds. This error pops up when building for iOS. I tried adding Capabilities like `Audio, Airplay and Picture in Picture` in `Background Modes` to no avail.

**Comment by danielehrhardt** [comment]
> Encountering the same issue but on audio players. I'm using `tone.js` to play sounds. This error pops up when building for iOS. I tried adding Capabilities like `Audio, Airplay and Picture in Picture` in `Background Modes` to no avail.

Did you found a solution?

**Comment by vycoder** [comment]
@danielehrhardt not really. The audio is playing but the error just keep popping up on the console. It doesn't seem to affect audio playing in any way (not that I'm aware of currently). At this point, I'm just ignoring those logs.

**Comment by cordial** [comment]
> 

Which instrument or player were you using from tone.js? I'm getting this error without any sound when using an Oscillator.

**Comment by cordial** [comment]
> > 
> 
> Which instrument or player were you using from tone.js? I'm getting this error without any sound when using an Oscillator.



> @danielehrhardt not really. The audio is playing but the error just keep popping up on the console. It doesn't seem to affect audio playing in any way (not that I'm aware of currently). At this point, I'm just ignoring those logs.


Which instrument or player were you using from tone.js? I'm getting this error without any sound when using an Oscillator.
