### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by pabloservin** [ionic-team/capacitor#5461]
### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 3.4.1    
  @capacitor/core: 3.4.1   
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1    

Installed Dependencies:    

  @capacitor/ios: not installed
  @capacitor/cli: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/core: 3.4.1

[success] Android looking great! 👌
```

### Platform(s)
Android 6 (API 23)

### Current Behavior
App is stuck in a blank screen after splashscreen
In the Android Studio logcat and inspect tool by chrome the following syntax error show: "Unexpected token =>"

It works fine on newer versions, only happens in android 6.0.0 both on emulator and on real device.

### Other Technical Details

`npm --version` : 7.24.2

`node --version` : 16.14.0

**Comment by jcesarmobile** [comment]
Capacitor requires System WebView => 60 to be installed on the device, older versions cause this kind of problems.

There is a feature request to show some error screen instead of failing to load 
https://github.com/ionic-team/capacitor/issues/4884

**Comment by pabloservin** [comment]
Yes, I have faced this issue in the past and forgot about updating the webview, I just remembered 5 minutos after opening the issue. Thank you anyway @jcesarmobile
