### ISSUE TITLE
Hide scroll bar in android app

### ISSUE THREAD

**Issue by mohammad0-0ahmad** [ionic-team/capacitor#5469]
### Discussed in https://github.com/ionic-team/capacitor/discussions/5416

<div type='discussions-op-text'>

<sup>Originally posted by **mohammad0-0ahmad** February  8, 2022</sup>
Hello!

I've tried to hide the scroll bar in Android app that is created by using capacitor and next.js and I couldn't  do so in web source code.
I ended up to modify @capacitor\android\capacitor\src\main\java\com\getcapacitor\CapacitorWebView.java file by adding  the following line inside constructure function:
```java
    public CapacitorWebView(Context context, AttributeSet attrs) {
        super(context, attrs);
   +     setVerticalScrollBarEnabled(false);
    }
```

That line could hide the scrollbar but I wonder if I can hide it from my source code instead because I couldn't find a solution for that in the docs.

Best regardes.

![Screenshot_1644343438](https://user-images.githubusercontent.com/50488054/153048856-e80a3651-5c6e-421e-8937-437c61e077de.png)

</div>

**Comment by ThinhVu** [comment]
/* Hide scrollbar for IE, Edge and Firefox */
.hide-scroll-bar {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}

/* Hide scrollbar for Chrome, Safari and Opera */
.hide-scroll-bar::-webkit-scrollbar {
  display: none;
}

**Comment by mohammad0-0ahmad** [comment]
> /* Hide scrollbar for IE, Edge and Firefox _/ .hide-scroll-bar { -ms-overflow-style: none; /_ IE and Edge _/ scrollbar-width: none; /_ Firefox */ }
> 
> /* Hide scrollbar for Chrome, Safari and Opera */ .hide-scroll-bar::-webkit-scrollbar { display: none; }

Thanks for your answer, but does this work with MUI? With other words, I am not using ionic-ui solution

**Comment by ThinhVu** [comment]
> > /* Hide scrollbar for IE, Edge and Firefox _/ .hide-scroll-bar { -ms-overflow-style: none; /_ IE and Edge _/ scrollbar-width: none; /_ Firefox */ }
> > /* Hide scrollbar for Chrome, Safari and Opera */ .hide-scroll-bar::-webkit-scrollbar { display: none; }
> 
> Thanks for your answer, but does this work with MUI? With other words, I am not using ionic-ui "components" solution

It's CSS, and it'll work in every devices.

**Comment by jcesarmobile** [comment]
You can create a plugin and put this code in the load method
```
public void load() {
    bridge.getWebView().setVerticalScrollBarEnabled(false);
}
```

Or without a plugin you can put this code in the MainActivity.java

```
    @Override
    public void onStart() {
        super.onStart();
        bridge.getWebView().setVerticalScrollBarEnabled(false);
    }
```

**Comment by mohammad0-0ahmad** [comment]
I will check that soon, thanks for your answers @jcesarmobile  @ThinhVu.
