### ISSUE TITLE
getPhoto call from useCamera results in split photo

### ISSUE THREAD

**Issue by arthrotech** [ionic-team/capacitor#5471]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.5.0
  @capacitor/core 2.5.0
  @capacitor/ios 2.5.0
  @capacitor/electron not installed

[error] Xcode is not installed
```

### Platform(s)
web

### Current Behavior
Taking a photo results in the image being split - see screenshot - it occurs consistently based on what you're taking a photo of - that is if i take a photo of the monitor as shown below it will always split - taking photos of other items works normally

### Expected Behavior
Expecting the photo to display as per the preview - not adjusted in anyway

![jhZckqSFdw5MAdAmKVZ41z](https://user-images.githubusercontent.com/96405775/156086464-64684040-c4d7-46a8-b065-9df85c77bb77.jpeg)

```
const photo = await Camera.getPhoto({
      resultType: CameraResultType.Uri,     
    });
```

One more thing i have noticed is the `direction` option is not respected, at least on my pixel4a - it defaults to the front facing camera

**Comment by jcesarmobile** [comment]
Try updating to capacitor 3 and latest version of pwa-elements, there have been a few improvements like adding support for direction and might have fixed this problem too, I can’t reproduce with latest versions.

**Comment by arthrotech** [comment]
upgrading to capacitor 3 does not fix the problem - would you mind not closing the bug

**Comment by jcesarmobile** [comment]
Create a new issue and provide a sample app where the problem can be reproduced.

**Comment by arthrotech** [comment]
@jcesarmobile  all the information is above - i have given you a recreate namely

Capacitor 3.4.1 latest
google pixel4a

When you 'can't recreate' it due to not having the device are you just going to close the bug again? Just reopen it here

**Comment by jcesarmobile** [comment]
You have not provided a sample app where it can be reproduced, so no, all the information is not above. That minimal code is not enough, sorry,

Also, if you are using capacitor 3, then it’s probably a bug in @capacitor/camera plugin, so should be reported in the plugins repository, not here.
https://github.com/ionic-team/capacitor-plugins/issues
