### ISSUE TITLE
bug: Error reporting when opening agent in vite project

### ISSUE THREAD

**Issue by estoi** [ionic-team/capacitor#5472]
## Bug Report
Hello, my English is not good. I'm using translation software.
I try to configure the agent in vite + vue3 project to solve the cross domain problem of Axios. After I configure it, the browser works normally, but the console throws an error when running on the Android device. At present, I can't solve it. What's the solution?
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.4.1
  @capacitor/cli: 3.4.1
  @capacitor/android: 3.4.1

```

### Platform(s)

vue: ^3.2.25
vite: ^2.7.2
axios: ^0.26.0
android: 11

### Current Behavior

![image](https://user-images.githubusercontent.com/44252820/156142049-4af28a15-a83f-4e99-bad3-d581bb16e6d1.png)

### Other Technical Details

`npm --version` output: 7.10.0

`node --version` output: v16.0.0

`pod --version` output (iOS issues only): 

### Additional Context

```js
// vite.config.js

export default defineConfig({
    server: {
        host: "localhost",
        // port: 8080,
        open: true,
        cors: true,
        proxy: {
            '^/api': {
                target: 'https://xxx.xxx.xxx/', 
                changeOrigin: true,
                ws: true,
                rewrite: (path) => path.replace(/^\/api/, '')
            }
        }
    },
});
```

**Comment by bitsnaps** [comment]
I'm not sure if Capacitor support Vite at this moment!

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
