### ISSUE TITLE
Missing plugin to control media from notification or lock screen

### ISSUE THREAD

**Issue by emilsaj** [ionic-team/capacitor#5473]
In Cordova it was possible to use [cordova-plugin-music-controls](https://github.com/homerours/cordova-music-controls-plugin), but as you probably know, this causes build failure in capacitor.

So right now, my team is having a very hard time finding a replacement for Capacitor 3. Do you have some work in progress or can we simply not use Capacitor to build iOS/Android apps if this is a requirement for the application?

Best regards,
Emil Jensen

**Comment by jcesarmobile** [comment]
There is a request to create a community plugin here
https://github.com/capacitor-community/proposals/issues/158

it list two existing plugins, not sure if they would fit your needs
https://github.com/selcip/capacitor-music-controls-plugin
https://github.com/ingageco/capacitor-music-controls-plugin
