### ISSUE TITLE
Platform cordova return false

### ISSUE THREAD

**Issue by ttibau** [ionic-team/capacitor#548]
Hello, 
How I can return webview platform with capacitor?
I'm using ionic platform but everytime the verification returns false.

Import:
```import {Platform} from '@ionic-angular'```

Inject in constructor...

checking:
```
if(this.platform.is('cordova'){
console.log('is webview');
} else {
console.log('isn't webview');
}
```

Everytime i'm receiving **isn't webview** in device

**Comment by jcesarmobile** [comment]
You can use device plugin https://capacitor.ionicframework.com/docs/apis/device

For this.platform.is('cordova') not being true, that's an Ionic bug.
In Ionic 3 I've tested and returns 3, on Ionic 4 I think it has been fixed recently, but maybe it's not released yet.

**Comment by ttibau** [comment]
@jcesarmobile Thanks for your reply! 
I need to check when the platform is **webview**, the plugin mentioned only return **ios** or **android**, etc, correct?
How I can return if the apps is running in **webview** (android, ios, WP) independent of platform? 
Thanks
<img width="269" alt="captura de tela 2018-05-17 as 11 33 23" src="https://user-images.githubusercontent.com/16947646/40184592-05676bf4-59c7-11e8-9e34-dc8bab3258ff.png">

**Comment by jcesarmobile** [comment]
it returns ios when executing as ios app, android when executing as android app, and pwa when running as a website. 
So ios and android are being executed on the webview, and pwa on a web browser

**Comment by ttibau** [comment]
I got it, but how I can run some code when executing in webview? 
I need to run some code when my project is running in android, ios, etc and run other code when my project run in website. Can you help me?
Thanks.

**Comment by jcesarmobile** [comment]
For doubts and questions better use our Capacitor slack or the forum.

It should be something like
```
const info = await Device.getInfo();
if (info.platform === "pwa") {
// website code here
} else {
// app code here
}
```
Be aware that the else will also execute electron code and other possible platforms added in the future.

If using Capacitor APIs, best way of executing code is with a try/catch, if the api is available for the platform it will run, if not the catch code will be called, this way you don't have to check the platform

**Comment by ttibau** [comment]
That's works! 
Thank You! 
Um abraço do Brasil! 💚 💛
