### ISSUE TITLE
Plugins are missing dependencies error while syncing cordova-plugin-advanced-http@3.2.2

### ISSUE THREAD

**Issue by enes-get-local** [ionic-team/capacitor#5480]
I have a capacitor react.js project and added `cordova-plugin-advanced-http@3.2.2` via npm. 
Problem is it throw error like 

```
Plugins are missing dependencies.
       Cordova plugin dependencies must be installed in your project (e.g. w/ npm install).
       
       cordova-plugin-advanced-http is missing dependencies:
       - cordova-plugin-file (>=2.0.0)
```
Is there a way to fix this ?

**Comment by jcesarmobile** [comment]
That's a warning, not an error, it's telling you that you have to install the dependencies yourself, in example with npm isntall command if you are using npm as package manager, if using npm then you should do `npm install cordova-plugin-file` and then `npx cap sync` again
