### ISSUE TITLE
bug:  3.4.2 throws kotlin error

### ISSUE THREAD

**Issue by tigohenryschultz** [ionic-team/capacitor#5482]
### Capacitor Version

  @capacitor/cli: 3.4.2
  @capacitor/core: 3.4.2
  @capacitor/android: 3.4.2
  @capacitor/ios: 3.4.2

### Platform(s)
Android

### Current Behavior
```
× update android - failed!
[error] TypeError: srcFiles is not iterable
        at kotlinNeededCheck (C:\repos\tigosmart\node_modules\@capacitor\cli\dist\android\update.js:236:35)
        at handleCordovaPluginsGradle (C:\repos\tigosmart\node_modules\@capacitor\cli\dist\android\update.js:171:32)
        at Object.updateAndroid (C:\repos\tigosmart\node_modules\@capacitor\cli\dist\android\update.js:36:11)
        at async C:\repos\tigosmart\node_modules\@capacitor\cli\dist\tasks\update.js:69:13
        at async Object.runTask (C:\repos\tigosmart\node_modules\@capacitor\cli\dist\common.js:143:23)
        at async Object.update (C:\repos\tigosmart\node_modules\@capacitor\cli\dist\tasks\update.js:63:5)
        at async sync (C:\repos\tigosmart\node_modules\@capacitor\cli\dist\tasks\sync.js:56:5)
        at async syncCommand (C:\repos\tigosmart\node_modules\@capacitor\cli\dist\tasks\sync.js:33:13)
        at async C:\repos\tigosmart\node_modules\@capacitor\cli\dist\index.js:68:9
        at async C:\repos\tigosmart\node_modules\@capacitor\cli\dist\telemetry.js:26:13

```

### Expected Behavior
```
| update android [info] Found 11 Cordova plugins for android:
       cordova-plugin-advanced-http@3.2.2
       cordova-plugin-android-permissions@1.1.3
       cordova-plugin-ble-central@1.4.4-alpha.3
       cordova-plugin-file@6.0.2
       cordova-plugin-globalization@1.11.0
       cordova-plugin-network-information@2.0.2
       cordova-plugin-screen-orientation@3.0.2
       cordova-plugin-wifiwizard2@3.1.1
       cordova.plugins.diagnostic@6.1.1
       es6-promise-plugin@4.2.2
       phonegap-plugin-barcodescanner@8.1.0
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by rezakaboli** [comment]
× update android - failed!
[error] TypeError: srcFiles is not iterable
        at kotlinNeededCheck
        (E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\android\update.js:236:35)
        at handleCordovaPluginsGradle
        (E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\android\update.js:171:32)
        at Object.updateAndroid
        (E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\android\update.js:36:11)
        at async
        E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\tasks\update.js:69:13
        at async Object.runTask
        (E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\common.js:143:23)
        at async Object.update
        (E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\tasks\update.js:63:5)
        at async Object.sync
        (E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\tasks\sync.js:56:5)
        at async runCommand
        (E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\tasks\run.js:59:17)
        at async
        E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\index.js:97:9
        at async
        E:\Src\WorkSpace\IdmTablet\IdmTabletSolution\IdmTabletOnsenUICap\node_modules\@capacitor\cli\dist\telemetry.js:26:13

**Comment by jcesarmobile** [comment]
fixed on https://github.com/ionic-team/capacitor/pull/5481
