### ISSUE TITLE
feat: How to permanently allow usage of camera and microphone on iOS

### ISSUE THREAD

**Issue by maxcodefaster** [ionic-team/capacitor#5485]
### Description

Problem: By default, iOS quickly forgets about permissions granted to requests originating from WKWebView. Every time the user relaunches the app and performs an action within WKWebView such as turning on their microphone or camera, WKWebView asks for their permission. What's more, when WKWebView initiates a permission request, iOS will prompt twice: Once for the native layer, and once for the website loaded within WKWebView.

### Platform(s)

iOS

### Preferred Solution

See how react native webview solved this: 
https://github.com/react-native-webview/react-native-webview/issues/2256

**Comment by jcesarmobile** [comment]
what's your Capacitor version? this was already included in 3.4.0

**Comment by maxcodefaster** [comment]
Was on 3.3.4. Upgrading to 3.4.X solved this. Thank you.
