### ISSUE TITLE
Problem when build with facebook-plugin

### ISSUE THREAD

**Issue by ttibau** [ionic-team/capacitor#550]
Hello, 
I'm trying to install plugin:
```
 npm install --save cordova-plugin-facebook4
```
So when build in android studio, I'm receiving this error:
<img width="1345" alt="captura de tela 2018-05-18 as 16 50 32" src="https://user-images.githubusercontent.com/16947646/40254900-9c45a8a2-5abb-11e8-8fc9-7c2bf0114e83.png">

is there something I forgot?

Thanks

**Comment by jcesarmobile** [comment]
Just regular gradle errors when the versions mismatch.
You can force the custom tabs version by adding this to the app's build.gradle

`implementation 'com.android.support:customtabs:27.1.1'`
