### ISSUE TITLE
bug: Remove all the console messages

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/capacitor#5517]
Hi,

Please remove all the console messages on Capacitor plugins. Because it'll directly effect to degrade the performance of native apps. And also security risk too. i.e. can see the table names and etc. Thanks!

I use this plugin: https://github.com/capacitor-community/sqlite

The author of that plugin has mentioned like so:

`this is the messages coming from capacitor itself nothing to do with the plugin`

Please refer here for more info: https://github.com/capacitor-community/sqlite/issues/236

![c1](https://user-images.githubusercontent.com/5206526/159172247-7177f5ef-82ab-4dc0-b09b-c415938d8bd5.png)

**Comment by Sampath-Lokuge** [comment]
It is here: https://capacitorjs.com/docs/v2/apis/console

_capacitor.config.json_

```
{
	
	"hideLogs": true,
	
}
```

**Comment by jcesarmobile** [comment]
For Capacitor 3 you should use `loggingBehavior` set to `none`, `hideLogs` is deprecated in Capacitor 2. Those link you provided is for Capacitor 2.

**Comment by Sampath-Lokuge** [comment]
Oh... But it seems working fine on Android devices.

Anyway, I'll use your one. But I cannot see any Capciotr 3 related Console plugin section on plugins API on the official doc. Any clue? Thanks!

**Comment by jcesarmobile** [comment]
Console is not a plugin, so was removed from the plugin section. The configuration is documented on the configuration docs
https://capacitorjs.com/docs/config

**Comment by Sampath-Lokuge** [comment]
Ok sure. Thanks a lot!
