### ISSUE TITLE
feat: Allow disable Cordova bridge

### ISSUE THREAD

**Issue by riderx** [ionic-team/capacitor#5522]
### Description
All the plugin i use are now in Capacitor and my whole stack is in Capacitor, it could be great to be able to opt-in to disable Cordova bridge in the codebase.
Like with something inside the `capacitor.config.json`

### Platform(s)
IOS and Android

### Preferred Solution
Be able to disable is the solution to me.

### Alternatives
Have a version in npm without cordova like `3.4.3-nocordova` could be even more interesting but seems a bit hard to manage.

**Comment by jcesarmobile** [comment]
closing as duplicate of https://github.com/ionic-team/capacitor/issues/2356
