### ISSUE TITLE
location.host is empty if server.androidScheme is used

### ISSUE THREAD

**Issue by EKashpersky** [ionic-team/capacitor#5528]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.3.1
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.3.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
location.host is an empty string

### Expected Behavior
location.host to be 'localhost' 

### Code Reproduction
Set server.androidScheme to 'test'

### Additional Context
If server.androidScheme not set, then location.host contains 'localhost'

**Comment by jcesarmobile** [comment]
This is an Android WebView bug that Google team closed as won't fix and recommended to not use a scheme different from http or https. The location object is managed by the WebView internally, there is nothing we can do about it.

**Comment by EKashpersky** [comment]
Thanks
