### ISSUE TITLE
bug: Request failed with status code 419 - on Android

### ISSUE THREAD

**Issue by Burotica** [ionic-team/capacitor#5532]
Hello,

I developed an application in VueJS that I compile for Android and IOS with Capacitor 3.4.3, NPM 8.3.0, Axios 0.26.1

I have no problem in the Web version and on IOS, but on Android the authentication gives me an error:
Request failed with status code 419

Authentication is thus done on a URL in https:

axios.post(process.env.VUE_APP_URLAPI+'auth/login', {
    email: this.userEmail,
    password: this.password
  })
.then(response => {
    console.log('response login', response)
})
.catch(error => {
    console. error('Axios error ', error);
})

I searched on Google, except for leads on an X-CSRF problem, I don't see the problem.

For information, I tested on a GET API without security, it works well

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
