### ISSUE TITLE
feat: custom keyboard with "done" action on inputs, and custom actions (if necessary)

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/capacitor#5536]
### Description
Being able to show "close keyboard" on "return" actions when keyboard is open.

### Platform(s)
iOS

### Preferred Solution
<img width="349" alt="image" src="https://user-images.githubusercontent.com/25119847/160161377-36344f26-090e-431a-9a60-429a9133a027.png">

### Current behavior with capacitor keyboard (not buttons for input navigation)
<img width="352" alt="image" src="https://user-images.githubusercontent.com/25119847/160161631-faf7ffae-746d-4a03-9a2f-03758d1348ce.png">

### Additional Context
Inspirations from past cordova plugins:
- https://www.npmjs.com/package/cordova-plugin-native-keyboard
- https://github.com/mrchandoo/cordova-plugin-decimal-keyboard
- https://www.npmjs.com/package/cordova-plugin-for-ios-custom-keyboard

**Comment by jcesarmobile** [comment]
You can use `setAccessoryBarVisible` function to display the accessory bar, it's disabled by default.
 https://capacitorjs.com/docs/apis/keyboard#setaccessorybarvisible
