### ISSUE TITLE
localStorage durability

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#555]
In iOS webview running under Cordova storage will be cleared arbitrarily (for example of the device is running low on disk). It's essentially [treated as cache](https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html#localstorage).

There are plugins such as [cordova-plugin-nativestorage](https://github.com/TheCocoaProject/cordova-plugin-nativestorage), but it would be even better if localStorage was stored in a durable location instead.

Are there plans to work around this limitation in capacitor? Ideally by storing localStorage data in a durable location under iOS, but another option would be a public API for storing data durably.

**Comment by mlynch** [comment]
We have a Storage API already for just this purpose! 😁

**Comment by sandstrom** [comment]
Thanks @mlynch, I must be blind! 🙈

**Comment by sandstrom** [comment]
@mlynch Quick followup question on this matter.

We're in the process of migrating from Cordova to Capacitor. In Cordova we're using (cordova-plugin-nativestorage)[https://www.npmjs.com/package/cordova-plugin-nativestorage] addon. It uses `Sharedpreferences` (android) and `NSUserDefaults` (ios).

We store login session tokens with this addon. To avoid logging out all users when they upgrade from our app v1 (cordova) to v2 (capacitor), what would you recommend?

1. Integrate that plugin in capacitor only for migration (read once, copy to capacitor storage)
2. Release v1.1 which will write from plugin-nativestorage into (ephemeral) `localStorage` (DOM) and have v2 (capacitor) read `localStorage` and put into Capacitor Storage
3. Something else?
