### ISSUE TITLE
bug: Camera not working on android apk

### ISSUE THREAD

**Issue by fulvous** [ionic-team/capacitor#5554]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/cli: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Camera works on PWA and IOS correctly
Tested on Android version 12 not working
Tested on Android version 9 not working

### Current Behavior

Added permissions to AndroidManifest.xml (android/app/src/main/AndroidManifest.xml)

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_MEDIA_STORAGE" />

    <uses-feature android:name="android.hardware.camera" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.hardware.camera.autofocus" />

After executing 
    const cameraPhoto = await Camera.getPhoto({
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Camera,
      quality: 100,
      saveToGallery: false,
      correctOrientation: false,
      allowEditing: false,
    });
I get the message to give permissions to the camera and after accepting the permissions, I get the following errors:

{
   capacitor Camera.getPhoto "message": "Unable to create photo on disk"
}

Uncaught (in promise) Error: Unable to create photo on disk at Object.cap.fromNative

### Expected Behavior

Camera should popup the and work

### Other Technical Details

`npm --version` output:
8.1.2
`node --version` output:
v16.6.0
`pod --version` output (iOS issues only):

**Comment by umairsyed613** [comment]
I have the same issue, when i generate release apk install it manually on my phone everything works fine, but when i generate release signed app bundle and put it on play store the camera is not working, backButton listener is not working. any idea how to debug this?

**Comment by fulvous** [comment]
Hi, I found out that camera is working if I build the app using android studio IDE with sdk 11.0.11. 
The problem appears in my .gitlab-ci.yml script when build the apk with the following lines:

- ionic capacitor sync android
- ionic capacitor copy android
- gradlew assembleDebug

**Comment by fulvous** [comment]
Hi, so in order to close this issue, I would like to share my solution:

First of all, it was needed to add the following two permissions to the AndroidManifest.xml previos to compiling:

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

Despite of that, I was still getting some filesystem error. So after comparing my code with the sample github code. I found a difference in this snipet:

  1 export const savedFile = (filename: string, data: string) => {                
  2   return Filesystem.writeFile({                                               
  3     path: filename,                                                           
  4     data: data,                                                               
  5     directory: Directory.Data,                                                
  6   });                                                                         
  7 };

I replaced it with this one:

  1     const savedFileSuccess = await Filesystem.writeFile({                       
  2       path: fileName,                                                           
  3       data: base64Data,                                                         
  4       directory: Directory.Data,                                                
  5     });

And then it worked on mobile apps, android and ios too.

**Comment by jcesarmobile** [comment]
Not sure how that could fix your problem since you said you had those permissions already and that code you have provided is for saving the image in the filesystem, not for taking a picture.
But closing since you got the problem solved.
