### ISSUE TITLE
Camera : cannot see image  to be captured

### ISSUE THREAD

**Issue by javiercoh** [ionic-team/capacitor#5557]
### Capacitor Version

   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.4.1
  @capacitor/cli: 3.4.1
  @capacitor/android: 3.4.1

[success] Android looking great! 👌

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\jcohe\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.9
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.2
   OS     : Windows 10

### Platform(s)
App runs as PWA and it is failing on SAMSUNG Galaxy A02 Core with Android 11

### Current Behavior
User cannot see the image being captured. Please see image file attached

![img_to_capture_not_being_shown](https://user-images.githubusercontent.com/67232841/161406104-4dcdbd1d-9815-47e9-81f2-76d3f1dea075.jpg)

### Expected Behavior
User should be able to image to be captured

### Code Reproduction
```
async takePicture() {
  console.log('take');
  
   
  const image = await Camera.getPhoto({
    
    allowEditing: false,
    source: CameraSource.Camera,
    resultType: CameraResultType.Base64
  });
 
  return image
  
}

```

### Other Technical Details

`npm --version` output: 8.1.2

`node --version` output: v16.13.2

**Comment by jcesarmobile** [comment]
Does it work here?
https://webrtc.github.io/samples/src/content/getusermedia/gum/

Do you see any errors in the console?

**Comment by javiercoh** [comment]
> Does it work here? https://webrtc.github.io/samples/src/content/getusermedia/gum/
> 
> Do you see any errors in the console?

Thank you very much @jcesarmobile!

 Same issue when trying the new link:
![image](https://user-images.githubusercontent.com/67232841/161599591-65ecd512-b6a1-4f5b-9022-f0e8131cb5b8.png)

Unfortunately I cannot access the user console right now, but probably will do it in the next few days. Any thougths though?

**Comment by jcesarmobile** [comment]
What's the browser and version you are using?

The link doesn't use the plugin, just regular getUserMedia API (that the plugin uses internally), but if none of them work it looks like a problem on the device or browser.

**Comment by adavie1** [comment]
In `AndriodManifest.xml` have you added this:
```
  <!-- Permissions -->

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

```

**Comment by javiercoh** [comment]
> What's the browser and version you are using?
> 
> The link doesn't use the plugin, just regular getUserMedia API (that the plugin uses internally), but if none of them work it looks like a problem on the device or browser.

chrome version 100.0.4896.79 thanks

**Comment by javiercoh** [comment]
> In `AndroidManifest.xml` have you added this:
> 
> ```
>   
> 
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.CAMERA" />
> 
>     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
> ```

thanks @adavie1  excuse my ignorance but i thought this would only affect the native/apk version, not the pwa...

**Comment by adavie1** [comment]
@javiercoh not sure about PWA, but Android definitely.

**Comment by jcesarmobile** [comment]
When running as PWA the permissions should be declared in the browser, Chrome already declares them and also request them when needed.

Doesn't look like a permission problem because if there is a permission error it should show a permission error.
I have that same Chrome version and it's working fine on my devices, so looks like a problem in your device since it also fails on the provided link.

**Comment by javiercoh** [comment]
Agree, seems device related.
