### ISSUE TITLE
Question about remote web apps

### ISSUE THREAD

**Issue by jorgecoca** [ionic-team/capacitor#556]
It is not clear to me whether or not I can deploy a web app with Capacitor to my server and consume it on Android/iOS, or if instead I have to bundle the web app together in the APK/IPA of the mobile app.

With Capacitor, how can I update the layout of a web app remotely? Would I need to do a new app release to the store, or can I do that remotely?

**Comment by mlynch** [comment]
This would be a good question for the forum: https://forum.getcapacitor.com/

Think of Capacitor as just a JS library, so you'd deploy your app to the web like any other web app. However, you can also package it up for the app stores.

**Comment by timLoewel** [comment]
@jorgecoca did you get an answer in the forum? I could not find it.
I have the same problem.
I do not understand why this was closed. The feature is really obvious and seems to fall into the scope of capacitor, no?
 @mlynch: what do you mean by "just a JS library"? Capacitator is the one responsible for loading the javascript code, right? 
This should be handled in the documentation, if just to say that it does not work.

**Comment by jcesarmobile** [comment]
Capacitor allows you to set a url to load, but that’s meant to be used for development only, primarily because Apple doesn’t allow to wrap websites. But technically, as long as you don’t add new plugins, if you upload your www to a web server and point to it, it should work

**Comment by evromalarkey** [comment]
I want to render my app server side via php, and so far it seems that should work. Did anyone had any problems setting up remote url for production use? I had previously done few cordova apps this way and had no problems with apple.
