### ISSUE TITLE
"SyntaxError: Unexpected token (" on Android 7.0.0 (API 24)

### ISSUE THREAD

**Issue by trytuna** [ionic-team/capacitor#5560]
I am having an issue with ionic running on Android 7. I am getting the following error message:

```
localhost/:53 Uncaught SyntaxError: Unexpected token (
```

![Screenshot 2022-04-11 at 14 58 23](https://user-images.githubusercontent.com/128096/162744308-976b87e0-5b43-4f6f-a743-ca55408ac56c.png)

Which I figured out should be this line of code: https://github.com/ionic-team/capacitor/blob/1451ec850a9ef73267a032638e73f1fc440647b9/core/native-bridge.ts#L61

Its a fresh tab based project with angular as the framework

This is my environment:
```
% ionic info
       
       Require stack:
       - /Users/timo/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/timo/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/timo/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli/index.js
       - /Users/timo/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.18.2 (/Users/timo/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.16
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 (/Users/timo/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.6.0
   OS     : macOS Monterey
```

```
WebView version: 52.0.2743.100
```

**Comment by trytuna** [comment]
This is a major show stopper for android 7 :(

**Comment by jcesarmobile** [comment]
Capacitor requires webview 60 or newer, you are using version 52.

you can track this issue about showing a native error message when the webview is out of date

https://github.com/ionic-team/capacitor/issues/4884

**Comment by trytuna** [comment]
Shouldn't Capacitor show this kind of Message? Is there some example code to do something like this?

Don't get me wrong - I don't mind implementing this but the reason to use Ionic with Capacitor is so that one don't have to mess with native code. This seems so essential that it would be a good candidate to be included into Capacitor.

**Comment by trytuna** [comment]
Ping
