### ISSUE TITLE
Desktop application not working after capacitor library update 

### ISSUE THREAD

**Issue by fahad-cinnova** [ionic-team/capacitor#5566]
I have recently update the capacitor library for my ionic project. But after update the capacitor library my android and ios versions are working fine. But my windows version not working . I'm not able to send any http/https request.

I have update elector capacitor below
From: "@capacitor-community/electron": "^1.4.2",
To: "@capacitor-community/electron": "^4.1.0",

My others versions are below
"@capacitor/core": "^3.4.3",
"@capacitor/ios": "^3.4.3",
"@capacitor/android": "^3.4.3",
"@ionic/pwa-elements": "^3.0.2",
"@ionic/angular": "^5.0.0",

Please let me know if anyone have an idea to resolve my problem.
This is the screen shot of console.
![image](https://user-images.githubusercontent.com/102585302/163940986-29d85984-6d34-4054-aec1-0086012873b2.png)

**Comment by jcesarmobile** [comment]
capacitor electron is community maintained, you should report it in it's own repository
https://github.com/capacitor-community/electron

major version bumps usually mean breaking changes, so you should check if the plugin has some steps documented about what you should do or what breaks, I could only find the v3 to v4 breaking changes here
https://github.com/capacitor-community/electron#-version-4-info
