### ISSUE TITLE
bug: native calls from iframe never complete

### ISSUE THREAD

**Issue by akvadrako** [ionic-team/capacitor#5567]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/ios: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
```

### Platform(s)

Android

### Current Behavior

When I call a capacitor plugin from inside an iframe, it returns a promise. However that promise never resolves, nor throws an error.

For Example:

```js       
         Capacitor.Plugins.WebView.getServerBasePath().then(data => {
            console.error('DATA', data)
        }).catch(e => {
            console.error('ERROR')
        })

```

I see this in the logs:

```
[ 04-19 10:54:04.356  5437: 5571 V/Capacitor/Plugin ]
To native (Capacitor plugin): callbackId: 59043351, pluginId: WebView, methodName: getServerBasePath

[ 04-19 10:54:04.356  5437: 5571 V/Capacitor ]
callback: 59043351, pluginId: WebView, methodName: getServerBasePath, methodData: {}
```

but that's it.

### Expected Behavior

Ideally, when calling a native method from inside an iframe, it should work correctly.

A less ideal outcome is that it throws an error.

### Code Reproduction

https://github.com/akvadrako/ionic-bug-iframe

**Comment by jcesarmobile** [comment]
That's expected, iframes should not have access to the native bridge.

**Comment by akvadrako** [comment]
Then shouldn't it give an error instead of just hanging?

And shouldn't that be documented?

**Comment by DSergiu** [comment]
@jcesarmobile would you please add more here? 

The iframes are getting a `pending` promise which never resolves inside the iframe, but it console logs with the result just fine. Ideally the promise resolves inside the iframe.

**Comment by DSergiu** [comment]
Bringing @Steven0351 @theproducer in the loop. Would you mind re-opening this issue or providing more info on the above?
