### ISSUE TITLE
bug: Can't seem to copy from webview on Android using capacitor-clipboard

### ISSUE THREAD

**Issue by Vaelio** [ionic-team/capacitor#5568]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/android: 3.4.3
  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3

[success] Android looking great! 👌
```

### Platform(s)

Android (My phone is running android 12, cannot test on other phones right now)

### Current Behavior

I am building a password manager app and while it works successfully on web version i can't seem to copy password to clipboard on android. At first i was using `navigator.clipboard.write(data)` but it wasn't working on android so i tried various methods before finding the plugin capacitor-clipboard. Still, i can't manage to copy to clipboard. 

I am using vuetify to create the view and the javascript code i use to copy is the following (using @capacitor/clipboard):

```javascript
const writeToClipboard = async (p) => {
  await Clipboard.write({
    string: p,
    label: "data"
  });
};
```

### Expected Behavior

The function writeToClipboard fails on android

### Code Reproduction

I'll try and provide an empty vuetify project in the next days to demonstrate but essentially try to copy to clipboard anything from a vue using the previous code and it'll fail on android (I can't test for iOS, but it works on web)

### Other Technical Details

I generated the android app using this method

https://ivanmijatovic.com/how-to-build-android-and-ios-app-using-vue-and-vuetify-with-capacitor

`npm --version` output: 8.5.5

`node --version` output: v17.9.0

### Additional Context

This looked promising to me but i have no idea how to do this with the generated android project

https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest

I tried aswell to use the `document.execute("Copy")` bypass but same result

From Mozilla's documentation it looks like `navigator.clipboard.writeText` should work inside webview (https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) but i had no success

Thanks for your time :)

**Comment by jcesarmobile** [comment]
navigator.clipboard doesn’t work on the WebView because it requires permissions that can’t be requested.
I reported it to chromium team some time ago
https://bugs.chromium.org/p/chromium/issues/detail?id=1271620&q=&can=4

I also reported a few more related issues on the android bug tracker with no response en years.

but the plugin is working fine for me, it uses the native clipboard, so would be good if you can provide the sample app.

**Comment by Vaelio** [comment]
Ok nevermind using a sample app i managed to copy using `@capacitor/clipboard`. The code is very similar so clearly i don´t know what i'm doing lol. Sorry for the time loss.
