### ISSUE TITLE
bug: @capacitor/ios since 3.5.0 asset image with spaces in name doesnt load

### ISSUE THREAD

**Issue by rostislavcz** [ionic-team/capacitor#5592]
## Bug Report
Hi, I noticed, that when I load something like this in my code:
`<img src="assets/image with space.jpg">`
it is not loaded since @capacitor/ios 3.5.0, untill 3.4.3 image is loaded just fine

### Platform(s)
IOS

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
