### ISSUE TITLE
feat: ios credential management

### ISSUE THREAD

**Issue by runspired** [ionic-team/capacitor#5593]
### Description

wkWebView has added the ability to opt-in to keychain usage: https://trac.webkit.org/changeset/265525/webkit

capacitor should make use of this feature :)

### Platform(s)

ios

### Preferred Solution

Automatically configure wkWebView or provide a capacitor config via which to configure the wkWebView instance to allow for credential management.

**Comment by jcesarmobile** [comment]
What specific methods are you referring to?
_canUseCredentialStorage and _setCanUseCredentialStorage seem to be private

Also, it looks like the setting is for disabling the storage, not for enabling it

> This setting is to allow apps to explicitly deny using the credential storage for network operations. (e.g. to make sure the Keychain UI doesn't pop up for an offscreen load)

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
