### ISSUE TITLE
Automatic detection of Android Studio on linux

### ISSUE THREAD

**Issue by erperejildo** [ionic-team/capacitor#560]
`npx cap open android`

this command tries to open Android Studio on a default path but I've got this installed on a different location

**Comment by erperejildo** [comment]
Ok, found this:
https://github.com/ionic-team/capacitor/commit/f68ea10a1b3659e32d2029a771ba35fdfd96cd5f

Working now, but it's a bit annoying if we're working from different computers. There is no way to automatically find Android Studio like Cordova does?

**Comment by jcesarmobile** [comment]
Found this, we can try it https://github.com/apache/cordova-android/blob/master/bin/templates/cordova/lib/getASPath.bat

**Comment by jsdussanc** [comment]
Me too for ubuntu

**Comment by darrenmothersele** [comment]
Android Studio installed from AUR on Arch Linux is also not detected. 

The configuration option to override the install path only works on Windows.

**Comment by jcesarmobile** [comment]
@darrenmothersele the linux configuration option is linuxAndroidStudioPath, have you tried that one?

As the automatic detection is working on windows now and it's not a problem on macOS, edited the issue title for linux (but not sure if it's possible to detect it there)

**Comment by darrenmothersele** [comment]
@jcesarmobile sorry it took a while for me to respond. I stopped using my linux machine for daily development work and I'm back on my hackintosh - so was unable to test this.

I can confirm that setting `linuxAndroidStudioPath` does work correctly.

**Comment by gbhipolitoglyph** [comment]
sorry, where can I see and edit the `linuxAndroidStudioPath` config? thanks

**Comment by OoDeLally** [comment]
@gbhipolitoglyph `linuxAndroidStudioPath` is a key-value in your `capacitor.config.json`.

**Comment by jcesarmobile** [comment]
closing as won't do

In Capacitor 3 users can use `CAPACITOR_ANDROID_STUDIO_PATH` environment variable to configure the android studio path if installed in the non default place.

https://capacitorjs.com/docs/config#environment-variables
