### ISSUE TITLE
bug: RuntimeException from LocalNotificationManager on Android 12

### ISSUE THREAD

**Issue by josluimg** [ionic-team/capacitor#5604]
## Bug Report
We are receiving a lot of crash report on Google Play Console. Only in Android 12

The track is: 
`java.lang.RuntimeException: 
  at com.getcapacitor.Bridge$1.run (Bridge.java:551)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:210)
  at android.os.Looper.loop (Looper.java:299)
  at android.os.HandlerThread.run (HandlerThread.java:67)`

`Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.getcapacitor.PluginHandle.invoke (PluginHandle.java:99)
  at com.getcapacitor.Bridge$1.run (Bridge.java:542)
  at Caused
  at android.app.PendingIntent.checkFlags (PendingIntent.java:375)
  at android.app.PendingIntent.getBroadcastAsUser (PendingIntent.java:645)
  at android.app.PendingIntent.getBroadcast (PendingIntent.java:632)
  at com.getcapacitor.plugin.notification.LocalNotificationManager.cancelTimerForNotification (LocalNotificationManager.java:365)
  at com.getcapacitor.plugin.notification.LocalNotificationManager.schedule (LocalNotificationManager.java:155)
  at com.getcapacitor.plugin.LocalNotifications.schedule (LocalNotifications.java:75)`

### Capacitor Version
```
Installed Dependencies:

  @capacitor/cli 2.4.9
  @capacitor/android 2.5.0
  @capacitor/core 2.5.0
  @capacitor/ios 2.5.0
  @capacitor/electron not installed
```

### Platform(s)
- Android 12 (SDK 31)
- Android 12L (SDK 32)

### Current Behavior
java.lang.reflect.InvocationTargetException
com.getcapacitor.PluginHandle.invoke

99,7% ocurred on foreground.

### Expected Behavior
No crash error

### Code Reproduction
You must receive a notification on Android 12 (Device doesnt matter: Samsung, xiaomi...)

### Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: v12.16.3

### Additional Context
We don't have more information

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by josluimg** [comment]
Hello @Ionitron I understand you because without reply it's very difficult build a solution. The error ocurrs when you receive a notification Push in foreground. So it's a scenary difficult to reproduce o prepare a code to reproduce. Firebase Crashlytics reports:

Caused by java.lang.IllegalArgumentExceptioncom.orange.miorange: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by jcesarmobile** [comment]
Capacitor 2 targets SDK 29, if you want to target SDK 31 (or 32) you'll have to update to Capacitor 4 once it's out.

**Comment by josluimg** [comment]
Hello @jcesarmobile  I see it... I found the crash on Capactor . It is solved on C3 y C4... So I suposse we will not have a 2.5.1 version fixing this problem

**Comment by jcesarmobile** [comment]
It’s only solved in capacitor 4, really on the @capacitor/local-notifications plugin version 4 that we will launch with capacitor 4 since we moved plugins out in capacitor 3.

**Comment by maxcodefaster** [comment]
> It’s only solved in capacitor 4, really on the @capacitor/local-notifications plugin version 4 that we will launch with capacitor 4 since we moved plugins out in capacitor 3.

Any chance to install capacitor v4 plugins already or is there any eta for releasing v4? some of us require to target sdk 31 already.

**Comment by youxiang-git** [comment]
Hi @jcesarmobile, I'm facing the same issue as above but exclusively with the "cron"-style ScheduleOn function, at and every works fine. Is this an isolated issue with ScheduleOn?

**Comment by jcesarmobile** [comment]
Please, don’t ping me.

if you think you have found an issue, create a new issue and provide a sample app where the issue can be reproduced.
