### ISSUE TITLE
Add electron AutoUpdating / Packaging to electron template

### ISSUE THREAD

**Issue by FlowShowcontrol** [ionic-team/capacitor#561]
Feature suggestion:

Please add the electron autoupdater & electron build module to the electron template by default. It would probably be required to add the github repository to the package.json file but then apps would have Electron supported autoupdating by default and can be distributed more easily.

https://electronjs.org/blog/autoupdating-electron-apps

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.
If you are interested in this feature, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by jcesarmobile** [comment]
removing the labels since electron is no longer part of capacitor

not sure if this is supported by the community version of the platform, if not you can request the feature there
https://github.com/capacitor-community/electron

**Comment by jcesarmobile** [comment]
Capacitor 3 removed electron support, it's a community platform now
You can request the feature there 

https://github.com/capacitor-community/electron
