### ISSUE TITLE
IOS module error

### ISSUE THREAD

**Issue by FlowShowcontrol** [ionic-team/capacitor#562]
When deploying Capacitor app to IOS I get the following error:

```
⚡️  ------ STARTUP JS ERROR ------

⚡️  TypeError: undefined is not an object (evaluating 'modules[moduleId].call')
⚡️  URL: http://localhost:8662/build/vendor.js
⚡️  vendor.js:55:29
```

This error does not occur when running with `ionic serve`. Capacitor app is created over a fresh ionic install (Latest). `npx cap update ios` && `npx cap sync ios` have been run.

What are good ways to troubleshoot these kinds of errors? It seems silly sometimes to just paste the whole thing into an issue...

**Comment by FlowShowcontrol** [comment]
Ionic version 3.20.0

Added plugin ionic-zeroconf

A new ionic app where I created a capacitor app on.

**Comment by jcesarmobile** [comment]
Sorry, I can't still reproduce.

Can you provide your code or a sample project?

**Comment by FlowShowcontrol** [comment]
Yes I'll get back to you with a sample project

**Comment by timephy** [comment]
@FlowShowcontrol Did you manage to fix it? What did you do?
