### ISSUE TITLE
bug: Filesystem on Android does not work

### ISSUE THREAD

**Issue by malte94** [ionic-team/capacitor#5634]
### Capacitor Version

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

### Platform(s)

Android (only production build)

### Current Behavior

I am using the following code to save and open a File with Filesystem for Android. The code works well on the localhost (Android emulator). Also iOS is no problem.

However, as soon as I run the application from the production server on either the Android emulator or a real Android device, Filesystem does not seem to be working anylonger.

I performed, of course, a npx cap sync/update, npm run build and rebuild the app and uploaded it to the Google Play Console.

```
    // Android uses the new implementation from Capacitor

    if (isPlatform('android')) {
        if (filename.includes(".json")) {
            filename = filename.replace(".json", ".xlsx");
            encodeBase64(content)
        }
        const result = await Filesystem.writeFile({
            path: filename,
            data: content,
            directory: Directory.Documents
        });

        FileOpener.showOpenWithDialog(result.uri, mimeType)
    }

    // iOS uses the implementation from Cordova

    else if (isPlatform('ios')) {
        if (File.checkFile(File.tempDirectory, filename)) {
            setTimeout(() => {
                File.removeFile(File.tempDirectory, filename)
            }, 1000)
        }
        File.writeFile(File.tempDirectory, filename, content, true).then(success => {
            FileOpener.showOpenWithDialog(File.tempDirectory + filename, mimeType)
                .then(() => console.log('File opened'))
                .catch(e => toast.error("Fehler beim Öffnen der Datei: " + e));
        })
            .catch(e => toast.error("Fehler beim Speichern der Datei: " + e));
    }
```

The console error is:

```
Uncaught (in promise) Error: "Filesystem" plugin is not implemented on android
    at f (static/js/35.a7ac7253.chunk.js:2)
    at static/js/35.a7ac7253.chunk.js:2
```

The Android project structure looks like this:

https://ibb.co/sCFQqwC

### Expected Behavior

Filesystem should be available on Android on production.

### Other Technical Details

`npm --version` output: 8.5.5

`node --version` output: 16.15

`pod --version` output (iOS issues only):

**Comment by malte94** [comment]
After some research, I could resolve the issue. Capacitor does not seem to be compatible with service-worker. I removed those in React, rebuild the client and app and the plugins do work now. On iOS this doesn't seem to be an issue at all.

**Comment by jcesarmobile** [comment]
Yeah, plugins don’t work from service workers, there is another issue reported about it

https://github.com/ionic-team/capacitor/issues/5278
