### ISSUE TITLE
bug: Keyboard not scroll to the focus input on iOS

### ISSUE THREAD

**Issue by dodomui** [ionic-team/capacitor#5635]
### Capacitor Version

```
PASTE OUTPUT HERE
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

### Platform(s)

iOS

### Current Behavior

Clicking an input field and it blocked by the keyboard does not scroll the view to the focused input field.
It occurs on a long input list. 

### Expected Behavior

We expected it to work as it does in Android, where the view scrolls to the focused input field instead.
In the keyboard resize options, I tried 'none', 'body', 'ionic', and 'native'. None worked.

### Other Technical Details

`npm --version` output:
8.10.0
`node --version` output:
v16.13.0
`pod --version` output (iOS issues only):
1.11.3

**Comment by jcesarmobile** [comment]
It’s the expected behavior, you can use the keyboard events to scroll yourself. The provide the height of the keyboard so you can do any needed calculation.

https://capacitorjs.com/docs/apis/keyboard#example
