### ISSUE TITLE
feat: Allow a way to set a different sourceCompatibility and  targetCompatibility in capacitor.build.gradle

### ISSUE THREAD

**Issue by gmbett** [ionic-team/capacitor#5640]
### Description
I have an Android project which is using the latest version of Capacitor cli, core and android: 3.5.1

Our project is configured to use **JavaVersion.VERSION_11** as Java _sourceCompatibility_ and _targetCompatibility_ but the auto generated file `capacitor.buid.gradle` is using **JavaVersion.VERSION_1_8** as defined in https://github.com/ionic-team/capacitor/blob/main/cli/src/android/update.ts.

This difference is making Gradle to choose 1.8 instead of 11.

### Platform(s)
Android

### Preferred Solution
Allow a way to set the preferred compatibility version.

**Comment by jcesarmobile** [comment]
You can force gradle to use the version 11 in different ways, you can try some of the answers here
https://stackoverflow.com/questions/21028438/gradle-sourcecompatibility-has-no-effect-to-subprojects

In Capacitor 4 we are setting the java version to 11, but we won't offer an option to keep using version 8

**Comment by gmbett** [comment]
ok, thanks!
