### ISSUE TITLE
bug: I get "Cordova is not available. Make sure to include cordova.js or run in a device/simulator" error on certain  Android devices when using Ionic Native

### ISSUE THREAD

**Issue by salazarbarrera** [ionic-team/capacitor#5646]
## Bug Report
As the title says, I'm just trying to make a simple call to AppVersion.getAppName()  from @ionic-native, but it doesn't work on certain devices. I need it to work on three different devices, one with Android 6, one Android 7.1 and one 8.1, but it only works on the later. The other two give the runtime error "Cordova is not available. Make sure to include cordova.js or run in a device/simulator", as if the WebView came from a browser and not an APK built with capacitor.

### Capacitor Version
$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1

[success] Android looking great! 👌

```
PASTE OUTPUT HERE
```

### Platform(s)
Android 6
Android 7.1

### Current Behavior
App can't find cordova.js as if it was executed inside a browser.

### Expected Behavior
To work as it does in Android 8.1.

### Code Reproduction
Removing all the stuff from my job, this is more or less what causes the problem. When I inspect the WebView through Chromium (in chrome://inspect/#devices ) I can see the error. The same goes with logcat. I can build it either manually in Android Studio or with `$ionic cap run` and I get the same results. 

Needless to say, this also affects other things from Ionic Native, like the WebIntent plug-in.

```
import { ComponentFixture, TestBed, waitForAsync } from '@angular/core/testing';
import { IonicModule } from '@ionic/angular';
import { AppVersion } from '@ionic-native/app-version/ngx';

@Component({
  selector: 'myscreen',
  templateUrl: './myscreen.page.html',
  styleUrls: ['./myscreen.page.scss'],
})

export class myScreenPage implements {

  constructor(
      private app: AppVersion,
    ) {}

  fuctionTriggeredByIonButton() {
    console.log(this.app.getPackageName());
  }

```

### Other Technical Details
The devices are POS. The three of them come from the same manufacturer, so my guess is it is a problem triggered by the Android API version.

`npm --version` output:
8.5.5

`node --version` output:
v18.2.0

**Comment by jcesarmobile** [comment]
What’s the webview version of the devices where it doesn’t work?
Should be displayed on the chrome://inspect/#devices screen

**Comment by salazarbarrera** [comment]
Good question! I didn't notice before, but the two which doesn't work have the same version.

It works on:

- WebView in io.ionic.starter (70.0.3538.110) - Android 8.1

It doesn't work on:

- WebView in io.ionic.starter (52.0.2743.100) - Android 6.0
- WebView in io.ionic.starter (52.0.2743.100) - Android 7.1.2

**Comment by jcesarmobile** [comment]
Capacitor requires [webview 60 or newer](https://capacitorjs.com/docs/android#android-support), you are using version 52.

you can track this issue about showing a native error message when the webview is out of date

https://github.com/ionic-team/capacitor/issues/4884

**Comment by salazarbarrera** [comment]
Thanks for the information and the suggestion!
