### ISSUE TITLE
KochavaTrackerCordova plugin I am unable to find a way to integrate in my capacitor app

### ISSUE THREAD

**Issue by HamzaAdam** [ionic-team/capacitor#5649]
How to integrate a plugin in my capacitor app which doesn't have any npm registry. Kochava gives a package to manually add in project but I didn't see a way to integrate it.

**Comment by jcesarmobile** [comment]
You still use npm install command, but instead of using the plugin id on npm you use the path to the file.
If it’s a .zip you might need to unzip it first and use the path to the folder instead.
