### ISSUE TITLE
isPluginAvailable is not available

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#565]
The PWA guide has an example for checking if a plugin is available, but it doesn't really work as isPluginAvailable doesn't exist on Capacitor.

See example code.
```
import { Capacitor } from '@capacitor/core';

const isAvailable = Capacitor.isPluginAvailable('Camera');

if (!isAvailable) {
  // Have the user upload a file instead
} else {
  // Otherwise, make the call:
  Camera.getPhoto()
}
```

It works fine when doing `"bundledWebRuntime": true`, in that chase Capacitor.isPluginAvailable('Camera'); is available and works.

**Comment by mschwarzmueller** [comment]
I'm still getting this despite setting `"bundledWebRuntime": true` and re-building + copying the project. Did you have to adjust anything else?
