### ISSUE TITLE
bug: PushNotifications.register is not a function (Android)

### ISSUE THREAD

**Issue by Houdhey** [ionic-team/capacitor#5656]
### Capacitor Version

```

  @capacitor/cli 2.2.0

  @capacitor/android 2.2.0

  @capacitor/ios 2.4.2

  @capacitor/core 2.2.0

```

### Platform(s)

Android

### Current Behavior

Triggerring PushNotifications.register() for Android Device.
Getting this error : PushNotifications.register is not a function

### Expected Behavior
Should work, and allow me to receive Push Notifications.

### Code Reproduction
```   PushNotifications.requestPermission().then((permission) => {
      if (permission.granted) {
        PushNotifications.addListener('registration', (registration) => {
          console.log('PUSH NOTIFICATIONS DEBUG - REGISTRATION ' + JSON.stringify(registration));
        });
        PushNotifications.register();
}
});
```

### Other Technical Details

`npm --version` output: 8.5.0

`node --version` output: v16.14.2

**Comment by jcesarmobile** [comment]
Sorry, we no longer support Capacitor 2 except for security issues. 
Consider upgrading to Capacitor 3 https://capacitorjs.com/docs/updating/3-0
