### ISSUE TITLE
bug: IOS App Status bar overlays content

### ISSUE THREAD

**Issue by geniux-dev** [ionic-team/capacitor#5675]
Can you guys show us how to add Safe Areas margins on Xcode(IOS)

Issue: my app overlays with status bar.

**Comment by jcesarmobile** [comment]
You don’t do it from Xcode, you should use css
https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by geniux-dev** [comment]
Thanks guys, am sorted!

**Comment by twoco** [comment]
The status bar on Android and iOS differs from device and OS version, etc. Managing all variations is impossible. You'll always have case like "white text on white background" or "black text on black background". Therefore there must be a way to tell the WebView (iOS and Android) to let the status bar undependend from website content. Just render the website below the status bar. No CSS, etc. As I remember from Cordova there was a flag like fullscreen or not. Serveral options for either: hide the status bar (native fullscreen) or fullscreen with overlapping status bar with safe area setting and a mode with independent status bar. Where the app content (HTML/CSS) cannot affect the status bar. 

Btw. setting `StatusBar.setStyle({ style: this.settings.darkMode ? Style.Dark : Style.Light });` works but is usless until you don't know the status background style and behavior. No matter what you do. In the end there are always users who see an unprofessional/partial hidden status bar.

@jcesarmobile
