### ISSUE TITLE
bug: Cant build Capacitor on M1 Mac cause of old GoogleTagManager

### ISSUE THREAD

**Issue by SheppardX** [ionic-team/capacitor#5685]
### Capacitor Version
```
Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

```

### Platform(s)
iOS on Mac with M1 Chip

### Current Behavior
cant get build cause GoogleTagManager is old version (7.3.1) and not ready for m1 chips it got updated and fixed on version 7.4.0
In Podfile.lock i can see that CordovaPluginsStatic is using GoogleTagManager (= 7.3.1) and CordovaPluginsStatic is coming from  capacitor-cordova-ios-plugins
https://github.com/firebase/firebase-ios-sdk/issues/7509 last post

'GoogleSymbolUtilities' for architecture arm64

is this the right place to post ?

### Expected Behavior
Its gets build 

### Other Technical Details

`npm --version` output: 8.5.5

`node --version` output: v14.19.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment]
CordovaPluginsStatic is generated from your installed Cordova plugins, so you should see which plugin is using that dependency and report to the plugin maintainer.

**Comment by jcesarmobile** [comment]
All the content from capacitor-cordova-ios-plugins comes from your installed Cordova plugins, Capacitor searches for all your installed Cordova plugins and put the code in that folder, so one of your Cordova plugins has the problem, you have to find out which one and report it to their maintainers.

**Comment by jcesarmobile** [comment]
Start by searching "cordova" in your package.json as cordova plugins usually have cordova in their name. Then see if any of the results has "firebase", "firestore", "google", "analytics", etc on the name too.
