### ISSUE TITLE
bug: iOS 13 and 12 stuck at a blank screen

### ISSUE THREAD

**Issue by catt-stefano** [ionic-team/capacitor#5686]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.5.1
  @capacitor/ios: 3.5.1
  @capacitor/core: 3.5.1

[success] iOS looking great! 👌
```

### Platform(s)
iOS 12 and 13. Xcode 13.4.1

### Current Behavior
When I build the iOS version of my app, after the splashscreen disappears, the app remains blank. This was observed on iOS simulators running iOS 13.3 and iOS 12.4 and also on a device running iOS 12.3.1
![Simulator Screen Shot - iPhone 11 Pro - 2022-06-15 at 12 29 21](https://user-images.githubusercontent.com/11888433/173806451-c9b4e3a3-bc7d-45ad-a364-022dc56f93b7.png)

This is the output on Xcode:
```
⚡️  Loading app at capacitor://localhost...
⚡️  WebView loaded
```

### Expected Behavior
On the web version and on iOS 14 and 15, the blank app start screen is displayed.
![Simulator Screen Shot - iPhone 13 Pro - 2022-06-15 at 12 30 48](https://user-images.githubusercontent.com/11888433/173806673-832d7d1b-736c-413c-a5ab-9f7d4a058dcd.png)

### Code Reproduction
I've been able to reproduce the issue with the blank app from the ionic start command.
Those are the commands I used to create the app:
```
ionic start
// select blank template and angular
cd APP_FOLDER
npm install @capacitor/core
npm install @capacitor/cli --save-dev
npx cap init
npm install @capacitor/ios
npx cap add ios
ionic build
npx cap sync ios
```
Here is the resulting app: https://github.com/catt-stefano/testBlankIOS

### Other Technical Details

`npm --version` output: 8.12.1

`node --version` output: v16.13.2

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment]
Angular 14 only supports latest 2 iOS versions by default, that leaves iOS 13 out

Check this link for Angular 13 but change es2020 instead of es2015
https://ionicframework.com/docs/reference/browser-support#a-note-on-angular-13-support
