### ISSUE TITLE
Error: "custom" plugin is not implemented on electron: 

### ISSUE THREAD

**Issue by mjaga** [ionic-team/capacitor#5689]
### Capacitor Version - 3.0
core.mjs:6485 ERROR Error: Uncaught (in promise): Error: "custom" plugin is not implemented on electron
Error: "custom" plugin is not implemented on electron
    at createPluginMethod

**Comment by jcesarmobile** [comment]
Sorry, no idea what you are talking about, but electron isn’t a community platform now, you can report issues on its own repository
https://github.com/capacitor-community/electron/issues

But I would recommend to give more details about the issue and provide a sample app where the issue can be reproduced
