### ISSUE TITLE
Documention issue

### ISSUE THREAD

**Issue by Dan203** [ionic-team/capacitor#569]
Not sure if this is the right place to post this, but on the docs page if you're on an iPad in portrait mode the hamburger button that should show the side menu does not work. Click it and it does nothing. I have to disable orientation lock and turn iPad sideways to navigate the docs.

**Comment by kevinports** [comment]
@mlynch Fixed here: https://github.com/ionic-team/capacitor/commit/994489984b218884ca5fb3d1dd48bc092ddc3b7d can you redeploy?

**Comment by jcesarmobile** [comment]
Closing as web was redeployed and the bug is no longer present
