### ISSUE TITLE
bug: npx cap sync android didn't remove Cordova plugin configurations settings when removed that plugin

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/capacitor#5711]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/android: 3.3.1
  @capacitor/core: 3.3.0
  @capacitor/ios: 3.3.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

I have used this plugin with my app and later stage I removed it.
`Social Sharing:` https://ionicframework.com/docs/native/social-sharing

But  `npx cap sync android` didn't remove relevant plugin details from the

\android\app\src\production\res\xml\config.xml 

```
<feature name="SocialSharing">
    <param name="android-package" value="nl.xservices.plugins.SocialSharing"/>
  </feature>
```

\android\app\src\main\AndroidManifest.xml

`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />`

### Expected Behavior

We would like to remove them all from the above locations.

### Other Technical Details

`npm --version` output:

6.14.12

`node --version` output:

v14.16.1

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
