### ISSUE TITLE
Bounce effect that moves entire view

### ISSUE THREAD

**Issue by alpine-gh** [ionic-team/capacitor#5734]
Expected (Cordova):
https://i.imgur.com/6fTCJDk.mp4

Actual (Capacitor):
https://i.imgur.com/Q9Vt3Sk.mp4

This doesn't happen in Cordova but it does in Capacitor. It happens randomly when scrolling or when gripping from the toolbar.

**Comment by jcesarmobile** [comment]
Please, when creating issues don’t delete the template, provide all the requested information, including a sample app where the issue can be reproduced.
Closing the issue as invalid.
