### ISSUE TITLE
msg.toLowerCase is undefined

### ISSUE THREAD

**Issue by bazuka5801** [ionic-team/capacitor#5740]
Platform: iOS 15
Browser Platform: WebKit

https://github.com/ionic-team/capacitor/blob/1451ec850a9ef73267a032638e73f1fc440647b9/core/native-bridge.ts#L385

![image](https://user-images.githubusercontent.com/11452353/177244287-a2813883-c7b9-4d3b-a156-ce317623dc57.png)

In some cases, `msg` can contain CustomEvent error instead of string 
![image](https://user-images.githubusercontent.com/11452353/177244470-42e01ff0-5394-4c3b-94d9-3313bc142f9c.png)

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by bazuka5801** [comment]
@jcesarmobile Please, reopen
