### ISSUE TITLE
bug: ios getPhoto "Select more photos"

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/capacitor#5747]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS 15

### Current Behavior
When you initially start an App, you will get asked if a user is allowed to select all Photos or only some specific. 
If the User select some speific and then restart the app and request again a Photo with getPhoto function from Capacitor Camera the Promise will resolve the image data will return and then iOS asks if he want to select more Photos or keep the current selection. 

Can this be adjusted to prevent the popup? Because i only want to select one Photo not multiple. 
![image](https://user-images.githubusercontent.com/19570043/177518769-4ab1ed5f-64aa-48a4-aff8-34b566c8b120.png)
![image](https://user-images.githubusercontent.com/19570043/177518380-54d0d683-3269-465c-9b69-ab9db0d0cb25.png)

### Expected Behavior
There are two possible Behaviors.
1. The iOS Popup should not be shown because it is a single selection and it should not be possible to select more photos. 
2. The Popup will be shown and after the seconds selection the Promise will resolve not before. 

### Code Reproduction
1. Install Capacitor 
2. use Capacitor Camera
3. use getPhoto Method
4. start the iOS App
5. select a Image
6. Wait for the popup and select "Select more photos..."
https://github.com/danielehrhardt/ios-getphoto-popup

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by danielehrhardt** [comment]
https://github.com/danielehrhardt/ios-getphoto-popup

**Comment by josephvoxone** [comment]
How about this, maybe this helping. 
![image](https://user-images.githubusercontent.com/26720255/177542571-8ad35c62-2608-404f-be30-f0884e3aba74.png)
GalleryImageOptions you can set a **limit** 

https://capacitorjs.com/docs/apis/camera#galleryimageoptions

**Comment by josephvoxone** [comment]
Oh, I think it's only working on iOS 13 and older versions.
![image](https://user-images.githubusercontent.com/26720255/177544290-e2979bc9-7dd8-4cee-b995-a94875764f23.png)

**Comment by jcesarmobile** [comment]
Sadly that's the behaviour of the native component used by the Camera plugin to pick images from the gallery and I agree that it's a terrible UX.
It's not really asking you to select more photos, but to allow more photos to be picked next time.

There is nothing we can do from code, but you can prevent the "Select More Photos" prompt by adding this to your Info.plist

```
<key>PHPhotoLibraryPreventAutomaticLimitedAccessAlert</key>
<true/>
```
