### ISSUE TITLE
feat: Implement Themed Icons (Android 13)

### ISSUE THREAD

**Issue by bhandaribhumin** [ionic-team/capacitor#5752]
## Feature Request
Google recently announced the first Developer Preview of Android 13, while there are a lot of new APIs. One of them is that developers got access to API for Themed app icons.

### Platform(s)

Android 13

### Preferred Solution

Add <monochrome android:drawable=""/> attribute to the <adaptive-icon> element.

![1_M2-8CaLjK41Z_IJ3qf_JmQ](https://user-images.githubusercontent.com/3336047/177927682-7ecd8786-9f60-47c0-b154-9a36d16813d8.png)

That’s all, the system automatically applies tint color for the monochrome icon.

### Let’s take a look at the sample icon Microsoft Teams

![1_x6NQ2p8zB3dRsfHBKZ3YFA](https://user-images.githubusercontent.com/3336047/177927564-f4177f4d-d898-4284-9331-022e52d4e89f.png)

**Comment by jcesarmobile** [comment]
Capacitor doesn't generate icons nor restrict you in using this feature in any way, you can add the monochrome icon already if you want.
The only thing we might need to do is to add a default monochrome capacitor icon to the android template that is added when you run `npx cap add android` so it ships with all the icons, but we would do that on next major release once SDK 33 support is officially added.
