### ISSUE TITLE
bug: locate proper Info.plist based on the configured scheme for cordova plugin missing configurations  

### ISSUE THREAD

**Issue by puopg** [ionic-team/capacitor#5755]
## Feature Request

When checking cordova plugins, seems the file name for "Info.plist" is hardcoded. In the guide for Capacitor 3, the guide instructs developers to rename the Info.plist files to things like "App qa-Info.plist". If you are using cordova plugins, warnings start to appear that things may need to be added to the Info.plist, since its looking for the incorrect hardcoded Info.plist file.

This is happening in this method: https://github.com/ionic-team/capacitor/blob/902e1f56af32143b817cf03233264203bcd5adab/cli/src/cordova.ts#L354

This request is to add support for environment specific configuration for what the Info.plist file is named, so that these warnings are properly reported.

Warnings that are displayed are like:

In Capacitor 3.3.3
``` 
[fatal] Unable to read: /Users/myUserName/Desktop/code/project/ios/App/App/Info.plist
[fatal] Unable to read: /Users/myUserName/Desktop/code/project/ios/App/App/Info.plist
```

And in Capacitor 3.6.0, they are no longer `[fatal]` errors, but warnings. A big improvement i must say than in 3.3.3 though!

### Platform(s)
iOS

### Cordova Plugin seen on
Launch Navigator: https://github.com/dpa99c/phonegap-launch-navigator

### Preferred Solution
Maybe add a configuration option in the `ios` config in capacitor to allow developers to specify the name of the Info.plist file to use, default to "Info.plist" if not set to maintain compatibility.

**Comment by jcesarmobile** [comment]
Thanks for the issue.
We already have a "scheme" config option for iOS, but it's not being used for locating the Info.plist path, so it's a bug, not a feature request.
