### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by thevariousartist** [ionic-team/capacitor#5758]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0

### Platform(s)
IOS
Android

### Current Behavior
The Capacitor Browser is having issues with web redirects - with different behaviors in iOS and Android. 

My Ionic app uses the Capacitor Browser plugin to present a Federation Login page. There is an “authentication URL” returned upon successful SSO login - or if the user is already logged in then there is an immediate “authentication URL” redirect.

Here’s what I am seeing…

**iOS**: for a first time login, the web redirect works and deep links back into my app – no problem here. However, if SSO is active, then there is an immediate redirect which the Browser ignores. I can see the URL change, and it works if I open it in a separate mobile web browser.

**Android**: for a first time login, the web redirect is ignored and the user is left stuck in the browser. Again, if I copy the URL to a separate web browser then it deep links back into the app.

### Expected Behavior
Android should observe the redirect in the same manner as iOS upon a successful SSO login.  But they both should observe that redirect if it is returned "immediately" (i.e. the Federation sees an existing SSO session and immediately returns the authenticated redirect URL, instead of the Federation login page)

### Other Technical Details
npm: '8.5.5'
node: '16.15.0'
pod: '1.8.4'

### Additional Context
(none)

**Comment by jcesarmobile** [comment]
The plugin just uses [Android Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs/) and we have no control on it's navigation or behavior.
If it's not working as you expect you should report the issue to Google.

In version 5.0.0 of @capacitor/browser plugin we have updated the dependency to use latest version of custom tabs, not sure if that could have fixed the issues, give it a try and if not, as I said, report it to Google.
