### ISSUE TITLE
bug: Sveltekit ReferenceError: document is not defined

### ISSUE THREAD

**Issue by joejarlett** [ionic-team/capacitor#5763]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0

[error] index.html file is missing in
        C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\android\app\src\main\assets\public
```

### Platform(s)

windows 10 android sveltekit

### Expected Behavior

when running vite dev or vite build I receive the following error 

C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\node_modules\@capacitor\app\dist\plugin.cjs.js:20
        document.addEventListener('visibilitychange', this.handleVisibilityChange, false);
        ^

ReferenceError: document is not defined
    at new AppWeb (C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\node_modules\@capacitor\app\dist\plugin.cjs.js:20:9)
    at C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\node_modules\@capacitor\app\dist\plugin.cjs.js:8:78
    at async loadPluginImplementation (C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\node_modules\@capacitor\core\dist\index.cjs.js:158:47)
error Command failed with exit code 1.

### Code Reproduction

fresh sveltekit install
yarn add @capacitor/core @capacitor/cli @capacitor/android @capacitor/app @capacitor/filesystem
yarn dev

### Other Technical Details

`yarn--version` output: v1.22.5

`node --version` output: v16.15.1

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by joejarlett** [comment]
I tried it again from scratch to make a repository for you and it worked... sorry to waste your time

**Comment by sdekna** [comment]
> I tried it again from scratch to make a repository for you and it worked... sorry to waste your time

I'm stuck at the same problem... any ideas what was the problem?

**Comment by xemuj** [comment]
> > I tried it again from scratch to make a repository for you and it worked... sorry to waste your time
> 
> I'm stuck at the same problem... any ideas what was the problem?

same here

**Comment by sdekna** [comment]
> > > I tried it again from scratch to make a repository for you and it worked... sorry to waste your time
> > 
> > 
> > I'm stuck at the same problem... any ideas what was the problem?
> 
> same here

I believe I solved it by using making sure it is only executed in a browser... something like: `browser &&`
