### ISSUE TITLE
bug: iOS 14 Simulator Reports `isNativePlatform == false`; `getPlatform == "web"`

### ISSUE THREAD

**Issue by billpull** [ionic-team/capacitor#5764]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0
```

### Platform(s)

iOS <= 14
XCode 13.3
NextJS 12.1

### Current Behavior

Running on iOS 14.X via the simulator or actual device capacitor incorrectly reports the platform as `web`.

Calling `Capacitor.isNativePlatform` is `false`
Calling `Capacitor.getPlatform` is `"web"`

### Expected Behavior

Calling `Capacitor.isNativePlatform` is `true`
Calling `Capacitor.getPlatform` is `"ios"`

### Code Reproduction

TBD

### Other Technical Details

`npm --version` output: 8.5.0

`node --version` output: v16.14.2

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

This is a statically built NextJS site using v12.1 
Build command is `yarn build && yarn export && npx cap sync ios`

Using the following plugins:
```
Found 7 Capacitor plugins for ios:
       @capacitor-community/http@1.4.1
       @capacitor/browser@1.0.7
       @capacitor/geolocation@1.3.1
       @capacitor/keyboard@1.2.3
       @capacitor/local-notifications@1.1.0
       @capacitor/share@1.1.2
       capacitor-native-settings@0.2.0
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by billpull** [comment]
I fixed this issue by setting 

```
ios: {
   limitsNavigationsToAppBoundDomains: true
}
```

and adding `localhost` to `WKAppBoundDomains` as suggested by the setting.
