### ISSUE TITLE
bug: Android 9 API 28 App launches with white screen

### ISSUE THREAD

**Issue by KerimM** [ionic-team/capacitor#5765]
## Bug Report
E/Capacitor/Console: File: http://localhost/ - Line 287 - Msg: SyntaxError: Unexpected token .
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught SyntaxError: Unexpected token .","url":"http://localhost/vendor.js","line":22300,"col":38,"errorObject":"{}"}}
E/Capacitor/Console: File: http://localhost/vendor.js - Line 22300 - Msg: Uncaught SyntaxError: Unexpected token .
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/core: 3.6.0
  @capacitor/cli: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0
```

### Platform(s)
Android

### Current Behavior
App launches with white screen

### Code Reproduction
ionic start 
Angular
Tabs

### Other Technical Details
Mac M1 and Windows 10

Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true, ide.instant.shutdown=false
Non-Bundled Plugins: org.jetbrains.kotlin (212-1.7.0-release-281-AS5457.46)

`npm --version` output:  8.12.1

`node --version` output: v18.4.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context
None

**Comment by jcesarmobile** [comment]
angular, by default, only supports latest 2 android versions, if you want to support older versions you have to configure your app to compile to es5

This note on Ionic docs talks about iOS 13, but will also help you with Android
https://ionicframework.com/docs/reference/browser-support#a-note-on-angular-13-support
