### ISSUE TITLE
bug: Problem when compile to ios on M1 Apple

### ISSUE THREAD

**Issue by ruialves7** [ionic-team/capacitor#5766]
### Capacitor Version
npx cap doctor

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

package.json
{
  
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~14.0.6",
    "@angular/core": "~14.0.6",
    "@angular/forms": "~14.0.6",
    "@angular/platform-browser": "~14.0.6",
    "@angular/platform-browser-dynamic": "~14.0.6",
    "@angular/router": "~14.0.6",
    "@awesome-cordova-plugins/calendar": "^5.44.0",
    "@awesome-cordova-plugins/in-app-browser": "^5.44.0",
    "@capacitor-community/apple-sign-in": "^1.0.1",
    "@capacitor-community/contacts": "^1.1.3",
    "@capacitor-community/facebook-login": "^3.4.0",
    "@capacitor-community/stripe": "^3.8.2",
    "@capacitor/android": "3.6.0",
    "@capacitor/app": "^1.1.1",
    "@capacitor/camera": "^1.3.1",
    "@capacitor/core": "^3.6.0",
    "@capacitor/device": "^1.1.2",
    "@capacitor/filesystem": "^1.1.0",
    "@capacitor/ios": "3.6.0",
    "@capacitor/keyboard": "^1.2.3",
    "@capacitor/network": "^1.0.7",
    "@capacitor/push-notifications": "^1.0.9",
    "@capacitor/share": "^1.1.2",
    "@capacitor/splash-screen": "^1.2.2",
    "@capacitor/storage": "^1.2.5",
    "@fortawesome/angular-fontawesome": "^0.11.1",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-brands-svg-icons": "^6.1.1",
    "@fortawesome/free-regular-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@ionic/angular": "^6.1.14",
    "@ionic/angular-toolkit": "^6.1.0",
    "@ionic/cli": "^6.20.1",
    "@ionic/pwa-elements": "^3.1.1",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@pantrist/capacitor-firebase-dynamic-links": "^1.1.2",
    "cordova-plugin-calendar": "^5.1.6",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "ionic-cordova-oauth": "0.0.9",
    "ionic2-calendar": "^0.6.9",
    "native-run": "^1.6.0",
    "rxjs": "~7.5.6",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.6"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.6",
    "@angular/cli": "14.0.6",
    "@angular/compiler": "~14.0.6",
    "@angular/compiler-cli": "~14.0.6",
    "@angular/language-service": "~14.0.6",
    "@capacitor/cli": "^3.6.0",
    "@ionic/lab": "3.2.13",
    "@types/jasmine": "~4.0.3",
    "jasmine-core": "~4.2.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~10.9.1",
    "tslint": "~6.1.3",
    "typescript": "~4.7.4"
  },
  "description": "Uma prenda à distância de um click",
  "cordova": {
    "plugins": {},
    "platforms": []
  }
}

### Platform(s)
ios

### Current Behavior
When i run ionic capacitor run ios --prod, the process stay in waiting mode indefinitely

### Other Technical Details
Apple M1

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ruialves7** [comment]
Hi,

I have a macbook pro with M1 CPU. If you install, on mac with same specs, my dependencies, you will see the problem. Basically, when i run " ionic capacitor  build ios --prod" with my dependencies installed, the xcode never opens. It don't return a error, but the process stay blocked on updating plugins phase and never terminate. If you need i can send a video.

Rui

**Comment by jcesarmobile** [comment]
Sorry, I can't reproduce and also have a M1 CPU mac, so might be something wrong with your computer.

Since the command not completing is an ionic command, the problem might be on ionic CLI, so you should report it in that repository https://github.com/ionic-team/ionic-cli

But first, if you didn't install CocoaPods from homebrew or other package manager but instead installed it directly with gem install, try this https://capacitorjs.com/docs/ios/troubleshooting#apple-silicon-ffi-bus-error

**Comment by ruialves7** [comment]
Hello,
I don't believe it's from my PC. I can compile the android version without any problem. With ios, after a lot of trying I end up getting it too.

I've followed all these tutorials and HOWTOs. This situation only started to happen after the last sdk update.

But it's ok I understand that it is a specific problem.

Thank you for your help,
Rui
