### ISSUE TITLE
How to setup unique accessibility IDs for Capacitor components to use with Appium

### ISSUE THREAD

**Issue by rocklaam** [ionic-team/capacitor#5772]
### Discussed in https://github.com/ionic-team/capacitor/discussions/5771

<div type='discussions-op-text'>

<sup>Originally posted by **rocklaam** July 19, 2022</sup>
Hey guys, my project has finished building an App using Capacitor and React. Currently, we are setting up a Java Appium project to automate test cases with this app. We are trying to add accessibility IDs or class names for React components like this:

![image](https://user-images.githubusercontent.com/29154789/179716510-ae61f7e3-19ec-4206-9ff5-7040a547fd6c.png)

However, when running the testing .apk (Android) and .ipa (iOS) file with the Appium inspector, all components were transformed into native flatform components like this: 
**[Android]**
![image](https://user-images.githubusercontent.com/29154789/179716889-56dab533-c276-47c1-9b4d-64a44ab3d47c.png)

**and [iOS]**
![image](https://user-images.githubusercontent.com/29154789/179716963-5f1a4919-f5b0-4f5e-8c09-3af561d88b67.png)

In Android, we can get component's ids via resource-id, but we can't in iOS builds.

Is our approach a proper solution or do we need to follow another way? In case our solution is correct, what do we need to get Ids for the iOS platform?

Looking forward to your answers, thank you very much!</div>

**Comment by jcesarmobile** [comment]
I'm sorry that nobody has answered in your discussion, but this is not a capacitor bug, so I'm closing it.
I'm not very familiar with appium, but using ids have worked for me in the past. Make sure you are using WebView context and not the native context
https://appium.io/docs/en/writing-running-appium/web/hybrid/
