### ISSUE TITLE
value of type 'CAPBridgeViewController' has no member 'getWebView'

### ISSUE THREAD

**Issue by Manu43236** [ionic-team/capacitor#5775]
i have flutter project wrapping the react project into webview using capacitor. So now i have upgraded capacitor to 3.6.0 after upgrade i am facing an issue with iOS. can't able to accept the flutter app deligate #3123 #5312 

<img width="822" alt="Screenshot 2022-07-20 at 11 28 59 AM" src="https://user-images.githubusercontent.com/22816151/179907796-9f0b844c-cf7e-4986-8d21-0ec341684486.png">

**Comment by jcesarmobile** [comment]
`getWebView` method was removed in Capacitor 3 from CAPBridgeViewController, you can use just `webView` instead.
But the error doesn't seem to indicate that there is something wrong with CAPBridgeViewController but with your FlutterAppDelegate, can you provide a sample app so we can investigate further?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
