### ISSUE TITLE
bug: Capacitor 4 plugin is not implemented on android

### ISSUE THREAD

**Issue by michaeltintiuc** [ionic-team/capacitor#5779]
### Capacitor Version

```
  @capacitor/ios: not installed
  @capacitor/android: 4.0.0-beta.2
  @capacitor/cli: 4.0.0-beta.2
  @capacitor/core: 4.0.0-beta.2
```

### Platform(s)

- Android

### Current Behavior

Follow the [Plugin tutorial](https://next.capacitorjs.com/docs/plugins/tutorial/introduction) and update to v4

### Expected Behavior

The plugin should be registered and not throw errors

### Code Reproduction

https://github.com/michaeltintiuc/capacitor-4-plugin-tutorial

### Other Technical Details

`npm --version` output: `8.11.0`

`node --version` output: `v16.15.1`

`pod --version` output (iOS issues only):

### Additional Context

iOS versions seems to be working fine.

**Comment by jcesarmobile** [comment]
In Capacitor 4 you have to call registerPlugin before super.onCreate instead of after, I've created an issue on the docs repository to address it, thanks for testing Capacitor beta!
https://github.com/ionic-team/capacitor-docs/issues/16
