### ISSUE TITLE
bug: getCapacitorElectronConfig() not working, due to minification's issue

### ISSUE THREAD

**Issue by NoxFly** [ionic-team/capacitor#5784]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3
  @capacitor/core: 3.4.3
```

### Platform(s)
Windows 10

### Current Behavior
The `getCapacitorElectronConfig()` returns an empty object `{}` while the file exists and the configuration isn't empty.

### Expected Behavior
This function should return the (non-empty) object.

### Code Reproduction
This bug does not need any code reproduction, because it's not due to a code's issue, but to a minification's issue. See the Additional Context section.

If you really need one, just tell me, but please, read this section before any code reproduction request.

### Other Technical Details

`npm --version` output: 8.12.2

`node --version` output: v16.14.2

`pod --version` output (iOS issues only):

### Additional Context

It seems that in `node_modules/@capacitor-community/electron/dist/core/index.js`, in this minified file, `getCapacitorElectronConfig` will call the `Y()` function.

I just tried some things on it and I found something.

I just developed it a bit so it's cleaner to show you were it is.

Here is the default minified Y function : 
```js
function Y(){let e={};return(0,h.existsSync)((0,b.join)(l.app.getAppPath(),"build","capacitor.config.js"))?e=require((0,b.join)(l.app.getAppPath(),"build","capacitor.config.js")).default:e=JSON.parse((0,h.readFileSync)((0,b.join)(l.app.getAppPath(),"capacitor.config.json")).toString()),e.electron&&(g=T(g,[e])),Z(g)}
```

```js
function Y() {
	let e={};

	const path = (0,b.join)(l.app.getAppPath(),"build","capacitor.config.js");
	const pathJSON = (0,b.join)(l.app.getAppPath(),"capacitor.config.json")

	console.log('config exists ? -> ', (0,h.existsSync)(path));

	return (0,h.existsSync)(path)
		? e = require(path).default
		: e = JSON.parse((0,h.readFileSync)(pathJSON).toString())
        ,e.electron && (g = T(g, [e])),Z(g); // <-- this line
}
```
The last line is the bug, and returns an empty object.
The minifier puts comma `,` before `e.electron` and `Z(g)`. If instead we put `;`, the code is working and the object is well returned.

Hence, you should check this function. It seems that your code is right but the minifier you use just broke your code here.

It's too bad, because I can't use CapacitorSplashScreen, and much more. Hope you'll fix this as soon as possible.

**Comment by jcesarmobile** [comment]
@capacitor-community/electron is community maintained, you should report the issue on their own repository

https://github.com/capacitor-community/electron
