### ISSUE TITLE
bug: capacitor-google-maps does not appear

### ISSUE THREAD

**Issue by GuillaumeGascon** [ionic-team/capacitor#5791]
### Capacitor Version

@capacitor/cli: 3.6.0
@capacitor/core: 3.6.0
@capacitor/android: 3.6.0
@capacitor/ios: 3.6.0

### Platform(s)

Android (not checked on iOS)

### Current Behavior

The Google logo show on the bottom of the page but the map does not appear

![This is an image](https://i.ibb.co/jDF5msZ/Screenshot-20220726-094804-Shareman-scaled.jpg)

### Expected Behavior

I should see the map

### Code Reproduction

Typescript :

```
import { Component, ElementRef, ViewChild } from '@angular/core';
import { GoogleMap } from '@capacitor/google-maps';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'register-available-services',
  templateUrl: './register-available-services.page.html',
  styleUrls: ['./register-available-services.page.scss'],
})
export class RegisterAvailableServicesPage {

  @ViewChild('map', {static: true, read: ElementRef}) mapElement!: ElementRef;

  map!: GoogleMap;

  progressValue = 6 / 6;

  constructor() { }

  async ionViewDidEnter(): Promise<void> {
    await this.createMap();
  }

  async createMap(): Promise<void> {
    document.querySelector('body')?.setAttribute('style', 'background: transparent !important');
    this.map = await GoogleMap.create({
      forceCreate: true,
      id: 'google-map',
      element: this.mapElement.nativeElement,
      apiKey: environment.googleMapsApiKey,
      config: {
        center: {
          lat: 33.6,
          lng: -117.9,
        },
        zoom: 8,
      }
    });
  }

}
```

HTML:

```
<header
  [title]="'Services disponible'"
  [displayGoBack]="true"
  [displayProgressBar]="true"
  [progressValue]="progressValue.toString()"></header>

<ion-content>
  <div class="content">
    <capacitor-google-map #map></capacitor-google-map>
  </div>
</ion-content>
```
SCSS:

```
ion-content {
  --background: none !important;
  background: transparent;
  .content {
    width: 100%;
    height: 100%;
    capacitor-google-map {
      display: inline-block;
      width: 100%;
      height: 100%;
    }
  }
}
```

### Other Technical Details

`npm --version` output: 6.14.11

`node --version` output: 14.15.5

### Additional Context

I've tried several things:

- Use ngAfterViewInit instead of ionViewDidEnter;
- Use a setTimeout;
- Not wrapping capacitor-google-map in a div;
- Set capacitor-google-map  with a fixed height and width;

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by GuillaumeGascon** [comment]
My bad, i wasn't using the right API Key so that's why the map does not appear.
