### ISSUE TITLE
File type input does not work in Capacitor V3 - Android

### ISSUE THREAD

**Issue by EdissonG** [ionic-team/capacitor#5794]
Hi,

File type input does not work in capacitor v3

### Capacitor Version V3 - Ionic V6

I'm using input type file and the way to upload files, I'm doing it natively with Javascript, and it works fine on web, but when I'm going to use it on Android it doesn't upload any files:

https://user-images.githubusercontent.com/64019193/181138342-54031a1b-31cd-40ca-904f-09bda8e4ed61.mp4
```
<button type="button" mat-raised-button (click)="fileInput.click()">{{ field.label }}</button>
<input hidden type="file" onclick="this.value = null" (change)="onFileChange($event)" capture #fileInput>
```

I don't understand why it doesn't work if Ionic is really supposed to be running HTML, and I'm also using Ckeditor V5, and it has the same problem. Likewise, I talked to an acquaintance, and he told me he has the same issue and he thinks it's because of the Web View.

The only solutions I see is to use plugins :/ and I don't know which ones to use and logically Ckeditor would keep the issue.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by EdissonG** [comment]
Hi, 

I really do not see that it is necessary to replicate the case when it is evident that it is a bug(I'm sure) or if there is any possible solution may already happen to someone because I do not think it is the only case.

I attach a video where it is clearly evidenced that on PC it works <input type="file">

https://user-images.githubusercontent.com/64019193/181405221-e66121c0-24d3-436b-b4b5-fac1fe10006c.mp4

And also the solution is to look for a third party plug-in that solves it :(.

Thank you.

**Comment by EdissonG** [comment]
Hi, 

Solved :D

I was helped by the solution of  @tripodsgames
https://github.com/ionic-team/capacitor/issues/1564
