### ISSUE TITLE
bug:  Livereload not rebuilding the Ios on xcode 

### ISSUE THREAD

**Issue by StefaniToto** [ionic-team/capacitor#5796]
Im trying to livereload my app.
On Windows => VScode

`ionic capacitor run android -l --external --adress `

After entering the comand will show a list of simulators/devices and after i choose one the app is installed there and rebuilded after every change.`

On Mac => VScode

`ionic capacitor run ios-l --external --adress `

After entering the comand Xcode is open. (No devices are listes as in windows) Installing the app through Xcode. On VScode changes are detected but no rebuild is happen on device/simulator.

Any solution please ?

   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/android: 3.6.0
  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/ios: 3.6.0

**Comment by jcesarmobile** [comment]
what's your @ionic/cli version in macOS? looks like you are using an old version

**Comment by StefaniToto** [comment]
@jcesarmobile 

`
Angular CLI: 13.3.8
Node: 16.16.0
Package Manager: npm 8.11.0
OS: darwin x64

Angular: 13.3.11
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.8
@angular-devkit/build-angular   13.3.8
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cli                    13.3.8
@schematics/angular             13.3.8
rxjs                            6.6.7
typescript                      4.4.4`

**Comment by jcesarmobile** [comment]
Latest @ionic/cli is 6.20.1
https://www.npmjs.com/package/@ionic/cli

You are using the old and deprecated ionic package which has not been updated for 2.5 years

Run

```
npm uninstall -g ionic
npm install -g @ionic/cli 
```

**Comment by StefaniToto** [comment]
@jcesarmobile Thanks a lot
