### ISSUE TITLE
Invalid `Podfile` file: cannot load such file -- /Users/admin/CapProject/node_modules/@capacitor/ios/scripts/pods_helpers.

### ISSUE THREAD

**Issue by victorybiz** [ionic-team/capacitor#5798]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.0.0
  @capacitor/core: 4.0.0
  @capacitor/android: 4.0.0
  @capacitor/ios: 4.0.0

Installed Dependencies:

  @capacitor/cli: 4.0.0
  @capacitor/core: 4.0.0
  @capacitor/android: 4.0.0
  @capacitor/ios: 4.0.0
```

### Platform(s)

iOS

### Current Behavior

I successfully upgraded from Capacitor v3 to v4 following the step-by-step Upgrade Guides on the Capacitor Documentation. But when I run `npx cap sync ios` or `ionic cap sync ios`, it run into the following error
```
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] 
        [!] Invalid `Podfile` file: cannot load such file --
        /Users/admin/CapProject/node_modules/@capacitor/ios/scripts/pods_helpers.
        
        #  from
        /Users/admin/CapProject/ios/App/Podfile:1
        #  -------------------------------------------
        >  require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
        #
        #  -------------------------------------------
```
it seems the `node_modules/@capacitor/ios/scripts/pods_helpers` file is missing in the current release.

### Expected Behavior

Should install, copy and sync dependencies for ios.

**Comment by jcesarmobile** [comment]
How did you migrate?
That step is not documented for the step to step guide, should only happen if you used `npx cap migrate` command.

As workaround you can remove the `require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'` line and this block 
```
post_install do |installer|
    assertDeploymentTarget(installer)
  end
```

**Comment by victorybiz** [comment]
Thank you @jcesarmobile, your workaround worked. 
I actually used `npx cap migrate` and then went through the guide to ensure all value was updated.

**Comment by jcesarmobile** [comment]
let's keep it open until the linked PR is merged

**Comment by ronaldomatos** [comment]
I just created a new project and got that!  Thx @jcesarmobile works to in here!

**Comment by leafac** [comment]
Like @ronaldomatos, I ran into this issue when trying to follow [the tutorial on getting started](https://capacitorjs.com/docs/getting-started). And I confirm that the workaround proposed by @jcesarmobile worked.

Congratulations to the team working on Capacitor! It’s really well put together, the documentation is great, and the responsiveness in issues like this is just outstanding 👏

**Comment by scr2em** [comment]
Got the same issue. @victorybiz thanks for being proactive.

**Comment by jcesarmobile** [comment]
@capacitor/ios 4.0.1 is now out with the fix, you can run migrate command again and it will add the failing code if you removed it and fix other issues it caused on android themes

**Comment by mamun223** [comment]
This was really helpful. Thanks for sharing!
