### ISSUE TITLE
capacitor, can we create some native UI like floating, widgets, bubbles or status bar ?

### ISSUE THREAD

**Issue by hiepxanh** [ionic-team/capacitor#581]
Yes, I hear that project [ACE from Microsoft ](http://microsoft.github.io/ace/) can linking, invoke native code from javascript. But it to difficult to use. Can Capacitor have some strategy to creating just a widget for example with Ionic code ?

I know that is an exaction. But I just need some Idea, just an idea... strategy or flow... that may help me to create and connecting with native code to create widgets for example on android. 

just give me some comment, I will mark issue is closed as soon as I have some idea.

**Comment by mlynch** [comment]
Thanks for the question, we have some plans to help with native app shell (navigation/etc.), while keeping most of the page content web based. Nothing too concrete at this point

**Comment by mhamri** [comment]
can I bring this one back to life? 
@mlynch any update on this? I'm looking for some solution for creating floating with the capacitor or unfavourably the Cordova

**Comment by vanishedvan** [comment]
Any updates on this?

**Comment by mlynch** [comment]
Take a look at Ionic Portals which we launched recently and makes it easy to embed Capacitor into existing native apps so you can get full UI control: https://ionic.io/portals
