### ISSUE TITLE
Get last PluginCall instance on resume

### ISSUE THREAD

**Issue by triniwiz** [ionic-team/capacitor#582]
Is there a way to save/restore a plugin call instance on app resume ? What i'm trying to is use the Chrome Custom Tabs to do sso so after the app has been resumed i would like use the same plugin call to return the data that was lasted used.

**Comment by mlynch** [comment]
Yep there is! I am mobile right now but take a look at the App API for the restore event. Let me know if that helps for now and I can answer more questions later

**Comment by triniwiz** [comment]
I saw there is one used for activity results but when creating a new instance I think it uses the private msgHandler instance

**Comment by triniwiz** [comment]
Figured out a work around

**Comment by jcesarmobile** [comment]
would be good if you can comment the workaround, maybe it's something we should document, or fix so you don't need a workaround

**Comment by triniwiz** [comment]
@jcesarmobile I stored the call in a static variable then onResume I saved the call after that i was able to use the call
