### ISSUE TITLE
feat: send route path to route processor

### ISSUE THREAD

**Issue by gugu** [ionic-team/capacitor#5830]
## Feature Request

It would be great if RouteProcessor's process method in Android gets actual path instead of index.html

### Description

If I have multiple index.html files and want to open /settings/index.html if URL is /settings/subpath/subpath, /other/index.html if URL is /other/subpath/subpath and /index.html in other cases. Previously I did this by monkey patching your module, but this time I noticed RouteProcessor class, which is created for custom routes. The problem is it sends path /index.html for every route without file extension and does not send actual path. Request path attribute in this process method will make it suitable for custom routing

### Platform(s)

Android

### Preferred Solution

call `routeProcessor.process(basePath, path)` instead of `routeProcessor.process(basePath, '/index.html')`

### Alternatives
call `routeProcessor.process(basePath, '/index.html', path)` instead of `routeProcessor.process(basePath, '/index.html')`

**Comment by jcesarmobile** [comment]
Can you provide more details about your use case?
We only append `index.html` if the url to process is `/` or doesn't have a `.` on it (is not a file with extension). 
Since you say you are loading different `index.html` files, they have the `.`, so shouldn't load the default one.
How are you loading those?

**Comment by gugu** [comment]
Example: /settings/abc/def => /settings/index.html
/everything/else => /index.html

**Comment by jcesarmobile** [comment]
Yeah, I understood that from the issue description.
I meant more details about what you are trying to accomplish with the route processor, are you using your own class?
how are you navigating to those urls?

I think it should be possible to do at the moment, but would involve using your own BridgeWebViewClient subclass and RouteProcessor, but can be messy.

**Comment by jcesarmobile** [comment]
Closing since there was no response.

Also I've verified that the route processor receives the whole path, the problem is that the default behavior of the "local server" is to append the `index.html`, so the feature looks like a duplicate of this one (allow loading from alternate paths) https://github.com/ionic-team/capacitor/issues/3912

**Comment by gugu** [comment]
I use npm patch-package, here are my changes:
```
diff --git a/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift b/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift
index 54faf2d..dd65dff 100644
--- a/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift
+++ b/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift
@@ -13,7 +13,7 @@ import Cordova
 // swiftlint:disable lower_acl_than_parent
 // swiftlint:disable file_length
 // swiftlint:disable type_body_length
-internal class CapacitorBridge: NSObject, CAPBridgeProtocol {
+public class CapacitorBridge: NSObject, CAPBridgeProtocol {
 
     // this decision is needed before the bridge is instantiated,
     // so we need a class property to avoid duplication
@@ -88,7 +88,7 @@ internal class CapacitorBridge: NSObject, CAPBridgeProtocol {
     public static let fileStartIdentifier = "/_capacitor_file_"
     public static let defaultScheme = "capacitor"
 
-    var webViewAssetHandler: WebViewAssetHandler
+    public var webViewAssetHandler: WebViewAssetHandler
     var webViewDelegationHandler: WebViewDelegationHandler
     weak var bridgeDelegate: CAPBridgeDelegate?
     @objc public var viewController: UIViewController? {
diff --git a/node_modules/@capacitor/ios/Capacitor/Capacitor/WebViewAssetHandler.swift b/node_modules/@capacitor/ios/Capacitor/Capacitor/WebViewAssetHandler.swift
index 9dbff7a..6ed474f 100644
--- a/node_modules/@capacitor/ios/Capacitor/Capacitor/WebViewAssetHandler.swift
+++ b/node_modules/@capacitor/ios/Capacitor/Capacitor/WebViewAssetHandler.swift
@@ -2,15 +2,15 @@ import Foundation
 import MobileCoreServices
 
 @objc(CAPWebViewAssetHandler)
-internal class WebViewAssetHandler: NSObject, WKURLSchemeHandler {
+public class WebViewAssetHandler: NSObject, WKURLSchemeHandler {
 
     private var basePath: String = ""
 
-    func setAssetPath(_ assetPath: String) {
+    public func setAssetPath(_ assetPath: String) {
         self.basePath = assetPath
     }
 
-    func webView(_ webView: WKWebView, start urlSchemeTask: WKURLSchemeTask) {
+    public func webView(_ webView: WKWebView, start urlSchemeTask: WKURLSchemeTask) {
         var startPath = self.basePath
         let url = urlSchemeTask.request.url!
         let stringToLoad = url.path
@@ -55,7 +55,7 @@ internal class WebViewAssetHandler: NSObject, WKURLSchemeHandler {
         urlSchemeTask.didFinish()
     }
 
-    func webView(_ webView: WKWebView, stop urlSchemeTask: WKURLSchemeTask) {
+    public func webView(_ webView: WKWebView, stop urlSchemeTask: WKURLSchemeTask) {
         CAPLog.print("scheme stop")
     }
 
```

**Comment by gugu** [comment]
Probably it was an issue for capacitor@v3, and it is okay now

**Comment by gugu** [comment]
Yes, I guess it was an issue when I posted an issue, looks like everything is okay now
