### ISSUE TITLE
bug: location.Priority not found geolocation

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/capacitor#5834]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1
```

### Platform(s)

android

### Current Behavior
@capacitor/geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/Geolocation.java:15: error: cannot find symbol
import com.google.android.gms.location.Priority;
                                      ^
  symbol:   class Priority
  location: package com.google.android.gms.location

### Expected Behavior
No error

### Code Reproduction
Install Cap 4.0.1

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
https://capacitorjs.com/docs/updating/4-0#geolocation

> playServicesLocationVersion has been updated to 20.0.0

You have to remove your `playServicesLocationVersion` variable from variables.gradle so it uses version 20.0.0 or update the value to 20.0.0 in variables.gradle

**Comment by danielehrhardt** [comment]
> https://capacitorjs.com/docs/updating/4-0#geolocation

maybe something for:
`npx cap migrate`
