### ISSUE TITLE
bug: Could not find module 'GoogleMapsUtils' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor#5838]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/ios: 4.0.1
```

### Platform(s)

- iOS

### Current Behavior

Building with Capacitor 4 shows this in Xcode:

```
Could not find module 'GoogleMapsUtils' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: /Users/marvin/Library/Developer/Xcode/DerivedData/App-crqbxbzyeutdeicjehmylpqenxfw/Index.noindex/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Modules/GoogleMapsUtils.swiftmodule
```

### Other Technical Details

`npm --version` output: pnpm 7.9.0

`node --version` output: 18

`pod --version` output (iOS issues only): 1.11.3

**Comment by IT-MikeS** [comment]
Unfortunately Google Maps SDK currently doesn't support running on Simulators on a M1 or newer chips, we outline it in the linked section of the docs below. However if you use a real device you will be fine.

https://capacitorjs.com/docs/apis/google-maps#ios

**Comment by muuvmuuv** [comment]
Ah, jesus, so sorry... I read this ten times when Google Maps came out but was sick last week so just upgrade to Cap 4 and did not thought about that line argh

**Comment by IT-MikeS** [comment]
All good, you wouldn't believe how often I miss things that I look back on and go: "oh, well then" 😂
