### ISSUE TITLE
Google Plus Auth

### ISSUE THREAD

**Issue by ttibau** [ionic-team/capacitor#585]
Hello, 
I installed the plugin: https://github.com/EddyVerbruggen/cordova-plugin-googleplus and in @ionic-native I need to put **my client reverse id**, but i don't see where I need to put this client reverse id in capacitor. 

How I configure Google Plus Auth with capacitor.
Thanks for anything!

**Comment by jcesarmobile** [comment]
When running `npx cap update ios` or `npx cap sync ios` you should get a message like this that explains what to do:

> Plugin cordova-plugin-googleplus might require you to add 
>     <dict>
>       <key>CFBundleTypeRole</key>
>       <key>CFBundleURLName</key>
>       <key>CFBundleURLSchemes</key>
>       <string>Editor</string>
>       <string>REVERSED_CLIENT_ID</string>
>       <array>
>         <string>$REVERSED_CLIENT_ID</string>
>       </array>
>     </dict>
>    in the existing CFBundleURLTypes entry of your Info.plist to work

Looks like it's not properly formated, you should add it like this:

        ```
        <dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLName</key>
            <string>REVERSED_CLIENT_ID</string>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>$REVERSED_CLIENT_ID</string>
            </array>
        </dict>
```
You have to replace `$REVERSED_CLIENT_ID` with your client reverse id value

**Comment by jcesarmobile** [comment]
Closing the issue as the "how" is answered.

Created a new one to track the problem where the dict content doesn't appear on the right order
https://github.com/ionic-team/capacitor/issues/586

**Comment by ttibau** [comment]
Thanks for the reply, in ios I get this message that explains how to solve, but not android?

**Comment by ttibau** [comment]
Maybe include `<string name="REVERSED_CLIENT_ID">REVERSE_CLIENT_ID</string>` in **strings.xml** solve this?

**Comment by jcesarmobile** [comment]
I've read the Android docs and code and it doesn't mention/reference anything about the REVERSED_CLIENT_ID there, seems like it's only used for iOS

**Comment by ttibau** [comment]
@jcesarmobile I apologize my confusion, thanks for your reply. 

I installed the plugin with npm and after installed run `npx cap sync`. The capacitor found the plugin:

<img width="743" alt="captura de tela 2018-06-18 as 15 28 28" src="https://user-images.githubusercontent.com/16947646/41555879-697ce838-730f-11e8-9135-5680a677e959.png">

And I tried to use login:
```
this.googlePlus.login({
            'webClientId': 'XXXXXXX.apps.googleusercontent.com',
            'offline' : true  
          }).then(obj => {
            console.log(obj);
          }, error => {
            console.log(error);
          })
```

But in button login clicked, I'm receiving this message: 
<img width="623" alt="captura de tela 2018-06-18 as 15 41 28" src="https://user-images.githubusercontent.com/16947646/41555943-9d94433c-730f-11e8-9884-28f8f5e3dfbd.png">


Can you help me? Thanks for anything!

**Comment by jcesarmobile** [comment]
Doesn't look like it's installed, the plugin should appear as `CordovaPluginGoogleplus`

**Comment by ttibau** [comment]
You're right! Thanks!

**Comment by ttibau** [comment]
@jcesarmobile I'm receiving this message:
> Can only use lower 16 bits for requestCode

I saw in #405  the cause of this problem, do u know if have any solution? 
Thanks again.

**Comment by jcesarmobile** [comment]
No, there is no solution for that, somebody will have to send a PR to the plugin using a lower request code. I did that on phonegap-plugin-barcodescanner for the same reason
