### ISSUE TITLE
bug: Capacitor 4.0.1 API level 26 (Oreo) not starting in emulator

### ISSUE THREAD

**Issue by co-dax** [ionic-team/capacitor#5856]
## Bug Report

Newly created CapacitorJS project (as described in "Code Reproduction" section below) fails to start on Android emulator API level 26 (Oreo) but it works fine on other API levels.

### Capacitor Version
4.0.1

### Platform(s)
Android Oreo API 26
Windows 10

### Current Behavior
Completely fresh capacitor ionic project/application does not start on android emulator Oreo API 26 in Android Studio.

### Expected Behavior
Application should start the same way as in the case of other API levels

### Code Reproduction
1. In command prompt type "ionic start"
2. Choose "Angular"
3. Choose "Tabs" template
4. type "ionic build"
5. Go into the newly created project folder
6. type "ionic build"
7. type "ionic capacitor add android"
8. type "npx cap sync android"
9. In Android Studio open "android" folder within the newly created project folder.
10. Start application with emulator by using a virtual device with level API leve 26 (Oreo)
11. This is the screen I am getting in Logcat:
![image](https://user-images.githubusercontent.com/7594292/184495908-16a048e1-c869-446f-9297-fa97f32444f7.png)

12. This is what I am getting in Chrome Developer Tools:
![image](https://user-images.githubusercontent.com/7594292/184495967-e87cf836-b8e2-46c3-b947-6ac6f94ecca6.png)

13. Device screen in emulator is completely white.

### Other Technical Details
Android Studio Chipmunk | 2021.2.1 Patch 2
NodeJS v16.5.0
Windows 10

`npm --version` output: 8.5.5

`node --version` output: v16.15.0

**Comment by co-dax** [comment]
It started working again.
Seems it is a transient issue. I couldn't reproduce it after it started working again.

**Comment by jcesarmobile** [comment]
angular, by default, only supports latest 2 android versions, if you want to support older versions you have to configure your app to compile to es5

This note on Ionic docs talks about iOS 13, but will also help you with Android
https://ionicframework.com/docs/reference/browser-support#a-note-on-angular-13-support
