### ISSUE TITLE
feat: Implementing native TCP socket functionality

### ISSUE THREAD

**Issue by AmirHmZz** [ionic-team/capacitor#5857]
### Description
TCP Sockets can be used in IOT projects because websockets use lots of RAM in comparision with plain TCP sockets. This feature can help IOT developers to connect their apps via plain TCP socket to their microcontrollers.

### Platform(s)
Android, IOS
Windows, Mac, Linux

### Preferred Solution
There's no other way than doing it natively as long as there's not support for plain sockets in javascript.

**Comment by jcesarmobile** [comment]
You can request community plugins in capacitor-community organization in the proposals repository
https://github.com/capacitor-community/proposals/issues
