### ISSUE TITLE
bug: Whenever I run an Android emulator, AndroidManifest.xml get changed

### ISSUE THREAD

**Issue by npearson72** [ionic-team/capacitor#5858]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior
I am using Ionic 6 with React. I run the following command to start up Android emulator:

`ionic cap run android -l --external --target Pixel_5_API_33`

The emulator starts up, but right away the `AndroidManifest.xml` file get updated and an `AndroidManifest.xml.org` file is added.

When I shut the emulator down, everything goes back to normal. In other words, the changes to the `AndroidManifest.xml` are reverted and the `AndroidManifest.xml.org` is deleted.

I’ve not seen any equivalent behavior with iOS.

### Expected Behavior

I would expect that `AndroidManifest.xml` does not change when I start an emulator.

### Code Reproduction

You can reproduce this by creating a new project `ionic start photo-gallery tabs --type=react --capacitor`

Then add android to the project `ionic cap add android`

Then start up an emulator: `ionic cap run android -l --external --target Pixel_5_API_33`

### Other Technical Details

`npm --version` output: I use yarn: `1.22.19`

`node --version` output: `16.15.1`

`pod --version` output (iOS issues only): `1.11.3`

**Comment by jcesarmobile** [comment]
Capacitor CLI doesn't change your `AndroidManifest.xml` file, since you are using ionic commands it's probably Ionic CLI what's making changes in your `AndroidManifest.xml`, and if it's doing them it's probably because it's needed for live reload and restores the changes after you stop the live reload.
