### ISSUE TITLE
Suggestion about performance improvement - Capacitor vs Cordova

### ISSUE THREAD

**Issue by raxim1** [ionic-team/capacitor#587]
# Approach:
I have made two blank angular cli project (capacitor vs. cordova) - https://cli.angular.io/

# Suggestion:
#### Speed can be improved with `777ms / 1s 433ms` by fixing "major issues" below.

# Logs:
1) Capacitor log: [capacitor_mobile.log](https://github.com/ionic-team/capacitor/files/2117895/capacitor_mobile.log)

2) Cordova log: [cordova_mobile.log](https://github.com/ionic-team/capacitor/files/2117894/cordova_mobile.log)

# Tools:
angular 5.2.0
angular cli - no ionic used
capacitor: 1.0.0-beta - gradle 4
cordova: 8.0.0 - gradle 3 (issue with gradle 4 - what you need to manually solve)
test device: sony xperia z3 compact
android studio: 3.1.3

# Summary:
## Capacitor:
1, Loading Time: 4 s 140ms (06-19 02:35:05.465 - 06-19 02:35:09.605)
2, Memory used: 63-64MB.
3, Dex file size: 3MB
## Cordova:
1, Loading Time: 4s 340ms
2, Memory used: 60MB
3, Dex file size: 70KB

# Major issues (cause major delay):
1) multidex issue or layout problem probably - appears on cordova also
`06-19 02:35:05.705 - 06-19 02:35:06.482` (`777ms`) .../system/bin/dex2oat
2) just right after "CrashFileManager", sometimes the following chromium error happens - cordova_log contains (happened on capacitor also)
`06-19 02:37:36.780 20005-20224/com.raxim.myscoutee E/chromium: [ERROR:budget_service.cc(160)] Unable to connect to the Mojo BudgetService.` (`656ms`)

# Negligible issues (does not cause major delay):
1) "memUsed" has been called too frequently
06-19 02:35:08.429 - 06-19 02:35:08.496 (67ms)
2) Why WebView on android device would like to start "devtool"?
06-19 02:35:07.064 - E/chromium: [ERROR:devtools_http_handler.cc(292)] Cannot start http server for devtools. Stop devtools.
3) Gradle 4 / cordova 8 can be introduced (instead of gradle 3 / cordova 7)

# Webview Team response: (for track record purpose)
1) https://bugs.chromium.org/p/chromium/issues/detail?id=854471 - BudgetService is a log spam
2) https://bugs.chromium.org/p/chromium/issues/detail?id=854472 - devtool is a log spam
3) https://bugs.chromium.org/p/chromium/issues/detail?id=854475 - multidex is an Android Studio issue

**Comment by mlynch** [comment]
Do you have a video of the differences?

Is this an Ionic Angular app or vanilla Angular app? Either way, Angular is not fast to load, so I can guarantee the bulk of the load time you're seeing is Angular related.

Are you using wkwebview for Cordova? That could explain some differences.

I highly doubt there is anything materially different in perf between Cordova and Capacitor once you factor in the above

**Comment by raxim1** [comment]
I just generated a blank project with angular cli, and added cordova in one case and added capacitor in the other case. after that i made an ng build --prod in both case (maybe base-ref is needed)

My approach can be easily reproduced within 10-15 minutes.
https://cli.angular.io/

Unfortunately i cannot take video at the moment.

In the case of cordova i haven't any splash screen, but i have measured the time until it's not going to be a white screen. (that will be the appearance of the webview, the angular part is taking very small amount of time relatively to ionic, as it's a totally empty project - it takes millisec)

I have compared the folder structures and i personally think that the app-compat v7 with all the dependencies causing the issue. Cordova 8 does not include it, just v4 which is much more smaller.

I don't think it's a capacitor code issue, i think it's the issue how many dependencies you are relying on.
I'm aware of the cordova code, there shouldn't be real difference regarding to the bridge etc.

But capacitor is better than Tinder. :)

I have a very complex angular cli based app, and with cordova there is no real difference between the loading time. 500KB difference in js size does not count too much. (maybe some hundred millisec more),
3MB ionic js size definitely counts. I'm an expert in ionic development, as i have grasped some ideas to my self-made framework, and i would have liked to recreate cordova also (i don't think looking at the code is a big deal to really cleanup), as capacitor did. Capacitor seems to me has got extra features which took time.

**Comment by raxim1** [comment]
Ok figured out, but you won't like the results.
I cannot disclose the other log because of security reason, but i have attached the capacitor one.

1) multidex issue propably (777ms) - appears on cordova version also
06-19 02:35:05.705 .../system/bin/dex2oat
06-19 02:35:06.482
2) loading time especially of the empty angular cli app
06-19 02:35:07.910 - 06-19 02:35:08.429 (508ms only)
3) just right after CrashFileManager, sometimes the folowing chromium error happens
06-19 02:37:36.780 20005-20224/com.raxim.myscoutee E/chromium: [ERROR:budget_service.cc(160)] Unable to connect to the Mojo BudgetService.
The main problem with it, that it did cost:
06-19 02:37:36.780 - 06-19 02:37:37.436 (656ms) - i know that it's not your responsibility, but it needs to be pushed to Google aggressively, if you want to achieve improvements on the load time.
4) there are several log
06-19 02:35:08.429 - 06-19 02:35:08.496 (it does not cost too much, but for me there are duplicates, regarding to memUsed - does it necessary to check it within 67ms???)
5) made a mistake - i can tell you it's a bunker
06-19 02:35:09.605 - 06-19 02:35:10.700 - splash screen timed out - (1s 95ms)
In most of the case i don't think it's necessary to hide splash screen when the angular app is finished the load.

[mobile.log](https://github.com/ionic-team/capacitor/files/2113487/mobile.log)

**Comment by jcesarmobile** [comment]
1. on the official page - npm install --save @capacitor/core @capacitor/cli is not correct as @capacitor/cli should be a dev dependency.
You are right, we should change that

2. <script src="native-bridge.js"></script> - needs to be added to the index.html instead of capacitor.js - related videos is confusing

Not really, native-bridge.js is injected into the webview, so you don't have to link it.
capacitor.js is used when you don't use a bundler, so if you don't use a bundler, you need to add `"bundleWebRuntime": true` to the `capacitor.config.json` file and link `capacitor.js` in your index.html
Not sure what related video you refer to

3. I have found an empty cordova.js file under the generated asset folder.
The cordova.js is generated for Cordova compatibility. When no Cordova plugins are found the file is empty.
It's there just in case people is testing an existing Cordova app with cordova.js linked in the index.html, so by generating an empty file the link to cordova.js won't return a 404 error.

4. there is a typo - npx @capacitor/cli plugin:generate should be npx cap plugin:generate
Not a typo, when you are in a project folder where you installed @capacitor/cli you can use `npx cap plugin:generate`, but if you are in a regular folder with no package.json and no @capacitor/cli installed, you have to use `npx @capacitor/cli plugin:generate`, that will work on any folder without installing @capacitor/cli. You usually generate the plugins from outside the app folder where you don't have node packages installed.

**Comment by raxim1** [comment]
The 4. section was not really working for me. (folder not found or something like that happened, but does not matter) Thank's for your valuable response. To be honest i have created a bug, and after that figured out many things. Sadly at the moment i'm notable to build android based capacitor plugin. (it needs some further development), but at least i can include it to the main stuff for a while. I hope the capacitor will be stable, as i would like to shy away from the cordova completely. (no cordova plugin will be used, as they are very unstable, buggy etc)

**Comment by raxim1** [comment]
There is only one major bug, and it's describing a process, how i have analyzed the log. The real issue i think which can be resolved by the team is the first dex related issue. Other ones are not really issues or cannot be solved by your team.

**Comment by 1BJK903** [comment]
Is this still the case? I mean, the performance between Capacitor vs. Cordova... still in favour of Cordova?
