### ISSUE TITLE
bug:  Cannot resolve symbol 'S' in BridgeWebChromeClient.java

### ISSUE THREAD

**Issue by Samsonroyal** [ionic-team/capacitor#5870]
### Capacitor Version

```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.6.0
  @capacitor/android: 4.0.1
  @capacitor/core: 3.6.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

In Android studio when I click run app[Ctrl+F5], the build fails and displays this error `Cannot resolve symbol 'S':288`
### An illustration of the error
![error](https://user-images.githubusercontent.com/26835888/185118059-11ad1801-d456-48f0-b8d6-dd7d13be0760.png)

### Expected Behavior

The app is expected to run smoothly and open in the AVD emulator attached to android studio

### Code Reproduction

https://github.com/Samsonroyal/clone-app
#### Steps to reproduce error
1. Git Bash into project folder
2. Run `ionic cap open android`
3. Wait for android studio to open and load/sync gradle
4. Run app(Ctrl+F5 on windows) or press the green run app button
5. Read error in terminal

### Other Technical Details

```
Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.github.masahirosuzuka.PhoneGapIntelliJPlugin (212.5712.51), com.herbert.george.flutter-snippets (2.1.1-stable-1), com.abeade.plugin.figma.import (1.2.0), Dart (212.5744), org.jetbrains.kotlin (212-1.7.10-release-333-AS5457.46), io.flutter (69.0.2), com.crzsc.FlutterAssetsGenerator (2.0.0)
```

`npm --version` output: 6.14.11

`node --version` output: v14.15.5

### Additional Context

https://stackoverflow.com/questions/31140521/cannot-resolve-symbol-in-intellij-idea

https://stackoverflow.com/questions/24970646/how-to-overcome-android-studio-cannot-resolve-symbol-for-android-classes

**Comment by jcesarmobile** [comment]
I can't reproduce on the provided sample app, can you verify you can reproduce on the app?

This is most likely related to having `compileSdkVersion = 30` or a lower version in `android/variables.gradle` file (or setting compileSdkVersion to 30 somewhere else), but the provided app as `compileSdkVersion = 32`, so it's working fine for me.
If I change the value to 30 then I can reproduce, but that's expected, Capacitor 4 should be used with at least version 32.

**Comment by Samsonroyal** [comment]
Open terminal and cd into taasa-app folder and run the `ionic open android` command.
You'll reproduce the same exact environment I have over here.

**Comment by Samsonroyal** [comment]
> Open terminal and cd into taasa-app folder and run the `ionic open android` command. You'll reproduce the same exact environment I have over here.



> I can't reproduce on the provided sample app, can you verify you can reproduce on the app?
> 
> This is most likely related to having `compileSdkVersion = 30` or a lower version in `android/variables.gradle` file (or setting compileSdkVersion to 30 somewhere else), but the provided app as `compileSdkVersion = 32`, so it's working fine for me. If I change the value to 30 then I can reproduce, but that's expected, Capacitor 4 should be used with at least version 32.

https://github.com/ionic-team/capacitor/issues/5870#issuecomment-1218109322

**Comment by jcesarmobile** [comment]
there is no taasa-app folder in the sample project you provided

**Comment by Samsonroyal** [comment]
The taasa-app folder/directory is unfortunately another repo within the repo "Clone-app" therefore I am having issues pushing it.
I tried using git add submodules but it only works for files and not directories(repos)

 I have invited you as a collaborator on the original repo; it should be easy to clone the code from there and replicate the environment settings. Kindly accept it.

**Comment by jcesarmobile** [comment]
I got access to taasa-app and as I suspected you have `compileSdkVersion = 30` in `android/variables.gradle`.
Also noticed that you have only updated @capacitor/android package to 4.0.1 but not `@capacitor/core` nor `@capacitor/cli`.

You should update everything to Capacitor 4 following this guide https://capacitorjs.com/docs/updating/4-0

Or if you are not ready for updating to Capacitor 4 yet, you should install @capacitor/android 3.6.0 to match your core and cli versions.

**Comment by Samsonroyal** [comment]
Is it okay and possible to downgrade `compileSdkVersion = 30` to 20? 

 I have no qualms about updating; I am only worried the versions might not be stable and thus throw up more errors.

**Comment by jcesarmobile** [comment]
You don't have to downgrade to 20, you have to upgrade to 32 if you want to use Capacitor 4, but you should update more things if you want to use Capacitor 4, see the guide linked in my previous comment.

Or if you want to keep using 30 you have to use Capacitor 3 on all packages, you have update @capacitor/android to 4.0.1.

Using 32 will be mandatory for existing apps submissions to Google Play staring in November.

**Comment by Samsonroyal** [comment]
Then it's best I upgrade everything; the `compileSdkVersion = 32` and capacitor to 4; let me follow the guide on the link you provided; I'll be back if there are any mishaps.😊 thanks a bunch @jcesarmobile

**Comment by Samsonroyal** [comment]
> You don't have to downgrade to 20, you have to upgrade to 32 if you want to use Capacitor 4, but you should update more things if you want to use Capacitor 4, see the guide linked in my previous comment.
> 
> Or if you want to keep using 30 you have to use Capacitor 3 on all packages, you have update @capacitor/android to 4.0.1.
> 
> Using 32 will be mandatory for existing apps submissions to Google Play staring in November.

### error message when I run `npx cap migrate `
Should I remove the node modules and start the process anew?
```
× Installing Latest NPM Modules. - failed!
[error] Failed to migrate: Error: ENOTEMPTY: directory not empty, rmdir 'D:/Github
        Repos/taasa-app/node_modules/@capacitor/haptics'
```

**Comment by jcesarmobile** [comment]
yeah, try that, but you'll have to run `npm install @capacitor/cli@latest` again before running migrate or it won't run

**Comment by Samsonroyal** [comment]
I successfully migrated to capacitor 4, and it works fine; I exported the project to android studio.
