### ISSUE TITLE
Invalid Podfile file: cannot load such file -- /Users/username/Project/node_modules/@capacitor/ios/scripts/pods_helpersbug: 

### ISSUE THREAD

**Issue by nnve** [ionic-team/capacitor#5874]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/core: 3.7.0
  @capacitor/android: 3.7.0
  @capacitor/cli: 4.0.1
  @capacitor/ios: 3.7.0

[success] iOS looking great! 
```

### Platform(s)

IOS

### Current Behavior

I successfully upgraded from Capacitor v2 to v3 following the step-by-step Upgrade Guides on the Capacitor Documentation. 
But when I run npx cap sync ios or ionic cap sync ios, it run into the following error

✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] 
        [!] Invalid `Podfile` file: cannot load such file --
        /Users/username/Project/node_modules/@capacitor/ios/scripts/pods_helpers.
        
        #  from
        /Users/username/Project/ios/App/Podfile:1
        #  -------------------------------------------
        >  require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
        #
        #  -------------------------------------------
it seems the node_modules/@capacitor/ios/scripts/pods_helpers file is missing in the current release.

It works If i remove the require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers' line and this block
post_install do |installer| ...

OR

If i downgrade @capacitor/cli to 3.7.0, it works also too (without modify Podfile).

### Expected Behavior

Should install, copy and sync dependencies for ios.

### Other Technical Details

`npm --version` output: 8.16.0

`node --version` output: 16.16.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment]
Are you updating from Capacitor 2 to Capacitor 3 or from Capacitor 3 to Capacitor 4?

You have @capacitor/cli: 4.0.1 but @capacitor/ios: 3.7.0

**Comment by nnve** [comment]
I have updated  from Capacitor 2 to Capacitor 3.
Yes my @capacitor/cli is in 4, but it seemed to me that this library is supposed to be backwards compatible. In the migration, it always says to take the latest.
As I report, @capacitor/cli 3.7 works.

**Comment by jcesarmobile** [comment]
Capacitor is not backwards compatible, all capacitor CLI, core, android and iOS versions must match.
The guides always refer to “latest” because they were latest at the time they were written and we don’t revisit once we launch a new major version.

If you use CLI 4.x and run npx cap add ios it will create an app that is not compatible with @capacitor/ios 3.x
