### ISSUE TITLE
debug one app built by Capacitor 3 in one Android device then throw error each 1 sec in chrome inspect console

### ISSUE THREAD

**Issue by CyrusNG** [ionic-team/capacitor#5882]
**Issue**
When I debug one app built by Capacitor 3 in one Android device, the following error will throw out per 1 sec in chrome inspect console. And I globally search web & android folders' no any related "collections" properties. So I have no idea why the error thrown. 
May I know anyone met my case and how to solve this issue? Thanks!

**Error Like this:**
```
TypeError: Cannot read properties of undefined (reading 'collections')
   at <anonymous>:1:53
   c.handleError  @  vendors~253ae210.092…040b088f3098b3.js:3
   cap.handleWindowError  @  (index):360
   error (async)  
   initNativeBridge  @  (index):367
   initBridge  @  (index):488
   (anonymous)  @  (index):490
   (anonymous)  @  (index):506
```

**package.json**
...
   "@capacitor/android": "^3.7.0",
    "@capacitor/core": "^3.7.0",
    "@capacitor/ios": "^3.7.0",
    "@capacitor/storage": "1.2.5",
...

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by CyrusNG** [comment]
**Reproduce Steps:**
**Step1:** create one simple node project include index.html only:
`<!doctype html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="viewport-fit=cover,width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
      <meta name="format-detection" content="telephone=no">
      <meta name="msapplication-tap-highlight" content="no">
   </head>
   <body>
      <div id="app">Hello</div>
   </body>
</html>`

**Step2:** run capacitor command:
`npx cap add android`
**Step3:** click "run" in Android

Then try to debug then issue happen in chrome inspect.

**Comment by jcesarmobile** [comment]
sorry, I can't reproduce with that, can you provide a full sample app we can clone?

**Comment by CyrusNG** [comment]
> sorry, I can't reproduce with that, can you provide a full sample app we can clone?

Let me try to compare other capacitor versions and other devices, and get more info for this issue, then make a sample app for this issue. ^_^

**Comment by CyrusNG** [comment]
@jcesarmobile I have found why the issue happen. It is just a Chrome plugin called 'MobX Developer Tools' to make this issue happen. This plugin is for debugging my project's data processing solution.

**just CLOSE it in Chrome extensions page**, then work well.
