### ISSUE TITLE
feat: Content provider in file/folder selector on Android

### ISSUE THREAD

**Issue by shirok1** [ionic-team/capacitor#5883]
### Description

I would like to select some file in, for example, OneDrive app on my phone, so that the content of the file will be synced automatically outside my app.

### Platform(s)

Android.

### Preferred Solution

Special Capacitor API for specifying content type to storage access framework.

**Comment by jcesarmobile** [comment]
That looks like a good candidate for capacitor-community plugin
https://github.com/capacitor-community/proposals
