### ISSUE TITLE
bug: Sidebar menu with ion-refresher

### ISSUE THREAD

**Issue by connectMyClub** [ionic-team/capacitor#5886]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1
```

### Platform(s)

iOS, Android, Web

### Current Behavior

When I go to a route where the page has a ion-refresher the sidebar menu will not open on drag unless you move the page up slightly. Pages without an ion-refresher work as expected. The sidebar menu opens on drag. All pages the sidebar menu opens using the hamburger button.

The menu can be dragged open if the drag is over the header or footer but not ion-content with ion-refresher

### Expected Behavior

The sidebar menu should open on drag with all pages

### Code Reproduction

https://github.com/connectMyClub/ion-refresher

### Other Technical Details

`npm --version` output: 8.5.2

`node --version` output: v14.15.4

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by connectMyClub** [comment]
I've reduced ion-content on ion-page to width:90% and given left:5% seems to help.

**Comment by connectMyClub** [comment]
That ended up not working. At the moment I'm working with 

```this.content.scrollToPoint(0, 1, 1000)```

**Comment by connectMyClub** [comment]
@Ionitron Here's the repro on github which demonstrates the issue of intermittent side menu drag opening with / without an ion-refresher 

[https://github.com/connectMyClub/ion-refresher](url)

**Comment by connectMyClub** [comment]
A little more from trying to work around the issue. 

If the page has a long list and the page is moved up by just one pixel the sidebar menu will open all of the time. If the page is then moved back down the one pixel, so the page sits right at the top, the sidebar menu will not then always open.

If the page content is less than the full screen height, so the page cannot be dragged up and down, then the sidebar menu doesn't always open.

I hope this goes some way to finding and resolving the issue.

**Comment by jcesarmobile** [comment]
This seems to be a bug on ionic framework since there is no Capacitor code related and the problem is reproducible on web platform.
You should report it on the [ionic framework repository ](https://github.com/ionic-team/ionic-framework/issues)
