### ISSUE TITLE
FR: Unable to monitor Angular HTTP requests

### ISSUE THREAD

**Issue by mburger81** [ionic-team/capacitor#589]
We are not able to monitor **Ionic4** + **Angular6** **HTTP** requests running test app on real android device using android studio.

If we use Chrome  DevTools -> Remote Device monitoring we don't see any traffic in NETWORK also we don't see traffic using Android Studio Profiler

https://developer.android.com/studio/profile/network-profiler?utm_source=android-studio#network_connection_troubleshooting
Profiler does only work with HttpURLConnection and OkHttp, so probably not with XMLHttpRequest which HttpClient is on top.

So it would be very difficult to debug traffic on android devices. Right?

**Comment by jcesarmobile** [comment]
From chrome://inspect/#devices I can see xhx and fetch calls made to mapbox API

<img width="744" alt="captura de pantalla 2018-06-19 a las 12 30 10" src="https://user-images.githubusercontent.com/1637892/41592339-9085a02a-73bc-11e8-89f9-c0fc5e20b652.png">

**Comment by mburger81** [comment]
Sorry man, this was my mistake! 
On first opening the INSPECTOR from DEV TOOLS there is no NETWORK log. We have to reload the page or do something other to see network log.
My mistake. Sorry!
