### ISSUE TITLE
bug: camera always show a prompt

### ISSUE THREAD

**Issue by aktivdigital-frontend** [ionic-team/capacitor#5890]
### Capacitor Version
```
4.0.1
```

### Platform(s)
Android

### Current Behavior
I set source to CameraSource.Camera, but prompt is always show. (F"rom photos" and "Take pucture" options)

### Expected Behavior
I want to start camera immediately

### Code Reproduction
```
import { Camera, CameraDirection, CameraResultType, CameraSource } from "@capacitor/camera";

startCamera() {
  let options: {
	  direction: CameraDirection.Front, 
	  resultType: CameraResultType.Uri
	  source: CameraSource.Camera
  };
  
  Camera.getPhoto(options).then((file: any) => {
	  console.log(file);
  }, (err) => {
	  console.log(err);
  });
}
```

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v14.15.0

`pod --version` output (iOS issues only): -

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
