### ISSUE TITLE
bug: @capacitor/push-notifications Value of type 'CAPPlugin' has no member 'getConfig'

### ISSUE THREAD

**Issue by yannickcare** [ionic-team/capacitor#5894]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/ios: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/core: 3.6.0

```

### Platform(s)

IOS

### Current Behavior

When compiling, receiving an error : Value of type 'CAPPlugin' has no member 'getConfig'
in file ios/Plugin/PushNotificationsHandler.swift

### Expected Behavior

No compile error

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Version 4 of the plugins are meant to be used with capacitor 4, you are still in capacitor 3.
Please, upgrade to capacitor 4 https://capacitorjs.com/docs/updating/4-0
