### ISSUE TITLE
bug: Xcode 16 Pods Signing Error

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/capacitor#5912]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

Installed Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- iOS

### Current Behavior

I am using the [CleverPush](https://github.com/cleverpush/cleverpush-cordova-sdk) plugin in my app. It seems like the Capacitor CLI creates a file called `CleverPush-CleverPushResources`. Please see the screenshot.  **Every time I run "npx cap build" the File and its signing settings gets overwritten.** I can't deploy the app to my device.
<img width="1611" alt="Bildschirmfoto 2022-09-14 um 11 23 56" src="https://user-images.githubusercontent.com/39862171/190117655-58e7625a-b8ba-4cb1-962f-6a69173a606e.png">
```
/ios/App/Pods/Pods.xcodeproj: error: Signing for "CleverPush-CleverPushResources" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'CleverPush-CleverPushResources' from project 'Pods')
 ** BUILD FAILED **
```
I am also receiving a lot of these warnings: 
```
warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
         warning: Run script build phase '[CP] Copy Pods Resources' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
         warning: Run script build phase '[CP] Copy XCFrameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'GoogleAppMeasurement' from project 'Pods')
         warning: Run script build phase '[CP] Copy Pods Resources' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'CleverPushNotificationServiceExtension' from project 'App')
```
### Expected Behavior

My signing settings shouldn't be overwritten.

### Other Technical Details

`yarn --version` output: 1.22.19

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment]
There is no `npx cap build` command (yet). I guess you mean `npx cap update`, or `npx cap sync`.

Both of them run `pod install` under the hood, and that's what is resetting the signing changes you made.
You should never make changes on the Pods projects, those are handled by CocoaPods.

But looks like there is a bug with CocoaPods not working correctly with Xcode 14, check https://github.com/CocoaPods/CocoaPods/issues/11402 (includes workaround)
