### ISSUE TITLE
bug: Kotlin class cannot be registered as Plugin

### ISSUE THREAD

**Issue by hoi4** [ionic-team/capacitor#5926]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/core: 4.2.0

[success] Android looking great! 👌
```

### Platform(s)
android

### Current Behavior
I am trying to create a native plugin for Android using Kotlin. When running the app, an error is thrown in `MainActivity.java` --> `cannot find symbol class TestPlugin`

```java
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    registerPlugin(TestPlugin.class); // This fails with "cannot find symbol class TestPlugin"
    registerPlugin(TestPluginJava.class);
    super.onCreate(savedInstanceState);
  }
}
```

The respective kotlin class only contains a `load` function:
```kotlin
@CapacitorPlugin
class TestPlugin : Plugin() {

  override fun load() {
    super.load()

    println("TEST PLUGIN INIT")
  }
}
```

### Expected Behavior
According to the [docs](https://capacitorjs.com/docs/android/custom-code) I assume it should be possible to run native kotlin code out of the box. 

Note: I did not get any prompt when creating the kotlin class in Android Studio and the Android Studio option `Tools` -> `Kotlin` -> `Configure Kotlin in Project` yields "All modules with Kotlin files are configured"

If it takes more configuration to get Kotlin code working, some guidance would be much appreciated!

### Code Reproduction
You can also find the simple setup from above in [this sample repo](https://github.com/hoi4/cap-kotlin).

### Other Technical Details

`npm --version` output: `8.15.0`

`node --version` output: `16.17.0`

**Comment by jcesarmobile** [comment]
You need to enable kotlin for your project for being able to use the kotlin plugin, not sure why it didn't prompt to you when you added the kotlin file or why 
> Tools -> Kotlin -> Configure Kotlin in Project yields "All modules with Kotlin files are configured"

I've added a kotlin fragment to your project and then removed it and this is the other changes Android Studio made in gradle to enable kotlin

https://github.com/hoi4/cap-kotlin/pull/1

**Comment by hoi4** [comment]
Thank you @jcesarmobile 
It would be great to have the necessary changes also in the docs 👍🏻
