### ISSUE TITLE
bug: Capacitor Browser not working in Android - build error

### ISSUE THREAD

**Issue by Dhanesha-Dishit** [ionic-team/capacitor#5932]
### Capacitor Version
  @capacitor/cli: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/ios: 3.6.0
  @capacitor/browser 4.01

###Output
![Screenshot 2022-09-05 113258](https://user-images.githubusercontent.com/79834415/191023561-ba91a1cc-ab63-4219-bbd6-6c7a5c22d47a.png)

### Platform(s)
Android

### Current Behavior

Am using capacitor with Nuxt frontend. My motive is to use an in-app browser in Android, I am using the capacitor browser to achieve that but the build is failing in Android. Throwing error as shown in the output.

### Expected Behavior

Android build should go through and the in-app browser should work.

### Code Reproduction
```
<template>
  <div>
    <button @click="openBrowser">Hello</button>
  </div>
</template>
<script>
import { Browser } from '@capacitor/browser'
export default {
  methods: {
    async openBrowser() {
      await Browser.open({ url: 'http://capacitorjs.com/' })
    }
  }
}
</script>
<style scoped>
</style>
```

### Other Technical Details
```
Using Capacitor with Nuxt.js Framework
```

**Comment by jcesarmobile** [comment]
Version 4.x of plugins are meant to be used with version 4.x of Capacitor (core, cli, ios and android packages), you are using version 4.x of the plugin but still in Capacitor 3.

Migrate to Capacitor 4 using [this guide ](https://capacitorjs.com/docs/updating/4-0)or downgrade the plugin to latest 1.x.
