### ISSUE TITLE
feat: Provide support for SolidJS

### ISSUE THREAD

**Issue by pashvin** [ionic-team/capacitor#5934]
### Description

SolidJS (https://www.solidjs.com/) is like ReactJs but has better performance. In terms of code syntax, it is much easy to use.
Providing support of ionic for SolidJS will help improve the popularity of the SolidJS framework. Also SolidJS port from ReactJs should be not that hard as syntax of SolidJS and ReactJS is very simillar.

### Platform(s)

Request for New web framework - SolidJS along with React, Angular & Vuejs.

**Comment by jcesarmobile** [comment]
You have reported the issue on capacitor repository.
Capacitor is framework agnostic, you can use whatever framework you want.
