### ISSUE TITLE
feat: allow params types other than strings in CapacitorHttp

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/capacitor#5942]
### Description

I need to send the coordinates { lat:1234, lng:5678 } (extracted from the Geolocation plugin) to the server. it works fine on the web, but on iOS I'm getting the error Could not cast value of type '__NSCFNumber' to 'NSString' when passing the coordinates to the params like

```
  const options = {
    url: 'https://example.com/my/api',
    params: { lat:1234, lng:5678 },
  }
```

### Platform(s)
iOS

### Preferred Solution

Allow HttpParams to accept string | string[] | Boolean | Number, etc

**Comment by ItsChaceD** [comment]
Are you confusing `params` with `data`? As far as I know, query parameters are strings by nature. If you need to pass numbers as a query parameter, then try:

```
const options = {
    url: 'https://example.com/my/api',
    params: { lat:'1234', lng:'5678' },
  }
```

If this still needs attention, then please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction) and I would be glad to help.

Thanks!

**Comment by jongbonga** [comment]
I get that, the casting to string is tedious. 

I was previously using angular `new HttpParams({fromObject:params}).toString()` and appending it to the url. 

So I want a cleaner way and just pass the params directly without having to worry about the types
