### ISSUE TITLE
bug: Capacitor 4.3 Http/Cookies: document.cookie is not accessible (deletion)

### ISSUE THREAD

**Issue by malte94** [ionic-team/capacitor#5946]
First of all, thank you for putting so much effort into Capacitor. With CapacitorCookies and CapacitorHttp it is now easily possible to run an app connected to an API locally.

```
Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0
  @capacitor/android: 4.3.0
```

### Platform(s)

iOS, Android

### Description

Capacitor Http/Cookies should provide the possibilty to handle `document.cookie`. This is necessary for many libraries, for example to delete cookies. A logout is also not possible from the app, when using cookies for authentication.

`document.cookie = "auth=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";`

**Comment by ItsChaceD** [comment]
Hello, Capacitor 4.3 should handle `document.cookie` for you, as long as you enable it in the configuration.
See: https://capacitorjs.com/docs/apis/cookies#example-configuration

**Comment by malte94** [comment]
Hey @ItsChaceD, Thank you for your reply!

As far as I understand the documentation, setting and getting cookies works fine with `document.cookie`.

However, what if a third-party library wants to remove a cookie? This wouldn't work because it certainly wouldn't use the CapacitorCookies.deleteCookie method, right?

**Comment by ItsChaceD** [comment]
@malte94 Yes, this should handle 3rd party libraries modifying cookies since every `document.cookie` call will get proxied through the native layer if it is enabled in the config. As far as Cookie based authentication (3rd Party Cookies), Capacitor should also intercept any `Set-Cookie` response headers and handle them accordingly on the native platforms 😄 If you encounter an issue though, please create a reproduction and I can investigate it.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by WillooWisp** [comment]
> Hello, Capacitor 4.3 should handle `document.cookie` for you, as long as you enable it in the configuration. See: https://capacitorjs.com/docs/apis/cookies#example-configuration

I can only see the XSRF-TOKEN in document.cookie, but it does not have the same value as when looking in developer tools in the browser. 
The Http only cookies for identity are not there, but I see them in dev tools.
`
"XSRF-TOKEN=CfDJ8H5oRNAoR9FCmxVX2bMP46S1ETbhNHgL6rwINkjyHRd9MC07r8hI-Y7A76hmlbn_xUkUz6fnUiknogFMyEOXHbhZ0gW2KZVY3uJXpDI4S4jzMa2xxa8AH6mV6lkNXrkA3p0MM0827nwUmcWJbiwvrt5_8SWdbvx-gzOiHbnawis9b-m-iTjQwY8LtMuFNbXmEQ"
`

**Comment by Z2Y** [comment]
In ios when response has multiple set-cookie header only the last value was applied.
