### ISSUE TITLE
bug: ion icons disappear when Http enabled

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/capacitor#5947]
## Bug Report

Ionic icons not showing when `CapacitorHttp: {  enabled: true }` in `capacitor.config.ts` on native 

### Capacitor Version
```

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS

### Code Reproduction

```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  ...
  plugins: {
    CapacitorHttp: {
      enabled: true
    }
  }
};

export default config;
```

**Comment by nicklasuhde** [comment]
I have the same issue!

**Comment by rensjaspers** [comment]
Here's a minimal sample application that demonstrates the issue:
https://github.com/rensjaspers/capacitor-http-missing-ion-icons-sample

I get "unsupported URL" errors like this one: 
```
⚡️  To Native ->  App addListener 124667420
2022-09-23 11:31:22.573110+0200 App[22553:2273293] Task <14803BC4-3F93-4D63-9370-506DC2DA7DAD>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=/svg/accessibility.svg, NSErrorFailingURLKey=/svg/accessibility.svg, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <14803BC4-3F93-4D63-9370-506DC2DA7DAD>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <14803BC4-3F93-4D63-9370-506DC2DA7DAD>.<1>, NSUnderlyingError=0x600000341fe0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}
```

**Comment by isabo** [comment]
FWIW the Chrome remote debugging console shows a `MalformedURLException`:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/70673/191941147-903f746a-3a49-47fd-a56a-db76ff1e0f82.png">

**Comment by henrikstromberg** [comment]
I have the same issue!

**Comment by WillooWisp** [comment]
I also get the MalformedURLException as soon as it tries to load a remote SVG as source into an img element now, this used to work before.

**Comment by anttironty** [comment]
I had the same problem, solution was to add `!resource.toString().startsWith('http')` to the if statement on `native-bridge.js` row 364, so capacitor uses regular `window.fetch` if the resource url doesn't start with http (http/https).

```
window.fetch = async (resource, options) => {
                        if (resource.toString().startsWith('data:') ||
                            resource.toString().startsWith('blob:') ||
                            !resource.toString().startsWith('http') ) {
                            return win.CapacitorWebFetch(resource, options);
                        }
                        //continue
```

**Comment by jongbonga** [comment]
> I had the same problem, solution was to add `!resource.toString().startsWith('http')` to the if statement on `native-bridge.js` row 364, so capacitor uses regular `window.fetch` if the resource url doesn't start with http (http/https).
> 
> ```
> window.fetch = async (resource, options) => {
>                         if (resource.toString().startsWith('data:') ||
>                             resource.toString().startsWith('blob:') ||
>                             !resource.toString().startsWith('http') ) {
>                             return win.CapacitorWebFetch(resource, options);
>                         }
>                         //continue
> ```

@anttironty Maybe make a PR request for the above?

**Comment by ItsChaceD** [comment]
This issues affects Angular apps or any apps fetching local resources, however there should be a fix coming for this very soon. It also affects XHR requests, so the above fix will only cover 1 use case
