### ISSUE TITLE
bug: Capacitor 4.3 Cookies: Setting cookies is asynchronous when it should be synchronous

### ISSUE THREAD

**Issue by epeach1** [ionic-team/capacitor#5950]
## Bug Report
Setting and getting cookies should both be synchronous but only getting cookies is currently. No change is returned when getting cookies immediately after setting them. This synchronous behavior for setting cookies is required by a third party library and breaks existing behavior of document.cookie.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS
Android

### Current Behavior

Setting cookies and immediately reading cookies results in old data being returned.

### Expected Behavior

When reading from document.cookie immediately after setting a cookie, the new values should be returned.

### Code Reproduction

Clicking each button should set the cookie to that value and display it immediately, instead you have to click it twice to see the correct value. 

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <script>      
      function setCookie(value) {
        const output = document.getElementById('cookies')
        document.cookie = `name=${value};`;
        output.textContent = `> ${document.cookie}`
      }
  </script>
  </head>
  
  <body>
    <button onclick="setCookie('foo')">Set cookie foo</button>
    <button onclick="setCookie('bar')">Set cookie bar</button>

    <div>
      <code id="cookies"></code>
    </div>
  </body>
</html>

```

```
{
  "appId": "com.example.app",
  "appName": "cookie",
  "bundledWebRuntime": false,
  "webDir": "dist",
  "ios": {
	"contentInset": "always"
   },
  "plugins": {
    "CapacitorCookies": {
	"enabled": true;
    }
  }
}
```

### Other Technical Details

`npm --version` output: 7.6.0

`node --version` output: v15.11.0

**Comment by ItsChaceD** [comment]
A fix should be coming for this soon 👍 It was initially made asynchronous to align with and utilize `CapacitorCookies.setCookie(...)` under the hood.
