### ISSUE TITLE
bug: can not use two plugins with the same name

### ISSUE THREAD

**Issue by robingenz** [ionic-team/capacitor#5957]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior

I use two Capacitor plugins with the same name:
1. The official `@capacitor/device` plugin
2. A custom `@custom/capacitor-device` plugin which exposes just more internal information about the device.

I use the plugins as follows:

```ts
import { Device } from '@capacitor/device';
import { Device as ExtendedDevice } from '@custom/capacitor-device';

const getBatteryInfo = async () => {
  return Device.getBatteryInfo();
};

const getMemoryInfo = async () => {
  return ExtendedDevice.getMemoryInfo();
};
```

I now get the following message at runtime:
```
"Device.getBatteryInfo()" is not implemented on android 
```

### Expected Behavior

I would like to be able to use two plugins with the same name. After all, you don't always have an impact on the names and that shouldn't be limiting.

### Code Reproduction

The custom plugin is unfortunately private. If you still need an example app, I will of course create one.

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment]
Capacitor uses reflection for calling the plugin methods, and the name is used as the plugin id for getting the actual plugin, so there can only be one plugin for each name. 
Note that the name is the specified in the `CapacitorPlugin` annotation (i.e `@CapacitorPlugin(name = "Device")`), not the java class name.
