### ISSUE TITLE
bug: removeAllListeners call from JS to Native iOS fails

### ISSUE THREAD

**Issue by karlvr** [ionic-team/capacitor#5959]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

When calling the `removeAllListeners` function on my plugin, I receive an error that the method is not found.

```javascript
await MyPlugin.removeAllListeners()
```

Results in the following output from the iOS Simulator:

```
⚡️  Error calling method removeAllListeners on plugin MyPlugin: No method found.
⚡️  Ensure plugin method exists and uses @objc in its declaration, and has been defined
```

The method `removeAllListeners` is defined for `Plugin` in `capacitor/core/src/definitions.ts`:

```typescript
export interface Plugin {
  addListener(
    eventName: string,
    listenerFunc: (...args: any[]) => any,
  ): Promise<PluginListenerHandle>;
  removeAllListeners(): Promise<void>;
}
```

Other methods I expected (like `removeListener`) are not included in the definitions (see below).

### Expected Behavior

I expect the JS call to trigger the native `removeAllListeners` method. It's really handy for handling full page reloads.

### Code Reproduction

Can I get away with saying that adding the following in my `.m` fixes it:

```c
CAP_PLUGIN_METHOD(removeAllListeners, CAPPluginReturnPromise);
```

And if I've understood correctly, the problem is in `CapacitorBridge.swift`:

```swift
        let selector: Selector
        if call.method == "addListener" || call.method == "removeListener" {
            selector = NSSelectorFromString(call.method + ":")
        } else {
```

We check for "addListener" and "removeListener" but not "removeAllListeners" (and not "checkPermissions" and "requestPermissions", which are listed in `JSExport.swift`).

I don't think the same problem exists on Android (based on an inspection of the code; but I apologise, I have not tested that yet)

**Comment by jcesarmobile** [comment]
yeah, at the moment you'll have to add those methods to the .m file, for us to make the methods available for all plugins would require breaking changes, so won't be doing it until next major release.

**Comment by karlvr** [comment]
@jcesarmobile OK, thank you. Easy to add.
