### ISSUE TITLE
feat: Download Files with CapacitorHttp

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/capacitor#5964]
### Description

I used `@capacitor-community/http` to upload and download files **and** report the progress, but in the newly released `CapacitorHttp` this feature is gone!

### Platform(s)

- iOS
- Android

### Preferred Solution

```ts
const result = await CapacitorHttp.downloadFile({
    url: options.url,
    responseType: 'blob',
    fileDirectory: Directory.Data,
    filePath: `${options.directory}/${filename}`,
    progress: true
});

Http.addListener('progress', progress => {
    console.log(`Progress: ${((progress.bytes / progress.contentLength) * 100).toFixed(0)}%`);
});
```
### Alternatives

Alternatively, it possible to use the Angular HttpClient to download files **and** report the progress, but this often results in CORS errors.

**Comment by ItsChaceD** [comment]
This feature is in the works, but will most likely be included in the `@capacitor/filesystem` plugin

**Comment by oke007** [comment]
Any ETA for this download and upload features with progress listener?

**Comment by AshleyMedway** [comment]
2023 the year of `downloadFile`? :)

**Comment by kristojorg** [comment]
Is there anywhere we can track progress on this issue?

**Comment by acosme** [comment]
update:

https://github.com/ionic-team/capacitor-plugins/releases/tag/%40capacitor%2Ffilesystem%405.1.0
