### ISSUE TITLE
feat: retain multiple calls per event until consumed

### ISSUE THREAD

**Issue by robingenz** [ionic-team/capacitor#5967]
### Description

Currently `retainUntilConsumed` supports only one call per event. This leads to older calls being dropped when a new call is received, even though both calls may still be relevant.

**Example**: My [Capacitor Firebase Cloud Messaging plugin](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/messaging) has a [`notificationReceived` listener](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/messaging#addlistenernotificationreceived-), which should return all notifications received while the app was not active and not only the last notification.

### Platform(s)

- Android
- iOS

### Preferred Solution

The `retainUntilConsumed` option should save all calls.

**Comment by riderx** [comment]
@robingenz maybe return array instead of one event could fix your issue no ?

**Comment by robingenz** [comment]
No, unfortunately not. Since I don't know when the event will be consumed, I also don't know when I have to clear the array again. 
Besides, this would only be a workaround with a bad developer experience.
