### ISSUE TITLE
bug: Android 10 API 29 App launches with white screen

### ISSUE THREAD

**Issue by ashokwagh** [ionic-team/capacitor#5972]
### **Bug Report**

E/Capacitor/Console: File: http://localhost/ - Line 286 - Msg: SyntaxError: Unexpected token ?
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught SyntaxError: Unexpected token ?","url":"http://localhost/vendor.js","line":48478,"col":28,"errorObject":"{}"}}
E/Capacitor/Console: File: http://localhost/vendor.js - Line 48478 - Msg: Uncaught SyntaxError: Unexpected token ?
E/Capacitor/Console: File: http://localhost/ - Line 286 - Msg: SyntaxError: Unexpected token .
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught SyntaxError: Unexpected token .","url":"http://localhost/main.js","line":1798,"col":26,"errorObject":"{}"}}
E/Capacitor/Console: File: http://localhost/main.js - Line 1798 - Msg: Uncaught SyntaxError: Unexpected token .

### **Capacitor Version**
```
Installed Dependencies:

  @capacitor/core: 4.2.0
  @capacitor/cli: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: Not installed
```
**### Platform(s)**
Android

**### Current Behavior**
App launches with white screen

Expected Behavior
Code Reproduction
ionic start
Angular
Tabs

### **Other Technical Details**

npm --version output: 7.24.0

node --version output: v16.10.0

pod --version output : 1.11.3

### **Additional Context**
[Similar issue](https://github.com/ionic-team/capacitor/issues/5765)

**Comment by jcesarmobile** [comment]
Have you tried what I said on my comment? 
I guess it didn't work since you added a 👎 reaction to it
Can you provide a sample app where you have done what I mentioned on that comment and still doesn't work?

**Comment by ashokwagh** [comment]
@jcesarmobile es5 is very old and deprecated now.
Can you suggest any recent version which can fix this error.

**Comment by jcesarmobile** [comment]
The lower you can use is es2015 if you want to support iOS 13 and chrome 60 (which is the minimum capacitor supports).
We have updated the ionic angular templates to target es2015 instead of es2020 so users don’t have to.
