### ISSUE TITLE
bug: Capacitor camera plugin requestPermission method does not trigger native request dialogd

### ISSUE THREAD

**Issue by yksolanki9** [ionic-team/capacitor#5977]
### Capacitor Version

```
  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0
```

### Platform(s)
Android (Havent tested on IOS yet)

### Current Behavior
If the user denies the camera permission, I show a popover asking them to provide camera permissions. When they click on proceed, I call `Camera.requestPermissions()` and I expect to see the native permission dialog, but instead the method directly returns `denied`, which was the last response of the user

### Expected Behavior
The native permission dialog should be shown to the user, else there's no difference between `checkPermission()` and `requestPermissions()`

### Code Reproduction
```
async startCamera() {
  const permissions = await Camera.requestPermissions();
  if(permissions.photos === 'denied' || permissions.camera === 'denied') {
    //Popover asking them to click `Allow` on the native permission dialog
    const data = showPopover();
    if(data === 'proceed') {
      return startCamera();
    }
    goBack();
  }

  //Capture logic once permission is given
}
```

### Other Technical Details
```
"@capacitor/camera": "^1.3.1",
```

**Comment by jcesarmobile** [comment]
denied on Android means they have checked the "never ask again" checkbox, otherwise the result is "prompt-with-rationale", so if you get a denied status you should ask users to go to the app settings and change the permission, prompting will have no effect.

https://capacitorjs.com/docs/plugins/web#aliases
