### ISSUE TITLE
bug: Throwing error after migrating to v4

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor#5983]
## Bug Report
Facing issue after Migrating to capacitor `v4.3.0` from `v3.6.0`

I have custom Plugin in my application made for some 3rd party Device using their SDK for both android and IOS. But after migrating to capacitor v4 using vscode extension. everything is working fine all other plugins but my custome plugin is showing error. 
`Error: "IonicNativePluginExample" plugin is not implemented on android`
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android
iOS

### Current Behavior
Custom Plugin not working.

### Expected Behavior
My custom plugin Should work as other plugins are working. 

### Code Reproduction
Can't share native custom code. 

### Other Technical Details

`npm --version` output: 8.1.2

`node --version` output: v16.13.1

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Saqib92** [comment]
I can't share Native plugin code as it is Under company's ownership. But my plugin Works in 3.6.0.

**Comment by jcesarmobile** [comment]
You can provide a sample app with another plugin that just does nothing, doesn't need to be a real app with a real plugin, that's why it's called sample app.

**Comment by Saqib92** [comment]
> You can provide a sample app with another plugin that just does nothing, doesn't need to be a real app with a real plugin, that's why it's called sample app.

Will create sample app with demo plugin.

**Comment by Saqib92** [comment]
This is demo Repo:

Having same issue on demo plugin also:

**Comment by Saqib92** [comment]
this is example repo with Demo plugin. facing same issue:
Before Migration to v4: https://github.com/Saqib92/capacitor-migration-issue

After Migration: 
https://github.com/Saqib92/capacitor-migration-issue/tree/v4

I have made branch named v4 after Migration.

**Comment by jcesarmobile** [comment]
In Capacitor 4 you have to call registerPlugin before super.onCreate
https://capacitorjs.com/docs/updating/4-0#change-registerplugin-order

**Comment by Saqib92** [comment]
is there any change like this for iOS? because i haven't tested it on iOS yet.

**Comment by Saqib92** [comment]
Thank for you help. Will migrate my app to v4.

**Comment by Saqib92** [comment]
Error while running : `npx cap migrate`

> [error] Unknown command: migrate
