### ISSUE TITLE
bug: cap.nativePromise is not defined

### ISSUE THREAD

**Issue by zakuru** [ionic-team/capacitor#5989]
## Bug Report
Hi,
I setup my configuration files to load CapacitorHttpPlugin but it still does not work as expected as the nativePromise is undefined on the cap object:

**capacitor.config.json**
`{
    "plugins": {
        "CapacitorCookies": {
            "enabled": true
        },
        "CapacitorHttp": {
            "enabled": true
        }
    }
}`

**capacitor.config.ts**
``` import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  plugins: {
    CapacitorCookies: {
      enabled: true,
    },
    CapacitorHttp: {
      enabled: true,
    },
  },
  appId: 'xxxxx',
  appName: 'xxxx',
  webDir: './dist/js/mspa',
  bundledWebRuntime: false
};

export default config; 
```

### Capacitor Version

```

Latest Dependencies:       

  @capacitor/cli: 4.3.0    
  @capacitor/core: 4.3.0   
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0    

Installed Dependencies:    

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0   
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0    

[success] Android looking great! 👌
```

### Platform(s)

Android Emulator and also real Android Device

### Current Behavior

cap.nativePromise is not defined
![image](https://user-images.githubusercontent.com/171174/195272094-76bed16a-8648-4565-95e0-4bca8a24cca3.png)

### Expected Behavior

cap.nativePromise to be defined so that I can use CapacitorHttp plugin 

### Other Technical Details

`npm --version` output: 6.14.17

`node --version` output: v14.20.0

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by zakuru** [comment]
Problem fixed.
Upgrade to latest NPM version and did full clean rebuild
Thanks all for the amazing job
