### ISSUE TITLE
bug: Firebase getIdToken(true) for refresh token - Refresh token for persistence of user on app is not returning token but error - jsonexception

### ISSUE THREAD

**Issue by shreyasPL** [ionic-team/capacitor#5996]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0
  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
Capacitor.config.js
```
{
  "appId": "our-app.com",
  "appName": "appname",
  "bundledWebRuntime": false,
  "npmClient": "yarn",
  "webDir": "build",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    },
    "FirebaseAuthentication": {
      "skipNativeAuth": false,
      "providers": [
        "google.com",
        "facebook.com",
        "apple.com"
      ]
    },
    "CapacitorHttp": {
      "enabled": true
    }
  },
  "server": {
    "androidScheme": "https",
    "iosScheme": "ionic", 
    "cleartext": true,
    "allowNavigation": [
      "*"
    ]
  }
}
```

### Platform(s)

1. capacitor android only - We are using capacitor.https -> enabled true flag as part of new release 4.3.0 of capcitor.

### Current Behavior

1. We know firebase access token expires after an hour.
2. We use getIdToken(true) - forcerefresh param to true, for forceful token with extended one hour token.
3. This function is returning jsonexception error when being called.
4. FirebaseError/auth-network-failed is returned with no other information.
NOTE: getIdToken() without param after logging in, returns token perfectly. But with parameter as true it fails all the time.

### Expected Behavior

1. getIdToken(true) should return new token, not the error.

### Code Reproduction

```
const app = getApp();
const auth = getAuth(app);
const updatedUser = auth.currentUser;
updatedUser?.getIdToken(true).then(token => {
     console.log(token, "Forceful"); // doesn't return this
}).catch(err => {
     console.error(err)
});
```
### Other Technical Details

`npm --version` output: 8.11.0

`node --version` output: v16.16.0

`pod --version` output (iOS issues only): nil

### Additional Context

firebase: 9.8.2

Please see the image below for the error.
![image](https://user-images.githubusercontent.com/114076352/195836023-53065d49-38ea-4f5b-9ee2-d451bfa06d95.png)

Thank you.

**Comment by shreyasPL** [comment]
@mlynch 
Could you please look into this issue?
I am unable to set the labels.
Thank you.

**Comment by harpalsira** [comment]
@mlynch 
Hi Max, we would really appreciate this bug being looked at as it's critical that it is fixed before we launch our app. I have reached out to support through other channels but if you could let us know what options we have to expedite this fix, I would be eternally grateful!
best, 
Harpal

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by harpalsira** [comment]
@Ionitron thank you so much for taking a look. We’ll provide the additional information you have requested asap. Really appreciate the help!

**Comment by IbtesamAnsariPL** [comment]
### Code Reproduction
Steps:
1. Clone - https://github.com/IbtesamAnsariPL/pl-test
2. Run web platform.
3. Click on Login and then Refresh button -> Works as expected
4. Run on android platform - `npm run android`
5. Click on Login and then Refresh button -> Refresh fails with `JSON Exception`

**Comment by IbtesamAnsariPL** [comment]
@mlynch I have attached the reproduction steps above. Please have a look into it.

**Comment by shreyasPL** [comment]
@jcesarmobile Any update on this?
