### ISSUE TITLE
bug: npx cap migrate |  Upgrading gradle wrapper files failed

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/capacitor#5998]
### Capacitor Version

```
3.5.1
```

### Platform(s)

Android

### Current Behavior

It is getting failed.
![image](https://user-images.githubusercontent.com/23274631/195993113-4919b3b5-ddeb-4832-9d47-c87cae1ca38f.png)

### Expected Behavior

In case of failed it should give more information or link to update manually.

### Other Technical Details

`npm --version` output: 6.14.13

`node --version` output:v 14.17.1

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by indraraj26** [comment]
closing. I was able to build apk. I think Android studio did the magic.
