### ISSUE TITLE
bug: CapacitorCookies document.cookie setter doesn't handle attributes

### ISSUE THREAD

**Issue by afladmark** [ionic-team/capacitor#6012]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
All

### Current Behavior
I've been testing the set override provided by CapacitorCookies for `document.cookie` and I'm getting an unexpected result. It doesn't seem to handle any attributes beyond `key=value`. For example, if one adds expiry or other things like:

```javascript
 document.cookie = "doSomethingOnlyOnce=true; expires=Fri, 31 Dec 9999 23:59:59 GMT; SameSite=None; Secure"
```

The end result appears to be multiple cookies like: `doSomethingOnlyOnce=true`, ` expires=Fri, 31 Dec 9999 23:59:59 GMT`, ` SameSite=None` and Secure is discarded as it has no "value". Note the leading spaces on ` expires` and ` SameSite` too.

I had a look at the code and there doesn't seem to be anything to handle this, it just splits on `;` and creates a new cookie for each. As such it's impossible to set an non-session cookie and all cookies expire on relaunch of the app.

Furthermore, it's not even valid to create multiple cookies via a single call to `document.cookie`. From the Mozilla docs:

```
Note that you can only set/update a single cookie at a time using this method.
```

### Expected Behavior
The `document.cookie` set override should handle only a single cookie and should support all valid additional attributes and thus support features like expiration.

### Code Reproduction
```javascript
 document.cookie = "doSomethingOnlyOnce=true; expires=Fri, 31 Dec 9999 23:59:59 GMT; SameSite=None; Secure"
```

`document.cookie` should then return: `"doSomethingOnlyOnce=true"`, but instead it returns:

```
"SameSite=None;doSomethingOnlyOnce=true;expires=Fri,%2031%20Dec%209999%2023%3A59%3A59%20GMT"
```

### Other Technical Details
N/A

### Additional Context
[Mozilla Developer Docs](https://developer.mozilla.org/en-US/docs/web/api/document/cookie)

**Comment by afladmark** [comment]
Further to this, as a workaround, I've tried to use the `setCookie` method instead.

```javascript
CapacitorCookies.setCookie({ key: 'jwt_key', value: jwtValue, expires: "Fri, 25 Nov 2022 17:07:06 GMT" })
```

When I run `document.cookie` I get the kay and value back as expected. Woo. 

However, when I kill and restart the app and run `document.cookie` again I get back: `""`. :-(  Is this really this broken or am I missing something?

**Comment by ItsChaceD** [comment]
https://github.com/ionic-team/capacitor/pull/6086
