### ISSUE TITLE
Android 11 or bigger - Unable to resolve camera activitybug: 

### ISSUE THREAD

**Issue by gusmarra** [ionic-team/capacitor#6014]
i am trying to get a picture with the Camera plugin and everything works perfect in Android 10 or less. For Android version 11 or 12 I got an error

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/electron: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

### Platform(s)
Android 11 and 12

### Current Behavior
When call

 const image = await Camera.getPhoto({
      quality: 90,
      source: CameraSource.Prompt,
      width: 600,
      resultType: CameraResultType.DataUrl,
      promptLabelHeader: 'Foto',
      promptLabelCancel: 'Cancelar',
      promptLabelPhoto: 'Desde la galería',
      promptLabelPicture: 'Desde la camara'
    });

got the following error

ERROR Error: Uncaught (in promise): Error: Unable to resolve camera activity

### Other Technical Details
I also have all the intent on the AndroidManifest

<queries>
      <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="http" />
      </intent>
      
      <intent>
        <action android:name="android.media.action.IMAGE_CAPTURE" />
      </intent>
      
      <intent>
        <action android:name="android.intent.action.GET_CONTENT" />
        <data android:mimeType="image/*" />
      </intent>
      <intent>
        <action android:name="android.intent.action.PICK" />
        <data android:mimeType="image/*" />
      </intent>
      <intent>
        <action android:name="android.intent.action.CHOOSER" />
      </intent>
    </queries>

variables.gradle

ext {
    minSdkVersion = 21
    compileSdkVersion = 29
    targetSdkVersion = 29
    androidxAppCompatVersion = '1.1.0'
    androidxCoreVersion =  '1.2.0'
    androidxMaterialVersion =  '1.1.0-rc02'
    androidxBrowserVersion =  '1.2.0'
    androidxLocalbroadcastmanagerVersion =  '1.0.0'
    androidxExifInterfaceVersion = '1.2.0'
    firebaseMessagingVersion =  '20.1.6'
    playServicesLocationVersion =  '17.0.0'
    junitVersion =  '4.12'
    androidxJunitVersion =  '1.1.1'
    androidxEspressoCoreVersion =  '3.2.0'
    cordovaAndroidVersion =  '7.0.0'
}

**Comment by jcesarmobile** [comment]
Capacitor 2 will only receive security updates, this was fixed for Capacitor 3 (and we are in Capacitor 4 already), you should consider updating.
Update from 2 to 3 [guide](https://capacitorjs.com/docs/updating/3-0)
Update from 3 to 4 [guide](https://capacitorjs.com/docs/updating/4-0)

To solve the issue, you can add this to your manifest
https://github.com/ionic-team/capacitor-plugins/blob/main/camera/android/src/main/AndroidManifest.xml#L3-L7
