### ISSUE TITLE
bug: document.cookie is not a string when empty on Android with the CapacitorCookiePlugin

### ISSUE THREAD

**Issue by jrobeson** [ionic-team/capacitor#6020]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0

[success] Android looking great! 👌

```

### Platform(s)
Android

### Current Behavior

When accessing document.cookie in the console via the chrome inspector, the result is `undefined`, while on chrome on regular websites the result is `''`

When attempting to use the axios http library, it fails because it calls `match` on what it expects to be a string, but isn't.

### Expected Behavior

I expect `document.cookie` to return an empty string when no cookies are set as per https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-8747038

### Code Reproduction

Just open any android application with the plugin enabled and access `document.cookie` in the inspector.  I might be submitting a PR for this, once i have some questions answered, so I'm gonna skip out on the reproducer for now. I'll add one if necessary

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context

I've narrowed it down to the fact that [`getCookie`](https://github.com/ionic-team/capacitor/blob/ae941017fff3bcfa75e0788535f356a56ce6fa05/android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookieManager.java#L54) can return null if there are no cookies stored, which is returned unconditionally by callers like [`getCookieString`](https://github.com/ionic-team/capacitor/blob/ae941017fff3bcfa75e0788535f356a56ce6fa05/android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookieManager.java#L43)

As far as fixing it, it seems like a function called `getCookieString` should perhaps always return a string, but there are perhaps other callers that might make that annoying to deal with. It could also be fixed in the native-bridge instead.  Let me know what you folks think about that.

**Comment by jrobeson** [comment]
this is not fixed capactitor 4.5.0 on android at least. I don't have an ios device to verify it there.

**Comment by ItsChaceD** [comment]
This is merged into `main`, so it will be included with the next release of capacitor.

**Comment by jrobeson** [comment]
oh my mistake. sorry. It is indeed after the 4.5.0 release.
