### ISSUE TITLE
feat: Integrate support for Redex

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/capacitor#6025]
This has the potential to make the final APK smaller and faster at runtime, both for the default APK and for plugin Java/Kotlin code.
https://github.com/facebook/redex

I guess the optimization pass could be opt-in via a JSON config flag.

**Comment by jcesarmobile** [comment]
Thanks for the request, but we would rather not depend on 3rd party companies for Android development other than from Google.
As I understand redex, anybody could add that to their app, doesn't need to be built in into Capacitor.
