### ISSUE TITLE
Camera PWA/Browser with pwa-elements >= 0.0.12 wrong gray overlay / not displayed correctly

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/capacitor#603]
**I'm submitting a:**
[X] bug report

**Current behavior:**

Implementing the camera (base64) as displayed in the documentation (https://capacitor.ionicframework.com/docs/apis/camera) works just fine if I add the pwa-elements v0.0.11 in index.html respectively

     <script src='https://unpkg.com/@ionic/pwa-elements@0.0.11/dist/ionicpwaelements.js'></script>

but as soon as I try to use pwa-elements 0.0.12 or above the camera isn't displayed anymore, it just end up in a gray overlay

     <script src='https://unpkg.com/@ionic/pwa-elements@0.0.12/dist/ionicpwaelements.js'></script>

the camera feature itself still work, if I try my luck and click there or there at some point a photo is taken

**Screenshots**

pwa-element v0.0.11: OK

<img width="968" alt="capture d ecran 2018-06-22 a 17 09 33" src="https://user-images.githubusercontent.com/16886711/41784320-a7290698-763f-11e8-9203-92f51eedc7b5.png">

pwa-element v0.0.12: Not OK

<img width="974" alt="capture d ecran 2018-06-22 a 17 08 05" src="https://user-images.githubusercontent.com/16886711/41784360-c656b52e-763f-11e8-9deb-6c651356cc0f.png">

**Comment by mlynch** [comment]
This is just waiting on some last Ionic 4 bug fixes and then it'll work

**Comment by peterpeterparker** [comment]
@jcesarmobile still doesn't work in a v3 app

<img width="1223" alt="capture d ecran 2018-08-18 a 11 59 50" src="https://user-images.githubusercontent.com/16886711/44298165-4b9fbf80-a2de-11e8-8194-f20a7a4139bf.png">

<img width="1224" alt="capture d ecran 2018-08-18 a 11 59 41" src="https://user-images.githubusercontent.com/16886711/44298166-5195a080-a2de-11e8-9007-45d1bf6b4133.png">

**Comment by jsdussanc** [comment]
Ward

**Comment by mlynch** [comment]
Can you try `@ionic/pwa-elements` 1.0.0? https://github.com/ionic-team/capacitor/issues/658#issuecomment-427504179

**Comment by peterpeterparker** [comment]
Didn't tested with an Ionic v3 app but I could confirm that I didn't faced the problem anymore when I tried to take a photo in Safari with the `@ionic/pwa-elements` 1.0.0 and a Ionic v4 app, no overlay problem, all good, thx a lot for the fix @mlynch 👍

**Comment by mlynch** [comment]
w00t!
