### ISSUE TITLE
bug: Changing "appName" in capacitor.config.json does nothing to the folder name of the platform versions

### ISSUE THREAD

**Issue by jcosta33** [ionic-team/capacitor#6031]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0
```

### Platform(s)

iOS, Android

### Current Behavior

My app name is not applied to the folder names inside each platform. xCode uses the folder name to name the project, which is why this is a problem. I have deleted and ran the "add" command multiple times to no effect.

### Expected Behavior

The folders and config files should inherit from this value. 

### Code Reproduction

Simply start any ionic app, change the "appName" and see it having no effect on the build folders.

### Other Technical Details

`npm --version` output: 6.14.17

`node --version` output: v14.19.2

`pod --version` output (iOS issues only): 1.11.3

**Comment by mlynch** [comment]
Additionally, trapeze.dev can do this and has a lot more native mobile project configuration features
