### ISSUE TITLE
bug: document.cookie does not seem to work at all with capacitor/core http

### ISSUE THREAD

**Issue by silviogutierrez** [ionic-team/capacitor#6032]
## Bug Report

I may be going crazy, so if this isn't functionality that is supposed to work, please let me know.

### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌


```

### Current Behavior
Requesting any URL that replies with `set-cookie` as a header seems to be ignored. `document.cookie` continues to be undefined.

### Expected Behavior
With CapacitorHttp and CapacitorCookie enabled, requesting a URL that has a `set-cookie` should update `document.cookie` and send cookies afterwards to further requests.

### Code Reproduction
Clone the repo here: https://github.com/silviogutierrez/capacitor-http-tests

This is virtually the result of `npm init @capacitor/app` but with these lines modified; https://github.com/silviogutierrez/capacitor-http-tests/blob/main/src/js/capacitor-welcome.js#L83

Run:
npm install
npm run build
npx cap sync ios
npx cap sync android
npx open android
npx open ios

Then run both projects. Click "make request" and see how the console logs cookies, and they continue to be undefined. Just in case it was an async thing, click "log cookies" a bit later to continue observing the behavior.

Note the curl for the URL being hit produces this (note the set-cookie header)
```
curl -X GET -I https://www.joyhealthtracker.dev/api/csrf/
HTTP/2 200
server: openresty/1.15.8.2
date: Thu, 27 Oct 2022 02:55:46 GMT
content-type: application/json
content-length: 2
strict-transport-security: max-age=15724800; includeSubDomains
vary: Cookie, Origin
x-frame-options: DENY
x-api-version: v13.0.0
set-cookie: csrftoken=vK5Kbn4cx4L2rGjKsw84QbMN6Blk5eq1yl378tLhQLnoKvkS2bt4up6wDRYd4fSC; expires=Thu, 26 Oct 2023 02:55:46 GMT; Max-Age=31449600; Path=/; SameSite=Lax
x-request-id: 1000f65fb8b46700f9bff000daf1be90
```

**Comment by silviogutierrez** [comment]
Hi @ItsChaceD , thanks for looking into this. I'm wondering if you're able to reproduce. If so, I'm wondering why others have not reported this. Is using cookies *that* unusual with capacitor? That is, is everyone else using JWT stored in local storage?

Thanks!

**Comment by jrobeson** [comment]
@silviogutierrez capacitor only just included a cookie plugin in core in the past month. I'm not sure how many people are using it yet.

Previously I think folks were using the separate http plugin, which I imagine handled cookies.

**Comment by silviogutierrez** [comment]
@jrobeson true, though I imagine a lot of the code is shared. This is just about the most basic use case, so I'm wondering if my repro is wrong.

**Comment by ItsChaceD** [comment]
The primary issue was that by default on native platforms, `Set-Cookie` responses are only set for the remote server url. Due to the nature of Capacitor however, it is required to set the cookie responses on the local url as well in order for them to persist and be accessed by `document.cookie`.

This PR addresses this issue, as well as some other issues with cookies persisting: https://github.com/ionic-team/capacitor/pull/6086

**Comment by jrobeson** [comment]
@ItsChaceD then you can close this one right?
