### ISSUE TITLE
Camera PWA/Browser: Cancel lead to Uncaught (in promise): undefined

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/capacitor#604]
**I'm submitting a:**
[X] bug report

**Current behavior:**

When I cancel the camera popup in the browser I land on the following error:

> Error: Uncaught (in promise): undefined
>     at c (http://localhost:8100/build/polyfills.js:3:19752)
>     at http://localhost:8100/build/polyfills.js:3:19174
>     at rejected (http://localhost:8100/build/main.js:167:89)
>     at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
>     at Object.onInvoke (http://localhost:8100/build/vendor.js:5134:33)
>     at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
>     at r.run (http://localhost:8100/build/polyfills.js:3:10143)
>     at http://localhost:8100/build/polyfills.js:3:20242
>     at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
>     at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5125:33)

**Screenshots**

<img width="968" alt="capture d ecran 2018-06-22 a 17 09 33" src="https://user-images.githubusercontent.com/16886711/41784510-348d1952-7640-11e8-9f43-6544625105b3.png">

<img width="971" alt="capture d ecran 2018-06-22 a 17 17 03" src="https://user-images.githubusercontent.com/16886711/41784516-39bad4b4-7640-11e8-9727-bfe1c8fa4189.png">

**Code**

Same as in the documentation https://capacitor.ionicframework.com/docs/apis/camera

**Comment by mlynch** [comment]
If you don't take a photo the call rejects, so you need to wrap `getCamera` in a try/catch

**Comment by peterpeterparker** [comment]
thx, sorry for having opened the issue then @mlynch

**Comment by cc-xerri** [comment]
Problem solved. https://stackoverflow.com/questions/52352608/capacitor-trying-to-catch-the-cancel-on-camera shows that that feature was missing and should be released soon.

**Comment by jcesarmobile** [comment]
Next time you can create a new issue as this one was for PWA, not for iOS and I would have missed it if it wasn't for your SO question.
