### ISSUE TITLE
bug: CORS error when changing server.hostname on iOS

### ISSUE THREAD

**Issue by RClaudiuM** [ionic-team/capacitor#6045]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[error] com is missing in
        /Users/'user'/Projects/'project'/'project/'project'/packages/'package'/android/app/src/main/java.
        Please create a directory structure matching the Package ID 'appId' within the
        /Users/'user'/Projects/'project'/'project'/'project'/packages/'package'/android/app/src/main/java
        directory.
```

### Platform(s)

1. iOS

### Current Behavior

As it stands now the app works fine in iOS with the default server.hostname config in `capacitor.config.ts` but when I change the hostname to anything else like `sub.example.co.uk` the android app works fine but the iOS app throws a CORS error in Safari when I make a PUT request.

### Expected Behavior

The app should make that PUT request in Safari without a CORS error

### Code Reproduction

I'll have to spin up a whole CORS enabled back-end for that

### Other Technical Details

`npm --version` output: 8.11.0

`node --version` output: v16.15.1

`pod --version` output (iOS issues only): 1.11.3

CapacitorCookies plugin is enabled on iOS, but it does not really matter because i get the same behaviour if i disable it.

### Additional Context

Of course CORS is enabled on the back-end and the origins are added on the server.
For android is `http://server.hostname` 
And for iOS is `capacitor://server.hostname`
*Replace `server.hostname` with whatever you have in `capacitor.config.ts` at server.hostname*

I'll attach some screenshots with the failed request.
I am unable to see the preflight for the request because Safari doesn't have that feature

### iOS:
![Screenshot 2022-11-02 at 10 21 52 AM](https://user-images.githubusercontent.com/94641613/199437422-2e1dbd0e-4cce-44bd-b4f3-805dd161be32.png)
![Screenshot 2022-11-02 at 10 23 21 AM](https://user-images.githubusercontent.com/94641613/199437436-5452df73-fe17-4ff3-a6cb-934fc65023c7.png)

### Android:
Preflight request:
![Screenshot 2022-11-02 at 10 31 55 AM](https://user-images.githubusercontent.com/94641613/199439615-79a4a13f-219f-4bf4-a208-c810a79f1826.png)

Actual Request:
![Screenshot 2022-11-02 at 10 35 14 AM](https://user-images.githubusercontent.com/94641613/199440022-d63836d1-77a2-40f0-9366-58ceb1a25e4e.png)

I am 100% sure CORS is enabled on the back-end and the origins for both Android and iOS are added there

**Comment by jcesarmobile** [comment]
CORS problems are almost always server problems or in rare cases WKWebView bugs, in any case it's not a Capacitor bug.

As of Capacitor 4.4.0, you can use Http plugin to use native connections instead of WebView connections for XHR and fetch
https://capacitorjs.com/docs/apis/http
