### ISSUE TITLE
Allow full screen video on Android

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#605]
I've created a video.js sample app and it doesn't show the full screen video button, nor opens full screen when using `playsinline: false` option.
Same app in Cordova has full screen video button and goes full screen when play is pressed if `playsinline: false` option is used.
We should also allow full screen video in Capacitor

Sample app:
https://github.com/jcesarmobile/playerjs-example

**Comment by rgolea** [comment]
@jcesarmobile found an article on it but I'm just starting on mobile and Android and I'm not able yet to understand everything to make a PR.
https://www.monstertechnocodes.com/2018/07/how-to-enable-fullscreen-mode-in-any.html?m=1
As far as I can see, it has to do with the Webview and ChromeClient that you assign to the webview and it's settings. It has something to do with enabling fullscreen on that view but I don't fully understand what's going on. Maybe check it out?

Cheers!

**Comment by rgolea** [comment]
@jcesarmobile found an article on it but I'm just starting on mobile and Android and I'm not able yet to understand everything to make a PR.
https://www.monstertechnocodes.com/2018/07/how-to-enable-fullscreen-mode-in-any.html?m=1
As far as I can see, it has to do with the Webview and ChromeClient that you assign to the webview and it's settings. It has something to do with enabling fullscreen on that view but I don't fully understand what's going on. Maybe check it out?

Cheers!

**Comment by rgolea** [comment]
@jcesarmobile found an article on it but I'm just starting on mobile and Android and I'm not able yet to understand everything to make a PR.
https://www.monstertechnocodes.com/2018/07/how-to-enable-fullscreen-mode-in-any.html?m=1
As far as I can see, it has to do with the Webview and ChromeClient that you assign to the webview and it's settings. It has something to do with enabling fullscreen on that view but I don't fully understand what's going on. Maybe check it out?

Cheers!

**Comment by rgolea** [comment]
Any news on this?

**Comment by greensopinion** [comment]
We've run into this issue as well, the "full screen" control button is present but disabled on the video player.

**Comment by rgolea** [comment]
@greensopinion yeah, mine too... I've been trying to debug the project and implement this feature on my own on capacitor. It seems it has something to do with the WebView or WebChromeClient handling entering and exiting fullscreen but since I'm not an Android developer it's going really slow...

**Comment by rgolea** [comment]
@greensopinion try PR #1763 and tell me if this works for you

**Comment by greensopinion** [comment]
> @greensopinion try PR #1763 and tell me if this works for you

Just tested on the simulator, works!  Thanks @rgolea

**Comment by rgolea** [comment]
@greensopinion any time! I would recommend that each time you start a project you just copy-paste the changes from the PR in order to have the latest version of capacitor (until the PR merges).
