### ISSUE TITLE
bug: plugin for IOS custom viewController will not display view. 

### ISSUE THREAD

**Issue by jaybowman** [ionic-team/capacitor#6052]
## Bug Report
I'm building a plugin and my custom view will not open. It acts like the view controller can't find the xib file.
see [stackoverflow](url) 
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
```

### Platform(s)
IOS, I have the plugin working fine on Android

### Current Behavior
My issue is that the view doesn't display, I get a black screen on the simulator. It's like the controller can't find the xib view file. Degbugging I get the events firing: viewDidLoad(), ViewDidAppear(). The links between the controller and the xib are all good in xCode. I tested with an UIAlertController and it displays OK.

### Expected Behavior
Load my map view

### Code Reproduction

```
DispatchQueue.main.async {
    let  mapCtrl = NavigateRouteViewController(withRouteInfo: routeInfo)
    mapCtrl.modalPresentationStyle = .fullScreen
    self.bridge!.viewController!.present(mapCtrl, animated: true, completion: nil)            
}
```

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v16.13.0

`pod --version` output (iOS issues only): 1.10.1

**Comment by jcesarmobile** [comment]
I'm sorry but this is a bug in your code, not a Capacitor bug.

If you want to ask for help, you can create a discussion on the [discussions section](https://github.com/ionic-team/capacitor/discussions) or create thread on [the Ionic forum](https://forum.ionicframework.com/c/capacitor/26)

But you should provide more information, there isn't enough information in this issue to help you. Also the link to stackoverflow is broken.
