### ISSUE TITLE
bug: Requested but did not find extension point with identifier blabla watchOS

### ISSUE THREAD

**Issue by twoco** [ionic-team/capacitor#6058]
## Bug Report

> Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

### Capacitor Version

```
@capacitor/cli: 3.4.3
@capacitor/core: 3.4.3
@capacitor/android: 3.4.3
@capacitor/ios: 3.4.3
```

Capacitor 4.4 is currently not possible. I think it should also fixed in 3.x. Or is this a known issue related to this version? I would be grateful for any tip and appreciate any help. It's just exhausting... I've updated my Mac OS, iOS and Xcode to the latest version.

### Platform(s)

iOS 16.0.2

### Current Behavior

Just wanted to build a simple Ionic Angular Capacitor on my MacBook M1 with Ventura 13.0. No special configuration. Just created a new Ionic capacitor app. Some weeks ago it worked flawless. Ok I got the FFI bus error. But fixed with the installation. Then it works fine. And today I get another weird message about WatchSupport?! My app is not related to Apple Watch. Just target iOS iPhone. The Android build works btw.

### Expected Behavior

Build without pain.

### Code Reproduction

```
ionic capacitor run iOS
[capacitor] ✔ Copying web assets from www to ios/App/App/public in 306.26ms
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 450.04μs
[capacitor] [info] Found 1 Cordova plugin for ios:
[capacitor]        cordova-plugin-insomnia@4.3.0
[capacitor] ✔ copy ios in 324.10ms
[capacitor] ✔ Updating iOS plugins in 3.96ms
[capacitor] [info] Found 4 Capacitor plugins for ios:
[capacitor]        @capacitor/app@1.1.1
[capacitor]        @capacitor/haptics@1.1.4
[capacitor]        @capacitor/keyboard@1.2.2
[capacitor]        @capacitor/status-bar@1.0.8
[capacitor] [info] Found 1 Cordova plugin for ios:
[capacitor]        cordova-plugin-insomnia@4.3.0
[capacitor] ✔ Updating iOS native dependencies with pod install in 1.66s
[capacitor] ✔ update ios in 1.68s
[capacitor] ✖ Running xcodebuild - failed!
[capacitor] [error] 2022-11-06 21:21:53.869 xcodebuild[2288:35311] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

### Other Technical Details

`npm --version` output: 8.5.0

`node --version` output: 16.14.2

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by twoco** [comment]
I got it to work now. Xcode updated again. Agree to the license and log in again for the dev team account. Nothing is related to the watchOS issue, but anyway...
