### ISSUE TITLE
bug: StatusBar setOverlaysWebView overlay false does not work.

### ISSUE THREAD

**Issue by twoco** [ionic-team/capacitor#6059]
### Capacitor Version

```
@capacitor/cli: 3.4.3
@capacitor/core: 3.4.3
@capacitor/android: 3.4.3
@capacitor/ios: 3.4.3
```

### Platform(s)

iOS 16.0.2

### Current Behavior

```ts
StatusBar.setOverlaysWebView({ overlay: false });
```

does not work.

### Expected Behavior

There must be a way to set the status bar to not be overlaid. It should be possible to leave the status bar unaffected by HTML content.
For example if your app provides a light and dark mode, it's impossible to handle the color of the status bar. You don't know the background. `StatusBar.setStyle({ style: this.settings.darkMode ? Style.Dark : Style.Light });` works, but makes no sense if overlayed. I could underlay it with HTML and contrast color if I would know the height. But this is just bungling. I think the status bar behavior is something to configure in WebView. So I don't need to care about the StatusBar or my content underneath. Just render the app below the status bar. No need for safe areas, styles, etc. 

### Code Reproduction

Just create a new app and execute the code above.

### Other Technical Details

`npm --version` output: 8.5.0

`node --version` output: 16.14.2

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment]
This is intended, not a bug.

You should be able to know the status bar height by checking the safe area constant values that Apple provides.
https://webkit.org/blog/7929/designing-websites-for-iphone-x/

Also, for automatic status bar text color change based on the user's device theme you can use `Style.Default`.

**Comment by twoco** [comment]
What's with Android? My current problem is I have to set the text color of status bar depending on theme or header background. On Android the status bar does not overlay. Changing the color causes either black on black or white on white. Can Android status bar overlay or not? If not, then I just check the OS before chaning. But I never know the current status bar behavior / appearance. Default style does not fix the issue until I don't know the appearance (e.g. overlaid or not). Also the setting overlay or not of Capcitor doesn't work. ...

**Comment by twoco** [comment]
It seems that `safe-area-inset-top` does not work on Android. I set `setOverlaysWebView` on Android and need to set `_forceStatusbarPadding` on `IonicModule`. But it's not the best solution. Is this a known issue? Or how to handle this? I appreciate any hint.
