### ISSUE TITLE
Geolocation plugin needs to be reusable from java code

### ISSUE THREAD

**Issue by fssrepository** [ionic-team/capacitor#606]
You might want to watch the position and show on a native map.

I would like to call a logic from my plugin code instead of from the javascript, as i need to callback every time with the new position on the map.

**Comment by mlynch** [comment]
I don't understand what you're asking. Can you clarify please?

**Comment by fssrepository** [comment]
There is a line inside the Geolocation plugin:

  @PluginMethod(returnType=PluginMethod.RETURN_CALLBACK)
  public void watchPosition(PluginCall call) {

Now what i would like to instead of populating the PluginCall from my java code to be able to use the Geolocation code behind, i would like to use a proper interface.

It would be nice for every plugin, if the logic would be extracted from the Plugin logic, so i can reuse the code for any code what i'm writing in java also. (as there are plugins which will be always available, depending on it, instead of rewriting some logic would be welcoming)

**Comment by jcesarmobile** [comment]
Usually map SDKs have their own code for getting and drawing the user position, so you shouldn't really need to get it from Geolocation plugin to draw it, the map SDK should handle it itself.
