### ISSUE TITLE
Single Sign-on (SSO) Child Browser Flow (v2)

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#6066]
Capacitor has an excellent [Browser API](https://capacitor.ionicframework.com/docs/apis/browser).

However, a common usage is Single Sign-on (SSO) such as OpenID-Connect and system-to-system authentication, such as OAuth. For these use-cases the Browser API doesn't work that well.

It would be great if Capacitors Browser API would support this common use-case.

Happy to elaborate on this and describe the use-cases in-depth.

Let me know what you think! Is this something that could be added to the Browser API?

## iOS

Apple has two classes for this, [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) (deprecated) and [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) (their most recent API).

They make sure that credentials (active sessions) with the identity provider is re-used within the child-browser, to avoid prompting the user for login credentials over and over again.

## Android

Android has [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs#whentouse) for this purpose, they work similar to their iOS equivalents.

***

*Opened this issue, since your bot [locked](https://github.com/ionic-team/capacitor/issues/1948#issuecomment-1073677022) the original one.*

**Comment by jcesarmobile** [comment]
The issue you linked was closed because at the time there was already another issue asking for an auth plugin, which later on was turned into a [community plugin request](https://github.com/capacitor-community/proposals/issues/17).
