### ISSUE TITLE
feat: @capacitor/browser are too few features

### ISSUE THREAD

**Issue by lys623** [ionic-team/capacitor#6069]
### Description

https://github.com/apache/cordova-plugin-inappbrowser  Hopefully it will line up

must：

1. executeScript
2. insertCSS
3. loadstart
4. toolbar custom-made

**Comment by jcesarmobile** [comment]
Browser plugin is a totally different plugin from InAppBrowser and none of those features are possible on the native components Browser plugin uses, but on the other hand is way more secure.
So if you want more security, use Browser plugin, if you need those features, use InAppBrowser plugin, Capacitor has Cordova plugin support, so you can use it.
