### ISSUE TITLE
bug: zsh:1: command not found: npx？？？

### ISSUE THREAD

**Issue by lys623** [ionic-team/capacitor#6071]
## Bug Report

 click 'Run Android':

![image](https://user-images.githubusercontent.com/4364314/201309878-26a7977f-acfd-41ee-9644-18b98a4af49e.png)

I have installed npx，

![image](https://user-images.githubusercontent.com/4364314/201310085-95e5de1f-3b9d-489d-96a5-ed56b8516cb4.png)

![image](https://user-images.githubusercontent.com/4364314/201310114-e632bfd5-7f9e-453c-b4fe-ae622a45f586.png)

### Capacitor Version

```
PASTE OUTPUT HERE
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
That looks like a bug on the ionic extension, you can report issues with the extension here https://github.com/ionic-team/vscode-extension/issues

Also, not sure if it could be related, but you are using the deprecated ionic CLI, uninstall it and install @ionic/cli 

```
npm uninstall -g ionic
npm install -g @ionic/cli
```
