### ISSUE TITLE
bug:  app build with cap 4 plugin fails No Such Module capacitor

### ISSUE THREAD

**Issue by sdetweil** [ionic-team/capacitor#6089]
## Bug Report
see https://forum.ionicframework.com/t/capacitor-4-plugin-in-upgraded-app-fails-build-no-such-module-capacitor/228622
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/ios: 4.4.0

[success] iOS looking great! 👌
[success] Android looking great!
```

### Platform(s)

only trying ios at the moment

### Current Behavior

ionic build, npx cap sync work ok
npx cap open ios,  opens xcode as expected, select project build 

fails. on the plugin stub swift file... which compiled just a second ago in the plugin project folder

### Code Reproduction

all I did was add my plugin,,, npm install and pod install as before..

### Other Technical Details

`npm --version` output: 8.11.0

`node --version` output: v16.15.1

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

![image](https://user-images.githubusercontent.com/1498142/202047642-31a48057-9b7b-4da2-af47-9137bd3123f1.png)
![image](https://user-images.githubusercontent.com/1498142/202047762-183c3470-4a12-4523-8fdb-af465e850b0b.png)

**Comment by sdetweil** [comment]
i removed the ios folder and did

npx cap add ios
ionic build 
npx cap sync ios
all worked

open xcode, same failure

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by sdetweil** [comment]
yeh, SO much fun.. now to try to create a new app AND a new plugin..  in the OLD cap 3.3 and then migrate it.. 

isn't there any path debug info, clearly gotta be a path problem.. the plugin thinks its one thing the app thinks its another
