### ISSUE TITLE
dark/light theme doesn't switch until app restart

### ISSUE THREAD

**Issue by ddurham2** [ionic-team/capacitor#6100]
There's a comment in #4677 that seems to have been ignored when that issue was marked closed.  That is, dark mode is now correctly detected from the system when the app starts up, but at least for me on Android, you have to kill and restart the app for it to change after sunrise.
  I would expect it to either change while the app is running, or at the very least, change the next time I return to the app (even if I left it running).

Original Comment:
        I can report the same issue. I can change the theme in the app once anf when I want to change it back the new color theme is not applied. iOS works fine

_Originally posted by @danielsogl in https://github.com/ionic-team/capacitor/issues/4677#issuecomment-1208516171_

**Comment by jcesarmobile** [comment]
Capacitor doesn't handle the changing of the theme, it just uses the `DayNight` theme as google engineers recommended as it's supposed to handle the changing of themes automatically on the WebView.
If the change is not working fine, then you should report it to Google.

**Comment by ddurham2** [comment]
Umm.. closing this seems a bit premature.  I definitely have other Android apps that work properly.  So, either I'm doing something wrong or incomplete, or capacitor is.  All indications are that ionic aims to make apps behave as native apps.

Just noting, I'm using what the ionic command initially generated.  Thankfully, it does generate the css files with darkmode colors already defined.

Is there evidence that _any_ capacitor app changes properly w/o restarting the it?  If so, is there some call that at least has to be made when returning to the app, or called periodically?  Is extra requirement this documented (I'm not reading anything in the theming docs and I'd be happy to make a PR to correct that)?  Is there a call I can make to attempt to redraw/re-evaluate the view?

There's some evidence here that we must be proactive, but I'm fuzzy on the Android details there (the reason I'm using ionic in the first place):
- https://stackoverflow.com/questions/41724748/cannot-switch-between-modes-in-daynight-theme-dynamically
and here
- https://www.itcodar.com/android/letting-webview-on-android-work-with-prefers-color-scheme-dark.html
and this guy has written a plugin to add the missing support, but appears to require involved changes to the native java and swift code to make it work
- https://medium.com/@hinddeep.purohit007/supporting-dark-mode-in-ionic-capacitor-8e57fe9dbd47

It seems that capacitor may need some built in help to complete this functionality, no?
