### ISSUE TITLE
IOS AVAudioSessionPortOverrideNone doesn't route to handset

### ISSUE THREAD

**Issue by john8675309** [ionic-team/capacitor#6102]
I am using the plugin cordova-audio-toggle and it works fine in Android, I can do an AudioToggle.setAudioMode(AudioToggle.EARPIECE); The audio is routed to the handset instead of the speakerphone. On IOS this isn't the case. The Audio is routed to the Speaker no matter what. It's acting like the output device isn't seen by Capacitor, anyone have any ideas?

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jcesarmobile** [comment]
thanks for letting us know
