### ISSUE TITLE
bug: Capacitor Browser plugin overwrite headers

### ISSUE THREAD

**Issue by jorgegvillanueva** [ionic-team/capacitor#6119]
## Bug Report
when my app opens a page with svgs inside, the request loading that svg files has response headers wrong: instead of image/svg-xml has text/html. But the original are right: the plugin is overwritting the headers

### Capacitor Version

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0
  @capacitor/android: 4.3.0

### Platform(s)
Android

### Current Behavior
svg files loaded in object tags in pages inside the Capacitor Browser plugin are loaded with wrong response content type header.
Server responds with aimage/svg+xml but the plugin transforms it on text/html. 
When the svg is shown inside the object tag, appears with  two tags wrapper: html and body. But those tags breaks the css inside the svg we are using.

### Expected Behavior
svg headers must not be overwrotte

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
