### ISSUE TITLE
bug: CapacitorHttp - SSLHandshakeException on Android

### ISSUE THREAD

**Issue by KevinKelchen** [ionic-team/capacitor#6127]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Native Android

### Current Behavior

Hello there! 👋

Using the Angular `HttpClient`, which uses `CapacitorHttp` at a lower level, making a request to a particular API endpoint on native Android fails with an `SSLHandshakeException`. Native iOS with or without `CapacitorHttp`, Native Android _without_ `CapacitorHttp`, and Web work fine.

### Expected Behavior

Native Android should successfully receive the response to the request and not incur an `SSLHandshakeException`.

Also, if we want `CapacitorHttp` to work the same as XHR/fetch, this would be a difference.

### Code Reproduction

https://github.com/KevinKelchen/capacitor-http-ssl-handshake-issue#steps-to-reproduce

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

Thanks so much! 😀

Kevin

**Comment by jcesarmobile** [comment]
Thanks for the issue and the sample app with detailed steps to reproduce, but in this case I can't reproduce, the app is working fine on my Android device with both `CapacitorHttp` enabled and disabled. 
`SSLHandshakeException` can happen for several reasons, including a bad time/date on the device, missing intermediate certificates on the servers, certificates not trusted by certain devices, etc.
I've done a SSL check on `cdn.arcgis.com` and looks like it's missing some intermediate certificates according to https://www.digicert.com/help/
> The server is not sending the required intermediate certificate.
And missing ROOT certificate according to https://www.sslchecker.com/sslchecker
But other sites say everything is ok, so not sure how accurate that information is.

In which device/emulator did you find the problem? What's the Android version?
Does it also happen if you disable `CapacitorHttp`?

**Comment by jcesarmobile** [comment]
Ok, going to close for now, it might have been some temporary problem on the emulator or the server.
