### ISSUE TITLE
feat: make useLegacyBridge property of CapacitorConfig TS interface optional

### ISSUE THREAD

**Issue by VirtuaBoza** [ionic-team/capacitor#6128]
### Description

Since @capacitor/cli@4.5.0, the configuration options for android within the `CapacitorConfig` interface requires a `useLegacyBridge` boolean value, but I think it should be optional.

### Platform(s)

N/A

### Preferred Solution

According to the docs, it already defaults to `false`, so I think changing the Typescript definition to make the property optional is all that would be required.

**Comment by jcesarmobile** [comment]
It's already fixed here https://github.com/ionic-team/capacitor/pull/6095

Will probably be released this week.
