### ISSUE TITLE
bug: CapacitorHttp - Uploading a Blob fails on native iOS and Android

### ISSUE THREAD

**Issue by KevinKelchen** [ionic-team/capacitor#6132]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Native iOS
Native Android

### Current Behavior

Hello there! 👋

Using the Angular `HttpClient`, which uses `CapacitorHttp` at a lower level, making a request to upload a Blob on native iOS and Android fails. Native iOS _without_ `CapacitorHttp`, Native Android _without_ `CapacitorHttp`, and Web work fine.

In our production app, we are uploading files to our server and sending the `File` `Blob` *without* using `FormData`. For this repro, `file.io` seemed like a simple, reasonable solution for an endpoint that accepts file upload. However, it seems to require the use of `FormData`. Hopefully the repro will capture the issue we're having in our production app.

### Expected Behavior

Native iOS and native Android should successfully upload the Blob.

Also, if we want `CapacitorHttp` to work the same as XHR/fetch, this would be a difference.

### Code Reproduction

https://github.com/KevinKelchen/capacitor-http-blob-upload-issue#steps-to-reproduce

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

Thanks so much! 😀

Kevin

**Comment by joshuakwaite** [comment]
🥳 anything we can do to help that PR go through?

**Comment by jcesarmobile** [comment]
This is not reproducible on Capacitor 5.7.0, so it was probably fixed when the linked PR was merged
