### ISSUE TITLE
bug: CapacitorHttp - Loading esri vector map tiles fails on native iOS and Android

### ISSUE THREAD

**Issue by KevinKelchen** [ionic-team/capacitor#6134]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Native iOS
Native Android

### Current Behavior

Hello there! 👋

On native iOS and Android, there appears to be an issue with using the [esri ArcGIS API for JavaScript v3.x](https://developers.arcgis.com/javascript/3/) to load a vector tile layer in a map control. Using it will result in network requests to retrieve vector tile files including `.pbf` files. The network requests will use the `CapacitorHttp` plugin at a lower-level.

Native iOS _without_ `CapacitorHttp`, native Android _without_ `CapacitorHttp`, and Web work fine.

I'm not sure what exactly is failing about it, and it works without `CapacitorHttp`, so I did not tear down to a more minimal repro. If I had to guess which requests are problematic, it would be the requests for `.pbf` files which appear to contain binary data:

![image](https://user-images.githubusercontent.com/8027502/204925811-96f28e34-b7b4-4c10-9ae3-f7742ca891e6.png)

We've observed other issues with `CapacitorHttp` working with `Blob` data, so that makes me suspicious.

### Expected Behavior

Native iOS and Android using `CapacitorHttp` should work the same as without it and the same as Web. The map should display with the vector tile layer.

### Code Reproduction

https://github.com/KevinKelchen/capacitor-http-map-vector-tile-issue/blob/main/README.md#steps-to-reproduce

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

Thanks so much! 😀

Kevin

**Comment by colesimmons** [comment]
Also experiencing this!
