### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by shivamssh** [ionic-team/capacitor#6141]
import org.apache.cordova.file.FileUtils;
## Bug Report
Getting an error after installing media-capture plugin and after running command for build then throws error

android\capacitor-cordova-android-plugins\src\main\java\org\apache\cordova\mediacapture\Capture.java:35: error: package org.apache.cordova.file does not exist
import org.apache.cordova.file.FileUtils;

### Capacitor Version

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\shivam.sharma\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.3.9
   @angular-devkit/build-angular : 15.0.2
   @angular-devkit/schematics    : 15.0.2
   @angular/cli                  : 15.0.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.0
   @capacitor/android : 4.6.0
   @capacitor/core    : 4.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.7.1

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.0
   OS     : Windows 10

### Platform(s)
Android
 "@awesome-cordova-plugins/media-capture": "^6.2.0",
    "@capacitor/android": "^4.6.0",
    "cordova-plugin-media-capture": "5.36.0",

### Current Behavior

After installing media-capture it gives error - android\capacitor-cordova-android-plugins\src\main\java\org\apache\cordova\mediacapture\Capture.java:35: error: package org.apache.cordova.file does not exist
import org.apache.cordova.file.FileUtils;

### Expected Behavior
Android build should be created successfully.

**Comment by jcesarmobile** [comment]
cordova-plugin-media-capture has a dependency on cordova-plugin-file, but capacitor doesn't install the dependencies.
When you run `npx cap update` or `npx cap sync` it shows a warning about the missing dependency and tells you to install it.
Install cordova-plugin-file package and run `npx cap sync` and the problem should be solved.
