### ISSUE TITLE
bug: capacitor migration not updating t latest version. 

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor#6145]
`npm i -D @capacitor/cli@latest`
After installing latest CLI  running cap migrate not updating to latest version. 

`npx cap migrate` 

it only upgrades to v4.0.0. 
Current version is 4.6.0.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Saqib92** [comment]
Github url of demo project:

[Github Repo](https://github.com/Saqib92/capacitor-migration-issue)

To reproduce try these steps:

1) Clone repository
2) `npm i`
3) `npm i -D @capacitor/cli@latest`
4) `npx cap migrate`

It will upgrade to version 4.0.0 for platforms, core and plugins. Everything will be updated to `v4.0.0`. It should update to latest version of everything.

**Comment by Saqib92** [comment]
Changes committed. Please check package.json it only upgraded to `v4.0.0`

**Comment by jcesarmobile** [comment]
The packages are being set as `^4.0.0`, that means it will use latest 4.x version available. 
You can check the `package-lock.json` file, it says 4.6.0 version was installed.
https://github.com/Saqib92/capacitor-migration-issue/commit/6414230186908e10992d77f2ebf1ed250064dc35#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R2241
