### ISSUE TITLE
Plugin request: Credit card scanner

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/capacitor#615]
Credit card scanner just like card.io
This plugin is buggy, not maintained and not work at browser (pwa)

I know capacitor is beta and this plugin is very low priority, but save this issue open, maybe someday someone will take up the glove

There is an option that this plugin is irrelevant cuz maybe scanning credit card on the browser is impossible (Android and iOS is based on GPU)

**Comment by fssrepository** [comment]
I'm creating lots of in-house plugin for capacitor (cordova plugins were not maintained and buggy).
Looking at card.io, combining some of my plugins it can be done. (i'm not using open cv library - with that one is quite complicated task, but if you use mlkit from google, it won't be a big deal, i think some hours work) The opencv has some sort of webbrowser port, so it might scan in the browser.

Card data cannot be sent over the wire, as there is some regulation, what you need to fulfill, but i'm using mlkit for different less regulated purposes.

I had an idea some times back to scan id card, it might be the same thing. MlKit can read text.

http://tesseract.projectnaptha.com/ - Unfortunately it's very buggy, but web based, just can read normal book text (it's stable on that one), does not handle colors.

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/4. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
