### ISSUE TITLE
bug: Error: Geolocation.requestPermission is not implemented on web

### ISSUE THREAD

**Issue by nusjeff** [ionic-team/capacitor#6154]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

```

### Platform(s)

Web browser

### Expected Behavior

Dont throw an error

### Code Reproduction

```
import { Geolocation } from '@capacitor/geolocation';
const result = await Geolocation.requestPermissions()
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context

![image](https://user-images.githubusercontent.com/10702455/206690045-e4bf6fea-5c67-4aa1-a533-71984e054a4d.png)

**Comment by jcesarmobile** [comment]
It's not possible to request geolocation permission on web at the moment, so the method rejects with "Not implemented on web" error. It's not a bug, works as expected.
