### ISSUE TITLE
Browser is opening in popover instead of fullScreen

### ISSUE THREAD

**Issue by jpinkster** [ionic-team/capacitor#616]
By Default the SafariViewController should open in fullScreen mode based on more standards out there. Currently it is being hard set to popover. I would like to create a PR setting this to fullScreen mode instead.

Please review my fork / PR (Cannot figure out how to PR back to this repo): https://github.com/jpinkster/capacitor/pull/1

Lines:
https://github.com/ionic-team/capacitor/blob/99455d2a2e419ca12e3ee991b70c6f7216448924/ios/Capacitor/Capacitor/Plugins/Browser.swift#L20

**Comment by jcesarmobile** [comment]
@mlynch maybe add an option on the BroserOpenOptions to choose the presentation style?
But probably making full screen default and popover as option

**Comment by jpinkster** [comment]
What is the estimated timeline around this change? Currently we are manually updating the .swift file from node_modules which is an issue for our jenkins auto deployment process. I would love to get jenkins back to work 😆

**Comment by sbannigan** [comment]
Just submitted a PR to fix this and add to the BrowserOpenOptions. Not sure if there is anything equivalent for Android, so I noted that the option is for iOS only. CC: @jpinkster
