### ISSUE TITLE
bug: Images broken on the blog https://ionic.io/blog/ionic-vs-react-native-performance-comparison

### ISSUE THREAD

**Issue by zakuru** [ionic-team/capacitor#6162]
Images a broken on the blog pose not sure when to raise the issue 

![image](https://user-images.githubusercontent.com/171174/207547315-d180321d-1f7d-4f48-90ab-d40e6b59ee37.png)

Would be great to have them fixed 
Otherwise please let me know who to reach 
Thanks and sorry for any disturbance

**Comment by jcesarmobile** [comment]
Thanks for the report, I forwarded it to the proper team and it has been fixed.

**Comment by zakuru** [comment]
thank you so much @jcesarmobile !
