### ISSUE TITLE
Feature request: Ability to configure the port on which Capacitor runs its webserver

### ISSUE THREAD

**Issue by ntbnnt** [ionic-team/capacitor#617]
Currently, it doesn't seem possible to configure a dedicated port for Capacitor and instead it always chooses a random port. Ideally, I think the port number is configurable maybe via `capacitor.config.json` with a `capacitorPort` key since I think this is a fairly common setting to configure for any webserver. My main use case for configuring the port is to ensure that an external API I call can maintain strict cors policy (i.e. doesn't allow wildcard configurations). If this were implemented, it would make Capacitor a great option for our suite of PWAs.

https://github.com/ionic-team/capacitor/blob/dc2b5d7dbb893f597dc45be120ec95140129a669/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L94

**Comment by findusl** [comment]
This is closed as solved but I don't see the option in the configuration. How can it be done? https://capacitorjs.com/docs/config

**Comment by jcesarmobile** [comment]
The port was removed later on when the server was removed, there is no web server anymore.

**Comment by Chris2011** [comment]
Thx for letting us know, but how does it work internally? Does Android call a webserver and use http:// or does the App bootstrapped with app://. I couldn't find this detailed information to understand it. If you have a documentationpart for this, please point me to it. Thx.

**Comment by jcesarmobile** [comment]
When the WebView makes a request to `https://localhost` (or the configured scheme/hostname, it gets intercepted by the`shouldInterceptRequest` method https://developer.android.com/reference/android/webkit/WebViewClient#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest)
And it returns the data of the file being requested from the filesystem.
