### ISSUE TITLE
feat: Request to update the blog post https://ionic.io/blog/ionic-vs-react-native-performance-comparison to compare with React-Native and Hermes Engine

### ISSUE THREAD

**Issue by zakuru** [ionic-team/capacitor#6172]
Hi,

React-Native comes with a new JS Engine starting version 0.7: Hermes engine.

Would it be possible to request an update of the blog post against version 0.7 with Hermes engine ?

Thanks in advance

**Comment by jcesarmobile** [comment]
This repository is for reporting Capacitor issues, please, only use it for reporting Capacitor issues.

You can contact Ionic at https://ionic.io/contact

**Comment by zakuru** [comment]
ok thank you
