### ISSUE TITLE
not able to access import CapacitorHttp from @capacitor/core' 

### ISSUE THREAD

**Issue by amazonsingh** [ionic-team/capacitor#6176]
## Bug Report
when I import CapacitorHttp from core module, it throwing error
```'"@capacitor/core"' has no exported member named 'CapacitorHttp'```

do we need to install it as 
```npm i @capacitor/http```
and then import it as
```import { Http } from '@capacitor/http';```
but documentation is suggesting, that this module is exported in core https://capacitorjs.com/docs/apis/http
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0
  @capacitor/cli: 4.1.0

[success] iOS looking great! 👌
[error] app/src/main/assets directory is missing in android
```

### Platform(s)
mac os 13

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
CapacitorHttp was added in Capacitor 4.3.0, you are using Capacitor 4.1.0
