### ISSUE TITLE
bug: Svelte javascript not running (blank screen)

### ISSUE THREAD

**Issue by stemaDev** [ionic-team/capacitor#6178]
### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/cli: 4.6.1
  @capacitor/android: 4.6.1

[success] iOS looking great! 👌
```

### Platform(s)
iOS

### Current Behavior

I have a frontend that I made with Svelte. It works fine in browser. However I wanted to make an IOS app out of it with using Capacitor and for whatever reason, when I run the app in the simulator or my phone, I got a "blank" screen.
Later on I found out that it actually loads the html as when I set the background color in an inline style, it applies it and I added a text to the html and it shows.
Then I thought that it has issues with running JS bundle or it doesn't reach the app.js file. I added a "console.log" at the beginning of the app.js file which svelte creates and that log shows up in the log of xcode so it finds the js and runs it. I was thinking that maybe it cannot render into "body" so I created a max sized div and rendered into that. In a browser it still works, but nothing on the phone.

### Expected Behavior
javascript should be running as in a browser.

### Code Reproduction
I'll try to create one later.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by stemaDev** [comment]
The issue was with routing. The webserver in the app probably (can't say for sure) can't handle the server side urls and thus won't render any component. directly adding one of my components in place of the "router" component showed the component in the simulator, so I have to implement hash-based routing
