### ISSUE TITLE
bug: [CapacitorHttp] response.text() does not work on responses with Content-Type: application/json

### ISSUE THREAD

**Issue by silviogutierrez** [ionic-team/capacitor#6184]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)
- iOS
- Web

### Current Behavior
Related to #6170. Even if you try to work around the buggy behavior (strings, numbers and booleans are valid JSON and should be parsed) by calling `response.text()` instead of `response.json()`, Capacitor has already tried to parse this as JSON and return JSON for the data instead of the raw string.

It should return the raw string

### Expected Behavior
Calling `response.text()` on a response should return plain text, even if the headers indicate this is JSON. 

### Code Reproduction
See #6177, but for convenience: 

Go to https://github.com/silviogutierrez/capacitor-http-tester and clone the repository.

Run `npm install` and `npm cap sync` to get both emulators working.

Then run `npm run build && node server.js` to start the local server.

Now open `http://localhost:3000` and see how everything works on the browser.

After that run `npx cap open iOS` and run the simulator. And `npx cap open android` and run the emulator. 

This issue number and text case will be shown as failing on both iOS and Android, but passing on web.

**Comment by jcesarmobile** [comment]
Can't reproduce on Capacitor 5.7.0
