### ISSUE TITLE
bug: Navigation isn't native

### ISSUE THREAD

**Issue by ollyde** [ionic-team/capacitor#6185]
We are trying to migrate a Svelte project to iOS/Android.

I understand that Ionic can supply navigation transitions but they are extremely buggy and low quality.

You need to add a native navigation stack to capacitor, otherwise it's not viable as a PWA framework.

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/core: 4.6.1

[success] iOS looking great! 👌
```

### Platform(s)
iOS
Android

### Current Behavior
When tapping links or trying to swipe back there is no transition.

### Expected Behavior
- When swiping back it should swipe back.
- When going forwards or backwards it should use the platforms native transition.

### Code Reproduction
https://github.com/ollydixon/konsta
```run build + cap Sync + cap run ios```

Video example is using Cap with a design framework. It's the same result without the framework.

https://user-images.githubusercontent.com/6940726/208994819-6db030a6-df6d-4fd6-8334-39a711f4c569.mov

**Comment by jcesarmobile** [comment]
Closing as won't do
There are two options here:
one is using an UI framework that handles navigation animations for you, or do it yourself if you think the framework animations are extremely buggy and low quality.
two is creating a native view controller on every navigation so you can apply native animations to it.
That's already possible (with a considerable part of native code on your part) or using Portals, but still, I wouldn't recommend doing this as it's cumbersome and inefficient.

**Comment by ollyde** [comment]
@jcesarmobile we figured it out using a screenshot wrapper and layer to screen transitions in multiple web-views inside Capacitor. 
Thanks for taking a look, wasn't hard to fix. 
You guy should look into implementing this cause the current nav works badly on Android (new swipe back) and iOS.
