### ISSUE TITLE
Couldn't Configure App To lauch with a specified port 

### ISSUE THREAD

**Issue by Timileyin105** [ionic-team/capacitor#6187]
## Bug Report

angular v15
node v18
ionic v6.20.4

i have a capacitor app which runs on port 8100 by default, i need to change the default port from 8100 to another on the app startup.

i tried changing my package.json but discovered the start there wasnt in use 

thanks

**Comment by IT-MikeS** [comment]
If you are referring to running your app via `ionic serve` then you can use the `--port ` option in the cli command ([Ref](https://ionicframework.com/docs/cli/commands/serve)) otherwise please provide a reproduction repo of this issue.

**Comment by jcesarmobile** [comment]
Closing as Capacitor doesn't run your app on any port, this seems related to the framework you are using (ionic?).

If you are running ionic commands you can use --help parameter to see available options as, as Mike mentioned, you most likely need the --port parameter.
