### ISSUE TITLE
 Problem when init session with opentok in iOS

### ISSUE THREAD

**Issue by csarglue** [ionic-team/capacitor#619]
I need to use the opentok plugin in ios (opentok.js), but there is an error when init session in, without allowing me to post videos

The error it gives is: TypeError: 'arguments', 'callee', and 'caller' can not be accessed in this context.

**Comment by jcesarmobile** [comment]
can you show the code you are using?

the plugin is `cordova-plugin-opentok`, right? I've seen that there are others available.

**Comment by csarglue** [comment]
I am using cordova-plugin-opentok. 

When I do:
 session.connect (token, (error) => {
}

I have something as log:
Error on session connect: {"type":"sessionConnected","cancelable":true,"_defaultPrevented":false,"target":{"apiKey":"0000000","sessionId":"1_MX40NjA3ODY2Mn5-MTUzMDE4MjY5NDUyMH5jMUlMNUNUcGU5S0tnQjMzepn2WjhoZEt-UH4","connections":{"8E94POC0-D959-42DE-B29F-7EC0A6CC5A38":{"connectionId":"8E94POC0-D959-42DE-B29F-7EC0A6CC5A38","creationTime":"1530182697"}},"streams":{},"subscribers":{},"alreadyPublishing":false,"__testonly__":{},"token":"T1==cG5ydG5lcl9pZD00NjA3ODY2MmZzaWc9ZjgyYTNiNzM2NTQ3ZDE0MDM2OTU0ZjFjMTdjZjc4YzNlM2Y4MjkwZTpzZXNzaW9uX2lkPTFfTVg0ME5qQTNPRFkyTW41LU1UVXpNREU0TWpZNU5EVXlNSDVqTVVsTM5VTlVjR1U1UzB0blFqTXplU3QyV2pob1pFdC1VSDQmY3JlYXRlX3RpbWU9MTUzMDE4MjY5NSZub25jXT0wLjYwODc1MTQxNDU0ODc2Mzgmcm9sZT1wdWJsaXNoZXImZXhwaXJlX3RpbWU9MTUzMDI2OTA5NSZpbml0aWFsX2xaeW91dF9jbGFzc19saXN0PQ==","connection":{"connectionId":"8E94POC0-D959-42DE-B29F-7EC0A6CC5A38","creationTime":"1530182697"}}}

**Comment by jcesarmobile** [comment]
Did you find a solution?
