### ISSUE TITLE
bug: Capacitor push-notification: pushNotificationReceived in foreground

### ISSUE THREAD

**Issue by vanderbreye** [ionic-team/capacitor#6195]
## Bug Report
Capacitor 4.1.2
the listener pushNotificationReceived never gets triggered when app is in foreground;
But the push is triggered (via notification) when app is in Background or killed

### Platform:
Android (13, Device: Pixel4a)

### Current Behavior

When sending a Push notification via FCM and the app is open, pushNotificationReceived does not get fired.
If the app is in background, the same formatted push gets received & open in the notification-area.
All listeners were set correctly, all permissions are granted.

window.addListeners = async function(){

  await Capacitor.Plugins.PushNotifications.addListener('pushNotificationReceived',notification => {
  console.log("Push received");
  alert(JSON.stringify(notification));
  });
  
  await Capacitor.Plugins.PushNotifications.addListener('registration', token => {

[...]

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by yugandhargangu** [comment]
capacitor.config.json
{
"PushNotifications": {
      "presentationOptions": []
    }
}

Platform: **Android**
Issue description:
While sending Firebase notifications, The app is showing notification contents in notfiction panel only if app is in background. It is not being shown in notifications panel when app is in forground or user is using it.

**Comment by vanderbreye** [comment]
> not being shown in notifications panel when app is in forground

yes, THAT's normal behavior for android apps when a notification is received while app is in foreground.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by vanderbreye** [comment]
closing:
I had started a fresh project, copied over all files and reinstalled the plugins by handy - now "pushNotificationReceived" works as expeced.
