### ISSUE TITLE
bug: live reload doesnt work and google chrome is crashing in the emulator

### ISSUE THREAD

**Issue by ciprianm11** [ionic-team/capacitor#6201]
### Capacitor Version

```
miles@miles-linux bigdata]$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1

```

### Platform(s)
android 

### Current Behavior
E/Capacitor/Console: File: chrome-error://chromewebdata/ - Line 1 - Msg: Uncaught TypeError: Cannot read property 'triggerEvent' of undefined
this is what i see in the run console. 
google chrome doesnt go past accept and continue in the emulator
no live reload working

### Expected Behavior
would expect chrome to work in the emulator 
would expect live reload to work

### Code Reproduction
i just followed the install tutorial available today 30.12.2022 https://capacitorjs.com/docs/getting-started

### Other Technical Details
using Android Studio Dolphin | 2021.3.1 Patch 1 (works perfectly with my flutter project)

`npm --version` output: 8.19.2

`node --version` output: v18.12.0

`pod --version` output (iOS issues only):

### Additional Context
I would also suggest for future newcomers to capacitorjs, please generally improve the documentation especially the part about getting capacitor installed. Its so confusing with all those crossover references to ionic and if you do any googling about capacitor you also get references about cordova or something. its so cryptic and confusing.

**Comment by jcesarmobile** [comment]
live reload is not handled by capacitor, so if it's not working you should check your framework/tooling as the problem might be there
