### ISSUE TITLE
feat: TLS pinning for Capacitor HTTP

### ISSUE THREAD

**Issue by adnbrownie** [ionic-team/capacitor#6203]
### Description
In our applications, we are currently using [cordova-plugin-advanced-http](https://github.com/silkimen/cordova-plugin-advanced-http) which supports [TLS pinning](https://github.com/silkimen/cordova-plugin-advanced-http#setservertrustmode). We would like to request this feature for Capacitor HTTP, as the lack of this feature is currently holding us back from making the move to Capacitor HTTP.

### Platform(s)
iOS & Android.

### Additional Context
It seems this feature has a demand from [other](https://github.com/ionic-team/capacitor/issues/5145#issuecomment-1268301506) [parties](https://github.com/ionic-team/capacitor/issues/5145#issuecomment-944651468) [as](https://github.com/ionic-team/capacitor/issues/5145#issuecomment-944993635) [well](https://github.com/ionic-team/capacitor/issues/5145#issuecomment-1082365310).

**Comment by pbergner** [comment]
Also very interested in this feature

**Comment by JustinLebo** [comment]
I second this request!
