### ISSUE TITLE
Application shows white screen if Android WebView not latest or updated.

### ISSUE THREAD

**Issue by opindia123** [ionic-team/capacitor#6209]
### Capacitor Version

 Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1

### Platform(s)

Android

### Current Behavior

On some devices if android webview is not latest application shows white screen and stuck on that.
After update android webview from play store application start showing desired pages.

### Expected Behavior

Capacitor application should not be depend on android webview updates.

### Other Technical Details

`npm --version` output:
8.5.5
`node --version` output:
v16.15.0
`pod --version` output (iOS issues only):

### Additional Context

This issue observe in some android devices with platform version android 8,9,10 and 11.
Is there setting need to be take care during build process. Kindly update.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jansgescheit** [comment]
In this case it should show a hint that the webview is to old and has to be updated.

**Comment by jcesarmobile** [comment]
Capacitor requires Chrome/System WebView 60 to work.
https://capacitorjs.com/docs/android#android-support

All those devices have a newer Chrome/System WebView version, so your problem is your framework not supporting the Chrome/System WebView versions those devices have, not Capacitor. You'll have to check your framework docs to see if you can compile to older versions or not.
