### ISSUE TITLE
Weird padding at the bottom

### ISSUE THREAD

**Issue by dfjmax** [ionic-team/capacitor#621]
Just created a new project(Ionic + Capacitor) following the instructions on:
https://capacitor.ionicframework.com/docs/getting-started/with-ionic

Installed the app in IOS, and it looks like the attached screenshot(if you don't see the white padding at the bottom please open the image in another tab or something):
![img_0188](https://user-images.githubusercontent.com/10993488/42039413-9f3ab66a-7ac3-11e8-88b6-ba8f7ceb83f1.PNG)

Is this related probably with the StatusBar? Just noticed that it has the same size.

**Comment by mlynch** [comment]
This was fixed in #442. What version are you on? `npx cap doctor`

**Comment by dfjmax** [comment]
> This was fixed in #442. What version are you on? npx cap doctor

The issue is happening in iPhone 6, with IOS latest version.
npx cap doctor output:
@capacitor/cli: 1.0.0-beta.0
@capacitor/core: 1.0.0-beta.0
@capacitor/android: 1.0.0-beta.0
@capacitor/ios: 1.0.0-beta.0
Capacitor iOS: 1.0.0-alpha.39

**Comment by dfjmax** [comment]
Quick update:
I think this issue should be reopened!
I tested in other devices with the simulator, and with my iPhone 6. This is how it looks on iPhone X:
<img width="343" alt="screen shot 2018-06-28 at 12 59 45" src="https://user-images.githubusercontent.com/10993488/42045981-3a5d8410-7ad3-11e8-9e13-1fc569ac0d1a.png">

**Comment by dfjmax** [comment]
Okay sure. So are you planning on reopening the #337 ? Thanks!

**Comment by ix-xerri** [comment]
Same issue on iPhone X for me and running 1.0.0-beta.1.
