### ISSUE TITLE
bug: CapactorHttp does not pass Authorization header on iOS

### ISSUE THREAD

**Issue by amoscardino** [ionic-team/capacitor#6213]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/core: 4.6.1

[success] iOS looking great! 👌
```

### Platform(s)

- iOS

### Current Behavior

Making an HTTP request with `CapacitorHttp` and including an `Authorization` header results in the actual request to the server missing the header.

### Expected Behavior

All headers passed to `CapacitorHttp` should be passed to the server.

### Code Reproduction

I'm not sure how to set up a full replication of this since it requires a server app in addition to the client app. The client code is simple:

```
const response = await CapacitorHttp.get({
    url: 'https://my.server.domain/api/something'
    headers: {
        'Authorization': `Token MyToken12345`
    }
});
```

The behavior is the same when using `fetch()` with the plugin enabled to intercept those requests, too.

### Other Technical Details

`npm --version` output: 8.19.1

`node --version` output: v16.13.2

`pod --version` output (iOS issues only): 1.10.1

### Additional Context

I asked about this issue on the [Ionic Forums here](https://forum.ionicframework.com/t/capacitor-http-plugin-not-sending-header-on-ios/230220).

After some digging into the [Capacitor code](https://github.com/ionic-team/capacitor/blob/0735e89d48e77a1ddca97a48e3851f4a0a3ea2c1/ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift#L111), I think the issue is related to `URLRequest` and [how it treats certain headers](https://developer.apple.com/documentation/foundation/nsurlrequest#1776617). Per Apple's documentation, certain headers are reserved and setting them will do nothing. `Authorization` is one of those headers but there's no other way to pass that header when using `CapacitorHttp`.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by amoscardino** [comment]
Apparently this is not a bug but a (really) bad error message from the API I'm trying to interact with. Closing now.
