### ISSUE TITLE
bug: plugin_event_listener.remove doesnt

### ISSUE THREAD

**Issue by sdetweil** [ionic-team/capacitor#6218]
### Capacitor Version

4.6.1
```
PASTE OUTPUT HERE
```

### Platform(s)

ios 

### Current Behavior

says the function in the plugin was called
but add again produces duplicate events
remove add again now triple events

### Code Reproduction

see #3827 

### Other Technical Details

`npm --version` output:
8.9
`node --version` output:
16.8
`pod --version` output (iOS issues only):
1.11.3
### Additional Context

ionic Vue app, 
add listener on viewDidEnter 
remove on IonviewWillLeave

reroute to view again 
plugin only used in single view

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by sdetweil** [comment]
I'm gonna close this.. I think its the provider causing the duplicates
