### ISSUE TITLE
bug: CapacitorHttp unable to use delete method in ios

### ISSUE THREAD

**Issue by junxiong96** [ionic-team/capacitor#6219]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
```
### Platform(s)
Ios

### Current Behavior
i am trying to use CapacitorHttp.delete() method but in apps it will throw below error
```
 Error: Plugin CapacitorHttp does not respond to method call "delete" using selector "delete:".
⚡️  Ensure plugin method exists, uses @objc in its declaration, and arguments match selector without callbacks in CAP_PLUGIN_METHOD

```
but if i tried CapacitorHttp.request({...options,method:'delete'}) then it works fine

### Expected Behavior
Able to use CapacitorHttp.delete() method

### Code Reproduction
```
const { data } = await CapacitorHttp.delete(options);
```

### Additional Context
i think the function should be delete instead of del right?
[Reference](https://github.com/ionic-team/capacitor/blob/main/ios/Capacitor/Capacitor/Plugins/CapacitorHttp.swift)
<img width="596" alt="image" src="https://user-images.githubusercontent.com/37995428/212825877-37e3f1bb-bf62-4c71-b76d-133a2f158710.png">

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by junxiong96** [comment]
can refer to below repository 
[Reference](https://github.com/junxiong96/capacitorhttp-delete-issue)
