### ISSUE TITLE
feat: Support plugins installed as npm optional dependecies.

### ISSUE THREAD

**Issue by GiviMAD** [ionic-team/capacitor#6221]
## Feature Request
I would like to be able to have the capacitor plugins installed in optionalDependecies.
### Description

Whenever I installed a capacitor plugin as optional dependency the cap sync command ignore this module as if it was not installed.
If I move this plugin to devDependencies or dependencies the sync command works correctly. 

### Platform(s)

Affects sync in all platforms.

### Preferred Solution

Capacitor sync command been able to detect plugins listed as an optional dependency only if it's installed (present on the node_modules folder).

### Alternatives

Capacitor sync command been able to detect plugins listed as an optional dependency and break the build if it's not installed.

### Additional Context

In my case I want this because I have a bunch of dependencies for electron/capacitor that I want to skip to download in the web version pipeline. It seems to work well for everything unless for the capacitor plugin I'm using, as it is invisible to the sync command when installed this way, therefore the sync do not add the required code for the plugin to work into the platforms folders (android/ios).

**Comment by jcesarmobile** [comment]
Capacitor will only search for plugins in `dependencies` and `devDependencies`.
If you want to use plugins that are not in `dependencies` and `devDependencies`, you can use the `includePlugins` [capacitor config file](https://capacitorjs.com/docs/config) configuration option that accepts an array of plugin ids to sync on `npx cap sync` command. So, if you use a .js or .ts config file you can create your own logic that picks the plugins you want, including optional dependency ones.
