### ISSUE TITLE
bug: (ios) where to enable codeSignIdentity/developmentTeam, previously set in cordova build.json

### ISSUE THREAD

**Issue by laurentperez** [ionic-team/capacitor#6226]
## Bug Report

Hello. Migrating our CI from cordova to capacitor. We're unable to set the signing identity (without having to load the Xcode UI, not possible from batched CI)

Under cordova it was working thanks to setting it in `build.json`. 

Under capacitor this file looks unused. capacitor.config.ts has no keys for iOS signin/team setups.

Example of build.json

```
{
    "ios": {
        "release": {
            "codeSignIdentity": "iPhone Developer",
            "developmentTeam": "xxxxxxxxxxxxxxxxxxxxxxxxx",
            "packageType": "app-store",
            "automaticProvisioning": true,
            "buildFlag": [
                "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
                "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
                "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\""
            ]
        }
    }
}
```

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)
ios

### Current Behavior

```
npx cap sync ios && npx cap build ios throws

error: Signing for "App" requires a development
        team. Select a development team in the Signing & Capabilities editor. (in target 'App' from project 'App')
```

### Expected Behavior

npx cap sync ios && npx cap build ios can read signing and provisioning settings from `build.json` file

### Code Reproduction

npx cap sync ios && npx cap build ios

### Other Technical Details

`pod --version` 1.11.3

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
