### ISSUE TITLE
bug: CapacitorHttp - already escaped URL fails since 4.6.2

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/capacitor#6230]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- iOS
- android maybe as well?

### Current Behavior

Some api i have to work with is expecting a json object escaped in a query param. So I'm sending a request like this:

```
/some-api?filter=%7B%22uuids%22%3A%5B%some-uuid%22%5D%7D
```

But with [this PR](https://github.com/ionic-team/capacitor/pull/6169) landed in 4.6.2 it escapes the already escaped url into:

```
some-api?filter=%257B%2522uuids%2522%253A%255B%252261… (link was too long to copy)
```

For me it looks like the already escaped url is escaped again which causes the result to be wrong.

### Expected Behavior

The url should not be escaped twice.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by EinfachHans** [comment]
Here is the reproduction:
https://github.com/EinfachHans/cap-http-encoding

Steps:
1. Checkout
2. Build project for iOS (android seems to work fine): `ionic capacitor build ios`
3. Run app, open console, click "send request"

The request is sent to url:
`https://api.publicapis.org/random?filter=%7B%22uuids%22%3A%5B%22some-uuid%22%5D%7D`

But the plugin sends it to: 
`https://api.publicapis.org/random?filter=%257B%2522uuids%2522%253A%255B%2522some-uuid%2522%255D%257D`

**Comment by stonewoodman** [comment]
I have the same problem, but not in the GET parameter, but in the path. 
Example Request:
```
CapacitorHttp.request({
  data: undefined,
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
  },
  method: 'GET',
  url: 'https://example.com/path/16SWc9PQ%3D/NGFjNzV'
});
```
on iOS is really called `https://example.com/path/16SWc9PQ%253D/NGFjNzV`
android works fine
