### ISSUE TITLE
bug: Capacitor 4 Plugin

### ISSUE THREAD

**Issue by developerSave** [ionic-team/capacitor#6243]
## Bug Report

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/android: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/cli: 4.6.2

### Platform(s)
Android

### Current Behavior
E/Capacitor/Console: File: https://my-url/js/6.js - Line 1 - Msg: Uncaught (in promise) Error: "Share" plugin is not implemented on android

### Expected Behavior
I need to share pdf files. When I run quasar dev and I open my android app in browser, sharing work correctly

### Code Reproduction

That's my repository:  https://github.com/developerSave/capacitor-bug

import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import com.getcapacitor.plugin.Share;

import java.util.ArrayList;

public class MainActivity extends BridgeActivity {

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // Initializes the Bridge
   this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
        // Additional plugins you've installed go here
        // Ex: add(TotallyAwesomePlugin.class);
        add(Share.class);
   }});
 }

}

### Other Technical Details

my package.json:

"dependencies": {
    "@byteowls/capacitor-filesharer": "^4.0.0",
    "@capacitor/android": "^4.6.2",
    "@capacitor/core": "^4.6.2",
    "@capacitor/filesystem": "^4.1.1",
    "@capacitor/share": "^4.1.0",
    "@quasar/cli": "^2.0.0",
    "@quasar/extras": "^1.15.9",
    "axios": "^0.21.1",
    "capacitor-blob-writer": "^1.1.3",
    "core-js": "^3.6.5",
    "file-saver": "^2.0.5",
    "quasar": "^1.22.5",
    "vue-i18n": "^8.0.0",
    "vuex-persist": "^3.1.3"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.13.14",
    "@capacitor/cli": "^4.6.2",
    "@quasar/app": "^2.0.0",
    "eslint": "^8.10.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-vue": "^9.0.0",
    "eslint-webpack-plugin": "^2.0.0",
    "prettier": "^2.5.1",
    "workbox-webpack-plugin": "^5.1.4"
  },
  "browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "engines": {
    "node": ">= 10.18.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  } 

`npm --version` output:  8.11.0

`node --version` output:  v16.16.0

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by developerSave** [comment]
> This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.
> 
> Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
> 
> Thanks! Ionitron 💙

Hi!
That's my repository: https://github.com/developerSave/capacitor-bug


unfortunately, it's really incomplete

**Comment by developerSave** [comment]
project in repository uploaded

**Comment by jcesarmobile** [comment]
You are using Capacitor 2
https://github.com/developerSave/capacitor-bug/blob/main/quasar-project/src-capacitor/package.json#L8

For using version 4 of Capacitor plugins you have to use Capacitor 4

**Comment by developerSave** [comment]
> @capacitor/core: 4.6.2
> @capacitor/cli: 4.6.2

Hi! 
I've different versions between package.json and package-lock.json and I don't know why

**Comment by developerSave** [comment]
> package-lock.json

ok I actually checked better and I've all package-lock.json not upgraded and package.json in src-capacitor folder not upgraded. I don't know why, because I upgraded them using npm install

**Comment by developerSave** [comment]
I upgraded my project to Capacitor 4, but it still doesn't work

**Comment by nagab198** [comment]
I have same issue when first time app working fine but app reaching plugin not implemented in Android error occurred

**Comment by developerSave** [comment]
> I have same issue when first time app working fine but app reaching plugin not implemented in Android error occurred


I solved using write file + open file, because I can't save file in "Downloads" directory
