### ISSUE TITLE
feat: target & public-host via environment variables

### ISSUE THREAD

**Issue by staff0rd** [ionic-team/capacitor#6256]
### Description
`ionic capacitor run android -l --external` prompts for `target` in all cases and for `public-host` when more than one network interface is detected. These prompts can be avoided by passing `--target` and `--public-host` but the actual values differ among developers on a project shared a cross a team.

### Platform(s)
Windows, macOS, *nix

### Preferred Solution
I'd like it to be possible to set some environment variable, for example `CAPACITOR_ANDROID_TARGET`, `CAPACITOR_PUBLIC_HOST` or similar such that whenever i call `ionic capacitor run android` it will set these values from the environment, rather than from the argument.

### Alternatives
I attempted to do it myself with a combo of `dotenv` & `cross-var` but was unsuccessful. Ultimately my desire is to have something like `"whatever": "ionic capacitor run android -l --external"` as a `package.json` `script` and have the `public-host` and `target` picked up from (whatever) environment

### Additional Context
If there's appetite for such a change, i can potentially implement it myself upon some direction

**Comment by jcesarmobile** [comment]
Ionic commands are managed by Ionic CLI, not Capacitor CLI, so you should request the feature in [Ionic CLI repository](https://github.com/ionic-team/ionic-cli/issues)
Maybe the target part could be done in Capacitor CLI too, but the `public-host` is Ionic CLI specific.
