### ISSUE TITLE
feat: allow applications to set a higher min SDK version number

### ISSUE THREAD

**Issue by adnbrownie** [ionic-team/capacitor#6260]
### Description

Currently,`android lint` will complain if you set the Android minSdkVersion to more recent API versions (like e.g. API version 29 or 30). While Capacitor supports older versions just fine, there might be other reasons for an application to choose to support only newer versions of Android.

### Platform(s)

Android

### Preferred Solution

Disable the linting rule for obsolete SDK checks altogether using disable 'ObsoleteSdkInt' in https://github.com/ionic-team/capacitor/blob/main/android/capacitor/build.gradle#L58

### Alternatives

Alternatively there'd be the option to add issues stemming from the SDK version checks to the lint-baseline.xml file. This would mean that if new SDK version checks are introduced at a later point in time, they need to be added to the lint-baseline.xml file as well.

### Additional Context
    
1. https://developer.android.com/studio/write/lint#pref
2. https://developer.android.com/studio/write/lint#snapshot

### To Reproduce

1. Create a new project with @ionic/cli: `npx @ionic/cli start myTestApp tabs`
2. Go into the created folder (`/myTestApp`), add the Android resources: `npx @ionic/cli capacitor add android`
3. Configure the Android SDK
4. Change the minSdkVersion in `variables.gradle` to e.g. 29
5. run `gw lint`

output (extract):

```
myTestApp/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/Bridge.java:324: Error: Unnecessary; SDK_INT is always >= 30 [ObsoleteSdkInt]
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The full lint text report is located at:
```

Repository with reproduction is at https://github.com/adnbrownie/ionic_issue_6260_reproduction

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by adnbrownie** [comment]
Repository with reproduction is at https://github.com/adnbrownie/ionic_issue_6260_reproduction

**Comment by tobiloeb** [comment]
I have the same problem. We are using a library which needs a minSdk version for at least 23.
