### ISSUE TITLE
bug: flavor and scheme flags not working with cap build

### ISSUE THREAD

**Issue by mibzman** [ionic-team/capacitor#6269]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
```

### Platform(s)

iOS, Android

### Current Behavior

`npx cap build --scheme flavor ios`
Output:
```
✖ Building xArchive - failed!
[error] Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace flavor.xcworkspace -scheme
        chopstop -destination generic/platform=iOS -archivePath flavor.xcarchive archive
        
        User defaults from command line:
        IDEArchivePathOverride =
        <path>/ios/App/flavor.xcarchive
        IDEPackageSupportUseBuiltinSCM = YES
        
        xcodebuild: error: 'flavor.xcworkspace' does not exist.
```

`npx cap build --flavor flavor android`
result:
`error: unknown option '--flavor'`

### Expected Behavior

If a scheme or flavor works with `cap run`, it should also produce the same built output when run with `cap build`.  Or be noted in the [flavor/scheme documentation](https://capacitorjs.com/docs/guides/environment-specific-configurations#setup-a-new-ios-scheme)

### Code Reproduction

https://github.com/mibzman/cap-flavor-example

### Other Technical Details

`npm --version` output:
8.11.0
`node --version` output:
16.16.0
`pod --version` output (iOS issues only):
1.8.4

**Comment by jcesarmobile** [comment]
scheme actually works on iOS, you might not have a scheme created on your project that matches the name

flavor is not implemented for Android on build command

**Comment by mibzman** [comment]
I have reproduced my issue with iOS schemes in [this repo](https://github.com/mibzman/cap-flavor-example).  If you run `npx cap build ios --scheme "App QA"` you should get this output:

```
✖ Building xArchive - failed!
[error] Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace
        "App QA.xcworkspace" -scheme "App QA" -destination generic/platform=iOS
        -archivePath "App QA.xcarchive" archive
        
        User defaults from command line:
        IDEArchivePathOverride =
        .../cap-flavor-example/ios/App/App QA.xcarchive
        IDEPackageSupportUseBuiltinSCM = YES
        
        xcodebuild: error: 'App QA.xcworkspace' does not exist.
```

I have followed the [scheme documentation](https://capacitorjs.com/docs/guides/environment-specific-configurations#setup-a-new-ios-scheme) exactly.  I get the same result using `capacitor.config.json` to select the scheme.

Thank you for the update on android flavors.  For anyone else with this issue, I'm currently building directly with `./gradlew` to get a flavor bundle.

**Comment by jcesarmobile** [comment]
thanks, I can reproduce the issue on iOS now
can you create a new issue about it? 
since the android problem is that flavor is not implemented, but on iOS scheme is implemented but presents some problems, so they are different issues
