### ISSUE TITLE
bug: ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

### ISSUE THREAD

**Issue by RSKAntec** [ionic-team/capacitor#6270]
### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] Android looking great! 👌
[error] Xcode is not installed

```

### Platform(s)

-using a terminal through CLion (where the project is open)

### Current Behavior

If I try `npx cap run android` then I get the following output:

√ Copying web assets from public to android\app\src\main\assets\public in 35.38ms
√ Creating capacitor.config.json in android\app\src\main\assets in 4.24ms
[info] Inlining sourcemaps
√ copy android in 70.52ms
√ Updating Android plugins in 3.17ms
√ update android in 108.49ms
[error] native-run failed with error

        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors

### Expected Behavior

Since Ionic says on https://github.com/ionic-team/native-run/wiki/Android-Errors that it supports up to Android SDK 33, I would expect it to work. All the previous steps in https://capacitorjs.com/docs/ worked fine.

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v18.12.1

**Comment by jcesarmobile** [comment]
33 is already supported, 33x is not, not sure what that is, couldn't find anything about it

see https://github.com/ionic-team/native-run/issues/286

**Comment by tomsnj** [comment]
Had same problem and tried to back off to v32.  Still getting same error so backoff must not be correct.  Any further info?

**Comment by tomsnj** [comment]
Thanks. I downgraded my platform to Android 12 and then all was good. Thanks.
