### ISSUE TITLE
bug: CapacitorHttp XMLHttpRequest (Angular HttpClient) interceptor doesn't pass headers correctly

### ISSUE THREAD

**Issue by dennisameling** [ionic-team/capacitor#6274]
### Capacitor Version

```
% npx cap doctor  
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android and iOS

### Current Behavior

When using Angular's HttpClient in combination with Capacitor's `CapacitorHttp` [intercepting enabled](https://capacitorjs.com/docs/apis/http), headers are sent incorrectly to the server.

Here's what it looks like on Android (did [remote debugging](https://ionicframework.com/docs/troubleshooting/debugging#android-and-chrome) to get some more details):

<img width="1904" alt="Screenshot 2023-02-05 at 11 32 27" src="https://user-images.githubusercontent.com/17739158/216814071-c373f2d4-08b8-41b5-a448-f139482444fe.png">

**Note that the `headers` are a JSON-encoded string when `CapacitorHttp` is intercepting `XMLHttpRequest`. That doesn't seem right!**

And here's what it looks like on iOS:

<img width="200" src="https://user-images.githubusercontent.com/17739158/216814481-710bb194-b7aa-4337-8daa-21217b349b6f.PNG" alt="IMG_0064" />

### Expected Behavior

I expect Angular's HttpClient to work correctly in combination with `CapacitorHttp`'s `XMLHttpRequest` interceptor.

### Code Reproduction

Here's the full codebase of my screenshots above: https://github.com/dennisameling/capacitor-http-bug

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v16.18.1

`pod --version` output (iOS issues only): 1.11.2

**Comment by zakuru** [comment]
similar issue when upgraded to 4.6.3 - had to rollback to 4.6.2

**Comment by matudelatower** [comment]
Same issue here, apparently overwrites all request even `@angular/common/http`, and interceptors doesnt work.

**Comment by zakuru** [comment]
@jcesarmobile  can you please help look into it ?

**Comment by jonesdhtx** [comment]
Having similar issue using `fetch` directly from within our capacitor project, request headers are no longer getting sent properly. Seems like this change would be the culprit: [https://github.com/ionic-team/capacitor/pull/6251/files](https://github.com/ionic-team/capacitor/pull/6251/files#diff-8afda3e2bce7fb91a14a66d96d63a89f112b852cf39223e6f820a1575cbdafebL503)

**Comment by brandonaaron** [comment]
I'm also pointing the finger at PR #6251 for breaking http calls. App works fine in 4.6.2 but server gets bad/missing info on 4.6.3.

**Comment by muuvmuuv** [comment]
Since its Native → Browser it could be due to [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers). Can you try adding that to your server and select the headers you want to expose to the client?

**Comment by davy-ikv** [comment]
This change breaks passing headers in iOS

https://github.com/ionic-team/capacitor/commit/028c556a50b41ee99fe8f4f1aa2f42d3fd57f92d#diff-73da2144bc5fefb384b6fc1501a8efbabac7cfdf2faa411b68cdd113f53d884dL430-R432

JSON.stringify headers makes headers become a String, but in native part of iOS, it expect headers is a hash table ([String: String])

**Comment by jcesarmobile** [comment]
Resolved on https://github.com/ionic-team/capacitor/pull/6303
