### ISSUE TITLE
device info not working under ubuntu

### ISSUE THREAD

**Issue by fssrepository** [ionic-team/capacitor#628]
device.js 

```
if (_ua.indexOf('Android') !== -1) {
} else {
throws exception on replace!!!
}
```
I personally think that the capacitor code needs to check a little bit thoroughly whether a variable is undefined or not

**Comment by danielsimon1** [comment]
I don't get how this is related with Capacitor.
Can you show us more code, including where you actually use a Capacitor plugin?

**Comment by jcesarmobile** [comment]
Can you test with latest version? We did some improvements in the user agent parsing code and it should work now.
If still doesn't work, can you tell us in which browser did you try?

**Comment by jcesarmobile** [comment]
Seem to work fine now, please reopen if you still face the problem in latest beta, but please, provide the requested information
