### ISSUE TITLE
bug: Capacitor does not initialised when server.url uses ssl on Android

### ISSUE THREAD

**Issue by adrigardi90** [ionic-team/capacitor#6291]
### Capacitor Version

```
4.6.2
```

### Platform(s)

Android

### Current Behavior

Given a project with `appendUserAgent` and `server.url` pointing to a https link:
```
  appendUserAgent: `test`,
  server: {
    url: "https://xxxx",
    cleartext: true,
    androidScheme: "https",
    allowNavigation: [`*`],
  },
```
Capacitor does not initialised, hence it's not available in the global window object:

<img width="598" alt="android" src="https://user-images.githubusercontent.com/22976673/218172152-1d936912-a3f7-49e7-8e79-485f83d608de.png">

### Expected Behavior

Capacitor should get initialised and injected in the global window once the link gets rendered as it happens on **iOS**:
<img width="853" alt="ios" src="https://user-images.githubusercontent.com/22976673/218170518-c1715cbc-1680-4f07-9580-0d4519177e53.png">

### Code Reproduction

Check [here](https://github.com/adrigardi90/capacitor-example) the steps to reproduce it. 

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v12.20.0

### Additional Context

Worth to mention I explicitly need `appendUserAgent` property. In some cases it looks it works pointing to a different https link. But in some others, `overrideUserAgent` is the only way to make it work. So depending on the link and the `userAgent` value Capacitor gets available or not. 

I check related issues: [#3707](https://github.com/ionic-team/capacitor/issues/3707), #[7234](https://github.com/quasarframework/quasar/issues/7264), [#5354](https://github.com/ionic-team/capacitor/issues/5254) but I don't spot any similarity. 

In this case I don't see any log related to a SSL issue nor to a problem on the Bridge at some point. In fact, I always see the plugins get registered without errors and the app gets started:
```
02-10 19:12:47.968  7838  7838 D Capacitor: Starting BridgeActivity
02-10 19:12:47.978  7838  7838 D Capacitor: Registering plugin: WebView
02-10 19:12:47.983  7838  7838 D Capacitor: Registering plugin: Camera
02-10 19:12:47.986  7838  7838 D Capacitor: Registering plugin: Device
02-10 19:12:47.989  7838  7838 D Capacitor: Registering plugin: Filesystem
02-10 19:12:47.993  7838  7838 D Capacitor: Registering plugin: SplashScreen
02-10 19:12:48.043  7838  7838 W Capacitor: Unable to read file at path public/plugins
02-10 19:12:48.045  7838  7838 D Capacitor: Loading app at https://xxxxx
02-10 19:12:48.050  7838  7838 E Capacitor: System WebView is not supported
02-10 19:12:48.054  7838  7838 D Capacitor: App started
```
_("System WebView is not supported" is a debug log when the Android version is not the minimum one, but it does not prevent the app to get started. Other links with the same log work)_

However, Capacitor is not available once the link is rendered, in contrast to iOS where it works seamlessly. 

I tried with different Android devices on the emulator and BrowserStack but I always get the same issue.

**Comment by adrigardi90** [comment]
Any update on this please? It's a blocker at the moment

**Comment by jcesarmobile** [comment]
the sample app you provided requires user/password that are not provided on the steps to reproduce, can you provide them?

**Comment by adrigardi90** [comment]
Changed, it should work now without credentials

**Comment by jcesarmobile** [comment]
the provided url doesn't return anything, Capacitor only injects itself in html pages with a head tag 
it's mentioned here 
https://capacitorjs.com/docs/getting-started#add-capacitor-to-your-web-app
