### ISSUE TITLE
bug: CapacitorHttp plugin does not fully support content-types other than JSON.

### ISSUE THREAD

**Issue by dv-alan** [ionic-team/capacitor#6299]
### Capacitor Version
@capacitor/cli: 4.6.3    
@capacitor/core: 4.6.3   
@capacitor/android: 4.6.3
@capacitor/ios: 4.6.3    

### Platform(s)
Android
iOS

### Current Behavior
As of commit #6165 the resulting change created an incosistnecy in how data from the CapacitorHttp module is sent between iOS and Android. Where iOS is sending data correctly as a form with the proper content type, the Android counterpart is just performing a .ToString() on the data object passed by the developer. This removes any support for posting forms, especially forms with multi-part/form-data on an Android platform. And can confirm this when comparing the Android variant with the iOS variant against a .NET Core Web API.

For context, compare the methods setting the request data in both cases. [iOS's set data](https://github.com/ionic-team/capacitor/blob/main/ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift#L96) and [Android's set data](https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java#L172). Further more, referring to the former capacitor-community/http plugin, most of which I assume is just adapted code, used to work perfectly in a production environment and handled all of the necessary request content-types. Kindly refer to this [code snippet](https://github.com/capacitor-community/http/blob/main/android/src/main/java/com/getcapacitor/plugin/http/CapacitorHttpUrlConnection.java#L171) as it's a tried and tested scenario.

### Expected Behavior
1. The resulting request needs to be identitcal between iOS and Android. If in both scenarios both content types are forms, then this should be preserved.  
2. Android should be able to handle all types of content-types correctly, not json only.

**Comment by koraxos** [comment]
Any update on this ?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
