### ISSUE TITLE
bug: `appUrlOpen` never triggers or even listener is not added

### ISSUE THREAD

**Issue by chomamateusz** [ionic-team/capacitor#6300]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

Deep links were configured accordingly to the docs found here: https://capacitorjs.com/docs/guides/deep-links and they are working in both platforms Android and iOS (app is opening correctly instead of a browser). Then, after the app is open, we should grab the URL that was open through the `appURLOpen` capacitor App plugin event. On Android, it works like a charm. On iOS app is opening, but event seems never emitted, event listener seems never triggered.

### Expected Behavior

Event `appURLOpen` should trigger on Android and on iOS as well.

### Other Technical Details

App is using React (v16.13.1) with create-react-app. App is simply a wrapper over the web version. On web version, we do not need deep links, of course. Here in the app, the deep links are needed to provide a possibility to log in via FB/Google and come back after OAuth callback to app, not to the browser on the phone.

`npm --version` output: 8.19.2

`node --version` output: v18.12.1

`pod --version` output (iOS issues only): 1.11.3

### Code Reproduction

Sadly, I cannot share the full code example as it's not a public code. I will try to make a clean React app tomorrow with capacitor added and post here as reproduction example. For now, I am able to describe the process very precisely with code samples and logs provided. Please check it out below:

I'm using a custom-made component named `MobileNativeEventsListener` that is placed in the root of main app router (react-router). 

For debugging purposes, I've added lots of `console.debugs`.

To get the error, I'm opening the app, and right away as the `MobileNativeEventsListener` is mounted first logs should appear. Then I'm clicking on Google login that redirects me to a browser where I log in, then the redirect from my server takes me back to the app. The native part of the code gets the URL with the Google verification code that is needed to run Google OAuth callback in the app. But then the even listener created in `MobileNativeEventsListener` do not trigger and nothing happens. On Android, this event triggers here, and we are rerouted to the right path where callback is called, and the user is logged in.

 So on iOS output form the logs are:

```javascript
[Debug] [useEffect] component mounted – {history: Object, location: Location} (main.76a0f6b3.chunk.js, line 1)
[Debug] [pause] App paused (main.76a0f6b3.chunk.js, line 1)
[Debug] [appStateChange] App state changed to NOT ACTIVE (main.76a0f6b3.chunk.js, line 1)
[Debug] [resume] App resumed (main.76a0f6b3.chunk.js, line 1)
[Debug] [appStateChange] App state changed to ACTIVE (main.76a0f6b3.chunk.js, line 1)
```

![Screenshot 2023-02-15 at 16 16 47](https://user-images.githubusercontent.com/20150525/219070305-5652066b-3f78-4ca8-9200-5a838035a1f9.png)

Here is the code:

```typescript
import React from 'react'

import { useHistory } from 'react-router-dom'

import type { URLOpenListenerEvent } from '@capacitor/app'
import { PluginResultData } from '@capacitor/core'
import { App } from '@capacitor/app'

const createHandleAppUrlOpen =  ({ history, location }: { history: ReturnType<typeof useHistory>, location: typeof window.location }) => (data: PluginResultData) => {
  console.debug('[appUrlOpen] App opened with URL:', data)

  const checkDataForUrl = (data: PluginResultData): data is URLOpenListenerEvent => data.url !== undefined

  if(!checkDataForUrl(data)) {
    console.debug('[appUrlOpen] Data does not includes url property! Listener not triggered.')
    return
  }
  const event = data

  const hostname = location.hostname

  if (!hostname) return
  if (!event.url.includes(hostname)) return

  const slug = event.url.split(hostname).pop()

  if (!slug) return

  history.push(slug)
}

const addCapacitorListeners = ({ history, location }: { history: ReturnType<typeof useHistory>, location: typeof window.location }) => {
  const handleAppUrlOpen = createHandleAppUrlOpen({ history, location })

  App.addListener('appUrlOpen', handleAppUrlOpen)

  App.addListener('backButton', () => {
    console.debug('[backButton] App back button pressed')
  })
  App.addListener('pause', () => {
    console.debug('[pause] App paused')
  })
  App.addListener('resume', () => {
    console.debug('[resume] App resumed')
  })
  App.addListener('appStateChange', ({ isActive }) => {
    console.debug(`[appStateChange] App state changed to ${isActive ? 'ACTIVE' : 'NOT ACTIVE'}`)
  })
  App.addListener('appRestoredResult', data => {
    console.debug('[appRestoredResult] Restored state:', data)
  })
}

const removedCapacitorListeners = () => {
  App.removeAllListeners()
}

const MobileNativeEventsListener = () => {
  const history = useHistory()
  const location = window.location
  
  React.useEffect(() => {
    console.debug('[useEffect] component mounted', { history, location })

    addCapacitorListeners({ history, location })
    
    return () => {
      console.debug('[useEffect] component UNmounted', { history, location })

      removedCapacitorListeners()
    }
  }, [history, location])

  return null
}

export default MobileNativeEventsListener
```

I've also tried to investigate why the event is not triggered and by putting breakpoints in Swift native code in `handleUniversalLinks` method which is called by iOS to handle involving deep link. These are the results:

The handle is called and payload have right URL inside that should open the app then reroute to Google callback page with the token.

![Screenshot 2023-02-15 at 16 27 44](https://user-images.githubusercontent.com/20150525/219079107-dbc91ac1-7c7c-4c46-ab94-f76996ec15e0.png)

But when follow the code execution, we will find that next is called function named `notifyLisetners` and it seems like there were no listeners for that event! Despite the fact that our JS code registered one!

![Screenshot 2023-02-15 at 16 29 01](https://user-images.githubusercontent.com/20150525/219079216-fb0de5b8-a9f1-46da-98d7-7dec89786f6f.png)

## Additional context

Here I'm pasting the video from iOS and from the same app build on Android to give you some context to what I'm doing ang what it should look like, as on Android it's simply working.

Android:

https://user-images.githubusercontent.com/20150525/219071789-e5d9760f-30e7-4ee8-a151-4f10bccff0a7.mp4

iOS:

https://user-images.githubusercontent.com/20150525/219070867-1054c7a4-4349-476d-8ee2-cf95fb37ec63.mp4

**Comment by antijingoist** [comment]
Hi, 

So this is what I'm seeing by deeplinking using URL types on iOS, in js:

I setup a URL type in my target app -> info:
![image](https://user-images.githubusercontent.com/663100/219394268-a0b0445c-88bb-49da-90df-425c5a35bde8.png)

Then I added a listener like you did. This only logs to console:
 
```
Capacitor.Plugins.App.addListener('appUrlOpen', data => {

      console.log('App opened with URL:', data);

    });
```

When I click a link on iOS that uses my url type `hai://`, in this case: `hai://does/this/work` , I get the following in the console: `[Log] App opened with URL: – {url: "hai://does/this/work", iosSourceApplication: "", iosOpenInPlace: ""} (app.js, line 10)`


Is the handler in your setup named "handleAppUrlOpen"?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
