### ISSUE TITLE
bug: Capacitor Cookies - `document.cookie` not behaving as expected on iOS

### ISSUE THREAD

**Issue by crhayes** [ionic-team/capacitor#6308]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/ios: 4.6.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS

#### How it Manifests
I have an Ionic React application using [Auth0 React](https://github.com/auth0/auth0-react). I have successfully configured it so that user sessions persist when the user closes and relaunches the app. However, this is broken on Native iOS when Capacitor Cookies is enabled; after closing and relaunching the app the session is lost. Disabling Capacitor Cookies restores the correct behaviour.

Config:
```ts
// capacitor.config.ts
const config: CapacitorConfig = {
  ...,
  plugins: {
    CapacitorCookies: {
      enabled: true,
    },
  },
};
```
#### Technical Details
After some investigation I've uncovered an issue with the iOS monkeypatch of `document.cookie` with regards to how multiple cookies are joined into a single string. Specifically, multiple cookies are separated by `;` rather than `; `:

**Native iOS with Capacitor Cookies disabled**
![image](https://user-images.githubusercontent.com/727536/219958026-6dc6b14c-97e8-49bb-86f5-6a158541a1bd.png)

**Native iOS with Capacitor Cookies enabled**
![image](https://user-images.githubusercontent.com/727536/219958042-367a0116-edac-4bcf-bf4a-a05ad304c924.png)

**Native Android with Capacitor Cookies enabled/disabled**
<img width="913" alt="image" src="https://user-images.githubusercontent.com/727536/219959534-773c25ae-bb7c-4527-9685-2a51fc026920.png">

Note that Native Android with Capacitor Cookies both enabled and disabled, as well as Native iOS with Capacitor Cookies disabled, all separate cookies with a semicolon and space. However, when Capacitor Cookies is enabled, Native iOS separates cookies with only a semicolon. This results in critical errors parsing cookies.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#read_all_cookies_accessible_from_this_location):

> [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#section-5.4) mandates a single space after each semicolon, but some user agents may not abide by this.

Furthermore, popular libraries expect `; ` when parsing the `document.cookie` string:
- [js-cookie splits on `; `](https://github.com/js-cookie/js-cookie/blob/main/src/api.mjs#L57)
- [es-cookie splits on `; `](https://github.com/theodorejb/es-cookie/blob/master/src/es-cookie.ts#L45)

The relevant code in the iOS moneypatch appears to be [this line](https://github.com/ionic-team/capacitor/blob/57f8b39d7f4c5ee0e5e5cb316913e9450a81d22b/ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift#L91).

The Auth0 client library leverages `es-cookie` which is why this issue manifests for me. 

### Expected Behavior

The native iOS `document.cookie` (get) functionality should return cookies separated by `; ` (semicolon+space).

### Code Reproduction

No _(If would be helpful in this case let me know and I will create one)_

### Other Technical Details

`npm --version` output: `8.5.0`

`node --version` output: `v16.14.2`

`pod --version` output (iOS issues only):
```
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
1.11.3
```

### Additional Context

N/A

**Comment by OskarLebuda** [comment]
@crhayes  I've reported same bug a you. 
https://github.com/ionic-team/capacitor/issues/6311

The problem is right here https://github.com/ionic-team/capacitor/blob/main/ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift#L91

The CookieManager joined cookies without the space

**Comment by crhayes** [comment]
> @crhayes I've reported same bug as you. #6311

@OskarLebuda Hopefully this issue is addressed quickly! I suggest closing your issue so we don't have duplicates. You can post any additional details or proposals in this thread.

**Comment by OskarLebuda** [comment]
I've closed my report. My proposal is to add to the CapacitorConfig:
```typescript
plugins: {
    CapacitorCookies: {
      enabled: true,
      separator: '; ',
    },
  },
```

to manage this your self. Or fix it globaly. But some of reason this works like now.

**Comment by efuturetoday** [comment]
I have the same issue with the delimeter and the whitespace. Another quick solution would be to also enable to override the document.cookie property - so everyone can modify the getter and setter of the cookie property. Currently that is not possible and I opened a issue for that. The original unpatched document.cookie property can be overwritten and will be overwritten by capacitor cookie plugin but the new property can not be overwriten as the original one.
https://github.com/ionic-team/capacitor/issues/6275
