### ISSUE TITLE
File Inputs not working inside Capacitor apps on Android

### ISSUE THREAD

**Issue by danielsimon1** [ionic-team/capacitor#631]
I'm trying to implement a file input inside my Capacitor app. On iOS everything is working as expected, but on all tested Android devices just nothing happens when the user clicks on the file input element. I tried a simulator running a Google Pixel 2 and a Huawai P9 Plus. If the app is built with Cordova, the file input works again.

**Steps to reproduce:**
1. Follow the steps to create a project for a Capacitor app (I created an Ionic project with the sidemenu template)
2. Add the following snippet somewhere in your HTML code: `<input type="file">`
3. Build the app for Android

**Expected behavior:**
When the user clicks on a file input element inside a Capacitor app, some kind of dialog should pop up to select a file on the device.

**Comment by wtrocki** [comment]
@danielsimon1 Hi, This is HTML5 component that requires some special handling from the webview. 
This could be the workaround for the moment:
https://capacitor.ionicframework.com/docs/apis/filesystem#method-readFile-0
