### ISSUE TITLE
bug: Capacitor 4 content does not fill the screen

### ISSUE THREAD

**Issue by suleymanbariseser** [ionic-team/capacitor#6310]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)

Android

### Current Behavior

After upgrading capacitor from 3 to 4, app's layout started to behave weirdly. It does not fill screen on android app, while it fills the screen on ios application.

### Additional Context

<img width="233" alt="Screenshot 2023-02-20 at 14 18 00" src="https://user-images.githubusercontent.com/50797736/220091050-01f5bc78-1486-47a5-8598-e336735fd7ba.png">

**Comment by crhayes** [comment]
@suleymanbariseser This looks like an issue that should have a repro attached, as well as more details regarding Android SDK version, device, etc.

With the details provided in this issue it would be next to impossible to debug and find the root issue.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
