### ISSUE TITLE
Keyboard hide is not dismissing the keyboard (iOS)

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/capacitor#632]
When calling `Keyboard.hide()` in our application you can see that the method was successfully called:
```
⚡️  WebView loaded
⚡️  To Native ->  App addListener 78662995
⚡️  To Native ->  Keyboard hide 78662996
```

But the keyboard remains active on the view. This is on an iPad, when opening a login form the input is auto focusing. 

This behavior is fine (autofocus), but I need to be able to dynamically dismiss the keyboard, because when displaying a modal over the view, the keyboard prompts through the modal and typing shows the iOS input cursor move across the view. 

-- 

I've tried reassigning the first responder, but it's completely ignored by the webview.

**Comment by jcesarmobile** [comment]
In which iOS version did you see it?

**Comment by sean-perkins** [comment]
@jcesarmobile the device is on iOS 11.3.1 (iPad Air 2)

**Comment by sean118** [comment]
`Keyboard.hide()` is now throwing an exception because of a thread issue.

> UI API called on a background thread: -[UIView endEditing:]

Executing `[self.webView endEditing:YES]`_(in Keyboard.m)_ on the main thread fixes it:

```
dispatch_async(dispatch_get_main_queue(), ^{
	[self.webView endEditing:YES];
});
```

**Comment by jcesarmobile** [comment]
Fixed by https://github.com/ionic-team/capacitor/pull/1158 and https://github.com/ionic-team/capacitor/pull/1203
