### ISSUE TITLE
I want to detect mobile location is on or off

### ISSUE THREAD

**Issue by TechNerdsUzi** [ionic-team/capacitor#634]
when i install cordova.plugins.diagnostic plugin in my capacitor app i got this error

Android dependency 'com.android.support:support-v4' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution

plzz tell me how i fix this.

**Comment by danielsimon1** [comment]
I had a similar issue and fixed it by adding the following to the `build.gradle` file inside the `android` folder.

```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}
```

**Comment by jcesarmobile** [comment]
I think best way of handling this is to add the dependency to the app's build.gradle with the version you want to use. (i.e. `implementation 'com.android.support:support-v4:27.1.1'`). That should get rid of this problem.

If not, adding what danielsmin1 said will force all support libraries to use 27.1.1 version.
