### ISSUE TITLE
On app reboot `localStorage` is lost

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#636]
First of all, thanks for all your efforts in making PWA great again!

I'm not sure is it a bug or my misunderstanding.

Our app API writing some data to `localStorage`, and relies on it during auth. After building the app with Capacitor for Android, everything worked fine. However, if the app was forcefully closed (as shut down process), the next time app turned out to launch with clear `localStorage`.

That's happens everytime the app is shutted down.

My understanding was that `localStorage` should persist until Android or user _somtimes_ decides to clear it. However, in my case, it happens every time.

I assume that might happen because `localStorage` is destroyed with Chrome's webview when the app is closed, or maybe each time app starts it gets a different domain name, which will also mean a new, clear `localStorage`.

Is it correct behavior?

I know that easy solution is Capacitor's `Storage`, however, we can't use it for 3rd-party tools, like AWS Amplify, which using directly `localStorage` methods. I could override `localStorage` methods with Capacitor's `Storage`, but that won't work because Capacitor's one are Promise-based.

Anyway, it's still solvable by watching changes in `localStorage` and gradually pushing them to the `Storage`, and on hard shut down restore `localStorage` state from `Storage`. Though, I wanted to ensure that it is correct approach and that wiped `localStorage` on every shut down is expected behavior.

**Comment by pwespi** [comment]
I'm seeing the same issue with IndexedDB. The reason is
```
this.authority = UUID.randomUUID().toString() + "" + knownUnusedAuthority;
```
in WebViewLocalServer.java. Because of that line the app gets a new security origin and thus a new database on each restart. Setting the UUID manually to something fixed works as a workaround for me.

**Comment by ArmorDarks** [comment]
Oh, I see. So that's not intended behavior.
