### ISSUE TITLE
bug: whitescreen on android emulator with SDK <= 28

### ISSUE THREAD

**Issue by htmoia** [ionic-team/capacitor#6360]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/core: 4.7.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

App shows whitescreen on android emulators SDK <= 28

### Expected Behavior

App should start and show tabs/ homescreen

### Code Reproduction

```
ionic start android-support tabs --type=angular --capacitor 
cd android-support 
ionic capacitor run android
```
Choose android emulator with SDK <= 28

### Other Technical Details

`npm --version` output: 8.3.1

`node --version` output: v16.14.0

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Angular 15 doesn't support old Chrome versions that the emulators use by default.
Use Angular 14 or test on real devices.

**Comment by htmoia** [comment]
Thanks for your reply. Downgrading to angular 14.2 as well as changing compile target to ES5 did not help. Still whitescreen on those emulators. Anything that I could have missed? Or is it adviced to only use latest emulators/SDKs for development?
