### ISSUE TITLE
bug: Icons & html, css elements are not showing.

### ISSUE THREAD

**Issue by ashin-kk** [ionic-team/capacitor#6365]
### Capacitor Version
```
Latest Dependencies:       
  @capacitor/cli: 4.7.0    
  @capacitor/core: 4.7.0   
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0    

Installed Dependencies:    
  @capacitor/cli: 4.7.0    
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0    
  @capacitor/core: 4.7.0   

[success] Android looking great! 👌
```

### Platform(s)
Android. Created a Nuxt.js project with the following packages. 
```
{
  "name": "user",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@capacitor/android": "^4.7.0",
    "@capacitor/core": "^4.7.0",
    "@capacitor/ios": "^4.7.0",
    "@nuxtjs/axios": "^5.13.6",
    "core-js": "^3.19.3",
    "nuxt": "^2.15.8",
    "vue": "^2.6.14",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "vuetify": "^2.6.1",
    "webpack": "^4.46.0"
  },
  "devDependencies": {
    "@capacitor/cli": "^4.7.0",
    "@nuxtjs/vuetify": "^1.12.3"
  }
}

```

### Current Behavior
![image](https://user-images.githubusercontent.com/40032009/222884869-1be2a8a1-18e7-4b12-9b4d-d387feb46aaa.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/40032009/222884857-4205c436-4eba-4266-bf78-45778416c845.png)

### Other Technical Details

`npm --version` output: 9.4.2

`node --version` output: v16.14.0

`pod --version` output (iOS issues only): - 

### Additional Info
2 months ago we did not have these problems when we create another app.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ashin-kk** [comment]
Hi @Ionitron 

sorry for the same. 
please find the code reproduction:
https://github.com/ashin-kk/bug-capacitor

**Comment by ashin-kk** [comment]
I followed the same instructions available on the official website to add the capacitor to an existing project. Then used the following to run the app.
```
npx cap sync
npm run build
npm run generate
npx cap copy
npx cap open android
```

Run the app with a Physical device. Didn't try using an emulator.
1) Xiaomi Mi A1  ` Found the same issue `
    Android 9.0 
    API 28
  
2) Xiaomi Redmi 220233L2I   ` Works fine `
    Android 11.0 
    API 30
  

Also tried a fresh install. But still, it shows the same problem in **`1st device`**.

### 1st Device
![image](https://user-images.githubusercontent.com/40032009/223295628-b85dbe49-c0a3-4598-a20b-08411847b1de.png)

### 2nd Device
![image](https://user-images.githubusercontent.com/40032009/223296749-12286049-fd51-4ad0-9824-f6be4a9d4f65.png)

**Comment by jcesarmobile** [comment]
Sorry, I can't still reproduce, I've tested in a Xiaomi note with Android 9, which is the closer I can get
this is a rendering issue, so it's not a Capacitor issue but a WebView issue or a problem in the framework you are using.
Make sure the System WebView and/or Chrome is up to date on the device that has problems.
