### ISSUE TITLE
bug: live reload shows a white screen after run the app using React framework 

### ISSUE THREAD

**Issue by b3lg1c4** [ionic-team/capacitor#6366]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/core: 4.6.3
```

### Platform(s)
Android
iOS (not tested)

### Current Behavior
Using `ionic capacitor run android -l --external` starts the app with a white screen. When i check the console in `chrome://inspect`, i get:

![image](https://user-images.githubusercontent.com/76604627/222940099-c6ca4492-5759-454f-aa6f-864e7a4b69d4.png)

### Expected Behavior
Should allow me to run the application with live reload feature. I can use `ionic capacitor run android --external` without live reload, and the white screen is not showing.

### Code Reproduction
1- `ionic start testApp blank --type=react --capacitor`
2- `npm install @capacitor/android` 
3- `npx cap add android`
4- `ionic capacitor sync android`
5- `ionic capacitor run android -l --external`
6- I select my device (Android 9.0 Google APIs | x86) to run the app
7- Go to `chrome://inspect` in the browser
8- Inspect the device with the current running app and see the error as the image uploaded above.

### Other Technical Details
I'm using Ionic with React Framework(`@ionic/react: ^6.0.0`)

### Additional Context
I tried downloading different `globalThis` polyfills and imported to `index.tsx` of my project, but it seems not working as it keeps showing the same error.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by b3lg1c4** [comment]
I already added the code reproduction for any ionic created app.

**Comment by jcesarmobile** [comment]
please, provide a github repository or a zip with the sample app

**Comment by b3lg1c4** [comment]
@jcesarmobile When you unzip the folder's app, make a `npm install`.
[testApp.zip](https://github.com/ionic-team/capacitor/files/10921851/testApp.zip)
