### ISSUE TITLE
Android:  iframe with the Blob URL/Object URL does not work correctly

### ISSUE THREAD

**Issue by natalya-semenova** [ionic-team/capacitor#6377]
### Capacitor Version
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/ios: 4.7.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
Programmatically attaching iframe with the Blob URL/Object URL source produces an iframe with empty body/content.

### Expected Behavior
iframe content is being displayed

### Code Reproduction
https://github.com/natalya-semenova/vue-cap-test

### Other Technical Details
`npm --version` output: 9.5.0

`node --version` output: v18.14.2

**Comment by indice** [comment]
I have the same problem, it works on ios and desktop, but not on adnroid.

    "@capacitor/android": "^5.1.1",
    "@capacitor/app": "^5.0.6",
    "@capacitor/assets": "^2.0.4",
    "@capacitor/cli": "^5.1.1",
    "@capacitor/core": "^5.1.1",
    "@capacitor/device": "^5.0.6",
    "@capacitor/ios": "^5.1.1",

**Comment by iBobik** [comment]
Maybe regression in Cordova?
https://issues.apache.org/jira/browse/CB-9558

**Comment by DLotero** [comment]
@natalya-semenova did you find the solution for this? I have a similar issue

**Comment by psantos9** [comment]
Got the same problem here:

Iframe renders the content in browser:
![Screenshot 2024-02-02 at 17 01 23](https://github.com/ionic-team/capacitor/assets/1428629/e544157c-c26b-4ef1-a87e-59de83ea5b0d)
But is empty on android
![Screenshot 2024-02-02 at 17 00 28](https://github.com/ionic-team/capacitor/assets/1428629/8fe97567-5af8-47e1-9be7-d551a56cc815)

`
"@capacitor/android": "^5.6.0",
"@capacitor/app": "^5.0.7",
 "@capacitor/core": "^5.6.0"
`

Any help here? thank you!

**Comment by psantos9** [comment]
I've created a [minimal vue project](https://github.com/psantos9/vue-capacitor-iframe-android?tab=readme-ov-file#issue-description) that reproduces this issue. Project has two iframes, the leftmost's iframe src is set with a URL.createObjectURL from a blob, the rightmost iframe src is set with a base 64 encoded string of that same blob's contents. Leftmost Iframe is failing on Android and works in Web. Rightmost Iframe works in both android and web:
```
<template>
  <div class="h-screen flex items-center space-x-2 justify-center bg-gray-500">
    <iframe class="w-[250px] h-[250px] bg-white" :src="src" />
    <iframe v-if="src2 !== null" class="w-[250px] h-[250px] bg-white" :src="src2" />
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
const blob = new Blob(
  [
    '<div style="display: flex; align-items: center; justify-content: center; height: 100%; font-size: 1.5rem;">IFRAME CONTENT SHOWN</div>'
  ],
  { type: 'text/html' }
)
const src = URL.createObjectURL(blob)
const src2 = ref<string | null>(null)
const init = async () => {
  src2.value = `data:text/html;base64,${btoa(await blob.text())}`
}
init()
</script>
```
### Android (left iframe failing, right iframe works as expected)
![Android](https://raw.githubusercontent.com/psantos9/vue-capacitor-iframe-android/main/public/empty-android-iframe.png)

![Android behavior](https://raw.githubusercontent.com/psantos9/vue-capacitor-iframe-android/main/public/android-behavior.png)


### Web (both iframes render as expected)
![Web iframe](https://raw.githubusercontent.com/psantos9/vue-capacitor-iframe-android/main/public/web-iframe.png)

![Web behavior](https://raw.githubusercontent.com/psantos9/vue-capacitor-iframe-android/main/public/web-behavior.png)

**Comment by psantos9** [comment]
@jcesarmobile would you happen to have any clue on this one?

**Comment by DanialV** [comment]
Any update on this we still have problem

**Comment by mattfik** [comment]
Also experiencing this issue. Perhaps this PR is the solution? https://github.com/ionic-team/capacitor/pull/5498
