### ISSUE TITLE
Capacitor 4 handling of Android light/dark themes is still buggy 

### ISSUE THREAD

**Issue by moose4lord** [ionic-team/capacitor#6400]
### Capacitor Version
```
Ionic:

   Ionic CLI                     : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.6.1
   @angular-devkit/build-angular : 15.2.2
   @angular-devkit/schematics    : 15.2.2
   @angular/cli                  : 15.2.2
   @ionic/angular-toolkit        : 8.0.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.13.0 (/usr/local/bin/node)
   npm    : 8.19.3
   OS     : macOS Catalina

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0

[capacitor] [info] Found 5 Capacitor plugins for android:
[capacitor]        @capacitor/app@4.1.1
[capacitor]        @capacitor/haptics@4.1.0
[capacitor]        @capacitor/keyboard@4.1.1
[capacitor]        @capacitor/preferences@4.0.2
[capacitor]        @capacitor/status-bar@4.1.1

Here is my userAgent string:
userAgent:Mozilla/5.0 (Linux; Android 12; Pixel 3a Build/SP2A.220505.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36
```

### Platform(s)
Android

### Current Behavior
Capacitor is still having issues with handling light/dark themes on Android.

If I start an app using the Android light theme, the screen shows the app with a light background, but the status bar is shown as white text on a gray background (instead of black text on a white background). Not a deal breaker, but it looks odd. If I use the StatusBar.getInfo() API to read back the state of the status bar, it shows the status bar color is #757575, but it's style is DARK (which is incorrect, it should be LIGHT).
![Screenshot1_light_theme](https://user-images.githubusercontent.com/15672113/225351715-e4c7166a-2039-42e0-ac69-6ca44ce3862a.png)

Then if I change to the Android dark theme, the app colors change to dark colors, as they should, but the status bar remains white text on a gray background (instead of white text on a black background).
![Screenshot2_light_to_dark_theme](https://user-images.githubusercontent.com/15672113/225352403-8753068f-297e-46de-b58e-884cc397b5b2.png)
Changing back to the Android light theme does nothing, the app remains stuck on the dark theme. You need to exit and restart the app to reset the theme.

Similarly, if I start an app using the Android dark theme, the screen shows the app with a dark background, and the status bar is show as white text on a black background. If I use the StatusBar.getInfo() API to read back the state of the status bar, it shows the status bar color is #000000 and it's style is DARK. Everything is working as it should.
![Screenshot3_dark_theme](https://user-images.githubusercontent.com/15672113/225354246-c0a715d4-d5bd-4e45-a7bf-a13e48d950e4.png)

Then if I change to the Android light theme, the app colors change to light colors, as they should, but the status bar remains white text on a black background (should be black text on a white background).
![Screenshot4_dark_to_light_theme](https://user-images.githubusercontent.com/15672113/225355293-e2d51833-fe95-4fd9-8e4d-c868df760cc9.png)
Again, changing the Android theme back to dark does nothing, the app seems to be stuck with the light theme.

So, I think this is highlighting three related issues:
1) changing the Android theme while an app is running only works the first time you do it. After that, changing the Android theme has no effect on the running app.
2) The capacitor status bar plugin is not updating the status bar properly when the theme changes, and displays an odd grey status bar when the light theme is in effect.
3) The capacitor status bar plugin's StatusBar.getInfo() API  does not detect the light theme properly (says style=DARK).

These bugs are mentioned in issue #6100, but that issue has been closed. @jcesarmobile made  a comment about Capacitor 4 using Android's DayNight theme, and that was supposed to handle the light/dark theming automatically, but that doesn't seem to be the case.

### Expected Behavior
Capacitor should be managing the Android light/dark themes properly.

### Code Reproduction
You can see the issue with any of the Ionic starter apps. My repo is here:
[https://github.com/moose4lord/myApp-6.6.1](https://github.com/moose4lord/myApp-6.6.1)

### Other Technical Details
   NodeJS : v18.13.0 (/usr/local/bin/node)
   npm    : 8.19.3

**Comment by jcesarmobile** [comment]
As you have commented, Capacitor 4 is using the `DayNight`, which is what Google engineers told us to use for automatic theme changes.
If the automatic theme change is not working properly, please, report it to Google engineers in their issue tracker as the problem is on the WebView, not in Capacitor
