### ISSUE TITLE
bug: iOS - "Take video and photo" -> Selecting video app crashes.

### ISSUE THREAD

**Issue by YanDevDe** [ionic-team/capacitor#6406]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
- iOS

### Current Behavior

When this input is triggered, and I choose "Take video and photo" - the camera app opens, and it works just fine for the camera. However, once I switch to video, the app simply crashes.

### Expected Behavior

No crash at all when selecting video (photo works fine)

### Code Reproduction

Just <input type="file" />

### Other Technical Details

`npm --version` output: 8.5.5

`node --version` output: v16.15.0

`pod --version` output (iOS issues only): 1.11.2

### Additional Context

I've added the necessary permission for the camera in Info.plist which works fine for photo. But not for video.

```
	<key>NSCameraUsageDescription</key>
	<string>To upload Photos and Video to ...</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>To upload Photos and Video to ...</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>To upload Photos and Video to ...</string>
```

There is also a related issue - but to me, it looks like it hasn't been tested under the video:
https://github.com/ionic-team/capacitor/issues/5046

**Comment by jcesarmobile** [comment]
If you are using input file and it crashes it's a WebView bug, not a Capacitor bug, you should report it to Apple/WebKit. Capacitor does nothing on iOS to make input file work, it should just work.

If you are using video, make sure you are also adding the Microphone usage description, at least is needed for using `getUserMedia`, so it wouldn't surprise me if it's needed for input file.

**Comment by YanDevDe** [comment]
It doesn't crash on Safari Browser in iOS, and it works just normally as expected. 
But the Microphone Usage Description was actually the missing one - after adding this - it worked just well! Thank you so much!

**Comment by jcesarmobile** [comment]
Apple's WebKit team works on both Safari and WKWebView (Capacitor uses the later), but they are not 100% the same, so some things work in Safari but don't work in WKWebView.
Sometimes, like this case, is just missing configurations, but sadly Apple doesn't document that kind of things.
