### ISSUE TITLE
bug: npx cap build android default variant is debug not release

### ISSUE THREAD

**Issue by laurentperez** [ionic-team/capacitor#6412]
### Capacitor Version

```
zsh 2724  (git)-[68-ciprodmobile]-% npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

```

### Platform(s)
android

### Current Behavior

npx cap build android produces a release build

npx cap open android shows that the active build variant is "debug" not "release"

### Expected Behavior

npx cap open android shows that the active build variant is "release"

might be related to https://github.com/ionic-team/capacitor/issues/324

Q :

- how can we produce a release variant ?

**Comment by markemer** [comment]
`npx cap open` is behaving as expected - you'll have to set it yourself in Android Studio under `Edit Configurations`
