### ISSUE TITLE
bug: Capacitor is not in production mode when build with "ionic capacitor build ios --prod" ? loggingBehavior: 'debug' ->  Still output

### ISSUE THREAD

**Issue by informatikTirol** [ionic-team/capacitor#6415]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
IOS

### Current Behavior
When I build IOS with 
"`ionic capacitor build ios --configuration production`" or "i`onic capacitor build ios --prod`", 
Capacitor should be in production mode. 

In capacitor.config.ts I set 
`loggingBehavior: 'debug'`

but I still get debug output from Capacitor

Only when I set 
`loggingBehavior: 'none'`
then there is no log output.

My question: Is Capacitor still not in production mode? How do I get Capacitor in production mode?

### Expected Behavior

Capacitor in production mode.

**Comment by jcesarmobile** [comment]
capacitor doesn't have a `production` option, those `production` and `--prod` options are for ionic command, and only affect the ionic build of the web assets, but not the native builds.
