### ISSUE TITLE
bug: Auto Filling Credentials: "save credentials​" does not work. 

### ISSUE THREAD

**Issue by informatikTirol** [ionic-team/capacitor#6417]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
IOS

### Current Behavior
I configured everything what suggested on 
https://capacitorjs.com/docs/guides/autofill-credentials
* Configuration in XCode
* Apple App Site Association File​

Fill with the default IOS password manager (for me it is 1Password) does work now. 
But when I open the manager, I get a log error in XCODE log: 

` [AXRuntimeCommon] Unknown client: App`

Save Credentials (https://capacitorjs.com/docs/guides/autofill-credentials#save-credentials)
does not work, maybe it is related to this error.

I installed capacitor-ios-autofill-save-password.

When I execute: 

` 
    if (Capacitor.getPlatform() === 'ios') {
        SavePassword.promptDialog({
            username: username,
            password: password,
        })
        .then(() => console.log('promptDialog success'))
        .catch((err) => console.error('promptDialog failure', err));
    }
`
then I get the following error

`
2023-03-21 07:35:32.762177+0100 App[28229:15425787] [AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:19989 (
	0   AXRuntime                           0x00000001e2b797f0 _AXGetPortFromCache + 932
	1   AXRuntime                           0x00000001e2b7b9a4 AXUIElementPerformFencedActionWithValue + 772
	2   UIKit                               0x000000023f86dae8 2FB1F859-1BC4-30B2-B751-1BC0A9B31400 + 785128
	3   libdispatch.dylib                   0x000000010392453c _dispatch_call_block_and_release + 32
	4   libdispatch.dylib                   0x0000000103925ff0 _dispatch_client_callout + 20
	5   libdispatch.dylib                   0x000000010392e0a0 _dispatch_lane_serial_drain + 988
	6   libdispatch.dylib                   0x000000010392edc8 _dispatch_lane_invoke + 420
	7   libdispatch.dylib                   0x000000010393bcac _dispatch_workloop_worker_thread + 740
	8   libsystem_pthread.dylib             0x0000000206e60df8 _pthread_wqthread + 288
	9   libsystem_pthread.dylib             0x0000000206e60b98 start_wqthread + 8
)
2023-03-21 07:35:32.764419+0100 App[28229:15425787] [AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:19989 (
	0   AXRuntime                           0x00000001e2b797f0 _AXGetPortFromCache + 932
	1   AXRuntime                           0x00000001e2b7b9a4 AXUIElementPerformFencedActionWithValue + 772
	2   UIKit                               0x000000023f86dae8 2FB1F859-1BC4-30B2-B751-1BC0A9B31400 + 785128
	3   libdispatch.dylib                   0x000000010392453c _dispatch_call_block_and_release + 32
	4   libdispatch.dylib                   0x0000000103925ff0 _dispatch_client_callout + 20
	5   libdispatch.dylib                   0x000000010392e0a0 _dispatch_lane_serial_drain + 988
	6   libdispatch.dylib                   0x000000010392edc8 _dispatch_lane_invoke + 420
	7   libdispatch.dylib                   0x000000010393bcac _dispatch_workloop_worker_thread + 740
	8   libsystem_pthread.dylib             0x0000000206e60df8 _pthread_wqthread + 288
	9   libsystem_pthread.dylib             0x0000000206e60b98 start_wqthread + 8
)
2023-03-21 07:35:32.765978+0100 App[28229:15425787] [AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:19989 (
	0   AXRuntime                           0x00000001e2b797f0 _AXGetPortFromCache + 932
	1   AXRuntime                           0x00000001e2b7b9a4 AXUIElementPerformFencedActionWithValue + 772
	2   UIKit                               0x000000023f86dae8 2FB1F859-1BC4-30B2-B751-1BC0A9B31400 + 785128
	3   libdispatch.dylib                   0x000000010392453c _dispatch_call_block_and_release + 32
	4   libdispatch.dylib                   0x0000000103925ff0 _dispatch_client_callout + 20
	5   libdispatch.dylib                   0x000000010392e0a0 _dispatch_lane_serial_drain + 988
	6   libdispatch.dylib                   0x000000010392edc8 _dispatch_lane_invoke + 420
	7   libdispatch.dylib                   0x000000010393bcac _dispatch_workloop_worker_thread + 740
	8   libsystem_pthread.dylib             0x0000000206e60df8 _pthread_wqthread + 288
	9   libsystem_pthread.dylib             0x0000000206e60b98 start_wqthread + 8
)
`

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by markemer** [comment]
Can you point me to a sample project?

**Comment by informatikTirol** [comment]
HI, here is a sample code: https://www.dropbox.com/s/j2v5bskr3wqk2e3/APP_RL.zip?dl=0

**Comment by markemer** [comment]
I've been a bit involved with Capacitor 5 recently, but this is still on my radar. I use 1password on my phone as well, so I should be able to test with your project.

**Comment by informatikTirol** [comment]
Thank you, would be a very important feature for me.

**Comment by jcesarmobile** [comment]
the link is not working, can you upload the app again or publish it in a github repository?

**Comment by informatikTirol** [comment]
I have uploaded the file again: https://www.dropbox.com/s/j2v5bskr3wqk2e3/APP_RL.zip?dl=0

**Comment by jcesarmobile** [comment]
the provided app doesn't include the ios folder with the native iOS project, you have to provide it and it has to be configured according to https://capacitorjs.com/docs/guides/autofill-credentials#configuration-for-ios

**Comment by informatikTirol** [comment]
Here is the corresponding IOS Folder: 
https://www.dropbox.com/s/gi6h7bndkzfz3in/ios.zip?dl=0

**Comment by jcesarmobile** [comment]
Sorry, I can't properly test since the register button doesn't work, so I can't register, and as I can't register I can't see if the password was saved.

But doesn't looks like your server is correctly configured as there is no file in `/.well-known/apple-app-site-association`, and [branch validator](https://branch.io/resources/aasa-validator/) also shows validation errors. 
Not sure if you forgot to upload the [association file ](https://capacitorjs.com/docs/guides/autofill-credentials#apple-app-site-association-file) since you said you have created it.

Upload the file to that folder and make sure it's accessible on the `/.well-known/apple-app-site-association` url and served with `application/json` content type.
If still doesn't work you should probably report the issue to the [auto fill plugin repository](https://github.com/cuongpl/capacitor-ios-autofill-save-password/issues) since that's what saves the password, not Capacitor
