### ISSUE TITLE
bug: How to get or request "Add Photos Only" permission in iOS?

### ISSUE THREAD

**Issue by shaifulborhan** [ionic-team/capacitor#6421]
### Capacitor Version
4.7.1

```
Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

```

### Platform(s)
@capacitor/camera

### Current Behavior

In iOS, how can I get or request the correct value of the "Add Photos Only" permission?

Using Camera.checkPermissions() simply returns 

```
{
   "camera": "denied",
   "photos": "denied"
}
```

<img width="442" alt="Screenshot 2023-03-22 at 6 55 27 AM" src="https://user-images.githubusercontent.com/802225/226760703-08a49059-9eb2-42e4-b5ca-3462508a634f.png">

### Expected Behavior

Able to get the correct status flag for the  "Add Photos Only" permission in iOS.

Able to request the  "Add Photos Only" permission in iOS.

### Code Reproduction

```
const hasPermission = await Camera.checkPermissions();
alert( JSON.stringify(hasPermission))
```

### Other Technical Details

`npm --version` output: 6.14.17

`node --version` output: v14.20.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

I was using the @capacitor/share plugin to Share files. In iOS, it has the option to "Save file..." which prompts the user for the "Add Photos Only" permission.

I want to be able to check the status of the permission in the app and show a notice if the user has clicked "Don't Allow".

**Comment by markemer** [comment]
Can you add a simple project showing the issue? `Camera.checkPermissions()` returns the proper values in my tests.

**Comment by jcesarmobile** [comment]
Camera plugin doesn't allow this, it has "camera" alias for taking pictures permission and "gallery" alias for read/write permission into the gallery. Gallery returns true only if both read and write are allowed, but in your case, read is not allowed, only write, so it returns denied.
You'll need to create your own plugin if you want to know if writing to the gallery is allowed. The main purpose of camera plugin is reading, not writing.
