### ISSUE TITLE
feat: New webkit feature - Inspectable WebKit, inspect production apps

### ISSUE THREAD

**Issue by alexcroox** [ionic-team/capacitor#6441]
## Feature Request

![image](https://user-images.githubusercontent.com/1065835/228040803-862a0be6-9178-4cc7-871a-ffc3f8ffc467.png)

https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/

**Comment by thmclellan** [comment]
Thanks @alexcroox for sharing this. It seems like a breaking change from iOS 16.3, which allowed for in-app webview contents to be inspected by default while running from Xcode.

For anyone who just upgraded to iOS 16.4 and lost their Safari > Develop > iPhone options, here is a temporary workaround that you can add to the end of the `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?)` function in the main `AppDelegate` class in Xcode. 

```
// When running from Xcode in debug mode, enable webView inspection 5 seconds after startup
#if DEBUG
  if #available(macOS 13.3, iOS 16.4, tvOS 16.4, *) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 5.0) {
              if let vc = self.window?.rootViewController as? CAPBridgeViewController {
                  vc.bridge?.webView?.isInspectable = true;
              }
        }
  }
#endif
 ```

Not elegant at all with the 5 second delay but hopefully it helps someone waiting on a future update or plugin. Tested on Capacitor 4.4.0 with Xcode 14.3 RC2 with ionic serve project setup. I found Safari Technology Preview (16.4) was required to get console logging; Safari 16.3 connected but didn't actually show logs.

**Comment by qliqdev** [comment]
Also it will be correct if you add smth like

```
ios: {
      webview: {
        configuration: {
          inspectable: true
        }
      }
    }
```

in capacitor.config.ts.

@markemer pls take a look

**Comment by markemer** [comment]
Yeah - we're looking at figuring out how to not require 16.4 and build this in as well.

**Comment by markemer** [comment]
> Also it will be correct if you add smth like

Thanks, I will.

**Comment by timgavin** [comment]
@qliqdev how are you adding that to your config? This doesn't work for me with Simulator 14.3

```typescript
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.my.app',
  appName: 'App',
  webDir: 'www',
  bundledWebRuntime: false,
  ios: {
    webview: {
      configuration: {
        inspectable: true
      }
    }
  }
};

export default config;
```

**Comment by qliqdev** [comment]
@timgavin I didn't say that it is working solution. I have just asked contributers to make it configurable from cap configs file.

**Comment by thmclellan** [comment]
@HansFilip96 The example was for capacitor 4... there were some big improvements between v2 and v3. You could probably achieve the same thing on V2 if you adapt it to V2's CapBridgeViewController (https://github.com/ionic-team/capacitor/blob/2.x/ios/Capacitor/Capacitor/CAPBridgeViewController.swift) 

You could try changing the if block to something like this (not tested) 

 ```
if let vc = self.window?.rootViewController as? CAPBridgeViewController {
    vc.bridgedWebView?.isInspectable = true;
}
```

**Comment by markemer** [comment]
Capacitor 4.8.0 will support this on iOS 16.4+ - the current Capacitor 5 beta does already.

**Comment by raghav-kokotree** [comment]
Quick fix: 

Putting the following code in "func application" method of ios/App/App/AppDelegate.swift file will bring the option in Safari to inspect the application


```
#if DEBUG // Check if the app is running in debug mode
        if #available(macOS 13.3, iOS 16.4, tvOS 16.4, *) { // Check if the current platform version is at least macOS 13.3, iOS 16.4, or tvOS 16.4
            DispatchQueue.global(qos: .background).async { // Execute the following code asynchronously on a background thread with an appropriate quality of service
                let semaphore = DispatchSemaphore(value: 0) // Create a new DispatchSemaphore with an initial value of 0
                let delay: TimeInterval = 3.0 // Define a delay of 3 seconds
                _ = semaphore.wait(timeout: .now() + delay) // Wait for the semaphore to be signaled after the specified delay
                DispatchQueue.main.async { // Execute the following code asynchronously on the main thread
                    if let vc = self.window?.rootViewController as? CAPBridgeViewController { // Get a reference to the root view controller of the app's window and cast it to a CAPBridgeViewController
                        vc.bridge?.webView?.isInspectable = true // Set the isInspectable property of the CAPBridgeViewController's web view to true, allowing it to be inspected with the Safari Developer Tools
                    }
                }
            }
        }
#endif // End of debug mode check
```


The complete file will look like this:

```
import UIKit
import Capacitor

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        

#if DEBUG // Check if the app is running in debug mode
        if #available(macOS 13.3, iOS 16.4, tvOS 16.4, *) { // Check if the current platform version is at least macOS 13.3, iOS 16.4, or tvOS 16.4
            DispatchQueue.global(qos: .background).async { // Execute the following code asynchronously on a background thread with an appropriate quality of service
                let semaphore = DispatchSemaphore(value: 0) // Create a new DispatchSemaphore with an initial value of 0
                let delay: TimeInterval = 3.0 // Define a delay of 3 seconds
                _ = semaphore.wait(timeout: .now() + delay) // Wait for the semaphore to be signaled after the specified delay
                DispatchQueue.main.async { // Execute the following code asynchronously on the main thread
                    if let vc = self.window?.rootViewController as? CAPBridgeViewController { // Get a reference to the root view controller of the app's window and cast it to a CAPBridgeViewController
                        vc.bridge?.webView?.isInspectable = true // Set the isInspectable property of the CAPBridgeViewController's web view to true, allowing it to be inspected with the Safari Developer Tools
                    }
                }
            }
        }
#endif // End of debug mode check
        
        
        
        
        return true
    }
    
    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }
    
    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }
    
    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }
    
    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }
    
    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
        // Called when the app was launched with a url. Feel free to add additional processing here,
        // but if you want the App API to support tracking app url opens, make sure to keep this call
        return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
    }
    
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        // Called when the app was launched with an activity, including Universal Links.
        // Feel free to add additional processing here, but if you want the App API to support
        // tracking app url opens, make sure to keep this call
        return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)
    }
    
    
}

```

**Comment by jcesarmobile** [comment]
closing since @capacitor/ios 4.8.0 was released

**Comment by jcesarmobile** [comment]
that's not needed, unless you want to allow debugging in production apps, also, should be inside `ios` object, but still, I wouldn't recommend adding that, since it's for production apps, debugging is enabled by default for debug apps in 4.8.0.

**Comment by raffyPhotoup** [comment]
I still can't get my console.log working on my simulator. I have updated capacitor/ios to 4.8.0. Has this been fixed on that version?

**Comment by raffyPhotoup** [comment]
I can't seem to make any of my console.logs show on the web inspector. Should I be updating anything else for this to work? All my capacitor plugins are currently on 4.0.1 and I don't really want to upgrade to capacitor 5 yet.

**Comment by qliqdev** [comment]
> I can't seem to make any of my console.logs show on the web inspector. Should I be updating anything else for this to work? All my capacitor plugins are currently on 4.0.1 and I don't really want to upgrade to capacitor 5 yet.
> 
> capacitor/core, ios, and cli are all on 4.8.0

Try to remove `node_modules` folder and `package-lock.json` after run again `npm install`

**Comment by raffyPhotoup** [comment]
> > I can't seem to make any of my console.logs show on the web inspector. Should I be updating anything else for this to work? All my capacitor plugins are currently on 4.0.1 and I don't really want to upgrade to capacitor 5 yet.
> > capacitor/core, ios, and cli are all on 4.8.0
> 
> Try to remove `node_modules` folder and `package-lock.json` after run again `npm install`

Works now on my end but I had to install the Safari Technology Preview to see the console.logs.

Thanks

**Comment by albertreed** [comment]
I've upgraded core/cli/ios to 4.8.0 and I'm still not seeing my app as inspectable from safari or safari technology preview. Is there anything more you need to do beyond just upgrading those packages? Tried clearing out node_modules, build artifacts, etc as well. 

XCode 14.3. Sim is running iOS 16.4

Also tried adding 
```
ios: {
      webview: {
        configuration: {
          inspectable: true
        }
      }
    }
```

To my config.

**Comment by razarahil** [comment]
Check if there any update available for native-run

**Comment by nikage** [comment]
> Not working with 4.8.0

I've updated to 4.8.0 and it works like charm with this config.

```
android: {
    appendUserAgent: "android:application",
    webContentsDebuggingEnabled: true
  },
  ios: {
    appendUserAgent: "ios:application",
    webContentsDebuggingEnabled: true
  },
```

**Comment by markemer** [comment]
> > Not working with 4.8.0
> 
> I've updated to 4.8.0 and it works like charm with this config.
> 
> [snip]

You should only need those  if you're running your app in release mode. Or really, just a mode where an `#if DEBUG` fails. Let me know if that isn't the case for you.

**Comment by nikage** [comment]
> You should only need those if you're running your app in release mode. Or really, just a mode where an #if DEBUG fails. Let me know if that isn't the case for you.

Basically my actual code looks like this, but I thought it would be irrelevant to the issue(live means webpack dev server). 

```
android: {
    appendUserAgent: "android:application",
    webContentsDebuggingEnabled: !!isLive
  },
  ios: {
    appendUserAgent: "ios:application",
    webContentsDebuggingEnabled: !!isLive,
  },
```
