### ISSUE TITLE
tip: Hold your horses with the new XCode (14.3)

### ISSUE THREAD

**Issue by zarko-tg** [ionic-team/capacitor#6454]
We get permanent iOS build failures after updating to XCode 14.3.
It seems to be related / a bug in cocoapods, most likely this one https://github.com/CocoaPods/CocoaPods/issues/11808

For now it's wise to stay on XCode 14.2, and wait for a fix in cocoapods before updating XCode I suppose.

**Comment by Hen-Dricks** [comment]
Same here, i'm just downgrading to 14.2

**Comment by ciccilleju** [comment]
same problem, downgraded to 14.2

**Comment by ryaa** [comment]
This seems to be the same as https://github.com/ionic-team/capacitor/issues/6457

**Comment by farshidpg** [comment]
same problem with 14.3 and capacitor

**Comment by piotr-cz** [comment]
Apparently Cocoapods issue have been fixed in v1.12.1: https://github.com/CocoaPods/CocoaPods/issues/11808#issuecomment-1513820696

**Comment by zarko-tg** [comment]
@piotr-cz Correct, things are back to normal now - building with XCode 14.3 works as expected.
