### ISSUE TITLE
Feat: Recurring Functions While App is Not Visible

### ISSUE THREAD

**Issue by alexandermccormick** [ionic-team/capacitor#6465]
### Description
Run functions when the app GUI is not visible on the device screen, in a recurrent fasion.

### Platform(s)
Android / iOS

### Preferred Solution
An official Capacitor plugin

### Additional Context
[This](https://capacitorjs.com/docs/v2/apis/background-task) page in the Capacitor docs has stated for a few years now that soon this plugin would support running functions, when the app GUI is not visible on the device screen, in a recurrent fasion. I understand there are a few community solutions, but none of them seem to work reliably across devices or with both Android and IOS. Is this still a planned feature, or should the documentation be updated? At the moment, this plugin feels more like an `onClose` app lifecycle hook.

**Comment by jcesarmobile** [comment]
Should be possible with Background Runner plugin

https://capacitorjs.com/docs/apis/background-runner

**Comment by alexandermccormick** [comment]
Oh man, looks like that has seen quite a few updates since I last looked at it. It's no longer just for one last function upon the app exiting then? I will definitely take a look into this again, thank you.
