### ISSUE TITLE
I want to hide url when open a weblink using @capacitor/browser plugin

### ISSUE THREAD

**Issue by sumanrc** [ionic-team/capacitor#6468]
## Feature Request
https://user-images.githubusercontent.com/98080516/230069147-a2e2b827-a85d-4349-9196-fbbc52c5b06a.png
when opening a weblink using the **@capacitor/browser** plugin it opens in Chrome browser but I want to open it in **in-app**.
And also want to hide the URL when the URL opens.

### Platform(s)
Android and IOS

**Comment by jcesarmobile** [comment]
That's not possible with `@capacitor/browser` because the native components used by the plugin don't allow it.
