### ISSUE TITLE
bug: Angular 15 and window.location.pathname

### ISSUE THREAD

**Issue by scope-li** [ionic-team/capacitor#6469]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/ios: 4.7.3
  @capacitor/android: 4.7.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)
Angular  & Capcitor & Android

### Current Behavior
With `androidScheme: "capacitor"` in `capacitor.config.ts` and in Andorid, you will get in `window.location.pathname` the value with a prefix `//localhost` (e.g. `//localhost/` or `//localhost/some/other/path`). 
This breaks some location/router logic in Angular 15 (I believe since 15.0.3).

_By the way, `window.location.host` and `window.location.hostname` are also empty, but not a problem for this issue._

iOS has no Problem, it get `window.location.pathname` without a `//localhost` prefix.

### Expected Behavior
With `androidScheme: "capacitor"` in `capacitor.config.ts` and in Andorid, I will get in `window.location.pathname` the value WITHOUT a prefix `//localhost` (e.g. `//localhost/` or `//localhost/some/other/path`). 

### Code Reproduction
https://github.com/scope-li/repoducer_angular15_capacitor

If you start the App in Android-Studio, you will get an error ` Error: NG04002: Cannot match any routes. URL Segment: 'localhost'`, because angular means that localhost is a piece of the path.

### Other Technical Details
Nothing, see reproducer repo.

### Additional Context
That `//localhost` is in `window.location.pathname` has always been the case, but probably became a problem since https://github.com/angular/angular/pull/48327/files and `_stripOrigin()`.

**Comment by jcesarmobile** [comment]
The provided app doesn't include Capacitor nor a custom scheme, so can't be verified.
But the problem is probably related to this WebView issue https://bugs.chromium.org/p/chromium/issues/detail?id=1029487

Google engineers recommend to not use a custom scheme for loading assets, you should stick with http or https or weird things can happen and google is not going to fix them.
