### ISSUE TITLE
bug: App crashing on using camera - Capacitor on Android 12 , 13

### ISSUE THREAD

**Issue by ersaurabh101** [ionic-team/capacitor#6474]
## Bug Report
App crashes and restarts when taking and confirming a picture on Android 12 and 13.  
[App crashes on clicking this button after taking picture](https://i.stack.imgur.com/NMvmY.jpg)

### Capacitor Version
> Capacitor ver: 4.2.0  
> minsdkversion: 22  
> compilesdkversion: 33  
> targetsdkversion: 33  
```
We are using `Capacitor` camera plugin. When capturing an image with the camera plugin it crashes everytime I take a picture and the app restarts. 
```

### Other Technical Details
After we click the `tick` icon, we get the base64 code in the `imageUrl` variable.

`npm --version` output: 8.5.3

`node --version` output: 12.18.3

### Additional Context
We tried asking on Ionic forums, Stackoverflow. No one is helping us. Hope we find help here.

**Comment by jcesarmobile** [comment]
For being able to use targetsdkversion 33, you have to update to Capacitor 5 (still in beta)
You can update to Capacitor 5 beta following[ this guide](https://capacitorjs.com/docs/next/updating/5-0), or keep using target/compileSDK 32.
