### ISSUE TITLE
v5 Status

### ISSUE THREAD

**Issue by co-dax** [ionic-team/capacitor#6476]
Is v5 safe for production use?

I am asking as:

1. From the git history I would say it is 5.0.0-beta.1
2. The latest version of npm does not state it is a beta release. Version name [here](https://www.npmjs.com/package/@capacitor/core?activeTab=versions) is "5.0.0-nightly-20230407T150524.0" 
3. There is documentation on how to migrate from v4 to v5 [here](https://capacitorjs.com/docs/next/)
4. v5 is not marked as beta in the versions dropdown in the UI header at [this link](https://capacitorjs.com/docs/next) 
![image](https://user-images.githubusercontent.com/7594292/230728551-04309fbd-6d0e-4c74-b585-d254c7d72c49.png)

5. The only thing that would imply v5 is not yet stable/production release is the word "**next**" in the following link [https://capacitorjs.com/docs/next](https://capacitorjs.com/docs/next)

**Comment by IT-MikeS** [comment]
No, it is currently in BETA the `latest` tag in NPM is still 4.7.3:

![Screenshot 2023-04-10 at 11 43 01 AM](https://user-images.githubusercontent.com/20338451/230937288-ca15cabd-679d-4e05-8759-6be26bcba5bd.png)

**Comment by co-dax** [comment]
Thanks @IT-MikeS
