### ISSUE TITLE
feat: Web implementation of Http Plugin should be able to cancel requests

### ISSUE THREAD

**Issue by Crylion** [ionic-team/capacitor#6481]
### Description
The Angular HTTP client is able to cancel in-flight requests in favor of newer ones, if the observable (or chain of observables) on the request is unsubscribed. We have been using that functionality for a rather aggressive type-ahead on a search input, because the client wanted the search to be as responsive as possible. So instead of debouncing the request a little, to give the user time to finish their typing, new search requests are literally fired for every character typed. The client wanted this explicitly, because the server is fast enough to actually return results almost instantly.
However, we still have to take care, not just to queue all these requests, in case the server or internet connection slows down a little. Which means: Only the latest request, for the most recently typed character, should actually remain queued. The previous ones need to be cancelled if they are still in-flight.
In action, it looks like this:

<img width="469" alt="Screenshot 2023-04-10 at 11 11 04" src="https://user-images.githubusercontent.com/776753/230871892-a6db3455-89e8-4760-9f2a-9940bf4b51d3.png">

When using the web implementation of the Capacitor HTTP Plugin (in the same application, hooked up to the same chain of observables) however, it looks like this:

<img width="454" alt="Screenshot 2023-04-10 at 11 13 22" src="https://user-images.githubusercontent.com/776753/230872152-a0f9d304-76af-463a-a33b-0d485f67d673.png">

### Platform(s)
Web

### Preferred Solution
I guess the problem is, that the `request` method of the Capacitor plugin returns a Promise, instead of an Observable like the Angular client. Since the capacitor implementation just does an await on the `fetch` call, there is probably no way it could be cancelled by the subscriber to the promise. 
```
const response = await fetch(url, requestInit);
```
With the angular client, you can just use `switchMap` to start your requests, and for each new request the unfinished ones just get automatically unsubscribed, which actually cancels the in-flight http requests.
If it were feasible to return an observable instead of a promise, RxJS even provides a simple creator method to return one from a fetch request: https://rxjs.dev/api/fetch/fromFetch

**Comment by jcesarmobile** [comment]
there is a feature request already that covers all platforms, so closing as duplicate

https://github.com/ionic-team/capacitor/issues/5978
