### ISSUE TITLE
bug: failing to import plugins due to TypeError: Failed to resolve module specifier "@capacitor/preferences"

### ISSUE THREAD

**Issue by mr-zwets** [ionic-team/capacitor#6484]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/core: 4.7.0

[success] Android looking great! 👌
```

### Platform(s)
I'm using capacitor yo make an android app only currently.
The webapp I'm porting over does not use any framework or npm, just html, css & js.

### Current Behavior
Trying to import a capacitor-js plugin, I get 
`Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught TypeError: Failed to resolve module specifier \"@capacitor/preferences\".` in the android studio logs.
Tested the same for "@capacitor/push-notifications" and a couple other random plugins.

VS code does correctly show the path to the plugin in the node_modules folder.

I asked two more experienced programmers who used capacitor before if I was clearly doing something wrong but they reproduced the error. 

longer error logs:
```
E/Capacitor/Console: File: http://localhost/ - Line 628 - Msg: TypeError: Failed to resolve module specifier "@capacitor/preferences". Relative references must start with either "/", "./", or "../".
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught TypeError: Failed to resolve module specifier \"@capacitor/preferences\". Relative references must start with either \"/\", \"./\", or \"../\".","url":"http://localhost/","line":0,"col":0,"errorObject":"{}"}}
E/Capacitor/Console: File: http://localhost/ - Line 0 - Msg: Uncaught TypeError: Failed to resolve module specifier "@capacitor/preferences". Relative references must start with either "/", "./", or "../".
```

### Expected Behavior
I expect the import to work correctly.

### Code Reproduction
```
git clone git@github.com:mr-zwets/cashtokens-wallet-app.git
cd cashtokens-wallet-app
npm i
npx cap sync
npx cap open android
```
So without plugins everything works.

Then adding a plugin with
`npm install @capacitor/preferences`
adding `import { Preferences } from '@capacitor/preferences';`
`npx cap sync`

### Other Technical Details

`npm --version` output: 8.0.0

`node --version` output: v18.12.1

Thanks for taking the time to look at this, capacitor-js is a very cool tool 🙏

**Comment by jcesarmobile** [comment]
can you provide a full sample app where the plugin is already being used?

**Comment by mr-zwets** [comment]
Added a commit which imports & uses the preferences plugin and causes the issue mentioned above ->

https://github.com/mr-zwets/cashtokens-wallet-app

**Comment by jcesarmobile** [comment]
For using Capacitor plugins (or any npm package) you have to use a bundler (such as vite, webpack, etc), so when you do `import { Something } from 'some-npm-package';`, it picks the appropriate code from node_modules and bundles it with your app.

**Comment by mr-zwets** [comment]
ah sorry, I see this was a stupid question after all.
Thanks for your time 🙏 I'm used to the react world where this is handled by default haha.
Now I'm no longer stuck & know what to do...
Setting up vite!
