### ISSUE TITLE
bug: dependency installation with 2 high severity vulnerabilities

### ISSUE THREAD

**Issue by caeduInformaticas** [ionic-team/capacitor#6485]
### Capacitor Version
```
@capacitor/core: 4.7.3
@capacitor/cli: 4.7.3
@capacitor/android: not installed
@capacitor/ios: not installed
```

### Platform(s)
none

### Current Behavior
when creating a project and installing the dependencies as output 2 high severity vulnerabilities:
# npm audit report

xml2js < 0.5.0
Severity: high
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
No fix available
node_modules/xml2js
   @capacitor/cli *
   Depends on vulnerable versions of xml2js
   node_modules/@capacitor/cli

2 high severity vulnerabilities

### Expected Behavior
clean install

### Code Reproduction

<img width="870" alt="Captura de pantalla 2023-04-10 a la(s) 21 35 20" src="https://user-images.githubusercontent.com/26305194/231032566-a1b79d14-ab3a-46b1-b0f2-147bcfcdb518.png">

### Other Technical Details

`npm --version` output:
9.5.0
`node --version` output:
18.15.0

`pod --version` output (iOS issues only):

### Additional Context
1 create a project = ionic start app_name
2 start app successfully
3 rm -r node_modules; rm package-lock.json
4 npm install
5 output with 2 high severity vulnerabilities

// It is not blocking but it should be fixed

Thanks

**Comment by pmarkoulidakis** [comment]
The security issue has been discussed here:
https://github.com/Leonidas-from-XIV/node-xml2js/issues/663
And the PR comments 
https://github.com/Leonidas-from-XIV/node-xml2js/pull/603
