### ISSUE TITLE
AGP version 8.0.0 doesn't work with Capacitor

### ISSUE THREAD

**Issue by Charchad** [ionic-team/capacitor#6504]
Hi,

This morning I upgraded my version of Android Studio to Flamingo, and one of the recommended things is to upgrade the Android Gradle Plugin to version 8.0.0.

The upgrade can be performed but then the project doesn't work due the following error:

```
A problem occurred configuring project ':capacitor-android'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:
```

So the problem is that now namespace needs to be defined inside build.gradle instead of AndroidManifest.xml, like this:

```
android {
    namespace 'com.getcapacitor.android'
}
```

Is there a plan to fix this in the near future? 

Note: This also needs to be fixed in all your official plugins

**Comment by Charchad** [comment]
Forgot to mention that I'm using Capacitor version 4.6.1, but I don't see any mention about this on newest releases. Is it already fixed?

**Comment by jcesarmobile** [comment]
It's something that is already fixed for Capacitor 5 (beta 2 at the moment), but won't be fixed for Capacitor 4 because it's a breaking change.
If using Capacitor 4 we recommend to not upgrade to gradle 8.

**Comment by Charchad** [comment]
okay, then we will wait for Capacitor 5 to migrate.

Thanks!

**Comment by AE1NS** [comment]
```
@capacitor/android: 5.0.0-beta.3
@capacitor/core: 5.0.0-beta.3
```
```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.0'
...
```
```
android {
    namespace "..."
...
```
Removed package attribute from AndroidManifest.xml
Everything updated to latest in Android Studio.


Gradle build is still failing:
```
Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

android {
    namespace 'com.example.namespace'
}

If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.
```

Does this still happen to anyone else?

**Comment by NePheus** [comment]
Just to understand it correctly: No installed capacitor plugin may have the package name defined in the AndroidManifest.xml. Otherwise this issue occurs? So all plugins (also community plugins) must be refactored first, before updating to capacitor 5 + gradle plugin v8?

**Comment by Charchad** [comment]
Correct. All modules in your project (either yours or added by Capacitor or community plugins) needs to declare the namespace outside the AndroidManifest.xml. Otherwise AGP v8 doesn't work

**Comment by timmyrosen** [comment]
@Charchad This is kind of insane. Not expecting a Capacitor 5 upgrade coming any time soon for any of my projects then. Sad.

**Comment by azhar-neolysi** [comment]
> Correct. All modules in your project (either yours or added by Capacitor or community plugins) needs to declare the namespace outside the AndroidManifest.xml. Otherwise AGP v8 doesn't work

can you explain in detail

**Comment by Charchad** [comment]
Hi @azhar-neolysi, I think the issue is pretty clear... from some time alredy the Android Gradle Plugin has been giving warnings that namespaces (or package name) must no longer be defined inside the AndroidManifest.xml but on build.gradle. This applies to all your modules in your Android project.

That's why, for example, if you try to upgrade now to the Android Gradle Plugion version 8, using Capacitor 4.6.1 the project no longer compiles because the modules that are "automatically" generated by Capacitor are still defining the value inside AndroidManifest.xml

capacitor-android
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.getcapacitor.android">
</manifest>
```

capacitor-android-cordova-plugins
```
<?xml version='1.0' encoding='utf-8'?>
<manifest package="capacitor.android.plugins"
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:amazon="http://schemas.amazon.com/apk/res/android">
<application >
</application>
</manifest>
```

Also official capacitor plugins, like:

capacitor-network

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.capacitorjs.plugins.network">
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>
```

Apparently some issues are already fixed by Capacitor 5, but if you are using other community plugins, these also needs to be updated.

**Comment by jcesarmobile** [comment]
Capacitor CLI 5.0.2, released yesterday, will patch any plugin that has not done the package migration from `AndroidManifest.xml` to `build.gradle` so you don't need to wait for plugin maintainers to update their plugins.
