### ISSUE TITLE
bug: HttpParams encoded incorrectly on Android

### ISSUE THREAD

**Issue by jkeys089** [ionic-team/capacitor#6511]
### Capacitor Version
4.7.3

### Platform(s)
Android

### Current Behavior
Making a `GET` request using CapacitorHttp with params like `{ "k": "a&b" }` results in a query string like `?k=a&b` (i.e. the ampersand is NOT encoded despite `HttpOptions.shouldEncodeUrlParams = true`).

### Expected Behavior
The resulting query string should be `?k=a%26b` (i.e. the ampersand is encoded to `%26`)

### Code Reproduction
```js
import { CapacitorHttp } from '@capacitor/core';

const doGet = () => {
  const options = {
    url: 'https://example.com/my/api',
    shouldEncodeUrlParams: true,
    params: { k: 'a&b' },
  };

  const response = await CapacitorHttp.request({ ...options, method: 'GET' })
};
```

### Other Technical Details
The flaw is in the [`HttpURLConnectionBuilder.setUrlParams`](https://github.com/ionic-team/capacitor/blob/88d0ded9e7356531ffc4563b9b81a0f3f069484b/android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java#L121) method. It constructs the `urlQueryBuilder` without encoding and then relies on the [URI constructor](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#URI(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)) to encode: 

> Any character that is not a [legal URI character](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#legal-chars)

However, as stated in the java.net.URI docs this will not encode [legal chars](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#legal-chars) and, thus, results in incorrect behavior.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by jkeys089** [comment]
@jcesarmobile I've added a reproducer project https://github.com/jkeys089/capacitor_android_http_params_reproducer. Would you be open to a pull request to fix this issue?
