### ISSUE TITLE
bug: Promblem with using capacitor preferences plugin - 'A resource failed to call close. '

### ISSUE THREAD

**Issue by mr-zwets** [ionic-team/capacitor#6515]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/core: 4.7.0

[success] Android looking great! 👌
```

### Platform(s)
I'm using capacitor to make an android app.
The webapp I'm porting over does not use any framework or npm, just html, css & js.
I added the Vite blunder to be able to add the capacitor plugins.

### Current Behavior
Trying to use the capacitor-js preferences plugin, my app doesn't load an instead gets stuck on the message
`W/System: A resource failed to call close. `

longer error logs:
```
D/Capacitor: Registering plugin instance: Preferences
W/Capacitor: Unable to read file at path public/plugins
D/Capacitor: Loading app at http://localhost
...
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 23838399, pluginId: Preferences, methodName: get
V/Capacitor: callback: 23838399, pluginId: Preferences, methodName: get, methodData: {"key":"darkMode"}
W/System: A resource failed to call close. 
```

### Expected Behavior
I expect the the preferences plugin to work correctly now that I added a bundler after issue #6484 

### Code Reproduction
```
git clone git@github.com:mr-zwets/cashtokens-wallet-app.git
cd cashtokens-wallet-app
yarn
yarn vite build
npx cap open android
npx cap sync
```

### Other Technical Details

`npm --version` output: 8.0.0

`node --version` output: v18.12.1 

Sorry that I need much help, but I'm really determined to get this to work 🙏

**Comment by jrobeson** [comment]
So is this actually a bug in capacitor? or he plugin code? If it's the plugin code, then shouldn't the bug be filed at https://github.com/ionic-team/capacitor-plugins/issues ?

**Comment by jcesarmobile** [comment]
I've tested the provided app and the plugin is working properly. The `A resource failed to call close.` message is unrelated to the plugin.

The problem why your app is not working is that you have a listener for `DOMContentLoaded` where you unhide some content and since you are awaiting for the plugin result, when the code reaches the `DOMContentLoaded` listener call, it has already fired and adding a listener for `DOMContentLoaded` after it has fired has no effect, so everything inside the listener function is not running.

**Comment by mr-zwets** [comment]
Thank you so much for explaining this issue to me! Now I'm no longer hard stuck 🙏 
I'll try without listening to  `DomContentLoaded` and if that doesn't work I know it's an issue with importing the mainnet-js library through the html tags.
Thanks again, really appreciate that you investigated my specific case to help me out.
I will do my best to launch a cool app in return!
