### ISSUE TITLE
PRODUCT_BUNDLE_IDENTIFIER is hardcoded to `com.getcapactior.app`

### ISSUE THREAD

**Issue by microadam** [ionic-team/capacitor#653]
Hello,

When adding the ios platform using `npx cap add ios` I have noticed the generated project has a hardcoded value for its `PRODUCT_BUNDLE_IDENTIFIER` of `com.getcapactior.app`

This is specified here: https://github.com/ionic-team/capacitor/blob/895a5bf817ac06628bacffeca4795bf8e3f7bf01/ios-template/App/App.xcodeproj/project.pbxproj#L375

This caused me some issues when trying to build the project as I started getting signing errors complaining that my selected provisioning profile didn't contain a match for `com.getcapactior.app`.

Have I done something wrong somewhere and this being hardcoded is correct? or is this a genuine bug?

Many thanks

**Comment by jcesarmobile** [comment]
It was a genuine bug, fixed now. 
Thanks!
