### ISSUE TITLE
bug: PushNotifications.register() returns 'undefined' on Android

### ISSUE THREAD

**Issue by ashin-kk** [ionic-team/capacitor#6553]
### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 4.8.0    
  @capacitor/core: 4.8.0   
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0    

Installed Dependencies:    

  @capacitor/cli: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/ios: 4.7.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

// PERMISSION CHECKING & REGISTER
```
 async registerNotifications() {
            let permStatus = await PushNotifications.checkPermissions();

            if (permStatus.receive !== 'granted') {
                permStatus = await PushNotifications.requestPermissions();
            }

            console.log('permStatus :==', permStatus);
            console.log('permStatus receive :==', permStatus.receive);

            const register = await PushNotifications.register();
            console.log('register :==', register);
        },
```

// RESULT IN LOG
![image](https://user-images.githubusercontent.com/40032009/235823869-d3b8bee6-8c26-4a3c-9f67-c2ef7af2d4ec.png)

### Other Technical Details

I followed as mentioned on the official plugin page. Added google-services.json file as well. Don't know what's missing. Please guide. 
I am just a beginner in capacitor.

`npm --version` output: 9.6.1

`node --version` output: v18.15.0

`pod --version` output (iOS issues only): NA

**Comment by jcesarmobile** [comment]
yeah, that's what register method returns
https://capacitorjs.com/docs/apis/push-notifications#register

for getting the push token you have to add a listener for registration
https://capacitorjs.com/docs/apis/push-notifications#addlistenerregistration
