### ISSUE TITLE
bug: Moving the docs from /next broke all the links in Google

### ISSUE THREAD

**Issue by ptmkenny** [ionic-team/capacitor#6561]
## Bug Report

Congratulations on the Capacitor 5 release!  Unfortunately, as a result of moving
https://capacitorjs.com/docs/next/updating/5-0
to 
https://capacitorjs.com/docs/updating/5-0
all the links in Google to the docs are broken.

For example, I searched for `capacitor 5 update guide` and the first hit is to https://capacitorjs.com/docs/next/updating/5-0, which is now a broken link with no redirect on launch day.

Please try to find a way to have permalinks or redirects for the next release.

**Comment by jcesarmobile** [comment]
fixed in https://github.com/ionic-team/capacitor-docs/pull/179
