### ISSUE TITLE
bug: Capacitor Google Maps. Cannot get control of Markers, Circles etc

### ISSUE THREAD

**Issue by almaz1213** [ionic-team/capacitor#6575]
### Capacitor Version

```
npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.1
  @capacitor/core: 5.0.1
  @capacitor/android: 5.0.1
  @capacitor/ios: 5.0.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.0-beta.3
  @capacitor/core: 5.0.0-beta.3
  @capacitor/android: 5.0.0-beta.3

[error] Missing <manifest package=""> attribute in app/src/main

```

### Platform(s)

web, android

### Current Behavior

Hi, I'm trying to find something working and useful in Capacitor Google Maps plugin. I created a map, added a marker using addMearker and a circle using addCircles. They appear on the map but I cannot find how can I change them or set a listener for handle manual changes. How can I get created objects?  

### Expected Behavior

probably addCircles must return array of added Circle objects

### Code Reproduction

```
this.gMap.setOnBoundsChangedListener(d=>{
      this.currBounds = d;
      if (this.dial.inData.command === 'setArea') {
        if (!this.circle) {
          this.circle = {
            center: d.bounds.center,
            radius: 2000
          }
          this.gMap.addCircles([this.circle]).then(console.debug).catch(console.error)
        } else {
          this.circle = {
            center: d.bounds.center,
            radius: 2000
          }
        }
        console.debug('this.circle', this.circle);
      }
    })
```

### Other Technical Details

`npm --version` output:
9.5.1

`node --version` output:
v18.16.0

`pod --version` output (iOS issues only):

### Additional Context

using documentation https://capacitorjs.com/docs/apis/google-maps#addcircles

**Comment by jcesarmobile** [comment]
Both addCircles and addMarkers return an array of the circles/markers ids added.
If that's not working properly, please, create an issue on https://github.com/ionic-team/capacitor-plugins/issues and provide a sample app where the issue can be reproduced.
