### ISSUE TITLE
ERROR:cdvMinSdkVersion not set

### ISSUE THREAD

**Issue by zimdim** [ionic-team/capacitor#659]
On building in Android studio I get ERROR:'cdvMinSdkVersion' for project ':app' of type org.gradle.api.Project.

**Comment by jcesarmobile** [comment]
Can you list your Cordova plugins?
One of them is probably setting the cdvMinSdkVersion variable, but we don't have that in Capacitor

**Comment by jcesarmobile** [comment]
Closing as there was no response and couldn't reproduce with that little information.

**Comment by jcesarmobile** [comment]
I was able to reproduce, it was fixed here https://github.com/ionic-team/capacitor/pull/1016
