### ISSUE TITLE
bug:  App.addListener('appUrlOpen'...)

### ISSUE THREAD

**Issue by skytern** [ionic-team/capacitor#6600]
### Capacitor Version
npx cap doctor
   Capacitor Doctor   

Latest Dependencies:       

  @capacitor/cli: 5.0.3    
  @capacitor/core: 5.0.3   
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3    

Installed Dependencies:    

  @capacitor/android: 5.0.3
  @capacitor/cli: 5.0.3    
  @capacitor/core: 5.0.3   
  @capacitor/ios: 5.0.3   

### Platform(s)
Android / Ionic / Angular / Capacitor
"Pixel6 API 33 Android 13.0" 

### Current Behavior
Deep link were configured with the docs https://capacitorjs.com/docs/guides/deep-links#angular
But i have only the listener without emission.
![image](https://github.com/ionic-team/capacitor/assets/36536345/778723a0-908b-4b69-9d0d-6111c906ca31)

### Expected Behavior
I would like to have an emit event when the Browser app load an URL.
![image](https://github.com/ionic-team/capacitor/assets/36536345/cd390b42-d76d-4157-a639-b68fde6f0373)

The goal is to handle callback on Oauth2 (spotify).

### Code Reproduction
Repository to reproduce bug:
https://github.com/skytern/ionic-listener-app-url-open/tree/master

### Other Technical Details
Node v18.16.0
Npm 8.12.2

**Comment by jcesarmobile** [comment]
The provided app doesn't include the android folder, so we can't check if the app is correctly configured to be opened from url schemes or deep links.
Also the sample app just navigates to `http://capacitorjs.com/`, which belongs to us, so you can't associate that url with your app as you can't host the association files there. 
Can you provide a sample app with the android folder, correctly configured to use url schemes or deep links and a url that has been associated with that app?

**Comment by skytern** [comment]
Thank you for your response and your time. @jcesarmobile 
And sorry, if it wasn't clear, the goal is not to redirect my website to my app.
My goal it is not to have this situation "https://capacitorjs.com/docs/guides/deep-links#creating-site-association-files"

The workflow is to handle Spotify callback.
When I use OAuth on the request of authentication, I send a URL of callback in parameters.

To summarize, we have these steps :
1 - We detect if we have a token for Spotify
2 - If no, we redirect the user with @capacitor/Browser to Spotify website (with callback URL in parameters)(in Spotify dashboard I authorize few URL callbacks)
3 - At the end of authentication, Spotify redirects user to the callback URL
4 - In this step, I need an event to fetch a URL with token in parameter like (spotify.app://callback?token=thisToken)

I think my error is linked to the wrong callback URL ? I think that "capacitor.config.ts" in appId field gives the application name as "io.ionic.starter".

And if I test this URL "io.ionic.starter://callback?token=thisToken" I may have an event with Addlistener, but I don't have this case.

I'm not sure, it's necessary to provide "AndroidManifest.xml" ? Maybe I need to add an intent filter with the app name as "io.ionic.starter" ?

All these questions to find out exactly what the scope of Add.addListener is. When is this feature supposed to work ?

Thanks again for your question, maybe I didn't understand how it is work ?

**Comment by jcesarmobile** [comment]
Yeah, you need an intent filter with a custom scheme, it’s slightly different from the one mentioned in the deep links tutorial, check the app plugin docs.
https://capacitorjs.com/docs/apis/app#android

The scheme has to be unique so there is no other app with the same scheme declared. Don’t use io.ionic.starter.

**Comment by skytern** [comment]
@jcesarmobile 
I just lost my mind between different deep link documentation.
Everything works like I wanted.
Thank you
