### ISSUE TITLE
bug: App not working on Amazon Fire HD 10  due to webView version and errorPath

### ISSUE THREAD

**Issue by arcadius** [ionic-team/capacitor#6602]
### Capacitor Version

```
Capacitor:

   Capacitor CLI      : 4.8.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.8.0
   @capacitor/ios     : 4.7.3
```

### Platform(s)

android

### Current Behavior

The method `Bridge.isMinimumWebViewInstalled()` expects the WebView package to be  `com.android.chrome` or `com.google.android.webview` 

Amazon uses a different WebView package name i.e `com.amazon.webview.chromium`
so, `Bridge.isMinimumWebViewInstalled()` failes to detect the correct WebView version and returns `false` -> the errorPath page is displayed 

### Expected Behavior

The Amazon WebView Major version seems to be the same as the official Google WebView major version, so we only need to make a small change to use the package name `com.amazon.webview.chromium` to support Amazon Fire devices

**Comment by jcesarmobile** [comment]
fixed in https://github.com/ionic-team/capacitor/pull/6603
