### ISSUE TITLE
feat: Allow extension of `WebViewDelegationHandler` in iOS

### ISSUE THREAD

**Issue by e-e-e** [ionic-team/capacitor#6605]
### Description

We are wanting to run custom crashlytics reporting within our capacitor app to get observability on any unusual spikes in webview crashes per a release. In order to do this we want to report errors within the `WKNavigationDelegate`'s `webViewWebContentProcessDidTerminate` method, so that we can monitor the number of times our webviews are being terminated.

At the time of writing, Capacitor on iOS sets the webview's navigation delegate to an instance of `WebViewDelegationHandler` which has a lot of extra functionality, including reloading the webview on crashes. We experimented with overwriting the webviews navigation delegate with our own custom implementation, however this caused issues as doing so removed the functionality from `WebViewDelegationHandler`.

### Platform(s)

iOS

### Preferred Solution

Remove `internal` scoping from `WebViewDelegationHandler` to allow consumers to extend its functionality through extensions.

### Alternatives

I am not a strong swift developer, so am unsure if there are better alternatives.  Open to any suggestions as to how else we could execute custom code when the webview is unexpectedly terminated.

### Additional Context

We are able to add such override behavior on android as such:

```kotlin
public class CrashReportingWebViewClient extends BridgeWebViewClient { ... }
```

```kotlin
public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        WebView webView = this.bridge.getWebView();
        CrashReportingWebViewClient webViewClient = new CrashReportingWebViewClient(this.bridge);
        webView.setWebViewClient(webViewClient);
    }
}
~~

**Comment by peitschie** [comment]
I've got a PR for Android that exposes this as a plugin hook: https://github.com/ionic-team/capacitor/pull/6416

If we can get any type of buy-in from the core Capacitor team, I'd be happy to extend that to support this use-case as well 🙂 

Just for my own record keeping, there's some existing discussion about this hook https://github.com/ionic-team/capacitor/discussions/5260 and https://github.com/ionic-team/capacitor/discussions/5488

**Comment by alextreppass** [comment]
Hi @markemer thanks for picking this up. Making the change backwards-compatible with Capacitor 4 would be great if possible, we'd love to use this but are not yet in a position to upgrade to 5 🤞🏼

**Comment by gummibjorn** [comment]
Hi @markemer 

We would also be interested in having the option to extend the WebViewDelegationHandler in iOS.

e.g.
<img width="897" alt="Screenshot 2023-09-25 at 09 28 39" src="https://github.com/ionic-team/capacitor/assets/11292339/fb825c85-0c45-4627-b8c9-69f461c56a6d">

Something like that would be awesome.

Please contact me if this seems feasible to you.

BR
Mario

**Comment by jcesarmobile** [comment]
It's already possible to use your own `WebViewDelegationHandler` by [using a custom ViewController ](https://capacitorjs.com/docs/ios/viewcontroller)

But also, in Capacitor 6 `WebViewDelegationHandler` will be public https://github.com/ionic-team/capacitor/pull/6894
