### ISSUE TITLE
bug: CapacitorHttp: Empty response with no-cors mode enabled

### ISSUE THREAD

**Issue by LeGeek01** [ionic-team/capacitor#6617]
### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 5.0.4    
  @capacitor/core: 5.0.4   
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4    

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/ios: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4
```

### Platform(s)
All

### Current Behavior
When do a request with the @capacitor/http plugin with no-cors enabled, the plugin returns `
Object { data: "", headers: {}, status: 0, url: "" }` while the request respond with 200 and a text.
With no-cors disabled, the object is correctly completed.
Note that the no-cors mode is tested in a URL that doesn't include a Allow-Origin headers and doesn't correspond to the same host (and generate an error if no-cors mode is disabled).

### Expected Behavior
The plugin complete the result object

### Code Reproduction
```js
await CapacitorHttp.get({
    url: 'https://cdn.discordapp.com/attachments/(example of valid discord image)',
    webFetchExtra: {  }
}) //==> No problem because the discord CDN specify the Allow-Origin to *
```
```js
await CapacitorHttp.get({
    url: 'https://demo.index-education.net/pronote',
    webFetchExtra: { mode: 'no-cors' }
})
// ==> The request succeeds but the plugin returns the object { data: "", headers: {}, status: 0, url: "" }
```
```js
await CapacitorHttp.get({
    url: 'https://demo.index-education.net/pronote',
    webFetchExtra: {  }
})
// ==> The request fails because of CORS Restrictions
```

### Other Technical Details
The result is catched by the `then` method

NPM v`9.6.5`

NodeJS v`20.2.0`

**Comment by Vexcited** [comment]
> `webFetchExtra: { mode: 'no-cors' }`

This is only related to [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and [`no-cors` mode](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode) always respond with opaque responses. That means, you can't access Response.

> `no-cors`
> Prevents the method from being anything other than HEAD, GET or POST, and the headers from being anything other than [simple headers](https://fetch.spec.whatwg.org/#simple-header). If any ServiceWorkers intercept these requests, they may not add or override any headers except for those that are [simple headers](https://fetch.spec.whatwg.org/#simple-header). In addition, JavaScript may not access any properties of the resulting [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response). This ensures that ServiceWorkers do not affect the semantics of the Web and prevents security and privacy issues arising from leaking data across domains.

So, this issue should only apply to Web platform, Http plugin can only bypass CORS restrictions in Android and iOS platforms, since they don't use the Fetch API but native functions instead.
