### ISSUE TITLE
Percentage based heights don't function correctly in the Android WebView causing visual HTML bugs

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/capacitor#662]
# Bug Report

**Capacitor Info**
**Version:** Capacitor 1.0.0-beta.1

**Describe the Bug**
Inside the Android WebView, HTML elements that have percentage based heights function incorrectly. Instead of being relative to the element's parent's height, it is relative to the root element. This only occurs inside the Android WebView in Capacitor and cannot be replicated in Android Google Chrome, or a Cordova build of the same app. This also occurs outside any sort of framework and can be replicated with a single `index.html`. This is also most likely the cause for #482.

**Steps to Reproduce**
1. Start up a empty Capacitor project with a single `index.html` file in the `www` directory.
2. Add this code to the `body`:
```
<div>
	<div class="test-child"></div>
</div>
```
3. Add this style block to the `head`:
```
<style>
	.test-child {
		height: 100%;
		width: 50px;
		background: red;
	}
</style>
```
4. Run the Capacitor build on an Android device or emulator.
5. See this result:
<img width="346" alt="screen shot 2018-07-16 at 5 10 10 pm" src="https://user-images.githubusercontent.com/15218748/42783840-34696a6e-891b-11e8-95f2-02788d12796d.png">

**Expected Behavior**
Because the `test-child` div is wrapped in another div, it should have 0 height, but for some reason the child ignores the parent and expands to fill the viewport. This will cause many visual problems for any elements that have their height set as a percentage, including Ionic's own dialog component as seen in #482.

**Additional Context**
I've been digging into Capacitor's Android WebView implementation to try and find the cause, but no luck so far. I've also been comparing it to Cordova since that seems to work correctly, but there is a lot going on in both projects that it might be difficult to pinpoint exactly why this is happening. We are continuing to research this problem internally and will update this issue with any new information.

**Comment by mlynch** [comment]
Unsure if related, but will try this suggestion:

https://bugzilla.xamarin.com/show_bug.cgi?id=25935

> This reproduction case here does not use the correct webview renderer for the platform so it did not get hte fix. They need to set the LayoutParams of their custom android webview to be MatchParent to get the fix.

**Comment by sbannigan** [comment]
@mlynch tried that one. I was hopeful because that issue was the closest I've seen to the problem, but didn't seem to work.

**Comment by mlynch** [comment]
Yea, no luck on that

**Comment by mlynch** [comment]
Tried FrameLayout, no luck

**Comment by mlynch** [comment]
I'm wondering if it's related to the AppCompatActivity we use, that'd be something different from Cordova

**Comment by mlynch** [comment]
<img width="574" alt="screenshot 2018-07-17 13 05 18" src="https://user-images.githubusercontent.com/11214/42836942-1f92306a-89c2-11e8-880b-6b85e90916ab.png">

**Comment by mlynch** [comment]
Okay can confirm it's not AppCompatActivity. Hacked it out and still see it

**Comment by mlynch** [comment]
Fixed by sending scripts in the `<head>` tag in the main HTML body, instead of before the HTML content

**Comment by solojuve1897** [comment]
@mlynch 
Possible to get hands on the fix? Like through npm installing latest master-version instead of offical beta?

**Comment by moberwasserlechner** [comment]
I can also confirm that this fixes problems with Angular Material 2's `matDialog: MatDialog` and `<mat-datepicker />`. Both were stretched to full height. Thank you.
