### ISSUE TITLE
When using Filesystem.writeFile to save large files (blobs) on Android 13, it results in a memory overflow, causing the app to crash!

### ISSUE THREAD

**Issue by hexianggui** [ionic-team/capacitor#6624]
my code:
```
const savePackage = async (blob: Blob) => {
  const base64Data = (await convertBlobToBase64(blob)) as string;
  const path = "mobest/mes/mobestmes.apk";
  return await Filesystem.writeFile({
      path: path,
      data: base64Data,
      directory: Directory.Data,
      // encoding: Encoding.UTF8,
      recursive: true,
    });
};
```
Usually, a memory overflow occurs when a blob exceeds 26MB. This particular blob is 57MB in size and it is an APK file. When I set 'encoding: Encoding.UTF8' and save it on my physical device, the file can be saved but becomes corrupted and cannot be read. Here are some partial error or warning messages from the virtual machine:
 ```
    Throwing OutOfMemoryError "Failed to allocate a 34187664 byte allocation with 25149440 free bytes and 26MB until OOM, target footprint 198650776, growth limit 201326592" (VmSize 30823812 kB)
    java.lang.OutOfMemoryError: Failed to allocate a 34187664 byte allocation with 25149440 free bytes and 26MB until OOM, target footprint 198650776, growth limit 201326592
  at java.lang.StringFactory.newStringFromChars(Native Method)
  at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
  ....
 ```
 Although the issue can be resolved by adding the following code within the 'application' tag in the 'AndroidManifest.xml' file, it is hoped that Filesystem.writeFile can support writing large files. Thank you!
 ```
    <application
        android:largeHeap = "true"
        android:hardwareAccelerated = "false"
        ......
 ```

**Comment by jcesarmobile** [comment]
That's a limitation of the OS, if you need to write large files it's recommended to write it in chunks using `appendFile` instead of trying to write all at once.
