### ISSUE TITLE
bug: Iframe user agent

### ISSUE THREAD

**Issue by snolaxpokemon** [ionic-team/capacitor#6625]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4

### Platform(s)
android

### Current Behavior
I setting overrideUserAgent to change user agent to view desktop site on android.
const config: CapacitorConfig = {
  appId: 'io.ionic.test',
  appName: 'test',
  webDir: 'www',
  server: {
    androidScheme: 'https'
  },
  overrideUserAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57 Trailer/93.3.2482.83',
  android: {
    overrideUserAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57 Trailer/93.3.2482.83'
  }
};

Every request using HttpClientModule work well except request of iframe, image, etc.
My iframe
home.page.html
<iframe [src]="iframeSrc" title=""></iframe>
home.page.ts
iframeSrc: SafeUrl = this.sanitizer.bypassSecurityTrustResourceUrl("https://chat.zalo.me/");

It using default user agent of device to request
Mozilla/5.0 (Linux; **Android 13**; sdk_gphone64_x86_64 Build/TPB4.220624.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.74 Mobile Safari/537.36
### Expected Behavior
user agent request should be 
Mozilla/5.0 (**Windows NT 10.0**; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57 Trailer/93.3.2482.83

### Code Reproduction

https://github.com/snolaxpokemon/testiframe.git

command:
npm install
ionic build 
npx cap sync android

run emulator and using chrome devtool to watch request headers.

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v18.12.1

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by snolaxpokemon** [comment]
> This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.
> 
> Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
> 
> Thanks! Ionitron 💙

Update Code Reproduction

**Comment by snolaxpokemon** [comment]
it worked in API 21 and 29, but user-agent didn't change in API 30
https://stackoverflow.com/questions/62434410/set-user-agent-in-webview-for-android-api-30/62535531

**Comment by jcesarmobile** [comment]
Thanks for the sample app, but I can't reproduce.
For making it more obvious, I changed your iframe url with `https://www.whatismybrowser.com/detect/what-is-my-user-agent/` so the user agent gets displayed on the screen.
Tested on Android 28, 30 and 33 emulators and real Pixel 6 with Android 13.

Anyway, since Capacitor's overrideUserAgent just calls `webView.getSettings().setUserAgentString(overrideUserAgent);`, so if that no longer works you should report it to Google as they should the ones fixing it, not us. But again, it's working fine for me, so might be device specific.
