### ISSUE TITLE
bug: Logs are showing in my app on Android device (not emulator)

### ISSUE THREAD

**Issue by yannickcare** [ionic-team/capacitor#6626]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

```

### Platform(s)

Android

### Current Behavior

When loading my app, I see logs in the background of my application

### Expected Behavior

Logs should never show

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only):

### Additional Context

![Screenshot_20230601-093852_c4g-caregiver](https://github.com/ionic-team/capacitor/assets/58120733/e60f1d97-db5e-4405-85f6-855b41f1c4ce)

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by yannickcare** [comment]
In my code, I load

`this.httpClient.get('assets/version', {responseType: 'text' }).subscribe((version) => {
      this.version = version;
    });`

which is displayed in our footer, it works on web, and emulator, but on device, it loads the content of the page instead, that is what displays the code. So the question is why is the assets/version loading the page html instead of the file?

**Comment by yannickcare** [comment]
needed to enable 
`
"CapacitorHttp": {
      "enabled": true
    }
`
