### ISSUE TITLE
iOS build fails when using cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by danielsimon1** [ionic-team/capacitor#663]
I tried to add the plugin `cordova-plugin-googlemaps` to my Capacitor app.
In Android, everything is working fine, but on iOS the plugin causes the build to fail:

```
CordovaPluginGooglemaps/PluginUtil.h:14:9: error: 'MainViewController.h' file not found
```

**Comment by jcesarmobile** [comment]
Yeah, this plugin won't work as it's highly coupled with some Cordova classes that Capacitor doesn't have. See https://github.com/ionic-team/capacitor/issues/215

**Comment by Jbz797** [comment]
Some news about this issue ?

**Comment by jcesarmobile** [comment]
it's not working and it's not going to work
