### ISSUE TITLE
bug: When run androd get  ”com/sun/istack/FinalArrayList“ wrong

### ISSUE THREAD

**Issue by shouhuori** [ionic-team/capacitor#6634]
### Capacitor Version
```
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely
       deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4

[error] Missing <manifest package=""> attribute in app/src/main

```

### Platform(s)
android

### Current Behavior
When run ```npx cap run android ``` get this error:
```
npx cap run android                                     chao@chaozongdeiMac

✔ Copying web assets from dist to android/app/src/main/assets/public in 12.90ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 1.41ms
[info] Inlining sourcemaps
✔ copy android in 28.52ms
✔ Updating Android plugins in 2.07ms
[info] Found 3 Capacitor plugins for android:
       @capacitor/browser@5.0.2
       @capacitor/camera@5.0.2
       @capacitor/splash-screen@5.0.2
✔ update android in 60.12ms
✔ Please choose a target device: › HUAWEI ELE-AL00 (8KE5T19425024235)
✖ Running Gradle build - failed!
[error] 
        > Configure project :app
        WARNING: Using flatDir should be avoided because it doesn't support any meta-data
        formats.
        
        > Configure project :capacitor-cordova-android-plugins
        WARNING: Using flatDir should be avoided because it doesn't support any meta-data
        formats.
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        com/sun/istack/FinalArrayList
        > com.sun.istack.FinalArrayList
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 1s
```

### Other Technical Details

`npm --version` output: 9.5.1

`node --version` output: v18.16.0

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by shouhuori** [comment]
I push code at [https://github.com/shouhuori/cap5](https://github.com/shouhuori/cap5)

**Comment by jcesarmobile** [comment]
Thanks for the sample app, but I can't reproduce.
Looks like gradle/java related, not Capacitor related. 
Are you using JDK 17 and have JAVA_HOME environment variable configured to use it? 
Capacitor 5 requires JDK 17 and running from the CLI uses gradle to build, which requires JAVA_HOME configured.
Does the app build if you run `npx cap open android` and then run from Android Studio instead of using the `npx cap run` command?

**Comment by shouhuori** [comment]
Thanks a lot! I change JDK 11 to JDK 17 is OK.
