### ISSUE TITLE
bug: incorrect Android http url param encoding

### ISSUE THREAD

**Issue by jkeys089** [ionic-team/capacitor#6644]
### Capacitor Version
5.0.2

### Platform(s)
Android

### Current Behavior
Making a `GET` request using CapacitorHttp with params like `{ "k": "a&b" }` results in a query string like `?k=a&b` (i.e. the ampersand is NOT encoded despite `HttpOptions.shouldEncodeUrlParams = true`).

### Expected Behavior
The resulting query string should be `?k=a%26b` (i.e. the ampersand is encoded to `%26`)

### Code Reproduction

- Project - https://github.com/jkeys089/capacitor_android_http_params_reproducer
- Relevant code - https://github.com/jkeys089/capacitor_android_http_params_reproducer/blob/6a735ffa58311d8c299fddf78bb848942653bfbb/src/js/capacitor-welcome.js#L4
- Screenshot of issue from reproducer ![](https://user-images.githubusercontent.com/1695857/237483820-78c2a3c5-0569-4fd1-a905-0f6975ffb893.png)

### Other Technical Details
The flaw is in the [HttpURLConnectionBuilder.setUrlParams](https://github.com/ionic-team/capacitor/blob/88d0ded9e7356531ffc4563b9b81a0f3f069484b/android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java#L121) method. It constructs the urlQueryBuilder without encoding and then relies on the [URI constructor](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#URI(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)) to encode:

> Any character that is not a [legal URI character](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#legal-chars)

However, as stated in the java.net.URI docs this will not encode [legal chars](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#legal-chars) and, thus, results in incorrect behavior.

### Additional Context
Originally reported at https://github.com/ionic-team/capacitor/issues/6511

**Comment by markemer** [comment]
Can you update the title on this? I'll be taking a look soon.

**Comment by markemer** [comment]
Also, have you tested this on iOS and Android and it's just Android?

**Comment by jkeys089** [comment]
@markemer title updated. It is just Android (also see: https://github.com/ionic-team/capacitor/pull/6586).

**Comment by PHELAT** [comment]
Hi!
Is there any updates on this? What's the blocker for https://github.com/ionic-team/capacitor/pull/6586?
