### ISSUE TITLE
bug: Blank screen with npx cap run ios (empty html document)

### ISSUE THREAD

**Issue by raythree** [ionic-team/capacitor#6649]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4
  @capacitor/core: 5.0.4```
```

### Platform(s)
* MacOS Ventura 13.4 
* Xcode  14.3.1

### Current Behavior
I am getting a white screen deploying to iOS, either a real device or a simulator. Using Ionic React framework.   Seems to be the same as this: 

https://github.com/ionic-team/capacitor/issues/5470

After building and syncing, if I deploy via:

```
npx cap run ios
```

I get the white screen. Connecting via Safari develop mode, I can see that the document shows "about:blank" and is an html document with an empty body tag. After reading the issue above, I tried deploying as:

```
ionic cap run ios -l --external
```

And this consistently works fine. Leaving off the "-l --external" results in it using the blank document.  

### Expected Behavior

Should deploy the app without the "-l --external" flags.

### Code Reproduction
N/A

### Other Technical Details

`npm --version` output:
9.5.0

`node --version` output:
18.14.2

`pod --version` output (iOS issues only):
1.12.1

**Comment by raythree** [comment]
I realized that I had a "server" entry in `capacitor.config.ts` as I was running previously with live reload. This need to be removed when deploying without live reload I assume, so probably best to keep two separate capacitor configs.

**Comment by jcesarmobile** [comment]
Ionic CLI is supposed to remove the server part when you stop the server, if that's not working properly you should report it in the [Ionic CLI repository](https://github.com/ionic-team/ionic-cli/issues).
