### ISSUE TITLE
bug: CFBundleExecutable Key - The bundle does not contain a bundle executable

### ISSUE THREAD

**Issue by bc-whisnant** [ionic-team/capacitor#6653]
## Bug Report
CFBundleExecutable Key - The bundle at 'node_modules/@capacitor/browser/ios/Plugin/Info.plist' does not contain a bundle executable. When uploading to testflight the binary is invalid due to a missing bundle executable.

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4
```

### Platform(s)
MacOS Monterey 12.6.3
Xcode 14.2

### Current Behavior
When running the app in a simulator and building the .ipa file everything works perfectly. When I upload to the app store through both xcode and fastlane everything seems to go fine. However, in Testflight the status of the upload is `Invalid Binary`. Please see below for more error message information.

The process is as follows: I open xcode, update some project settings and then build the app with the following command `npm run build-ios-gamma && cd ios/app && fastlane gamma`. This is successful when using fastlane and also when uploading to testflight manually through xcode. But it fails when it gets to Testflight with the error message of `Invalid Binary`. At that point Apple sends an email with the error message listed below.

```
`CFBundleExecutable Key - The bundle at 'node_modules/@capacitor/browser/ios/Plugin/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.`
```

### Expected Behavior
The app should upload and then binary should be valid in Testflight.

### Code Reproduction
N/A

### Other Technical Details
`npm --version` output: 8.11.0

`node --version` output: v16.16.0

`pod --version` output (iOS issues only): 1.11.0

### Additional Context
I recently upgrade to capacitor 5 so I could use @capacitor/browser. I used `npx cap migrate` to assist with migration from version 3 to 5.

**Comment by markemer** [comment]
Few questions - have you tried a full clean build with a deleted derived data. Have you attempted to load the ipa you built for the store on a device?

**Comment by bc-whisnant** [comment]
Hey,
I apologize. I had tried both of those and it didn't work but then I
figured out the issue. I work in a hybrid application with multiple
node_modules folders and I had the package installed in two different
places. This was completely my fault. I meant to get back to this and
update it but I got busy and completely forgot.

**Comment by jcesarmobile** [comment]
glad you figured out
