### ISSUE TITLE
bug: MediaChrome: Picture-in-picture is not enabled

### ISSUE THREAD

**Issue by RobinHavre** [ionic-team/capacitor#6655]
### Capacitor Version

```
@capacitor/cli: 4.7.0
@capacitor/core: 4.7.0
@capacitor/ios: 4.7.0
@capacitor/android: 4.7.0
```

### Platform(s)
```
Android 13
Android 12
```

### Current Behavior
Trying to play video with picture-in-picture mode does not work (nothing happens, the video still plays inline in the webview). The following warning is logged in the console:
```
MediaChrome: Picture-in-picture is not enabled
```

### Expected Behavior
The video should overlay the app and play as picture-in-picture mode, as described here: https://developer.android.com/develop/ui/views/picture-in-picture

### Code Reproduction
AndroidManifest.xml
```xml
<activity
android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
android:launchMode="singleTask"
android:resizeableActivity="true" 
android:supportsPictureInPicture="true"
...>
</activity>
```

### Additional Context
We have verified that Picture-in-picture access has been given to the app, by opening Android Settings > Apps > ``Special app access`` > ``Picture-in-picture``. Then selecting the app and Picture-in-picture is listed as enabled.

This all works as expected on iOs.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
