### ISSUE TITLE
bug: @capacitor/http; Missing 'progress' event listener on XMLHttpRequest

### ISSUE THREAD

**Issue by Jopie01** [ionic-team/capacitor#6658]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/core: 5.0.5

```
### Platform(s)
I've only tested on Android, but I assume this also affects iOs.

### Current Behavior
I hooked up the `onprogress` event in my code to show the progress of downloading a file to the user. But **enabling** the `@capacitor/http` plugin the progress doesn't show up anymore. I only see the popup and when the downloading is done, it will show the file. When I **disable** the plugin, the progress is shown again.

### Expected Behavior
The user should see the progress of the download. 

### Code Reproduction
Below the function using the XMLHttpRequest to fetch data from the backend which works within the webbrowser and with `@capacitor/http` **disabled**
```javascript

makeXMLRequest(method, params, headers, useDatabase=true, cancelFunc, progressFunc)  {
  const req = this.checkParams(params, headers, useDatabase);
  if (req.error !== undefined && req.error !== null) {
    return Promise.reject(req.error);
  }

  return new Promise((resolve, reject) => {
    let fetch = new XMLHttpRequest();

    if (cancelFunc !== undefined && cancelFunc !== null) {
      cancelFunc.cancel = () => {
        fetch.abort(null);
      };
    }
    // open a connection
    fetch.open("POST", req.host);
    // set extra request headers
    for (const key in req.headers) {
      fetch.setRequestHeader(key, req.headers[key]);
    }

    fetch.onload = (oEvent) => {
      if (fetch.status >= 200 && fetch.status < 300) {
        // difference between @capacitor/http and the 'normal' XMLHttpRequest
        // @capacitor/http returns already a JSON
        const result = JSON.parse(fetch.response);
        resolve(result.result);
      } else {
        reject(fetch.statusText);
      }
    };
    // send progress data back
    fetch.onprogress = (oEvent) => {
      if (progressFunc !== undefined && progressFunc !== null) {
        progressFunc(oEvent.loaded, oEvent.total);
      }
    };

    fetch.onerror = (oEvent) => {
      reject(fetch.statusText);
    };
    // abort the connection
    fetch.onabort = (oEvent) => {
      reject(false);
    };
    // send the data
    fetch.send(JSON.stringify(
      {method: method, params: req.params, id: req.uid}
    ));
  });
}
```
### Other Technical Details
The `progress` event is described here: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event and I would have thought to find it also here https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/assets/native-bridge.js#L417 but I can't find it.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
