### ISSUE TITLE
bug: cannot override UNUserNotificationCenter delegate (iOS)

### ISSUE THREAD

**Issue by rpanadero** [ionic-team/capacitor#6666]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/ios: 5.0.5
  @capacitor/android: 5.0.5

```

### Platform(s)

- iOS

### Current Behavior

It is not possible to override the UNUserNotificationCenter delegate that Capacitor Push Notifications plugin set on application start.

The issue seems to be here because the current implementation is not checking whether it is a already a delegate set.

### Expected Behavior

It should be possible to implement an application specific UNUserNotificationCenter delegate to add custom code because some push broker integrations sometimes requires this.

In fact, I already opened some years ago a question about this and a PR was introduced by the team to support it. Could you have have a look at this to check it the implementation was broken unintentionally. That implementation was working properly, but it seems that a code refactor broke it.
https://github.com/ionic-team/capacitor/issues/1631

### Other Technical Details

`npm --version` output: 9.7.1

`node --version` output: v18.16.0

`pod --version` output (iOS issues only): 1.12.1

### Additional Context

This issue also seems to be related: https://github.com/ionic-team/capacitor/issues/4735

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
