### ISSUE TITLE
bug: (Splash screen) can not manually hide splash screen

### ISSUE THREAD

**Issue by MarcusAngel** [ionic-team/capacitor#6674]
### Capacitor Version
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)
Android only

### Current Behavior
When `launchAutoHide: false` calling `SplashScreen.hide()` has no effect. 

### Expected Behavior
Splash screen should be hidden as is the case on iOS

### Other Technical Details
`yarn --version` output:
3.6.0

`node --version` output:
v18.15.0

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by MarcusAngel** [comment]
Apologies, somehow the splash screen plugin was installed twice, both as a dependancy and and a dev dependancy. Working fine.
