### ISSUE TITLE
bug:  App isn't installed notification after adding android:exported="false" in AndroidManifest.xml application activity 

### ISSUE THREAD

**Issue by aaravenalabs** [ionic-team/capacitor#6678]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/ios: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/core: 5.0.5

[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)

Android

### Current Behavior

After adding android:exported="false" in AndroidManifest.xml application activity, when opening the app in an android device, appears "App isn't installed" notification.

### Expected Behavior

The App should open

### Code Reproduction

Repo: https://github.com/aaravenalabs/android-export-issue-app.git
Steps: 
   1. Open file: android-export-issue-app\android\app\src\main\AndroidManifest.xml
   2. Set <activity  android:exported="true"> to false
   3. Run cap sync android
   4. Run cap open android
   5. Deploy app to a device
   6. Try to open the app

### Other Technical Details

`npm --version` output: 9.5.0

`node --version` output: v18.15.0

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
That's expected, if you open the `AndroidManifest.xml` in Android Studio it will show you a red warning on the `exported="false"` line saying
> A launchable activity must be exported as of Android 12, which also makes it available to other apps.

**Comment by aaravenalabs** [comment]
Ok, I did not noticed it, thanks so much
