### ISSUE TITLE
iOS xcode Project - No such module found ‘Capacitor’

### ISSUE THREAD

**Issue by vi354258** [ionic-team/capacitor#668]
Hi All,

I built a capacitor app using use Angular 6 and capacitor beta version. When I open the xcode project after running the 'npx cap add ios' command. It is showing an error stating "No such module found Capacitor " in AppDelegate.swift file.

<img width="1010" alt="screen shot 2018-07-22 at 2 43 57 pm" src="https://user-images.githubusercontent.com/29449105/43044606-d75fc8bc-8dc6-11e8-87a6-ded359e5c3a3.png">

Thanks in Advance.

**Comment by bitflower** [comment]
Had the same and did `pod install` inside `ios/App/App`. Maybe it helps you and the team to find the solution.

**Comment by sbannigan** [comment]
@vi354258 make sure you are opening the Xcode Workspace (`App.xcworkspace` instead of `App.xcodeproj`). You can also just run `npx cap open ios` and that should open the correct workspace.

**Comment by jcesarmobile** [comment]
Closing as there was no response after 2 weeks.

It's probably caused by opening the `.xcodeproj` instead of the `.xcworkspace`, that's why we have `npx cap open ios` command, to avoid this confusions.

**Comment by vi354258** [comment]
Yeah, Thankyou.

Sorry for the delay

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by oliverandersencox** [comment]
Just updated Angular and Ionic as per the guide on the beta 16 release and am having this same issue.

Have tried 'npx cap open ios' and clicking the .xcworkspace directly. None resolve the issue

**Comment by jcesarmobile** [comment]
Sometimes Xcode complains, but runs ok if you click the run button. Did you try?

**Comment by oliverandersencox** [comment]
So nothing worked - i ended up removing the ios project completely and running 'npx cap add ios' and it fixed the problem

**Comment by zeusstl** [comment]
In my case, an xcode upgrade was required to resolve this issue.
https://github.com/ionic-team/capacitor/issues/1396#issuecomment-489397834

**Comment by thakurvijendar** [comment]
> @vi354258 make sure you are opening the Xcode Workspace (`App.xcworkspace` instead of `App.xcodeproj`). You can also just run `npx cap open ios` and that should open the correct workspace.

I am trying to anaylze the application using xcodebuild, my command looks something like

xcodebuild -project App.xcodeproj -scheme App -sdk iphonesimulator12.4 clean analyze

and I am getting analyze failed error with cause no such module 'Capacitor'
import Capacitor

**Comment by kristianmandrup** [comment]
I'm having the same issue. Initially I followed the [Ionic - building for iOS page](https://ionicframework.com/docs/building/ios) but after following those steps I had a Podfile but no Pods folder with pods and no `.xcconfig` files.

Then I went to the `ios/App` folder and ran `pod install` which installed all the pods. However now it complains about no capacitor module.

I'm also told Conversion to Swift 5 is available. Not sure if I should try that or not. I'm also told to upgrade to recommended settings.

**Comment by eladnava** [comment]
Everyone facing this error even after opening the `*.xcworkspace` project in Xcode, make sure you haven't changed your `Deployment Target` in Project Settings to less than `11.0`.

**Comment by simonhaenisch** [comment]
> xcodebuild -project App.xcodeproj -scheme App -sdk iphonesimulator12.4 clean analyze
>
> and I am getting analyze failed error with cause no such module 'Capacitor'

@thakurvijendar I've just run into something similar as well and the problem is that you were trying to build the _project_ rather than the _workspace_.

```
xcodebuild -workspace App.xcworkspace -scheme App build
```

☝️ this works because the workspace also contains `Capacitor`, `CapacitorCordova` and `Pods-App`. Just thought I'd leave this here in case someone else tries building/archiving through the command line.

**Comment by jan-nick** [comment]
Still facing this issue after trying every fix mentioned here

**Comment by Sibi4** [comment]
I'm having the same issue. Capacitor pods are present in Podfile (I ran 'pod install inside iOS/App/App' ) but **AppDelegate.swift** is still complaining: **No such module 'Capacitor'**

platform :ios, '12.0'
use_frameworks!

//workaround to avoid Xcode caching of Pods that requires
//Product -> Clean Build Folder after new Cordova plugins installed
// Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityHttp', :path => '../../node_modules/@capacitor-community/http'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
