### ISSUE TITLE
bug: env(safe-area-inset-*) not working

### ISSUE THREAD

**Issue by marcelxpfeifer** [ionic-team/capacitor#6692]
## Bug Report
The css env vars for safe-area-insets are not being set to 0px inside the browser of capacitor.

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5
```

### Platform(s)

android and iOS

### Current Behavior

env(safe-area-inset-*) returns 0px even on devices that have a safe area.

<img width="565" alt="image" src="https://github.com/ionic-team/capacitor/assets/40826752/b8f93c15-a52f-4eb2-89f9-76f12d59b5c5">

### Expected Behavior

the env(safe-area-inset-*) should return device specific safe areas so the website inside capacitor can respect these safe areas.

### Code Reproduction

https://github.com/marcelxpfeifer/capacitor-missing-safe-areas

**Comment by kjr-lh** [comment]
Add `<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">` to the head of your html file

**Comment by marcelxpfeifer** [comment]
> Add `<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">` to the head of your html file

That's it thanks
