### ISSUE TITLE
Incorrect apkName variable in cli/src/run.ts and cli/src/config.ts for multi dimensional flavors

### ISSUE THREAD

**Issue by julienfdev** [ionic-team/capacitor#6703]
Hi there ! 

I've just noticed a bug  in the way the CLI handles multi-dimensional flavors on Android with Gradle 8+ (didn't try with earlier versions, but I don't see why it would be different)

https://github.com/ionic-team/capacitor/blob/d0ab34fb04d63d6feba496a7c2bd802b455861d6/cli/src/android/run.ts#L53C1-L53C1

### Steps to reproduce

From a blank project, add this to build.gradle : 

```
   flavorDimensions "branding", "environment"
    productFlavors {
        foo {
            dimension "branding"
            manifestPlaceholders = [ displayName:"Foo" ]
        }
        bar {
            dimension "branding"
            applicationId = "com.example.bar"
            manifestPlaceholders = [ displayName:"Bar" ]
        }
        prod {
            dimension "environment"
            manifestPlaceholders = [ envSuffix: '']
        }
        beta {
            dimension "environment"
            applicationIdSuffix = ".beta"
            manifestPlaceholders = [ envSuffix: " Beta" ]
        }
        alpha {
            dimension "environment"
            applicationIdSuffix = ".alpha"
            manifestPlaceholders = [ envSuffix: " Alpha" ]
        }
    }
``` 

multi dimensional flavor configurations are now : 
fooProd, fooBeta, fooAlpha, barProd, barBeta, barAlpha

the current code thus yields an apkName of, for example `app-fooProd-debug.apk`, while, for multi dimensional flavors, it should be : `app-foo-prod-debug.apk`, resulting in a `ENOENT` error. 
Launching with Android Studio is fine

I would gladly implement the fix myself but i'm not used to working on CLI tools.

Cheers !
Julien

**Comment by julienfdev** [comment]
I've changed my mind 😅 : #6704

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
