### ISSUE TITLE
bug: Android Galaxy, 1 file is not selected via input type=file multiple

### ISSUE THREAD

**Issue by fireonmac** [ionic-team/capacitor#6706]
It's not resolved yet on the latest dependencies (5.1.0) and the original issue was locked without any solution. 
You can see the original issue in the link below.

https://github.com/ionic-team/capacitor/issues/6305

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
