### ISSUE TITLE
Input of foreign letters (Swedish) not working on Android

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#671]
Hi.

Brand new Vue.js-project. Added only Capacitor as extra. Tried inputting Swedish letters (åäö) in input-fields. Doesn't work at all.

Tried on Samsung Galaxy Note 8 with standard Samsung Keyboard and also Swiftkey. 

Here I will also mention one thing which I have experienced. On pages with input-fields the app will feel very laggy and I feel somehow that this is also connected to the keyboard. Not sure though. The same page on the web is very smooth. 

Any thoughts about this?

**Comment by jcesarmobile** [comment]
Fixed in #673
