### ISSUE TITLE
bug: Selecting single image from Android gallery does not work with a multiple input field

### ISSUE THREAD

**Issue by theigl** [ionic-team/capacitor#6710]
### Capacitor Version
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.1.0
  @capacitor/core: 5.1.0
  @capacitor/android: 5.1.0
  @capacitor/ios: 5.1.0

Installed Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior

When you have a `<input multiple>` field and select a *single* image from the *Android Gallery*, the input field does not receive any data. It works fine when multiple images are selected or when selecting a single image from any other source.

We debugged the issue and found the root cause here:

https://github.com/ionic-team/capacitor/blob/1b8352dc5124dc3f57d7881d619537cbf8c3674b/android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java#L431

If we change the condition to > 0, then the input field behaves as expected.

### Expected Behavior

It should be possible to select a single image from the Android Gallery when using a multiple input field.

### Code Reproduction

Reproducer: https://github.com/divatzk/capacitor-file-upload-test

The reproducer contains only one page with a single and a multiple input field. To reproduce the issue, click on the multiple input field and select a single image from the Gallery. Nothing happens in this case. If you select 2 or more images, it works.

**Comment by theigl** [comment]
It looks like the problematic conditional has been in place since the very beginning: https://github.com/ionic-team/capacitor/pull/714

@jcesarmobile: Do you remember why you added `getItemCount() > 1`? We locally changed it to `getItemCount() > 0` and all our test-cases seem to work.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
