### ISSUE TITLE
bug: cordova-plugin-3dtouch onHomeIconPressed callback does not trigger

### ISSUE THREAD

**Issue by godhand1607** [ionic-team/capacitor#6712]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.1.1
  @capacitor/core: 5.1.1
  @capacitor/android: 5.1.1
  @capacitor/ios: 5.1.1

Installed Dependencies:

  @capacitor/cli: 5.1.0
  @capacitor/core: 5.1.0
  @capacitor/android: 5.1.0
  @capacitor/ios: 5.1.0

[success] iOS looking great! 👌
```

### Platform(s)
- iOS

### Current Behavior
- The `onHomeIconPressed` listener doesn't trigger whenever we press a shortcut/quick action

### Expected Behavior
- The `onHomeIconPressed` listener should trigger

### Other Technical Details

`npm --version` output: 9.6.7

`node --version` output: 20.3.1

`pod --version` output (iOS issues only): 1.21.1

### Additional Context
- Related issues:
    - https://github.com/EddyVerbruggen/cordova-plugin-3dtouch/issues/48
    - https://github.com/EddyVerbruggen/cordova-plugin-3dtouch/issues/32 

- The `onHomeIconPressed` listener works on cordova. 
- We're in the process of migrating to capacitor and currently doing an audit of the plugins that we use

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
