### ISSUE TITLE
bug:  Missing <manifest package=""> attribute in app/src/main

### ISSUE THREAD

**Issue by godhand1607** [ionic-team/capacitor#6713]
### Capacitor Version
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.1.1
  @capacitor/core: 5.1.1
  @capacitor/android: 5.1.1
  @capacitor/ios: 5.1.1

Installed Dependencies:

  @capacitor/cli: 5.1.0
  @capacitor/android: 5.1.0
  @capacitor/core: 5.1.0
  @capacitor/ios: 5.1.0

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)
- android

### Current Behavior
- Getting the android error below when running `npx cap doctor`
```
[error] Missing <manifest package=""> attribute in app/src/main
```

### Expected Behavior
```
[success] android looking great! 👌
```

### Additional Context
- The issue shows even on a newly scaffolded capacitor app, following the getting started docs https://capacitorjs.com/docs/getting-started

**Comment by davidkroeg** [comment]
Is it possible that the `npx cap doctor` still checks for the package attribute in capacitor 5.0.0 although this was moved to the build.gradle?

https://capacitorjs.com/docs/updating/5-0#move-package-to-buildgradle

I do have the same issue when running `npx cap doctor` but the project itself works fine.

**Comment by kevinswartz** [comment]
I am also seeing this same issue, any ideas?
```
npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main

```
