### ISSUE TITLE
Unable to install APK produced by Capacitor

### ISSUE THREAD

**Issue by Fanman03** [ionic-team/capacitor#6714]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.1.1
  @capacitor/core: 5.1.1
  @capacitor/android: 5.1.1
  @capacitor/ios: 5.1.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.1.1
  @capacitor/android: 5.1.1
  @capacitor/core: 5.1.1
```

### Platform(s)
Android

### Current Behavior
When attempting to install an apk produced by Capacitor via adb, I am recieving the following error:
```adb: failed to install app-release-signed.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]```

The apk file was built by selecting Project -> Prepare Release in the Visual Studio Code extension.

### Expected Behavior
The application should install, as it does on the Android Studio emulator.

### Code Reproduction
Here is my `capacitor.config.json` file for reference:
```{
  "appId": "com.fanman03.camviewerplusclient",
  "appName": "CamViewerPlus Client",
  "bundledWebRuntime": false,
  "webDir": "dist",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
  },
  "server": {
    "androidScheme": "https"
  }
}
```

`npm --version` output:
`8.19.2`
`node --version` output:
`v18.16.0`
`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
If you are building from the vs code extension, it looks like a problem with the vs code extension, not with Capacitor, you should report it there.

It's probably using jarsigner instead of apksigner
https://github.com/ionic-team/capacitor/issues/6284

**Comment by 1e4** [comment]
@Fanman03 Did you get this solved? I'm coming across the same issue even when using cli
