### ISSUE TITLE
bug: iOS app switching causes network lost error. 

### ISSUE THREAD

**Issue by odekappcraft** [ionic-team/capacitor#6733]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.1
  @capacitor/core: 5.2.1
  @capacitor/android: 5.2.1
  @capacitor/ios: 5.2.1

Installed Dependencies:

  @capacitor/cli: 4.8.1
  @capacitor/android: 4.8.1
  @capacitor/ios: 4.8.1
  @capacitor/core: 4.8.1

[success] iOS looking great! 
```

### Platform(s)

iOS

### Current Behavior

For a long running API call if we switch the app and come back , it throws network connection lost error. 
Also, makes a http status code 499 call. 

### Expected Behavior

It should keep the call running till it times out. 

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
