### ISSUE TITLE
bug: White screen issue in first opening

### ISSUE THREAD

**Issue by berkayclk** [ionic-team/capacitor#6734]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.2.1
  @capacitor/core: 5.2.1
  @capacitor/android: 5.2.1
  @capacitor/ios: 5.2.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.1.0
  @capacitor/ios: 5.1.0
  @capacitor/core: 5.1.0
```

### Platform(s)
- IOS

### Current Behavior

I'm trying to serve our web application as an ios app, but it is stuck on a white screen.  

### Expected Behavior
The frontend application should be rendered on webview.  

### Other Technical Details
 When I debug the capacitor source code, the path comes as an empty string "" to the router function. It comes for routing of "capacitor:/localhost" url. 

`npm --version` output: 8.19.4

`node --version` output: v16.20.0

`pod --version` output (iOS issues only): 1.12.1

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
