### ISSUE TITLE
bug: apk cannot be installed

### ISSUE THREAD

**Issue by zdu-strong** [ionic-team/capacitor#6737]
### Capacitor Version

![version](https://github.com/ionic-team/capacitor/assets/48673442/d6f71f98-5459-4dae-b350-4b9f1893eb72)

### Platform(s)
android

### Current Behavior
![InstallFailed](https://github.com/ionic-team/capacitor/assets/48673442/4fc81b60-7506-4f02-9ca8-45879f6325f6)

### Expected Behavior
apk installed successfully.

### Code Reproduction
Git Repository: [https://github.com/zdu-strong/temp-capacitor](https://github.com/zdu-strong/temp-capacitor)
Run Command: npm run make
Generated apk:  [https://github.com/zdu-strong/temp-apk/blob/master/app-release-signed.apk](https://github.com/zdu-strong/temp-apk/blob/master/app-release-signed.apk)

### Other Technical Details

`npm --version` output:
9.8.0
`node --version` output:
v18.16.1
`Windows System Info` output:
![windows](https://github.com/ionic-team/capacitor/assets/48673442/0c0166df-1115-41db-9689-264941cbd6a4)
`Android Studio Info` output:
![Android Studio](https://github.com/ionic-team/capacitor/assets/48673442/2d7aede1-773c-4779-a021-2214868a24f2)

**Comment by tiga05** [comment]
You should have a look in the android logs for a more specific reason. Most of the time the reason for not being able to install an app is written down there.

Use adb logcat or the log window of the android studio (which is also just  adb logcat) to track down the issue.

**Comment by zdu-strong** [comment]
I'm sorry, I can't understand the log, and there are too many logs.

In [my main repository](https://github.com/zdu-strong/Technical_Backup/tree/master/capacitor), with the same code, use android studio to build [the apk](https://github.com/zdu-strong/temp-apk-build-by-android-studio/blob/master/app-release.apk), install and use everything work fine.
I'm looking forward to using command line packaging, it's easier and faster.

**Comment by zdu-strong** [comment]
Has anyone ever used "npx cap build" to get an apk that works on android 13?
This command has never worked for me, and I'm not sure it works.

**Comment by zdu-strong** [comment]
I will try to build apk using other way.
