### ISSUE TITLE
bug: Camera Issue - getUserMedia API is not working on hostname localhost:8080

### ISSUE THREAD

**Issue by TShivaSantosh** [ionic-team/capacitor#6759]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.2.1
  @capacitor/core: 5.2.1
  @capacitor/android: 5.2.1
  @capacitor/ios: 5.2.1

[success] iOS looking great! 
```

### Platform(s)

iOS 16.5.1. Some versions of iOS 15 and all versions of iOS 16

### Current Behavior

Our application is using a third-party Vonage JavaScript library for virtual-visit flows, and the Vonage JavaScript library is internally using the getUserMedia() API to access the camera.

The getUserMedia() API is not working on the host capacitor://localhost:8080 in the latest iOS devices. We are getting Error code as AbortError and the error message "The operation was aborted." However, the getUserMedia API is working fine on the host capacitor://localhost in the latest iOS device. The hostname capacitor://localhost:8080 is in the secure context, as per the Feature Detection test in the MDN document https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts. I believe this is an issue with WKWebView, and I have created a WebKit issue asking for resolution (https://bugs.webkit.org/show_bug.cgi?id=259304).

We have been using localhost:8080 for a very long time, over 5 years, and this is the first time we have run into the issue while building virtual visit flows. In the long term, will we run into issues again since we have changed the default configuration? Should we switch back to the default configuration? If yes, how can we safely migrate critical data stored in ionic-storage from the hostname localhost:8080 to localhost? Please advise.

### Expected Behavior

    let video: any = document.querySelector("#videoElement");
    navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" }, audio:false })
    .then( (stream) => {
      video.srcObject = stream;
      video.play();
    })
    .catch( (e) => {
      // eslint-disable-next-line no-console
      console.log("Something went wrong!" + e.message);
    });

getUserMedia API should resolve to then with stream object instead of going to catch with AbortError

### Code Reproduction

Link to sample app that reproduces issue 
https://github.com/TShivaSantosh/ionic-sample-app-camera-issue

Steps to reproduce-

Run the sample app on device. 
Launch the application 
Camera permission should be requested, and the preview should be displayed inside the video element on the HTML page.

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

The GetUserMedia API on the domain capacitor://localhost:8080 is working for in the Android application, and when Angular is built locally, it is also functioning in the Safari browser on http://localhost:8080/.

The GetUserMedia API on the domain capacitor://localhost:8080 is working on iOS versions 14 till 15.5, but it is not working on iOS versions 15.5+ and 16.

**Comment by jcesarmobile** [comment]
This seems an iOS bug, Capacitor doesn't really do anything for the `getUserMedia` API to work, that's built-in in the WKWebView. It's working fine on iOS 17 beta, so looks like Apple fixed it already.

Anyway, not sure why would you want to set a port on the hostname, Capacitor doesn't use web server, so having a port on the hostname doesn't really do anything, if you remove the port the app will work.
