### ISSUE TITLE
feat: Allow access from native side on native plugins too

### ISSUE THREAD

**Issue by mlostekk** [ionic-team/capacitor#6760]
### Description

Right now I am using FirebasePerformance, but I want to start a trace on the native side (basically very early in onCreate) and then later in TS end the trace when the web app is actually rendered. This is really possible, are there plans to make this accessible?

### Platform(s)

All

**Comment by jcesarmobile** [comment]
This seems very specific to your needs, you can probably create your own plugin to do that.

**Comment by mlostekk** [comment]
@jcesarmobile , yep, unfortunately we scrapped all plugins and rewriting them ourselves
