### ISSUE TITLE
bug: Binary data gets wrapped in a json, breaking IOT devices that expect actual binary data

### ISSUE THREAD

**Issue by ZweiEuro** [ionic-team/capacitor#6763]
Hi!

Why does your library wrap binary data in a json struct?
 The TS side doesn't even provide any way to set "bodyType" for any request
https://github.com/ionic-team/capacitor/blob/f378edae9e87901ae2edbf8c339e401a60bfddf0/android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java#L382

I understand that it may be practical to infer datatype from the "content-Type" header field but there has got to be a better way to do this than:
1. silently discarding data no matter if it was set or not because content-type header field was missing. A warning if "Content-Type" === undefined && !contentType.isEmpty() is not too much to ask. This is incredibly confusing. https://github.com/ionic-team/capacitor/blob/f378edae9e87901ae2edbf8c339e401a60bfddf0/android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java#L192

2. Not providing any way to set the variable "bodyType". I can't find where or how to set this from the outside per request. (It's not documented anywhere) https://github.com/ionic-team/capacitor/blob/f378edae9e87901ae2edbf8c339e401a60bfddf0/android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java#L207C66-L207C66

3. Just assuming any data that is not "application/json" should be wrapped as such. https://github.com/ionic-team/capacitor/blob/f378edae9e87901ae2edbf8c339e401a60bfddf0/android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java#L217

You are 100% unable to send pure binary data, like a firmware, or specific IOT device control; and it wouldn't even be difficult.

What is the reasoning behind designing this this way?

**Comment by ZweiEuro** [comment]
Ah I just found this rather confusing piece of information
https://github.com/ionic-team/capacitor/blob/f378edae9e87901ae2edbf8c339e401a60bfddf0/android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java#L382

sets the variable as "dataType"

but the function internally renames it to "bodyType".

Even if i set it though it does not change the outcome; the first byte from the post data keeps being "{"

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
