### ISSUE TITLE
bug:  capacitor init proj-new io.ionic.starter --npm-client npm exited with exit code 1.

### ISSUE THREAD

**Issue by johnsnow0** [ionic-team/capacitor#6770]
### Capacitor Version

npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/ios: not installed
  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2

```
vilkas@Mrfox proj-new % ionic integrations enable capacitor
> npm i --save -E @capacitor/core

added 1 package, and audited 1182 packages in 16s

180 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
> npm i -D -E @capacitor/cli

added 43 packages, and audited 1225 packages in 8s

183 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
> capacitor init proj-new io.ionic.starter --npm-client npm
error: unknown option '--npm-client'
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor init proj-new io.ionic.starter --npm-client npm exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

### Platform(s)

MacOS 12.6.4

### Current Behavior

Command `ionic integrations enable capacitor` returns error: > capacitor init proj-new io.ionic.starter --npm-client npm
error: unknown option '--npm-client'
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor init proj-new io.ionic.starter --npm-client npm exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

### Expected Behavior

Expect to finish capacitor install with no errors.

### Code Reproduction

To isolate the cause of the problem, we ask you to provide a minimal sample application that demonstrates the issue.
For full instructions, see: https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction

### Other Technical Details

Please provide the following information with your request and any other relevant technical details (versions of IDEs, local environment info, plugin information or links, etc).

`npm --version` output:
8.3.1
`node --version` output:
v16.14.0
`pod --version` output (iOS issues only):
1.12.1
`ionic --version` output:
5.4.16 (actualy i have updated global ionic/cli version to the latest 7.1.1 and deleted old npm files also removed old ionic, but it still show version 5.4.16
### Additional Context

There was similar issue and the problem was solved with removing node_modules from wrong location. My project does not have this issue.

**Comment by jcesarmobile** [comment]
If you are getting version 5.4.16 when you run `ionic --version`, then Ionic CLI is not properly uninstalled.
If you are in macOS you can run `which ionic` and then `rm -rf` the path you got on the which command.

Anyway, the Ionic CLI repository is https://github.com/ionic-team/ionic-cli, if you have issues with Ionic CLI you should report the problems there (but still, this is not an Ionic CLI bug, it's a problem with your node install/config/caches)

**Comment by johnsnow0** [comment]
Thank you for advice, unfortunately it did not helped. Still same version, after removal. Then i was submitting this issue, i did not related it directly to my capacitor install error. If experts will tell, that i should go and look how to remove ionic properly and it will fix my capacitor error, i will try to do it.

**Comment by johnsnow0** [comment]
I made all these steps and even installed nvm and tried different node-npm combinations, but ionic --version still show the same 5.4.16 despite that ionic package.json show 7.1.1. I don't believe that this problem is so unique. Maybe someone will know the answer sooner or later...

**Comment by johnsnow0** [comment]
Finally i solved my problem based on this post https://stackoverflow.com/a/35495660/22167170. The problem was that for some reasons old ionic files there located at home dir/node_modules/ionic. I've deleted ionic folder and everything is working now. Ionic version upgraded to 7.1.1.
