### ISSUE TITLE
bug: Installing capacitor on a default vuetify project fails

### ISSUE THREAD

**Issue by deidyomega** [ionic-team/capacitor#6777]
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/core: 5.2.2

[error] Missing <manifest package=""> attribute in app/src/main

### Platform(s)
`uname -a`
Linux devserver 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior
Attempted to install capacitor on a vuetify (vue) project, failed

### Expected Behavior
Installing the default vuetify project, then installing capacitor should succeed.

### Code Reproduction
Sample: https://github.com/deidyomega/com.example.cap
Below code used to generate sample: 
`npm create vuetify` ==> Essentials (Vuetify, VueRouter, Pinia)
`npm run build`
`npm install @capacitor/core @capacitor/cli`
`npx cap init ExampleApp com.example.cap --web-dir=dist`
`npm run build`
`npm i @capacitor/android`
`npx cap add android`
`npm run build` <-- Fails

```
> com.example.cap@0.0.0 build
> vue-tsc --noEmit && vite build

/dev/com.example.cap/node_modules/vue-tsc/bin/vue-tsc.js:64
                        throw err;
                        ^

Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at getRelativePathFromDirectory (/dev/com.example.cap/node_modules/typescript/lib/tsc.js:5637:9)
    at relativeToBuildInfo (/dev/com.example.cap/node_modules/typescript/lib/tsc.js:117963:38)
    at toFileId (/dev/com.example.cap/node_modules/typescript/lib/tsc.js:117968:22)
    at arrayFrom (/dev/com.example.cap/node_modules/typescript/lib/tsc.js:715:24)
    at toFileIdListId (/dev/com.example.cap/node_modules/typescript/lib/tsc.js:117974:21)
    at /dev/com.example.cap/node_modules/typescript/lib/tsc.js:117897:32
    at mapDefined (/dev/com.example.cap/node_modules/typescript/lib/tsc.js:300:22)
    at getBuildInfo2 (/dev/com.example.cap/node_modules/typescript/lib/tsc.js:117893:26)
    at newProgram.getBuildInfo (/dev/com.example.cap/node_modules/typescript/lib/tsc.js:118145:41)
    at Object.getBuildInfo (/dev/com.example.cap/node_modules/typescript/lib/typescript.js:117443:70)
```

Node.js v18.16.0

### Other Technical Details

`npm --version` output:
9.5.1

`node --version` output:
v18.16.0

### Additional Context
I was able to reproduce this bug with literally nothing but the default vuetify project. I changed no code and got the error.

A more complete showing of the terminal i/o:
https://gist.github.com/deidyomega/3275eb4f5e486cfcae6bd36219949b68

**Comment by deidyomega** [comment]
Sample App:
https://github.com/deidyomega/com.example.cap

This follows the exact steps above to reproduce error

**Comment by jcesarmobile** [comment]
Thanks for the sample app.

I can reproduce, but I can also reproduce by just doing
```
npm create vuetify ==> Essentials (Vuetify, VueRouter, Pinia, typescript, npm) 
npm run build
npm run build
npm run build
```
So there seems to be something wrong with vuetify that breaks the app on the third `npm run build`, it's not related to Capacitor as I didn't do any of the Capacitor related steps and still failed.
