### ISSUE TITLE
Android: Do not use the == operator for String comparison in Java

### ISSUE THREAD

**Issue by moberwasserlechner** [ionic-team/capacitor#678]
In Java you should **never** compare Strings with the == operator because unlike Javascript it compares the object references and not the actual content.

Comparing with == might work because of sth called [String interning](https://en.wikipedia.org/wiki/String_interning) which is a VM optimization but it's not secure to rely on that and there are cases in which it definitely does not work.

I will create a PR as soon as I did some further testing.

BR, Michael

**Comment by mlynch** [comment]
Not sure what this is in reference to. If you see a specific issue in the Android code it's probably just a simple mistake. Would love a PR! Cheers

**Comment by moberwasserlechner** [comment]
Sry I made it sound more dramatic than it actually is ;)
