### ISSUE TITLE
bug: CapacitorHttp plugin issue with iOS (every other call).  Works with Android/Web app

### ISSUE THREAD

**Issue by thevariousartist** [ionic-team/capacitor#6789]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

[success] iOS looking great! 👌

### Platform(s)
iOS

### Current Behavior
Every other call to backend web service fails.

For the unsuccessful call, I see this error after the failure:
... (NSURLErrorDomain error -1000.)","message":"The operation couldn’t be completed"

For the successful call, I see this just before the call (not sure if this affects the next web service call):
... [NSURLSession sharedSession] may not be invalidated

### Expected Behavior
In iOS I Expect the web service call to succeed every time, rather than "every other time".
In Android it works every time.
In Web App it works every time.

### Code Reproduction
    try {
       const url = 'https://example.com/my/api';
       const options: HttpOptions = { url: url };
       const httpResponse: HttpResponse = await CapacitorHttp.get(options);
   } catch (error) {
     // ERROR in iOS only (every other call): 
     //     (NSURLErrorDomain error -1000.)","message":"The operation couldn’t be completed"
  }

### Other Technical Details
Ionic:

   Ionic CLI                     : 7.1.1 (/Users/me/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.2.0
   @angular-devkit/build-angular : 16.1.5
   @angular-devkit/schematics    : 16.1.5
   @angular/cli                  : 16.1.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : 5.2.2
   @capacitor/core    : 5.2.2
   @capacitor/ios     : 5.2.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.1 (/Users/me/.nvm/versions/node/v18.16.1/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

`npm --version` output: 9.5.1

`node --version` output: v18.16.1

`pod --version` output (iOS issues only): 1.12.1

### Additional Context
const config: CapacitorConfig = {
  plugins: {
    CapacitorHttp: {
      enabled: false,  // tried both FALSE and TRUE, but get same result
    }
  },
  webDir: 'www'
};

Tried the above config with and without but it made no difference to the result:
   iosScheme: 'https'

Backend web services are all "https" and have been working fine for years under Angular HTTP, Cordova HTTP plugins, etc.

Various links that seem relevant or are my other requests for help:
[https://forum.ionicframework.com/t/capacitorhttp-ios-error/231416](url)
[https://stackoverflow.com/questions/76764952/issue-with-capacitorhttp-on-ios](url)
[https://forum.ionicframework.com/t/capacitorhttp-ios-error/231416/6](url)

**Comment by jcesarmobile** [comment]
You shouldn't need to use `encodeURI(url)` for the plugin to work.
If you can provide a sample app we can take a look and try to fix it, if not, the issue will auto close in two weeks.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
