### ISSUE TITLE
bug: CORS error when loading local videos in iOS with live reload  

### ISSUE THREAD

**Issue by danbunkr** [ionic-team/capacitor#6797]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2
  @capacitor/cli: 5.0.5
```

### Platform(s)
Live reload on IOS

### Current Behavior
Per: https://github.com/ionic-team/capacitor/issues/4089 & https://github.com/ionic-team/capacitor/pull/6539 we should now be able to load local videos via fetch(localFilePath) in capacitor. This is fixed for images which was a result of PR 6539 but videos are still having the same CORS issue references in the 4089 bug.

![image](https://github.com/ionic-team/capacitor/assets/82471930/bcf2c529-f1cd-4da8-bf99-69e99246a906)

### Expected Behavior
Both local videos and images should be able to be accessed in live reload without CORs issues.

### Code Reproduction
Same Reproduction as: Just select a local video file instead
https://github.com/ionic-team/capacitor/pull/6539

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v16.18.1

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
