### ISSUE TITLE
bug: Capacitor Http & WKWebView on iOS 16.6

### ISSUE THREAD

**Issue by lexuantunght** [ionic-team/capacitor#6813]
## Bug Report
Capacitor Version: 5.2.3

Platform(s): iOS

### Current Behavior
- In iOS 16.3.1, Capacitor Http works well with Set-Cookie from server and send cookie but after I upgrade to iOS 16.6, all requests not send cookie. I check log from xcode and see: [NSURLSession sharedSession] may not be invalidated
- Like above issue, in iOS 16.6 if my app is minimized (not close), web view doesn't update. In my app, I make a countdown and it doesn't count until I restore app. However it works well in iOS 16.3.1

### Expected Behavior
It should work well like iOS 16.3.1

### Code Reproduction
Always in iOS 16.6
I think maybe Apple has updated some privacies in new version of iOS that can make WKWebView and Capacitor's plugins work incorrectly. 
Please take a look. Thanks!

**Comment by ItsChaceD** [comment]
Are you testing on a simulator or physical device?

**Comment by lexuantunght** [comment]
I tested on physical device: iPhone 12 Pro - iOS 16.6 due to no simulator  > 16.4 in my xcode

**Comment by lexuantunght** [comment]
Any update about this issue?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by mitschmidt** [comment]
@lexuantunght did you find a solution in the end? Facing a similar issue where we get reports from users with iPhone 12 Max Pro and iOS 16.6+ that our app is not working properly.

**Comment by seabamirum** [comment]
We were encountering the same issue, but it went away after trying a number of things--perhaps something to do with regexp syntax? Wish I could be more helpful.

**Comment by lexuantunght** [comment]
> @lexuantunght did you find a solution in the end? Facing a similar issue where we get reports from users with iPhone 12 Max Pro and iOS 16.6+ that our app is not working properly.

I switched to use cordova-plugin-advanced-http & cordova-plugin-advanced-websocket and it works correctly
