### ISSUE TITLE
bug: google maps market, could not load image svg dataUrl

### ISSUE THREAD

**Issue by CrackerakiUA** [ionic-team/capacitor#6824]
### Capacitor Version
"@capacitor/android": "^5.2.3",
"@capacitor/core": "^5.2.3",
"@capacitor/google-maps": "^5.3.0",
"@capacitor/ios": "^5.2.3",

### Platform(s)
Ios and Android

### Current Behavior
On android and ios, we don't see svg dataUrl

### Expected Behavior
Pins should be loaded properly also on android and ios

### Code Reproduction
```
const newMap = await GoogleMap.create({
	id: 'my-map', // Unique identifier for this map instance
	element: mapRef, // reference to the capacitor-google-map element
	apiKey: apiKey, // Your Google Maps API Key
	config: {
		center: {
			// The initial position to be rendered by the map
			lat: 33.6,
			lng: -117.9,
		},
		zoom: 8, // The initial zoom level to be rendered by the map
	},
});

const svgData = `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><circle cx="16" cy="16" r="10" fill="#FF5733" /></svg>`;
const svgUrl = 'data:image/svg+xml;base64,' + btoa(svgData);
await newMap.addMarker({
	iconUrl: svgUrl,
	coordinate: {
		lat: 33.6,
		lng: -117.9
	}
});
```
### Other Technical Details
Repo where you can have capacitor app with this marker loading:
https://github.com/CrackerakiUA/capacitor-google-map-pin-issue

`npm --version` output: 9.5.1

`node --version` output: v18.16.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment]
The native Google Maps SDKs don't support SVGs for icons, and the plugin doesn't support data urls neither.
>  iconUrl | string | Path to a marker icon to render. It can be relative to the web app public directory, or a https url of a remote marker icon. **SVGs are not supported on native platforms**.

https://capacitorjs.com/docs/apis/google-maps#marker

**Comment by CrackerakiUA** [comment]
Google Maps SDKs support SVGs for icons:
https://developers.google.com/maps/documentation/javascript/examples/marker-modern
It's very strange that you are not supporting dataUrls, how do you put custom markers on map, based on document which marker represent. This sounds like very common thing to have.

**Comment by jcesarmobile** [comment]
that's the javascript API, so it will work on web, but won't work on iOS or Android because they use the native Google Maps SDK. Sadly their native SDKs are not a 100% match with the javascript SDK, so the plugin can't be neither a 100% match on all platforms.
