### ISSUE TITLE
bug: Stopping a scroll with tap triggers underlying click event

### ISSUE THREAD

**Issue by aeharding** [ionic-team/capacitor#6826]
### Capacitor Version

- 5.2.3

### Platform(s)

- Android

### Current Behavior

Inside an Android Capacitor app, tapping the screen to stop a scroll in progress triggers the underlying HTML click event.

This can be especially apparent to users in a feed-based app such as [Voyager](https://github.com/aeharding/voyager).

### Expected Behavior

Stopping a scroll by tapping the screen should not trigger underlying HTML click event handler. This is the behavior everywhere else (iOS Capacitor, iOS Safari, and Android Chrome).

### Code Reproduction

The simple Ionic List example from `ionic start` (expanding the list with additional items so the view is scrollable) is enough to replicate. See test:

https://github.com/aeharding/test-scroll

#### Demonstrating the problem running inside @capacitor/android web view

Notice how tapping the screen with a scroll in progress navigates to the email detail page.

https://github.com/ionic-team/capacitor/assets/2166114/daeabf91-2ee8-44b3-937f-74b0c03322b0

#### Demonstrating the problem does not exist running inside Chrome

Notice how tapping the screen stops the scroll and does not navigate to the email detail page.

https://github.com/ionic-team/capacitor/assets/2166114/51f69188-61db-4f06-9b8b-27be38627eb7

## Maybe related?

- https://github.com/react-native-webview/react-native-webview/issues/3090
- https://github.com/react-native-webview/react-native-webview/issues/863
- https://stackoverflow.com/questions/51586395/touch-to-stop-momentum-scroll-also-fires-the-tap-event-in-webview
- https://forum.ionicframework.com/t/ionic4-5-android-dont-trigger-click-event-while-touch-stop-scrolling/196960

**Comment by aeharding** [comment]
Based on the related issues in react-native-webview, I suspect this is an Android Webview bug. I did not find an existing bug, so I have created a new Chromium bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1474135

**Comment by jcesarmobile** [comment]
I can reproduce on a regular WebView without Capacitor involved and it's also an issue in react native WebView, so it seems the WebView behavior.
I couldn't find any method to control this, so I'm going to close the issue.
Hopefully some Google engineer answers on your chromium bug and provides more information, I've starred it.
