### ISSUE TITLE
HTTP request responseType is never used by core native bridge, always set to 'text'

### ISSUE THREAD

**Issue by mariniu** [ionic-team/capacitor#6828]
I found the following line in CapacitorHttpPluginWeb, inner the method to perform an http request:

`let { responseType = 'text' } = response.ok ? options : {};`

It seems lead to a bug, cause the value of responseType should be read from `options.responseType` attribute as follow:

`let { responseType = 'text' } = response.ok ? options.responseType : {};`

Right now, in my implementazion (using capacitor 5.2.3) when I set responseType value in the options of the request, the result response takes always `'text'` value.

https://github.com/ionic-team/capacitor/blob/26f2ccdb44485155ce1788c4131f44c1454bd8eb/core/src/core-plugins.ts#L367C33-L367C33

**Comment by KrzysztofProgrammer** [comment]
Hi, I try to dig it more. 
Probably we have similar problem - I try to download pdf/image file as blob or arraybuffer by setting up responseType at request options. https://capacitorjs.com/docs/apis/http#httpresponsetype
Problem is with that plugin always response with string type. 
I'm try to debug it on Android.

Found this piece of code:
https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/assets/native-bridge.js#L575C46-L575C46
```
cap.nativePromise('CapacitorHttp', 'request', {...}).then(nativeResponse) => {
   type of nativeResponse.data  is always string, not base64 encoded data, not blob or arraybuffer
});
```

At CapacitorHttp.java ``public class CapacitorHttp extends Plugin`` there are support for requests and responses for this.
```
JSObject response = HttpRequestHandler.request(call, httpMethod, getBridge());
```
HttpRequestHandler support blobs using readStreamAsBase64. After this response is typed as JSObject. 

As I understand response from Java should be base64 encoded string. There is no direct support for blob in this class. 
Can't understand why I don't see at upper level base64 formatted data string.

I see only support at browser (web) implementation. I don't check web implementation, I'm focused on Android.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
