### ISSUE TITLE
onesignal-cordova-plugin error must not undeclare prefix (continued)

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/capacitor#683]
Follow-up to issue #637 onesignal-cordova-plugin error must not undeclare prefix

Still getting error: must not undeclare prefix.

Installed Ionic: 4.0.0-beta.0
Installed Capacitor: 1.0.0-beta.1
Create Ionic blank project.
Installed OneSignal cordova plugin: onesignal-cordova-plugin@2.4.1

This release of capacitor looks to have the fix from pull request #645
https://github.com/ionic-team/capacitor/pull/645
https://github.com/ionic-team/capacitor/compare/1.0.0-beta.1...master

My understanding is this is caused by empty values e.g. "". There are two empty strings in 
AndroidManifest.xml.

app/build/intermediates/manifests/full/debug/AndroidManifest.xml
```
<manifest xmlns:amazon=""
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.blank.app"
    android:versionCode="1"
    android:versionName="1.0" >
```

```
<meta-data
            android:name="onesignal_app_id"
            android:value="" /> <!-- Deprecated - Pulled from OneSignal dashboard. -->
        <meta-data
            android:name="onesignal_google_project_number"
            android:value="str:REMOTE" />
```

**Comment by jcesarmobile** [comment]
No, it has not been released yet.

In the diferences between master and beta 1 you can see this two commits:
[Add amazon schema to capacitor-android-plugins](https://github.com/ionic-team/capacitor/commit/ca6ead32bc66de8fb0160fa9145a72d411027262)
[Replace PACKAGE_NAME with the appId](https://github.com/ionic-team/capacitor/commit/12281488e555d527a0d847ed5056ac5ff0349b84)
Those are the ones fixing one signal problems
