### ISSUE TITLE
feat: capacitor camera plugin handling iOS permissions

### ISSUE THREAD

**Issue by javebratt** [ionic-team/capacitor#6830]
## Feature Request

Have Capacitor's camera plugin handle iOS permissions by default when using `pickImages()`

### Description

When we use the `pickImages()` function, the native iOS permission prompt shows up, if the user gives access to all of their images, the plugin works as expected, and everything is well.

But when the user clicks on `Select Photos...` to only give access to a subset of images, then the image picker currently shows ALL the devices images, instead of the images the user gave access to.

As shown in the video below:

https://github.com/ionic-team/capacitor/assets/7296623/444770cd-24b5-4cf7-95ae-4dbaa14e434c

That demo app has this feature isolated and the repo can be found here https://github.com/javebratt/capacitor-picker-test.

This is confusing for users and we would want to have the file picker only show the images the user already gave access to.

### Platform(s)

This is only affecting iOS

### Preferred Solution

If possible, it would be better for Capacitor to handle this under the hood and only show the user the images they already gave access to.

### Alternatives

The only alternative at the moment is to implement our own custom photo picker and use functions like `getLimitedLibraryPhotos`, and `pickLimitedLibraryPhotos`, to display the image thumbnails and allow the user to select from them.

This is all additional work, but the only way to achieve it right now.

**Comment by jcesarmobile** [comment]
That's the behavior of the native photo picker, it doesn't really need any permissions to pick the user images, the permission is for providing private information of the pictures such as the exif information, so when the user select some pictures, they are giving permission for accessing privacy information of those pictures, but the app can still access all the pictures.

I know it's confusing, but it's how Apple designed it.

All we could do is to not return the exif so the permission is not needed or add an option to tell the plugin to not request the permission or change the permission flow of the plugin all together, but there is no native picker that shows only the pictures the user selected.

**Comment by javebratt** [comment]
Thanks for the explainer 🙌🏼

**Comment by jaufgang** [comment]
> All we could do is to not return the exif so the permission is not needed or add an option to tell the plugin to not request the permission or change the permission flow of the plugin all together, 

For many purposes, uploading exif metadata is not necessary. It would be great to have an option to skip the permissions step and exclude exif metadata.
