### ISSUE TITLE
bug: iOS hostname ignored by iOS Save Password dialogue

### ISSUE THREAD

**Issue by emmernme** [ionic-team/capacitor#6833]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/ios: 5.2.2
  @capacitor/android: 5.2.2

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)
iOS

### Current Behavior
Our app has several Associated Domains (company.xy, company.xz, ...). In order to support password autofill, we have chosen a primary domain to be used as the hostname as `CapacitorConfig.server.hostname`. This seems to work fine – however, using [capacitor-ios-autofill-save-password](https://github.com/cuongpl/capacitor-ios-autofill-save-password) referenced from the [Capacitor guide](https://capacitorjs.com/docs/guides/autofill-credentials), iOS seems to mix up the domains, not using the provided hostname domain, but seemingly another domain at random from the Associated Domains.

### Expected Behavior
iOS should use the provided hostname as the domain used for password autofill & save, not a seemingly random domain from the Associated Domains.

`npm --version` output: 8.1.2

`node --version` output: v16.13.1

`pod --version` output (iOS issues only): `Ignoring ffi-1.14.2 because its extensions are not built. Try: gem pristine ffi --version 1.14.2
1.12.1`

### Additional Context
Ref. https://github.com/ionic-team/capacitor/issues/5633. 
I have tried re-arranging the Associated Domains in the App target in Xcode, changing the `hostname` to another domain, but nothing seems to change the domain which iOS chooses for password autofill & save.

Is there a way to ensure iOS uses a single domain for password autofill & save?

Bonus question: Would it be possible to programmatically choose what domain iOS uses for autofill&save from the included Associated Domains? This would enable password autofill for the different domains supported.

**Comment by emmernme** [comment]
This is virtually impossible to create a sample app to reproduce – it requires an app set up with two or more verified Associated Domains and a login screen. I don't have a set of testing domains with Associated Domains set up, so I hope this is possible to troubleshoot without a full project to reproduce – feel free to reach out if you want to screen share to see the issue & relevant code.

**Comment by jcesarmobile** [comment]
Sorry to hear that, it looks like an Apple/WKWebView issue to me since Capacitor doesn't control the native prompts, or a misconfiguration.
Try reporting the issue to the WebKit team on https://bugs.webkit.org/, but they will most likely also require a reproduction.
