### ISSUE TITLE
bug: top level await in `capacitor.config.ts` not working

### ISSUE THREAD

**Issue by ximex** [ionic-team/capacitor#6836]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0
```

### Platform(s)

ios, android

### Current Behavior

if i want to use a top level await in `capacitor.config.ts` for an import of another file i got an error.
i run: `npx --theme=xxxx cap sync`

### Expected Behavior

that a top level await works.

### Code Reproduction

the import statement is:
``const themeConfig = await import(\`./src/theme/${process.env.npm_config_theme}/config\`);``

in the `package.json` the prop `type` is set to `module`

### Other Technical Details

`npm --version` output: `8.18.0`

`node --version` output: `18.8.0`

### Additional Context

The stack trace of the error:
```
[error] Parsing capacitor.config.ts failed.
        
        /home/xxx/project/capacitor.config.ts:41
        const themeConfig = await Promise.resolve(`${`./src/theme/${process.env.npm_config_theme}/config`}`).then(s =>
        __importStar(require(s)));
        ^^^^^
        
        SyntaxError: await is only valid in async functions and the top level bodies of modules
        at Object.compileFunction (node:vm:360:18)
        at wrapSafe (node:internal/modules/cjs/loader:1048:15)
        at Module._compile (node:internal/modules/cjs/loader:1083:27)
        at require.extensions..ts
        (/home/thomas/develop/roc-web-app/node_modules/@capacitor/cli/dist/util/node.js:34:72)
        at Module.load (node:internal/modules/cjs/loader:997:32)
        at Module._load (node:internal/modules/cjs/loader:838:12)
        at Module.require (node:internal/modules/cjs/loader:1021:19)
        at require (node:internal/modules/cjs/helpers:103:18)
        at requireTS
        (/home/thomas/develop/roc-web-app/node_modules/@capacitor/cli/dist/util/node.js:36:15)
        at loadExtConfigTS
        (/home/thomas/develop/roc-web-app/node_modules/@capacitor/cli/dist/config.js:89:54)
```

**Comment by ximex** [comment]
i also try to do this changes: https://github.com/ionic-team/capacitor/pull/4299
but didn't solve the problem

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
