### ISSUE TITLE
Use of prompt(...) in native-bridge for CapacitorCookies/CapacitorHttp creates white flash / interrupts page transitions

### ISSUE THREAD

**Issue by agclark27** [ionic-team/capacitor#6840]
The addition of the CapacitorCookies and CapacitorHttp plugins has created an issue on iOS wherein any navigation from one page to another results in a temporary white flash. This is caused by Webkit stopping the rendering during the following two synchronous calls in native-bridge to check to see if the plugins are enabled:

https://github.com/ionic-team/capacitor/blob/03dd3f96c7ee75b6fff2b7c40d0c9a58fb04fce5/core/native-bridge.ts#L369

https://github.com/ionic-team/capacitor/blob/03dd3f96c7ee75b6fff2b7c40d0c9a58fb04fce5/core/native-bridge.ts#L457

The use of the synchronous prompt(...) hack isn't as problematic within the plugins themselves, but since the enablement check happens at document load when the script is injected, it creates this brief flash. If those checks are removed, the page loads just fine.

Since we'll know on the native side if the plugins are enabled, we could modify the creation of window.Capacitor to push in global variables that define whether or not the two plugins are enabled and thus avoid the need for the sync call in native-bridge.

https://github.com/ionic-team/capacitor/blob/03dd3f96c7ee75b6fff2b7c40d0c9a58fb04fce5/ios/Capacitor/Capacitor/JSExport.swift#L19

**Comment by agclark27** [comment]
Tagging @ItsChaceD

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
