### ISSUE TITLE
Building mobile app with capacitor only

### ISSUE THREAD

**Issue by LutzFelix2003** [ionic-team/capacitor#6851]
### Discussed in https://github.com/ionic-team/capacitor/discussions/6849

<div type='discussions-op-text'>

<sup>Originally posted by **Kalo2412** August 30, 2023</sup>
I have a web app build with the SAP ui 5 framework ( typescript ). I am trying to use the capaciroe only cli with its dependencies to build a mobile app. I have followed the starter guide for downloading all packages. Then the workflow is following.
npx cap add android
npx cap sync
npx cap open android

When i run the mobile app from the android studio. I get a blank web page. The logcat is saying localhost/index.js not found. I have not changed anything in the capacitor config file. What is the problem?

PS: on ios simulator it works !!!</div>

**Comment by jcesarmobile** [comment]
closing since there was no response
