### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by lfalkner** [ionic-team/capacitor#6855]
### Capacitor Version

```
@capacitor/core: 4.7.0
```
(also present in @capacitor/core: 5.x)

### Platform(s)

iOS, Android

### Current Behavior

Response headers are not added to an XHR request that is issued over the bridge when the casing does not match expectations. For example, XMLHttpRequest.prototype.getResponseHeader returns headers correctly regardless of casing.
E.g., getResponseHeader('My-Header') and getResponseHeader('my-header') should return the same value. 
CapacitorHttp XHR requests for the native-bridge must have correct casing to match the returned header. 

This means that integrations with third party libraries will break if they use the case insensitive nature of the web implementation.

### Expected Behavior

Native XHR requests should check for case insensitive headers on the response object

**Comment by lfalkner** [comment]
Thanks for updating; I've reached out via our support contact and will post back with any relevant information if possible

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
