### ISSUE TITLE
bug: Android CapacitorCookies.getCookies ignores url parameter

### ISSUE THREAD

**Issue by nickredding** [ionic-team/capacitor#6856]
### Capacitor Version
5.2.3 and 5.3.0

### Current Behavior

Prior to 5.2.3, the CapacitorCookies plugin getCookies returned the cookies associated with the url domain provided as a parameter.

As of 5.2.3 this plugin entry point ignores the url domain provided as a parameter and returns ALL cookies in document.cookie. This was done to exclude HTTPONLY cookies (https://github.com/ionic-team/capacitor/pull/6787).

Unfortunately, this change prevents retrieval of cookies from a specific domain since document.cookie includes cookies from all of the domains that have set cookies.

The solution should have avoided this by (a) retrieving the cookies associated with the provided domain using the original code, and (b) removing the cookies from the retrieved list that do not appear in document.cookie.

That way, only cookies set by the supplied domain that were not HTTPONLY would be returned.

**Comment by nickredding** [comment]
See https://github.com/nickredding/bug6792 which has been extended to demonstrate this problem.

**Comment by nickredding** [comment]
The fix is to modify getCookies in the module CapacitorCookies.java as follows

`
    @PluginMethod
    public void getCookies(PluginCall call) {
        String url = call.getString("url");
        HttpCookie[] urlCookies = cookieManager.getCookies(url);
        this.bridge.eval(
                "document.cookie",
                value -> {
                    String cookies = value.substring(1, value.length() - 1);
                    String[] cookieArray = cookies.split(";");

                    JSObject cookieMap = new JSObject();

                    for (String cookie : cookieArray) {
                        if (cookie.length() > 0) {
                            String[] keyValue = cookie.split("=", 2);

                            if (keyValue.length == 2) {
                                String key = keyValue[0].trim();
                                String val = keyValue[1].trim();
                                try {
                                    key = URLDecoder.decode(keyValue[0].trim(), StandardCharsets.UTF_8.name());
                                    val = URLDecoder.decode(keyValue[1].trim(), StandardCharsets.UTF_8.name());
                                } catch (UnsupportedEncodingException ignored) {}
                                for (HttpCookie urlCookie : urlCookies) {
                                    if (urlCookie.getName().equals(key)) {
                                        cookieMap.put(key, val);
                                        break;
                                    }
                                }
                            }
                        }
                    }
                    call.resolve(cookieMap);
                }
            );
    }`

**Comment by nickredding** [comment]
I have some comments on #6787 which was the motivation for changes in 5.2.3 to ensure HttpOnly cookies are not visible to Capacitor application code.

document.cookie was invented eons ago to enable Javascript front-end code to access and set cookies for the server. The expectation was that the Javascript front end was only dealing with a single domain (the domain of the server), and subsequent abuse of the document.cookie interface led to the creation of the HttpOnly attribute (https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies) to mitigate cross-site scripting attacks. It is this spec that #6787 used as the motivation to change CapacitorCookies.getCookies to ignore the url provided and simply return all of the cookies in document.cookie.

However, for Capacitor native apps, neither of these assumptions and rationales apply. Browsers cannot load Capacitor native apps so the security issue with cross-site scripting attacks does not apply. As well, Capacitor apps can easily deal with multiple servers (with different domains), so the assumption that document.cookie can represent an authoritative cookie store is not valid. Different domains could easily set cookies with the same name, resulting in collisions in document.cookie (which will only represent the most recent value set for the duplicate cookie name).

Indeed, the Capacitor Http.request plugin entry point happily circumvents CORS restrictions and provides the Set-Cookie headers to the Capacitor client code, contrary to the HTTP cookie spec (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) which states that the Set-Cookie header is a "forbidden response-header" for Javascript front-end code.

I'm not suggesting that Capacitor should enforce all of these restrictions. On the contrary, to do so would cripple Capacitor as an app platform.

However, I think the limitations of document.cookie should be acknowledged and the Capacitor platform should enable apps to access cookies stored agains a domain directly if using document.cookie is not feasible.

Therefore, the CapacitorCookies plugin should provide entry points getUrlCookie({url, name}) and getUrlCookies({url}) to retrieve cookies set against an url (bypassing document.cookie).

I'm going to post this in a couple of other places, hoping to get the attention of whoever owns the philosophy and implementation of the CapacitorCookies plugin.

**Comment by ItsChaceD** [comment]
> The fix is to modify getCookies in the module CapacitorCookies.java as follows
> 
> 
> ```
> @PluginMethod
> public void getCookies(PluginCall call) {
> 
>     String url = call.getString("url");
>     HttpCookie[] urlCookies = cookieManager.getCookies(url);
>     this.bridge.eval(
>             "document.cookie",
>             value -> {
>                 String cookies = value.substring(1, value.length() - 1);
>                 String[] cookieArray = cookies.split(";");
> 
>                 JSObject cookieMap = new JSObject();
> 
>                 for (String cookie : cookieArray) {
>                     if (cookie.length() > 0) {
>                         String[] keyValue = cookie.split("=", 2);
> 
>                         if (keyValue.length == 2) {
>                             String key = keyValue[0].trim();
>                             String val = keyValue[1].trim();
>                             try {
>                                 key = URLDecoder.decode(keyValue[0].trim(), StandardCharsets.UTF_8.name());
>                                 val = URLDecoder.decode(keyValue[1].trim(), StandardCharsets.UTF_8.name());
>                             } catch (UnsupportedEncodingException ignored) {}
>                             for (HttpCookie urlCookie : urlCookies) {
>                                 if (urlCookie.getName().equals(key)) {
>                                     cookieMap.put(key, val);
>                                     break;
>                                 }
>                             }
>                         }
>                     }
>                 }
>                 call.resolve(cookieMap);
>             }
>         );
> }
> ```

Thank you, I can make a PR for this fix.

...

As far as your other comment, I appreciate your perspective and the time you took to elaborate on the concerns.  I understand that Capacitor native apps are different from web applications and they inherently have different restrictions.

However, the change introduced in #6787 was motivated by a broader concern for security and privacy. While it is true that Capacitor apps should support multiple domains, allowing unrestricted access to HttpOnly cookies could potentially cause security vulnerabilities, especially since they are exposed to the WebView. 

Since Android has a limitation where it does not allow cookie properties to be accessed when retrieving them from the cookie store, there is no way to filter out httpOnly cookies at runtime without using the `document.cookie` getter on the WebView. 

We are actively looking at other solutions still that will allow multiple domains for cookie storage, while still respecting security concerns. For now, we will:
1. implement a PR incorporating the fix you suggested
2. Add flag in the capacitor config which will allow for the old functionality of retrieving all cookies from the cookie store, if enabled (#6899)

**Comment by nickredding** [comment]
Thank you for your response and proposed action on this.

I'd just like to point out that it is very easy for a Capacitor app developer to patch the code in CapacitorCookies and CapacitorHttp to remove any restrictions that these plugins impose to avoid security vulnerabilities. To me, it makes more sense to parameterize these restrictions so that developers can make their own decisions as to what to work with.

Note that developers of Javascript front-end code for web sites don't have similar abilities to patch out restrictions imposed by the browser platforms. That is the fundamental difference between a native Capacitor app and a web page.

**Comment by ItsChaceD** [comment]
> Thank you for your response and proposed action on this.
> 
> I'd just like to point out that it is very easy for a Capacitor app developer to patch the code in CapacitorCookies and CapacitorHttp to remove any restrictions that these plugins impose to avoid security vulnerabilities. To me, it makes more sense to parameterize these restrictions so that developers can make their own decisions as to what to work with.
> 
> Note that developers of Javascript front-end code for web sites don't have similar abilities to patch out restrictions imposed by the browser platforms. That is the fundamental difference between a native Capacitor app and a web page.

Yes they could patch out restrictions, but that would be at build time. We are mostly trying to be careful about introducing security vulnerabilities that an end user could take advantage of at runtime

**Comment by nickredding** [comment]
I'm not trying to be argumentative here, just trying to understand your concerns.

With apps downloaded from the Apple or Google app stores, the normal Javascript debugging tools are not available (Web Inspector on iOS and DevTools on Android don't work). Also, there is no way for an end user to get a Capacitor native app to make a request to a web server that it has not been developed to access. Neither of these limitations exist for web site front end code--it can be freely examined through browser debugging tools and requests to servers not configured by the front end developer are easy to execute via the debugging tools. Thus restrictions that exist to prevent abuse of web site front end code by end users are not relevant for Capacitor native apps.

The only exception to this for Capacitor apps would be if the app allows the end user to specify a web server to make a request to. In that case, the app developer explicitly exposed the app to security vulnerabilities which is frankly rather foolish and irresponsible, and almost certainly not necessary.

**Comment by ItsChaceD** [comment]
I understand where you are coming from and a lot of the security concerns can be mitigated by the app developer. But, we would rather be proactive and err to the side of caution. 

WebViews can be inspectable with normal dev tools if [webContentsDebuggingEnabled](https://developer.android.com/reference/android/webkit/WebView#setWebContentsDebuggingEnabled(boolean)) is enabled in the [config](https://capacitorjs.com/docs/config). A lot of apps still use this flag in production and we don't want to introduce security vulnerabilities for existing apps.

Aside from that, even if this is disabled, there are still ways to execute javascript or XSS attacks on the WebView via input forms, url params, etc. We want to take on the burden of preventing all exposure to threats, rather than placing blame on app developers. Especially since a lot of Capacitor users are web-developers first and would not expect `httpOnly` cookies to be exposed to the client.

 Therefore, the current best approach is to add an optional flag in the config to allow for insecure cookies to be retrieved

**Comment by nickredding** [comment]
OK thanks I'll leave it at that!

I hope you will address the other issues I raised with http.post, cookies and document.cookie (#6885, #6882, #6860 and #6792). They are all rather fundamental and I provided suggested code fixes for all of them.

**Comment by ItsChaceD** [comment]
Will do! Thank you again for the detailed reports, and especially for the reproductions & suggested code fixes. Will make things a lot smoother 😅
