### ISSUE TITLE
Bug : Capacitor Camera plugin does not open gallery to select photos for Android 13 and SDK 33 version

### ISSUE THREAD

**Issue by samadhansalunkhe1** [ionic-team/capacitor#6864]
### Capacitor versions
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/camera: 4.1.4

```
Current output : {camera: 'granted', photos: 'denied'}
```

### Platform(s)
Android 13 (Haven't tested on IOS yet) - Not working
Android 10 - Working

### Current Behavior
When user tries to open Gallery at the first time then he has getting permission prompt and if the user has allows that Picture and Video permission, then does not open gallery. When user click on allow permission option, then I call Camera.requestPermissions() and I expect to open device gallery to choose pictures, but instead the method directly returns error like `user has denied to access photos`.

### Expected Behavior
After allowing picture and video permission, then device gallery should open to select picture.

### Code Reproduction
       const checkPermission = await Camera.checkPermissions();

       if (checkPermission.photos == 'prompt') {
         const requestPermission = await Camera.requestPermissions();
         if (requestPermission.photos == 'granted') {
           StatusBar.hide();
           const image = await Camera.getPhoto({
             quality: 90,
             allowEditing: false,
             source: CameraSource.Photos,
             resultType: CameraResultType.Base64
           });

           if (image) {
             this.saveImage(image)
           }
         }
       } else {
         if (checkPermission.photos == 'denied') {
           const requestPermission = await Camera.requestPermissions();
           if (requestPermission.photos == 'granted') {
             StatusBar.hide();
             const image = await Camera.getPhoto({
               quality: 90,
               allowEditing: false,
               source: CameraSource.Photos,
               resultType: CameraResultType.Base64
             });

             if (image) {
               this.saveImage(image)
             }
           }
         }
       }

### Other Technical Details
    minSdkVersion = 22
    compileSdkVersion = 33
    targetSdkVersion = 33
    androidxActivityVersion = '1.4.0'
    androidxAppCompatVersion = '1.4.2'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.8.0'
    androidxFragmentVersion = '1.4.1'
    coreSplashScreenVersion = '1.0.0-rc01'
    androidxWebkitVersion = '1.4.0'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.3'
    androidxEspressoCoreVersion = '3.4.0'
    cordovaAndroidVersion = '10.1.1'

### Additional Context
Also, I tried with below Android permission plugin and READ_MEDIA_IMAGES permission but still facing same issue.

    @awesome-cordova-plugins/android-permissions: 6.4.0

   <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"></uses-permission>
   <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"></uses-permission>

    await this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.READ_MEDIA_IMAGES).then(async (res) => {
         if (res.hasPermission) {
           StatusBar.hide();
           const image = await Camera.getPhoto({
             quality: 90,
             allowEditing: false,
             source: CameraSource.Photos,
             resultType: CameraResultType.Base64
           });

           if (image) {
             this.saveImage(image)
           }
         } else {
           const getPermission = await this.androidPermissions.requestPermissions([this.androidPermissions.PERMISSION.READ_MEDIA_IMAGES]);
           if (getPermission.hasPermission) {
             StatusBar.hide();
             const image = await Camera.getPhoto({
               quality: 90,
               allowEditing: false,
               source: CameraSource.Photos,
               resultType: CameraResultType.Base64
             });

             if (image) {
               this.saveImage(image)
             }
           }
         }
       }, async (error) => {
         console.log('in error ', error);
         await this.androidPermissions.requestPermissions([this.androidPermissions.PERMISSION.READ_MEDIA_IMAGES]);
       });

**Comment by jcesarmobile** [comment]
for properly targeting SDK 33 you have to update to Capacitor 5
https://capacitorjs.com/docs/updating/5-0
