### ISSUE TITLE
bug: [iOS]'AppDelegate' has different definitions in different modules, build issue on integration with existing iOS App

### ISSUE THREAD

**Issue by uditajmera** [ionic-team/capacitor#6871]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/android: 5.0.3
  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/ios: 5.0.3
```

### Platform(s)

iOS

### Current Behavior

Created a [sample iOS app](https://github.com/uditajmera/capacitor_integration) and currently attempting to integrate Capacitor into the project. During the integration process, we added the Capacitor and Cordova frameworks to the sample project and are now encountering the following build issues.

As capacitor has dependency on Cordova, upon adding Cordova to the app, Cordova has public classes like AppDelegate and scrollView that cause build issues when integrated with the sample iOS app:
 i) The App has its own AppDelegate, and Cordova has a public AppDelegate.h inherited from NSObject, which causes the following error:
'AppDelegate' has different definitions in different modules; first difference is defined here found super class with type 'UIResponder'
 [https://github.com/ionic-team/capacitor/blob/0cc927ef5f0f7076a6d486d666d78483f1d71[…]/CapacitorCordova/CapacitorCordova/Classes/Public/AppDelegate.h](https://github.com/ionic-team/capacitor/blob/0cc927ef5f0f7076a6d486d666d78483f1d71c54/ios/CapacitorCordova/CapacitorCordova/Classes/Public/AppDelegate.h)
 
![Screenshot 2566-09-07 at 11 38 36 AM](https://github.com/ionic-team/capacitor/assets/7745409/7d129813-b8bc-4519-a80b-c0c90cda924f)

 
ii) ScrollView error displays as
Cannot override with a stored property 'scrollView'
In our code, we have UIView subclass that has “scrollView” property. This error seems to occur due to a conflict between these declarations, as observed here:
in [https://github.com/ionic-team/capacitor/blob/0cc927ef5f0f7076a6d486d666d78483f1d71[…]os/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.h](https://github.com/ionic-team/capacitor/blob/0cc927ef5f0f7076a6d486d666d78483f1d71c54/ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.h#L29C1-L29C1)

### Expected Behavior

After integration build should be successful

### Code Reproduction

Sample project which has build issues after Capacitor integation:
https://github.com/uditajmera/capacitor_integration

`npm --version` output: 9.8.0

`node --version` output:v18.10.0

`pod --version` output (iOS issues only):1.12.1

### Additional Context

As we know, Capacitor has a dependency on Cordova and  if App using Capacitor doesnt need to use Cordova plugins still app needs to import or add dependency on Cordova.

Would like to propose a solution that allows Capacitor to eliminate its dependency on Cordova and modularize the code. To address this issue, we propose implementing the Inversion of Control (IOC) design pattern, where Cordova will have a dependency on the Capacitor module, reversing the current scenario in which Capacitor depends on Cordova. We have attached a component diagram and sequence diagram to provide a clearer understanding.
Here are the key module changes:

### Capacitor:
1. Capacitor will incorporate Cordova’s public interfaces, currently utilized by Capacitor from Cordova. For example, CDVConfigParser, CDVPlugin, and CDVPluginManager interfaces.

2. CordovaProvider will be a singleton class with an optional property of type CordovaHelperProtocol. Configuring this property is optional, so if an app doesn’t require Cordova plugins, the app will not configure it. CordovaProvider will provide a public configure(:CordovaHelperProtocol) method, allowing the iOS app to configure or inject the CordovaHelper object from Cordova.

3. Capacitor will introduce a CordovaHelperProtocol interface containing all the necessary function declarations for accessing Cordova objects. Since Capacitor requires CDVPluginManager, CDVPlugin, and CDVPluginManager objects, the implementation of CordovaHelperProtocol will reside within Cordova. The iOS app will initialize and configure the CordovaHelperProtocol implementation in CordovaProvider. By implementing it in this manner, Capacitor will establish loose coupling with Cordova, enabling it to utilize Cordova’s functionality without direct dependency on it.
```
protocol CordovaHelperProtocol {
func getCDVPluginManager(parser: CDVConfigParser,
              viewController: UIViewController?,
              webView: WKWebView?) -> CDVPluginManager

func getCDVPlugin(webViewEngine: WKWebView)

func getCDVPluginmanager(parser: CDVConfigParser, viewController: UIViewController, webView: WKWebView)
}
```

4. The CordovaProvider object will use CordovaHelper to obtain all the objects required, as per the protocol declared in Capacitor. For example: CDVConfigParser, CDVPlugin, CDVPluginManager.

### Cordova:
1. Cordova will add a dependency on Capacitor.
2. Cordova will implement the CordovaHelperProtocol  declared in Capacitor.  CordovaHelperImpl  will implement `CordovaHelperProtocol ; it will initialize and return object as per protocol for eg:-
```
@implementation CordovaHelperImpl

- (id<CDVPluginManager> _Nonnull)getCDVPluginManagerWithParser:(CDVConfigParser * _Nonnull)parser viewController:(UIViewController * _Nullable)viewController webView:(WKWebView * _Nullable)webView {
    return [[CDVPluginManagerImpl alloc] initWithParser: parser viewController: viewController webView: webView];
}
```
3. Cordova will implement the protocols declared in Capacitor, such as CDVConfigParser, CDVPlugin, CDVPluginManager  whose implementation is already present in Cordova.

 Please review it and let us know your feedback. 
 Please find the attached diagrams - Component and sequence diagram for proposed solution.
 
![Screenshot 2566-09-05 at 6 12 59 PM](https://github.com/ionic-team/capacitor/assets/7745409/027745c8-e5d8-435f-abb4-d2ff37eb78c0)
![seq_dig (1)](https://github.com/ionic-team/capacitor/assets/7745409/98504f61-6c18-4133-9206-999f1ca2ed30)

**Comment by jcesarmobile** [comment]
It's a known issue documented on Portals
https://ionic.io/docs/portals/for-ios/known-issues#objective-c-app-delegate

The workaround is to rename your AppDelegate
