### ISSUE TITLE
bug: Android using https scheme + custom hostname cannot proxy api route to my server

### ISSUE THREAD

**Issue by vincentsartoko** [ionic-team/capacitor#6875]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/android: 5.3.0
  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

For several reasons, I need to use `androidScheme` as **https** and `hostname` as my website's domain (let's pretend it to be **domain.com**). Everything works until I need to fetch my server `https://domain.com/api/*`. From Logcat, looks like it fetches a local file which of course didn't exist. How can I proxy the requests with `/api/` prefix to not fetch local files and do remote request instead?

### Expected Behavior

Get response from my remote server `domain.com` when requesting with `/api/` prefix.

### Additional Context

Here is my capacitor.config.ts:

```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.appname.app',
  appName: 'appname',
  webDir: '../b/build',
  server: {},
  android: { path: '../a' },
  plugins: {
    GoogleAuth: {
      scopes: ['openid', 'profile', 'email'],
      androidClientId: 'xxx.apps.googleusercontent.com',
      forceCodeForRefreshToken: true
    }
  }
};

export default config;
```

**Comment by jcesarmobile** [comment]
You can't set the local domain to be the same as remote domain and expect it to work, if they are the same then the requests will go to the local "server" as it's happening, that's expected.
I think you can use a subdomain for the local or remote hostname, like using `local.domain.com` on the local "server" or `api.domain.com` for the remote server with the API and most things should still work.

**Comment by vincentsartoko** [comment]
My solution is to add a DNS A record called `proxy.domain.com` which points to my server.
