### ISSUE TITLE
`colorPrimaryDark` does not affect status bar color

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#688]
It is unclear is it intentional or a bug, but changing `colorPrimaryDark` in `colors.xml` does not change the color of the status bar — it always remains black.

**Comment by solojuve1897** [comment]
In android/app/src/main/res/values/styles.xml

You will find:

<style name="AppTheme.NoActionBar" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:background">@null</item>
    </style>

Add the following three inside the style-tag:

        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

This should work if you haven't changed other settings relevant to themeing.

**Comment by ArmorDarks** [comment]
These values are there by default, they are predefined by Capacitor template

**Comment by solojuve1897** [comment]
@ArmorDarks You changed the colors in colors.xml, that's good and should be enough one would argue but the connection between the default template and the colors isn't working. At least it don't in my setup. What I did was adding the above mentioned lines in the AppTheme.NoActionBar-style, after that the colors was changed in the app according to what I setup in colors.xml.

**Comment by ArmorDarks** [comment]
So, I suppose it should be marked as a bug in a supplied template?

**Comment by jcesarmobile** [comment]
`colorPrimaryDark` has no relationship or effect with the status bar color.
If you want to set the status bar color to the `colorPrimaryDark` you can add `<item name="android:statusBarColor">@color/colorPrimaryDark</item>` to the `AppTheme.NoActionBar` style. You can also use Status Bar plugin's javascript API https://capacitor.ionicframework.com/docs/apis/status-bar#method-setBackgroundColor-0
