### ISSUE TITLE
feat: iOS: Allow setting WebKit.WKProcessPool from outside to optimize memory usage.

### ISSUE THREAD

**Issue by i-pavlov** [ionic-team/capacitor#6887]
### Description
Currently, all the WKWebViews created by the Capacitor framework will use their own process pool to operate. And there is no way for users to provide their own WKProcessPool instance from outside the Capacitor framework or to configure the framework to share that pool internally. 

There are some [recommendations from Apple](https://developer.apple.com/documentation/webkit/wkprocesspool), where they suggest using it for apps with more than one WKWebView:

> If your app creates multiple web views, assign the same WKProcessPool object to web views that may safely share a process space. 

Also, seems like Framework users also do not have access to the WKWebViewConfiguration object, so there is no way to configure it without framework modification.

WebViews require **a lot** of RAM, and creating a new pool for each WKWebView increases app memory usage by a lot. That can be a problem, especially on low-end devices. For some websites, the numbers can be as 200+ MB per each.

### Platform(s)
iOS

### Preferred Solution

It would be great if the process pool could be configured from outside. Optional property in InstanceDescriptor could solve the problem. It also can be defaulted to nil, so will not affect any existing Capacitor user.

**Comment by jcesarmobile** [comment]
You can create a custom view controller with a custom webview and custom configuration or proccess pool

https://capacitorjs.com/docs/ios/viewcontroller
