### ISSUE TITLE
Yet another(?) Keypad-issue [Samsung Galaxy S8]

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#689]
Hi.

Another issue to report. Don't know exactly how to reproduce, I will just describe what happened. 

Did a build and ran the application through Android Studio for the first time with this specific device (Samsung Galaxy S8). The app opened but the textfields (email and password) on the login-page showed only a numerical keypad (a keypad one wants to show when input type is "number", which by the way never happens but I have already opened an issue regarding this), preventing me from being able to login at all of course. The e-mail-field has input type "text" and the password-field has input type "password". I closed the app and didn't care since the keypad has been quite buggy in my experience and was about to write an issue here. But when I opened the app again to see the same behavior I got the expected alpha-numerical keypad instead. I haven't been able to reproduce it again on the device.

Edit: This was on beta 1. Have since deployed beta 3 on all testing devices without it occuring. The incident maybe just should be ignored for now.

**Comment by ArmorDarks** [comment]
I experienced exactly the same issue on the first launch. However, I wasn't able to reproduce it either.

**Comment by jcesarmobile** [comment]
This also should be fixed with https://github.com/ionic-team/capacitor/pull/717 as it will use the default keyboard and not the simplified one that caused so many problems.
