### ISSUE TITLE
bug: downloadFile recursive not working Android

### ISSUE THREAD

**Issue by martinglover** [ionic-team/capacitor#6896]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/ios: 5.3.0

```

### Platform(s)

Android

### Current Behavior

When trying to download a file for the first time to a directory within cache I get an error, if I create the directory manually I stop getting an error
```
useFilesystem.ts:72 Error: Error downloading file: /data/user/0/com.appname/cache/pdf/category/filename.pdf: open failed: ENOENT (No such file or directory)
    at returnResult (VM3:853:32)
    at win.androidBridge.onmessage (VM3:828:21)
```

### Expected Behavior

`recursive: true` should generate the directory path

### Code Reproduction

```
await Filesystem.downloadFile({
  url,
  'pdf/category/filename.pdf',
  directory: Directory.Cache,
  recursive: true
});
```

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
