### ISSUE TITLE
bug: json parsing - #6170 reocurring

### ISSUE THREAD

**Issue by n-ext** [ionic-team/capacitor#6897]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.2.1
  @capacitor/core: 5.3.0
  @capacitor/android: 5.2.1
```

### Platform(s)

android, ios

### Current Behavior

https://github.com/ionic-team/capacitor/issues/6170 is reoccuring on 5.3.0

### Code Reproduction

Old issue repo can be used, just change versions to 5.3.0
https://github.com/JanMisker/Capacitor-JSONParseError

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by markemer** [comment]
Does it fail on the latest Capacitor 5 version?

**Comment by jcesarmobile** [comment]
I can't reproduce on 5.7.0, nor on 5.3.0
On the provided app an error is returned, but it's because the mocky url is down, I created a new mocky url that returns the same string and it's working fine on all Capacitor 5 versions I tried.

**Comment by n-ext** [comment]
This bug occurs on Capacitor 5 when API return string with `content-type: application/json`.

I've noticed that there is option to pass content type to CapacitorHttp, but you cannot override auto json parsing when this header is set. Allowing developers to override it will fix this issue.

**Comment by jcesarmobile** [comment]
Please, create a new issue with a sample app that reproduces the issue, the provided app didn't reproduce the issue.
