### ISSUE TITLE
Custom Splash Screen?

### ISSUE THREAD

**Issue by jsrbn** [ionic-team/capacitor#690]
Is it possible to set my own image or page as the default Splash Screen? I can only find options to hide or show it in the Documentation but not to change the appearance of it.

**Comment by wtrocki** [comment]
https://www.joshmorony.com/adding-icons-splash-screens-launch-images-to-capacitor-projects/

**Comment by ViniciusRio** [comment]
I was looking for something similar to Cordova, where it copies the CSS (https://tobiasahlin.com/spinkit/) and pastes it somewhere to use. Is there something similar in Capacitor?
