### ISSUE TITLE
bug: Capacitor 5 IOS not able to render pdf 

### ISSUE THREAD

**Issue by lim-enhui** [ionic-team/capacitor#6904]
### Capacitor Version

```
  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0
```

### Platform(s)

iOS

### Current Behavior

Not able to render Pdf onto iOS Native Web View

### Expected Behavior

Expected to render Pdf onto iOS Native Web View

### Other Technical Details

`npm --version` output:
npm: '9.5.0'
`node --version` output:
node: '18.15.0'
`pod --version` output (iOS issues only):
COCOAPODS: 1.12.0

### Additional Context

Currently, tested on Capacitor 5 unable to render the Pdf on iOS Native Device. Angular 16 and ngx-extended-pdf-viewer is able to render properly onto Web and onto Capacitor v4 iOS Native Device. Rolling back to Capacitor 4.

**Comment by lim-enhui** [comment]
https://github.com/lim-enhui/glow-mobile/tree/main

```
Working version build on ios device: "@capacitor/ios": "4.8.1", "@capacitor/core": "4.8.1"
the pdf is not able to render on Capacitor v5
```

**Comment by jcesarmobile** [comment]
I've tested your sample app and the pdf was rendering, then updated `@capacitor/core` and `@capacitor/ios` to 5.3.0 and the pdf was still rendering.

Are you testing on real devices or simulators?
What's the iOS version you have tested?
I've seen it fail to render with both Capacitor versions on iOS 17, but randomly, it sometimes works and sometimes it doesn't work, so that looks more like a problem in the library and not related to the Capacitor version.

**Comment by lim-enhui** [comment]
I will need to do more test.

**Comment by lim-enhui** [comment]
```
Same branch: https://github.com/lim-enhui/glow-mobile/tree/main

I commit some minor change using capacitor http.. 

First, build the ionic capacitor build ios
Second, ionic serve to let it be acting host server.
 
Working version build on ios device: "@capacitor/ios": "4.8.1", "@capacitor/core": "4.8.1"
the pdf is not able to render on Capacitor v5

```

**Comment by lim-enhui** [comment]
Hi team the reproduction is added last week. Please check out the code and run ionic capacitor build ios. Run ionic serve for a hosting server. The pdf is not able to run on capacitor 5 but able to run on 4.X.

**Comment by jcesarmobile** [comment]
Now I can reproduce, but because you changed the code to use blob, it's not working on 4.x nor on 5.x, because blob is not supported by Http plugin at the moment, there is another issue about that
https://github.com/ionic-team/capacitor/issues/6126
