### ISSUE TITLE
bug: capacitior http is not sending post request data since 5.4.0

### ISSUE THREAD

**Issue by Nikhil1920** [ionic-team/capacitor#6916]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.4.0
  @capacitor/core: 5.4.0
  @capacitor/android: 5.4.0
```

### Platform(s)

Currently tested on android

### Current Behavior
post requests with plain text body is not being sent

### Expected Behavior
the body should be sent

### Code Reproduction
```js
let res = await fetch(encodeURI(`some post endpoint`), {
		method: 'POST',
		headers: {
			'Content-Type': 'text/plain'
		},
		body: `some plain text body`
	});
```

### Additional Context
Working as expected with 5.3.0 version

**Comment by ximex** [comment]
we also have problems with `fetch` since `5.4.0`. don't know if it's the same problem but we see this error message: `Cleartext HTTP traffic to localhost not permitted`
we are fetching a file from `http://localhost/config.json`
don't ask why. it's deprecated code 😅

**Comment by Nikhil1920** [comment]
@ItsChaceD Thanks for the quick resolution 5.4.1 fixed the issue

@ximex this should help you https://capacitorjs.com/docs/updating/5-0#update-androidscheme basically you are trying to fetch a non https domain from a https domain and it is getting blocked

**Comment by ximex** [comment]
looks like this fixed my issue: https://github.com/ionic-team/capacitor/pull/6954
