### ISSUE TITLE
Electron: Automatically adapt base-path

### ISSUE THREAD

**Issue by fifafu** [ionic-team/capacitor#693]
For electron apps the base path must not be "/" because otherwise it will be unable to load any referenced files. It should either be not set or "./".

It would be great if this could be done automatically.

**Comment by nasiruddin-saiyed** [comment]
Angular Cli supports for various options, i prefer to use while building, as
`ng build --prod --base-href=./`

for more options you can refer https://github.com/angular/angular-cli.

**Comment by jcesarmobile** [comment]
Capacitor is framework agnostic and shouldn't edit user files, so I'm going to close this as it's Angular specific and @nasiruddin-saiyed explained how to do it with the angular cli.
So you'll have to run with `--base-href=./` to build before doing the `npx cap copy electron`.
