### ISSUE TITLE
bug: Playstore deployment error, AIDL detected

### ISSUE THREAD

**Issue by vincentsartoko** [ionic-team/capacitor#6930]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/core: 5.3.0

[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
When creating a release on Playstore, I stumbled across this error message:

We've detected that one or more of the app bundles included in this release are using the following Play Billing Library versions: AIDL
These are unsupported versions of Google Play Billing. Upgrade to a supported version to publish this app. [Learn More.](https://developer.android.com/google/play/billing/deprecation-faq)

These are the plugins that I use on my capacitor app:
```
"@capacitor-community/admob": "^5.1.1",
"@capacitor/android": "^5.3.0",
"@capacitor/app": "^5.0.6",
"@capacitor/browser": "^5.1.0",
"@capacitor/cli": "^5.3.0",
"@capacitor/clipboard": "^5.0.6",
"@capacitor/core": "^5.3.0",
"@capacitor/dialog": "^5.0.6",
"@capacitor/preferences": "^5.0.6",
"@capacitor/share": "^5.0.6",
"@capacitor/splash-screen": "^5.0.6",
"@capacitor/status-bar": "^5.0.6",
"@capawesome/capacitor-app-update": "^5.0.1",
"@capawesome/capacitor-file-picker": "^5.1.0",
"@codetrix-studio/capacitor-google-auth": "^3.3.2"
```

Please leave a message if you could solve this issue 🙏

**Comment by jcesarmobile** [comment]
Capacitor doesn't use Play Billing Library, so must be some of your plugins.
But I don't know which one, sorry.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
