### ISSUE TITLE
bug: Wrong width/height, wrong scale

### ISSUE THREAD

**Issue by mrmrmystery** [ionic-team/capacitor#6931]
### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1

[success] Android looking great! 👌
```

### Platform(s)

android

### Current Behavior

Every dimension seems to be divided by about two. When I create a div with a width of 1000px it fills about two thirds of the screen which is 2800px wide (visible in attached image). Also canvas look blurry because they are somewhat scaled up. When I call window.innerWidth or window.innerHeight i also get wrong values. The value are about half of the actual display size. I checked the viewport scales but everything is set to 1.0.

### Expected Behavior

Width and height should be the values the device actually has

### Code Reproduction

create a div with width = 1000px
```
<div style="height: 100px; width: 1000px; background-color: blueviolet;">

</div>
```

### Other Technical Details

Application was created with the ionic vs-code extension. The framework I selected was vue and I selected the platforms web and android. I run the application on an galaxy tab s7+ with a resolution of 2800x1752 pixels.

`npm --version` output: 10.1.0

`node --version` output: v20.7.0
![Screenshot_20230922_191342](https://github.com/ionic-team/capacitor/assets/73742423/1602e659-0cf8-4e35-ae02-72eb49592e0c)

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
