### ISSUE TITLE
Beta3 breaks IOS Angularfire2/firebase integration

### ISSUE THREAD

**Issue by ghq2340** [ionic-team/capacitor#694]
Beta3 breaks Angularfire2/firebase integration ( https://github.com/angular/angularfire2 ), when IOS app is launched, it opens the auth firebase URL, then a network error is shown on the screen, similar behavior was reported on issue #667 

![1 cap_ios_redirect](https://user-images.githubusercontent.com/41524283/43373314-ab15a7c6-935d-11e8-8317-aca602a997fc.png)

![2 cap_ios_networkerror](https://user-images.githubusercontent.com/41524283/43373315-b00c5838-935d-11e8-9bd1-058a32a03d0a.png)

**Comment by ghq2340** [comment]
@mlynch any suggestions?

**Comment by jcesarmobile** [comment]
Did you try in Android? Or only iOS?

I've tried on Android and wasn't able to make it work, nor on iOS, only on web.
It's my first time trying angularfire2, so I'm probably missing something.

Can you provide a sample project where I just have to put my credentials and run it? And also tell me if I have to enable something in firebase console.

**Comment by ghq2340** [comment]
Only happens on IOS during the component’s constructor initialization (hello.component) here’s how you can recreate the problem (ionic 3, 4 are also impacted):

1. Download this test Project (Top Bar / EXPORT): https://stackblitz.com/edit/angular-cy2kel

2. Install packages and fix project structure (starkblitz bug - https://github.com/angular/angular/issues/23962):
cd angular-cy2kel
npm install
mv src/angular.json . && rm -rf src/src/environments/ && mv src/src/* src/ && rm -rf src/src/

3. Add your firebase configuration in app.module.ts ( https://firebase.google.com/docs/web/setup )

   export const firebaseConfig = {
       apiKey: "xxxxxxxxxx",
       authDomain: "your-domain-name.firebaseapp.com",
       databaseURL: "https://your-domain-name.firebaseio.com", 
       projectId: "your-domain-name,
       storageBucket: "your-domain-name.appspot.com",
       messagingSenderId: '<your-messaging-sender-id>'
   };

4. Run npm run build

5. Run “ng serve” to validate the app, If you get this error “Cannot read property 'write' of undefined” read:
   https://stackoverflow.com/questions/51303264/angular-cli-cannot-read-property-write-of-undefined

6. Install/configure capacitor 1.0.0-beta.3
   npm install --save @capacitor/cli@1.0.0-beta.3 @capacitor/core@1.0.0-beta.3
   npx cap init [appName] [appId]

7. Change capacitor’s "webDir" from “www” to "dist" in capacitor.config then run the IOS App
	npx cap add ios
        npx cap open ios (run it)
   
    “Issue #694 has been reproduced here”

8. To recreate issue #667, close/terminate the running App then disconnect the network (wired or wifi) from your test station then run the IOS  app again

**Comment by jcesarmobile** [comment]
Those were really helpful steps to reproduce.

Fixed in @capacitor/ios@1.0.0-beta.4 `npm install --save @capacitor/ios@1.0.0-beta.4`

Also update @capacitor/cli and @capacitor/core for other bugfixes

I've been able to reproduce #667, will look into it.

**Comment by ghq2340** [comment]
During Android test I noticed that the presence of "google-services.json" is now mandatory I believe "Push notifications" is the peace asking for it. Building an app that doesn't need Push notifications or uses a different provider will also be required to configure it, I guess the easy fix is to disable the plugin in "android/app/build.gradle" --->"apply plugin: 'com.google.gms.google-services'", sounds a little ugly and requires an additional step in the building pipeline maybe it should be document somewhere.
