### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Badkill3487** [ionic-team/capacitor#6941]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.8.1
  @capacitor/core: 4.8.1
  @capacitor/android: 4.8.1

### Platform(s)
Web

### Current Behavior
When I run a http post request and get a 204 the output is a JSON parse error.
The ResponseType of the request is json because 200 when data is available and 204 when there is no data available.
As far as I understand the WebPlugin a response with type json will always be run with JSON.parse.

### Expected Behavior
A 204 Response should not be run through JSON.parse

### Code Reproduction

- run app with ionic serve
- send HTTP request, with  responseType json. to any API which returns 204 HTTP code
- check browser console

**Comment by jcesarmobile** [comment]
Capacitor 4 is out of Maintenance.
Try updating to Capacitor 5 and if the issue persists, please, create a new issue and provide a sample app where the issue can be reproduced.
