### ISSUE TITLE
bug: Ionicons not loading - Failed to connect to localhost/127.0.0.1:80

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/capacitor#6944]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/ios: 5.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- Android 8.1 (Umidigi One)
- Android 13 (Samsung Galaxy)

### Current Behavior

Ionicons are not showing up. CapacitorHttp is enabled! 

Frameworks:
- Angular 15
- Ionic 7

The following error get thrown multiple times:
```bash
polyfills.js:1220 Unhandled Promise rejection: Failed to connect to localhost/127.0.0.1:80 ; Zone: <root> ; Task: null ; Value: Error: Failed to connect to localhost/127.0.0.1:80
    at returnResult (VM3:913:32)
    at win.androidBridge.onmessage (VM3:888:21) Error: Failed to connect to localhost/127.0.0.1:80
    at returnResult (http://localhost/:917:32)
    at win.androidBridge.onmessage (http://localhost/:892:21)
```

<img width="949" alt="Bildschirmfoto 2023-09-28 um 13 10 39" src="https://github.com/ionic-team/capacitor/assets/39862171/ca525bec-32a0-44a7-94c5-30bcc6c9b327">

Seems like this happened before: https://github.com/ionic-team/capacitor/issues/5947

### Expected Behavior

All Icons should show up. 

### Code Reproduction

I simply ran `yarn cap sync android` and launched the app using Android Studio.

### Other Technical Details

`npm --version` output: 9.6.7

`node --version` output: v18.17.1

`pod --version` output (iOS issues only):

**Comment by mariusbolik** [comment]
Here is an example project: https://github.com/mariusbolik/ionicons-not-showing

I started a new ionic angular project and enabled Capacitor HTTP.

**Comment by willmav5000** [comment]
I've been encountering the same issue described in this thread. In my case, the problem arises when CapacitorHttp is enabled. I've traced it back and found that this bug was introduced in version 5.4.0 of @capacitor/core.

The temporary solutions I found are to either downgrade to version 5.3.0 or disable CapacitorHttp, both of which make the icons visible again.

**Comment by waltercruz** [comment]
I was about to report the same bug!

To reproduce is simple, just create a tabs project from ionic start. Add the android support. Build it the CapacitorHttp enabled and ionicons won't show. Disable CapacitorHttp and ionicons show again.

My temporary solution was to downgrade @capacitor/core to 5.3.0

**Comment by dimitr0v** [comment]
We have the same issue..
