### ISSUE TITLE
bug: geolocation plugin not requesting gps permissions

### ISSUE THREAD

**Issue by DarknessRisesFromBelow** [ionic-team/capacitor#6945]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1

[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)

android

### Current Behavior

running Geolocation.requestPermissions() returns an error saying it does not exist, and the popup never shows up

### Code Reproduction

```
import { Geolocation, Geoposition } from '@ionic-native/geolocation';
const App: React.FC = () => {
    Geolocation.requestPermissions();
   return (<IonApp>
		<IonReactRouter>
			<IonTabs>
			<IonRouterOutlet >
				<Route exact path="/home">
				<Tab1 />
				</Route>
			</IonRouterOutlet>
			<IonTabBar slot="bottom" id="appTabBar">
				<IonTabButton tab="tab1" href="/home" >
				<IonIcon icon={home}/>
				<IonLabel>Home</IonLabel>
			</IonTabBar>
			</IonTabs>
		</IonReactRouter>
		</IonApp>
);
```

### Other Technical Details

`npm --version` output: 9.6.5

`node --version` output: v18.12.1

`pod --version` output (iOS issues only):

### Additional Context

see issue #1762 for other people facing same issue

**Comment by DarknessRisesFromBelow** [comment]
also, removing the Geolocation.requestPermission(); line and trying to get location returns an error saying location permission wasn't accepted

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
