### ISSUE TITLE
Push Notifications Plugin on iOS undefined

### ISSUE THREAD

**Issue by danielsimon1** [ionic-team/capacitor#696]
In the pull request https://github.com/ionic-team/capacitor/pull/633 push notifications for iOS have been included as a native Capacitor plugin. I tried to use the plugin in my iOS app unsuccessfully.
This is my code:

```
const { PushNotifications } = Plugins;
PushNotifications.register()
  .then(() => console.log('registering successful'))
  .catch((error) => console.error(error));
```

I'm getting the following error at run time:

> TypeError: undefined is not an object (evaluating 'PushNotifications_1.register')

What I noticed when debugging with the Console app is, that no `CAPPushNotificationsPlugin` gets registered.

Edit: I'm running the latest capacitor version (beta3)

**Comment by jcesarmobile** [comment]
Is it a new app or an existing app?

**Comment by danielsimon1** [comment]
It's an existing app. I recently upgraded capacitor to beta3.

**Comment by jcesarmobile** [comment]
In that case, you have to update `@capacitor/ios` too as it doesn't get updated on cli update.

And add this changes we added to the template as your app was created with an old template that didn't have that
https://github.com/ionic-team/capacitor/commit/91c59486ee4250b5212fe665c10bf43721b050ad

**Comment by jcesarmobile** [comment]
Oh, there is a bug, it appears as `register` on the typescript definitions but had it as `requestPermissions` in the native code. Try with `requestPermissions()` for now, but I'll rename it to register on next version.

**Comment by danielsimon1** [comment]
`PushNotifications` is not undefined anymore, thanks for helping me to resolve this issue.
But now if I call `requestPermissions`, the Promise never gets resolved, even though it seems that the device successfully received a token. Also the event `didRegisterForRemoteNotificationsWithDeviceToken` never gets fired.

**Comment by jcesarmobile** [comment]
Did you add the methods I mentioned?

You also have to enable push notifications in your project capabilities section, that will create the required entitlements file and also add push capabilities for your provisioning profile

**Comment by danielsimon1** [comment]
Everything working now, thanks!

**Comment by qanuj** [comment]
this looks to be back with

``TypeError: PushNotifications.requestPermissions is not a function. (In 'PushNotifications.requestPermissions()'

**Comment by jcesarmobile** [comment]
It’s requestPermission
