### ISSUE TITLE
feat: Support suspending functions in Kotlin plugins (copy of #6550)

### ISSUE THREAD

**Issue by codepushr** [ionic-team/capacitor#6964]
### Description
Allow Kotlin suspending function as Capacitor plugin methods.

### Platform(s)
Android

### Alternatives
Currently we have to use simple non-suspending functions and use callbacks for reporting Plugin results.

### Additional Context
Copy of #6550

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by ngmiduc** [comment]
I was also wondering about how to use a kotlin supsense function inside a capacitor plugin!
