### ISSUE TITLE
Ionic capacitor Android: bug microphone api when calling getUserMedia

### ISSUE THREAD

**Issue by gregoiregentil** [ionic-team/capacitor#6967]
If I access getUserMedia in an Android Ionic app, I get an error if audio = true. If audio is false, there is no error. It was working "before" until a few weeks ago so something somehow broke recently.

> ionic start react blank --type angular
> ionic cap add android
> ionic cap sync android
> ionic cap open android

Add permissions to the Manifest.xml file:

> uses-permission android:name="android.permission.CAMERA"
> uses-permission android:name="android.permission.RECORD_AUDIO"
> uses-permission android:name="android.permission.RECORD_VIDEO"

Add the following code:

> ionViewDidEnter() {
> 	this.test();
> }
> 
> async test() {
> 	const t = await navigator.mediaDevices.getUserMedia({ audio:true, video: { facingMode: 'environment' } });
> }
> 

The error is the following (not the call to microphone):

> 
> ERROR Error: Uncaught (in promise): NotAllowedError: Permission denied
>     at Y (polyfills.441dd4ca9dc0674f.js:1:16047)
>     at polyfills.441dd4ca9dc0674f.js:1:15137
>     at polyfills.441dd4ca9dc0674f.js:1:15243
>     at d (main.6a8cd5614a1ac0a6.js:1:368881)
>     at pe (main.6a8cd5614a1ac0a6.js:1:369100)
>     at v.invoke (polyfills.441dd4ca9dc0674f.js:1:6632)
>     at Object.onInvoke (main.6a8cd5614a1ac0a6.js:1:150995)
>     at v.invoke (polyfills.441dd4ca9dc0674f.js:1:6572)
>     at h.run (polyfills.441dd4ca9dc0674f.js:1:1998)
>     at polyfills.441dd4ca9dc0674f.js:1:16842
> handleError @ main.6a8cd5614a1ac0a6.js:1
> next @ main.6a8cd5614a1ac0a6.js:1
> next @ main.6a8cd5614a1ac0a6.js:1
> _next @ main.6a8cd5614a1ac0a6.js:1
> next @ main.6a8cd5614a1ac0a6.js:1
> (anonymous) @ main.6a8cd5614a1ac0a6.js:1
> he @ main.6a8cd5614a1ac0a6.js:1
> next @ main.6a8cd5614a1ac0a6.js:1
> emit @ main.6a8cd5614a1ac0a6.js:1
> (anonymous) @ main.6a8cd5614a1ac0a6.js:1
> invoke @ polyfills.441dd4ca9dc0674f.js:1
> run @ polyfills.441dd4ca9dc0674f.js:1
> runOutsideAngular @ main.6a8cd5614a1ac0a6.js:1
> onHandleError @ main.6a8cd5614a1ac0a6.js:1
> handleError @ polyfills.441dd4ca9dc0674f.js:1
> runGuarded @ polyfills.441dd4ca9dc0674f.js:1
> s.microtaskDrainDone @ polyfills.441dd4ca9dc0674f.js:1
> T @ polyfills.441dd4ca9dc0674f.js:1
> Promise.then (async)
> X @ polyfills.441dd4ca9dc0674f.js:1
> C @ polyfills.441dd4ca9dc0674f.js:1
> scheduleTask @ polyfills.441dd4ca9dc0674f.js:1
> onScheduleTask @ polyfills.441dd4ca9dc0674f.js:1
> scheduleTask @ polyfills.441dd4ca9dc0674f.js:1
> scheduleTask @ polyfills.441dd4ca9dc0674f.js:1
> scheduleMicroTask @ polyfills.441dd4ca9dc0674f.js:1
> ee @ polyfills.441dd4ca9dc0674f.js:1
> Y @ polyfills.441dd4ca9dc0674f.js:1
> (anonymous) @ polyfills.441dd4ca9dc0674f.js:1
> (anonymous) @ polyfills.441dd4ca9dc0674f.js:1

**Comment by gregoiregentil** [comment]
A demo project is available at https://tmp.gentil.com/micro.tbz2

**Comment by jcesarmobile** [comment]
Microphone usage also needs `<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>`, there is a warning in logcat about that
> Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording

It's been always like this because in Capacitor 1-2 we included that permissions in the default app template, but removed it in Capacitor 3 when we moved the plugins out and removed all the permissions except for the internet one.

https://github.com/ionic-team/capacitor/blob/2.x/android-template/app/src/main/AndroidManifest.xml#L57-L62C5

**Comment by gregoiregentil** [comment]
MODIFY_AUDIO_SETTINGS was missing. Thank you. I still don't get it why it was working with Capacitor 4 just before. Never mind.
