### ISSUE TITLE
bug: Build failed because Capacitor.swiftmodule is missing a required architecture. 

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/capacitor#6968]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Xcode Version 15.0 (15A240d) / ios

### Current Behavior

Trying to run the app via xcode on a simulator output the bellow message
<img width="530" alt="Screenshot 2023-10-07 at 17 46 52" src="https://github.com/ionic-team/capacitor/assets/12111716/f9008ed2-8b0d-4177-b1ce-b429e05c2d55">

### Other Technical Details

`npm --version` output: 8.3.1

`node --version` output: v16.14.0

`pod --version` output (iOS issues only): 1.13.0

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
