### ISSUE TITLE
bug: Activity with result is always returning `ActivityResult{resultCode=RESULT_CANCELED, data=null}`

### ISSUE THREAD

**Issue by shashwatmi** [ionic-team/capacitor#6972]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
```

### Platform(s)
Android

### Current Behavior
i am always getting ActivityResult{resultCode=RESULT_CANCELED, data=null}, when Starting Activity with `startActivityForResult`

### Expected Behavior
Should get result i set in Started Activity through Activity Result.

### Code Reproduction
flow looks like this.

Plugin -> Activity -> SDK Activity.

SDK Activity Returns the result to Activity through Intent and Activity returns Result through ActivityResult
```

@CapacitorPlugin(name = "Esign")
public class Esign extends Plugin{

    @PluginMethod()
    public void echo(PluginCall call) {
        // Create Intent Here
        startActivityForResult(call, eSign, "handleMessage");
    }

    @ActivityCallback
    private void handleMessage(PluginCall call, ActivityResult result){
       // Handle Callback Here.
    }
}
```
Activity Looks Like this
```

if(sdkResponseJson != null){
            Log.e("sdkResponse",sdkResponseJson);
            Intent resultIntent = new Intent();
            resultIntent.putExtra("resp", sdkResponseJson);
            setResult(RESULT_OK,resultIntent);
            finish();
        }


```

**Comment by shashwatmi** [comment]
@jcesarmobile The Code example provided, in Issue is exactly the crux of it. If you can guide me a bit more about details required i will be more than happy to add them.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
