### ISSUE TITLE
bug: Capacitor 5 crashes on IOS on loading a Go static lib

### ISSUE THREAD

**Issue by envoyant** [ionic-team/capacitor#6974]
### Capacitor Version

```
npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.4.2
  @capacitor/ios: 5.4.2
  @capacitor/core: 5.4.2

[success] iOS looking great! 👌
```

### Platform(s)
IOS

### Current Behavior
The test Ionic/Capacitor application links to a native static library and returns a string which is displayed in the console log. A static library written in C with a single function works as expected. If the same functionality is implemented in Go the following output is observed in the console log:

WebView failed provisional navigation
Error: The file "public" couldn't be opened.

This happens the moment any function in the static library is called from Swift. If the library is imported but no functions are called from Swift the application works as per normal (presumably the linker optimises the library out).

The application worked as expected in Capacitor v3. Capacitor v5 exhibits the above behaviour.

### Expected Behavior
It should display the string returned by the function in the static library.

### Code Reproduction
https://github.com/envoyant/capacitorLoadGo.git

### Other Technical Details

Xcode 14.3.1
go version go1.21.2 darwin/arm64

`npm --version` output:
9.6.7
`node --version` output:
v18.17.1
`pod --version` output (iOS issues only):
1.12.1

### Additional Context
The readme.md contains building and test execution instructions.

**Comment by jcesarmobile** [comment]
I'm not able to build the go library, can you provide a sample app that has the go library already built and also a capacitor 3 app where it was working.

**Comment by envoyant** [comment]
The Go library is actually already built. Executing the following command will install the built Go library:

cp golib/build/iphone/libgolib.* ios/App/golib/

The built C library can be copied into the IOS project by:

cp clib/libgolib.? ios/App/golib/

**Comment by envoyant** [comment]
I don't know how to create a Capacitor v3 project from scratch as it is created from the Ionic CLI. I did go down the route of trying to downgrade Capacitor from v5 to v3 and was not convinced that it is working correctly. We have an existing Ionic / capacitor application that uses a library written in a combination of Go and C++. We were forced by the Android App store to upgrade Capacitor from v3 to v5. This broke the ability to link in the static lib on IOS (it works well enough on Android). To prove that the project is otherwise functional under IOS I created a stubbed library in C. When this is used the application works perfectly. The conjecture is that it has something to do with the initialisation of the Go runtime environment and that something has changed from Capacitor V3 to V5. I also created a small Swift iPhone app that has no problem loading and using the library in question.

**Comment by alex-steinberg** [comment]
@jcesarmobile I've created a [Capacitor plugin](https://github.com/alex-steinberg/capacitor-plugin-c-go-static-libraries/tree/master) and example app clearly explaining the issue here.

You should be able to run it fairly quickly to see the issue. We'd greatly appreciate any support you can give, even if it's sending us in the right direction.

We would have taken out a support contract yesterday but we're a tiny African company without the funds at this stage. Thanks in advance 🙏

**Comment by alex-steinberg** [comment]
@jcesarmobile @dotNetkow to update you, we've pivoted to recompiling our libraries to WASM. Capacitor doesn't seem able to handle the Go library on the native side (https://github.com/alex-steinberg/capacitor-plugin-c-go-static-libraries/tree/master).

Is this generally your recommended approach (using WASM), or is Capacitor intended to work well with static libraries? This seems a rather under-documented part of the ecosystem, so just checking with y'all here.

**Comment by bosbaber** [comment]
@envoyant made some progress which I believe he will post here tomorrow. He discovered that if he makes minor changes to the swift router then the problem disappears. We don't really understand why the issue occurs and we are worried that this points to some kind of underlying concurrency issue. By overriding the router with our patch we seem to have found a workaround.

**Comment by envoyant** [comment]
The problem has been isolated. The behaviour of the following line of Swift code changes when a static Go library is linked. The behaviour per se has nothing to do with Capacitor, a native Swift iPhone app exhibits the problem. Capacitor 5's Router class is however dependent on it and breaks when a Go library is statically linked. Presumably the initialisation of the Go runtime has this as side effect. As Swift is not an open source language it is not that easy to investigate any further. The simple test case creates an instance of the URL class, specifically wrapping a file:

let fileUrl = URL(fileURLWithPath: "")
print("fileUrl:'\(fileUrl.absoluteString)'")

Without a linked static library or a C library the print produces a string:

fileUrl:'file:///'

Capacitor5 depends on this behaviour in the Router class. When a Go static library is linked for some reason or other the default initialisation changes and the same code now produces a string similar to:

fileUrl:'file:///private/var/containers/Bundle/Application/[guid value]/testApp.app/'

The guid is generated for each run.

By specifically changing the initialisation to:

let fileUrl = URL(fileURLWithPath: "/")

the problem disappears, at least from a Capacitor5 perspective and the result of the initialisation is always:

fileUrl:'file:///'

Apple's documentation simply states:

If the path is an empty string, the system interprets it as “.”.

Using this as explicit initialisation:

let fileUrl = URL(fileURLWithPath: ".")

renders the exact same result as the empty string. The resultant URL really looks like the path of the application on phone. For the moment the conclusion is thus that the Go runtime initialisation changes the concept of the local application folder. Whichever way this is regarded, this would seem to be really unwanted behaviour that the Go runtime initialisation should change the "home" directory for the entire app.

**Comment by envoyant** [comment]
Given that we now have a workaround we will no longer be pursuing this bug.

**Comment by alex-steinberg** [comment]
Wow! Unexpected behaviour. Great find @envoyant!

Would love to know if you're the only people in the world linking a static Go library to a Capacitor app, let alone an iOS app...

**Comment by Gaal123** [comment]
Hello @alex-steinberg I've face the same problem but I'm only share the plugin with GO, hence I can not ask to the final developer to made the same work around. Can I ask to still consider to patch it in the way was suggested by [envoyant](https://github.com/envoyant)? Meanwhile I'll open a ticket to GO team to understand why of this behavior and try to resolve it definitly. 
Thanks in advance
