### ISSUE TITLE
feat: CLI command to just copy the Capacitor configuration file

### ISSUE THREAD

**Issue by oliveryasuna** [ionic-team/capacitor#6977]
### Description

If I am working in development mode, I will configure `capacitor.config.json` to point to a dev server. If I just change `capacitor.config.json`, I will execute `cap copy`. This seem inefficient, since `cap copy` also copies the build output to platform directories.

### Platform(s)

N/A.

### Preferred Solution

There should be a command that just copies `capacitor.config.json` to platform directories.

Or maybe add `--no-build` flag to `copy`.

### Alternatives

I wrote a script to copy the file to respective places.

**Comment by jcesarmobile** [comment]
The OS already provide command for copying files, so we are not going to provide wrappers around it, the CLI is supposed to be simple, so adding a command for copying a single file just makes it slightly more complex for little benefit.

**Comment by oliveryasuna** [comment]
@jcesarmobile And what does it do now? Copy files. What's the difference?

**Comment by oliveryasuna** [comment]
Also, with respect, your opinion is not maintainable. What if, for whatever reason, you decide to change the layout to platform folders and `capacitor.config.json` is placed somewhere else? Now, my script is broken.

It seems that my use case is a very common one, and developers should not have to wait for the build dir copy.

**Comment by jcesarmobile** [comment]
It does more things than copying files, it generates and copies other needed files.
If we add a copy capacitor.config.json, then somebody else will ask for a command to copy just the cordova.js, other for copying the capacitor.plugins.json, and we will end up with 100 copy commands.

If we change the place where the capacitor.config.json you'll have to adjust, we will do it in a major version release and we will document it.

**Comment by oliveryasuna** [comment]
@jcesarmobile You have convinced me; I agree with you. Still, maybe there is room for something in between. Perhaps exported methods that resolve the path to where `capacitor.config.json` is placed in platform directories.
