### ISSUE TITLE
feat: Support java v21

### ISSUE THREAD

**Issue by zdu-strong** [ionic-team/capacitor#7014]

**Comment by jcesarmobile** [comment]
There is nothing to do on Capacitor side, the supported java versions depend on gradle, we update gradle versions on major releases with the latest version available, users can update their apps whenever they want.

For supporting java 21 you have to use gradle 8.4, which is not officially supported by latest Android Studio, not even by the latest canary version
https://docs.gradle.org/current/userguide/compatibility.html
https://developer.android.com/build/releases/gradle-plugin

**Comment by zdu-strong** [comment]
Thanks.
