### ISSUE TITLE
"The data couldn’t be read because it isn’t in the correct format" when parsing empty data object  as JSON

### ISSUE THREAD

**Issue by BigPackie** [ionic-team/capacitor#7018]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@capacitor/ios@5.2.2` for the project I'm working on.

The `tryParseJson` method errors out and fills the `data` part of the response with "The data couldn’t be read because it isn’t in the correct format" This happens when the optional `data` parameter in the `buildResponse` method is not null but instead it is empty. 

Extending the guard to also take into account an empty data parameter fixes this issue.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift b/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift
index ea990d3..bbc8f8b 100644
--- a/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift
+++ b/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift
@@ -124,7 +124,7 @@ open class HttpRequestHandler {
         output["headers"] = response.allHeaderFields
         output["url"] = response.url?.absoluteString
 
-        guard let data = data else {
+        guard let data = data, !data.isEmpty else {
             output["data"] = ""
             return output
         }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
