### ISSUE TITLE
App doesn't officially go into 'background' state

### ISSUE THREAD

**Issue by mval1002** [ionic-team/capacitor#702]
Hi Capacitor team! I'd like to start by saying I'm very impressed with this project! I can't wait to see what's in store for the future!

But in the meantime I've run into a strange issue - My app doesn't register as in the background when I hit Home. While I wait for a more official push (FCM, specifically) implementation, I'm using [phonegap-push-plugin](https://github.com/phonegap/phonegap-plugin-push), and it wen't quite smoothly... until I tried to get a background notification. They would only be shown when I swiped the app out of recents. As a short term fix, I have used the forceShow setting which will show the app even in the foreground. This is obviously not ideal, since if the app is ACTUALLY in the foreground getting push notifications is unexpected and distracting.

I used the appStateChange listener, and it shows the app is no longer active after hitting Home:

```
D/Capacitor: App paused
D/Capacitor: Saving instance state!
D/Capacitor: Firing change: false
             Notifying listeners for event appStateChange
D/Capacitor: App stopped
D/Capacitor: callback: -1, pluginId: Console, methodName: log, methodData: {"level":"log","message":"App state changed. Is active? false"}
I/console: App state changed. Is active? false
```

 but it seems there may be something missing, as the system believes otherwise! Any information or advice would be very appreciated!

**Comment by jcesarmobile** [comment]
This is for Android, right?
What's the plugin version you are using?

**Comment by mval1002** [comment]
Thanks for the very quick response!

Yes, I'm using Android (I'm dreading making it work on iOS - I don't have access to a Mac at the moment).

I'm using the latest version of both the phonegap-push-plugin (2.2.3) and Capacitor (beta 3). Nexus 5X on Android 8.1.0.

**Comment by jcesarmobile** [comment]
I think it was fixed by https://github.com/ionic-team/capacitor/pull/791 as it adds support for the cordova events (pause, stop, destroy, etc)
