### ISSUE TITLE
Error: "CapacitorCookies.getCookie()" is not implemented on android

### ISSUE THREAD

**Issue by mikmikmik** [ionic-team/capacitor#7027]
### Capacitor Version

Latest Dependencies:
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:
  @capacitor/cli: 5.5.1
  @capacitor/ios: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
Android

### Current Behavior
In Chrome console:
```
Uncaught (in promise) Error: "CapacitorCookies.getCookie()" is not implemented on android
    at chunk-vendors.1b351493.js:3:2616
```

### Expected Behavior
To be implemented the same way as CapacitorHttp.

### Additional Context
I upgraded to Capacitor 5 so had to replace Community http plugin with CapacitorHttp and CapacitorCookies.
added this in capacitor.config.json :
```
"plugins": {
    "CapacitorHttp": {
      "enabled": true
    },
    "CapacitorCookies": {
      "enabled": true
    },
```
Synced, build, cleared Android studio cache, synced project with gradle files... still got the same error blocking my app.
Also tried this proguard rule:
`-keep public class * extends com.getcapacitor.Plugin`

**Comment by mikmikmik** [comment]
Oh I didn't see it was not even a method... so I should have used this:
```
const getCookies = () => {
  return document.cookie;
};
```

**Comment by jcesarmobile** [comment]
yeah, there is no `getCookie` at the moment, only `getCookies`
there is a feature request here https://github.com/ionic-team/capacitor/issues/6859
