### ISSUE TITLE
bug: CapacitorCookies.getCookies() returns empty object

### ISSUE THREAD

**Issue by mikmikmik** [ionic-team/capacitor#7029]
### Capacitor Version

Latest Dependencies:
@capacitor/cli: 5.5.1
@capacitor/core: 5.5.1
@capacitor/android: 5.5.1
@capacitor/ios: 5.5.1

Installed Dependencies:
@capacitor/cli: 5.5.1
@capacitor/ios: 5.5.1
@capacitor/core: 5.5.1
@capacitor/android: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
Android

### Current Behavior
It returns an empty object

### Expected Behavior
It should return a refresh token cookie I can see in the DevTools for http://localhost when I debug/inspect

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
