### ISSUE TITLE
bug: Capacitor Http and Native Bridge don't handle ReadableStream

### ISSUE THREAD

**Issue by philjones88** [ionic-team/capacitor#7032]
### Capacitor Version

```
npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
```

### Platform(s)

iOS (only tested)

### Current Behavior

calling `fetch('url', { method: 'POST', body: new URLSearchParams([ ['foo', 1], ['bar', true] ])`

results in https://github.com/ionic-team/capacitor/blob/main/core/native-bridge.ts#L475 `Request` being made with a body of `ReadableStream`

which is passed through `convertBody` https://github.com/ionic-team/capacitor/blob/main/core/native-bridge.ts#L54

onto `cap.nativePromise` which fails with a `DataCloneError: The object can not be cloned.` in `postToNative`

### Expected Behavior

you can call `fetch` with the first parameter being a string url and the body being in the second parameter

### Other Technical Details

`npm --version` output: `9.8.1`

`node --version` output: `18.18.0`

`pod --version` output (iOS issues only): `1.10.1`

**Comment by philjones88** [comment]
Investigating and debugging more:

https://github.com/ionic-team/capacitor/blob/main/core/native-bridge.ts#L57

This doesn't seem to work, I had planned to expand it to cover `URLSearchParams` but the `body` property of the `Request` object is a `ReadableStream` so not sure how `instanceof` would ever work...

**Comment by philjones88** [comment]
Here's a sample:

https://codesandbox.io/s/capacitor-fetch-instanceof-testing-98cmm6?file=/src/index.ts

You will notice a JSON (string) request and a URLSearchParams request both log out as `intanceof` `Object` and `ReadableStream` NOT the original types...

This code surely doesn't work? My next step is to build a full Capacitor example. Maybe there's something specific to iOS and Android devices that makes body of not type `ReadableStream` ?

**Comment by mr-matt-b** [comment]
I'm getting the same issue trying to get the `oidc-client-ts` OAuth flow from a Web App working in Android. The `/token` endpoint creates a `URLSearchParams` object and passes it to the body, which winds up empty after sending it across the bridge. 

I can go into more detail but since the PR that solves this issue has already been approved I figure there's no need. Is there something else stopping this PR from being merged?
