### ISSUE TITLE
feat: Restricted Permissions policy for READ_MEDIA_IMAGES

### ISSUE THREAD

**Issue by mpcoder-es** [ionic-team/capacitor#7036]
## Feature Request
Update @capacitor/camera to comply new Google Play Restricted Permissions policy(https://support.google.com/googleplay/android-developer/answer/9888170?hl=en)

### Description
As shown in this link https://support.google.com/googleplay/android-developer/answer/13986130?sjid=7513807573939384086-EU&hl=en the @capacitor/camera plugin will be affected.

### Platform(s)
Android Apps that target Android 13 (API level 33) or later

### Preferred Solution
Maybe implement pickLimitedLibraryPhotos and getLimitedLibraryPhotos for Android.

### Additional Context
https://capacitorjs.com/docs/apis/camera#picklimitedlibraryphotos

**Comment by jcesarmobile** [comment]
Closing since this is the wrong repository and we already have a pull request that uses photo picker API
