### ISSUE TITLE
bug: Cannot GET /_capacitor_file_/data

### ISSUE THREAD

**Issue by gmcaixeta** [ionic-team/capacitor#7045]
## Bug Report

I migrated from capacitor 3 to capacitor 5.
Now when I try to get a photo that I took from camera using webpath:

``` 
 const response = await fetch(photo.webPath!);
 const blob = await response.blob();
 const base64Data = (await convertBlobToBase64(blob)) as string;`
``` 
I am getting this error:

``` 
Cannot GET /_capacitor_file_/data/user/0/io.ionic.starter/cache/61944.1698760933784.jpeg
```

I've tried many forms of accessing this path, but when I get the response, I have a GET request error.
It only recognizes via src attribute of "img" html tag. GET request does not work.
Does anything changed on capacitor permission, or something else ?

```
### Capacitor Version
💊   Capacitor Doctor  💊

 

Latest Dependencies:

 

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

 

Installed Dependencies:

 

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/core: 5.0.5
```

### Platform(s)
Android Mobile
Android Studio emulator

### Current Behavior

The error occurs when it tries to fetch photo.webPath. As I said it only occurs when I try to access the photoPath as a request. When I use  src attribute of "img" html tag, it displays the image.

``` 
 const response = await fetch(photo.webPath!);
 const blob = await response.blob();
 const base64Data = (await convertBlobToBase64(blob)) as string;`
``` 

### Expected Behavior
On capacitor 3 I could get the base64 output correctly.

### Code Reproduction
Minimal sample application 

https://github.com/Akaori/vue-capacitor-camera

### Other Technical Details

    "@capacitor-community/barcode-scanner": "^4.0.1",
    "@capacitor-community/sqlite": "^5.0.5",
    "@capacitor/android": "5.0.5",
    "@capacitor/app": "5.0.3",
    "@capacitor/camera": "^5.0.7",
    "@capacitor/core": "5.0.5",
    "@capacitor/haptics": "5.0.4",
    "@capacitor/keyboard": "5.0.4",
    "@capacitor/status-bar": "5.0.4",
    "@ionic/vue": "7.4.3",
    "@ionic/vue-router": "7.4.3",
    "@types/cypress": "^1.1.3",
    "bcryptjs": "^2.4.3",
    "core-js": "^3.8.3",
    "crypto-browserify": "^3.12.0",
    "ionicons": "^7.0.0",
    "jeep-sqlite": "^2.3.9",
    "moment": "^2.29.4",
    "pinia": "^2.1.4",
    "typeorm": "^0.3.17",
    "vue": "^3.2.13",
    "vue-router": "^4.0.3"

**Comment by jcesarmobile** [comment]
This was a capacitor http bug, it's fixed already if you update your `@capacitor/core` and `@capacitor/android` packages, the versions you are using are very old.
