### ISSUE TITLE
bug: Android backup mechanism restore previous versions of app and updates aren't applied

### ISSUE THREAD

**Issue by Oupsla** [ionic-team/capacitor#7046]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
There are 2 bugs in one: 
- Since capacitor 5, we got a bug that was really hard to diagnose, when users uninstall/re-install the app from the play store, they correctly get the latest version of the app (shown in the Android menu by long-pressing the app) but when the app is launched it is an old version of the app that appears (we show the version of the current app somewhere in our app).
- It seems that updates of the app don't overwrite previous versions of the app, they seems to be stored locally and not overwritten by the update (see explanations below in technical details)

### Expected Behavior
- Latest version of the app is launched after an installation from the store (even if the user uses it before)
- When user updates the app from the store, it is the latest version that is launched

### Code Reproduction
Hard to tell how to reproduce it sadly... (see technical details below)

### Other Technical Details
So after digging why this happens, we found that was caused by the Android backup mechanism (is seems to be).
I'll try to explain : 

- A new user downloads the app from the store, in version 1.0.0 for example, and uses it.
- The Android backup is triggered (by Android Os) and backups all files (shared preferences, databases, files, ...)
- An update is deployed on the store, the version 1.1.0 for example.
- The user uninstalls the app and re-installs it from the store, so the latest version 1.1.0, BUT the android backup mechanism kicks in and restores the previous version (the 1.0.0 for this user, but can be random across users, depends on when the backup systems has been triggered by the system).
- So Android menu shows that the app is up-to-date (1.1.0) but the users is currently using a previous version (1.0.0) and can even be broken if the backup is missing some assets

We have disabled the backup system with `android:allowBackup="true"` in the manifest ([link](https://developer.android.com/guide/topics/data/autobackup?authuser=1#EnablingAutoBackup)) so it seems to work for our newest version of our app, and if users uninstall/reinstall the app to this version they aren't impacted anymore.

So it seems that the backup mechanism with Capacitor backups too many files (html/js assets) and shouldn't.

BUT... if the user doesn't do this manipulation and just updates his app, it seems that this new version of the app doesn't overwrite previous versions of the app.
When an user do an update from the store, it seems that old versions of the app (from the backup mechanism maybe?) are still on the phone of the user and take the priority, so it is still an old version of the app that is launched.

That is currently the main bug for us because we can't ask all of users to uninstall/reinstall the app from the store and we don't have find any automatic workaround yet.

### Other
Hope you can help us on that really strange bug 😄

**Comment by Oupsla** [comment]
Hello @jcesarmobile I don't know how to create a reproduction since it implies to push the application through the Play Store

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
