### ISSUE TITLE
bug: CapacitorHttp fails on Android for some secure URLs

### ISSUE THREAD

**Issue by dschnelldavis** [ionic-team/capacitor#7055]
### Capacitor Version
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1
  @capacitor/core: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android only (works fine on IOS)

### Current Behavior
Attempting to use CapacitorHttp on Android to fetch or get any URL from https://egov.uscis.gov results in the following error:
```
error: java.security.cert.certpathvalidatorexception: trust anchor for certification path not found.
```
On IOS there is no error, and CapacitorHttp appears to work just fine.

### Expected Behavior
CapacitorHttp on Android should retrieve the specified resource, just as it successfully does on IOS.

### Code Reproduction
```
fetch('https://egov.uscis.gov/csol-api/ui-auth');
```

### Other Technical Details
`npm --version` output: 9.8.1

`node --version` output: v18.15.0

`pod --version` output (iOS issues only): N/A

### Additional Context
This appears to have something to do with security certificates on Android, but I could not figure out how to fix it.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
