### ISSUE TITLE
Allow the implementer to decide behavior of clicking links inside app 

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/capacitor#706]
As per a discussion here: https://github.com/ionic-team/capacitor/pull/699#issuecomment-410042266

Currently we are making assumptions based on how the consuming applications will behave (for consistency sake with other platforms; i.e. iOS vs. Android). This leads to locked behavior that as an implementer of the framework, cannot get around without forking and adjusting behavior in the library. 

Ideally for these types of situations we would let the implementer decide how items behave. 

---

For example:

Assuming url schemes with `http` and `https` should always open in a new window external of the app. 

**Pros**: This is common behavior for Android of when a link is tapped.

**Cons**: Iframes (with the exclusion of PR: #704) always open the link in a new window regardless of trying to frame in an external URL. 

**Alternative solutions**: Do nothing as the framework and let the implementer handle the decision logic behind behavior. For this specific example, users could create a directive (or Ionic could include a directive in the core package) for listening to link clicks and handling the behavior in that implementation. You could also have a stencil web component for external links. 

```
this.elementRef.nativeElement.addEventListener('click', (e) => {
            const link = e.target as HTMLLinkElement;
            if (link.classList.contains('loop-link')) {
                e.preventDefault();
                const url = link.href;
                if (url) {
                    Browser.open({
                        url,
                        toolbarColor: (document.querySelector(':root') as HTMLElement).style.getPropertyValue('--loop-branding-color')
                    });
                }
            }
        })
```

The reason why this is valuable is: less work for your team in maintaining, no assumptions on behavior of consuming applications and developers have full control over how core functionality behaves. 

Now the number of these types of instances may be slim and this might just be a pointless recap since the iframe issue has been addressed, but regardless a good point of reference for others who find themselves in similar situations. 

Cc: @mlynch @jcesarmobile

**Comment by ajayak** [comment]
To add, all the redirects that starts with `localhost:PORT` should be opened inside the app.

My app opens google chrome browser when a URL redirect happens.

**Comment by jcesarmobile** [comment]
I just merged[ this PR](https://github.com/ionic-team/capacitor/pull/966) that added allowNavigation configuration option where you can add an array of allowed urls, this way you can allow to navigate to all those urls, not just the server url. (sort of what allow-navigation of cordova-plugin-whitelist does)

I think this is better than opening all inside the webview, so going to close
