### ISSUE TITLE
cbug: Xcode 15 IOS 17 Datepicker + timepicker crash 

### ISSUE THREAD

**Issue by noevermaurice** [ionic-team/capacitor#7065]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/core: 5.3.0
  @capacitor/cli: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

IOS 17 with Xcode 15

### Current Behavior

click on button to open The date picker  but does not open when I press it then I get the error and the whole app freezes this the error 

Exception	NSException *	"CALayer bounds contains NaN: [0 0; 232 nan]. Layer: <CALayer:0x6000006a42c0; position = CGPoint (24 127); bounds = CGRect (0 0; 0 0); delegate = <_UIDatePickerOverlayPlatterView: 0x125c4caf0; frame = (24 127; 0 0); transform = [0, 0, 0, 0, 0, 0]; layer = <CALayer: 0x6000006a42c0>>; sublayers = (<CALayer: 0x6000006a4200>, <CALayer: 0x6000006a41a0>); opaque = YES; transform = CATransform3D (0 0 0 0; 0 0 0 0; 0 0 1 0; 0 0 0 1)>"	0x0000600000cbe2e0

### Expected Behavior

The date picker should open when you press a button and you should be able to select a date 

### Other Technical Details

i use next.13 with capasitor 

`npm --version` output: 9.5.1

`node --version` output:v18.16.0

`pod --version` output (iOS issues only): 1.13.0

**Comment by jcesarmobile** [comment]
Capacitor doesn't provide any date/time picker.
If you are using just regular web input fields, you should report the issue to Apple on the [webkit issue tracker](https://bugs.webkit.org/).
If you are using some plugin, report the issue in the plugin repository.
