### ISSUE TITLE
bug: Service workers fail to register on iOS via WKWebView, potentially feature request?

### ISSUE THREAD

**Issue by NathanWild** [ionic-team/capacitor#7069]
### Capacitor Version

```
@capacitor/core: 5.5.1
@capacitor/cli: 5.5.1
@capacitor/android: 5.5.1
@capacitor/ios: 5.5.1
```

### Platform(s)
iOS

### Current Behavior
When attempting to register a service worker via the `.register()` function I get the following error:

```TypeError: serviceWorker.register() must be called with a script URL whose protocol is either HTTP or HTTPS```

### Expected Behavior
To be able to register a service worker within the app successfully.

### Code Reproduction
This can be simply done in any basic application by attempting to call `navigator.serviceWorker.register` pointing to the associated service worker `.js` file. For example:

```javascript
if ("serviceWorker" in navigator) {
  // Register a service worker hosted at the root of the
  // site using the default scope.
  navigator.serviceWorker.register("/sw.js").then(
    (registration) => {
      console.log("Service worker registration succeeded:", registration);
    },
    (error) => {
      console.error(`Service worker registration failed: ${error}`);
    },
  );
} else {
  console.error("Service workers are not supported.");
}
```

This works perfectly fine on both web/PWA and Android as the service worker is served over the correct protocol that it expects.

### Other Technical Details
`npm --version` output: 9.5.1

`node --version` output: v18.16.1

`pod --version` output (iOS issues only): 1.13.0

### Additional Context
I'm currently intending to use service workers to essentially pass authorization headers to all requests going through the domain which handles our APIs, and later be used for handling the caching of requests/content when the user is in an offline state.

As I understand from reading through some previous issues, such as https://github.com/ionic-team/capacitor/discussions/3714, it's not possible to serve assets via http/https as it's reserved for remote URLs, hence why the assets are served via `capacitor://localhost...` for the WebView. If it was possible for service workers `.js` files to be served and used via the custom protocol I'd imagine this wouldn't be an issue.

There's also a similar discussion at https://github.com/ionic-team/capacitor/discussions/5502 which seems to cover the same problem I'm having and the same approach taken to implement it following the steps required here at https://github.com/quasarframework/quasar/issues/10934 using iOS's [App-Bound Domains](https://webkit.org/blog/10882/app-bound-domains/).

A question to stem from this issue is what other approaches or solutions are there to handling both authentication and offline content easily with Capacitor? Even in Ionic's own blog post (https://ionic.io/blog/best-practices-for-building-offline-apps) one of their methods for offline content is to use service workers for caching, which doesn't even seem to be possible when using Capacitor to build an iOS app.

**Comment by jcesarmobile** [comment]
I agree that it's potentially a feature request, but that should be requested to Apple, not us, there isn't much we can do if it's Apple who is not allowing service workers on custom schemes.

There is this issue already https://bugs.webkit.org/show_bug.cgi?id=206741
But since they are now supported for http/https maybe it would be good to have a new one specific to custom schemes.
