### ISSUE TITLE
Getting 401 http_status & code 3 for @awesome-cordova-plugins/file-transfer/ngx

### ISSUE THREAD

**Issue by amitgharge-amyth** [ionic-team/capacitor#7071]
I am using FileTransfer from @awesome-cordova-plugins/file-transfer/ngx & I getting error during the method call fileTransfer.download() i.e 401 http_status & code 3. Please help me out to resolve this.

**Comment by jcesarmobile** [comment]
Please, don't use github issues to ask questions, just to report issues.


You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
