### ISSUE TITLE
bug: Ionic 5 horizontal (vertical) scroll of canvas element

### ISSUE THREAD

**Issue by Misha123457** [ionic-team/capacitor#7072]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1

### Platform(s)
Android

### Current Behavior

The HTML code with scrolling part looks as follows:

<ion-content [scrollX]=“true”>
<canvas #pdfcanvas id=“pdfcanvas”>check
<ion-content (closing tag)>

It works fully as expected on web: the Canvas document is scrolled, but once using Capacitor (Android) transformation : not possible to scroll anything both y and y on handy device

### Expected Behavior

Possibility for User to scroll canvas document after Capacitor transformation same way as a on web page

`npm --version` output: 8.19.3

`node --version` output: v18.13.0

**Comment by jcesarmobile** [comment]
Thanks for the sample app, but it doesn't build as it's missing several dependencies, I tried to install them but still fails to build because of `pdfjs-dist` package.
Can you provide a sample app that builds?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
