### ISSUE TITLE
bug: FocusScope with contain={true} reopens date/time pickers on iOS 17.x in capacitor

### ISSUE THREAD

**Issue by alexeigs** [ionic-team/capacitor#7077]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

[info] Using Gemfile: RubyGems bundle installed
[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- iOS

### Current Behavior

On iOS 17.x, within a Capacitor app, using react-aria's FocusScope component with contain={true} results in native date/time picker inputs reopening immediately after being closed. This behavior is not observed in the mobile Safari browser on the same iOS version, suggesting the issue is specific to how Capacitor's web view handles focus management in conjunction with react-aria.

### Expected Behavior

When a user selects a date/time from the native picker and closes it, the picker should remain closed, allowing normal progression through the form or application. The focus should not be trapped in a way that causes the picker to reopen.

### Code Reproduction

```
  <FocusScope contain={true}>
    <input
      type='date'
    />
  </FocusScope>
```

### Other Technical Details

`yarn --version` output: 3.5.1

`node --version` output: 20.9.0

`pod --version` output (iOS issues only): 1.12.1

### Additional Context

This issue significantly impacts user experience on iOS 17.x devices, as it hinders the usability of forms or dialogs containing date/time inputs. The problem does not occur on earlier iOS versions or when accessing the same content through Safari on iOS 17.x, which points towards a potential issue in the Capacitor environment.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
