### ISSUE TITLE
bug: Live Reload stuck on splash screen on device

### ISSUE THREAD

**Issue by Hesesses** [ionic-team/capacitor#7078]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1
```

### Platform(s)

iOS

### Current Behavior
1. `ionic capacitor run ios -l`
2. select device
3. stuck on splash screen

`ionic capacitor run ios` works fine on device
`ionic capacitor run ios -l` works fine with simulator

### Expected Behavior

`ionic capacitor run ios -l` should work on real device

### Other Technical Details

`npm --version` output: 8.19.4

`node --version` output: v16.20.1

`pod --version` output (iOS issues only): 1.14.2

macOS: 14.1.1
xcode: 15.0.1
iOS: 17.1.1

### Additional Context

output from `ionic capacitor run ios -l`
```
[capacitor] ✔ Copying web assets from www to ios/App/App/public in 282.39ms
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 547.63μs
[capacitor] [info] Found 1 Cordova plugin for ios:
[capacitor]        cordova-sqlite-storage@6.1.0
[capacitor] ✔ copy ios in 310.64ms
[capacitor] ✔ Updating iOS plugins in 5.23ms
[capacitor] [info] Found 5 Capacitor plugins for ios:
[capacitor]        @capacitor/app@5.0.6
[capacitor]        @capacitor/haptics@5.0.6
[capacitor]        @capacitor/keyboard@5.0.6
[capacitor]        @capacitor/splash-screen@5.0.6
[capacitor]        @capacitor/status-bar@5.0.6
[capacitor] [info] Found 1 Cordova plugin for ios:
[capacitor]        cordova-sqlite-storage@6.1.0
[capacitor] ✔ Updating iOS native dependencies with pod install in 1.29s
[capacitor] ✔ update ios in 1.35s
[capacitor] [info] Sync finished in 1.828s
```

**Comment by jcesarmobile** [comment]
you also need to use `--external` so it uses the local IP of the computer, if not, it uses localhost, which won't work on a real device since the live reload server is in your computer, not in your device.
