### ISSUE TITLE
feat: "Live updates" like process without Appflow

### ISSUE THREAD

**Issue by sserdyuk** [ionic-team/capacitor#7088]
### Description
I find that many updates we publish to our apps are just the JS and CSS type of thing. I am interested in sidestepping the Apple and Google store upload and approval process for those small changes. Both platforms allow the assets to be updated without releasing a new version of the app. The only current solution is to use Ionic's Appflow that costs $4199/mo for the base service (seriously?). We already have the CD/CI solution for like 1% of that, and we can host the assets ourselves. Wouldn't be nice to have a some sort of plugin to replace the assets from a self-hosted source? I looked at the past requests and didn't see anything about this. 

### Platform(s)
Both iOS and Android.

### Preferred Solution
I think the easiest solution would be to use fetch updates from a pre-configured https endpoint. The app could use the major version to construct the request path to check for the latest available asset set version. If the version is newer, download the asset set in the background and replace at the new app restart. I think the most intricate part is the replacement because it is tightly couples with how Capacitor initializes the app. 

### Alternatives
None, really.

### Additional Context
Based on the recent announcement from Ionic, Capacitor has all of the tooling to perform the updates.

**Comment by jcesarmobile** [comment]
Anybody can create their own "live updates" plugin or any other update mechanism, there aren't any limitations inside Capacitor to prevent it.
