### ISSUE TITLE
feat: App versions based on package.json

### ISSUE THREAD

**Issue by BenRacicot** [ionic-team/capacitor#7089]
### Description
For iOS we must change the version for each App Store release. 
`the Info.plist file must contain a higher version than that of the previously approved version`
I've been updating this manually via `ios/App/App.xcodeproj/project.pbxproj` `MARKETING_VERSION = 3.0.2;`

### Platform(s)
iOS and Android

### Preferred Solution
Perhaps we could we get the root project's package.json version to drive our app build versions.

**Comment by jcesarmobile** [comment]
Capacitor never modifies the user projects, so this is not something Capacitor will do.
If you want to automate the version changes for the native projects you can take a look at [trapeze](https://trapeze.dev/)
