### ISSUE TITLE
bug: TypeError: t.find is not a function (React + Vite / only when building from capacitor://localhost)

### ISSUE THREAD

**Issue by AntoineAwaida** [ionic-team/capacitor#7092]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1
  @capacitor/cli: 5.5.1

[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

Blank page at initial loading. 
XCode logs : 

```
TypeError: t.find is not a function. (In 't.find(n=>n.type==="COMITE_EXECUTIF")', 't.find' is undefined)
⚡️  URL: capacitor://localhost/assets/react-dom-81b79c2c.js
⚡️  react-dom-81b79c2c.js:14:3342
```

### Expected Behavior

Should load my app (it works if I set my local Vite server with private IP address instead of the default capacitor://localhost one).

### Code Reproduction

Not sure I can reproduce

### Other Technical Details

`npm --version` output: 9.8.1 

`node --version` output: 18.18.0

`pod --version` output (iOS issues only):

### Additional Context

All the code is in React/Typescript. It seems everything works well before building the app with vite (i.e. reaching my local development server makes the app working).
I previously packaged the app using PWABuilder (thus transforming it into a PWA).

**Comment by AntoineAwaida** [comment]
Ok i was just not pointing towards my remote API, and my Vite proxy only operated when I was reaching the Vite development server.
Sorry about that

**Comment by jcesarmobile** [comment]
glad you figured out
