### ISSUE TITLE
Handling 'Referer' Header in WebView for Capacitor/Cordova with TinyMCE Cloud

### ISSUE THREAD

**Issue by nolanmak** [ionic-team/capacitor#7104]
## Issue Description
I'm developing a mobile application using [Capacitor/Cordova] with a frontend built using `create-react-app`. Our application integrates TinyMCE (version 6.3.1) from Tiny Cloud for rich text editing. We've encountered an issue related to domain verification: TinyMCE requires a 'Referer' header for domain verification, but in the [Capacitor/Cordova] WebView environment, this header is not present or is not set correctly due to the lack of a traditional web domain.

## Environment
- Framework: [Capacitor/Cordova]
- Frontend: `create-react-app`
- TinyMCE Version: 6.3.1
- Platform: iOS/Android

## Expected Behavior
The app should be able to integrate TinyMCE without domain verification issues, as traditional web domain concepts do not apply in a [Capacitor/Cordova] WebView.

## Actual Behavior
A dialog from TinyMCE appears indicating that the 'Referer' header is missing, leading to a domain verification failure. This issue can be reproduced by simply integrating TinyMCE Cloud in a [Capacitor/Cordova] environment.

## Steps to Reproduce
1. Create a new `create-react-app` project.
2. Integrate TinyMCE Cloud following standard web integration methods.
3. Wrap the application in a [Capacitor/Cordova] environment and run it on a mobile device or emulator.
4. Observe the domain verification issue due to the absent 'Referer' header.

## Questions
1. How can we handle or emulate the 'Referer' header in a [Capacitor/Cordova] WebView, considering there is no traditional web domain?
2. Are there any known workarounds, configurations, or best practices within [Capacitor/Cordova] for integrating web services like TinyMCE Cloud that rely on standard web headers?
3. What approaches can we take in a `create-react-app` based project to ensure TinyMCE Cloud works seamlessly in a mobile app context?

Any assistance, insights, or suggestions on this matter would be immensely helpful.

Thank you!

**Comment by RotemCarmon** [comment]
@nolanmak did you find a solution?

**Comment by nhdms** [comment]
Bump

**Comment by nolanmak** [comment]
@RotemCarmon  & @nhdms   I never found a direct solution for this, but to get around it, I switched from using TinyMCE Cloud to local TinyMCE.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
