### ISSUE TITLE
bug: iOS App no longer receives touch events after popover dialog

### ISSUE THREAD

**Issue by findusl** [ionic-team/capacitor#7106]
## Bug Report

This is a special bug report, as I cannot provide a minimal reproducable example, but I can provide a solution which I think should be integrated with Capacitor by default. If not that, then at least it will help others with the problem.

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.1.1
  @capacitor/core: 5.1.1
  @capacitor/ios: 5.1.1
  @capacitor/android: 5.1.1

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main

### Platform(s)

- iOS

### Current Behavior

When opening an iOS dialogs, that uses the pop-over style and then return to the app, the app is "frozen" and no longer takes userinput. When debugging in safari, it becomes clear, that the app is not actually frozen, but simply does not get any more user input. Even reloading the browserpage using the debugger, does not fix the issue. In the simulator, it is even possible to navigate a bit with the tab and enter keys, the issue only seems to impact touch events and they do not reach the web page.

Pop-over style iOS dialogs are for example the browser from @capacitor/browser (unless setting presentation style) or the html filepicker (html <input...). The same filepicker is used by the @capacitor/camera and is also affected when used through the plugin.

### Expected Behavior

The app does not "freeze".

### Code Reproduction

We have tried reproducing the issue in a minimal sample application and were unable. The application that does experience the issue, has a complex view hierachy, including an iFrame and many layers of views. There was a very similar issue #2711, it is not unique to our application.

### Solution

The solution is rather simple although not obvious. One has to wrap the CAPBridgeViewController in a UINavigationController. For example, like this in AppDelegate.swift:

``` Swift
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        let viewController = CAPBridgeViewController(nibName: nil, bundle: nil)
        let window = UIWindow()
        let navigationController = UINavigationController(rootViewController: viewController)
        navigationController.isNavigationBarHidden = true
        window.rootViewController = navigationController
        self.window = window
        window.makeKeyAndVisible()
        return true
 }
```

Using a UINavigationController seems a logical approach and should probably be part of the default for capacitor.

### Other Technical Details

`npm --version` output: 9.5.1

`node --version` output: v18.16.0

`pod --version` output (iOS issues only): 1.14.2

The issue can be reproduced both in Simulator and a real device, running iOS 17.

### Additional Context
Seems simliar to #2711

**Comment by findusl** [comment]
@jcesarmobile Did you read the description? I cannot provide a minimal reproducable example. You can choose to take the solution or you might as well just close it.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by denisLoncaric** [comment]
I encounter the same problem; the "freeze" consistently occurs whenever the iframe is being displayed on the screen.

**Comment by findusl** [comment]
@denisLoncaric Does the solution work for you?

**Comment by denisLoncaric** [comment]
@findusl I gave it a shot, but unfortunately, it didn't solve the problem. After some more testing, I found out that the "freeze" happens when I use the `history.push` (react-router) method to redirect from the page where the iframe is displayed.
