### ISSUE TITLE
bug: Browser addListener browserFinished event never fired when the user close the browser

### ISSUE THREAD

**Issue by davideramoaxa** [ionic-team/capacitor#7110]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/cli: 5.3.0
  @capacitor/ios: 5.5.1

[info] Using Gemfile: RubyGems bundle installed
[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- iOS
- Android

### Current Behavior

- I register the listener 
``` 
Browser.addListener('browserFinished', () => {
      ...
 });
```
- I open the browser 
```
Browser.open({ url: loginUrl, windowName: '_self' })
```
- Then I press the X button on the toolbar to close it

The `browserFinished` callback is never called.

### Expected Behavior

The `browserFinished` callback should be called.

### Other Technical Details

`npm --version` output:
```
8.19.3
```

`node --version` output:
```
v18.13.0
```

`pod --version` output (iOS issues only):
```
1.12.1
```

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
