### ISSUE TITLE
bug: capacitor appstatechange event is not calling api when isActive ve status is false

### ISSUE THREAD

**Issue by adeel399** [ionic-team/capacitor#7118]
### Capacitor Version

```
PASTE OUTPUT HERE
```

### Current Behavior

App.addListener('appStateChange', ({ isActive }) => {
  console.log('App state changed. Is active?', isActive);
});
I want to call api as i minimize app so if isactive is false i want to call api but did not hit at all

### Expected Behavior

It should call api if isactive is false but it did not 

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
