### ISSUE TITLE
bug: Old javaScript build persists upon running 'cap sync', even after app reinstallation

### ISSUE THREAD

**Issue by antarsaha9** [ionic-team/capacitor#7120]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
```

### Platform(s)

- Android

### Current Behavior

I am using React as JS library and create-react-app template. Currently working on android only. When using ```config.server.url``` while running react dev server, the changes made in JS is reflecting instantly in android. 

- Scenario 1:
When using the JS build code, which is made by running ```react-scripts build```, the changes is not reflecting in android, instead a old build is showing in android. I do execute ```cap sync``` every time after making JS build.

- Scenario 2:
When installing the app in a new device(where the app is never installed before), then app is using the latest JS build, which it should.

- Scenario 3:
From scenario 1, if I clear the app data from android settings, then surprisingly app use the latest JS build.

I have followed steps in this order:
1. ```react-scripts build```
3. ```cap sync```
4. ```cap run android``` or run from android studio

### Expected Behavior

The app should always use the latest JS build, instead of caching.

### Other Technical Details

`npm --version` output: 9.5.0

`node --version` output: v18.15.0

`pod --version` output (iOS issues only):

### Additional Context

I use Manual setup of @capgo/capacitor-updater to update the JS code without Play Store release.

**Comment by jcesarmobile** [comment]
This looks like a bug on `@capgo/capacitor-updater` or a caching issue on your end.
Capacitor returns headers to not cache files, and the files are correctly copied on sync since the other devices have the correct files, so it's not a Capacitor bug.
