### ISSUE TITLE
bug:   App. listener appUrlOpen not called

### ISSUE THREAD

**Issue by CamilleFrive** [ionic-team/capacitor#7122]
### Capacitor Version

```
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS iphone 15 pro Max

### Current Behavior
if have this method
```
const tryClose = async () => {
    if (Capacitor.isNativePlatform()) {
      await Browser.close();
    }
  };
```

and I do that
```
  App.addListener('appUrlOpen', (data) => {
    if (data.url == 'frive://close') {
      tryClose();
      window.location.reload();
    }
  });
```

somewhere in the code i do that
```
  window.location.replace('frive://close');
```

My issue is that tryClose is not called on some device and on another devices (like my iPhone XS) everything works fine

but I still have 

```
 To Native ->  App addListener ***
```

I don't know what to do  now

### Expected Behavior
the browser in app is closed and the user webview content is reloaded

`npm --version` output:
10.2.3
`node --version` output:
v18.19.0
`pod --version` output (iOS issues only):
1.14.3

**Comment by CamilleFrive** [comment]
It seems that some javascript button may seems to not work on some devices

**Comment by dv29** [comment]
I'm sorry i dont understand, i'm new to capacitor/ionic. is there anything i can do to workaround?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
