### ISSUE TITLE
bug: How to use Capacitor in a React SSR web app with no index.html file?

### ISSUE THREAD

**Issue by leo1104** [ionic-team/capacitor#7144]
I have a project built using React SSR, and we want to add Capacitor to the project. The issue is that throughout the entire application, we don't have an index.html file; all files are JavaScript files. Instead of an index.html as the core file, we have an index.js file.

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
