### ISSUE TITLE
bug: Error: EPERM: operation not permitted, rmdir ...

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [ionic-team/capacitor#7150]
### Capacitor Version
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0
  @capacitor/core: 5.6.0

[error] index.html file is missing in D:\MyProjects\intelligate\application-core\android\app\src\main\assets\public

### Platform(s)
windows

### Current Behavior
The error occurs after the first restart of the application. The first restart is normal, but when I try to restart it again, I get this error

PS D:\MyProjects\intelligate\application-core> ionic cap run android -l --external --force
? Which device would you like to target? Resizable (Experimental) API 33 (emulator) (Resizable_Experimental_API_33)
> capacitor.cmd sync android
[capacitor] × Copying web assets from dist to android\app\src\main\assets\public - failed!
[capacitor] × copy android - failed!
[capacitor] [error] Error: EPERM: operation not permitted, rmdir 'D:\MyProjects\intelligate\application-core\android\app\src\main\assets\public\js'
[capacitor] √ Updating Android plugins in 2.43ms
[capacitor] [info] Found 1 Capacitor plugin for android:
[capacitor]        @capacitor/preferences@5.0.6

How do you fix it? Very annoying this error, I already do not know what to do....

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
