### ISSUE TITLE
Capacitor server cannot answer HTTP-Range_Request

### ISSUE THREAD

**Issue by motto76** [ionic-team/capacitor#7151]
## Bug Report
Capacitor server cannot answer HTTP-Range_Request

### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 5.6.0    
  @capacitor/core: 5.6.0   
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0    

Installed Dependencies:    

  @capacitor/ios: not installed
  @capacitor/android: 5.5.1    
  @capacitor/cli: 5.5.1        
  @capacitor/core: 5.5.1       

[success] Android looking great! 👌
```

### Platform(s)
only Android tested

### Current Behavior
The app memory contains a 'Cloud Optimized Geotiff', which we request via HTTP range request. The response header shows the requested size, but the content includes the entire file.
As the file is several hundred MB in size, sooner or later an OOM will occur.

### Expected Behavior
It is expected that only the part of the file that was requested will be delivered in the result.
For requests to online resources, it works as expected. The respective servers only deliver the requested section of the image.

### Other Technical Details
As it currently appears, the Capacitor server is not able to answer HTTP range requests and therefore sends the complete file. (See also the last sentences under the following link: [https://http.dev/range-request] )

`npm --version` output:
9.8.1

`node --version` output:
v18.18.0

`pod --version` output (iOS issues only):

**Comment by scottmizo** [comment]
I've ran into this same issue.  I believe the range start is correct but Capacitor is delivering the rest of the file and not honoring to end position.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
