### ISSUE TITLE
bug: npx cap sync custom cordova plugin doesn't work

### ISSUE THREAD

**Issue by loremru** [ionic-team/capacitor#7162]
Why capacitor doesnt sync my custom cordova plugin?
https://www.npmjs.com/package/kipi-browser

It works with real cordova-in-app-browser, but doesn't work with mine? Where is the difference? What is the rule of detection as a cordova plugin?

**Comment by loremru** [comment]
@dallastjames any thoughts?

**Comment by jcesarmobile** [comment]
You have to provide a sample app so we can reproduce, as the bot requested.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
