### ISSUE TITLE
bug: npx cap run android -> Gradle: > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64

### ISSUE THREAD

**Issue by regetskcob** [ionic-team/capacitor#7166]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior

When I run `npx cap run android` it fails with a gradle error/exception telling me `BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64`. The project is freshly created and iOS version is running, as well as the web-version.

### Expected Behavior

Android app should be building and running as well.

### Other Technical Details

`gradle version` is 8.0.2
`npm --version` output: 10.2.5
`node --version` output: v20.10.0

### Additional Context

Full output:
```
dbocksteger@Daniels-MBP hallo-welt % npx cap run android
✔ Copying web assets from browser to android/app/src/main/assets/public in 4.38ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 548.42μs
[info] Inlining sourcemaps
✔ copy android in 14.84ms
✔ Updating Android plugins in 1.68ms
✔ update android in 14.35ms
✖ Running Gradle build - failed!
[error] 
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Could not open settings generic class cache for settings file
        '/Users/dbocksteger/Development/experimental/angular/hallo-welt/android/settings.gradle'
        (/Users/dbocksteger/.gradle/caches/8.0.2/scripts/41bleq3pqmzd04rqmo279sxv9).
        > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major
        version 64
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 299ms
```

**Comment by jcesarmobile** [comment]
what's your java version? 
Capacitor requires java 17 to work, it might work in newer versions too, but not in all, it will depend on the gradle version used as the java support depends on the gradle version

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by shoyabsiddique** [comment]
restart the ide ur using, idk it worked for me
