### ISSUE TITLE
bug: screen-orientation plugin Cannot find name 'OrientationLockType'

### ISSUE THREAD

**Issue by Story5** [ionic-team/capacitor#7168]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- ionic
- web
- ios
- android

### Current Behavior

```
Error: node_modules/@capacitor/screen-orientation/dist/esm/definitions.d.ts:3:18 
- error TS2552: Cannot find name 'OrientationLockType'. Did you mean 'OrientationType'?
3     orientation: OrientationLockType;
```

### Expected Behavior

run success

### Code Reproduction

```
npm install @capacitor/screen-orientation
```

### Other Technical Details

`npm --version` output:`10.2.3`

`node --version` output:`v20.10.0`

`pod --version` output (iOS issues only):`1.14.3`

**Comment by jcesarmobile** [comment]
typescript 5.2 removed the type, there is a PR in review to fix the issue, see https://github.com/ionic-team/capacitor-plugins/pull/1914 for workarounds
