### ISSUE TITLE
bug: Discrepancy in Cordova Plugin Registration Logic between iOS and Android

### ISSUE THREAD

**Issue by uditajmera** [ionic-team/capacitor#7169]
Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: unknown
  @capacitor/core: unknown
  @capacitor/android: unknown
  @capacitor/ios: unknown

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1

[info] Using Gemfile: RubyGems bundle installed
[success] iOS looking great! 👌
[success] Android looking great! 👌
Platform(s)
iOS, android, web

### Current Behavior

"In the iOS CapacitorBridge.registerPlugin function code, it iterates through all Objective-C runtime classes to search for the presence of CDVPlugin. At line number 290 in CapacitorBridge, injectCordovaFiles is enabled. According to this logic, exportCordovaJS is only executed if CDVPlugins is present.

The code reference for the iOS implementation can be found here: [iOS CapacitorBridge Code](https://github.com/ionic-team/capacitor/blob/main/ios/Capacitor/Capacitor/CapacitorBridge.swift#L290).

However, in the Android counterpart, exportCordovaPlugin occurs every time without any specific check on the presence of CordovaPlugin classes. The relevant code can be found here: [Android Bridge Code](https://github.com/ionic-team/capacitor/blob/d1e05bf6a3c5629654954b1344c97b44c1a629c2/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L981-L983).

This code is called from the loadView method, as shown in the reference code: [Android loadView Code](https://github.com/ionic-team/capacitor/blob/d1e05bf6a3c5629654954b1344c97b44c1a629c2/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L249)."

### Expected Behavior

Logic should be same in both iOS and Android

**Comment by markemer** [comment]
We've changed the plugin registration for Cap 6, but this logic is still around. Is this causing a specific issue? Registration is likely to change again soon (in a non-breaking fashion), so I'm inclined to wait unless there is a specific problem this causes. We'll make sure to bring them in line when those changes happen.

**Comment by jcesarmobile** [comment]
cordova-ios and cordova-android are very different between them, and also, despite we try to make them as close as possible, @capacitor/ios and @capacitor/android are different between them, and it's also related to how cordova-ios and cordova-android work, the compatibility layer and plugin registration has to be different for each one of them in Capacitor packages.

So closing as won't fix.

Nevertheless, we plan to remove the Cordova related code if there are no Cordova plugins installed in a future Capacitor release, but will be done on update/sync, not from the native code.
