### ISSUE TITLE
bug: App plugin keep logging on appstatchange on android 13

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor#7170]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/ios: 5.0.4

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android v13

### Current Behavior
```
App.addListener('appStateChange', ({ isActive }) => {
     console.log(isActive)
});
```
appStateChange keep logging even after 1st time app starts. 

### Expected Behavior
it shoudl only log when app state changes. 

### Code Reproduction
```
ngOnInit() {
    
    App.addListener('appStateChange', ({ isActive }) => {
      if (!isActive) {
        // do something when not active
      } else {
        // do something when active      
      }
    });
  }
```

### Other Technical Details

`npm --version` output: 10.2.3

`node --version` output: v20.10.0

`pod --version` output (iOS issues only):

### Additional Context
Some other plugins are also not working correctly on android 13.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
