### ISSUE TITLE
Harmony OS Support

### ISSUE THREAD

**Issue by adrian-cytrix** [ionic-team/capacitor#7173]

**Comment by user080975** [comment]
Same here, since Harmony OS is dropping support for Android APK’s after January 18th 2024, we really need to port our Capacitor app over to Harmony OS.

**Comment by Ryanccl** [comment]
Harmony OS versions 1.0-3.0 support apk. After version 4.0, apk is not supported. Compatibility is required.

**Comment by dallastjames** [comment]
Thanks for reaching out! We currently have no plans to support HarmonyOS directly as part of Capacitor. 

Building a custom platform for Capacitor to support HarmonyOS, similar to the community-built [electron platform](https://github.com/capacitor-community/electron) might be an option for you if Harmony compatibility is critical for your application.
