### ISSUE TITLE
bug: CapacitorCordova CDVViewController does not have all data and methods exported

### ISSUE THREAD

**Issue by phyr0s** [ionic-team/capacitor#7174]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/android: 5.6.0
  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0

```

### Platform(s)

Ios, Android

### Current Behavior

I created one cordova plugin that basically has one index.html. In cordova there is no problem opening that index.html using CDVViewController but in capacitor there is few member not exported (wwwFolderName and startPage) and can't open the file.

### Expected Behavior

That member should be in the CDVViewController  in CapacitorCordova pods

<img width="971" alt="Captura de pantalla 2024-01-05 a las 12 54 37" src="https://github.com/ionic-team/capacitor/assets/11390548/ae1e08b4-1503-4246-bfd8-282ce9cddbaa">

**Comment by jcesarmobile** [comment]
Closing as won't do.
Those members are only used when creating multiple Cordova ViewControllers so they use different folders/files to load assets from than the initial Cordova ViewController. But in Capacitor projects there are no real Cordova ViewControllers. So even if we add those members, they won't do anything in your plugin.

I think it's better to make the plugin not build than making it build but not work as expected.

**Comment by phyr0s** [comment]
@jcesarmobile  Understood about folders/files load assets in capacitor. So the question is ¿How i can do that using capacitor? A plugin that contains a isolated website/ionic/any web development index.html?

**Comment by phyr0s** [comment]
Understood about folders/files load assets in capacitor. So the question is ¿How i can do that using capacitor? A plugin that contains a isolated website/ionic/any web development index.html?
