### ISSUE TITLE
bug: useSuspenseQuery raises NetworkError when API response is null

### ISSUE THREAD

**Issue by AntoineAwaida** [ionic-team/capacitor#7175]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1
```

### Platform(s)

iOS 17.1. web is not affected. not tested on Android.

### Current Behavior

To reproduce this, you have to : 
- setup a (Node ?) API which yields a response with the value `null`
- use useSuspenseQuery from `"@tanstack/react-query": "^5.4.3"`
- have the CapacitorHttp Plugin enabled

What happens then is on iOS, this yields a NetworkError upon call of the API via `"axios": "^1.4.0"` inside useSuspenseQuery.

### Expected Behavior

On desktop, or in Safari on the iPhone,or if the value returned by the API is not null, or if I use useQuery instead of useSuspenseQuery, no error is raised. 

### Other Technical Details

`npm --version` output: 9.8.1

`node --version` output: 18.18.0 

`pod --version` output (iOS issues only): 1.13.0

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
