### ISSUE TITLE
iOS Capacitor phone app cannot select audio Bluetooth output and input

### ISSUE THREAD

**Issue by makamekm** [ionic-team/capacitor#7179]
### Discussed in https://github.com/ionic-team/capacitor/discussions/5401

<div type='discussions-op-text'>

<sup>Originally posted by **dchappelle** January 31, 2022</sup>
We have a web client that uses WebRTC to make audio and video calls. The web client uses the Quasar framework and we're now using Capacitor to run it as a hybrid app on Android and iOS. On both platforms, when a call is made, the audio is always routed to the device's speaker (unless there is e.g., a bluetooth headset attached). I created a plugin to toggle the speakerphone - which works on Android but not for iOS (15.2.1). I noticed for iOS, when looking at the audio session, there is only ever one output device available i.e., _iPhone speaker_ and trying to change the session category/mode doesn't work.

My question... is it possible to route the audio to other than the speaker for a Capacitor iOS phone app?</div>

**Comment by markemer** [comment]
You'd have to use [Audio Routing](https://developer.apple.com/documentation/avfaudio/avaudiosession/audio_routing) in a native plugin. A better place for this question would be on https://forum.ionicframework.com/ where there should be a number of people that could help.
