### ISSUE TITLE
bug: [ERROR] Error while parsing Capacitor CLI version.

### ISSUE THREAD

**Issue by rusakovic** [ionic-team/capacitor#7180]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS, Android

### Current Behavior

1. Accoring to  https://capacitorjs.com/docs/guides/live-reload
```
 npm list -g --depth=0
/.nvm/versions/node/v18.17.1/lib
├── @ionic/cli@7.2.0
├── corepack@0.18.0
├── native-run@2.0.0
└── npm@9.6.7
```

2. Run command
```
ionic cap run android -l --external
ionic cap run ios -l --external

```

3. Got error
```
[ERROR] Error while parsing Capacitor CLI version.
```

### Expected Behavior

Application should be run with live reload.

### Other Technical Details

`npm --version` output: 9.6.7

`node --version` output: 18.17.1

`pod --version` output (iOS issues only): 1.13.0

### Additional Context

From what file Capacitor CLI version is parsed? How to fix it. Thank you.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
