### ISSUE TITLE
bug: File download from another web content loaded in iframe is not working

### ISSUE THREAD

**Issue by khaojam** [ionic-team/capacitor#7181]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/cli: 5.6.0

[success] Android looking great! 👌
```

### Platform(s)
Capacitor Android

### Current Behavior
I have an iframe embedded in the web app and the iframe will load some custom html content which was hosted on our backend server. The html contains a link to download file like pdf file. It works as expected on Capacitor iOS but not on Capacitor Android. When tapped on the link, nothing happens and there is no error in the console either. 
Refer to the screenshot on below, tapping on the "Download" hyperlink working as expected but not the "Click here to download PDF with fancy name". Both are anchor element with download attribute assigned to it.

### Expected Behavior
It should prompt the "Save as" action sheet to allow user to save the file.

### Code Reproduction
```
<iframe class="frame" [src]="frameSrc" frameborder="0"></iframe>
  
<div style="padding: 20px">
   <a href="https://..../test.pdf" download>Download</a>
</div>
```
https://github.com/khaojam/ng15-cap

### Other Technical Details

`npm --version` output: 8.19.3

`node --version` output: 16.19.0

`pod --version` output (iOS issues only):

### Additional Context
![58ba3d87-fa7c-40fb-8d5c-a51b6762dc07](https://github.com/ionic-team/capacitor/assets/5226787/4f895d48-449b-4ff5-8bae-4394a0c419da)

**Comment by khaojam** [comment]
Added link to the sample app code.

**Comment by jcesarmobile** [comment]
the provided app is not a capacitor app and it doesn't include any iframes or pdf files

**Comment by khaojam** [comment]
> the provided app is not a capacitor app and it doesn't include any iframes or pdf files

@jcesarmobile Sorry, I've missed out the commit for the changes. The changes should be in the repository now. Thanks.

**Comment by khaojam** [comment]
Hmmm...May I ask why my comment was marked as abuse? 😅

**Comment by jcesarmobile** [comment]
The "view PDF link" returns a 404 error, but I understand what you mean.

Sadly Android's WebView doesn't support PDF rendering, it's not a Capacitor bug, just something Android doesn't support and only Google can fix/implement.

There are some workarounds such as using pdfjs library to display the PDF files, or if it's an online PDF you can use google drive or google docs urls (I think they also use pdfjs internally) "wrapping" your file, something like this: 
`https://drive.google.com/viewerng/viewer?embedded=true&url=https://testing.api.connectsolutions.ch/html/c3/c38c397c-ec90-414c-8cef-1f82092ced91/pdf/Liste%20des%20protéines%20végétales%20pour%2010g%20de%20protéines.pdf`

(note that the ` ` needs to be escaped with `%20`
