### ISSUE TITLE
bug: Uncaught (in promise) Error: not implemented when using a plugin

### ISSUE THREAD

**Issue by KiddoV** [ionic-team/capacitor#7182]
## Bug Report
I've encountered this error when using ``Keyboard`` plugin:

```ts
if (Capacitor.isNativePlatform()) {
    Keyboard.addListener("keyboardDidShow", info => {
        console.log("keyboardDidShow", info);
        // f7.dialog.alert(`keyboardDidShow, height: ${info.keyboardHeight}`);
    });
};
```

```ts
//capacitor.config.ts

import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
	appId: "...",
	appName: "...",
	webDir: "dist",
	server: {
		// androidScheme: 'https',
		cleartext: true,
	},
	loggingBehavior: "debug",
};

export default config;

```

Everytime ``Keyboard events`` called, this error show:
![err1](https://github.com/ionic-team/capacitor/assets/28552977/5902d740-ad84-4dcf-a1cc-3a7eabfb60b1)

![err2](https://github.com/ionic-team/capacitor/assets/28552977/a06398d4-e74d-48ad-8bb5-c63d9c503adb)
![err3](https://github.com/ionic-team/capacitor/assets/28552977/829d4b68-1ab7-4310-8bbc-75e7e93562eb)

### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Platform(s)

Android

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
