### ISSUE TITLE
bug: Unable to read or write file from the storage "com.KvarReader.myapp/files/mydata/data.txt"

### ISSUE THREAD

**Issue by Saty-27** [ionic-team/capacitor#7189]
### Capacitor Version
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@capacitor/android": "^5.6.0",
    "@capacitor/cli": "^5.6.0",
    "@capacitor/core": "^5.6.0",
    "@capacitor/filesystem": "^5.2.0",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```
PASTE OUTPUT HERE
```

### Platform(s)
android

### Current Behavior
unable to create file and read it.

### Expected Behavior
To write file into the filesystem and access the file from it

### Other Technical Details
1. app.tsx
"import React, { useState, useEffect } from 'react';
import { Filesystem, Directory, Encoding } from '@capacitor/filesystem';
import { Plugins } from '@capacitor/core';

const { Storage } = Plugins;

function App() {
  const dataDirectory = 'mydata';
  const fileName = 'text.txt';
  const [directoryPath, setDirectoryPath] = useState('');
  const [fileContent, setFileContent] = useState('');

  const writeAndReadFile = async () => {
    try {
      // Check if the directory exists, and create it if it doesn't
      const directoryExists = await Filesystem.isDirectory({
        path: dataDirectory,
        directory: Directory.Documents,
      });

      if (!directoryExists) {
        await Filesystem.mkdir({
          path: dataDirectory,
          directory: Directory.Documents,
          recursive: false,
        });
        setDirectoryPath(`Directory '${dataDirectory}' created successfully.`);
      } else {
        setDirectoryPath(`Directory '${dataDirectory}' already exists.`);
      }

      // Write the file to the 'mydata' directory
      await Filesystem.writeFile({
        path: `${dataDirectory}/${fileName}`,
        data: 'This is a test',
        directory: Directory.Documents,
        encoding: Encoding.UTF8,
      });
      setFileContent(`File '${fileName}' written successfully.`);

      // Read the file from the 'mydata' directory
      const readContents = await Filesystem.readFile({
        path: `${dataDirectory}/${fileName}`,
        directory: Directory.Documents,
        encoding: Encoding.UTF8,
      });

      setFileContent(`Read contents: ${readContents}`);
    } catch (error) {
      console.error('Error:', error);
      setFileContent(`Error: ${error.message}`);
    }
  };

  useEffect(() => {
    const requestPermission = async () => {
      try {
        const status = await Storage.requestPermissions();
        if (status.publicStorage === 'granted') {
          // Permission granted, proceed with your logic
          console.log('Storage permission granted');
          writeAndReadFile();
        } else {
          // Permission denied, handle accordingly
          console.log('Storage permission denied');
        }
      } catch (error) {
        console.error('Error requesting storage permission:', error);
      }
    };

    requestPermission();
  }, []); // Run once when the component mounts

  return (
    <div className="App">
      <header className="App-header">
        <p>HELLO WORLD</p>
        <p>{directoryPath}</p>
        <p>{fileContent}</p>
      </header>
    </div>
  );
}

export default App;
"
2.defination.tsx
"import { Plugins, Capacitor } from '@capacitor/core';

const { Permissions } = Plugins;

export const requestStoragePermission = async (): Promise<boolean> => {
  try {
    if (Capacitor.isNative) {
      const result = await Permissions.requestPermissions({ permissions: ['storage'] });
      return result.permissions.storage === 'granted';
    }
    return true; // Non-native platform (web, etc.), assume permission is granted
  } catch (error) {
    console.error('Error requesting storage permission:', error);
    return false;
  }
};
"

i am new to react please do help me out :)

**Comment by VishvaaDiben** [comment]
Hi, what error is shown when app loads ?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
