### ISSUE TITLE
bug: readFile on same path changes data retrieved

### ISSUE THREAD

**Issue by Luuckyy** [ionic-team/capacitor#7196]
### Capacitor Version
```
@capacitor/cli: 4.8.1
@capacitor/android: 4.6.1
@capacitor/core: 4.8.1
@capacitor/ios: 4.8.1
```

### Platform(s)
Only happens on iOS

### Current Behavior
The data retrieved from both variable are not matching because there is a slight change in the data retrieved

### Expected Behavior
Both data should be equal

### Code Reproduction

```typescript
const image = await Camera.getPhoto({
  quality: 90,
  allowEditing: false,
  resultType: CameraResultType.Uri,
  presentationStyle: 'fullscreen',
  promptLabelPhoto: 'De la galerie',
  promptLabelPicture: 'Prendre une photo',
  saveToGallery: false,
  promptLabelCancel: 'Annuler',
  direction: CameraDirection.Rear      
});



let t1 = await Filesystem.readFile({
  path:image.path
})

let t2 = await Filesystem.readFile({
  path:image.path
})

console.log('[PHOTOS]', t1 == t2)
console.log('[PHOTO T1]', t1.data)
console.log('[PHOTO T2]', t2.data)
```

### Other Technical Details

`npm --version` output: 10.2.4

`node --version` output: v20.11.0

`pod --version` output (iOS issues only): 1.14.3

**Comment by VishvaaDiben** [comment]
Hi, what difference getting in the data retrieved for t1 and t2 ?

**Comment by Luuckyy** [comment]
> Hi, what difference getting in the data retrieved for t1 and t2 ?

Basically it was either changes at the end of the data like
`
t1.data = '.../xAAfAAABBQEBAQEBAQ'
t2.data = '.../xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBw'
`

or some sequences of characters in the middle of the file
I will give a full example in the next days but can't right now because my mac is at work

**Comment by VishvaaDiben** [comment]
I see, It may be caused by the function of getPhoto hasnt completely finished processing its image.path. Hence maybe t1 gets the unfinished path name and t2 gets the complete path name. Anyway to check the path name, you can trace with log (eg. console.log (image.path), before executing read file for t1 and t2.

**Comment by Luuckyy** [comment]
The problem got solved by itself, the only difference in before and now is that I updated iOS from 17.1.2 to 17.2.1, not sure why that would fix it but that's the only clue I have, anyway thanks everyone for taking your time
