### ISSUE TITLE
Icons on the bottom-right corner of the website are almost invisible

### ISSUE THREAD

**Issue by gldraphael** [ionic-team/capacitor#72]
**Link:** https://ionic-team.github.io/capacitor/   
**Screenshot:**
<img width="249" alt="screen shot 2018-01-19 at 09 42 20" src="https://user-images.githubusercontent.com/10794213/35134582-29956d40-fcfd-11e7-816b-7a6cd37114c3.png">

**Comment by mlynch** [comment]
Thanks, fixed 🤙
