### ISSUE TITLE
`Plugins.App.addListener` unpredictable type

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#720]
## Current behavior

When `Plugins.App.addListener()` used in a mobile app, which has implementation, it is just _a function_.

When used in a web app, it returns _a promise_ with an error `Uncaught (in promise) App does not have web implementation.`

## Expected behavior

In both cases, it should be a promise, or a function, otherwise it makes it very difficult to catch an error.

For instance, when used in a mobile app, it's just a function, so attempts to use `.catch()` method will fail.

From the other side, when used in a web app, it suddenly becomes a promise, for which the only way to use `.catch` for error handling, or use `try catch` in pair with `async` function and `await` operator. 

All that makes error handling for `Plugins.App.addListener()` quite troublesome.

**Comment by jcesarmobile** [comment]
The problem was App not having a web plugin, I think all plugins have web version now, so shouldn't be a problem
