### ISSUE TITLE
Document that you can pass vite flags when running ionic capacitor run android -l --external

### ISSUE THREAD

**Issue by rodpatulski** [ionic-team/capacitor#7201]
### Description

Document that running a command like this is possible 'ionic capacitor run android -l --external -- --mode staging' 

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

I struggled to find a way to pass in vite flags when running `ionic capacitor run android -l --external ` The only way I figured out that you can use '--' was to use chatgpt and passing flags like 'mode' to vite can be done with `ionic capacitor run android -l --external -- --mode staging`

### Additional Information

If there's already documentation for this , please let me know where as I could not find it anywhere.

**Comment by jcesarmobile** [comment]
This repository is for Capacitor project, you are referring to Ionic CLI commands.

It's documented for a few commands such as [serve](https://ionicframework.com/docs/cli/commands/serve), which `ionic capacitor run` runs under the hood when using `--livereload` option.
