### ISSUE TITLE
feat: Clarify the unit of readTimeout and connectTimeout options in HttpOptions

### ISSUE THREAD

**Issue by truyenncarmd** [ionic-team/capacitor#7205]
### Description
readTimeout and connectTimeout options of HttpOptions do not specify in second or in millisecond: https://capacitorjs.com/docs/next/apis/http#httpoptions

### Platform(s)
All

### Preferred Solution
Add second or millisecond into their description

**Comment by jcesarmobile** [comment]
http is a core plugin, moving it back to capacitor repository

**Comment by bosh-code** [comment]
Looking at the docs for the native functions the plugin calls, Android appears to be in milliseconds, but iOS uses seconds.

For example:
Android: https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setConnectTimeout-int-
iOS: https://developer.apple.com/documentation/foundation/urlrequest

I think the docs should specify ms and the iOS code should handle the conversion

**Comment by markemer** [comment]
> Looking at the docs for the native functions the plugin calls, Android appears to be in milliseconds, but iOS uses seconds.
> 
> For example: Android: https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setConnectTimeout-int- iOS: https://developer.apple.com/documentation/foundation/urlrequest
> 
> I think the docs should specify ms and the iOS code should handle the conversion

I agree - however I am a bit worried about changing that behavior, but it's probably causing bugs, you either get 1ms on Android and 1 sec on ios or something like 1 sec on Android and 1000 seconds on iOS.
