### ISSUE TITLE
[Bug]: event capacitorDidRegisterForRemoteNotifications not called

### ISSUE THREAD

**Issue by barbar-binks** [ionic-team/capacitor#7208]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0
  @capacitor/android: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

I have integrated Capacitor Push Notifications Plugin with Firebase using these instructions: [https://capacitorjs.com/docs/guides/push-notifications-firebase](url) and I have created a page to view all received notifications using Capacitor.getDeliveredNotifications(). On Android it is working where i can see a list of all notifications received on the device but on iOS i get the following error: 

`[error] - ERROR {"errorMessage":"event capacitorDidRegisterForRemoteNotifications not called.  Visit https://capacitorjs.com/docs/apis/push-notifications for more information"}`

following the link to the error does not contain any instructions on this particular error. Or even mention a 'capacitorDidRegisterForRemoteNotifications' event.

### Expected Behavior

get an array of delivered notifications. 

### Project Reproduction

https://github.com/barbar-binks/push-error

### Additional Information

AppDelegate.swift file has these functions:

`    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
      Messaging.messaging().apnsToken = deviceToken
      Messaging.messaging().token(completion: { (token, error) in
        if let error = error {
            NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
        } else if let token = token {
            NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: token)
        }
      })
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
      NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }`

app.component.ts constructor is: 

`  constructor(
    private translate: TranslateService,
    private storage:StorageService,
    private toastCtrl:ToastController,
    private navCtrl:NavController,
    private sound:SoundService,
    private userService:UserService,
  ) {
    const _self = this;
    PushNotifications.addListener('registration',
    (token: Token) => {
      Device.getId().then(
        (id:DeviceId) => {
          _self.userService.registerFcm(token, id).then(
            (result:any) => {
              console.log(result.message);
            },
            (error) => {
              console.log(error.error);
            }
          )
        }
      )
    }
  );
  PushNotifications.addListener('registrationError',
    (error:any) => {
      console.log('PUSH NOTIFICATION ERROR', error.error);
    }
  );
    PushNotifications.addListener('pushNotificationReceived', notification => {
      if(notification.link) {
        _self.toastCtrl.create({
          header: notification.title,
          message: notification.body,
          color: 'sky',
          swipeGesture: 'vertical',
          position: 'top',
          duration: 5000,
          buttons: [
            {
              icon: 'open',
              side: 'end',
              handler: () => {
                _self.navCtrl.navigateForward(notification.link!);
              }
            }
          ]
        }).then(
          (toast) => {
            toast.present();
            _self.sound.play('assets/sounds/notification.mp3');
          }
        )
      } else {
        _self.toastCtrl.create({
          header: notification.title,
          message: notification.body,
          color: 'sky',
          swipeGesture: 'vertical',
          position: 'top',
          duration: 5000,
        }).then(
          (toast) => {
            toast.present();
            _self.sound.play('assets/sounds/notification.mp3');
          }
        )
      }
    });

    PushNotifications.addListener('pushNotificationActionPerformed', (notification) => {
      const data = notification.notification.data;
      if(data.url) {
        _self.navCtrl.navigateRoot(`${data.url}`);
      }
    });`

i also added a listener after login, where users are asked for notification permissions and after granting, i add the listeners again.

**Comment by jcesarmobile** [comment]
Closing as invalid.
Issues with plugins should be reported in the plugins repository (https://github.com/ionic-team/capacitor-plugins), and the sample app should be a complete sample app, not just random files and they don't even include the usage of `getDeliveredNotifications()` funtion
