### ISSUE TITLE
[Bug]: Depplink not working in android 13

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor#7210]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/cli: 5.6.0
  @capacitor/ios: 5.6.0a
```

### Other API Details

```Shell
npm: 10.2.3
node: v20.10.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

when clicking on my website link it is redirecting to browser. 

### Expected Behavior

when clicking on my website link it should open app. 

### Project Reproduction

https://github.com/Saqib92/cap-deeplink-issue

### Additional Information

Deppliks are working in android 10. not working in android 12 and 13. 

```
initializeApp() {
    this.platform.ready().then(() => {
      this.setupDeepLink();
    })
  }

  setupDeepLink() {
    App.addListener('appUrlOpen', (event: URLOpenListenerEvent) => {
      this.zone.run(() => {
        const slug = event.url.split("loginlink").pop();
        if (slug) {
          this.router.navigateByUrl(`/loginlink${slug}`)
        }
      });
    });
  }
```

**Comment by jcesarmobile** [comment]
Your website is associated with the app `ink.shopmyl.app`, but the sample app is `com.myweb.app`.
Prior to Android 12 that didn't matter, but for Android 12 the app id has to match with the one in the `assetlinks.json`.

Also the certificate fingerprint has to match, so for development builds it won't work unless you sign them with the same fingerprint you have in the `assetlinks.json` file, which is probably the release certificate at the moment.

**Comment by Saqib92** [comment]
Sample repo updated!!

`com.myweb.app` was or example only.

I am using `demo.shopmyl.ink` in all places for my actual project ans its not working in android 12+
