### ISSUE TITLE
[Bug]: CLI AndroidManifest.xml parsing with tab indentation results in invalid parsing

### ISSUE THREAD

**Issue by geferon** [ionic-team/capacitor#7215]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0

### Other API Details

```Shell
NPM Version: 8.1.4
Node Version: 20.3.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

cordova.ts reads the AndroidManifest.xml and gets rid of newlines and tab characters, so if you indent with tabs instead of spaces, this (notice the tab characters instead of spaces for spacing the attributes):
```xml
<meta-data
	android:name="com.google.firebase.messaging.default_notification_color"
	android:resource="@color/colorAccent" />
```
will end up like this
```xml
<meta-dataandroid:name="com.google.firebase.messaging.default_notification_color"android:resource="@color/colorAccent" />
```
Which will end up not getting parsed correctly, resulting in errors like these:

```
/ copy android [fatal] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at doesXmlManifestContainRequiredInfo (C:\Projects\Capacitor_App\node_modules\@capacitor\cli\dist\cordova.js:721:78)
    at C:\Projects\Capacitor_App\node_modules\@capacitor\cli\dist\cordova.js:759:38

| update android [fatal] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at doesXmlManifestContainRequiredInfo (C:\Projects\Capacitor_App\node_modules\@capacitor\cli\dist\cordova.js:721:78)
    at C:\Projects\Capacitor_App\node_modules\@capacitor\cli\dist\cordova.js:759:38
```

### Expected Behavior

Parsing AndroidManifest.xml be indifferent from tab indentation to spaces.

The lines in cordova.ts that are causing this problem are:
https://github.com/ionic-team/capacitor/blob/4c03451758ead44b764934967f48824ef4a28d8a/cli/src/cordova.ts#L814-L828

An easy solution to this would just be replacing \n|\t with ' ' instead of ''.

### Project Reproduction

Don't have an example in hand

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by jacobalbano** [comment]
This just happened to me as well.

Working manifest declaration:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
```

Not working (tab indentation):
```xml
<manifest
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
>
```

Working (space indentation):
```xml
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
>
```

**Comment by geferon** [comment]
I was unavailable for this time and couldn't provide a sample app... Is there a way this issue could be reopened?

**Comment by marshall86** [comment]
i'm having the same issue after I installed the plugin "capacitor-branch-deep-links". Any idea on how to fix it?

**Comment by geferon** [comment]
@marshall86 replace the tabs with spaces

**Comment by marshall86** [comment]
where?
