### ISSUE TITLE
[Bug]: Unable to get selected file in singleInstance mode on Android 13 real device

### ISSUE THREAD

**Issue by HarelM** [ionic-team/capacitor#7220]
### Capacitor Version

5.6.0

### Other API Details

```Shell
node 20.10.
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Can't select a file using `<input type="file" />` in single

### Expected Behavior

I should be able to pick/select a file from my device

### Project Reproduction

https://github.com/ionic-team/capacitor/files/14043906/open-reproduction.zip

### Additional Information

The following issue was closed, but I believe the bug still exists as I was able to reproduce it on the simplest app on my Android 13 device, more information can be found in this link to the previous issue: 
- #6943

I think the main difference is that the app is using `android:launchMode="singleInstance"` on a physical device running Android 13.

I also submitted the below rejected PR:
- https://github.com/ionic-team/capacitor/pull/7194

Please, please, please let me know how I can assist in order to help solve this.
Please do not close this bug as none-reproducible as I can easily reproduce this and I'll be happy to help in the investigation, testing, coding etc.

My current workaround is to use `patch-package` with the linked PR, but I need to update this patch-package every time I update the capacitor version in my app.

**Comment by jcesarmobile** [comment]
As explained in your pull request, this is an Android bug, not a Capacitor bug, Capacitor just uses `fileChooserParams.createIntent()`, which should return the appropriate `Intent` for handling the photo picking and I told you we weren't going to change that. 
If the returned `Intent` has problems with  `singleInstance` or `singleTop` launch modes, that's something Google should fix, not us. The returned `Intent` works fine with the default and recommended launch mode Capacitor apps use by default, `singleTask`. And also it works best on Android 14 than your proposed solution as it uses the new photo picker component. So, again, we are not going to change that.

So, if you want to use one of those launch modes and they have problems with Capacitor or Capacitor plugins, you'll have to make the necessary adjustments yourself.

I also explained in the pull request how you can use a custom `WebChromeClient ` that can be set in the `MainActivity.java` file or on a `Plugin` class so you don't have to rely in `patch-package`.
