### ISSUE TITLE
Can we use native Google mobile ads SDK plugin? (Not AdMob) 

### ISSUE THREAD

**Issue by vincentsartoko** [ionic-team/capacitor#7222]
### Description

Google Mobile Ads SDK

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

I can't seem to find a good way to implement this library: https://developers.google.com/ad-manager/mobile-ads-sdk/android/quick-start.

This is not AdMob, thus can't use the existing AdMob plugin. This could be very useful to broaden Capacitor app monetization capability.

**Comment by jcesarmobile** [comment]
Please, don't use the issues to ask questions.

As far as I understand admob is deprecated and the mobile ads SDK is the new name.

The capacitor-community admob plugin has a dependency to `com.google.android.gms:play-services-ads`, so pretty sure it's already using the new thing. But if not, you can create your own plugin.

If it's still unclear for you, you can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
