### ISSUE TITLE
Ionic capacitor xcode simulator issue. Error Domain=com.apple.VisionKit.RemoveBackground Code=-8 “(null)”[Bug]: 

### ISSUE THREAD

**Issue by neerajrathore** [ionic-team/capacitor#7233]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
Ionic CLI                     : 7.2.0(.nvm/versions/node/v18.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.5
   @angular-devkit/build-angular : 17.1.0
   @angular-devkit/schematics    : 17.1.0
   @angular/cli                  : 17.1.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : 5.6.0

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.0

System:

   NodeJS : v18.13.0 (.nvm/versions/node/v18.13.0/bin/node)
   npm    : 8.0.0
   OS     : macOS Monterey
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

I am encountering a persistent white screen on a particular page. Along with this, I have observed the following error messages in the console:

`Error Message: [com.apple.VisionKit.RemoveBackground] Request to remove background on an unsupported device. Error Domain=com.apple.VisionKit.RemoveBackground Code=-8 "(null)"`

`Error Message: [UILog] Called -[UIContextMenuInteraction updateVisibleMenuWithBlock:] while no context menu is visible. This won't do anything.`

### Expected Behavior

there is no problem at logic and code as the code is perfectly fine on android. so I am expecting this to be a ios xcode issue. I am not able to test my app properly.

### Project Reproduction

localhost://8000

**Comment by jcesarmobile** [comment]
closing as invalid since no sample app was provided
