### ISSUE TITLE
[Feature]: Minor Functionaltiy or Documentation Improvement for Capacitor Platform methods

### ISSUE THREAD

**Issue by folsze** [ionic-team/capacitor#7239]
### Description

The Capacitor.isNativePlatform() returns true on macos catalyst

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

The Capacitor.isNativePlatform() returns true on macos catalyst

So this documentation is not correct:
https://capacitorjs.com/docs/core-apis/web#isnativeplatform

"Check whether the currently running platform is native (ios, android)."

Since IOS != MacOS

This could either be addressed by saying this in the docs or by changing the method code, especially the getPlatform() method, which currently does not return "desktop" (only web/ios/android)

**Comment by jcesarmobile** [comment]
platforms are the platforms Capacitor supports, that's `ios`, `android` and `web`, since you are using `@capacitor/ios`, the app is an iOS app and the platform is `ios`, doesn't matter if you are running it on macOS by using catalyst or if you se `@capacitor/android` in a tv or a car, the platform there would be android.
There is no "desktop" platform. 

Desktop or catalyst would be a value for the Device plugin to return, there is an issue already, but catalyst is not officially supported
https://github.com/ionic-team/capacitor-plugins/issues/438

**Comment by folsze** [comment]
Thank you for the information.

I am using Capacitor & Ionic. I think I am able to detect whether the app is running Catalyst or not. Like this:

```
constructor(platform: Platform) {}

if (Capacitor.isNativePlatform() && !this.platform.is('ios') && !this.platform.is('android')) {
// must be catalyst
}
```

I also logged the platforms only with this.platform.platforms(), from Catalyst:

Here is the result:
["cordova","capacitor","desktop","hybrid"]

Now I am not sure whether electron would return the same values. If electron returns the same values, but does not return true for Capacitor.isNativePlatform() then my first mentioned method is probably the best way of figuring it out? Or did I get sth wrong, maybe you know more?

or is this not a correct way of doing that?

If this is really a valid approach then I could also post it here:
https://github.com/ionic-team/capacitor/issues/3881
and here:
https://github.com/ionic-team/capacitor-plugins/issues/438

Sine in the above link it says:

### Describe Alternatives

There are no other good ways of doing this that I know of.

so maybe this would be helpful for people

**Comment by folsze** [comment]
Determining this would for example be helpful for people using Capacitor Admob, which does not support catalyst.

**Comment by jcesarmobile** [comment]
I'm not very familiar with capacitor electron platform, it used to have a `isNativePlatform()` that returned true, but now it doesn't seem to be there (in a quick code search I did on the repository).
