### ISSUE TITLE
Brand new capacitor app requires google-services.json

### ISSUE THREAD

**Issue by jdwfly** [ionic-team/capacitor#724]
**Summary:**
After creating a new ionic app and adding in capacitor to it, the app will not build in android studio because it requires google-services.json (a firebase config file).

**Steps to Reproduce:**
ionic start test tabs --type=angular
cd test
ionic build
npm install --save @capacitor/cli @capacitor/core
npm uninstall --save cordova-plugin-splashscreen
npx cap init Test com.example.test
npx cap add android
npx cap open android

**Expected Results**
The app should build and run in android studio without needing a google-services.json file.

**Actual Results**
```
File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
C:\code\test\android\app\src\nullnull\debug\google-services.json
C:\code\test\android\app\src\debug\nullnull\google-services.json
C:\code\test\android\app\src\nullnull\google-services.json
C:\code\test\android\app\src\debug\google-services.json
C:\code\test\android\app\src\nullnullDebug\google-services.json
C:\code\test\android\app\google-services.json
```
<hr>
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (C:\Users\Joe\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

System:

   NodeJS : v8.11.3 (C:\Program Files (x86)\nodejs\node.exe)
   npm    : 5.5.1
   OS     : Windows 10

Capacitor: 1.0.0-beta.4

**Comment by daniel-lucas-silva** [comment]
remove
apply plugin: 'com.google.gms.google-services'
implementation 'com.google.firebase:firebase-messaging:17.1.0'
classpath 'com.google.gms:google-services:4.0.1'

from android/build.gradle and android/app/build.gradle

i want to know why cap is adding firebase to the project

**Comment by danielsimon1** [comment]
In https://github.com/ionic-team/capacitor/pull/698, Push Notifications have been added in Capacitor Android. That requires Firebase and that's the reason why it's asking you for a `google-services.json` file.
But you're right, if you don't actually use push notifications , the app should still build without a Firebase configuration.

**Comment by jcesarmobile** [comment]
For people facing this, the PR will only affect new apps as the change is on the template. 
You can replace the current apply with this in the build.gradle if you don’t use push but plan to do it in the future

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.warn("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}

**Comment by nhhockeyplayer** [comment]
so for those who do plan on using the json file

where in the project d owe locate the json file

I located mine at my project root dir and it still gave this error

**Comment by jcesarmobile** [comment]
In `yourProject/android/app/`

**Comment by robertnicjoo** [comment]
> In `yourProject/android/app/`

still giving error

**Comment by hectorromerodev** [comment]
> For people facing this, the PR will only affect new apps as the change is on the template.
> You can replace the current apply with this in the build.gradle if you don’t use push but plan to do it in the future
> 
> ```
> try {
>     def servicesJSON = file('google-services.json')
>     if (servicesJSON.text) {
>         apply plugin: 'com.google.gms.google-services'
>     }
> } catch(Exception e) {
>     logger.warn("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
> }
> ```
> 
> If don’t plan on using it, remove it as @daniel-lucas-silva said

You need to remove this too

`apply plugin: 'com.google.gms.google-services'`
