### ISSUE TITLE
[Bug]: Capacitor.getPlatform() and Capacitor.isNativePlatform()

### ISSUE THREAD

**Issue by malte94** [ionic-team/capacitor#7241]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

### Platforms Affected

- [X] iOS
- [X] Android
- [X] Web

### Current Behavior

I can not use "Capacitor.getPlatform()" to determine whether the user is on Android or iOS, if the user is on the "mobile web". "isNativePlatform" must always be true, which appears a bit redundant for me.  Thus, I need to use native JavaScript code.

Previously, I could achieve this using "isPlatform" from Ionic.

```
  if (/iPad|iPhone|iPod/.test(navigator.userAgent)) {
    document.documentElement.classList.add('iphone');
    document.body.classList.add('iphone');
  }

  if (Capacitor.getPlatform() === "ios" && Capacitor.isNativePlatform()) {
    document.documentElement.classList.add('iphone-native');
    document.body.classList.add('iphone-native');
  }
```

### Expected Behavior

I would expect to use it like this:

```
  if (Capacitor.getPlatform() === "ios") { // User is on Safari e.g.
    document.documentElement.classList.add('iphone');
    document.body.classList.add('iphone');
  }

  if (Capacitor.getPlatform() === "ios" && Capacitor.isNativePlatform()) { // User has opened the App
    document.documentElement.classList.add('iphone-native');
    document.body.classList.add('iphone-native');
  }
```

### Project Reproduction

-

**Comment by jcesarmobile** [comment]
`getPlatform()` returns the Capacitor platform where the app is running, if you are running in a web browser the Capacitor platform is web.
You can use Device plugin if you want to know the OS where the app is running, it's returned by `getInfo` in the `operatingSystem` attribute https://capacitorjs.com/docs/apis/device#getinfo
