### ISSUE TITLE
[Bug]: JSValueEncoder

### ISSUE THREAD

**Issue by aliexalter** [ionic-team/capacitor#7244]
### Capacitor Version

   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/cli: 6.0.0-rc.0
  @capacitor/core: 6.0.0-rc.0
  @capacitor/android: 6.0.0-rc.0
  @capacitor/ios: 6.0.0-rc.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
pod version 1.14.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

Error in JSValueEncodingContainer function in JSValueEncoder.swift file saying
:stop **Missing return in getter expected to return 'String'**

### Expected Behavior

Cannot build in iOS getting error in file
JSValueEncoder.swift
<img width="1272" alt="Screenshot 2024-02-12 at 7 28 38 PM" src="https://github.com/ionic-team/capacitor/assets/2280503/117c7d25-7109-4981-92ee-93bd2c0dd2fb">

### Project Reproduction

Create new project in capacitor 6.0.0-rc.0 and add platform ios. open xcode and build.

### Additional Information

```
private enum EncodingContainer: JSValueEncodingContainer {
    case singleValue(SingleValueContainer)
    case unkeyed(UnkeyedContainer)
    case keyed(AnyKeyedContainer)

    var data: JSValue? {
        switch self {
        case let .singleValue(container):
            return container.data
        case let .unkeyed(container):
            return container.data
        case let .keyed(container):
            return container.data
        }
    }

    var type: String {
        switch self {
        case .singleValue:
            "SingleValueContainer"
        case .unkeyed:
            "UnkeyedContainer"
        case .keyed:
            "KeyedContainer"
        }
    }  //here :stop
}
```

**Comment by aliexalter** [comment]
it should be like this
```
private enum EncodingContainer: JSValueEncodingContainer {
    case singleValue(SingleValueContainer)
    case unkeyed(UnkeyedContainer)
    case keyed(AnyKeyedContainer)

    var data: JSValue? {
        switch self {
        case let .singleValue(container):
            return container.data
        case let .unkeyed(container):
            return container.data
        case let .keyed(container):
            return container.data
        }
    }

    var type: String {
        switch self {
        case .singleValue:
            return "SingleValueContainer"
        case .unkeyed:
            return "UnkeyedContainer"
        case .keyed:
            return "KeyedContainer"
        }
    }
}
```

**Comment by jcesarmobile** [comment]
Capacitor 6 requires Xcode 15
