### ISSUE TITLE
[WebSettings Docs]: When to access WebSettings before the URL load?

### ISSUE THREAD

**Issue by hbordersTwitch** [ionic-team/capacitor#7246]
### Description

Add documentation explaining the best way to access WebSettings before Bridge.loadWebView()

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

After inspecting BridgeFragment and BridgeActivity, I'm guessing it is best to declare a custom plugin as the last plugin loaded. From within that plugin, I can access the `Bridge.webView.settings` and make my customizations. However, it would be ideal to document this as the best practice. I'd like my `WebSettings` customization to be effective before the `Bridge.loadWebView()`.

### Alternatives

I don't think there are any alternatives in the 5.6.0 codebase

### Additional Information

I realize that committing to lifecycle hooks like this can tie your hands for long periods, so it's also fine to say explicitly that this isn't supported, and at least then downstream folks know about this risk when upgrading.

Thanks so much for this project!

**Comment by jcesarmobile** [comment]
Settings are not intended to be changed, other than the configurable ones with settings from https://capacitorjs.com/docs/config
If you think some other setting should be configurable you can create a feature request for it.

But users are free to change them if they want/need, on their own risk, so I don't think we should document that they can or shouldn't change anything.

Answering your question, yes, probably the only way of changing a setting before `loadWebView` is by creating a plugin that sets the setting on the plugin's load method.

**Comment by hbordersTwitch** [comment]
Thank you for your prompt and clear response!
