### ISSUE TITLE
ionicpwaelements.js Breaks Ion-Icon

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/capacitor#725]
Adding ionicpwaelements.js to an Ionic4 project breaks some ion-icons. The "side menu" sample project hamburger icon does not show. However, ion-icons next to menu items do show but smaller in size. The "tab" sample project tab icons do not show.

My understanding is ionicpwaelements.js is currently required (and needs to be added manually) for capacitor elements e.g. camera in browser.

Manually added to index.html in head tag:

    <script src="https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements.js"></script>

Reproduce:
1. Create an Ionic 4 side menu sample project.
2. Add capacitor.
3. Menu hamburger icon displays okay.
4. Add to index.html (in head tag):
    <script src="https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements.js"></script>
5. Menu hamburger icon does not show or render in DOM:
https://www.screencast.com/t/Xk54N5gs

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (C:\Users\matth\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by danielsimon1** [comment]
I had a similar issue with PWA elements & icons in my Ionic 3 app: https://github.com/ionic-team/ionic/issues/14678
Unfortunately, I was not be able to fix it.

**Comment by codediodeio** [comment]
Confirming this issue as well in Ionic4 w/ Angular. It seems the `<script src='https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements.js'></script>` is needed to make the capacitor Camera work, but breaks other things like icons and modals. 

For example, getting this err when running ModalController `present() `, but works fine with the pwaelements script. 

```
TypeError: Cannot read property 'classList' of undefined
```

**Comment by peterpeterparker** [comment]
Adding PWA elements v0.0.14, v0.0.13, 0.0.12 or event 0.0.11 to a dummy app where I try to use the camera as displayed in the documentation in an Ionic v4 app breaks for me at runtime with the following error:

> ionicpwaelements.2fgvex1b.js:6 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
>     at Object.R [as Mn] (https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements/ionicpwaelements.2fgvex1b.js:6:10617)
>     at map.forEach.n (https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements/ionicpwaelements.2fgvex1b.js:6:14876)
>     at Array.forEach (<anonymous>)
>     at D (https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements/ionicpwaelements.2fgvex1b.js:6:14863)
>     at https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements/ionicpwaelements.2fgvex1b.js:6:14970
>     at https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements/ionicpwaelements.2fgvex1b.js:6:15000
>     at https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements/ionicpwaelements.2fgvex1b.js:7:3

**Comment by peterpeterparker** [comment]
Side note, I just did the exact same test with the PWA elements v0.0.11 in an Ionic v3 app, it went fine

With the pwa elements v0.0.14 and Ionic v3 app, I didn't face the problem neither but then I faced of course my old friend https://github.com/ionic-team/capacitor/issues/603

**Comment by mlynch** [comment]
Can you try `@ionic/pwa-elements` 1.0.0? https://github.com/ionic-team/capacitor/issues/658#issuecomment-427504179

**Comment by peterpeterparker** [comment]
@mlynch `@ionic/pwa-elements 1.0.0` solves my above issue 👍

**Comment by mlynch** [comment]
w00t!
