### ISSUE TITLE
[Bug]: `NaN` is not supported on Android

### ISSUE THREAD

**Issue by robingenz** [ionic-team/capacitor#7251]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/ios: 5.4.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

If I pass `NaN` as a value to a plugin, the value `null` is received on the Android side. 

This means that users of the Capacitor Firebase Firestore plugin cannot save a `NaN` value (see https://github.com/capawesome-team/capacitor-firebase/issues/556) because `null` is also a valid value.

### Expected Behavior

It should be possible to pass the value `NaN` to a plugin. This is also already possible under iOS.
It should also be possible to receive a `NaN` value in the web layer.

### Project Reproduction

https://github.com/robingenz/capacitor-firebase-plugin-demo

### Additional Information

See https://github.com/robingenz/capacitor-firebase-plugin-demo/blob/676a3ea77190011b1951f7e9e983156467cf9a77/src/app/modules/firebase-firestore/firebase-firestore.page.ts#L43

**Comment by robingenz** [comment]
@theproducer Perhaps you could also take a look at this issue: #7265 

Let me know if I can help you with testing!

**Comment by markemer** [comment]
See my comment on #7265: 

https://github.com/ionic-team/capacitor/issues/7265#issuecomment-1960354224
