### ISSUE TITLE
[Feature]:  Support Meta Quest VR Headset

### ISSUE THREAD

**Issue by joeldhenry** [ionic-team/capacitor#7256]
### Description

Sideloading the app produces errors within capacitor core

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

Sideloading the app produces errors within capacitor core - it seems that the logic to get device is native android returns 'meta' instead of android. this causes the app to not load and be stuck at splash screen. webview loads successfully.

**Comment by jcesarmobile** [comment]
Since it uses Android, apps should just work. 
Core can only return `ios`, `android` or `web` for platforms, so it's not possible that it's returning `meta`.
Can you provide a sample app and logcat logs with the actual errors?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
