### ISSUE TITLE
[Bug]: Capacitor window object is undefined with server.url

### ISSUE THREAD

**Issue by patrik-skilling** [ionic-team/capacitor#7269]
### Capacitor Version

💊   **Capacitor Doctor**  💊

**Latest Dependencies:**

```
@capacitor/cli: 5.7.0
@capacitor/core: 5.7.0
@capacitor/android: 5.7.0
@capacitor/ios: 5.7.0
```

**Installed Dependencies:**

```
@capacitor/cli: 5.1.1
@capacitor/android: 5.1.1
@capacitor/core: 5.1.1
@capacitor/ios: 5.1.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

When running Capacitor app against certain domain the Capacitor object (`window.Capacitor`) is undefined for Android app.
Configuration we use is that we point app against external domain with `server.url`.

### Expected Behavior

Capacitor object should be injected in window object with every type of configuration in `Capacitor.config `

### Project Reproduction

https://github.com/patrik-skilling/public-capacitor-undefined-demo

### Additional Information

We have notice that the issue can be solved when we modify the user-agent with `appendUserAgent` string. (Any string in the configuration would solve the issue). We are not sure why.
See code example inside Git repo and read the `README` for instructions.

If you want us to add any additional information let us know. We will keep track of the Github issue for updates.

**Comment by jcesarmobile** [comment]
There seems to be some problem with your app redirects to (`https://support.skilling.com/hc/en-gb`).
Since it works if you change the user agent, I guess you have some code on the server to load different content or none at all depending on the user agent and Capacitor is failing to inject the javascript code because of that.

Anyway, on Capacitor 6 the javascript is injected in a different way and it's not affected by this problem.

**Comment by patrik-skilling** [comment]
Okey thank you for quick recap on the issue. @jcesarmobile 

Can you give us information on what causing the issue and how the javascript is injected differently on Capacitor 6?

Why I ask is because it would take many months before all our dependencies have done the upgrade to Capacitor 6.
We use 20 plugins today with a bit of mix:

1. 6 community plugins
2. 10 core plugins
3. 4 third party plugins
