### ISSUE TITLE
Camera API is returning front matter metadata with the base64 string

### ISSUE THREAD

**Issue by javebratt** [ionic-team/capacitor#728]
Hey there, I'm working with the Camera API and retrieving the `base64` string to upload my pictures to a Cloud Storage.

The API adds metadata to the `base64` string here: https://github.com/ionic-team/capacitor/blob/b74580af900b0aba76ae808b018b9d7e518880ce/ios/Capacitor/Capacitor/Plugins/Camera.swift#L200

```js
if settings.resultType == "base64" {
  let base64String = jpeg.base64EncodedString()
  
  self.call?.success([
    "base64Data": "data:image/jpeg;base64," + base64String,
    "exif": makeExif(imageMetadata) ?? [:],
    "format": "jpeg"
  ])
}
```

The problem is that when it adds this ` "base64Data": "data:image/jpeg;base64," + base64String,` the `base64` string becomes incompatible with Firebase Cloud Storage, so I have to manually remove the `"data:image/jpeg;base64,"` from the string.

Is there a way to pass a flag to remove that data or have an extra property that returns just the `base64String`?

Thanks!

**Comment by jcesarmobile** [comment]
As per https://github.com/ionic-team/capacitor/pull/1167, the result type base64 won't return the data part anymore and there is a new result type to get the data url.
Closing
