### ISSUE TITLE
[Bug]: Filesystem.downloadFile() creates empty file when the remote server returns 404

### ISSUE THREAD

**Issue by dumb** [ionic-team/capacitor#7288]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/cli: 5.4.0
  @capacitor/core: 5.4.0
  @capacitor/android: 5.4.0
  @capacitor/ios: 5.4.0
```

### Other API Details

```Shell
npm: 10.2.4
node: v21.6.0
pod: 1.12.1
```

### Platforms Affected

- [ ] iOS
- [ ] Android
- [X] Web

### Current Behavior

When using Filesystem.downloadFile() in a web app, if the remote server returns 404 (or any other failure), downloadFile will simply create an empty file rather than throwing an error.

Example code:

```
try {

   const res = await Filesystem.downloadFile({
      progress: true,
      recursive: true,
      path: 'thisdoesnotexist.jpg',
      url: 'https://google.com/thisdoesnotexist.jpg',
      directory: Directory.Library
   });

   console.log('downloadFile: Complete');
   console.log('downloadFile path: ', res.path); // outputs: /LIBRARY/thisdoesnotexist.jpg
   console.log('downloadFile blob: ', res.blob); // outputs Blob {size: 0, type: "text/html; charset=utf-8"}

} catch (error:any) {

   console.log('downloadFile failed: ', error.message); // this error is never thrown on web

}
```

This only seems to affect web, errors are successfully thrown on Android and iOS.

### Expected Behavior

Filesystem.downloadFile() should throw an error if the remote server responds with any 4xx or 5xx status codes.

### Project Reproduction

Please see example code above

**Comment by dumb** [comment]
Unfortunately I don't have the time to create a sample app. Example code was provided under Current Behavior, if that's insufficient feel free to ignore the bug.

**Comment by jcesarmobile** [comment]
closing as invalid since there is no sample project and it's the wrong repository.
