### ISSUE TITLE
Camera throws console error after picture (PWA)

### ISSUE THREAD

**Issue by Bforsyth1234** [ionic-team/capacitor#729]
I am getting a console error after taking a picture with my chrome browser. Below is a screen shot of the error and a link to my github project. 

![capture](https://user-images.githubusercontent.com/4528782/44040543-94595220-9ee9-11e8-9285-e6531f5b34e0.PNG)

[https://github.com/Bforsyth1234/capacitor-camera-demo](url)

**Comment by jcesarmobile** [comment]
I just cloned your project, and ran
npm install
ionic serve

And worked as expected.

What's your OS? Chrome version?

**Comment by mlynch** [comment]
Can you try `@ionic/pwa-elements` 1.0.0? https://github.com/ionic-team/capacitor/issues/658#issuecomment-427504179

**Comment by jcesarmobile** [comment]
Closing as I can't reproduce with latest pwa-elements, so it's probably fixed.
