### ISSUE TITLE
[Bug]: requesting audio via `CapacitorHttp` returns non-decodable audio

### ISSUE THREAD

**Issue by ej-shafran** [ionic-team/capacitor#7294]
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/ios: 5.7.0
  @capacitor/android: 5.7.0

[error] Xcode is not installed
[success] Android looking great! 👌

### Other API Details

```Shell
npm --version: 10.2.3
node --version: v18.19.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Taking the following steps:
1. Enable `CapacitorHttp`
2. Make a `fetch` request to an audio endpoint
3. Get the `arrayBuffer` of the response
4. Creating an `AudioContext`
5. Calling the [`decodeAudioData`](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData) method on the `arrayBuffer`

Results in:

<pre>DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data</pre>

This does not happen in web, nor in the Android build without `CapacitorHttp` enabled. I didn't check the behavior for iOS.

### Expected Behavior

Taking the steps listed above should not error, just as in web.

### Project Reproduction

https://github.com/ej-shafran/capacitor-http-audio

**Comment by jcesarmobile** [comment]
this is not reproducible using 5.x branch, so will be fixed on next Capacitor 5 release
