### ISSUE TITLE
[Bug]: Signing with build command still not working in 6.0.0-rc.0?

### ISSUE THREAD

**Issue by AlansCodeLog** [ionic-team/capacitor#7299]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 6.0.0-rc.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0

[success] Android looking great! 👌

### Other API Details

```Shell
npm: 10.2.4 
node: v20.11.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

I ran into this issue https://github.com/ionic-team/capacitor/issues/7054.

It was supposedly solved, so I upgraded the cli to [6.0.0-rc.0](https://www.npmjs.com/package/@capacitor/cli/v/6.0.0-rc.0) but I was still getting an error:
```
Failed to load signer "signer #1"
java.io.IOException: Unsupported password spec for Key "app" password for signer #1: PASSWORD
        at com.android.apksigner.PasswordRetriever.getPasswords(PasswordRetriever.java:191)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:293)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
        at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:405)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:324)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
```
I printed out the apksigner command run to try to run it myself but it also gave the same error. Eventually tried passing --key-pass the password with `pass:` (because unlike --ks-pass it was not added) and then it worked. 

```
apksigner sign ... --ks-pass pass:PASSWORD ... --key-pass pass:PASSWORD
```
So what seems to be happening is this line is not adding `pass:`. https://github.com/ionic-team/capacitor/blob/fe5333082622f549f81541369feeb12ca0945e03/cli/src/android/build.ts#L114

I can submit PR to fix, but also would it not be better to allow the user to specify this and somewhere in the documentation + CapacitorConfig types link to the apksigner docs? which allow more options than just `pass:` like `env:` and `file:` which can be very useful. https://developer.android.com/tools/apksigner#:~:text=%2D%2Dkey%2Dpass%20%3Cinput%2Dformat%3E

### Expected Behavior

I would expect to be able to either pass the password without `pass` in both cases or better docs/error + enforcement of `pass/env/file:` prefix.

### Project Reproduction
[Repo](https://github.com/AlansCodeLog/capacitor-signing-issue)
Build web project, add android with capacitor, then try to do `npm run cap:build`. I added a script to be sure it uses the project's pinned 6.0.0 cli.
Keystore is included with password 123456 for both passwords an key alias "key"`.

### Additional Information

If anybody runs into this, as a workarround you can do something like this in the capacitor.config.ts:

```
{
	// ...
	android: {
		buildOptions: {
			// ...
			keystoreAliasPassword: `pass:${process.env.ANDROID_KS_ALIAS_PASSWORD}`,
		},
	},
}
```

**Comment by AlansCodeLog** [comment]
Added repro.

**Comment by markemer** [comment]
Have you tried this with 6.0.0-rc.1? Let me know if it's still broken.

**Comment by jcesarmobile** [comment]
I've tested on the provided app and it's still broken, looks like there was a typo when making the requested changes
