### ISSUE TITLE
Disable caching for GCDWebServer

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#73]
Caching doesn't make sense for a local app and will only cause dev challenges

**Comment by jcesarmobile** [comment]
You have set `cacheAge ` to 0 here https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L80.
I think that should disable the caching.

**Comment by mlynch** [comment]
I think that just sets the header for `index.html`. We need to have a catch-all handler that does it for other assets:

![screen shot 2018-01-19 at 8 39 17 am](https://user-images.githubusercontent.com/11214/35155760-5f8fd858-fcf4-11e7-9969-72a35027779f.png)
![screen shot 2018-01-19 at 8 39 33 am](https://user-images.githubusercontent.com/11214/35155764-602a2656-fcf4-11e7-9466-9028a94842b4.png)

**Comment by mlynch** [comment]
Actually, I think this is working. If you refresh, then the network tab is caching from memory and those headers don't show, but if you step through it as the app first loads, the files are properly not cached. I think this is good to go but will keep an eye on it.
