### ISSUE TITLE
[Bug]: capacitor.config.ts not working when ionic build

### ISSUE THREAD

**Issue by DennisZhangOiler** [ionic-team/capacitor#7317]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/cli: 5.7.1
  @capacitor/core: 5.7.1
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

[success] Android looking great! 👌

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

the config variable in capacitor.config.ts won't affect `AndroidManifest.xml` generated by command `ionic build`

### Expected Behavior

it should generated configs from the ts file

### Project Reproduction

if needed, I'll provide

**Comment by jcesarmobile** [comment]
which kind of configurations?
There aren't any official Capacitor configurations that make changes in the `AndroidManifest.xml`

**Comment by DennisZhangOiler** [comment]
Hi @jcesarmobile , the file `capacitor.config.ts` was generated by `npx cap init`, and I found this doc [page](https://capacitorjs.com/docs/config), but it's not clear how it works, should I manually update `AndroidManifest.xml` and that file was just a hint? I thought it's gonna automatically migrate it to xml file.

**Comment by jcesarmobile** [comment]
Capacitor configuration file is only for Capacitor related configurations, for native project configurations you have to [edit the native files yourself](https://capacitorjs.com/docs/android/configuration), or use some programmatic tooling such as [trapeze](https://trapeze.dev/)
