### ISSUE TITLE
[Bug]: Cookies lost after exiting of application

### ISSUE THREAD

**Issue by MrMole96** [ionic-team/capacitor#7318]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/cli: 6.0.0-rc.0
  @capacitor/core: 5.7.1
  @capacitor/android: 5.7.1
  @capacitor/ios: 5.7.1

### Other API Details

capasitor.config.ts

```typescript
const config: CapacitorConfig = {
    server: {
      iosScheme: "https",
      androidScheme: "https",
      hostname: "localhost",
    },
    plugins: {
      CapacitorHttp: {
        enabled: true,
      },
      CapacitorCookies: {
        enabled: true,
      },
    },
};

``` 

### Platforms Affected

- [X] iOS
- [X] Android
- [ ] Web

### Current Behavior

After exiting the app, cookies are lost, and after reopening, the user is automatically logged out. 

This problem is visible only for ios and android

### Expected Behavior

Cookies should persist after exiting the app and be available after reopening.

### Project Reproduction

not included

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
