### ISSUE TITLE
[Bug]: CapacitorHttp removing query params when using native fetch 

### ISSUE THREAD

**Issue by marcelobotega** [ionic-team/capacitor#7319]
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/core: 5.7.2

[success] Android looking great! 👌

### Other API Details

```Shell
❯ npm --version
10.2.4

❯ pnpm --version
8.15.1

❯ node --version
v20.11.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Since `@capacitor/android@5.7.1` when calling an API using the browser fetch with `CapacitorHttp` enabled, the interceptor is removing the query params.
`CapacitorHttp.get` works normally.

### Expected Behavior

The query params should not be removed from the URL

### Project Reproduction

https://github.com/marcelobotega/capacitor-http-error

### Additional Information

The instructions for the reproduction repo are on the readme. 
The problem do not happen on `@capacitor/android@5.7.0` you can downgrade the version on package.json and the API calls will have the query params.
The placeholder API will work, but the `?postId=2` params will not be on the URL on version >= 5.7.1

**Comment by colbymelvin** [comment]
Seeing this also

**Comment by booleanbetrayal** [comment]
This seems like a major regression that could lead to lots of application breakage.

**Comment by patrickjquinn** [comment]
This has entirely broken my project as I'm sure it has for many. This should be considered a sev1 regression IMO.

**Comment by ciekawy** [comment]
I did try 5.7.3 and now I'm getting `Failed to load resource: Could not connect to the server.`

and the url instead of
`https://<host>/<path>?<queryparams>`
is:
`https://localhost/_capacitor_https_interceptor_/<host>/<path>?<queryparams>`
