### ISSUE TITLE
[Bug]: Android Live Reload broken in Capacitor 5.7.2

### ISSUE THREAD

**Issue by alextreppass** [ionic-team/capacitor#7323]
### Capacitor Version

[warn] The bundledWebRuntime configuration option has been deprecated. Please,
       use a bundler to bundle Capacitor and its plugins.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

### Other API Details

```Shell
yarn --version
3.2.1

OSX Sonoma 14.4.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Our `capacitor.config.ts` when running in live reload mode (`-l external`), has the following config:
```js
server: {
  url: process.env.LIVE_RELOAD_SERVER_URL,
  cleartext: true,
},
```

`LIVE_RELOAD_SERVER_URL` is set as `http://10.0.2.2:3000` for Android (as Android Studio treats the host machine's ip as 10.0.2.2), and `http://0.0.0.0:3000` for iOS.

We are using this setup to proxy a local dev server running on port 3000 for fast iteration without having to run `npx cap run` + rebuild each time.

### Issues
In 5.7.2 with Android, when going to the url capacitor's `live-reload.ts` generates (e.g. http://192.168.1.241:3000) the webpage does not load. There is an `ERR_CLEARTEXT_NOT_PERMITTED` error:
![Screenshot 2024-03-08 at 9 53 39 am](https://github.com/ionic-team/capacitor/assets/154376/bbb6f054-8821-47b4-9457-ce4fb5f2d7ea)

It doesn't look like there have been updates to https://github.com/ionic-team/capacitor/blob/main/cli/src/util/livereload.ts since @IT-MikeS introduced it, so something else must be going on here.

### Expected Behaviour

This worked great on 5.4.2:
```
  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2
```

The webview would load correctly.

### Project Reproduction

https://github.com/alextreppass/capacitor-live-reload-bug

**Comment by alextreppass** [comment]
Here's a finding and a fix for **Android** at least, through adding `console.log` to the build capacitor js:

If I log `config.app.extConfig.server` here: 
https://github.com/ionic-team/capacitor/blob/e45d60d15445fa55320eb6274de67d4b4191f30a/cli/src/cordova.ts#L1080-L1085

It comes through as` { url: 'http://192.168.1.241:3000' }`, i.e. missing `clearText` from our exported capacitor `config` object.

Manually patching `cleartext: true` back in that line works — the simulator loads and liveReload works.

**iOS** app still crashes at startup unfortunately.

**Comment by alextreppass** [comment]
Update: **iOS** works fine actually, I was running into another bug https://github.com/ionic-team/capacitor/issues/7324 that was preventing app startup

**Comment by alextreppass** [comment]
@jcesarmobile hello, I have added a minimal repro here: https://github.com/alextreppass/capacitor-live-reload-bug

Thank you

**Comment by alextreppass** [comment]
Hi team @jcesarmobile @Steven0351, hoping the attached repro is enough to remove the 'needs reproduction' label? Thanks

**Comment by alextreppass** [comment]
Hello, I'm not sure why my comment was flagged as abuse. I'm assuming a bot?

![Screenshot 2024-03-19 at 1 27 12 PM](https://github.com/ionic-team/capacitor/assets/154376/825c7521-e86d-4215-9637-4bde6aede557)

The requested repro is [alextreppass/capacitor-live-reload-bug](https://github.com/alextreppass/capacitor-live-reload-bug). Am happy to provide more information as needed

Regards

**Comment by fcamblor** [comment]
+1 I noticed the same behaviour as the one @alextreppass described in his repro

I don't understand why `server.cleartext` is stripped at some point.

**Comment by e-e-e** [comment]
I am also encountering this issue and was able to reproduce with the repo shared by @alextreppass

**Comment by MirazMac** [comment]
Facing the same issue. In my case: **android\app\src\main\assets\capacitor.config.json** is being replaced with a dynamic one when I run the live-server.

Example:

On my root **capacitor.config.json**, I have this in the server section:

```json
"server": {
		"url": "http://192.168.1.4:3000",
		"clearText": true
	}
```

I also ran "npx cap sync" 

So the file at: **android\app\src\main\assets\capacitor.config.json** also contains the same thing. 


But when I run
 npx cap run android  -l

The file at: **android\app\src\main\assets\capacitor.config.json** changes to the following:


```json
	"server": {
		"url": "http://172.25.144.1:3000"
	}
```


And when I exit the run command. The file reverts back to the original contents. So my specified values in the root **capacitor.config.json** is not being used for the server.

**Comment by george-martinec** [comment]
still and issue 👍🏻 live-reload using custom server field in config.

**Comment by alextreppass** [comment]
Hello. A reproduction was attached above a couple of weeks ago

**Comment by piktur** [comment]
I can see the `cleartext` property is omitted on reassignment here: 

https://github.com/ionic-team/capacitor/blob/5b2ab7c68db4e77b8b2961e927acc5a708ee260f/cli/src/util/livereload.ts#L123C2-L148C4

Noting the protocol is also hardcoded and prevents SSL.

**Comment by piktur** [comment]
This [Gist](https://gist.github.com/piktur/a75b3217467eda3d3b7813c7260483d5) preserves server options declared in `capacitor.config.*`, also implements an additional CLI option to override the HMR server protocol.
