### ISSUE TITLE
[Bug]: Cannot easily disable the new LiveUpdates plugin

### ISSUE THREAD

**Issue by alextreppass** [ionic-team/capacitor#7324]
### Capacitor Version

[warn] The bundledWebRuntime configuration option has been deprecated. Please, use a bundler to bundle
       Capacitor and its plugins.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platforms Affected

- [X] iOS
- [X] Android
- [ ] Web

### Current Behavior

Setting LiveUpdates config to `{ enabled: false }` is what the capacitor docs say https://ionic.io/docs/appflow/deploy/deploy-live-update#capacitor-sdk

However, with @capacitor/cli 5.7.2 the shape of the config is:
```ts
export interface LiveUpdateConfig {
    appId: string;
    channel: string;
    autoUpdateMethod: AutoUpdateMethod;
    maxVersions?: number;
    key?: string;
}
```

It looks like the commit from @carlpoole back in Sept 2023 to turn this into a `key?: string` type (interestingly - not a record type?) is part of 6.0.0 and not yet released.

### Issue

The app fails to launch

**iOS:**
 ```
CapacitorLiveUpdates/LiveUpdates.swift:20: Fatal error: Invalid LiveUpdate configuration. Check that both an appId and channel have been provided
```

**Android:**
(I cannot easily get a Stack trace from the Android simulator, but I assume the error is similar)

### Workarounds

Omitting the `LiveUpdates` block from `config.plugin` does not work.

Forcing `enabled: false` into this object does not work either:

```
  config.plugins = {
    ...config.plugins,
    LiveUpdates: {
      // @ts-ignore
      enabled: false,
    },
  };
```

For now, setting `channel` to a dummy value (which we never publish to) allows the apps to start up, at least

```js
config.plugins = {
  ...config.plugins,
  LiveUpdates: {
    appId: 'XXXXXXXX',
    channel: '_disabled_',
    autoUpdateMethod: 'none',
  },
};
```

### Expected Behavior

* Please support `enabled: false` in @capacitor/cli as per the docs
* and/or, if `config.LiveUpdates` is missing entirely, do not set up the functionality and continue loading the app

### Project Reproduction

Not needed - hopefully the above is clear

**Comment by Steven0351** [comment]
Any issues related to the new plugin should be opened up with Appflow support through your account in dashboard.ionicframework.com <img width="288" alt="Screenshot 2024-03-08 at 9 38 08 AM" src="https://github.com/ionic-team/capacitor/assets/24440751/f8ab6262-b28a-4c86-96c3-0ebcd208a78f">. The new LiveUpdates plugin is not open source or a community supported project and any issues or feature requests should be opened there.

**Comment by Steven0351** [comment]
All that being said, you can just add the `enabled: false` to the existing dummy values.

**Comment by alextreppass** [comment]
Hello @Steven0351 enabled: false does not work, as per the report in the OP.

I can file this through support I guess then

**Comment by jcesarmobile** [comment]
You have to use the `LiveUpdates` type that the live updates plugin exposes instead of the `LiveUpdates` type that `@capacitor/core` exposes.

You might need to add something like this at the beginning of your `capacitor.config.ts` file so it knows what the correct plugin type is `/// <reference types="@capacitor/live-updates" />`

**Comment by Steven0351** [comment]
> Hello @Steven0351 enabled: false does not work, as per the report in the OP. Would that not be an issue to report here on the capacitor side?
> 
> I will file this through support either way. Thanks

The types we exposed through the CLI for CapacitorConfig were a mistake. Those types have been removed to avoid these conflicts in Capacitor 6, however those on Capacitor 5 are stuck with the types exposed through the CLI.

Per the OP, you were trying to _only_ put `enabled: false`, I mean to say that it needs to be:
```
{
  appId: "something",
  channel: "something-else",
  enabled: false
}
```
This is by design. You are welcome to request a change to that design through support.

**Comment by alextreppass** [comment]
Thanks both. Yes it does look like the two `LiveUpdateConfig` types are incompatible.

I've gone with this for now:
```ts
    LiveUpdates: {
      appId: 'unused',
      channel: 'unused',
      autoUpdateMethod: 'none',
      // @ts-ignore
      enabled: false,
    },
```
