### ISSUE TITLE
[Feature]: Support for Bun Package Manager

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/capacitor#7326]
### Description

Add Bun to the available package managers that can be used with Capacitor

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

![download](https://github.com/ionic-team/capacitor/assets/39862171/98d4a005-f881-4c90-a451-f3c260f82996)

[Bun.sh](https://bun.sh/) is a new, super fast package manager that saves a lot of time on installing packages and running commands.

For example, when updating capacitor and running `bun cap migrate`, I can only choose between `npm`, `yarn` and `pnpm` to install dependencies.

Also `bun cap sync` does not work and results in the following error: `Could not find the web assets directory: ./www.`. 
www Directory is available in my project and the sync command does work with yarn.

**Comment by Nikita0x** [comment]
I second it.
Regarding ```bun cap sync```, try ```bunx cap sync``` - works for me.
I wish ```ionic build``` was using bun under the hood. It would probably decrease build time 3x.

**Comment by dtarnawsky** [comment]
The VS Code extension for Ionic recently added support for bun. The typical set of functionality it uses includes:

- Build - `bunx ng build`
- Serve - `bunx ng serve`
- Outdated - `npm outdated`
- Assets - `bunx @capacitor/assets generate --ios`
- Sync - `bunx cap sync`
- Run - `bunx cap run ios`
- Install - `bun install`
- List - `bun pm ls`

You should find that there is nothing really preventing you from using bun. Perhaps the `cap migrate` could do with an option to use bun.

You'll also find that bun works well for Mac for development but the recent release on Windows still has some issues building some type of projects (like Angular). This will improve over time but it isn't an Ionic/Capacitor thing.

**Comment by Nikita0x** [comment]
> The VS Code extension for Ionic recently added support for bun. The typical set of functionality it uses includes:
> 
> * Build - `bunx ng build`
> * Serve - `bunx ng serve`
> * Outdated - `npm outdated`
> * Assets - `bunx @capacitor/assets generate --ios`
> * Sync - `bunx cap sync`
> * Run - `bunx cap run ios`
> * Install - `bun install`
> * List - `bun pm ls`
> 
> You should find that there is nothing really preventing you from using bun. Perhaps the `cap migrate` could do with an option to use bun.
> 
> You'll also find that bun works well for Mac for development but the recent release on Windows still has some issues building some type of projects (like Angular). This will improve over time but it isn't an Ionic/Capacitor thing.
Thank you!
But I am not using Angular (its Vue). Will `bunx build` work too? And what is the extension? I was using it without any Ionic extension? Thanks

**Comment by dtarnawsky** [comment]
For old school vue projects you would run `bunx vue-cli-service build`
For vite based vue projects you would run `bunx vite build`

You can take a look at the extension for VS Code [here](https://ionic.link/vscode).

**Comment by Nikita0x** [comment]
@dtarnawsky Much love! Thanks
