### ISSUE TITLE
[Bug]: Integration of SPM (Extern -> Google) in plugin

### ISSUE THREAD

**Issue by Droppix** [ionic-team/capacitor#7344]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/cli: 6.0.0-rc.0
  @capacitor/core: 6.0.0-rc.0
  @capacitor/android: 6.0.0-rc.0
  @capacitor/ios: 6.0.0-rc.0

[success] iOS looking great! 👌

### Other API Details

```Shell
pod --version: 1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

The integration of an external "SPM" in the plugin is compiled correctly, but when I try to launch iOS application, I systematically get

```
no such module 'NearbyConnections'
import NearbyConnections
```

My Plugin have only this code:

```
import Foundation
import NearbyConnections

@objc public class NearbyConn: NSObject {
    @objc public func echo(_ value: String) -> String {
        print(value)
        return value
    }
}
```

NearbyConnections is SPM from google (https://github.com/google/nearby)

### Expected Behavior

Integration of SPM

### Project Reproduction

https://github.com/google/nearby

### Additional Information

I've been trying to integrate an external google framework for 3 days now, but it seems impossible. I've tried with capacitor v5 (cocoapods) and capacitor v6 (spm), but there's no way out.
If you have a solution, I'm interested...

Thanks

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
