### ISSUE TITLE
[Bug]: capacitor native http interceptor breaking requests

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/capacitor#7352]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.3
  @capacitor/core: 5.7.3
  @capacitor/android: 5.7.3
  @capacitor/ios: 5.7.3

Installed Dependencies:

  @capacitor/cli: 5.7.3
  @capacitor/core: 5.7.3
  @capacitor/android: 5.7.3
  @capacitor/ios: 5.7.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Other API Details

```Shell
npm 10.2.3
node v18.19.0
pod 1.14.3
```

### Platforms Affected

- [x] iOS
- [ ] Android
- [ ] Web

### Current Behavior

Since `5.7.1` the http requests are either missing params or adding extra elements to the URL.
The current behaviour is adding `localhost/_capacitor_https_interceptor_` to the url on IOS when `CapacitorHttp` is enabled

using mapbox sdk
![Screenshot 2024-03-18 at 15 44 27](https://github.com/ionic-team/capacitor/assets/12111716/aa5afcea-34d0-4aa4-af41-76be89cee4e1)

using axios
![Screenshot 2024-03-18 at 16 27 54](https://github.com/ionic-team/capacitor/assets/12111716/0cee3e7e-1360-4d54-8ad7-d8a31fe821e8)

### Expected Behavior

Foreign elements shouldn't break the request

### Project Reproduction

https://github.com/jongbonga/code-reproduction

**Comment by colbymelvin** [comment]
I'm noticing the same on iOS / Capacitor 5.7.3.

Notably, the URLs are formatted the same on Android and aren't causing issues, so I have to assume this is an issue with how the native iOS webView code handles these intercepted requests.

**Comment by st474ddr** [comment]
Maybe I encounter the same problem.

I want to send a request to Microsoft Graph API.
You could see my request URL is `capacitor://oacloud360/_capacitor_https_interceptor_/graph.microsoft.com/v1.0/me/calendar/calendarView?startDateTime=2024-03-24T00:00:00%2B08:00&endDateTime=2024-03-24T23:59:59%2B08:00&$top=50`

However, the response showed it got the parameter "startDateTime" was 2024-03-24T00:00:00 08:00.
The "+" or "%2B" has gone.

![image](https://github.com/ionic-team/capacitor/assets/17706261/d5489298-1f43-4e94-9716-ca9bd0233419)
