### ISSUE TITLE
[Feature]: Polygon parameters on Google Maps

### ISSUE THREAD

**Issue by almaz1213** [ionic-team/capacitor#7355]
### Description

 get paths of the edited/moved polygo

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

Hi guys, I added a polygon to capacitor google map:
```
let p: Polygon = {
        paths: this.circleToSquare(bounds.center, 10000),
        editable: true,
        draggable: true,
        fillColor: '#00ff00',
        fillOpacity: 0.25,
        strokeColor: '#009900',
        strokeWeight: 2,
        geodesic: true
      }

 this.gMap.addPolygons([p]);
```
I can edit and move the polygon on the map. How can I get paths of the edited/moved polygon?

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository

**Comment by almaz1213** [comment]
It's issue because  cannot get paths of the edited/moved polygon in Capacitor Google Maps plugin
