### ISSUE TITLE
[Bug]: Anchor link - `unable to display URL`

### ISSUE THREAD

**Issue by edshkliaruk** [ionic-team/capacitor#7356]
### Capacitor Version

Capacitor CLI version: 5.1.0

### Platforms Affected

- [X] iOS
- [X] Android
- [ ] Web

### Current Behavior

Tapping on anchor link doesn't work and see the issue like below:

<img width="751" alt="Screenshot 2024-03-19 at 10 15 38" src="https://github.com/ionic-team/capacitor/assets/125352863/8459e494-7582-4645-9389-04f1a38886f6">

### Expected Behavior

Tapping on anchor link we should be navigated to the section with ID.

### Project Reproduction

Simple issue, without link

### Additional Information

it's reproducible on IOS 17, Android 12

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
