### ISSUE TITLE
[Bug]: app crashes in IOS, call multiple endpoints

### ISSUE THREAD

**Issue by JoseCanulEI** [ionic-team/capacitor#7370]
### Capacitor Version

Capacitor 2 and Capacitor 5

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

Hi, I have a problem in iOS, I get an error on some screens, I have synchronous calls through axios and the only thing it detected is when I call the endpoint and the response usually takes a while, when I call the second endpoint, the application crashes and reboot, I want to think it's because the app goes into the background and doesn't wait for the second endpoint, can anyone help me? Send image

### Expected Behavior

App not restart

### Project Reproduction

only on ios, on android ok

### Additional Information

![image](https://github.com/ionic-team/capacitor/assets/109531364/3f47ce58-fc61-435f-a562-441909f9a78c)

**Comment by JosefBredereck** [comment]
We observed a similar issue on iOS. At random, the app crashes in an Angular application when requests are fired and aborted.
The question remains what exactly causes the issue, we could not create a successful reproduction. Sometimes it happens when a request gets unsubscribed (aborted) and sometimes when the request resolves with an error. 

```
scheme stop
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This task has already been stopped'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000111da7761 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010d3e3904 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111da763f -[NSException initWithCoder:] + 0
	3   WebKit                              0x000000010e042658 -[WKURLSchemeTaskImpl didReceiveResponse:] + 141
	4   Capacitor                           0x000000010a05272d $s9Capacitor19WebViewAssetHandlerC06handleA11HttpRequestyySo15WKURLSchemeTask_p_10Foundation3URLVSbtFyAF4DataVSg_So13NSURLResponseCSgs5Error_pSgtYbcfU_ + 2621
	5   Capacitor                           0x000000010a0529bd $s9Capacitor19WebViewAssetHandlerC06handleA11HttpRequestyySo15WKURLSchemeTask_p_10Foundation3URLVSbtFyAF4DataVSg_So13NSURLResponseCSgs5Error_pSgtYbcfU_TA + 93
	6   Capacitor                           0x000000010a01d60c $s10Foundation4DataVSgSo13NSURLResponseCSgs5Error_pSgIeghggg_So6NSDataCSgAGSo7NSErrorCSgIeyBhyyy_TR + 252
	7   CFNetwork                           0x000000010f728698 CFNetwork + 38552
	8   CFNetwork                           0x000000010f7461b1 _CFHTTPMessageSetResponseProxyURL + 16951
	9   libdispatch.dylib                   0x0000000113092747 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00000001130939f7 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000011309b8c9 _dispatch_lane_serial_drain + 1127
	12  libdispatch.dylib                   0x000000011309c665 _dispatch_lane_invoke + 441
	13  libdispatch.dylib                   0x00000001130a976e _dispatch_root_queue_drain_deferred_wlh + 318
	14  libdispatch.dylib                   0x00000001130a8b69 _dispatch_workloop_worker_thread + 590
	15  libsystem_pthread.dylib             0x00000001158aeb84 _pthread_wqthread + 327
	16  libsystem_pthread.dylib             0x00000001158adacf start_wqthread + 15
)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by JosefBredereck** [comment]
The actual position where the crash happens is https://github.com/ionic-team/capacitor/blob/3c411fd0a400b18c2d032e3b8be3fc4b5449bcbd/ios/Capacitor/Capacitor/WebViewAssetHandler.swift#L184

Based on https://stackoverflow.com/a/73581176 a possible solution could be to not abort the request like you would in the web environment.

Maybe the solution Flutter has implemented could give a possible direction:
https://github.com/arnaudelub/flutter_polywebview/blob/76def884f29ac13065a538a10789b761c168c5ff/ios/Classes/CustomeSchemeHandler.swift

**Comment by JoseCanulEI** [comment]
Thanks, I solved
