### ISSUE TITLE
[Bug]: Migrating @capacitor-community/sqlite to Capacitor 6 iOS Build Failed

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/capacitor#7378]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/cli: 6.0.0-rc.2
  @capacitor/core: 6.0.0-rc.2
  @capacitor/android: 6.0.0-rc.2
  @capacitor/ios: 6.0.0-rc.2

[error] app directory is missing in android
queaujeanpierre@MacBook-Pro-de-Queau-Jean-Pierre sqlite % 

### Other API Details

```Shell
npm: 10.4.0
node: 20.11.0
pod: 1.10.0
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

When building  after having use `npx @capacitor/plugin-migration-v5-to-v6@latest` i got 
```
** BUILD FAILED **


The following build commands failed:
        SwiftCompile normal x86_64 Compiling\ AppUUID.swift,\ Array+Capacitor.swift,\ CapacitorBridge.swift,\ CapacitorCookieManager.swift,\ CapacitorCookies.swift,\ CapacitorExtension.swift /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/AppUUID.swift /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/Array+Capacitor.swift /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorCookies.swift /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorExtension.swift (in target 'Capacitor' from project 'Pods')
        CompileSwift normal x86_64 /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift (in target 'Capacitor' from project 'Pods')
(2 failures)

 *  Arrêt du processus de terminal "/bin/zsh '-l', '-c', 'npm run verify:ios'". Code de sortie : 65. 
```

### Expected Behavior

I expect like for others platforms the build to succeed

### Project Reproduction

Take the latest version of @capacitor-community/sqlite run the `npx @capacitor/plugin-migration-v5-to-v6@latest` and try to build you will get the error

### Additional Information

The build process works find for Android, Web and Electron

**Comment by jepiqueau** [comment]
i run pod update and the open Xcode and i got ` /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift:440:27 Value of type 'WKWebView' has no member 'isInspectable'` and ` /Volumes/Development_Lacie/Development/Capacitor6/sqlite/node_modules/@capacitor/ios/Capacitor/Capacitor/Codable/JSValueEncoder.swift:103:5 Missing return in getter expected to return 'String'`

**Comment by jcesarmobile** [comment]
Thanks for the issue, but it's not a Capacitor issue.
If you are having problems with the migration you should report in the migrator repository.
https://github.com/ionic-team/migrate-capacitor-plugin/issues
Or ask a question on the forum or github discussions.

Anyway, I ran the migrator on the sqlite repository and I couldn't reproduce, are you using Xcode 15? It's a Capacitor 6 requirement (and soon will be a requirement for submitting apps to the app store too, starting April 29, 2024.).
The `Value of type 'WKWebView' has no member 'isInspectable'` seems to indicate you are using an older Xcode version that didn't have that property available yet. It was introduced in Xcode 14.3.0.

**Comment by jepiqueau** [comment]
@jcesarmobile thanks for answering quickly, i had Xcode 14, so i try to update to Xcode 15 without success My MacBook Pro run macOS 12.7.4 and Xcode 15 requiert macOS 14 So i am stuck i do not know if i can upgrade to macOS 14 My MacBook Pro was bought in 2018

**Comment by jcesarmobile** [comment]
Latest Xcode 15 requires macOS 14, but there are a few Xcode 15 versions that still work on macOS 13, I'm still on macOS 13 and using Xcode 15.2.

Also I think MacBook Pro 2018 can be updated to macOS 14
