### ISSUE TITLE
[Bug]: isNativePlatform not working as expected

### ISSUE THREAD

**Issue by aliforouzan** [ionic-team/capacitor#7387]
### Capacitor Version

"@capacitor/android": "^5.7.2",
    "@capacitor/browser": "^5.2.0",
    "@capacitor/core": "^5.7.2",

### Other API Details

```Shell
npm --version
9.7.2
node --version
v20.4.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [X] Web

### Current Behavior

in an Android device calling `isNativePlatform` returns false and `getPlatform` returns 'web'

### Expected Behavior

in an Android device calling `isNativePlatform` returns true and `getPlatform` returns 'android'

### Project Reproduction

no link

### Additional Information

I use capacitor on a Next.js project

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
