### ISSUE TITLE
[Bug]: App loses all history after Android restarts the app?

### ISSUE THREAD

**Issue by Linksku** [ionic-team/capacitor#7390]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Android often frees memory from background apps, even on my new Pixel 8. After it frees memory from my Capacitor app, if I go back to the app via the recent apps button, the app no longer has any navigation history, so it shows the homepage. If I press the back button, it closes the app, so there's no other history items.

### Expected Behavior

When switching back to some other native apps, they show the previous page I was on. It seems like other apps reloaded, but retained navigation history. E.g. I think Messenger restores navigation history but Instagram doesn't.

### Project Reproduction

N/A

### Additional Information

I don't have anything that uses a lot of memory.

**Comment by jcesarmobile** [comment]
You'll have to save the state/navigation and restore it if it's different from the last one
