### ISSUE TITLE
[Bug]: Camera's pickImages only allows one photo to be picked.

### ISSUE THREAD

**Issue by kobe-ra** [ionic-team/capacitor#7393]
### Capacitor Version

Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0
  @capacitor/core: 5.6.0

[success] Android looking great! 👌
[error] Xcode is not installed

### Other API Details

```Shell
npm --version
10.5.2

node --version
v20.9.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

User clicks button that calls `Camera.pickImages()` without any settings. It opens their filesystem, allowing them to pick one single file. On tapping second file, the first gets unselected (radio button behavior)
![WhatsApp Image 2024-04-12 at 11 25 13](https://github.com/ionic-team/capacitor/assets/32091524/d2942fcf-f5fd-41e0-a15f-e18576140c4e)
![WhatsApp Image 2024-04-12 at 11 26 06](https://github.com/ionic-team/capacitor/assets/32091524/0593fd61-9c82-4f68-80b8-b9c1c5ffaa86)

When implemented with `<input type="file">` their phone correctly opens gallery and allows multiple files input.

### Expected Behavior

Allowing user to pick multiple files.

### Project Reproduction

unnecessary without MIUI 14

### Additional Information

Can this be solved on capacitor's side or is is OS problem?
OS itself allows multi file selection since it works with <input> element, so it should be possible for `pickImages()` too.

**Comment by jcesarmobile** [comment]
This is a limitation on some devices where their gallery app don't understand the attributes to select multiple pictures.

Hopefully the new picker used in Capacitor Camera plugin 6.x that will be released soon fixes this issues, if you say input file works, the new picker will probably work too.
