### ISSUE TITLE
[Bug]: ion-datetime

### ISSUE THREAD

**Issue by almaz1213** [ionic-team/capacitor#7398]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.7.1
  @capacitor/core: 5.7.1
  @capacitor/android: 5.7.2

### Other API Details

```Shell
10.2.5
v20.10.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [X] Web

### Current Behavior

in hourCycle == 'h24' allows to choose time from 24:01 to 24:59

### Expected Behavior

max time must be 23:59

### Project Reproduction

https://github.com/ionic-team/capacitor/assets/17139263/b04703f6-04a2-4a35-9777-4c1c5c3fb980

### Additional Information

![1](https://github.com/ionic-team/capacitor/assets/17139263/b04703f6-04a2-4a35-9777-4c1c5c3fb980)

**Comment by jcesarmobile** [comment]
Ionic Framework issues should be reported on Ionic Framework repository
https://github.com/ionic-team/ionic-framework/issues
