### ISSUE TITLE
[Bug]: XHR onreadystatechange not working for non POST requests

### ISSUE THREAD

**Issue by ndrake** [ionic-team/capacitor#7417]
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/cli: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
npm: 10.2.3
node: v18.19.0
pod: 1.14.3
```

### Platforms Affected

- [X] iOS
- [X] Android
- [ ] Web

### Current Behavior

After upgrading our app v5 app, our Axios requests don't seem to be intercepted by CapacitorHttp.  This is happening in both iOS and Android.

### Expected Behavior

CapacitorHttp intercepts all requests like it did with Capacitor v5

### Project Reproduction

https://github.com/ndrake/cap-http-bug-repro

### Additional Information

Might be the same issue as this recently reported bug: https://github.com/ionic-team/capacitor/issues/7416

**Comment by patrickjquinn** [comment]
Can confirm this issue.
