### ISSUE TITLE
[Bug]: duplicate values in `packageClassList`

### ISSUE THREAD

**Issue by tafelnl** [ionic-team/capacitor#7422]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0
  @capacitor/core: 6.0.0
```

### Other API Details

```Shell
Node: v20.12.2
NPM: 10.5.0
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

Create a fresh Capacitor project. Install any non first party Capacitor plugin (for example `@capacitor-community/in-app-review`). Run `npx cap sync`. You will see the value `InAppReviewPlugin` appearing twice in the `packageClassList` parameter in `ios/App/App/capacitor.config.json`.

### Expected Behavior

Since it's a new feature (at least, I think, because I've never seen it before) I'm not sure what the expected behaviour should be actually. But looking at the output for first party Capacitor plugins, I think it's expected to only have one value inside the `packageClassList` for each plugin.

### Project Reproduction

.

**Comment by tafelnl** [comment]
I'm sorry, I won't be having time to create a reproduction soon. In al sincerity, it's also of no importance to me to get this issue fixed. So you're on your own for this one

**Comment by bc-m** [comment]
Got the same issue after removing [@capacitor-community/barcode-scanner](https://github.com/capacitor-community/barcode-scanner) and installing [@capacitor-mlkit/barcode-scanning](https://github.com/capawesome-team/capacitor-mlkit/tree/main/packages/barcode-scanning).

```json
{
	"appId": "APP_ID_REMOVED",
	"appName": "APP_NAME_REMOVED",
	"webDir": "www",
	"server": {
		"androidScheme": "http"
	},
	"plugins": {
		"PushNotifications": {
			"presentationOptions": [
				"badge",
				"sound",
				"alert"
			]
		}
	},
	"packageClassList": [
		"BarcodeScannerPlugin",
		"BarcodeScannerPlugin",
		"AppPlugin",
		"CAPBrowserPlugin",
		"ClipboardPlugin",
		"PreferencesPlugin",
		"PushNotificationsPlugin",
		"SplashScreenPlugin"
	]
}
```

**Comment by bc-m** [comment]
__Reproduction__

```bash
mkdir cap-repro-issue-7422
cd cap-repro-issue-7422
npm init --yes
git init
mkdir ./www
echo "<h1>hello world</1>" > ./www/index.html
npm install @capacitor-mlkit/barcode-scanning @capacitor/app @capacitor/core @capacitor/ios @capacitor/cli typescript
npx cap init "MyApp" "com.capacitor.app" --web-dir "www"
npx cap add ios
npx cap sync

cat ios/App/App/capacitor.config.json
```

Execute above bash-script and you will see an duplicate `BarcodeScannerPlugin` entry in `packageClassList` array, like this:

```json
{
        "appId": "com.capacitor.app",
        "appName": "MyApp",
        "webDir": "www",
        "packageClassList": [
                "BarcodeScannerPlugin",
                "BarcodeScannerPlugin",
                "AppPlugin"
        ]
}
```
