### ISSUE TITLE
[Bug]: Failed to request allowed query parameters from WebPrivacy

### ISSUE THREAD

**Issue by jonasbehlic** [ionic-team/capacitor#7434]
### Capacitor Version

> capacitor-app@1.0.0 npx
> cap doctor

[warn] The bundledWebRuntime configuration option has been deprecated. Can be
       safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
jonasbehlic@MBPtilhndeJonas VAOWTEST % 

### Other API Details

```Shell
XCODE 15+ LOG:

⚡️ Loading app at capacitor://localhost...
Failed to request allowed query parameters from WebPrivacy.
⚡️ WebView loaded
⚡️ To Native -> SplashScreen hide 62190960
⚡️ TO JS undefined
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

The app is working but on all my Capacitor projects we suddenly got the errors below, we even tried to setup a brand new Capacitor project but even complete fresh with just the standard page with comes with the install the errors appears: 

-> Warning: -[BETextInput attributedMarkedText] is unimplemented 
⚡️  Loading app at capacitor://localhost...
-> Failed to request allowed query parameters from WebPrivacy.
⚡️  WebView loaded
⚡️  To Native ->  SplashScreen hide 111656092
⚡️  TO JS undefined

### Expected Behavior

⚡️  Loading app at capacitor://localhost...
⚡️  WebView loaded
⚡️  To Native ->  SplashScreen hide 111656092
⚡️  TO JS undefined

### Project Reproduction

https://github.com/jonasbehlic/WebPrivacyIOS

**Comment by oriollpz** [comment]
Same here, any solution @jonasbehlic ?

**Comment by jonasbehlic** [comment]
No not yet. But I’m not really sure if the warning is of any importance.

**Comment by jonasbehlic** [comment]
> Same here, any solution @jonasbehlic ?

Did yours also just happen suddenly after Xcode update? Or did it appear before? And does your app still work or are you getting an white screen? 

my app works fine. Which is why I’m not sure of the importance or if this is a bug or just Privacy files missing. 

I’ve filed ticket with Apple Developer Code Level support but unfortunately haven’t heard anything from them yet.

**Comment by jonasbehlic** [comment]
> Same here, any solution @jonasbehlic ?

It's a bug inside the newest Apple iOS update.

**Comment by jcesarmobile** [comment]
Those messages come from Apple code itself, it's not a Capacitor issue and not related to any Capacitor code, it appears just by using a `WKWebView`.

You can report the issue to WebKit engineers in https://bugs.webkit.org/

But if your apps work I wouldn't worry too much about it.
