### ISSUE TITLE
[Bug]: for plugins the removeAllListeners function does not exist on iOS

### ISSUE THREAD

**Issue by JanMisker** [ionic-team/capacitor#7435]
### Capacitor Version

[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0
  @capacitor/android: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
% npm --version       
10.5.0
% node --version
v18.20.2
% pod --version
1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

On iOS the `removeAllListeners()` function on plugins is `undefined`, whereas on Android it exists as expected. 
I reproduced for PushNotifications but also checked it via console for built-in plugins like Camera.

Maybe has to do with this: https://capacitorjs.com/docs/updating/plugins/6-0#remove-removealllisteners-method

### Expected Behavior

The `removeAllListeners()` function should work the same on iOS and Android.

### Project Reproduction

https://github.com/JanMisker/TestPushNotifRemoveAll

**Comment by jcesarmobile** [comment]
The provided app doesn't include any `removeAllListeners()` call, can you update it?

Are you sure you updated correctly? looks like you updated your plugins to Capacitor 6 but you are still using `@capacitor/ios` 5.x.

**Comment by JanMisker** [comment]
Sorry my bad I wasn't using the src dir, I modified the repository to show the issue. I just put everything in [`src/index.html`](https://github.com/JanMisker/TestPushNotifRemoveAll/blob/79940218c8f051067f53d028c8dc4b1fa89205d0/src/index.html#L31).
I do use the 6 version of ios, as you can see in the [`package.json`](https://github.com/JanMisker/TestPushNotifRemoveAll/blob/79940218c8f051067f53d028c8dc4b1fa89205d0/package.json#L19).

Below screenshot of what happens when running on iOS vs. Android emulator 

iOS:
<img width="492" alt="Screenshot 2024-04-29 at 13 56 18" src="https://github.com/ionic-team/capacitor/assets/334008/407b4962-5072-4f3a-8514-24191ac3d968">

Android:
<img width="258" alt="Screenshot 2024-04-29 at 13 56 50" src="https://github.com/ionic-team/capacitor/assets/334008/8eec56f3-eaba-4c0b-a91e-255bbdc8f7bc">

**Comment by jcesarmobile** [comment]
Oh, yeah, since you changed the sample to not import the plugin, the common methods like `removeAllListeners` don't get generated since that's generated from javascript.

I guess we could generate it from native too as we do for `addListeners` so it's available even if the plugin is not imported.

But if you import the plugin, the `removeAllListeners` method is available and works as expected, the problem is just a matter of generating method for being accessible from `Capacitor.Plugins.PluginName`, which is technically deprecated.

**Comment by JanMisker** [comment]
One of our projects is really old and "vanilla" javascript, not using modules. So we'd have to find a way to include that generated plugin code without imports.

Still, isn't it strange that that same project, so without importing the plugin, does seem to work on Anroid?

**Comment by jcesarmobile** [comment]
This is an iOS issue only, on Android the plugins methods have annotations that auto generate the javascript and `removeAllListeners` is one of the base plugin class methods, but on iOS no such thing exists, so they have to be generated programmatically.
