### ISSUE TITLE
[Bug]: UnknownError: Connection to Indexed Database server lost. Refresh the page to try again

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/capacitor#7439]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
Pod Version: 1.15.2
iOS Version: 17.4 / 17.4.1
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

In Sentry, I see this errors thousands of times
```ts
{
  arguments: [
    {
      message: Uncaught (in promise): UnknownError: Connection to Indexed Database server lost. Refresh the page to try again,
      name: Error,
      promise: [Object],
      rejection: [Object],
      stack: X@capacitor://localhost/polyfills.6dcd41db847c19ec.js:1:17839
      @capacitor://localhost/polyfills.6dcd41db847c19ec.js:1:16920
      @capacitor://localhost/polyfills.6dcd41db847c19ec.js:1:17028
      ot@capacitor://localhost/main.674109a900c89374.js:1:1426341
      onInvoke@capacitor://localhost/main.674109a900c89374.js:1:746807
      @capacitor://localhost/polyfills.6dcd41db847c19ec.js:1:2774
      @capacitor://localhost/polyfills.6dcd41db847c19ec.js:1:18623
      onInvokeTask@capacitor://localhost/main.674109a900c89374.js:1:746626
      @capacitor://localhost/polyfills.6dcd41db847c19ec.js:1:3443
      A@capacitor://localhost/polyfills.6dcd41db847c19ec.js:1:10797
      @capacitor://localhost/polyfills.6dcd41db847c19ec.js:1:9568,
      task: [Object],
      zone: [Object]
    }
  ],
  logger: console
}
```
I am using the latest Version of Ionic Storage for Angular, Capacitor Preferences and Firebase. I don't really know if some of these Libraries are the cause of this error. 

I hope someone of has some more information about this error.

Kind reagards,
Marius

### Expected Behavior

-

### Project Reproduction

-

**Comment by jcesarmobile** [comment]
This looks like an Apple bug, there have been similar issues in the past, it was supposedly fixed on iOS 13, so since Capacitor only supports iOS 13+ it's probably a regression. Report it on https://bugs.webkit.org/

This is the old issue and people is commenting on it, but I think it would be better to create a new one
https://bugs.webkit.org/show_bug.cgi?id=197050

**Comment by mariusbolik** [comment]
Thank you for the fast resonse @jcesarmobile!
What I find strange is that my app supports iOS 15+ and I see errors in Sentry for iOS 17+. Can you say anything more about that?

**Comment by jcesarmobile** [comment]
As I said, check the link, there are recent comments about being broken on iOS 17.4

**Comment by banjerluke** [comment]
My users are also being affected by this issue starting with iOS 17.4. 

FYI, I posted a new bug on bugs.webkit.org: https://bugs.webkit.org/show_bug.cgi?id=273827
