### ISSUE TITLE
[Bug]: NativeBridge doesn't pass responseType to native HTTP

### ISSUE THREAD

**Issue by SillyButt** [ionic-team/capacitor#7445]
### Capacitor Version

@capacitor/cli: 5.6.0
@capacitor/core: 5.6.0
@capacitor/android: 5.6.0
@capacitor/ios: 5.6.0

### Other API Details

```Shell
npm: 10.5.0
node: 20.9.0
```

### Platforms Affected

- [X] iOS
- [X] Android
- [ ] Web

### Current Behavior

When using http requests via patched by Capacitor's native-bridge XHR/Fetch with expected `responseType`, the Bridge doesn't pass `responseType` to Native HTTP (Android/iOS). This leads to Native HTTP to not process the data with expected response type.

**Example:**
A request with `responseType: 'blob'` will not be treated by native HTTP as Blob and encoded to base64 rather than a plain string, despite `responseType` to be expected in native bridges code on Android and iOS side.

### Expected Behavior

Requests with `responseType: 'blob'` should return Blob with valid type.

### Project Reproduction

https://github.com/SillyButt/capacitor-response-type-bug-reproduction

### Additional Information

- [HttpRequestHandler.java:request with expected responseType](https://github.com/ionic-team/capacitor/blob/5b2ab7c68db4e77b8b2961e927acc5a708ee260f/android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java#L394C22-L394C34)
- [HttpRequestHandler.swift:request with expected responseType](https://github.com/ionic-team/capacitor/blob/5b2ab7c68db4e77b8b2961e927acc5a708ee260f/ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift#L153)
- [Bridge's code](https://github.com/ionic-team/capacitor/blob/5b2ab7c68db4e77b8b2961e927acc5a708ee260f/android/capacitor/src/main/assets/native-bridge.js#L657)

A convenient visualization of the code flow
![CleanShot 2024-05-02 at 11 58 52@2x](https://github.com/ionic-team/capacitor/assets/8080654/0e5cdebc-be7a-4b03-97c3-877b1053e3b7)

**Comment by jcesarmobile** [comment]
This is not reproductible in Capacitor 5.7.5 nor 6.0.0, please, when reporting issues make sure you are using latest version.

**Comment by SillyButt** [comment]
Do you have a PR or commit to back up the statement? I don't see any commit regarding the topic with changes that fix this.
I tried to reproduce the issue on V6 in dummy project, but couldn't succeed because bridge doesn't forward the request to NativeHttp (probably because both client and server are under the same origin).
But the issue is definitely actual.

![CleanShot 2024-05-23 at 15 25 18@2x](https://github.com/ionic-team/capacitor/assets/8080654/acb4393f-0537-44b1-ad7e-055038b26d14)
