### ISSUE TITLE
[Feature]: Add progress event emission on native side

### ISSUE THREAD

**Issue by GimpMaster** [ionic-team/capacitor#7448]
### Description

Capacitor Native Bridge is missing progress events

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

When looking at Capacitor Http plugin for XHR.send() there is a comment saying

`//TODO: Add progress event emission on native side`

I didn't see any open issues to actually do this. It would be great to get progress events for uploading large files.

Here is the link to the line of code: https://github.com/ionic-team/capacitor/blob/main/core/native-bridge.ts#L789

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
