### ISSUE TITLE
[Feature]: Put app logic into an external package

### ISSUE THREAD

**Issue by fansanelli** [ionic-team/capacitor#7451]
### Description

Ideas to ship applications in a B2B scenario 

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

Hello Capacitor team,

I open this issue as a feature request, but probability it should be splitted in many more if acknowledged.
When we develop an app we may want to customise and sell it to different customers but, at the same time, ship it on a store without have to submit the same app several times with maintenance burden and so on.
My idea is that we should have a base app (empty shell) with an updated capacitor and a plugin to download from cdn, validate and run the "real" app.
In this way we could also ship simple hotfixes without republishing our apps, but the most important thing should be able to give our customers different links to download their own (sub)versions.
As core change maybe capacitor may try to load, when this new plugin is configured, a different local index, stored into a package downloaded outside of the market, or fallback to the base application index that contains instructions to obtain the full app.
Mostly this idea is inspired by games that ask to download a minimalist client, but needs several GBs of extra contents to run.
I'm sure this would make happy a lot of people :)
Please let me know 
Cheers 
Francesco

**Comment by jcesarmobile** [comment]
It's already possible to load web assets from internal memory, there are several plugins that allow that.

Updates for just fixing bugs is allowed by both Apple and Google.
But be careful as changing the app functionality with updates might lead to app rejection on the stores. Also note that all the plugins that you need should be installed on the "base" app even if not using them at the moment if you plan to make them available with updates.
