### ISSUE TITLE
[Bug]: Build failed because Capacitor.swiftmodule is missing a required architecture. Would you like to build for rosetta instead?

### ISSUE THREAD

**Issue by VerburgtJimmy** [ionic-team/capacitor#7452]
### Capacitor Version

Latest Dependencies:
@capacitor/cli: 6.0.0
@capacitor/core: 6.0.0
@capacitor/android: 6.0.0
@capacitor/ios: 6.0.0

Installed Dependencies:
@capacitor/cli: 6.0.0
@capacitor/core: 6.0.0
@capacitor/android: 6.0.0
@capacitor/ios: 6.0.0

### Other API Details

```Shell
npm version: 10.7.0
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

After I upgraded my ionic application to V8 and my capacitor version to V6 I can't build my app on ios. I am getting the following message as a popup when building the app with 'ionic cap build ios' and then running it in xcode 15:  Build failed because Capacitor.swiftmodule is missing a required architecture. Would you like to build for rosetta instead? 
And in the output of xcode it gives this error: Could not find module 'capacitor; for target 'x86_64-apple-ios-simulator' found: arm64-apple-ios-simulator.

Now if I run it on a rosetta simulator it works but that of course is not what I want. I want to be sure it runs good natively.

### Expected Behavior

That when i run the new build i don't get the error displayed above.

### Project Reproduction

No link

### Additional Information

My simulator is a Iphone 15 on ios 17.4

**Comment by scr2em** [comment]
same issue

**Comment by iHackFX** [comment]
same issue

**Comment by betocantu93** [comment]
same isssue

**Comment by VerburgtJimmy** [comment]
I will try to create a new repo with a new project to check if the issue is with my current project. I have updated this project from ionic v7 to 8 and capacitor v5 to v6 and after that i got this error so if the issue is consistent with v6 it should happen in a new v6 project with ionic. If not it is a problem in the upgrade from v5 to v6.

**Comment by VerburgtJimmy** [comment]
Just checked and a new ionic project using capacitor v6 doesn't have this error. I will now try to compare the different package version from my own project and the new test project to see if the issue lies there

**Comment by VerburgtJimmy** [comment]
Just checked and debugged my npm packages and it appears this error comes when i add the @capacitor-mlkit/barcode-scanning package. Therefore I have closed this issue and i have made a new issue at that package. See this [https://github.com/capawesome-team/capacitor-mlkit/issues/153](issue)
