### ISSUE TITLE
TypeError: window.Capacitor.triggerEvent is not a function. (In 'window.Capacitor.triggerEvent('pause', 'document')', 'window.Capacitor.triggerEvent' is undefined)

### ISSUE THREAD

**Issue by aleddulla** [ionic-team/capacitor#7458]
### Capacitor Version

TypeError: window.Capacitor.triggerEvent is not a function. (In 'window.Capacitor.triggerEvent('pause', 'document')', 'window.Capacitor.triggerEvent' is undefined)

Getting this Capacitor/app

import { App } from '@capacitor/app'

App.addListener('appUrlOpen', (data) => {
})

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

import { Plugins } from '@capacitor/core'

### Expected Behavior

Resolve the error

### Project Reproduction

htt

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
