### ISSUE TITLE
Camera plugin doesn't work in Safari

### ISSUE THREAD

**Issue by rja-majconsulting** [ionic-team/capacitor#746]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.0 (/Users/rja/.nvm/versions/node/v8.11.2/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.11.2 (/Users/rja/.nvm/versions/node/v8.11.2/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra

```

**Describe the Bug**
When loading the cameraModal on Safari 11, there is an exception thrown: 
`TypeError: cameraModal.present is not a function. (In 'cameraModal.present()', 'cameraModal.present' is undefined) http://localhost:8100/home-home-module.js:504:56`.
Doing the same on Chrome 68 or Firefox 61 does not create any error.

**Steps to Reproduce**
1. Clone the sample app provided
2. npm install
3. ionic serve
4. click on the button 'Take Picture' on safari 11
5. see the error

**Related Code**
https://gitlab.com/raphael.jammart/ionic-capacitor-camera

**Expected Behavior**
Same behaviour on Safari 11 than in Chrome or Firefox: camera modal is loaded and able to take a picture.

**Comment by jcesarmobile** [comment]
See https://github.com/ionic-team/capacitor/issues/574 and https://github.com/ionic-team/capacitor/issues/658

**Comment by jcesarmobile** [comment]
Ah, sorry, didn't notice it was just for Safari

**Comment by jcesarmobile** [comment]
I got that error the first time, the second one the camera started, but the camera UI didn't appear

**Comment by rja-majconsulting** [comment]
I just again rebuild and restart the server and all suddenly seems to work... I don't understand why...

**Comment by jcesarmobile** [comment]
In my case, the camera modal wasn't appearing on Safari when the debug console was open and docked, if I closed it or undocked it it works fine. I knew it was working because the green light of the camera was on and a red camera icon appeared on safari's address bar.

**Comment by rja-majconsulting** [comment]
Ok. For me, it works "sometimes" when I try to load multiple time the page. Does it work each time for you now?

**Comment by rja-majconsulting** [comment]
When putting a break point in 'camera.js', the 'cameraModel' object is marked as 'hydrated' when it is working as expected but the object is not 'hydrated' when it is not working.

**Comment by jcesarmobile** [comment]
Seems to work fine now with latest @ionic/pwa-elements (1.0.2 at the moment), closing
