### ISSUE TITLE
[Feature]: Support Native Angular Localization

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ionic-team/capacitor#7463]
### Description

Add build support for Angular's native localization features

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

It would be great to see Capacitor support Angular's native localization features.  It seems more than practical to support Angular's built in localization which is an extremely robust option. Angular configured for  standalone is pretty much dead in the water for community based localization options seeing as `ngx-translate` doesn't support standalone. 

With the advancement of AI it's only going to make more sense for solutions to incorporate localization since it is now becoming so affordable and easy to translate text. I only see the need for Ionic to support Angular's native localization to become more and more prevalent.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
