### ISSUE TITLE
[Bug]: CompileSwift normal arm64 (in target 'App' from project 'App') xcodebuild -exportArchive

### ISSUE THREAD

**Issue by tomasztyc** [ionic-team/capacitor#7464]
### Capacitor Version

5.7.4

### Other API Details

```Shell
npm --version: 10.5.0
node --version: v20.12.2
pod --version: 1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

When I want to export .ipa file by command: `xcodebuild -exportArchive ...` I'm getting the error about:
`CompileSwift normal arm64 (in target 'App' from project 'App')
	SwiftCompile normal arm64 Compiling\ AppDelegate.swift,\ GeneratedAssetSymbols.swift /Users/runner/work/"xxx"/ios/App/App/AppDelegate.swift /Users/runner/work/"xxx"/ios/App/build/App.build/Release-iphoneos/App.build/DerivedSources/GeneratedAssetSymbols.swift (in target 'App' from project 'App')`
The same is when I'm trying to build the app for any iOS device.

I can't use `v6` as some plugins which I'm using are still incompatible with `v6`

### Expected Behavior

I want to build the app for simulator and export .ipa file.

### Project Reproduction

No link

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
