### ISSUE TITLE
[Feature]: Http plugin: Support ArrayBuffer as request body and response

### ISSUE THREAD

**Issue by marcelklehr** [ionic-team/capacitor#7471]
### Description

I would like to send and receive binary data via http without being limited to CORS

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

Allow me to set an arraybuffer as request buffer

**Comment by jcesarmobile** [comment]
If you mean when using the patched fetch/XHR, it should be working already, if it's not working for you, please, create a new issue and provide a sample app that reproduces the problem.

If you mean when using the `CapacitorHttp` API directly, you have to do the conversion to base64 yourself.

**Comment by marcelklehr** [comment]
Mmh, I think I'm still on v5 maybe that's the issue.

**Comment by jcesarmobile** [comment]
If using latest 5.x it should also work, there were no changes related to http in v6 vs v5 and fixes are being backported until 5.x maintenance period ends
