### ISSUE TITLE
[Bug]: CapacitorHttp post return data is wrong

### ISSUE THREAD

**Issue by urbanczyks** [ionic-team/capacitor#7474]
### Capacitor Version

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0
  @capacitor/android: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
npm --version output:
10.7.0
node --version output:
v20.12.2
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

CapacitorHttp.post not returning json data type, it works fine on ios and web but android response.data is not ok.
Example:

doPost(url: string, host:String, code:String) {
    const options: HttpOptions = {
      responseType: 'json',
      url,
      headers: {
        'Accept-Encoding': 'gzip',
        'content-type':'application/json'
      },
      data: {
        //This is a test data object to be tracked so try this or create your own!
        access_token: "super_secure",
        host: host,
        external_id: code
      },
    };
    return from(CapacitorHttp.post(options));
  }
here is a return request from android, data should be a json object, but it's not:
Object
data: "\u001f�\b\u0000\u0018�Kf\u0000\u0003�VJ�/-�L-��K�MU�R�,I�W�QJI��,K-��/�/.ỈO�O\u0001�\u001a\u001a�\u0018�*�\u0002\u0000\u0000\u0000��\u0003\u0000���26\u0000\u0000\u0000"
headers:
Cache-Control: "max-age=0, private, must-revalidate"
Connection: "keep-alive"
Content-Encoding: "gzip"
Content-Type: "application/json; charset=utf-8"
Date: "Mon, 20 May 2024 19:23:04 GMT"
Etag: "W/\"f37e75f9c8a3f69671b0c09fba3cb35c\""
Nel: "{\"report_to\":\"heroku-nel\",\"max_age\":3600,\"success_fraction\":0.005,\"failure_fraction\":0.05,\"response_headers\":[\"Via\"]}"
Referrer-Policy: "strict-origin-when-cross-origin"
Report-To: "{\"group\":\"heroku-nel\",\"max_age\":3600,\"endpoints\":[{\"url\":\"https://nel.heroku.com/reports?ts=1716232984&sid=c4c9725f-1ab0-44d8-820f-430df2718e11&s=OxqpOLdTw3L12jh7ZRqzKOXKiIV%2Bi0Hkah%2BTrEqWMcM%3D\"}]}"
Reporting-Endpoints: "heroku-nel=https://nel.heroku.com/reports?ts=1716232984&sid=c4c9725f-1ab0-44d8-820f-430df2718e11&s=OxqpOLdTw3L12jh7ZRqzKOXKiIV%2Bi0Hkah%2BTrEqWMcM%3D"
Server: "Cowboy"
Strict-Transport-Security: "max-age=63072000; includeSubDomains"
Transfer-Encoding: "chunked"
Vary: "Accept-Encoding"
Via: "1.1 vegur"
X-Android-Received-Millis: "1716232983734"
X-Android-Response-Source: "NETWORK 200"
X-Android-Selected-Protocol: "http/1.1"
X-Android-Sent-Millis: "1716232983265"
X-Content-Type-Options: "nosniff"
X-Frame-Options: "SAMEORIGIN"
X-Permitted-Cross-Domain-Policies: "none"
X-Request-Id: "d5c9e9b2-4ec9-4acd-9988-306b030094db"
X-Runtime: "0.210513"
X-Xss-Protection: "0"
__proto__: Object
status: 200
url: "https://tiramizoo-sorting-app-wjjudczu.herokuapp.com/api/scannings"

### Expected Behavior

return data as JSON object

### Project Reproduction

https://github.com/urbanczyks/CapacitorHttp-bug

### Additional Information

click API btn to make a request, on ios and web works great, on android request response data is not working

**Comment by urbanczyks** [comment]
get gets the same result, return data is corrupted

**Comment by jcesarmobile** [comment]
closing since the reporter figured out and the sample repository is empty
