### ISSUE TITLE
[Feature]: expose `methodName` via `CAPPluginCall`

### ISSUE THREAD

**Issue by robingenz** [ionic-team/capacitor#7476]
### Description

Expose the method name of the plugin method that was called.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

On **Android**, we can call `getMethodName()` to get the method name of the plugin method that was called.
On **iOS**, there is no such method/property. It would be great if there was a `methodName` property in `CAPPluginCall`.

**Comment by robingenz** [comment]
Would a PR be welcome?

**Comment by markemer** [comment]
> Would a PR be welcome?

Yeah, this seems reasonable - I just don't know when I can get to it, so a PR would be great.

**Comment by robingenz** [comment]
> Yeah, this seems reasonable - I just don't know when I can get to it, so a PR would be great.

Done: #7641
