### ISSUE TITLE
[Bug]: Update CapacitorHttp "Large File Support" doc, fix Filesystem.downloadFile() doc

### ISSUE THREAD

**Issue by bluepuma77** [ionic-team/capacitor#7477]
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌

### Platforms Affected

- [X] iOS
- [X] Android
- [X] Web

### Current Behavior

Current [CapacitorHttp doc](https://capacitorjs.com/docs/apis/http#large-file-support) states:
> **Large File Support**
> Due to the nature of the bridge, parsing and transferring large amount of data from native to the web can cause issues. Support for downloading and uploading files to the native device is planned to be added to the @capacitor/filesystem plugin in the near future.

### Expected Behavior

Instead it should probably be updated and link to [Filesystem.downloadFile() doc](https://capacitorjs.com/docs/apis/filesystem#downloadfile).

At the same time [Filesystem.downloadFile() doc](https://capacitorjs.com/docs/apis/filesystem#downloadfile) needs to be improved, as it is totally missing all the [HttpOptions from CapacitorHttp](https://capacitorjs.com/docs/apis/http#httpoptions), currently only shows `path` and `directory` as parameters, but something like `url` is probably needed for a download ;-)

Some note in the other direction on how to enable `CapacitorHttp` for `Filesystem.downloadFile()` might help, too.

### Project Reproduction

https://forum.ionicframework.com/t/how-to-use-filesystem-downloadfile-how-to-set-url/241420

**Comment by jcesarmobile** [comment]
It's a problem on the docs generator, already mentioned on https://github.com/ionic-team/capacitor-plugins/issues/1884#issuecomment-1795680833
