### ISSUE TITLE
window.history.back() doesn't work in Android

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#748]
## Version

1.0.0-beta.4

## Platform

Android, used with Vue and vue-router

## Issue

When application launched as an Android app, calls to `window.history.back()` do nothing.

They do not throw errors, anything. They simply do not go to the previous route, even when you go deeply through the app.

On the other hand, `window.history.back()` works as expected when application launched as PWA.

Issue _always_ appears on the fresh launch of the Android app. If app would be left then for a few minutes, sometimes `window.history.back()` starts to work.

Issue not related particularly to the Vue — it will appear in any SPA, which uses browser history mode.

**Comment by jcesarmobile** [comment]
tried in a frameworkless app both SPA and navigating to different files and it's working fine, so this is fixed or not a Capacitor issue.

**Comment by kmschott** [comment]
What was the fix to this issue? I am currently encountering the same.
