### ISSUE TITLE
[Feature]: material you themeing

### ISSUE THREAD

**Issue by theotheroracle** [ionic-team/capacitor#7484]
### Description

https://github.com/Materialious/Materialious/issues/308 the developer of this app reported that material you colour functionality is not supported, but this would be a very useful feature that shouldn't be too difficult to implement 

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

pull the colors using https://source.android.com/docs/core/display/material

**Comment by jcesarmobile** [comment]
Capacitor doesn't provide any UI or colors.
