### ISSUE TITLE
Strange buggy behaviour introduced in beta 6

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#750]
I have been using Capacitor for a while now, since the first Alpha-version actually. This particular issue has never occured before. This occured for me on Android with my Vue.js-application (scaff. via a webpack-template). I haven't tested it on iOS. No problem on the web. And, to be clear, no problem what so ever in earlier beta (4) - I have rolled back and tested it.

The issue is connected to the "this"-keyword I think. Sometimes its value is correct and sometimes it isn't. How this is so I really have no clue. Something must have been introduced since beta 4 which brought about this effect.

**Example:**

I use Vuex-actions to call my API. It can look like the following:

import { getMembers } from '../store/actions'

And in the mounted-hook:

getMembers(this.$store, this.user.email)

More than often this will produce the error "Cannot read property 'email' of null". Sometimes it will work though. At the moment I can't use beta 6 at all because of this.

**Comment by solojuve1897** [comment]
Doing it like the following will possibly solve it (I think, not totally sure):

let _this = this
getMembers(_this.$store, _this.user.email)

The problem is that I have to go through my whole project to find all possible occurrences where this behaviour can occur and change the code. The question left unanswered though is what happened since beta 4 which brought about this?

**Comment by mlynch** [comment]
It seems highly unlikely this hasn’t anything to do with Capacitor. The only thing that maybe did anything was the change we made to remove arrow functions, but I doubt that’s related.

**Comment by solojuve1897** [comment]
I actually think you are right @mlynch, not sure though. I really dont know what's going on here and how come there is a difference between building with Beta 4 and Beta 6. Will do some more testing tomorrow and see what I arrive at.

**Comment by solojuve1897** [comment]
@mlynch 

I have solved the problem. I have an interceptor in my main.js catching 401-responses which my API sends under some specific circumstances. When this is the case I do some user-cleanup to logout, ultimately setting user to null. So for some reason an endpoint which is working with previous versions of Capacitor is returning a 401 when building with beta 6. Strange, but the bug is most certainly on my side. Don't ask me why, I really don't care anymore, just happy to have solved it.
