### ISSUE TITLE
[Bug]: Focus is reset to the first focus element when put the focus by physical keyboard and rotate the screen

### ISSUE THREAD

**Issue by cuonghuunguyen** [ionic-team/capacitor#7502]
### Capacitor Version

@capacitor/ios: not installed
@capacitor/cli: 6.0.0
@capacitor/android: 6.0.0
@capacitor/core: 6.0.0

### Other API Details

```Shell
npm: 10.2.4
node: v20.11.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Steps to reproduce:
* Use the physical keyboard's tab key to focus any elements
* Rotate the screen 

-> The focus is moved back to the first focusable element

### Expected Behavior

The focus element keeps on the same element

### Project Reproduction

https://github.com/cuonghuunguyen/capacitor-demo

### Additional Information

**This issue cannot be reproduce on Emulators, please reproduce on the real device**

Any capacitor project, I can reproduce it when using Iconic plugin of vscode and create a new template project using React
_No response_

**Comment by jcesarmobile** [comment]
I've tested on two real Android devices and I can't reproduce.
Might be some bug on the WebView version your device has, I tested on Android 11 and Android 14 devices with WebViews 120.0.6099.43, 126.0.6478.71 and 128.0.6547.3 versions
