### ISSUE TITLE
[Feature]: how to do ssl pinning?

### ISSUE THREAD

**Issue by pratz0701** [ionic-team/capacitor#7505]
### Description

how to do ssl pinning?

### Platforms

- [X] iOS
- [ ] Android
- [X] Web

### Request or proposed solution

"plugins": {
		"CapacitorHttp": {
		  "enabled": true
		},
		"SSLPinning": {
			"certs": ["ios/App/App/Certificates/_.chalo.com.cer", "ios/App/App/Certificates/_.chaloweb.com.cer"]
		  }
    }
this is implemented inside capacitor.config.json file, but when i dont add the certificates the app runs fine. How to check if the app has ssl pinning enabled?

**Comment by jcesarmobile** [comment]
For SSL pinning you need the `@ionic-enterprise/ssl-pinning` plugin, which is a paid plugin.

https://ionic.io/docs/ssl-pinning/install

**Comment by pratz0701** [comment]
I am currently using an ionic app , can you please help me buy this plugin without creating the new ionic app? and if I try to install this plugin without paying, it gives me error that "https://registry.npmjs.org/@ionic-enterprise%2fssl-pinning - Not found
npm ERR! 404  '@ionic-enterprise/ssl-pinning@*' is not in this registry." is this an expected error?

**Comment by jcesarmobile** [comment]
Try contacting sales team

https://ionic.io/contact/sales
