### ISSUE TITLE
[Feature]: How to output logs

### ISSUE THREAD

**Issue by defolly** [ionic-team/capacitor#7506]
### Description

when npx cap run android -l   Can the logs be printed on the vscode terminal?

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

when npx cap run android -l  Can the logs be printed on the vscode terminal?  Like  react native cli ,  It's  very helpful for the development phase

**Comment by jcesarmobile** [comment]
No, they can't be printed.
