### ISSUE TITLE
Being able to restrict "npx cap sync" to one platform?

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#751]
I have both iOS and Android in my repo and am using VSTS to automate the build process. I begun automating Android and got this working. Then I started working with iOS and got that working. When going back to Android to test a new build I will get the following error when running "npx cap sync":

[error] 'pod' is not recognized as an internal or external command

I'm asuming that since I now have both iOS and Android in the repo Capacitor will try to sync both platforms and fails when coming to iOS (since it's building on a Windows-machine for Android). How do you propose solving this issue? I was thinking if one could restrict so that one only syncs one platform?

E.g. npx cap sync --android

**Comment by jcesarmobile** [comment]
You already can, the command is npx cap sync android

**Comment by solojuve1897** [comment]
Thanx @jcesarmobile. Missed that :-)
