### ISSUE TITLE
[Bug]: Error Registering Plugins

### ISSUE THREAD

**Issue by vishwasganatrahl** [ionic-team/capacitor#7512]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0
  @capacitor/android: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
npm --version output: 10.2.3
node --version output: v20.10.0
pod --version output: 1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

I have been using capacitor/push-notification and capawesome/fcm for push notification, also capacitor/screen-orientation deps for my project and they were working fine untill today I get error messages for these plugins that they are not implemented on IOS, and while running the IOS app on the mobile, I get this error printed on the xcode console:

Error registering plugins: keyNotFound(CodingKeys(stringValue: "packageClassList", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"packageClassList\", intValue: nil) (\"packageClassList\").", underlyingError: nil))

⚡️  Loading app at https://example.app.com...

### Expected Behavior

NA

### Project Reproduction

NA

**Comment by sahildev-ambula** [comment]
Any luck on this ?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
