### ISSUE TITLE
[Bug]: QR code parse error, error = R: No MultiFormat Readers were able to detect the code.

### ISSUE THREAD

**Issue by zemmelmootez** [ionic-team/capacitor#7514]
### Capacitor Version

6.0

### Platforms Affected

- [ ] iOS
- [ ] Android
- [X] Web

### Current Behavior

the camera is not opening and i'm getting this error in console

### Expected Behavior

expecting the camera to open

### Project Reproduction

https://gist.github.com/zemmelmootez/c0be9e2381d3db7ae4f6ef127d5ceff5

### Additional Information

this is error only in prod  in dev it work ine

**Comment by jcesarmobile** [comment]
please, report the issue on https://github.com/ionic-team/capacitor-barcode-scanner/issues and provide a full sample app and steps to follow to reproduces the problem, not just a snippet of code
