### ISSUE TITLE
[Feature]: Add geolocation EXIF data to images captured with the camera

### ISSUE THREAD

**Issue by nelsonvassalo** [ionic-team/capacitor#7524]
### Description

Add the additional EXIF data to images captured with the camera, in the same way images from the gallery already do.

### Platforms

- [X] iOS
- [ ] Android
- [X] Web

### Request or proposed solution

GPSLatitude, GPSLatitudeRef, GPSLongitude and GPSLongitudeRef should be in the EXIF data. Right now exif does not include those on iOS platform

### Additional Information

It seems it is implemented [on Android](https://github.com/ionic-team/capacitor/pull/2284) but not on iOS only.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by ryaa** [comment]
@nelsonvassalo 

> GPSLatitude, GPSLatitudeRef, GPSLongitude and GPSLongitudeRef should be in the EXIF data. Right now exif does not include those on iOS platform

It seems that this is not available (see https://stackoverflow.com/a/68075175/5151355). I also faced a similar issue but with the capacitor camera-preview plugin and had to add the missing GPS EXIF details myself - see https://github.com/capacitor-community/camera-preview/issues/164#issuecomment-2232990927

**Comment by nelsonvassalo** [comment]
@ryaa  Yeah I'm also doing that but it's not a good practice to repeat work that we know is done by the camera once already. This information should just be available.
