### ISSUE TITLE
[Bug]: @capacitor/google-maps "Error calling method create on plugin CapacitorGoogleMaps: No method found." on iOS

### ISSUE THREAD

**Issue by juanpe1103** [ionic-team/capacitor#7533]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 5.7.6
  @capacitor/android: 5.7.6
  @capacitor/ios: 5.6.0
  @capacitor/core: 5.7.6

### Other API Details

```Shell
npm 10.7.0
node v20.14.0
pod 1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

(In browser safari, its working fine)
When running the app from Xcode on a physical iPhone or in the emultator, I get the following error:

⚡️  To Native ->  CapacitorGoogleMaps create 20086726
⚡️  Error calling method create on plugin CapacitorGoogleMaps: No method found.
⚡️  Ensure plugin method exists and uses @objc in its declaration, and has been defined

### Expected Behavior

No error, map renders

### Project Reproduction

```
<capacitor-google-maps #mapRef></capacitor-google-maps>

import {GoogleMap} from '@capacitor/google-maps';

@ViewChild('mapRef', {static: true}) mapRef: ElementRef;
  newMap: GoogleMap;

   this.newMap = await GoogleMap.create({
      id: 'capacitor-google-maps',
      element: this.mapRef.nativeElement,
      apiKey: environment.keys.googleMaps,
      config: {
        center: center,
        zoom: 13,
      },
    });
```
ADDITIONAL INFORMATION:
It is the final step for finish the final project of my engineering career :)

**Comment by juanpe1103** [comment]
Can someone help me with this please?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
