### ISSUE TITLE
[Bug]: FormData not working when CapacitorHttp is enabled

### ISSUE THREAD

**Issue by goldenfireking** [ionic-team/capacitor#7538]
### Capacitor Version

		"@capacitor/android": "^6.1.0",
		"@capacitor/app": "^6.0.0",
		"@capacitor/core": "^6.1.0"

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

when I use @capacitor/core@5.7.5,  CapacitorHttp works great, but after I upgrade @capacitor/core version to 6.1.0, when I upload file use formData, the request headers lost Content-Type: "multipart/form-data;" then upload failed.

### Expected Behavior

version 6.1.0 should work as 5.7.5, auto add Content-Type: "multipart/form-data; boundary=--xxxxxxxxxxxxxx" to headers

### Project Reproduction

no link

**Comment by jongbonga** [comment]
I had the same issue after upgrading to capacitor 6, while creating a reproduction code, I noticed the error happened when I set the `content-type: 'multipart/form-data'`, I dropped it from the header and it worked.

So on Capacitor 5 it works with the `content-type: 'multipart/form-data'` hard-coded in the headers, it doesn't on Capacitor 6

Reproduction: https://github.com/jongbonga/code-reproduction

**Comment by michaelwolz** [comment]
This might be related to https://github.com/ionic-team/capacitor/pull/7518 too (even though this is a slightly different behavior). There is also an example implementation as requested. At least after applying the fix, it will work again when manually providing the content-type header.

**Comment by jcesarmobile** [comment]
jongbonga, michaelwolz, can you create a separate tickets for your issues?

**Comment by jongbonga** [comment]
@jcesarmobile sure

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
