### ISSUE TITLE
[Bug]: All plugins return "Not implemented" only on ios

### ISSUE THREAD

**Issue by Lorenzo0111** [ionic-team/capacitor#7539]
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0
  @capacitor/core: 6.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
npm --version: 10.7.0
node --version: v20.14.0
pod --version: 1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

All the plugins, inspecting via Safari develop console, throws "Unhandled Promise Rejection: Error: "<PluginName>" plugin is not implemented on ios"

### Expected Behavior

Everything should work

### Project Reproduction

https://github.com/saundapp/app

### Additional Information

I've already followed this [troubleshooting guide](https://capacitorjs.com/docs/ios/troubleshooting#plugin-not-implemented) but nothing changes. On android everything works fine

**Comment by jcesarmobile** [comment]
Can you provide steps to run the app and reproduce the issue or a simpler app?
I can't run `npm install` nor `yarn install` on the provided app.

**Comment by Lorenzo0111** [comment]
I fixed it myself, thanks for trying to help

**Comment by xbisa** [comment]
@Lorenzo0111 I had a similar issue on iOS. I discovered it only happened when I built my Angular app for production, so I added a new build configuration. It's a temporary solution, good for now.
