### ISSUE TITLE
iOS WebView is not debuggable

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#754]
## Version

1.0.0-beta.4

## Platform

iOS

## Issue

Seems that WebView attached in such a way that it isn't debuggable via Safari.

When simulator actually launched with built Capacitor app, in `Safari -> Develop -> iPhone simulator` said that there is no debuggable view right now, though, it should be.

**Comment by jcesarmobile** [comment]
I think safari sometimes doesn’t detect the webview, try restarting safari or even the computer

**Comment by mlynch** [comment]
Try the Safari Developer Preview. It's less buggy and finds webviews more easily.

**Comment by ArmorDarks** [comment]
Safari Technology Preview fixed the issue, thanks!
