### ISSUE TITLE
[Feature]: Add geolocation EXIF data to images captured with the camera

### ISSUE THREAD

**Issue by nelsonvassalo** [ionic-team/capacitor#7547]
### Description

Add the additional EXIF data to images captured with the camera, in the same way images from the gallery already do.

### Platforms

- [X] iOS
- [ ] Android
- [X] Web

### Request or proposed solution

GPSLatitude, GPSLatitudeRef, GPSLongitude and GPSLongitudeRef should be in the EXIF data. Right now exif does not include those on iOS platform

### Additional Information

It seems it is implemented https://github.com/ionic-team/capacitor/pull/2284 but works only on Android, not on iOS.

[Example repo](https://github.com/taxem-org/test-picture)

Additionally, we should be able to retrieve information after capture or selection from gallery. If we are selecting an image via the prompt, there's no way of knowing whether the image was captured or selected from gallery.

**Comment by jcesarmobile** [comment]
the provided repository is not accessible, can you make it public or provide the correct url?

**Comment by jcesarmobile** [comment]
I've verified that the code is correct, as you can see, the geolocation information is correctly returned when picking an image from the gallery that has geolocation information.

But when taking a new picture from the app, the native component used by the plugin doesn't capture geolocation information, so the plugin can't return it because it's not there to return.

**Comment by nelsonvassalo** [comment]
@jcesarmobile 
`But when taking a new picture from the app, the native component used by the plugin doesn't capture geolocation information, so the plugin can't return it because it's not there to return.`

This is the core problem. Can't we retrieve it?

**Comment by nelsonvassalo** [comment]
Excuse me, why are my comments marked as abuse? And why was the issue closed? It persists…

**Comment by ryaa** [comment]
> I've verified that the code is correct, as you can see, the geolocation information is correctly returned when picking an image from the gallery that has geolocation information.

It seems that no coordinates are returned when a photo(s) are picked on an Android device - see https://github.com/ionic-team/capacitor-plugins/issues/2147
