### ISSUE TITLE
[Bug]: Capacitor 6 migration gets localStorage cleared

### ISSUE THREAD

**Issue by alphagamer7** [ionic-team/capacitor#7548]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
node --version output: v18.17.0
```

### Platforms Affected

- [X] iOS
- [X] Android
- [X] Web

### Current Behavior

So while migrating from capacitor 5 to capacitor 6, the localStorage as well as indexedDB storage gets cleared. 

### Expected Behavior

Migrating from Capacitor 5 to 6 should keep the localStorage and indexedDB storage.

### Project Reproduction

Is there anyway that the localStorage could remain? 

### Additional Information

Capacitor storage remains as expected, only issue with localStorage and indexedDB storage.

**Comment by jcesarmobile** [comment]
It's documented on the Capacitor 6 update guide, the default scheme changes from `http` to `https`, if you want to keep the data you have to set it back to `http` 

https://capacitorjs.com/docs/updating/6-0#update-androidscheme
