### ISSUE TITLE
I'm in the middle of migrating my app from cordova to capacitor.

### ISSUE THREAD

**Issue by akshar-bk** [ionic-team/capacitor#7549]
I'm in the middle of migrating my app from cordova to capacitor.
For offline usages I download a large file (100Mb) and then unzip it (in memory in JS code) and store its data in indexDB.
This unfortunately crashes when using the capacitor filesystem plugin.
I'm currently using two plugins which I wish I could remove:
1. The ability to download a large file straight into the device filesystem (FileTransferPlugin as this fails in "classic" cordova)
2. The ability to open a large file and use it as a blob (or arraybuffer)

Here's my current code and future code if anyone is interested to see how this is being used in my app:
Currently using cordova file plugin and file transfer plugin
https://github.com/IsraelHikingMap/Site/blob/e10acfbfcc15d7f4601bb923581254f3d1ee1f68/IsraelHiking.Web/src/application/services/file.service.ts#L346L354
https://github.com/IsraelHikingMap/Site/blob/7784673508d3ee8ce22e91e04b74af818295d7f5/IsraelHiking.Web/src/application/services/file.service.ts#L339L350

_Originally posted by @HarelM in https://github.com/ionic-team/capacitor/issues/984#issuecomment-1199828231_

**Comment by akshar-bk** [comment]
@HarelM I would like to know how you proceed?
Currently I have a similar use case as of yours.

**Comment by HarelM** [comment]
I'm not sure I understand the question. 
I'm still using these plugins in my app, which now uses capacitor and I don't have a capacitor "native" plugin that does the same as those. I also did not spend the time to develop one, so I don't think I'm entitled to complain...
My app doesn't crash as far as I know...

**Comment by jcesarmobile** [comment]
Capacitor's Filesystem plugin has a downloadFile method that downloads directly into the Filesystem
https://capacitorjs.com/docs/apis/filesystem#downloadfile

And there is a `convertFileSrc` helper function that turns filesystem urls into "WebView" urls that you can use from html/javascript like in img or video src attribute or on fetch/XHR calls to get a Blob or any other web usage that you can think of
https://capacitorjs.com/docs/core-apis/web#convertfilesrc
