### ISSUE TITLE
add options in capacitor config file

### ISSUE THREAD

**Issue by faustobdls** [ionic-team/capacitor#755]
Hello, I would like to add to the "capacitor.config.json" the features we had in the "config.xml" of the cordova:
1. config minVersionSDK and android targetVersionSDK
2. splashScreen image and app icon configuration

these two features would be a hand in the wheel, because we could use the ionic cordova resource to generate these visual elements and add in the project them through the "npx cap copy".

**Comment by ArmorDarks** [comment]
You can add them to the config file, if you want to, and then pull that data into `build.gradle` file with Groovy

**Comment by jcesarmobile** [comment]
In the app's build.gradle file you have minSdkVersion and targetSdkVersion, you can manually change the values there.
icons can be configured in AndroidManifest.xml
We don't want to add those variables as options on `capacitor.config.json` as that would require to modify the user's project, and that's something we want to avoid.

the splash screen name is already configurable for Android (see https://capacitor.ionicframework.com/docs/apis/splash-screen)
