### ISSUE TITLE
[Bug]: Plugin error return both 'errorMessage' and 'error'

### ISSUE THREAD

**Issue by JingLeiTalan** [ionic-team/capacitor#7554]
### Capacitor Version

When use call.reject(error) in custom plugin,  the plugin js result which contains 'errorMessage' and 'message', the content are the same, 

After checked, seems like in the JS.swift :
![image](https://github.com/ionic-team/capacitor/assets/92030419/50af74a0-dfb3-4c24-8aae-1d6eda07828e)

How can we only return the result which can be parsed more clearly at ionic side ? 

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

JS error rertun an json with errorMessage and message

### Expected Behavior

JS error return what be defined in the call.reject()

### Project Reproduction

no

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
