### ISSUE TITLE
[Bug]:  External component plugins not installed in host application.

### ISSUE THREAD

**Issue by simonetassi** [ionic-team/capacitor#7567]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.5
  @capacitor/ios: 5.7.5

[success] Android looking great! 👌
[error] Xcode is not installed

### Other API Details

```Shell
npm --version: 10.8.2
node --version: v22.4.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Capacitor doesn't install in the "host" application plugins that are installed in external Angular component which is imported in the "host" application itself.  These plugins are installed in the external component project as "dependencies".

Error obtained: `Error: "BarcodeScanner" plugin is not implemented on android`.

This gets fixed after installing the plugins used by the external component in the "host" application, but it's not how it should work.

### Expected Behavior

Since capacitor plugins are installed in the external component project they shouldn't have to be installed in the "host" application as well to make the component work. 

### Project Reproduction

You can find a sample app at https://github.com/simonetassi/ionic-example-app which depends on https://github.com/simonetassi/ionic-example-lib (that is installed via npm).

**Comment by simonetassi** [comment]
You can find a sample app at https://github.com/simonetassi/ionic-example-app which depends on https://github.com/simonetassi/ionic-example-lib (that is installed via npm). 

Even if `@capacitor-mlkit/barcode-scanning` is included among`ionic-example-lib` dependecies , it is not included in the `ionic-example-app` android `capacitor.settings.gradle` file, and consequently it's not being used in the application.

**Comment by jcesarmobile** [comment]
Capacitor plugins need to be explicitly declared in the app's `package.json`, it won't allow plugins that are dependencies of other packages.

If you want, you can implement your own plugin detection logic and pass the list to the capacitor configuration file using the `includePlugins` configuration option.

https://capacitorjs.com/docs/config

for reference https://github.com/ionic-team/capacitor/issues/3265
