### ISSUE TITLE
[Feature]: Show the Capacitor Version Number in the Device API

### ISSUE THREAD

**Issue by digical** [ionic-team/capacitor#7574]
### Description

Show the capacitor version number 

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

Using this API library -> https://capacitorjs.com/docs/apis/device

Add this call: getVersionNum()

### Additional Information

Cordova has this in their platform.  I was using this in Cordova before switching to Capacitor.

**Comment by jcesarmobile** [comment]
Device plugin shows information about the device, so Capacitor version makes no sense in Device plugin.

There is a feature request for adding a version to Capacitor
https://github.com/ionic-team/capacitor/issues/266
