### ISSUE TITLE
[Feature]: Extend JSValueDecoder/JSValueDecoder with More Control over Dates, Data, and Numbers

### ISSUE THREAD

**Issue by grantjbutler** [ionic-team/capacitor#7576]
### Description

It'd be great if we had more control over how dates, data, and non-confirming floats were encoded and decoded.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

`JSONEncoder`/`JSONDecoder` from Foundation allow you to configure the object with a strategy as to how to encode or decode dates, data, and non-conforming floating point numbers. This is most helpful when working with dates, as there are many ways to encode or decode dates from some structured data (it could be formatted as a UNIX timestamp in seconds or milliseconds, or be formatted as an ISO 8601 string).

It'd be great if `JSValueDecoder` and `JSValueEncoder` supported some or all of the various ways that `JSONDecoder` and `JSONEncoder` can be configured to transform these various values.

**Comment by Steven0351** [comment]
Data isn't actually a valid type to pass through to a WKWebView. As far as non-conforming floats, everything actually passes over the bridge as an NSNumber, so I'm not 100% sure anything there could happen. I have, however, opened PR #7647 to address Date and URL issues.

**Comment by Steven0351** [comment]
Thinking more about the non-conforming float strategies, I would believe today those are not throwing at all because Infinity, -Infinity, and NaN are valid NSNumbers. We would need our own strategy that allows for not throwing or converting to a string.
