### ISSUE TITLE
[Bug]: Capacitor Android Keyboard Arrow Keys Focus Order

### ISSUE THREAD

**Issue by joeldhenry** [ionic-team/capacitor#7580]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
npm version 9.8.1
node version 18.18.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Arrow Keys do not follow logical order, and also differ up vs down. this is different order compared with tab index as well. this is an issue when using industrial devices or devices with a built in keyboard. chrome doesnt support arrow keys so i presume this is either webview specific or capacitors implementation of webview. 

### Expected Behavior

arrow keys should navigate arround the page the same way other input types would - such as tab index and should be reproducable. 

### Project Reproduction

N/A

### Additional Information

Tested on android emulator with keyboard, 
pixel 6a with bluetooth keyboard
and zebra MC93000 which has built-in keyboard

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
