### ISSUE TITLE
[Bug]: Capacitor HTTP on android body is missing using rtk query

### ISSUE THREAD

**Issue by WurstMitBrot** [ionic-team/capacitor#7584]
### Capacitor Version

💊   Capacitor Doctor  💊 
Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/ios: 6.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
❯ npm --version
10.5.0
❯ node --version
v21.7.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

When using the capacitor http plugin with the following config
```
  plugins: {
    CapacitorHttp: {
      enabled: true,
    },
  },
```
and also using rtk query post requests are missing the body.
This only happens on android and if the config is active.

Using fetch the body is sent and everything works.

### Expected Behavior

Making a post request with rtk query and capacitor http plugin should send the body property with the request.

### Project Reproduction

https://github.com/WurstMitBrot/capacitor-fetch-example

**Comment by jcesarmobile** [comment]
So you say that the `Create user rtk query ✕` button is not doing anything on Android?

In my testing it's creating a John Doe user like iOS does.

What's the Android version of the device/emulator where you are testing?

**Comment by WurstMitBrot** [comment]
@jcesarmobile i just updated all sdks etc. It indeed works. Thank you very much.
