### ISSUE TITLE
[Bug]: cannot regrister capacitorDidRegisterForRemoteNotifications

### ISSUE THREAD

**Issue by feruz111** [ionic-team/capacitor#7586]
### Capacitor Version

<img width="665" alt="image" src="https://github.com/user-attachments/assets/7475b936-81fe-4ee0-ba9d-d1561a12427f">

Hello dear team,

When running `PushNotifications.removeAllDeliveredNotifications();` i am getting this error. I am calling this function in my react tsx project, in layout component in useEffect to fire when component launches. Is there any specific reason why i am getting this error and how to resolve it?

Thanks Feruz.

### Platforms Affected

- [x] iOS
- [ ] Android
- [ ] Web

### Current Behavior

When running `PushNotifications.removeAllDeliveredNotifications();` i am getting this error.

### Expected Behavior

When running `PushNotifications.removeAllDeliveredNotifications();` it should not throw that error if app is registered for push notifications

### Project Reproduction

https://apps.apple.com/gb/app/clientwindow/id6446678741

**Comment by feruz111** [comment]
@markemer Hi there, please could you help me with this, in general why would we get this kind of error?

**Comment by jcesarmobile** [comment]
please, provide a sample app (source code, not built app)

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
