### ISSUE TITLE
[Android Studio]Unable to delete directory

### ISSUE THREAD

**Issue by moh4sa** [ionic-team/capacitor#7590]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
Android Studio Koala | 2024.1.1 Patch 1
Build #AI-241.18034.62.2411.12071903, built on July 11, 2024
Runtime version: 17.0.11+0-17.0.11b1207.24-11852314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

I'm facing the below error it prevents me from running the app
`Unable to delete directory '/Users/app/node_modules/@capacitor/status-bar/android/build'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - /Users/app/node_modules/@capacitor/status-bar/android/build/generated/res/pngs/debug`

### Expected Behavior

to run without any issue

### Project Reproduction

https://github.com/moh4sa/repo

**Comment by jcesarmobile** [comment]
Closing since this doesn't look like a Capacitor issue and the provided repo is not accessible or is invalid.

Try closing and reopening Android Studio making sure the app project is open only once.
Also try invalidating Android Studio cache
https://capacitorjs.com/docs/android/troubleshooting#invalidate-cachesrestart
