### ISSUE TITLE
[Bug]: Failed to load service worker when build app

### ISSUE THREAD

**Issue by radonirinamaminiaina** [ionic-team/capacitor#7592]
### Capacitor Version

```
@capacitor/core: 6.1.1
@capacitor/android: 6.1.1
@capacitor/cli: 6.1.1
```

### Other API Details

```Shell
npm version: 10.1.0
node version: v20.9.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

I have an error `An unknown error occurred when fetching the script.` and `net:ERR_CONNECTION_REFUSED` when loading service-worker.js script.

### Expected Behavior

PWA should work like web browser behavior

### Project Reproduction

https://github.com/radonirinamaminiaina/capacitor-sw

### Additional Information

>I implemented PWA with capacitor, when I run `cap run android`, but it works perfectly in web browser but it has an error within the webview.

Here the result from web browser:
![image](https://github.com/user-attachments/assets/853e1887-7dca-42c5-9c5e-95a0fdd84219)

And the result from webview:
![image](https://github.com/user-attachments/assets/29fba722-7bb1-4a3c-a9ed-e06a1f5dfb3e)
![image](https://github.com/user-attachments/assets/5168964c-09df-4d15-9547-3770b61ad8f6)

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor/issues/1655#issuecomment-579229390
