### ISSUE TITLE
[Feature]: Persist storage (IndexedDB etc.)

### ISSUE THREAD

**Issue by NyaomiDEV** [ionic-team/capacitor#7594]
### Description

We should be able to persist our storage directly when shipping a Capacitor app. This should grant us unlimited quota from the get-go, as the user can clear the app's data to also clear its storage.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

`navigator.storage.persist()` should allow us to persist our IndexedDB data when the origin is `localhost` or whatever is configured in the Capacitor config.

### Alternatives

Community SQLite plugins don't seem to have survived the Capacitor 6 migration. This leaves us with a plethora of old plugins and no clear way to have apps with persistent storage.

**Comment by jcesarmobile** [comment]
`navigator.storage.persist()` is a browser feature. 
If it's not working as intended, please, report it to Google or Apple.

**Comment by NyaomiDEV** [comment]
> `navigator.storage.persist()` is a browser feature. If it's not working as intended, please, report it to Google or Apple.

It is a browser feature, but from my testing it doesn't work on Capacitor Android specifically.

Chrome itself would never prompt the user for such permission, so it falls on Capacitor to make up for that somehow.

Citing [web.dev](https://web.dev/articles/persistent-storage#chrome_and_other_chromium-based_browsers):

> Chrome, and most other Chromium-based browsers automatically handle the permission request, and do not show any prompts to the user. Instead, if a site is considered important, the persistent storage permission is automatically granted, otherwise it is silently denied.
> 
> The heuristics to determine if a site is important include:
> 
> - How high is the level of site engagement?
> - Has the site been installed or bookmarked?
> - Has the site been granted permission to show notifications?
> 
> If the request was denied, it can be requested again later and will be evaluated using the same heuristics.

`window.Notifications` is not available in Capacitor (there's of course the Local Notifications plugin though), and there's no way to "bookmark" ourselves into the Capacitor WebView as a work-around.

Has the "site" (=app) been installed, though? Since the user willingly downloaded our app, I'd assume they have it installed, however the WebView doesn't know that, and still it denies access to persisted storage.

The only heuristic that might pass is high engagement with the WebView, but we don't know if that counts for `localhost` and there's still the risk of having the app newly installed on a device which is low on storage, and having users complain about lost data.

Therefore, I think this *is* a Capacitor issue after all.
