### ISSUE TITLE
[Bug]:  @capacitor/google-maps tagged V6 has unmet peer dependency with V6, forcing install doesn't work on Android

### ISSUE THREAD

**Issue by wgehner** [ionic-team/capacitor#7600]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/ios: 6.1.1

### Other API Details

```Shell
npm --version 10.7.0
node --version v20.15.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

npm install @capacitor/google-maps 

Console output:
      
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: stt-gemini-map@0.0.0
npm error Found: @capacitor/core@6.1.1
npm error node_modules/@capacitor/core
npm error   @capacitor/core@"^6.1.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @capacitor/core@"^5.0.0" from @capacitor/google-maps@5.4.1
npm error node_modules/@capacitor/google-maps
npm error   @capacitor/google-maps@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/Wolfgang/.npm/_logs/2024-08-02T20_14_11_745Z-eresolve-report.txt

npm error A complete log of this run can be found in: /Users/Wolfgang/.npm/_logs/2024-08-02T20_14_11_745Z-debug-0.log

### Expected Behavior

Install success

### Project Reproduction

https://github.com/wgehner/beercss-in-app

### Additional Information

If I force installation with --legacy-peer-deps, Map doesn't show in android device, logcat output shows:

Line 1 - Msg: Uncaught (in promise) Error: "CapacitorGoogleMaps" plugin is not implemented on android

**Comment by jcesarmobile** [comment]
see https://github.com/ionic-team/capacitor-google-maps/issues/5

an update on that, the google library we were waiting on was finally released last week, so there should be a final google maps plugin release soon.

**Comment by wgehner** [comment]
Great, can't wait!
