### ISSUE TITLE
[Feature]: update push notification icon programatically

### ISSUE THREAD

**Issue by snake-py** [ionic-team/capacitor#7603]
### Description

need to update the push notification icon like other icons using the sync command

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

Hello, 

I am building a multi tenant application using capacitor. For that I need to update the push notification icon during my build process. With other icons it already works very well! It would be quite handy for me that I can maybe specify a icon in `capacitor.config.json` as push notification icon. WHich Then gets generated and placed into the respected folders.

**Comment by jcesarmobile** [comment]
Capacitor doesn't handle the icons on sync command, if it's working for you, you probably have something else already handling them, but it's not Capacitor.
