### ISSUE TITLE
[Bug]: all plugins is not implemented on android

### ISSUE THREAD

**Issue by akeagle** [ionic-team/capacitor#7609]
### Capacitor Version

    "@capacitor/android": "^5",
    "@capacitor/camera": "^5",
    "@capacitor/cli": "^5",
    "@capacitor/core": "^5",

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

all plugins is not implemented on android, include official plugin and custom plugin, and this behavior is only on android7, but ok on android9。

### Expected Behavior

plugin can normally work。

### Project Reproduction

Not at the moment

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
