### ISSUE TITLE
[Feature]: Proposed documentation improvement

### ISSUE THREAD

**Issue by maxwelljmckee** [ionic-team/capacitor#7611]
### Description

Improvement to `Custom ViewController` docs article

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

See Capacitor docs https://capacitorjs.com/docs/ios/viewcontroller

In this article, under the section entitled "Edit `Main.storyboard`", the image provided shows the expected initial-state but not the desired end-state. I got stuck on this step for a while as I had changed the `Class` value, but left the `Module` set to `Capacitor`. 

Especially for folks with less native dev experience, it would be nice to include an extra image and/or an extra one or two sentences in the description making this explicit specification.

<img width="774" alt="Screenshot 2024-08-07 at 1 59 36 PM" src="https://github.com/user-attachments/assets/ec2a303e-2b8c-4610-b29a-9ab64f9ba023">
<img width="170" alt="Screenshot 2024-08-07 at 2 04 32 PM" src="https://github.com/user-attachments/assets/5d739456-ac7c-4bd7-aea5-41cb15450e7d">

**Comment by jcesarmobile** [comment]
You can request documentation improvements on the capacitor documentation repository
https://github.com/ionic-team/capacitor-docs/issues
