### ISSUE TITLE
[Feature]: BridgeFragment supports creating plugins？only support activity？

### ISSUE THREAD

**Issue by CHENQINGFU** [ionic-team/capacitor#7613]
### Description

BridgeFragment supports creating plugins？only support activity？

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

BridgeFragment supports creating plugins？only support activity？

**Comment by jcesarmobile** [comment]
Please, don't use github issues to ask questions, just to report issues.


You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26), on [Ionic discord](https://discord.com/invite/UPYYRhtyzp) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository

**Comment by CHENQINGFU** [comment]
已收到邮件。
