### ISSUE TITLE
[Bug]: Camera cannot select picture from Gallery app

### ISSUE THREAD

**Issue by Abhi-dev-sh** [ionic-team/capacitor#7623]
### Capacitor Version

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.7.6
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0

### Other API Details

```Shell
npm version - 10.7.0
node version - 20.15.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Using the Camera plugin on Android phones, when a picture is selected in the Gallery app, this error is thrown: {} //Empty error object.

### Expected Behavior

Users are able to use the Gallery app to select their pictures on android phones.

### Project Reproduction

NA

### Additional Information

We are facing the same issue raised for older versions.
Refer this ticket - https://github.com/ionic-team/capacitor/issues/2060.
The exact behavior we are facing in our app.

Code-
const cameraPhoto = await Camera.getPhoto({
        resultType: CameraResultType.Base64,
         quality: 100,
         width: 1280,
         height: 720,
      });

Reproduction Steps: Configure the Camera plugin to return base64 data and use the option to select a picture from gallery instead of taking a new photo.

**Comment by jcesarmobile** [comment]
Please, report the issue on the plugins repository https://github.com/ionic-team/capacitor-plugins/issues

And make sure you provide a sample app that reproduces the issue, if you are using latest version of the plugin, it requires Capacitor 6 and you are still using Capacitor 6.
