### ISSUE TITLE
[Feature]: Support monorepos with a single `package.json`

### ISSUE THREAD

**Issue by oliveryasuna** [ionic-team/capacitor#7624]
### Description

Support monorepo solutions such as NX and Turbo.

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

This issue was closed a while back: https://github.com/ionic-team/capacitor/issues/5028.

I think it should be considered. Many new projects utilize modern monorepo tools, such as NX and Turbo. At least with NX, typically you will have a single `package.json` in the project root.

As it is now, developers must create a `package.json` in the "app" module, and must ensure that the plugin versions are the same as the root `package.json`.

**Comment by jcesarmobile** [comment]
monorepos are already supported

**Comment by steve-todorov** [comment]
@jcesarmobile could you give an example of how to achieve what @oliveryasuna describes in his ticket? I am also having a similar problem. I don't seem to be able to find this in any examples or in the docs. Perhaps it needs to be updated?

**Comment by carlspring** [comment]
@jcesarmobile  : In what way is the comment above "abuse" and is it really that hard to use actual words that form more meaningful answers?
