### ISSUE TITLE
[Bug]: cannot scroll horizontally on inputs in iOS

### ISSUE THREAD

**Issue by ej-shafran** [ionic-team/capacitor#7627]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌

### Other API Details

```Shell
npm --version: 10.8.1
node --version: v20.13.1
pod --version: 1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

When rendering an HTML input, if the text in the input overflows (in web and Android) you can swipe horizontally over the input to scroll it and show the rest of the text. However, when doing the same thing in iOS, the horizontal swipe does not work, and you cannot easily view the rest of the text within the input. You can run the iOS app in the provided reproduction to see.

### Expected Behavior

I expect the behavior of inputs in iOS to match that of the Android build or the web version.

### Project Reproduction

https://github.com/ej-shafran/capacitor-scroll-ios-issue

**Comment by jcesarmobile** [comment]
I see the same behavior on the iOS app and on iOS Safari, so looks like iOS doesn't behave the way you want, but it's not a bug, just how iOS works.

You can do a long press on the input and that allows you to drag left or right to show more text, but not swipe.
