### ISSUE TITLE
[Bug]: Failed to load the ts file of m3u8 video after enabling CapacitorHttp for capacitor

### ISSUE THREAD

**Issue by ss-sola** [ionic-team/capacitor#7642]
### Capacitor Version

@capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/ios: 6.1.2
  @capacitor/android: 6.1.2

### Other API Details

```Shell
npm -v:10.2.4
node -v:v20.11.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

When I enabled the CapacitorHttp ,like this
 plugins: {
    CapacitorHttp: {
      enabled: true,
    },
  }
When I use HLS to play M3U8 videos, my request for TS files fails. If CapacityHttp is not enabled, my other request will have cross domain issues. I have found a solution, which is to add ${location. origin}/_capacitor_http_interceptor_ before the request address when sending my own request. This can convert the request into a native request, just like enabling CapacityHttp. But I don't understand why requesting the TS file would fail.

### Expected Behavior

The request for the ts file of m3u8 was successful

### Project Reproduction

[测试apk](https://blog.metasola.cn/app-debug.apk)

### Additional Information

I only tried the Android platform

**Comment by ss-sola** [comment]
I have identified the issue and am using Artplayer+HLS to play m3u8 videos（ https://test-streams.mux.dev/x36xhzz/url_0/193039199_mp4_h264_aac_hd_7.m3u8 ），The content fragment of it is' url-462/193039199_mp4_264.aac_hd_7. ts'. When it is requested, the address changes to‘ https://localhost/url_462/193039199_mp4_h264_aac_hd_7.ts ’. What is the address I hope for‘ https://test-streams.mux.dev/url_462/193039199_mp4_h264_aac_hd_7.ts ’. In the web, its address is what I want, but not in the app

**Comment by jcesarmobile** [comment]
You have to use absolute urls, if you use relative urls the browser will create the absolute url based on the `navigator.location.href` value, which for Capacitor apps is `https://localhost/`.
That's how browsers work, not a Capacitor issue.
