### ISSUE TITLE
[Bug]: HTML5 Audio pauses as soon as it is played - Real IOS Device only

### ISSUE THREAD

**Issue by aheadfullofcode** [ionic-team/capacitor#7646]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌

### Other API Details

```Shell
NPM: 8.19.2
Node: v18.19.0
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

HTML Audio stream pauses as soon as I hit play. This issues only occurs in the built app on physical device. The issue does not occur in browser or in the Xcode Simulator 

The audio stream with the issue is [noodsradio.out.airtime.pro](https://noodsradio.out.airtime.pro/noodsradio_a)

### Expected Behavior

The expected functionality is that the play button triggers the audio and the audio continues to play, is not paused. 

### Project Reproduction

https://github.com/noodsradio/noods-app

### Additional Information

I've recently added the following to my capacitor.Config

`
const config: CapacitorConfig = {
  appId: 'io.ionic.starter',
  appName: 'NoodsRadio-App',
  webDir: 'www',
  server: {
    androidScheme: 'https',
    allowNavigation: ['st.chatango.com'],
  },
};`

**Comment by alex-mironov** [comment]
Any suggestions on how to overcome it?

**Comment by RaresTarniceru** [comment]
Disabling the Capacitor cookies fixed the problem for me. Just set in the capacitor.config file: 
`plugins: {
        CapacitorCookies: {
              enabled: false
        }}
`

**Comment by aheadfullofcode** [comment]
@bulletbrand For me the solution was to make sure I was only activating background mode when the app was in the background. So something like this..

` if (this.platform.is('ios') || this.platform.is('android')) {
      // You're on a device, call the native plugins.

      document.addEventListener(
        'pause',
        () => {
          console.log('App is going to background, enabling background mode');
          this.backgroundMode.enable();
          console.log(this.backgroundMode.isActive());
        },
        false
      );

      document.addEventListener(
        'resume',
        () => {
          console.log('App is back in foreground, disabling background mode');
          this.backgroundMode.disable();
          console.log(this.backgroundMode.isActive());
        },
        false
      );
    } else if (this.platform.is('desktop')) {
      console.log('You are running in the browser');
    }`
    
    I'd read elsewhere that having background mode enabled when the app is in foreground can cause issues with play/pause of media
