### ISSUE TITLE
 parallélism for capacitor and Android and iOS 

### ISSUE THREAD

**Issue by aragon5956** [ionic-team/capacitor#7650]
### Description

can include multiple parallelism

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

Hello,
Could you include parallelism in capacitor for Android and iOS, liké multithreading , multitasking , and multiprocessing to execute mobile application using correctly multi cores and virtualisation
Regards

### Additional Information

Good luck

**Comment by jcesarmobile** [comment]
Should be possible already.

**Comment by aragon5956** [comment]
Bandes d'abrutis !
