### ISSUE TITLE
[Bug]: Android build not including capacitor plugins 

### ISSUE THREAD

**Issue by kylejoeckel** [ionic-team/capacitor#7660]
### Capacitor Version

[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
Kyles-MBP-2:micard-next-capacitor kylejoeckel$ pnpm -v
9.1.1
Kyles-MBP-2:micard-next-capacitor kylejoeckel$ node -v
v22.5.1
"next": "14.1.0"
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

The app successfully builds and i am able to navigate around a few of the account creation and sign up pages however when i try to log in or create an account ( the first use case for a capacitor plugin ie Preferences ) i recieve an error "Preferences is not implemented on android". Similarly, i get the same error with any other capacitor such as browser or camera. I've run the normal commands for this process such as sync and copy. I should note that the iOS version works as expected with no issue. 

### Expected Behavior

Obviously these packages should be converting and working as expected in the android build.

### Project Reproduction

https://github.com/miware-org/micard-next-capacitor/tree/android

**Comment by curlyz** [comment]
Probably due to NPM packages is installed with Bun or PNPM. Since these use symlink, not a real files in node_modules.
And pod install turned out need a real files.

**Comment by TheBoneJarmer** [comment]
Hi, I just hit this same issue as well and I realized that the folder `capacitor-cordova-android-plugins` and the file `local.properties` are being ignored by git. I had to remove the `android` folder and re-run `npx cap add android` to realize this. I just checked and they are indeed present in the .gitignore file:

https://github.com/ionic-team/capacitor/blob/5bd85519833797efe13769c545abd1993987d1c9/android-template/.gitignore#L93

https://github.com/ionic-team/capacitor/blob/5bd85519833797efe13769c545abd1993987d1c9/android-template/.gitignore#L27

**Comment by jcesarmobile** [comment]
Closing since the provided repository is not accessible
