### ISSUE TITLE
[Bug]: Marker tintColor, tittle and snippet not rendering

### ISSUE THREAD

**Issue by pepulin** [ionic-team/capacitor#7661]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/ios: not installed
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2

### Platforms Affected

- [ ] iOS
- [ ] Android
- [X] Web

### Current Behavior

I create a marker like this:

```
let id = await map.addMarker({
  coordinate: {
    lat: elem.latitude,
    lng: elem.longitude
  },
  title: 'My Marker',
  snippet: 'This is a custom marker with tintColor',
  tintColor: { r: 60, g: 179, b: 113, a: 0 }
});
```

The marker is rendered, but title, snippet and color does not change.

### Expected Behavior

The marker should be rendered blue and title/snipped should appear.

### Project Reproduction

N/A

**Comment by pepulin** [comment]
Hi!
I've made a basic example (using my project skeleton) to show you what's happening.
https://github.com/pepulin/IonicMap

You have to add your google API Key:
apiKey: "YOUR_API_KEY",

Tell me if you need more info, thanks!

**Comment by jcesarmobile** [comment]
docs say that `tintColor` is iOS and Android only, so it's expected to not work on web, it was not supported in the past, but now should be possible once the plugin start using `AdvancedMarkerElement`, subscribe to https://github.com/ionic-team/capacitor-google-maps/issues/48 if interested on that feature. 
Once that is implemented you could request `tintColor` to be implemented for web by creating an issue on the [plugin repository](https://github.com/ionic-team/capacitor-google-maps/issues)

`title` is working as expected, if you hover the pin you'll see the title.

`snippet` is not documented as Android and iOS only, but it is, the javascript SDK doesn't allow to create snippets
