### ISSUE TITLE
[Feature]: PMTiles Byte Range Request Support

### ISSUE THREAD

**Issue by plasticviking** [ionic-team/capacitor#7664]
### Description

Add `.pmtiles` to `mediaExtensions` in `WebViewAssetHandler`

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

Like audio and video files, PMTiles relies on HTTP 206 Partial Content HTTP responses (made with a `range`). See https://github.com/protomaps/PMTiles for the client-side library.

In a project I have been developing, I found that on the IOS platform I could not access bundled `.pmtiles` assets via range request (instead of partial content, full content was returned and triggered errors within the PMTiles client). I discovered after investigation that Capacitor IOS supports 206 responses for certain path extensions only and further that adding `.pmtiles` to the list of supported extensions resolves the problem and allows access to bundled large vector map tilesets in pmtiles format.

A PR accompanies this issue and passes this addition of the `.pmtiles` extension back upstream in case others have a requirement to use this mapping library.

**Comment by jcesarmobile** [comment]
Can you provide a sample Capacitor app that uses PMTiles library?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
