### ISSUE TITLE
Needing documentation of how to use a Cordova plugin

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ionic-team/capacitor#767]
Creating a new Ionic-V4 app using Capacitor I am having trouble to find the documentation of how it is supposed to be implemented, when there is a need for a Cordova-plugin.

I would like to use
https://www.npmjs.com/package/@ionic-native/app-preferences
and following instructions on 
https://capacitor.ionicframework.com/docs/basics/cordova

I install

_npm install --save @ionic-native/app-preferences@5.0.0-beta.14_

and

_npm install --save cordova-plugin-app-preferences_

I import the ngx-version of the wrapper

_import { AppPreferences } from '@ionic-native/app-preferences/ngx';_

but when running the app I get these messages
```
common.js:295 Native: tried calling AppPreferences.fetch, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
cordovaWarn @ common.js:295
17:13:14.600 core.js:1673 ERROR Error: Uncaught (in promise): cordova_not_available
```
I have tried other plugins like GoogleAnalytics, and also there I end up with the same problem

In the many Migrations guides I haven't found anyone describe the solution

**Comment by jcesarmobile** [comment]
You just use it same way you used it with Cordova. I've just tested on Android and worked fine.
Steps I used:
1. ionic start appName tabs --type=angular (didn't add cordova nor pro)
2. cd appName
3. npm install @capacitor/core @capacitor/cli
4. npx cap init (introduced name and package)
5. npm install --save @ionic-native/app-preferences@5.0.0-beta.14
6. npm install --save cordova-plugin-app-preferences
7. Added `import { AppPreferences } from '@ionic-native/app-preferences/ngx';` on top and `AppPreferences` in providers in app.module.ts file.
8. Added `import { AppPreferences } from '@ionic-native/app-preferences/ngx';` and 
```
constructor(private appPreferences: AppPreferences) {
    this.appPreferences.fetch('key').then((res) => { console.log('test1 ' + res); });
    this.appPreferences.store('key', "justATest").then(res => {
      console.log(res)
      this.appPreferences.fetch('key').then((res) => { console.log('test2 ' + res); });
    })
  }
```
in home.page.ts
9. ran `ionic build`
10. ran `npx cap add android`
11. ran `npx cap open android`
12. Wait for Android Studio to launch
13. Run app from Android Studio with a device connected and check the logs.

That's all.

If you npm install a Cordova/Capacitor plugin after `npx cap add android` then make sure you run `npx cap update` before running from Android Studio again.
If you make html, js, ts, css changes, run `ionic build` again and also run `npx cap copy`.
Or when in doubt, run `npx cap sync` as it does update+copy.

BTW, [Capacitor's Storage](https://capacitor.ionicframework.com/docs/apis/storage) plugin does the same as app-preferences plugin.

**Comment by ThorvaldAagaard** [comment]
I will switch to the Capacitor Storage, but your last line clarified a lot for me as I am using ionic serve to test my application, and is aiming at upgrading my PWA too, and a lot of the cordova plugins i am using does support web/PWA.

A very fine description btw, and I will cross link it to the Ionic forum

But are you then planning building your own plugins for functionality like
cordova-plugin-google-analytics?

**Comment by jcesarmobile** [comment]
For PWA we would like to have the same core plugins as on iOS and Android. But there are no plans on a google analytics plugin as core. Maybe as a separate plugin in the future. 

I've created a new issue about adding cordova browser plugin compatibility to PWA. If you are interested add a :+1: reaction as we use it to see interest in feature request issues.
https://github.com/ionic-team/capacitor/issues/769

Also, might be good if you comment there with a list of plugins with browser support that you use, because I though most of cordova-browser plugins were just mocking the data.
