### ISSUE TITLE
[Bug]: Capacitor Android: Missing Debug Symbols in Generated App Bundle

### ISSUE THREAD

**Issue by tarektaamali** [ionic-team/capacitor#7673]
### Capacitor Version

npx capacitor doctor
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2
  @capacitor/cli: 6.1.2

### Other API Details

```Shell
npm --version output:
10.5.0
node --version output:
v20.12.2

pod --version output (iOS issues only):
n/a
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

When generating an Android App Bundle using Capacitor, the resulting bundle does not include the necessary debug symbols (BUNDLE-METADATA/com.android.tools.debugsymbols) required for debugging and crash analysis in Google Play Console. This issue makes it difficult to diagnose native crashes as the app bundle lacks native debug symbols.

Debug symbols can be manually located in the local build directory (android/app/build/intermediates/merged_native_libs/release/out/lib) when building locally. However, when using Ionic Appflow, there is no access to these files, making it difficult to upload debug symbols to Google Play Console for apps deployed via Appflow.

### Expected Behavior

The App Bundle should include native debug symbols (BUNDLE-METADATA/com.android.tools.debugsymbols) to facilitate debugging and crash reporting.

### Project Reproduction

Create an Ionic + Capacitor project. Build the Android App Bundle using the command ionic capacitor build android --release. Check the generated bundle and note that the debug symbols are missing. Upload the App Bundle to Google Play Console. Notice the warning or errors regarding missing debug symbols for native code.

**Comment by eric-horodyski** [comment]
Hi @tarektaamali, thanks for reaching out! If I understand correctly, you are requesting that Ionic Appflow builds provide these debug symbols. If so, please open a support ticket at https://ionic.zendesk.com. If not, please help me clarify any portions of your issue I've misunderstood.
