### ISSUE TITLE
[Feature]: Add packageClassList property to CapacitorConfig

### ISSUE THREAD

**Issue by ColeKainzRSG** [ionic-team/capacitor#7699]
### Description

packageClassList was recently added to the capacitor config, but it is not in the CapacitorConfig interface

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

Add a packageClassList property to the CapacitorConfig interface

### Alternatives

Set the exported capacitor config type as the union of CapacitorConfig and

```
interface RegistrationList {
  packageClassList: string[];
}
```

**Comment by jcesarmobile** [comment]
Thanks for the proposal, but it's not exposed on purpose, it's only used internally by Capacitor tooling and we put it in the generated `capacitor.config.json` to avoid adding a separate file as on iOS it's harder to add files to the native projects and would have complicated the migration for users, but users should not try to add packages to that list.
