### ISSUE TITLE
[Bug]: export 'buildRequestInit' was not found in @capacitor/core

### ISSUE THREAD

**Issue by dvag-lukas-rybacki** [ionic-team/capacitor#7717]
Thought i found a releated issue here https://github.com/ionic-team/capacitor/issues/6176 but since i am running Capacitor v3.x i am confuesed why this error appears.

### Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

### Installed Dependencies:

  @capacitor/cli: 3.9.0
  @capacitor/core: 3.9.0
  @capacitor/ios: 3.9.0
  @capacitor/android: 3.9.0

### Other API Details

```Shell
npm version 6.14.18
node version v14.21.3
```

### Platforms Affected

- [ ] iOS
- [ ] Android
- [X] Web

### Current Behavior

Running either `ng serve` or `ng build` causes the error in the log

./node_modules/@capacitor/filesystem/dist/esm/web.js:46:28-44 - Error: export 'buildRequestInit' (imported as 'buildRequestInit') was not found in '@capacitor/core' (possible exports: Capacitor, CapacitorException, CapacitorPlatforms, ExceptionCode, Plugins, WebPlugin, WebView, addPlatform, registerPlugin, registerWebPlugin, setPlatform)

### Expected Behavior

Serving or building the `www`

### Project Reproduction

https://github.com/dvag/com.dvag.portos.mobile.app.2.0/tree/feature/ENDKU-1881

**Comment by jcesarmobile** [comment]
The provided app is not accessible.

Anyway, Capacitor 3 is out of support. You are probably using some plugin for a newer Capacitor version and it's conflicting, if you are using Capacitor 3 you should use version 1 of the core plugins

**Comment by dvag-lukas-rybacki** [comment]
For anyone coming accros this issue running older capacitor versions like me, downgrading capacitor/filesystem to v4.x resolves this issue. Sure @jcesarmobile the goal here would be the migrate up to v6
