### ISSUE TITLE
[Bug]:The Android app, built with Capacitor and Angular and installed using app.debug.apk, crashes after I changed the minSdkVersion from 22 to 26.

### ISSUE THREAD

**Issue by Harshida-ck** [ionic-team/capacitor#7729]
### Capacitor Version

    "@capacitor/android": "^6.1.2",
    "@capacitor/angular": "^2.0.3",
    "@capacitor/app": "^6.0.1",
    "@capacitor/core": "latest",
    "@capacitor/inappbrowser": "1.0.2",

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

I recently installed the Capacitor/InAppBrowser plugin in my Android app, which requires a minimum SDK version of 26. After updating the minSdkVersion from 22 to 26 in my project configuration, the app installed via app.debug.apk started crashing unexpectedly. I am looking into the causes of this crash and how to resolve it.

### Expected Behavior

After installing the Capacitor/InAppBrowser plugin and updating the minSdkVersion from 22 to 26, I expected the Android app installed via app.debug.apk to function without any issues. Specifically, I anticipated that the app would launch successfully, and the InAppBrowser functionality would work seamlessly, allowing users to open web content within the app

### Project Reproduction

(https://github.com/Harshida-ck/Capacitor-Angular-App)

**Comment by Harshida-ck** [comment]
Hello! Just checking in to see if there have been any updates on this. Thanks in advance!

**Comment by Harshida-ck** [comment]
I have created the issue under [https://github.com/ionic-team/capacitor-os-inappbrowser](url).

**Comment by jcesarmobile** [comment]
The provided app is not a valid Capacitor app, it doesn't have a capacitor config file nor the android folder with the native project, can you add that?
