### ISSUE TITLE
[Bug]: Filesystem.writeFile throws java.lang.ArrayIndexOutOfBoundsException when base64Data passed is empty

### ISSUE THREAD

**Issue by braincomb** [ionic-team/capacitor#7730]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[error] Xcode is not installed
[success] Android looking great! 👌

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Relevant web layer code:

```ts
      const imageName = "image.jpg";
      const fileContent = await fetch(`/assets/${imageName}`);
      const blob = await fileContent.blob();
      const base64Data = (await convertBlobToBase64(blob)) as string;

      // Write the file to cache directory
      const savedFile = await Filesystem.writeFile({
        path: imageName,
        data: base64Data,
        directory: Directory.Cache,
      });
```

When file is found and it forms a proper `base64Data`, the application works as expected. However, when I mistyped the fetch path to `/public/assets/${imageName}`, the file was not found and therefore `base64Data` formed was empty like so: `data:image/jpeg;base64,`, this causes Filesystem.writeFile to crash the application:

> 23:01:27.588  E  Unable to open asset URL: http://localhost/public/assets/image.jpg
> 23:01:27.611  V  To native (Capacitor plugin): callbackId: 109817524, pluginId: Filesystem, methodName: writeFile
> 23:01:27.611  V  callback: 109817524, pluginId: Filesystem, methodName: writeFile, methodData: {"path":"image.jpg","data":"data:image\/jpeg;base64,","directory":"CACHE"}
> 23:01:27.612  E  Serious error executing plugin
>                  java.lang.reflect.InvocationTargetException
>                  	at java.lang.reflect.Method.invoke(Native Method)
>                  	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
>                  	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)

Full stacktrace attached:
[stacktrace.txt](https://github.com/user-attachments/files/17485682/stacktrace.txt)

### Expected Behavior

When base64Data passed is empty, I expect the application to not crash and simply return and propagate the error to the web layer.

### Project Reproduction

N/A

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
