### ISSUE TITLE
[Bug]: CapacitorCordova pod contains AppDelegate

### ISSUE THREAD

**Issue by jeroentrappers** [ionic-team/capacitor#7734]
### Capacitor Version

CapacitorCordova version 4.7.0

https://github.com/CocoaPods/Specs/blob/master/Specs/e/8/3/CapacitorCordova/4.7.0/CapacitorCordova.podspec.json

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

During build, there can be  conflicts, because this file is not prefixed as it normally should be for a library.

### Expected Behavior

AppDelegate should not be part of the library.

### Project Reproduction

any ios project that includes that pod 

### Additional Information

pod 'CapacitorCordova'

**Comment by jcesarmobile** [comment]
The file exists for Cordova Plugin compatibility and needs to be called like that for plugins that have Categories on AppDelegate to compile.
