### ISSUE TITLE
[Bug]: SPM - capacitor-swift-pm.git Version declared to branch main

### ISSUE THREAD

**Issue by 7-plus-t** [ionic-team/capacitor#7735]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/ios: 6.1.2
  @capacitor/android: 6.1.2

### Other API Details

```Shell
> npm --version
10.9.0

> node --version
v22.10.0
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

Using the SPM beta for iOS:
In the `Package.swift` of CapApp-SPM, generated by `npx cap sync`, the dependency on Capacitor and Cordova is declared as follows: 
`.package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", branch: "main"),`

This causes SPM to use the latest commit of `https://github.com/ionic-team/capacitor-swift-pm.git` and therefore always the newest Capacitor version is used. This cannot be overridden by the parent app, as the `branch: "main"` overrules other constraintes like `exact` or `from` when there is a conflict.

A similar problem exists in all the Capacitor plugins that have been converted to the SPM structure, where in `Package.swift` the dependency to Capacitor is declared with `branch: "main"`.

### Expected Behavior

The `Package.swift` of CapApp-SPM and the plugins should be changed, so it states:
`.package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", from: "6.0.0"),` (or `7.0.0` for the upcoming Capacitor release).
This allows the parent app to declare the version of Capacitor to be used, without SPM resolution conflicts.

### Project Reproduction

Use any plugin example app

**Comment by flgubler-ergon** [comment]
We have faced the same problem in our project: the build suddenly started using the _capacitor 7_ alpha version which obviously is unacceptable for a productive app.

A reproduction can be found here: https://github.com/ionic-team/capacitor-ios-spm-template/blob/main/template/App/CapApp-SPM/Package.swift - it is apparently a different dependency, but uses `branch: "main"` as well.

**Comment by 7-plus-t** [comment]
see https://github.com/ionic-team/capacitor-plugins/pull/2221 for fix in plugins

**Comment by flgubler-ergon** [comment]
Cool, thanks
