### ISSUE TITLE
[Feature]: spm for barcode-scanner

### ISSUE THREAD

**Issue by rbalet** [ionic-team/capacitor#7739]
### Description

supporting spm for the barcode-scanner library

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

Support spm: https://capacitorjs.com/docs/ios/spm

**Comment by jcesarmobile** [comment]
barcode plugin is located at https://github.com/ionic-team/capacitor-barcode-scanner/issues, you can create feature requests there
