### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by HannanAkbar** [ionic-team/capacitor#774]
It would be great to add WebAssembly support. Is it planned?

**Comment by bmsantos** [comment]
@HannanAkbar, yes, Capacitor works just fine with WASM and I don't think that it requires any official support. You can try it with Blazor using Bionic, an experimental framework for Blazor that tries to have the amazing feeling of Ionic CLI. Its all experimental at this point.
https://bmsantos.github.io/bionic/

**Comment by jcesarmobile** [comment]
As @bmsantos said, it already works as it’s implemented by the browser, going to close the issue. 

If you face specific wasm issues that only apply to Capacitor, please, report them providing more details and we will try to fix it

**Comment by XamiKami** [comment]
It in fact does not work, [see my issue here](https://github.com/ionic-team/capacitor/issues/1864)
because it doesn't seem to accept the `application/wasm` Mime-type
