### ISSUE TITLE
[Bug]: Missing documentation for plugin @capacitor/motion

### ISSUE THREAD

**Issue by frederikheld** [ionic-team/capacitor#7743]
### Capacitor Version

See https://capacitorjs.com/docs/apis/motion in the version of 2024-10-30

### Platforms Affected

- [ ] iOS
- [ ] Android
- [ ] Web

### Current Behavior

The `devicemotion` event is not available on Android in insecure contexts. See this statement from the Chromium team: https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins/ This seems to affect the WebView as well.

Therefore this plugin will not work if [live-reloading](https://capacitorjs.com/docs/guides/live-reload) is enabled! This took me some hours to figure out!

Also I would appreciate if you could add some lines about the advantages of this plugin compared to the `devicemotion` event listener. See my question #7742

### Expected Behavior

I don't have to debug for hours

### Project Reproduction

//

**Comment by jcesarmobile** [comment]
You can report Capacitor plugins issues at https://github.com/ionic-team/capacitor-plugins/issues
