### ISSUE TITLE
[Feature]: Add a plugin to pass phone calls

### ISSUE THREAD

**Issue by JulienLecoq** [ionic-team/capacitor#7755]
### Description

Add a plugin to pass phone calls

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

Capacitor currently lacks a plugin for making phone calls. Therefore, it’s not possible to initiate a phone call by long-pressing a phone number in an ion-item (an Ionic component), for example. I need this for my mobile application.

I don't know if this would be possible to implement on Web since long presses are not detected as user input, shitty web... as usual, but I assume this should be possible on iOS/Android since I don't think there is the same limitation.

### Alternatives

There is this community plugin: https://github.com/mantosh59/call-number

But it does not seem to be maintained and does not seem to work.

**Comment by jcesarmobile** [comment]
You should be able to use anchor tags (`a`) to call to numbers, i.e. `<a href="tel:666666666">666666666</a>`. Not on long press though, a simple click will show the options to call or open phone app with the number dialled depending on the OS and device.

Also [app-launcher](https://capacitorjs.com/docs/apis/app-launcher) plugin seems to work for calling too, i.e. `AppLauncher.openUrl({ url:'tel:666666666' });`.

If none of those is acceptable for your use case you could create a proposal on [capacitor-community proposals repository](https://github.com/capacitor-community/proposals)
