### ISSUE TITLE
[Bug]: Filesystem plugin does not notify user once the download is completed

### ISSUE THREAD

**Issue by candida17** [ionic-team/capacitor#7760]
### Capacitor Version

User should be notified when the download is complete and open the downloaded file
Using the capacitor version 6
Angular 18

### Platforms Affected

- [X] iOS
- [X] Android
- [ ] Web

### Current Behavior

Currently, once the download is complete user needs to manually navigate to Files app and locate the file.

### Expected Behavior

Expectation is to notify the user when download is complete and upon clicking the notification take user to the file location

### Project Reproduction

sample project will be created if required

**Comment by jcesarmobile** [comment]
That's up to the developer to implement, some developers might want that behavior, some others might not.
