### ISSUE TITLE
[Bug]: BridgeFragment doesn't call WebView.destroy in Fragment.onDestroy()

### ISSUE THREAD

**Issue by hbordersTwitch** [ionic-team/capacitor#7766]
### Capacitor Version

[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊 Capacitor Doctor 💊

Latest Dependencies:

@capacitor/cli: 6.1.1
@capacitor/core: 6.1.1
@capacitor/android: 6.1.1
@capacitor/ios: 6.1.1

Installed Dependencies:

@capacitor/cli: 6.1.1
@capacitor/ios: 6.1.1
@capacitor/android: 6.1.1
@capacitor/core: 6.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
$ npm --version
10.7.0
$ node --version
v22.2.0
$ pod --version
1.15.2
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

[`BridgeFragment.onDestroy()` calls `Bridge.onDestroy()`](https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/java/com/getcapacitor/BridgeFragment.java#L127-L132), but [`Bridge.onDestroy()` does not call `WebView.destroy()`](https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L1349-L1358).

This matters because if we don't call `WebView.onDestroy()`, the `WebView` leaks its `WebMessageListener` instances. Capacitor's `WebMessageListener` holds a references to the `CapacitorWebView`, which holds a reference to the `Bridge`, which holds a reference to the `BridgeFragment`.

### Expected Behavior

After `BridgeFragment.onDestroy()`, Capacitor cleans up all resources

### Project Reproduction

Please let me know if you require a repro for this.

### Additional Information

One can work around this by extending `BridgeFragment.onDestroy()` and calling `bridge.getWebView().destroy()` manually.

Thank you for this project!

**Comment by jcesarmobile** [comment]
Thanks for the issue, but we are removing `BridgeFragment` on Capacitor 7 since is not something Capacitor apps use.

If you are using it, we would recommend to just copy the `BridgeFragment` class into your project or inside a plugin and use that one instead of the one inside Capacitor as it will go away, and then apply any changes you need like calling `WebView.destroy()`.
I've verified that `BridgeFragment` doesn't use any Capacitor's private or protected attributes/classes, so can be recreated outside of Capacitor if needed.

**Comment by hbordersTwitch** [comment]
Just to double-check, are you planning to do a similar deprecation of `CAPBridgeViewController`?

**Comment by jcesarmobile** [comment]
No, `CAPBridgeViewController` is used by Capacitor apps. For iOS we already removed `CAPWebView` class in Capacitor 6, which was sort of the `BridgeFragment` equivalent.
