### ISSUE TITLE
[Feature]: WebView on iOS should respect dynamic system font size from accessibility settings

### ISSUE THREAD

**Issue by marcelklehr** [ionic-team/capacitor#7770]
### Description

WebView on iOS should respect dynamic system font size from accessibility settings

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

A closed issue from 2022 suggests to use font: -apple-system-body to scale text according to the accessibility settings, but this doesn't seem to work (see https://github.com/ionic-team/capacitor/issues/2748 ). Ideally, the default font-size in the webview should already follow the accessibility settings.

### Additional Information

I'm on v6.2.0

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
