### ISSUE TITLE
how to Hide Vertical Scroll bar on iOS 

### ISSUE THREAD

**Issue by diadal** [ionic-team/capacitor#7774]
`setVerticalScrollBarEnabled` version for iOS      
      
              You can create a plugin and put this code in the load method
```
public void load() {
    bridge.getWebView().setVerticalScrollBarEnabled(false);
}
```

Or without a plugin you can put this code in the MainActivity.java

```
    @Override
    public void onStart() {
        super.onStart();
        bridge.getWebView().setVerticalScrollBarEnabled(false);
    }
```

_Originally posted by @jcesarmobile in https://github.com/ionic-team/capacitor/issues/5469#issuecomment-1129924289_

**Comment by jcesarmobile** [comment]
Please, don't use github issues to ask questions, just to report issues.


You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26), on [Ionic discord](https://discord.com/invite/UPYYRhtyzp) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
