### ISSUE TITLE
[Bug]: Ionic app not run IOS 15.5

### ISSUE THREAD

**Issue by diendv** [ionic-team/capacitor#7779]
### Capacitor Version

"@angular/animations": "^18.0.0",
    "@angular/common": "^18.0.0",
    "@angular/compiler": "^18.0.0",
    "@angular/core": "^18.0.0",
    "@angular/forms": "^18.0.0",
    "@angular/platform-browser": "^18.0.0",
    "@angular/platform-browser-dynamic": "^18.0.0",
    "@angular/router": "^18.0.0",
    "@capacitor/app": "6.0.1",
    "@capacitor/browser": "^6.0.2",
    "@capacitor/camera": "^6.0.2",
    "@capacitor/core": "6.1.2",
    "@capacitor/filesystem": "^6.0.1",
    "@capacitor/haptics": "6.0.1",
    "@capacitor/ios": "6.1.2",
    "@capacitor/keyboard": "6.0.2",
    "@capacitor/local-notifications": "^6.1.0",
    "@capacitor/push-notifications": "^6.0.2",
    "@capacitor/screen-orientation": "^6.0.2",
    "@capacitor/share": "^6.0.2",
    "@capacitor/splash-screen": "^6.0.2",
    "@capacitor/status-bar": "^6.0.1",
    "@ionic/angular": "^8.0.0",
    "@ionic/storage-angular": "^4.0.0",
    "@types/lodash": "^4.17.10",
    "highcharts": "^11.4.8",
    "ionicons": "^7.2.1",
    "lodash": "^4.17.21",
    "luxon": "^3.5.0",
    "ng2-file-upload": "^7.0.1",
    "rxjs": "~7.8.0",
    "swiper": "^8.4.5",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

When the app is turned on, the screen displays a white interface.

### Expected Behavior

Help me find the cause and fix this error

### Project Reproduction

no link

**Comment by jcesarmobile** [comment]
Please, don't use github issues to ask questions, just to report issues.


You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26), on [Ionic discord](https://discord.com/invite/UPYYRhtyzp) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository

But you can give this a try
https://forum.ionicframework.com/t/problems-with-white-screen-after-splash-screen-on-android-7-and-below-ionic-7-with-angular/238019/2

Anyway, Ionic is supposed to support iOS 15, so you should probably report the issue in Ionic Framework issue tracker if that happens in newly created apps too
https://github.com/ionic-team/ionic-framework/issues
