### ISSUE TITLE
[Bug]: FormData request failing with CapacitorHttp enabled

### ISSUE THREAD

**Issue by vinay-khatri** [ionic-team/capacitor#7783]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

### Other API Details

```Shell
npm v10.8.2
node v18.20.5
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

I am sending a multipart/form-data request from capacitor.js app in android to my hono backend. But my Hono app throwing an error when trying to parse this request. I send the same request from my website and it works absolutely fine.

When i explicitly set headers as "multipart/form-data", no request is being sent at all. I have also used CapacitorHttp.post() method and XMLHttpRequest but all failed.

```js
const submitReview = () => {
        let formData = new FormData();
        for (var key in review) {
            formData.append(key, review[key]);
        }
        formData.append("image", newImage);
        formData.append("service_id", id);
        fetch(`${string.Api_Url}/v1/service/review`, {
            method: "POST",
            credentials: "include",
            body: formData,
        })
            .then((raw) => raw.json())
            .then((res) => {
                if (res.success) {
                    getService(id);
                    toastType = "success";
                    toastMessage = "Review Submitted";
                    showToast = true;
                } else {
                    console.log(res.error);
                    toastType = "error";
                    toastMessage = res.error;
                    showToast = true;
                }
            });
    };
```

### Expected Behavior

I want my request to return json data.

### Project Reproduction

Not Available

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
