### ISSUE TITLE
[Bug]: @capacitor/filesystem - readdir won't read files from dir

### ISSUE THREAD

**Issue by biast12** [ionic-team/capacitor#7784]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[success] Android looking great! 👌

### Other API Details

```Shell
npm --version output: 10.9.1
node --version output: v21.6.0
```

### Platforms Affected

- [ ] iOS
- [ ] Android
- [X] Web

### Current Behavior

Filesystem.readdir does not output the files within the folder given (it gives an empty array)

When dirpath is "" / not a dir does it give an array with 49 objects where the "langs" dir is listed

The folder structure:
- ROOT/
  - DATA/
    - langs/
      - en.json
      - da.json
      - de.json

Here is my function
```
const importLanguages = async () => {
    try {
      const dirpath = "langs";
      const languageFiles = await Filesystem.readdir({
        path: dirpath,
        directory: Directory.Data,
      });

      console.log(languageFiles);

      const loadedLanguages: { [key: string]: string } = {};

      for (const file of languageFiles.files) {
        const filePath = file.uri;
        const fileContent = await Filesystem.readFile({
          path: filePath,
          directory: Directory.Data,
        });
        const langModule = JSON.parse(fileContent.data as string);
        const langCode = file.name.match(/(\w+)\.json$/)?.[1];
        if (langCode) {
          if (langModule.lang) {
            loadedLanguages[langCode] = langModule.lang;
          } else {
            loadedLanguages[langCode] =
              t("pages.settings.general.lang_missing_key") ||
              "Lang key missing";
          }
        }
      }

      const sortedLanguages = Object.fromEntries(
        Object.entries(loadedLanguages).sort(([, a], [, b]) => {
          if (a === "English") return -1;
          if (b === "English") return 1;
          return a.localeCompare(b);
        })
      );

      setLanguages(sortedLanguages);
    } catch (err) {
      console.error("Error reading language files", err);
    }
  };
```

### Expected Behavior

It should / is expected to list out the en.json, da.json and de.json files within the langs dir, they're in there and it can find the langs dir

### Project Reproduction

It's a private repository, so i can't share a link really

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
