### ISSUE TITLE
[Bug]: iOS App Shows Blank White Screen After Being in Background for a Few Hours

### ISSUE THREAD

**Issue by yashoda-esb** [ionic-team/capacitor#7793]
### Capacitor Version

5.7.0

### Other API Details

```Shell
npm version: 10.2.3
node version 18.19.0

App Framework: Angular + Capacitor
Device: iPhone 12 and in the latest version as well
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

When the app is resumed:

- A blank white screen is displayed.

- Inspecting via Safari Web Inspector shows the <body> tag is empty.

- No UI or functional elements are visible.
![blank-screen-issue](https://github.com/user-attachments/assets/b2a65cff-440a-495e-b950-a29c5d90b975)

### Expected Behavior

The app should resume from where it was paused, with all UI elements intact and functional.

### Project Reproduction

I cannot share my project's code due to confidentiality. However, you can use the official Capacitor starter template with angular the reproduction steps are given above

### Additional Information

When using my app on an iOS device, if I put the app in the background (pause mode) for several hours, and then resume it later, the app shows a blank white screen. Inspecting the DOM reveals that the <body> tag is empty, and none of the expected UI elements or app content is displayed.

This issue occurs only on iOS devices and does not seem to affect Android.

**Steps to Reproduce**

1. Open the app on an iOS device.
2. Perform normal app operations (any feature or page).
3. Minimize the app by pressing the home button or switching to another app.
4. Wait for several hours (or a significant period, like overnight).
5. Resume the app by selecting it from the background.

**Comment by jcesarmobile** [comment]
This is usually caused by the WebView being terminated by the OS while the app is in background due to low memory.
That causes the WebView to reload and depending on how your app is built/configured can cause the white screen, i.e. if you use a router and it's not able to "recreate" the page from the current url. 

Here you can see some different solutions for different frameworks
https://github.com/ionic-team/capacitor/discussions/7097
