### ISSUE TITLE
[Bug]: viewport crash after Share.share() in message

### ISSUE THREAD

**Issue by dabaaaz** [ionic-team/capacitor#7797]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/ios: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/core: 6.2.0

### Other API Details

```Shell
npm 9.6.6
node 18.17.0
pod 1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

When I use **Share.share()**, the webview that I get back seems different, and I can't figure out how to fix it.
If I share it via Mail, there's no issue, but the bug only appears when I share it through the Messages app.

### Expected Behavior

I'd like the black padding not to appear after sharing

### Project Reproduction

Not reproductible like that, need a video ?
But there are screenshots before and after

![IMG_6604 (1)](https://github.com/user-attachments/assets/bc9fd4e0-684c-40cd-8e55-ccc17c334286)
![IMG_6605 (1)](https://github.com/user-attachments/assets/c4944e23-8ae1-4c9e-ad28-5d60348164fe)

### Additional Information

I tried this but nothing change :

  "zoomEnabled": false,
  "ios": {
    "contentInset": "never"
  },

**Comment by jcesarmobile** [comment]
it's a problem on the keyboard plugin, it's already reported on https://github.com/ionic-team/capacitor-plugins/issues/831
