### ISSUE TITLE
BUGs in MockCordovaWebViewImpl init method guids cordova File plugin can't work. 

### ISSUE THREAD

**Issue by netsesame2** [ionic-team/capacitor#783]
Today I found my Cordova File plugin can't work when invoke readAsByteArray() method....

Debug and find that, the plugin will read A File's type use this:
```
resourceApi.getMimeType(....)
```

However, the resorceApi field is always null which is assigned during plugin loading. 
```
//When plugin is created, it will need resourceApi as parameter
public LocalFilesystem(String name, Context context, CordovaResourceApi resourceApi, File fsRoot) {
        super(Uri.fromFile(fsRoot).buildUpon().appendEncodedPath("").build(), name, resourceApi);
        this.context = context;
}
```
The plugin is loaded by PluginManager,  which is then inited by MockCordovaWebViewImpl in init() method. So what's happened?

In the MockCordovaWebViewImpl's init() method, we can see that:
```
// Located in /com/getcapacitor/cordova/MockCordovaWebViewImpl.java
this.pluginManager = new PluginManager(this, this.cordova, pluginEntries);
this.pluginManager.init();
this.resourceApi = new CordovaResourceApi(this.context, this.pluginManager);
```
resouceApi is created after plugin is initted. So plugin always get a null value.
Revert the code as following will resolve the issue:
```
this.pluginManager = new PluginManager(this, this.cordova, pluginEntries);
this.resourceApi = new CordovaResourceApi(this.context, this.pluginManager);
this.pluginManager.init();
```

Hope to update.

**Comment by jcesarmobile** [comment]
Thanks for your input and the debugging.

Would be nice if you could send a pull request with the fix. 

If you don’t know how to do it I can give you a hand.
If you don’t want, let me know and I’ll do it next week.

**Comment by netsesame2** [comment]
Publish a pull fixs here: https://github.com/ionic-team/capacitor/pull/784

**Comment by jcesarmobile** [comment]
merged, thanks!
