### ISSUE TITLE
[cordova-plugin-secure-storage] SecureStorage.create(...) never calls back

### ISSUE THREAD

**Issue by ptitjes** [ionic-team/capacitor#787]
### Environment
```
    "@capacitor/android": "^1.0.0-beta.7",
    "@capacitor/cli": "~1.0.0-beta.7",
    "@capacitor/core": "~1.0.0-beta.7",
    "@ionic-native/secure-storage": "~5.0.0-beta.14",
    "cordova-plugin-secure-storage": "^2.6.8",
```
### Description
When calling SecureStorage.create(...), the promise never resolves or errors.

After debugging it seems the native call is sent to the android bridge but the callbacks are never called.

The plugin works correctly with Cordova.

**Comment by jcesarmobile** [comment]
This plugin was using ArrayBuffer and that was not working in Capacitor.

It has been fixed in https://github.com/ionic-team/capacitor/pull/860 and https://github.com/ionic-team/capacitor/pull/868, so maybe the plugin works now.
