### ISSUE TITLE
New base project not finding locally or globally installed npm modules.

### ISSUE THREAD

**Issue by jcrosby10** [ionic-team/capacitor#793]
Yesterday I installed capacitor to try it out as a replacement for cordova. I like it because in addition to mobile there is also support for electron. I created a base project and can install and run it on a phone. However when I try to load an npm module I run into issues.

If I do `import Something from "module-name";` I get a `SyntaxError: Unexpected identifier`
If I do `import("module-name").then(console.log(module)).catch(console.error(error))` it says it cant find the module. I have tried different local and global modules. It cant even find `@capacitor/core`. If I try to manually point it to where a module is installed like `path/to/node/module-name` I get `Failed to fetch dynamically imported module: https://localhost:7871/node_modules/module-name`. I'm not sure what is going on here. Does anyone have any ideas?

**Comment by jcesarmobile** [comment]
Can you provide a sample project or give more information about your stack?

**Comment by mlynch** [comment]
Hey, sounds like your app needs to have a bundler installed. Capacitor doesn’t prescribe any specific tooling for your actual app. If you use something like Ionic, for example, all of that comes ready out of the box. We are agnostic to your actual JS app tooling.

**Comment by mlynch** [comment]
Changed my mind. Capacitor is imported in the docs so our template should have some basic module loading to make it work. TypeScript + Rollup?

**Comment by jcrosby10** [comment]
Does it have to be TypeScript? Because I'm currently trying to load the modules in a plain JavaScript file using native JavaScript imports that I think would just work.

**Comment by mlynch** [comment]
You have to have a module loader for that to work. You don’t get that for free in a JS app

**Comment by jcrosby10** [comment]
So even using any of these [options](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) I still need a module loader?

**Comment by mlynch** [comment]
Yes, you can't just import node modules in a web app. There has to be some system that can find those modules for you, at build time or through some custom local web server with access to node modules (some electron apps do this). Dynamic `import()` *does* work, but it works based on modules that can be found/loaded like a script tag. That means only files that are accessible to your page like any other static asset (images, scripts, etc.)

**Comment by jcrosby10** [comment]
is there a module loader you recommend?

**Comment by mlynch** [comment]
If you use a bundler like Rollup or Webpack, those will do the module loading and bundling in one, so you don't have to think about importing anything at runtime:

Rollup is a simple one that we use for a number of projects: https://rollupjs.org/

Webpack is also highly popular https://webpack.js.org/

**Comment by mlynch** [comment]
Closing as this issue is stale and it doesn't appear to be capacitor-related.
