### ISSUE TITLE
PWA/Web camera picture rotated on Android

### ISSUE THREAD

**Issue by bmsantos** [ionic-team/capacitor#796]
PWA/Web on Android camera pictures appear rotated.
This seems to be the way Camera works on Android when used through browser.

A possible solution here could be to use the motion API to inform the user to place the phone in the correct orientation for the picture. Unfortunately, the motion API is the one that I haven't been able to make it work yet on any platform, but I will confirm this.

**Comment by bmsantos** [comment]
I've confirmed that Motion only works on PWA/browser if one access to browser events directly:

https://developers.google.com/web/fundamentals/native-hardware/device-orientation/

This works:
```javascript
    self.shadowRoot.querySelector('#listen-to-orientation').addEventListener('click', async function(e) {
      if (window.DeviceOrientationEvent) {
        window.addEventListener('deviceorientation', function (event) {
          console.log(event);
        }, false);
      }
    })
```

This does not work (but I'm assuming that it should):
```javascript
    self.shadowRoot.querySelector('#listen-to-orientation').addEventListener('click', async function(e) {
      const { Motion } = Capacitor.Plugins;
      Motion.addEventListener("orientation", function (event) {
        console.log(event);
      });
    })
```

**Comment by jcesarmobile** [comment]
Closing in favour of https://github.com/ionic-team/ionic-pwa-elements/issues/11 as it should be fixed there, and once it's fixed we should update the version to include the fix.
