### ISSUE TITLE
Push Notifications with Capacitor. Is there a plugin for it?

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#811]
Hi.

I'm a bit confused if there is a plugin built by the Capacitor team for Push Notifications or not. I can't find anything in the docs? If not. What are my alternatives if I want to have it for iOS and Android?

**Comment by jcesarmobile** [comment]
Yes, it has a PushNotifications plugin, but it's undocumented. Will try to document it today.
When in doubt, check the typescript definitions.

Closing as there is another issue open for the Push Notifications
