### ISSUE TITLE
iOS Camera is not fullscreen

### ISSUE THREAD

**Issue by ranolution** [ionic-team/capacitor#819]
In the camera plugin for iOS it does not account for iPads and always displays the camera as a popover. It needs to be fullscreen for iOS standards. As a temporary fix to the problem I have commented out these two lines in the getPhoto function

`//imagePicker!.popoverPresentationController?.delegate = self
  //self.setCenteredPopover(self.imagePicker!)`

And then in the showCamera function I have added this line after the source type is set to camera.

`imagePicker.modalPresentationStyle = .fullScreen`

I am unsure if this fix break anything for other platforms or use cases as I am developing solely for iPad.

**Comment by jcesarmobile** [comment]
> It needs to be fullscreen for iOS standards

Can you point where in the Apple Human Interface Guidelines it says it has to be full screen?

In browser plugin we added an option to choose the presentation style, maybe we could add it here too.

**Comment by ranolution** [comment]
https://developer.apple.com/documentation/uikit/uiimagepickercontroller

From the docs of the uiimagepicker see number 4 for full context.

> On iPad, if you specify a source type of UIImagePickerController.SourceType.camera, you can present the image picker modally (full-screen) or by using a popover. However, Apple recommends that you present the camera interface only full-screen.

**Comment by jcesarmobile** [comment]
Ok, note that for gallery it only allows popover, camera allows both but recommends full screen. So we should add a presentation option that only affects camera and make full screen default, but keep popover as only option for gallery
