### ISSUE TITLE
Capacitor Browser plugin issue

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#825]
I am getting an error on opening link on the browser. In the log you can see I am sending link to open.
```
content.openLinkInBrowser = function (urlToOpen) {
        var deferred = $q.defer();
        console.log({url: urlToOpen});
        Browser.open({url: urlToOpen}).then(function (browserRef) {
            deferred.resolve(browserRef);
        });
        return deferred.promise;
    };
```
<img width="668" alt="screen shot 2018-09-26 at 11 46 33 pm" src="https://user-images.githubusercontent.com/8480351/46105325-6b86a500-c1f3-11e8-8e92-1cf284146fc4.png">
<img width="262" alt="screen shot 2018-09-26 at 11 46 15 pm" src="https://user-images.githubusercontent.com/8480351/46105327-6c1f3b80-c1f3-11e8-87c1-c35680652533.png">
<img width="748" alt="screen shot 2018-09-26 at 11 42 01 pm" src="https://user-images.githubusercontent.com/8480351/46105329-6c1f3b80-c1f3-11e8-9449-a3b8d89ff9a8.png">

**Comment by jcesarmobile** [comment]
I can only reproduce if I use an empty string as url, can you double check that you are not calling open multiple times and one of them is with an empty string?

I've sent a PR that handles the empty string
https://github.com/ionic-team/capacitor/pull/829

**Comment by stripathix** [comment]
@jcesarmobile I found that I need to encodeURI before opening it because url was having space.

To fix encodeURI.
```
Browser.open({url: encodeURI(urlToOpen)}).then(function (browserRef) {
            deferred.resolve(browserRef);
        });
```

**Comment by stripathix** [comment]
Is there any event I can capture when IAB is closed?
