### ISSUE TITLE
Android: Icons are loaded on every router action

### ISSUE THREAD

**Issue by moberwasserlechner** [ionic-team/capacitor#826]
**Issue**

In my `index.html` I have various icons

```
  <link rel="shortcut icon" href="favicon.ico">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/img/icon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/img/icon/favicon-16x16.png">
```

Those icons are loaded once on startup but also on every page change handled by angular router. So I see the following multiple times.

```
D/Capacitor: Handling local request: https://localhost:9911/favicon.ico
D/Capacitor: Handling local request: https://localhost:9911/assets/img/icon/favicon-16x16.png
D/Capacitor: Handling local request: https://localhost:9911/assets/img/icon/favicon-32x32.png
```

I don't think loading those icons is needed at all.  Although its a local server, not loading not required resources should increase the performance. It's a small improvement but many small steps will have a impact.

**Solution / Workaround**
I don't know how to differ a icon request from a normal asset. The file name is not a good approach. The `link` attribute `rel="icon"` would be but I don't have that. afaik.

I will most propably remove the icons from my `index.html` for the android (future ios) build using webpack or use a `index.capacitor.html` without that parts.

**Version info:**
Angular: 6.1.8
Capacitor: 1.0.0-beta.7 it also occured
Android: 5-8

**Comment by moberwasserlechner** [comment]
So I created new configurations in `angular.json` for Android and replacing the default `index.html` with a `index.capacitor.html`, which does only include the absolutely needed stuff. No icons, no manifest, no noscript.

This works great and I got rid of the png icons but the `favicon.ico` remains and is still loaded/handled on every route change.

```
D/Capacitor: Handling local request: https://localhost:9911/favicon.ico
D/Capacitor: Handling local request: https://localhost:9911/favicon.ico
D/Capacitor: Handling local request: https://localhost:9911/favicon.ico
```
The WebView is automatically looking for `/favicon.ico`, although I have not referenced it in a link element.

This could be prevented by Capacitor because the name will not change. It would be nice but so far only its only a logging issue. I'll give it a try and do some testing and eventually create a PR.

**Comment by moberwasserlechner** [comment]
If I do as suggested in https://stackoverflow.com/a/41223255

```
    if ("/favicon.ico".equalsIgnoreCase(path)) {
      try {
        return new WebResourceResponse("image/png", null, null);
      } catch (Exception e) {
        Log.e(LogUtils.getCoreTag(), "favicon handling failed", e);
      }
    }
```

the favicon is only requested once and not on every router action. This was not really expected.

The big question is: Why is it requested on every router action in the first place?

**Comment by moberwasserlechner** [comment]
That doesn't feel right. Wouldn't I then see the same behaviour on the web/pwa as well, if Angular router was responsible.

As I said I have no element pointing to favicon.ico in my index.html, so why would Angular router request the favicon. Isn't it more likely that WebView, WebViewClient or WebChromeClient is responsible for this, because it's their default behaviour.

I searched the angular repo for `favicon.ico` and the only thing not related to `aio` or `benchmark` is https://github.com/angular/angular/blob/master/integration/platform-server/src/server.ts#L38, which seems to be similiar to what I want do.

Additionally: If I remove the favicon.ico from the build because it's not needed I get errors like

```
D/Capacitor: Handling local request: https://localhost:9911/favicon.ico
E/Capacitor: Unable to open asset URL: https://localhost:9911/favicon.ico
E/Capacitor: Unable to open asset URL: https://localhost:9911/favicon.ico
```

I think this use case is worth addressing in Capacitor.

**Comment by moberwasserlechner** [comment]
@mlynch thx for merging.

**Comment by aincube** [comment]
I don't know how it's possible, but I have the same probelm on version **5.6.0**. I have an Android build of Angular project which requests _favicon_ on each router action.
![swappy-20240618_102027](https://github.com/ionic-team/capacitor/assets/365061/e361dd13-3198-4346-a2fe-d25ef57246dd)
