### ISSUE TITLE
How i can send files from camera with CameraResultType.Uri?

### ISSUE THREAD

**Issue by daniel-lucas-silva** [ionic-team/capacitor#833]
```javascript
import { Plugins, CameraResultType } from '@capacitor/core';

const { Camera } = Plugins;

async takePicture() {
  const image = await Camera.getPhoto({
    quality: 90,
    allowEditing: true,
    resultType: CameraResultType.Uri
  });
 
  var imageUrl = image.webPath;
  imageElement.src = imageUrl;
}
```

How i can send form with a camera image file?

**Comment by dalepo** [comment]
Hey Daniel, did you solve this? Could the capacitor team document this better?

**Comment by daniel-lucas-silva** [comment]
i have sent as base64, then i have converted to file on back end;

**Comment by jcesarmobile** [comment]
Capacitor doesn't provide a plugin or method for uploading files, you can use XHR or fetch to do so.

As example of how you can do it.

get the blob from the url: 

`let blob = await fetch(cameraResult.webPath).then(r => r.blob());`

or get the blob from the base64:

`let blob = b64toBlob(contents.data, "image/jpg", 512);`

(google for b64toBlob method).

Once you have the blob, append it to FormData
```
let formData = new FormData();
formData.append("image", blob);
```

And upload it with XHR or fetch (example for XHR)
```
var oReq = new XMLHttpRequest();
oReq.open("POST", "https://yourserver.com/upload.php", true);
oReq.send(formData);
```

**Comment by faizeee** [comment]
thank you @jcesarmobile . you are life saver.

**Comment by AEROGU** [comment]
@jcesarmobile Perfect! thank you
