### ISSUE TITLE
cannot install cordova platform `ios` after `capacitor-ios`

### ISSUE THREAD

**Issue by mixuala** [ionic-team/capacitor#834]
please reference this bug: https://github.com/ionic-team/ionic/issues/15760

I discovered it's enough to hide the capacitor platform folder to install a Cordova platform. This seems to work.

## platform Cordova:ios - Add Cordova platform AFTER Capacitor
> FIX: hide capacitor folder & install ionic-native/cordova
```
# <!-- hide Capacitor -->
<!-- temporarily rename Capacitor folder: ./ios  -->

# <!-- add Cordova/ionic native  -->
ionic integrations enable cordova
ionic cordova run ios
npm install --save @ionic-native/camera@beta
ionic cordova plugin add cordova-plugin-camera
ionic cordova prepare ios

# <!-- re-add Capacitor by restoring folder name -->
npm uninstall --save cordova-plugin-splashscreen
npx cap open ios
npx cap update
npm run build; ionic capacitor copy ios

```

**Comment by jcesarmobile** [comment]
This is a Cordova issue, it fails to install platforms if the project has folders with the name of the platforms. It’s already reported on Cordova JIRA.

Deleting the folder is not a good idea as for capacitor the native projects are not build artifacts and it’s allowed to make manual changes, I think it’s better to rename and rename back after adding the Cordova platforms
