### ISSUE TITLE
Showing recieved Push Notification in the Notification Center and update app-icon badge number?

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#837]
Hi.

So I am implementing Push Notifications for my app and got stuck when I finally reached the point where my device is receiving notifications. At the moment I only log them in the console. How can I:

1.  When recieved, show the notification in the Notification Center?
2.  Update the app-icon badge?
3.  Maybe show a prompt, vibrate etc. 

Conditionally do the above if the notification was recieved when the app was in the foreground or not.

Is any of this possible at the moment? If not I will probably go for a Cordova-plugin or something, since I have a deadline approaching, and see if I can get that working smoothly with Capacitor.

**Comment by solojuve1897** [comment]
On a separate, or maybe directly connected issue, the recieved notification looks like this:

**Comment by solojuve1897** [comment]
On a separate, or maybe directly connected, issue, the stringified version of the recieved notification (on Android) looks like this:

```
I/Capacitor/Plugin/Console: {"data":"{message=Notification Hub test notification}"}
```

I'm reacting to the message-part "message=Notification Hub test notification" which is not correct json missing quotation marks for the key and the string-value. Is this correct? The notification looked like this when it was originally sent from the server:

`{"data":{"message":"Notification Hub test notification"}}`

**Comment by matthew-valenti** [comment]
@solojuve1897 - I'm following in your footsteps and running into similar questions. I've started a forum post here to log progress: https://forum.getcapacitor.com/t/push-notifications/127/4

How are you sending out your push notifications? I'm using cloud messaging but it's unclear if this is compatible with the current Capacitor implementation: https://www.screencast.com/t/1HK1IUfWVv

**Comment by solojuve1897** [comment]
@matthew-valenti

I use Azure notification hub with a ASP.NET Core WebAPI backend.

The plan is trying to implement the Cordova plugin for Push Notifications instead of Capacitors. What I understand is that Capacitors is unfinished at the moment.

https://www.joshmorony.com/sending-push-notifications-with-the-phonegap-push-plugin-in-capacitor/

**Comment by solojuve1897** [comment]
"In Android there are two types of payloads, notification payload and data payload.
Notification payload is displayed by the system, data payload is not.
Your notifications have data payload.
You can probably use the local notification plugin to display the data you receive."

**Comment by fab971** [comment]
Hi everyone,

I think I have a similar issue. Everything is working as expected when the app is in foreground. But when the app is closed pushes are not shown by the notification center. I tried using different payload (data/notification/combination of both) but it sill not working.

The "funy" part is: when I open the app after sending a push, I'm able to read from the handler (pushNotificationReceived) the push message sent before.

I'm not able to see what I'm missing...

PS: Using the phonegap/cordova push plugin works like a charm, I just want to remove all cordova dependencies from my project and use capacitor instead

My environment:
OS: Android
Ionic 4
Push sender: Azure Notification Hub 

Cheers,

Fabien

**Comment by anasvn** [comment]
> Hi everyone,
> 
> I think I have a similar issue. Everything is working as expected when the app is in foreground. But when the app is closed pushes are not shown by the notification center. I tried using different payload (data/notification/combination of both) but it sill not working.
> 
> The "funy" part is: when I open the app after sending a push, I'm able to read from the handler (pushNotificationReceived) the push message sent before.
> 
> I'm not able to see what I'm missing...
> 
> PS: Using the phonegap/cordova push plugin works like a charm, I just want to remove all cordova dependencies from my project and use capacitor instead
> 
> My environment:
> OS: Android
> Ionic 4
> Push sender: Azure Notification Hub
> 
> Cheers,
> 
> Fabien

Did you find solution yet?
