### ISSUE TITLE
Feature Request : Orientation lock plugin

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#838]
We have a player that runs a video. In Cordova we have a plugin to lock the orientation to landscape whenever a video is played. Can we do the same thing with a capacitor?

**Comment by jcesarmobile** [comment]
Issues tagged with plugin request are closed but tracked for reactions to gauge interest.
If you are interested in this plugin, add the thumbs up emoji (+1) reaction on the issue so we can sort them based on it.

**Comment by jcesarmobile** [comment]
Is the player from a plugin? or a video tag?
If it's a plugin you can probably configure it to use the orientation you want.

**Comment by stripathix** [comment]
No, it is a presentation running inside an iFrame. For iPhone, I open url in inAppBrowser and for iPad I open it in modal with iFrame tag. In cordova whenever that iframe is loaded i used to lock orientation to landscape.

**Comment by Ionitron** [comment]
👋 

We now have a repo for [Capacitor Community proposals](https://github.com/capacitor-community/proposals/).

This request has been moved to https://github.com/capacitor-community/proposals/issues/8. Please 👍 the issue if you'd like to see this plugin for Capacitor!

Thanks!
Ionitron 💙
