### ISSUE TITLE
Cannot deeplink to another app via Anchor Tags

### ISSUE THREAD

**Issue by cthos** [ionic-team/capacitor#839]
I'm attempting to link off to Slack using `slack://` urls, which is currently failing on iOS with `Failed to load resource: unsupported URL`.

On Android, this works by a URL Interceptor transforming the link into an Intent, and as such works great.

Is there a way to deep-link like this on iOS?

This did work on Cordova at some point in the past, but I've not checked recently.

**Comment by jcesarmobile** [comment]
It was working if links had `target="_blank"`, but with latest change will open any external link.
