### ISSUE TITLE
app versions

### ISSUE THREAD

**Issue by dahlb** [ionic-team/capacitor#840]
I have been unable to find any capacitor method of setting the app version for android/ios it appears to always set the generated files to version 0.0.1/1, ignoring the package.json version defined.

Is there plans to have the generator set the app version or have I missed something in the way it currently works?

**Comment by jcesarmobile** [comment]
Capacitor doesn't edit your project, so you have to handle the version numbers in the native way for each platform.

So for iOS you set it in the target details by setting Version and Build numbers
![captura de pantalla 2018-10-02 a las 13 02 24](https://user-images.githubusercontent.com/1637892/46345062-7aca8000-c643-11e8-8a99-0ce9d05c8323.png)

For Android you set the versionCode and versionName in the App build.gradle
![captura de pantalla 2018-10-02 a las 13 04 38](https://user-images.githubusercontent.com/1637892/46345144-c67d2980-c643-11e8-8a14-ee3bdce6f175.png)

**Comment by MikeyBeLike** [comment]
For anyone finding this as well, you can also update your ios Info.plist file too if you want to do it programmatically or something..

Changing the version number as outlined above, changed my info.plist file too:

![image](https://user-images.githubusercontent.com/1624261/61059223-92b00b00-a3f0-11e9-9db5-20a4c7f38abf.png)

**Comment by dlodeprojuicer** [comment]
This would be come in handy if xcode can pickup the build and version from capacitor.config.json

```
{
  "appId": "za.co.stech.brand",
  "appName": "Abashwe",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "dist",
  "build": "6",
  "version": "2"
}
```

**Comment by marekgoczol** [comment]
If you're still having this issue, check if you have your version set in build.gradle file for Android (default in `android/app/build.gradle`).

**Comment by REPTILEHAUS** [comment]
+1 for being able to set this in capacitor.config.json
