### ISSUE TITLE
Support nested json for PluginCall options

### ISSUE THREAD

**Issue by moberwasserlechner** [ionic-team/capacitor#845]
Capacitor uses Json for configurations in `com.getcapacitor.Config` and `com.getcapacitor.PluginCall` but only `Config` supports nested json for configuration.

So `Config#getString("android.appId")` works but `PluginCall#getString("android.appId")` does not.

We could build better structured and more readable plugin options if nesting is possible the same way for both classes.

So the access to `Config#getString` or `PluginCall#getString` should be calling the same method in the same super class.

Although I described it for Android it should be possible in IOS as well.

E.g. This is what I already do in a custom plugin.
```typescript
Plugins.OAuth2Client.authenticate({
      appId: environment.oauthAppId.google.web,
      authorizationBaseUrl: "https://accounts.google.com/o/oauth2/auth",
      accessTokenEndpoint: "https://www.googleapis.com/oauth2/v4/token",
      scope: "email profile",
      resourceUrl: "https://www.googleapis.com/userinfo/v2/me",
      web: {
        redirectUrl: environment.redirectUrl,
        windowOptions: this.OAUTH_WINDOW_OPTIONS
      },
      android: {
        appId: environment.oauthAppId.google.android,
        customScheme: this.OAUTH_ANDROID_SCHEME
      }
    }).then(resourceUrlResponse => {
      this.authenticateBackend("GOOGLE", resourceUrlResponse);
    }).catch(reason => {
      console.error("Google OAuth rejected", reason);
    });
```

**Comment by jcesarmobile** [comment]
yeah, right now it has the getObject and then on the object you can get it's own elements based on keys, but might be good to have nested strings as in Config

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Or if you are really interested and have the knowledge to implement this, you can send a PR.
