### ISSUE TITLE
Support file sharing in the core Share plugin

### ISSUE THREAD

**Issue by moberwasserlechner** [ionic-team/capacitor#846]
Sth like this:

```typescript
Plugins.Share.shareFile({
      data: base64EncodedFileData,
      cacheDirectory?: "" // where to cache the file, which should be shared
})

**Comment by jonathon-m** [comment]
Hopefully this will include support for Web Share API Level 2. Considering it's [available in Chrome 75](https://developers.google.com/web/updates/2019/05/web-share-files), it'll likely be standard soon.

**Comment by Bktechmasala** [comment]
capacitor share plugin fully worked prooved see video solved your problem https://youtu.be/5ulM4jedpB0

**Comment by jcesarmobile** [comment]
Turns out Share plugin was already able to share files by using the url param, I've fixed it for Android too. So will close this issue once it's merged.

**Comment by jonathon-m** [comment]
Thanks @jcesarmobile !
