### ISSUE TITLE
[suggestion]: Split up Capacitors's features (and remove some) to make it simpler and easier to understand/use

### ISSUE THREAD

**Issue by nklayman** [ionic-team/capacitor#849]
**The Problem:** Currently, getting started with capacitor is somewhat confusing. It targets 3 different build styles: PWA (injecting a service worker/app manifest), Electron (wrapping another tool), and android/iOS (placing website inside of webview of a native mobile). In addition to this, it also provides an unifying API for all platforms. While these are great features, I feel they could be organized better. I propose Capacitor is split up into two packages. One with the android/iOS hybrid app configuration, and one with unifying APIs that work on Web, Android, and iOS. As for Electron/PWA, these should be handled by the CLI Tooling layer (explained below) as they are out of Capacitor’s scope.

**Developer Tooling Layers:** To explain my idea, I will split the developer tooling environment into different layers, each with their own step in the build process:
CLI Tooling layer: The CLI tooling layer job should convert an app written in es6/with a framework to a compiled site, ready to be deployed on an http server. Example include Ionic CLI, Vue CLI, create-react-app, etc… It can also target Electron and PWA.
API layer: The API layer provides a unified API to the developer, in place of browser APIs. When a function is called, the API layer should detect if the app is functioning as a website (SPA, PWA, Electron), an Android app, or an iOS app. It then calls the proper native API. I propose that this functionality should be removed from Capacitor and moved into a separate package, we’ll call it Bridge for now. Bridge will replace Ionic Native by supporting cordova APIs/plugins as well. Bridge only needs to be installed if the developer is trying to access a web/native API. 
Hybrid layer: Capacitor should be a direct replacement to cordova, simply providing a way to run a website inside of a native app. It handles Cordova/native plugins, implementation of native api’s (made available to app developers through Bridge), but leaves building the final app to the Native Layer.
Native layer: The native layer handles building your final, native app. This is either xCode or Android studio. Capacitor should leave building/signing to these native tools, instead of trying to implement them itself (in my opinion).

**Reasoning:** I feel that this is a much better organization of Capacitor’s features. It reduces complication and makes it easier to understand, especially for new developers. It allows developers to use any build system and framework they want. Cross-platform apps will be a breeze as Bridge provides a single access point to APIs for every platform. As for PWA/Electron builds, they should be handled by the CLI Tooling layer. Bridge will use Web APIs when an app is running in one of these environments. As for a development server (with HMR), capacitor should have a NodeJS API which allows the CLI Tooling Layer to start an Android/iOS emulator, and have it load a provided URL.

**P.S.:** These are just my suggestions to making Capacitor easier to understand and use. Feel free to modify my idea (or completely ignore it) if you disagree with my opinions. These ideas come from me using Capacitor in my own project. Coming from Cordova, this is so much better, but it was a little confusing to get started. I can’t wait for a final 1.0 release alongside Ionic 4!

Looking forward to your response,
Noah

**Comment by mlynch** [comment]
Thanks for the thoughtful write up. I am not convinced, this sounds more complicated than what we have, but I've also been using Capacitor since the first line 😉

Will leave it open for others to comment on and see if it sparks any discussion.

**Comment by jcesarmobile** [comment]
There is a @capacitor/cli that is the few cli commands you can use.
Then there is @capacitor/core that has the common API and web implementation, sort of the bridge you mention.
And finally each platform is a separate package, @capacitor/ios, @capacitor/android and @capacitor/electron. They will be installed by the cli when adding a platform. Each one of those is to handle the native implementation of that platform, adding the not common bits of APIs and native code.

So I think what we have is pretty close to what you ask for, looks like a single package, but there are a few of them in a mono repo managed by lerna.

> This is either xCode or Android studio. Capacitor should leave building/signing to these native tools, instead of trying to implement them itself (in my opinion).

That's exactly how it works

> CLI Tooling layer: The CLI tooling layer job should convert an app written in es6/with a framework to a compiled site, ready to be deployed on an http server.

I don't think that should be the job of Capacitor, as it's framework agnostic, some people might prefer some tooling for the compilations, others might prefer another, so I think it's better if we let people decide what they want to use as long as they give us the compiled output and we only package that output compiled with them with the tools they choose.

**Comment by nklayman** [comment]
The CLI tooling layer is separate from capacitor. You can use any tooling/framework you want, as long as it compiles to a website, sorry if I didn't make this clear. While the code is organized quite well, the website/docs implies that capacitor:
- Can run your website as an Android/iOS app
- Can modify your webpack config and package your app for electron
- Can inject a service worker/app manifest to make your app a PWA
- Provides a unifying API for all these platforms

My biggest confusion is with Electron. How is capacitor supposed to modify the webpack configuration to make this work properly? It seems that this is just a WIP right now, so this hasn't been done yet. There are many special configuration changes that must be made to make webpack work with Electron. Because of this, it seems better to let the CLI tooling layer handles this, as well as PWA. Because capacitor has the unifying API and android/iOS support, it makes it unclear to what Capacitor is trying to do. The introduction on the site says
> Capacitor provides a consistent, web-focused set of API

But is also
> a spiritual successor to Apache Cordova and Adobe PhoneGap

To me, these seem like completely different things, and should be separate tools. Sorry I didn't transfer my idea well, and I hope this clarifies it better.

**Comment by jcesarmobile** [comment]
I can't find anything about webpack on the docs/website, other than a few sentences where it says you have to use webpack or rollup or something similar, or else use the bundledWebRuntime option that generates a capacitor.js file you can put in a script tag. Nothing related to electron.

**Comment by nklayman** [comment]
Even though capacitor does not require webpack to use with electron, I think it is safe to assume 90% of people will be using webpack.

**Comment by nklayman** [comment]
What I'm trying to say is 
A) PWA and Electron targets require modifications to the webpack config, making Cli tools such as vue-cli, create-react-app, etc... better suited to handling this.
B) The android/ios target and cross-platform API should be separate packages to reduce confusion.

**Comment by mlynch** [comment]
PWA/Electron shouldn't require any modifications to webpack. `@capacitor/core` is a library like any other JS library and it does the cross-platform switching for you

Android and iOS are already separate packages, they are just in one repo so we can more easily work on them.

Am I missing something?

**Comment by nklayman** [comment]
There is no point arguing, you guys made it, so it's your choice. I will close this issue to prevent further time wasted.

P.S. there are quite a few settings that must be changed for electron. First, some CLI tools load external scripts into the `index.html` with absolute (`/js/app.js`) paths, which don't work with Electron. Second, the webpack target should be set to `electron-renderer`. Webpack also mocks `__dirname` and `__filename`, which should be disabled. In addition to this, if you want native modules to work, externals must be set properly and the path to node_modules set on the dev server. As for PWA, there are some changes as well, see [here](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-plugin-pwa/index.js). The chainWebpack function modifies the base webpack config to work with pwa.
