### ISSUE TITLE
Got an email from Apple for Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#850]
I am not even using Push notification. With Cordova I was not getting this email. Looks like capacitor by defualt injects PushNotification framework or something.

 
--
 
`Dear Developer,We identified one or more issues with a recent delivery for your app, "******". Your delivery was successful, but you may wish to correct the following issues in your next delivery:Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.Best regards,The App Store Team`

**Comment by jcesarmobile** [comment]
Can you try removing this two methods from AppDelegate.swift and resubmit again?

```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidRegisterForRemoteNotificationsWithDeviceToken.name()), object: deviceToken)
}

func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.DidFailToRegisterForRemoteNotificationsWithError.name()), object: error)
}
```

**Comment by stripathix** [comment]
Doing it now.

**Comment by stripathix** [comment]
Did not get an email from apple but the new version of app is not visible in my test flight app. Let me try to build and push again.

**Comment by stripathix** [comment]
It works now after removing those functions

**Comment by jcesarmobile** [comment]
Yeah, I've tested and removing the code works.
But also added a configurable compilation condition so push can be disabled without removing the code (see linked PR).

**Comment by Jaspur** [comment]
But how to fix this when you do want push notifications to be enabled?

**Comment by danielsogl** [comment]
@jcesarmobile This is still an issue. Is it possible to adjust Capacitor to not include this two lines oob? I received multiple mails the last few days about that problem from our testers.

**Comment by jcesarmobile** [comment]
It’s documented how to avoid that message

 
https://capacitor.ionicframework.com/docs/apis/push-notifications

Or you can just remove the push methods from AppDelegate.swift

**Comment by danielsogl** [comment]
My problem with that implementation is that you had to have the error first and don't know why it happened until you read the entire capacitor docs or google the error and land in this issue here.
It should be the other way around. Comment those functions out by default and when users want to use push the read the dos and will enable them by themselves.

**Comment by adrynov** [comment]
I agree with Daniel. 

I got exactly the same message with bare bones Capacitor project and only searching GitHub issues, found this Closed issue.
