### ISSUE TITLE
Camera warning in Android release management

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#851]
I am not using camera plugin. But still I am getting this warning.
<img width="584" alt="screen shot 2018-10-04 at 9 03 52 pm" src="https://user-images.githubusercontent.com/8480351/46485297-09dcc100-c819-11e8-8a86-a41251ca3d5b.png">

```
New permissions added
Warning:

Users that have the APK with version code 1809141924 may need to accept the android.permission.CAMERA permission, which may result in them not upgrading to this version of the app.

Tip:

Ensure that the new permissions are necessary, and consider mentioning these permissions in the What's new in this release text.
```

**Comment by stripathix** [comment]
Looks like from manifest.xml I should remove camera permission.

**Comment by jcesarmobile** [comment]
Yeah, base project includes all the permissions required by core plugins, but if you don't use some plugins you can remove those permissions.

Also, camera permission is not even required by camera plugin, it's only required if you use `navigator.getUserMedia` in your app to get the camera feed.

We should do a better job about documenting the plugin permissions.

**Comment by jcesarmobile** [comment]
Created https://github.com/ionic-team/capacitor/issues/852 to track the docs issue, going to close this one
