### ISSUE TITLE
Android release apk is giving Webpage not available

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#857]
Debug apk works good on my device but on doing a release by using Android Studio to Generate Signed Apk. On running signed apk I am getting this screen. I found that below permission should be on top of manifest file under root tag but moving it to top also not helps.

`<uses-permission android:name="android.permission.INTERNET" />`

<img width="345" alt="screen shot 2018-10-05 at 1 00 05 pm" src="https://user-images.githubusercontent.com/8480351/46521936-cd53a880-c89e-11e8-8c71-042e7e873716.png">

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="***************">
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale"
            android:name="**********.MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/custom_url_scheme" />
            </intent-filter>

        </activity>

        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>
    </application>

    <!-- Permissions -->
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <!-- Geolocation API -->
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />
    <!-- Network API -->
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>

```

**Comment by stripathix** [comment]
On doing Clear Cache and Clear Storage in device under App Info > Sorage, it works now. Any idea why it was happening.

**Comment by stripathix** [comment]
Got the same issue on one more Android device.  Is this something related to a device which has app-debug.apk installed on their device and now trying to install app-release.apk? Although I have uninstalled app-debug.apk before installing app-release.apk.

**Comment by stripathix** [comment]
Hi @jcesarmobile, Could you please help me with this. 

Some users are getting this with app-release.apk also. This issue goes when on doing Clear Cache and Clear Storage in the device under App Info > Storage. 
But this is not something we can ask every user. Any idea what's going on.

**Comment by boozedog** [comment]
Can someone look at this? I'm having same problem

**Comment by stripathix** [comment]
@jcesarmobile  To reproduce.
1) Install app(version 0.0.1) that is built using Cordova on a device.
2) Install app(version 0.0.2) that is built using a Capacitor on the same device as an update. Then it shows webpage not available screen.

This goes away when I clear storage of app. But we can't ask every user to clear their storage.

**Comment by stripathix** [comment]
On debugging it shows:

<img width="1280" alt="screenshot 2019-01-01 at 4 54 21 pm" src="https://user-images.githubusercontent.com/8480351/50572481-9f232d80-0de7-11e9-9d15-a224a6f481e5.png">

Looks like there is some conflict in Cordova and capacitor. Maybe cordova app is running some background service what fails with capacitor.

**Comment by jcesarmobile** [comment]
Looks like the problem was an empty string stored on preferences making it fail to load files as explained on #1214, should be fixed on next release

**Comment by YajJackson** [comment]
@jcesarmobile why was this closed without a fix being submitted?

**Comment by jcesarmobile** [comment]
there was a fix submitted, but it's not linked here becase this issue and #1214 are duplicates and the fix (https://github.com/ionic-team/capacitor/pull/1256) was linked to that other issue.

**Comment by NaheelSalman** [comment]
I faced the same issue and I go through all the git issues listed here #857 , #1256
BUT
What works for me is :
I went to terminal and typed command
ionic cap build android --release
Then it OPENED the ANDROID STUDIO After generating and syncing bundles
and I make the file f9 button
then generated the signed bundles with ANDROID STUDIO.
Located the apk
and Installed it in mobile
cross checked with SIM NETWORK...
Wow It works :)
![WhatsApp Image 2023-07-05 at 13 11 12](https://github.com/ionic-team/capacitor/assets/39267623/0a2ab77e-8a13-488a-b490-0fbaf59ed3eb)

Happy Coding
