### ISSUE TITLE
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

### ISSUE THREAD

**Issue by contactjavas** [ionic-team/capacitor#863]
This is happened after i update to *AndroidStudio 3.2*
`Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;`

The solution is to use gradle `4.4` but ofcourse, we can not use it since minimum supported gradle version for Android studio 3.2 is 4.6. So, can't make it 4.4. Here is the error if i change back to 4.4:
`Gradle sync failed: Minimum supported Gradle version is 4.6. Current version is 4.4. If using the gradle wrapper, try editing the distributionUrl in E:\mobile\ionic\jasatukang\android\gradle\wrapper\gradle-wrapper.properties to gradle-4.6-all.zip`

For more information, please [look at this issue](https://github.com/novoda/bintray-release/issues/213)

**Comment by nikosdouvlis** [comment]
Just a temp fix, since I was facing the same issue.

Open your project in Android Studio -> File -> Project Structure -> Project (sidebar) and set
- `Gradle version`: 4.4
- `Android Plugin Version`: 3.1.1

**Comment by jcesarmobile** [comment]
This is related to `com.novoda.bintray-release`.

As that is only used for publishing capacitor-android, a better workaround would be to just remove all `com.novoda.bintray-release` related entries from capacitor-android's build.gradle as you won't be publishing.

So remove 
`classpath 'com.novoda:bintray-release:0.8.0'`
and
`apply plugin: 'com.novoda.bintray-release'`
and the whole publish block
```
publish {
    userOrg = 'ionic-team'
    repoName = 'capacitor'
    groupId = 'ionic-team'
    artifactId = 'capacitor-android'
    if (version != null) {
        publishVersion = System.getenv("BINTRAY_PKG_VERSION")
    } else {
        publishVersion = '0.0.0'
    }
    desc = 'Capacitor Android Runtime'
    website = 'https://github.com/ionic-team/capacitor'
}
```

Seems like novoda has already fixed it, but not released, so we will have to wait until they release.

Another option would be to get rid of novoda plugin and use bintray plugin as proposed on[ this PR ](https://github.com/ionic-team/capacitor/pull/752)

**Comment by jcesarmobile** [comment]
novoda released bintray-release 0.9 with the problem solved, you can manually change the 0.8.0 to 0.9 in the capacitor-android gradle file, or wait until this PR is merged and a new capacitor version is released https://github.com/ionic-team/capacitor/pull/970

**Comment by siordache94** [comment]
hi,
which one is the capacitor-android gradle file?
kinda new to the android studio ecosystem.
thank you

**Comment by emojot** [comment]
Yes com.novoda:bintray-release:0.8 -> com.novoda:bintray-release:0.9 will solve the problem

**Comment by theunreal** [comment]
> userOrg = 'ionic-team'

When doing npm install it will re-install this file, since it's located in @capacitor under node_modules ..

**Comment by theunreal** [comment]
> This is related to `com.novoda.bintray-release`.
> 
> As that is only used for publishing capacitor-android, a better workaround would be to just remove all `com.novoda.bintray-release` related entries from capacitor-android's build.gradle as you won't be publishing.
> 
> So remove
> `classpath 'com.novoda:bintray-release:0.8.0'`
> and
> `apply plugin: 'com.novoda.bintray-release'`
> and the whole publish block
> 
> ```
> publish {
>     userOrg = 'ionic-team'
>     repoName = 'capacitor'
>     groupId = 'ionic-team'
>     artifactId = 'capacitor-android'
>     if (version != null) {
>         publishVersion = System.getenv("BINTRAY_PKG_VERSION")
>     } else {
>         publishVersion = '0.0.0'
>     }
>     desc = 'Capacitor Android Runtime'
>     website = 'https://github.com/ionic-team/capacitor'
> }
> ```
> 
> Seems like novoda has already fixed it, but not released, so we will have to wait until they release.
> 
> Another option would be to get rid of novoda plugin and use bintray plugin as proposed on[ this PR ](https://github.com/ionic-team/capacitor/pull/752)

@jcesarmobile 
When doing npm install it will re-install this file, since it's located in @capacitor under node_modules..
Any permenant solution?
