### ISSUE TITLE
Capacitor with admob-free

### ISSUE THREAD

**Issue by DooDiddle** [ionic-team/capacitor#866]
After installing admob-free plugin, my app stops working. This is for android and ionic4, with capacitor installed. The error I see says:

index.js:177 Uncaught TypeError: Object(...) is not a function
    at index.js:177
    at Object../node_modules/@ionic-native/admob-free/index.js (index.js:186)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)
(anonymous) @ index.js:177
./node_modules/@ionic-native/admob-free/index.js @ index.js:186
__webpack_require__ @ bootstrap:81
./src/app/app.module.ts @ app.component.ts:11
__webpack_require__ @ bootstrap:81
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:81
0 @ main.ts:12
__webpack_require__ @ bootstrap:81
checkDeferredModules @ bootstrap:43
webpackJsonpCallback @ bootstrap:30
(anonymous) @ main.js:1
content_script.js:10 Uncaught Error: Unrecognized event name: undefined
    at receivePageEvent (content_script.js:10)
    at content_script.js:4

____

Here is how I installed admob:

npm install cordova-plugin-admob-free
npm install @ionic-native/admob-free
npx cap update

in package.json I see
"@ionic-native/admob-free": "^4.15.0",
"cordova-admob-sdk": "^0.20.0",

In app.module.ts
import { AdMobFree } from '@ionic-native/admob-free'; 
...
  providers: [
    StatusBar,
    SplashScreen,
    AdMobFree,

Can anyone help with this problem?

**Comment by DooDiddle** [comment]
Here is index.js line 177:

    AdMobFree = __decorate([
        Plugin({
            pluginName: 'AdMobFree',
            plugin: 'cordova-plugin-admob-free',
            pluginRef: 'admob',
            repo: 'https://github.com/ratson/cordova-plugin-admob-free',
            platforms: ['Android', 'iOS']
        })
    ], AdMobFree);
    return AdMobFree;

**Comment by jcesarmobile** [comment]
I can't reproduce and doesn't look like a Capacitor issue.

If you are using Ionic 4 I would recommend using "@ionic-native/admob-free": "5-beta.21" instead of "@ionic-native/admob-free": "^4.15.0"

Then you should change your imports from `import { AdMobFree } from '@ionic-native/admob-free';` to `import { AdMobFree } from '@ionic-native/admob-free/ngx';`

**Comment by DooDiddle** [comment]
ok. In order to install admob free I did:

$ ionic cordova plugin add cordova-plugin-admob-free
$ npm install @ionic-native/admob-free@beta

I am using capacitor, is it ok to have done the first command/should I have not done that?

**Comment by jcesarmobile** [comment]
yeah, that's ok

**Comment by DooDiddle** [comment]
This still doesn't work. I see a black container where the ad should display. How can I debug this?

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by tarunksingh** [comment]
you have to check that on an actual device. it will not be shown in emulator.
