### ISSUE TITLE
Time in iOS status bar jumps randomly

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/capacitor#883]
I’m running into a really weird issue with the iOS status bar. We’ve noticed it during development, but now I’m actually spending the time to look at it. Sometimes the status bar time will “jump” up a few pixels when using the app. I’ve noticed that it seems to be related to the time changing (or I guess the status bar updating). Here are some screenshots of it in a “normal” state, then a minute later back to the shifted state, then back to normal a minute later.

![ipad](https://user-images.githubusercontent.com/15218748/46883586-8296db00-ce20-11e8-8795-6abe2edc50b0.jpg)

I’ve experienced this on iPad and iPhone in both iOS 11 and 12. It also happens on iPhone X, although its less noticeable because there is a little more breathing room for the clock. I haven’t seen this in any other native iOS apps and it doesn’t appear to be related to ionic since this was just an empty index.html.

**Comment by jcesarmobile** [comment]
I've seen it on my device, but thought it was because of being using iOS 12 beta, will look into it.

**Comment by sbannigan** [comment]
Yeah I thought the same thing. Reproducible on iPhone X iOS 11 and 12. iPad iOS 12 only. Actually doesn't appear to be a problem with iPhone 8 and under. iOS 12 moved the clock on iPads to the left side similar to iPhone X, so thats the only thing that seems similar.

**Comment by sbannigan** [comment]
Confirmed that this does not happen with Cordova.
