### ISSUE TITLE
Ignore certain files when copying webDir?

### ISSUE THREAD

**Issue by uturnr** [ionic-team/capacitor#885]
My webDir contains normal and gzipped versions of certain files, example:

`app.c517e5203dffb5eb5471.js` and `app.c517e5203dffb5eb5471.js.gz`

I was getting `Error: Duplicate Resources` when building in Android Studio until I deleted the gz files.
Is it possible to configure capacitor to ignore certain file types when copying?

**Comment by jcesarmobile** [comment]
We do a full copy of the folder, adding some kind of "whitelist" of files is out of the scope of Capacitor, you should remove your build step that creates the .gz or add a new script to remove them and run it before the `npx cap copy` command so you copy a compatible www folder.

Closing as won't fix

This is a bug in Android Studio considering duplicate files based on the file name without extension, I think they should fix that, so you can report it to them too.
