### ISSUE TITLE
Does Capacitor work with phonegap-plugin-push?

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#887]
Hi.

Has anybody managed to get Capacitor to work with phonegap-plugin-push?

https://github.com/phonegap/phonegap-plugin-push

Since Capacitors own plugin for Push Notifications are missing essential parts (the ability to display the recieved Push Notification, showing a badge on the app icon etc.) I'm thinking about trying to use this third-party plugin. If that won't work I'm forced to temporarily switch to Cordova, which I really don't want to.

**Comment by jcesarmobile** [comment]
See this blog post
https://www.joshmorony.com/sending-push-notifications-with-the-phonegap-push-plugin-in-capacitor/

It requires some manual changes
