### ISSUE TITLE
Feature request: Share plugin support to open email client with To, Subject and Body

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#889]
I don't understand how to pre-populate **To** field of the email client.

```
content.shareInformation = function (title, text, url, dialogTitle) {
        if (content.isCapacitorMobileApp) {
            Share.share({
                title: title,
                text: text,
                url: url,
                dialogTitle: dialogTitle
            }).then(() => window.console.log("Successful share")).catch((error) => window.console.log("Error sharing", error));
        }
    };
```

**Comment by stripathix** [comment]
I have tried this but nothing happens.

`window.open("mailto:" + AppConst.errorReporting.mailto + "?subject=" + AppConst.jsonBlobReporting.subject + "&body=" + vm.reportdata, "_self");`

**Comment by jcesarmobile** [comment]
iOS? Android? both?
and with a regular anchor tag? or with window.location = 'mailto...'?

**Comment by stripathix** [comment]
iOS. 

Let me try anchor and window.location.
