### ISSUE TITLE
Sometime when error occurs related to capacitor then a modal opens.

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#892]
What is thi modal about how to disable it. I saw that it is described in native core capacitor.

<img width="624" alt="screen shot 2018-10-17 at 5 44 12 pm" src="https://user-images.githubusercontent.com/8480351/47085565-9bdec380-d234-11e8-9943-8e445f662a33.png">
<img width="240" alt="screen shot 2018-10-17 at 3 12 06 pm" src="https://user-images.githubusercontent.com/8480351/47085576-a436fe80-d234-11e8-8f69-705e8d398745.png">

**Comment by jcesarmobile** [comment]
It can't be disabled at the moment, but will only show while in debug mode. I think there was another issue to add a preference to disable it, but I can't find it, so I'll leave your issue open to do so.

**Comment by stripathix** [comment]
Ah, so it will not be shown when the app is in release mode ?

**Comment by jcesarmobile** [comment]
No, only in debug to help you catch issues
