### ISSUE TITLE
NodeJS 10 Support

### ISSUE THREAD

**Issue by cleversolutions** [ionic-team/capacitor#893]
Is there a problem with using node 10? 
Both `npx @capacitor/cli create` or `npx cap init` hang after entering the App name.

If I provide a name on the command line such as `npx cap init "My App"` I'm able to get a little further along before it again hangs (and locks up the console). 

Strangely enough I can run `npx @capacitor/cli create my-app "My App" "com.example.myapp"` then copy files to an existing ionic 4 project. 

$ node.exe --version
v10.12.0

**Comment by jcesarmobile** [comment]
Can't reproduce on my mac with node v10.12.0 (using nvm in case it's relevant)
What's your OS? npm version? npx version?

**Comment by Ionaru** [comment]
When running `npx cap init` in a Windows 10 Powershell, the CLI asks for an App Package ID and immediately exits. This happens before I can enter anything.

![npxcapinit](https://user-images.githubusercontent.com/3472373/47392657-80d0ef80-d71d-11e8-8e58-0cc29f4fed24.gif)
