### ISSUE TITLE
What is the proper way to handle Cordova plugins?

### ISSUE THREAD

**Issue by leshik** [ionic-team/capacitor#894]
Capacitor's documentation states that Cordova's `deviceready`event is not needed anymore. What is the proper way to handle plugins initialization? On Android, I get `plugins is not defined` error right after start (not the case for iOS though). The error is gone after hitting reload button in Chrome inspector.

**Comment by mlynch** [comment]
You still need that if you're using Cordova plugins. If you listen for the event are those plugins then working?

`deviceready` is only not needed for Capacitor plugins as they are all exported and ready before your page loads.
