### ISSUE TITLE
Android Geolocation plugin returns empty object if location is not available

### ISSUE THREAD

**Issue by uturnr** [ionic-team/capacitor#909]
On Android, if the user's location is not available, the plugin returns an empty object. For example, this would occur if the user has Location turned off in settings. Shouldn't it return a PositionError with code 2?

In `capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Geolocation.java`, in `sendLocation`, if `lastLocation` is null, `call.success();` is called:

```
private void sendLocation(PluginCall call) {
  String provider = getBestProviderForCall(call);
  Location lastLocation = getBestLocation(provider);
  if (lastLocation == null) {
    call.success();
  } else {
    call.success(getJSObjectForLocation(lastLocation));
  }
}
```

In JS,

```
Geolocation.getCurrentPosition().then(position => {
  console.log(position);
}).catch(err => {
  // PositionError handling
});
```

`position` is returned as an empty object.

**Comment by gesrt** [comment]
Same issue. I use cordova-plugin-geolocation instead. It works fine.
[https://ionicframework.com/docs/native/geolocation/](url)
