### ISSUE TITLE
Share plugin not working with PWA

### ISSUE THREAD

**Issue by NuruddinBadawi** [ionic-team/capacitor#910]
I have implemented the Share plugin but it's doesn't work in PWA as it's mention in capacitor share [documentation](https://capacitor.ionicframework.com/docs/apis/share), and as I know the PWA mean also a web browser correct me if wrong

and thanks.

**Comment by NuruddinBadawi** [comment]
Chrome last version '70.0.3538.67 '

**Comment by jcesarmobile** [comment]
And you you get any error?

**Comment by NuruddinBadawi** [comment]
yes `Uncaught (in promise) Web Share API not available`

**Comment by jcesarmobile** [comment]
Yeah, if the browser doesn't have navigator.share available it won't work on that browser and will show that error.

Looks like it's only available on Chrome for Android and Opera for Android for now, no desktop browser support it yet.

**Comment by Bktechmasala** [comment]
capacitor share plugin fully worked prooved see video solved your problem https://youtu.be/5ulM4jedpB0
