### ISSUE TITLE
error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#914]
'/Users/oliverandersen/Documents/Ionic Projects/Skwap/node_modules/@capacitor/cli/assets/capacitor-cordova-ios-plugins/sources/CordovaPluginFacebook4/src/ios/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKConstants.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This error has come out of no where and is stopping me being able to build my capacitor Io nic project.

I have done as it asks and disabled bitcode - no difference

Ive uninstalled npm modules, and reinstalled them, and done the same with capacitor

Any ideas?

**Comment by jcesarmobile** [comment]
Which Facebook plugin are you using?

**Comment by oliverandersencox** [comment]
"cordova-plugin-facebook4": "^3.1.0",

**Comment by jcesarmobile** [comment]
They have updated the Facebook frameworks on latest release. Try downgrading to previous version for now. I’ll take a look

**Comment by oliverandersencox** [comment]
@jcesarmobile I downgraded the package 3-4 times and each time got the same response. 

Appreciate your help - its such a pain in the arse!

**Comment by oliverandersencox** [comment]
I can no confirm that downgrading did work eventually - after building then running npx cap sync fixed this - Thanks @jcesarmobile

**Comment by jcesarmobile** [comment]
Ah, yeah, you have to run update or sync after npm install.

Good to know that downgrading fixes the proble, but will try to fix the problem with latest version

**Comment by jcesarmobile** [comment]
Looks like latest facebook SDK is having some troubles with Cordova too, so I think it's better if you keep using the downgraded version.

I can't find a way of disabling bitcode on our end, so you'll have to do it by adding something like this to the `projectName/ios/App/Podfile`, at the end of the file. That will disable bitcode for all targets once you run `npx cap update` or `npx cap sync`
```
# BITCODE bug fix
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```
