### ISSUE TITLE
Capacitor iOS is incompatible with Swift 4.2

### ISSUE THREAD

**Issue by JensRavens** [ionic-team/capacitor#920]
If you currently create a project with Capacitor with a current Xcode from the Mac AppStore (10.0), the project by default is set to Swift 4.2. Next up Cocoapods will install the dependencies and set the Pod-Target to the same Swift version. As Capacitor does not define a Swift version in its podspec file it will inherit the Swift version from the project which leads to build errors due to unknown constants (that were renamed in Swift 4.2). 

There would be two solutions to fix this problem:

- rewrite Capacitor iOS to use Swift 4.2 (which should be the long term plan)
- specify a Swift version in the Podspec (just add a `s.swift_version = '4.0'` to the podspec file)

I currently use a fork that has the altered podspec file. If you're interested I can submit it as a pull request.

**Comment by jcesarmobile** [comment]
What's your CocoaPods version?
We have the Swift version defined in https://github.com/ionic-team/capacitor/blob/master/.swift-version, which works fine, at least with CocoaPods 1.4.0 and older. 

Looks like `s.swift_version = '4.0'` was added in CocoaPods 1.4.0, so would be good to have it in our .podspec files, so kudos if you send a PR.

Updating to 4.2 is planned, but not sure when as it will not work on Xcode 9

**Comment by JensRavens** [comment]
Yep, that's what I already thought. I'm running on cocoapods 1.5. I'll do a PR right away.

**Comment by jcesarmobile** [comment]
Merged, thanks!
