### ISSUE TITLE
LocalNotifications example

### ISSUE THREAD

**Issue by bsaf** [ionic-team/capacitor#925]
Hi 👋🏼I'm trying to get a Local Notification displaying on iOS.

This is my example code (tried to follow the [definitions](https://github.com/ionic-team/capacitor/blob/master/core/src/core-plugin-definitions.ts) file):

```js
    LocalNotifications.schedule({
      notifications: [
        {
          title: "Title",
          body: "Body",
          id: 1234,
          schedule: { at: Date.now() + 1000 * 5 },
          sound: null,
          attachments: null,
          actionTypeId: "Nothing",
          extra: null
        }
      ]
    });
```

When I run this on a device, I first get the modal asking for permissions to show notifications but then a crash at this point in Xcode when running:

<img width="1082" alt="error" src="https://user-images.githubusercontent.com/35183/47486122-87538a00-d837-11e8-87e1-13de9e3438d3.png">

Here's the Xcode log from the `print(notification)` line:

```swift
<UNNotification: 0x280bdace0; date: 2018-10-25 08:27:09 +0000, request: <UNNotificationRequest: 0x280537e70; identifier: 1234, content: <UNNotificationContent: 0x283eb3480; title: Title, subtitle: (null), body: Body, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: Nothing, launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null),, trigger: (null)>>
```

I think my `LocalNotifications.schedule` call might be incorrect? Happy to submit a doc PR once I've understood the problem.

**Comment by jcesarmobile** [comment]
`at` should be a Date, but you don't pass a Date as you add the 1000 * 5, it works if you do it like this `{ at: new Date(Date.now() + 1000 * 5 )}`:

Full example:
```
LocalNotifications.schedule({
      notifications: [
        {
          title: "Title",
          body: "Body",
          id: 1234,
          schedule: { at: new Date(Date.now() + 1000 * 5 )},
          sound: null,
          attachments: null,
          actionTypeId: "Nothing",
          extra: null
        }
      ]
    });
```

**Comment by bsaf** [comment]
Thank you!
