### ISSUE TITLE
Bug: Push Notifications icon is missing on Android

### ISSUE THREAD

**Issue by leshik** [ionic-team/capacitor#926]
Android shows just round circle in place of the notification icon. Related to #759 and #884.

**Comment by jcesarmobile** [comment]
If no push icon is specified it will use the app icon. But push icon should be white pixels on a transparent backdrop

As the default capacitor icon is not made from white pixels and don't have transparency you'll see a white circle or square (depends on the Android version).
We won't provide a default push icon, users should generate it themselves for their apps, and then add this to their `AndroidManifest.xml` (with the appropriate name)

`<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/push_icon_name" />`

Keeping it open to document it on the push notification docs.
