### ISSUE TITLE
[feat] add an optional splash screen spinner

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/capacitor#928]
[X] I would like to suggest a feature

**Description**

Cordova provide the ability optionally to display a spinner over the splash screen.

Reference: https://github.com/apache/cordova-plugin-splashscreen

      <preference name="ShowSplashScreenSpinner" value="false"/>

I personally found this option interesting because I kind of feel that without spinner, even if the app took only 2 seconds too boot, as a user you kind of ask yourself if something is happening or not

If I'm not mistaken, maybe I missed it in the documentation, but this isn't possible yet in Capacitor therefore I allow myself to just suggest this feature

p.s.: If that would not be possible, already answered or if it's a duplicate etc. plz accept my apologies in advance

**Comment by ptitjes** [comment]
Hi @peterpeterparker. You may be interested in animating your splash screen using https://github.com/ionic-team/capacitor/pull/790 (android only). See [an example of what it brings](http://ptitjes.free.fr/cabasvert/app-startup.mp4), or [a simpler version](http://ptitjes.free.fr/cabasvert/animated-splash-screen.mp4).

Some info on AnimatedVectorDrawable:
- https://developer.android.com/reference/android/graphics/drawable/AnimatedVectorDrawable

How I do it:
- https://github.com/cabasvert/cabasvert/blob/master/packages/client/capacitor.config.json#L8
- https://github.com/cabasvert/cabasvert/tree/master/packages/client/android/app/src/main/res

Ask me if you need more info.

**Comment by peterpeterparker** [comment]
@ptitjes thx for the links and details, definitely interesting and I might use it at some point, really cool 👍

that being said, I think the idea of a spinner is still kind of not too bad. It would be good to have a solution for both iOS and android and a spinner could be applied on full size splash image

**Comment by jcesarmobile** [comment]
added spinner feature on https://github.com/ionic-team/capacitor/pull/1653
