### ISSUE TITLE
ios build problem for CordovaPluginFirebase

### ISSUE THREAD

**Issue by DaveRicho** [ionic-team/capacitor#934]
When trying to build the app in xcode 10, I get the following build error:

```
/node_modules/@capacitor/cli/assets/capacitor-cordova-ios-plugins/sources/CordovaPluginFirebase/src/ios/Firebase/RemoteConfig/FirebaseABTesting.framework/Headers/FIRExperimentController.h:3:9: error: 
'developers/mobile/abt/proto/ExperimentPayload.pbobjc.h' file not found
#import "developers/mobile/abt/proto/ExperimentPayload.pbobjc.h"
        ^
<unknown>:0: error: could not build Objective-C module 'CordovaPlugins'
```
This is using "@capacitor/cli": "^1.0.0-beta.8".

I have added capacitor to an existing ionic 3 project. (apologies if that the problem right there).

**Comment by nikosdouvlis** [comment]
Same problem, haven't found a solution yet

**Comment by maedewiza** [comment]
Any ways to fix it?

**Comment by arneldomingo** [comment]
Is there a fix?

**Comment by arneldomingo** [comment]
Is there a fix?

**Comment by rrath-edr** [comment]
I am facing the same with. Why this is closed.
I have migrated and ionic 4 cordova project to capacitor and getting the same error.

**Comment by iepicfellow** [comment]
Facing the same issue

**Comment by marutifh** [comment]
I am facing same issue when used with cordova camera plugin. Did anyone found any solution for the same?

**Comment by iepicfellow** [comment]
Hmm... I couldn't solve the issue so I reverted back to cordova and it for my use it works fine.

**Comment by DaveRicho** [comment]
I ended up starting a New Ionic v4 project with capacitor v2 and manually ported across my v3 code.

**Comment by marutifh** [comment]
Okay sure, I started new project with ionic 5 and just added this cordova camera plugin in Capacitor, And I am stuck here with this.

**Comment by iepicfellow** [comment]
maybe try adding it with `ionic cordova plugin add cordova-plugin-camera` and `npm install @ionic-native/camera`, then `cordova platform add ios` and `ionic cordova build ios`. This uses cordova not capacitor to build which should not cause much of a difference.
