### ISSUE TITLE
Capacitor Dev Tools alert in production

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#935]
I run: npm run build --prod 

When the app is on the phone and i shake it, it still pops up with the reload alert from capacitor.

How can I stop this from happening?

**Comment by jcesarmobile** [comment]
yeah, --prod is an angular/ionic/framework thing on how you build the www, it has nothing to do with Capacitor's debug/release mode. That appears on Capacitor's debug mode.

I'm keeping the issue open to allow to configure the menu from a configuration option, and also to fix the problem when you hit reload on an angular app, that turns the screen white.

**Comment by jcesarmobile** [comment]
Closing as dev menu is going away https://github.com/ionic-team/capacitor/pull/1458
