### ISSUE TITLE
Capacitor Dev Menu

### ISSUE THREAD

**Issue by drtomato** [ionic-team/capacitor#936]
I am experimenting with Ionic 4 and Capacitor on my iPhone. If I shake the phone a small menu (‘Capacitor Dev Menu’) with the options Reload and Cancel is displayed. No matter what I select, the screen then goes completely blank and I have to kill the app and restart it. What is this menu for, what it is supposed to do and can I turn it off?  I don’t want my app to go dead every time I happen to shake my phone.

**Comment by jcesarmobile** [comment]
Duplicate of #935
