### ISSUE TITLE
Edit image activity intent returning with null data

### ISSUE THREAD

**Issue by ydorea** [ionic-team/capacitor#937]
I'm making an app that uses the Camera plugin from Capacitor. When I set height and width to the same value, I get stretched images, so I figured the user might want to crop them so they don't stretch too much.

Problem is, the app crashes every time I edit a picture. Using Android Studio debugger I found the data returned by the edit activity is something like `Intent { flg=0x1 }`, which turns to make the `data.getData()` null, and crashes the app (that doesn't check if the uri is null).

I melted my brain off trying to figure out what is the issue, but I couldn't. So for now I'll remove the editing and leave the images streched because I have to finish this project. But I want to do this eventually, so, any guesses?

**Comment by jcesarmobile** [comment]
Which app are you using to edit?

**Comment by ydorea** [comment]
I think it's a native android app. The code in Capacitor's plugin is `Intent editIntent = new Intent(Intent.ACTION_EDIT);` and then `editIntent.setDataAndType(origPhotoUri, "image/*");`

**Comment by jcesarmobile** [comment]
Yeah, the intent open a native app, but it will be different per device, that’s why I’m asking which one

**Comment by ydorea** [comment]
Jesus, it appears this app wasn't actually a native app, it's an app called QuickPic that I had installed some time ago. I thought it was native because there was no logo... Maybe that's why?
