### ISSUE TITLE
iOS: "server.port" config property not retrieved (always empty)

### ISSUE THREAD

**Issue by moberwasserlechner** [ionic-team/capacitor#938]
In my capacitor.config.json I have

```
{
  "server": {
    "port": 1111
  }
}
```

The Bridge tries to get the property. But it is always 0 and therefore a random port in the range of 3000 to 9000 is used.

I have not tried it in production yet but I think I run into CORS issues as soon as I do because my production backend does not allow all origins.

**Comment by jcesarmobile** [comment]
Port should be a string, not int.
On Android it works because the Android JSON class does the type coercion, but on Swift as we do it, we don't do any coercion.
