### ISSUE TITLE
iOS: Disable 3D Touch (allowsLinkPreview)

### ISSUE THREAD

**Issue by kalicki** [ionic-team/capacitor#939]
Hey

It's an incredible improvement, if we turn off the 3D Touch on the view. Now any button or something with link or redirect to page if you press opens via `localhost`. Cordova has solved this.

Ref:
https://developer.apple.com/documentation/webkit/wkwebview/1415000-allowslinkpreview

https://github.com/ionic-team/cordova-plugin-wkwebview-engine/blob/a2049be5f9d24ac27bf9aaed260f494f11ca5b23/src/ios/CDVWKWebViewEngine.m#L130

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Note that since plugins have access to the webview, they can easily change this kind of property values

**Comment by jcesarmobile** [comment]
It's been implemented, removing the feature request label
