### ISSUE TITLE
LocalNotification crashes on iOS

### ISSUE THREAD

**Issue by drtomato** [ionic-team/capacitor#941]
I am not sure whether I am doing something wrong or whether I have found a bug. Anyway, here it goes: I am trying out the API for Local Notifications with the following code:
```
   async scheduleNow() {
      this.notifs = await Plugins.LocalNotifications.schedule({
         notifications: [{
            title: 'Test',
            body: 'Swipe now to learn more',
            id: Math.floor(Math.random() * 10),
            actionTypeId: 'OPEN_PRODUCT',
            extra: {
               productId: 'PRODUCT-1'
            }
         }]
      })
   }
```
When invoking this method from a buttom, this causes a crash in ```CAPUNUserNotificationCenterDelegate```, line 47:

![screenshot 2018-10-30 at 00 32 37](https://user-images.githubusercontent.com/6412564/47686454-83c75680-dbdb-11e8-9856-7b342b477a20.png)

My package.json:
```
   "dependencies": {
      "@angular/common": "6.1.10",
      "@angular/core": "6.1.10",
      "@angular/forms": "6.1.10",
      "@angular/http": "6.1.10",
      "@angular/platform-browser": "6.1.10",
      "@angular/platform-browser-dynamic": "6.1.10",
      "@angular/router": "6.1.10",
      "@capacitor/cli": "^1.0.0-beta.3",
      "@capacitor/core": "^1.0.0-beta.3",
      "@capacitor/ios": "^1.0.0-beta.8",
      "@ionic-native/core": "5.0.0-beta.14",
      "@ionic-native/splash-screen": "5.0.0-beta.14",
      "@ionic-native/status-bar": "5.0.0-beta.14",
      "@ionic/angular": "4.0.0-beta.7",
      "@ionic/ng-toolkit": "1.1.0",
      "@ionic/pro": "2.0.3",
      "@ionic/schematics-angular": "1.0.7",
      "@ngx-translate/core": "^10.0.2",
      "@ngx-translate/http-loader": "^3.0.1",
      "@types/leaflet": "^1.2.9",
      "@types/leaflet.markercluster": "^1.0.3",
      "cordova-background-geolocation-lt": "^2.13.2",
      "cordova-plugin-background-fetch": "^5.4.1",
      "cordova-plugin-cocoalumberjack": "0.0.4",
      "core-js": "^2.5.3",
      "ionic-logging-service": "^5.1.0",
      "leaflet": "^1.3.3",
      "leaflet-pulse-icon": "^0.1.0",
      "leaflet.markercluster": "^1.3.0",
      "rxjs": "6.3.3",
      "zone.js": "^0.8.26"
   },
   "devDependencies": {
      "@angular-devkit/architect": "0.9.0-beta.3",
      "@angular-devkit/build-angular": "0.9.0-beta.3",
      "@angular-devkit/core": "0.9.0-beta.3",
      "@angular-devkit/schematics": "0.9.0-beta.3",
      "@angular/cli": "6.2.5",
      "@angular/compiler": "6.1.10",
      "@angular/compiler-cli": "6.1.10",
      "@angular/language-service": "6.1.10",
      "@types/jasmine": "~2.8.6",
      "@types/jasminewd2": "~2.0.3",
      "@types/node": "~10.11.7",
      "codelyzer": "~4.5.0",
      "jasmine-core": "~3.2.1",
      "jasmine-spec-reporter": "~4.2.1",
      "karma": "~3.0.0",
      "karma-chrome-launcher": "~2.2.0",
      "karma-coverage-istanbul-reporter": "~2.0.0",
      "karma-jasmine": "~1.1.1",
      "karma-jasmine-html-reporter": "^1.3.1",
      "protractor": "~5.4.0",
      "ts-node": "~7.0.0",
      "tslint": "~5.11.0",
      "typescript": "^2.9.2"
   },
   "config": {
      "ionic_source_map": "source-map"
   }
```

**Comment by peterpeterparker** [comment]
Just tested, the following works with me with Xcode 12 and simulator. Maybe something with the action type?

```
     async schedule(at: Date) {
        if (!this.platform.is('hybrid')) {
            return;
        }

        const notifications: LocalNotification[] = [];

        notifications.push({
            title: 'Task is over',
            body: 'This is the content',
            id: 0,
            schedule: {
                at: at,
                repeats: false
            }
        });

        await LocalNotifications.schedule({notifications: notifications});
    }
```

**Comment by drtomato** [comment]
Thanks for testing, I will try your code! But given that my app crashes the way it does, my problem must be something else than a simple data error - it seems that an expected property is missing from the data object which causes the crash. Do you think you could post your package.json here to let me check and verify that I am not using incompatible versions or something like that? Thanks!

**Comment by peterpeterparker** [comment]
@drtomato here you go

```
"dependencies": {
    "@angular/common": "~6.1.1",
    "@angular/core": "~6.1.1",
    "@angular/fire": "^5.1.0",
    "@angular/forms": "~6.1.1",
    "@angular/http": "~6.1.1",
    "@angular/platform-browser": "~6.1.1",
    "@angular/platform-browser-dynamic": "~6.1.1",
    "@angular/router": "~6.1.1",
    "@capacitor/android": "^1.0.0-beta.8",
    "@capacitor/cli": "^1.0.0-beta.8",
    "@capacitor/core": "^1.0.0-beta.8",
    "@capacitor/ios": "^1.0.0-beta.8",
    "@ionic/angular": "4.0.0-beta.13",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "core-js": "^2.5.3",
    "d3-array": "^1.2.4",
    "d3-axis": "^1.0.12",
    "d3-scale": "^2.1.2",
    "d3-selection": "^1.3.2",
    "d3-shape": "^1.2.2",
    "date-fns": "^1.29.0",
    "firebase": "^5.5.6",
    "hammerjs": "^2.0.8",
    "rxjs": "6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.8.5",
    "@angular-devkit/build-angular": "~0.8.5",
    "@angular-devkit/core": "~0.8.5",
    "@angular-devkit/schematics": "~0.8.5",
    "@angular/cli": "~6.2.5",
    "@angular/compiler": "~6.1.1",
    "@angular/compiler-cli": "~6.1.1",
    "@angular/language-service": "~6.1.1",
    "@ionic/angular-toolkit": "^1.0.0",
    "@types/d3-array": "^1.2.4",
    "@types/d3-axis": "^1.0.11",
    "@types/d3-scale": "^2.0.2",
    "@types/d3-selection": "^1.3.2",
    "@types/d3-shape": "^1.2.4",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.11.3",
    "@types/swiper": "^4.2.2",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.3.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  },
```

**Comment by drtomato** [comment]
Thanks @peterpeterparker ! I'll try it out and report back within a day or two.

**Comment by drtomato** [comment]
Sorry, I just can't get this to work. To eliminate all other potential problems I created an Ionic/Capacitor project from scratch:
```
> ionic start Test1 blank --type=angular
> cd ./Test1
> npm install
> npm run build
> npm install --save @capacitor/core @capacitor/cli
> npx cap init Test1 se.xeq.test1
> npx cap add ios
> npx cap sync
> cd ios/App
> pod update
```
Then I modified ```home.page.html```and ```home.page.ts```to trigger a local notification, built the project without errors (but with quite a lot of warnings) in Xcode 10.1 (10B61) and launched the simulator.  When clicking the button "Trigger event", I still get:

```Thread1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP,subcode=0x0)```
on line 47 of ```CAPUNUserNotificationCenterDelegate.swift```

This is the last part of the log:
```
SplashScreen.hideSplash: SplashScreen was automatically hidden after default timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout). Read more at https://capacitor.ionicframework.com/docs/apis/splash-screen/#hiding-the-splash-screen
2018-11-02 21:36:04.566249+0100 App[30676:22624606] [Accessibility] WKContentView[@] set up: @ pid: @ MACH_PORT -687536640
⚡️  To Native ->  LocalNotifications schedule 29308391
⚡️  TO JS {"ids":["0"]}
<UNNotification: 0x600002455160; date: 2018-11-02 20:36:04 +0000, request: <UNNotificationRequest: 0x600002aaaca0; identifier: 0, content: <UNNotificationContent: 0x60000112e880; title: Task is over, subtitle: (null), body: This is the content, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null),, trigger: (null)>>
```
I am completely stuck and would appreciate any help I can get. I put the project on GitHub so if you want you can just clone it from here:
```
https://github.com/drtomato/Test1.git
```
Thanks!

**Comment by drtomato** [comment]
@peterpeterparker

The schedule thingy did it, thanks a lot! I had found an example that I followed that didn't require the use of schedule (no schedule = same as 'show now') but I may have found old code or something relating to some other local notifcations plugin - there seems to be a lot of them around which is all very confusing to a newbie in this environment, like me :) 

I also just saw that there have now been examples similar to yours posted as a response to #925 so that is all very good.

Since I have you on the line, so to speak, and you are a contributor to the Capacitor project, I hope you don't mind if I ask some additional questions? 

1. The Capacitor LocalNotifications plugin is only supported on iOS and Android so what is actually the point with it, when there is already a Cordova plugin available (that I can use with Capacitor, I have tried) that essentially does the same thing?
2. As it is natural to use badges in conjunction with notifications, is there a way to use these from Capacitor (I have not seen anything about that in the docs)? I have seen in UNNNotificationContent on iOS that there seems to be some provisioning for badges but I don't think there is any way of setting it from Capacitor.

Any light you can shed on this would be much appreciated, many thanks in advance!

**Comment by peterpeterparker** [comment]
@drtomato cool to hear it worked out. now that your issue is solved I would suggest to close this issue since there isn't a problem anymore

about your question, well I didn't contribute to this project since a while and I'm only back since a couple of days, so I could not really answer your question, I could only give my thought

1. I would say, it is just way more handy to have it included in the library too since LocalNotifications is something many people may use aka if all user of Capacitor which are looking to use local notifications, to specially just for that case, don't have to install an extra plugin it's kind of cool

2. No idea but at some point I guess I'll have the same question, maybe you could open a separate support question in this tracker about it or bump the question on the Slack channel?

Best

**Comment by drtomato** [comment]
@peterpeterparker thanks for all your help and comments regarding this issue, I will close the ticket.

**Comment by peterpeterparker** [comment]
@drtomato coolio, my pleasure
