### ISSUE TITLE
Values from strings.xml not found in capacitor AndroidManifest.xml

### ISSUE THREAD

**Issue by nstokoe** [ionic-team/capacitor#943]
I'm trying to get my project to compile with the [jeduan/cordova-plugin-facebook4](https://github.com/jeduan/cordova-plugin-facebook4) cordova plugin. I have included my facebook id and app name in the app/src/main/res/values/strings.xml like so:

```
<?xml version="1.0" encoding="UTF-8"?>
<resources>
    <string name="app_name">UI</string>
    <string name="title_activity_main">UI</string>
    <string name="package_name">[redacted]</string>
    <string name="fileprovider_authority">[redacted]</string>
    <string name="custom_url_scheme">[redacted]</string>
    <string name="fb_app_id">[redacted]</string>
    <string name="fb_app_name">UI</string>
</resources>
```

I have also added the necessary facebook values to app/src/main/AndroidManifest.xml like so:
```
...
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/fb_app_id"/>
<meta-data android:name="com.facebook.sdk.ApplicationName" android:value="@string/fb_app_name" />
<activity android:name="com.facebook.FacebookActivity"
          android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
          android:label="@string/fb_app_name" />
...
```

Despite this fact I am getting this error upon compilation:

```
dManifest.xml:13: AAPT: error: resource string/fb_app_id (aka capacitor.android.plugins:string/fb_app_id) not found.
    
/Users/nstokoe/code/fullmeasure/prototype/ui/node_modules/@capacitor/cli/assets/capacitor-android-plugins/build/intermediates/manifests/aapt/release/AndroidManifest.xml:16: AAPT: error: resource string/fb_app_name (aka capacitor.android.plugins:string/fb_app_name) not found.
    
/Users/nstokoe/code/fullmeasure/prototype/ui/node_modules/@capacitor/cli/assets/capacitor-android-plugins/build/intermediates/manifests/aapt/release/AndroidManifest.xml:20: AAPT: error: resource string/fb_app_name (aka capacitor.android.plugins:string/fb_app_name) not found.
```

The file it is complaining about looks like this in my node_modules:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:amazon="http://schemas.amazon.com/apk/res/android"
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="capacitor.android.plugins"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="27" />

    <application>
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/fb_app_id" />
        <meta-data
            android:name="com.facebook.sdk.ApplicationName"
            android:value="@string/fb_app_name" />

        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/fb_app_name" />
    </application>

</manifest>
```

Is there something I am missing to make the values defined in strings.xml available to the manifest files in the capacitor module?

**Comment by djabif** [comment]
hey @nstokoe, I'm facing this issue. Did you find the solution?

**Comment by nstokoe** [comment]
We got it to work but the process I recall was very cumbersome and prone to issues. It involved modifying multiple config files inside the node_modules directory for the plugin which meant any time we updated our packages it had to be repeated. We ended up giving up on that approach because it was too brittle and opted for making our own capacitor plugin for facebook auth.

**Comment by djabif** [comment]
Yep, I think I will end up doing the same :(

**Comment by matheo** [comment]
For the record, adding the missing `fb_app_id` and `fb_app_name` to `app/src/main/res/values/strings.xml` worked for me, but it's concerning to not have them added automatically from the plugin config.

**Comment by masimplo** [comment]
I am currently facing the same issue when trying to build for android using gradle. I am using version 4.2.1 of the facebook plugin.

**Comment by jcesarmobile** [comment]
I can't reproduce on latest Capacitor using latest plugin.

Steps I've followed:

- npm install cordova-plugin-facebook4
- npx cap sync android
- add `<string name="fb_app_id">random_id</string>` and `<string name="fb_app_name">random_name</string>` in the app strings.xml
- click the sync gradle button on Android Studio
- run the app

You don't need to modify your AndroidManifest.xml, that is added in the capacitor-cordova-android-plugins' AndroidManifest.xml and Android Studio is smart enough to merge all the modules manifests into one.

**Comment by ThonyFD** [comment]
For someone facing this issue building release versions:

change **assemblerelease** for **app:assemblerelease**

Read this for more info: [https://stackoverflow.com/questions/60990805/difference-between-appassemblerelease-and-assemblerelease](url)
