### ISSUE TITLE
Page not aligned to screen

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#945]
Another very odd issue - out of the blue. There is a small space under the screen of around 30px pushing the entire app up:

![img_1851](https://user-images.githubusercontent.com/6772168/47752941-d9f4d200-dc8d-11e8-85ff-ae6580d77c3a.jpeg)
- Click the image to see the whitespace under the app

When I inspect it in safari, there are no added margins or anything to suggest the reason for this happeneing

**Comment by jcesarmobile** [comment]
I can't reproduce, can you provide a sample app?
