### ISSUE TITLE
Need better documentation for using custom plugins on Android

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/capacitor#952]
After digging into the Android custom plugin docs, I finally realized that I needed to add each custom capacitor plugin to `MainActivity.java`. If I was writing a custom plugin, I might not have missed this step, but when implementing a plugin into a project, I was not aware that an extra step was required for Android as opposed to iOS where all that is required is running the update command.

Ideally this step could be automated with the update command, but at least having clearer documentation for using custom plugins or maybe more descriptive error handling for this situation would be helpful.

**Comment by jcesarmobile** [comment]
Android plugins have `NativePlugin` annotation, but I don't know how to get all classes with that annotation to do the automatic registration.
@moberwasserlechner, if you do, a PR would be appreciated.
But we should also measure if there are performance implications on the startup time when using reflection as I've always heard it's slow.

**Comment by moberwasserlechner** [comment]
@jcesarmobile yeah sure. I will try to do some capacitor development next week. (There are also a few I other task I like to look at)

I guess this should be done before you release 1.0.0.

**Comment by jcesarmobile** [comment]
Closing as it's now documented at https://capacitor.ionicframework.com/docs/plugins/android#export-to-capacitor
