### ISSUE TITLE
Globalization Plugin not working in browser

### ISSUE THREAD

**Issue by federicotortora** [ionic-team/capacitor#953]
"npx cap serve" throws 
"Uncaught TypeError: Object(...) is not a function "
when Globalization plugin is used because it's looking for Cordova() object.

**Comment by jcesarmobile** [comment]
Cordova support is for iOS an android only for now, there is another issue to add browser support

**Comment by federicotortora** [comment]
sorry: 
https://capacitor.ionicframework.com/docs/basics/cordova
Capacitor comes with full Cordova plugin compatibility, so using existing Cordova plugins in Capacitor is easy.

So what you suggest? I have to open an issue where?

**Comment by jcesarmobile** [comment]
No, the issue is already open, you can add the +1 reaction (not as a comment) here https://github.com/ionic-team/capacitor/issues/769
