### ISSUE TITLE
Google Plus Login cordova error

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#961]
#When trying to get Google login working with capacitor I am getting this error:

`GooglePlus* gp = (GooglePlus*) [self.viewController pluginObjects][@"GooglePlus"];
No visible @interface for 'CDVViewController' declares the selector 'pluginObjects'
`

Google plus login works great with firebase within the browser, however after installing cordova google plus package, the app becomes unbuildable with the error above.

Seems to be capacitor causing the issue.

I have added the instructed info to the info.plist - any ideas?

**Comment by jcesarmobile** [comment]
I've send a PR with a "fix".
Note that it's quoted because it only allows the project to build, but wherever a plugin uses it, it won't work.
Gladly `cordova-plugin-googleplus` removed that code in version 6.0.0
