### ISSUE TITLE
NPM Scoped Prefix being Appended to PodName, Then Capacitor can't find PodSpec

### ISSUE THREAD

**Issue by T-Knott-Mesh** [ionic-team/capacitor#963]
**This is the Terminal Output where it is looking for a podspec called  "MeshIntelligenceCapacitorFirebaseAuthPlugin" but the Podspec s.name is "CapacitorFirebaseAuthPlugin"**

===================================================================
Podspec File for Plugin published on npm @mesh-intelligence/capacitor firebase-auth-plugin 

File Name: CapacitorFirebaseAuthPlugin.podspec

`  Pod::Spec.new do |s|
    s.name = 'CapacitorFirebaseAuthPlugin'
    s.version = '0.0.1'
    s.summary = 'This is a plugin to allow native SDK usage for authentication with firebase on iOS, Android, and Web/PWA. It is a Ionic Capacitor Plugin. '
    s.license = 'MIT'
    s.homepage = 'https://github.com/MeshMyCampus/capacitor-firebase-auth-plugin'
    s.author = 'Tsavo van den Berg Knott'
    s.source = { :git => 'https://github.com/MeshMyCampus/capacitor-firebase-auth-plugin', :tag => s.version.to_s }
    s.source_files = 'ios/Plugin/Plugin/**/*.{swift,h,m,c,cc,mm,cpp}'
    s.ios.deployment_target  = '10.0'
    s.dependency 'Capacitor'
  end`

=========================== Terminal output ==============================

`MacBook-Pro-5:Mesh-PWA-Alpha ourquad$ npx cap sync
✔ Copying web assets from esm-bundled to ios/App/public in 38.77ms
✔ Copying native bridge in 846.54μp
✔ Copying capacitor.config.json in 929.06μp
✔ copy in 50.46ms
✔ Updating iOS plugins in 3.44ms
  Found 1 Capacitor plugin for ios:
    MeshIntelligenceCapacitorFirebaseAuthPlugin (0.0.11)
✖ Updating iOS native dependencies:
✖ update ios:
[error] Analyzing dependencies
Fetching podspec for `Capacitor` from `../../node_modules/@capacitor/ios`
Fetching podspec for `CapacitorCordova` from `../../node_modules/@capacitor/ios`
Fetching podspec for `MeshIntelligenceCapacitorFirebaseAuthPlugin` from `/Users/ourquad/Mesh-PWA-Alpha/node_modules/@mesh-intelligence/capacitor-firebase-auth-plugin`
[!] No podspec found for `MeshIntelligenceCapacitorFirebaseAuthPlugin` in `/Users/ourquad/Mesh-PWA-Alpha/node_modules/@mesh-intelligence/capacitor-firebase-auth-plugin`
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/ourquad/Mesh-PWA-Alpha/node_modules/.bin in PATH, mode`

===================== Alternative Solution ====================================

For now, what I have done is  gone into the capacitor ios/App/Podfile and manually changed it to the correct pod name. 

`platform :ios, '10.0'
use_frameworks!

target 'App' do
  // # Add your Pods here

  // # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAuthPlugin', :path => '/Users/ourquad/Mesh-PWA-Alpha/node_modules/@mesh-intelligence/capacitor-firebase-auth-plugin'
  # Do not delete
end`

** The issue is that if I run npx cap sync then it will reset the Podspec file to the following ** 

`platform :ios, '10.0'
use_frameworks!

target 'App' do
  // # Add your Pods here
 
  // # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'MeshIntelligenceCapacitorFirebaseAuthPlugin', :path => '/Users/ourquad/Mesh-PWA-Alpha/node_modules/@mesh-intelligence/capacitor-firebase-auth-plugin'
  # Do not delete
end`

Any thoughts as to why this may be happening? 

All the best, 
-Tsavo

**Comment by jcesarmobile** [comment]
Can you publish the plugin or share a public plugin with this problem?

The workaround is to change the name in your .podspec to `MeshIntelligenceCapacitorFirebaseAuthPlugin` so it matches the one Capacitor CLI generates, but probably Capacitor CLI shouldn't add the `MeshIntelligence` part, so if you can provide a sample plugin it would be helpful to fix the problem.

**Comment by T-Knott-Mesh** [comment]
@jcesarmobile Hello :) Thank you for the reply, try out my plugin @mesh-intelligence/capacitor-firebase-auth-plugin, I have just made it public. It is practically nothing but some message logging but I am just trying to figure out the workflow.  I would love to know if the pod file adds the prefix for yourself. It may be fixed in the beta 11 that was released last night!

**Comment by T-Knott-Mesh** [comment]
@jcesarmobile Any luck with this ?

**Comment by jcesarmobile** [comment]
We have been discussing about what to do, but nothing decided yet.

Your only option for now it's to rename your .podspec to `MeshIntelligenceCapacitorFirebaseAuthPlugin` and change the name inside it too.

**Comment by T-Knott-Mesh** [comment]
No problem, I am currently doing that :) If there is anything else I can do to help, just let me know!

**Comment by jcesarmobile** [comment]
There was a bug on plugin creation that didn't allow the name to contain the scope. I've fixed it in https://github.com/ionic-team/capacitor/pull/1319. So if the scope was added afterwards, it will make the podspec don't match as in your case.

Now if you create it like `@mesh-intelligence/capacitor firebase-auth-plugin`, both the .podspec and name inside it will be `MeshIntelligenceCapacitorFirebaseAuthPlugin` from the beginning. 

I'm not really sure if I should remove the scope when naming the .podspec file. The scope allows to have two different packages with the same name as long as they both have a different scope, but if the .podspec excludes the scope, then two plugins might have the same name and that will cause conflicts.

In example if I create `@jcesarmobile/capacitor firebase-auth-plugin` and exclude the scope it will be named `CapacitorFirebaseAuthPlugin.podspec`, and same thing for `@mesh-intelligence/capacitor firebase-auth-plugin`, while right now they will be called `JcesarmobileCapacitorFirebaseAuthPlugin.podspec` and `MeshIntelligenceCapacitorFirebaseAuthPlugin.podspec` respectively

**Comment by T-Knott-Mesh** [comment]
Ahhh interesting. I see. Well however you end up wishing to execute on this
I will make it work!

Thanks for getting back to me on this. You guys are killing is so keep up
the great progress, lots of awesome stuff being facilitated by Capacitor !

🍻

-Tsavo

**Comment by T-Knott-Mesh** [comment]
Oh and I would keep the scope :)

**Comment by jcesarmobile** [comment]
Ok, going to close the issue as the generator allows scopes now and we agreed on keeping it on the podspec name. 
Thanks for the feedback!
