### ISSUE TITLE
Location.Href leads to 404 on iOS

### ISSUE THREAD

**Issue by Nasicus** [ionic-team/capacitor#968]
In our app we normally use react-router, but in certain cases we have to use `location.href` to redirect.
On android this works fine. However on iOS URL's other than `/` result in `404` pages!

This will work:

```
location.href = `/`
```

This will not work and result in a `404`:

```
location.href = `/login`
```

Note that `/login` is a route which is defined in our React App.

I guess the `Capacitor` web server is not configured to handle `wildcards` / HTML 5 routes or however this is called.

Is there any way to fix this? Is this even capacitor's fault?

Edit:

I saw that on `android` there is a `html 5 mode`, which is enabled by default. However for iOS I didn't find anything similar:
https://github.com/ionic-team/capacitor/blob/68af143c3ccb0dc5bd37f01973c3cdaa57d42307/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L176

**Comment by jcesarmobile** [comment]
Should be fixed on beta 11 that we released yesterday. 
I don't know much about React, so I can't test, can you test it and verify?

**Comment by Nasicus** [comment]
Will do so tomorrow

**Comment by Nasicus** [comment]
Tested & verified.

Thanks!
