### ISSUE TITLE
Beacon API cannot load : Sentry with capacitor + ionic 4 + vue not working

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#969]
Using sentry ("@sentry/browser": "4.2.4") with Ionic 4 and Capacitor and VUE.

In console, I am getting
[Error] **Beacon API cannot load** https://sentry.io/api/18**55/store/?sentry_key=34**********************27abc&sentry_version=7. **Failed HTTP authentication**

[Error] **Beacon API cannot load h**ttps://sentry.io/api/18**55/store/?sentry_key=34**********************abc&sentry_version=7. **Failed HTTP authentication**
[Error] Failed to load resource: Failed HTTP authentication (store, line 0)

**Comment by jcesarmobile** [comment]
Sorry, I have no idea about what @sentry/browser does or how it works.
If you figure out what's wrong and tell us why it's Capacitor's fault reopen the issue with that information, and if possible with a sample project or enough steps to reproduce.
