### ISSUE TITLE
Android: Deeplinks -  App opens twice sometimes

### ISSUE THREAD

**Issue by Nasicus** [ionic-team/capacitor#971]
I'm not sure if this is capacitors fault, but I had quite the trouble with this.

Basically what happens is this:

If you have the app already open and click on a deep link in another app which supports inline-browsers (like Gmail) the app will be opened a second time.
You can see this when you look at your recent app list.
That in itself might not even be that bad. However for us our plugins respectively the callbacks of the plugins don't work correctly anymore.  Both app instances will just have a blank screen and be unusable. You have to close them again. But even then: The deeplink will never work correctly.

The solution for this is quite simple:

You have to set the `launchMode` on the `MainActivity` to `singleTask`.

```
android:launchMode="singleTask"
```

See this [stack ](https://stackoverflow.com/a/25997627/1712056) answer.

It may be a good idea to at least update the "sample app" (which you can create by using capacitor) to include this `launchMode`. 

As I said: I'm not sure if there is anything really wrong in capacitor or if this is the expected behavior.

**Comment by jcesarmobile** [comment]
Closing as this PR https://github.com/ionic-team/capacitor/pull/1477 set the template launchMode to singleTask

**Comment by KovshefulCoder** [comment]
Thanks, helped even with Jetpack Compose and Navigaton (navigation:navigation-compose)
