### ISSUE TITLE
Is there any way to know if app is running over xcode/Testfligth or AppStore production

### ISSUE THREAD

**Issue by stripathix** [ionic-team/capacitor#976]
In Cordova I was using below plugin to detect if the app is running on TF or AppStore to decide on the environment.
https://github.com/Arcticus/Cordova-Plugin---Test-Flight-Detector

Is there any way to detect the app environment in the capacitor?

**Comment by stripathix** [comment]
Ahh thanks a lot. I did not know that we can use almost all existing Cordova plugin with a capacitor. This plugin works well with a capacitor.

Will using cordova plugin cause any performance issue with capacitor? Looks good to me.

**Comment by jcesarmobile** [comment]
Not every plugin works, but sometimes we can fix it and increate the compatibility. Other times just add the plugin to a "black list" when it causes the build to fail.

It shouldn't cause any performance issue.
