### ISSUE TITLE
Libraries which depends on `localStorage`

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#981]
Beta.11 basically drops `localStorage` support

> localStorage will be lost as the url changes. We always recommend using the Storage API to avoid this issue.

I wonder what to do with 3rd-party libraries, which are relying on the `localStorage` and you can't change that? For instance, `aws-amplify`.

**Comment by jcesarmobile** [comment]
Yeah, it's how @ptitjes says, it's lost from beta 8 to beta 11, because it doesn't use the localhost url anymore, nor http scheme, and the url changes because of that. But once you have beta 11 the url doesn't change and you can use localStorage just fine. It doesn't affect new apps neither, it's just for apps migrating from beta 8 to beta 11

**Comment by mlynch** [comment]
Many apps that update require you to log back in, so unfortunately this isn't ideal but I think that's what people will need to do here if they stored some auth credentials in localstorage.

**Comment by stripathix** [comment]
I am using AWS Cognito for authentication. AWS Cognito uses localstorage to save all its credentials. And my live app is running using Cordova. I am migrating to Capacitor and Ionic 4. This means all users will have to log back in?

This is so sad. Is there any workaround for that?

**Comment by stripathix** [comment]
@jcesarmobile  it will also affect app migrating from Cordova to capacitor :-( .

Basically, all ionic(1, 2, 3) app(using local storage) that are in app-store right now. If they will upgrade to the capacitor.

**Comment by mlynch** [comment]
A workaround would be to push an update right now that stores anything in local storage using the Storage API we provide instead, and then sync it back when you move to the new version. There is some storage API in WKWebView but I’m unclear if it can be used to migrate data over. Anyone know? https://developer.apple.com/documentation/webkit/wkwebsitedatastore

**Comment by T-Knott-Mesh** [comment]
@mlynch, @jcesarmobile It seems that on a full application close and re-open, at least on iOS your storage API is not persisting data. I can't find anyone else with a similar issue but it works perfectly fine in browser. Only when emulated on iOS device/simulator does it clear storage on app restart. 

Any immediate thoughts? If not I can post an issue. 

All the best, 
-Tsavo
