### ISSUE TITLE
Cordova-plugin-file-opener-2 doesn't build on Android Studio

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/capacitor#982]
I'd npm installed cordova-plugin-file-opener2 but when trying to build on Android Studio it doesn't work. The error point me to the error you get in the .gradle of the cordova plugins when doing the CTRL+SHIFT+F command. After I uninstall it builds correctly.

OS: Linux Ubuntu 18.10
ionic: 4.3.1
capacitor: 1.0.0-beta.11

**Comment by jcesarmobile** [comment]
This is a problem on the plugin, it uses android support v4 with + instead of pining a version, so it's using 28.0.0 which causes those errors.

You can force 27.1.1 by adding this to your app build.gradle

```
configurations.all {
    resolutionStrategy {
        force "com.android.support:support-v4:27.1.1"
    }
}
```

**Comment by Bandito11** [comment]
@stewwan it didn't work when I tried it.
