### ISSUE TITLE
CDVURLProtocol.h not found after upgrading to 1.0.0-beta.11

### ISSUE THREAD

**Issue by gabrielmaldi** [ionic-team/capacitor#987]
I'm getting this error when I try to (clean and) build the Xcode project `ionic capacitor run ios` starts:

<img width="995" alt="screen shot 2018-11-20 at 2 26 09 pm" src="https://user-images.githubusercontent.com/3728897/48791547-ba6f2900-ecd0-11e8-984f-1e764ec26b20.png">

This is how I upgraded to Capacitor 1.0.0-beta.11:

<img width="390" alt="screen shot 2018-11-20 at 2 26 49 pm" src="https://user-images.githubusercontent.com/3728897/48791579-c8bd4500-ecd0-11e8-9111-a76b4c65b8f7.png">

I read the release notes and there seem to be no other changes to be performed for iOS (unlike for Android, which there are).

Thanks

**Comment by jcesarmobile** [comment]
What's your Xcode version?
How do you clean the project?

I've tested on Xcode 10.1. I did Product -> Clean Build Folder, ran again and everything worked.

**Comment by gabrielmaldi** [comment]
I'm using Xcode 10.1 (10B61) and cleaning the same way you are. I also deleted my DerivedData folder just in case.

Are you running a new project from scratch? Or upgrading to Capacitor beta.11 from a previous beta?

**Comment by jcesarmobile** [comment]
Xcode 10 is doing strange things with CocoaPods

Try this.
Close Xcode
run `npx cap update ios`
Open Xcode again `npx cap open ios`
Do the Product -> Clean build folder again
Run the app.

**Comment by jcesarmobile** [comment]
Going to close as there was no answer after my last comment and another user was having a similar issue and was fixed following this steps.
