### ISSUE TITLE
[BUG] Capacitor: Unable to open index.html

### ISSUE THREAD

**Issue by nicobytes** [ionic-team/capacitor#989]
Hello! I try build app with capacitor but not work, show me the same error with:

```
ionic cap sync android
```

![screen shot 2018-11-21 at 11 14 42 am](https://user-images.githubusercontent.com/7611944/48850326-cadddd00-ed7e-11e8-81e7-6de7049b98af.png)

![screen shot 2018-11-21 at 11 07 44 am](https://user-images.githubusercontent.com/7611944/48850336-d16c5480-ed7e-11e8-9b7d-af637830eb78.png)

![whatsapp image 2018-11-21 at 11 16 42 am](https://user-images.githubusercontent.com/7611944/48850435-0d071e80-ed7f-11e8-94b8-473eb55b07b2.jpeg)

index.html in www:
![screen shot 2018-11-21 at 11 58 45 am](https://user-images.githubusercontent.com/7611944/48852980-e2b85f80-ed84-11e8-9bcf-b732ea7bee4d.png)

index.html in public:
![screen shot 2018-11-21 at 12 02 34 pm](https://user-images.githubusercontent.com/7611944/48853221-670ae280-ed85-11e8-9b6e-c604566936df.png)

**Comment by mlynch** [comment]
What's your capacitor config look like? Looks like your Android device is trying to load `localhost` which doesn't work in an Android emulator

**Comment by mlynch** [comment]
Okay was told I'm wrong because this would be loading our fake localhost in the app. Not sure what is going on.

**Comment by mlynch** [comment]
Right as I click "reopen" the button changes to "close" @jcesarmobile 😂

**Comment by jcesarmobile** [comment]
That's really strange indeed, the file is there but still doesn't find it.
Can you provide a sample project?
Also, in which OS are you developing?

**Comment by nicobytes** [comment]
Hello! @jcesarmobile ! of course here the project: https://github.com/EscuelaIt/ionic4-capacitor

My setup is:

![screen shot 2018-11-21 at 12 33 50 pm](https://user-images.githubusercontent.com/7611944/48855101-ce2a9600-ed89-11e8-9120-a55ff76b4642.png)

**Comment by jcesarmobile** [comment]
can you commit the www and public folders?
So I have the exact same project as you do

**Comment by nicobytes** [comment]
@jcesarmobile of course! done https://github.com/EscuelaIt/ionic4-capacitor/tree/master/www

**Comment by jcesarmobile** [comment]
No idea of what's going on, I ran the app and it's working fine on my machine

![captura de pantalla 2018-11-21 a las 17 51 40](https://user-images.githubusercontent.com/1637892/48856306-5f176680-edb6-11e8-8085-808f4629e606.png)

**Comment by nicobytes** [comment]
I try in my emulator but the result is:

![screen shot 2018-11-21 at 7 24 24 pm](https://user-images.githubusercontent.com/7611944/48873353-c4be1f80-edc3-11e8-8b1a-59732f9ff964.png)
![screen shot 2018-11-21 at 7 28 01 pm](https://user-images.githubusercontent.com/7611944/48873356-c851a680-edc3-11e8-8e2b-d29d6d03279a.png)

**Comment by jcesarmobile** [comment]
that's a problem on ionic-pwa-elements, if you remove the script tag for it is should work.

**Comment by nicobytes** [comment]
OK work! but if I remove ionic-pwa-elements doesn't work for web, pwa and electron =(

![screen shot 2018-11-21 at 8 17 10 pm](https://user-images.githubusercontent.com/7611944/48874615-8c6e0f80-edca-11e8-9168-befea520edf6.png)

**Comment by jcesarmobile** [comment]
yeah, you'll have to wait for a new release or update the emulator's Chrome version to latest (as far as I know that is only possible if the emulator has google play, not all have it)

**Comment by nicobytes** [comment]
@jcesarmobile when I try in my device doesn't work.. 

![screen shot 2018-11-21 at 9 30 43 pm](https://user-images.githubusercontent.com/7611944/48876576-22a73300-edd5-11e8-9059-e22988cb017f.png)
![screen shot 2018-11-21 at 9 32 36 pm](https://user-images.githubusercontent.com/7611944/48876582-289d1400-edd5-11e8-98c9-106dbd10c9fa.png)
![screen shot 2018-11-21 at 9 32 46 pm](https://user-images.githubusercontent.com/7611944/48876584-2dfa5e80-edd5-11e8-916b-5c4d019e0747.png)

**Comment by jcesarmobile** [comment]
For some reason the public folder is not copied to your device, it’s hard to know why without having access to it. As it worked on your simulator and my device I don’t think it’s a problen on your project, but some configuration in your device

**Comment by jcesarmobile** [comment]
@nicobytes did you find what was going on?
