### ISSUE TITLE
pushwoosh-phonegap-plugin gives ld: library not found for -lPushwoosh

### ISSUE THREAD

**Issue by chintan13** [ionic-team/capacitor#990]
I have **npx cap sync** is working fine now but it still gives below error while trying to build for IOS
for Android its working fine

ld: library not found for -lPushwoosh
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jcesarmobile** [comment]
Latest version of the plugin is compatible with Capacitor

https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/pull/306
