### ISSUE TITLE
sync android produces invalid characters in gradle file on 1.0.0-beta.11 

### ISSUE THREAD

**Issue by bogdbo** [ionic-team/capacitor#992]
It seems after updating to beta.11 `sync android` produces mixed slashes in my gradle file.

This does not compile on Windows and the paths seem to be in the normal format returned by nodejs' `path.join`.

![image](https://user-images.githubusercontent.com/889997/48899280-d94bf780-ee57-11e8-98a9-b60dd3f1d731.png)

**Comment by bogdbo** [comment]
Yes, this is on Windows 10, and those are capacitor plugins but are not public and they are installed from disk and npm will create a system link. The path in the error-screenshot is to the original directory, I guess `path` is following system links. Manually undoing the change to how it was on beta.8 fixes it.

![image](https://user-images.githubusercontent.com/889997/48901654-cee12c00-ee5e-11e8-8931-53b88c4fa0b9.png)

**Comment by ptitjes** [comment]
Oups... I guess this is mine to fix!
