### ISSUE TITLE
Ionic capacitor {undefined is not a function}

### ISSUE THREAD

**Issue by salemdomain** [ionic-team/capacitor#995]
![screenshot_2018-11-23-11-41-43](https://user-images.githubusercontent.com/40359993/48934636-f21ae280-ef15-11e8-91f1-cb18376bf76e.png)

Please help my app is working just fine in the browser but when am launching the apk in real device its showing the following error { undefined is not a function } . Thanks

**Comment by salemdomain** [comment]
hi @jcesarmobile 

sorry information like what do you want me to provide?

**Comment by jcesarmobile** [comment]
That’s a JavaScript error, so probably the best is to provide a sample project that reproduces the problem

**Comment by salemdomain** [comment]
i think its capacitor problem and not javascript....because its working fine in the browser with no any error or warning. @jcesarmobile

**Comment by jcesarmobile** [comment]
Sorry, I can’t reproduce

**Comment by salemdomain** [comment]
@jcesarmobile

Its angular problem.
I tried to uncomment the following lines in polyfill.ts and the problem is gone but i lost the style { shadow dom } is not working.

import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
