### ISSUE TITLE
Custom plugin: CLI writes absolute path to iOS Podfile

### ISSUE THREAD

**Issue by moberwasserlechner** [ionic-team/capacitor#998]
Using a custom plugin like `npm i @byteowls/capacitor-oauth2 --save` and running one of these commands
```
npx cap sync ios
npx cap add ios
```

the Capacitor CLI writes a absolute path to `ios/App/Podfile`

```
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'ByteowlsCapacitorOauth2', :path => '/Users/moberwasserlechner/development/tc/my-app/node_modules/@byteowls/capacitor-oauth2'
  # Do not delete
```
The path should be relative because different developers have different development setups.

It might happen at https://github.com/ionic-team/capacitor/blob/37e05da31512c2b60e732a979c4d093cc742c233/cli/src/ios/update.ts#L91 but I'm not sure.

This occurs both on beta.8 and beta.11

BR, Michael

**Comment by moberwasserlechner** [comment]
On Android it works as expected
```
include ':byteowls-capacitor-oauth2'
project(':byteowls-capacitor-oauth2').projectDir = new File('../node_modules/@byteowls/capacitor-oauth2/android/@byteowls/capacitor-oauth2')
```

**Comment by jcesarmobile** [comment]
It’s rewritten every time you run update, so it’s not a real problem, if in a different machine just run update again. 

But is going to be changed to be relative so it works as on Android, will keep it open to use this as the reference issue when I send the PR (or somebody else)

**Comment by moberwasserlechner** [comment]
It's small but would be nice to have as the podfiles are versioned and every dev on a team would change it by runing the update. thx

**Comment by jcesarmobile** [comment]
Also, in latest release we moved Cordova plugin files outside of node_modules, so now you can commit them if you want, but if you don’t commit them (or if use an older cli version) you’ll have to run update anyway (if have any Cordova plugin)

**Comment by moberwasserlechner** [comment]
Ok good know but is there a way to let the CLI know that I'm not using Cordova. I see a punch of new files after upgrading a project to beta.11. 

On the other hand I guess the new files do not hurt and might be expected by the CLI.

**Comment by jcesarmobile** [comment]
There are just 2 new folders and they shouldn't contain much files.
But we could probably make the CLI delete them when there are no Cordova plugins
