### ISSUE TITLE
How to cache images in capacitor

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#999]
I am following this guide as I would like to get caching working with images in capacitor, however It doesnt seem to work with any of the approaches ive taken.

https://medium.com/ninjadevs/caching-images-ionic-ccf2f4ca8d1f

Is there a partiuclar way to set up caching images with capacitor?

**Comment by jcesarmobile** [comment]
Sorry, but I'm not going to read a long blog post and follow it step by step to try to figure out what is working and what is not.
You'll have to debug and when you know what is not working, report that individual issue so it can look into it.

**Comment by oliverandersencox** [comment]
Fair enough - I'm more curious to see of there was potentially had recommendations the capacitor guys have towards image caching
